== Preface by the Author.

Believing it required of me in my early life,
to keep a record of the merciful dealings of the Lord with me,
and the remarkable manner in which he, in his tender compassion,
has followed me by his reproofs of instruction, accompanied by such offers of help,
as when faithfully cooperated with,
never have failed to be all-sufficient for every work and
service He has been pleased to call me to perform,
I have been induced to continue the narrative, in hopes that, if it should be published,
the perusal of it would afford lessons of instruction and encouragement to such as may,
in adorable mercy,
be awakened to the necessity of searching into the things which pertain to salvation.

The reader will, I hope,
make every reasonable allowance for my relating some circumstances,
which may not be likely to excite general interest.
In the narration of what occurred in discourses and controversies,
great allowance must also be made;
the best of memories not being able to recollect every particular:
but the earliest care was taken, after such opportunity, to minute down what occurred;
and I believe I am safe in saying, that by seeking, at these times,
for help from the good Remembrancer, he graciously condescended to assist me.
Care has been taken in no way to alter the sense of what was communicated by others;
and where I had companions,
to whom I could conveniently submit my memorandums for perusal and correction,
if necessary, it has been done; and in revising these,
where any doubt has arisen as to the correctness of any part, it has been suppressed.

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Tottenham, 1834.
