== Chapter I.

Apprehending it will prove a relief to my own mind,
and may afford a ray of encouragement to some poor weary traveller like myself,
should these fragments be cast before the public,
I am most easy to attempt something by way of Journal,
to show forth the Lord`'s wonderful dealings,
his merciful interference and deliverance manifested towards me,
in times of sore trial and conflict, both inwardly and outwardly.

I was born in Holborn, London, about the second month, 1754.
My parents were members of the national church,
and zealously engaged to bring up their children in the
due observance of its religious rites and ceremonies,
and every moral duty.
In my infancy they left the place of my birth, and settled in Whitechapel,
until I had attained about the twelfth year of my age.
My father had, for many years,
filled the office of librarian to the society of Gray`'s Inn.
His situation calling for his daily attendance,
and feeling the infirmities of old age coming upon him,
it became necessary to change his place of residence,
which induced him to take the Three Tuns public house at Islington,
and move there with his family.

This change exposed me to great temptations, being naturally of a volatile disposition,
and early addicted to vanity.
Before, I had been kept close within doors,
seldom being allowed to go into the company of other children, except at school;
but now I was exposed to all sorts of company,
and allowed to ramble over the village unprotected, both by day and late of an evening,
carrying out beer to the customers, and gathering in the pots,
and waiting upon such company as came to the house.
First-days were generally the most busy days I had,
being scarcely ever able to get to a place of religious worship.
This, by long continued neglect, became a matter of the greatest indifference to me;
which had not been the case before my parents changed their abode.
I can now recur to the satisfaction I at times experienced,
in going with my parents to what is called church;
but my exposed situation in my father`'s house, open to almost every vice,
and the artifices of such evilly disposed persons as I had at times to do with,
had nearly effected my ruin.
My father being unacquainted with this business, and of an easy disposition,
by lending his property and other means, wasted what substance he had,
which obliged him to quit this line of life,
and retire to apartments provided for him and his family, in Gray`'s Inn,
and live on his salary.

I was now about sixteen years of age.
A person who frequented my father`'s house, and who had been an officer in the army,
having begun business in the grocery line in Wapping,
proposed to my parents to take me as an apprentice for five years, to which they agreed.
Here my situation was not improved, as respected good example;
for my master was given to much liquor and company;
and his wife from her manner of being brought up, was not a suitable mistress for me.
These things, together with the examples of wickedness exhibited in the neighbourhood,
rendered my new situation every way a dangerous one.
But though thus exposed, adorable Mercy met with me,
and awakened in my mind a degree of religious thoughtfulness.
I endeavoured to obtain an acquaintance with a young man in the neighbourhood,
towards whom I felt an attachment,
from an apprehension that his countenance bespoke him to be of a serious disposition.
His company proved helpful to my preservation,
from going greater lengths in folly and dissipation than I might otherwise have done;
and his example awakened in me again that liking which I
once had for attending a place of religious worship,
when I had the opportunity; but this did not often occur;
my master and mistress spending the first-day from home, in pleasure,
I was left to take care of the house.
My master`'s inclination for company and strong drink caused him to neglect his business;
and after I had been with him a little more than one year,
he was compelled to give it up, and move to Portsmouth,
where he opened a shop in the same line.
I felt regret at being obliged to leave my new acquaintance; and the more so,
as my exposure to temptation was not at all lessened by my change of residence.
A sense of the necessity of care how I formed new
acquaintance was in mercy awakened in me,
to which I endeavoured to give good heed.
In time a sober, religious young man, rather older than I was, attached himself to me;
and our intimacy was of mutual benefit,
continuing the remainder of the time I stayed in this part of the country.

The neighbourhood in which my master resided,
exposed me more to the danger of being drawn aside from the path of virtue,
than any other part of the town; this circumstance,
together with the little probability of my making
any improvement in a knowledge of my business,
induced me to write to my parents to procure my indentures, which being effected,
I returned to London, and obtained a situation in the same line of employ.
Although I did not mend my situation as respected the neighbourhood I settled in,
yet the change was abundantly for the better as respected my master, who was a sober,
religiously disposed man, and a great help to me.
He being a constant attender of the Foundling Hospital chapel,
I became his companion on first-day mornings,
and in the afternoon resorted to such places of worship
as were noted for popular preachers.

In this situation I remained about three years,
until I became acquainted with a young man, a distant relation,
descended from the Society of Friends.
I then forsook the Foundling Hospital chapel,
and other places of worship which I had frequented,
and kept solely to the meetings of Friends, on first-day mornings.
But my motive for this change was not a pure one;
my chief inducement being to meet my young relation, and go to dine with him;
his acquaintance causing me to neglect the attendance
of a place of worship the remaining part of the day,
which had been my uniform practice for the last three years.
My new companion also took me to the most fashionable
tea-gardens and other places of public resort,
where we spent the afternoon, and, at times, the evening;
this led the way to my giving greater latitude than ever to my natural inclination.
Still I continued to attend Friends`' meetings on first-day morning,
more than twelve months, but spent the remainder of the day in pleasure.
The retrospect did not produce those comfortable feelings which I had once known,
when this day of the week was differently occupied; and I was again, in unmerited mercy,
met with,
and my attention arrested to consider the misery into which the
road I had now chosen to travel would eventually lead me,
if I continued to pursue it.

Feeling a decided preference to the meetings of Friends, I continued my attendance;
experiencing an increased care to observe the time appointed,
and to be diligent also in the attendance of afternoon meetings.
The more faithfully I gave up to these impressions of duty,
the more my desires increased after an acquaintance with the Almighty,
and the knowledge of his ways.
Earnest were my prayers, that in this day of his powerful visitation,
in mercy renewed to my soul, he would not leave me,
nor allow me to become a prey to my soul`'s adversary;--that his hand would not spare,
nor his eye pity, until an entire willingness was brought about in me,
to cast myself down at his holy footstool.
As resignation was thus wrought in me,
to yield to the purifying operation of the Holy Spirit and fire,--that the fan of God`'s
word and power should effect the necessary separation between the precious and the vile,
corresponding fruits were brought forth in me, and manifested by my outward conduct.
I soon found that my old companion considered me no longer a fit one for him,
and our intimacy ceased.

Fresh trials now awaited me.
The knowledge of my attendance at Friends`' meetings reached the ears of my parents,
who manifested great displeasure.
My father took opportunities to persuade me to leave the meetings of Friends,
laying out the Society in as unfavourable and ridiculous
a point of view as he well knew how.
Finding his arguments made no impression on my mind,
he requested I would go with him the next first-day to the chapel of Gray`'s Inn,
and hear their chaplain.
It being his particular request, I consented, and attended; but my conflict was such,
during the whole of the time I was there,
that I was ready to conclude my countenance indicated the state of my mind,
and that all eyes were upon me.

From this time I never more attended.
But my difficulties did not end here as respected my parents,
whom I felt an increase of care not willfully to disoblige.
Wave after wave arose in my soul.
Using the plain language, and refusing to conform to the vain compliments of the world,
were brought close home to my mind, and laid me under great suffering;
not only on account of my becoming still more obnoxious to my parents,
but my employer not professing with Friends, if I gave up to those convictions of duty,
my conduct to his customers, would not be approved by him.
Thus the spirit was willing, but the flesh was weak;
for instead of seeking to that Almighty Power for help,
who I was fully persuaded laid the necessity upon me,
and firmly maintaining my ground by faithfulness, I sunk under discouragement, and,
to avoid the cross I should have to take up if I continued where I was,
left my situation, with a view of procuring one in a Friend`'s family.
No situation had offered for me, when the time proposed for my leaving arrived,
and I had nowhere to shelter my head but my father`'s house; who, with my mother,
was much opposed to me, on account of my persisting to attend the meetings of Friends.
After being some time out of employ, my father one day told me,
he would rather follow me to my grave, than I should have gone among the Quakers;
and he was determined I should quit his house that day week,
and turn out among those with whom I had joined myself in profession.

Having no place in prospect, and but little means to support myself,
this was a time of close proving.
But He who cares for the very sparrows,
notwithstanding I had brought myself into this strait,
partly through my shunning the cross, in his unmerited mercy looked down upon me.
I opened my situation to Margaret Bell, a member of Devonshire-house Monthly Meeting,
who afterwards became a nursing mother to me,
and by whose exertions a situation was procured for me to enter upon,
the day I was to leave my parents`' home.
This was at a banking-house in Lombard street,
where most of the clerks were in membership with Friends,
and where I entertained a hope of being more secure and out of the way of much temptation.
But, alas!
I soon found my mistake,
and that no situation was safe without the daily unremitting watch was maintained;
for it was evident that very few of my new companions,
were acquainted with that inward work I so much longed after an increase of;
many of them being as much given up to the world, and its delusive pleasures,
as other professors of the Christian name.

For lack of keeping steadily on the watch, I had nearly made shipwreck of faith.
But, oh! the mercy of that God who sought me,
snatched me again as a brand out of the burning, and opened mine ear to his counsel,
pointing out to me the need of increasing circumspection.
Although my new situation, among professors with the Society of Friends,
where I was not known, lessened my difficulty in using the plain language,
and not using vain compliments,
yet when I fell in the way of my relations and former acquaintance,
my difficulty continued great; and when unfaithful,
allowing the slavish fear of man to lord over me, I was sensible of inward weakness,
causing the hands to hang down and the knees to smite together,
in consequence of the withdrawing of the quickening
influence of the Spirit and power of Christ.

My mind was exercised with a belief, that if I continued faithful to Divine requiring,
a gift in the ministry would be committed to my charge.
Earnest were my secret cries, in meetings and out of meetings,
for Divine preservation in this awful work; to be kept from running before I was sent,
and of over-staying the right time when the command was clearly and distinctly heard,
"`Go forth.`"
About the twenty-fourth year of my age my mouth was first opened in a few words,
at a meeting then held every fifth-day evening, in the Park meetinghouse.
O! the peace I was favoured to feel, and which continued for some time;
but I found by experience, to my great sorrow,
that Satan can transform himself into an angel of light;
and when he cannot effect his evil purpose, by causing us to lag behind,
he will then try us, by endeavouring to hurry us on before our good Guide.
Some time after my first appearance in the evening meeting at the Park,
I ventured on my feet, and after I had expressed a few words,
I found myself embarrassed and took my seat.
Gladly would I have left the meeting, concluding all eyes were upon me;
but this I found I must not do, whatever my sufferings might be.
After the plungings I had to pass through, by night and by day, for this misstep,
my Divine Master, who knew the sincerity of my heart, had compassion upon me,
and was pleased to say, "`It is enough.`"
I did not venture to express anything in meetings for a great length of time;
and when I again apprehended it was required of me so to do,
the unguarded step I had before taken greatly increased my difficulty.

My mind became uncomfortable respecting part of the
business which it fell to my lot to transact,
having to purchase lottery tickets for country correspondents,
and other matters that I felt a scruple against, which again brought me under exercise,
lest I should be involved in fresh difficulties, not knowing what to turn my hand to,
in order to get a living in as respectable a way as that I was now in.
But as I became willing to seek and become subject to Divine direction,
in a matter of such importance as the changing of my present situation,
patiently waiting on this Divine Counsellor,
I clearly saw I must settle down to that manner of getting
my livelihood which Truth pointed out to me.
One first-day, when it was my turn to keep house,
my mind became deeply exercised with the subject of a change,
accompanied with earnest prayer that the Lord would be pleased to direct me.
In mercy he heard my cries, and answered my supplications,
pointing out to me the business I was to pursue, as intelligibly to the ear of my soul,
as ever words were expressed to my outward ear,--That
I must be willing to learn the trade of a shoemaker.
This unexpected intimation at first involved me in great distress of mind; first,
from my time of life to learn the trade,
and then the little probability of being soon able
to earn as much as would afford me necessaries;
as my salary was small, and I was obliged to make a respectable appearance,
I had not been able to save much money.
After giving the subject due consideration,
and calling to mind my frequent supplications to be rightly directed in this matter;
at a suitable time I acquainted my employers with
my apprehended duty in quitting their service.

Although this step afforded me relief, yet the prospect of making such a change,
and the remarks I should expose myself to, was humiliating.
I thought I might conclude the bitterness of death was gone by,
when I had informed my employers of my intention; but,
alas! how little do we know about the future.
My parents`' displeasure, which had a little subsided, was again awakened,
and threatened to be more violent than ever.
Notwithstanding my employers were silent, on my giving them the information,
yet the subject obtained their deliberation.
Friends, who I believe had my welfare at heart,
were diverse in their sentiments respecting my proposed change.

When the time was come for my employers setting me at liberty, they put me off;
and several Friends had conversation with me,
if possible to prevent my prosecuting the object now in view,
which I wished to consider rather as a mark of their kindness,
than from a desire to lead me into perplexity, which I believe would have been the case,
had I not been preserved near to my good Guide.
After being put off from time to time by my employers,
and continuing to hear the various sentiments of Friends on the occasion,
my dear and valued friend and mother in Christ, Margaret Bell,
expressed herself in a way that gave a spur to my diligence in procuring my liberty.
"`The diversity of sentiments abroad, among Friends,`" said she,
"`on your intended change of employ, without great care,
seems to be likely to involve you in perplexity;
and therefore I am for leaving you to the great Master`'s guidance.`"

My employers finding that I was firm in my intention, liberated me;
and I entered into an agreement with a man in the borough,
to instruct me in the working part of shoemaking, with measuring and cutting out;
for which I was to give him more than half of my small savings.
Yet I trusted that if I kept close to my good Guide in my future stoppings,
he would so direct me,
that time would evince to my friends I had not been deceived in the step I had taken.
The billows, at times, would rise very high one after another; yet,
to my humbling admiration, I had to acknowledge, to the praise of that Power,
which I believed had led me into this tribulated path, that they all passed over me.
My little surplus of money wasted fast, and my earnings were very small, not allowing me,
for the first twelve months, more than bread, cheese and water, and sometimes bread only,
to keep clear of debt, which I carefully avoided.
On first days I was frequently invited to a Friend`'s house,
where I got such a meal as I had formerly been accustomed to.
Sitting constantly on the seat at work was hard for me, so that I might say,
I worked hard and fared hard.
My friends manifested a fear my health would suffer;
but I soon became reconciled to the change in my diet, as did also my constitution.
My countenance, some of my friends would tell me, reminded them of the vegetables in
Daniel chpter 1.

After I had been under the care of my instructor about eighteen months,
his health so declined that he was frequently unequal to pay much attention to me;
but I had by this time made considerable proficiency in my new calling.
In awhile it appeared better for me to free myself from my instructor,
and begin as a master for myself,
having offers of plenty of employment from such who could make
allowances for one who had only newly entered into such an engagement.
I therefore took lodgings in the city,
beginning business with my small capital of the few shillings I had yet left,
always getting pay for my work as I carried it home.
In time, and by dint of application, under the Lord`'s helping hand,
who I believe pointed out for me the path I was treading,
I became equal to manage a business of more extent.

After I had been settled in my new situation a few months,
my prospects began to be very discouraging.
From the declining state of my health,
I was unable to give my business the attention it called for.
My debility so increased, that the doctors recommended my leaving London altogether;
the thoughts of doing which, and having new connections to seek,
was a fresh trial of my faith; but as my health continued to get worse,
I concluded I had no alternative; I therefore turned my attention to Tottenham,
where there was a large body of Friends.
I left London accordingly.

After a few months my health improved, and my prospects began to brighten;
but above all other favours, I esteemed the evidence I was favoured with,
that this was my right place of settlement.
Thus does our almighty Care-taker,
as we are willing to become subject to his control and government, lead us about,
and in various ways instruct us, by sickness and by health, crosses and disappointments,
that we of ourselves are poor, feeble, fallible mortals,
wholly at the disposal of his turning and overturning hand.
When I became able to give proper attention to my business,
I found my London connections were desirous to employ me,
and the two Friends`' schools at Tottenham were also kindly disposed towards me;
which threw so much business into my hands that I
was soon under the necessity of employing two journeymen;
and I was favoured to give so much satisfaction to my employers,
that they promoted my interest.

Believing it would be to my advantage every way to change my condition in life,
I besought the Lord to guide me by his counsel in taking this momentous step;
and I thought I had good ground to believe he was pleased to grant my request,
and point out to me one who was to be my companion for life, Mary Pace,
a virtuous woman of honest parents, to whom I made proposals of marriage;
and in the seventh month, 1778, we were united in that solemn covenant.

About the year 1790, an apprehension took hold of my mind,
that it was required of me to be willing to leave my family and outward concerns,
to engage in the Lord`'s work; which, if I gave up to and was liberated by my friends,
would be likely to take me a considerable time from home.
This was a fresh trial of my faith in the all-sufficiency of that Power, who,
when he calls forth, can not only qualify for the work,
but amply care for those left behind.
My wife`'s time was fully occupied in attending to her little family,
as we kept no servant, and she was also unacquainted with the management of business.
I had none I could leave in the charge of mine but
a man who had acted as an assistant to me,
and had forfeited his membership on account of unsteady conduct,
so that it would seem very little dependence was to be placed upon him.

I found the enemy began to be very busy, endeavouring to take advantage of me,
and to sap the foundation of my confidence in the never-failing arm of Divine Power.
When the concern was afresh brought before the view of my mind,
and I endeavoured after a willingness, Satan was also present with me,
to magnify my difficulties,
by laying before me the lack of qualification in this man to manage my concerns,
and that should he neglect to make my shop properly secure at night,
robbers would have easy access to my property,
the loss of which might involve me in great difficulty the remainder of my days.
Nor was it likely this man would have much authority over the rest of my journeymen,
for by this time I had several men in my employ, who, when I was at home,
would at times neglect their work,
and it seemed to me they would be more likely to do so in my absence.

My wife and children also claimed all the attention I could spare from my business:
and when the concern was brought into view,
and my mind exercised that if it was a Divine requiring,
I might be strengthened faithfully to give up to it,
then these discouragements came in like a flood,
so that my plungings were almost more than I was able to bear.
I was one day tempted to come to the conclusion,
that let the consequences be what they might,
I must give up all prospects of ever moving in this engagement;
but He who knew the sincerity of my heart, did not leave me in this season of extremity,
to become a prey to the adversary of souls,
but in his unmerited mercy had compassion on me.
One day, when I was standing cutting out work for my men,
my mind being under the weight of the concern,
these discouragements again presented themselves, if possible, with double force;
but in adorable mercy, I was so brought under the calming influence of Divine help,
as I had not often, if ever before, known.
And as I became willing to yield to it,
the power of the mighty God of Jacob was mercifully manifest,
subduing the influence and power of the adversary;
holding out for my acceptance this encouraging promise,
which was addressed to my inward hearing,
in a language as intelligible as ever I heard words spoken to my outward ear,--"`I will
be more than bolts and bars to your outward habitation--more than a master to your servants,
for I can restrain their wandering minds--more than a husband to your wife,
and a parent to your infant children.`"

At this, the knife I was using fell out of my hand; and I no longer dared to hesitate,
after such a confirmation.
I therefore resolved, if the concern continued with me,
and it should appear the right time, to lay it before the next Monthly Meeting.
In the twelfth month, 1790, I laid the concern before my friends,
to visit the Monthly Meetings of Norfolk, and families of Friends in the city of Norwich,
which appeared to obtain the solid deliberation of the meeting;
and at the next Monthly Meeting a certificate was ordered to be prepared for me.

I believed it to be my duty to exert myself in arranging and settling my outward concerns,
under an assurance, that if I did my part herein faithfully,
nothing would be lacking on the part of my Divine Care-taker.
I left home on seventh-day, the second of third month, 1791;
my kind friends William Forster and Wilson Birkbeck accompanying me as far as Stansted,
in Essex.
I lodged this night at the house of William Grover,
and on first-day morning attended meeting here.
My heart was brought under exercise on account of some, who, if my feelings were correct,
were satisfying themselves with mourning over their weakness,
instead of rightly seeking for help to overcome those
things which caused the hands to hang down.
After dinner I rode to the house of James Wright,
and found his family with a few others sitting in silence;
this proved a time in which a little strength was handed to my needy soul.
Second-day morning reached Wells in time for their Monthly Meeting:
that for worship as well as that for discipline were to me seasons of deep inward exercise.
I trust I am safe in saying, I endeavoured to labour honestly with the members.

Fourth-day attended Monthly Meeting at Lynn, which was small.
Some of our little company appeared to be bound to the testimonies we have to bear,
and Gospel order was in a good degree maintained.
Proceeded to Norwich,
and was at the evening meeting where I was favoured to have
a morsel of that bread which alone can nourish the soul,
and support it under its exercises, for Zion`'s sake;
for which favour I hope I felt truly thankful.
First-day attended meeting at Yarmouth, and on second-day their select meeting;
after which the Monthly Meeting was held, which was large,
and the business conducted in a good degree of brotherly condescension.

Third-day we returned to Norwich, and on fourth-day attended Monthly Meeting,
where I informed Friends of my apprehension of duty to visit the
families of both members and attenders of meeting in the city,
and a committee was appointed to assist, as occasion might require.
In this service I was engaged about six weeks, and had about sixty-six sittings;
during which, such were my hidden conflicts,
that I was at times nearly ready to desert the field of labour;
but being preserved in patience, willing to do or suffer all the Lord`'s will,
the retrospect afforded peace,
and proved a fresh incitement to persevere in the path of duty,
until the portion of labour allotted in this part of the vineyard was fully accomplished.

I next proceeded to Wymondham Monthly Meeting, the business of which,
according to the view given me, was conducted in a dry, formal way.
I think I never found it more trying to obtain relief to my own mind than at this time.
Here ended my service in this Quarterly Meeting; and now,
feeling my way clear to return home, I proceeded to Kelvedon.

In the course of conversation in the evening,
mention was made of a general meeting to be held at Colne on first-day,
which fastened on my mind, and brought me again into bonds;
but such was my desire to reach home as speedily as well could be,
that I strove to get from under the weight of it.
Next morning we set off; but the further we proceeded,
the more my suffering of mind increased.
Thus the mercy of the Most High follows us; notwithstanding we rebel,
still he gives us proof that he wills not the death of him that dies.

I could no longer conceal my situation from my companion, wherefore we parted;
he proceeding towards London, and I returning to Kelvedon.
When my will had thus far become subject,
my detention from my home and family was made easy to me.
First-day morning I was at Kelvedon meeting;
and in the afternoon the general meeting at Colne, which was largely attended; and,
I trust, an edifying meeting to many,
and my mind was comforted under a hope of being in my right place.

On second-day I was favoured to reach my own home in the evening,
where I found my family well,
and my outward concerns in as good order as if I had taken
the management of them the whole of the time.
After such demonstrations of the superintending care of the Most High,
what must be the sad consequences of unfaithfulness to Divine requirings,
should it in a future day mark my footsteps.

At the Yearly Meeting this year,
a committee was appointed to visit some members of our religious Society at Dunkirk,
in France, who had emigrated from Nantucket and New Bedford, in North America.
While the appointment was in progress, my mind was impressed with an apprehension,
that it would be right for me to offer myself as one of the committee;
but I allowed the appointment to close without doing so.
The committee was left so far under the care of the Meeting for Sufferings,
as to have the power to add to it, any Friend who might feel a concern,
with the consent of his own Monthly Meeting, to join it.
The subject continuing to press with increasing weight on my mind,
I informed my Monthly Meeting; which furnished me with a minute of its concurrence,
and this being presented to the Meeting for Sufferings,
that meeting set me at liberty to join the committee, in the eighth month, 1792.
The committee met at Dover,
and being joined by a committee appointed by the Quarterly Meeting of Kent,
engaged the packet for Calais.

On sixth-day morning, the wind being favourable, we set sail; but after about two hours,
a calm took place,
in consequence of which we did not reach Calais harbour before the gates were shut,
and no admittance could be obtained until the next morning.
Having cast anchor,
the keepers of the houses of entertainment outside the walls came on board our packet,
and pressed us much to go ashore, against which we were strongly advised,
and therefore concluded to get what sleep we could on board.

The next morning a boat was engaged for us,
on board of which we went about nine o`'clock, and reached Dunkirk in the evening,
and were kindly received by Friends there.
First-day, a few of the town`'s people gave us their company,
both in the morning and afternoon meeting, and behaved quietly.
Second-day morning the joint-committee sat down together,
and concluded it would be proper to visit the families, which accordingly took place.
After which they held a conference with some Friends of Dunkirk;
and as it did not appear, either to the Friends of the place, or the joint committee,
that those Friends could, with benefit to themselves,
be joined to any Quarterly or Monthly Meeting in England,
a report was drawn up accordingly, to be laid before our next Yearly Meeting,
and signed by the whole of the committee.

Fourth-day we left Dunkirk; and after violent jolting, and tossing from side to side,
as if we should be thrown over, we were favoured to reach Calais safe this evening.
Fifth-day morning, about nine o`'clock, we sailed for Dover,
and about one in the afternoon I was favoured to set my foot on English ground.
On sixth-day reached my own home;
where on my arrival I found fresh cause to acknowledge that my Divine Master
had not been lacking in his watchful care over all I had left behind.

1793+++.+++ 19th of ninth month.
Being one of a committee appointed by the Yearly Meeting,
to visit the Quarterly and Monthly Meetings in Lincolnshire,
I left my own home and reached Gedney.
Here I met with Joseph Storrs of Chesterfield, John Bateman of Chatteris,
Rudd Wheeler of Hitchin, and James Wright of Haverhill,
of the Yearly Meeting`'s committee.
We rode to Spalding and attended meeting there on first-day morning,
and if my view of its state was correct, the life of religion was at a low ebb.
The Monthly Meeting was held on second-day, out of its usual course,
to accommodate the committee.
From the low state of this meeting we were introduced into considerable exercise;
desirous, if possible, to be instrumental in strengthening the few,
who appear truly alive to the promotion of the Lord`'s cause.
We next proceeded to Wainfleet, and sat with Friends in their Monthly Meeting.
Many of the town`'s people came into the meeting for worship,
some of whose countenances and behaviour manifested religiously-disposed minds.
It proved a solid, satisfactory meeting; and some of us had no doubt,
if the members of our Society in this place, kept their habitation in the truth,
there would be a gathering again;
the scattering that had taken place being sorrowfully apparent,
and I trust the labour bestowed this day will not be lost,
but that fruits may appear after many days.

On sixth-day attended the select Monthly Meeting at Gainsborough, which was small;
and at the close the Monthly Meeting was held.
From the answers to the queries,
it appeared an increase of faithfulness in the execution of the discipline was lacking.
First-day, accompanied by James Wright, I attended Waddington meeting.
On our way there, we passed a considerable company of men,
who were standing about the market-cross, towards whom I felt a great flow of love.
We met with but a small company at the meetinghouse,
yet we were well satisfied our lot had been cast among them.
Towards the close of the meeting,
the company we left at the market-cross came again before the view of my mind,
accompanied by a revival of the feeling awakened in me as we passed them,
and attended with a belief,
that on our return we should find a number of persons collected there;
and if I stood truly resigned to do the Lord`'s will,
he had a service for me to perform among them, the prospect of which, for a time,
was more than I felt well able to bear.
On our way to the Friend`'s house we were to dine at, we had to pass the marketcross,
and found great numbers of men collected about it as before;
at the sight of whom my heart seemed to leap, through the fear that came over me.
I passed them, and proceeded, until my uneasiness,
from a sense of resisting the pointings of duty, became such,
that I opened my situation to my companion, who, pausing,
expressed his willingness to return with me.
On our way back, we came to a company of men who were standing at a lane end;
and believing it would be best for me so to do, I requested such of them as were willing,
to follow us to the market-cross, which all appeared readily to comply with.
After a pause I ascended one of the steps of the cross,
on which the people came from the doors of their houses,
and we soon had a very large gathering.
Some of the company, at first appeared disposed to be light and airy,
but in a short time seriousness generally prevailed; and at our parting,
many expressed their thankfulness for the opportunity,
and were in waiting about the Friend`'s house where we dined,
to take leave of us at our departure.

Second-day attended Broughton Monthly Meeting,
which is considered to be the largest in this Quarterly Meeting; after which,
we attended the Quarterly Meeting held at Lincoln,
from which place I returned to my own home, and was favoured to find my family well,
and outward concerns in good order.

In the twelfth month this year,
my Monthly Meeting granted me a certificate to visit the families
of members and attenders of Wandsworth Monthly Meeting;
soon after which, accompanied by my kind friend William Forster,
I left my family and outward concerns,
having endeavoured to do my best in a faithful arrangement of them,
which I have always found to be a great stay to my mind when absent from them.
Attended the Monthly Meeting at Wandsworth, and spread my concern before Friends,
which obtained their deliberation,
and a committee was appointed to assist me in my proceedings.
It appeared that a visit of this kind had not been
performed in this meeting for at least twenty years.

From this circumstance,
and the unfriendly appearance of many of the members and attenders,
discouragement took hold of my mind; yet a renewed persuasion was awakened in me,
that there is a Power above every power, who can open, and none can shut,
and can make way for us in the minds of others, when, viewing the path we have to tread,
with the eye of our finite comprehension, no way appears.
This, in adorable mercy, proved to be the case;
for apprehensions had been expressed by some Friends,
that many would refuse a visit of this nature;
whereas such refusal occurred in one instance only, and openness was generally manifest.
By endeavouring, as I humbly hope,
to be found faithful in delivering what appeared to be the counsel of my Divine Master,
although at times I had close things to say;
yet abiding under the influence of that love "`which thinks no evil,`" but "`rejoices
in the truth,`" from the affectionate manner those I visited took their leave,
I was encouraged to cherish a hope, that neither hurting nor destroying had taken place;
but that an open door was left for such as might have to tread the same ground after me.
Having accomplished this visit, and attended the Quarterly Meeting for Surrey,
held at Kingston, I returned home again,
where I was favoured with the usual salutation of all was well.
