== Chapter II.

In the early part of the year 1793,
a concern spread with considerable weight over my mind,
to pay a religious visit to the king; the importance of which,
and the seeming improbability of my obtaining such an interview as would relieve my mind,
plunged me into great discouragement.
After enduring much conflict, and trying to put the concern away from me,
my endeavours were fruitless; for the more I endeavoured to get from under it,
the more the burden increased.
I concluded, to try if writing to the king would be accepted by my Divine Master,
and sat down several times for the purpose;
but every attempt to obtain relief in this way proved in vain.

After I had, for a length of time, trifled with this concern,
showing myself willing to do the Lord`'s work, but in my own way, it was taken from me;
and I found myself left in a state of anguish,
such as I do not remember to have experienced before.
But, in the midst of judgment, mercy was vouchsafed,
my mind being permitted to experience the calming influence of Divine regard again;
accompanied with a hope, that if the concern sprung from a right source,
and I stood fully resigned to do the Lord`'s work, I should be tried again.

As I endeavoured patiently to abide in this resigned state of mind,
early in the year 1794,
my Divine Master was pleased to visit me by the renewal of this concern;
putting my faith and faithfulness afresh to the test: but it did not come alone,
for my former discouragements came before my mind, as lively and strong as heretofore.
I was given to see, that my safety was in abiding in the quiet,
and keeping my concern within my own bosom, until I was able, with certainty,
to see to whom I was to open my mind;
it appearing to me of importance that this first step should be rightly taken.
After patiently waiting upon the Lord, earnestly desiring him to direct me,
Joseph Gurney Bevan presented with clearness, and I concluded,
if the matter remained with me when next I went to London, to unbosom myself to him.
I went to London week after week, but had not strength to search him up,
rather endeavouring to shun him,
though at the same time I had a great dread of the consequences if I again rebelled.
Earnest were my secret petitions to the Lord,
that I might be strengthened to yield unreserved obedience to his requirings,
beseeching him to strip me in every way he should see fit,
until his purposes respecting me were effected.
As to my outward affairs, my mind was so borne down with this prospect,
that I know not how I got through them,
often feeling myself in that situation in which I thought I could say,
"`I go spoiled all the day long, he that hates me,
seeking my life to take it away,--when will the day be gone and the night come;
when my bed shall comfort me and my couch ease my complaint; then, lo!
I am terrified with visions, I am scared with dreams.`"

My bodily health began to suffer, the cause whereof was as yet only known to myself,
and to that merciful long-suffering God who kept me from sinking
below hope of yet having to praise him on the banks of deliverance.

Going to London on my usual business,
and calling at the house of my brother-in-law to inquire after the health of my sister,
respecting whom we had received, the preceding day, a very favourable account,
the servant replied, "`My mistress is dead.`"
My mind was led to consider my daily request, that I might be stripped,
until a willingness was brought about in me,
unreservedly to resign myself to the Divine disposal.
And how very near this awful stroke was brought! a sister dear to me,
next to my own dear wife!
This sudden and unexpected event roused me; I proceeded to the house of a Friend,
where unexpectedly I met with Joseph Gurney Bevan,
and retiring with him into another room, informed him how matters were with me,
which afforded relief to my mind; his willingness to sympathize with me, was encouraging,
saying that he believed way would open for me to cast off my burden,
or I should be relieved from it.

The concern continuing with me, I took a further opportunity with him,
and he proposed our meeting George Stacey, which taking place,
and the subject appearing of importance, it was concluded to call in further aid;
and it was agreed to meet at the close of the second-day morning meeting.
In this meeting my feelings were such as I cannot well describe,
under the testimony of Thomas Scattergood,
who I was fully satisfied was a total stranger to the state of my mind;
by his uttering these words, "`Who are you, that are afraid of a man that must die,
or the son of man that must wither as the grass of the field?`"
bringing the matter with still more weight before my mind;
and yet a disposition was roused in me to put off to some one else what he had said.
At the close of the meeting we retired,
and after we had passed some time in solemn silence, Joseph Gurney Bevan,
opened the subject that had brought us together.
At our parting, it was concluded to meet again on sixth-day,
and it appearing right that steps should be taken to obtain a private interview,
efforts were made, but not being able to succeed,
I endeavoured to feel after the most likely way to effect my relief.
The only means, appeared to be my going to Windsor,
and attempting an opportunity with the king, on the terrace;
but from the throng of company present at such times, the prospect was discouraging.

On second-day morning, the 12th of fourth month, I came to town to proceed.
George Stacey was proposed for my companion, and we drove down to Windsor.
George having some knowledge of a person employed about the castle,
sent for him to ascertain if a private interview with the king could be obtained, but,
as heretofore, there appeared no probability of succeeding:
yet we had the assurance given us,
that if I would commit to writing what I wished to communicate,
it should be delivered to him.
This I found I must not attempt,
until I had made every effort to obtain a personal interview,
and therefore was obliged to decline his kind offer.
Before he left us, he said, he could see no opportunity so likely to meet my views,
as our being in the stable yard the next morning about eight o`'clock,
as the king was to mount his horse at that time to go a hunting;
we therefore concluded to be in readiness by that time.
George going to observe how things were, very soon returned, saying, now was the time,
for the king was come from the castle into the yard.
I had heard of people being brought into such a state of perturbation,
that they have felt as if they might be knocked down with a feather;
I thought I was brought into a feeling of this state of inability, both of body and mind,
but it felt to me as if it was now or never.
As I went from the inn to the yard,
I felt like a vessel emptied of everything of a religious nature to communicate to others.
The king coming to the door of the stable, my companion said,
"`This friend of mine has something to communicate
to the king;`" on which the king stepped up to me.
Silence was observed for a few minutes, during which my dwelling continued to be,
as it were, in the stripping room.
Strength being given me to break silence, and utter the words, "`Hear,
O king!`" all fear was taken away from me;
what was communicated was well received by the king, the tears trickling down his cheeks,
and he stood in a very solid manner,
until I had fully relieved my mind of all that came before me.

George Stacey acknowledged the king`'s kindness in giving us the opportunity,
and it was said,
he did not pursue his diversion of hunting that day but returned to the queen,
and informed her of what had passed.

Way having been thus made for me to obtain relief,
I was favoured to see that great care was necessary not
to make my visit a subject of familiar communication.
Friends manifesting a desire to receive the account of the proceedings.
By the injudicious remarks at times expressed in my hearing,
I was made humblingly sensible, I was in danger of being lifted up,
and forgetting that Arm that had wrought my deliverance.
Having passed over this Jordan, how shall I find language to set forth to the full,
your praise, O you Great Almighty Helper!
Let me pray you, for ability, faithfully to dedicate the remainder of my time,
my talents, temporal as well as spiritual, to your work and service,
and that it never may fail to be the language of
my soul,--Dispose of me and of them as you see fit.

In the ninth month this year,
I laid before the Monthly Meeting a concern to visit
the families of Friends belonging to Capel,
Croydon, Reigate, Guilford and Godalming meetings.
A certificate being granted me in the tenth month, I left my dear wife,
family and outward concerns;
and having pursued these prospects until the whole was accomplished,
and attended the Quarterly Meeting for Surrey,
I was favoured to reach my own home with the reward of peace.

1795+++.+++ Twelfth month 20th. I left my home,
and attended Aylesbury meeting on first-day morning;
where Friends are much reduced in number.
Second-day morning proceeded to Oxford Quarterly Meeting;
very few women attend when the Quarterly Meeting is held here,
and those few sit with the men while the business
of the men`'s Quarterly Meeting is transacted.
It appeared, this custom had long been a source of uneasiness to some Friends.
The subject came weightily before the meeting at this time,
and after it had obtained much solid deliberation,
it was concluded best to resume the women`'s Quarterly Meeting at this place,
which was a comfort to many minds,
from the testimonies that were borne in confirmation of this measure.
I was thankful I had been willing to attend this meeting,
believing many who were present will remember it as a day of Divine favour,
under a grateful sense of which we separated.
Fourth-day morning,
rode to Aylesbury to attend Buckingham Quarterly Meeting to be held here this day.

Next morning I set forward for home, expecting to reach it by night;
but I was unexpectedly detained at Amersham, it being their usual meeting day.
Friends here are very few in number;
and I was made thankful my progress had been thus arrested,
being comforted in sitting down with the little company.
I had no other expectation but that of reaching home by night;
but I felt such a stop in my mind against proceeding then, I dared not attempt it.
I saw no way for me,
but labouring after a willingness to be disposed
of as the wisdom of Truth would point out;
and after a while it appeared clear to my mind, I must be willing to go to Wycombe;
which I accordingly did.
I left Wycombe in the afternoon,
under a thankful sense that I had been in the way of my duty.
I reached home this night, a distance of thirty-six miles;
and was favoured to find my dear wife and family well, and my outward concerns,
as heretofore well cared for: to whom can the praise be due, but the Lord alone?
May I continue to be found desirous above all things to render it now and forever.

1802+++.+++ 20th of eighth month.
Having obtained a certificate from my Monthly Meeting,
I left home to visit Friends in Kent and some parts of Hampshire.
First-day attended Rochester meeting;
in which I laboured with some who had forsaken their first love,
whereby they had fallen short in attaining to that dignity in the church of Christ,
designed for them.
In the afternoon meeting, silence appeared to be my proper place;
at the close I opened my prospect to visit the families, which being united with,
I proceeded therein, and on third-day evening closed this service.

Fourth-day proceeded to Margate, and next day attended the usual meeting:
the state of our Society here appears very low; several, not professing with Friends,
came into the meeting, and my mind was favoured with a comfortable hope,
that although very exercising and discouraging in the beginning, it ended well.
At the close the members were requested to stop,
to whom I opened my prospect of a visit to the members and attenders of this meeting,
which was united with.
Feeling my mind brought under a concern to have a meeting with such as were visitors,
it being the bathing season,
I could not let Friends separate without informing them thereof;
at the same time requesting them to endeavour to come at the mind of Truth,
and not because I had produced a certificate of the unity of my friends at home,
keep back their sentiments, should they be opposed to my view of having such a meeting.
After considerable time spent in silence,
Friends set me at liberty,
and concluded the next day at eleven o`'clock would be the most suitable time.
The meeting was well attended, and it was thought ended to a good degree of satisfaction.

After having finished the visit to the families in this place, I proceeded to Canterbury,
where only parts of three families were in membership.
Not feeling it required of me to move in the line
of religious labour here as at other places,
I proceeded to Dover.

First-day attended meeting here,
and visited the families of members and attenders of their meeting,
which I was favoured to effect on third-day, and in the evening walked over to Folkstone;
and proposed proceeding in a visit to their families.
It appearing to be cordially united with, I entered upon the visit next morning;
and on fifth-day was favoured to close these religious engagements.
Ashford was the next meeting in course;
and on looking towards it in the best manner I was capable,
my way felt quite closed up with respect to a visit.
I therefore proceeded to London, which place I reached late in the evening.

Being now only five miles from my own home, I felt drawings towards it,
but feared making the attempt,
as my religious engagements were only in part finished, lest
my mind should become entangled,
and my religious prospects be clouded thereby.
Early next morning I left London for Ringwood, in Hampshire, attended meeting there;
and in the afternoon sat with the few Friends at Fording-bridge.
Two young men, not professing with Friends, came into the meeting:
I was constrained to address one of them in so pointed a manner,
he could not but understand it was intended for him; and I understood,
from that afternoon he continued his attendance of Friends`' meetings,
and has joined in membership with us.
I mention this circumstance to encourage others, who may be thus singularly led;
feeling it at the time a trial of my faith thus to expose myself.

Next morning I left the quiet abode of my kind friend James Neave,
proceeded to Salisbury, and visited the families of this meeting.
Here, if my feelings were right respecting the religious state of our Society,
the lamp of profession is almost extinguished,
through the bond of true discipleship being broken, love, religious love, not maintained,
from some worldly cause, and so they had become a house divided,
I felt deeply for a little remnant among them, who were going mourning on their way,
breathing in secret the language of "`Give not your glory to others,
nor your heritage to reproach.`"

I returned to Fording-bridge; attended their mid-week meeting,
and from there passed to Ringwood,
intending to take the next packet from Southampton to Guernsey.
On inquiry, I found the packet was to sail that afternoon;
the prospect of being detained until the next packet was to sail, felt trying to my mind,
and led me to examine how far I had been careful,
not to loiter or remain longer than was necessary
in any of the meetings where my lot had been cast,
in order, should such appear to be the case,
that it might prove a warning to me in future.
Attended several meetings and on fifth-day morning left Ringwood for Southampton.
About four o`'clock in the afternoon I went on board the packet,
where I had the company of Edmund Richards, a Friend who resided at Guernsey:
after being on our passage two nights and one day,
we were favoured to land safe on the island of Guernsey,
about ten o`'clock on seventh-day morning.

First-day attended the meeting which was small; about eight are in membership,
and some few others attend.
In endeavouring to relieve my mind in the meeting, I had to give it as my belief,
there was a people in the island who were seeking after the Truth, but who,
on looking towards our religious Society,
had been stumbled by the disorderly walking of some who were going under our name.
After meeting a Friend told me,
he expected an individual in the meeting would conclude
I had been told some circumstances respecting him,
of which I could fully clear Friends.

The afternoon meeting was large, some of the town`'s people coming in;
and I hope it proved a profitable meeting to most of us.
At the close of the afternoon meeting,
I proposed a visit to the families of such as were
members and those who usually attended their meeting;
which being united with, I proceeded.
Fourth-day attended the usual meeting,
and in the afternoon I walked three miles out of town to visit a man and his aged mother;
the man was a frequenter of Friends`' meetings; the mother was eighty years of age,
had been blind twelve years,
but appeared a remarkable example of resignation to the deprivation she had experienced,
manifesting a precious tender frame of mind, reminding me of Simeon of old.
I felt much refreshed in being in her company.
After leaving this poor but comfortable abode,
we made a visit to two women who frequent Friends`' meeting:
on entering their poor cottage, the language to the apostles saluted the ear of my soul,
"`Peace be to this house;`" for I thought it might truly be said,
the Son of peace was there.
I do not know when I have more regretted my not being
master of the French language than on this occasion,
as neither of these two women understood English:
what I had to communicate was through my kind companion Nicholas Naftel.
This mode of communication,
however willing our interpreter may be to do justice
to the subjects he is entrusted with,
is a great hindrance to the enjoyment which might be experienced in such visits,
preventing that interchange of sentiment, which otherwise might take place.

Feeling clear of Guernsey, and drawings in my mind towards Jersey,
about ten o`'clock on fifth-day morning we engaged a passage in a small open boat,
and in about four hours, with difficulty, the surf being full of motion, we landed,
and walked two miles to a village, called St. Ones, to the house of Philip Hurle.
He has long been convinced of the principles of Friends,
and holds a meeting at his house, being joined by a few others who sit down in silence.
He received us gladly, saying, he felt low and tried of late, fearing,
as the summer was far advanced,
they should not have a visit from an English Friend this year.
Our arrival soon became noised abroad, and several seeking people made us a visit,
manifesting by their gestures the current of love that flowed towards us,
and which I thought I could say was mutually felt.
I found it rather a relief that I was not able to hold conversation with them,
they appearing so anxious to be informed on various subjects;
but we thought it safer to turn their attention inward to the great Master, Christ Jesus,
than to engage their attention by much argument.
Next morning we had a meeting with Philip Hurle and those who generally
meet with him for the purpose of religious worship:
this appeared to be a heart-tendering season.
After the meeting closed, Philip Hurle requested Nicholas Naftel to inform me,
I had spoken as clearly to the states of some in that meeting,
as if I had long been acquainted with them; and some of them, we understood,
charged him with giving me information respecting them.
In the afternoon we had a large public meeting.
When the meeting was over, the people expressed their desire we should have another,
proposing to meet when and where we should appoint; but this I did not fall in with,
as it always has appeared to me better to leave the people in a longing condition,
than in a loathing one; and especially as I did not feel the pointings of duty.

On our way from the boat, when we first landed, we passed a respectable looking house,
which attracted my attention, accompanied with an impression,
that my Master had some service for me there;
but I then felt satisfied to pass quietly on.
I kept this matter to myself, until the time for our departure was at hand,
when the subject came with such weight on my mind that I feared any longer to conceal it.
On Nicholas Naftel describing the house to Philip Hurle,
and my prospect to visit the family who resided there, he manifested some alarm, saying,
the parson`'s brother lived there, and they were great folks;
that he feared our going would give offence; adding, there is a young woman,
sister to the master of the house, resides with him, who has of late become more serious.
Feeling, as I believed, that Spirit near which, if attended to,
would preserve me from giving any just occasion of offence,
and that I should not be clear in my great Master`'s sight without it, I made an attempt
to introduce myself to such of the family as were willing to receive us;
we accordingly proceeded, and were received by the young woman before alluded to,
in a very courteous manner, and a full opportunity was afforded to relieve our minds,
and from the affectionate manner in which she took leave of us at our parting,
we had reason to be satisfied our visit was kindly received.
I was enabled to go on my way rejoicing that I had not been
permitted to desert my post of religious duty.
We were expected to take tea with a family; and on reaching our place of entertainment,
had the company of three neighbours in addition to the family.
The time before tea passed in conversation on religious subjects, I trust profitably;
yet it felt to me that care was necessary,
lest a disposition should be fed which has a life in talking of the mercies of God,
without being concerned daily to dwell under a sense thereof,
ready in acknowledging their own insufficiency and unworthiness,
and yet self and self-activity not so slain, as livingly to feel their dependence on Him,
who remains to be "`the resurrection and the life`" to all who truly confide in him.
After tea we dropped into silence,
and believing myself called upon to minister to our little company,
I had to lay before them the necessity of being weaned from all dependence on man,
however favoured at times the instrument might be,
if ever we come to witness a being taught of the Lord,
and an establishment in righteousness.
An elderly woman,
who I afterwards understood was a leading character in the Methodist society,
and much looked up to by many among them, at our parting manifested her friendship,
expressing the desire she felt that if we never met again in this life,
we might have a joyous meeting in eternity.

First-day we proceeded to a part of the island called St. Helliers;
where we met with two members of our religious Society, and an interesting young woman,
their niece, who received us kindly,
notice having reached them of our intention of being at their meeting today,
which proved a satisfactory one.
In the evening we had a large meeting,
which was mercifully owned by the great Master of all rightly-gathered assemblies;
we were much solicited to make a longer stay on the island,
but with this evening`'s work, my service closed.
We therefore took our departure, and reached Guernsey,
from which I embarked for Southampton,
and was favoured to return to my family with the reward of peace,
and renewed cause for thankfulness, in that I found all things well.

1803+++.+++ In the seventh month this year,
I informed my Monthly Meeting of an apprehension of duty
to visit the families of Friends in Berkshire and Oxfordshire,
not visited when I was there about six years before;
and a certificate was ordered to be brought to the next Monthly Meeting.
But, I little knew the trial of faith that awaited me.
On my religious prospects reaching the ears of a young man,
who had for some time had the management of my business in my absence;
and who had taken offence in consequence of my having recently
spoken to him respecting some irregularity of conduct,
he gave me notice he should quit my service before the next Monthly Meeting.
My condition for a time felt almost insupportable; being unable to see,
that I was discharged from the work assigned me,
nor did it appear possible I could qualify another person in such a short time,
to conduct my business, however willing he might be to do his best.
No way clearly opened, but to endeavour to train up my youngest son,
about fourteen years of age, to take the care in my absence.
I feared the consequences of staying at home,
and to leave my business under the care of one so
young and inexperienced in men and things,
was a close trial of my faith;
but I was enabled to come at a willingness to arrange
my outward matters in the best way I could;
and then leave them to Him who aforetime had given me abundant proof,
that he remained faithful and true in fulfilling his promises.

On the 27th of eighth month I left home;
but for many miles my tried mind could hardly resign it,
under the circumstances in which I parted from it;
but before evening my anxiety was wholly taken away.

First-day, attended meeting at Maidenhead, which was small;
in the afternoon walked to Henley; the few Friends of this meeting were convened,
to whom I opened my prospect of a visit to their families,
and proceeded therein this evening.
Third-day visited two members of our Society at Christmas Common,
with whom I was led into sympathy,
on account of the bad road and distance they had to travel to meeting,
from a hope that attended my mind they were desirous not to be
found slack in the discharge of duty in assembling with their friends.
Fourth-day walked to Wallingford; three families of Friends reside here.

After making a visit to each of them, in the evening I returned to Shillingford.
Fifth-day proceeded to visit the few families in this place and Warborough,
attending their mid-week meeting.
If my feelings were correct, the life of religion is at a very low ebb:
that which gives the victory over the roving of the mind in meeting,
and over the unlawful passions out of meeting, not being rightly sought after,
is in consequence not enough known.

Having visited the families here except two,
I felt a stop in my mind against proceeding further; why it was so I must leave.
Next day walked eight miles to Abingdon, where only one family of Friends reside,
who keep up a meeting; after sitting with this family,
I walked fourteen miles to Farringdon.
First-day attended meeting there, which is pretty much made up of one family.
I proceeded this afternoon to Burford, and next morning commenced a family visit,
which I was helped to accomplish before I retired to rest.

Third-day walked to Witney, about seven miles, and on fourth-day visited their families:
among those I visited was an individual who had
been a class-leader in the society of Methodists;
but being favoured to see the insufficiency of the will and activity
of the creature to further the will of the Creator,
became dissatisfied with occupying this situation,
and was induced to separate from that religious society,
from a conviction of the necessity there was to wait
upon the Lord in silence for that renewal of strength,
whereby alone we can grow up as trees of righteousness of his own right hand planting.

Accompanied by Thomas Minchin,
went to where there are several in profession with Friends, some who are in membership,
others who have been disowned,
and some who make a profession of being under convincement.
We sat down with them collectively, a very aged couple made a part of our company.
The man, from his patriarchal appearance and great profession of kindness to us,
might pass for one of the first-rate active members of the Monthly Meeting.

After we had sat a short time together,
on a sudden my mind was struck with the idea of something coming towards me,
which bore the resemblance of a sheep,
down to the very hoofs and over the whole body and head,
but as it seemed to approach nearer,
I plainly discovered the snout and piercing eyes of a wolf,
which it had not power with all its craft and cunning to disguise.
Nothing could I come at but this wolf, so completely disguised down to the very hoofs,
and yet its sharp snout and its fierce eyes betrayed it.
It appeared to me if I was faithful, strange as the relation of it might appear,
I must inform the meeting how my mind had been occupied.
After struggling with these apprehensions of duty a considerable space,
I was enabled to stand up and faithfully relate what had so closely occupied my attention;
with my belief of its being descriptive of the character
and conduct of some individual present,
whereby the way of Truth had been evilly spoken of,
and the principles we profess in various ways reproached.
Having fully relieved my mind,
in endeavouring to set forth the sorrowful consequences
that would eventually follow such deceitful acting,
unless a timely amendment of conduct took place;
I felt constrained to clear my companion from having
given me information respecting any present.

After meeting, my companion told me, it was a great relief to him I had done as I did;
if I had not he must have been under the necessity of doing it;
that I had been enabled to speak to the state of the aged man,
who professed so much kindness to us before meeting,
as correctly as if I had been acquainted with every circumstance
relating to his conduct for many years past.
He had long been disunited from the Society,
and his conduct in various ways continued very reproachful,
his conformity in his apparel,
giving him confidence with those who were strangers to him,
so that the reputation of the Society frequently suffered through him.

At North Newton, I visited the families of Friends.
On my entering the house of the only family not visited, I felt a stop in my mind,
accompanied with a caution against taking my seat in the house,
which tried me not a little.
I felt it best for me to say to the mistress of the house,
that if I had any service assigned me among the members of this meeting,
it appeared to me that it closed with the last family I sat in.
It was therefore safest for me not to proceed further.
The master of the house, with tears, replied,
he supposed I was only sent to the righteous,
and that the lukewarm and indifferent were to be left to themselves.
I believed silence on my part was best,
although it appeared to me he had correctly described
the sorrowful state he had fallen into;
I felt deeply for the man,
yet I thought this disappointment might tend more to their real and lasting
advantage than anything that could be communicated to them.

This afternoon intending to go to Deddington to lodge,
where there were several persons under convincement, who attended Adderbury meeting;
Friends of Banbury expressed their fear I should
not be comfortably accommodated with a lodging;
but as I apprehended it best for me thus to proceed, I believed,
if I laboured after contentment with the best accommodation their slender means afforded,
I should be cared for.
I reached Deddington in the evening: the attenders of meeting were soon collected,
which would not have been the case earlier in the day: we sat down quietly together,
and I humbly hope I was in my proper place this evening.
I now set my face towards my own home, where I found my family well,
and my outward concerns in as good order as if I
had been present with them the whole time.

I had not been long at home,
before the subject of my having a meeting at Uflington
near Farringdon became a burden too heavy to bear.
Our Monthly Meeting drawing nigh, I informed my friends how I was circumstanced,
and that I wished to be at their disposal,
either to give up my certificate and remain at home,
or pursue my prospect of having a meeting at Uffington.
My friends encouraging me to pursue my prospect,
on the 13th of tenth month I again left home,
and reached Farringdon on the following day;
on informing Friends there the cause of my returning,
they very kindly proceeded to have the meeting-house prepared,
and notice given for a meeting on first-day afternoon.
When we reached Uffington many were gathered round the meeting-house,
and in a short time the meeting was full.
The solid quiet behaviour of the people during the time of silence,
which continued a full hour, was commendable;
and the solemnity felt over the meeting was more than is
often experienced where the company is so large;
and principally persons not of our religious persuasion,
very much unacquainted with our manner of sitting
together for the purpose of Divine worship.

While I was on my feet, engaged in addressing the assembly, a circumstance occurred,
that for a short time broke in upon the solemnity with which the meeting was favoured.
The main beam of the upper gallery, which was crowded with people, as well as underneath,
on a sudden gave a violent crack and broke short off.
My feelings were much excited for those who were under the gallery.
It was however soon cleared above and below,
without any of our company sustaining any injury except from the fright.
The people, such as could, coming into the meeting-house again,
and the meeting settling down quietly,
afforded me an opportunity of relieving my mind among them;
and the meeting closed under a precious sense,
that holy help had been near to us during our sitting together.
I returned to Farringdon, I hope I may say, thankful to my Divine Master,
who had so bountifully cared for me this day.

But I soon had to see my difficulties were only in part got through;
for before I could make my escape to my own home,
I was again arrested by an apprehension of duty to have a public meeting at Deddington.
I feared to proceed any way but to Banbury,
concluding the Friends of that meeting would be the
most suitable for me to confer with on the occasion.
It appeared that an attempt to have a meeting there had been made a short time ago,
and a place procured for the purpose,
but when Friends arrived they were refused admittance,
through the interference of a person who had great influence in the town.
It being summer time, and the weather favourable for it,
Friends thereupon concluded to hold their meeting
under a large tree at one end of the town,
where in a short time there was a large gathering of people.

After the meeting had become settled,
the man who had prevented their having the place to meet in,
came shouting to the spot where Friends and others were assembled,
threatening to break up the meeting,
declaring it was an unlawful assembly. Finding the people were not moved by his threats,
and that Friends kept their standing,
he asked who was willing to go into the town to fetch a saw or a hatchet.
A man present offering his services, went; on his return,
he was ordered by his employer to ascend the tree and cut off the limbs,
hoping by this means to disperse Friends and the people;
but a woman Friend kneeling down in supplication,
his mind appeared to be so far softened that he ordered the man to stay his hand.

Awhile after the Friend rose from her knees, he gave orders to the man to proceed,
on which the people requested Friends not to be afraid,
for that they would protect them from harm.
Disturbed as this opportunity was, it proved the means, in the Divine hand,
of producing an inquiry in some who were then present,
after the more acceptable way of the Lord.
These accounts were discouraging to me, and the more so,
as I could observe Friends were much tried at the
thought of making an attempt to hold a meeting there;
but the more I looked at all the circumstances attending this matter,
the more I feared the consequences of too easily giving up making the attempt;
and a Friend offered to accompany me to Deddington to try what could be effected.
I felt not a little for my kind friend who had thus offered to accompany me,
believing it was done much in the cross.
I could see no other way for me to proceed,
but to wait upon the person who had so violently opposed Friends having a meeting before.
We accordingly went to his house, expecting, from report,
no other than rough treatment from him; but in this we were agreeably disappointed.

On our entering the room where he was sitting,
I offered him my hand with as pleasant a countenance as I well was able to muster,
when he with apparent kindness gave me his, and brought a chair for me.
I then, in as brief and handsome a manner as I was capable of,
informed him the cause of my thus waiting upon him,
requesting him to give his reasons for opposing Friends having a meeting in the town;
to which he very mildly replied, their parson preached them a very good sermon,
yet to be sure he was a very drunken man.
I told him I marvelled not that their town had got the name of drunken Deddington,
when from his acknowledgment the people had such a bad example before them.
I told him the opposition he had manifested towards Friends
might arise from his not being acquainted with their principles;
and having provided ourselves with Barclay`'s Apology and the Summary of Friends`' Principles,
we presented him with them, which he appeared to receive kindly.

He observed that most of the principal inhabitants
were to meet that morning to choose a mayor,
and he wished to refer me to them; and if they were agreeable to my having a meeting,
he would not oppose it.
After pausing on this proposal, I felt it best to inform him,
that if I could not obtain a meeting without much difficulty,
I believed it would be best for me to turn my attention towards
a meeting to be held in our meeting-house at Adderbury,
being distant only three miles;
and for a general invitation to be given to the people of Deddington;
to which he replied, he believed it would be most likely to answer my expectation,
as they were a very rough set at Deddington: he invited us to take refreshment,
and we parted friendly.

We heard, after this opportunity,
that he carried himself kindly towards those who
had begun to attend the meetings of Friends,
which aforetime he had not done.
I thought if nothing more was effected by the steps we had taken than removing the prejudice
from this man`'s mind against those who have begun to attend our meetings,
it was well worth passing through what we had done to bring it about.

First-day morning attended meeting at Adderbury.
I had a fear of which I could not suppress the expression,
lest the people of Adderbury should get knowledge of the meeting,
and so fill the seats that those who came from Deddington would not be accommodated;
but I found Friends were of the mind that from the distance,
there would not be many from Deddington.
In the afternoon when we reached the meeting-house, we found it nearly filled:
the meeting sat more than an hour in silence,
during which it seemed at times that if a pin had fallen it might almost have been heard,
which precious covering was mercifully vouchsafed until the meeting closed;
after which it was to me a very animating sight,
to behold the people ascending the hill to Deddington,
very few of the people of Adderbury, it was said, being in the meeting.
On third-day, I was favoured again to reach my own home,
with a portion of that peace which will not fail to attend simple obedience.

At our next Monthly Meeting, I returned my certificate,
and informed Friends of a prospect I had to visit some meetings in Essex,
Suffolk and Norfolk.
It appearing needful I should move herein before another Monthly Meeting,
I informed the meeting, and a certificate was accordingly drawn up and signed.
12th of eleventh month I left home, walked to Chelmsford, about twenty-seven miles.
First-day morning, attended meeting there,
in hopes to find a little morsel of bread to help me on my way,
but in this I was disappointed.

In the afternoon I proceeded to Stebbing, where a meeting was appointed at five o`'clock,
for Friends only.
Third-day I walked to Thaxtead, and attended the select meeting,
in which my mind was refreshed; after this was held the Monthly Meeting,
in which it appeared a good degree of care was maintained,
not to enter upon the weighty concerns of the meeting in a superficial manner.

After the Monthly Meeting, I reached Becking, and next day Coggeshall;
attended a meeting there appointed at my request,
and in the afternoon one at Earle`'s Colne, both of which meetings are small;
my heart yearned in Gospel love towards some of the youth,
who I believed were under the preparing hand of the great Head of the church for usefulness.
O, for these! may they find skilful nursing fathers and skilful nursing mothers,
such as will neither dandle them too much on their knees,
nor neglect to give them their necessary portion of sound wholesome food in due season.
From Earle`'s Colne I reached Halstead, and next day attended their mid-week meeting,
in which I was engaged to labour with some far advanced in life,
who through an unwillingness fully to come under
the government of the Great Gardener of the heart,
were in a withered unfruitful state,--also in a line of encouragement to the youth.

This night I reached Sudbury, and next morning Bury.
The few Friends here were collected this evening at my request,
and the meeting proved a very exercising one,
yet apprehending I was in my right place in sitting with them I was made thankful.
Seventh-day I walked to Ipswich, and first-day attended meeting there,
where I found a considerable body of Friends, among whom were many young people,
to whom I trust, through holy help, the language of encouragement was handed out,
to be willing to accept in early life the offers of Divine love and mercy,
to press through the crowd of hindering things towards
that state of perfection attainable in this life,
that the complete victory over sin being experienced,
they may not fall short of the true enjoyment designed for them in this wilderness journey.
After the morning meeting I walked to Woodbridge, attended the afternoon meeting there,
and then the Preparative Meeting.

On second-day returned to Ipswich, and in the evening attended the select meeting.
Third-day attended the Monthly Meeting; and on my way I called upon a sick Friend,
who rather pleasantly told me,
some of the young people conceived what I had expressed
on first-day on perfection was advancing new doctrine,
and that he had endeavoured to justify what I advanced on that head;
this circumstance remained with me and increased, until it burdened my mind.
The meeting previous to Friends entering upon the business was large,
yet the way did not appear clear for me to attempt
to confirm what I had advanced on first-day.
I therefore endeavoured after patience to bear my burden;
but before the meeting for business was over,
I was brought under the necessity of requesting a
meeting with the young people in the evening.
It was concluded upon to hold it at six o`'clock, and I went to it under discouragement;
it was largely attended, and proved solid and satisfactory,
after which I returned to my kind friend John Perry`'s, where I quartered.
A young man came to me, saying, he with others,
had questioned the soundness of what I had advanced in the meeting on first-day;
and that he was thankful he had been at the meeting this evening,
the subject having been further spoken to, much to his satisfaction.
I felt thankful I had been preserved in patience from making
an untimely offering in the meeting for worship,
previous to Friends entering on the business of the Monthly Meeting,
to get from under my burden;
a fresh proof that our time to do the Lord`'s work is not the best time.

Fourth-day walked to Tivitshall.
At the close of the mid-week meeting their select meeting was held,
after which I proceeded to Norwich and next day walked to Yarmouth,
and had a meeting with Friends there this evening.
First-day to Tasborough, and attended meeting there,
in which I believed myself called to sound an alarm to a state present,
in so plain and pointed a manner, that I felt much discouraged after I had taken my seat;
but my head was again lifted up, under a hope I had not been out of the way of my duty,
in what I had thus delivered,
by a testimony that was offered in the meeting by an exercised sister,
confirming what I had before uttered.

In the afternoon I returned to Norwich,
where a meeting was appointed to be held that evening at my request.
To observe how much this meeting had been stripped in a few years of its useful members,
was to me mournful;
and the more so in observing so few of the rising
generation likely to fill the vacant seats of such.
Poverty, I believe I am safe in asserting, has not been the cause of this falling away,
nor the necessary care and attention to provide things honest in the sight of all men,
but a determination on the part of some parents to possess the wedge of gold,
and to get great riches;
and on the part of the children of such to deck and adorn themselves
with the Babylonish garments of the world`'s fashions,
which is to be expected in the children of such parents.
Second-day I proceeded towards Coggeshall,
and attended Essex Quarterly Meeting held there,
and here my service closed for the present.
I proceeded towards my own home, which I was favoured to reach in safety,
and as heretofore has been in adorable mercy my experience, found my family well,
and outward concerns abundantly cared for,
of which blessing I desire every part of my future conduct may manifest a grateful sense.
