== Chapter IV.

1807+++.+++ At our Monthly Meeting in the second month,
I requested its certificate to visit the meetings in the neighbourhood of Ackworth,
the families of Friends in Lancaster and Liverpool meetings,
and some meetings in Wensleydale, which being united with,
a certificate was ordered accordingly.

First-day, 15th of the third month I left home, and reached Hertford in the evening;
attended their select Quarterly Meeting,
and second-day the Quarterly Meeting for discipline:
the meeting for worship was I believe truly profitable to some,
and the business closed agreeably.
Fourth-day I walked to Kettering in Northamptonshire,
and attended their meeting next day;
but my unfaithfulness caused me to leave this place under suffering,
yet it appeared safest for me to proceed, endure my sufferings with patience,
and endeavour after greater faithfulness in future.
Reached Sheffield on seventh-day.
First-day attended their two meetings,
and on second-day a large satisfactory meeting at Wakefield,
appointed at the request of Thomas Colley.
Here, as at some other times, I kept back unseasonably to my own hurt,
and I was led to fear, to the hurt of the meeting,
of which I found some of my friends were sensible.
O when shall I learn obedience by that which I suffer.

Third-day walked to Leeds, in the evening attended the Quarterly select Meeting,
and on fourth-day the Quarterly Meeting for discipline,
the business of which occupied three sittings,
and was conducted in a quiet becoming manner;
it closed with a meeting for worship on fifth-day evening.
First-day attended meeting at Burton,
which meeting-house and burial-ground is said to
be the first erected by Friends in these parts.
Over the principal entrance of the graveyard,
there is a large copper-plate engraving much obliterated by time.
An aged man, a member of the Society who now occupies the house adjoining the premises,
told us, his family had continued to reside there for three generations,
and related the following anecdote,
showing how Friends came into possession of the property.
In the commencement of the Society in this neighbourhood,
a young man who had embraced the principles of Friends died;
and when they were taking the body to the parish graveyard for burial,
a number of rude people assembled, and became so tumultuous,
that they threw the coffin down, broke it, and rolled the dead body into the road;
the owner of the property which the meeting-house and burial-ground now occupy,
being present, was so affected at this conduct,
that he said he would prevent such outrages in future; and marked out the ground,
and gave it to Friends for the purposes for which it is now used.

As I had not the prospect of my time being wholly filled up in appointing meetings,
and being persuaded it would be beneficial both to mind and body to be suitably employed,
I proposed to my kind landlord Christopher Walker of Dirtcar,
to make myself as useful on his farm as my strength would allow.
Fifth-day walked to Pontefract: from a heavy fall of snow,
I had some difficulty to reach the meeting in proper time:
it was largely attended for a mid-week meeting; in the afternoon walked to Ackworth,
a meeting being appointed at my request at six o`'clock this evening.

Sixth-day morning walked to Burton,
to attend a meeting appointed for the members of our own religious Society.
In the afternoon walked nine miles to Lumbroyd,
a meeting being appointed to be held at five o`'clock this afternoon:
the snow being much drifted, made travelling on foot in this open country difficult,
yet as I believed it was required of me to set this example,
I was helped to press through every obstacle,
under a persuasion that if I refused to maintain my post in this respect,
my Divine Master would have no further service for me.
This meeting is much stripped of its members, and has now become very small;
and if my feelings were correct, the life of religion is at a very low ebb.
I was led in a singular manner in the line of the ministry, which is trying to nature.

First-day morning walked to Highflatts, and attended meeting there which was very large;
in the afternoon to a meeting at Wooldale, which was largely attended,
and closed under a precious sense that Divine regard was hovering over us.
Fifth-day attended meeting at Wakefield,
in the afternoon walked to Dewsbury to a meeting held in a Friend`'s house,
no meeting-house being yet erected in this rather new settlement.
Next day I walked back to my home at Dirtcar, for so it felt to me,
when no further prospect of service opened; thinking it a favour,
during these cessations, that I had something like a permanent home to go to,
where an opportunity was allowed me usefully to employ myself.

First-day morning walked to Paddock near Huddersfield, about thirteen miles,
the weather being wet and boisterous at first turning out, was discouraging,
yet I was helped to get along and reach the meeting-house in due time.
If my views of the state of the members of our Society there are correct,
the precious seed of the kingdom is buried in many hearts
under the surfeiting cares and concerns of this life.
In the afternoon I walked to an appointed meeting at Brighouse.
It was largely attended by those not in profession with Friends,
which circumstance at first disconcerted me not a little,
my views in appointing the meeting being only to members and attenders;
but as there was no alternative but to bear it quietly,
I was favoured with help to rise above my discouragements,
and to obtain relief to my own mind in a close searching
testimony to the members and attenders.

While I was on my feet, a young man left the meeting,
who I afterwards understood was a member;
it appeared that something which I had offered touched him to the quick.
After the meeting was over, I began to dispute the correctness of all I had said,
letting in great discouragement.
During this conflict of spirit, a Friend stepped up to me, saying,
she believed it was best for her to tell me,
that there were those among them who well knew there was occasion
for such close doctrine being delivered among them.
Second-day morning after an interesting opportunity
with a young couple with whom I took my breakfast,
I walked to Dirtcar and resumed my employ.

Fifth-day attended meeting at Gildersome,
and was comforted in sitting with the few that compose it;
and in the afternoon walked to Rawden to attend an appointed meeting.
There I found a considerable body of members and attenders of meeting,
the greater part young people.
During my sitting in this meeting, a fear exercised my mind,
that the world and its treasures were making such inroads on some of our company,
that there was great danger they would deprive the Society of their services,
and ultimately themselves of heavenly treasure.
The language of encouragement was given me to hold out to some of the youth,
that if obedience kept pace with knowledge a living
ministry would yet be raised up among them.
Second-day walked to Undercliff near Bradford, and attended the Monthly Meeting there:
which was rather small, but on the whole profitable.

First-day walked to Burton: the meeting house being damp,
the meeting was held in an upper room, and I was apprehensive,
from Friends thus deserting the meeting-house,
strangers might be prevented from sitting down with them,
by supposing that Friends were occupied about some Society concerns and I therefore
advised Friends to adopt some means of making the meeting-house safe to sit in.
Second-day attended Monthly Meeting held at Burton.
While the clerk of the Monthly Meeting was reading that part of my certificate,
in which my friends expressed a desire that every instance of dedication
might be blessed to myself and those among whom my lot was cast,
a young man wept aloud.
On inquiry, I found he had been much visited,
and that these expressions had a tendency to bring closely home to his mind,
seasons of favour, which if he had improved,
it was believed by his friends he would have come forward in usefulness in the Society.
Earnest desires accompanied my mind on his account, that he may be excited to dedication:
but, alas! what will the good desires of our friends avail,
unless we ourselves are willing to yield in humble
submission to the impressions of Divine good.

Third-day walked to Halifax, where about five members of our religious Society reside,
and proposed a meeting with them at five o`'clock next evening,
after which walked to Paddock to attend their mid-week meeting; but,
to my great disappointment, a very few compared with their number, gave their attendance:
after meeting walked back to Halifax, and attended the evening meeting.
Stripped as this meeting is of its members, I was encouraged to believe,
if the few who are left were but earnestly engaged to seek for holy help
and to be found faithful in supporting our Christian testimonies,
there would yet be a revival in this meeting,
there once having been a large body of members of
our Society in this town and its neighbourhood.

Next morning I walked to Brighouse, and attended the week-day meeting, which was small.
I hope our sitting together was of real profit to some of the little company;
but not feeling my mind easy to leave this neighbourhood,
I stayed over their first-day meeting.
In the meeting this morning, I was constrained to say,
I believed there were some present,
who were in danger of making a sacrifice of their right
of membership to their own and the church`'s loss.
I was led also to state what I believed would be the sorrowful result of such conduct,
slighting the private labours of the church, and those public admonitions,
not the result of outward information, of which in mercy they had been the objects.
I felt much tried, after taking my seat, lest I should have been deceived.
Humiliating as these dispensations are, I dare not desire to be excused from them,
or to have them removed, before the full time is come; from a persuasion,
that the more we have been favoured during our ministerial labours,
the greater is the need for some dispositions to
be thus brought as it were into the stripping room,
lest self should be disposed to boast,
or claim part of the credit of what has been communicated.

After meeting a Friend informed me, that a young woman, present at this meeting,
of amiable dispositions and good capacity, and who,
if willing to come under the preparing hand of the great Head of the church,
might become singularly useful in the Society,
was in great danger of having her affections entangled
with a person not in profession with Friends.
These testimonials have a tendency to hold out encouragement to faithfulness,
and if we keep in a true sense of our own insufficiency
and the all-sufficiency of Jesus Christ the Righteous,
will not exalt us in our own imagination, but on the contrary humble us into the dust.

First-day morning attended meeting at York,
and in the afternoon meeting I sat under considerable exercise,
but unequal to rise and cast off my burden.
Third-day, attended the Monthly Meeting at Selby, which was small.
Many meetings in this country are much stripped of ministers,
which makes the company of a stranger traveling in this way acceptable,
but this circumstance calls for increased care and watchfulness,
that the great kindness of our friends does not prove a snare,
or turn us out of the path allotted for us.

Fifth-day morning walked to Malton,
a meeting being appointed at my request at six o`'clock this evening:
I was led to hope it would prove profitable to some of our small company.
Next day walked to Scarborough, to attend a meeting appointed this evening,
which was small.
The following day walked thirty-seven miles to Beverly.
Feeling drawings in my mind to sit down with Friends of Hull on first-day,
I proceeded there by coach, where I met with a pretty good-sized meeting:
but as in many other places up and down, it appeared to me,
the gods many and the lords many had so obtained the dominion over some of the members,
that the precious testimonies given us to bear, are permitted to fall to the ground.
Being strengthened, I humbly hope I may say, to discharge myself faithfully,
I was favoured to depart in peace.
In the afternoon attended a meeting at North Cave.

Fifth-day I was at the usual meeting at Wakefield, and in the afternoon went to Leeds,
and next day attended Monthly Meeting there.

First-day attended the meetings at Leeds,
and on second-day walked to Pontefract to attend the Monthly Meeting.
The town appeared in great confusion in consequence of a recent election.
I feared we should have a trying meeting, but best help was mercifully near,
whereby the concerns of the Society were conducted
more satisfactorily than might have been expected.
Fourth-day had a meeting with Friends of Thirsk, and walked fourteen miles to Helmsley,
where a meeting was appointed to be held at six o`'clock this evening.
Holy help was in unmerited mercy vouchsafed,
for which favour I humbly hope some were made thankful.
Next morning walked to Kirby Moor Side to attend a meeting appointed at my request;
where we had a considerable gathering of Friends and others.
It was held in holy quiet, the calming influence of Divine love and mercy being near.
First-day morning, accompanied by my kind friend John Spence, I walked to Darlington,
and attended meeting: best help being near,
I was enabled to cast off a load of exercise to the relief of my
own mind and I hope to the benefit of some in the meeting.
Rode to Stockton-on-Tees, a meeting being appointed at six o`'clock this evening.
My service appeared to be with some who had sold their birthright,
to whom I had to declare, the present was a time of fresh visitation to their souls.

On second-day the Monthly Meeting at Guisborough,
was large and principally composed of young people,
some of whom appear to be under the forming hand of the Heavenly Potter:
the desire of my soul was,
may they be found willing to endure the proving dispensations of Divine wisdom,
comparable to what the earthen vessels in the potter`'s house have to pass through,
before they are fit to be brought into use!
After meeting I walked to Castleton ten miles,
and had a comfortable meeting with the few Friends there next morning.

In the afternoon walked to Whitby fourteen miles, over a dreary moor,
and next day attended meeting there: Friends I was informed were pretty generally out:
it proved a very trying meeting to me.
After it I walked to Russel Dale, and next day to Helmsley,
and attended their usual meeting: in the afternoon to Bilsdale,
a meeting being appointed at seven o`'clock this evening,
in which strength was given me to relieve my mind, I hope,
to the encouragement of some of our little company.
Next day walked about thirty-two miles to Knaresborough, and next day to Rawden.

First-day attended meeting there, and at Bradford in the afternoon,
which was a time of close exercise to come at any proper settlement of mind:
such dispensations are necessary to be passed through;
there must be a willingness brought about in us, however painful and trying it may be,
to sit where the people sit, in order to become qualified,
through the aid of Divine love and mercy,
to speak to the states of those we are called upon to address.

Second-day I walked to Lothersdale about twenty-two miles.
The great quantity of rain that has fallen of late makes travelling on foot trying:
I hope to be preserved in patience, apprehending it is the line of conduct I must pursue,
when time will allow of it.
Attended meeting here, which to me was a time of mourning,
under a persuasion that the Seed of the kingdom was in prison in many of their hearts:
our company was principally composed of young people.
Although I had to sit in a state of great suffering,
yet I was favoured to leave the meeting under a belief,
I had been faithful in delivering what appeared to be the counsel of my Divine Master.
Sat with the few Friends belonging to Darley meeting.
I felt thankful my lot was cast among them,
and was favoured to receive a morsel of that bread,
which alone can support the mind under the exercises it has to pass through.

First-day morning attended meeting at Settle, and one at Skipton in the evening:
many of the town`'s people gave us their company,
and it was held in a quiet orderly manner.
On second-day attended Monthly Meeting at Otley;
the business of which appeared to be proceeded in under the influence of holy help,
and closed under a sense thereof.
Fifth-day attended the Monthly Meeting at Doncaster, which to me was very trying;
perhaps my own unfaithfulness was the cause,
my faith seeming nearly if not altogether exhausted.
I left the meeting and town under much discouragement, and next day walked to Dirtcar;
this home, under my present suffering state of mind, appearing the safest place for me.

Third-day walked to Selby, and on fourth-day to Hull, in time for their select meeting.
I felt well rewarded for my exertions in sitting down with
the few members that compose this select meeting.
Fifth-day attended the Monthly Meeting, which was large;
and I was comforted in beholding a number of hopeful
young people make a part of this meeting:
but alas, how are these hopes in the rising generation sometimes blasted;
this appearance of fruitfulness, how does it wither and come to naught,
through the prevalence of the spirit of this world,
variously held up for the acceptance of the unwary youth.
First-day attended a meeting at Thornton-in-the-Clay,
and in the afternoon walked nine miles to Malton,
a meeting being appointed at my request at five o`'clock this evening.
There was much rubbish to get through, before the spring of Divine life could be come at,
which occasioned much labour;
but I believe those who were willing to bear their allotted portion herein,
did not go without the reward.
Second-day attended the Monthly Meeting,
the business of which was conducted in much harmony,
although the faithful labourers as at many other places are few:
and how can it be expected the number of these will increase,
as long as the encumbering things of this world keep so many from
feeling that lively interest in the prosperity of Zion,
that would beget a willingness to be made use of,
in advocating her cause against all which opposes
her arising and shining "`fair as the moon,
clear as the sun, and terrible as an army with banners.`"

Feeling drawings in my mind to make a visit to a great man in the neighbourhood,
who once had a right of membership,
I concluded it would be best for me to go and take breakfast with the family.
I accordingly proceeded; but on my arrival, found visitors not in profession with Friends.
After breakfast was over, I made an effort to leave, as it did not appear to me,
way could be made to obtain an opportunity with the head of the family:
but I found I must be willing to seek for holy help to break through the difficulty.
After some struggle of mind,
strength was given me to request that we might sit down quietly together,
which appeared to be readily yielded to.
This afforded an opportunity to obtain relief, beyond what at first I could have expected.

I left the family under a thankful sense, that I had been preserved from being a coward,
and went on my way rejoicing: walked to York about twenty-two miles,
which I reached in time for the select Quarterly Meeting this evening.
Fourth-day the meeting for worship was largely attended;
many concurring testimonies were borne,
and the different states of the people ministered to, under true Gospel authority:
what an unspeakable favour it is, a backsliding people as we are,
that we are not forsaken by Him who alone is able to do our souls good!
The meeting for discipline through its several sittings was conducted in much harmony,
and Friends separated under a grateful sense of that
help which in adorable mercy had been extended.

Sixth-day passed in making some friendly calls: one of these to a young man,
in whose best welfare my mind became interested when in the city before:
believing the most precious of all jewels lay buried under a heap of rubbish, of finery,
fashion, and self-gratification in which he was indulging,
I earnestly cautioned him against further giving way to gratify his heart`'s desire,
but to be willing to accept of the offers of Divine help that yet awaited his acceptance,
and thus he would experience freedom from every entanglement,
and witness his captive soul to be set free.
The visit appeared to be well received;
and under a sense that I had been in the way of my duty, I felt truly glad.
First-day attended Pickering meeting,
in which I sat and suffered under a feeling of the heavy
burdens which the honest-hearted members here have to bear.
In the evening we had a sitting in my kind friend William Rowntree`'s family,
in which my spirit was refreshed and comforted.

Fifth-day attended the mid-week meeting at Todmorden, which was made up of young people,
many of whom have so lost the mark of their profession that
they are become numbered with the people at large.
This is a great loss to many of our youth who are
under the necessity of attending fairs and markets,
and mixing with the multitude, by whom,
having lost this badge of our religious persuasion,
they are expected to use the language of the world and conform to a train of inconsistencies,
thereby doing violence to their better feelings, which they might have escaped,
had they not shunned the cross.

First-day attended the usual meeting at Liverpool,
at the close of which I presented Friends with my certificate,
informing them of my prospect to visit the families
of the members and attenders of their meeting:
and they uniting with my religious prospect, I was left at liberty to proceed.
After the close of the afternoon meeting I entered upon this humiliating engagement,
for so it felt to me,
which I was favoured with holy help to get through in thirteen days,
having had eighty-one sittings, attended six meetings for worship, the Monthly Meeting,
and a meeting for the youth.
Sixth-day morning I left Liverpool for Lancaster, which place I reached on seventh-day.
First-day morning, at the close of their meeting,
I proposed a visit to the families of members and attenders;
a committee was thereupon appointed to lay out the visits, and on seventh-day,
after having in all about sixty sittings,
I was mercifully helped to close this arduous engagement.

First-day morning attended meeting at Wyersdale,
where I found a considerable collection of members and attenders; but oh! the life,
the precious life of true religion seemed at a very low ebb.
In the afternoon I walked about twelve miles to Ray,
and sat with the few that profess with Friends, about ten in number.
It was hard to obtain full relief to my exercised mind,
yet I left the meeting under a comfortable hope,
that I had not kept back any part of that given me to deliver.
Third-day walked about twenty-eight miles to Masham,
sat with the four members that compose this meeting,
and was rewarded for the fatigue of body I passed through to accomplish this visit.
Fourth-day attended a meeting appointed at my request at Leyburn:
the house was a poor place for the purpose,
and much crowded by those not in profession with Friends.
The sense I had, in this mixed congregation,
of the lack of the help of the spirits of brethren rightly
baptized into a desire to be aiding the Lord`'s work,
was more to me than any bodily inconvenience.
Fifth-day I walked about eight miles to Aysgarth,
and attended meeting there this morning,
where I met with a few who I believe were rightly
engaged for the support of our various testimonies;
but my mind was introduced into a fear that others present,
were laying waste many if not all our precious testimonies,
to some of whom I had hard things to deliver.
In the afternoon walked about ten miles over the moor to Reeth,
and had a meeting with four members.
The prospect here is discouraging, unless a revival takes place,
the meeting being reduced and the meeting-house shut up.

First-day attended the two meetings at Liverpool,
hoping to see my way clear on second-day for moving towards my own home;
but as heretofore I found it was not safe to be looking too far forward,
but to be content to live one day at a time.
Fourth-day attended a burial, at which were many not in profession with us:
I believe it proved to some a satisfactory time.
Fifth-day walked to Hardshaw about twelve miles, attended Monthly Meeting there,
returned to Warrington this evening,
and lodged at my kind friend John Bludwick`'s. A company of poor persons at West Houghton,
about ten miles from Warrington,
were in the practice of meeting together for religious worship after the manner of Friends,
towards whom my attention was turned,
with an apprehension of duty to sit with them on first-day in their usual meeting.
I had not heard that Friends had yet taken so much cognizance of them as this,
and how this would be approved of by Friends of the Quarterly Meeting,
was a subject that tried me not a little,
lest it should be considered like laying hands suddenly upon them.

I came down to breakfast next morning in a very poor plight to walk to Macclesfield,
as I had given my kind friend to expect I intended.
On my informing him how it had fared with me through the night, and that,
looking towards home, my way was shut up, he encouraged me to pursue my prospect,
offering to procure a conveyance and bear me company.
I believed it best to proceed on foot, and as he would not be equal to such a task,
another Friend offered to accompany me.
On seventh-day we walked to Wigan,
where some of those who met at West Houghton we understood resided,
to obtain information where their place of meeting was, and one whom we met with,
engaged to conduct us to it next morning.
I cautioned them against informing any, of our intention of sitting with them,
except those who were their usual attenders.
From the feelings which accompanied our minds in this family,
we thought it might be said, peace was within their walls.

The next morning the man conducted us to their meeting-place, in a very secluded spot,
remote from the public road.
At the hour appointed, the meeting gathered very punctually, in all about thirty-four,
many of whom, to my feelings, seemed to bring good along with them into the house.
In a short time a profound silence spread over us, and not a few of our company,
under the influence of it, were humbled and bathed in tears.
Such were my feelings on the occasion, I could not but secretly acknowledge,
these are worshipping God in Spirit, and have no confidence in the flesh.
This silence was of long continuance,
and feelings of tenderness towards this contrite company were so excited in my breast,
that it was difficult for me to express among them what was on my mind,
without manifesting such a degree of abasement as
rendered my words I feared at times unintelligible.
The Friend who accompanied me, after speaking a very few words, sat down; telling me,
after the meeting,
his mind was so wrought upon through the contrition generally apparent in the meeting,
that after uttering a few words he was obliged to desist.
When the meeting broke up, the floor in every direction was strewed with their tears.
As there was a cottage adjoining their meeting place occupied by one of the families,
we concluded to invite ourselves to dine with them,
in order to have more of the company of such as inclined to give it to us.
We found those who lived remote from the meeting place had
brought their dinners with them to eat in the cottage,
which was both clean and comfortable:
hearing of our intention of coming to sit with them,
they had made provision for us at the cottage.
Although our fare was homely, our minds having been previously refreshed,
and still continuing to feel the precious effects of it,
we were abundantly satisfied with our repast,
uniting in the acknowledgement we never enjoyed a meal more.

On inquiry, they informed us, this was the first visit they had received from Friends:
at times some of them attended Friends`' meeting, which they would prefer,
rather than meeting as they now do,
but the nearest Friends`' meeting some of them would
be able to get to was eight miles distant.
We were as much refreshed by some of the remarks made by our company,
as by the comfortable meal we made.
I felt the need of cautioning them to be on the watch,
lest they should be weary of sitting in silence,
and that should set some of them to preaching.
Desirous of information respecting their rise and progress,
so far removed as they are from any meeting of Friends,
the following relation was given us.
An old man, who lived at West Houghton, much attached to the principles of Friends,
on seventh-day evening went to a barber`'s shop to be shaved,
at which shop some of those who now meet at West Houghton attended also.
The old man at times introduced conversation on religious subjects,
and especially on the principles professed by Friends,
whereby a desire was excited in them to become further
acquainted with our religious principles,
in which he took great pains to satisfy them,
furnishing them with such Friends`' books as were in his possession.
He died before they met as they now do, and his removal was like the loss of a father,
from the veneration they still manifest for his memory.
It was evident he had been an instrument in the Divine hand of great good to them.

Since the visit we made them,
several of this company have been received into membership with the Society,
and a meeting of Friends is now settled there.
On our way back to Warrington, we came up to a company of young men,
whose conduct as I passed them manifested much levity.
I felt the fire of the Lord kindled in my bones against
their unruly unchristian-like conduct,
and yet a fear came over me lest the feelings that were
excited should proceed from a fire of my own kindling.
I passed on, but the further I advanced, the greater my uneasiness became;
and seeing no way for me to escape condemnation, but by being willing to turn back,
we did so.
On my claiming their attention, some withdrew,
those that remained manifested a degree of thoughtfulness,
as if willing to receive what I had to offer,
and feeling my mind released from the burden I had been brought under,
I was enabled to go on my way rejoicing.

We reached Warrington in time for the evening meeting,
which was largely attended by those not in profession with our religious Society.
The meeting appeared to separate under a feeling of the overshadowing of Divine good.
I now began to hope the way would open for me to move towards home:
but alas! bonds and afflictions awaited me.
A sleepless night was my portion,
which afforded me an opportunity to take a retrospect of some of my movements of late,
that if I had in any wise missed my way, I might be favoured to see it,
that a sense of it might excite me to more care and circumspection in future.

First-day attended meeting at Macclesfield,
and many not in profession with Friends gave us their company.
In the afternoon walked about thirteen miles to Leek,
a meeting being appointed at my request:
we had a large gathering of those of other professions;
to me it was a laborious but relieving time,
and I believe there was ground to hope it would prove
a time of profit to some of our company.

Second-day walked twenty-nine miles to Derby:
as I did not reach it until a late hour in the afternoon, it brought me under difficulty,
feeling drawings in my mind to have a meeting this evening with such as
were considered the more libertine of those not professing with Friends.
A few Friends were called together, to whom I opened my prospect,
with which they appeared cordially to unite, except as it respected the time,
that being too short for giving notice:
and next morning was proposed as likely to secure a better attendance.
I endeavoured to give this proposal of Friends due place in my mind,
but not being satisfied it would be safe for me to put the meeting off,
they concluded to do their best in giving notice for seven o`'clock this evening.
When the meeting closed,
Friends said it was larger than had been known for a considerable time,
and of a description of people who had not been seen at a meeting of Friends here.
The time appointed being well observed, the meeting was early settled,
and it proved a solid time, the people departing much in the quiet.
There is great need for those who are travelling in the work of the ministry,
and those who are consulted, relative to their movements,
to keep their eye single to the one alone unerring Guide.

Third-day morning I left Derby, a few of the Friends accompanying me a little on my way,
walked thirty miles to Leicester under a thankful sense
of the lovingkindness and fatherly care of the Most High,
in being with me under my various exercises and helping me along from day to day.

The following sixth-day brought me safe to my own home,
where after an absence of six months I was favoured to find all well.
