== Chapter V.

1808+++.+++ My mind, at times for some years past, had been impressed with a belief,
it would be required of me to make a visit to Friends in Ireland,
and apprehending the time was come to lay the prospect before my friends,
in the second month this year I requested a certificate
of the Monthly Meeting to engage in this service,
which was granted me in the third month.
I made the necessary preparation to return with such Friends
as came from that nation to attend our Yearly Meeting;
but when this time arrived, my way was so shut up, I dared not proceed.
On endeavouring to find out the cause,
I was given to see that my not having been faithful to the
Divine requiring by freeing myself from my leasehold property,
was one cause.
Being made willing to yield in the disposal of this property,
I became freed from any future encumbrance that might occur,
which I esteemed a very great favour.

Seventh-day, 9th of seventh month, I took my leave of my dear wife and family.
On first-day morning attended meeting at Hertford, and in the afternoon at Hitchin,
where I was favoured to receive a morsel of that
bread which alone can sustain the immortal part.
Second-day rode to Ampthill in Bedfordshire.
Third-day walked thirty miles to Lower Heaford.
Fourth-day morning proceeded on foot towards Hinkley in Leicestershire.

About nine o`'clock the sun shone out very hot,
exceeding anything I had before experienced.
I made but little progress, although by stripping off most of my apparel,
I relieved myself all in my power.
By twelve o`'clock the air became so hot that I felt
as if I was surrounded by heat from a fire.
I had not passed a habitation of any description,
and was some miles from the house of entertainment; I became very thirsty.
The weather having been long dry, no water was to be met with;
but after awhile I found a small body of stagnant water,
in which a cow was stamping her feet to cool herself, but my thirst was such,
I felt thankful for this supply.
I proposed to remain under the shade of some trees until the sun set;
but as they were at a distance from the road, I considered I might lie down and perish.
I therefore concluded it most prudent to keep on the road, and do my best,
in hopes I should be able to reach some cottage to take shelter in.
After travelling about two miles I caught sight of a boy driving some cows,
and offered to reward him if he would carry my bundle of clothes,
and conduct me to the nearest house.
I procured a drink of water at this house, and the people conveyed me to the inn.
After tea I proceeded and was favoured to reach Hinkley late in the evening.
Nearly fifty horses, it was reported, dropped down dead on the North Road,
and many people who were working in the fields.
It was supposed to be the hottest day known in this nation.
Notwithstanding all I had endured,
I considered it a great mercy I had been so cared for and brought safe through at last,
to be under the care of my friends again.

Fifth-day morning attended meeting here, and at Colebrook Dale on first-day.
If my feelings were correct,
it appeared to me many were contenting themselves with living on the labours of others,
and not labouring to know the Lord for themselves:
at the close of the meeting for worship the preparative meeting was held,
and my unfaithfulness therein caused me to leave the Dale with a sorrowful heart.

In the afternoon I rode to Shrewsbury and attended a small evening meeting.
The fathers in the church are removed from this part of our religious Society,
and the prospect of their vacant seats being filled
from among the present members of the meeting,
appeared discouraging.
Fourth-day being their Monthly Meeting, Friends importuned me to stay.
I found watchfulness necessary on my part,
lest I should be tempted to make a halt beyond my proper time,
not apprehending I had any thing to do with their Monthly Meeting.

On second-day morning I took to my feet again.
The day being fine,
the winding river Severn frequently making its appearance
among the hills clothed with wood,
and the simple manners of the people I met with,
rendered this day`'s journey less trying than sometimes is the case.
I reached Chirk early in the evening, where I took up my abode for the night,
for I scarcely can say I slept, the house being full of noisy company,
who continued until a very late hour.
I felt poorly next morning,
and unequal to pursue the journey of thirty-five miles before me;
but after taking breakfast, I proceeded, and reached my destined port in the evening.

Fourth-day walked about thirty-three miles to Llangefric;
the heavy rain that fell during the course of the
day added much to the beauty of the surrounding scenery,
by the rapid falls of water which in many places
poured down the cavities of the stupendous mountains,
yet it rendered walking difficult:
but as I apprehended I was moving in accordance with the requiring of my Divine Master,
I was cheered by a hope I should be cared for by him to the end of my journey.
Fifth-day morning I proceeded, and reached Holyhead about noon;
and about seven o`'clock in the evening I went on board a packet for Dublin.
Considering the danger of the great deep,
and the suffering from sickness which those who are
unaccustomed to traverse it mostly have to endure,
I felt thankful I had objected to any Friend accompanying me merely across the water.

We had a crowded vessel: some of the passengers, at my first going on board,
manifested a disposition to pass their jokes upon me;
but by endeavouring to keep near to that Divine principle
which can preserve in every situation,
and to refrain from retaliating or resenting,
I was enabled to express my disapprobation of their treatment,
in language that appeared to be well received,
they generally carrying themselves respectfully towards me afterwards.
On sixth-day morning we were favoured to land safely,
and I walked to the house of my kind friends Jonas and Ann Stott.

First-day morning attended Meath street meeting: my service in this meeting,
was to labour with those who had acted disorderly, not only to their own hurt,
but also that of the meeting,
by remaining in the meetinghouse yard in conversation
after the meeting should have been fully gathered,
and then coming into the house in a large body,
which I understood had long been a practice.
In the afternoon attended Sycamore-alley meeting, which was a large and favoured meeting.
At the close of it was held what is called their stop meeting,
allowing Friends of the city an opportunity of inquiry if any circumstance
has occurred since the last meeting that requires notice.
I presented my certificate,
and in much weakness and fear informed Friends of my apprehension of duty
to pay a visit to the families of members and attenders of meetings;
which being united with,
on second-day morning accompanied by John Smithson
I proceeded in this awfully important engagement.
Third-day attended Meath street meeting, a time of Divine favour,
which I believe will not soon wholly pass away from the remembrance of some of us.

Sixth-day attended Sycamore-alley meeting, in which an alarm was sounded to some,
who had been prevailed upon to give in their names
to follow the Lamb of God who takes away sin,
and had run well for a time, but from some cause had halted again,
and taken up a polluted rest, thus by their example becoming like the evil spies.
Seventh-day I was joined by Susannah Hill, a minister in good esteem with her friends,
whose company was cheering to my mind under this arduous engagement.
Third-day morning attended Meath street meeting, which to me was an exercising time.
My service was to labour with some whose attendance of week-day meetings was only occasional,
just sufficient to keep their credit pretty fair with their friends,
yet in Monthly Meetings manifested zeal to assist in preserving good order in the church;
and I had to give it as my firm belief,
the Lord`'s work never could prosper in the hands of such.

Sixth-day attended Sycamore-alley meeting,
which on our first sitting down was owned by the Master of all rightly gathered churches.
What a favour we should esteem it,
that he still condescends to dispense his heavenly blessings,
to give us bread in our own houses and water in our own cisterns,
that there may be no depending upon the instrument for help.
The care manifested by some Friends who were shopkeepers,
to receive the family visit free from interruption, by shutting up their shops,
I thought was worthy of notice.
Second-day, a difference having long existed between two Friends of this meeting,
I did not see my way clear to proceed further in our visit,
without making the attempt to bring these two individuals nearer together,
which through holy help was accomplished, to the great comfort of the parties.

Third-day attended Meath street meeting, which was large for a week-day meeting.
I felt called upon to press on the minds of those assembled a sense of the need,
if we were benefitted by our thus coming together,
of leaving our homes and outward concerns in faith and not in fear,
looking to that Almighty power to oversee them in our absence,
who is better able to do so than we are ourselves,
and not to allow the enemy of all our sure mercies to occupy
our minds with slavish fears of our outward concerns suffering,
when we are thus honestly endeavouring to be found in the
faithful discharge of this duty towards Almighty God.
Third-day attended Meath street meeting, a time of renewal of strength to many,
after which the Monthly Meeting occupied two long sittings:
it was pleasant to observe the care manifested on the part
of the active members of this large Monthly Meeting,
not superficially to hurry through the business that came before the meeting.

Fifth-day we were favoured to close our visit to the families in this city and neighbourhood,
under, I humbly hope,
a united feeling of gratitude to the great Author of every blessing,
who had thus mercifully carried us through.
Sixth-day attended Sycamore-alley meeting,
and made a visit to an establishment for the reception of the poor of all descriptions,
where every necessary of food,
bedding and clothing is furnished to such who are
disposed to avail themselves of the privilege;
doing great credit to this large populous city of Dublin.
My next visit was to the Foundling Hospital, where nearly one thousand children are fed,
clothed and educated:
an engraving on the front of a clock in one of the wards engaged my attention,
which was presented to this institution by lady Arabella Denny,
at a time when the infants were brought up by hand, and is nearly as follows:
"`Children who are brought up with spoon victuals require often and regular feeding.
This clock strikes every twenty minutes.
It is desired that every child that is then awake may be taken up and sufficiently fed.`"
We were informed,
that before the donor of this clock undertook the oversight of this institution,
it was in a very neglected state:
but her zeal in devoting her time and fortune to its welfare had been a great
means of producing the regularity and humane care now so conspicuous,
doing great credit to the present managers:
may her example availingly preach this language to those possessing the means,
"`Go you and do likewise.`"
The evening of their day would then afford them that peaceful reflection,
which would be more salutary to the mind than anything this world can afford.
