== Chapter VII.

Sixth-day left Ross for the Quarterly Meeting of Ulster, to be held at Lisburn;
reached Dublin this evening, about seventy-three Irish miles.
Leaving Ross under much bodily indisposition, from frequent and close exercise of mind,
this day`'s journey seemed almost too much for my nature:
had I yielded to the pleadings of flesh and blood,
I had not proceeded further at this time;
but giving way to the ease of the flesh I was fully
aware would introduce the mind into suffering,
harder to bear than bodily pain, produced by pursuing my prospects of religious duty.
Early on seventh-day morning I proceeded,
and reached Lisburn at a very late hour in the night.
Second-day sat with Friends in their Quarterly Meeting for discipline,
which was more stripped of its members,
through that unsoundness of principle that had crept into the Society,
than either of the others in this nation, and is small:
there appeared to me a hopeful prospect of some of
the young people coming forward in true usefulness;
the business of the meeting was conducted in much harmony.

Third-day attended the school-committee,
after which a parting meeting for worship was held to good satisfaction.
Fourth-day rode to Ballinderry, about five miles, to attend a meeting there,
appointed at my request.
I felt well satisfied in giving up to this service.
In the afternoon attended a meeting at Hillsborough,
where I sat down with a small company.

Fifth-day attended a meeting for Friends at Lisburn, in which,
to make use of some expressions of an aged minister before the meeting separated,
"`the golden sceptre was reached forth to the humbling of many minds.`"

In the afternoon rode to Belfast; reached in time for the meeting in the evening,
which is held in an out-building, there not being`' a meeting-house of Friends here,
most of the Friends of this meeting being new settlers.

Sixth-day rode to Mile Cross.
This meeting consists of one family and an aged man;
a considerable number of other people attended, who behaved well:
I hope it proved a profitable meeting.
Seventh-day, 11th of third month, rode to Antrim; had a meeting with Friends there,
and a few of the neighbours gave their attendance.
First-day morning walked about nine Irish miles to Lower Grange;
the road being good and the country well cultivated, with a fine view of Lough Neagh,
felt reviving to my nature, and helped me on my way.
As we approached the meeting-house, my guide pointed out several small farm-houses,
formerly occupied by Friends`' families,
though there is now but one family belonging to this meeting; in addition to this family,
a few attend the meeting, who stand disowned, and some young people,
the offspring of such; several of the neighbours gave us their company.
At the close of the meeting I felt it required of me to request
those who usually attend the meeting to keep their seats,
with whom I had an opportunity to the relief of my mind.

After taking refreshment, we walked about nineteen Irish miles to Ballinacree.
The meeting consists of part of two families.
I had been apprized of the situation of the family I was to quarter at.
The mistress of the house remained firm with Friends;
but I found on our arrival she was absent from home,
at which I felt not a little disappointed:
her husband was one of those who had quite discontinued
the attendance of the meetings of Friends,
and in consequence of unsoundness of principle,
had forfeited his membership in the Society,
although at one time he was considered a useful member.
He received me with every possible mark of kindness,
which continued during my stay with him: when I came down to breakfast next morning,
he told me he had sent a messenger two miles to inform his son, who was an apprentice,
and a woman, who had married out of the Society to a Roman Catholic,
of our intention of havins; a meeting that morning,
although no request had been made of him to do so.
Having dressed himself in his best clothes,
I concluded he intended to go with us to meeting, but was disappointed,
he went with me to the door of the meeting-house and returned into his own house again.
Not feeling it required of me to solicit his company, I went into the meetinghouse,
which was under the same roof as his dwelling: his son, the woman who had married out,
and some young women in the neighbourhood, and a few persons not professing with Friends,
composed our meeting.
I felt satisfied I had taken this journey on foot to sit with the few I met with here.

Turning into my quarters again, my landlord had provided a handsome dinner for me;
after partaking of which, I left.
He appeared to part with me respectfully;
and I felt it safest for me to pass over in silence
the conduct that had deprived him of his membership:
although I felt much on his account, it being evident the light had become darkness,
and that it was great indeed.
Not being able with clearness to see my way out of Antrim,
I proceeded again to that place; and by endeavouring to keep in the quiet,
my mind was brought under apprehensions of duty,
to call upon the members and attenders of the meeting.
On entering one house, I felt shut up as to conversation; silence took place,
which continued for some time:
my service was with an individual who had forfeited membership with Friends,
by being present at a marriage where the parties proceeded
contrary to the rules established by our Society.
From the humble and tender manner in which a sense of his misconduct was expressed,
and the loss that had been sustained thereby,
I held out the language of encouragement to seek
again with earnestness for the lost piece of silver.

Proceeded towards Lurgan.
We travelled about eleven miles to tea, and again went forward;
night closed in upon us very fast, yet I did not apprehend danger,
my guide telling me he had gone the road before,
and professed to be well acquainted with it.
On inquiring if we had any water to pass through,
he informed me we had no water all the way, and a straight turnpike-road to Lurgan.
We had gone only a few miles more,
when we turned short round a corner of the turnpike-road,
but my guide persisted in our being on the right road.
The night was now so dark we could scarcely see a yard before us,
and I became very uneasy.
On going about one mile on this road, I found our horse was stepping in water;
I left the car, and walked over a foot-bridge.
My guide still persisting we were on our right road, I mounted the car again;
but we had not gone much further before I was obliged to call out,
"`My feet are crushed against the sides of a bridge,
I will proceed no further this way,`" requesting my guide to return
to some houses we had passed and make the needful inquiry;
from which it appeared we had left our right road when we
turned round the corner of the turnpike.

Being now afraid to trust myself with my driver,
I concluded to walk behind the car the rest of our journey;
but I could not see to pick my way,
and the road was so rough I felt unable to proceed behind the car,
and yet was afraid to get in again.
While in this situation I thought I observed a level foot-path, and made towards it,
but it proved to be a ditch full of water, into which I plunged at my full length, which,
when I recovered my feet again, took me up to my middle.
I made my way out as well as I was able, wet, and wounded from the crush at the bridge,
every pocket appeared to be filled with water.
I now was so wet that I dare not ride, but proceeded behind the car:
before we reached Lurgan on a sudden I was again plunged at full length
in a stream of water that came from a mill-race which ran across the road.
The assurance that we were now near our port cheered me.
In this maimed,
comfortless condition I reached the house of my kind friend Thomas Haughton,
about ten o`'clock at night, by whose great care I suffered but little from getting wet,
but my bruises made it needful for me to take to my stick.
On relating our situation at the bridge,
we were informed that we were in imminent danger if we had proceeded,
of plunging into a gut of Lough Neagh, fourteen feet deep.

14th of third month, attended the usual meeting at Lurgan:
in the evening rode to Moyallen, and attended an appointed one there;
the house was pretty full.
This to me was the most trying meeting I have sat since I came on this side of the water;
it was hard work to obtain relief,
yet I hope I may say I was enabled to acquit myself faithfully.
Sixth-day rode to Richill to attend an appointed meeting there, which was large;
it proved an exercising meeting, yet to me a relieving one.

Seventh-day attended Charlemont Monthly Meeting, held at Upper Grange.
The destroyer has made sore work in this meeting, through unsound principles,
dividing in Jacob and scattering in Israel.
I was led to warn the youth, of whom there was a considerable number present,
to be careful they did not contract habits of intimacy
with those who had imbibed unsound principles,
as they must expect to suffer loss in the best things if they did.
The business of the Monthly Meeting was agreeably conducted.
First-day attended meeting here:
I had many invitations to the houses of those who had seceded,
who were present at the meeting; but it appeared safest for me to keep to my quarters,
lest my example should encourage the young people to go astray.

Third-day had a meeting at Coot-hill;
fears were excited in my mind that the standard of Truth was suffered almost,
if not wholly,
to fall to the ground by those who were in membership with our religious Society here.
Fourth-day reached Rathfriland, and had a meeting with Friends this afternoon:
two families make up this meeting.
Fifth-day rode to Richill, and attended the Monthly Meeting there, which was large,
but little business came before it; in transacting which,
a more lively zeal for the right support of the discipline appeared to be lacking.

First-day attended meeting at Mountmelick,
where a great number of young people were present.
I was led to fear my unfaithfulness this morning had blocked up the way of others,
whereby the meeting had been hurt;
a sense of which so operated on my mind in the afternoon meeting,
that I could not rise above it, and therefore brought a burden away with me again.
In a religious opportunity I was favoured with strength
to obtain a little relief to my suffering mind.

Second-day attended the Quarterly Meeting for discipline,
which was a time of Divine favour; adjourned to third-day morning,
and closed under a continuation of the same blessed covering.
In the evening was a parting meeting, which was largely attended,
Friends patiently continuing to the end, which indeed crowned all,
parting from each other under a grateful sense,
that as a people we were not forsaken by Him who has bread
enough and to spare for the truly hungry soul.
Fourth-day attended the usual meeting, which was also large.
Friends here being in the practice of pretty generally shutting
up their shops to attend their mid-week meeting.

Having a prospect of visiting the families of Moate and Ballymurry meeting,
and mentioning the subject to my kind friend Ann Shannon,
it appeared that she also was under a similar concern;
and when the meeting closed we spread our concern before Friends,
which being united with, in the afternoon we proceeded to Tullamore,
about eleven Irish miles, where two families reside;
we felt much for the young people so far removed from the society of Friends.
Fifth-day proceeded to Moate, about eleven Irish miles: soon after our arrival,
we requested the company of such suitable Friends of the meeting as could come together,
to whom we proposed a visit to the families of members of their meeting,
which being united with, we proceeded this evening,
and first-day closed our service here.

Second-day morning we rode to Athlone, sat with the two families there,
and then to Roscommon, taking Friends`' families in our way.
Third-day attended an appointed meeting at Ballymurry, which was large;
after which we sat with the families there.
In the afternoon proceeded to Hall, sat with a family there and lodged.
Fourth-day returned to Moate, and attended their Monthly Meeting:
the meeting for worship was owned by the great Master,
and that for business was also a time in which best help was near.
After this meeting we rode to Tullamore, where we separated,
my companion returning to her own home and myself proceeding by boat to Dublin,
where I arrived safely in the evening.

Seventh-day proceeded to Lurgan, and on first-day attended meeting there.
No afternoon meeting being held, although many Friends live in the town,
felt to me trying;
and believing it safest for me to request Friends should be called together,
a meeting was accordingly held in the evening;
and I was satisfied in having yielded to this pointing of duty.

12th of fourth month, attended Monthly Meeting at Ballinderry, and on the 14th,
the Monthly Meeting at Moyallen, which was small.
Society concerns here are at a low ebb,
yet it was evident to the humbling of some of our minds,
that the great and good Husbandman was near to help,
if there was but a willingness to accept thereof.
17th, rode to Richill, and attended Monthly Meeting there:
the meeting for worship was considered a favoured time;
and that for discipline was agreeably conducted; after which I rode to Newry.
Sixth-day evening, reached Dublin.

This evening proceeded to Waterford, and reached it on seventh-day afternoon,
about one hundred and thirty Irish miles.
Friends appeared glad to see me once more among them, which feeling was mutual.
First-day attended the usual meetings.
Sixth-day rode to Anner Mills.
Seventh-day walked to Clonmel: on my entering the suburbs sadness covered my mind,
feeling the bubbling up of a concern which for some
weeks past has at times been my companion.
Attended the select Quarterly Meeting:
the business of which was conducted with much solid deliberation,
and in the evening the school committee;
the care manifested for the rising generation was encouraging.

First-day attended the two meetings for worship; in the morning,
matter flowed freely through several rightly qualified instruments,
tending to inform the seeking mind, confirm the doubting,
and encourage the willing-hearted.
I left the afternoon meeting sad from a sense of unfaithfulness,
by allowing the right time for delivering what I had given me for the people to pass by,
on which account my way afterwards became quite closed up:
when shall I learn more perfect well-timed obedience?--will
my sufferings never teach me this necessary lesson?
Second-day morning the meeting for business commenced, and closed on third-day;
during the several sittings the overshadowing of the Father`'s love was evidently felt,
whereby the hearts of many were contrited,
causing expressions of gratitude sweetly to flow before we separated.

Left Clonmel after the Quarterly Meeting; reached Dublin on sixth-day,
in time to attend the committee appointed by the Yearly
Meeting to revise the rules of the Society in this nation.
I considered it a privilege to be present at the several sittings of this committee,
to hear read over the minutes of our early Friends,
in which a care was so manifest that the camp should be
preserved clean from everything of a contaminating nature,
and also to observe a revival of this concern in
those who took an active part in this committee.

Seventh-day, 29th of fourth month, attended the select Yearly Meeting,
which now consists only of the select Quarterly Meetings of Munster and Leinster,
that of Ulster being dissolved during the sorrowful
religious rebellion that raged so much in this province.
The meeting was well attended,
and many of our hearts were contrited before the Lord under a fresh sense of his mercy,
in that we have not been forgotten by him.
First-day attended Meathstreet meeting in the morning: in the afternoon Sycamore-alley,
in which, if my feelings were correct, encouragement was handed out to the faithful,
both immediately and instrumentally.
Second-day morning attended the first sitting of the Yearly Meeting,
which was considered larger than usual: its concerns were conducted with unanimity,
and evident proofs that a desire for the best welfare of the Society was kept in view:
it closed on fourth-day, the 10th of the fifth month.

Fifth-day rode to Rathangan, attended Monthly Meeting there, and proceeded to Mountmelick.
Sixth-day, at my request, Friends of the meeting were called together,
before whom I spread a prospect of visiting the members and attenders oi`" their meeting,
which being united with,
and my late companion having the concurrence of her friends to proceed in a like visit,
we unitedly entered upon it on seventh-day.
Third-day was the Youths`' meeting, the first that had been held in this place;
it proved a solid and instructive season, and if properly kept up,
I doubt not but these meetings will have their service.

Fourth-day attended the Monthly Meeting,
which is composed of several particular meetings; much business came before it,
and my mind was comforted under a belief that an increase of concern was prevalent,
that the wholesome discipline established among us might be properly maintained.
Seventh-day we rode out of town and visited one family,
which closed our visit to families in this meeting.

First-day attended morning meeting, which proved a favoured parting opportunity.
In the afternoon rode about eight miles to Mountrath, to attend a meeting this evening;
many of the town`'s people gave their attendance: to me it was a trying meeting;
the harp being hung on the willows, no precious song of Zion could be proclaimed.
Fourth-day attended the mid-week meeting at Edenderry, where,
after deep wading I was favoured to obtain relief.

Fifth-day, accompanied by my friend William Neale, proceeded to Moyallen,
which place we reached on sixth-day evening.
Seventh-day entered upon a visit to the families of members and attenders of this meeting.
First-day attended the two meetings there.
In the morning meeting my unfaithfulness reproved me.
What a mercy it is to such erring, straying,
poor mortals as I have cause to subscribe myself, to have this good Monitor following us,
and that he is faithful in executing judgment where needful!
Second-day the Quarterly Meeting for this province commenced,
the business of which was conducted in much harmony; a favour at all times,
but especially to the Friends of this meeting,
it having been sorrowfully otherwise with them when tried with
those contentious spirits they had to bear with a few years past.
Sixth-day we were favoured to accomplish our visit,
being helped to come to a satisfactory close, having visited, we were told,
all in the neighbourhood who had not wholly deserted the meetings of Friends.

Seventh-day we proceeded towards Lurgan,
feeling drawings in my mind to make a visit to a man and woman who, among others,
had separated themselves from the Society several years ago.
We went to their house, had a religious opportunity with them;
and at our parting they appeared loving, acknowledging they took our visit kind:
having been enabled to clear my mind towards them, I felt truly thankful.
Taking a circuitous route to Rhone-hill to call on two young people,
similarly circumstanced with the former,
on our entering their abode they received us kindly,
and without any apparent opposition to what was offered to them;
yet the language formerly uttered forcibly impressed my mind at our parting,
"`There is no hope.`"
We reached our kind friend Thomas Greer`'s this evening,
and proposed a visit to the families of members and attenders of Grange meeting,
which being united with, we proceeded therein.
First-day morning, the meeting was large, but a time of deep inward exercise.
I felt under difficulty in opening my mouth, from a sense given me,
there were those present who might be compared to
evil spies to catch at what might be offered,
and make a handle of it to uphold their own unsoundness of principle,
but I was favoured with strength to leave the burden of the word given me, among them,
in which I found peace.
Fourth-day attended the midweek meeting, after which their Preparative meeting was held.

Sixth-day rode out to Cabra, about eight miles; had three sittings,
two of which were with large families; some of the youth appeared hopeful.
Returned to Dungannon; took three sittings on our way: rising early,
having numerous sittings, and keeping at it till late, I became nearly exhausted;
but if all does but close peacefully it will prove an ample reward.
This day being favoured with a comfortable account of my family,
I have cause to say with thankfulness,
it operated as a spur to my endeavours to do my Divine Master`'s work with diligence,
who is so mercifully caring for mine at home.
Seventh-day attended Monthly Meeting here:
the business appeared to be conducted under a good degree
of concern for the right ordering of the discipline,
and the meeting closed under a precious sense of the overshadowing of Divine regard.

In the evening we made two visits,
the first to a considerable number of young people
who are in the practice of attending Friends`' meetings;
the last sitting was with a family,
the heads of which had separated from Friends and attend the meeting of Separatists,
held at Dungannon; but the children continue to attend the meeting of Friends.
Believing it would accord most with my feelings,
that no message should be sent to this family,
but that I should go in the evening with the Friends who were to accompany me,
and propose the visit to the heads of the family myself;
we accordingly proceeded to the house: the man opened the door for us,
and at first looked rather coolly upon us.
I told him what had brought me to his house,
on which he readily consented to collect his wife and children,
and sit down with us himself.
My service was principally directed to the parents,
which we had good ground to believe was well received.
The man, walking with us towards my quarters, acknowledged that he took the visit kind,
believing it was well intended.
This day closed with a heart filled with thanksgiving and praise,
in that the opposing spirit in every opportunity we have yet had, where such has been,
has bowed to that all-controlling Power who is alone sufficient to bring it into subjection.

First-day morning was a solemn parting meeting with most present;
many of the young people were melted into tears, which affected my mind not a little,
hoping I had obtained a place in some of theirs;
it was a season that will not soon be forgotten by me.
Second-day, closed this arduous engagement.

In the afternoon we left my kind friend Thomas Greer`'s, and went to Richill,
where sadness was again my clothing,
from a belief it would be unsafe for me to quit this neighbourhood
without attempting an interview with an individual,
on whose account my mind had at times been brought under exercise,
he having separated himself from Friends.
I formed an acquaintance with him in years past, when he attended London Yearly Meeting,
and travelled in the work of the ministry in England, to the satisfaction of Friends.
We left our quarters early on third-day morning,
and reached his residence in time to see him.
On his entering the room where we were,
I told him I was come to breakfast with him unasked:
his countenance told me I was an unwelcome guest; but I was, in adorable mercy,
kept above discouragement,
although he manifested the greatest unwillingness to enter into conversation with me;
but by endeavouring to do my best in unburdening my mind,
I was strengthened to declare what appeared to be
the counsel of my Divine Master respecting him,
and constrained to put the query to him,
why it was that the gift in the ministry which he once exercised acceptably,
was either lying dormant or had been taken away from him;
earnestly entreating him to be willing to search into the cause hereof.
He said there was no openness in the minds of the people to receive what he had to offer.
I earnestly entreated him to consider well if he had not blocked up his
own way in the minds of those who once gladly received his ministry;
if so he must expect, unless a place of true repentance was mercifully granted him,
the consequences with respect to himself would be dreadful in a future day,
warning him against persisting to make the way difficult
for his children to get to the meetings of Friends:
one of his sons, a hopeful young man, proposed going a few miles with us,
but to this the father objected.

Third-day, travelling over the mountains to Dundalk,
afforded me an opportunity to turn over some leaves of my time for a few weeks past,
which furnished fresh cause for humble thankfulness
in that I had been so cared for by Him,
without whose permission a sparrow falls not to the ground.
Recurring to the embarrassment I was introduced into during,
and at the close of the Yearly Meeting;
through some injudicious observations from some members
of society in my native land reaching me,
stating it was considered time for me to return,
I esteemed it a great mercy that I was preserved from so doing,
as in all probability I should have done had I been left to myself,
and thereby taken a burden home with me, hard to bear,
although wilful disobedience might not have attached to me.
Fifth-day proceeded to Enniscorthy,
and on seventh-day attended the select Quarterly Meeting there.

We were favoured with a comfortable sitting together.
At this meeting I gave Friends an account of some
of my proceedings since the Yearly Meeting,
with the outline of my future prospects of religious service in this land,
entreating them to be willing to enter into my situation and to
express their feelings as to my proceeding further or not,
being quite resigned to return home if it was the mind of the meeting I should do so.
Friends were united in judgment,
it was right to leave me at liberty to pursue my
prospects of religious duty among them,
and I was enabled to take fresh courage to proceed as Truth opened the way.

In the evening attended the Provincial school committee,
in which I was comforted to observe the care manifested for the welfare of the children.
First-day, the meeting this morning was largely attended;
in which I believe many were favoured,
not only to see the need of renewing their covenants,
but also experienced ability in mercy given to do so.
May they be confirmed by sacrifice, is what I earnestly desired for myself,
and all who were so wise as to join in with these
offers of Divine help thus in mercy extended.
The afternoon meeting was attended by many of the town`'s people,
and held long in silence; towards the close some offerings were made:
the meeting separated much in the quiet,
and under a humbling sense of the fresh extension of Divine regard to us.
Second-day morning the Quarterly Meeting for discipline commenced,
at which we had a numerous company of young people of both sexes.
Holy help being mercifully vouchsafed,
the minds of many were introduced into a right exercise for the support
of the discipline established among us in the ordering of Divine wisdom:
the meeting closed under a grateful sense hereof.
After the close of the meeting, I requested some Friends of Dublin to stop,
before whom I spread the situation of the meetings of Upper Grange,
Richill and Ballinderry, relative to Friends`' books,
there appearing a lack of them in these meetings,
to lend to such members and attenders of meeting
who were not of ability to purchase for themselves.

Fifth-day, 29th of sixth month, attended the usual meeting at Waterford,
in which the Divine presence being mercifully near,
prepared the minds of those who were called to take an active part in the Monthly Meeting,
which succeeded this meeting,
whereby the several matters that came before it were conducted in true religious harmony;
although as respected myself, through a fear of saying too much,
I left the meeting under a sense of condemnation.

First-day the usual meetings to me were trying parting opportunities.
Second-day evening I went on board a packet bound for Milford-haven,
weighed anchor about ten o`'clock, and after a very boisterous passage,
was favoured to reach Milford-haven the next day at noon.
Fourth-day attended the Monthly Meeting there, which was very small,
after which walked to Haverfordwest, about eight miles, and next day to Carmarthen.
In consequence of rain, the roads were very deep and miry in places,
which made it difficult getting along;
yet feeling most easy to pursue this mode of travelling, by seeking for Divine support,
my trials were rendered less difficult than otherwise would have been the case.

First-day attended meeting at Swansea, which was small;
yet I felt comforted in sitting with these few, under a consoling hope,
that a good degree of a right concern was maintained for the support of Truth`'s testimonies.
In the afternoon rode to Neath, and attended the evening meeting,
where I found a few well-concerned members of our religious Society.

Third-day walked to Pontypool, and attended the Monthly Meeting there,
consisting of five men.
The little business that came before the meeting was agreeably conducted:
I felt well satisfied my lot was cast with Friends here.
Late this evening, the 14th of seventh month, I was favoured to reach Bristol safely,
having walked about thirty-four miles.
Sixth-day, I reached my own home, where I was favoured to find all things well;
for which blessing may I never fail to render to the Lord his due,
unreserved obedience and praise.

1810+++.+++ At the Monthly Meeting in the second month,
I informed my friends of an apprehension of further service in Ireland,
on which account a certificate was ordered to be produced at the next Monthly Meeting:
this prospect of duty being thus far disposed of,
I apprehended it was right for me also to inform
my friends of a religious prospect with which,
for several years, I had been exercised, of a yet more trying and humiliating nature,
namely: paying a visit to New South Wales;
the performance of which I viewed at a distance,
but believed the time was come for me to inform my friends; as I could not doubt,
from the feelings of my mind when the subject was brought before me,
there was an individual or individuals under a similar concern;
and that if they faithfully gave up to the service
I should be provided with a companion in the engagement,
never having been able to see that it would be required of me to proceed alone.

At the Quarterly Meeting in the third month I opened my prospect of visiting Ireland.
The meeting liberating me, on the 29th of the third month,
I again left my dear wife and family in the Lord`'s keeping,
in company with my dear friend, Benjamin White, of Buckingham Monthly Meeting,
Pennsylvania, then on a religious visit to these nations.
We left London this evening by coach for Holyhead.

At Stoken Church our coachman covered up his lamps
to prevent a coachman behind us seeing where he was,
that he might not pass us: the night being very dark,
his left wheel ran upon a high bank, whereby we were nearly upset.
When a few miles from Holyhead, to avoid a rugged part of the road usually travelled,
which had been newly repaired, he took a by-road on the sand.
The tide being then flowing, we became set fast in a deep miry place: our horses,
in attempting to extricate us from our difficulty, broke their tackle, and became unruly.
One of the passengers, a very tall, stout man, took us on his back and landed us safely,
with our luggage, on a high sand-bank, surrounded by the tide, and which,
it was more than probable, would soon be covered over when the tide was at its height,
we therefore resolved to make our escape on foot, frequently wading through water,
not without considerable anxiety for our safety,
lest we ourselves should get into a quag; but we were favoured to reach the inn safe,
although very wet.

Seventh-day afternoon we went on board the packet
with flattering prospects of a short passage,
but were disappointed, not reaching Dublin until second-day morning,
much worn with fatigue;
yet I trust the retrospect will not fail to produce
thankfulness for our merciful escape from danger.
Third day attended Meath-street meeting, in which my companion was largely engaged;
expressing a few words myself, I was relieved.
At the breaking up of the meeting,
Friends manifested satisfaction at seeing me once more among them,
and I considered it a favour that I had left an open door.
This evening my companion and myself separated, he remained at Dublin,
and I left by coach for Clonmel, and reached Anner Mills, on fourth-day afternoon.

Fifth-day attended an adjournment of the Monthly Meeting at Clonmel,
in which I opened my prospect to visit the drinking-houses in that town and its neighbourhood;
which, after obtaining much solid consideration,
was referred to the members of the select meeting, who, after mature deliberation,
set me at liberty to pursue my prospect; Isaac Jacob, a beloved brother,
in the station of an elder, giving up to accompany me.
My poor body needing recruiting before I entered on this arduous engagement,
I concluded not to proceed until second-day.
First-day morning attended meeting here, in which our holy Redeemer,
in adorable mercy condescended to fulfill his gracious promise, which,
when mercifully vouchsafed to the truly devoted mind, is enough!
The afternoon meeting was a season in which cause for encouragement
to persevere in the right way of the Lord was evidently to be felt.
Second-day morning, having passed a sleepless night, enfeebling both to body and mind,
I felt in my own apprehension unequal to encounter the day`'s work before me,
but by looking to that Almighty Power who has promised to be strength in weakness,
encouragement was received to make the attempt.
When my kind companion arrived at my quarters for us to proceed,
the sight of him almost upset me, but being sensible that nothing short of a quiet,
cheerful submission on my part to the humiliating task before me would effect my acquittal,
we moved towards the bridge.
Our first visit proved open and satisfactory, as was the case throughout the day,
during which we were enabled to pay thirty visits; I say enabled,
for nothing short of Divine interference could thus have
made way for us in the minds of those we sat with.

Third-day we accomplished twenty-nine visits;
what was communicated appeared to be kindly, and in some instances, gratefully received.
At one place the head of the family pressed me to accept of two half-crown pieces,
saying, she offered it as a mark of her gratitude,
and manifested disappointment at its being refused.
It appearing to us better that no previous information of
our intention should be given to the parties to be visited,
their outward matters were not generally so arranged
as to allow of much time being spent in a pause;
it felt the more necessary to have the eye of the mind kept single,
and the bent of it continually directed to Him, from whom only help can come,
to minister in due time to the states of those we are called to labour with.
Frequent interruptions also occurred from the calls of customers;
these suspensions in the midst of a communication would have been very trying,
unless the all-supporting arm of Omnipotence was steadily relied on.

Fourth-day,
this visit closed under feelings of reverent thankfulness
that we had been mercifully cared for.
My companion used often to say,
it seemed as if the Good Master went into the houses before us to prepare the way,
in which sentiment I could heartily unite.
Such were the feelings of solemnity we met with on entering the houses,
and when sitting with the keepers of them and their customers,
that at times it seemed much like paying a family visit among Friends.
We next paid a visit to the mayor, who received us kindly,
heard my remarks with attention,
and expressed his desire to promote the work I had been engaged in:
fresh cause to seek for a disposition to set up the Ebenezer,
by abiding in that state in which the creature is abased and prostrated as into the dust.

Fifth-day attended an adjournment of the Monthly Meeting,
at which I gave in a report of my proceedings.
I began to feel like a vessel that had been unladen of a heavy cargo,
but accompanied with this caution, to take care to keep the ballast in the vessel,
as a vessel without ballast is in danger of being
upset by every wind it may have to contend with.
I humbly hope I may say I was made truly thankful for this
proof that the good Remembrancer was near.

Sixth-day morning I left Anner Mills, and proceeded towards the Ninemile House:
our first stopping place was Kilcash; and on our alighting,
we were informed the landlord and his wife were in bed;
as we had no intention of spending money in their house,
calling them up appeared trying to me.
I endeavoured to proceed on our way, but I became sensible this would not make for peace,
so I ventured to have the keepers of the house called, and after waiting a short time,
they gave us their company.
They manifested an agreeable disposition and willingness to receive what was communicated,
and acknowledged in a feeling manner their sense
of the necessity of attending to what had been said,
and their thankfulness that they had not been passed by.
We proceeded about two miles further and made a halt again:
from the appearance of the man of the house I anticipated some difficulty,
but by keeping in the patience, the way gradually opened to obtain relief,
and the man appeared well satisfied, saying,
his own bishop could not have advised him more fully to the purpose.
We next stopped at the Nine-mile House, kept by a widow,
whose husband had been murdered a few weeks ago near his own dwelling.
We felt much for her in this trying situation, and, I trust,
were enabled to administer suitable counsel, for which she appeared thankful.
After sitting with another family, my service in this way ceased for the present.
We proceeded to Waterford; the sun broke forth brilliantly; the herbage was beautiful;
the views picturesque; all nature serene, and my mind relieved from a load of exercise.
I do not know when I have been more capable of enjoying
the wonderful works of the outward creation.
We reached Waterford in the evening, having travelled about thirty-six Irish miles.

Seventh-day I made a few calls on my friends,
but I found it needful to restrain my inclination in making these social visits,
believing they do not always tend to our own benefit or that of those we call upon,
through too easily promoting ourselves, or joining others in,
conversation of a very trifling, and consequently unprofitable nature,
instead of that retirement of mind,
that quietness and confidence in which our strength lies for the
faithful discharge of every good word and work.

First-day attended the morning meeting here,
at the close of which I produced my certificate,
and opened a prospect of visiting the drinking-houses at Kilkenny and Gallon.
After solid deliberation, I was left at liberty to pursue my apprehensions of duty,
and four Friends were nominated to assist me in the prosecution of this arduous engagement.
The afternoon meeting was large, and I trust a time of Divine favour;
at the close of which I parted from many I dearly loved in this city,
expecting never more to meet them in mutability.

On retiring to bed, the weight of what I had in prospect at Kilkenny and Gallon,
so overwhelmed me that I slept but little,
and rose next morning under such a feeling of bodily debility,
that had nature been permitted to take the rule,
I was prepared to plead to be excused from the bitter cup in prospect; but,
through adorable mercy, my head was borne above all discouragements of mind and body,
and after a solid opportunity with some Friends who came to take their leave of me,
accompanied by my very kind friends Thomas White, Joseph Jacob, Thomas Gootch,
and William Blain, we reached Kilkenny in the afternoon,
and took up our abode at an inn there.
We met with my kind friend William Neale, from near Mountrath, who was helpful to us.
After taking refreshment, we had two sittings, and then returned to our quarters;
it being evident that the morning was the best time to find the houses quiet,
and to obtain the attention of the keepers.
Being informed that the bulk of the inhabitants were Roman Catholics, and that Friends,
a few years ago, when passing through the streets of Kilkenny,
were subjected to great insult; added to my sufferings of mind,
but rather prepared me for meeting with opposition in the discharge of duty.

Third-day morning early we proceeded,
sometimes confining the visit to the keepers of the house,
and at other times sitting with the company who were drinking.
From the bigotry and superstition which prevailed in this town,
I marvelled not at my suffering when looking at Kilkenny; some telling us this day,
they were bound by their father confessor not to hear any one but him,
which they were determined to abide by: in other places we were kindly received;
and some of the opportunities abundantly compensated
for all the difficulties we had to pass through,
which were not trifling; the rude people following us,
hooting and acting as if they would have done us mischief.

Fourth-day morning we turned out again on our embassy,
and on entering the house we first visited,
my mind was under so great a load of depression,
that if I dared to have made my escape I would gladly have done it;
but the result of this visit afresh confirmed me,
how frequently we make suffering for ourselves through the lack of a more steady
reliance on that Almighty Power who has the hearts of all men at his command.
We sat down with the man of the house, who received us kindly,
and gave me a full opportunity,
and at our parting manifested satisfaction with what had been communicated.
The visits this day were mostly of this description;
much openness to receive what was offered.
At one place out of the city, a man was very opposing,
but I was enabled to relieve my mind towards him.
We also had an opportunity with some soldiers and others,
who appeared attentive to what was offered, and manifested kindness towards us.
After making thirty-five visits this day, our service at Kilkenny closed.
Our being made a gazing-stock in passing through the streets,
was an occasion often to recur to the caution,
to take care to keep ballast in the vessel.

Fifth-day morning we moved towards Gallon; and called at the houses on our way there.
We had not proceeded far before we were informed the priest had
been trying to prejudice the minds of the people against us,
and to prevent our being received, in consequence of which, some houses were shut,
and where the doors were not closed against us,
there appeared but little disposition to hear.
Sometimes I felt easy to pass them by, and at other times,
after quietly hearing their reasons for refusing to sit down with us,
if matter arose in my mind which I dare not take away with me, I offered it:
in some instances where refusals were given, their minds were so wrought upon,
that at parting they appeared satisfied,
acknowledging they believed our intentions were very good.
The crowd of people that gathered round us was very interrupting,
and they behaved in an uncivilized manner; yet my mind was preserved quiet,
feeling the necessity of letting them see that my dependence was
placed on the supreme all-powerful Preserver of the universe.
About twenty sittings closed our service at Gallon.

I cannot doubt, but that amidst all the consternation the town was in,
that which was communicated in some places would be as bread cast upon the waters,
found many days hence.
A respectable looking young man followed us into one of the houses,
and was particularly addressed: I could not but believe he felt it a time of visitation.
On reaching our inn, I was introduced into fresh exercise,
from an apprehension that I must be willing to return to Kilkenny,
and attempt to obtain an interview with the Roman Gatholic bishop.
I proposed to my companions our sitting down quietly together before we separated,
without disclosing to them the exercise of my mind: and it still pressing upon me,
I informed my kind companions of it, which I thought I observed tried their minds.
I therefore felt at liberty to say,
if they were willing to take my concern upon themselves,
I believed I could safely leave it there; but this they feared to do,
and we therefore returned to Kilkenny.
Believing it to be right for me to propose to my
companions to go with them to the bishop`'s house,
and endeavour to make my own way towards obtaining an interview;
we proceeded accordingly, but were informed the bishop was at dinner,
and would not be at liberty till five o`'clock.
I requested the servant to say,
that a Friend from England was desirous of speaking to him,
and that we meant to return at the time proposed.

On our arrival at the house again, we were ordered up-stairs,
where the bishop received us with great civility, ushered us into a room,
brought me a chair, placing it opposite to a sofa on which he took his seat.
My companions, Thomas White and Thomas Gootch, taking seats also,
we dropped into silence, which I broke by saying,
a visit had been paid to the drinking-houses in Kilkenny,
which I supposed he had been acquainted with, to which he replied, "`Well.`"
I observed that in performing this visit my fears, and the various reports I had heard,
were fully confirmed,
that the laity profess to believe the clergy have full power to forgive their sins,
adding, the people may be so deceived as to believe the priest has this power;
but that I did not believe it possible the clergy could believe it themselves;
and therefore as their superior, to whom the people were taught to look up for counsel,
I desired he would seek to the Almighty for help, and as he valued his own precious soul,
as ability was afforded him,
endeavour to turn the minds of the people from man unto God and Christ Jesus,
who only can forgive sins:
otherwise he would incur a load of condemnation too
heavy for him to bear in the great day of account,
when the deceiver and deceived would be all one in the sight of God,
whether actively or passively deceiving the people.
That at times when considering the subject,
it was my belief that if the Almighty had one vial of wrath more powerful than another,
it would be poured out upon those who thus deceived the people.
Here I closed for the present: he manifested great confusion, shutting his eyes,
as not being able to look me in the face.
A pause ensued, and after awhile he requested leave to say something, to which I replied,
he had heard me without interruption, and I was willing to hear him in like manner.
He began by saying, it was very indecorous and unchristian in me to come to his house,
a stranger to him and from another land, and address him in such a manner, charging him,
who was a man of so much experience in the church of God, with being a deceiver, saying,
surely I must be mistaken.
I told him it was in love to his soul, and under an apprehension of religious duty.
He called upon me to produce my authority for my mission;
I told him my authority was in my own breast: he said, conversion was a great work,
and he was not to be converted all at once.
I queried with him, "`Are not the people thus deceived?
do they not believe the clergy have power to forgive their sins?
are you endeavouring to undeceive them,
for the clergy cannot be so deceived as to believe this power is vested in them;`"
exhorting him to be willing to cooperate with that Divine help which,
if rightly sought after by him, would be extended,
whereby ability would be received to undeceive the people; again reminding him,
that the deceiver and deceived were all one in the sight of God;
and that it continued my firm belief,
if the Almighty had one vial of his wrath more powerful than another,
it would be poured out on those who thus deceived the people,
whether actively or passively engaged therein.
He said he believed I meant well, and that he commended my principles,
but he could not say he thanked me for my visit.
I expected at times he would have turned me out of the room.
We rose from our seats to take our leave, when the bishop clasped my hand,
and holding it, paused, saying, "`I believe I may say,
I feel thankful for it;`" doubtless meaning the visit;
requesting us to take some refreshment, he kindly conducted us to the stairs again,
and we parted, never more to meet on this side eternity; for I received an account,
about twelve months after this visit, of his removal by death.

We returned to our inn rejoicing; I under a sense of faithfulness,
in cooperating with the help mercifully vouchsafed to deliver
what to me appeared to be the whole counsel of my Divine Master,
and my companions, that I was helped to get through to my own relief.
Sixth-day morning we called upon a magistrate, who had kindly offered his assistance,
should it be found necessary:
he expressed in an agreeable manner his approval of our movement, adding,
that he had been with some of those we had visited,
who manifested a desire to be more careful in future in the sale of spirits, saying,
it only remained now for the magistrates to do their part,
in which he hoped they should not be deficient,
and that he desired to be helpful to Friends at any future time.
We also made a call upon the mayor, who had likewise offered his assistance;
he also expressed his satisfaction at our proceeding
and his desire it might have its use.
My mind had looked towards a public meeting,
but not feeling it to press sufficiently upon me to justify the attempt,
we proceeded to Ballitore this afternoon.
Seventh-day, reached Dublin.

First-day morning attended Meath-street meeting, which was large.
The language of encouragement was held out to the faithful,
but an alarm sounded in a particular manner to those who were negligent
in their duty of attending our religious meetings.
The afternoon meeting at Sycamore-alley was well attended,
and owned by the great Master`'s presence.
In the evening had a religious opportunity in a Friend`'s family:
may I never be the means of putting by opportunities like these,
where way is made for them by Him whose presence alone animates
and quickens the mind to every good word and work.

Second-day, 23rd of fourth month,
attended the committee appointed to revise the minutes for
the intended Book of Discipline for Friends in this nation,
which continued its sittings until sixth-day: to me it proved an interesting time;
the care manifested for the preservation of the wholesome
discipline established among us,
in all its parts, was great.
Seventh-day attended the select Yearly Meeting, where I again met Benjamin White,
also Robert Fowler and John Abbot from England.

First-day, 29th of fourth month.
Sycamore-alley meeting in the morning was largely
attended by Friends from different parts of the nation,
and proved a memorable time.
Care being taken to clear the court of those who had long been in the
habit of standing in conversation after the meeting should be gathered;
it early settled down in quiet.
The afternoon meeting at Sycamore-alley was also a season of Divine favour,
calling for an increase of thankfulness.
At our quarters in the evening was a large company of Friends, chiefly young people,
and in a religious opportunity Benjamin White was largely
engaged in holding out the language of encouragement.
May it be properly remembered by fruits of faithfulness manifesting themselves;
if this should not be the case,
seeing the language cannot be more applicable to
any society of professing Christians than to us,
"`You have I known above all the families of the earth,`" must we not
expect the subsequent part of the verse will also be fulfilled,
"`I will punish you for all your transgressions.`"

Second-day, 30th of fourth month.
The Yearly Meeting for Discipline commenced its sittings
under the overshadowing of Divine regard.
Third-day attended the usual meeting for religious worship;
a season of encouragement to the youth; and to their superiors in age,
who were settled on their lees, a time of awful warning.
Sixth-day attended the usual meeting for worship, in which,
Benjamin White had good service: being too hasty in taking my seat,
I did not obtain full relief.
When shall I learn more entire dependence on that Almighty power, who,
when he puts forth, goes before,
and never will leave or forsake so long as we confide in him.

First-day the meetings at Sycamore-alley were largely attended;
a number of persons of other societies giving their company.
Second-day evening attended the closing sitting of the joint committee,
which I doubt not to many was like a feast of fat things,
under a sense whereof high praises ascended to the Great Author of these renewed blessings.
Third-day the Yearly Meeting closed as it commenced,
under a grateful sense that Divine regard continued to be with us to the end;
after which was held a parting meeting.
Fourth-day evening, Benjamin White, Robert Fowler, Robert Eaton,
Elizabeth Clibborn and myself, went on board the packet for Holyhead,
and I was favoured to reach my own home in safety, where I found all well.
