== Chapter IX.

First-day morning attended Meath-street meeting, which was large,
and closed under a humbling sense that Divine mercy had been near to us,
owning our assembling together.
In the afternoon attended Sycamore-alley meeting,
at the close of which the usual stop meeting took place.
Feeling the subject of a visit to the drinking-houses in this large
city and suburbs to press upon me with increased weight,
I spread my prospect before this meeting,
requesting my friends to endeavour after a right judgment,
and to keep every discouraging consideration out of sight:
the meeting appeared to be introduced into close exercise.
No obstruction arising,
the further care was referred to the elders and overseers
and a few Friends nominated for that purpose.
Second-day morning met the elders and overseers and Friends nominated to aid
in accomplishing my intended visit to the drinking-houses in the city and suburbs.
Emptied, and never more stripped:--O,
the need of enduring these stripping and emptying seasons,
in order to being entrusted with the new wine of the kingdom to hand out to others,
pure and unadulterated.
The outward vessels, before they are fit to receive fresh liquor,
must undergo a thorough cleansing; sometimes firing is needful,
and even taking to pieces to be scraped and made
over again before they are effectually cleansed.
Thus it is with the vessels of our hearts:
we often need this emptying--this stripping--this purifying
from the taint of our first nature--the will,
wisdom, and activity of the creature, which never did, nor ever will do,
the Lord`'s work.

Third-day attended Meath-street meeting.
Fourth-day morning proceeded in the visit to the drinking-houses in the city,
and from the manner in which we have been generally received,
fresh cause has been felt to continue to trust in Him who, when he puts forth,
goes before.
Openness was manifested to receive what was said, and at one place where,
on our sitting down, I anticipated some resistance, quietness came over us,
whereby the word given to communicate appeared as
rain in its season on the thirsty ground.
Making a pause before we departed,
the young man of the house requested leave to say that he
felt the force of the truths that had been declared,
adding, he was a Papist by profession, yet he could address me in the language of father,
believing I had been endeavouring to do him good;
he hoped the cause I was engaged in would prosper,
and he believed I should have my reward hereafter.
Eighteen visits were accomplished this day.

Fifth-day, we accomplished twenty-two visits.
My poor body begins already to feel the effects of this engagement; but,
under a persuasion if care is maintained to look to Him who remains
to be strength to us in our times of greatest weakness,
I am favoured with the assurance he will not fail to equip for the next day`'s engagement,
seeing it is not by might, nor by power,
but by the Lord`'s Spirit renewedly quickening us,
that we are enabled to hold on our way,
and perform that portion of labour he may see meet to assign us.
Sixth-day attended the usual meeting at Sycamore-alley,
in which I was favoured to receive a renewal of strength.
We were enabled to accomplish fourteen visits.
The weather being warm, and the rooms mostly small, with low ceilings,
these together with the smell of the whiskey and beer,
overcame me so much that I was nearly deserting the field of labour before the day closed.
Seventh-day morning attended a funeral, after which, accomplished seventeen sittings,
mostly encouraging: at one place we were kindly invited to take refreshment.

Second-day morning,
just strength enough to crave ability to continue
faithful to the end of this day`'s work.
Our first visit was to Meath-street:
on our entering the house I felt as if I was going to be exposed to shame,
feeling unequal to deliver anything that might be required of me; but help, in mercy,
was afforded; openness being also manifested to receive what was delivered.
Nineteen visits were accomplished this day.
One man told us he had been in the practice of keeping his house open on first-day,
and had often taken eight pounds on that day, mostly for liquor;
but from the distress of mind which he was brought under,
on account of his conduct in this respect,
feeling himself a party in the guilt incurred by those who, through drinking to excess,
unfitted themselves for their religious duties, he resolved to give up the practice,
although he met with opposition from those who frequented his house;
yet by persevering he had been favoured to accomplish it.
He said, he had not yet gone so far as he must go,
by shutting up his grocer`'s shop also on first-day;
expressing his desire not to be permitted to stop short in his duty in this respect;
adding,
he had every encouragement to be faithful to that which he saw was required of him,
in that he had not been a loser by the sacrifice he had made; for,
by looking over his affairs,
he found they were in a more thriving condition since he had maintained
his ground against selling liquor on first-day than before.
Our visit appeared grateful to him;
and the day closed under a humbling sense of the applicability
to my mind of the query,--how much do you owe unto your Lord?
and no means to make a suitable return save by future obedience.

Third-day attended Meath-street Monthly Meeting,
in which holy help was manifestly near in transacting the business that came before it.
Fourth-day, proceeded to Corkstreet, James-street, etc.; accomplished twenty-one visits:
which in many instances appeared to be thankfully received.
One man,
who seemed to have some sense of the evil of drunkenness and its sorrowful tendency,
attempted to justify his own conduct, when taking too much whiskey, by saying,
their priest got drunk,
and surely the crime could not be greater in him than in the priest.
On my remarking how lamentable it was to hear such a character
of those who should set the people an example of temperance,
he replied, it was so.
Fifth-day nineteen visits were accomplished; and we were generally well received.

Sixth-day attended the usual meeting at Sycamore-alley; a time of holy quiet,
preciously preparatory to the work before us this afternoon.
The day proving wet, we did not accomplish more than seven sittings this afternoon,
some of which were trying; one woman, calling us wolves in sheep`'s clothing,
praying the Almighty to preserve her out of our hands,
who came to impose upon the people.
Seventh-day, we accomplished twenty visits, most of which were solid opportunities;
except at one place, the woman and her company treated us roughly;
but we were carried above their abuse;--another week to give an account of.

First-day morning at Meath-street meeting,
which suffered loss by the disorderly practice of standing in the
yard in conversation after the meeting should be fully gathered;
and yet I was comforted in believing some improvement had taken place.
The afternoon meeting at Sycamore-alley was large, and a more timely attendance observed:
it proved a quiet, solemn meeting.
These opportunities not being at our command,
it is incumbent on us that they be received with feelings of reverent gratitude.

Second-day proceeded to the Quay, a place I looked towards with expectation of suffering,
and it proved so, beyond anything I had yet known in Dublin.
Endeavouring to keep near holy help amidst all our discouragements,
we were enabled to accomplish eighteen visits today: the last was to a poor widow,
which we had reason to believe was seasonable to her,
and an agreeable close of the day to ourselves.
Third-day my kind friend Jonathan Hill was in waiting to proceed in the visit,
but my mind became so depressed I was obliged to decline.
Fourth-day morning, having a little recruited my bodily strength,
and my mind being afresh encouraged, we were enabled to accomplish twenty-one sittings.
The Good Power being near to visitors and visited made the way easy for us,
as my companion acknowledged, beyond what he could have expected.

Fifth-day, we were helped to accomplish twenty-three visits,
which were generally well received.
Accomplished fourteen visits this afternoon:
at one place it appeared as if the whole neighbourhood
was set in battle-array against us,
following us into the house we were going to visit: taking their seats by me,
they called for beer, and declared I should not leave the room until I drank with them;
on my refusing, they called for spirits; and on my refusing that,
one of them said he would know what I was; brawling,
trembling and looking pale with anger,
demanding to know my commission for going about to convert the people,
and asking if I had been ordained.
I felt much tried, more on my companion`'s account than my own;
yet I could not see my way clear to leave, nor yield to fear;
but feeling that Power to be near that never had disappointed me in my most trying moments,
believing all would end in bluster,
and that they would not be permitted to hurt a hair of our heads,
by keeping quiet matter was given me for expression, and strength to deliver it,
which they were not able to oppose or gainsay.
Feeling myself clear of them,
we left under a thankful sense we had been supported
to maintain our standing with firmness.

At another place, the man we visited, after hearing what I had to offer, said,
he had been out drinking the preceding evening, and kept it up till morning,
and he was going in like manner to spend his time that evening, adding,
he knew it to be a crime to get drunk; yet he hoped, if he went at times to his duty,
(meaning mass,) that would settle the account.
I queried with him, how he felt the next day?
He acknowledged he felt uncomfortable, and then he got upon his horse, and, by company,
tried to get rid of his uneasiness.
I told him the time would come when his uneasiness would be too powerful for him,
and should he be removed by death in a state of intoxication, knowing it to be a crime,
as he acknowledged,
what account would he be able to render for his "`sinning against knowledge?`"
He replied, he was willing to run the venture,
and settle the account in the best manner he was able.
After requesting him to think seriously on the subject, we left him.
What an awful instance of that state of depravity the human heart may abide under,
even while in mercy followed by Divine conviction.
Notwithstanding this day was attended with some severe trials of faith and patience,
it closed peacefully to ourselves.

Seventh-day I proceeded under great depression of mind, and from the bustle we met with,
under much suffering.
After we had accomplished four visits I was obliged
to give up further proceeding this day.
First-day morning attended Meath-street meeting: getting low and discouraged,
I allowed the right time to pass over, in which, I believe,
I should have made my offering.
Second-day morning, after accomplishing four visits,
I was obliged to rest the remainder of this day.

Third-day morning attended Meath-street meeting: the buying and selling,
planting and building, or things comparable thereto,
occasioned us to have a very small meeting; after which, with some difficulty to myself,
we accomplished five visits.
Fourth-day morning proceeded again, I hope I may say desirous of doing my very best,
under a very enfeebled state of body.
We bent our course to Churchstreet, Constitution-hill, and the Circular-road.
We were enabled to accomplish nineteen visits during the day, generally satisfactory.
At one place, the mistress of the house offered me money, urging the acceptance of it,
and expressed her surprise at my refusing.
I returned from the field of labour afresh animated to be willing to press on to the end,
from the assurance that aided by Divine help, it would be crowned.
Fifth-day, proceeded to the outskirts of the city; and after travelling over much ground,
we accomplished only nine visits, generally satisfactory.

Sixth-day, made three visits before meeting; attended Sycamore-alley meeting,
which proved a time of holy quiet,
in which a little morsel of soul-sustaining bread was dispensed.
After meeting we again pursued the work whereunto the call is daily renewed in my mind;
accomplished ten visits, generally meeting with an open reception,
except in two instances.
At one place the man of the house whom I was addressing sat quiet,
until a man who was drinking reproached him with
hearing me with more attention than his own priest:
although these remarks did not cause him suddenly to interrupt me,
yet in time he got into a great rage that I should
insult him who was so much better taught,
turned pale and trembling, and said, theirs was the only true religion in the world;
querying with me, would I eat meat on a Friday?
I told him,
the good things of the Almighty were to be received with thankfulness every day.
He said, as I would eat meat on a Friday, I was going the high road to hell.
He wished he had us out, declaring what he would do to us.
His countenance became terrible; and, had I yielded, fear would have predominated,
and caused us hastily to make our escape;
but we were mercifully preserved in the quiet until I felt liberty to leave,
assured that no personal injury would be permitted to befall us.

Seventh-day accomplished nineteen visits, mostly in Mary`'s-lane and Pill-lane,
among a very depraved class of our fellow creatures.
Entering some of the houses, the countenances of those who kept them,
as well as their company, exhibited so much of the depravity of human nature,
that it brought a great damp over my spirits;
yet I was enabled to get through the visits to my own relief,
openness being generally manifested to receive what was communicated,
and I cannot believe that in all cases it will be as water
spilt upon a stone--though no visible fruits may soon appear.
A customer at one place took his seat by us,
I suppose for the purpose of disputing with us.
He questioned me as to my belief in the Trinity;
asked me if I believed in the possibility of our sins being forgiven on earth.
I told him I believed it was absolutely necessary this should be experienced,
but that God and Christ only had power to forgive sins.
He said Christ had given power to his priest to forgive sins;
that he had Christ in heaven,
and Christ next door to him (meaning his priest,) and in a rage told us,
none but those of their church could be saved.

Second-day, accomplished twenty-two visits, generally satisfactory,
although at times we had much religious prejudice to combat.
Third-day morning attended Meath-street meeting,
after which we proceeded towards the Customhouse:
the appearance of some of the houses and company threatened suffering.
I found it hard work to maintain my standing with becoming firmness;
yet I humbly hope I was faithful in expressing all I was entrusted with for communication.
After making six visits, a cold chill coming over me,
I was obliged to lie by the remainder of this day.

Fourth-day, we bent our course towards Berwick-street.
Our work lay among some of the most striking instances of the
depravity of human nature the city of Dublin or its suburbs furnish,
so far as I have yet seen.
One woman, after learning the nature of our visit, on a sudden left us,
and I supposed she did not mean to give us her company,
but in a short time returned again, saying,
she had been to fetch some of her neighbours to partake with her in the visit,
who behaved well: the woman appeared tender,
expressing her thankfulness for the opportunity,
and the desire which she felt that the advice given her might be remembered to profit.
At another place, the woman of the house was so deaf,
I was obliged to extend my voice to such a high pitch,
that it raised some of the neighbours, and brought them into the house,
which occasioned us a large company, some of whom appeared disposed to be rude,
but through the endeavours of others they were kept quiet; at our leaving,
the woman and company expressed their thankfulness for the visit, one man excepted.
Although we mostly had rough company to sit with today,
yet we were generally kindly treated.

Fifth-day, we proceeded to Barrack-street.
The first house we entered made a deplorable appearance:
it was very early in the morning, yet we found,
on descending the steps into the drinking-room, which much resembled a cellar,
the window-frames and glass broken, and several young women, without shoes,
stockings or caps, dancing to the fiddle.
We made towards the room set apart for the keepers of the house,
where we met with the mistress.
Requesting, if she had a husband to have his company, he soon made his appearance.
I endeavoured to lay before them what arose,
although I found it difficult to get fully relieved.
The fiddle, and at times the screaming of the dancers, was a great interruption.
The man remained quiet for a short time and then left: us,
the woman appearing to have the management of the house:
what I had to say brought her to tears.
On inquiry I found she had children,
I therefore requested her seriously to consider what would be her conclusion
respecting the conduct of any person who should harbour her children,
and allow them to go on in such wicked practices as she
was now encouraging the young girls in under her roof,
who might be without parents or friends to take charge of them, saying,
I did not wish for a hasty reply; she confessed she should think they acted a cruel part.
I therefore entreated her to attend to that Divine monitor in her own breast,
which she confessed she at times witnessed to be near,
which would clearly make known to her the necessity
to rid her house of such company as she now harboured,
which would be one way whereby she might hope for the Divine blessing
on honest endeavours for the support of herself and family,
otherwise she must look for a blast following them every way.
She continued tender, and at our parting, in a feeling manner expressed her desire,
that what had been communicated might be profitably remembered by her.

After receiving her warm expressions of gratitude, we proceeded to leave the house,
but on reaching the top step of the entrance my attention was again arrested,
and I found I must be willing to return into the
apartment where the dancing was going forward,
and quietly submit to any insults that might be the
result of my being found in the way of my duty.
On my companion being informed hereof, he appeared tried as well as myself,
but I found it would not bring peace to our own minds to hesitate.
We therefore turned back, which the woman of the house observing, came and stood by us,
I supposed to prevent any rude behaviour that might be offered.
I requested the man who had the fiddle to cease playing and take his seat,
which he complied with, and those who were dancing to do the like,
which each one yielded to.
The scene exhibited in different parts of this large room,
if it were possible fully to describe,
would produce a picture of as great human depravity and misery as well can be conceived.
On a bench near us lay young girls,
overcome with their night`'s revelling and drunkenness,
past being roused by anything that occurred round them; others, from the same causes,
reclining on the tables, barely able to raise their heads and open their eyes,
and altogether incapable of comprehending what was going forward:
companies of men and women in boxes in other parts of the room drinking.

On our standing silent among them a short time,
quietness prevailed over the whole company.
Strength was received to utter what was given me,
and after I had been some time engaged in addressing this band of human misery,
I think I shall not, while favoured with my mental powers,
wholly lose sight of the distress and horror portrayed in the countenances
of those young women who had ceased their dancing.
Feeling my mind relieved and about to depart,
such of the company who were equal to it rose from their seats,
acknowledging their gratitude for the labour that had been extended,
and their desire that what had been said might not be lost upon them,
and that a blessing might attend us.
My back was towards the door,
and not hearing a footstep of those who came in while we were engaged,
when we turned to go out I was surprised at the addition made to our company:
my companion remarked,
it appeared as if something brought an awe over their minds on entering,
and they quietly took their seats,
and when the seats were full others sat on the ground.

We retired to a Friend`'s house near,
and after being recruited proceeded in our visit to Barrackstreet;
and accomplished as much as way opened for us to do.
I became sensible it would not be safe to delay going to a house in Mary`'s-lane,
which I had knowingly passed by,
in consequence of a caution given me by a collector of the excise, who said,
he never dare go beyond the door, taking a person with him when he went to collect.
I endeavoured to resign myself to Divine protection, and we proceeded.
We only obtained the man`'s company; and,
from the appearance of all we saw about the house,
there was reason to believe wicked practices were permitted to go on by those he harboured.
I endeavoured to lay before him in very plain terms my views of his proceedings,
and what he must expect, if he continued to pursue his present line of conduct,
would in the end be the sorrowful consequences of his harbouring the company he did,
and allowing such wicked practices in his house;
exhorting him to look to Almighty God for help to clear his house from wicked company,
telling him, I believed, while I was addressing him,
he felt the Divine Witness in his own breast reproaching
him for his conduct in these respects.
He was much brought down,
acknowledging he had at times acted against that better judgment he was favoured with,
and was willing to receive anything further I had to offer to him,
mentioning the name of a Friend he dealt with,
and proposing to meet me at his house to have a more quiet time together.
Pausing a little on his request,
it appeared safest for me to say I did not feel any thing more in commission for him.
Being about to depart I felt a stop in my mind; on endeavouring to see the cause,
I was brought under the necessity of going into the
apartment where the different companies were drinking,
male and female, who, except that they were more sober,
appeared much like the company in Barrack-street;
some of them were uttering expressions awful to hear.
Standing a short time quietly among them, I requested their attention:
such as were standing took their seats,
and what I had to say was heard without interruption;
others came in while I was speaking, whose countenances bespoke great levity,
but they took their seats quietly with the rest.
At our departure they generally showed themselves respectful,
expressing thankfulness for the advice that had been given them: thus this day`'s work,
through the continuation of holy help, closed peacefully, and, I humbly hope,
under a sense of the necessity of adopting the language of the royal Psalmist,
"`Not unto us, O Lord, not unto us, but unto your name be the praise!`"

Sixth-day, attended Sycamore-alley meeting: a quiet favoured time,
which to myself was like a feast of fat things after the storms we had endured.
After meeting we accomplished eight visits, in all of which we were kindly received,
yet we were obliged to cut this day`'s work shorter than usual;
partly from debility and the chills that at times came over me,
my voice became so weak I scarcely could speak to be heard.
Seventh-day morning, proceeded to Marlborough-street,
calling upon all on this side of the water whom we had not yet found at home.
We were generally so well received,
that to me it felt like going to members of our own religious Society,
to give advice respecting some branches of our testimonies:
thus closed another week`'s work to account for to that God who
alone sees the heart and what our real motives to action are,
and will reward us accordingly.

First-day, attended Meath-street meeting in the morning; in the afternoon Sycamore-alley,
in which we were favoured with the good presence of him who is God and changes not,
but from everlasting to everlasting is nigh at hand and not afar off,
to help those who continue to rely upon him.

Second-day, 13th of eighth month, 1811,
I left my quarters desirous to try to do my best this day in prosecuting our visit;
but from the great nervous debility I was labouring under,
I became so dispirited I found myself unequal to make any effort.
Third-day, attended Meath-street meeting.
Fourth-day, we bent our course to Patrick-street,
but in consequence of the crowd of people that collected round us,
we were obliged to proceed to another part of the city.
We were favoured to accomplish seventeen visits, generally satisfactory.

Fifth-day, we again bent our course to Patrick-street.
The first call we made we met with a determined repulse.
At the next place we came to, all things were made easy for us;
and the opportunity proved a favoured one both to visitors and visited:
a good degree of thoughtfulness appeared to be excited
in the minds of the man and his wife,
who, in a feeling manner, acknowledged their thankfulness for the visit.
We were afresh encouraged to put on strength in the name of the Lord,
who has thus far led us about and instructed us, that we have nothing at our command,
but must look to, and in full confidence lean on Him that has the key of David;
when he shuts none can open, and when he opens none can shut.

At the next place the master of the house looked fiercely at us,
and as if he had resolved to oppose and perplex us, behaving snappishly,
asking me what I wanted, and whether would I give him an order for whiskey.
People, who from their appearance and behaviour, were disorderly characters,
crowded in after us, and gave me an unfavourable idea of consequences;
yet I was led to believe, if I followed the counsel of my good Guide,
gloomy as our situation appeared, I must maintain my standing patiently among them.
I therefore laid hold on the courage thus mercifully held out for my acceptance,
and requested the man of the house quietly to sit down,
and I would let him know what had brought me to his house.
I found it required of me patiently to hear all he had to say however painful it might be.
Truth being stronger than that opposing spirit by which he was actuated,
he gradually became quiet and softened in his mind,
manifesting a willingness to hear what I had to say,
and at our pairing showed a kind disposition,
expressing his desire to attend to the advice given him, and all ended quietly.
The crowd continuing to follow us we were constrained to leave Patrick-street again,
but by taking another direction, were enabled to accomplish nineteen visits today.

Sixth-day attended Sycamore-alley meeting,
in which fresh cause was in mercy vouchsafed to acknowledge,
that the shout of the King immortal is still in unmerited mercy to be heard among us.
After meeting we accomplished twelve sittings,
the last as trying as any we have at all met with.
The man having heard of our coming appeared to set himself in battle-array,
meeting us in a taunting way with his hat in his hand, saying,
his thus meeting us was out of respect,
and making a great profession of his respect for our religious Society,
telling us he was a convert to the Romish church.
His ferocious countenance, the turbulent temper he evinced, his large figure,
and the unfavourable impression my mind received of the company that was drinking,
were such, that if I dared, I gladly would have quitted;
but keeping in the patience until he had wasted all his ammunition,
I endeavoured to lay before him, notwithstanding all the profession he had made,
of his safety as to salvation,
the danger of his being deceived at last in this momentous matter:
exhorting him to be willing to turn to that Divine Light in his own heart which would
give him to see the dangerous situation he was in while he continued in the gall of
bitterness and those bonds of iniquity he was allowing himself to be bound by.
He received what I had to offer without interruption, became more calm,
and sitting down desired me to communicate all I had in commission for him, saying,
he was willing to receive it.
Feeling my mind discharged from anything further to communicate, we departed,
and left him to that Almighty Power that had in mercy broken in degree his hard heart.

Seventh-day, proceeded to Patrick-street, where we were roughly handled at the quay;
our lot was again cast in one of those houses occupied by disorderly females:
the mistress and her depraved company treated us with respect.
I felt much for my companion, diffident and unacquainted with such haunts of wickedness.
I endeavoured in very plain terms to set before the keeper of the
house her reproachful conduct in upholding such an establishment,
warning her of what she must expect will be the consequence hereafter,
if she continued to allow of such evil practices
as she well knew had been going forward in her house,
and with her free consent.
She appeared to receive kindly what was offered: at our parting her countenance,
and that of her company, manifesting such a degree of thoughtfulness,
I was led to hope the impressions made on their minds would not, in every case,
soon pass away.

First-day, attended Meath-street meeting:
my unfaithfulness therein caused me to leave it under distressing feelings;
yet what a mercy it is when we fall short in the discharge of duty to our God,
that he follows us by the reproofs of instruction that they may prove the way to life,
by animating us, with greater earnestness, to wrestle for those daily supplies of faith,
which alone can give the victory over all that would let
and hinder our faithfully following our heavenly Guide.
In conversation after meeting,
with a fellow traveller in the hope and fellowship of the Gospel,
it appeared that my unfaithfulness had been a two-fold
loss to the meeting by my sitting in her way:
when the beautiful order of the Gospel is thus broken in upon,
what a loss it may prove to those assembled!
Attended Sycamore-alley in the afternoon: my obedience was again put to the test,
and being brought to a willingness to become anything
or nothing as my Divine Master willed I should be,
he was pleased to give me strength to say what I was commissioned with,
and I left peacefully.

Second-day: my nature was much disposed to plead inability to turn out;
but as no excuse would acquit me of wilful rebellion against
the grain of faith in mercy dispensed in this needful time,
I proceeded, and after accomplishing eleven visits,
many of which were very trying to human nature,
I was obliged to go home and rest the remainder of the day.

Fourth-day, we made an early turn out, and accomplished twenty-five visits;
being generally well received, except in a few instances.
One man told us we ought to be burnt, that the earth might be rid of us:
we were preserved from making any reply to his observations,
but when an opportunity occurred I expressed what appeared to be given me for him,
which he quietly heard, became more calm;
and on our quitting followed us along the street,
expressing the desire he felt for a further opportunity,
but I told him we must leave him to that law within which he acknowledged his belief in,
and by which he would sooner or later be judged.
He parted from us apparently in an agreeable disposition of mind.
Thus wonderful, from time to time, has been the display of the Divine Power,
causing the lion to lie down with the lamb,
and giving us to experience that there is neither
hurting nor destroying in all God`'s holy mountain;
so long as we act under the influence of his fear, we are preserved from hurting others,
and others are restrained from harming us.

Fifth-day, we bent our course to Dury-lane and Minion-square;
and had interesting opportunities in two families where
there were several children grown up to maturity.
Our visit appeared to be acceptable both to parents and children.
On entering one house, a man was drinking, who, from his appearance,
I supposed to be a Catholic priest, from whom I expected opposition,
and would gladly have requested the man of the house
to give me his company in a private room,
but this I clearly saw would not make for peace;
we therefore took the man of the house into the common drinking room.
My fears respecting the man who was drinking were soon realized;
for no sooner had we taken our seats, but he attacked me, saying,
I had no right to interfere with the members of their church,
which was the only true one, and theirs the only true ministers,
all others being deceivers.
As he manifested a desperate, revengeful disposition,
I allowed him to spend himself without replying to any thing he had to say.
On his ceasing, I sat quiet awhile,
and then expressed what I had to say to the man of the house,
which I was permitted to do without being interrupted,
this man`'s spirit appearing chained.
When we were about to depart, this priest-like man gave us his hand,
and with it his blessing.
Nineteen visits being accomplished, this day closed under a grateful sense,
that through the daily fresh supplies of holy help this
arduous engagement was fast advancing to a termination.

Sixth-day, attended Sycamore-alley meeting, and accomplished eleven visits,
generally satisfactory; but in consequence of the crowd we were rather inconvenienced.
Seventh-day, we called on such as we did not find at home or had been denied,
and way was made for us to clear off our list, thirty-five.
Thus another week closed with songs of thanksgiving and
praise in my heart for the help already in mercy extended.

First-day, attended Meath-street meeting in the morning,
in which the sound of an alarm went forth to such as were
negligent in the attendance of week-day meetings,
and in a due observance of the time appointed.
Attended Sycamore-alley meeting in the afternoon: a quiet favoured time.
Second-day, seventeen visits were accomplished.
At one place, the man of the house told us, he had been to confession yesterday,
and that was enough; his priest had done all for him that he stood in need of.
I believe he gave us a correct description of the state of his mind; whole,
and needing no physician but his priest.

Third-day morning, we bent our course to Barrack-street.
In our first visit, the appearance of the keepers of the house,
the company that was drinking, and the female lookers-on, caused me to tremble.
On my requesting the keepers of the house to afford me an opportunity with them,
they complied, and the companies that were drinking followed us,
quietly taking their seats.
I was led in a very plain manner towards the keepers of the house;
laying before them what they had to expect would be the sad consequences
of their continuing to shake hands with iniquity as they were now doing.
Great quietness was observed,
and there was reason to hope what was delivered made an impression on the minds of some.
The man of the house, when we were about to leave,
in a humble manner acknowledged his consciousness of guilt,
and his desire to attend to the counsel he had received.
After we left the house, my companion told me,
his fears were excited when the people followed us in such numbers,
and heard the plain manner I had to labour with the people of the house.
We pursued our visits, which, in most instances, were satisfactory,
and this afternoon closed this humiliating engagement in the city and suburbs,
having had in all about six hundred sittings.

Sixth-day, attended Sycamore-alley meeting: at the close of which the committee met,
to whom I opened a prospect of duty to visit the Protestant and Romish bishops,
and the mayor and sheriffs; after mature deliberation,
it was concluded to refer the subject to the select members; who met,
but not being able to come to a judgment,
referred it to the committee and the select members, jointly.
First-day morning, attended Meath-street meeting,
at the close of which the joint-committee met, and adjourned to third-day.
Although, from a desire I felt to clear out of Dublin,
this suspense was rather trying to human nature;
yet I hope I was favoured to esteem it a mercy from my heavenly Father
in having my mind at rest respecting the disposal of my religious prospects,
now under the care of my friends, and to be careful for nothing respecting them;
aware how needful it was for me not to over-act my part by cutting and carving for myself,
or in any way dictating to the joint-committee,
but aiming at abiding passive as to the result of the committee`'s deliberation.

Third-day, attended Meath-street meeting; at the close of which the joint-committee met,
liberating me to visit the mayor and sheriffs;
but as fears were excited in the minds of some of the committee
that a visit to the bishops might endanger unpleasant controversy,
way did not open to liberate me to make such a visit:
endeavouring to give this subject all the consideration I was capable of,
I was not able to come at any such separation in my own mind,
believing a visit to the bishops was as much a continuation
of the visit I had been engaged in,
as one to the mayor and sheriffs;
I therefore found my safety was in standing still for the present.

Sixth-day, attended Sycamore-alley meeting,
at the close of which the joint-committee was called together,
when I gave Friends the view I had taken of the conclusion the committee had come to,
and that I felt the subject for the present completely at rest in my own mind.
The way opening for me to move towards the North again, I requested,
if no objection arose to my proceeding,
some Friend would stand ready to take charge of me,
and should the subject of my proposed visit to the mayor, sheriffs and bishops,
on my return to the city, revive,
I stood resigned again to call upon my friends for their aid in its accomplishment.
This conclusion, I was thankful to find, was satisfactory to the committee,
it having felt trying to me that anything like clashing in sentiment should appear,
feeling bound in Gospel love to the Friends of Dublin.

Seventh-day, accompanied by my kind friend William Birkett, jun,
we proceeded to Mountmelick, where I was kindly cared for by James and Hulda Pim.
First-day, attended the two meetings there.
Second-day, rode to Rathangan.
Fifth-day, accompanied by my kind friend William Beale, proceeded to Mountrath;
attended meeting there.
Sixth-day, made an agreeable visit to a Friend and her numerous family, at North Grove.
Seventh-day, accompanied by my kind friend William Neale, we rode to Moate.

First-day, attended meeting there.
Third-day, we rode to Ballymurry.
Friends having been informed of our proposed visit, informed their neighbours,
who came flocking to the meeting, which tried me not a little,
my prospect being confined to Friends.
The meeting, I believe, proved satisfactory to all parties:
those not professing with Friends expressing their unity
with the truths of the Gospel that had been delivered.

First-day, attended meeting at Grange.
I was rejoiced in once more being permitted to sit with Friends here,
which rejoicing I believe was mutually felt.
Fourth-day, at Ballinderry.

Fifth-day, Lisburn meeting; and sixth-day proceeded by coach to Dublin,
where I was favoured to arrive safely.
On seventh-day morning,
feeling drawings in my mind to attend the Quarterly Meeting for the province of Leinster,
to be held at Moate, I proceeded from the coach to the canal-boat,
where I unexpectedly had the company of my kind friend Robert Fayle:
we reached Tullymore in the evening.
First-day morning, reached Moate.
The two meetings this day were large,--seasons in which we were favoured with
a fresh evidence that Divine mercy still follows us as a religious body,
in order that those testimonies which some of our forefathers sealed
with their natural lives may not be allowed to fall to the ground,
through a spirit of lukewarmness and the love of the world
gaining the ascendency over their successors in profession.

Second-day, the Quarterly Meeting for discipline commenced.
The hint given not to stand in the meeting-house yard when the meeting should be gathered,
being attended to, the meeting settled down in quiet:
the various matters which occupied its attention were conducted in much harmony,
and Friends separated under a thankful sense hereof.
Third-day, the parting meeting was held:
the presence of the Great I Am being mercifully continued to us to the end,
caused feelings of gratitude to flow in many of our minds.
Fourth-day, left Moate; reached Dublin in the evening.

Sixth-day, attended Sycamore-alley meeting; at the close of which,
feeling drawings in my mind to visit the drinking-houses in Killculen and Neice,
I was liberated to pursue the prospect.
Second-day, proceeded to Killculen, and made an attempt to pay a visit in the evening,
but the man of the house being in a state of intoxication, we returned to our inn,
having uniformly found that evening was not a suitable time for these visits.

Third-day morning we accomplished eight visits, some of which were open and satisfactory;
but it was evident that prejudice had entered the minds of others
who refused to receive us having given all the offer,
I left with a peaceful mind.
We then bent our course to Neice on our arrival there,
we were informed the petty sessions was to be held, which discouraged me,
expecting the houses would be in a bustle;
but as I was not able to see other than that this was the right time to proceed,
we concluded to take the houses at the upper end of the town first,
and work our way towards the middle, where the most of the bustle was likely to be,
and when we had accomplished thus far, begin again at the lower end of the town,
and proceed in like manner: hoping by the time that thus much of our visit was completed,
the bustle in the middle of the town would have subsided.
Although we met with much openness, and had some satisfactory opportunities, yet,
before we finished,
we had cause for believing prejudice had obtained the ascendency over some minds.
After having about twenty sittings we left Neice, and reached Dublin late this evening.
On reclining my head to rest for the night,
the retrospect of our little act of dedication this day caused tears of
gratitude to flow freely for that Divine help that had been in mercy extended,
which continued at times during the following day.

Sixth-day, attended Sycamore-alley meeting, at the close of which,
the subject formerly spread before Friends coming again with weight before my mind,
I called the attention of the committee again to
the whole of my prospect of religious duty,
as I at first spread it before them.
After these subjects had been again maturely weighed and considered,
two Friends were nominated to arrange for the several visits.

First-day, attended Meath-street meeting in the morning,
a season in which heavenly bread was dispensed to some.
Second-day morning, agreeable to appointment, proceeded to the mansion-house,
and were cordially received by the mayor and one of the sheriffs,
the other being prevented through indisposition.
Much frankness was manifest in attending to the various subjects of abuse
which had come under my notice during my visit to the city.
They freely acknowledged their conviction of the justness of my observations,
and requested if I had remedies to propose, to be free in communicating them.
After I had given my views as to the remedies most likely to effect the change,
so desirable in the city and suburbs,
we left them under a grateful sense of Divine interference,
in thus inclining their hearts to receive what I had to offer.
From the Mansion-house, we next went to the Roman Catholic bishop,
who received us civilly.
I had but little to communicate to him,
and that principally of a nature tending to rouse him to consider
the great load of responsibility that rested on him,
in consequence of the implicit dependence which the people place on the clergy;
laying before him the sorrowful account they will have to give in a future day,
who are building up the people in this reliance on themselves,
instead of turning their attention to Christ within, the hope of glory;
and especially where they themselves are not found walking
in the footsteps of the flock of Christ`'s companions,
and using their influence and authority to suppress every appearance
of evil among those over whom they take such an important charge.
He assented to the truth of my observations,
and we took leave of each other with marks of kindness.

The Protestant bishop being in England, we proceeded to the deanery in Cavan-street:
the dean received us respectfully.
My chief engagement was to lay before him the need there was for the clergy of the Protestant
religion to be vigilant in their endeavours to strengthen the hands of the magistrates,
for the suppression of the evil practices apparent in the city and suburbs,
which must come under his notice in passing through the streets.

On our quitting,
I informed the dean of my intention to call upon the chief magistrate of the police,
upon which he kindly offered us a letter of introduction;
but arrangements having been already made for us, we declined his kind offer,
and proceeded to the castle, where the dean was waiting to receive us,
who accompanied my companion and myself to the chief magistrate`'s apartments,
by whom we were kindly received.
I informed him of my engagements in the city and suburbs,
and of the observations I had made on the great immorality of the people,
more especially as it respected drunkenness.
I added,
that although I was well aware the chief actors in these abuses were Roman Catholics,
and that the bulk of the people were of this religious profession,
yet that the Protestants held the reins of government,
and except those who are in authority exert their
influence and endeavours to remedy these evils,
which draw down the displeasure of Almighty God,
they become parties in the guilt in the Divine sight.
The necessity of something being done was in a very agreeable manner acknowledged,
and a willingness shown to receive any suggestion from me by way of remedy.
After having given my views on the different means of applying help,
we parted under feelings of regard, and took an affectionate leave of the dean.
Although I felt cause to rejoice that way had been made for me to obtain relief,
and that nothing had occurred to produce controversy, I felt my nature so worn down,
that I was obliged to go home, and not attend the Monthly Meeting which was then sitting,
as I wished to do: the meeting however adjourning to the evening,
I gave in a short report of my proceedings.

Fourth-day, a meeting was appointed by Martha Brewster of Bury in Suffolk,
here on a religious visit; which proved a parting meeting to me and many I dearly love,
and occasioned many tears to be shed.
Way now being clearly made for my departure to my own home,
after a satisfactory sitting with the select members and overseers,
accompanied by several Friends, I proceeded to the Pigeonhouse,
and went on board the packet.
Captain Judd, for Holyhead: after a passage of ten hours we landed safely.
Seventh-day, we proceeded to Manchester.

First-day morning, attended meeting there;
and in the afternoon sat with Friends of Rochdale.
Second-day, proceeded to Barnsley, where I was favoured to find my dear wife well,
my widowed daughter and grandchild much recruited in their health,
and my daughter`'s outward affairs in every respect well cared for;
awakening in my mind the language of, "`Return unto your rest, O my soul,
for the Lord has dealt bountifully with you.`"
