== Chapter X.

In the eighth month, 1812, I left home for Sheffield, to attend a burial.
On my way there, before I reached the quarters I was aiming at,
I turned out of my road to the house of a Friend; where I was informed that Ann Fry,
a Friend of Frenchay meeting, personally unknown to me;
from an apprehension of religious duty was likely to visit the families of the colliers,
miners, and a description of men called the Gang, at Kingswood and in its neighbourhood.
Her Monthly Meeting, it appeared, had liberated her for the service,
and had selected a committee to assist her,
but for lack of a companion she had not proceeded.
The recital of the circumstance excited my feelings,
but after leaving the Friend`'s house my mind became pretty free from the subject.
Soon after my return home, however,
it revived with such weight that I was unable to come at any settlement,
until I yielded to write to Ann Fry, requesting the outlines of her religious engagement.
I did so in such a cautious way as not to leave ground for supposing that
more than sympathy for her in this arduous engagement had been my motive,
lest after trying the fleece I should find the will on my part was accepted.
Her reply did not produce that sort of acquittal which I could gladly have accepted;
and there was no way for me to come at peace but
by being willing to unite with her in the service.
I therefore cast myself upon my Monthly Meeting for its disposal,
and a certificate being granted me, on first-day, the 4th of tenth month,
I left my own home, and got to Birmingham week-day meeting,
where I had to labour with the double-minded;
but it was hard to obtain full relief to my mind.

Fifth-day, sat with Friends at Worcester, in which an evidence was mercifully granted,
that stripped as Friends here are of outward ministry,
the Minister of ministers was near to help those who were devoutly depending upon him.
After meeting walked to Tewkesbury:
here my mind was brought under exercise on account of several young people at my quarters;
and by endeavouring to express what was given me to communicate,
I was enabled to go on my way rejoicing;
whereby the toil of this day`'s work was diminished.
Seventh-day evening, reached the abode of my kind friend Joseph Fry, at Frenchay,
although much exhausted with my long travel, yet abundantly rewarded in mind,
by a hope that my movements thus far had been in the line of Divine appointment.

11th of tenth month.
First-day, I attended meeting here, at the close of which I produced my certificate,
allowing me to accompany my friend Ann Fry in her religious visit,
which appeared to meet the general concurrence of Friends of the meeting.
In the afternoon we embarked in this arduous engagement,
proceeding to a cluster of cottages about a mile from our home:
here we collected the occupiers of them into one cottage most commodious for the purpose,
with whom we had a quiet, and satisfactory meeting.
Quitting these cottagers, we found a number of men standing by the roadside,
and made a halt, with whom we had good service,
they appearing to receive kindly what we had to offer to them.
We then returned home, with minds filled with gratitude for this beginning.

Second-day, we proceeded, and making a halt at some cottages,
my companion laboured to collect them into the one most commodious for their reception.
At our first sitting down they manifested so much unsettlement, going out and coming in,
that I was discouraged; but after a time of exercise of both faith and patience,
a considerable company were prevailed upon to take their seats quietly.
I trust it may be said, that matter was given suitable to states present,
and a willingness wrought in many of their minds to receive it.
We left them under a thankful sense that best help had been near.
At another cottage, about forty persons were collected;
and in a short time great quietness prevailed, many countenances manifesting solidity,
and attention to what was offered.
We were helped to labour among them in the love of the Gospel,
accompanied with a belief that the truths delivered were received with gladness by many.
We proceeded to a workhouse; where the company consisted of aged persons and children,
about twenty in all, but in a miserably neglected condition.
After having a quiet opportunity with them,
we had a free conversation with one of the parishioners relative
to the neglected state we found these poor creatures in,
and were led to hope they would be better cared for in future.

Third-day, we bent our course towards Mangotsfield.
On our way seeing a man thrashing in a barn, we left the high-road and made up to him:
his countenance appeared careworn, and weighed down with anxiety of mind.
We found him more intelligent than the generality of those we had met with,
and on inquiry into his situation,
it appeared he had a wife and nine children to support,
and his own earnings all he had to depend upon to meet his expenses.
The counsel we had to impart appeared a word in due season,
and as a cordial to his poor tried mind.
I felt truly thankful my companion had thus given
way to the impressions of her mind on this occasion.

We proceeded to the cottage of a collier; on entering which my nature recoiled,
at viewing the filth that surrounded us; and the neighbours crowding in,
the place was nearly full: we had an open opportunity among them,
accompanied with a hope that our labour would not be in vain:
our visit appeared to be kindly received by most of them.
A large room being offered us to hold a meeting in, we accepted of it,
and at four o`'clock this afternoon, nearly one hundred men,
women and children were collected.
Unacquainted as they generally were with the manner of our meetings,
and considering the rough uncultivated state in which they are brought up,
their quiet behaviour was to us admirable:
we could not doubt but that the opportunity was a time of Divine favour to many.
My companion`'s mind being drawn to make a visit to some soldiers in the neighbourhood,
we proceeded to their quarters, and obtained a sitting with them.
We had reason to believe the counsel imparted was well received:
they acknowledged their sense of the good we intended them,
and their desire to keep in view what had been communicated: we then returned home,
humbly thankful to Israel`'s Shepherd, in thus mercifully caring for us another day.

Fourth-day, attended the meeting at Frenchay:
afterwards we visited four families in their cottages, and were well received.
We also visited three public-houses, in which we found much company, some full of liquor,
and had opportunities both with the keepers of the houses and their customers,
by whom we were generally treated with great civility.
Our next visit was to some soldiers in their mess-room: on our first entering,
appearances were discouraging, the fife and fiddle playing,
and their minds appeared all a-float;
but on my requesting them to lay their diversions aside, they complied,
and sat down quietly with us,
many giving proof that their minds were impressed with what was offered.
May these instances of Divine interference prove a fresh excitement to faithfulness.

Sixth-day, we bent our course toward the parish of Mangotsfield;
had numerous visits among colliers and others,
and found a willingness to receive what we had to say.
We were comforted in observing so much sensibility in things of the greatest importance,
as we met with among this degraded, uneducated portion of our fellow creatures;
and that first-day schools were establishing in this
dark and long-neglected part of the nation.
We had to lament the lack of better qualified teachers in these schools;
but a hope was awakened in our minds that time would apply a remedy,
as many well-disposed individuals in the neighbourhood
were exerting themselves in the proper care of them.
During this day`'s labour our minds were deeply affected with the
instances of human misery we met with among the aged,
sick, and infant, poor.
In the evening we bent our course to Hambrook; visited the public-house there,
and saw about sixteen soldiers in their mess-room.
On our first entering some of them appeared so disposed to giddiness,
that I feared we should have met with rude behaviour;
but through the kind and merciful interference of our Divine Master,
on my requesting them to take their seats, they became quiet,
and sat down soberly with us, manifesting a disposition to receive what was communicated.
At our parting, they united in expressions of obligation for our visit.
I trust we were not deficient in our sense of gratitude to that good Power who,
having appointed us such a humiliating path,
had thus mercifully and wonderfully cared for us through another day.

Seventh-day,
our lot was cast among some who profess to be the followers of George Whitfield:
although we found it difficult to come at silence among them,
yet as patience was abode in, it was obtained, and I trust it may be said,
we had good service among some of them.
In one visit to a young couple,
three young men came into their cottage while we were sitting in quiet,
who appeared giddy and disposed to interrupt us;
but by endeavouring to keep under our exercise,
it evidently spread like leaven through the whole company;
they evincing a becoming degree of serious thoughtfulness,
a full opportunity was afforded us to relieve our minds:
may the praise be given to that high and holy One
who inhabits eternity and dwells on high,
for his merciful interference on our behalf this day,
by quieting the minds of those we had to labour with,
whereby the yoke was made easy and the burden light.

First-day, our first visit was to an aged couple,
whose situation every way appeared deplorable; destitute of outward comforts, and,
from remarks which escaped their lips,
there was reason to fear they were totally unacquainted with the Comforter within.
We laboured to bring them to a proper sense of their dangerous situation,
but all appeared of no avail:
we could not divest our minds of a fear that ignorance
was not the cause of their lamentable situation:
they were on the very verge of eternity,
but a confirmed indifference prevailed respecting things of the greatest importance.
We left them under painful impressions:
may this case prove a stimulus to us to seek for holy help,
to use all diligence in the faithful performance of every religious duty,
during our few remaining days here below.

Our next call was at the cottage of another aged couple, if possible,
more void of outward comforts than those we had just left,
but evidently abounding with that inward consolation which sweetens every bitter cup,
which in the ordering of Divine Wisdom may be permitted to be dispensed.
The tender frame of mind we found them in, and the gratitude our visit excited,
enabled us to go on our way under some degree of rejoicing.
After other visits to cottages, we visited a first-day school,
held at a meeting-house called a Bethel, where about two hundred children are educated:
we first had a sitting with the children, and then with the managers by themselves,
during which we set before them the necessity to experience on
their part a correspondency of conduct and converse with the doctrines,
precepts, and example of our holy Redeemer,
in order that their endeavours for the children`'s
future welfare might be blessed to them:
our visit was kindly received.
A room offered to hold a meeting in, was accepted, and about forty persons assembled:
it was conducted with much quiet,
and we had reason to believe the people departed satisfied.
This day`'s work has afresh confirmed us in the belief, notwithstanding the rough,
uncultivated manners of those we visit,
that there is something stirring among them that is precious:
in some places it appeared to us that it might be truly said,
the fields were white already to harvest:
O for faithful labourers by example! may it please
the Divine Husbandman to send such among them.
What cause is there for thankfulness on our parts,
that we have been favoured with holy help, as I humbly hope,
whereby another day has been well closed.

Second-day, we bent our course to Downend;
in the first cottage we entered we found three small children left quite by themselves.
Inquiring after their parents, we found that the father had been killed in a coal-pit,
and the mother was gone out to a day`'s work.
We could not but deplore their unprotected situation,
and yet we had met with more pitiable cases,
much larger families left to struggle almost with starvation.
The repetition of the same language almost daily assailed our ears, "`My husband,
my sons, were killed in the pit.`"
The destitute situation in which these widows and their fatherless children are left,
was cause at times of mourning to us,
especially on observing the apparent indifference
manifested by some of the men thus employed,
to the dangers to which they are daily exposed.
When we endeavoured to awaken them to a true sense thereof,
and persuaded them to seek to the Almighty for help to live in his fear continually,
and thus be prepared to leave this world,
should it be their lot suddenly to be called out of time,
some of the more thoughtful would reply,
that when they did strive to turn their attention towards these subjects,
the largeness of their families, the high price of provisions,
and their difficulties were such,
that these cares and perplexities dissipated their good thoughts and desires.
Willing as I trust we were to sympathize with them under their accumulated difficulties,
I am persuaded our feelings fell very short of what must at times have been their experience.
Many were the visits accomplished this day to the habitations of misery and woe;
nothing but a sense of duty could have supported our minds and carried us through:
it closed with a meeting of upwards of thirty men, women, and children.

Third-day morning, we bent our course towards Kingswood,
and met with some truly seeking minds.
We had an opportunity with a professor and his wife,
at whose house a meeting is held weekly by some of the society of Methodists.
We encouraged them to be in good earnest,
frequently to consult the Divine law within them, and to seek for holy help,
that the general tenour of their conduct and converse might correspond therewith:
we reminded them also of the conspicuous situation in which
they had placed themselves among their neighbours,
whose eyes would be upon them.
Although this day we were made sad by beholding the
abject situation of so many of our dear fellow creatures,
destitute, as they appeared to be, of every outward comfort;
yet our minds were also comforted under a hope,
that if the work of righteousness was allowed to go forward according
to the will of that Almighty Power who had begun this good work,
their outward condition would become so improved,
that their example would spread and prevail among their neighbours.
Notwithstanding the depraved countenances of some with whom we sat,
the rough and uncultivated manner in which they at first received us,
and the unwillingness they manifested to attend to our entreaties,
it rarely occurred but that at our parting some proofs were manifested of their sense
of the need there was for them to be in good earnest about their immortal souls.
This day closed with a large meeting of colliers, their wives and others,
many of whom appeared to be reached:
the time of silence being owned by the over-shadowing
of the immediate influence of the Spirit of Christ,
the way was prepared for the reception of what was communicated,
whereby many of them were humbled and contrited before the Lord.
When the meeting closed,
several of the company requested they might be remembered again in the same way:
may the praise be given to that Almighty Power, who, when he calls to the work,
fails not to give strength proportioned to the trials of each day.

Fourth-day, our first visit was to a young man, a collier, who,
from his own acknowledgment,
had been awakened in an extraordinary manner to a sense of his sinful state;
strength had been mercifully given him to break off from his wicked practices,
and to turn his back upon his evil associates.
Having run well for a time,
he became united in membership with the society of the Methodists,
but through unwatchfulness, sorrowfully lost ground again;
hereby crucifying the Son of God afresh, and putting him, as he acknowledged,
to open shame, by totally deserting every place of religious worship,
and joining himself to his former wicked companions.
His mind appeared to be awfully impressed with a sense of
the deplorable situation he had plunged himself into,
and the sad consequences that eventually must result,
without a change in his present mode of spending his time,
which change he declared he despaired of ever being favoured to witness,
giving it as his belief no door of hope would ever be opened to him.
We deeply deplored his situation, and as ability was afforded,
laboured to encourage him to seek earnestly for the return
of that help which he once had found to be all-sufficient.
He appeared to receive our visit kindly.

Our next visit was to a collier and his wife, in profession with the Wesleyan Methodists;
the man appeared fast advancing to his final close, but in such a sweet,
resigned frame of mind, that our sitting with them was as a cordial to us, labouring,
as we had been, under the painful feelings which our last visit had excited.

Fifth-day, we went to Kingswood; and made several visits.
In the afternoon we had a meeting in a room used sometimes by the Methodists,
and another in the evening in a different direction, both to good satisfaction.
At the breaking up of each the people importuned us to have another meeting with them.
Sixth-day we went to Listen parish: our first visit was to an aged couple;
the woman had been confined to her bed five years,
to whom we were enabled to impart such counsel as made our visit acceptable,
if we may judge from the affection they manifested at our leaving them.

The next two cottages we visited were occupied by widows,
whose husbands had been killed in a coal-pit: they were left in a destitute situation,
so that they were obliged to force their boys to work in the pit
almost before their strength was equal to the labour required,
to get bread for the family,
and thus they were thrown into the society of those
whose example was likely to corrupt their morals.
How should the very recital of cases like these,
produce gratitude in the minds of both parents and
children who are not placed in such trying situations.
Should it not raise the heart-felt inquiry,
What shall I render to the Lord for all his benefits?
and ought there not to be a willingness to sacrifice all he is calling for?
My companion feeling drawings in her mind to have a meeting in this neighbourhood,
it was concluded to accept of the use of one of these cottages for the purpose,
and that notice should be given for ten o`'clock on first-day morning.

Our next visit was to the poor but comfortable cottage of a blind woman,
who lived alone and was far advanced in life.
We found her busily occupied in scraping and picking potatoes,
which she performed with great dexterity.
She informed us, with expressions of gratitude,
that the parish allowed her two shillings and sixpence per week,
and this we understood was the whole she had with certainty to depend upon.
We considered her as perfect a picture of contentment as we had met with.
I could not see in her helpless condition, for lack of sight,
how she could spare anything for rent, and therefore concluded the cottage was her own;
but questioning her on this subject, she replied,
her cottage belonged to her next neighbour,
and to satisfy him for the use of it she weekly washed the linen for his family,
herself finding soap and firing; this to us appeared the more extraordinary,
having no means, we found, to heat her water but in an iron pot on the range,
which she told us was carried by herself and poured into the wash-tub,
to do which appeared almost incredible; it surprised us she had escaped injury.
On inquiry, we found her statement to be correct, and that she was a clean washer:
the neatness of her cottage, the cleanliness of her apparel, though very old,
was to us striking, but above all, her state of mind,
the whole theme of her converse abounded with gratitude and praise
for the bounties heaven was daily bestowing upon her.
She was frequently the subject of our conversation and admiration during the day,
affording an instructive lesson of real contentment,
with what by many would be accounted miserable fare and very great deprivation.

We proceeded to Warmley, making calls as we passed along;
one on a young woman nine months confined to her bed from ill health;
but in addition to her bodily suffering, during our opportunity with her,
it appeared she was labouring under distress of mind,
which she said arose from her class-leader having deserted her,
she being in connection with the society of Methodists.
After sitting awhile in silence, I asked her,
if she had not reason to fear she had placed too much dependence on her class-leader,
and not enough looked to the Lord with that single
eye and simple dependence he called for;
she acknowledged she believed it had been the case.
I advised her to consider her class-leader deserting her,
as permitted in mercy to bring her to a true sense how little,
instrumental help is to be depended upon,
and to drive her home to the only sure help in herself.
I added,
that there was reason to fear in these class-meetings
not a few preciously visited of the Lord,
have been excited to a premature disclosure of his merciful dealings with them,
thereby lavishing that on others which was only designed for their own help and strength,
and thus they have had nothing left for themselves
to look to or lean upon in times of proving;
this she acknowledged she believed had been the case.

After recommending her to the best of all leaders, in herself,
we parted under a hope that her mind had received some consolation by our visit.
We then made a call at the dark, miserable abode of a collier,
who told us he had a wife and nine children;
of whom four sons had just returned from their work in the pit.
The man appeared to be seriously disposed,
and thoughtful about the best welfare of his numerous family: he,
with his wife and children, manifested satisfaction for the visit we paid them,
after which we returned home.

Seventh-day, we went to what is called the Cock-road,
about four miles from the city of Bristol, notorious for more than half a century,
as being the settlement of persons who are called the Gang.
The chief part of them, it has long been known, live by plunder, robbery, coining,
horse-stealing, and every evil practice within their reach,
and have long been a terror to Bristol and the neighbourhood;
all attempts to get rid of them having as yet proved unavailing.

First-day we went to Wormley-common,
where a meeting was appointed to be held in a cottage:
we found about fifty persons assembled.
We were much favoured during the time of silence,
by the presence of Him who was graciously pleased to promise
to be with those who are gathered in his name,
of which number we hoped some of our company were.
When the meeting closed, a man of respectable appearance came up to us, saying,
he hoped good had been done by the meeting,
and that he believed we had been rightly sent into this dark corner of the earth:
he wished we could see it our place to come more frequently,
not doubting but it would have its service.
In the afternoon we attended a meeting in another part of the common,
which was large and proved satisfactory.
After taking refreshment we proceeded to Kingswood,
to attend a meeting at six o`'clock this evening.
The weather proving wet, we expected a small attendance,
but the place was so crowded that many could not get seats; notwithstanding which,
and their being unacquainted with our manner of silting together in silence,
the meeting was agreeably conducted, and ended satisfactorily.
Thus closed a day of exercise, to the praise of Him, be it said, who, when He puts forth,
goes before,
and prepares the way for the reception of the seed
he gives to scatter abroad among the people.

Second-day, we went to the Cock-road, and continued visiting from house to house,
until we felt the need of our dinner, which we generally took in our chaise.
While taking our repast, we were surrounded by a number of poor children,
among whom was a girl apparently about sixteen years of age,
clad as miserably as can well be conceived.
On asking her why she did not go to work, she told us, work was not to be had; saying,
"`Sometimes I have food,
and other times I am obliged to go without:`"--she
pointed with her finger where her mother lived,
and said she was at home.
Having finished our repast, we believed it would not be best to pass her by,
and proceeded to the house the girl pointed to,
which we found to be an abode of misery in every sense of the word.
The mother, this girl, two other women, and three children were living together,
obtaining what little support they had by their evil practices.

We sat down with them,
and endeavoured faithfully to lay before them the tendency of their manner of life,
as it respected themselves, their children,
and others whom they were instrumental in drawing into their company,
and the punishment that awaited them without true repentance.
At first they appeared to soar above what we said, and resented our interference,
as they termed it; but we were mercifully carried above fear,
strength being given to plead with them,
until the Divine Witness in their minds was evidently reached;
and they were so brought down, as to evince some degree of contrition, acknowledging,
at our parting, their full belief that we wished them well,
and that they were obliged to us for the counsel we had given them.
Humiliating as the interview was,
we left them thankful that we had been strengthened to maintain our post.
In the afternoon we had a large meeting with some of those called the Gang;
which was quiet, and openness was manifested to receive that which was communicated.
The days becoming very short,
and the roads being in such a state as not to admit of our going quickly over the ground,
together with our distance from Frenchay,
appearing likely to prevent our keeping at our work
as late at night as we conceived was necessary,
lodging was provided for us in the Cock-road.

Fourth-day, we attended meeting at Frenchay,
which I trust was a time of favour to the visited youth;
after which we went again to Cock-road.
The first visit we made was to a woman who, we were informed,
kept as disorderly a house as any in the neighbourhood,
and was a very immoral character herself.
On our laying before her the guilt in which she was implicated,
by harbouring the company she did in her house,
she at first treated our remarks with contempt, saying,
she knew she must answer for her conduct herself:
but by degrees she evinced a willingness to receive what we had to say to her,
assuring us of the desire which she felt to conduct
herself more orderly than she had done,
and not to allow young persons to resort improperly to her house as heretofore.
She acknowledged, at our parting,
she believed we wished her better than she had done herself.

Fifth-day, we went to Cock-road and made many visits;
much openness to receive us and our testimony was manifested.
In the afternoon we proceeded to Hill-mount,
where a meeting was appointed to be held at four o`'clock,
but from some cause unknown to us,
the people did not generally assemble until six o`'clock; notwithstanding this,
although it proved a close exercise both of faith and patience,
yet when the meeting closed, a hope accompanied our minds,
that we had been in the way of our duty,
and that the labour of this day would not prove in vain.
At the close of the meeting, we took up our first night`'s abode in the Cock-road.

Sixth-day, proceeded to the parish of Briton.
Our first call was at the miserable abode of five single sisters; they existed together,
for it could hardly be called living.
One of them appeared far gone in a decline, possibly for lack of necessaries;
another was afflicted with fits; a third looked starving from hunger and cold,
exhibiting a ghastly countenance.

On our approach, one of them made her escape, with scarcely clothes to cover her.
The habitation, within and without, as well as its inmates,
exhibited the most striking picture of human misery
an artist could be supposed to portray--neither bedsteads,
bed, blankets, sheets, pillow, bolster, table, chair, or household stuff of any kind,
except two stools, and some broken earthenware.
On inquiry how they passed these cold winter nights,
we were informed they laid down on the floor, which was paved with large stones,
before the best fire they were able to make up, the warmth from which,
with the few rags their cottage furnished, supplied the lack of bed-covering.
They informed us their employ had been heading pins, but their employer had failed.
Two of them had one shilling each from the parish,
in addition to one shilling more which they earned,
which was the whole they had to subsist on.
We could not but commiserate their trying allotment in this world, and we endeavoured,
as ability was afforded,
to turn their attention to the alone sure way of securing that inward help and support,
which would not fail them, but would conduct them safely through all the trials of time,
producing the joyous fruits of righteousness,
and ultimately land them safe where no more sorrow will be known.
My companion stated their case to a Friend of Bristol,
and bedding and other articles were furnished them.

We proceeded to finish this part of Cockroad, and made many visits,
some of which were relieving to our minds.
We halted at a public-house, where we met a considerable company of men,
who appeared to live in idleness and fulness of bread, producing wantonness;
and we had no doubt, from circumstances, that they were a party of those called the Gang;
with whom, I believe we may say,
we endeavoured to deal plainly--the fear of man being mercifully taken away.
They behaved towards us with much civility,
and appeared to receive kindly what we had to declare.

We had a large meeting this evening at Hill-mount, which was conducted in a quiet,
orderly manner.
The meeting holding late, the night very dark, and by-roads to travel,
roads as bad as can well be conceived, our journey appeared perilous;
but we were favoured to reach our lodging safely, for which we felt thankful.
We did not apprehend danger from the Gang, among whom we were travelling,
not merely from the information we received, that we need not fear them day or night,
for no one should insult us,
but from being favoured with full confidence in the superintending care of Divine Providence;
short of which,
what could have supported us in travelling generally late in the evening in such a neighbourhood,
where others are afraid to travel alone in the day time.

Seventh-day, we made a few calls, and arranged for meetings.
First-day morning, a meeting in a cottage near our lodging, was thinly attended,
but quiet, and to us comfortable.
At the close, observing a man turn into the adjoining cottage, we followed him,
taking our seats: from his own confession, during what we had to communicate,
he proved to be one of the Gang:
we remonstrated with him on the danger to which he
exposed himself by violating the laws of his country,
and set forth the peace of mind that would result
from getting his livelihood in an honest way;
he acknowledged he was fully aware of these things, and that he was far from a happy man.
On my telling him he passed his time amidst hope and fear,
hoping at times he should escape being detected in his evil practices,
but fear at other times so tormenting him as almost to overcome hope;
he said it was truly descriptive of his situation; adding,
the way he was getting his livelihood was the way his father had brought him up,
and he could not live as he did by hard labour, not having been brought up to it,
and pay five shillings a week to the parish for three children;
but he must continue his course of life, namely: to plunder, trick,
and cheat every way he could.
On endeavouring to turn his attention seriously to
consider the awful situation into which,
if he continued this same course of life, he would plunge himself eternally,
he replied with apparent feelings of horror, he must leave all future consequences.
He manifested great frankness; no disposition to put by what he knew belonged to him;
but expressed, as if he really felt what he said,
that he believed we desired better things for him than he was able to do for himself.
He appeared about twenty-six years of age, of a fine, strong, healthy constitution,
was unable to read, and had never, but twice, he told us,
entered a place of religious worship.
We parted from him, sorrowing on his account, committing him to that Divine Power,
who yet remains all-sufficient to work wonders for the children of men,
even for the most rebellious.

We proceeded to Cock-road-house,
where a meeting was appointed at two o`'clock this afternoon, which was largely attended,
the people conducting themselves in a solid manner.
We then went to Hill-mount, where a meeting was to be held at five o`'clock this evening;
the house was crowded, and the quiet preserved was remarkable, considering the rough,
uncultivated company we were among.
The people appeared to sit quietly,
and to be attentive to the truths of the Gospel given us for communication;
and we were encouraged to hope this would prove a season of profit to many.
That the praise might be given to whom it belongs,
both by the hearers and those who were counted worthy to
proclaim the truths of the Gospel of life and salvation,
was the desire of my heart at the close of another day: to Him are we accountable,
who sees and knows the heart, and all our motives of action,
and who will reward us accordingly. Romans 2:7.

Second-day, 2nd of eleventh month, we attended the Monthly Meeting at Frenchay,
at which we gave in a report of our proceedings thus far,
with which the meeting`'s satisfaction was expressed,
accompanied with acknowledgments of an evidence that
the Good Shepherd had in mercy been mindful of us.
Third-day, we went to Hill-mount: from the badness of the road our carriage broke down:
we were obliged to return to Frenchay.

Fourth-day, we went to Cabra-heath: our first visit was to the cottage of a collier,
where a considerable number of his neighbours, in addition to his own family,
soon collected.
A young woman who came in manifested much disposition to levity,
but that which was delivered reaching her condition, she became serious,
and parted from us,
giving evident proof that a degree of religious thoughtfulness was awakened in her mind.
Our next visit was to a collier and his wife,
who were at the meeting on first-day evening, and now welcomed us to their cottage:
the man dispatched messengers to invite his neighbours, and we had a numerous assembly.
Utterance was largely given, and great openness evinced to receive the word preached;
and we parted under a humbling sense of our heavenly Father`'s love:
fresh cause for the acknowledgment, that all is of mercy, unmerited mercy,
and to set up the Ebenezer, and say, our help has come from the Lord.

After making a few more calls, we returned to our lodgings.
Some of our company this day, in a feeling manner, expressed their belief,
that our feet having been turned among the poor inhabitants here,
was designed by the Almighty in mercy to be a fresh call to them.
One poor collier, at the close of an opportunity, expressed himself nearly as follows:
"`If we miss so great salvation thus frequently offered to us,
and again renewed and brought home to our very houses,
surely it will be more tolerable for other wicked
nations in the great day than for us.`"

Fifth-day, proceeded to Cabra-heath.
Our first call was at the cottage of a young man,
whom we found lounging at his fire-side,
appearing as if he had been out on a night`'s ramble;
and his house abounded with good things.
It seemed that we were not welcome guests, for he treated our observations with contempt:
notwithstanding which, we continued, as matter arose in the line of apprehended duty,
to communicate it to him; and after awhile he appeared rather softened down,
and evinced more willingness to receive our counsel:
he parted from us in a friendly manner,
and did not attempt to clear himself from the bad
practices that were brought before his view.

We made several visits on our way to Cabra-common.
As we were passing along, two men caught our eye, employing themselves in catching birds;
a way in which some of the Gang spend a part of their time,
as a cloak for their nightly depredations.
We attracted their notice,
and our proceeding being by this time noised abroad among them,
they manifested a determination to avoid us, and separated to the right and left,
whereby I expected we should lose them.
But one being an old man, and having a high gate to get over to make his escape,
I was upon him before he was aware.
On my requesting him to give us his company in a cottage hard by, he consented.
My companion saw the other man cross the road not far from us and go into a cottage,
to which I prevailed on the elderly man to accompany us.
On our reaching the cottage, the man my companion saw go into it was not to be seen;
and on inquiring for him, the woman of the house replied, he had gone out again.
My companion cautioned her against persisting in an untruth, saying,
she saw him come into the house,
and there was no back way for him to make his escape again;
on which the woman called out, "`Richard, come down stairs,`" but no Richard replied:
she repeated it, but in vain.
Fully believing, if we preserved peace of mind, we must not miss seeing him,
I went to the stairfoot, calling out, "`Richard, come down stairs,
or I must come up and fetch you down:`" no reply being made,
strength was given me to go up into his chamber,
where I found him crouched down behind the head of the bed.
I should have been as nothing in his hands, a large-boned, hale young man,
had he resisted me.
I told him we wanted to have his company, took him by the collar from behind the bed,
and sent him down stairs before me,
on which he quietly took his seat in the chimney corner: after a pause,
my companion began to address him in such a manner
that his wife`'s countenance manifested astonishment,
directing her eyes towards him, as if she wished him to receive it.
He sat very quietly the whole time,
and although at first he appeared disposed to stout it out, yet, after much labour,
and endeavouring to lay before him the sad consequences that he must expect would
eventually follow his continuing to pursue his present mode of getting a livelihood,
he became more tender.
I felt it laid upon me before we parted to remind him,
that if he continued to follow his wicked practices,
his father having brought him up therein would avail
him nothing in the great day of account,
not being aware that the old man was his father.
From the kind manner they all took leave of us,
we were disposed to hope the labour bestowed would not all be in vain;
and truly thankful we were that we did not easily give up to discouragement.

Sixth-day, we again proceeded to Cabra-heath and Wollard`'s-common:
for the present we have left the Gang, and are now among hatters,
many of whom appear under a religious concern for their soul`'s welfare;
yet from the anxiety they are under to provide for their numerous offspring,
it is feared their good desires are too frequently overpowered.
From the high price of bread they had been compelled
to begin upon their potatoes before the usual time,
which, it seemed probable, would not carry them through the winter.
These scenes of misery and woe, in addition to our inward exercises,
at times plunged us into suffering.
This day closed with a visit to a public-house in the Cock-road,
which afforded us satisfaction.

Seventh-day, we went to Wollard`'s-common.
Among those we visited this day was a poor collier:
he informed us that a few years ago his mind was awakened to a sense of his sinful state;
and he manifested a truly religious concern on his
own account and on account of his family.
From his numerous offspring and the high price of provisions,
he appeared struggling with great poverty;
but this he assured us was not his greatest trouble;
his wife refusing to unite with him in going to his place of worship,
and in properly caring for the welfare of their children, he said,
was his greatest trouble.
His wife sitting by, confessed she could not plead lack of time:
but a lack of inclination in herself to go to a place of worship, seemed the real cause;
she acknowledged she saw the benefit her husband`'s becoming religious had been to him;
saying, before this change took place he was a wicked man,
and would curse her for hours at a time.
Nothing we had to say seemed to make any impression on her mind;
though she parted from us kindly.
After this opportunity we collected the hatters generally in this district,
with whom we had a religious meeting, and one afterwards with a young couple,
which we had cause to believe was to mutual satisfaction.

First-day, we attended a meeting appointed at our request in the Baptist meeting-house,
at Hannam, which was large,
and we were encouraged to hope was a season of profit to many.
On our way home we called at a house, said to be a haunt for disorderly persons,
particularly on a first-day.
We found many young men standing outside, whom we invited in, with which they complied,
and took their seats with those who were already there.
We had an opportunity with the woman of the house first,
but in the presence of her customers;
we laid before her the wickedness of her harbouring the company she did,
and allowing such evil practices to be going forward: we then addressed the young men,
relative to their spending their time in that unjustifiable manner.
Some appeared to receive our advice kindly,
and others manifested more of a hardened disposition.
Having endeavoured to acquit ourselves faithfully,
we returned home with hearts abounding with gratitude to Him,
who was our Alpha and continued to be our Omega.
This day we had a sitting in the family with whom we quartered,
which closed a trying day`'s work.

Second-day, we went to Cabra-heath: in the first visit we made,
on taking our seats in the family, so much levity was manifested that we were much tried,
but by endeavouring after ability to endure all with Christian patience,
seriousness gradually spread over the minds of our company,
and we had a favoured opportunity together,
and at our parting were solicited by the family to repeat our visit.
How can we any longer doubt the sufficiency of Divine goodness to make way for us,
where the eye of human reason, looking on the discouraging side of our situation,
can see no way for us to proceed.
May these instances of Divine interference prove like a nail fastened in a sure place,
is the prayer of my soul.
After a similar visit we went to the smelting works, and from there to the poor,
but peaceful, cottage of a collier, with whom and his family we had a precious meeting.

Fourth-day, we went to Cabra-heath: on our way a man on horseback made towards us,
and my companion believed he was one of the Gang,
as we began by this time to have a pretty correct idea of them from their dress, manners, etc.
Being desirous we might have his company, I stepped out of the chaise near a cottage,
requesting him to go in with us, which he complied with.
After some time spent in silence, we opened to him such matter as came before us,
respecting his manner of life, to which he did not demur,
but confessed he felt at times the great need there was to amend his ways;
he appeared quite willing to receive what we had to say,
expressing the obligation he felt himself under for it,
and requesting we would visit him at his own home,
giving us his address for that purpose.
We made many visits this day to colliers and hatters,
some of whom we could not doubt were thirsting after the sincere milk of the word,
that they might grow thereby; to whom our spirits were nearly united.

Fifth-day, our first call this morning was at the miserable abode of a man,
who informed us he was seventy-five years of age.
By a hurt in the coal-pit, thirty years ago, he lost one of his legs;
about the same time his wife and ten children were taken with a fever;
shortly after their recovery his children all had the small-pox;
two years ago his wife became deranged, set fire to her clothes, and was burnt to death;
since which, in his absence, his house was broken into,
and part of his bedding and wearing apparel taken away:
all which he related with the utmost composure, and such sweetness of countenance,
as indicated the truth of what he added;
that he hoped through all he had been preserved from murmuring.
A more perfect example of contentment and Christian
patience I thought I never before beheld.
His recital of the precious effects which his various trials had produced on his mind,
was to me a very instructive lesson,
nothing that escaped his lips in the least degree
manifesting a desire to receive pecuniary aid.
At six o`'clock we attended a meeting held in a house
belonging to the followers of George Whitfield.
The evening being wet, and roads across the common deep in mire,
we expected a small meeting, in which we were agreeably disappointed: it gathered early;
the attendance was large, and we had a comfortable time together.

Sixth-day,
our visit to Wollard`'s-common this afternoon was attended with a comfortable hope,
that there are many here under a precious visitation:
that nothing may be permitted to retard the work of salvation,
has been the prayer of my soul.
At six o`'clock this evening we attended a meeting at the smelting works,
where we had reason to believe many received the word preached, with gladness.

Seventh-day, we bent our course to the upper road from Bath to Bristol,
and accomplished many visits, in most of which my companion had good service,
but my lips were sealed in awful silence through the whole of the day.
First-day, we visited a school in a dissenting meeting-house on Wollard`'s-common:
the labour we were enabled to bestow on the children
and their teachers appeared to be well received.
During our visit in this neighbourhood we met with several
young men whose education had been wholly neglected,
who could not be prevailed upon to attend the first-day schools.
I felt drawings in my mind to visit the cottage of a newly married couple,
the husband being of this description;
after much entreaty he was prevailed upon to accompany us to the school,
and have his name entered as a scholar,
which afforded us some hope others would be encouraged to follow his example.
We then proceeded to the first-day school at Cock-hill,
where we met with a considerable number of children under the care of teachers.
Little seemed to be required of us towards the children,
but our minds were brought under exercise on behalf of the teachers,
and we set before them the necessity of endeavouring to know their whole conduct
and converse to be in unison with the doctrines and precepts of Christ,
whereby their endeavours in this good work,
will be blessed to the children under their care.

An aged couple, living in the school-house, attracted my attention;
and seeking for Divine help,
I was strengthened to be faithful in ministering what appeared to be the counsel
of my Divine Master for them tears rolled down the cheeks of the woman,
but the man`'s mind did not appear capable of receiving what was, offered.
In the afternoon we attended the school in the Upper-road:
here little more occurred than our making a few observations.
We took tea at the house of our kind friend Stevens,
who had taken an active part in the establishment of these schools.
In the course of conversation respecting our visit to Cock-road,
among those denominated the Gang,
and the willingness they generally manifested to
receive us and attend our appointed meetings,
he informed us that the members of their society
had taken much pains to have meetings with them,
changing the times and places for holding them in their neighbourhood,
in hopes of accommodating them, but these attempts had proved fruitless.
We had the company of a preacher of the Wesleyan persuasion,
who made us the offer of their chapel for a meeting, assuring us of a large congregation;
but not feeling that which warranted our holding a meeting here,
we declined accepting this kind offer,
although we were given to understand the people would be disappointed,
if we left the neighbourhood without having a meeting with them.

Third-day, we proceeded to the great school near Cock-road;
and in most of our visits this day my companion had good service.
Here this arduous engagement,
which we have believed ourselves called upon to pursue from day to day,
was brought to a peaceful close, accompanied with the language of.
Return to your rest, O my soul,
for the Lord has been bountiful in administering his help in the time of need.
Fourth-day, attended meeting at Frenchay,
at the close of which we made a further report of
our proceedings to the satisfaction of our friends.
Fifth-day, I took leave of my kind companion and her family, proceeded to Bristol,
and attended meeting there.

Seventh-day, left Bristol for my own home,
which I was favoured to reach and found my dear wife well.
Those called the Gang, and the colliers generally, had large families of children;
but to us it was lamentable to understand,
but very few of them who were living together as husband and wife, were married.
As some of the colliers had joined in membership with the Methodists,
having prayer-meetings at their houses,
I found it required of me to lay before the leading members of this society,
the care that was necessary, not to admit into membership with them any,
until they were married in a way which the laws of
the land demand to make it a lawful marriage;
otherwise they would be countenancing such an iniquitous practice.
The following extracts from the printed circular of the
Kingswood Association for the suppression of these depredators,
may furnish some idea of the state of desperate wickedness,
many of those we have been visiting must be sunk into;
and yet their conduct towards us was unimpeachable.

"`Whereas,
the alarming depredations continually committed by a very
daring and daily increasing combination of thieves,
extending their ravages for many miles round the country,
and well known to reside chiefly in this neighbourhood, have induced a few persons,
desirous of promoting the welfare of the community,
to unite their efforts in attempting to form a society
for the suppression of such enormous evils;
in order to adopt, with unwearied diligence,
such measures as may tend to produce the desired effect,
by striking at the root of such a system of iniquitous practice, as, it is supposed,
never was equalled in any other part of the kingdom.

"`The committee, in pursuance of their appointment, have met at Kingswood-hill,
and resolved (in an entirely gratuitous manner,
and with unremitted attention,) to use every exertion in
their power to promote the designs of this institution;
and having acquired a comprehensive view of this singular system,
as to the different modes in which their diabolical purposes are accomplished,
conceive it not irrelevant to detail a few particulars.

"`This scheme of unparalleled enormity demanding such earnest attention,
has been progressively and uninterruptedly maturing for a long series of years;
and such is the nature of their establishment,
that whole families are dependent on this combination for maintenance;
many hundreds of the younger branches are well known
to be now in actual training for the like purpose.
It is also ascertained,
that they are in the habit of decoying labourers from their accustomed employment,
and formally admitting them into their society.

"`Great numbers of hucksters, in this and the surrounding neighbourhood,
are in alliance with them;
the venders of the goods are seen passing with cart-loads
to and from different places by night,
none presuming to interrupt them;
and although it seldom occurs that any of these plunderers
succeed in securing their booty,
without being recognized by colliers passing to and from the mines,
before they arrive at their several places of residence,
yet they consider themselves as inviolably secure;
for any one daring to impeach them would endanger both property and life;
consequently ordinary means adopted by societies in general in offering rewards,
would be altogether abortive.

"`Should the statement of these circumstances create surprise,
or be deemed an exaggeration, suffice it to observe, that the committee,
several of whom have been long resident in Kingswood,
close observers of the transactions alluded to,
and for those peculiar reasons selected as most suitably
qualified to meet the exigencies of the society,
stand pledged to give the most positive proof of their existence,
which is sufficiently notorious to the majority of the inhabitants of these parts.

"`The great number of persons resident in the neighbourhood of Kingswood
might reasonably have encouraged us to expect extensive assistance:
such, however, is the astonishing terror prevalent in the minds of very many,
arising from an apprehension that the incensed miscreants would
reward their interference with still greater destruction;
and so many are prevented from aiding this association
on account of relationship to them,
that when it is considered, in addition hereto,
that thousands are connected by receiving and vending the goods,
it will not appear surprising that very few, comparatively,
remain sufficiently virtuous or courageous to unite with us;
and it must be needless to hint at the unparalleled enormities we have to expect,
unless such prompt and energetic measures be adopted as the nature of the case requires.
Under the impression, therefore, of their very urgent necessity,
the committee have determined on such cautious and vigorous
steps as are very likely to accomplish their designs;
and hope, through the united exertions of many of the respectable inhabitants of Bristol,
Bath, Kingswood, and their vicinity,
to be soon enabled to proceed to successful operation.`"
