== Chapter XII.

1820+++.+++ 7th of fifth month.
Left Hitchin, my present place of residence, to attend the Yearly Meeting,
and walked to Hertford.
First-day morning, attended meeting there,
in which I hope I was favoured faithfully to acquit myself.
In the afternoon I proceeded to Tottenham,
and was favoured to reach it in time for the Evening meeting,
where I met with several strangers like myself on their way to London.

Second-day, proceeded to London: attended the first sitting of the select Yearly Meeting,
wherein fresh cause was experienced to unite in the acknowledgment
that holy help was mercifully vouchsafed to us.
Fourth-day,
attended the first sitting of the Yearly Meeting for the general concerns of the Society.
Towards the close of the sittings of this meeting,
my mind was exercised with an apprehension of duty
to pay a visit to the women`'s Yearly Meeting;
but discouragement prevented my coming forward in time:
fearing the consequences of my unfaithfulness, should the women`'s meeting separate,
as it was understood their present sitting would close their business.
I laid my case before the meeting, which set me at liberty.
I endeavoured to do my best to obtain relief; but, as I have often found,
unfaithfulness in not keeping to the right time in my religious movements,
causes weakness and dismay.
After the Yearly Meeting, I returned home, which to me was an abode of suffering;
but I endeavoured to keep quiet, hoping as my disobedience had not been wilful,
way would open for my relief,
and I frequently supplicated that I might be favoured
to abide the day of the Lord`'s judgments.

The necessity of taking up my pen, gradually opening before me; when the time was come,
I sat down with my mind turned to the Lord;
on which it was laid upon me to address the members
of our religious Society in Great Britain and Ireland.
As the various subjects arose, I saw that I must speak the whole truth.
After devoting several days to it, I copied it over; and after it had undergone revision,
and a fair copy was made for the press,
I called together the members of the select meeting, to whom it was read:
some trifling omissions were proposed, with which I felt easy;
and no objection being made to my printing it, I put it into the hands of the printer,
ordering a sufficient number to supply every family in the different
Quarterly Meetings of the United Kingdom with a copy.
Having corrected the press, and ordered their distribution, I returned home,
making melody in my heart to the Lord, who had thus in mercy supported me,
and brought me through this trial.
Here follows the address.

[.embedded-content-document.address]
--

[.letter-heading]
An Address to Friends in Great Britain and Ireland.

[.salutation]
Dear Friends,

In the first place,
let me put you in mind of the nature and importance of that religious profession, we,
as a Society, are making among men;
which I believe would be found to be above that of
every other society of professing Christians--namely,
the absolute necessity of our living, acting,
and moving in all our civil as well as religious engagements,
under the influence and government of the Spirit of Christ Jesus our Lord and Lawgiver;
that '`whether we eat or drink, or whatsoever we do,
God the Father may in all things be glorified.`'

This, my friends, is the chief corner-stone of our building, our fundamental principle;
therefore,
let us consider how far the general tenour of our conduct corresponds therewith,
how far we are each endeavouring earnestly to be found, in all things,
conformable to the example and precepts of the great
and holy Pattern of all Christian perfection,
of Him who has trod the path of temptation and trial before us,
but who rejected every snare of the enemy.
If this should not be the case with us, is there not a danger of our becoming to others,
who, from our exalted profession,
may be looking to us for example and encouragement in the way to the heavenly Canaan,
like the evil spies unto the children of Israel formerly;
or that our examples may prove as lets and hindrances to such,
instead of helps to press through difficulties and discouragements
towards the mark for the prize--which is,
'`You shall be holy, for I, the Lord your God, am holy;`' '`Be perfect,
even as your Father which is in heaven is perfect?`'

Let us remember, however, we may be at peace with ourselves by thus professing;
but not doing the very best in our power to attain this perfect stature of the Christian,
we are but branding ourselves in the estimation of the more serious and
thinking part of the community with the odious character of hypocrites;
neither do I believe that we escape at all times the like
censure from the more unthinking and irreligious part.
And let us remember, that the sad effects of thus dissembling will not end here;
for if this conduct be persisted in,
we must expect to incur the woe pronounced by our blessed Lord, '`Woe unto you.
Scribes and Pharisees, hypocrites; for you shut up the kingdom of heaven against men;
for you neither go in yourselves,
neither do you allow them that are entering to go in.`' For if
every one that names the name of Christ is to depart from iniquity,
is it not obligatory on the part of such as make the high and holy profession we do,
to endeavour to attain to such a state of purity of conduct and converse among men.

I believe our first Friends were raised up as a people,
to bear testimony to the sufficiency of that pure
principle of light and life in all mankind,
which would direct them in the way to the heavenly Canaan,
and strengthen them to walk therein.
They confirmed the truth of their testimony by the general tenour of their conduct,
giving ample proof to by-standers, that,
through submission to its holy appearance in their hearts and minds,
they were mercifully redeemed from the world and its spirit, not only from its pleasures,
but also from its treasures,
and were enabled to count all things appertaining to this life but as dross and as dung,
so that they might win Christ.

Hereby they became as an ensign to the nations, for the fame of them spread far and wide:
they became instrumental in the Divine Hand to gather souls unto God,
and had to proclaim the glad tidings of the church being added unto daily.

But alas, my friends! how is the gold become dim,
and the most fine gold changed! how is the love of God,
and that humility and self-denial so manifest in them, now, by too many among us,
turned into the love of other things, such as gold and silver,
and a desire to make an appearance of greatness in the world!
That these sorrowful reverses have taken place in too general a way among us,
as a Society, let the reports brought up from the Monthly to Quarterly Meetings testify,
especially as to a growth in the Truth, and convincement;
for it is truly distressing to sit at the Monthly Meetings when this query is answered,
and observe the difficulty and embarrassment the active members feel themselves
under to answer so as to pass the Quarterly Meeting without remark;
especially as respects the first part of a growth in the Truth,
which I understand to imply, an inquiry,
what individual advancement we are making towards the kingdom of heaven.

Yet, notwithstanding these sifting seasons so frequently occur,
for such I find them to be to myself, and so I doubt not they prove to many others,
they are at times as '`when a man beholds his natural face in a glass, and goes his way,
and straightway forgets what manner of man he was.`' For lack of abiding
enough under these renewed visitations of the Great Head of the church,
how evident is it, that we soon forget again our many deformities,
hereby adding sin to sin.
Is not this too much our situation as a Society at the present day?
Are not Monthly Meetings and Quarterly Meetings going on from quarter to quarter,
and from year to year, satisfying themselves with telling the same dismal tale,
'`We hope some among us witness a growth in the Truth!
Now, if the ground of this hope, where meetings venture thus far to express themselves,
were called for,
I fear it would not be found in the general to be that well-grounded
hope which gives victory over the world.
At other times, '`but little growth in the Truth,
and some convincement,`' '`but little convincement,`'
or '`no convincement appears among us.`'

Do not these things, my friends, loudly call upon us, as a religious body,
making a high profession, to be willing, each one for himself,
to enter timely into the closet of the heart,
and seek for Divine help to shut to the door thereof against carnal reasoning,
great natural acquirements, and love of the world,
which there is cause to fear have overpowered the better judgment of many among us.
Hereby, as we become willing to stand open to Divine conviction,
we may be favoured each one to see in what manner, and how far,
we may have contributed to this sorrowful declension,
and timely amend our ways and our doings;
seeing we are yet mercifully followed as a religious Society,
both immediately by the Great Head of the church, and instrumentally,
with line upon line, precept upon precept.
O, how applicable to His dealings, as respects our Society,
is the language of the Most High, formerly uttered, '`How shall I give you up, Ephraim?
how shall I deliver you, Israel?
how shall I make you as Admah?
how shall I set you as Zeboim?
Mine heart is turned within me; my repentings are kindled together.
I will not execute the fierceness of mine anger; I will not return to destroy Ephraim;
for I am God and not man; the Holy One in the midst of you:
and I will not enter into the city.`' May we no longer be
found walking unworthy of these His multiplied mercies,
but be prevailed upon to return to the good old ways,
that we also may be found in those paths of holiness of life and conversation,
in which our forefathers walked, under sore travail of mind and great suffering of body,
and waste of outward substance, through persecutions.
Oh! let us no longer be found trampling, as it were, upon their testimony,
by slighting the many great and precious privileges of this day of outward ease,
we who are uninterruptedly eating the fruit of the
vineyards and olive yards we never planted,
but which they were made instrumental to plant for us; thus making the way easy to us,
as it now is, to assemble for the purpose of Divine worship,
for transacting Society concerns,
and for the support of our various religious testimonies.
Lest, if we still continue to refuse yielding our necks to the same precious yoke of Christ,
which they took on them, and by so doing found it to be all-sufficient to bring down,
and keep down the spirit of the world,
that has now gained the ascendency over too many among us; by this their obedience,
giving proof, that although in the world, they were not of the world,
but at enmity with its spirit, its maxims, and manners,--dead, not only to its pleasures,
but so dead to a desire after its treasures,
that when in order to preserve a conscience void of offence in the sight of their Creator,
they were for faithfulness to his law and testimony, stripped of their outward substance,
they counted these losses of their earthly treasure to be gain.
I say, if we will not cast away from us these things,
which have led into captivity again to the world, to its spirit, its manners,
and there is reason to fear, many of its maxims, and deceitful ways,
our gods of gold and silver, of wood and stone,
our sumptuous and richly-furnished houses,
in some of which is displayed all the elegance the art of the upholsterer can devise,
(for it is lamentably the case that little or no trace of true self-denial
is now to be found in the habitations of many of our members,
and even of some who stand in the foremost rank,) lest,
in the day when the Almighty may see fit,
after long forbearing in love and mercy with this favoured nation,
to rise up and plead with it in judgment,
we should have the largest portion thereof administered unto us as a people,
and the declaration formerly uttered respecting the children of Israel
be fulfilled also upon the unfaithful members of our religious Society,
'`You have I known of all the families of the earth,
therefore I will punish you for all your iniquities.`'

By unfaithful members,
I would not be understood to mean exclusively those among
us who have cast off all restraint as to dress and address,
and are unfaithful in other branches of our religious testimony;
for these I have long been led to believe are not the greatest
enemies that the Truth has to contend with,
in the minds of the Lord`'s visited children,
whether of our own or other religious societies; because in our own Society,
such as these are not looked up to for example, and as respects the world more at large,
such are only known to be of us within the circle of their immediate acquaintance,
and by their thus becoming (if I may so speak) consistently inconsistent with our profession,
there is reason to apprehend they pass along as to conduct much unnoticed.
But I would wish the term unfaithful to be understood
to refer more immediately to those who,
in their garb and language, support the character of a consistent Friend;
but whose conduct with respect to their commercial transactions and manner of living,
their houses and furniture does not correspond with their religious profession,
but proves they are the friends of the world and not of Christ Jesus.
The fruits brought forth by such testify, that within, like the whited sepulchres,
they are full of dead men`'s bones and rottenness,
and that the spirit of the world is the governing principle in most,
if not all their actions among men.
How many among us are pursuing their worldly concerns, as if they counted gain godliness,
and not, as must be the case with the true disciples and followers of Christ,
godliness with contentment to be the greatest riches,
proclaiming in the language of conduct, that all is fish that comes to their net,
regarding neither quantity nor quality,
so there be a prospect of a good profit attached to it.
And how have the gifts which the god of this world
has bestowed on these votaries blinded their eyes,
many of whom, I doubt not,
were once favoured to see clearly the things that belong to peace and salvation.
O, these professing worldlings, who say, they are Jews and are not,
but whose fruits testify they are of the synagogue of Satan, I have been persuaded,
have been the greatest enemies to the spreading of our
religious principles and the enlargement of our borders;
those who maintain an uniform consistent warfare against the Babylonish garment,
but with all their might grasp at the wedge of gold,
and aim at making a splendid appearance in their way of living.
I believe no character is more odious in the estimation of those termed libertines,
than these,
especially where it is known they are taking an active part in Society concerns.
For in neighbourhoods where meetings are held,
it is pretty generally known by those out of the Society,
who are what the world calls our pillars; though it cannot be doubted,
that such must at times prove stumbling-blocks to honest inquirers after Zion,
and be instrumental in turning the blind out of the right way of the Lord.

So look to yourselves, my friends, you to whom these remarks apply,
you who have resolved to obtain an impossibility, and be heirs of two kingdoms.
Is it any marvel at all,
that so little fruit is to be found from the labour that has of late years been
bestowed by the messengers of that same Gospel our first Friends preached,
whose feet have been turned into the highways and hedges.
For I cannot doubt but that the word preached has
been both believed and received by many,
but on their comparing things with things,
the conduct of many among us has been found at variance with the doctrine preached,
and this even with some whom they considered to be seated as the Aarons and the Hurs,
by the side of these the Lord`'s messengers.
And doubtless many have left the meeting-place with sorrowful hearts,
and instead of resolving to pursue the path pointed out, towards the heavenly Canaan,
have formed this conclusion, that they had better remain as they were,
than have the feet of their minds turned into the way and not persevere,
as they clearly saw was the case with many among us.

Nor do the sad effects of this dissembling end here;
for I think I have frequently been able to trace
its sorrowful consequences to many of the dear youth,
as being one cause, why so few of them,
in this day of outward ease as to liberty of conscience,
are coming forward in the line of true usefulness in the Society and among mankind,
or helping the good cause by the religious exercise of their spirits in meetings,
and by consistent conduct out of meeting.
We may be active in Society concerns, and yet strangers to this religious exercise;
without which we cannot become helpers in the Lord`'s cause and lights in the world.
I would that I were able to believe,
that all of us who stand in the station of ministers and elders,
had escaped this too general contagion of the love of the world;
but with sorrow it must be acknowledged, if we speak the truth,
that there is reason to fear,
the complaint of the Almighty through one of his servants formerly,
may apply to some of this class:
'`The leaders of this people cause them to err.`' And such a line of conduct,
if persisted in, must in the end prove fatal in its consequences.

Let none be saying, I expose things too much; for those to whom these remarks apply,
have been exposing themselves more already;
for our hearers and the world at large are quick-sighted,
and although our defects may have been passed over in silence,
as respects notice thereof to ourselves, yet they do not pass unobserved,
or without being remarked upon as to others, nor is it to be desired they should;
the people are not to be expected to take things upon trust,
or pin their faith on our sleeves, but to see and know for themselves.
The enemy of all good is not idle, but ever alert,
and ready with baits suited to answer his purposes;
so that when the good hand has been turned towards any,
and they have been favoured to see and feel the need of a still
further separation in love and affection from all sublunary things,
and the mind has become exercised with desires to experience this;
then he has endeavoured to counteract the gracious design of Omnipotence,
by raising mountains of discouragement and difficulty in their way,
endeavouring to persuade that the path thus opened
to their view is not to be trodden by mortals:
and as a confirmation of these his evil suggestions,
turning their attention towards such in a more particular manner,
who stand in the fore-rank, and are making a great profession,
but not coming up in a consistent conduct;
and hereby there is reason to fear the pure witness in such is often again put to silence.

I cannot doubt but that a desire to do a great stroke of business, get great riches,
and make a great figure in the world, is as much some men`'s besetting sin,
as ever the love of strong drink has been that of others.
But where the temptation is yielded unto,
which of these do we conceive to be the greatest sinner,
he whose mind and faculties are so besotted with strong drink,
that he is hereby rendered unequal to the performance
of either his civil or religious duties,
or he in whom the same effect is produced by an overcharge of business?
for this must be the case--it must disqualify for a faithful
discharge of civil as well as religious duties,
when the mind and spiritual faculties of any person are so benumbed and overcome,
if not with surfeiting and drunkenness, yet with cares of this life,
with the love of his gold and silver, houses and land,
and so intent on his mortgages and bonds, his interest and compound interest,
trying to make a heaven here below.
In this state his religious performances and offerings are made, like the niggard`'s,
grudgingly.
If at meeting, scarcely in due time, and with his heart so full of the world,
that as he brought it to meeting with him,
so there is reason to fear he returns with it again;
and before he gets well off the premises he has a touch about it with some one,
it being the thing that is nearest to his heart:
and if the church trust him with any of her concerns to execute,
it must give place to every of his temporal engagements,
and only have the refuse of his time, perhaps an evening after the fatigue of the day,
when the poor mind is more fit for sleep than religious exercise.
Is it to be expected that delinquents, who may be visited by such,
should be brought to a due sense of their outgoings, and be reclaimed,
when the language so fitly applies--physician, heal yourself?
I am aware the former character is deemed the most immoral;
but I am not able to bring my mind to believe it the most sinful:
for if our minds are but unfitted for a faithful
discharge of our civil and religious duties,
whether such disqualification proceeds from the love of gold or of strong drink,
I believe the crime is the same in the Divine estimation.

I believe I am safe in saying,
I have not been lacking at times in endeavouring to cast
a veil of charity over the conduct of some of my friends,
who it is evident have in this way become Satan`'s bond-slaves,
and my heart is made sad on their account: I have an assurance,
that whatsoever our temptations and besetments may be, if we are but in good earnest,
willing to resist and overcome them, he that covets great trade, great riches,
and to make a figure in the world, as well as he that takes strong drink,
will experience a way, a sure and certain way, to be cast up in due time by the Lord,
for his escape from this otherwise impassable gulf between
him and an eternal resting-place with the righteous.
For the self-same Divine principle of light and life,
which our worthy forefathers believed in, followed, and were actuated by,
is still with us, as the cloud by day and pillar of fire by night,
is still experienced by those who wait for it,
and found by such as submit to its government, which is an all-regulating principle,
subduing every inordinate affection and disposition.
It says, availingly, from time to time,
to such who thus continue subject to its controlling power.
Thus far you shall go,
but no further with safety in your worldly concerns and engagements.
But if we will continue to harden our hearts against its holy intimations and restraints,
we must expect to wander into the many bye-ways and crooked paths of the enemy,
making for ourselves a labyrinth which we may never get clear out of.
There is reason to fear this has been the case with many,
and I firmly believe restraint to be needful,
not only as to the quantity of trade or business,
in which we may engage with safety to ourselves,
but also as respects the nature and quality of such our worldly concerns,
that it may preserve us not only from an overcharge of business,
but also from being engaged in such business as either directly
or indirectly tends to lead away the mind from the pure,
peaceable, self-denying path,
and to foster the contrary disposition in ourselves or others.

How remarkably was this manifest in the members of our Society in the beginning;
until the enemy was permitted to try us with the bait,
which has not failed to take with some of all classes
in society--riches and worldly prosperity.
In proportion as the mind has been let out, and desires increased after these,
it has become indifferent as to consequences; neither fearing the overcharge of quantity,
nor properly regarding the quality of business.
Happy had it been for many in the present day of sore conflict,
from the general depression of trade,
had they willingly and timely yielded to those Divine intimations;
for I believe none ever turned aside from the path of safety totally ignorant thereof,
but that in the beginning of their erring and straying,
the witness for God followed them, and at times smote them:
but if we disregard its invitations and secret monitions,
it is then most just on the part of Almighty God,
to leave us to the power and insinuations of Satan; the god of this world,
who rules in the hearts of the children of disobedience.
But even while thus promoting the cause of the evil one,
such may continue to make a fair show in the flesh, as to a profession of religion,
and be very tenacious respecting some externals,
as were the Pharisees--things comparable to the mint, anise, and cummin,
and in which Satan will not oppose them, so long as they rest therewith satisfied,
and continue to rebel against the light,
refusing to submit to the heart-cleansing operation of God`'s word and power,
which only can effectually cleanse the inside of the cup and the platter.

Happy, I say, had it been for many, had they attended to the pure limitations of Truth,
who are now plunged, with their families,
into accumulated difficulties and unlooked-for distress;
and respecting whom the declaration of the apostle has been verified,
'`They that will be rich fall into temptation and a snare,
and into many foolish and hurtful lusts, which drown men in destruction and perdition;
for the love of money is the root of all evil; which while some coveted after,
they have erred from the faith,
and pierced themselves through with many sorrows.`' And
it is to be feared there are many more of this description,
who, at times, quake for fear of that, which, without Divine interposition,
seems coming upon them.
And is it to be wondered at, that these things should happen among us,
when the conduct of many under our name is so opposed to the profession they are making,
which demands of us that we be '`found men fearing God and hating covetousness?`'

How opposite is this disposition of mind to that of the love of the world;
for as this disposition is brought about in us, and abode in,
the mind as much dreads the very approach of any of Satan`'s gilded baits,
as if surprised by a rattlesnake or other venomous creature, whose wound is fatal;
because if we allow ourselves to be beguiled by him, spiritual death will surely follow.
And this has been verified respecting many,
since I first became acquainted with the Society of Friends;
many who gave proof that they were the visited children of the Lord our God,
who had covenanted with him, and for a time evidently confirmed the same by sacrifice;
but for lack of continuing to ask wisdom daily,
to go in and out before the Lord with acceptance;
(for I find if we are favoured to possess it,
we must daily ask wisdom of Him who still fails not to grant liberally;) and
by giving the things of this world the preference,--riches and greatness,
they have been permitted to obtain their heart`'s desire: but it has been evident,
that which they thus coveted did not come alone,
but attended with its never-failing companion.
For those who covet an evil covetousness, must expect to possess leanness of soul;
also the sorrowful consequences of which will be unfruitfulness towards God,
which although it may appear to be very slow in its gradations,
yet such may rest assured, that it will take place,
whatever they may have known aforetime of an enlargement
of heart towards him and his cause.
For when the door of the heart becomes open towards
covetousness and the love of this world,
and there is a stumbling at the cross of Christ,
a refusing to become crucified unto the world and the world unto us, this love of God,
once known and felt, in time takes its departure again.
O,
these spots in our feasts of charity! for such I fear they have
been to many who have been called together by the Lord`'s messengers.
These wells without water, these clouds without rain; these stumbling-blocks to others,
and to the youth among ourselves.
Who have been coveting an evil covetousness, launching out into a great way of business,
which Truth never justified them in.
And even some among us, not satisfied when a kind Providence has so favoured them,
as that there has been an ample supply from their present business for basket and store,
to satisfy their thirst of more, have infringed upon the rights and privileges of others,
adding one fresh business to another.
How does such a mode of procedure comport with a people professing, as we do,
to be dead to the world, and alive unto Him, whose apostle declared,
'`If any man love the world,
the love of the Father is not in him`' From which proceeds this conduct.
Let the just witness tell us, my friends; and may it arouse us before it be too late.
Let such no longer continue to say, '`Today or tomorrow we will go into such a city,
and continue there a year, and buy and sell,
and get gain;`' whereas they know not what shall be on the morrow:
but let them be willing to yield to the restraining influence of God`'s word and power.

Consider from where this determination proceeds, which many among us appear to have made;
this willingness to sacrifice everything that should be nearest and dearest to them,
in order to add ten thousand to ten thousand, and twenty thousand to twenty thousand,
and double and treble it again and again, if possible.
Let these things speak for themselves:
can they proceed from any other disposition than the love of the world?
O let such consider if the apostle`'s declaration be not true as to them,
that the love of the Father is not in them.
For many years I have esteemed it a reproach to such
a Society of professing Christians as we are,
when any of our members have been summoned from works to rewards,
and have left behind them such large sums of money of their own accumulation.
O what a cloud has it brought over their very best actions,
however conspicuous they may have stood in society!
O the sorrowful feelings I have been dipped into at times
on the account of such!--language fails me to set them forth.
It is painful for me thus to expose myself on this sorrowful subject,
for such I have often experienced it to be; but I believe that,
if my feeble efforts be accepted as a peace-offering,
that which appears to be the whole counsel must be imparted.^
footnote:[I would not be understood as charging such as
leave large property behind them which they inherited;
and with regard to the disposal of such property by will,
were sentiments of the kind here enforced more prevalent,
I believe it would be more distributed,
and that this would be conducive to the solid peace
of such as thus dispose of it in time.]

Some have replied, when remonstrated with on these subjects,
that they are at a loss to define the word '`enough;`' but this difficulty,
I am of the mind, rests with themselves: in the first place,
through an unwillingness to have their needs circumscribed
by that power which is from above;
and in the next, for lack of a sincere desire to have this word defined for them,
by that wisdom which is as competent to direct in
this as in any other important step of life.
As it is a duty we owe to the body,
to make suitable provision for its comfort and convenience, especially for old age,
that we may rather be helpful to others than require their help:
so likewise to put our children in the way to get their living by moderate industry,
and provide for such of them as may not be in a capacity to help themselves:
when a kind Providence has entrusted to us so much as may answer these purposes,
if after this there remains a disposition to accumulate,
then I believe we are violating that command of the Divine Master,
'`Lay not up for yourselves treasures upon earth,`'
and we are giving full proof where our hearts are:
not that I apprehend it would be better for all such who have thus attained,
to quit their trades and occupations;
because some may be more in the way of their duty in continuing to pursue them honourably;
when, besides introducing deserving persons as their successors,
they may be the means of helping those who are not able to help themselves,
with which description of persons the world abounds,
such as the widows and the fatherless, and the infirm,
who frequently are obliged to labour under extreme pain and suffering;
but there must be no adding to the '`enough,`' lest
that enough which has been mercifully dispensed,
be taken away again; for, '`covet all,
lose all,`' has been the reward of such conduct many times.

I am aware of the trying state of trade and commercial affairs,
and the great difficulty many honest minds have had to struggle with,
who are obliged to give credit in their trade;
thus depending upon others to make good their own payments.
Yet I believe that complaints of lack of punctuality in fulfilling engagements,
would not continue among us, were we in earnest to do everything in our power,
that the chief cause, the inordinate pursuit of business, might be removed.
What sorrowful instances of notorious and scandalous
failure have of late years happened among us,
for lack of the timely exercise of this care!
How have the records of our Monthly Meetings been
sullied by report after report of this kind;
principally through lack of observing the limitations of Truth in our trade,
and exercising a care,
that our way of living might in all things be consistent with what we profess!
The excellent advices that are annually read in all our meetings,
I have long been led to fear, are become to many who hear them as a stale thing;
but this is not the case with the right-minded,
who are desirous of receiving help every way.

However, by others`' harms let us take warning.
Friends, lessen your temporal concerns;
you that have been permitted so far to weather the storm, which has been long gathering,
and, at times, has blown a heavy gale.
And notwithstanding there has been some intermission,
something which at times might be termed sun-shine, with a hope that the worst was past,
and that better times as to commercial affairs were hastening,
how soon has the expectation of such been disappointed, and how many,
that have thus been tempted to venture out on the vast ocean of commerce,
have become a total wreck!
Has not the next cloud that has gathered,
still exceeded those which went before in magnitude and terrific appearance,
sometimes as if ready to burst and carry destruction before it every way.

Friends,
lessen your trade and business with all the resolution you are capable of mustering,
taking especial heed to the good pilot at the helm.
Get into a safe port,
to as safe an anchoring place as the nature of your various outward circumstances,
in these times, will allow of: otherwise it has long been my belief,
these instances of lack of punctuality and failure in the discharge of just debts,
will more and more increase among us:
because it is my belief the day of the Lord is coming
'`upon every one that is proud and lofty,
and upon every one that is lifted up, and he shall be brought low;
and upon all the cedars of Lebanon that are high and lifted up,
and upon all the oaks of Bashan, and upon all the high mountains,
and upon all the hills that are lifted up, and upon every high tower,
and upon every fenced wall, and upon all the ships of Tarshish,
and upon all pleasant pictures.`' Read the remainder of this remarkable chapter,
together with the foregoing one; and let none say,
We have long since heard such things--they were long ago
proclaimed in our ears by an Emlen and a Scattergood;
but what has come of it?
lest our calamity come upon us as a thief in the night, in a day when we look not for it,
and at an hour when we are not aware.
O remain no longer unwilling to act the part of wise mariners,
you that sail on the wide ocean of trade and commerce,
and have its tempestuous billows oftentimes to contend with,
and to whom it has appeared as if nothing less than a total wreck could be the result.
For when danger like this threatens him, he looks well to the helm, reduces his sails,
and lightens the vessel by lessening the cargo rather than risk the loss of the whole.

I am aware of the distress the creaturely part must have to endure,
before the mind is at all likely to be brought into
a willingness to take such steps as these.
And I think I can feel much for those of my friends who have families,
and have so far extended their manner of living, as that,
from the depressed state of trade and the various losses they are assailed with,
their income barely covers their expenses, while, perhaps, their families are increasing.
For it is gratifying to our nature to appear to the world to be increasing in substance,
but mortifying to retrench,
lest it should be suspected that we are going down hill in the world.
But this must be done by many among us,
or I am greatly mistaken in what has long been the feeling of my mind.
Friends, you must be content with the half loaf, which is better than no bread at all.
Lessen your business, and regulate your family expenses accordingly;
otherwise you may be brought into the same trying situation many are now in,
who once carried their heads very high in the commercial world, and move in,
what are called, the more genteel circles,
but who have now no bread at all that they can strictly call their own.

I am now under the necessity of claiming your attention, my dear sisters,
in order that you may do your part,
in facilitating the escape of your husbands and parents from the
troubled waters and sunk rocks of commercial difficulty,
which the keen eye of human policy is so often unable to discover;
for with you generally rests the management of household affairs:
it is also principally for the supply of these that the labouring oar is kept tugging.
You must be willing, mothers and children,
to examine closely the mode and circumstances of your expenditure,
with a mind made up to relieve, as far as in you lies, the head of the family,
who may have both wind and tide to contend with.
Search your houses, search your tables, search your garments;
and where any expense can be spared without lessening your real comforts,
seek for holy help to rid the vessel of it.
I am well aware it will require holy help to take such steps;
but this I am assured will not be lacking if sought
after in a proper disposition of mind.
And we shall find that those things which have been sacrificed,
being calculated only to gratify the vain mind in ourselves and others,
and pamper a depraved appetite, had not the effect of adding real comfort to our hearts.
Regard not the world`'s dread laugh,
but set your intimates and neighbours this salutary example;
show them the way to live well at little expense;
an example I believe we are called upon, as a religious Society,
in a peculiar manner to be holding up, especially in the present state of the nation.
And however this may prove a sore conflict to the fleshly part,
by letting us down in the eyes of the world,
yet in the end we shall appear more honourable than some among us of late years have;
who have gone on pushing business to keep up an appearance
which their circumstances did not justify,
clothing and feeding themselves and their children
with that which they were not able to pay for.

And, Friends, you that are of ability of body, learn to wait more upon yourselves,
and bring your children to do the like: I find I am never better waited on,
than when I wait upon myself.
Teach your children industry and a well-regulated economy;
I fear there is too much need in the present day to press this wholesome practice;
for next to a truly pious example, you cannot bestow upon your children a better portion.
This appears to have been much the case with our first Friends;
and it had been better for many of our youth,
had their parents trod more in the footsteps of these.
Labour is a part of the penance enjoined by the fall,
'`By the sweat of your brow shall you get your bread.`'
This sentence pronounced upon Adam descends to all his posterity.
Suitable employment, under the regulating influence of an all-wise Creator,
is salutary both for mind and body, and qualifies us the better to feel for,
and proportion labour, to those who may be placed under us.
It may even prove a secondary means of keeping our nature under subjection,
which we cannot be ignorant is corrupt, and requires much subduing;
something to check its impetuosity and bear rule in all our actions.
There is yet another precious advantage results from bringing
up children in habits of well-regulated industry and economy;
little business will then be found sufficient to bring up a family reputably,
when our needs are confined to the real comforts and conveniencies which Truth allows,
as far as ever our circumstances will warrant them.
It is those things which have nothing to recommend them but show,
and an appearance of what the world calls gentility,
that are opposed by the Truth in each of our minds,
did we but attend to it more faithfully: for lack of this attention,
how many have become slaves to appearances.
And where this well-regulated industry and economy are lacking,
and idleness and fulness of bread prevail,
how little is to be observed in the conduct of such,
of reverential thankfulness for the bounties they are receiving from heaven.

When we are content to move in this humble sphere,
we are prepared the better to meet such reverses as may come upon us.
Let none among us say in his heart, I am out of the reach of reverses,
because none are out of the reach of them;
for however variously our outward substance may be secured,
all sublunary things are unstable as the waters; and various as may be our resources,
every supply may be cut off;
the Philistines may be permitted to stop up all the
wells which we have dug for ourselves and our children.
The Most High may permit his little army to enter into our vineyards and olive yards,
and strip us of all, without power on our part to prevent the devastation;
for what the palmer-worm leaves, the canker-worm may eat,
and what the canker-worm leaves,
the caterpillar may so destroy that not the least
vestige of our once greenness and greatness may remain.
This has been the case with many within my memory.
The crafty have been so taken in their own craftiness,
and the lofty so brought down from their seats, and the men of low degree exalted,
that he who was the servant has become the master of his once master,
and even his master`'s children have served his children.
What has been may be again: for thus has the All-wise Disposer,
to whom belong the cattle of a thousand hills and every visible thing,
for nothing is mine or yours, any longer than He sees fit we should possess it,
evinced his sovereignty and power to humble his creature man;
convincing him thus of the great uncertainty of all visible things.
And may these turnings and overturnings which we hear of,
and some more keenly feel the smart of, in commercial concerns and in families,
prove the means of stimulating us to leave things that are behind,
all of which are perishing, and press forward to those which are before,
which are eternal.

I am afraid, my dear sisters, to close this subject without adding another hint,
as essential to our being the better able to keep
our family expenditure within its proper bounds;
having myself experienced its salutary effects, when I had a numerous family around me.
It is,
to determine to purchase with ready money the various articles consumed for family use,
and that we resolve to perform this, however mortifying it may prove,
by depriving us of many things the natural disposition may crave in ourselves and children.
I believe great advantage will be found to result from such a practice,
both to parents and children,
more particularly to such as at times feel themselves straitened,
to carry on their business reputably.
For when these difficulties are felt by an honest mind, it becomes obligatory on such,
if they get through them, closely to inspect the manner of their expenditure,
and this will afford an opportunity of timely checking any
unnecessary expense that may have crept into the family.
But when things for family consumption are mostly, if not all, had upon credit,
this opens a wide door both for parents and children to greater indifference,
both as respects expediency and cost, than Truth at all justifies;
and the children of such parents are in danger of being
brought up ignorant of the real use or value of property.
When numbering my blessings,
I esteem this as not one of the least that my heavenly Father has bestowed upon me,
that he kept me in a little way of business,
and a care to keep my family expenses within proper bounds,
and taught me the lesson of contentment with little things;
because now I am advanced in life, I am satisfied I escaped manifold perplexities,
which would have been at this time my attendants,
had I sought after greater things as to this world.
The purchasing goods for family consumption on credit,
often proves a serious inconvenience to those,
on whom such are depending for their supplies,
especially if they are not before-hand in the world;
for it too frequently proves that such purchasers
are not very ready to make payment in due time,
and when this is the case, are they doing as they would be done by.

I have long viewed it as a mean practice,
to consume in any way the property of another person before I have paid for it,
except under some peculiar circumstances;
for general usage does not justify me or any other person, to say no more,
in wrong practices, especially a people making the high profession we do:
for we are not to view things as the world does, but through a more pure medium,
with the eyes of truth and uprightness.
I want us more frequently to recur to that which we are making profession of,
and as frequently compare our practice therewith, bringing all our deeds to that light,
by which, in a future day, they will be judged;
for I cannot refrain from expressing a jealousy,
that too many among us are swerving into this dangerous track of the world.
One of the diadems with which our first Friends were decked--one
of the many jewels that shone in their character,
and adorned their profession,
was the care they manifested to have nothing but what they could well pay for;
so that should reverses come, from the many perils they were in various ways liable to,
none might be losers by them.
This, in due time, with an uniform, consistent, upright conduct in other respects,
procured for them that confidence in the minds of all ranks, and that respect,
which they so long maintained.
I am not able to close this subject without entreating such,
to whom these remarks may apply, not to set light by them.
Look seriously at the subject, and make a stand, and hold up your testimony by example,
against this baneful practice, for so I doubt not it has been to thousands,
and the inlet to those embarrassments that have at last overtaken them.
If we are willing to be found thus standing in our proper allotment,
we may prove in degree instrumental, in the Divine hand, to check that torrent of evil,
which so sorrowfully pervades all classes:
for the practice has overspread the nation of supporting
an expensive manner of living upon credit,
which, if not timely checked, there is reason to fear may contribute,
among other evil practices, to work its ruin.
We have stood high as a religious society in the esteem of others,
for nearly a century and a half, in regard to honesty, integrity,
and an exemplary conduct.
Can we with truth say, we believe we have been rising higher in this respect,
of later years?
I fear this has not been the case; but that the many sorrowful failures,
the multiplied instances of lack of punctuality that
have of late years occurred among us,
with various departures in other respects from our well-known principles,
have given a severe shock to that confidence in us,
which once had place in the public mind.

The door has of late been set open much wider than was the experience of our first Friends,
for the members of our Society to associate with those of other religious professions,
in the management of the various institutions for benevolent purposes that are on foot.
Let us be careful, that this does not lead us to assimilate ourselves to the world.
The world hated our first Friends,
because they maintained a faithful protest against its spirit, its maxims and manners;
but in proportion as we put away from us the weapons of the Christian`'s warfare,
and join in league with the world,
a wider door of admittance into all companies and all societies will be opened to us.
Thus we have, indeed, occasion to look well to our stoppings and standing; remembering,
that so far as we join ourselves to the world in any respect,
we shall be condemned with the world.
'`If you were of the world,`' said our blessed Lord to his immediate followers,
'`the world would love its own; but because you are not of the world,
but I have chosen you out of the world, therefore the world hates you.`'

In order that we may not further forfeit the confidence of the public,
but regain that which we may have lost, let me again repeat the caution,
that by others`' harms we may take warning;
and by our future conduct give proof of our belief in this incontrovertible truth,
that a man`'s life or the true enjoyment of it,
consists not in the abundance of the things which he possesses.
Let us learn that essential lesson of contentment with little things as to this world,
remembering that He, whom we profess to take for our leader, declared respecting himself,
although Lord of the whole world,
'`The foxes have holes and the birds of the air have nests,
but the Son of man has not where to lay his head,`' so void was he of any earthly inheritance.
It was the exhortation of the prophet to Baruch, the son of Neriah,
'`Do you seek great great things for yourself?
seek them not: for behold I will bring evil upon all flesh, says the Lord;
but your life will I give unto you for a prey,
in all places where you go.`' While then we are engaged to circulate more generally,
among mankind at large, publications explanatory of our religious principles,
and religious tracts, may we give proof, in the first place,
of their happy effects upon our minds;
for example will do more than precept,--actions will speak louder than words;
so shall we each one become a preacher of righteousness,
that cannot fail to reach to the pure witness in the minds of others.
Thus may we become as saviours on Mount Zion, '`For saviours shall come upon Mount Zion,
to judge the Mount of Esau; and the kingdom shall be the Lord`'s.`'

And let us all retire to our tents; for if I am not mistaken,
such are the signs of the times, that they loudly call upon us so to do,
and there closely to keep.
The Lord is this tent, unto which the true Israel of God must flee to be safe;
and as there is thus an abiding in him, who is the munition of rocks,
should the potsherds of the earth begin to smite one against another,
such will be preserved from smiting with them, in word or deed,
and escape that danger which will more or less follow those who are found so meddling;
and that perturbation of mind, that instability of confidence and lack of support,
under the various probations that may, in unerring wisdom, be permitted to overtake,
which ever was, and will be, the case of those who make flesh their arm.

I cannot forbear to express a fear,
that there are among us who are not sound in the faith,
as it respects an entire reliance on the all-superintending care of Divine Goodness,
in times of danger and difficulty, but who are making flesh their arm;
and when at times their minds are awakened to behold the approach of danger,
as respects national affairs, are placing their confidence in, what they esteem,
the wise conducting of a well-disciplined army, and a large store of weapons of defence;
all which may effect the very destruction of those who are thus relying upon them,
instead of the living God, for preservation.
Such is the great uncertainty of all human events!
It must with reverence be acknowledged by every serious observer,
that the Divine protection has long been over us as a nation;
and for the sake of the few righteous among the
different professors of the Christian name,
is still, I believe mercifully continued.
But how soon, or how suddenly, this may be withdrawn from us as a nation,
because of our multiplied transgressions, is altogether unknown to us;
but should this once be permitted,
and the chain of the evil power be loosened for a time, this arm of flesh,
which there is reason to fear many are depending upon for support in such perilous times,
will become but as tow in the furnace!
Happy will it be in that day, for those who have made the Lord alone their refuge,
and placed their dependence on that Omnipotent and Omnipresent Being,
who will prove in such seasons a covert from the heat, a shelter from the storm,
and as the shadow of a great rock in a weary land;
a day and time when the minds of all may be clad with dismay as with a garment,
for fear of what is coming upon this part of the Lord`'s foot-stool.

And, Friends, let us not dare to meddle with political matters,
but renewedly seek for holy help to starve that disposition
so prevalent in us to be meddling therewith.
Endeavour to keep that ear closed, which will be itching to hear the news of the day,
and what is going forward in the political circles.
We shall find there is safety in so doing;
it is the only way for us to experience our minds to be preserved tranquil,
amidst all the commotions,
all the turnings and overturnings that may be permitted to take place,
when the measure of iniquity may be filled up.
I have found, that if we allow our minds to be agitated with political matters,
our dependence becomes diverted, by little and little,
from the true centre and place of safety, where perfect peace is experienced,
though the world and all around us may speak trouble.
Such as have this dependence,
will know it to be a truth fulfilled in their own individual experience,
that '`They that trust in the Lord shall be as Mount Zion, which cannot be removed;
but abides forever;`' and that as '`the mountains are round about Jerusalem,
so the Lord is round about his people from henceforth even forever.`' Now, Friends,
be willing to take up this cross,
for I have found it to be one of the many crosses I have had to take up,
and avoid reading political publications, and, as much as possible, newspapers;
and I am persuaded, if a willingness is but manifest on our part so to do,
sufficient help will be afforded from time to time,
to withstand this and every other temptation of the great adversary of our peace.
I am well aware that men in trade,
and sometimes those who are free from its incumbrances,
have occasion to resort to those channels of general information;
but when this is my case, I find it safest for me,
after I have received information on the subject in question,
then to put the paper away from me.
I am aware that it requires firmness so to act,
there being something in our nature so anxious to
know what is going forward in the world;
but, my friends, nature must be overcome by grace, which I never found to be lacking,
if rightly sought after.

I must now conclude, with expressing the earnest solicitude I feel,
that we may each of us be found willing to unite with that all-sufficient help, which,
I believe, yet waits our acceptance; and allow it so to operate in and upon us,
that we may become a people wholly separated in heart and mind, love and affection,
from everything that has a tendency to dim our brightness,
to prevent us from being as lights in the world;
and be clothed with those beautiful garments,
which so adorned our worthy ancestors--humility, self-denial,
and an entire dedication of heart to the work and service of our God;
a disposition truly characteristic of the disciples of him, who declared,
'`My kingdom is not of this world:`' and thus may the enemy
no longer be permitted to rob and spoil us,
but the language go forth respecting us, '`Happy are you, O Israel, who is like unto you,
O people; saved by the Lord.`'

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Hitchin, 1st of Eleventh month, 1820.

--
