== Chapter XVI.

Second-day morning, I waited on the chief magistrate at Hamburgh.
He met me with a pleasant countenance, saying, he had received the several addresses,
read them with satisfaction, and could give his full assent to the truths they contain;
and, said he, "`you have done our city a great kindness by their circulation;
I have no doubt, but in time fruits will appear,
but the amendment so necessary among us must be a gradual work.`"
Referring to the treatment I had experienced at Altona,
he assured me I might consider myself secure among them,
as did also other officers in the government, saying,
"`Take up your abode with us at Hamburgh;
we esteem your character and your motives for coming among us;
assured as we are of the purity of your intentions,
that nothing but true love could have influenced you to do as you have done:
you needed no certificate from your friends,
you have already given us the best certificate yourself.`"
In the afternoon I walked to Altona: the effect of my arrest had not subsided,
and the general sentiment prevailing was,
that the several subjects in the address would not have been so likely to obtain consideration,
had not my arrest taken place; many remarking,
that those in the government could not bear to have
the truth circulated among the people.
Third-day, went to Altona, and made a visit to the governor,
who was from home at the time of my arrest: he received me with great respect,
apologizing in such a handsome manner for what had taken place,
that I requested the matter might be passed over.

After presenting him with the address to Hamburgh, that for the magistrates,
senate and the clergy, and with some books, we parted;
he leaving me at liberty to make another call,
and informing me I was at liberty to reside in Altona, if I preferred it.
I was informed, that the pastor of what is called the +++_______+++ church,
had endeavoured to enforce on the minds of his hearers
the necessity of a serious attention to the address,
saying, its contents were too true, and the advice it contained not to be slighted;
for however it might be considered the author had exceeded a little in his observations,
it was to be lamented that a foreigner should have cause to make such remarks,
on the conduct of the inhabitants of Altona.
It felt due from me to make the pastor a call,
to afford him an opportunity to point out wherein I had
exceeded in any of the charges brought forward in the address.
I paid him a visit this morning: he fully relieved my mind on the subject, by saying,
he could not point out where I had exceeded in the
charges against the inhabitants of the city;
but assured me he was obliged to qualify the observations he made,
lest the people should suspect him of being converted to my religious principles,
and on that account should slight the remarks he had made:
that he himself was confirmed in the truth of all I had said,
but that preaching will not avail much:
so long as the police allows of these things that are wrong,
the people will avail themselves of them: reform must first be made by the government;
they must set the example, for the people look at the example of the higher class,
rather than think for themselves.
I felt relieved by making this visit, the matter being cleared up to my satisfaction;
which otherwise the busy enemy might have made a handle of,
in some of my future provings, to depress and cast me down.
The evening I passed very satisfactorily to myself,
in company with two of my friends in the government; and thus another day closed,
to account for.

Fourth-day, a hoarseness and pain at my chest,
occasioned by my confinement in the guard-house, so increased,
that I was obliged to keep at home the whole day; my kind friend Dr. Steinheim,
troubled me not a little, by pronouncing it to be unsafe for me to proceed to Norway,
unless some improvement took place in my health.

Fifth-day, not feeling clear of the police-master at Altona, I ventured out again,
and made him a visit,
to clear my friends of Altona from being suspected of assisting me in any manner,
or being privy to the address, before it came into my possession from England.
He questioned me very closely where it was printed;
and when shown the printer`'s name and place of abode in England; replied,
that might all be a deception.
I gave him the letter that accompanied them, and after understanding its contents,
and comparing the date with the post-mark, he put out his hand for me;
to confirm what I had said on the subject, I gave him my hand;
and he then appeared satisfied.
As I could not doubt but he suspected that some of
my friends in Altona were privy to my proceedings,
it was to me a great consolation, that I attended to the intimation in my own mind,
not to make any on this side of the water, privy to what I had in hand,
until it was ready for delivery, and that I could declare so much to the police-master;
although at first, from his manner,
it was evident he hardly could give credit to the truth of what I said.
I was told, if any had taken a part with me in it,
they would have been in danger of being fined, imprisoned,
and perhaps sentenced to hard labour for a time.

Feeling my mind drawn to make a visit to a man in Altona,
who was considered the principal of a sect called Christian Friends;
having procured an interpreter, we proceeded,
and found him a person very low in the world.
He gave us this simple account of their origin.
In the beginning of this century a poor shoemaker was brought to the knowledge of God:
in time he became acquainted with a man who was favoured with the like experience;
they regularly went home together from their place of worship,
and conversed on the subject the minister had preached upon;
after awhile a third joined them,
soon after this others manifested a desire to partake with them,
until their number became nearly two hundred.
For the first ten years they had no settled place to meet in, going from house to house,
as they could be accommodated,
and a merchant who joined them built a large room for them to meet in.
When the police-master had knowledge of the use for which this room was intended,
he sent for the proprietor, and spoke to him on the subject,
but no further notice had yet been taken of it.
On my inquiring relative to their time of meeting on first-day,
I was informed they only met in the evening at eight o`'clock.
The reason given for their not meeting in the middle of the day was,
to prevent the clergy complaining against them to the police-master,
for drawing people from the church;
it was said in their meetings they sat awhile in silence,
in order that they might have their minds delivered from all worldly concerns,
and be the better prepared to approach the Divine Being with acceptance; they prayed,
sung hymns, conversed on things appertaining to their soul`'s salvation,
and read the Scriptures.
It appeared they dared not acknowledge they had preaching among them;
yet I was informed this man at times addressed them in their assemblies as a minister.
I could not doubt his being a well-concerned man,
for whom and his brethren in their circumscribed allotment, I felt tenderly;
and I had fresh cause to prize my privileges in being
free from those shackles by which they are bound.

Fifth-day, made a call on the head of the Lutheran clergy of Hamburgh;
he expressed his full concurrence with the address, saying,
much more depended on the civil authority than on the clergy,
in trying to enforce the spirit of it;
these might recommend from the pulpit its contents,
and preach against the prevailing bad habits of the town and neighbourhood;
still the impressions that might be made on the congregation,
would be likely to lose their effect,
unless the civil power was diligent in enforcing the laws,
and the inferior officers of the government were better paid,
so as not to be exposed to bribes, and tempted to compromise with evil doers,
and sell vice rather than bring it to its just punishment.
That the principal clergy met occasionally,
but as men did not always unite in the same judgment,
this frequently prevented their going in a body to lay their grievances before the senate.
It is also much to be lamented that Hamburgh and Altona, so near as they are together,
are not under one government;
their different interests counteracted the enforcement of the laws,
which was the cause of much of the disorder that prevailed in the burgh,
neither party being willing to sacrifice their temporal
interest for the future spiritual welfare of the people.

My next call was upon the principal preacher of what is called St. +++_______+++ church;
he expressed his sorrow there was so much cause for the observations made in the address;
saying,
the clergy in former years had not done their duty
with the sincerity and boldness required of them,
as professed overseers and directors of the people;
but they became lukewarm and indifferent in these respects,
and he hardly knew how the evils now crept in among them were to be remedied;
that the dance-houses should not be allowed,
for it was there the young people`'s minds were contaminated.

Feeling my mind drawn to visit a young man, a priest of the Jewish persuasion,
accompanied by my friend D. B+++______+++, as interpreter, we proceeded to his residence;
where he received us courteously.
I presented him with the translation of my certificates, which he read with deliberation:
from his countenance and the frequent motion of his head,
it appeared the care of the Society towards its ministers was approved by him.
I also presented him with the address to Hamburgh, to the magistrates,
and that to the clergy, which he read while we were present,
making his observations as he went along.
Having finished them,
he said the contents of the several addresses met his full approval, but observed,
as they were only allowed in the state, they had no power to interfere in the government;
but so far as it was in his power to enforce the spirit of the address from the pulpit,
he would do it; for however we might differ in matters of faith,
it is the duty of all ministers to endeavour, as far as in them lies,
to enforce whatever contributes to the good of their hearers,
or to the good of society at large; although it yet depended on those that hear,
whether they would follow the advice given them.
He also said,
the law written in the heart of man or conscience was in unison with the law of Moses,
and was the best guide to conduct us through the path of life,
and that he referred to these to corroborate his preaching; for after all, he added,
preaching only has a reference to these guides.
We parted in feelings of much affection.
Although I hesitated considerably before my mind
was made willing to give up to this visit,
concluding my friends at home, if they came to hear how I had occupied my time of late,
would say I had strangely rambled from one priest to another;
but now I feel well satisfied in yielding to this pointing of duty,
especially as on inquiry it appears this young man`'s
character comports with the sentiments he advanced;
that he is called a preacher of new doctrines by the Jews here;
and from what I have been able to learn,
he is likely by degrees to lead them to a liking for the New Testament.

I again turned my attention to the subject of securing
a passage in the vessel bound for Christiana,
as it was desirable to avail myself of an agreeable captain and good vessel;
the vessels on this passage being mostly what are called crazy vessels;
but as a cloud came again over my mind,
I endeavoured to leave this matter for the present, and do my best to clear out,
not doubting but that the way I am to proceed to Christiana will open.
I waited on the chief magistrate of Hamburgh,
who informed me he had read over the proposed regulations, which he said were good,
if they could but be put in practice; but we must not stand still,
if we cannot do all we would; giving me the cheering information,
that the subject of the girls was brought before the view of the public,
and subscriptions already begun for the purpose of establishing a penitentiary,
and that a house was in a state of forwardness for the purpose.
At our parting, he expressed a hope, that on my return to Pyrmont from Norway,
I should be able to observe some improvement in the city.

I began now to feel as if my service here was nearly come to a close,
truly humbled I hope under a grateful sense of the mercies of my heavenly Father,
in thus dealing bountifully with me,
making way for me in the minds of those in authority and others,
when awakened by a sense of duty to call upon them.
Being now got into the eleventh month,
my friends here think my attempting to reach Norway
to winter will be attended with danger,
and much bodily suffering.
My hoarseness and pain at my chest continuing,
I at times looked at returning to England to winter,
as I could not see that it would be right for me to winter here;
and proceeded so far as to request the advice of my friends at home on the subject.
I felt very desirous, if I must winter in Norway,
which I had from the first of my leaving home been anxious to avoid,
to make the best of my way there, and go by the vessel my friends here had chosen for me,
which was soon to sail; concluding,
as Copenhagen has been brought before the view of my mind,
as a place at which I must be willing to spend a short time,
I might take it on my way back to Pyrmont in the spring.
But the subject coming more weightily before me,
I thought I clearly saw it would be unsafe for me to return to England,
or go by the vessel now in the river bound for Christiana;
and that there was no way for me to secure a safe arrival in Norway,
but to go by the way of Copenhagen; that my taking Copenhagen on my return,
would not be accepted by my Divine Master; and therefore,
although the prospect of an overland journey, quite alone, appeared discouraging,
unacquainted as I was with the language, currency,
and usages of the countries I should have to travel through,
and the doctor advised against the attempt from the state of my health,
yet as I could see no other way with clearness,
I began to make arrangements for my departure.

Sixth-day, 16th of eleventh month, after taking leave of several of my friends,
I proceeded to Altona; obtained my passport from the governor,
with his good wishes for my safety;
and taking my last meal with my kind friend James Vandersmisson,
who had furnished me with provision for my journey,
about two o`'clock in the afternoon I took my seat in the wagon,
which was to convey me to Kiel, the body of which was fixed on the axletrees,
and in it was slung a single-horse chaise seat.
This was a comfortless conveyance to travel in at this season of the year,
the weather being extremely cold.
My fellow traveller in the wagon professed to know some English,
but it was very little he knew, in addition to which he was so dull of apprehension,
that he was no fit companion.

While they were waiting for the letter-bags in Hamburgh and Altona,
I had to sit in the wagon until it was dark, before we started on our journey:
notwithstanding this detention was trying, independent of my suffering from the cold,
yet I felt truly thankful when I turned my back on this field of labour and inward travail,
not being conscious of having omitted aught that was called for at my hands.
This I esteemed among the many favours my heavenly Father has in mercy vouchsafed
to dispense during the many solitary weeks I passed over in Altona,
the retrospect of which affords some support to my mind,
when looking at the trying journey before me.
The night set in very dark, with rain, which beat into our vehicle:
after we had pursued our journey a few miles, I perceived we entered a river,
and travelled up it or across it about half a mile;
soon after we left the river a part of our carriage gave way,
which our driver secured by ropes.
The darkness of the night was such,
that our driver considered it to be unsafe to proceed without a light,
he therefore called at a cottage, and procured a lantern; but this was of short duration,
the wind and rain were tempestuous, and our lantern being out of repair,
the candle would not keep lighted,
we were therefore under the necessity of making the best of our way in the dark.
Before we reached the end of our first stage, our harness broke,
which they had difficulty in mending, so as to get forward with safety.

At about ten o`'clock we reached Ultzburgh, our first stage,
about fifteen English miles from Altona.
I had now been in the wagon about ten hours, and felt the need of refreshment:
being provided with some thick chocolate in a bottle, I procured some milk;
but although we halted nearly two hours, all my efforts to have it made hot,
proved in vain; I was therefore obliged to be satisfied with a drink of cold milk,
and we proceeded.
About three o`'clock on seventh-day morning, after breaking our harness a few times more,
we reached Bramstead, a stage of about fifteen miles further;
here our luggage was taken into the post-office: the tavern being opposite,
where I found I could procure hot milk, to mix with my bottle of chocolate in my pocket;
but through great fatigue I reeled,
and struck the bottle of chocolate against the leg of a table,
and broke it into small pieces;
the chocolate poured out at the bottom of my pocket and through the flap of my coat:
my greatest trouble now was how to get my clothes clean, having no others with me.
I found I must not expect help from the woman of the house,
who looked at me without in any way attempting to
lend me assistance to make myself clean,
I therefore managed by signs to get into the kitchen, procured some water,
and did my best towards cleansing my coat from the grease and soil of the chocolate,
drying it by their miserable fire.

Having lost my chocolate, I ordered, by signs, a breakfast,
for which I had to wait an hour; while my breakfast was preparing,
I went over to the post-office, to see that my luggage was safe;
when I observed a person tying up the bag I had with me with tape;
supposing it had become loose, I thought it was kind of him.
After having taken my breakfast, observing they were about loading the luggage,
I proceeded to see that the whole of mine was put in again, when, to my surprise,
I found the king`'s seal was put on the tape, as was also the case with my leather trunk.
I took my fellow traveller to them, pointing to the seals;
and by signs he made me understand, I must not attempt to open my luggage.

As I was altogether a stranger to the usage of the country,
and had no opportunity of inquiring why it was so,
and not observing that my fellow traveller`'s luggage placed under similar restraint,
various were my conjectures as to the cause of it, and what might be the result.
The busy enemy now watched his opportunity to improve
the various suggestions that presented to my mind,
as the cause of my luggage being sealed, and to bewilder and distress me,
and to cast me down below hope of escaping being
confined in one of their miserable prisons,
I remembered the governor and the police-master at Altona informed me,
their laws did not allow of distributing books or papers without leave of the police.
Having some tracts sent from England,
the whole of which I did not feel easy to take with me from Altona,
the day before my departure I left some at the guard-house among the soldiers,
and others I gave away in Altona,
a step I had well considered before I attempted to take it:
these considerations led me to conclude the circumstance
had come to the knowledge of the police-master,
and that he had taken offence at it, whereby my luggage was to be overhauled at Kiel.

In the afternoon we made another stage, and reached Ploen:
here my fellow traveller left me; imperfect as I found him in my native language,
I felt greatly stripped when we parted: we remained here nearly four hours,
being twenty English miles from Kiel; we took in a passenger for Kiel,
and changed our carriage, but the change did not add to my comfort,
for the curtains that should have defended us from the cold night air,
were so torn they afforded us but little shelter.

On our arrival at Kiel, I went to observe their movements respecting my luggage,
which was put into a room with the rest; it being now three o`'clock in the morning,
as I supposed the tavern-keepers would be all in bed,
and the post-office I found was no place of entertainment,
I considered how I should dispose of myself until the tavern-keepers were up:
I at length concluded by signs to obtain leave to sit in the wagon until morning.
Conversation took place between my fellow traveller and the post-master,
and as they frequently turned round to me, I concluded I was the subject of it,
but on what account, I was unable to understand; but hearing them name the merchant,
to whom I was directed, I felt cheered, and the more so, when my fellow traveller,
by signs, invited me to follow him to the Packet Hotel.
The people were in bed, but he would not leave me until I was safe in the house,
and by the bedside of the son of the hotel-keeper, who spoke English,
which was a comfort to me, that I cannot describe.
The young man, hearing of my desire to go by the packet,
assured me my luggage could be cleared in time;
but I considered he did not know under what circumstances it was placed.
I requested to go to bed, which was more desirable than food,
although I had been kept on short allowance.
As there were persons in the house going by the packet,
I requested to be called when they were,
and if it appeared best for me to encounter the passage by sea,
I would try to do my very utmost.
My kind friend Dr. Steinheim, advised my wearing a warm, flannel waistcoat next me,
which I had not been used to do; I therefore put one on the day I left Altona:
the irritation it produced was painful to bear,
and it occasioned a rash all over my body; as the eruption increased,
the pain in my chest and hoarseness gradually left me, which I esteemed a great favour.

I was called with those who were going by the packet, and did my utmost to rouse myself,
to give the subject of going all due consideration;
but the way for my proceeding was quite shut up, and why I could not tell.
I reasoned, that if I met with no other obstruction than my fatigue of body,
although it was great, I might regret missing so good a passage as it was likely to be.
I also feared, if I let this opportunity slip,
and remained at Kiel until the packet sailed again this day week,
we might have to beat about for days to make a passage.
The more I gave way to a desire to take my departure in this packet,
the more the uneasiness of my mind increased,
and the more sensible I was made that my present proper place was to remain at Kiel,
and trust for a good passage next week;
being assured if my remaining here was in the line of Divine appointment,
that same power which required my halting, was able to waft me over in the next packet,
in as short a time as if I went by the packet today, if He sees fit.
I therefore laid me down again to rest my weary bones: the keepers of the hotel,
I believe, did what they could to make me comfortable; but I needed more caring for,
than I had a right to expect at a hotel.
As I did not feel myself equal to go to the residence
of the merchant I was addressed to for help,
on my first rising this morning I sent to him; he soon made me a visit,
and spoke English.
I thought he appeared sensible of the care I stood in need
of and capable of entering into sympathy with me:
he left me, and calling again, put the question to me, was I comfortable.

I told him I needed more quiet than the house afforded,
and more of little matters provided for me than I could expect to have where I was,
I therefore should be glad to procure private lodgings: he left me, and soon returning,
offered me the privilege of making one of his own family.
I felt a difficulty to accept of his kind offer;
but as I was well assured it was made in great sincerity,
and fearing his feelings would be hurt if I refused, I accompanied this my kind friend,
Abraham Christian Bower, to his own home.
He kindly sent his clerk, who spoke English, with me to the post-office,
to see about my luggage.
The officer on duty behaved with great civility; I gave him my keys,
and after questioning me as to the contents of my luggage,
he gave liberty to have it sent to my lodgings;
and thus my anxieties respecting it were brought to a close.
I soon began to feel myself at home in my new abode, my only regret was,
the wife of my kind friend was not acquainted with my native tongue; this regret,
she gave me to understand, was great on her part.

Second-day, my flesh was so sore and bruised, that I was obliged to keep at home,
with my mind exercised towards the Lord, who I believe had required me to make this halt,
to preserve me from running before my guide,
and to keep me walking answerably to my profession, and the station I was travelling in,
as becomes a minister of Jesus Christ.

Third-day, to comply with the request of an invalid,
I ventured to make her and her husband a visit; she spoke English well:
with them I spent about two hours, to my own, and, I believe, their satisfaction.
It would almost appear as if she had previously known of my intention of coming to Kiel,
and, as such,
had been storing up questions to put to me respecting the members of our Society,
its practices, and on various religious subjects.
Although in my present state of bodily health,
I felt unequal to much exertion of this sort,
yet so fully convinced was I of the purity of her motives,
that I knew not how to refuse doing my best to answer her inquiries.
In many respects,
the information she had received respecting our principles and practices was very erroneous,
but which she acknowledged I had been enabled to clear up to her satisfaction;
and that I had removed from her mind sentiments which
she had imbibed unfavourable to our religious Society;
especially an opinion that we had no regular ministers among us.

On returning me my certificates, she said she had not only read them with attention,
but with pleasure, being fully satisfied these reports were not correct,
and in observing the watchful care the Society exercises over its ministers: she added,
"`From the account you have given me of your principles and practices as a Society,
it appears to me you come the nearest to the first Christians,
of any I have heard of in the present day; but when I was visiting at a watering-place,
I observed the professors of the established religion, who called themselves Protestants,
attended play-houses, dance-houses, and card-parties, on the sabbath-day;
there was also a settlement of some who called themselves Methodists in this place,
who protested against these practices of the members of the Establishment;
but I observed these Methodists indulged themselves in eating
and drinking beyond what I consider true moderation allows,
also in dressing themselves, having their houses furnished,
and conducting themselves in other respects like the people of the world,
aiming at great business to get riches.
I also met with some Roman Catholics who appeared to think much of themselves,
because of their abstinence and fasting on certain occasions.
As I am persuaded you will give me an honest reply,
pray tell me how is it with your Society in these respects.
Do they make great entertainments, having many dishes on their tables?
Are their houses furnished after the manner of the world?
Do they love to get money to keep it?
Are they covetous, and do not distribute according to their means to those who have need?`"
I felt myself brought into a great strait,
as my inquirer looked for an honest answer to her plain questions,
and for the moment was reduced to a state of awful silence.
I however replied, "`I hope I am safe in saying we still have preserved among us,
as a religious Society, those of whom it may be said,
they are endeavouring to be found walking in the
path of true self-denial and the daily cross,
in these and every other respect;
yet there are others among us who are sorrowfully departing from the
law and those testimonies which we are called upon to hold up to the world.`"
To which she again queried,
"`Are these departures mostly with those who have
joined your Society by what you call convincement,
or such as were born members?`"

I did not feel myself under difficulty in making a reply,
as it is obvious this departure chiefly is to be
found among those who have had a birth-right:
this matter being so far set at rest,
another query was brought forward more difficult for me to clear up to her full
satisfaction:--"`But what does your Society do with those who live,
and furnish their houses, and dress after the manner of the world,
and those who aim at doing great business to get rich because they are covetous.

"`Do your meetings for discipline, as you call them, disown such?
which you say is the case with your other disorderly members; for such I consider them,
according to the account you have given me of what your principles are, and,
if lived up to, will lead to the practice of.`"
It was trying to me to converse so long together, and I was obliged to return home,
having done my best to satisfy her inquiring mind;
but as her store of inquiry was not yet exhausted,
she engaged my company for the next day.

Fourth-day, feeling much debility from my exertion yesterday,
I was obliged to keep at home.
Fifth-day, being recruited, I spent a short time with my female friend and her husband,
endeavouring to satisfy her mind on the various subjects she brought forward.
I presented her with Henry Tuke, on Faith,
which I expected would furnish fresh work when we met again.
Three young men, students, gave us their company,
towards whom something began to stir in my mind, which I believe,
had I sincerely cherished, would have produced matter for communication.
They left me under very uneasy and distressing feelings: at times,
I would willingly have requested my female friend to invite them to her house,
to afford me an opportunity of relief;
but as this proposal had not the sanction of my Divine Master,
I found my safety would be in patiently bowing under the secret condemnation I merited,
and there let the matter rest, if the way never opened for us to meet again,
which never did take place.
May I learn more perfect obedience by the things I suffer, is the prayer of my soul!
I returned to my comfortable home, satisfied thus far with my detention at Kiel.

In the afternoon, accompanied by my kind landlord, I made a visit to pastor Harms,
a zealous, and I believe, pious preacher, of the Lutheran persuasion;
the necessity of the one saving baptism of the Holy
Spirit and fire was pretty fully entered into.
The pastor closed the subject by saying,
he had read the addresses to Altona and Hamburgh, etc.,
and was fully satisfied in his own mind I had known something of this baptism,
and expressed his earnest desire for my preservation to the end of my arduous journey.
