== Chapter XVII.

Sixth-day morning,
the way clearly opening in my own mind for me to take my departure on first-day,
I went on board the packet to secure my berth;
the appearance of the vessel and captain promised as much
outward comfort as I expect to meet with on ship-board.
On my way home we called upon my female friend; painful as it was to me,
from a return of the affection of my breath, to keep up much conversation,
I had not power to resist her inquiries.

Seventh-day morning, I awoke with the assurance that,
if I maintained my integrity towards God,
notwithstanding my many and unexpected detentions,
and having my journey to perform at this late season of the year,
I should be wafted over to Copenhagen with a short passage, and reach Norway safely,
to pass the remainder of the winter; but I must be content to live one day at a time,
avoiding all unnecessary anxiety about the morrow.
We called upon our female friend and her kind husband.
I expected to hear remarks from her on Henry Tuke`'s work on faith,
instead of which she fully accorded with the sentiments it contained;
except that she could not reconcile to her mind the possibility of those,
who never heard of Christ or the Scriptures, experiencing salvation.
I was enabled to explain the matter to her,
by reference to passages in the New Testament,
that she acknowledged she did not expect this subject
could have been cleared up so fully to her satisfaction:
at our parting, in a feeling manner she expressed her thankfulness to the Almighty,
who had thus unexpectedly brought us together,
and that my visit to Kiel would be in her affectionate remembrance
as long as she was favoured with her recollection.
In the evening I made a visit to the Dowager Countess Bernstorff:
she is very far advanced in life.
I was very agreeably struck with the great simplicity
of her attire and her unaffected manners;
she received me with that freedom and ease which is characteristic of those,
however exalted their station in life may be,
who are in sincerity seeking their way to Zion with their faces towards it.

We spent sometime agreeably together,
opening our views on matters of vital importance in the work of salvation;
her sentiments on these subjects evidenced she was well
instructed in things appertaining to the kingdom of heaven.
I had a short religious communication to her,
which she acknowledged she believed would at times be sweetly in her remembrance,
as well as the satisfaction the visit afforded her:
she regretted the shortness of our acquaintance,
and expressed the earnest desire she felt,
that the blessing of the Most High might attend all my labours:
this visit crowned my week`'s work.

First-day morning, the wind being fair,
the captain came to inform me he should sail earlier than he had at first proposed.
I was quite ready to take my departure,
but this information occasioned me more of a bustle than was desirable:
we had a quiet sitting together before we parted.
My visit to Kiel will I believe be in my remembrance
at times while able to recollect at all.
I went on board the packet, where I found an abundant supply of sea-store,
the bounty of my kind friends at Kiel.
In about twenty-five hours we reached Copenhagen,
which was considered as quick a passage as is generally made;
had it not been for the darkness of the night and the dangerous coast,
we should have landed some hours sooner.
My kind friend Abraham Christian Bower had written
to a merchant at Copenhagen to meet me at the packet,
but our arrival being earlier than was expected,
my caretaker did not reach in time to receive me.
I therefore remained on board a considerable time in a state of suspense,
fearing the information respecting me had not reached the merchant.
Viewing my situation as a stranger to the language and usages of the people,
among whom I felt as if I was now to spend some time;
accompanied also by a deep sense that trials awaited me in Copenhagen,
I was unable to suppress the flood of tears that gushed from my eyes.
A young man at length came to my assistance,
but he was so imperfect in the English language,
that it was but little he could do for me.
At the police-office, keeping on my hat excited attention, yet I was handsomely treated.
I was taken to a first-rate hotel,
and found there was no other way but to make the best of my situation for the night.

Third-day.
A son of Dr. Brand`'s, who was one of our passengers in the packet,
and paid me great attention on board,
at our parting gave me his father`'s address and an invitation to the house.
I proceeded to the doctor`'s residence; and on informing him how I was circumstanced,
his son took me to the Hotel Royal, where I had every accommodation I stood in need of.
I now began to feel more of that exercise I had been introduced into,
before and on my landing.
I was led to take a retrospect of the remarkable manner
I had hitherto been cared for and helped through difficulties;
holding out encouragement to hope I should be carried through
whatever might be called for at my hands in this place,
if I kept simple in my reliance on all-sustaining help,
free from consulting with flesh and blood,
and fully resigned to the service designed for me by my Divine Master here,
endeavouring after a state of nothingness of self,
and to know the Lord my God to be all in all.

In this dependent state of mind,
I was favoured to see that my course to Norway being thus directed,
was in order that I should attempt to obtain a personal interview with the king,
and present him with the addresses to Altona, Hamburgh, the magistrates and clergy,
and a copy of the proposed regulations for Hamburgh,
and Danish translation of my certificates;
but how to accomplish such an undertaking placed me in a trying situation.
The merchant I was referred to here for help, could not understand my native tongue,
so that I could not look to him.
I clearly saw, that except I did my best to obtain a personal interview with the king,
I should not be able to leave Copenhagen with a peaceful mind,
so essential to pursuing my future prospects of religious duty with patience and alacrity.
Under this assurance I earnestly besought the Lord my God, that he would be pleased,
as I knew not where to look for help, to direct me aright.
I retired to my bed,
but the difficulties that encompassed me were such that I slept but little.

In the morning I concluded to call upon my kind friend, the doctor,
and if the way opened for it, to lay my situation before him;
but this not being the case, I returned to my hotel, and sat down in quiet,
waiting on the Divine Counsellor to know how I was to proceed;
when my attention was unexpectedly turned,
having quite forgotten that I had them in my possession, to a list of names,
given me by a kind friend at Hamburgh,
of persons here whom he considered to be religiously disposed.
I searched my trunk for the paper, and having found it, sat down to read the list over.
When I came to the name of a person whom the paper stated was secretary to Count S+++______+++,
prime minister to the king;
I felt a stop against proceeding further in reading them over.
I thought the clear pointings of duty were to make him a call.
I procured a guide, who could act as my interpreter,
and we proceeded to the house of the count, where his secretary also resided.

On entering an anti-room, where the messengers were in waiting,
we inquired for the secretary, and were informed he was from home,
and his return very uncertain.
I felt as if I was fixed to the spot,
which I suppose attracted the attention of one of the messengers,
who again answered my inquiry, by saying that Count S+++______+++ was at home.
I considered I was a foreigner, and had nothing to depend upon to introduce myself,
but the merciful interference of Him, who is King of kings and Lord of lords;
and felt that my making the request to speak to him would be a bold attempt:
but as I could see no other way for me to proceed,
I requested the messenger to inform him that an Englishman,
one of the Society of Friends, called Quakers, would be obliged to him for an audience.
While waiting the return of the messenger,
adorable mercy preserved me from sinking below hope of being carried through the work,
which I believed was assigned me.
The messenger returned with this answer, that if I would wait,
the count would receive me.

I was shortly after ordered into his apartment; amidst hope and fear.
The count spoke my native tongue, which I esteemed a great favour.
I introduced myself to him by presenting him my certificates;
he appeared to read them with attention, making his remarks as he went along,
and closing with expressions of approbation,
at the care which the Society exercised over its ministers: he then asked,
"`Have you any of your Society in Copenhagen?`"
I replied, none that I knew of: he then added, "`Well, sir, what can I do for you?
what service can I render you?`"
This so opened the way for me,
that I felt no hesitation in informing him how I had been engaged in Altona,
and that if my great Master had any service for me at Copenhagen,
I believed it was to present to the king in person the address,
and lay before him such matters as at the time might arise in my mind;
I then requested him to make way for me.
He replied, the king did not understand English,
therefore he could not see what good was to result from the interview.
On my pressing the matter, he asked if I had the addresses with me,
as he should like to see their contents,
before he proceeded to obtain an interview for me with the king.
This I felt to be a reasonable request, and told him I had them not in my pocket,
but I would return to my hotel and bring them; on which he said,
he would remain to receive them.

On my return he expressed his fear that my hat being kept on my head would be in my way.
I was now so carried above discouragement, that I replied,
I hoped that would not be the case,
and requested he would fix the time for me to wait upon him for an answer;
to which he replied, he must attend the king in council tomorrow,
that if I would come the day after, he would inform me the result of my request.
Agreeable to appointment I waited on him;
from the kind manner with which he gave me his hand,
I felt satisfied he had not taken offence at any remarks which the addresses contained.
After some conversation,
he informed me the king had concluded to receive me at eleven o`'clock tomorrow,
and that he, the count, would undertake to interpret for me.
I had been thoughtful, if my request was granted,
how I was to find a person to interpret for me whom
the king might in all respects approve of,
but my good Master cared for me in this as well as in every other respect.

The count then looking rather earnestly at me, said,
"`You do not mean to appear before the king in those clothes,
do you?`" The breaking my bottle of chocolate,
independent of my clothes being very much worn, had given them a greasy appearance.
I told him I had no others with me, having left them at Altona,
intending to furnish myself with winter clothes when I reached Norway,
but I would endeavour to do my best to smarten myself; at which he smiled.
He requested I would come to him next morning,
and he would take care to have me conducted to the palace,
and be there himself to introduce me to the king.

On my way to my hotel, fresh trials began;
the enemy to all that is good bringing before the view of my mind my arrest at Altona,
with the difficulties I had to encounter in consequence of it;
setting before me how much worse I would be likely to fare here,
if offence was taken at anything I might communicate,
being at the very seat of government,
and a government where the word of the king was law.
But these buffetings of Satan were not permitted to be of long duration;
yet my baptisms were great, and no experienced,
exercised brother or sister near to console and comfort my tried mind;
none to look to for help, but the great universal Parent of all.
I set to work, did my best in cleaning and brushing my clothes and hat,
which was much in the same trim as my clothes.
I kept quiet in my apartment the remainder of the day, and, as may be supposed,
passed an anxious night, under deep exercise of mind, that I might be preserved faithful,
and deliver the whole counsel given me by my Divine Master.

I proceeded according to appointment, next day, to the count`'s residence,
who received me with his usual kindness,
and put me under the care of a confidential attendant to conduct me to the palace.
Entering a covered passage which led to the interior of the palace,
my nerves were not a little shaken, at the sudden appearance of eight of the tallest,
largest men I ever before saw, standing together under arms,
whose enormous hair caps and mustachoes gave them a terrific appearance.
Their countenances did not manifest a favourable disposition towards me,
I supposed in consequence of my entering the palace with my hat on;
although I doubt not this matter had been arranged by my kind friend the count,
from the great respect shown me by the different officers I was with afterwards.

I was first conducted into an apartment, where the king`'s messengers were;
here a chair was kindly offered me, where I waited some time;
and found it very hard work to abide in that state of mind set forth by our holy Redeemer,
"`When you shall be brought before kings and rulers for my sake,
take no thought beforehand what you shall speak.`"
The count at length arrived, and took charge of me;
while he ordered my attendant to be in waiting, on my quitting the king,
if I had occasion for him.
I was now taken into the king`'s anti-room, among the great officers of state,
to whom the count introduced me,
and such as could speak English manifested a sociable disposition.
It was to be expected that my keeping on my hat would excite attention,
as this empty mark of respect is more adhered to in Denmark,
than in any place I have been in on the continent;
but I could not observe the least appearance of disrespect on account of it.
It is some relief in trouble, or when under trial,
to have a companion to share the burden with us; but this not being permitted me,
I endeavoured to labour after resignation.
The door of the king`'s apartment at length opened,
and the count requested I would follow him.

At the door the king`'s chamberlain took off my hat,
and kept it till my return into the anti-room.
On entering the apartment I found the king in waiting to receive me:
I introduced myself by a short religious communication, on which the king,
through the count, replied, he felt obliged to me for what I had expressed to him,
and that I could not have desired better things for him.
I then informed the king what had induced me to leave my home, and come on the continent,
with the manner in which I had been engaged at Altona, a part of his dominions,
and also at Hamburgh, having the addresses to Altona, Hamburgh,
the magistrates and clergy, with a German copy of the proposed regulations,
and a Danish copy of my certificates, I requested the king`'s acceptance of them;
to which he replied he would, and took them from me,
saying it was pleasant to him to find my mind had
been thus interested in the welfare of his dominions,
and that it was his desire to promote religion among his subjects.

A pause for a short space ensued,
during which I found I must be willing to introduce a subject,
on which I knew a deputation from Hamburgh had waited on him,
but had not succeeded in their attempts.
I therefore requested liberty of the king to intrude on his time a little longer,
to lay before him, for his serious consideration, a subject which I dared not omit.
The reply was, "`Go on.`"
I told the king it was respecting the little lottery,
and as Altona and Hamburgh are so very near each other,
it must be obvious that it is of importance to the welfare of both places,
that friendship and a good understanding should be maintained between them,
the better to preserve the internal quiet of each, being under different governments.
If this friendship and good understanding, should by any means be broken,
it might prove the means of their becoming a great annoyance to each other;
and there was reason to fear this already.
I asked leave to explain myself, and was requested, in a kind manner, to relieve my mind.
I then said, I had been informed by persons in the government in Hamburgh,
that they at one time had a little lottery in their state,
but finding it to be injurious to the poor, it was totally abolished,
in hopes Altona would follow their example; but this not being the case,
their views were frustrated, their poor engaging in the lottery at Altona,
thereby impoverishing themselves and families.
It cannot be denied but this lottery must be a great injury to the poor, for,
in proportion as the public treasury is enriched thereby,
the pockets of the poor must be emptied.
I then exhorted the king to abolish this lottery,
and raise the money it produced towards the support of the state,
by levying a tax on the rich,
which I believed would in the end afford him much satisfaction.
I then acknowledged the gratitude I felt for his kind attention to my remarks,
and the desire that the remembrance of it might never be erased from my mind.
The opportunity altogether so affected my feelings, I could not suppress my tears:
the king and my very kind interpreter also appeared affected; and when I withdrew,
the king took leave of me in a respectful manner.

I returned with the count into the anti-room,
who assured me he felt satisfied he had introduced me.
Here a fresh and unexpected trial presented,
feeling something given me for the officers of state,
who were in waiting to go into council;
but I was again strengthened to express to them what my Divine Master entrusted me with,
my kind friend, the count, again interpreting.
It appeared to be well received by them,
and they kindly gave me their hands at our parting.
I now put myself under the care of my attendant to my hotel;
with my mind relieved from the burden I had been labouring under;
feelings of humble gratitude arose for the Divine assistance afforded me,
and I was favoured with a belief that faithfulness had marked my footsteps.
This little lottery is one which the government has under its own care;
and so small a sum as four pence may be advanced towards a share in it:
I was informed from good authority,
the time of drawing brings together such a concourse of
ragged miserable objects who have ventured their all,
as cannot easily be conceived.

There being only one vessel left in the port bound for Christiana,
and likely to be the last this season, I hastened to the merchant,
under whose care I considered myself placed, to secure my passage to Norway;
feeling desirous to get quietly away from Copenhagen as soon as I could.
We went on board the vessel,
but the prospect of my being in any respect made comfortable was very discouraging,
she being only forty tons burden;
the cabin was so small I could stand in the middle of it,
and nearly touch the sides with my hands.
On account of the season of the year the stove was moved
into the cabin to avoid the sea breaking over it,
and putting the fire out;
the berth I was to sleep in was as close to the fire as it could be,
not to scorch the bedding, and here the cooking was to be performed;
all these circumstances operated for awhile to discourage me;
but having heard such dismal accounts of the difficulties
of an overland journey at this late season of the year,
as the weather had already set in for severe frost and snow,
and fearing the vacant berth should be secured by some other person,
I agreed for my passage.
I made a call upon my kind friend the doctor,
and informed him of the steps I had taken for my departure,
when he gave me such reasons for not proceeding in the vessel at this season of the year,
as to confirm me it would be most prudent to relinquish going by her to Norway.
I therefore engaged the merchant to settle with the captain in the best way he could;
but in doing this there was no difficulty,
for the captain expressed himself satisfied that I had come to this conclusion,
as he said, if the weather should be stormy,
my being in the cabin would put them to difficulty,
and they could not avoid being a great annoyance to me.

My mind was introduced into exercise, on account of the queen and princesses,
yet as I did not feel sufficient to justify an attempt to obtain an interview,
I concluded my safety was in keeping quiet,
not doubting but that if this exercise was of the Lord,
way would open for its becoming matured, without care or exertion on my part,
as I did not feel it laid upon me at present to move in it.
I took an early opportunity of informing my kind friend the doctor,
that I was clear of the captain of the vessel,
and must submit to an overland journey to Christiana
as early as matters could be arranged for it,
desiring his advice in my movements in this respect.
He proposed furnishing me with letters to Elsinore,
to procure me letters when I crossed the Sound, and landed at Elsenburgh in Sweden;
and he advised me to advertise for a travelling companion to Christiana.
From accounts received of wrecks which have recently occurred on the coast to Norway,
I esteemed it a mercy that my intentions of going by sea were frustrated;
not only as it respected the danger and difficulties I escaped,
but I began to fear my leaving Copenhagen by her would have been,
as the prophet Isaiah describes, with haste and by flight,
and have laid a foundation for sorrow.

Next day I visited professor Muller, a serious character:
we spent some time agreeably together; at our parting,
he offered me a list of names in Christiana which
he apprehended would be of service to me there,
adding, "`But there is that about you,
that will be a sufficient introduction for you anywhere.`"
I continued under exercise about the queen and princesses,
yet no way opened that justified my taking steps to obtain an interview.
I made calls upon some of the persons whose names
I had on the list I brought with me from Hamburgh;
also upon my kind friend the doctor,
to inform him no reply had been made to my advertisement for a travelling companion.
I had, agreeably to his advice, also advertised for a servant,
to take charge of me to Christiana, requesting him, should a suitable person offer,
to have my letters in readiness.
He told me that one of the ladies who waited on the queen, who was a religious character,
and spoke English well, residing in the palace,
requested I would make her a morning`'s visit.
At the time I did not reply; but before I left him,
I found if I did what appeared to be right, I must say to him,
"`If your friend will appoint a time, and I am informed of it,
I feel quite at liberty to make her a visit.`"
This felt like the opening of a fresh line of service, and, at first view, was trying,
as I knew not what it might lead to,
nor when it would end: for every day`'s delay now, I understood,
would endanger my being detained on the road,
from the fall of snow that usually takes place about this season of the year.
I heard nothing further about my proposed visit,
until I called again upon the doctor for my letters;
when he informed me his footman was gone to my hotel to conduct me to the palace,
where his friend would be in waiting to receive me:
the footman soon returned and took charge of me.

I passed the king`'s body-guards, as before described; ascending a flight of stairs,
on a landing I met with four more of the like description,
and two more on another flight of stairs: the pass being narrow,
on my approaching the two latter sentinels, I suppose from my having my hat on,
one of them viewed me with great bitterness in his countenance,
muttering something which evidently bespoke evil towards me.
This occasioned me some unpleasant sensations,
and feelings of thankfulness arose when I considered
myself out of the reach of his fire-arms.
In the apartment of the doctor`'s friend,
more of the attendants on the queen and princesses joined us.
I took my seat with them, but not as if I felt myself a stranger;
the like friendly familiarity was manifested on their parts.
We soon entered into serious conversation,
which appeared to awaken in their minds various inquiries
respecting our religious Society and its principles;
desiring reasons why we differ from other professors on certain points.
I was enabled to give such replies as I believe gave satisfaction.
I produced my certificates, in the reading of which much interest was manifested,
and observations were made thereon.

After we had passed some time thus agreeably together, one of our company withdrew;
she returned again, a young woman following her,
of amiable countenance in plain and simple attire: as she made up to me,
her attendant informed me it was the princess royal: thus taken by surprise,
for the moment I felt at a loss how to notice her properly.
I informed our company, our usual way of showing respect to those we meet, was,
by our offering them our hand,
which I could gladly do to the princess if I should not give offence.
On which, the princess put out her hand to me,
expressing the satisfaction my visit had afforded the king, inquiring if I had a family,
and after their welfare.
Further conversation took place,
in as familiar a way as would have been the case had I been her equal,
so easy was her carriage and manners.
Feeling something in my mind of a religious nature to communicate to the princess,
I informed one of our company to that effect, requesting her aid as my interpreter;
the princess being informed hereof, a short pause took place;
and during what I had to communicate, she appeared solid and attentive.
On my acknowledging her kindness in giving me such a patient hearing, she replied,
she felt obliged to me for the counsel I had given her,
and at our parting gave me her hand.
Having reached the door of the apartment,
she returned to express the desire she felt that I might be favoured to get safely along,
and return to my family in peace.

I now took my seat among my kind friends and new acquaintance:
the subject broken in upon by the entrance of the princess was resumed;
soon after which a message came from the queen, saying,
had she not been circumstanced as she then was, she would have seen me;
but as she found I was likely soon to leave Copenhagen,
if I would come to the palace at six o`'clock in the evening, she would receive me,
and engage Count S to interpret for us: I returned for reply,
I accepted of the kind offer the queen had made me.
After spending some more time in the company of my kind friends,
being as much at home as I could have felt myself in my own little habitation, we parted,
under the pleasing prospect of meeting again in the evening,
and I was again put under the care of the doctor`'s footman to take me to my hotel.
The interesting manner in which our time had been passed over,
the unexpected visit from the princess, and the message from the queen,
dissipated from my recollection the painful feelings
I experienced on passing the last sentinel.

In the evening, under the care of the doctor`'s footman, I proceeded to the palace,
at the time appointed: a person was ready to receive me,
who conducted me into the grand saloon:
here I found one of my kind friends with whom I had
so agreeably passed the morning was in waiting.
Taking my seat by her, she said,
"`Your communication in the morning has been blessed to me to the present time:
many of your remarks were as applicable to my state,
as if you had long been acquainted with my situation, and such words in season,
I believe, will long be remembered by me.`"
We again entered into serious conversation, during which, on my remarking,
I believed one cause why religion is at such a low ebb on the continent,
and which I observed with sorrow, is the laxity of the clergy: to which she replied,
"`Therefore we do not see that improvement in the morals of the people so desirable;
for some of the clergy now take liberties which were not formerly practised,
by attending the theatre and other places of amusement,
and their example unfits them for the usefulness
which they otherwise might be of among the people.
And this is not all: is it to be expected, if they are sent for to attend upon the sick,
they can be in a fit state of mind to go from the
theatre or ball-room to visit the bedside of such?
I think not.`"

When she closed, another of the queen`'s attendants, entering the saloon, said,
the ladies waiting on the queen and princesses and the queen`'s
chamberlain were about to give me their company.
I soon found myself amidst my friends,
with whom I had spent my time so agreeably in the morning; after awhile,
the young princess was brought in, an interesting, unassuming young person,
about sixteen years of age: the count also made one of our company.
It being announced that the queen was in waiting to receive me, the count led the way,
the queen`'s chamberlain taking off my hat on our
entering the apartment in which she was:
the queen gave me her hand in an affable manner, and with much earnestness addressed me,
which the count gave me nearly as follows:--"`Your visit to the king was satisfactory,
and from the great esteem he feels for you,
the queen regrets much her not being able to speak with you in your own language,
but the count will do his best for us both.`"
She then inquired if I had a family, and after their welfare--my own health,
with various other matters.
Feeling something in my mind of a religious nature to communicate,
I informed the count thereof, who acquainted the queen of it, when a pause took place.
Having fully relieved my mind, she expressed her gratitude for what I had offered,
and that my mind had felt so interested in their welfare;
she also hoped the princess would profit by the advice I had given her;
that it was her greatest desire she might be found
coming up in the way of her duty to her Maker:
she then expressed her concern for my safe guidance and peaceful return to my family.
On my querying, would a few books explanatory of our principles be acceptable,
the queen replied, not only acceptable, but she should feel thankful for them:
at our parting, she gave me her hand again.
I returned to my friends, I hope truly thankful this visit was thus well got through.
I was again put under the care of the doctor`'s footman, and returned to my hotel,
making sweet melody in my heart to the Lord, who, in mercy, watched over me,
not permitting me to make the hasty move I should have done,
had I gone away by the vessel.

Having now a pretty clear evidence that my service here was nearly at a close,
there appeared no other way,
than either to push forward to Christiana without loss of time, or remain,
and winter at Copenhagen, which I dreaded.
The prospect of procuring a servant was very uncertain; the frost had set in very severe;
the snow being already deep, and I was informed, from the look of the clouds,
there was a probability of a greater fall than has yet been this season.
I therefore requested the hotel-keeper and his family to make inquiry on my behalf:
the only applicant in consequence of this second attempt was a man of colour,
who professed to speak English; he had lived in the service of the hotel-keeper;
but I found, on inquiry into his character,
they were very cautious in saying much on that head; and what I could learn about him,
rather tended to confirm my mind in the very unfavourable
opinion I had at first sight of him.
I endeavoured to be willing to accept his services,
although the prospect of putting myself in the hands of an unprincipled man,
to whom I was a total stranger, during a journey of nearly three hundred and fifty miles,
which it would take ten or twelve days to accomplish, was a fresh trial of my faith.
In this time of extremity my Divine Master in mercy renewed his assurance,
that the same invisible arm, which had been, in such a remarkable manner,
made bare for my help and deliverance, if I continued to lean upon and confide in it,
would support me and bring me safe to the end of my journey,
whatever difficulties I might meet with.

Having arranged for my departure,
I called to take leave of my kind friend the Count S+++______+++;
we passed some time together in conversation on the slave-trade.
This afforded me an opportunity of explaining to
his satisfaction a circumstance he had heard,
namely, that there were Quakers in America who held their fellow creatures in bondage,
which he lamented.
I replied, I believed such individuals are not in membership with the Society of Friends,
and therefore the Society cannot be accountable for their conduct;
they either have been disowned for immoral conduct,
or for refusing to liberate their slaves agreeable to the regulations of the Society,
or they may be persons who attend our religious meetings, conform in dress and address,
but never were in membership with the Society.
A fear at times prevailed in my mind in reference to the attendants on the queen,
whom I met at the palace; and it continuing with me,
I saw no way for my relief but by being willing to take up my pen, and as matter arose,
commit it to paper this I accordingly did,
and the delivery of it a kind friend undertook.

[.offset]
It was as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To the attendants on the queen, whose company I was favoured with at the palace.

[.salutation]
Respected friends,

Believing, if I had not so hastily departed from the palace,
I should have had a little tribute to leave with you,
and not feeling quite comfortable on account of my unfaithfulness,
I sit down to pen what may come before me in the line of religious duty;
hoping it will meet your acceptance, as we are never likely to meet again in mutability,
but to be far separated from each other as to the outward.
I feel solicitous that the union of spirit,
which I believe was so mutually felt when I was in the enjoyment of your company,
may continue to the end of our days;
and that we never may come short in a concern for each other`'s welfare;
individually so running as to obtain the crown, and so fighting as to have the victory,
and not as those who run at uncertainty, by fits and by starts,
nor as those who beat the air.
But if this is our merciful experience,
short of which we should not dare to rest satisfied,
it is indispensably necessary that we continually, and without wavering, look unto Jesus,
with a single eye to his honour, in all our actions and transactions among men;
knowing him, who was the author and finisher of the saints`' faith,
in like manner to become the author and finisher of our faith, who,
for the joy set before him, endured the cross, despised the shame,
and is now set down at the right hand of God the Father;
making intercession for the sons and daughters of men,
but in an especial manner for those who,
in the expressive language of conduct are testifying to others,
they have none in heaven but the Lord,
nor in all the earth they desire in comparison of their God; that he is indeed,
in their view, the chief among ten thousands, and the altogether lovely one.
These have experimentally to say, of a truth he is the wonderful Counsellor,
speaking in their souls--to their states and conditions, as never man yet spoke,
solving all their doubts and dissipating all their fears.
His inspeaking voice, as formerly, continues to be spirit and life,
quickening and animating to a willingness to follow
Christ whithersoever he may be pleased to lead,
or in whatsoever he may require them to do, or to leave undone.

He is not only to these a wonderful Counsellor,
making them wiser than all their teachers can possibly do;
but they know him to be the mighty God, the everlasting Father and Prince of Peace;
availingly saying to the weak,
'`Be strong;`' and to those who have no might of their own,
'`Put on strength in the name of the Lord;`' strengthening
the hanging down hands and confirming the feeble knees,
of such as are ready to faint and grow weary,
enabling them to make straight steps to their feet in the way of holiness--that
way which is cast up for the ransomed and redeemed of God to walk in.
Notwithstanding such may at times have to mourn over their spiritual languor, and say,
in the bitterness of their souls, '`to will is present with me,
but how to perform that which I see to be my duty,
I know not;`' yet as patience has its perfect work, such will know,
that help continues to be laid upon one that is mighty
to save and able to deliver to the uttermost,
all that come unto God, through faith in Christ Jesus our Lord.
For although the youth may faint and grow weary, and the young men utterly fall,
yet the promises of God stand sure,
that '`those who wait upon the Lord shall renew their strength;
they shall mount upward with wings as eagles,`'--the wings of faith in
the sufficiency of the Divine power to make them more than conquerors,--and
of love to the cause of truth and righteousness in the earth;
'`they shall run and not be weary,
and walk and not faint.`' '`Your eye shall see the King in his beauty,
and behold the land that is very far off;`' and know Jerusalem to be a quiet habitation,
at times participating in that holy quietude of mind
as an earnest or foretaste of that which is to come.
And if this earnest or foretaste so far surpasses in reality any earthly delight,
and which all who have in any degree tasted thereof cannot but acknowledge it does,
what will the full enjoyment of this eternal reward be!

Let these considerations act as a spur to our diligence, to be willing, each one,
through holy aid, to do our very best to press forward to the mark for the prize,
which is what the Almighty requires of us;
and then he will not fail to bless our best endeavours,
and make them fruitful unto holiness, which is the mark we are to aim at,
that we may obtain the prize.
'`Be holy, for I, the Lord your God,
am holy;`' for without holiness we cannot see the Lord to our comfort.
In thus doing our very best, the testimony of the apostle will become our experience,
that, through Christ strengthening us, we shall be able to do all things,
to pass through the troop of temptation and besetments of time,
escape being taken captive by our pleasures and lusts,
leap over the wall of sin and disobedience, overcome those dispositions and inclinations,
which, until overcome, continue to be as a wall of separation between us and our God,
to all eternity,--that impassable gulf we read of between us and heaven;
for until this old man with his deeds, which are corrupt, is put off,
we cannot experience a putting on the new man, Christ Jesus the Lord from heaven,
the quickening Spirit; which I crave for you all as for my own soul,
and bid you God speed, remaining very affectionately, your well-wishing friend,

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Copenhagen, 7th of Twelfth month, 1821.

--

I waited on my kind friend the doctor, requesting my letters; who informed me,
he had been in conversation with the king this morning,
who expressed his desire that some of our Society, who were the right sort of Quakers,
would settle in his dominions; saying, as far as was in his power,
he would do his best for their relief, where they had scruples of conscience,
but much would depend on the manner of their settling:
if they should spread themselves abroad among the people,
it might prevent his giving them the relief he would desire to do,
especially as it respected the conscript law; for although an absolute monarch,
yet it was his desire, as much as possible, to preserve peace among his subjects.
Therefore, if Friends were to come as settlers, and spread themselves abroad,
and he was to excuse them from a compliance with
the conscript law and other laws of the state,
against which they had a conscientious scruple, in preference to others of his subjects,
this preference would be likely to produce an envious
disposition in the minds of their neighbours,
and induce persecution in a way from which he might not be able fully to relieve them.
But should they incline to settle as a colony,
he had a large tract of country in Jutland at his own disposal, good land and good air,
which could be purchased at a very low price, where,
without exposing themselves to difficulty, with respect to their scruples of conscience,
they might be able to live in quiet:
so much I was requested to transmit to my friends in England,
and I was to refer to the doctor for further information, if necessary.

I took an affectionate leave of the doctor and his family, they saying, at our parting,
my visit to Copenhagen would long remain in their affectionate remembrance,
as will also their unremitting attention continue with me.
This parting visit cheered me not a little, and revived a hope in my mind,
that my coming single-handed to Copenhagen, was in the line of Divine appointment,
and that the good cause had not suffered through me.
I began to feel like a bird whose wing-feathers had been clipped,
but grown again ready to take its flight.
No other offer being made as a caretaker but the man of colour above mentioned,
as no time must now be lost for my proceeding, fresh trials commenced,
which I found I must, as much as possible, keep out of sight,
or they would be likely to overwhelm me.
I was assured all this was permitted in mercy to my soul,
to humble and keep down the creature, and drive me home, for preservation and help,
to an all-wise and beneficent Creator, who had done so much for me;
and however severe this thorn in the flesh may prove, and my faith put to the test,
as to a hair`'s breadth, during this long, dreary journey,
I believe I shall be cared for to the end of it by Him,
without whose notice a sparrow falls not to the ground.
Thus, in unmerited lovingkindness, my good Master deals with me,
after having owned me by his help, and brought me through many difficulties;
lest the creature should plume itself on what has been accomplished,
and be tempted to take to itself that which is due to the Creator only:
for so far as we are in any way made instrumental of good to others,
our qualification is of the Lord and not of ourselves.
As I saw no way for me but to send for this man of colour,
and with the help of my friends make as secure a bargain with him as could be;
this was accordingly done.
He twice fixed his time of meeting us, but did not keep his appointment.
I made a third attempt, which proved effective.

He set so high a value on his abilities to care for me,
and manage my money to the best advantage, having before travelled in the same capacity,
and was so exorbitant in his demands, that we could not come to terms with him;
we therefore agreed to meet again next morning.
I passed a trying night,
aware I must comply with the best terms that could be made with him, or winter here,
being informed that those who were in the habit of acting in this
capacity would not venture out at this season of the year.
We met again, when his sharping disposition manifested itself more than it had yet done:
while my friends were doing their best to bring him to terms,
this query passed my mind--Must I commit myself to the control of this
unprincipled man for so I thought I clearly felt him to be,
and as wicked, dark a spirit as I ever had met with.
Pausing and looking on him, the evidence in my own mind was so clear that I must submit,
and cast my care on Him who had all power to chain down this man`'s evil disposition,
whereby he would not be allowed to harm my person,
that I informed my friends they must do their best with him,
and I must submit to place myself under him and proceed to Elsinore; this,
after much difficulty, they accomplished,
and an agreement was drawn up and signed by him,
that he might not take any advantage of me at my journey`'s end.
He demanded a sum in advance to purchase warm clothing,
but none ever appeared while we were together.

We had twenty-four miles of bad road to travel this night,
and it was dark by four o`'clock: I procured my passport,
and a carriage was waiting on us at the time appointed, which felt cheering to my mind;
although the quantity of snow that was falling, and the intense coldness of the air,
looked discouraging; but my caretaker was not come.
After waiting considerably beyond the time, he made his appearance;
on one of my friends requesting to see his passport he had none:
fears were now excited that he either had not applied for one or could
not procure such a ticket from his landlord as would obtain him one;
and the police-office was closed,
and would not open again until four o`'clock in the afternoon.
The horses were ordered out of the carriage,
as I saw no way but to wait until the police-office opened again.
Although this was a fresh trial of faith and patience,
yet I considered there was cause for thankfulness, as the probability was,
had he proceeded without a passport, he would either have been imprisoned at Elsinore,
and I left to shift for myself, or I must have been detained there or come back with him.
I found doubts were entertained that he would not be able to procure a passport,
and I felt as if I must give up all prospects of my getting from Copenhagen this winter.
I sat down overwhelmed in distress, and had none to whom I could open my mind but Him,
who I was favoured to believe had directed my course to Norway;
and who in mercy again condescended to give me assurance,
that although I might seem hedged in on every hand,
unable to see any way to escape from my present difficulties, all should end well;
and in that faith I rose from the seat on which I had been pensively reclining,
enabled to cast away my sackcloth, wash and anoint,
and appear among my friends with a cheerful countenance.
Before five o`'clock my caretaker made his appearance with a passport, and we proceeded:
the night setting in dark, made our journey tedious,
and we did not arrive at our hotel until eleven o`'clock at night;
our carriage being open in the front I suffered much from the cold.

First-day morning, I concluded to keep quiet at my hotel, except procuring my letters,
until the people had returned from their places of worship: in the afternoon,
there being a boat to cross the sound for Elsenburgh in Sweden,
thinking it a suitable opportunity to present my letters,
and procure others to Elsenburgh, we proceeded to the boat.
On our way, an agreeable looking, genteel young man, a Dane, addressed me in English,
offering his assistance in any way he could serve me.
He took charge of clearing my luggage at the custom-house, my passport at the guardhouse,
and had me safely seated in the boat,
and kept in sight as long as we could see each other.
Although our time was short for communication,
yet I thought there was a union of spirit experienced that words could not convey.

We proceeded in a small open boat, the passage across the sound being about six miles.
On our landing, I began to look for difficulties,
on account of my keeping on my hat at the police-office,
as we were obliged to appear together, being included in one passport,
and my caretaker was very lavish with his compliments.
At the guard-house the officer on duty treated me with great respect,
requesting my caretaker to inform me the necessary passports should be sent to my hotel,
to allow of an early proceeding on our way next morning.
Reaching our hotel, I was comforted in finding our landlord spoke English:
here I purchased a sling-seat, which I afterwards found a great accommodation.

My landlord told me when I received my passport,
I must go to the governor and show myself,
as it was a practice required of all foreigners; but a message came from the governor,
saying, he would not require my attendance, which I was told was a favour shown me,
but why I did not understand.
Having a letter given me by the English consul to a friend of his at this place,
to assist me in any way I needed,
although I was supplied by my landlord with everything I needed;
yet I considered it a respect due to my friend`'s kindness, who furnished this letter,
to wait on the person to whom it was addressed; I proceeded to his house,
and found in company with him two of his friends, one of whom spoke English:
serious conversation took place and continued some time.
When I was about to depart, the person who spoke English said,
"`Do you not remember to have seen me before?`"
I was not able to recognise him; on which he replied, "`I am the person who,
in the police-office at Copenhagen, solicited your company to Elsinore,
as you were going there as well as myself;
since that time I have felt interested in your preservation,
from the agreeable impression your countenance made on my mind,
and which I believe will long be in my remembrance.`"
He expressed his regret that his business was not accomplished,
or he could care for me to Gottenburgh, the place of his residence;
he furnished me with the following letter to his family:

[.offset]
Translation.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Elsenburgh, 10th December, 1821.

The bearer of this, Mr. T. Shillitoe, who intends to travel to Norway,
do I introduce to your acquaintance,
and beg you to do everything for him in order to make him, on his journey,
as comfortable as possible; help him in every respect,
and try to furnish him with every obtainable convenience.

[.signed-section-signature]
J+++.+++ M. Lundberg.

--

This unexpected occurrence was fresh cause for humbling my mind,
producing feelings of gratitude, in the first place, to my Almighty Caretaker,
and then to this my stranger-friend.
My kind friend at Elsinore advised me to travel by furbo, which is,
forwarding a messenger from station to station,
to be provided with horses at such times as they are needed;
this is attended with additional expense, but greatly facilitates the journey,
and at times is a saving in the end.
The stages seldom exceed seven English miles;
and the post-horses are furnished by the farmers,
some of whom live several miles from the stations.
A merchant, who had arrived from Gottenburg,
advised our taking the common run of the road and save this expense,
as at this season of the year there was so little travelling on the road;
which we concluded to do.

Second-day, we proceeded before it was daylight in a small open cart,
the body of which was fixed on the axle-tree:
we met with no difficulty about horses the first two stages,
but at the third station a company of strolling players had engaged all the horses,
and we were detained two hours, and lost six hours in this way today.
They were on their way to Gottenburgh as well as ourselves, and to escape them in future,
I learnt where their stopping-place was for the night,
resolved to travel late to get a stage before them,
which we accomplished by eleven o`'clock; and by this means we saw no more of them:
we gave our furbo in charge of the landlord, whose business it was to send it forward.
Everything about the house was so filthy I could hardly eat what they provided for me,
or get into my bed.

Third-day, we proceeded again at four o`'clock this morning,
fearing the players should start early and overtake us;
being in a house with them was distressing to me.
We were comfortably off as to horses this day, but miserable as to carts and provision:
by travelling late we made a good day`'s journey.
By this time I was fully convinced I had committed myself
to a man who would manage my money to his own use.
On our reaching the station at night,
I ordered our cart to be ready to start at four o`'clock the next morning,
taking care our furbo was sent forward;
the necessity of making the best of my way to Christiana
was strongly impressed on my mind,
independent of the apprehensions I entertained,
in consequence of the inhabitants bringing their snow-ploughs to the roadside,
that a great fall of snow was soon expected.

We did not reach Gottenburgh until a late hour,
worn down by hard travelling from the badness of the road, jolting of the carts,
and exposed to the extremity of the frost, and the lack of suitable food,
and suffering in mind also,
in consequence of the quantity of spirits my caretaker swallowed down.
From the manner in which I saw my money was wasting, I attempted to remonstrate with him,
but I found I must keep quiet.
I procured a messenger to conduct me to the house of the merchant I was to apply to,
in order to have my Swedish money changed for Norway currency,
but it was too late to transact such business that night;
the merchant proposed coming to my hotel next morning.
I had so much knowledge of the currency as to ascertain
that more than half of my money was expended;
I was not yet half-way to Christiana, and I had no means of obtaining more;
and the probability was,
I should not be able to reach my journey`'s end for lack of money.

I retired to bed under great distress of mind,
unable to discern how I was to reach Christiana, and to turn back,
I should be no better off, under the care of a drunkard, a swearer, and a dishonest man,
in whose word I could not place confidence.
In this trying situation I could see no way for my relief.
While thus struggling with accumulated difficulties,
strength was in mercy given me to pour out my complaint before that all-beneficent Being,
who in mercy permitted a glimmering of hope,
that my taking this course to Christiana had been under his direction,
and bringing again before the view of my mind the
assurance he favoured me with before leaving Copenhagen:
but where my help was to come from, continued to be veiled from me.
Earnest were my cries, that the wormwood and the gall might not be meted in vain,
but tend to humble and keep down the creature,
and bring it under subjection to its Creator.

Although the cloud that had been permitted to come over my mind a little broke away,
and a glimmering of sunshine appeared,
yet when the merchant gave me his company in the morning,
my situation resumed its former distressing aspect.
He saw I was in trouble, for I could not conceal it,
and when I laid before him the cause of my distress,
kindly offered to advance all the money I stood in
need of to carry me to my journey`'s end.
I gave him the money I had left,
on which he told me nearly two-thirds of the money I brought from Copenhagen was expended,
and that I was not half-way on my journey:
he then proposed my accompanying him to a merchant
who frequently travelled the route I was to pursue,
in hopes of his being able to afford me some help on my way.

On entering the house of this person,
my kind friend informed me he had been educated in the principles of the Jews,
but had embraced Christianity: he appeared kindly disposed,
yet it was very little information he could afford me.
Feeling something stirring in my mind for him,
strength was given me to put him in remembrance,
that unless he had really experienced the one saving baptism of the Holy Spirit and fire,
his change of religious profession would be of no avail, with more to that effect;
all which he appeared to receive in an agreeable disposition of mind, saying,
he did not know but that he was as good a Christian
before he renounced the religion of his education,
as he now was.
When we left, my friend expressed his hope that what I had communicated,
coming upon him so unexpectedly from a stranger,
would make such an impression on his mind as to prove of future advantage to him:
this act of faithfulness afforded me a ray of hope,
that I was still an object of Divine regard.
My kind friend, the merchant, willing to help me in my difficulties,
made a further attempt to get information from a friend of his,
who frequently took the route I was going,
and who had made correct memorandums of distances, stopping-places at night,
and expenses.
He procured the necessary particulars, of which he put me in possession,
giving the man an account of every day`'s work,
the time for starting and reaching our sleeping-place at night,
the expense of our horses and carts, and his own expenses, giving him each day`'s money,
and charging me in his presence not to advance any further sum, except on my own account.
The man hesitated about proceeding under such restraint,
but my friend made the account out so clear to him, that he was obliged to yield,
and I had to take nearly one-sixth part of my money to Christiana.
Matters being thus arranged,
my kind friend encouraged me to believe I should get well through to Christiana;
but my trials were not yet come to a close.
After taking an affectionate farewell of him, we proceeded on our journey;
the night was dark and the roads bad.
I felt thankful that we reached Hide safe, where we were to sleep,
although at a late hour.

Sixth-day morning, we started at four o`'clock:
the heavy fog and great fall of snow we had to travel through, in an open cart,
would have been more trying, had I not provided myself with an oil-cloth dress, fearing,
if my fur coat and cap became wet, they might prove a burden to me,
from the difficulty of having them sufficiently dried
to make it safe for me to put them on again.
We frequently broke our harness today, and lost our linchpins,
which is no uncommon circumstance in travelling in these farmers`' carts.
To supply the place of a lost linchpin, the driver cuts a slick out of the hedge,
and proceeds, seemingly unconcerned as to the consequences that may occur,
such as our being turned out of the cart on the mountain-road down the dangerous precipices,
close to the edge of which we passed, and over bridges, where the water was deep,
and no guard to prevent accidents.
We did not reach Quistram, our night`'s quarters, until late,
and we had to wait long for our horses at some places,
occasioned by the furbo-money being kept back, no doubt by the man.
My stock of white bread being exhausted, and only black sour bread to be procured,
I began to suffer on this account.

Seventh-day, proceeded as the route was laid out by my kind friend at Gottenburgh:
we were to reach a steep mountain we had to descend, also a river, before it was dark;
and arrive at Wassguard in Norway at an early hour;
but we had to wait for horses at every station today,
and did not reach the mountain until near seven o`'clock in the evening.
It was so dark I could not see any part of the way we had to go;
but a terrifying description had been given me by
the merchant at Gottenburgh of this steep.
I therefore resolved to do my best for my preservation,
and concluded to walk behind the cart, keeping hold of the tail-board;
this I was able to endure for awhile,
frequently driving my feet against large pieces of the rock that stood up in the road,
and at other times, on a sudden dropping into holes: at length the descent was so great,
I dared no longer remain behind.
I secured the arm of the driver, who himself had been obliged to abandon the cart,
and with much difficulty, kept on my feet over the mud and stones.
We now had water to cross; from the darkness of the night,
I knew not how I was to find my way safely into the boat.
I proposed to my caretaker to offer to hire a candle and lantern,
but it was not to be procured.
I began to get low in my mind and feeble in body, through fatigue and lack of nourishment.
Plenty of sour bread and brandy I found were everywhere to be had,
neither of which I dare partake of.
A stranger who was acquainted with the river bank, observing the difficulty I was under,
kindly gave me his arm into the boat,
caring for me until I was safe on the bank of the other side.

On my landing, I was invited into the ferry-house, which,
from the cleanly appearance of it, I gladly accepted.
We had now six English miles to Wassguard, and did not arrive till a late hour, fatigued,
wet and hungry.

A trying circumstance occurred this afternoon, which,
for nearly two hours after we left the station, kept my mind in a state of anxiety,
not knowing what the result might be.
At each station where the traveller changes horses, a book is brought to him,
in which he is required to write his name, nation, place of abode,
where he last came from, where he is going, and the number of horses he hired,
with a space for complaints if the horses were not ready by the time the furbo required,
or if the conduct of the keepers of the station or driver was improper.
I had entered all the particulars required of me,
and no complaints about the horses not being ready,
it being clear to me that the keepers of the stations were not to blame.
Just as we were ready to get into our cart,
my caretaker seized the book and erased what I had written, and wrote in Danish,
I could not tell what; but from the rage he appeared in, I suppose,
because his brandy did not please him, either in quantity or quality,
I concluded he had entered complaints that would rouse the keepers of the station,
and we should have the police after us.
I remonstrated with him, telling him, he had no right to make erasures in their book,
which was under the inspection of an officer of the police;
that in consequence of his erasing what I had written, we might have the police after us,
and if I should be implicated in what he had done, I had no means of making my defence,
independent of our being prevented from pursuing our journey.
All the satisfaction I could have from him was, with an oath, "`No ketche,
no have`'e;`" however we heard no more of it, which I esteemed a favour.
Having a good fire in my room, I dried my wet clothes,
which was the only comfort the house afforded,
everything in it having misery stamped upon it.
I did my best to swallow my supper and breakfast,
assured they must partake of the filth so apparent both
to sight and scent everywhere about the house.

During our journeying today,
I had been frequently thoughtful how I was to dispose of myself tomorrow,
it being first-day.
Feeling pressed in my mind to make my way to Christiana,
as my health was suffering through long fasting and need of rest,
I concluded to start as usual at four o`'clock in the morning,
so as to reach the end of our second stage at nine o`'clock in the morning,
and not proceed again until afternoon,
which would allow my caretaker and the driver an opportunity, if they inclined,
to attend a place of worship: I therefore ordered our furbo to be drawn out accordingly.
The man called me in the morning, and I hastened to get my breakfast,
but the horses were not ready.

When we came to the next station, although so much behind our time,
we had to wait near an hour for the horses.
To question my caretaker about the cause of this delay, was of no use,
as I could not believe him if he spoke the truth,
and I had no means of obtaining information from the keeper of the station.
We did not reach the second station until eleven o`'clock,
and I found I must silently submit to these impositions, fearing,
if I should rouse this man`'s resolute, determined spirit,
as he had in his possession the money that was to carry us to Christiana,
he would leave me on the road,
among persons to whom I should not be able to make
myself understood so as to be helped forward.

When the afternoon came, our horses were not ready by the time appointed,
and thus it continued throughout the day: this threw us in the night,
which being very dark, the roads sometimes deep in snow,
and in other places with mud from the heavy rains,
we were obliged to stop one stage short of what I proposed;
but my disappointment was abundantly compensated by the clean,
comfortable appearance of everything about the station, for which I felt truly thankful.
I gladly arranged for our journey tomorrow,
being informed I was now only twenty-two English miles from Christiana;
the thought of which seemed to give wings to my mind.
Worn down as I was, I should have been willing to rest my weary bones in bed,
but I concluded to start again as usual at four o`'clock next morning,
doing my best to prevent being imposed upon relative to horses; I then retired to rest,
comforted that the time was nearly arrived when I
was likely to become my own master again.

When morning came I very reluctantly left my bed,
dreading another twenty-two miles on these bad roads, and in the uneasy cart; however,
after a clean, comfortable breakfast, I was enabled to take courage, and we proceeded,
and were favoured to reach Christiana about one o`'clock at noon; thankful,
truly thankful did I feel to that Divine Power who had thus, in his adorable mercy,
displayed the all-sufficiency of his subduing, supporting, never-failing arm,
both as it respected my own mind, my poor, almost worn out body, and the dark-spirited,
wicked individual in whose hands I had been for more than ten days.
