== Chapter XIX.

A captain bound for Stavanger, proposed to take me as a passenger in his vessel,
and to put into Christian-sands, and allow me two days there.
It was only a small herringsmack, with very poor accommodation;
yet as my service here appeared near a close, and no other vessel was in the port,
although the company I was to sail with did not understand my native tongue,
nor I theirs, I concluded to engage my passage;
assured that I should be cared for by that Almighty Power who cares for the very sparrows.
Sixth-day, I waited on the Baron Weddel,
and expressed my renewed apprehension of duty to visit the prisoners in the castle;
he told me I was at liberty to choose my own time, and first-day was concluded on:
after presenting him with the Book of Extracts and some tracts, we parted.

First-day morning, attended the usual meeting;
at the close of which the baron accompanied me and my interpreter to the castle,
where the prisoners were collected in one large room: on our entering the room,
my interpreter, on whom I had depended,
informed me he must decline interpreting for me on this occasion.
I felt myself placed in a trying situation; and had just strength enough to say to him,
he must not embarrass me at this critical time, but assist me by doing his best,
which induced him to submit.
We had about one hundred and sixty prisoners, with their keepers, the mayor of the fort,
some military officers, and others, with a large company round the windows,
which were set open.
The baron himself first addressed the prisoners, saying,
a stranger was come to pay them a visit,
and he hoped they would pay particular attention to what he might have to communicate,
he being a man fearing God, and much respected here by the first class of the people,
and that his view in paying them this visit,
was to turn their attention to the necessity of living a godly life.
These remarks produced great quietness; after which solemn silence ensued.
The minds of those present became so impressed with a sense of this solemn covering,
that those who were standing with their hats on their heads, took them off.
I was engaged to impress on the minds of the prisoners,
the absolute necessity for them in good earnest to seek unto God for help,
to witness a truly forgiving disposition of mind wrought in them
towards those who came forward as witnesses against them,
the police that had committed them, and the tribunal that had passed sentence upon them,
before they could expect fully to experience that
godly sorrow brought about in their minds,
which works true repentance,
and is the condition on which only we can witness
forgiveness of our sins from Almighty God:
encouraging them to bear with becoming patience and resignation,
their trying deprivations,
as the only way for them to be profited by the bitter cups they may have to drink,
during the remainder of their confinement.

The opportunity, my companion supposed, lasted about an hour; when it closed,
the mayor of the fort observed,
he never before had witnessed the countenances of the prisoners to be so seriously impressed;
and that he believed the visit would have a good effect on their minds.
The baron then addressed the prisoners again,
exhorting them to attend to what had been delivered, and try to amend their lives,
whereby they would become happy here and hereafter.
He then said, what I had communicated was well understood by the prisoners,
and he believed it would have a good effect,
and that my interpreter had done justice to my communication;
he also expressed the satisfaction the visit had given him.

Second-day morning,
the baron`'s servant came with an invitation for me and
my interpreter to take a family dinner with him,
which we accepted, and passed our time agreeably.

Fourth-day, I attended the usual meeting:
in the afternoon I received an agreeable visit from ,
informing me he had read through the Book of Extracts; he added,
"`I think the members of your Society are highly privileged; for if I happen to do wrong,
I have no one that will come and act the kind part to inform me of it,
and give me suitable advice on the occasion, as is the case with you and your members:
I admire the advantages your members enjoy:
it would be a happy world if all mankind were of your Society; for if I do wrong,
people will laugh at my faults, instead of helping me to amend my ways.

My mind being still exercised on account of the prisoners in the castle,
and believing I should not get clear of Christiana with a peaceful mind,
without being willing to issue a printed address to them,
I accordingly sat down for that purpose: when complete,
I put it into the hands of my friend and interpreter for inspection,
to make the necessary alterations where my mode of expression would make it difficult
for the translator to adopt words suitable to the Danish language,
and to make a fair copy of it.

First-day, attended the usual meetings:
waited on the Baron Weddel with the fair copy of the address to the prisoners;
read it over to him, requesting that, as I went along, if any parts were objectionable,
he would make his remarks on them.
Having read it through, he proposed a slight alteration,
with the addition of a subject which had already come before my mind,
when engaged in committing it to writing, but about which I let in discouragement.
Both of his proposals I could freely unite with:
he then expressed his full approbation of the whole, saying,
as nothing of the kind had ever before appeared among the prisoners,
he believed it would have its use.

Fourth-day, attended the usual meeting:
in the afternoon the address was prepared for the translator,
who engaged to complete it in three days.
Seventh-day, nothing has yet been done towards the translation of the address,
which occasions me much trouble.

First-day, attended the usual meetings under great discouragement,
from the depressed state of my interpreter`'s mind:
passed the evening in a state of mourning, and retired to bed under great distress.
Second-day morning,
not knowing how soon the summons would come for me to go on board the vessel,
and being assured I must not leave Christiana before the
address was ready to put into the hands of the baron,
for distribution among the prisoners, and no translation being yet received,
I urged my interpreter to go to the man who had it in charge; when he returned,
he informed me it was no further forward than when first put into his hands.
At length, after much delay and exercise of patience,
I obtained the translation of the address,
and got it corrected and put into the hands of the printer,
who had orders to print five hundred,
it being the desire of the baron that each prisoner should have one,
and to have some to forward to the prisoners of the
like description in other parts of the state.
A professor in theology came to my apartments on business,
to see my friend Enoch Jacobson;
and I was walking the room under great exercise of mind during his stay.

On his leaving,
he expressed to Enoch Jacobson his surprise at the
comfortable feelings his mind had been under,
during his being in my company, although we had not been able to converse,
and the desire he felt that the blessing of the Almighty might go with me.
On going down into the family, where he met with one of the officers of state,
these feelings remaining with him, it appeared he could not suppress an allusion to them,
and his surprise at the feelings of good his mind was still in the enjoyment of,
which he met with while in my company, without a word passing on either side.
This is not recorded with a view of attaching any good to the creature,
but as a confirmation,
that when there is an endeavour maintained to abide under
the attracting influence of the Spirit and power of Christ,
having our whole soul engaged in seeking his counsel and support,
those precious feelings we are introduced into, circulate as from vessel to vessel,
and leaven the minds of others into the like precious feeling,
so that they are at times benefitted hereby.

Fourth-day, the captain came to inform me he intended to sail the next day.
The prospect of being left behind was very distressing;
but such was now the debilitated state of my health,
from exercise of mind in various ways,
that independent of my not having received the proof-sheet of the address from the printer,
I was ready to conclude I was unequal to encounter the voyage;
but yet it appeared needful for me to be plain with my interpreter, and inform him,
that if I lost my passage,
I must not quit Christiana before the address was printed
and ready to put into the hands of the baron for distribution.
This roused him to procure despatch, and apply to the captain for more time,
who agreed to wait for me until sixth-day; for which indulgence I felt grateful; hoping,
if favoured to accomplish by that time all I have in prospect here,
when my mind was relieved, my strength would improve,
and it would be safe for me to commit my enfeebled
body into the hands of the best of all care-takers.
Experience has abundantly convinced me,
that by endeavouring to keep patient under trials and exercises,
the way is more likely to open for relief,
than by indulging in creaturely contrivance to effect it.

Fifth-day,
I found I should not leave comfortably without urging
the holding of the two months`' meeting,
which had not yet met during my stay, nor for a long time before;
this meeting was accordingly held.
An agreeable account was received and read from the two months`' meeting of Stavanger.

Sixth-day, my difficulties were brought to a close,
by the printer furnishing me with the quantity of addresses ordered.
I waited on the baron with a copy,
informing him my friend would furnish him with them for his distribution,
when he in a handsome manner expressed the satisfaction,
which the concern I had manifested for this class of his countrymen, had afforded him.
I felt it my duty, in reply, to say, there was nothing due to me on this account:
all praise must be given to that Almighty Power, who had influenced my mind,
and fitted me for the work.

Except for murder of parents, those who are convicted of crimes are sentenced to slavery;
some for terms of years, others for life.
They come into the town, and work under a military guard,
armed with cutlass and blunderbuss.
Others are variously employed: some allowed to go about without guard;
but all have the particular badge attached to this mode of punishment,
the body of their coat being a grey mixture, with dark brown sleeves;
one front of their breeches grey, the other dark brown.
Some have heavy fetters on their legs; and such as are refractory,
a heavy iron collar round their necks: others, who conduct themselves properly,
have only an iron ring round one leg.
They all have comfortable, warm clothing,
and look as if they were well supplied with food, and are very clean in their persons:
for these comforts I understand they are much indebted to the baron.
Here follows the address:

To The Convicts in the Castle of Aggerhuus.

Having had a previous opportunity with you, and yet feeling something further on my mind,
I shall in this way cast it before you, for your serious consideration.
In the first place, let me endeavour to persuade you to cherish, as much as in you lies,
a disposition or desire to read the Holy Scriptures,
as frequently as suitable opportunities offer;
beseeching the Almighty that he would mercifully
condescend to enable you to read them to profit;
as they '`are able to make wise unto salvation, through faith which is in Christ Jesus,
and are given by inspiration of God, and are profitable for doctrine, for reproof,
for correction, for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works.`'

May I also entreat you to be careful and avoid the
reading of all publications which may have a tendency,
in any degree whatever,
to counteract the good effects that will be produced from reading the Scriptures.
Remember the advice of the apostle: '`Be not deceived,
evil communications corrupt good manners;`' so, by the same means, the sentiments,
which you are sure, more or less, to imbibe by unsuitable reading,
will have a tendency to corrupt your minds,
and prove like the little foxes that spoil the vines,
destroying those buddings of good desires after the Lord and the knowledge of his ways,
that have been produced there through the instrumentality
of the Scriptures and other such means.
Fail not to cultivate a disposition of thankfulness for the privileges afforded you,
of attending your place of religious worship;
for I conceive it is our indispensable duty so to do,
agreeably to the exhortation of the apostle,
'`not forsaking the assembling of yourselves together, as the manner of some is;
but exhorting one another,
and so much the more as you see the day approaching:`' alluding, no doubt, to that day,
when we shall all appear before God, to give an account how we have passed our time here:
thus you will be holding out encouragement to each other to do the like,
and bearing public testimony to your dependence on and love to
Him who has created you for happiness here and eternally hereafter.
When thus assembled, be earnest in your desires after that great,
all-wise Being whom you are professing to approach;
that he would be pleased to effect in you and for you such a disposition of mind,
as that your coming before him may find acceptance in his sight,
and prove seasons of renewal of that strength so essential to our
coming up in the faithful performance of every good word and work.
I never knew any one who made progress in real, vital religion,
that was careless in these respects.

But let not this duty of worship to Almighty God be merely confined to
those times set apart for your assembling together for this purpose;
because it is a duty we should always be found in
the acceptable performance of in every situation,
even when our hands may be employed about the lawful concerns of this life;
it being an inward and heart-felt work, confined neither to time nor place.
The Almighty being omnipresent,
the sigh or the groan of sincerity never fails to reach the ear of his Divine mercy,
who is all-sufficient for preservation and help.
If we are concerned to be found daily looking to, and depending upon him,
every place will become to us a house of prayer;
and an altar would be continually set up in our souls,
on which offerings will not fail to be made in righteousness unto him who has promised,
'`to this man will I look, even to him that is poor and of a contrite spirit,
and trembles at my word.`' The promises of God are not yes and no,
but yes and amen forever,
confirmed in the daily experience of those who become
subject to the terms on which they are proposed,
being all made conditionally.

These hints being attended to,
I believe will in due time produce that quiet submission
in your minds to your present trying situation,
which you at this moment may not be aware of;
and also prove the means of assisting you to withstand the assaults of Satan,
should he endeavour to make you uneasy under your confinement,
and tempt you to contrive your escape.
But how awful does this subject strike my mind, when I consider if any of you,
in the attempt, should lose your natural lives,
for the great uncertainty of obtaining liberty to the mortal part,
and thereby plunge the soul into a state of eternal torment!
I cannot bring my mind to believe that such conduct can
ever meet with the approbation of the Divine Being,
but must be highly offensive in his sight.

Therefore should any such ideas be produced in your minds,
rest assured they proceed from that evil power,
whose first workings in you have brought you to this
miserable condition in which you now are;
who will continually be trying various ways, if possible,
to keep you in subjection to him, and to his allurements,
until he has effected your total ruin;
for he always has in the end proved himself to be a liar, and the father of lies.
Should it so happen that any of you effect this purpose of escaping,
either by your own contrivance, or through the suggestions of those,
whom that same evil power may make use of as his agents, in order to deceive you;
I believe I am safe in saying, that your minds will become like the troubled sea,
when it cannot rest,
'`whose waters cast up mire and dirt;`' always assailed by fears of being again apprehended,
knowing that, should such be the case,
you will be placed in a worse situation than you were in before you made the escape.
Neither can you look with confidence towards Almighty
God for the continuation of his support,
under your increase of suffering, while you are from time to time thus transgressing;
and instead of that enjoyment of liberty, with which you have flattered yourselves,
you will become a burden to yourselves,
and no doubt at times repent that ever you took such a step.

Consider also, should you make the attempt and be detected,
you must then expect it will occasion you a longer detention in your confinement,
than probably would otherwise be the case; and also deprive you of privileges,
of which those who have manifested submission to their allotment,
may be in the enjoyment.

I can readily believe your situation is a trying one,
and that there are those among you who have many bitter pangs to feel,
many heart-rending seasons to endure, deprived of the enjoyments of social life:
husbands separated from wives, parents from their tender offspring,
and children from their parents;
yet by this quiet submission you will come to see more clearly
whom you are to blame for being in this suffering condition,
than otherwise might be the case, and which is '`so essential to your being profited.
If you will only be honest with yourselves, in putting the query,
did not my conscience at times make known to me what was right and what was wrong,
and have I not been followed by that Divine Monitor in my own heart,
which if I had attended to it would have preserved me from those
evil practices which have brought me into this deplorable situation?
I believe you will then acknowledge that the cause is solely with yourselves.

Be, then, careful how you reflect upon the laws of your country, upon your prosecutors,
and those who were witnesses against you, the police,
or the judgment of that tribunal which felt the necessity
of placing you under proper care;
but keep in view,
the necessity of aiming after a truly forgiving disposition towards all men;
for this I believe must be experienced before that godly sorrow,
which works true repentance, can be fully known;
agreeable to the declaration of the inspired prophet, '`cease to do evil,
then learn to do well;`' and not till then can we approach the Almighty with confidence,
and beseech him that he would condescend in mercy to pass by our multiplied transgressions;
and then these your sufferings may not be in vain.

Let me encourage you to hope, that the design in putting the law in force against you,
on account of your improper conduct,
is not so much with a view to punishment as for your reformation,
that it may prove the means, in the Divine hand,
of restoring you to your near connections,
and becoming useful members in civil and religious society.
It is likely, when you consider your degraded situation,
you maybe discouraged from entertaining a hope that this will ever be your experience;
and no doubt the evil power will at the same time try to persuade you,
that your case is so desperate, your character now so branded with infamy,
that it is quite in vain for you to make any attempt in these respects:
but allow me to say, that if this entire submission to the dispensation,
which unerring Wisdom has permitted to overtake you for your correction,
be but thoroughly experienced, your afflictions will work together for your eternal good,
producing such an uniform line of good conduct,
as will evince that a thorough change of heart has taken place,
which is likely to do more towards your enlargement than any mortal interference.

Therefore let me once more entreat you to be willing to do your
very best towards the accomplishment of this desirable end,
and in your seasons of dismay, guard against being cast down below hope;
but remember the declaration in Sacred Writ,
that all things are possible to them that believe.
Believe then in the mercy and all-sufficiency of that mighty Power,
who has the hearts of all men at his command;
'`as the rivers of water he turns them whithersoever he will;`' and who,
of all the sons of men, is able to hinder or prevent him?
But if you are made witnesses of his merciful interference,
you must cleave unto the Lord with full purpose of heart,
resolving to obey all his Divine requisitions, by choosing the good,
and with holy magnanimity refusing the evil; for he yet remains mighty to save,
and able to deliver to the very uttermost, those who come unto him in faith.
Should you be released from your bondage, either through the mercy of your king,
or by the time expiring for which you were committed,
be watchful over your future conduct, lest you be brought into the same situation again;
for you will find that you still have the same unwearied adversary to contend with;
and should this be your deplorable situation,
imprisonment may then only end with your natural lives.

Endeavour also after a disposition to be kind and affectionate to each other,
for by this means you may become instrumental in doing much
towards the alleviating each other`'s suffering;
but if you pursue a contrary disposition, you will be sure to increase your own.

Before I close this subject, I feel disposed to give you as correct a statement,
as my memory will allow me, respecting Thomas Barrington, a countryman of mine,
of whom it is related, that he was a person of superior natural parts,
and had received a liberal education; but, as he reports of himself,
for lack of attending to that Divine Monitor in his
own mind that would have preserved him,
he got so involved in evil practices, that he became a notorious robber, and was at last,
by the hand of justice, stopped in his career.
Being tried in one of our courts of law,
he was sentenced to transportation to Botany Bay,
a distant station belonging to the English nation, to which their convicts are banished;
but, extraordinary to relate, in the course of time he became such a reformed character,
and was so respected for his general good conduct,
that it is said he filled the office of a magistrate to
the satisfaction of those who had concerns with him,
and that he was remarkable for his strict administration of justice:
this circumstance should therefore animate and encourage you,
to press after the like happy change; and that you may, is my sincere desire.

I remain your well-wishing friend, "`Thomas Shillitoe.

14th of Fifth month, 1822.

Extract from a letter, written by Enoch Jacobson,
giving an account of the delivery of the Address, by the Baron,
to the prisoners at the castle.

Christiana, 17th of Sixth month, 1822.

First-day, after you left me, in company with the baron, the mayor of the fort,
and many others, I attended at the castle;
the prisoners were assembled in the same large room as when you visited them.
The baron had requested me to read the tract, to which I objected,
on which he expressed himself willing to read it to the prisoners himself.
Before he began to read, his mind appeared prepared to say something,
but the band of music at the fort beginning to play,
fearing it should draw the attention of the prisoners and others who were present,
from the subject that was about to be laid before them,
an officer was sent to request they would cease playing,
in the meanwhile all remained quiet.
When the music had ceased playing, the baron,
in a serious manner addressed the prisoners;
reminding them of the time you were with them, telling them who you were,
and what you were, and what you at that time told them; saying,
this very man who had been so well disposed towards them before,
had now left behind him a printed tract, of which they were each to have one;
desiring them to pay close attention to what was there laid down,
as it was written by an individual who wished their eternal happiness,
and that they might become reformed characters,
and useful members of religious and civil society.
He then proceeded to read the tract,
in a way which proved him so fully to enter into the subject which it contained,
that the minds of the prisoners and the company, appeared to be very seriously affected,
the baron labouring with them during the opportunity,
that it might have its intended good effect, I cannot express what I felt at the time,
both on account of the baron, and many others who were present:
it reminded me of our former visit there.
At the close of the reading, the baron addressed the prisoners in an encouraging manner;
and when they left the room,
their countenances evinced that the opportunity had been to them a satisfactory one.

After having, in adorable mercy, for so I humbly hope I may say I esteem it,
been brought through all my difficulties thus far,
and feeling myself discharged from further service in Christiana,
accompanied by my kind landlord, his clerk,
and my dear friend and interpreter Enoch Jacobson, who still felt very near to me,
towards evening I went on board the fishing-smack, Tobias Rasmus owner:
the separation on their part appeared trying, but mine were tears of joy,
that I had been thus favoured to get safe out of Christiana.
There remained an evidence in my mind,
that under all the manifold interruptions which I
had met with in the way of my religious duty,
I had not willfully left anything unattended to,
which had been clearly manifested to be required of me;
this caused my cup so to overflow with feelings of
gratitude to my Almighty Helper and great Care-taker,
that I scarcely regarded myself as again committed
to such an unstable element as the great deep.
I had very unexpectedly the company of Lance Lasson, a Friend of Stavanger,
who spoke English, which added much to my comfort:
the wind continuing fair till seventh-day evening, we reached Moss.

First-day, we held our little meeting.
The wind this afternoon being contrary, we cast anchor,
and went on shore at Thorears Island, about two English miles from Thunsburgh:
setting my feet on shore again was grateful to my mind; my health is improving.

Second-day, the wind was contrary.
Third-day, the wind still ahead; the prospect of detention on this small dreary island,
was trying, only two families residing upon it; I felt desirous to reach Stavanger,
and become settled again for a short time; but the wind turned in our favour,
and we set sail: the vessel being small, occasioned a deal of motion,
pitching from head to stern; my having only a locker to sleep in,
my condition through the night was trying.

Early next morning, to get away from the closeness of the cabin,
and the offensive smell of the bilge-water, I had my mattress brought on deck,
and procured some covering to defend me from the spray of the sea,
which came over the deck.
The prospect of the foaming waves, with the almost continual dipping of head or stern,
and the violent cracking of the vessel as if she was going to pieces,
made our situation appear terrific.
At this time I found the busy enemy beginning his work in my mind,
by endeavouring to sap the foundation of my hold on that
Divine Power who had wrought such wonders for me;
but being favoured still to know Him in whom I had believed,
and earnestly seeking his support and preservation under these painful sensations,
my mind again became tranquil, and I was favoured with the assurance,
that every nail and every plank in the vessel,
was as much under the superintending care and control of the Divine Power,
as the mighty waves that roll over and over, and every wind that blows.
After much tossing and frequent tacking,
we were favoured to arrive safely at Christian-sands on sixth-day morning,
where I found a home at a clean, comfortable hotel.

My next call was upon Ole Moe, a serious man, of the sect called the Saints, in Norway,
of which sect Hans Hough was the founder;
I spent some time agreeably with him and his wife.
He informed me,
a number of serious persons met every first-day evening for religious purposes,
which had some hold on my mind;
but as we had already met with considerable detention on our passage, I felt desirous,
if the wind was at all favourable for getting on our way, to proceed next day.
I was also aware of the difficulty that would be
likely to attend my having a meeting with them,
from my friend, whom I supposed I must look to for my interpreter,
being deficient in the knowledge of the English language.
I was tempted to endeavour to put away from me these feelings,
and was permitted so to do for a time.
When we returned to our hotel,
the captain was there to inform us the wind was getting about in our favour,
and he wished us to hold ourselves in readiness to come on board early next morning.
I had been unmindful that I had a claim to two whole days at Christian-sands,
but as there was then no disposition in me to avail myself of this privilege,
I hastily consented to the captain`'s proposal.

Seventh-day morning early, we left our hotel to go on board the vessel.
Going to our boat, we had to cross a vessel on which a number of persons were collected,
as if for the purpose of seeing us go on board,
among whom a respectable-looking aged man so attracted my attention,
that I was constrained to offer him my hand: he followed us into our boat,
whereby I was led to suppose another passenger was added to our number;
but inquiring through my friend of the captain,
he informed me he was only come on board to have some of my company,
and that the boat along-side of our vessel was to take him ashore again.
Although I felt great nearness to the man, yet,
from the difficulty I was aware we must have to understand each other,
I felt not a little discouraged.
Through the help of my friend, he informed me, that on hearing of my arrival,
such were his feelings of love towards me,
that he could not find words to express them to the full,
lamenting much we were not able to converse freely together without the aid of an interpreter;
then putting his hand to his heart said, "`But I feel we can converse together here,
in a way that is beyond words.`"

When he left the vessel again, the tears gushed from his eyes,
accompanied by expressions of thankfulness we had thus met.
We proceeded on our way,
but not without my mind at times being tried with apprehensions that I
had left Christian-sands before the right time was fully come;
and when crossing the vessel to the boat,
my mind was introduced into exercise on account of the company there,
but I did not pause as I should have done,
in order that I might have more clearly known my Master`'s will respecting them.
I was led to hope these painful feelings would in time subside;
however they were not to be shaken off with all my efforts, and therefore,
there now appeared no way for me but patiently to abide the indignation of the Lord,
until he sees fit to say it is enough.

About four o`'clock in the afternoon, a very heavy fog came on,
the wind blew tempestuously and ahead; our captain manifested alarm,
and concluded to make to the nearest harbour for the night, which was Flekeroa,
a few miles from Christian-sands; but after all his efforts to reach it,
he was obliged to return to Christian-sands, where we landed safe late in the evening;
for which favour, I hope, I felt truly thankful,
as it afforded me an opportunity of manifesting my
entire willingness to be anything or nothing,
just as my Divine Master would have me to be.
I endeavoured after that quiet, resigned state of mind,
in which all fleshly reasoning and consulting is buried out of sight,
in order to come at a clear sense how far my willingness
to sit with the company at Ole Moe`'s,
would be accepted by my Great Master; for I have aforetime found,
from sorrowful experience, that our time is not the Lord`'s time.

Being favoured with an evidence that my willingness would be accepted,
I concluded to do all in my power next day towards
having a meeting with them at their usual time.
There was one difficulty which I knew not how to get over,
and the more I reasoned upon it, the more it increased, namely:
my interpreter being so deficient in the knowledge of the English language;
but as I believed it was a duty required of me to have a meeting with this company,
I was encouraged to believe that my interpreter would
be so helped that the cause would not suffer,
or that one more competent for the work would be provided: after which,
I retired to rest, leaving the things of the morrow to care for themselves.

First-day morning, my interpreter, a young man from New Bedford, in North America,
and myself, held our meeting,
which was mercifully owned by Him who promised to
be with the two or three gathered in his name,
which I was led to hope was in a good degree our case.
At the close of our meeting, the young man, who from his own account,
had a birthright in the Society, in a very tender and affectionate manner,
expressed his thankfulness for such an unexpected opportunity of sitting down with me.
After our meeting closed, we proceeded to Ole Moe`'s; himself, his wife,
and some of his servants gave us their company.

Something being given me for his servants, by being faithful to this trust,
my mind was made strong to express to their master all that came before me,
relative to my having a meeting with them in the evening,
which appeared to be very cheerfully complied with:
and when I stated the difficulty I was under,
on account of my interpreter being deficient in the English language, he replied,
he could make my mind easy in that respect, and sent for a friend of his,
who soon made his appearance, and spoke my native tongue fluently,
offering his services as my interpreter in the evening, which I gladly accepted,
having my friend as a watcher, lest, for lack of a clear view of my sentiments,
any unsound principles should go forth to the people as mine;
for which duty I could not doubt his being competent.

When meeting time came, we proceeded to Ole Moe`'s, who conducted us to a large room,
fitted up for the purpose of holding their meetings,
where we met with nearly one hundred persons.
After we had sat a considerable time in the meeting,
my mind was brought under exercise for service, but my interpreter had not arrived,
and when he did,
the people being unacquainted with the mode of sitting together in silence,
were for a time restless, until I requested they should be informed,
if they would endeavour after stillness in themselves,
I believed my good Master had something to hand to them through me, his poor instrument;
this had a good effect.
Standing on my feet, I reached forward a chair,
requesting my interpreter to take his standing by me.
While in the exercise of my gift,
I was made sensible he was brought under some right feeling
of the responsibility of the engagement he had entered into,
and I was fully satisfied he endeavoured conscientiously to do his best,
in giving a correct translation; which I was informed, after the meeting, was the case:
the people appeared attentive, and kept very quiet to the close of the meeting.

When we were about to quit,
the interpreter was requested by the principal of the congregation to say,
the meeting had been to them a very satisfactory one.
I had left the meeting-room, but was obliged to return,
and press upon the company the great advantages that would result to them individually,
if they were but willing to cultivate more of a disposition after quietness in themselves,
than they at present were acquainted with.
I returned to our hotel in hopes of being permitted to sleep on shore,
the better to prepare me to endure my miserable lodging-place on board the vessel;
but our captain ordered us on board again tonight, the wind having changed in our favour.
We accordingly went on board, and about twelve o`'clock at night took up our anchor,
and were on our way towards Stavanger.

Second-day, we made good sailing.
Third-day, entered the mouth of a river,
and had a fine sail between stupendous rocks about two English miles,
when we cast anchor, and then took to our boat;
after rowing about two English miles more,
we landed on an island where our captain`'s family resided:
here he proposed our spending two days, having a rough,
mountainous road to travel to Devick, his residence.
But I felt myself amply rewarded for my labour;
a more beautiful retreat from the hurries of this world,
I thought I never before had met with;--beautifully wooded and watered,
abounding with birds of various kinds,
whose shrill and melodious voices echoed in the air;
the ground also appeared so fertile as not to require much
labour to produce food for the inhabitants and their cattle.
I do not know that I was ever more disgusted than
with the slothful appearance of the inhabitants,
our captain`'s family excepted, both in their houses and their land, but above all,
their persons.

Devick is about four miles from Lundale Town,
contains about three hundred acres of fine wood, pasture, and corn-land.
I feared I should not be able to leave the island with comfort to myself,
without having them collected in a meeting capacity,
and yet to sit among them felt trying,
as I expected I could not escape without bringing away with
me some of the company which they carried about them.
As I saw no way for peace but to submit,
I had the captain informed of my concern to have the families collected,
for the purpose of having a meeting with them; he replied,
they were not of that description I should feel satisfied to meet with;
"`neither,`" said he, "`do I believe they will meet you.`"
But these replies did not excuse me from the attempt;
I therefore requested him and my friend to make the trial, and give them an invitation;
and I believed they would succeed: they yielded, and returned saying,
the invitation was generally well received.
The room I had slept in was given up for the purpose, which afforded me some comfort,
not having to sit with them in any of their filthy houses, and especially so,
as I should not have to occupy the room again.
They were punctual to the time, and orderly in their behaviour in meeting:
we were obliged to pack very close together, some having large families, mostly grown up;
my next neighbour was so frequently rubbing and scratching herself during the meeting,
that my mind was for a time somewhat disturbed by it,
expecting I should have some of the company that were the cause of her exertions.

When I first stood on my feet,
it appeared right I should lay before them their deplorable situation,
as to outward matters,
and the feelings that had been excited in my mind on their account in this respect,
from a persuasion their situation was capable of great improvement,
not so much by hard labour as by proper management,
and making their children industrious.
I told them, I had walked over much of their land,
and observed fine pasture-ground in some of the bottoms,
and the sides of the hills covered with loose stones,
and other stones which their children were capable of loosening from the soil,
and removing them to spots where there was only rock on the surface.
I reminded them, that while these stones were allowed to remain on the ground,
they were robbing their cattle;
recommending them to portion out to their children spots of ground to clear of stones,
with the promise of being rewarded with money, if any was in circulation among them,
to be appropriated towards purchasing such clothing as they stood in need of,
which would be doing something towards delivering them from
that abject state and misery they were now in.
Inuring their children to early habits of industry and good management,
would be the means of their getting more comfortably through life;
encouraging the children to industry and to assist their parents,
laying before them the advantages that would result to themselves,
and prove one means of drawing down the blessings of heaven upon them.
I told them, as I walked round their dwellings,
I never beheld a place more calculated to influence the
mind in contemplating the wonderful works of creation,
from the varied, beautiful scenery which caught the eye in every direction:
but they should remember that Satan, the common enemy of man`'s happiness,
found out our first parents, who were more secluded from mankind than they were;
for it is said they were alone upon the earth;
therefore they must not consider themselves secure from his temptations,
because their associates were so circumscribed; but by watching unto prayer,
and that continually.
Divine preservation would be experienced from his manifold snares and temptations,
and the Divine blessing secured on their honest endeavours for outward comforts.

Understanding a school-master attended on the children from Lunsdale Town,
I pressed upon them the advantages that might result to parents and children by setting
apart a portion of each day to collect their families and read the Scriptures,
exhorting the parents to set an example of diligence to their children,
when it was safe to cross in their little boat, in attending their place of worship.
They manifested attention to what was offered, and when the meeting closed,
I was informed many of them expressed their thankfulness that they had been thus noticed,
and for what had been said to them; they left us apparently in a serious,
thoughtful frame of mind, and at our departure, took an affectionate leave of us.
We set sail again, and about ten o`'clock at night were abreast of Los harbour, where,
during the last war, a large gun-brig, I was informed, was stationed,
fitted up by several individuals, which captured a great number of vessels,
whereby the owners and managers of her became very rich, purchased land,
and built themselves great houses, and, as Solomon says, had all their heart`'s desire.
But now their outward condition had undergone such a change,
that some were nearly without the necessaries of life,
and the great houses of others were going to decay for lack of means to preserve them;
a striking confirmation "`that wealth, gotten by vanity, shall be diminished.`"
The wind and tide being strong against us about midnight,
and our captain fearing a storm on this rocky coast, he turned the vessel about,
and put into a harbour, about six miles back.
I went on shore to get a little release from my miserable lodging-place:
the wind being in our favour, next morning we set sail again.

About nine o`'clock we were abreast of Los tower: unable to make any way,
we lay beating about the remainder of the day and part of next night.
Next day, we made some way, but night coming on, our captain fearing a storm,
attempted to get into harbour, but the tide ran very strong from the shore,
and no wind to help us: after we had nearly accomplished our purpose,
we were driven out to sea again, where we lay tossing about most of the night.
But my mind was so mercifully preserved in the quiet,
and free from apprehensions of danger,
that I was not permitted to feel a desire to be anywhere than where I then was.
I consoled myself with considering the favour it was,
I had not to contend with this dangerous, rocky coast in the winter;
thus upon every occasion,
as we are brought to a willingness to be entirely resigned to the Divine will,
we shall feel cause, under our greatest trials, to labour after thankfulness to Him,
who is continually watching over us for our good,
in the consideration that these trials are not so great as they might be.

Sixth-day, the wind was for a short time in our favour, after which,
we were obliged to be continually on the tack to make the most of the day,
and the whole of the following night,
which greatly increased my sickness and loss of appetite.

Seventh-day, at noon we were abreast of Seroog Island; the captain by agreement,
if I requested it, was to set me on shore at Egarsund,
about two miles up the river Seroog;
as I apprehended I was at the end of my journey by sea for the present,
I requested we might be landed there with our luggage,
but the tide ran so strong from the shore, and no wind to help us,
we were not able to get nearer the island than about four English miles;
night was coming on, and if we landed, we must be put on shore in the boat,
which was very small, and the sea in great motion, the prospect of which felt trying:
after some conflicts I was enabled cheerfully to submit.
When the boatmen had rowed about two English miles,
I observed they were under some alarm,
which I found was occasioned by their having to return to the vessel;
and fearing a fog was coming on;
but before we reached the island a fishing-boat took us up and our luggage.

Our passage up the river Seroog was awfully grand;
in some places the pass was so strait between the
rocks that we barely made our way along;
in other places,
the huge mass of rock appeared suspended above our heads as if ready to fall,
many pieces of it lying in the river.
We were favoured to reach Egarsund before it was dark, and, after making some efforts,
procured clean private lodgings, which I considered a great favour.

First-day, we held our little meeting in our own apartment,
after which we endeavoured to search out a young man who had drawn me here,
who had once joined the meeting of Friends in Christiana by convincement,
and from the account given of him at that time, he was an ornament to his profession;
but we found he was from home, and was not to return until next morning.
Egarsund is so situated among the rocks,
that there is no road out of it for a carriage;
we were therefore obliged to engage a boat and three men
to take us to the first station round the head-land.

Second-day morning, the young man gave us his company;
his having a knowledge of the English language was an advantage to us both:
we sat down together in silence, which continued a considerable time:
I informed him the resignation of his membership with the Friends
of Christiana was accepted by the two months`' meeting there,
but that I mourned the cause of it; persuaded, from the feelings of my own mind,
independently of the report I had received of his consistent conduct while at Christiana,
that his judgment had not only been convinced of the principles of our religious Society,
but that he had given ample proof thereof,
by a correspondency of conduct with the profession he was making;
and entreated him seriously to consider what had caused him to turn aside from that path,
which he then was favoured to see,
was the path in which he must go to reach heaven and happiness;
also the sorrowful consequences that would be likely
to result to others through his falling away;
the designs of the Almighty in thus visiting his mind being frustrated,
as it respected those to whom he should have become
a way-mark towards the New Jerusalem.

As a day of reckoning would overtake him, I entreated him to be willing to consider,
how he would be able to stand before the Judge of the whole earth,
to account for his time and talents, if he persisted in his disobedience: telling him,
I believed I was divinely commissioned to say,
his day of visitation was not clean passed over, but that,
notwithstanding his sorrowful declension, adorable mercy still waited his acceptance,
if he was but willing to follow the example of the woman in the Gospel,
who having lost her piece of silver, lighted a candle, swept her house,
and sought diligently after it, until she had found it:
earnestly beseeching him to be willing to allow the
candle of the Lord again to be lighted in his soul,
which would give him clearly to see the great loss
which he had sustained through his unwatchfulness,
and to suffer the besom of the Lord`'s judgments again to pass over his rebellious disposition;
whereby he would be restored into favour with Almighty God, which,
through disobedience to his revealed will, he had awfully forfeited.

He appeared to hear with patience what I had to offer,
manifested a pensive disposition of mind, saying,
he was sensible nothing I had offered was done with a view of reflecting upon him,
for having fallen away from that which he had clearly known to be his duty,
but in sincere good-will towards him; we parted affectionately.
His case was much to be deplored, he being a young man of engaging manners,
interesting in his person,
and we understood highly esteemed in the town for his upright conduct and humane disposition;
but the bent of his mind seemed turned to the world again;
when ruminating on his situation, the language of the prophet, I was led to fear,
was too applicable to him, "`There is no hope.`"

Feeling my mind relieved from further service,
we left Egarsund about eleven o`'clock this morning.
Having some arms of the sea to cross in our little boat, after much tossing,
we landed one mile short of Ogne;
our road to the first station lay over rocks and deep sands, which were much drifted.
I felt greatly fatigued; and when we reached the station,
no suitable carriage was to be hired to take us forward;
we then hired two as miserable horses as I think I ever before had to do with;
our luggage we fastened on one, and by myself and my companion`'s riding alternately,
we reached the next station: here we had to hire a carriage, called a cariole,
like our fish-carts.
I had been informed of the difficulty I should have in getting along;
the carts we meet with at the different stations, being so bad;
the wheels are cut out of the solid wood, and having no iron tire,
they were irregularly worn, which, with the badness of the road,
occasioned frequent jolting and sudden jars,
which to a stranger would be almost insupportable.

We however engaged this carriage to Stavanger, which proved a great accommodation,
rough as it was, when compared with what I must have suffered from the common carts.
We reached Soilard by night, and were favoured to procure comfortable lodgings,
for this part of the country.
I had learned quietly to put up with many things
that would be considered hardships in my native land.
We proceeded next morning with a pair of horses that
appeared to be hard worked and not half fed,
which was the case pretty much through this day`'s journey,
and greatly lessened the pleasure it might have afforded,
the weather being serene and fine.

During the last stage, our attendants, who were to take back the horses,
and whose place it is to walk by the side of the carriage, were two females;
we prevailed on them to get into our carriage,
and we took our turns with them in walking;
the inconvenience which we sustained was amply repaid by
the gratitude the poor women manifested for this attention,
and by the peaceful reflection it afforded.
I believe we allow ourselves to be plundered of much of that peace,
which a beneficent Creator designs for us in this life,
through yielding to a selfish disposition,
and an unwillingness to take our share in the difficulties and inconveniences of life.
O,
may I ever remain willing to give up luxuries in order to supply others lack of comforts;
and may my comforts at times be given up to supply others lack of necessaries;
and that even my necessaries at times may be given
up to relieve the extreme distress of others,
is what I crave,
from the assurance that such conduct is consistent with the true Christian character.

This afternoon we were favoured to reach Stavanger, for which I felt truly thankful.
On inquiry, we found the vessel we left at Egarsund had not arrived,
the wind remaining contrary; had we continued with it,
we should have been beating about to this time.
I obtained clean, comfortable lodgings, which was cheering to my mind,
and an earnest desire was awakened in me to be preserved patient
under every trial that may be permitted to fall to my lot.
