== Chapter XXII.

Fourth-day, 6th of eleventh month, 1822.
I left Geneva under exercise of mind, on account of many of its inhabitants;
yet the belief that the time for my tarrying there was fully accomplished,
afforded me a degree of peace.
When we entered the territories of France my luggage was examined:
the searchers behaved with great civility,
and yet had it not been for the help of my old companion who joined me again from Lausanne,
I should have been placed in a trying situation by my passport being detained,
the cause of which I could not have ascertained but through his means,
which was to send it to Paris for examination,
and to be forwarded to me again at Nismes in two weeks,
a paper being given me which was to serve me instead.
My being thus provided for, was fresh cause of awakening in me the language,
What shall I render to the Lord, who is thus caring for me, and watching my needs,
to have them all supplied.

Fifth-day, we reached Lyons: here my companion left me.
Feeling anxious to reach Congenies, to be settled for a short time,
I had nearly brought myself into difficulty,
through hastily making up my mind to proceed by the diligence to Nismes that evening.
Being furnished with a letter at Geneva, to a Protestant preacher here,
I proceeded to his residence to obtain assistance; but to my great disappointment,
I found he could not understand my language.
I had provided myself with a written request, in the French language,
of--"`Please take me to some person who can speak English,`"--which I presented to him:
he appeared at a difficulty to comply with my request.
This detention set my impatient disposition at work,
from a fear it would prove the means of losing my place in the diligence;
but he made signs to me to follow him, took me to an English family,
who had me conducted to the coach-office,
and I took my place to proceed to Nismes in the evening.

When I returned, my room being cold and comfortless,
with the prospect of having to sit long again in a carriage, the day being inviting,
I left my hotel to walk out of the city: observing a fine open road, over a bridge,
I made towards it, but suddenly felt such a stop in my mind that I dared not proceed;
but for what reason I was not able to understand.
I returned into the city, and rambled down as dirty, crooked,
and narrow a lane as any I afterwards met with in Lyons.
My mind was engaged in commemorating the Lord`'s merciful dealings with me thus far,
at the same time I felt almost overwhelmed at the prospect of the journey before me;
when, turning suddenly round the corner of a street, I felt some persons brush by me;
but my eyes were so fixed on the ground,
that I had not the least perception whether they were male or female that had passed,
until a hand was laid upon my arm.
On looking up, to my great surprise, two women Friends stood before me,
which almost overset me.
It appeared that these Friends, Elizabeth Charlton of Bristol,
and Priscilla Scales of Taunton, in Somersetshire,
were at this place waiting the return of Lewis Ma-jolier that evening,
to proceed next day for Nismes and Congenies.
I went to the coach office and procured a transfer
of my place in the diligence for the following evening,
and had my luggage conveyed to the hotel, where my friends were lodging.
For awhile I was scarcely able to realize this unexpected occurrence,
and found it needful to take care I was not over-elated at it.
In the evening Lewis Majolier arrived.

Sixth-day morning, I turned out for a walk,
rejoicing at the prospect of my being likely to be so well cared for to Congenies,
but my joy was of short duration.
Before I left my native land, Lyons was often brought before the view of my mind,
when looking towards the south of France;
and now it appeared to me I must not hastily take my flight from this city,
but be willing to endure the portion of suffering allotted to me here.
Apprehensions of duty being awakened in my mind, to have a meeting with the inhabitants,
bowed me to the very earth; to effect which, I felt there was no time to be lost.
I returned to my friends, and informed them how I was circumstanced,
which tried them as well as myself to proceed in it; but seeing, as I apprehended,
that if way was made for my having a meeting, I must look to the Protestant preacher,
to whom I had a letter of recommendation, to assist me; we accordingly waited on him.
He received us kindly.
On my informing him how it was with me,
and that I was come to throw myself upon him for help,
he manifested a willingness to enter into a view of my situation,
and to accommodate me with a place for the meeting,
and give information "`of it for second-day evening,
which time appeared to him the most likely for the meeting to be held to advantage.
He called upon us in the evening, to see if any further arrangements were necessary.
Lewis Majolier`'s family affairs required his speedy return,
and Elizabeth Charlton`'s husband being indisposed,
rendered her speedy return needful also.
I could not feel easy they should be detained on my account,
thankful to a kind Providence I had already been helped by them,
so I left them at liberty to return;
and the managers of the coach-offices being applied to,
transferred my place to the time best suiting myself.

Seventh-day, my three friends left me, and proceeded to Congenies.

Second-day, at the time appointed for the meeting, accompanied by a young man,
an Englishman, for my interpreter, we proceeded to the Protestant temple,
which was under repair.
Here we found a large upper room, accommodated with seats for the meeting,
and well lighted up: many persons were assembled, but mostly standing in conversation.
I requested my countryman to desire they would take their seats,
and cease their conversation; but from their being persons of the first rank in the city,
I could not prevail on him to make this request, which placed me in a trying situation;
I therefore saw no way but trying after quietness in myself,
and attending to my own proper business.
Feeling myself, as I believed,
called upon to address the assembly in the line of the ministry, at my request,
my interpreter desired such as could find seats to take them,
which request was complied with, and all soon became quiet.
A young woman, while I was speaking, was very light in her behaviour,
trying to effect the like behaviour in a young man,
but in time she became more seriously disposed:
from the unsettled state of the meeting at its commencement, it held long,
but the people remained quiet until it closed.

Third-day, 12th of eleventh month, 1822, accompanied by my countryman,
I made a visit to the Abbe Savage, at the Roman Catholic chapel.
He received me in a free, affable manner.
I represented to him some of the scenes of riot and
excess I had been a witness to in Lyons,
on the preceding first-day; and told him the Catholics as well as the Quakers,
declare their belief in Christ as being the Son of God,
and sent into the world to set mankind an example how they should walk.
Believing my mind had been rightly directed in making him this visit,
I found I must put this question to him,
which I told him I did with a mind open to conviction:
Was there anything in the tenets of the Catholic religion,
or could he point out to me anything in the doctrines, precepts,
or example of our holy Redeemer,
that in any way justified this riot and excess of which I had been a witness?
He replied; not anything, either in their tenets or in the Sacred Writings,
that justified these practices; and that he was one in sentiment with me.
I wished him to consider, as these were his sentiments,
how far he himself had been faithful in exerting his utmost influence, without fear,
favour, or affection, to have these evil practices suppressed; because,
as we were both far advanced in life,
we could expect no other but soon to be called to give an account of our conduct;
and if we have been conniving at evil practices in others,
instead of doing our part towards their being removed,
we shall have a sad account to give.
He acknowledged himself obliged for my observations, and requested my prayers for him.
I returned to my hotel with a heart overflowing with gratitude to my Almighty Helper,
who had given me strength to deliver what was laid upon me;
after which I made visits to some pious individuals.

Feeling my way open to take my departure this evening, I proceeded accordingly;
the son of the coach-master, having been at the meeting,
had secured a comfortable seat for me in the diligence,
and put me under the care of the superintendent,
by which means I was favoured to proceed comfortably,
and we reached Nismes on fifth-day night.
Sixth-day, my kind friend, Lewis Majolier, came in search of me,
with whom I proceeded to Congenies.

First-day, attended meetings there.
My kind friend, James Charlton of Bristol, who was here on account of his health,
became my interpreter;
and as he had obtained a pretty thorough knowledge of the French language,
he was of great use to me.

Believing it would be of advantage, both to my mind and body, I endeavoured,
as far as I was able, to assist in completing the wall of the burial-ground here,
by which means my time passed more comfortably to myself,
than otherwise would have been the case.

First-day, 1st of twelfth month, the meeting was large;
at the close of which was held an adjournment of the two months`' meeting.
Much labour has been bestowed on the Friends here,
to excite to a greater individual concern for the welfare of the cause of Truth;
and although it appears like hoping against hope,
earnest are my desires that Friends may not allow discouragement to prevail,
and hinder their doing what their hands may find to do; leaving the issue to the Lord.
A reading meeting is now established, as at Pyrmont, which was well attended at this time.
Some few strangers gave us their company;
Divine Goodness was pleased to condescend to be near to us;
and such was the precious covering felt over the meeting, that when it closed,
the people were unwilling to separate.
These precious feelings, we afterwards understood, were generally experienced,
so as to become the subject of conversation; some saying,
"`We never felt the like before;`" others, "`The love of God warmed our hearts.`"
A young woman who was at the meeting, but did not profess with Friends, we were informed,
said to another young woman professing with Friends, and who was not at the meeting,
but had been spending her time unprofitably,
"`Your heart must be hard to prefer spending your time as you have done this evening,
and slighting your privilege, by not attending the reading meeting.`"

Fifth-day, the meeting this morning was large, and a favoured time.
O these tokens of adorable love and mercy! how my soul craves
there may be a gathering under its all-preserving influence.

First-day morning, we had a comfortable sitting together; at the close of which,
the two months`' meeting was held;
the reading meeting in the evening was attended by many strangers,
and we had good ground for hoping it would prove a profitable,
instructive season to many.
The disorder occasioned in the two months`' meeting
by a painful case that came before it,
made such impressions on my mind,
that I saw no way for me to get properly from under them,
but by being willing to make a visit to the individuals
most conspicuous in occasioning it.
With the help of one of my countrymen I proceeded,
and endeavoured to do what appeared to be my proper business:
we had reason for believing our visit was kindly received.
Some cases having come under my notice that required the care of the overseers,
I endeavoured to encourage them to a timely faithful discharge of their duty.

Fifth-day, attended the usual meeting;
in which I should have been willing to keep silence,
could I have been satisfied it was my proper allotment;
but I found if I preserved my own peace,
I must proclaim the absolute necessity of being willing
to renounce our own ways and the ways of the world,
before we can experience the ways of the Lord to
be ways of pleasantness and his paths peace.

Sixth-day,
my mind had been at times exercised with apprehensions it
would be required of me to make a visit to the mayor,
which subject has come weightily before me this day,
accompanied by earnest desires that the Almighty will direct my movements,
and grant that they may be rightly timed; from the assurance,
that if we are favoured to obtain relief,
when brought under exercise for religious usefulness,
all our movements must be rightly timed; for except this is the case,
how can we expect to be favoured with the Lord`'s strengthening,
qualifying presence therein:
it being as impossible for us to do the Lord`'s work in our own time,
as it is for us to do it in our own strength.

Seventh-day, the time for making a visit to the mayor being come,
I requested the assistance of my kind friend, James Charlton, as my interpreter:
we proceeded to his residence, he received us in a kind, affectionate manner,
and I laid before him the dangerous consequences resulting
from the dancing-rooms and gaming-houses being opened,
especially on the first-day of the week, and the practice of playing at bowls, ball,
etc. on that day.
He in strong terms condemned these practices,
as having a tendency to bring together numbers of young persons,
and leading to pernicious consequences;
but as the laws of the nation allow these places to be opened
on a first-day after the places of worship are closed,
the mayor has no authority to close them, except any disturbance is occasioned in them:
a case of this sort having occurred, the mayor informed us he had then closed them.
I endeavoured to press upon him the necessity of
being firm in not allowing them again to be opened,
giving it as my belief, that so far as our authority extends,
if we fail to exert it faithfully in preventing practices that are evil,
we become parties in the sight of Almighty God in all the evil consequences.
I laid before him a case that had come under my notice of a lad in Congenies,
who had no visible means of obtaining money to gamble with, attending the gaming-table,
to the grief of his parents, to play on credit; and I stated,
that on further inquiry I found it was a common practice
to admit even children to game on credit.
I endeavoured to press upon him the necessity of his speedy interference,
to put a stop to such practices as would be likely
to be promotive of dishonesty in the youth,
by which they might hope to furnish themselves with the
means for gratifying their inclinations for this evil.
He acknowledged his full conviction of the truth of what I said on the different subjects,
and I could do no other than give him full credit for his willingness
to do his part towards remedying these matters.

We next waited on the Protestant clergyman, who received us kindly,
and manifested a disposition to hear what I offered to him, and to unite his endeavours,
with others, in having the evil practices which abound among them removed.
I had it in charge to remind him,
that the situation we professed to be called upon to fill, was an awfully important one,
requiring our utmost exertions, both by example and precept,
that we may be found faithful in warning the people of their danger,
otherwise we are countenancing them in their evil practices;
and if such should be the case with us,
we shall have a sad account to give of our stewardship in the great day of reckoning.

Before I left him, I proposed for his consideration,
whether an advantage would not be likely to result to the youth among them,
by assembling them on first-day evenings to read the Scriptures and other suitable books.
He allowed he believed such a practice would be beneficial,
and keep the youth out of unsuitable company,
but the Protestants were so numerous they could not assemble them in one house;
but he could recommend their uniting in companies for this purpose,
and would take the subject into consideration, and consult his consistory on it:
we parted in a friendly manner.

We then visited the adjoint mayor, who is a Catholic; he received us respectfully.
I spread before him my view of the necessity of keeping the dancing-rooms closed,
and prohibiting the use of the gaming-tables, especially on first-days:
but this he opposed, saying, the law allowed of their being opened at noon on Sundays:
we parted in a friendly manner.

First-day morning, we had a large meeting,
in which I was engaged to labour with the youth,
not to slight the day of Divine visitation which was mercifully extended,
lest they should draw down upon themselves the displeasure of heaven,
and the declaration pronounced against Jerusalem formerly
should be pronounced against them,--their house left desolate,
and the things belonging to their souls`' peace be forever hid from their eyes.

The afternoon meeting was small, few of the young men giving us their company.
I was constrained to call the attention of parents and heads of families
to this lamentable neglect of duty on the part of the young men,
so conspicuous on first-day afternoons,
and to urge them to consider if something further was not
required at their hands towards endeavouring to remedy it:
giving it as my belief,
their parents might be well assured they were neither in suitable company,
nor was their time properly occupied;
and that I was fearful the cause of Truth suffered through their evil example.
The reading meeting was largely attended by Friends and others;
it proved a season of comfort and encouragement to such
as were desirous to be found in the way of well-doing,
and of the daily-cross.

Second-day, I went to the school-room, and took my seat among the scholars:
during the pause that succeeded the reading,
I had some observations and advice to offer to one of the lads,
who had manifested a refractory disposition;
which produced considerable tenderness in his mind.
My friend, Priscilla Scales, had something to communicate,
which produced tenderness in many of their minds.

Third-day, Priscilla Scales and myself went to Aujargues, about two miles from Congenies.
Our first call was upon a young man who is engaged in business;
having but seldom seen him at meeting, and then unseasonably late,
I found I must be faithful in treating with him on this subject.
His wife not professing with Friends, and they having a family of small children,
I felt that caution was necessary in making my observations,
and I proposed their endeavouring to do their best to set
each other at liberty to observe a timely attendance;
seeing the Lord requires the whole burnt sacrifice,
if we fall short in devoting the whole time which is set apart for these religious duties,
we cannot expect our approaches before the Divine
Being will find full acceptance with him.
What was offered appeared to be well received: the Patois language,
which is a mixture of French, Spanish and Italian, made it trying to me,
because what I offered had to pass through two translations.
Fifth-day, attended the usual meeting.

First-day, our meeting was small; the reading meeting was well attended,
many strangers coming to it: we were favoured with a quiet, instructive opportunity,
for which many of our minds were made thankful.

Second-day,
my friend Priscilla Scales and myself feeling drawings in our minds to sit with such
Friends as were unnecessarily at Somnieres at the day of balloting for the army;
we made them a visit,
endeavouring to impart such counsel and admonition
as came before us in the line of apprehended duty,
which we had reason to believe was well received.

Fifth-day, 23rd of first month, 1823, the meeting this morning gathered well:
the good Shepherd, in mercy, condescended to stretch forth his crook,
for the help of those who were willing to lay hold upon it.
Early in the meeting I felt an engagement to stand up;
but fearing to interrupt the holy quiet that was spread over us, I kept silence,
until the word given me to proclaim became as a fire in my bones,
so that I dared no longer refrain from saying,
that if ever we are favoured to reign with Christ in his kingdom,
we must be willing to suffer with him in this world, by daily dying to self and to sin,
maintaining the daily warfare against the enemies of our own household,
our own heart`'s lusts, continually eyeing our great captain, Christ Jesus,
until the victory becomes complete;
and then the blessing dispensed to Israel formerly will not fail to be our experience,
the cloud by day and the pillar of fire by night will be vouchsafed to us.

First-day morning, our meeting was well attended,
and Divine mercy was again extended to the humbling of many minds.
The reading meeting gathered early, and was crowded by Friends and others.
It settled down in such a quiet as I have not often known exceeded;
affording fresh cause for the acknowledgment of "`good is the Lord,
and worthy to be waited upon, and feared, served, and obeyed!`"
The destitute situation of the young people of Congenies, for lack of employ,
having claimed much of our attention, we have been desirous of pointing out a way,
whereby they might be assisted in this respect;
assured that lack of suitable employ has been one of the causes
of their being so much in league with those of other societies,
and unable at times to earn sufficient to support nature.
A plan for their relief was adjusted,
which appeared likely in time to effect the end designed;
but in consequence of a rumour of war between France and Spain,
it appeared most prudent to take no steps towards its being put in practice.
Yet it is a subject of so much importance to the welfare
of the rising generation who profess our principles,
that a hope is raised in my mind,
at a future day their situation may engage the attention of Friends in England.
There is a considerable number of persons professing with Friends,
and a meeting regularly held at Giles, a part of this two months`' meeting,
situated about twenty English miles from Congenies,
who are generally visited by such Friends as come
on a religious account to the south of France,
and they had frequently been mentioned to me;
but as no way opened in my mind to proceed to make them a visit, I dared not attempt it.

First-day, attended the morning meeting, which was small.
The afternoon meeting was large, but gathered stragglingly:
I hope it was profitable to many.
The reading meeting was crowded and offers of Divine
help were evidently extended to the helpless;
but there was reason to fear the minds of some of the youth suffered loss
through the improper conduct of others in profession with us:
the transgressors were treated with on this account.

Second-day morning, I left my bed in a very tried state of mind,
which continued with me through the whole of the day.
In the evening, going into the school-room hilst the children were reading,
a few remarks sprung up in my mind for communication, which I was enabled to utter:
this little act of faithfulness procured me a morsel of heavenly comfort,
and I retired to bed with thankfulness for this mercy thus vouchsafed.

In the midst of difficulty and danger, oh,
the need there is for me to be careful in all my religious movements,
lest I should plunge myself into those troubled waters I at times so much dread.
Holy Father! keep me, I pray you, in the hollow of your mighty hand,
until that portion of labour you have assigned me
on this side the great deep is fully accomplished,
that when the time for my departure clearly opens to view,
it may be with the peaceful reflection of having done what I could.

Fourth-day morning, fresh trials and temptations open each day to the mind,
as a fresh call to labour for that bread which alone is sufficient to sustain the soul,
and keep it alive unto God.
A letter, received this morning from my native land,
speaks of war between this country and Spain,
and the probability of England being involved in it: on reading this,
Satan entered my mind like lightning,
suggesting to me the danger I should be involved in,
if such a circumstance took place before I was liberated to return home.
This, for the moment, was permitted to overpower me, and produce great depression:
but pausing,
I was favoured to resume my confidence in the never-failing arm of Omnipotence,
to carry me safely through all the trials that awaited me,
and sweetly to call to remembrance the covenants I had made and of late renewed,
under a sense given me that my Divine Master had
a further field of labour for me after my return.
I was enabled to turn my back upon these reports, and the suggestions of Satan,
and my peace was not again disturbed by them.
The meetings of Giles and Cordognan were again mentioned to me;
but however my passing them by may be a solitary instance,
my way in this respect continues quite closed up; and I find it will not do for me,
unbidden, to go in the same track which others have gone,
and I again gave the subject the go-by.

Fifth-day, we had a small meeting,
but in unmerited mercy it was owned by Israel`'s Shepherd.
Earnest have been my supplications for days past,
that the God of my life would be pleased so to direct my course to the end,
that nothing may be taken home with me,
which I should have left on this side of the great deep.

First-day morning, a small meeting:
the afternoon meeting better attended by the young men than is usual;
as was also the reading meeting, which was cause of rejoicing to some of our minds.

Second-day, Priscilla Scales and myself went to Fontanes,
a village about six miles from Congenies.
Sat with an aged Friend and her grandson,
who appear warmly attached to the principles we profess,
and full of love to those whom they believe to be concerned
in advocating the cause of truth and righteousness.
Had an open, satisfactory opportunity with the rest of the family.
From their situation, on account of distance,
and the bad road they would have to travel in winter, we encouraged them,
when they were not able to reach Congenies,
to sit down together in their own house on first and week-days,
fixing upon an hour the most suitable, and to be punctual in keeping to it,
which advice appeared to be well received.

Fourth-day, I received letters from England,
with an account of the prospect of the removal of a near relative,
who was anxious to see me once more.
Agreeable as such an interview would be to us both,
it excited afresh in my mind an earnest seeking to the Lord,
to be preserved watching against any effort or anxiety to be released from further service,
and return home, until the way clearly opened for it.
This evening brought a proof-sheet of the address to Geneva, which being corrected,
a suitable number was ordered to be printed for distribution.

Fifth-day, attended the usual meeting, which was small.
First-day morning, the meeting was well attended,
but greatly disturbed through the disorderly gathering of it,
which was spoken to in a plain and close manner.
The reading meeting was well attended.

Fifth-day, the meeting small, but a quiet, favoured time.

Sixth-day put me in possession of the address to Geneva,
and on seventh-day it was forwarded to two of my friends there,
to whom I had reason to believe my mind had been rightly
directed for taking the charge of the distribution.

3rd of first month, 1823.
First-day morning, the meeting was large: the reading meeting was well attended,
and closed satisfactorily.

Second-day morning, accompanied by my kind friend James Charlton,
we made a visit to the Protestant preacher;
a report being in circulation in the village that he was
in the habit of playing at bowls on the first-day.
I informed him of this report respecting him,
and that I did not dare to leave Congenies without mentioning it to him.
He did not deny the charge, but excused himself by saying, he might sometimes,
on that day, stand and see them play.
I felt I must tell him, if I had been guilty of such conduct,
I should feel myself implicated in those evil practices; adding,
that if the youth followed his example as spectators, there would be a danger, in time,
of their becoming players as well as others;
for Satan would be ready to whisper in their ear,
if they felt anything like reproof on the occasion,
there could be no harm in their playing,
as their minister encouraged them by being a looker-on; that if we profiled the people,
it must be by our good example as well as precept, and I hoped he would avoid, in future,
being present on such occasions.
He replied, young persons frequently diverted themselves in this way,
after their meeting in the morning was over;
they had been advised to abstain from these amusements
during the time appointed for religious worship,
but the custom of playing at bowls, etc. after their worship was over,
had been established perhaps four hundred years;
and he did not consider he was acting improperly, or taking any part in their amusements,
nor did he apprehend he was ministering cause of stumbling to others,
by standing to look on, quoting, by way of justification of his conduct in this respect,
the expressions of the apostle, "`Rejoice with them that rejoice.`"
I told him, that was not the rejoicing the apostle alluded to.
After some further observations on the dangerous tendency of his example in this respect,
we parted in a friendly manner.
Although unwilling to acknowledge the impropriety of his conduct,
he carried conviction in his countenance of its being wrong,
and I left him thankful to my Almighty Helper,
in thus strengthening me to do what to me appeared to be a duty.

Fourth-day, in company with my friend Priscilla Scales,
we made a visit to a young woman not in profession with our religious Society,
who had long been confined to a sick bed,
and appeared fast advancing towards the close of life:
a number of persons were in her room, variously engaged in conversation.
Believing my mind to be charged with something for the sick woman,
I desired they would cease conversation, which took place; my friend, Priscilla Scales,
gave her in French what I communicated.
The sick woman received what had been communicated, as a fresh token of Divine regard;
saying, it had introduced her mind into such comfortable feelings,
that she should be thankful to be permitted to depart under them,
for what had been communicated felt at that time
more to her than bags full of gold and silver.

I afterwards paid a farewell visit to the mayor,
to express the satisfaction which his steady conduct had afforded me,
in refusing to allow of the dancing-rooms being opened,
although great efforts had been made by the young men; they not succeeding,
the young women went in a body, and unable to prevail,
one of the company went on her knees to solicit the mayor to yield to their entreaties.
As ability was afforded, I endeavoured to encourage the mayor,
to remain firm in the determination which he had previously communicated to me;
observing to him how quiet the village had been on first-day evenings,
since they had been closed: to which he replied,
it was his determination to keep them closed during his continuance in office;
and expressing his desire for my safe return, we parted affectionately.

Fifth-day, the meeting was small;
apprehending it would be safest for me to have a religious opportunity with the ministers,
overseers, and their wives, seven o`'clock this evening was proposed for it,
and we met accordingly.
At our first sitting down together, I was closely tried with inward poverty,
accompanied by fears, that my calling Friends together,
was either something I had worked myself up to,
or that I had not observed the right time for moving in it:
but by endeavouring to keep in the patience during this stripping dispensation,
it tended to my centering down to the gift of Divine grace in myself;
and as I became willing to move under the influence
of that grain of faith in mercy dispensed,
matter was given me for communication, which I had reason to believe was well received:
may I be found enrolling this fresh interference of Divine mercy,
among the innumerable blessings he has been pleased to dispense,
since my arrival on this side the waters.

First-day morning, the meeting was well attended;
at the close of which the two months`' meeting was held; the queries were read,
and answers prepared, to go to London Yearly Meeting.
This afforded an opportunity to speak more fully to the state of things here:
the youth were laboured with, relative to their conduct,
both in meetings and out of meetings,
to endeavour to bring them to a proper sense of the loss they sustain,
for lack of greater circumspection of conduct,
as well as the injury their example was likely to be to others.
The afternoon meeting was small; but the reading meeting was well attended,
and from the unwillingness manifested on the part of the people to leave,
hopes were entertained that it was a season of profit to some.

Fourth-day, after an almost sleepless night,
I felt as if under the weight of the mountains, assailed by fears, that,
after all I have passed through,
in endeavouring to fulfill what I believed was the
Divine counsel respecting me in this journey,
the enemy will in some way gain upon me, and that I shall return home in disgrace.
O! for patience in these seasons of buffeting,
and for ability to flee for help to that merciful Redeemer, who told his poor disciple,
"`Satan has desired to have you, that he may sift you as wheat;
but I have prayed for you, that your faith fail not.`"

Fifth-day, although it is not permitted me to say, the winter is over and gone;
yet to have a glimmering prospect of its decline, my soul says, is enough.
First-day, the morning meeting and the reading meeting were well attended,
and more of the youth were at the afternoon meeting.
Friends separated under a favoured sense, that holy help had been extended.

Second-day,
rumours of very warm debates in the Chamber of Deputies
at Paris having alarmed the English residents there,
so many left, that the police was unable to supply passports in due time,
some hundreds having crossed to Dover and other ports in England:
but my place was to remain quiet; and this state of mind being attained,
I considered to be a great mercy dispensed from heaven.

Fifth-day, way opened to begin to make arrangements for leaving Congenies.
First-day morning, the meeting was well attended;
at the close of which the adjournment of the two months`' meeting was held,
and certificates were signed for Priscilla Scales and myself:
the afternoon meeting was well attended, as was also the reading meeting.

Second-day we made arrangements for our departure;
our places being secured to Lyons for sixth-day.
Fourth-day, my friend Priscilla Scales and myself made calls on Friends.

I felt tried, in consequence of not having received an account from Geneva,
of the receipt of the packet of the addresses; and yet,
believing we had done right by engaging our places for Lyons,
I had a hope I should not be disappointed,
but should receive it before we left Congenies.
Fifth-day morning, letters arrived from Geneva,
informing me of the receipt of the addresses; attended the usual meeting,
at the close of which we took a parting farewell of Friends here,
most of whom were waiting about the carriage to see the last of us;
to them it appeared to be a heart tendering season, in which I trust I may say,
we ourselves were sharers.
We left Congenies about noon, and were favoured to reach Nismes safely in the evening.

Sixth-day,
feeling drawings in my mind to visit the Protestant
clergy and the Catholic bishop of Nismes,
accompanied by my kind friend James Charlton, we proceeded,
and were received by the Protestant clergy with marked attention.
I was constrained to lay before them the importance of the station they, with myself,
professed to be called to, among the people;
and the great necessity there was to become preachers
of righteousness in our lives and conversation,
as well as in doctrine, thereby encouraging the people to faithfulness unto God;
and to maintain their protest, by their example,
against the wicked practice in use here on the first-day of the week,
of the people assembling in the Amphitheatre,
to bait a bull by men hired for this wicked purpose.
I was comforted in finding this circumstance had obtained their very serious consideration,
from the dreadful consequences frequently attending it.
When the poor animal received an injury, or the combaters were injured by him,
the acclamations of joy manifested by the spectators, we were informed,
were great beyond conception; so that neither the bloody scenes,
nor the death of a combatant, which at times occurred,
appeared to soften the minds of the spectators;
but rather tended to promote their ferocity;--women
as well as men sharing in these scenes of barbarity.

We were informed more had been done in Nismes than any other place in France,
towards improving the moral character of the Protestant population.
An interesting young man, in much simplicity, informed us,
he had under his care for instruction a number of young persons,
whom he met for that purpose every two weeks;
and he was hoping for their meeting more frequently on this occasion.
Some little fruits of this labour were apparent; schools for mutual instruction,
and also Sunday schools for children and adults were established,
it being on the youth their hopes of succeeding were chiefly placed.
At our parting,
such feelings of gratitude appeared to be excited for this sudden and unexpected visit,
and the counsel that had been imparted, that he said,
he felt unequal to find words to express himself to the full.
In some of our visits we were informed that all the appointments
lately made of bishops and clergy in the Roman Catholic congregations,
were of those who were the most attached to their superstitions,
and opposed to the introduction of education among the people,
which our interview with the bishop confirmed.
I attempted to find a clew to the bishop, by procuring a letter of introduction:
having been informed I should find a difficulty in obtaining admittance to him,
and if I did gain admittance, that I should not be well received by him.
My attempts failing, I found my peace consisted in proceeding to the Episcopal palace,
and requesting an audience with him, which we accordingly did.

On our application to see the bishop,
we were ordered to be there again at three o`'clock in the afternoon.
We called upon one of the Protestant clergy, who behaved in a brotherly manner,
and appeared to receive my observations in a kind disposition: at our parting,
I informed him of our intention of making a visit to the Roman Catholic bishop,
he replied, he was acquainted with him, and spoke of him in handsome terms,
very different from all I had heard before respecting him,
offering to give me an introductory note to him, which I gladly accepted.

At the hour appointed, we proceeded to the palace.
I told my friend, while on our way,
I expected our keeping on our hats would give offence:
although I had viewed the attempt to obtain an interview as a very formidable thing,
yet I was cheered, hoping our note would procure us an admittance;
but I did not look for more satisfaction in the interview
than obtaining relief to my own mind.
On our arrival I sent my note to the bishop,
and we were immediately shown into his apartment,
where we found him and a priest together.
The countenance of the priest on our entering the bishop`'s apartment with our hats on,
bespoke great contempt, and from the manner the bishop received us,
we could not suppose it was otherwise with him also.
I handed the bishop a translation of my certificates, requesting my friend to say,
they would inform him of my motives for leaving my own home; he received them,
but before he could have read one of them half through, in apparent displeasure,
he put them away from him, expressing his dissatisfaction with our visit, saying,
"`I have nothing to do with you; you are not in my jurisdiction,
and I do not want any of your instruction or interference;`"
turning over and over the note we had brought to him,
as if resentment rose in his mind against the writer of it,
and he wished to get quit of us again.
But such were the impressions on my mind,
that it appeared to me the way had been made thus far for us,
and that even should I be given in charge to his military guards,
which were placed at the entrance of his palace, I must not allow myself to be put by,
from leaving with him what appeared to be required of me,
except he and his priest turned me out of the room by force.
I therefore kept my standing, saying to my friend,
for whom I hope I was not deficient in feeling and sympathy, "`James,
you must give him what I have for him; tell him,
I am shocked at the practice at Nismes of baiting the bull;
and as it is in the power of the clergy to prevent this wicked practice,
and more especially so in the power of the Catholic clergy,
whose influence over the people is unbounded, it is my firm belief,
so far as they refuse to exert their utmost influence
and authority to do away these evil practices,
they become parties with the actors of them in the sight of Almighty-God,
and are implicated in all the guilt which is incurred by their continuance.`"

While I was thus expressing myself,
the bishop continued to turn over the note we brought him,
with a countenance big with displeasure; saying,
these matters were no business for either him or me to meddle with,
nor did he require my interference, or wish to hear anything I had to say.
Feeling myself clear of the bishop, I put out my hand, saying,
I could give him the hand of love, accompanied with a desire to meet him in heaven,
continuing my hand stretched towards him; he fixed his elbow against his side,
and put forth two of his fingers, which I took hold of:
I then offered my hand to the priest--he fixed his hands close down to his sides,
and would not condescend to go as far as the bishop had done, crying out, "`Aliens,
aliens!`" in a disposition of mind, evincing that had it been in his power,
and had the Inquisition been near, it should have been our lot.
I left them with a heart filled with gratitude to my adorable Almighty Helper,
for the support he was pleased to bestow on my companion as well as upon myself,
and thankful I had been enabled to yield to this duty.

We left Nismes this evening for Lyons, where we were favoured to arrive safely.

A letter having been given me to a family in Paris, on seventh-day I called with it,
and spent a short time agreeably with them in conversation on interesting subjects:
meeting with here one and there another, who, we have good ground for believing,
have the cause of Truth at heart, is as a cordial to the mind.

While on my way here, my fears were awakened,
that I should not be able to clear out of Paris,
without endeavouring to obtain an interview with the Catholic archbishop.
This subject coming weightily before me,
and believing I should not leave with peace without attempting to obtain it,
I procured a guide to a Friend who resided near the city,
for his advice how to proceed to effect an interview,
as it appeared that that day and first-day were the
two last days of what is called Lent and Paque,
great festivals.
This placed me in a trying situation, our places being engaged for second-day for Calais,
and our passports ordered by the messenger before we were aware of it;
the coach for third-day being full,
we could not have procured a transfer of our places to that day.
These considerations led me to try the subject again,
if I might not be excused from attempting an interview with him on second-day;
but as there appeared no way but to do my part towards it,
I wrote a note to the archbishop,
requesting he would allow me as early an audience as was admissible,
and received for answer, I should be admitted on second-day morning.
My difficulty now was to procure an interpreter in whom I could place confidence;
aware of the care that is necessary in selecting
the person to whom we commit ourselves and our sentiments:
two persons were proposed to me, and feeling more easy to accept one than the other,
the matter rested for the present.

First-day, attended meeting with a family of Friends and two young men.

Second-day, with my interpreter, I proceeded to the palace of the archbishop.
We were introduced to his chaplain, who appeared with several letters in his hand;
he inquired my business--I told him I attended agreeably to appointment,
in reply to a letter I sent to the archbishop; he turned over the letters,
and mine appeared among them: he then queried what was the nature of my business,
eyeing me very sternly, I suppose on account of my hat being kept on.
I told him I did not feel at liberty to mention the subject;
he then left me again for awhile, and returned,
still urging to know the nature of my communication.
I told him I had a subject to lay before the bishop,
in which I hoped he would feel an interest: he again left me, and returned, saying,
the bishop was at breakfast,
and after break fast he had business of great consequence to attend to.
I proposed waiting, or coming again at such a time as the bishop should appoint;
to which he then replied, the bishop will not see you at all.
Believing I had now done all in my power towards obtaining an interview,
I returned to my hotel, and sat down in the quiet;
and feeling as if I was not clear of the archbishop,
it was laid upon me to take up my pen and address him.

After procuring a translation of it,
and putting it in such a train for delivery as could
not admit of a doubt but that it reached his hand,
I felt like a man who, having finished his week`'s labour,
was looking forward with a degree of satisfaction at the approaching day of rest;
accompanied with this caution,
although my services on this side the water were now brought to a close,
care would be necessary when I was favoured to reach my native shore,
not to hasten over the ground, but again mind my stops.
Priscilla Scales and myself left Paris in the evening,
and were favoured to reach Calais safely.
The weather becoming boisterous, we were detained there until sixth-day morning,
when we left Calais by the steam-packet,
and were favoured to land safely at Dover about noon.

First-day attended meetings there,
and had a religious opportunity at a Friend`'s house in the evening,
with several young Friends.
Second-day morning, I left Dover for Rochester,
and attended a meeting in the evening appointed at my request,
in which I was favoured to obtain relief to my own mind,
for which favour I hope I felt truly thankful.
Everything appeared to wear a fresh face again,
being able to speak in meetings without an interpreter, and understand conversation,
occasioned new feelings not easy to describe.
Third-day, reached London.

Here I was informed that Henry Otiley and his wife,
respecting whom I interested myself at Bergen, in Norway,
and who went out from that port in a vessel bound for Baltimore, in North America,
had come under the care of Friends in England; the vessel run aground on the Essex coast,
the captain put them on shore, and when the vessel was in train for sailing,
left them behind.
Henry Otiley and his wife, not being able to make their case known,
were reduced to great distress; meeting with a Friend,
they presented the note I had given them at Bergen, addressed to Elizabeth Coggeshall,
at Baltimore.
The Friend having knowledge of my hand-writing, took them under his charge;
and they were ordered up to London, cared for by Friends there,
until a passage was provided for them in a vessel bound for Philadelphia,
and every necessary care taken for them on their passage.
This account produced thankfulness in my mind,
that I had attended to my impression of duty, by returning to give them this note,
which had brought them under the care of Friends here.

Fifth-day, attended Tottenham meeting.
Seventh-day, reached Hitchin, where after an absence of a year and ten months,
I was favoured to find my dear wife well; for which I hope I may say,
all that was within me blessed His holy name, who had so many ways cared for me,
and brought me safely through so many dangers and difficulties.
