== Chapter XXVI.

Fourth-day morning, accompanied by some of our newly-formed acquaintance,
I took the diligence for Hamburgh, which I was favoured to reach on fifth-day,
with songs of praise in my heart to that Almighty Power,
who had so mercifully cared for me every way.
On my arrival at Hamburgh, I felt disposed to spend some time among my friends there,
expecting it would be the last time we should be likely to meet on this side of eternity;
but I found Hamburgh was not to be a resting-place for me, and that my halting there,
longer than was necessary for me to recruit my strength and to prepare for my journey,
would subject me to danger.
My friends in England had proposed my making an overland journey to Petersburgh,
and forwarded me letters to Dantzic, Memel and Riga.

On my reaching Hamburgh, some captains at my hotel advised my going by sea, to Cronstadt,
in Russia, to escape the difficulties of an overland journey,
in consequence of my not being acquainted with any language but my native tongue;
and to sail from Lubeck, in preference to Elsineur,
the Lubeck vessels to Cronstadt being well fitted up for the accommodation of passengers.
But if I sailed from Elsineur,
I must take such accommodation as the merchant-vessels afforded;
and my sailing from Lubeck would occasion me much less travelling by land; Lubeck,
therefore, had the preference in my mind,
independent of that reluctance which I felt to set my feet again in Copenhagen,
which I should do if I sailed from Elsineur.
But the more I inclined to go by Lubeck,
the clearer I thought I saw my taking shipping there would endanger my being in some way,
I knew not how, involved in difficulty.
I therefore endeavoured after a willingness to take shipping at Elsineur;
but fresh difficulties presented: a diligence left Hamburgh daily for Lubeck,
and arrived the same day; and when my fare by it was paid,
I should have no further difficulty.
I had already experienced the inconveniences attending
a journey by a conveyance from Hamburgh to Kiel,
and feared to attempt to encounter this mode of getting forward again;
but after weighing all these considerations,
they were not sufficient to warrant my proceeding to Lubeck.
There appeared, therefore, no other way for me but travelling by extra post,
and advertising for a companion to share in the expense; which I accordingly did.
No reply being made to the advertisement,
I applied to an English coach-master to send me forward the first stage,
trusting to a kind Providence to care for me the remainder of my journey.

On second-day, I left Hamburgh,
in hopes my driver would be one who understood my native tongue;
but in this I found myself disappointed.
We had a considerable extent of water to pass through, where,
from the careless manner of the driver, I was in great fear that an accident would occur.
A short distance before our arrival at our first station,
a respectable-looking man came out of a house, asking me questions;
but we could not understand each other, neither could the driver help us out,
upon which he drove on: this person, however, followed us to the post-house,
for what I was unable to make out.
I found, also, none of the family could help me.
Observing a person standing at the door of one of the rooms of the hotel,
waiting to have his horses put to his carriage,
although not of a very prepossessing countenance to apply to for help,
yet I ventured to step up to him, and put the question to him, could he speak English.
He replied, by pointing his finger for me to go into the room,
where I found an agreeable looking female sitting, to whom I addressed myself;
on which she made me understand the person who had
thus followed me was the inspector of the customs,
to whom I must open my luggage: she also cared for my being sent forward the next stage.
I presented her, the inspector and the post-master, with some books,
which appeared to be well received, and went on my way again,
rejoicing in being thus far cared for; and yet, at times,
I was made thoughtful how I should be able to manage when night came on;
but a kind Providence so ordered for me at every station I came to,
that I met with all the help I stood in need of,
until I came to my lodging-place for the night,
agreeably to the route made out for me by the coach master at Hamburgh,
whose kindness had sent me to a clean, comfortable hotel.
Two females in the family spoke English fluently, which was consoling.

After passing a comfortable night, next morning I proceeded on my way,
and reached Kiel that evening, under feelings of gratitude to that Almighty Power,
whose mercies are over all his works.
I drove to the Packet-hotel; my kind friend.
Christian Bauer, would not allow me to remain there,
but had my luggage taken to his own house, who,
with his very kind wife showed me every attention in their power.
Our thus unexpectedly meeting again, afforded mutual gratification;
which appeared to be the case with the Professor Teonsen and his wife,
and others I had made an acquaintance with.
The Countess Bernstorff having heard of my being at Hamburgh on my way to Kiel,
wrote to request I would inform her of my arrival,
and she would come to her town-residence;
whereby I had much of the interesting company of this pious, aged woman; who,
I was led to believe,
felt it a great privilege to retreat from the bustle and pageantry of the court,
to which she was exposed in her husband`'s time,
from the high station which he filled in the Danish government.

Fifth-day, 26th of eighth month, I took leave of my friends at Kiel,
and went on board the steam-packet for Copenhagen.
After being some time on board, a young man,
who I supposed was of some account in the world, having his servant attending on him,
showed a disposition to be familiar with me.
As he spoke my language, I was cheered at the prospect of making his acquaintance.
We had also on board a person advanced in life, who, from the star he wore on his coat,
and the great attention paid to him by the captain and crew,
I concluded was a person who stood high in the government,
with whom my newly-formed acquaintance appeared to be in company.
The young man manifested so much interest in my comfort,
as to show me every attention in his power:
the elderly man also carried himself as handsomely
towards me as circumstances would allow of,
from our not being able to understand each other,
having me to sit down with them at their dinner table,
and partake of their provision--a separate table being provided for them,
from the rest of the cabin-passengers.
The secretary of the English ambassador at Berlin,
entrusted me with a packet to the English ambassador at Copenhagen,
which I engaged to deliver myself, provided I went that way;
otherwise I was to put it in a channel for delivery.
As I was directed, I informed my new acquaintance of the charge I had in my possession,
and the desire I felt to get quit of it before I slept that night,
requesting him to put me in the way so to do.
The young man informed his elder friend of this,
and they kindly offered to take charge of its delivery;
but I informed them that I had engaged, if I reached Copenhagen, to deliver it myself,
gratefully acknowledging their kindness.

When we came within a short distance of Copenhagen, a boat came alongside of us,
which I soon perceived was for my friends, who had shown me so much attention,
to whose company I had looked forward with pleasure on my landing,
and to their assistance at the police-office and customhouse: but now my hopes,
it appeared, would be disappointed in this respect,
as no boat came out that I could hire to land me with them; but,
to my agreeable surprise,
they informed me of their wish I should take a seat with my luggage in their boat,
and they would take care to clear my luggage and passport for me;
which offer I gratefully accepted.

On our landing,
I observed great attention was manifested by those
who had assembled to see the packet arrive,
to the company I was in.
My elderly friend, on our reaching the shore, kindly gave me his hand, and we parted:
the young man cleared my luggage and passport, then put me into a carriage,
with directions to take me to my hotel, and we parted.
On reaching my hotel,
I procured a messenger to accompany me to the English ambassador`'s,
and delivered my charge into his hands.
The longer I am spared in mutability,
the more clearly I am convinced of the necessity there is for us to attend to such intimations,
while thus moving about in religious service,
as we may be favoured with from place to place, and to abide quiet and in patience,
where our lots are cast, until the time for our departure is fully come:
had I yielded to the kind importunities of my friends at Kiel,
to pass another week with them, and go by the next packet-boat,
I should have deprived myself of the help I have received, and afterwards received,
from the young man, and his uncle, as he proved to be, Count Shoolburgh,
the commandant of the city of Copenhagen.

Seventh-day, on my way to my kind friend Dr. Brand`'s,
I observed a person before me in the uniform of those who attend on the king;
on coming up to him, he addressed me familiarly in English, which a little surprised me,
until I found it was the Baron Pichlien,
my kind young friend when on board the steam-packet;
who very kindly invited me to dine with him.
I made a very interesting visit to the doctor and his wife,
who were under great affliction in consequence of
the death of the attendant on the queen,
with whom I had made an acquaintance when here before; they informed me,
her bodily sufferings had been very great, which she bore with exemplary patience;
that her sick-bed and closing moments had had an
awakening effect on many about the court.
I presented the doctor with some books:
some I had which I wished to put into the hands of the princess,
I mentioned this to the doctor; he gave me a note to one of the attendants on the queen,
of whom I had some knowledge, and ordering his carriage out,
he gave his coachman instructions to drive me to the palace of Fredericksburgh.
When we arrived, the coachman left me in the carriage, while he went with the note;
when he returned, I found myself placed in difficulty,
not being able to understand a word he said, but Copenhagen;
by which I supposed my friend to whom the note was directed was at Copenhagen.

While I was musing in my mind to know how I was to proceed,
not feeling easy to give it up as a matter not to be accomplished,
although I could not see how it was to be brought about,
two handsomely-dressed young women came out of a door of the palace,
and crossed a grass-plat: the coachman called out to me,
"`Crown-princess,`" on my repeating, "`Crown-princess,`" he replied,
"`Ya.`" I sprang out of the carriage with my books, and hastened towards them:
on my advancing, the princess halted, looking pleasantly at me, and gave me her hand;
but not being able to understand each other,
the attendant on the princess not speaking English, as I hoped would be the case,
we all appeared disappointed.

The way not opening in my mind to leave the books with the princess, I again withdrew,
and was driven back to the doctor`'s residence.
It appeared the princess was going to take breakfast with a family,
whose gardens abutted against the doctor`'s gardens,
and where my friend would be in attendance;
this induced me to inquire as to the propriety of my going there with the books;
on which a servant was sent with me, and instructions given how to proceed.
At first I doubted whether any advantage would result from the step I had thus taken,
until a person, like an upper-servant in the family, came and took my note, manifesting,
after he had read it, some interest on my behalf: he informed me I must wait;
he then returned, and conducted me into the garden,
where my friend expressed much satisfaction that we were permitted to meet again.
The princess and the female head of the family soon made their appearance;
each in a kind manner gave me her hand, as also did the rest of the company;
a livery-servant soon entered the garden with chocolate
and cake for the princess and the rest of the company;
on which I drew back; being solicited to partake with them, I hesitated,
but on again being entreated, I accepted their kind ofter.
Breakfast being over, I presented the princess with the books:
she requested her attendant to inform me,
she regretted she could not converse with me in my own language,
also the pleasure it afforded her that they were still remembered by me.
Apologizing for having thus intruded myself,
I was requested not to consider it an intrusion: then feeling it best for me to withdraw,
they each gave me their hand.

On my return to Copenhagen, I overtook my kind friend the Baron Pichlien,
one of the attendants on the king,
who kindly offered to take me to the great royal library, which I accepted.
It is a handsome and very commodious building, well adapted for the purpose,
and furnished with a great store of books:
I found a shelf set apart for books printed by our religious Society,
and regretted to see it so barely supplied, not more than four books,
which when all were put together, would not make a volume larger than the Apology.
The librarian regretted they had not a better supply of Friends`' books,
which he thought would be read:
I therefore furnished him with such books as my means afforded.
This evening I waited on my kind friend the Count Schimmilman, with some books;
he received me with his usual affability: on giving me his hand,
he expressed in warm terms the pleasure our once
more being permitted to meet afforded him,
adding, with apparent feelings of sorrow,
"`We have had a great loss in one of your old friends;
one of the ladies of the court is deceased, since you were last here;
her experience in religious matters was great:
her bodily sufferings during her indisposition were beyond description,
but these she bore without ever uttering a complaint: she often spoke of you,
and her mind appeared much occupied about you:
she became more and more one in sentiment with you in matters of religion,
and made a very peaceful close; her loss is greatly felt by all about the court.`"
This was the individual who was in waiting to receive me in the grand saloon,
when I made a visit to the queen on my last journey.
After spending some time agreeably with the count, we parted affectionately.

Having a prospect when I left England of proceeding to Russia by way of Dantzic,
I had requested my friend at Petersburgh to address my letters to the former place,
for instruction how I was to proceed when I reached the Russian territories;
but now having changed my route to go by sea,
I feared that the letter to my friend at Petersburgh would not
reach him in time for me to get his reply before I left Elsineur;
and doubts were also in my mind whether the address of the letter was correct;--these
considerations came over me like a flood as if they would overpower every good desire;
but from this perplexity of mind I was in a very unexpected manner released,
by a person at the hotel, to whom I was an entire stranger,
coming into my room who spoke English well; he proved to be a merchant from Petersburgh,
travelling on account of his health.
On his understanding which way I was bound from Copenhagen, unsought for,
he kindly offered his services, and gave me a letter to his brother at Cronstadt,
the port in Russia at which I was to land;
requesting that every attention should be shown me, as if it was done to himself.
This I received as a further token of the watchful care of my Divine Master,
afresh exciting in my mind earnest desires to be found faithfully serving him,
whatever might be the dangers that might threaten
me in the prosecution of clear prospects of duty.
I still pleased myself with the hopes of being able to proceed on the morrow for Elsineur;
and having some books yet to dispose of,
I concluded the early part of the morning would be sufficient for that purpose.
Apprehensions of danger were awakened in my mind,
if I took any of my books with me to Petersburgh,
although I had not heard of any prohibition in this respect.

My friends considered it necessary that my passport
should be signed by the English ambassador;
but it being first-day I hesitated going to him for his signature;
but considering that my friends deemed it to be so very necessary,
and the uncertainly of what tomorrow might produce, by his being from home,
and as it did not appear to me like going to him in the regular course of his business,
but among the things that might be termed an act of necessity,
I proceeded to his residence.

On my way there I passed the royal theatre; the doors being open,
my attention was arrested by observing carpenters, brick-layers,
and others publicly at work,
preparing for the diversions that were to take place in the evening of the day:
this sight struck as at my very life,
and great fear came over me that my liberation from
Copenhagen was not so near as I expected:
sighing was my lot,
and crying for help to be found faithful to whatever
should be the result of this morning`'s walk.
The ambassador signed my passport, in addition to the signature of the police-master,
and sent it for me to the Russian ambassador for his signature,
which he considered most advisable.

I returned to my hotel,
and found after all I had not obtained my great Master`'s passport to leave on the morrow,
as I had been expecting; the gates of Copenhagen appeared closed against me,
and this warning voice arose, "`Go not out by haste or by flight,
but fulfill the whole of the appointed time;`" this I found must be attended to,
if I secured a safe guidance back again to my native land.

I saw no way for me, but to endeavour to labour after entire resignation,
to be willing to do all that appeared to be the Divine requiring respecting me:
after sitting down in quiet,
with my mind turned inward to the Lord for his counsel and help,
a visit to the crown-prince and his princess came again before me,
and I found that I must be willing to do my part towards its being accomplished,
if I left with a peaceful mind.
By waiting to be directed herein by Him, who remains to be the Wonderful Counsellor,
my attention was turned to my kind friend the Baron Pichlien,
as a person who might help me through this difficulty.
I therefore waited upon him, and informed him how I was circumstanced,
and that I was come to throw myself upon him for help: he informed me,
he was under engagement to dine with the prince that day,
and he would take care to make my request known to them.
My room being very close, and the weather extremely hot,
I turned out of the town for fresh air: the day was beautiful,
scarcely a cloud to be seen,--all nature appeared alive to that
enjoyment which the great Creator of the universe designed;
but such were the feelings afresh excited in my mind from
the remembrance of my morning`'s walk to the ambassador`'s,
and what arose with me on the occasion,
that I felt unequal to participate in these things as I gladly would have done.
I also felt my situation here,
being without any friend qualified to sympathize and counsel me in my movements.

I apprehended it to be required of me in some way to lay before the king,
my views on what I had observed at the theatre on first-day,
also other matters which I had noticed:
after turning the subject of an interview over again and again, I felt fully satisfied,
that if a suitable channel could be found,
whereby I could be assured that what was offered
to my mind to commit to writing for the king,
would be put into his own hands, this would be the best way for me to proceed:
but how it was to be effected with certainty, I at present was not able to see.

In the evening I waited on an individual,
whom I was satisfied I could make a confidential friend;
to him I made known my situation, and the mode I proposed to adopt;
with which my friend fully united.
It was his opinion, that the parliament being now sitting,
there would be some difficulty in obtaining such a quiet,
suitable opportunity with the king, as was desirable.
On my inquiring of my friend how I should be able to procure a
translation of what I might have to commit to writing for the king,
he was fully of the judgment,
that it would be better for it to be conveyed to him in my own language,
whereby no one would be implicated in it.
He also gave it as his opinion, when the king observed my signature,
he would put it into the hands of a suitable person to be translated:
I returned home to my hotel, and after again being favoured with a time of quiet,
with my mind turned inward to the Lord for his counsel,
I took up my pen and wrote an address to the king.

Second-day morning.
Having thus far been enabled to obtain relief to my mind,
the prospect of putting into the hands of an absolute monarch what I had penned,
appeared fearful, as I was a stranger to the language of the country,
and thereby unequal, except through an interpreter,
to plead my own cause should offence be taken against me;
but Divine mercy graciously condescended to compassionate
my frailty and momentary lack of confidence in Him;
and again enabled me to hold up my head in hope,
that He who had required this offering at my hands,
if I was but willing to move in it in faith,
would not permit any harm to come upon me in consequence.

Third-day, I received information from my kind friend the baron,
that the crown-prince would receive me at his palace in town that morning,
and that his servant should conduct me there;
and that the Princess Caroline would afterwards receive me at the palace at Sorgenfrey.
At the time appointed we proceeded to the palace of the crown-prince,
who received me in an affable manner: the books which I presented him with,
he pleasantly accepted.
I informed the prince I had prepared something to lay before the king,
requesting his advice as to delivering it,
that I might be fully satisfied it would come into the king`'s own hands:
he advised my sending it under cover to the king`'s daughter, the crown-princess,
whom the prince called my friend.
The prince appearing to have much business to attend to,
a care was necessary on my part not to overstay the right time;
I therefore took my leave of him,
and at our parting he expressed his satisfaction with the visit,
inviting me to make him a second call.
I then proceeded to Sorgenfrey: on my way there,
the subject of my sending the address to the king, under cover to the crown-princess,
closely occupied my mind; after mature deliberation,
I could see no way for my full acquittal,
but putting the address myself into the hands of the princess for the king;
then it appeared I should have done all that my great Master required of me;
but short of this I saw clearly I must not satisfy myself.

On my arrival at the palace, a person was in readiness to receive me, who spoke English,
and introduced me to the Princess Caroline: the princess speaking my native tongue,
made the visit more interesting; for speaking through another,
I have found to be a great take-off from the enjoyment of an interview of this sort,
especially with pious characters, whose sentiments it is so desirable to have genuine.
The princess received me in an affable manner.
Having paid a visit to England,
she became acquainted with some members of our religious Society:
it appeared to afford her pleasure in having this
opportunity of inquiring after their welfare.
On the princess taking her seat, she requested I would do the like, which I complied with.
After taking chocolate with her,
we entered into serious conversation on various subjects,
and I informed her of the necessity I had been brought under of addressing the king,
which address I saw no way for me to forward to the king,
but by putting it in the hands of the crown-princess for that purpose:
to which the princess replied, the crown-princess was coming to her in the afternoon,
on which I requested the princess would inform her,
that it would be the means of affording great relief to my mind,
if she would allow me to put the address into her own hands,
to deliver it herself to her father, the king;
and I would wait on her at the palace of Fredericksburgh at nine o`'clock the next morning:
this the princess appeared gladly to undertake for me.
After a religious communication, which obtained her solid attention,
and presenting her with Hugh Turford`'s [.underline]#Grounds of a Holy Life#,
it being the only remaining book in my possession, we parted; the princess saying,
that the conversation and visit altogether had been to her an interesting one;
with which I could freely unite on my part.
I returned to my hotel, and on reading over the address to the king,
I found I must copy it over afresh;
for such was the state of my nerves at the time I wrote it,
that in some places it was hardly legible;
and yet my nerves were at this time in such a state that I doubted
my mending the matter by attempting to recopy it;
but by being willing to do my best,
I was helped beyond my expectation at this time to accomplish my task.
I retired to bed weary both in body and mind;
yet I humbly hope not forgetful of the help that
Divine mercy had condescended to favour me with,
in the course of this day.

Fourth-day,
rose early and put myself in trim to proceed in time to Fredericksburgh my bodily
strength had become much enfeebled through exercise of mind and lack of sleep;
the weather was also very sultry, so that my walk looked discouraging.
On my way there, I clearly saw I had nothing but Divine interference to lean upon,
to make the way easy to me; earnest were my secret petitions to Him,
who I believed had called to the work,
that he would be pleased to continue near to me in the needful time.
The adversary, however, did not fail to endeavour in various ways to divert my mind,
from being centered where only help was to be found;
for he would be setting me at work in contriving
to sail from Elsineur as speedily as possible,
to reach Russia before the equinox;
but I was mercifully enabled to withstand his assaults,
having the assurance afresh sealed on my mind,
that if I simply attended to what appeared to be my proper business,
he who calls to the work, and can command the equinoxial gales at his pleasure,
will waft me safely over to the Russian shore;
and when my appointed time there is fulfilled,
give me a safe passage back again to my native land;
which assurance brought tears of joy from my eyes.

Having time to spare, on reaching the palace I walked into the gardens,
which are open to the public,
hoping to meet some persons there of whom I could
inquire the way to the apartments of the crown-princess;
but in this I was disappointed.
The time drawing near at which I had proposed to wait upon her,
I advanced towards the palace in fear,
least I should be found exceeding the bounds allowed to such as were not of the family.
I continued walking in the front and at the side of the palace,
hoping if the princess had concluded to grant my request,
she would see I was under difficulty how to obtain admittance to her.
As no person came to my help, seeing an entrance leading to a court-yard, I ventured in,
when a servant came up to me, saying, "`Are you an Englishman and a Quaker?`"
which comforted me not a little: he then conducted me up a flight of stairs,
at the head of which were placed two sentinels; to whom, I found from my conductor,
the necessary caution had been given,
not to interrupt me because of my hat being kept on;
they allowed me to pass without noticing it.
I was then conducted to the apartment of the princess,
who was attended by one of the females,
with whom I spent some time so agreeably when at Copenhagen before.

The princess received me with her usual affability of manner:
on my informing her the cause of my intruding on her kindness,
and putting the address into her hands directed to the king,
she assured me she would deliver it herself into her father`'s own hands;
which assurance gave me a full discharge on this subject.
After passing a short time in serious conversation with the princess,
through the means of her attendant, she inquired after my family,
expressing her desire that I might reach home in safety: she then gave me her hand,
and I withdrew, and returned to Copenhagen,
with heart-felt gratitude to that Almighty Power,
who had thus in mercy made way for me through the cloud and thick darkness,
which at one time spread over my mind.
In the afternoon I called upon the bishop; but he not speaking English,
I left him under expectations that I might be excused from making him another call.
I returned to my hotel,
endeavouring after that state of quietness and confidence in which our strength consists;
whether it be to abide in our tent while the cloud remains on the tabernacle,
or to move forward when the cloud is wholly taken away again.

As the way did not open with sufficient clearness to warrant
my making preparations for my departure as yet,
I endeavoured to let patience have its perfect work in me:
at length a fresh line of service opened before me of a humiliating nature,
that of visiting the prisoners.
Upon inquiry I found it was very doubtful, whether liberty would be granted.
I called upon my kind friend the baron,
and again informed him of the situation of mind in which I was,
not being aware that granting liberty to visit the prisoners rested with his uncle,
the Count Schoolburgh.
The baron manifested a disposition to enter into my religious engagements;
so that I felt fully satisfied to leave the matter with him,
and returned to my hotel to wait the result of his application to his uncle.

In the evening the baron called upon me to say that
all matters were arranged for my seeing the criminals,
and also the military prisoners if I had a desire so to do.
I had no idea the military prisoners would have been considered a part of my request,
nor could I see that I had anything to do with such,
whose confinement solely proceeded from disobedience of military orders;
but my trials were not as yet over.
I had now to look towards a suitable interpreter,
one who was thoroughly acquainted with the Danish and English languages:
my kind friend the baron would have been competent to the task,
but his various engagements in government concerns at that time,
claimed his whole attention;
I therefore could not feel easy to press on him to engage in the task.
As far as my slender means would allow me,
I made efforts to procure an interpreter myself, but all proved fruitless,
and dismay seemed as if it would have covered me as with a garment;
for I could see nothing before me,
but that after all the kindness of the baron and his uncle in granting me this privilege,
I must relinquish further attempts to have my prospects accomplished:
thus closed as trying a day as most I have had to pass through.
But if all does but work together to humble self,
so as really and truly to be of no reputation at
all--this will be well worth suffering for,
even should the cups, yet to be handed out to me,
be more bitter than those I have had to drink.

Third-day, 31st of eighth month, 1824.
After a sleepless night from the discouragements
I was under in procuring a suitable interpreter,
it occurred to me I might apply to the English consul for help,
he having carried himself kindly towards me;
but the way not clearly opening for my so doing,
I found it would be safest for me to relinquish it.
Earnest were my prayers in this critical moment,
to be rightly directed in my choice of an interpreter; my peacefully quitting Copenhagen,
and proceeding on my way,
seemed so much to depend on getting through what I had then before me,
in a way to secure the stamp of Divine approval on it.
Endeavouring to keep quiet under my discouragements,
my attention was turned to my kind friend Dr. Forrchambre: I went to his residence,
but I was unable to make out whether he was at home, or where he was to be found.
I returned to my hotel, feeling an evidence in my own mind I must try again to see him.
I made another attempt without success: after remaining at home several hours,
as quietly as the nature of my situation would allow, I made a third attempt,
but without succeeding; on which I concluded not to attempt any further to see him.
I then called upon my kind friend Dr. Brandis, and informed him of my trying situation;
one of his family gave me notes to two persons,
each of whom would be competent to help me: the notes were sent as directed,
but neither of the parties were to be met with.
It then appeared to me,
that it would be right for me to make another attempt to see Dr. Forrchambre:
I therefore proceeded to his residence, and found, as before, his door was made fast,
the house being let out to different families.
I resolved to traverse the house from the bottom to the top, to try to make him out,
when coming to a room-door, I heard a voice as if a person was lecturing.
I concluded to remain until the lecture closed, when I knocked at the door,
and the doctor himself opened it, and took me into his own apartment.
We were soon followed by another agreeably-looking man, who took his seat with us.
After some conversation had passed,
I informed the doctor what had brought me in search of him,
at the same time claiming his help: he pleaded his inability,
from not being thoroughly acquainted with the English language;
but he assured me his friend, who had given us his company,
whom he considered a serious character,
was fully competent to afford me the help I stood in need of His friend at first
requested to be excused from taking upon himself so much responsibility,
but on informing him of my circumstances, he at length yielded,
and agreed to attend upon me on the morrow in the afternoon.

Fourth-day, having at times felt drawings in my mind to make another visit to the bishop,
to the minister of police, and to my kind friend Count Schoolburgh,
the doctor kindly offered to accompany me to these places.
We proceeded to the Count Schoolburgh`'s: our meeting appeared to afford him pleasure,
which I could truly say it did to myself;
he informed me he had given orders for such of the prisoners
who worked on the fortifications to be detained at home,
that my views of seeing them together should not be thwarted;
and that the officers in the prison had orders to meet my views in all respects.
After taking an affectionate farewell, we proceeded to the minister of the police,
who received me kindly, saying,
everything at the prison was ordered to meet my wishes in all respects; he requested,
if I had any observations to make, I would do it.
I presented him with the address to Hamburgh, which he said he received with pleasure.

At the time appointed this afternoon, my kind helpmeet in the work waited upon me;
the assurance in my own mind before we proceeded,
that I might confide in his doing his best in giving the
correct sense of what I might have given me for the prisoners,
afforded me some consolation.
Our first visit was to the city prison, called the Jugshuuset:
we found the governor had received orders to admit me,
but he could not at first be made to understand my views for desiring to visit the prisoners.
This placed me in a trying situation; and when this was in degree brought about,
I had to contend with the same difficulty I met with at Spandau with the governor there,
for he objected to the prisoners being assembled,
they being what he called such desperate characters.
I hope I was not void of feeling for my interpreter and the governor,
who appeared much intimidated at the prospect of going among them assembled in a body.
I found a considerable number of those the governor considered the most orderly,
were working in one room together.
I requested to be conducted to this apartment;
on which we were attended by the governor and some of his officers.
I observed, as is the case on some parts of the continent,
a strong military guard dispersed about the prison;
but my dependence I found must be firmly fixed on that Divine power,
that is able to chain down the evil dispositions in the minds of the prisoners,
should there be a desire in any of them to harm us,
and that I must not lean in any degree to the arm of flesh.
It occurred to me, should the prisoners rise against us,
which I had not the least fear would be permitted to be the case,
if the military were to fire,
I should stand no better chance of my life than the prisoners.

In this apartment we met with eighty men prisoners,
employed in preparing and dyeing worsted for the manufacturers:
the governor having informed us there was another company in an adjoining room;
I persuaded him to have them brought to join these eighty, who were now with us,
and he ordered his officers to unlock their door and bring them to us:
quietness soon took place.
What I had to communicate appeared to be generally well received:
heart-felt sorrow was in a striking manner imprinted on many of their countenances;
and great quietness continued throughout the opportunity.
At our parting I gave each of the prisoners my hand.
He then conducted us into another large work-room without my making the request,
and ordering his officers to unlock the doors where the rest of the prisoners were,
they were assembled with the rest in this room.
After the governor had arranged them for all to hear,
as my interpreter`'s voice was not strong, the governor addressed them,
I was afterwards told, in a very appropriate manner,
endeavouring to impress their minds with a sense
of the difficulties I must have passed through,
to come to visit their country and them in this way, from the purest of motives;
he then exhorted them in an impressive manner to
give attention to what I should have to say to them.
This proved a quiet solid opportunity,
both to the prisoners and the officers of the prison, most of them giving me their hands,
I was led to hope, with feelings of gratitude to that Divine power,
who influenced my mind to make them this visit.

The governor then conducted us to the women`'s department,
where seventy prisoners were assembled; the chief of whom were prisoners for life,
except their good behaviour should merit the interference of the king,
who has the power of remitting any part of their sentence.
The women were variously employed; they were very clean in their persons and apartments,
generally appearing healthy, which was also the case with the men.
The governor arranged the prisoners in order before us,
and the opportunity was quietly conducted:
the prisoners were so generally broken into tears,
that I found it hard work fully to obtain relief of mind: on parting from them,
one woman very far advanced in life,
clasped my hand so very tight that I had great difficulty in getting away from her.
It was pleasant to observe the respect which they manifested
for the governor and the officers of the prison.
We parted under feelings of affection for the governor and his officers,
and proceeded to the great prison, called the Stockhuuset,
where those who are considered the most desperate of the criminals are confined:
many of them are chained together,
and employed under a strong military guard on the fortifications.

On our arrival at the prison, the captain of the guard was waiting to receive us;
we were, however, kept some time, which to me might appear longer than it was,
from the solicitude I laboured under to have this last part of my work accomplished:
it appeared that the cause of our detention was, a mistake as to the time of our visit,
and that the men who worked on the fortifications,
had been kept in the prison the whole of the morning awaiting our visit;
but of this arrangement I had not been informed,
so that in consequence of not attending at the time appointed,
they were liberated in the afternoon to go to their work, and had not all returned.
The prisoners were at length assembled in a large courtyard,
where the captain of the guard, my interpreter and myself proceeded:
the sight of so many hundreds of my fellow creatures,
very heavily loaded with fetters and chains, was truly affecting to me,
so that I felt as if I should sink under this exhibition of human woe and misery.
I could not help deploring the wretchedness and depravity
observable in many of their countenances,
which I was led to fear proceeded from the hardened state of their hearts,
induced by long imprisonment,
and the degraded state into which they felt themselves brought,
by being so publicly exposed to view, when marched to and from their work,
chained together under a military guard;
indeed the countenances of some appeared as if they were
ripe for committing the most heinous acts of barbarity;
nevertheless,
the fear of danger from them was not permitted to have any place in my mind.
Great pains were taken to arrange them round the yard,
and we were placed in a situation the most favourable for all the prisoners to hear:
but on taking our station I observed,
that the military guard of the prison was placed behind the prisoners,
who were arranged before us: this, for the moment, made rather a terrific appearance,
and led me, as before, to consider, that if a disturbance were to take place,
and the military were ordered to fire,
it was very unlikely we should escape with our lives.
But being favoured to resume my former confidence in that arm of Divine power,
which remains invincible, I was borne up above all these discouraging considerations;
feeling my mind centered where alone help is to be found,
to aid me in faithfully discharging that which appeared to me to be my duty,
towards these my poor wretched-looking fellow creatures.
The quietness that soon took place,
was such that had it not been for the objects before me,
I might have supposed I was standing beside the grave of a Friend.

I thought I had a sense given me that my interpreter was favoured with best help,
and would be enabled to get through with peace to his own mind,
as he afterwards acknowledged, expressing the thankfulness he felt,
that this opportunity of assisting me had fallen to his lot.
The behaviour of the prisoners during the whole of the time we were with them,
was becoming the occasion.
The countenances of many appeared solid, and,
as if sorrow for their misconduct filled their hearts,
the tears stood in the eyes of some, and trickled down the cheeks of others.
It being rather late in the evening, and feeling myself much exhausted,
I requested that the prisoners might be informed that I
felt unequal to give them each my hand as I wished to do,
and therefore I hoped they would excuse my not doing so:
but this omission has often since occasioned me some severe pluggings of mind;
and from what I at times feel when this visit comes up into view,
had I to pass through the same opportunity again,
I would rather it was necessary from exhaustion to carry me off the spot, than to omit,
as I did, giving these poor creatures each one my hand of love.
Before we parted, the captain of the guard addressed the prisoners,
my interpreter informed me, in a very impressive manner;
recommending them to attend to the advice which had been given them.
We were then conducted by the captain of the guard to his apartments,
where wine and fruit were provided for us.

Before we left the captain, as a token of remembrance of this opportunity,
he requested I would write on a sheet of paper my name and place of abode.
Recollecting that I had one of the pamphlets,
"`Thoughts on the Importance of Religion,`" at my hotel,
I told him I should be glad to present it to him,
if I had the means of conveying it to him: on my reaching my hotel,
a person from the captain was waiting to convey the book to him.
And now I was made fully sensible,
it was through the superintending care of Israel`'s Shepherd,
that my service in this place was brought to a peaceful close.
The gates of Copenhagen appearing set wide open to me,
I ordered a carriage for the morrow to take me to Elsineur.
