== Chapter XXIX.

After our luggage had undergone an examination and our passports were signed,
we proceeded to Nemenerzat, in Prussia.
Here we took a fresh carriage for Memel, where we arrived in the afternoon.
I felt truly thankful to be once more in a land of more liberty.
The rivers and roads beginning to break up, we feared detention;
on which account we thought of securing our places in the diligence to Berlin,
which was to set off the next morning from Memel; but as we understood we should have,
by this conveyance, to travel eleven days and nights before we reached Berlin,
and but little opportunity allowed to rest, much as we were worn down by hard travelling,
and the poor accommodations we had met with, we relinquished this plan,
having several offers of conveyances to Konigsberg; but if we accepted of these,
we must travel the strand-road, which we had made up our minds not to do,
on account of some alarming accidents that had recently occurred from the quicksands.

Fifth-day, having procured pretty comfortable quarters,
our party were refreshed by a good night`'s rest;
we concluded to proceed next morning to Konigsberg,
about one hundred and seventy-four English miles,
and contracted with a man for that purpose.

Sixth-day, morning, we pursued our journey; our carriage measured in length seven yards,
and two yards across, in which were seats slung; but so uneasy were they,
that we were glad to seat ourselves on our luggage,
and at times to lie down on the straw at the bottom of the carriage;
the top was covered with canvas, and a hole left on one side for us to enter;
but so small, that we were obliged to creep in head-first; the difficulty to me was such,
that I was obliged to have help in getting in.
About seven o`'clock in the evening we reached our quarters for the night,
having travelled about fifty-two English miles.
After taking refreshment, we retired to bed,
but the night`'s rest of some of our company was greatly interrupted
by the howling of the wolves in the neighbouring woods,
and the fleas with which our beds abounded.

Seventh-day morning, we proceeded on our way.
After we had travelled about five English miles, our driver made a halt,
telling us he must go and see if the ice on the river, which we had to pass,
would bear us.
He returned, telling us, a carriage had lately attempted to pass,
but the ice gave way and let it into the river.
As our driver resolved to venture, we quitted the wagon to go over on foot.
My dear friend, Daniel Wheeler, had a very narrow escape from the loss of his life;
for had he not been warned at the moment,
he was about to step upon a piece of ice which would have let him into the river;
but we were all favoured to make a safe landing.
I now comforted myself, in hopes the bitterness of our journey in this respect was over.
This being the most dangerous time of the year for travelling,
as the rivers are breaking up,
I was led at times to consider how far I had overstayed the right time at Petersburgh;
but as I felt fully satisfied this had not been the case,
I endeavoured to seek after a continuance of Divine support,
that I might be the better prepared to meet such further
trials of this sort as yet might await us.

We soon came to another large tract of water, which we had to cross,
and where men were plying with sledges to take passengers over, one of which we engaged,
and reached land.
After we had travelled some distance,
I observed on the road many carriages and persons collected together;
on our reaching the spot, we found we were come to a branch of the river Memel,
not having crossed it on our leaving the town; the ice had become dirty,
and put on a rotten appearance,
and the people thus collected were afraid to venture over the river,
which is supposed to be at least half a mile across.
The man at the ferry-house appeared anxious to have us for his guests,
but we felt no ways inclined to gratify him with our company;
as far as we were able to observe, we had not yet seen a more uncomfortable place,
and his countenance to me was more forbidding than his house.
We inquired of our driver how he meant to proceed.
He informed us of his intention to take his horses from his wagon,
and attempt to get his wagon over.
The man who had brought us safely over the latter water, had followed us with his sledge,
and offered to take charge of us again.
As my friend Daniel Wheeler felt his mind easy to venture across, which was my case,
we sat down in the sledge, in full confidence that we should be landed safely at Tilsit,
on the other side.

On our landing, the sledge returned and brought over our two young companions;
our wagon and horses soon followed us;
after which the company we found at the ferry house ventured over one after another.
We made a halt at Tilsit, and took our dinner, after which we proceeded on our journey;
our driver left the post-road, to take what he called a nearer way to Konigsberg.
We lodged at a small house of entertainment by the roadside;
but from the closeness of our bed-room, the abundance of fleas,
and the noise of the wolves in an adjoining wood,
some of us had but little sleep during the night.
If by taking this route, the road was shortened, it was not mended;
for our horses were so covered with mud from head to foot,
that it was not an easy matter to ascertain the colour which nature had given them.
On our arrival at Konigsberg, we engaged our places in the diligence to Konitz.

Third-day,
feeling desirous of ascertaining the state of the river which we had next to pass over,
I bent my course this morning towards it; but I found the road so deep in mud,
that I was obliged to abandon my intention.
During my short ramble,
I was led to take a solemn and awakening retrospect of my visit to Petersburgh,
which produced in my soul the acknowledgment,
that it was through Divine mercy and Divine interference only,
that way had been made for me to obtain that full relief
from the long trial and exercise of mind which I had endured,
whenever Russia came before me while in my native land;
and earnest cries were raised to the Lord my God,
that he would be pleased to continue still to make use of
such ways and means as to Him should seem best,
to effect that profound humility, abasement, and nothingness of self,
essential to my future preservation in that way, which will be most pleasing to him.

Fourth-day, having yet, as we are informed, three rivers to cross,
and being unable to come at the true state of any one of them,
the prospect of our proceeding would be trying,
but from the merciful assurance I am favoured with,
that notwithstanding the difficulties I may yet have to contend with,
I shall have a safe convoy to my own home,
if faith and patience are but steadily maintained.
At our first starting, we had a good road and comfortable space in our carriage:
but when we arrived at the end of our first stage, two persons were added to our number,
which, with the bad road we had to contend with, rendered our sufferings great;
our wheels sunk into such deep mud-holes, that we were near being turned over in them;
and the only person in our company who could understand us, was so sound asleep,
that it was with difficulty we awoke him to make him order
the driver to open the carriage-doors and let us out;
we felt thankful when the door was open, and we had obtained our liberty:
the weather was dry over our heads, but we suffered much from the piercing cold;
but great as our difficulties may be,
we shall see cause for thankfulness they are not worse, as they might have been,
as we were a considerable distance from any help;
such was the weight of our carriage that had it turned over,
all our efforts put together would not have been sufficient to set it up again.

Fifth-day, 24th of second month, this day about noon we reached Marienburg;
our patience was again put to the test, by being detained for the letter-bag,
and from other causes, until six o`'clock in the evening;
this detention was the more trying, as the probability was,
it would occasion us to cross two frozen rivers in the night, and that very dark;
and we were informed that the road which we had to travel was bad;
for we had been obliged to leave the great road on account of the waters being much out.
When we came to the river Nogart, there being but little ice floating,
we passed over without much difficulty in a barge built for the purpose;
but on our landing,
the sample of the road we had to travel presented a discouraging appearance;
and our conductor told us we should not be able to make more than one mile in an hour,
and we must have an additional wagon to take our luggage.
The face of the country appeared so generally under water,
that we were at times obliged to bend our course through large pools of water; and,
when able to keep the high-road, it was barely wide enough to take our wagon;
sometimes on each side of it there was a very deep precipice,
at the bottom of which was water:
in this dangerous situation we travelled until one o`'clock in the morning; yet,
trying as it was, we had much to be thankful for,
as the night proved clear and star-light, and the moon gave some light,
which it scarcely had done since we had been on our journey.
We had another river to pass to come at the lodging place,
which our conductor had been aiming at; but on reaching the banks of it,
we were informed it would not be safe to attempt to cross until day-light;
we were therefore taken to a house for the entertainment of travellers.

On inquiring for beds, none could be procured,
and the floor of the only room in which we could be accommodated,
was merely covered over with pea-stalks.
On entering this room where we had to take up our lodging for the night, dirty-looking,
miserable men and women put their heads out of the peastraw to gaze on us;
others were drinking, smoking, and making a noise: clean straw was brought in for us,
upon which I could gladly have laid my weary bones,
but from the fear of damp and the vermin I might collect from my next neighbour,
as they were lying pretty thickly about the floor,
and others were sitting drinking and smoking: we concluded to keep on our fur-coats, and,
by the help of a table to lay our heads upon, to try to get some sleep.

Towards morning, we enjoyed some quiet:
and at day-light a pretty general sallying out of men and women took place:
some of the men proceeded to prepare the way through the ice for our departure.
I rejoiced to see the peep of day, and was glad to turn out of our filthy apartment,
and get away from the fumes of the spirits and tobacco, to breathe the fresh air;
but when we came to take a view by day-light of the road
which we had travelled to reach this miserable abode,
and the danger we had been exposed to, while it occasioned a chill of dread all over me,
it awakened afresh in my mind feelings of gratitude,
and caused songs of praise secretly to arise to that Almighty Power,
who had in mercy watched over us, and preserved us from all harm.
When the men had cut a passage for us over the river Vistula,
which is of considerable width, a boat was in readiness to receive us and our luggage.
I felt a little tried on getting into the boat,
from the large sheets of ice floating round us.
I esteemed it a favour when we reached land again; yet on being informed,
that before we could be accommodated with a carriage to go forward,
we had a branch of this river still to cross,
and its surface like that which we had left, a fresh trial presented itself to my mind.
We however made our way through the ice better than I at first expected,
from the immense quantity that had floated down and collected like small hillocks.
We were truly glad when we reached Dirschaw, feeling ourselves in need of refreshment.

On entering our fresh carriage, it promised more ease than we found in that we had left,
and we had reason to believe this would have been the case,
had not the roads been much cut up during the thaw, and a severe frost now again set in,
by which means the roads were rendered so rough,
that my shoulders and elbows were full of pain and my sufferings hard to bear:
the like was the case with my dear companion, so much so,
that we could not have endured it many hours longer.
We reached Konitz on seventh-day morning;
here we concluded to rest awhile to recruit our strength,
and get a little eased of the soreness of our bones and flesh, for we felt much bruised.
Expecting we should have to cross the river Oder on the ice,
we felt solicitous to ascertain the state of it,
and learned from the post-master that it was considered safe to pass over;
but a short time might render it impassable from the floating down of the ice,
and then we might be detained at the ferry-house for two weeks or more;
and should a thaw take place,
the roads for awhile would be impassable without great risk of our lives:
weary and sore as we were, this put a spur to our exertions;
we therefore engaged a wagon, and had it well littered with straw,
which accommodated us and our luggage, and we proceeded on our journey again.

On second-day, taking provision with us,
we travelled about sixty-five English miles before night.
At the post-house we were informed,
that from the route which we had taken we should escape the ferry,
and pass over a bridge lately erected over the river Oder.
Third-day, we reached Fredericksburg to lodge,
having travelled about sixty-five English miles this day; to effect which,
we were obliged frequently to leave the post road and travel on the farmers`' grounds.

Fourth-day morning, we left Fredericksburg;
during the afternoon we arrived at the bridge which took us safe over the Oder,
thankful we had taken this route.
The river being broken up, the ice was floated down in such large masses,
as would have rendered our passing by the ferry dangerous,
if it had not detained us there.
This day we entered on the Ckanssee,
a new road on the plan of our mackadamized roads in England,
which gave us a cheering hope of being likely to reach Berlin the following day;
this we were favoured to accomplish by travelling one stage in an open wagon,
by which I caught a severe cold.
So anxious were we to get forward,
that after obtaining information respecting the best route for us to take,
we took the earliest opportunity to hire a carriage to Minden:
matters being concluded on, I made a call on my dear friend the magistrate F+++______+++,
the Count V+++______+++, and most of those I had made an acquaintance with, when here before:
this unexpected opportunity of once more seeing each other,
appeared to be mutually gratifying.

In the evening a person of the name of Lindly, formerly a Catholic priest,
but who had embraced the Protestant religion, called on us.
He had spent some time in Petersburgh,
and was contemporary with the person I met with at Altona,
who had been banished from Petersburgh on account of his religious principles:
he manifested much anxiety for information respecting those he had left behind in Petersburgh,
who were united to him and his companion in religious sentiments,
of which he said there were not a few; but as silence was to me the word of command,
and I had felt so much the necessity, when in Petersburgh,
of avoiding too free interaction with those I was a stranger to,
I was not prepared to converse on this subject.
We also received a visit from the magistrate F+++______+++,
who informed me he had recently received a visit from the pastor of the prison at Spandau,
which prison, I visited when here before, by whom he was assured,
that a great improvement had taken place in the conduct of the prisoners,
since that visit was paid to them;
that both the men and women had become much more orderly in their conduct,
and their behaviour at their place of worship was now very becoming.
This account felt like marrow to my bones, and awakened secret cries to the Lord my God,
that the praise and the glory might all be given to him, and to him alone.
I was not able to enjoy an exchange of sentiment when I called on the Count V+++______+++,
his amiable countess being from home, who was conversant in the English language,
but with which he was unacquainted.
I made him a second call, with an interpreter, but the count was from home;
in consequence of which he addressed me by letter,
which I think right to give a place in these memoirs,
as it may afford the reader some idea of the purity of his mind;
and the blessing it may prove to the kingdom of Prussia,
that her next sovereign in succession, has such a pious aide-de-camp, as the count,
so near his person.

[.offset]
The letter Englished is as follows:

[.embedded-content-document.letter]
--

[.salutation]
My dear and honoured friend,

I have been very sorry that we missed one another,
and your hasty departure deprives me of the hope of our meeting again: in the meantime,
receive my sincere thanks for the valuable book you sent me,
and for the undeserved kindness which you have shown me.
I forwarded the other copy to his royal highness the crown-prince;
he is greatly obliged to you for his present.
Your kind fellow traveller has also thought of us,
and sent my wife and children a supply of small and large books,
which they find quite a treasure.
I am really quite ashamed of your kindness: my wife, who has been some months from home,
intends to send you her written acknowledgment.

Thus you have heaped upon us, who feel poor, the blessing of love: and what shall we do?
we pray the Lord of mercy and of all life,
that he will bless you both with his richest blessings, that he will give unto us all,
the communion of the Spirit, and the love of the Father, and his fear.

With sincere and cordial love, I am,
my dear friend`'s faithful and devoted friend and brother,

[.signed-section-signature]
Charles Count V+++______+++,

[.signed-section-context-close]
Berlin, 2nd March, 1825.

--

Sixth-day, we left Berlin, and reached Brandenburg to lodge.
Seventh-day, we reached Magdeburg early in the evening,
where we took up our abode for the night.
Next day we proceeded on our journey in hopes of reaching Brunswick to lodge,
expecting we should find a continuation of the Chaussce,
as we had been led to understand would be the case; but after leaving Magdeburg,
to our great disappointment, we came on a road as bad as any we had yet met with,
which continued the whole of this day`'s journey:
we repeatedly expected to be overturned; and after twelve hours`' hard travelling,
at times fearing our horses would not hold out,
we advanced no more than thirty miles on our way.
We had furnished ourselves with provision, or we must have suffered on that account,
as the only house we came to during the day, was not able to furnish us with clean,
comfortable necessaries of life: next day we reached Brunswick to dinner,
and Payne to lodge.

My kind companion, Daniel Wheeler, and myself,
felt ourselves so much exhausted by these two days`' journey,
and so desirous of getting to bed,
that we omitted our usual precaution of airing our sheets, and coverlet ourselves;
these we suppose were damp, which occasioned our taking a heavy cold.
Next morning we proceeded towards Hildesheim;
but our poor horses were so oppressed in consequence of the bad road, that we concluded,
on reaching the end of our first stage,
to excuse the man from proceeding further with us, and to travel extra post to Elze.
This has been a large populous town, but in the eleventh month last,
nearly the whole of it was reduced to ashes, whereby numerous sufferers lost their all;
the most deplorable picture of distress which I ever beheld
presented itself as we travelled through the ruins,
exciting in my mind great sympathy for those who were the objects of it.

At Elze we engaged our places in the diligence for Minden,
which place we reached about five o`'clock next morning: on our arrival here,
rest to our fatigued bodies would have been truly acceptable;
but it appeared best that we should engage our places in the diligence,
which was to set off at nine o`'clock in the morning for Emmerick,
a frontier town in Prussia; this only allowed time to clean ourselves, take refreshment,
and make a short call on some of the Friends.
Here we were informed that we should again travel on the _Chaussce_,
but in this we were greatly disappointed; for from the badness of the road,
our heavy lumbering wagon, the great weight of luggage,
and long stops which our drivers made on the road,
we did not average more than two and a half English miles an hour,
which to me proved an exercise of patience.
But I was favoured, through the continuation of Divine mercy,
sensibly to feel the need there was, quietly to submit to these disappointments;
otherwise there would be a danger of my being robbed,
and spoiled of those feelings of gratitude that had been awakened in me,
for the favours vouchsafed during this wearisome and perilous journey, which I had,
through Divine help, thus far been enabled to accomplish.

We reached Munster, where we were detained ten hours,
which afforded us an opportunity of resting our weary bodies on a bed.
We had been assured that we should have the same carriage the whole of the way to Emmerick,
but this did not prove to be the case; this circumstance caused us some difficulty,
in seeing our luggage was all again rightly packed.
We had a more roomy carriage: but notwithstanding this we felt so sore and bruised,
that we were obliged to take four places for three of us,
the young Englishman having previously left us; had we not adopted this plan,
I believe we could not have gone forward this day.

Sixth-day morning, we proceeded on our journey; our road became still worse,
and I was fully satisfied of the truth of the report of some of our friends in Petersburgh,
if the winter had been quite broken up,
and succeeded by those falls of rain that frequently
take place at this season of the year,
the roads would have been so deep in mud as to render them for a time impassable;
so that every way, great as our trials of patience have been,
and much as our bodies have suffered, we have great cause to be thankful,
that we have been so cared for, and watched over by that Almighty Power,
who regards the very sparrows; and that we have been thus far brought safely on our way.
About two o`'clock on seventh-day morning, we reached Bocholt,
where we again changed our carriage, and were detained two hours in a cold,
comfortless kitchen: the sight of our new carriage was discouraging, it was smaller,
and only a basket-wagon; the curtains of which were so worn,
that we were but very little screened by them from the cold damp night-air.
We reached Emmerick about eight o`'clock in the morning, and I took a fresh cold,
my throat became very sore, and the roof of my mouth was so much swelled,
that I found it difficult to converse.

From Emmerick, we took our places to Arnheim, a frontier town of Holland,
at which place we arrived in the evening;
We then secured places in the diligence for Amsterdam,
where we arrived safely the following day.
I made a few visits to some of my friends there,
and as the packet from Rotterdam for England would not sail before first-day,
we agreed with a coach-master to take us to Helvoetsluys,
and on third-day morning we proceeded on our way.
Having reached Marsland Sluice, which was only about half-way,
our driver would not convey us any further;
we were therefore obliged to take a boat across the sluice,
and when we reached the shore on the other side, to take a carriage to the Brill,
where we had to cross and take a carriage forward.
These trials were all abundantly compensated,
by knowing I was now making progress near to my native land,
to enjoy the privilege of being understood in my own language.
The wind being fair for England, promised us a quick passage:
we reached Helvoetsluys before dark,
where we learned the packet for Harwich was to sail next morning at nine o`'clock.

Fourth-day, 16th of third month, 1825, we went on board the packet,
and set sail with a fair wind.
From the peaceful retrospect I was enabled to take of my visit to Petersburgh,
all the deprivations, perils, and dangers I have had to pass through,
seemed to sink into nothing.
The wind continuing fair,
about ten o`'clock at night we could discern the lights on the English coast;
and had it not been for the danger of the sand-banks,
we might have made a landing by four o`'clock the next morning;
but we did not effect it until eight o`'clock,
having had a passage of twenty-three hours.
After the examination of our luggage, taking refreshment, and trimming ourselves,
we took coach for London, which we were favoured to reach safely in the evening.
I proceeded to Tottenham, and on seventh-day to my own home at Hertford.

Second-day, I attended the Quarterly Meeting held at Hertford,
and gave in to the meeting a short report of my visit to the continent,
to the satisfaction of my friends, as I had reason to believe.
Feeling myself much exhausted,
I was obliged to leave the meeting before its business was got through.
My journey being now accomplished, and the excitement to push on being over,
I began more sensibly to feel how much nature had been exerted beyond what it could bear.
While labouring under this state of debility, a letter arrived,
giving an account of the dangerous state of health of our children at Sheffield.
My friends, as well as myself, thought that I was more fit to take to my bed,
than to undertake such a journey;
but as I was led to apprehend my sufferings from not seeing them,
should a removal of either take place, together with the suspense we might be kept in,
would be greater than the fatigue of the journey on sixth-day morning,
accompanied by my dear wife, I proceeded by coach to Sheffield,
which we reached the next day.
I continued in such a state of debility for some time,
as not to be able to get out to meeting.
I found it indispensably necessary to endeavour to keep in the lowly valley;
lest the dew, which I was favoured to witness resting on my mind,
should be suddenly dissipated,
through my too freely conversing on my religious movements on the continent,
or by reason of worldly matters that had transpired in my absence,
in the settling of which,
Divine interference had been manifest in a remarkable manner.
I never felt more need of all the help designed for me, than at the present time.

22nd of fourth month, 1825, although in a very low and depressed state of mind,
yet I humbly hope I may say,
I am made truly thankful in feeling earnest desires to the Lord begotten in my soul,
that he would be pleased to preserve me from allowing my
mind to be in any way entangled with my worldly matters;
and that he would give me strength to commit them all to his careful keeping,
and preserve me from doing more toward a further arrangement of them,
than he in his wisdom shall see fit to guide me therein:
and if the pointings of duty should be for me to commit the whole
disposal of them to my children`'s management in future,
to enable me cheerfully to submit to it.

In the fifth month, although I felt hardly equal to the undertaking,
I went up to London to attend the Yearly Meeting.
Further religious service which was in prospect pressed on my mind,
and spurred me on to be willing to do my best,
in order to return my certificate to the select Yearly Meeting,
and give in my report this year;
for should I be constrained to come forward to my Monthly
and Quarterly Meetings with a religious prospect,
which my mind has again been brought under, and be liberated by these meetings,
the way might be clear for me to lay my religious
prospect before the select Yearly Meeting next year.
I therefore proceeded by coach to Hertford, and from there to London;
attended the select Yearly Meeting, and returned my certificate,
and gave in a report of my proceedings, which was a relief to my mind.
I felt thankful strength was given me to attend the several sittings of the Yearly Meeting.

My mind continued to feel a lively interest and frequent exercise,
on behalf of the dear Emperor Alexander of Russia,
and his faithful friend the Prince Alexander Galitzin,
as well as the prince`'s secretary; feeling my mind drawn to make the same manifest,
by presenting each of them with a religious publication,
which to me appeared suitable for the occasion, I wrote letters to accompany them,
and committed them to the care of a kind friend for delivery.

[.offset]
That to the emperor was as follows:

[.embedded-content-document.letter]
--

Thomas Shillitoe has taken the liberty of requesting his dear illustrious friend
will accept of this small token of his continued sincere love and regard.
He has to recur daily, with feelings of satisfaction,
more easily conceived than described, to those precious overshadowings of Divine regard,
of which he was made very sensible during the interviews
he was favoured to have with his illustrious friend;
for whom his earnest breathings of soul continue to be, that Almighty God may be pleased,
according to the riches of his grace, so to strengthen him with might,
by his Spirit in his inner man, as that he may be enabled, with holy magnanimity of soul,
to rise above all the slavish fear of man,
and above every discouragement that Satan may be permitted
to lay in the way of a faithful walking before God:
that thus his illustrious friend may be found standing in
the allotment designed for him in this state of probation;
and finally, through the merits of the great Redeemer,
receive a crown of glory that fades not away.

--

Prudence seemed to dictate my not inserting the name
"`emperor,`" lest the parcel should be intercepted.

[.offset]
That to the prince Alexander Galitzin, and his secretary, was as follows:

[.embedded-content-document.letter]
--

I believe I can safely say, a day has not passed since our parting,
wherein I have not recurred to the frequent opportunities we had together,
and been made renewedly sensible of the precious savour of Divine love,
which then so sweetly united our hearts in sincere desires for each other`'s welfare.

Daily have my prayers been put up to the Lord Almighty,
whose power alone can preserve in heights and in depths;
that he may be pleased to support your heads above every billow, which,
in the ordering of his Divine wisdom,
and for the accomplishment of his inscrutable designs, may be permitted to arise:
and I am well assured, that if he alone be looked unto and depended upon,
he will do thus for you,
and enable you to continue to run in the ways of his requirings without being weary,
notwithstanding the many discouragements with which the enemy of
all righteousness may be permitted to assail your minds.
That this may be our united experience, is the fervent prayer of my soul.
Please accept of a small token of my remembrance.

[.signed-section-signature]
Thomas Shillitoe.

--

The Yearly Meeting being over, I returned to Sheffield.
Not getting better of that lassitude, weariness,
and increase of pain in my shoulder produced on the continent,
it was proposed for me to spend some time at Buxton, to bathe and drink the waters,
which I consented to, and I found great relief thereby.

During my stay at Buxton, I was disposed one morning to go into the poor`'s bathing room,
while the men were bathing; but from the smallness of the place,
the lack of proper ventilation, and the smell of the men`'s dirty clothes,
I was under the necessity of immediately leaving it.
I was well informed, that the poor patients were often obliged to dress themselves wet,
for lack of towels, which many were so poor they could not bring with them;
and when they came out of the bath, they had to stand on the bare stones,
or sit on a stone seat without matting, to undress and dress; and thus,
though some might derive benefit,
others were more likely to have their sufferings increased.
Believing I should not feel myself acquitted in point of duty,
unless I did my utmost fully to investigate the accommodations
of these baths for the poor,
I set about the business in good earnest.

When I had fully satisfied myself by witnessing the manner
in which these baths were neglected every way,
except the bare use of the water, the next consideration was,
how these things were to be remedied; and I found I must not leave Buxton,
if I was favoured to preserve a peaceful, quiet mind,
until I had made every effort in my power towards the accomplishment of this object.
I turned my attention first to one person and then to another in the place,
to whom I might open my views;
but I did not seem at liberty to confer with any of them on the subject.
I was informed that visitors had already felt much
on account of the neglected state of these baths,
and in consequence of their exertions,
an assurance had been given that the evils should be remedied;
but after they left Buxton nothing had been done.
I was brought so under the weight of the subject,
that it appeared to me I must make a visit in person to the Duke of Devonshire,
the baths being his property.
I therefore drew up a fair statement of all things
relative to the defects of these baths,
and walked to Chatsworth.

As I walked there, I felt somewhat discouraged.
Having no letter of introduction, I called at the house of a Friend at Bakewell,
hoping through him to obtain a letter of introduction from the clergyman of the parish;
but the Friend was not at home.
I proceeded under the belief,
that the best of introduction would accompany me if I only went in the faith, that He,
who, I humbly hope I felt, had called me to the work,
was able to make the way easy for me to obtain the ear of the duke;
I therefore proceeded.
On my arrival at the porter`'s lodge,
I was informed the duke did not receive any verbal messages.
I had put into my pocket one of our works on the principles of our religious Society,
thinking, if a difficulty should arise about my obtaining an interview,
this might in some way be a help to me: I then wrote the following note,
and sent it to the duke:

[.embedded-content-document.letter]
--

One of the Society of Friends, wishes in person to present the duke with a work,
which he hopes the duke will find an interest in reading.

--

The note being sent, I was immediately introduced to the duke,
who received me with great affability, requesting I would take a seat:
on my presenting him with the book, he expressed the satisfaction he had in receiving it,
and in a handsome manner proposed paying for it; to which, of course, I objected.
I then opened to him the main subject which had been the cause of my making him the visit.
It appeared he was wholly unacquainted with the neglected
state of these baths for the poor;
for he said,
it was his desire that the poor when bathing should be made as comfortable as the rich:
he treated the subject in an open, agreeable manner,
manifesting an inclination to receive any information I was capable of giving him.
On my begging leave to read the observations which I had
made relative to what was needed in the poor`'s baths,
he readily granted my request; a copy of which I left with him,
recommending him to visit them himself when the men were bathing,
that he might see and judge what was necessary to be done there,
to render the poor comfortable, which he assured me he would do,
and that the needful should be done; he expressed the obligation in strong terms,
which he felt himself under to me, by my laying this matter before him,
and we parted in a friendly manner.

I walked back to Buxton, rejoicing that the way had been made thus easy for me.
Although from the extreme heat of the weather, and the distance I had to walk,
being at least twelve miles, I felt greatly fatigued;
yet the satisfaction of mind resulting from exerting
myself in doing my very best for the help of those,
who were not in a way to help themselves, abundantly recompensed me.
It soon became noised abroad that I had been to Chatsworth, to the duke,
and the supposed errand I had been on;
this reached the ear of the individual in whom the duke confided
to see that these matters were properly attended to;
he soon afterwards made me a call, informing me, if I had spoken to him,
the needful should have been done.
But I had from good authority understood such promises
had before been made by the same individual,
but never realized.
I was therefore persuaded no way was so likely to effect a remedy,
as going to the principal, as I had done.
I left Buxton shortly after; but I received accounts from visitors whom I left behind me,
that soon after my departure the necessary improvements
for the accommodation of the poor`'s baths took place,
for both men and women.

9th of third month, 1825, My son-in-law received a letter from a Friend,
who was desirous of laying before me a prospect of duty,
which would be required of him to make a visit to New South Wales;
but as my mind was under exercise, from an apprehension the time was nearly come,
when I must be willing to lay before my friends a prospect of religious duty,
to visit Friends on the continent of America,
and that it would be unsafe for me to enter into the Friend`'s concern,
I dared not read the letter.
The latter end of this month, accompanied by my dear wife, we returned to our own home.

Second month, 1826.
My religious prospects to visit the continent of North America being now matured,
I this day informed the Friends of my own Monthly Meeting thereof,
and a certificate was granted me accordingly.
At the Quarterly Meeting, in the third month, I again opened my prospect of duty,
to pay a religious visit to Friends on the continent of America;
which being united with by the Quarterly Meeting,
an endorsement was made on the Monthly Meeting`'s certificate, and signed by the clerk.
Having proceeded thus far towards being set at liberty,
and my dear wife becoming so infirm,
as to make it necessary she should be nearer meeting than we at present were,
and it being her desire again to settle in the compass of Tottenham Monthly Meeting,
I engaged a residence for her there,
to which place we moved previously to the Yearly Meeting. At the select Yearly Meeting,
in the fifth month, 1826,
I opened my prospect of duty to pay a religious visit to Friends in America;
and this meeting, after solid deliberation thereon, ordered a certificate to be prepared;
which being done, and signed, was given me accordingly.

21st of sixth month, attended the Quarterly Meeting of Hertford,
of which I still remained a member, and from Hertford, I proceeded to Hitchin,
to take leave of my dear children and friends there.
