== Chapter XXX.

Sixth-day, 21st of seventh month, 1826.
I left my dear wife, family, and comfortable home at Tottenham; proceeded to London, and,
accompanied by three Friends, afterwards took coach to Sheffield, in Yorkshire;
at which place we were favoured to arrive safely on seventh-day afternoon.

First-day, attended the usual meeting there; in which I humbly hope I may say,
I endeavoured to acquit myself in such a way as would be the most
likely to secure to me that continuance of Divine regard,
which I awfully felt my situation in prospect would in a more especial manner need.
The meeting in the afternoon was largely attended,
and I believe proved a time of Divine favour, to the humbling of my heart.

Second-day morning, 24th of seventh month,
attended to some arrangements for my departure, and on third-day morning,
accompanied by my dear son-in-law, John Heppenstall,
proceeded to Ackworth school to attend the general meeting of that institution next day;
on our arrival we were kindly received by Robert Whitaker, his wife,
and other members of that family.
Here I met with several Friends from different parts of the nation,
which appeared to be mutually consoling.
It is a great favour thus to find that the bond of true discipleship is not dissolved.

Fourth-day morning, the meeting for Divine worship commenced;
it was attended by Friends and some others not in profession with us,
and proved a season in which the Ancient of Days was pleased, in his renewings of mercy,
to condescend to come down and tabernacle with us,
to the comforting of the minds of such as were rightly
concerned to gather to that place of true waiting,
where alone a right qualification for the performance
of acceptable worship is to be known.
After this, the concerns of the institution were entered upon: being one,
among many more,
nominated as a committee to examine the children`'s progress in learning,
I quietly submitted to my name standing, rather than set an example of refusing;
notwithstanding I felt so enfeebled both in mind and body,
with the prospect of the nearly approaching trials that awaited me,
I could gladly have been excused.
In the evening, after supper, the usual pause took place;
and by endeavouring faithfully to cast before my friends
that which I believed was given me for communication,
the day closed peacefully; for which, I hope I may say,
I was favoured to feel humbly thankful.

Fifth-day evening, the business of the general meeting concluded,
with feelings of gratitude accompanying many of our minds
for the favours that had been dispensed by the great I Am,
during its several sittings, and in mercy continued to the end.
After the close of the general meeting, I proceeded to Doncaster,
lodged at Richard Cooking`'s, and next day returned to Sheffield.

Seventh-day, 29th of seventh month, I proceeded by coach for Liverpool,
with my son-in-law John Heppenstall; which place we reached this evening,
and were kindly received by our mutual friends, Thomas and Frances Thompson,
by whom I was informed my passage in the packet, about to sail for New York on third-day,
had not been secured, agreeably to my request:
the captain feared he could not make me comfortable, as he wished to do,
in consequence of the crowd of cabin-passengers that were going in her,
mostly gay young men; and should they be disposed to sit up late at night, singing,
dancing, and drinking, as at times is the case, they would greatly annoy me,
and the captain might not have it in his power to prevent it.
There being two merchant vessels about to sail for New York the same day,
it was by my friends apprehended I should be more
comfortably accommodated by going in one of them:
it was too late this evening to attend to this matter,
so that the subject was left until second-day.

First-day, I found it hard work to stand up in meeting this morning;
I delivered that which to me appeared to be the counsel of my Divine Master.
The evening meeting was largely attended, and was a very exercising time;
yet I felt thankful my lot was cast among Friends in this place;
believing there were yet preserved in this meeting,
those who are mourning the desolation which the spirit of the world has occasioned,
within the borders of our once highly-favoured Society.
Spent the evening at my quarters:
this day closed under a comfortable hope that I had been
found in the faithful discharge of apprehended duty;
and earnest were my desires to be preserved moving under the guidance of Divine wisdom,
in securing my passage across the mighty ocean.

Second-day morning, 31st of seventh month,
the way appearing to open with clearness in my mind,
I proposed a few Friends to accompany me first on board the packet;
apprehending it would not be safe for me to relinquish a passage in her,
in favour of one in either of the merchantmen,
until I had a clearer evidence than at present I was able to come at;
notwithstanding all the difficulties a passage in the packet seemed to threaten.
Accompanied by my kind friends Thomas and Frances Thompson, and other Friends,
we proceeded on board the Pacific, packet-ship, Captain Crocker, bound for New York;
we took our seats in the cabin:
my spirit was bowed in humble prostration before the throne of Divine grace,
accompanied with earnest desires to be favoured with all-sufficient help,
that a willingness might be brought about in me cheerfully to yield to the Divine will.
I was favoured to get into that quiet,
where alone the voice of the true Shepherd is to be known; and a clear sense was,
as I believed, given me, that if I were faithful to present conviction,
I must submit to have my passage secured in the Pacific,
and not allow my mind to be perplexed by seeking further;
I therefore informed my friends to this effect: and my passage was secured in the packet.

Third-day, 1st of eighth month, accompanied by my son-in-law, T. and F. Thompson,
and several other Friends, we went on board the packet.
I humbly hope I could say,
I felt truly thankful in feeling myself so much at home on board; my mind was calm,
without a desire to leave, until, if permitted so to do,
I should land on the other side the Atlantic ocean.
We soon left the dock,
and were towed by a steam-boat about five miles down the river Mersey;
the wind being unfavourable for us to proceed on our voyage,
we cast anchor for the night.
Many of the cabin passengers returned by the steam-boat to the shore again;
but as I had taken an affectionate farewell of my friends,
and had indulged in the prospect of them on the pier,
as long as my eyes were capable of this enjoyment,
I concluded it would be best for me to remain quietly on board,
and occupy my time in arranging my luggage,
before the hurry occasioned by the other passengers, who would be alike occupied,
commenced.
Captain Crocker had kindly given up to me his own berth;
which being about the centre of the vessel, and having it to myself,
I passed the night very comfortably; yet not without some feelings of doubt,
how it would prove with us when the cabin-passengers returned to the vessel.
I could not but anticipate the probability of our frequently interrupting each other,
from the small space we had to occupy compared with our number;
there were twenty-seven cabin-passengers, a considerable number in steerage,
with our captain and his men, in all amounting to seventy-five souls.

Fourth-day morning, we had a very awful storm of thunder and lightning; but my mind was,
through Divine mercy, preserved quiet through the whole;
under the assurance I was as safe, and as much under the Divine protection at sea,
as on the dry land.
About ten o`'clock, our captain and the remainder of my fellow-passengers came on board:
and about half an hour after their arrival, we set sail with a fair wind for New York.
I was truly glad that I remained on board,
and embraced the opportunity of arranging my luggage,
from the confusion occasioned for a time by those who went on shore.
About ten o`'clock this evening we passed Holyhead.

Fifth-day morning, the wind fair; I began to feel symptoms of sea-sickness,
but it lasted a very short time, and I became more comfortable the remainder of the day.
Although my dear wife and children at times glanced before the view of my mind,
yet I was not permitted to feel anxiety on their account,
or for aught I had left behind me.
Having thus embarked on the bosom of the great deep
under an apprehension of Divine requiring,
my greatest concern was, that during my separation, whether shorter or longer,
from them and my outward concerns,
I might be preserved so fully and so faithfully attending to my great Master`'s business,
and so patiently abiding in that sphere of action he may see fit to place me in, as that,
when my service on the American shore shall be over,
if permitted to return to my native land,
it may be with the reward of that soul-enriching peace,
which ever will in due time follow obedience unto Him.

Sixth-day, the wind fair: at ten o`'clock this morning we came in sight of Cape Clear,
and about noon we lost sight of land and entered the Atlantic Ocean.
I had been led to consider, when the passengers returned to the vessel again,
that the first impressions we receive of liking or disliking each other,
are the most lasting and that when once the mind has received an unfavourable bias,
or an impression of disgust, in consequence of any improper demeanour on our parts,
it becomes an almost insuperable bar to that line
of usefulness which otherwise we might be of.
My own comfortable procedure from day to day,
while confined in such a narrow space as we were--only
the cabin or the deck for our accommodation,
and the way opening in the minds of my fellow-passengers to receive
any proposals I should feel it right to make to them,
would therefore much depend on my carrying myself in the
outset as courteously and affably as I could towards all;
at the same time, not countenancing wrong actions or expressions,
by keeping silence when duty called upon me to rebuke;
but being careful at all times to feel the necessity laid on me so to do,
and that it be done in the spirit of love and meekness; otherwise to keep silence,
and let the countenance manifest,
we do not approve of words or actions opposed to the doctrine of Christ our Saviour.

Seventh-day, wind fair, which I hope I esteem a great favour;
may I give proof thereof by my consistent conduct at all times and on all occasions,
while confined in this small space;
and not expect more from my fellow-passengers than I have a right to look for,
considering their age, education, variety of dispositions and propensities;
but endeavour to bear with Christian patience and fortitude any unpleasant occurrences,
should such take place.

First-day morning, calm weather: we make but little way.
My sickness has wholly subsided, and my appetite continues good;
yet my mind is afresh brought under exercise,
at the prospect of proposing to my fellow-passengers
our assembling today in a religious capacity:
may I be preserved, keeping my proper place among them every way.
At the breakfast-table, this morning, I received strength to propose,
that we should fix upon an hour to collect together, to sit down to read the Scriptures;
this seemed to be as far as I felt myself authorized to go;
with which the captain and passengers united,
and proposed our meeting at half-past ten o`'clock this morning.
A general muster took place accordingly: after a short pause,
one of the most giddy of our company, a well-educated man,
proposed himself to take my Bible and be the first reader.
On my being queried with, if I had any choice where our reading should commence,
having thus far been favoured to gain their attention,
I felt most easy to leave this matter to themselves.
After a suitable time had been spent in reading, a pause ensued; and feeling,
as I was led to believe, my mind charged with something for communication,
that which was offered appeared to be generally well received.
I had proposed in my own mind to make a visit to
the steerage-passengers and the ship`'s crew,
and read to them but before I could make the effort towards it,
a giddy young man of our company proposed such a measure being adopted,
and offered to accompany me with my Bible,
and others offered their assistance in reading to them; which accordingly took place;
those who attended, of the steerage-passengers and men, behaved orderly,
manifesting satisfaction that they had been thus far noticed;
and the day passed over quietly, beyond my expectation.

Supper being over,
I proposed closing the day by some one of us again
reading a suitable portion of the Sacred Writings,
which was joined in with, and our company assembled in the round-house.
After all were seated, and a quiet took place,
first one and then another of our company read; after which a little quiet ensued,
and one of our company, a serious young Englishman, proposed giving out a hymn.
For a moment I felt in a strait between two;
but as I was not bound to take an active part with them in this matter,
it appeared best for me quietly to keep my seat among them.
When it was over, I felt thankful,
in that I had reason to believe my not joining my voice with theirs therein,
had not lessened that regard which they increasingly manifested towards me.
Soon after our separation, we all retired early to bed.
The day having thus comfortably closed, was cause of thankfulness to my own mind;
and there was good ground for believing it was so with others in our company.
This day`'s proceeding afresh excited in me feelings of gratitude to my Divine Master,
in that he was pleased to preserve me from abandoning my passage in the Pacific.

Second-day, not making much way to New York:
my mind continues to be preserved in patience;
a virtue necessary for those to have a good store of, who traverse the great deep,
where there is nothing to look to but the unstable element, besides Him,
whose controlling power alone commands a storm or a calm.
Yet the adversary assaults me not a little with fears and discouragements, if possible,
to lay waste my confidence in the Divine all-sufficiency,
to care for and protect me on every hand;
but Divine mercy continues still to watch over me:
that I may never be permitted to forfeit this Divine superintending care and protection,
is the earnest prayer of my soul.

Third-day, fair weather, but the wind so very light, we make but little way.
How entirely, under our present circumstances, are we dependent on that Almighty Power,
who commands the winds and is obeyed!
Towards evening a brisk gale sprang up,
which had a cheering effect on the countenances of many of my fellow-passengers,
who were longing to reach our destined port.
I hope I am not unmindful of the favours I am enjoying, being preserved in resignation,
as to the event of a short or a long passage.

Fourth-day morning, going through the night at the rate of seven knots an hour,
and continuing so to do; from the motion of the vessel,
some of us feel disposed to be a little squeamish; but towards noon the wind slackened.
What a mercy it is from our heavenly Father, to be made willing, in every state,
therewith to be content!
During my time of retirement this morning, I was led to see with the eyes of my soul,
as clearly so as ever I beheld any object with my outward eyes,
myself landed in the city of New York, and a man approaching me in full speed,
and I was led to believe his mind was charged with
combustible matter to pour out upon me.
This, at first, caused that degree of sadness to come over my mind,
which I cannot describe; but I was favoured with the assurance,
if my dependence continued to remain firmly fixed on that arm of Divine preservation,
which had brought me through so many difficulties and dangers,
this man would be restrained by that same invisible power from doing me harm;
after which my mind became tranquillized.

Fifth-day, going at the rate of eight knots an hour,
which caused great motion in the vessel.
I found I must try to keep as quiet as possible,
or there would be a danger of my being quite laid by.
The man I had seen during my retirement yesterday,
came today fresh before the view of my mind; but an assurance attended from Him,
who never fails to fulfill all his gracious promises,
if on our part we are careful that the conditions of them are faithfully complied with,
that if I was earnestly concerned to keep near to Him,
who had called me forth into his service,
carefully avoiding meddling with matters that I was not called upon to meddle with,
patiently enduring such opposition as I might have to meet with,
in a faithful discharge of apprehended duty,
the sure Rock of defence would be a shelter for me in every storm.

Sixth-day, wind favourable: we have been out at sea only ten days,
and it is supposed we have made at least one-third of our passage.

Seventh-day, 12th of eighth month.
Weather continues very fine; our passengers generally in good health.
I often crave Divine support, to be preserved keeping my proper place among them;
especially as way appeared to be opened in their minds,
to receive any thing and everything I may have to offer,
whether by way of counsel or reproof, they also showed me every mark of respect,
when I have felt it required of me to give a suitable hint,
that their conduct has not quite savoured of a Christian spirit.
About noon, we hailed an English brig, bound for Liverpool.
It appeared we had been now eleven days from our moorings,
and sailed thirteen hundred miles.
I have been permitted for a short time this day,
to have my mind occupied in thinking on my dear wife and family;
but I find it will not be profitable for me to indulge much in this way, and considering,
as my great Master well knows,
that an over-anxious disposition of mind is one of my very weak sides, I esteem it,
I hope, a favour, that his restraining hand is laid upon me.
May I continue resigned to every one of his dispensations,
however opposed to human nature.
I cannot help looking forward with some degree of thoughtfulness towards tomorrow,
accompanied with earnest breathings towards the Lord,
that he would preserve me in my proper place among our ship`'s company.

First-day, the wind a-head this morning, which occasions our being on the tack.
The motion of the vessel is very trying to the passengers,
which led me to fear our intended sitting together this morning, would be prevented;
but when the time appointed came,
I requested our kind captain to promote our being called together,
which he appeared cheerfully to do; we mustered pretty strong,
considering the change that had taken place in the motion of our vessel;
some of our company today being much indisposed.
When all were seated, a suitable pause took place,
and a few chapters out of the New Testament were
read by different individuals of our company;
after which we again sat in quiet.
Matter arose in my mind for communication; but,
from the indisposition I was labouring under, owing to the motion of the vessel,
I feared the probability of my being able to acquit myself to any advantage to our company,
which caused much hesitation in my own mind;
yet I felt a dread of the consequences of withholding,
not doubting but that inward poverty would be the result; but after a struggle,
I was favoured with strength to yield to apprehended duty.
The evening closed with reading, as before, all retiring quietly to bed at an early hour.

Second-day, the wind still a-head,
and from the constant uncomfortable motion of the vessel, many of my fellow-passengers,
as well as myself, feel much exhausted.

Third-day, 15th. The wind yet a-head, a fresh call for the exercise of patience:
may I be preserved from manifesting any thing even like
a contrary disposition before my fellow-passengers,
is what I desire of the Lord my God.

Fourth-day morning, after a sleepless night, owing to our frequent tacking,
and the rolling of the vessel, I went on deck, and found, by inquiry,
we had made but little way during the night, the wind still continuing a-head.
By endeavouring to keep in the quiet, under our present trying situation,
I was favoured to attain to that state of mind, in which I thought I could truly say,
I had not the least desire to be anywhere than where I now actually am.
Although for the first eleven days we had made more than one-third of our passage,
for the last five days we have been continually on the tack,
and made but very little way.
Among such a company, I found it difficult to come at a secure spot for retirement;
I shifted from place to place, above and below deck, but in vain,
until I took my seat behind the mast of the forecastle.
Some of my omissions on shore found me out,
in this the most secluded spot I could come at,
and I dared not do otherwise than allow them to have their full scope in my mind.
Although my thus giving place to the painful remembrance
of them occasioned some very deep-felt secret sighs,
yet I was led to view it as a mark of Divine mercy and regard,
thus to bring before the view of my mind my short-comings,
in order that I may take warning thereby in my future moving along;
and more especially so,
in that I thought I was favoured with the evidence
that my disobedience did not lie against me as wilful.
This proved a season of renewing covenant;
and earnest were the breathings of my exercised soul, that through adorable help,
which I was led to believe would, from time to time, be offered for my acceptance,
faithfulness might so mark all my footsteps on the American shore,
as that I might be preserved from adding to that catalogue of omissions, which, at times,
rise up in my mind and reproach me.

Fifth-day morning: we have passed a very blowing night, with the wind still a-head,
the ocean greatly agitated; many of us much indisposed in consequence.
A day of as great exercise of faith and patience as most I have known;
a day of frequent renewing of covenant--a day in
which my mind has been brought to a willingness,
I humbly hope in godly sincerity, to say to my great Almighty Benefactor and Preserver,
"`I am willing to go anywhere, and to any one, you may be pleased to send me,
and through the continuance of your holy aid, to deliver your whole counsel,
be it whatsoever it may.`"
The prospect I have had for many years, of making a religious visit to New South Wales,
glancing afresh before the view of my mind, occasioned some deep heart-felt sighs;
that if it should continue to be a Divine requiring,
my great Master would not leave nor forsake me,
until a cheerful resignation was brought about,
to yield in this and every other matter of duty.

Sixth-day morning; going on deck,
the captain reported that we were now pursuing our
right course at the rate of five knots an hour,
which was cheering to our minds: expectations were held out,
of reaching soundings on the banks of Newfoundland by twelve o`'clock tonight,
if we continued this course; but at sunset the wind very much abated,
and we had a very trying night from the rolling of the vessel: I passed a sleepless one.
A calm came on, and from the increased rolling of our vessel,
I was obliged to take my position at full length on the deck.
During the stretching of my weary body on this hard bed,
my mind was led to contemplate the unbounded power of the great Ruler of the universe;
that the sovereign on his throne, has no more place with Him,
than the beggar on the dunghill,
but as it becomes the sovereign`'s chief care and concern to be found
walking in that way which is well pleasing unto his great Creator,
by whom he, as well as the meanest of his subjects, will be judged in a future day,
for the deeds done in the body.
These considerations led me afresh into near sympathy with my dear sovereign,
surrounded as he is by temptations, and by those called his friends; who,
there is reason to fear, will prove the worst of enemies--flatterers,
a description of persons who surround those in power:
and my soul was led to crave for him that help, which alone can enable him,
now in his advanced life, to choose the Lord for his portion;
and thereby secure for himself that celestial crown designed for him.

Seventh-day morning.
O, holy Father! keep me in the hollow of your Divine hand this day; that so,
through my good example to the multitude enclosed with me by these wooden walls,
who appear watching my movements, your great name may be glorified,
and inquiry begotten after the more acceptable way of serving you, our God.

First-day morning.
The little wind we have is still a-head:
a degree of solicitude accompanies my mind this morning,
that quietness as a canopy may cover our minds,
and that nothing on my part may be promotive of the contrary.
At the time proposed, we collected together pretty generally; and after all were seated,
and a pause had taken place, one of our company commenced reading:
when the reading closed, a pause took place again, and we separated much in quiet.
After which, accompanied by some of my fellow-passengers, we proceeded to the forecastle,
and collected such of the steerage-passengers and
men as were at liberty to give us their company:
after reading to them, a pause took place; feeling, as I apprehended,
my mind charged with something for communication,
that which I had to offer appeared to be well received.
In the evening, on my proposing to our kind captain that we should read,
he ordered the round-house to be lighted up,
and a pretty general assembling of our company took place: reading commenced,
and the evening closed quietly,
and in a manner becoming the occasion for which the day was set apart;
each retired early to bed.

Second-day morning: after passing a comfortable night, I went on deck,
and found the wind was still a-head of us; yet, through adorable mercy, which,
I was favoured renewedly to experience is watching over me,
guarding me on the right hand and on the left,
I was preserved both from being over-elated when we were making speed on our passage,
and from being cast down when we were tossed to and fro by the mighty billows,
which roll one after another against the sides of our vessel,
making little or no way on our passage.
Nor had I the shadow of a desire this morning to be anywhere but where I now am;
feeling truly thankful, as I humbly hope has been the case, that I have been enabled,
in my conduct and conversation among our ship`'s company,
to set an example of quiet submission to this,
as well as every other dispensation of Divine wisdom.
He deals with us, his unworthy creatures, as a tender father;
when he permits our worldly undertakings to be prosperous,
or all our fairest prospects to be blasted, whether gradually, or as in a moment,
when the destroyer is allowed to enter our borders,--yet all is in mercy,
unmerited mercy.
A small part of our company sat longer than usual after dinner, over their wine,
which threatened to produce a disposition to disturb
the quiet of the rest of the company on board:
such a circumstance not having before occurred, I proceeded to the cabin, and in a kind,
persuasive way, entreated them to quit their bottles and glasses,
and give us their company on deck, with which, in a short time,
they appeared pleasantly to comply.

While I was sitting in the round-house this evening,
part of our company came in one after another, and taking their seats,
soon began to sing; on which I arose to retire, which being observed by them,
they proposed to desist if I wished them, rather than offend me:
but as I did not feel that which would have warranted such a request on my part,
never having heard, since coming on board the vessel,
any thing escape any of their lips in this way that was indecent or immoral,
I left the round-house.
I felt satisfied with proceeding as I had thus done,
aware that if we are favoured to preserve that place in the minds of our fellow-passengers,
so that a word of caution, counsel, or reproof is well received,
we must not expect more from them than would be consistent with their education,
manner of bringing up, natural disposition, and advancement, if they had known any,
in religion.

Third-day morning: the wind continued a-head:
we sailed for awhile with a prospect of a short passage;
but how it may fare with us is uncertain:
we have no power to help ourselves on this trackless ocean;
it is enough to be favoured to know our minds preserved in stability,
and to be able to say in sincerity of soul unto Him, who when he commands is obeyed,
whether it be a storm or a calm, a wind favourable to our prospects of things,
or opposed thereto, "`Your will be done.`"
This being the state of my mind, I humbly hope, as I am not able of myself to come to it,
I feel truly thankful for the favour.

Fourth-day: the wind a little changed in our favour:
but towards noon it turned a-head again.
We have not, as yet, reached the banks of Newfoundland,
so little way have we made for the last twelve days.
The weather continues to be very fine, which is a great favour for us passengers,
both in the cabin and in the steerage; for the state of the air being very oppressive,
we must have suffered much,
if we could not have remained on deck until we retired to rest; notwithstanding which,
I found it hard work at times to bear up against the dizziness in my head,
and uncomfortable sensation in my stomach, as well as those misgivings inwardly,
which often arose before the view of my mind; which if I had given way to,
might have proved the means of my losing hold of the anchor of hope and shield of faith.

Sixth-day morning; the wind still a-head of us: this proved a trying day to me,
from the misgivings I had to combat with,
when considering the small space between us and eternity,
and that the starting of one of the planks of our vessel,
in all probability would inevitably soon send us to the bottom of the mighty deep.
However,
by endeavouring after that help that has never yet failed me in seasons like these,
I was enabled to lay hold of it when bed-time came,
and lie down in full confidence no harm would befall us.

A fair wind sprung up, and we are going seven knots an hour,
advancing now towards the banks of Newfoundland.
Our ship`'s company appeared much cheered with the prospect before us;
yet I could not but regret,
that instead of a quiet feeling of gratitude to the great Author of all good,
for this change that had taken place in our circumstances,
a disposition towards levity prevailed with some of our ship`'s company.
First-day now fast approaching again; I look towards it with earnest desires,
that nothing may be found lacking on my part towards
promoting the proper observance of it.

First-day morning, the vessel rolled so much in the night, that I had but little rest,
yet the wind continues fair for us.
Although it is supposed we are two hundred and fifty miles from land, yet a small bird,
resembling our yellow-hammer in England, settled on our rigging.
We also had a sight of some whales at a distance,
one of vast size first throwing his head and shoulders out of the water,
and then his tail and the other part of his body, spouting at a tremendous rate.
It might have been gratifying to have had a nearer view of him, yet,
considering what an enemy he might have proved by a nearer approach,
I was better satisfied that our distance kept as it did.

We held our meeting as usual, and were favoured with a solid, and, I hope, to some,
a profitable time.
I was comforted, when the time of silence took place,
to observe the quiet that continued over us, and the disposition manifested to remain so,
until it appeared right for us to separate.
At the time of our meeting breaking up, a fishing-vessel appeared in sight, at anchor;
our captain made towards her, and put out our long-boat:
the mate and a few of the passengers went on board,
in hopes of being able to procure some fresh fish, but found, on their arrival,
all their last week`'s catching was salted down;
yet they were willing to allow our company the use of their baits, hooks and lines,
for the purpose of a supply for their present needs, which privilege they embraced,
and in a short time they returned again to the vessel, with forty-nine fine cod-fish;
some, it was supposed, weighed thirty pounds each.
Although I could not be a partaker of them myself, yet I felt a secret pleasure,
not easily to be described, on account of the steerage-passengers,
who were to partake of this feast, which the mighty deep had afforded,
and who had been living much on their salt provision.
This fishing excursion occurring on the breaking up of our meeting in the cabin,
the minds of the steerage-passengers appeared too unsettled
to be likely to take any interest in our reading to them,
as heretofore, and therefore it was not attempted; but on inquiry,
it was thought seven o`'clock in the evening might be a
suitable time to call them together for that purpose.

When the time came, some of the cabin-passengers, who had given up to read to them,
failed not to remind me of it, and we assembled accordingly.
At first I felt discouraged,
from a fear we should not have been able to come at that quiet which is so desirable.
An Irishman, a steerage-passenger, became quarrelsome;
but he was prevailed upon to be quiet,
while one of our company was reading from the sacred pages;
which contain matter suited to all states and conditions of mankind.
Wounded and bruised as we may have become, through yielding to the world, the flesh,
or the devil, or to all of them, yet we shall find, as we peruse these Sacred Writings,
with minds rightly directed to the great Author of them,
that they will not fail to bring us to the spot where a sovereign remedy will be found;
and if we are but willing to have it applied to the full,
and our wounds searched to the very bottom, soundness of religious principle,
accompanied by soundness of conduct and conversation, will be brought about.
Seated on the forecastle, with the vast expanse of the mighty ocean before me,
its agitated state, the sea running very high,
the rolling motion of the vessel through the great foaming waves,
together with the occasion we were then assembled about,
introduced my mind into very awful feelings.
The fishing excursion had rather an unsettling effect on some of our cabin-passengers,
and I felt discouraged as to the probability of reading to profit,
before we retired to rest; yet I did not feel satisfied to omit proposing it, which,
when done, appeared to be cordially united with;
we therefore pretty generally assembled in the round-house,
and very soon quietly settled down.
After the reading closed, during which a good degree of attention was manifested,
I ventured, as ability was afforded, to plead the cause of truth and righteousness.
A good degree of solemnity continued during a considerable
pause that took place before we separated;
after which, as we were rising from our seats,
a young man manifested a disposition to excite levity in the minds of
two young women who had conducted themselves orderly during our sitting,
proposing their singing a psalm or a hymn with him.
From the light, airy disposition, which evidently prevailed in his mind,
I found myself called upon to interfere.
I told him if he would sing a psalm or a hymn,
in such a serious disposition of mind as was well suited to the occasion,
he must be left to his liberty so to do; but that,
if he attempted it in the light airy disposition of mind he was then in,
it was my belief it would be nothing short of offering an insult to the Divine Being;
and that sacred things were not to be thus trifled with.
He thanked me for my observations, and there the matter ended.
I was favoured to retire to rest peacefully, and with contentedness of mind; counting it,
I hope, a mercy to be spared from the anxiety,
which seemed to accompany the minds of some of my fellow travellers to reach New York.

Second-day morning, the wind was favourable,
which was a cheering prospect to our ship`'s company, in which I also was a partaker,
accompanied with feelings of gratitude that the weather
continued so favourable for our being on deck,
and that health prevailed throughout the whole ship`'s company.
The state of the air has greatly changed to cold, since coming to, and while we were on,
the banks of Newfoundland.
We observed a whale sporting about this day, which somewhat varied the scene;
we rarely have had a vessel in sight.

Third-day, I passed a very trying night, from the constant motion of the vessel;
towards morning, the wind sunk nearly to a calm,
yet we are making some way towards our port.
The weather again became very oppressive,
and I could hardly keep on deck until our awning was put up.
A large waterspout appeared in sight this morning;
our distance from it was supposed to be about six miles;
it was very visible to the naked eye: a great number of porpoises sporting about,
enlivened the dreary sameness of the ocean.
The heat was very oppressive,--the thermometer being at eighty degrees in the shade.

Fourth-day morning, the wind tacked about, yet pretty much in our favour,
and the weather rather moderated from a pleasant breeze springing up.
New South Wales has been uppermost with me part of this day,
should it be required of me to make the sacrifice;
the prospect of the length of the voyage, and the detention I might experience,
my advanced age, and the parting from my dear wife,
never more to see her again in this world, have bowed me as into the very dust;
until I was enabled to address my great Almighty Master in the language of,
"`I am resigned to go any where; only draw me by your Spirit and power,
and make me willing to run after you.`"
This state of true resignation, to what may be the future requirings of my Divine Master,
being attained, I was favoured to rise again as out of the deeps,
and to enjoy the social company and conversation of my fellow-passengers,
which previously I had no capacity for.

Fifth-day morning, the wind again a-head.
I have been led to view the quiet retreat I left at Highbury, near Flitchin,
and contrast it with my present situation,
enclosed in such a small space on the mighty ocean,
amidst a numerous company of individuals, who before I came on board the vessel,
were strangers to me,--the vessel rolling to and fro,
with hardly a quiet corner to be found suitable for reflection,--also
a frequent pain in my head with dizziness;--yet not a desire is
permitted to overpower my mind to be anywhere than where I am.
Surely this must be the Lord`'s doing;
and how can it be otherwise than marvellous in mine eyes, inasmuch as, by nature,
I have an utter aversion to being on the water,
and am a bundle of impatience and anxiety: may I never forfeit his favours,
but be found willing to devote the remainder of my days,
to the work and service my great and good Master may see fit to call me to,
is the prayer of my soul.
We made but little way today; the wind more fair towards evening.

Sixth-day morning, 1st of ninth month, 1826.
Almost a calm, and yet the motion of the vessel, from the disturbed state of the ocean,
caused some of us to feel very unwell.
Our captain proclaimed us to be about two hundred and fifty miles from New York.

Seventh-day morning, wind fair, running eight knots an hour; hopes are now entertained,
if this wind continues, of reaching New York by third-day next.

First-day morning; wind fair, making our course about four or five knots an hour:
may I be found faithful in our little meeting this day,
should anything be required of me to offer therein.
Our gradually advancing towards our destined port feels animating,
although the testimony in my own mind is, that bonds and afflictions await me there;
yet these feelings are accompanied with the assurance,
"`I the Lord will be with you;`" He never yet deceived or disappointed any,
whose reliance is firmly established on him for help
and protection in every needful time.
I sighed however,
and cried for preservation amidst the dangers that
I felt awaited me on the shores of North America.
At the usual time this morning, we assembled in the round-house: after all were seated,
and a suitable pause had taken place,
which from our first commencement I had recommended,
both previous to our reading and after it closed, several chapters were read;
during which, I thought the great Master fulfilled his gracious promise,
of being in the midst of us: we separated under feelings of holy solemnity,
which nothing of the creaturely part can possibly produce.
The weather was very fine; the serenity that covered the wide expanse of ocean before us,
to a mind capable of meditating on the wonderful works of an Almighty Power,
cannot but occasion feelings of awful wonder and astonishment.

A few days past we were riding on the proud waves, tossed to and fro, here and there,
at their pleasure;
today this boisterous unstable element appears comparatively almost without motion:
we keep gliding along towards our port, almost imperceptibly.
In the evening our usual reading took place in the round-house;
it proved a favoured meeting:
the day closed with feelings of reverent gratitude to the Author of all our mercies,
who has been pleased to be with me from time to time,
since traversing this watery element, surrounded by such a variety of individuals,
of different dispositions and religious professions;
and who has strengthened me to support our various testimonies, I humbly hope I may say,
in a good degree of faithfulness.

Second-day morning: going our right course:
we began to feel something of the breezes of the land,
by which the painful sensations in my head and stomach were abated;
the weather was fine and serene, and our vessel going about six knots an hour, which,
with the prospect of being likely soon to see New York,
occasioned cheerfulness on all countenances.
Although the prospect of hastening to port proclaims relief to my poor, frail tabernacle,
yet it also proclaims thraldom and captivity to my spirit.

Third-day morning; a brisk, fair wind, but on account of the great swell of the ocean,
we find it hard work to keep upon our feet or on our seats.
I have been enabled, on looking towards the time of my landing on the American shore,
to crave that obedience to every clear manifestation of duty may mark all my footsteps,
and the whole counsel of my great Master given me to communicate,
whether in the assemblies of the people, or privately to individuals,
be faithfully imparted; and also, that if opposition in any way be my lot,
while travelling on the shores of North America,
I may be favoured to live so near to the great Preserver of men,
as to be kept from opposing again in my own spirit; but if a reply be warranted,
that it may be done in the spirit of love and meekness; or if silence is to be observed,
that my lips may be sealed by that Almighty Power, who best knows when we should speak,
and when we should keep silence; and to whom alone must the event be left.
Made soundings again this afternoon in thirty-two fathoms;
and the colour of the water is much changed in a very short time.

Fourth-day morning; when I went on deck, the wind was again a-head:
the effect of this disappointment was evident in the countenances of many of our company;
but my mind, through the extension of Divine help,
is preserved in quiet submission to our present detention;
although hopes were awakened last evening,
that we should have seen Long Island before sunset.
This detention afforded me an opportunity of taking a retrospect
of my conduct among my fellow-passengers and our ship`'s company,
how far I had been endeavouring to keep my proper station among them;
as a kind Providence had given me considerable place
in the minds of most if not all on board.
After some very heavy rain, with thunder and lightning,
the wind towards noon became more fair.

Fifth-day morning, 7th of ninth month; the wind changed in our favour,
and we sailed at about ten knots an hour;
cheerfulness resumed its place on each countenance:
expectations were now held out that we should be abreast of Long Island by afternoon;
and at noon one of our crew went aloft,
and shouted "`land in sight,`" which we were not able to discern;
but in a short time after, a small spot of land became visible to the naked eye on deck.
Upon this cheering prospect, all hands began to prepare to reach the shore,
as it was now expected we should land at New York by night.
At two o`'clock a pilot came on board,
by whom we learned that health prevailed in the city; but, to our great disappointment,
for I felt I had a share in it, he informed us,
we should not be able to reach New York with this tide,
but must wait the tide tomorrow morning.
Some of our passengers proposed, when we threw out our anchor, to take to the pilot-boat,
and go on shore in her;
but it was necessary that the quarantine physician should attend on board the packet,
to ascertain the health of our ship`'s company, the proposal was abandoned.
We now had the land on both sides,
and the sweet and refreshing land breezes cheered not only our spirits,
but even our poor cow, whose eyes had appeared dim during the passage,
and whose voice I had not heard before,
put her head out of her crib and lowed in a most animating manner, with her ears forward,
her eyes sparkling, and sniffling up the air of the land,
as if rejoicing with us at the prospect of once more
setting her foot on some green pasture.

We reached the quarantine vessel about six o`'clock in the evening,
the physician stationed in her came on board our packet,
and soon set us all at liberty to go on shore.
A steam-boat, lying off Staten Island, was hailed, which soon reached us,
and the cabin-passengers with myself went on board her.
Although I apprehended my friends in New York were apprised of my coming in the Pacific,
yet as the packet could not get up this tide,
they would not be likely to expect my arrival tonight, which was fast coming on.
Having no recollection of the name of the street where Elizabeth Bowne,
the Friend with whom I intended to take up my abode, resided,
I began to fear I had taken a wrong step,
by not remaining on board the packet another night; but a person in the steam-boat,
I suppose, observing me to be a stranger, kindly inquired of me my place of destination,
offering his services to assist me in finding my quarters.
On informing him whose house I was bound for,
I found he had no knowledge where the residence of Elizabeth Bowne was,
but kindly proposed to take me to a friend of his,
and a member of our own religious Society, who, he said,
would conduct me safely to my quarters.
I felt my mind relieved on this subject, and found fresh cause for thankfulness,
as it was dark when we landed.
I was taken to the house of my ever afterwards kind friend William F. Mott,
who proposed I should take up my abode with them;
but as I was led to believe the pointings of best Wisdom, before I left my own home,
had been to take up my abode under the roof of Elizabeth Bowne, I felt most easy,
although late in the evening, to proceed to her residence,
and see if she was able to accommodate me without difficulty
to herself. I found an open door in her mind,
and that of her very kind widowed daughter, for my accommodation.
I anticipated the pleasure of a night`'s rest on shore; but, alas, was disappointed;
although everything had been done to add to my comfort in this respect,
I was not able to come at any sleep the night through:
like the miller who could not sleep unless the mill was at work, so I could not sleep,
from missing the rocking and motion I had been accustomed to on ship-board,
and I had to pass another such night before I was
able to recover my usual habit of sleep on shore.
