== Chapter XXXII.

Second-day morning, 30th of tenth month, 1826:
I left the hospitable abode of Elizabeth Bowne,
accompanied by my esteemed friend Henry Hull,
in order to attend Purchase Quarterly Meeting;
and reached Richard and Abigail Mott`'s before it was dark.
Third-day, we attended the Select Quarterly Meeting, which was small,
a time in which we were favoured to witness the wing of Divine regard stretched over us,
contriting some of our spirits;
for which favour the meeting appeared to separate under
feelings of reverent gratitude and thankfulness to Him,
who sits on the throne, and the Lamb immaculate, only worthy of all adoration and praise,
world without end.

The next day the Quarterly Meeting for church affairs commenced,
and the meeting for worship previous to entering upon the
business was very largely attended by men and women Friends.
I doubt not to some it proved a time of close exercise and travail,
that the Truth might have dominion over that spirit which
was secretly at work in the minds of several of the members,
to divide in Jacob, and scatter in Israel.
The meeting for discipline then proceeding with its business,
the queries were answered from the different Monthly Meetings, in a summary way.
I found, if peace of mind was to be my portion as I passed along,
however it might be in the cross to the creaturely part,
there was no other way to come at it but by simple obedience.
I therefore ventured to cast before Friends the loss which I believed they were sustaining,
by this summary way in which the answers were brought up
to the Quarterly Meeting from some of the Monthly Meetings;
thus depriving themselves of that help from the Quarterly Meeting,
which otherwise they might receive by clear, explicit answers.
It appeared to me,
there was reason to fear the discipline in some of the Monthly
Meetings was handled in a superficial manner;
and by keeping under my exercise, strength was afforded me, I hope I may say,
in the wisdom of Truth,
to point out the means whereby they might be enabled to apply a remedy.
Many solid Friends expressed their concurrence with my concern
on the various subjects I had alluded to,
and their thankfulness that I had been strengthened thus to labour among them.

Fifth-day morning, the parting meeting for worship was held:
soon after I had taken my seat, I was brought under exercise,
as I apprehended for religious service;
but before it appeared to me that the time was fully come to stand upon my feet,
a stranger to me expressed a very few words,
but so fully comporting with the opening my mind had been occupied with,
that I felt myself brought under a very great strait.
My exercise continued, and yet I hesitated to stand up,
lest the individual who had broken the silence of the meeting
should be in league with that disaffected part of the body,
which had been gaining ground in this Quarterly Meeting.
My faith was very closely proved: I hesitated to move with the opening,
lest I should be instrumental in feeding that,
which my friends might think needed starving, and yet I knew not how to keep silence.
But through patience and perseverance in endeavouring
to come at the mind and will of my Divine Master,
strength was given me to rise, and help administered to acquit myself, I believe,
to the satisfaction of my friends.
On inquiry, I found my fears relative to the Friend who broke silence in the meeting,
were without foundation: after the meeting closed,
I humbly hope I may say my heart overflowed with
feelings of gratitude to that Divine Power,
who had not allowed me to fall a prey to that evil one,
who is watching his opportunities, if possible, to frustrate the Lord`'s work.
We proceeded to Esther Griffin`'s to take our dinner: my expected companion, Samuel Wood,
had not arrived, but my mind was preserved calm and quiet,
which I considered a great favour, and a state I had no power to command.

Henry Hull intending to proceed to Peek`'s-kill,
and the way opening in my mind to accompany him there,
we moved forward to James Brown`'s,
who afterwards kindly offered to be my companion to Nine Partners`' Quarterly Meeting;
Henry Hull then left me and returned home.
About six o`'clock this evening Samuel Wood arrived at my quarters,
for which I felt thankful,
his Monthly Meeting having furnished him with an unlimited minute to attend me:
what can I say, but that it is the Lord`'s doing,
and can it be otherwise than marvellous in mine eyes.

The next morning, Samuel Wood, James Brown, and myself left Peek`'s-kill for Poughkeepsie.
At Fish-kill we halted to give our horses a bait.
While sitting in the hotel a funeral passed the window attended only by persons of colour,
which excited remarks from some company who were in the room with us,
rather of a contemptuous nature.
The behaviour of the mourners appearing to be becoming the occasion,
awakened in my mind a degree of sympathy towards this degraded part of our fellow creatures,
accompanied by a willingness to join them to the place of interment;
but as we were circumstanced,
having barely enough time to reach our place of destination before it would be dark,
and not knowing the course they were taking, I kept my feelings to myself.

We proceeded on our journey, and to my agreeable surprise,
after we had left Fish-kill about one mile,
I thought I observed the carriages standing that had passed our hotel with the funeral.
My companions proposed our halting, when we came to the place of burial,
which we accordingly did: Samuel Wood accompanying me,
we proceeded into the burial-ground; the body had been deposited,
and the last sod was then being laid on the grave,
and some of the company had already quitted the grave-side.
I requested the company to be called together again, which they seemed to do willingly;
a solemn quiet ensued,
and that which I had to offer appeared to have a humbling effect on many of their minds:
the quietness they manifested, and the weight over many of their countenances,
encouraged me to believe this act of dedication, which I had been strengthened to make,
was received with feelings of gratitude on the part of the burial company.
We were favoured to reach the residence of my countryman, Thomas Smarts, at Poughkeepsie,
before the day-light had quite disappeared.

First-day morning, attended the usual meeting at Poughkeepsie, which was large,
several of the town`'s people being present.
A meeting had been appointed at my request, for members and attenders of meetings,
at Pleasant Valley this afternoon, about the distance of seven miles;
which was largely attended.

We took up our abode for the night with Silas Downing, who, with his attentive wife,
amply cared for all our needs.

Second-day morning, 6th of eleventh month, we proceeded on our journey to Nine Partners,
and took up our quarters at Friends`' school,
and were kindly cared for by the superintendents, Asa Upton and his wife.
The Select Quarterly Meeting beginning at eleven o`'clock this morning,
I found myself encircled by a goodly company, as far as external appearances went,
which led me to hope,
if the inside of the cups and platters were in accordance
with the plainness and simplicity of the outside,
we should be favoured with a precious meeting together, and have to declare,
as in the beginning of our religious Society,
the glory of the Lord so filled the house of each of our hearts,
that there was no occasion for the ministers to minister.
Alas!
I had no such glad tidings to proclaim,
but to warn some present against that spirit of disaffection,
which was secretly at work in the hearts of many
of the disobedient members of our religious Society,
sapping the foundation of true religion and righteousness,
which aforetime they had been favoured in some degree to experience.

The next morning, Friends assembled to transact the affairs of Society:
the meeting for worship was large;
we were early favoured to settle down in outward quiet,
and the calming influence of the Spirit of Truth prevailed,
to the gathering of the minds of many to that true place of waiting,
where the voice of the Divine Counsellor is clearly understood.
The time of our sitting together was laborious to me,
being fearful to break in upon the precious quiet that was over the meeting:
but keeping in the patience, strength was mercifully given,
whereby I was enabled not only to obtain relief to my own mind,
but to afford relief to the honest-hearted members of the meeting.

In the evening I felt my mind drawn to have a religious
opportunity with the children of the school,
of which there is a considerable number.
It is the practice among Friends on this continent, in farming districts,
to have their children at home for the summer six months;
partly in consequence of the difficulty they are
under to hire labourers in the summer season,
and partly because some of those masters,
who undertake to teach school in country places, only engage for the winter half-year:
thus many of both sexes are kept at school to an age when the youth
in Great Britain have nearly finished their apprenticeship.
I proposed to the superintendent and my companions, to have a sitting with the children;
the scholars were collected accordingly, and I hope the time was not unprofitably passed.
I believe it will not be well to omit the following observations made
to me by a Friend in the station of elder in this Quarterly Meeting,
hoping they may prove a strength to some, and caution to others.
"`Some soldiers appear valiant by the fireside,
but when they are brought into the field of battle, they manifest great cowardice:
we have too many of these fireside valiants, who have done harm among us,
by conversing boldly by their firesides on the declension
which has taken place in our Society,
but have not been bold enough to declare, as they should have done,
their sentiments in our meetings,
which is the right place for them to relieve themselves.`"

Fourth-day morning, the closing meeting commenced, which was largely attended;
some few not in profession with Friends gave us their company:
much religious labour fell to the lot of others, until near the close of the meeting,
when my mind became charged with a little legacy to leave behind me,
but which from a fear of dissipating the precious covering that was over the meeting,
by making unnecessary additions, I had nearly taken away with me:
but venturing on my feet in that faith which ever did and
ever will give the victory over carnal reasoning,
I was favoured to obtain relief,
and the meeting closed under that precious covering which, as a canopy,
had been spread over us.

My companion, Samuel Wood and I rode to Stanford,
and took up our abode with Henry Hull and wife,
from whom we received every marked attention that we could desire.
We the next day attended Stanford Select Quarterly Meeting:
owing to the state of things in this meeting,
and the oppression the living members of it were labouring under,
I had not smooth things to declare,
as I found nothing would lend to my relief but plain
dealing and firmness in my manner of expressing myself,
both on the answers to the queries, and such other subjects as came before the meeting.
The meeting for discipline was large,
several Friends from Purchase and Nine Partners`' Quarters giving their company.
As we intended being at Hudson meeting on first-day morning,
Friends proposed a meeting being appointed for me at Athens on first-day evening,
and one at Coemans on second-day;
but not being able to see my way clear to have a meeting appointed at Athens,
I requested further time to consider of it;
and weighing this subject in the best way I was capable,
I found I must not venture upon such a meeting on my own account.

First-day, on our reaching the meetinghouse at Hudson,
we found the meeting already gathered:
if my feelings respecting this assembly were correct,
it appeared to me but very few of our members were truly awake
to their best and eternal interest;--a more distressing meeting
I had not sat since landing on the shore of the United States.
I felt thankful when it closed,--the retrospect affording a consoling evidence
I had not kept back aught I should have expressed to those assembled:
a dear friend, after meeting, told my companion,
he knew of no meeting of Friends where there was more need
of the doctrine that had been delivered than Hudson.
Hannah Barnard, who made such a schism among Friends in Ireland,
by spreading unsound religious principles in that nation,
was once a member of this meeting.

Second-day morning, we proceeded to Coemans: the horse-boat,
which was to take us across the river, being aground on the other side, we were detained;
and the road we had to travel being up-hill, and full of large stones,
we were not able to make much speed without danger of injuring our carriage;
the time for the meeting was left to the Friends there,
so that we were not acquainted with it.
I became very uncomfortable,
fearing we should not reach the meetinghouse in proper time:
on our getting in sight of it,
we observed the Friends standing about as if the meeting had broken up,
but we reached them before any had gone away except one young woman.
Friends collected around us,
and we informed them of the cause of our not reaching in due time,
and our willingness now to sit down with them; or,
if it appeared to them more desirable that a meeting should be held in the afternoon,
we were quite willing to conform to their wishes: after considering our proposals.

Friends concluded to go into the meetinghouse again, and the meeting soon became settled.
From a sense which I believed I had given me of the
deplorable state of things in this meeting,
with respect to those who are at ease in a bare profession of religion,
as well as of the youth,
it proved a time of sore exercise before I could rise upon my feet;
but by patiently waiting upon the gift,
strength was in due time given to engage in the work which I believed was assigned me.
The terms in which I had to express myself were such, as at times caused me to halt,
before I could utter them.
My hailing was not the effect of doubting what came before me for communication
being in full accordance with the sorrowful state of things,
but from a fear lest some should not be willing to bear what I had to offer,
and leave the meeting; but this did not prove to be the case.
Before we separated,
some Friends acknowledged themselves much satisfied that they had not dispersed,
as well as their unity with what had been offered in the meeting; saying,
there was great need for it, and if the young people were but willing to receive it,
this meeting would prove a blessing to them.
We accompanied Thomas Bedel and wife home, where we took up our quarters for the night.

Accompanied by our kind landlord and his son, we proceeded toward Duanesburg,
in order to attend that Quarterly Meeting:
after travelling about thirty-four miles of very bad road,
and passing over some dangerous, broken wooden bridges,
we reached the house of Isaac Gaige in safety; for which favour, I humbly hope I may say,
feelings of gratitude flowed in my heart to that Almighty Power,
who had watched over and preserved us from harm.

The next morning we attended the Select Quarterly Meeting, which was small.
I endeavoured to be faithful in the labour assigned me among this little company,
and was ready to hope it would not all be in vain.

Fifth-day, 16th of eleventh month, 1826.
The Quarterly Meeting for discipline was held,
which I understood was thinly attended by its members;
both the meeting for worship and that for discipline were to me trying:
at our quarters in the evening we had a comfortable sitting,
and the day closed with the language of "`Return unto your rest, O my soul,
for you have been abundantly cared for;`" and whether the people will hear or forbear,
I thought I was favoured with an evidence that,
by cooperating with that help which was in mercy extended, I should be clear.

The next day a meeting for worship was held,
and many not in profession with our Society gave us their company:
although I believe the command to speak was given me early,
yet I had not courage to obey, until the word became so much as a fire in my bones,
that I dared no longer withhold; my service was to our own members.
After meeting, we rode fourteen miles to Schenectady,
over a very rough road and broken bridges.

Seventh-day morning, we rode to a Friend`'s house at New Town,
who had buried her husband only the preceding day; we found her in a very feeble state,
as to her bodily health, surrounded by many children,
who appeared disposed to endeavour to supply the loss of their father,
by their kindness and attention.

First-day morning, attended New Town meeting, which was small,
and was much hurt by the disorderly manner of gathering.
If my feelings be correct, the life of religion is at a very low ebb among the members;
yet I was comforted in a hope, there was preserved a little remnant,
whose garments had been measurably kept clean,
and that there was a hopeful prospect in some young men.
After meeting, we proceeded to Troy, about fourteen miles,
to attend a meeting appointed in the evening at my request,
for members and such as attend our meetings.
I took my seat in the gallery,
but for awhile I would gladly have been anywhere than where I then was:
but endeavouring after resignation to my present allotment, in such a mixed congregation,
earnest were my cries to Him who hears in secret,
that He would be pleased so to watch over me, that I might keep my right place;
which secret petition, I humbly hope I may say, was mercifully granted,
to the contriting of my spirit, on the retrospect of this evening`'s work.

Second-day morning, we left Troy and rode to Saratoga, and on the following day,
attended the Select Quarterly Meeting: from the answers to the queries.
Gospel order appeared sorrowfully broken in upon;
the prospect of making any remarks was trying to
human nature, from the sense I had given me,
of a high-towering self-exalted disposition, which was uppermost in the minds of some,
who wanted to take the lead in transacting the business of the Society;
but as I waited in patience until the right time was come for me to open my mouth,
strength was given for the labour of this day; not only to the relief of my own mind,
but, if expressions are to be depended upon,
to the comfort of the little remnant of that Quarterly Meeting,
whose garments are not stained by the polluted principles afloat
in the minds of some of the members of this part of the body.

Fourth-day morning, the meeting for worship commenced: several women,
with their young children being present,
and the children becoming rather restless and uneasy,
it was needful for me to aim at having my mind brought into patience,
there appearing no alternative, but that it must be endured,
even by knowing it to be stayed where all that would disturb is subdued,
so that we are mercifully carried above it:
this was the case with our Friends in the beginning,
when the rude rabble came into their meetings with officers and drums to break them up.
The difficulty must be great to some of the parents of these children,
for they must either stay at home themselves,
or bring their children to meeting with them,
not having the means to hire servants to take charge of the children,
or frequently no person to be hired in whom they can fully confide.
I thought I could sympathize with my sisters who were placed under these circumstances,
and bid them God speed, in pursuing their often trying path of duty.
Another practice among Friends in country situations was a greater annoyance to me,
than bringing the infants to meeting, namely, the bringing their dogs with them,
and oftentimes into the meetinghouse;--two or three sometimes are walking
about the house during the whole of the meeting for worship,
and if not in the house,
they are quarrelling and barking on the outside during greater part of the meeting-time:
this not being a matter of necessity, I found myself called upon to protest against it.
The meeting for discipline commenced its business, and it was sorrowfully evident,
from the answers to the queries,
that the enemy of all righteousness had made his inroads into each of the Monthly Meetings:
breaches of love and unity were acknowledged by them all; and,
from the manner in which these deficiencies were passed over by the meeting,
there appeared very little prospect of any good being done at present.
Those who were preserved from the contaminating influence of infidel principles,
which were so evidently at work in the minds of some who placed themselves in the fore-rank,
and were endeavouring, if possible, to bring all to their anti-christian level,
had allowed fear so to take hold of their minds,
that they were robbed of that strength which would have been as
a shield of defence in times of discouragement and dismay.

The next day the concluding meeting for worship was held,
and after dinner Samuel Wood and myself rode to Milton.

Sixth-day, we proceeded towards Mayfield meetinghouse,
intending to be there on first-day.
We found the road very rough and dangerous,
from the snow that had fallen in the night and the frost;
but our greatest difficulty had not as yet come to our knowledge.
At a distance we observed a cloud of smoke in the valley, which we found,
on reaching the bottom of the hill,
was occasioned by a house taking fire very near to a bridge we should have to pass over.
It was then burning,
and those in attendance had laid some of the principal
timbers that were on fire on the bridge,
which obliged us to venture our horses and carriage
down a very rugged descent and through the brook:
although I had full confidence in my companion,
yet the prospect of such an expedient was a trial of my faith.
We made a halt at Galloway, and refreshed ourselves and our horses.
I had a little matter to offer before we proceeded again,
and we had cause to hope our visit was a seasonable one.
A Friend went with us, whose road home was part of our way to our next halting place;
he kindly offered to be guide to the end of this day`'s journey;
but as we understood from him the road we had to take was not difficult to find,
and he gave us such directions as my companion thought were quite sufficient,
we declined his kind offer.
But coming to where three roads met, we were brought into difficulty:
while pondering over our increased difficulties,
we espied some persons in a sleigh coming towards us: this was a cheering circumstance,
and they soon put us on our right road,
so that we reached the house of a Friend in safety, but not before it was nearly dark.

First-day morning, 26th of eleventh month, we had three miles to ride to meeting;
the road was so bad, it was more like being tossed about in a vessel at sea,
than riding in a carriage: the morning being very wet,
the meeting was smaller than usual, and greatly disturbed by late comers-in;
in the evening we had two short religious opportunities.

Second-day morning, the snow had nearly all disappeared,
and as there had been a frost in the night,
the prospect of the journey before us bore a more cheerful aspect:
the day was serene and clear, the sun shone warm,
and our road was on the banks of the Mohawk river;
the lofty mountains clothed with fine towering evergreens,
in many places reaching down nearly to the water`'s edge,
added greatly to the beauty of the scenery; yet the bad roads we had to travel, and,
at times, the precipices near the side of our road, little protected against danger,
were a great take-off from my enjoyment.

Third-day morning, we proceeded on our journey; our prospect appeared discouraging;
A storm of snow coming on, and the road before us bad to travel,
led me to consider the propriety of my movement,
in proposing to make my way to Canada at this season of the year;
but viewing the subject again, as well as I was capable of,
I could see no other way for me but to proceed,
and endeavour to attend the Monthly Meetings in Canada,
before the next half-year`'s meeting.
I therefore concluded, it would tend most to the peace of my own mind,
to try and lose sight of any difficulties that should present
themselves in the prosecution of apprehended duty.
By great exertions we were favoured to reach Utica before it was so dark
as to render it difficult for us to make our way through the town.

We made a few calls upon some of the Friends who reside here,
and who manifested a wish we should have a meeting with them;
but way not opening for it in my mind, we proceeded on our journey towards Bridgewater.

The next morning, 30th of eleventh month, we pursued our journey to Brothertown,
an Indian settlement.
A member of our Society, formerly resided in this settlement,
and his house being occupied by his son, we were bending our course that way,
when we met our intended landlord,
who halted on our informing him what had brought us so far on our way:
he kindly offered to return with us,
and render us every assistance in his power towards the object we had in view,
but which help he told us we had nearly been deprived of, as his road would,
in a few minutes more, have led him off that in which we were travelling.

On reaching his comfortable abode he welcomed us as acceptable guests,
although he did not profess with Friends.
Six o`'clock in the evening being proposed as the
most suitable time for the Indians to be collected,
we were most easy to leave this matter entirely to the judgment of our host.
Having a prospect of a meeting with the Stockbridge Indians the next day,
he kindly sent forward a messenger to fix the time for a meeting with them.
The school-house in Brothertown was the place concluded upon for the meeting,
and it was apprehended from the shortness of the notice, the badness of the roads,
and the probability of the night being dark, that the attendance would not be large.

At the time appointed we proceeded to the school-house the meeting was long in gathering,
but after it was fully gathered, a precious covering was to be felt.
For a considerable time, such was my emptied and stripped state of mind,
that I was tempted to regret I ever had the people called together;
but endeavouring to keep patient under these provings,
a very short simple sentence came weightily before my mind to stand up with,
and by yielding to this little opening, more enlargement was known.
Great quietness was observed through the whole of the meeting.
Our kind landlord informed us, a more orderly meeting had not been known there:
I humbly hope I was not deficient in labouring after feelings of gratitude
for this distinguished token of the continuation of Divine help.
As the Indians came into the school-house, I observed they placed, in an erect manner,
on each side of the fire-place, very long pieces of stick, like wands: this, on inquiry,
I was informed, was light-wood, burning like a torch or link,
which the Indians had provided to conduct them to their own houses again.
After the meeting closed,
we observed those burning sticks moving about in various directions;
the number that assembled being considerable.

At an early hour in the morning we left the abode of our kind friend,
whose care for us every way appeared to have been unremitting;
and were accompanied by a young man, an Indian,
as our guide to the settlement of the Stockbridge Indians.
We had a rough, hilly Indian road to travel,
which occasioned us to be rather behind the time appointed for the meeting;
it was to have been held at Captain Hendrick`'s, an old Indian chief;
but on reaching his habitation,
it appeared he had been suddenly seized in the night with some bodily indisposition,
and his bed was in the room where the meeting was to have been held.
In consequence of this circumstance, we held our meeting at the house of an Indian woman;
she had been partly brought up by a Friend +++[+++in the neighbourhood]
of Philadelphia, but after she grew to woman`'s state,
returned into the settlement of her ancestors, and resumed the Indian dress and manners:
she evidently retained a very grateful remembrance
of the kindness she had received from Friends,
and the obligation she was under to them, for their care of her in early life;
and seemed pleased she had it in her power to accommodate us with a place for the meeting,
and to care for us for the night, for which it appeared she had ample means.

The meeting was small, but it proved satisfactory;
the Indians generally behaved in a solid and attentive manner,
and appeared reluctant to leave us when the meeting closed.
This settlement of the Stockbridge Indians, we understood,
had been of late years greatly reduced,
nearly one thousand one hundred of them having emigrated to the west of this settlement,
near Green Bay,
in order that they might get out of the way of those temptations they found themselves
exposed to by the increase of the white people among them;
choosing rather to endure the deprivations they would
have to meet with in a newly settled country,
for the sake of that quietness and simplicity, which,
from the conversation we had with some, who are now on the wing to take their departure,
they consider to be most consistent with a truly religious life.
They told us they had been to see the spot they were about to emigrate to,
and appeared to rejoice at the prospect of the quiet
they should enjoy with those gone before them.
From the accounts given us, I could not doubt,
that the conduct of the white people towards this artless, and,
unless first provoked to acts of violence, unoffending race of mankind,
had been injurious,
by using every artifice to entice them to drink until they became drunk,
and then taking the advantage of them by getting possession of their lands.
I marvel not at the expressions of Red Jacket, the great chief of the Buffalo Indians,
which, I have been well informed,
was to this effect:--"`Whether the Great Spirit sent the white people among us or not,
I cannot tell; but this I can tell, since they came among us,
they have taught us many bad practices which we never before were acquainted with.`"
A sorrowful tale for a poor uneducated Indian to
tell of any professing the Christian name!

Our kind Indian hostess proposed sending word to Oneida,
of our desire to have a meeting tomorrow with the Indians of that settlement,
which offer we gladly accepted; they also proposed to guide us there,
provided we would take up our quarters at her house until the following day,
which we cheerfully accepted.
The evening was passed over very much to our satisfaction,
part of it occupied with a religious opportunity in her own family,
and hearing her relate some interesting statements,
relative to their progress under the difficulties
which they had been exposed to from time to time,
through the treachery of an agent and missionary,
appointed by the state to care for them, who brought heavy expenses against them,
and then took possession of some of their best land to cover their demands; she added,
"`We want none of their care, we are quite capable of caring for our affairs ourselves.`"
This we were well satisfied was the case with our landlady,
who appeared to possess powers of mind equal to most worldly transactions.

Seventh-day morning, we left this hospitable Indian mansion, a name it fitly deserves,
when compared with most other Indian huts, accompanied by our kind landlady,
her stepfather, and the daughter of the pious old Indian chief, Scannadore,
and proceeded towards Oneida, having nothing but an Indian road to travel on.
In consequence of a heavy fall of snow in the night,
the deep holes which we had to pass being filled up, we could not avoid them,
which made it trying to our horses and ourselves.
In one of these sloughs, our wagon gave such a crack,
that I expected our axletrees were broken,
and that we should be set fast in the middle of it;
my companion`'s courage appeared to serve him better than mine, and with help,
we made our way safely out again.
Having thus passed this slough, I was led to hope the worst was over,
but I soon found we had a river to ford.
This, however, we got over, and came to the school-house,
where the meeting was to have been held, agreeably to appointment the night before;
but it was much after the time fixed, owing to our difficulties in getting along.
There being no gathering at the school-house, as we had expected,
we rode to the house of an Indian family,
to whom the charge of giving notice had been entrusted; when, to our disappointment,
we were told that so far from the notice having been given,
they had been wholly unacquainted with our intention,
and as the weather continued so very stormy and unfavourable for the people collecting,
it would now be in vain to give notice.
Proposals were made to us to remain at Oneida that night,
the family of the house offering to accommodate us;
but my feelings recoiled at the prospect of taking up our abode here,
from the extremely filthy appearance of the inhabitants,
and everything belonging to the house;
and yet I dared not leave the settlement without being willing to do my part,
by submitting to any deprivation of comfort in order to obtain a meeting among them.
Whether our kind hostess, who had conducted us here,
observed any thing in my countenance that bespoke unpleasant feelings,
at the prospect of accepting the proposal of stopping in this family for the night,
or that she felt satisfied herself it was not likely we could be comfortable;
she proposed our going further into the settlement,
and trying to obtain accommodation at the house where the Episcopal preacher lodged,
and which had been the residence of the chief Scannadore;
this proposal I gladly fell in with,
believing we could not possibly be worsted by this attempt.

On our arrival at the house, understanding the preacher was at home,
we applied to him to know if we could be accommodated with a bed,
and such provision as the family afforded, and for our horses;
which being submitted to the family, they engaged,
if we were willing to take things as we found them, to do their best for our comfort;
which to me was a cheering reply, inasmuch as cleanliness, as far as our eyes could see,
was attended to.
The prospect of the comfort we were likely to have in our new abode,
when compared with the Indian house we had last left, was a fresh call for gratitude,
and I humbly hope I was not deficient in an endeavour to labour after it,
and to say in the language of holy David, "`Bless the Lord, O my soul,
and all that is within me bless his holy name,
and forget not all his benefits!`" who had thus made way for us in this wilderness,
among an Indian race, to possess the comforts of which the poor,
frail tabernacle stands in need.
I gladly helped to unload our luggage,
and cheerfully took possession of a seat in our new abode,
manifesting myself to be at home.

Way opening for it in my own mind, at a suitable time,
I informed the preacher of the errand that had brought
us to the settlement of the Oneida Indians,
producing to him my certificate to read; having done which,
he proposed giving up his place of worship and congregation tomorrow to me,
consisting of the Indians of this settlement,
or to read to them the service of the day and not give them a sermon.
On considering both these proposals in the best way I was qualified to do,
it felt most easy to me to accept of the latter,
in doing which we afterwards were led to believe we had done right.
But there appeared one great difficulty to attend
my mind in yielding to this latter proposal,
which I named to my kind friend who had made me this liberal offer, which was,
our sitting among them during the time of their religious performance with our hats on,
feeling, as I did,
a care on my mind to be preserved from willfully hurting
the feelings of those who did not profess with myself.
In reply, he, with apparent cheerfulness, informed us,
he did not wish us to depart in the least degree from our
accustomed manner of acting in our own place of worship;
thus this matter was brought to a close, peacefully to my own mind.
We passed the evening with the young man, the preacher, in his own apartment,
which added much to our comfort.
During our conversation, I found that if I had any thing to communicate tomorrow,
it must be conveyed to them through an Indian interpreter,
and that by our arrangement for the day, we should secure a better attendance,
as they pretty generally attend their place of worship on a first-day.

First-day, at the time appointed,
we proceeded with our friend the preacher to the meeting-place,
a commodious building erected by the state, but at the expense of the Oneida settlement;
the government disposing of so much of their land as covered the charges.
On our arrival,
our friend placed us in two chairs on the platform of what is called the altar,
taking his seat in the reading-desk; the Indians, we were told,
gathered very stragglingly at this time of the year,
when deprived of the rays of the sun to show the correct time of the day,
having scarcely a clock or watch in their possession.
The women assembled with their clean blankets over their heads;
such as had infants had them fastened upon a board, which board,
with the infant thus secured,
is placed in an erect position against the side of their seat;
after which the mother appeared to have no further care.
They manifested a devotedness of soul to that Almighty
Power before whom they professed to be thus assembled,
equal to anything I had before witnessed.
The solidity observable in the countenances of the women, and their whole deportment,
was well worthy of imitation by such as may rank the highest among professing Christians.
This seriousness of deportment was not so manifest among the men,
who took the opposite side of the house to that of the women.
Reading being gone through, our friend requested the interpreter,
who is paid for his services by the state, but at the Indians`' expense ultimately,
to inform the congregation they were not to expect, as heretofore,
a sermon from him that day, as I had desired to hold a meeting among them,
he had therefore given up that time to me which would have been thus occupied;
after which a pause took place.

Feeling my mind entrusted with matter to communicate, when I rose on my feet,
my interpreter prepared himself to fulfill the engagement he had undertaken,
for which I understood he was fully competent;
solid attention appeared to be given to what I had to offer, and I was led to believe,
from the orderly quiet manner in which they separated,
that what had been communicated was understood and was well received by them.
Feeling my mind relieved from further service, I informed our friend to that effect,
on which he immediately gave out a hymn.
I could see no other way for us but quietly to keep our seats,
which we did during the performance of this solemn act,
for so it felt to me to be with many of them;
if my feelings on the occasion were correct, not a doubt remaining in my mind,
although I could not understand a word, it being in the Indian`' language,
but that many of them felt the awful import of the words they uttered.
The women appeared to take the most active part, the melodious sound,
with the frequent gradual rise and fall of their voices,
equalled in melody and solemnity any thing of the
kind which I had before been a witness to.
After the meeting closed, we returned to our lodgings and took our dinner.
I felt well rewarded in my own mind that we had thus pressed
through the various difficulties that had presented,
to obtain a meeting with these Indians.
After dinner, under feelings of near affection,
which we had reason for believing were mutual,
we parted from our kind friend the preacher and the family,
who had every way in their power, I believe, cared for us,
and rode twelve miles towards the settlement of the Onondagua Indians,
and we took up our abode for the night at an inn.

Second-day morning, 4th of twelfth month, 1826, we pursued our journey;
the roads having been so much cut up, with deep holes,
which we could not at times avoid passing through, it made travelling very fatiguing.
About noon we were favoured to reach the house of a member of our Society,
in the Onondagua settlement, who, with his family,
are placed there by the Yearly Meeting of New York,
for the improvement of the Indians of this settlement.
On inquiry,
I found there was but little probability of our having
a meeting with the Indians of this settlement,
the men being mostly gone hunting for deer,
and from the difficulty of procuring an interpreter
who would be fully competent to the task.
We spent three days in the settlement, calling at some of the Indian huts,
and viewing the improvements that had taken place under the care of Friends.
We had frequent visits from the chief,
who is in possession of a large stock of cattle and pigs,
and his farm well cultivated and fenced,
which we observed was very much the case in this settlement,
as far as we went over this beautiful and fruitful valley.
I much regretted our lack of a suitable interpreter,
as it foreclosed our making some inquiries which we might have felt disposed to do,
and which I had no doubt would have produced from
them undisguised and disinterested replies.

The evening before we left the house of our kind friends,
it appeared that it would tend to the relief of my own mind
to request a sitting with the family of the chief,
his grandson, who speaks English,
and such of the Indians who inclined to give us their company.
The chief, his grandson, two men, and seven women attended:
after I had relieved my mind of what came before me, a pause took place,
and the grandson of the chief, in a feeling manner,
endeavoured by little and little to do his best to communicate to his
grandfather and the other Indians the substance of what I had been delivering.
Then the chief, in reply, said it had afforded him great comfort,
that I had been sent across the great water to visit them,
and that he hoped his grandson would remember what had been delivered by me,
and would not return to his old bad ways again,
but keep on more and more improving in his good conduct; adding,
that his mind had been comforted under the feelings he was favoured with,
while I was communicating among them.
The next morning we affectionately parted from them and the kind family,
under whose roof we had been amply cared for.

While in the Onondagua settlement,
desirous of having some correct view of the belief
which the Indians have of God and a future state,
I was informed they were cautious of conversing on these subjects;
but some months after I had visited the settlement, a kind friend there,
by letter furnished me with the following particulars,
which I believe it right for me to give a place in these memoirs,
not doubting their correctness, from what I had previously heard:
"`The Indians`' belief concerning a God is, that there is a great and good Spirit,
who is omnipotent, omniscient, omnipresent, the Creator of everything that is good;
but that he never had anything to do with evil, nor could,
for it is contrary to his nature; that he has not only made man intelligent, but has,
in infinite mercy, given him a portion of his own good Spirit,
to preserve him from all evil, and instruct him in everything that is proper to be done;
that from this source arises man`'s accountability,
and that he will receive a reward in exact proportion to his works, whether good or evil.
They also believe in the immortality of the soul, future rewards and punishments,
and a perpetual judgment seat in the mind,
which is always accusing or justifying us for our conduct;
that heaven is a place inexpressibly delightful,
where the good will live with the Great Spirit eternally: their idea is,
that the passage, or bridge, that leads to this happy place,
is not broader than a hair or the edge of a knife;
yet that there is no difficulty in the good passing it, for angels meet them,
and conduct them over; they also believe,
that beneath this narrow passage there is a dark, horrible pit,
full of every loathsome and tormenting disease, where the wicked are forever punished;
that when the wicked attempt to cross this bridge, there is no help afforded them;
they therefore fall into it, and it is impossible for them to get out again.`"
"`I know this,`" says the Friend, "`to be a correct statement,
having resided several years among them.`"

After leaving the Onondagua settlement, we proceeded to Skaneateles.
During the frost, my foot slipped off the step of our wagon,
whereby I received a considerable wound on my leg, and being exposed to the frosty air,
it became much inflamed; by attention it soon began to mend, which I considered a favour.

First-day, 10th of twelfth month, attended meeting at this place.
The next day was held the Preparative Meeting,
which was attended by a committee under appointment of the Monthly Meeting of Scipio,
to visit the several Preparative Meetings of this Monthly Meeting.
The answers to the queries were brought into the meeting, ready prepared by the overseers.
This practice placed me in a trying situation, inasmuch as,
to make objections to what was brought in by the overseers appeared like doubting
the veracity of the Friends who had prepared the document for the meeting;
and yet I found nothing but faithfulness and plain dealing
would acquit me in the sight of that Divine Being,
who alone was able to sustain through the future trials
that might await me in my wilderness journey through time:
I therefore earnestly besought the Lord for counsel in my movements,
and when that was in mercy clearly unfolded, for his sustaining help,
that faithfulness might mark all my steppings in that meeting.
Before the meeting closed,
vocal acknowledgments of gratitude were made by a Friend of the Monthly Meeting,
for the merciful help that had been dispensed,
during the transacting the weighty matters that came before the meeting.

Third-day morning, we had nine miles to ride to attend Sempronius meeting:
when breakfast had closed,
feeling a call of duty to relieve my mind of an exercise which it had been brought under,
I endeavoured to seek after holy help to discharge this duty:
we parted under feelings of affection for each other,
and were favoured to reach the meetinghouse before the time of Friends`' assembling,
which was cause of thankfulness, considering the badness of our roads.
The Preparative Meeting, being under adjournment to accommodate the visiting committee,
was held here this day:
we here met with a few well-concerned members of our religious Society;
but there was reason to fear, as it respected others,
little more remained with them than a claim to outward membership.
Although my being willing to sit where the people sit,
as it respected the bulk of this meeting, was the way to enter into suffering,
which the creature was ready to recoil at;
yet I was sensible this must be the case with us,
if we labour in the Lord`'s vineyard to the benefit of the people.
After meeting was over, my companion, myself, and the committee,
proceeded towards Salmon creek meeting.

The next morning we attended it;
the state of the Society here was trying to the rightly
exercised members among themselves as well as the visitors;
yet it was pleasant to find a willingness to receive
the close doctrine that was offered among them,
and to observe the apparent love that was manifested towards us at our parting.
After meeting, we proceeded towards Scipio.

Fifth-day morning, attended Scipio Preparative Meeting: the meeting held long,
Friends appearing disposed to go into the state of this meeting
more fully than I at first expected would be the case;
much counsel was imparted through different instruments, I humbly hope,
rightly fitted for the work.
The meeting closed to good satisfaction upon the whole, though unsoundness of principle,
and a disesteem of the Sacred Writings,
which afterwards made such havoc in this Monthly Meeting,
had already a little manifested itself at this time.
After meeting, we rode to Aaron.

Sixth-day, we attended the North-street Preparative Meeting,
where we found a considerable body of goodly-looking Friends,
with whom we had as comfortable a meeting as any that has fallen to our lot,
since coming into this Monthly Meeting; I considered it a favour,
our being thus incorporated with the committee during
our passing through these Monthly Meetings:
after meeting, we rode to Union Springs.

The following day, we attended the Preparative Meeting: here Friends have a commodious,
nearly new-built meetinghouse, beautifully situated in a very retired spot,
with but quite a small number to attend it.
If I had a sense given me of the state of our Society here,
the life of religion was at a very low ebb;
yet it was pleasant to find a disposition on the part of the members
to go further into the state of things than the answers to the
queries brought in by the overseers had done.
Intending to go to Junius meeting tomorrow,
and the distance being too far for us to reach in the morning,
we requested Friends`' assistance in pointing out a suitable stopping-place tonight:
the Seneca Falls was proposed to us,
where we were informed resided a family who were members of our religious Society;
after taking our leave of the committee,
and the kind friends with whom we took up our abode, we pursued our journey to the Falls.

First-day morning, we rode to Junius before breakfast:
here we found a large newly-built meetinghouse,
erected under the expectation of there being a very considerable settlement of Friends,
but after the house was finished,
most of the new settlers emigrated to some of the back settlements;
in consequence of which the meeting was small, as to members of our Society;
a few not in profession with Friends attended;
but the whole of us made a desolate appearance.
The straggling and unseasonable manner of the meeting`'s gathering,
together with the careless posture in which some took and kept their seats,
was cause of much exercise to my mind; the sorrowful tendency of which was felt,
by keeping the meeting for a length of time in a very unsettled state.
I found my peace very much depended on being faithful,
by recurring to these painful circumstances: before we separated,
in fear and trembling I ventured on my feet,
craving of the Lord to keep me faithful to his requiring;
and in the course of what I had to communicate on these disorderly proceedings,
I was led to address some individuals implicated therein,
who were taking an active part in the concerns of the Society,
and to lay before them the loss they were sustaining themselves,
and the danger there was of their example encouraging others in these practices.

After I had been thus engaged, when taking my seat again,
my mind was plunged into great suffering, through a fear which took possession of it,
that I had not had a sufficient warrant for expressing myself as pointedly as I had done,
and that it had been the enemy`'s work to lead me into difficulty:
I would gladly have gone out of the house before the meeting broke up,
to miss remarks which I thought I should not escape hearing.
Before I got clear of the meetinghouse premises, when the meeting broke up,
a goodly-like aged woman Friend came up to me,
giving me her hand in an affectionate manner,
exhorted me with much apparent feeling of mind,
to be faithful in my moving along in the service assigned me among Friends, adding,
with tears,
"`I am one of those you were led so pointedly to address near the close of the meeting,
and I hope your exercise will not be lost upon me.`"
These remarks felt as a cordial to my tried mind, accompanied by feelings of gratitude,
that dismay had not been permitted quite to overwhelm me;
I did not doubt my Divine Master well knew the need
there was for me to pass through this dispensation,
to humble and keep down the creaturely part in me.
