== Chapter XXXIV.

Fourth-day, 7th of third month, 1827, we rode towards Collins meetinghouse,
and took up our abode with our friend Charles Wood.
First-day morning, we proceeded towards Eden, where an indulged meeting is held,
there being about fourteen families and parts of
families who were considered to belong to this meeting.
We had previously been informed, that part of our road lay through a wood;
on entering which, no regular beaten track was to be observed: in some places,
trees which had recently been cut down, were left across the only path we could take;
and no way remained, but to do our best in passing over them,
to the danger of throwing down our horses and breaking our carriage-wheels:
it was with the greatest difficulty I could keep my seat in the wagon.
After our faith and patience had been thus exercised, we were, though cold and fatigued,
favoured to reach in safety the Friend`'s house where the meeting is held.
After taking some refreshment,
we took our seats at meeting with the aged couple belonging to the house,
three other small families, and one individual: it proved a very suffering meeting to me.
I was afresh persuaded, these meetings held in rooms where families live, are not,
generally speaking, productive of much benefit to those who attend them,
especially when so largely attended as this meeting would be,
if Friends belonging to it were rightly engaged in the faithful discharge
of the duty of assembling for the purpose of religious worship.
I left them sorrowing, on account of the deplorably low state of the Society,
and the manner in which the cause was, I feared,
suffering by the continuation of this indulged meeting:
Friends here are much away from the care and oversight
of the well-concerned members of the Monthly Meeting.

Third-day morning, we rode to Orangeville,
where we found another of these indulged meetings of long standing,
with an indulged Preparative Meeting.
The next morning we sat down with an agreeable little company of Friends.
At the close of the meeting for worship, which is held in a private house,
the Preparative Meeting sat. I felt considerable regret,
at the manner in which the meeting appeared to be interrupted for lack of better accommodation.
On mentioning this subject to Friends,
it appeared that ground for building a meetinghouse was provided.
We returned next day to Hamburgh.

Seventh-day, 17th of third month, we rode to Boston,
where there is a small settlement of Friends, and on first-day morning,
attended the usual meeting held at this place, which was small,
but the quietest meeting I have attended since I came on this side the water,
as it respected a timely attendance, and Friends keeping their seats:
it was a season in which I thought we had cause to acknowledge,
that our God had not forgotten to be gracious to us.

Fourth-day, attended their Preparative Meeting, in which the queries were answered,
as in other parts of this Yearly Meeting,
the overseers bringing their answers ready prepared for the meeting`'s use.
I endeavoured to rouse Friends to the necessity there
was for each one to consider for himself,
how far the answers intended for the Monthly Meeting
conveyed a correct view of the state of the meeting,
and if any shortness appeared in any part of the answers,
that those who were aware of it should be faithful in opening it to the meeting.

Fifth-day, attended Hamburgh Preparative Meeting, which was to me a time of suffering,
when the queries were to be answered,
especially that relative to the timely attendance of meetings, and behaviour therein.
I did not dare to allow the answer to pass without making remarks
on the great neglect manifested as to a timely attendance,
and the manner in which the meetings were disturbed by the
young people frequently going to the fire to warm themselves.
My faithfulness opened the way for other Friends to relieve their minds on these subjects,
with which they said they had long been burdened;
this appeared to bring the meeting under considerable exercise and concern,
that if possible these things might be prevented in future,
several Friends expressing a hope that the remarks
which had been made might not be forgotten.
Although suffering was my lot at this time,
yet I thought there was cause for thankfulness on my part.

I felt drawings in my mind to attend an indulged meeting at a place called Holland,
where there is a small settlement of members of our religious Society,
and made a call on an individual in our way,
who is not in membership with any body of professing Christians.
He had published a work, in which he sets forth the religious principles he holds,
professing to be one in principle with Friends,
especially so on the subject of war--he constantly attends our religious meetings,
preaches in them, and holds public meetings up and down;
but yet it appeared the solid part of the meeting were not satisfied with him,
although his demeanour,
dress and address in most respects were consistent with
what a member of our Society should manifest.

On inquiry into the cause of Friends being divided in their sentiments respecting him,
and the ground of dissatisfaction, I found that he had been a soldier in the late war,
and was wounded in battle,
in consequence of which the American government had settled a pension on him for life;
this pension, notwithstanding he had published his avowed principles against war,
it was pretty generally understood, he continued to receive,
but no Friend of the meeting was able to confirm it as a fact.
I could not divest my mind of a fear,--in consequence of the active
part some Friends had taken in the sale of his publication,
and in attending at his public meetings,--also his
appearances in and constant attendance of our meetings,
being allowed to preach in them,
and the countenance he received from some members of the meeting to continue so to do,
that if he really was continuing to receive his pension
from the government for his services during the war,
the reputation of the Society was in danger of suffering.
He received us very kindly: these subjects coming weightily before me,
I had great strugglings of mind, before I could yield to open my mind on them;
but as my desires were earnestly put up to the Lord
for strength to be enabled to divide the word aright,
that so what I had to offer to him might be words that were fitly spoken,
strength was given me to take the first step, by desiring his children to leave the room,
which took place.
As it appeared Friends were divided in their opinions
relative to his receiving his pension,
some professing to believe he did receive it, and others that he did not,
but all was conjecture; I therefore at once put the question to him,
Was not a pension settled upon him by the government of the United States,
in consequence of wounds he received in the field of battle during the late war?
To which he replied, it was the case.
I then queried with him, was he still in the practice of regularly receiving this pension?
He frankly acknowledged, he was.
I then endeavoured to lay before him the inconsistency of such conduct,
with his declared testimony against war in the book he had published and widely circulated.
The only attempt he made to justify his conduct, was by saying,
a sum of money was raised at the close of the war for pensioners,
and to keep up a naval establishment; and as the pensioners died off,
their pension was to go into the naval fund; he continued to receive his pension,
not so much for his own use,
but that the naval resources should not be increased
by his refusing to receive his pension.

As ability was afforded me,
I endeavoured to lay before him the inconsistency of his conduct,
with the doctrines and precepts of Christ,
whose cause he was making such a high profession of, and publicly espousing,
by having people called together and holding meetings with them,
professedly for the purpose of exalting the Redeemer`'s kingdom; and imposing himself,
as he had done, upon Friends, by presuming to preach in their meetings,
while he was in so great a breach of one of their fundamental principles.
I told him, were I in his situation,
until I had strength given me to sacrifice gain received through such an impure channel,
I should not dare to speak in the Lord`'s name, but must keep silence,
and especially so in the meetings of Friends; where his appearances, I was informed,
were very frequent, and at considerable length.
I added,
with respect to his holding meetings with those who
do not profess to have a scruple against war,
I believed that to the thinking part of those who read his work,
and heard him preach "`Christ crucified, to the Jews a stumbling-block,
to the wise Greeks foolishness, but to them that believed on him,
the power of God and the wisdom of God,`" and who were acquainted with his conduct by
continuing to be in the receipt of a reward for his services in the field of battle,
his labours would be null and void.
I told him, however some Friends may have carried themselves towards him,
so as to encourage him to preach in their meetings, yet I believed in the end,
he would find that they had not been his best friends;
but that they would be the cause of his sitting down
short of that experience in the work of righteousness,
which by this time he might have attained to,
had he been faithful to that very precious visitation,
which I could not doubt he had been favoured with.

He received what I had to communicate without any further attempt to palliate matters;
and yet it was evident, that,
although he could not maintain his ground on Christian principles,
upon which he had been at ease, as a warrant for his continuing to receive his pension,
the prospect of his being obliged to sacrifice it brought him into a very great strait;
on which account I hope I was not deficient in a willingness
to sympathise with him,--he having a sickly wife,
a large family of children, and as I was informed, a poor farm to bring them up upon.
I hope I may say, I felt truly thankful to my great and good Master,
in that he had not only given me utterance to the relief of my own mind,
but had also opened a door of entrance into this
person`'s mind to receive what I had to offer;
and I could not but hope,
from the affectionate manner in which he took his leave of us at our parting,
that what had been communicated would be as a nail fastened in a sure place.

On first-day morning we sat with the few Friends of Holland meeting,
in a small log meetinghouse;
part of a committee appointed by the Monthly Meeting to have the care of Friends here,
also gave us their company.
A cheering prospect accompanied my mind,
if the few well-concerned Friends of this meeting are favoured
to keep their places as faithful members of our Society,
there will in time be a gathering as from the highways and hedges.

Third-day, 27th of third month, we rode to Hamburgh,
and attended the Select Meeting there.

Fifth-day, my face was turned towards Clear-creek;
the Indians in the Buffalo settlement came before my mind,
accompanied by a belief I should not be able to leave these parts peacefully,
unless I stood resigned to have a meeting with them on first-day next.
I tried after quietness in order to arrive at some
conclusion before we proceeded on our journey,
but this I was unable to do.
I called upon a Friend,
who I had understood was acquainted with some of those who resided in the settlement,
to whom I felt it best to put some questions on the subject;
and after being favoured to get a little into quiet, so as to be able to turn the fleece,
I found it would be safest for me to have Friends called together; which being done,
I opened my prospect of duty of having a meeting in the
Buffalo settlement with the Indians next first-day;
which being united with,
Friends concluded to do the needful for its accomplishment.

Sixth-day morning, we proceeded to the Monthly Meeting at Clear-creek:
it was well attended, and the business conducted in an agreeable manner.

The next day we proceeded to Hamburgh: on our arrival we were informed,
the Indians in the Buffalo settlement received, with expressions of satisfaction,
the request to have a meeting with them.

First-day morning, 1st of fourth month, 1827,
we proceeded to the council-house of the Buffalo Indians,
where the meeting was to be held;
here we found the head chief of this district and others of the Indians,
who welcomed us cheerfully.
The Indians are very slow in their movements,
and the meeting was not fully gathered until an hour
after the time that had been proposed by themselves.
I was informed that the person engaged as interpreter,
was not in a fit state of mind to undertake such a service.
An Indian man, who spoke the English language, was then proposed to me,
and feeling willing to accept of his services, we took our seats,
the men at the upper end of the house, the women at the lower end.
The chief then stepped forward, and expressed the pleasure it had afforded him,
that so many Friends had given them their company,
and their readiness to hear what I had on my mind for them:
after which he took his seat and a pause took place.
After I had delivered what was given me in commission for them,
the chief again expressed the satisfaction my communication had afforded them.
My mind feeling relieved;
the head chief and his company appeared to part from us very affectionately.
I returned to Hamburgh again, satisfied that I had given up to the service.
We proceeded on our journey, and on fourth-day reached Henrietta,
and attended the meeting held there.
The meeting was small,
and it was a time of close exercise to me to come at a right settlement of mind:
after meeting we rode to Rochester.

Fifth-day, we attended the mid-week meeting here:
such hard things were required of me to deliver to the Friends of this meeting,
that when I had taken my seat,
I was led to call in question all that I had offered among them;
but when the meeting closed,
a Friend informed me there was great need for the remarks I had delivered in that meeting:
time also proved the necessity of them, for afterwards the members of this meeting,
pretty generally, united themselves to the separatists.
Thus, in our times of proving, the Hand of help through instrumental means,
is sometimes afforded to our relief, when we may be almost ready to faint and grow weary.
After meeting we rode to Farmington.

First-day, attended meeting at Galen; in consequence of a funeral,
the house was much crowded, and I humbly hope it is not presuming to say,
the truths of the Gospel were largely declared to the people,
and the necessity of diligence in the great work of salvation,
whilst the day of grace was lengthened out; the people manifested a solid,
attentive disposition;
and there was reason for believing it was a time of renewed visitation to many.

Fourth-day, attended the Select Quarterly Meeting at Scipio, which was small:
the business was conducted with great unanimity,
and proved a season of refreshment to my mind.

The next day,
the Quarterly Meeting for the general concerns of
the Society commenced with a meeting for Divine worship,
which was largely attended; and encouragement was held out to the faithful.
The church affairs were conducted in much harmony and brotherly condescension;
and it closed under a grateful sense,
that holy help had been near in transacting the various
matters that came before the meeting.

Sixth-day, the public meeting was held,
and we separated under feelings of gratitude to the Great Head of the church,
in that he had been pleased once more to own us by his life-giving presence,
to our comfort and consolation: in the afternoon we rode to Union Springs.

First-day morning, attended meeting at South Farmington;
it proved to me a time of deep inward labour and
travail of spirit to reach the spring of Divine life;
too many of those I was sitting among, there was reason to fear,
were contenting themselves with having a name to live,
yet at the same time were strangers to the practical
part of true religion in which righteousness consists.
The meeting, I understood, was small to what it would have been,
had the members been informed a stranger would be there;
but I had no warrant for such information being given,
wishing if I did sit with Friends of this meeting, to see them as they usually appear.

Third-day, 17th of fourth month, attended the Select Quarterly Meeting, which was small;
to me it felt a low, trying meeting.

Fourth-day,
the Quarterly Meeting for church affairs commenced with a meeting for worship;
at the close of which Friends entered upon the concerns of the Society;
after they had gone a considerable way into the business,
the meeting was greatly interrupted by the return of a number of lads
and young men who had left the house when the meeting for worship closed,
and who had remained out of the house unseasonably; but a spirit of insubordination,
liberty and equality so pervades religious,
as well as civil society in some places in this land,
that all prospect of applying a remedy to this,
as well as other evil practices among our youth, appears hopeless;
and thus the hope of a succession of faithful standard-bearers
being raised up among them,
is feeble.

Fifth-day, 19th of fourth month, 1827, the closing meeting for worship was held;
after which we rode to Galen, where we took up our abode for the night.

First-day, we attended meeting at New Hartford;
the meeting was chiefly composed of those of other religious persuasions;
afterwards we rode to Utica.
On fourth-day we were at Galway meeting, which was attended by heads of families only,
it not being much the practice to bring the children to week-day meetings hereaway;
this subject I found I must allude to in the meeting.
We rode then to Milton, and took up our abode for the night.

Fifth-day, attended Milton meeting, after which we rode to Saratoga.

Sixth-day morning, we proceeded to the ferry;
when we were about the middle part of the river, the current ran at a great rate,
and one of our horses became very uneasy.
I hope I may say,
I felt truly thankful when our horses and wagon were
safely landed on the shore in the state of Vermont.
We proceeded towards Danby, intending to reach Salem this night;
but after we had pursued our journey about ten miles,
we were obliged to alter our course,
being informed that the bridge on the road we were taking to Salem,
had broken down the day before, and let a wagon and horses into the stream.
I thought it might be considered a merciful escape for us, and fresh cause for gratitude,
amidst all our trials, that we have hitherto escaped harm this way,
considering the many rotten and decayed bridges over deep waters we had passed.

Seventh-day, after travelling over a rough, mountainous road,
we were favoured to reach Danby, this afternoon.

First-day, attended their usual meeting; many of their members and attenders of meeting,
we were informed, were absent,
but if we could stay and have another meeting among them,
a more general attendance would be likely to take place;
but not feeling the necessity laid upon me to yield to this information,
I concluded it would be safest for us to leave tomorrow.

Third-day, 1st of fifth month, 1827, we proceeded by Granville towards Queensborough,
a fatiguing and heavy day`'s travel.
I attended the Select Preparative Meeting; a small company,
and next day was at the Monthly Meeting, in which I was comforted,
by the early and quiet manner in which the meeting settled down.
We next proceeded by Fort Ann, Shoreham, towards Ferrisburgh:
our horses appeared so jaded with the last three days`' bad roads which we have travelled,
that I feared their holding out through this day`'s journey;
when we reached the tavern we were to bait at,
we could neither procure oats nor Indian corn;
the grasshoppers had been so numerous the last summer as
to destroy the crops of grain in this part of the country;
nothing but hay could be obtained.

First-day, I attended Strasburgh meeting; in the afternoon we rode to Monkton,
a meeting being appointed to be held there at my request; while on my feet,
engaged in testimony, a child, that was running about the meetinghouse,
placed itself before me, looking up in my face, smiling and playing its little antics,
on which I made a full stop, requesting the mother of the child would take it to herself,
which, to my great grief, occasioned the mother to leave the meeting; assured,
as I since have been, that had I endeavoured simply to attend to my Master`'s business,
the actions of this innocent child would not have
embarrassed my mind during the exercise of my gift.
We took up our abode for the night with our friend Joseph Hoag.

Fourth-day, I attended the Select Quarterly Meeting, very few in number: and, next day,
the Quarterly Meeting for discipline: the business of this,
as well as other meetings in this Quarterly Meeting,
appears to be very much done by the clerk, very few, if there are any such,
manifest by their words a godly zeal for the right
support of the discipline of the Society.

Sixth-day, the public meeting was held; after which we rode to Shoreham.
First-day, attended the usual meeting.

Second-day morning, accompanied by A. Potter, his wife and daughter,
and another wagon of N. Potter`'s, we proceeded towards Easton.
The women complaining of the headache from the heat, their wagons not having covers,
I offered them seats in ours and took my seat in one of theirs.
In going down a hill, at a sharp turn, one of the swingle-trees came off,
forced the wagon against the horses`' heels, and set them kicking in a violent manner;
the neck-yoke then came off,
whereby the whole weight of the wagon coming upon the horses,
forced them across the road down a steep, it was said thirty feet;
my companion and a young woman jumped out,
the horses broke loose from the wagon and ran off;
and the wagon in going down turned over,
whereby a young woman was forced out through the top, but without receiving much injury:
it turned over a second time, and threw out the wife of A. Potter.
We soon procured medical assistance, and miraculous to say,
no limbs were broken or displaced;
our carriage was much injured and our luggage scattered abroad;
our horses received little damage,
but the woman Friend was so much bruised and cut by the fall,
we were obliged to leave them behind at Easton,
but in a few days they were able to return home.
I thought there was fresh cause to acknowledge the
mercies of the Lord are new every morning,
and because thereof the sons of men are not consumed.

Third-day, attended the Select Quarterly Meeting,
and next day the Quarterly Meeting for discipline, which was small.
After attending the public meeting the next day, we rode to Troy.

First-day, attended meeting at Crum Elbow;
after meeting we rode to Poughkeepsie and took up our abode for the night.
Second-day, we reached my kind friend James Brown`'s, at Peek`'s kill;
and on fourth-day morning, my home at New York,
where I was kindly received and cared for by no much esteemed friend Elizabeth Bowne.

Seventh-day morning, attended the first sitting of the Select Yearly Meeting,
which was chiefly occupied in calling over the representatives,
and reading our certificates who were from Europe,
the certificates of Friends from other Yearly Meetings, which were not a few,
after which the meeting adjourned to the afternoon.

Second-day morning, the Yearly Meeting for transacting the affairs of the Society,
commenced, with an evidence,
that amidst the discouraging prospects on account
of the sad state of things in this Yearly Meeting,
by the spreading of unsound principles,
the outstretched arm of Omnipotence was still extended towards us as a religious body.

Fourth-day, the Select Yearly Meeting again sat;
this proved a deeply baptizing season to many;
matters were spoken to in the authority of Truth, in a way that, I doubt not,
had a tendency to stimulate to faithfulness those of whom it might be said,
they were ready to faint in their minds,
through the fear that at times took hold of them,
that the Society would be deluged by those anti-christian
principles which threaten to carry all away with them.
Fresh cause was felt by not a few, to set up the Ebenezer to the praise of Him,
who was pleased again to appear on the side of those in this Yearly Meeting, who,
for Zion`'s sake, dared not hold their peace, nor, for Jerusalem`'s sake, be at rest,
while the enemies of righteousness are endeavouring to make such inroads in the camp.
The confusion and uproar which prevailed in some
of the latter sittings of the men`'s Yearly Meeting,
and the abuse offered to those who occupied seats in the ministers`' gallery,
especially such as were from England, equalled any thing my pen can describe.
My countrywoman, Elizabeth Robson, had a concern to come into the men`'s meeting.
When the subject was spread before the men`'s meeting,
some of Elias Hicks`'s party made objections to her being allowed;
but their objections being overruled, as she entered,
a great number left the house in a body,
and remained in the yard until she left the meeting, when they returned.
Trying as these sittings were from day to day, I thought it was a favour,
that Friends were enabled quietly to sit through them to the end.

Seventh-day afternoon, the last sitting of the Select Meeting was held.
Such is the disordered, divided state of this part of the body,
that when an attempt was made to nominate a committee
to visit the Select Quarterly and Monthly Meetings,
it met with violent opposition: a female member of Jericho Monthly Meeting,
fearing the clerk should make a minute to that effect, left her seat,
and placing herself by him, laid hold of his elbow,
and told him he should not make a minute.
In this very tried state, without being able to effect any thing,
the meeting sat until past eleven o`'clock at night.

Fifth-day, 7th of sixth month, 1827:
after taking an affectionate leave of my kind land-lady Elizabeth Bowne and her family,
and other friends in the city, in company with my country folks, George and Ann Jones,
Isaac and Anna Braithwaite, and several other Friends,
I went on board the Washington steamboat for Newport on Rhode Island,
in order to attend the Yearly Meeting for the New England States.
We proceeded on our way without impediment, until about the middle of the night,
when on a sudden I found our progress was retarded,
which excited in my mind some serious apprehensions: I did not rise and go on deck,
as my naturally anxious disposition would have prompted me to do,
but tried to keep quiet in my berth.
On inquiry in the morning as to the cause of this detention,
we were told that a heavy fog came on, which rendered our proceeding dangerous;
soon after we proceeded again,
the great swell of the water occasioned the vessel to be so continually in motion,
that very few of us escaped sickness.

About eleven o`'clock the next morning,
we were favoured to set our feet on the shore at Newport,
where several Friends were waiting to receive us.
I went to the home of my kind friend Stephen Gould, who, with his attentive wife,
afforded me every accommodation my debilitated body required.

Seventh-day, I rode out to Portsmouth, about nine miles;
here the Select Yearly Meeting was held for the accommodation of Friends from the country,
who may be on their way to attend the Yearly Meeting.
This meeting was not large;
it was a time in which there was cause to acknowledge that holy help was near;
in the afternoon the Meeting for Sufferings was held,
the business of which appeared to be conducted in much harmony.

First-day morning, I attended the meeting held at Portsmouth; the house was crowded,
the meeting being attended by many not of our religious Society,
which we understood was the case at Yearly Meeting time.
From the light, airy disposition manifested by many of these at the close of the meeting,
it was to be feared,
their coming was more for pleasure than from a real desire to be benefitted.
In the afternoon I attended the meeting held at Newport: the house, which is very large,
was crowded, and numbers were standing in the yard;
the concourse of people led me to fear we should not be
able to hold the meeting in that quiet which was desirable;
but holy help being mercifully near to those who were called
to labour in this part of the Lord`'s vineyard,
a belief was produced in some minds,
that the labour of this afternoon would not all be lost; but,
in the experience of some of our numerous company, like bread cast on the waters,
which would be found after many days.

Second-day morning, the meeting for managing the affairs of the Society commenced:
in the opening we were favoured with a renewed evidence,
that the Lord in mercy was waiting to be gracious to us in this collected capacity;
if we were but willing in all our movements to await his putting forth.
The meeting adjourned until the afternoon, when the same holy quiet was again vouchsafed;
this to me,
after enduring what we had to pass through from the unruly
spirits we sat among in the Yearly Meeting of New York,
felt like breathing in another and a purer air.
After the business of the meeting was gone through,
it closed under a feeling sense of the continuance of Almighty help from Him,
who graciously condescended to declare,
he would be with his humble dependent children unto the end of the world.

Sixth-day morning, a meeting for worship was held,
which was attended by many not in profession with our religious Society;
we were favoured to have a still, quiet meeting before our parting,
and according to human probability,
never all to meet again in this world of probation and trial.
After this meeting, accompanied by a kind Friend, I rode to Tiverton,
a distance of about eleven miles.

On first-day morning attended Tiverton meeting, where I found a small company.
I felt well satisfied that I had given up to sit with the few I found here.
I then rode about five miles to attend the afternoon meeting at the Falls,
where there is a much larger body of Friends; with those of other societies,
who gave their attendance, the house was rather crowded.
I left the meeting under a hope I was in my right place in coming to it.
On our way towards our carriage, we made a call upon a sick Friend:
the evening was hastening on apace, and having five miles to ride,
I concluded in my mind not to make any halt here;
but I was soon made sensible that if I would go along under feelings of Divine approbation,
I must not chalk out a way for myself.
Feeling thus unexpectedly stopped in my proceeding,
I yielded to express what I believed I was entrusted with,
and had reason for believing I had been made an instrument
in the Divine hand of comforting the sick Friend,
and I hope to the edification of others that were present:
after which I was favoured to know what it was to go on my way rejoicing,
of which I had nearly deprived myself.

Fourth-day, 20th of sixth month, 1827, attended the Preparative Meeting of Aponeganset;
the overseers not being prepared with answers to
the queries to go forward to the Monthly Meeting,
occasioned some exercise to Friends, but patience being preserved, answers were prepared,
which the meeting appeared to settle quietly under,
and I felt satisfied in sitting with this little company.

Fifth-day, I attended the Preparative Meeting at Newtown, which was small.
I took my seat under feelings of great depression,
and would gladly have been anywhere than where I then was;
but by labouring after quiet submission to this dispensation of Divine wisdom,
I humbly hope I may say, it proved to me a truly profitable time,
and I was enabled to leave the meeting under a sense
that there was renewed cause to set up my Ebenezer,
to the praise and glory of the Lord my God,
who had in his mercy sustained me when I was nigh unto fainting.
In the afternoon I rode to New Bedford.

Attended the Select Monthly Meeting,
which is composed of the select members of Dartmouth, Westport and New Bedford;
the few in each of these Monthly Meetings,
not being considered equal to holding separate meetings: the queries were answered,
but from the backwardness of Friends in not fully
describing the state of their several meetings,
this part of the business went very heavily forward,
and the time of the meeting was very unsuitably protracted, and yet I trust,
there was cause to hope, it had not been an unprofitable meeting to some of us.

Accompanied by a kind companion, we rode to Westport,
to attend the Monthly Meeting this day: here we found a pretty large body of Friends,
and many not in profession with our religious Society
gave us their company in the meeting for worship.
I found it hard work to relieve my mind;
what I had to communicate being more especially to the members,
and such as were in the constant attendance of our religious meetings;
but I felt cause to esteem it a favour,
that I had been strengthened faithfully to acquit myself.

First-day, 24th of sixth month, 1827; attended meeting at New Bedford;
the morning meeting was much larger than I expected to see it:
from the sorrowfully divided state of this meeting,
owing to the anti-christian principles which had taken hold of the minds of its members,
I looked towards it with feelings of discouragement,
and took my seat under great depression.
Feeling something stirring in my mind for communication, I struggled with it for awhile,
until at last I found, if I left the meetinghouse in peace, I must give up,
and therefore ventured to stand upon my feet,
and in a feeble manner uttered what had been given me.
The afternoon meeting was a time of close travail to obtain full relief to my own mind.

The next day, I made a few social visits--I was led to hope,
not unprofitably to the visited: the day closed peacefully,
for which I felt truly thankful to that Divine Power from whom all good comes.

Third-day morning, about five o`'clock I left New Bedford,
and went on board a packet for Nantucket, a passage of sixty miles;
and was favoured to land on the island about twelve o`'clock at noon the same day.

Fourth-day, attended the North meeting;
the men`'s side of the house was very thinly attended,
there being a much greater proportion of female members,
many of whom are in a state of widowhood,
occasioned by the dangerous occupation the men embark in,
many being engaged in the whale-fishery.

From the great distance the vessels now have to go in search of fish,
it takes them sometimes two years from their home.
Here I met with my kind friends Smith Upton and his wife, whose company,
as I was now among strangers, felt like a cordial to my mind.
At the close of the meeting for worship, the Monthly Meeting for this district was held:
the queries were answered; and Friends manifested a willingness to receive any remarks,
those who were come among them had to make;
we were favoured to separate under a covering of good which is not at our command,
and therefore calls for gratitude.

Fifth-day morning, I attended the South meeting,
where we found a much larger body of Friends,
but the far greater proportion on the women`'s side of the house.
My sufferings in this meeting were great,
on account of the behaviour of a number of lads belonging to Friends.
I dared not do otherwise than throw this subject before the Monthly Meeting.
I was comforted in finding that it obtained considerable
entrance into the minds of several Friends,
and obtained the meeting`'s deliberation,
which ended in a proposal for a few Friends being
convened to consider of measures to effect a remedy.
The business of the meeting was conducted in much quiet;
and Friends separated under a feeling of that solemnity which brings us near together,
and unites in desires for an increase of these precious feelings.

We attended the Select Monthly Meeting,
where the queries were answered for the Quarterly Meeting,
in doing which Friends appeared to be brought under a care,
to send forward such answers as should convey to the Quarterly
Meeting the true state of things among them.

First-day, 1st of seventh month, this morning I attended the South meeting,
which was very large; and considered a solid, favoured meeting.
In the afternoon I attended the North meeting,
which was said to be large for that district; it was a time to be commemorated.
I returned to my quarters in the evening much exhausted;
here I found several Friends in waiting to have the company of the stranger,
but I felt more disposed to retire to my bed.
This I found would not bring peace to my own mind; very soon after I took my seat,
silence took place, which I did not feel disposed to cherish,
apprehending it would prove the means of my detention from retiring to my bed,
which I very much desired; but I could no longer doubt it was not of man,
and endeavouring to settle down quietly under it,
I found my Divine Master had some service for me in this company.
I endeavoured to be found faithful in the discharge
of what might be called for at my hands;
and retired to bed, breathing afresh the language of,
"`What shall I render to the Lord for all his benefits?`"
who has been with me through this day`'s work.

Third-day afternoon, attended a funeral; the company which assembled was very large, and,
as is the case with Friends on this island, a meeting was held at the house;
in consequence of which,
the company do not feel it obligatory on them generally
to follow the corpse to the graveyard.
Although I had a full opportunity to relieve my mind at the house,
I apprehended I must be willing to follow the corpse to its last depositing place,
which I did; here we had a large company of Friends,
and of persons not in profession with our religious Society.
I found little more was now expected than depositing the remains. I did
not see how I could with peace to my own mind let the people depart,
without requesting them to try to become more collected;
and stepping on an elevated spot, the most suitable situation to be generally heard,
I delivered what appeared to me to be the counsel of my great Master;
after which I was favoured to leave the graveyard with a peaceful mind.

Fourth-day, attended the Select Quarterly Meeting,
and next day the Quarterly Meeting for the general concerns of the Society,
which commenced with a meeting for worship.
This meeting, I believe, proved a time of instruction and comfort to many;
it closed with solemn supplication through a beloved sister,
and thanksgiving for the Divine condescension which
had been in mercy manifested towards us.
The meeting for discipline was conducted in much quiet,
yet it was evident it suffered loss for lack of more promptness on the part of Friends,
in speaking to the business.

Seventh-day morning, the wind being fair, I took my departure in a packet for Falmouth,
in company with about forty-seven other Friends,
on their way home from the Quarterly Meeting; and after a passage of about five hours,
we were favoured to land safely.
This afternoon,
we called on a Friend who appeared to be plunged into a
state of as much despair as I ever before had met with.
He had no ear to receive encouragement to look for that help, which,
I was fully made sensible, only could prove availing.
I understood he had been made an instrument in the Lord`'s hand of good to others,
having received a gift in the ministry,
and had been considered by his friends very lively in the exercise of it.
During my sitting with him, my feelings were such,
that I could not divest my mind of an apprehension,
he had reasoned with clear manifestations of duty,
until the right time for the discharge thereof was clean passed over,
whereby this great weakness had been permitted to come upon him;
in which sentiments I found I was not alone.
The sorrowful state I left him in, made such an impression on my mind,
that I craved it might prove a watch-word to me from time to time.

First-day, attended meeting at Falmouth, which was large.
I was ready to hope the concern expressed by a Friend at the close of this meeting,
that what had been offered might be as bread cast on the waters, and be found by some,
many days hence, would be fulfilled.
Being clear of Friends in these parts, my kind landlord drove me to Yarmouth on Cape Cod,
where I was kindly received.

Fifth-day, attended the mid-week meeting here;
many not in profession with us gave their attendance, to whom I was enabled,
I humbly hope I may say,
clearly to point out the absolute necessity there is for man to experience,
through the effectual working of the power of Christ in his heart,
a being enabled to "`follow his steps.`"

First-day, attended the usual meeting at Sandwich, which was rendered large,
by the coming in of such as did not profess with our Society.

Fifth-day, attended meeting at Pembroke, which was small;
at the close of the meeting for worship, was held their Preparative Meeting;
this proved a solid, and I believe, a favoured meeting to most, after which,
we proceeded to Shepherd`'s to lodge.

Sixth-day morning, when breakfast was over,
the family was assembled for the purpose of reading the Scriptures.
I rejoiced at this opportunity, believing it was conscientiously practised,
and not a mere formal matter; after which we proceeded to Long-plain,
and were kindly received by Obadiah Davis and his wife.

First-day morning, 22nd of seventh month, attended the meeting at Long-plain; this,
and the afternoon meeting were considered by Friends to be solid, satisfactory meetings;
the orderly manner in which the people left the meetinghouse,
I thought was a proof they had met with something more than words;
no disposition was manifested to converse,
each one seeming disposed to go quietly to their own homes.

Fourth-day,
we walked from New Bedford to Aponeganset to attend the Monthly Meeting of Dartmouth:
the meeting was small in consequence of its being the hay-season.
When we are truly alive to our eternal interest,
this fails not to stimulate to seek the kingdom of heaven in the first place,
and when duty calls us from our outward concerns, to leave them,
and commit them to the great Caretaker, who is able to do better by them in our absence,
than we can do by remaining with them, and neglecting our duty to Him,
from whom all our blessings proceed.
I felt well satisfied I had given up to sit with
the few who gave their company on this occasion;
yet I could not but regret the dull,
heavy manner in which the business of the meeting was conducted,
for lack of a more lively interest being manifested on the part of the members;
whereby more was imposed on the clerk than Truth warrants.
This evening we returned to New Bedford.

Sixth-day morning, feeling drawings in my mind to make a call upon a family,
I proceeded alone, believing it would be better for me so to do;
on taking my seat among them,
I was plunged into such distressing feelings as I have not often had to experience:
after a time of waiting, matter rose in my mind to communicate,
and I endeavoured after faithfulness: what I had to offer appeared to be kindly received,
yet it felt to me like hoping against hope.
Accompanied by my kind friend, Abraham Shearman, we made a visit to an aged Friend,
who had been eight years confined to the house in consequence of an accident,
with whom we had a sweet, quiet, religious opportunity.
I left her with the assurance, she was sensible of being under better care than poor,
frail, mortal man,
and that her bitter cup was sweetened by the fresh incomes of the good presence of Him,
whose presence administers life to the soul.

Seventh-day morning, made my last visit to my kind friend William Roach,
now in his ninety-third year.

First-day, attended meeting at Centre, which was large,
and very soon settled down in quiet, which, I believe, was generally felt.
Earnest were my inward cries to be preserved keeping my proper place in this meeting:
the opening given me was so small and simple, that I saw no other prospect,
if I stood up with it, but I should expose my own weakness,
and be unable to proceed either to my own relief or the profit of the people.
I sat long under the exercise, fearing to stand up, and fearing to take it away with me;
at length, in great weakness and fear, I ventured to rise;
and for this act of faith and faithfulness Divine Wisdom
condescended to deal bountifully to me his help,
for the faithful discharge of his requirings in this meeting.
After this season of Divine favour, which I believe the meeting was considered to be,
I was tempted to call in question what I had communicated.
Seasons of this sort are hard to the creaturely part to bear, after we have,
as we believe, done our very best in the faithful discharge of apprehended duty;
yet I have been renewedly persuaded,
they are in great mercy permitted to humble and keep down the creaturely part;
that so God only may have the glory.
If patience under these humiliating dispensations has its perfect work,
they will not be permitted to harm us,
but prove the means in the Divine hand of stimulating us,
to take a faithful retrospect of our movements, and beget in us an earnest desire,
if such may have been the case, to see when and where we may have missed our way.

Second-day morning, we made a visit to a female Friend in the meridian of life,
who had been confined to her bed nearly twenty years;
the languishing condition she lay in was very affecting:
a short time after we took our seats in the room, we dropped into solemn silence,
and after some time spent in this waiting state of mind,
matter was given for communication suitable to her tried condition,
and grateful were the feelings that accompanied my mind for the opportunity thus afforded.

Fourth-day, attended the Quarterly Select Meeting for Rhode Island, which was a small,
but quiet, favoured meeting.
The next day, attended the Quarterly Meeting for Society concerns,
which commenced with a meeting for worship:
the business that came before the meeting for discipline
was conducted in much harmony and brotherly condescension,
and, I believe I may say,
Friends were comforted in being together.
Having a prospect of attending the school-committee at Providence next morning,
it appeared necessary to proceed after the close of the meeting that night,
as we had a ferry to cross about half a mile over,
and which is sometimes so dangerous that the ferry-men
will not venture to put their boat out:
it was now blowing a very heavy gale,
and seemed doubtful whether we could get across this afternoon;
but I found I must not risk the morning, if we were able now to get a passage.
I therefore proposed our going down to the ferry; but when we arrived,
we found other Friends in waiting,
the ferry-men not being willing to take their horses and carriages across,
the wind and the current being very strong; but after waiting a considerable time,
the wind rather abated, and the boatmen consented to take us over.
Our horses and carriage filled the boat,
so that but little room was left for us comfortably to stow ourselves:
it proved a tossing time, the wind ahead, and a rapid current running against us,
some of our horses appeared not a little terrified;
about six o`'clock in the evening we were favoured to land on the opposite shore,
for which mercy, thankfulness was the clothing of my mind,
causing my cup to overflow with feelings of gratitude to our Almighty Caretaker.
We proceeded to the hospitable abode of our kind friend Moses Brown, of Providence.

Sixth-day morning,
attended the school committee held at the Institution,--a fine healthy situation,
on an agreeable eminence, and a short distance from the town of Providence.
After the examination of the children closed, a suitable pause took place,
and I felt well satisfied with the manner in which this day had been passed over.

Seventh-day, attended the Meeting for Sufferings, which was held at the school.
First-day morning, attended meeting in Providence; where the number of Friends is small.
In the afternoon I attended the meeting held at the school; this, to me,
was a very suffering time, occasioned, I had cause to believe,
for not timely yielding to rise on my feet,
and give the meeting what I was entrusted with for communication;
yet I felt it to be cause for thankfulness that I
was not permitted to take away that which,
I had no doubt in my own mind, was given me for others.

Second-day, 6th of eighth month, 1827, we rode to Smithfield Quarterly Meeting,
and attended the Select Meeting, which was small;
the answers to the queries were read and passed over
in silence by the members of the meeting,
as if all was well with the heads of the tribes, which did not appear to be the case;
by endeavouring after a right qualification to relieve my mind on various subjects,
more particularly applicable to this part of the Society,
I left the meeting thankful for the help afforded.

Fifth-day morning, the meeting for worship was numerously attended by Friends and others;
after which, the meeting for the affairs of the Society commenced:
the answers to the queries were the chief business that came before the meeting.
Although much weakness was manifested in these answers,
yet they were passed over almost in silence.
I ventured to relieve my mind on some subjects, and in having done my best,
I left the meeting more peacefully,
than I had reason to believe would have been the case had I kept silence.

Seventh-day, I proceeded to Lynn, and took up my abode with my friend Isaac Bassett.
On our way to our quarters I observed many people collected in the front of a house,
and persons sitting in the windows, which led me to inquire what was the cause of it;
on which I was informed a burial of a young woman who had
a birthright among Friends was about to take place;
but who having imbibed those anti-christian principles,
which had deprived many in that meeting of their membership in the Society,
became one among them.
My mind was arrested with apprehensions of duty to give my company at the burial;
but on making inquiry whether the body was to be buried in the graveyard of Friends,
I was informed that was not to be the case,
but in a piece of ground joining Friends`' burial ground,
which had been purchased by those who had left the Society, for their separate use.
This information brought me into a great strait; I found the father of the young woman,
who was a member of Society,
had requested some Friends to take the charge of conducting the funeral for him,
which they had undertaken to do.
How to proceed under these circumstances, felt difficult;
the ground in which the body was to be deposited, had been purchased by persons, who,
as well as the deceased,
had manifested themselves hostile to the Society and to its fundamental principles;
but trying the fleece, as I hope I may say I endeavoured sincerely to do,
I concluded it would be best for me to go to the house of a Friend,
where we should be able to see when the corpse left the house, which I accordingly did;
but the company had arrived at the graveyard before I had strength to proceed,
and did not reach the grave-side until the parents
had turned from the grave in order to quit it;
on which I requested the company, if they were easy so to do, would make a halt,
which appeared to be readily complied with.
After a short pause had taken place,
strength was given me to plead the cause of my Divine Master among them, and declare,
as we all had but one journey to perform through this world,
before we arrived at our eternal abode,
it behooved us to be especially careful that we performed this journey well;
inasmuch as there would be no returning to correct any errors that had been made,
either in religious principles or in practice: great quietness was to be felt,
and the minds of many appeared to be solidly affected.
I was led humbly to hope I had not been out of my place in taking this step.

First-day morning, attended meeting here; it was a large gathering:
many of those who had separated themselves from the Society and our religious meetings,
I was told, gave their attendance.
It proved a time of close inward exercise for the arising of Divine life,
which is the crown of all our assemblies, and which was, in degree,
mercifully experienced.
The afternoon meeting, I was informed,
was numerously attended by those who had separated themselves from our religious Society.
After I did my best, as I apprehended, in endeavouring,
as ability and matter were afforded, to plead my great Master`'s cause;
yet I sat down short of that relief which I had hoped for, when closing my communication,
which plunged me into some discouragement.
In the evening we had a great collection of Friends at my quarters.
The evening was passed over,
partly in social conversation and partly in a religious opportunity,
and we separated under an evidence that holy help had been near to us.

Second-day morning, 13th of eighth month, I rode to Boston, where,
in the early period of our religious Society,
Mary Dyer and others suffered death on account of their religious principles.
The Society of Friends are now here no more;
the meetinghouse belonging to Friends was so far gone to decay,
as to render it expedient to pull it down, since which the ground has been disposed of,
it being pretty much in the heart of the city.
Friends have it in prospect to purchase a more retired spot,
and build a new house for the accommodation of public meetings,
and to fulfill the will of the donor who gave the
ground on which the old meetinghouse stood.
I was informed, if I had a desire to have a meeting with the inhabitants,
a place could easily be procured for me.
I could not say,
I had not at times had some expectations such a service might be called for;
but as no way opened with any degree of clearness, to take such a step as this,
after I had visited one of my fellow-passengers to America,
we returned again to Lynn in the evening.

Attended the Select Quarterly Meeting for Salem, held at Lynn, which was very small;
the disaffection that had taken place in this Quarterly Meeting having, I understood,
swept away some of its once useful members.
I felt thankful in partaking with those who remain,
in the sufferings they were still in degree, at times, labouring under,
for the body`'s sake, even the church.

Fifth-day,
the Quarterly Meeting for transacting the affairs
of the Society commenced with a meeting for worship,
which was largely attended by Friends and others;
it was considered to be a time of Divine favour.
The meeting for discipline, to me, was a low, trying time; yet,
by endeavouring to feel a renewal of Divine strength,
to be enabled rightly to acquit myself,
I left the meeting under feelings of gratitude for
the help which had in mercy been vouchsafed to me.
In the afternoon, in company with two other Friends, I called upon one of the families,
who, with many others in this place,
had been carried away with these unsound principles--the sorrowful
effects of which had occasioned Friends so much suffering:
I went in fear and trembling.

On our sitting down, conversation took place,
which continued to be kept up on the part of the family as long as there was power left;
but when He, who has all power in heaven above and in the earth beneath,
sees fit to proclaim in the ear of the soul of man,
"`Be still,`"--notwithstanding all the opposition that may be felt in the mind to silence,
how remarkably is that disposition to keep up conversation,
and that fear of silence which has been manifested, subdued,
which was the case at this time.
After patiently enduring question after question to me, in order to keep up conversation,
a solemn pause took place, which continued some time;
during which I had great strugglings to obtain the victory over that creaturely fear,
and those doubtings which came into my mind like a flood, lest,
if any thing was given me for communication, it would not be received;
but endeavouring to be found faithful to that which was called for at my hands,
strength was given me to break silence; and although a part of what I had to communicate,
was trying to my nature to utter, yet, at our separation,
all the parties acknowledged the thankfulness that they felt for the visit;
to the truth of which I thought their countenances and conduct bore testimony.

The next day we proceeded to Salem, where we were kindly received.
First-day morning, attended meeting there, which was large,
many of other religious persuasions giving us their company.
That share of religious service which fell to my lot, there was reason to believe,
had a solemnizing effect on the minds of not a few.
The afternoon meeting was also largely attended by those not of our religious Society.

21st of eighth month, 1827.
This evening reached Dover, in the state of New Hampshire.
Fourth-day morning we left Dover for Berwick, where the Quarterly Meeting is to be held.
We were favoured to reach in time to attend the Select Quarterly Meeting,
which was small;
and if I was qualified to form a correct judgment of the
state of Society as it respects this part of the body,
things are at a low ebb.

Fifth-day, the Quarterly Meeting for discipline was held;
the meeting for Divine worship was large, and many not of our religious Society attended.
To me it was a very trying one, occasioned, I was led to fear,
because so few of those present,
who were making a profession of the necessity of silently waiting
before the Lord to become qualified by him to perform that worship
which he calls for from his dependent creature man,
were willing to accept of the means that would be afforded,
if rightly sought after and patiently waited for.
The business of the meeting for discipline seemed to go on heavily:
the meeting was large,
but those who were rightly qualified to help forward the concerns that came before it,
appeared to be very few in number.
Much of the business rested with the clerk; and when this is the case,
those who are endeavouring to fill such a situation rightly,
claim the sympathy of their friends, it too often occurring,
that those who sit silent in the meeting when subjects are before it, are the readiest,
out of the meeting,
to pull to pieces what the clerk has done according
to the best of the judgment given him.

First-day attended meeting at Dover: on reaching the meetinghouse,
we found a crowd standing in the yard; the bottom part of the house soon became filled;
it appeared that half of the meeting were not of our own
religious Society--the people behaved solidly and attentively,
and when the meeting closed, seemed to manifest rather an unwillingness to separate.

We rode to Rochester, where we visited a Friend declining fast in her bodily strength,
having a family of ten children to leave behind her to lament her loss:
we had an agreeable religious opportunity with her and her numerous family;
there was cause for believing that what was given me to communicate,
felt as a balm to her deeply tried mind.

Fourth-day, attended meeting, which was largely attended by Friends and others;
the people appeared generally to sit solidly, and when it was over,
although it lasted nearly three hours, they manifested an unwillingness to depart.
Fifth-day, attended meeting at +++_______+++; some Friends from Rochester also met us,
so that the house was nearly filled; we sat a considerable time in silence,
and although it was late before I had strength to stand on my feet,
and deliver what I believed was given me for communication,
yet the people`'s minds appeared to be kept very quiet to the last.
After meeting we proceeded to the high-road, which, being rocky and hilly,
we did not reach our quarters until a late hour.

Sixth-day, we had in prospect reaching Sandwich tonight,
so as to have a day`'s rest before first-day, and two Friends of that place,
calling upon us this morning, who were anxious to reach their own homes,
proposed our moving forward with them early after we had taken our breakfast;
but feeling very unexpectedly to myself, a stop in my mind as respected proceeding,
it appeared safest for me to set these two Friends
at liberty to return home at their own time.
By endeavouring to get into that inward quiet,
where the still small voice of the High and Holy One is clearly and distinctly heard,
the way opened in my mind to have the few Friends here called together,
who hold their meeting in a private house, leaving the time to be fixed by themselves:
eight o`'clock this evening was concluded upon as most suitable,
on account of the absence of part of some families.
During conversation with the family I was in,
I was led to ask the female head,--if any individual of late years
in that neighbourhood had joined the Society by convincement?
I was informed, a woman had joined Friends some years ago by convincement,
who lived in the neighbourhood.
She was, for awhile after she was received into membership,
a very diligent attender of meetings, a clean-handed woman,
and much beloved by Friends and others,
and had been very useful in meetings for discipline;
but Friends had been deprived of her company for nearly two years,
she having sunk into a despairing state of mind.

Feeling my mind drawn to make her a visit,
I proposed it to the Friend at whose house I was staying,
and we proceeded to her residence.
Her husband, who does not profess with our religious Society, received us kindly,
and introduced us to his wife: the weather was very warm,
yet we found her shut up in a close room,
with pieces of woollen cloth hung against the windows,
and placed at the bottom of the door, to prevent the air from blowing upon her.
The room was so oppressive, I scarcely knew how to bear it,
and she herself was clothed as if it had been a cold winter`'s day;
her countenance manifested a mind harassed beyond describing,
and wholly absorbed in caring for her poor body.
Believing from the impressions my mind received,
that it was a temptation of Satan she was labouring under,
in order to prevent her usefulness in her neighbourhood,
and in the Monthly Meeting to which she belonged,
I ventured boldly to declare to her my belief,
calling her a cumberer of the ground,--finding if I spoke to any good purpose,
it must be in plain terms; and yet I was fearful, as I proceeded,
she would not bear my plain dealing; her husband sitting by,
I knew not what he would think of me, a stranger as I was.

After delivering to her what arose in my mind,
which I believed Truth warranted me in doing,
I entreated her to accept of that Divine help which, from the feelings of my own mind,
still awaited her acceptance, and to break off from that bad companion in her own heart,
which had brought her into this situation,
and was depriving her family and the religious Society of which she was a member,
of the usefulness she was designed for.
Her mind was somewhat reached, and a little turned to that Divine Witness in herself,
which manifests all things;
her countenance became more placid--that harassed
appearance it had borne gradually disappeared,
and she began to brighten up,
as if she had been favoured afresh to lay hold on that faith,
which gives the victory over the accuser and tormentor of the brethren.
She then began to speak as follows;
"`I have been hoping that some Friend would be sent for my relief,
who would be able to dip into my tried situation,
and my mind was confirmed in the belief that this would be the case.`"
Her plea for absenting herself from meeting had been the lack of health;
she now acknowledged her belief that her declining state of health,
and being plunged into her deplorable state of mind,
was through the ascendency the adversary had obtained over her,
and arose from her unfaithfulness in not being willing, when called upon,
to open her mouth as a minister: dwelling on her small capacity for such a work,
and that nothing she might communicate would be likely to profit others,
and thus continuing to withstand the call,
instead of becoming a useful member of religious Society,
and of that service in her own family and to mankind at large,
which she was designed to have been, she felt herself a cumberer of the ground.
At our parting, she, in an animating manner,
expressed a hope she should get out to meeting again,
and the desire she felt this visit might be blessed to her,
and that I might never be permitted to become rusty, as she was,
for lack of being willing to be useful in the Master`'s service.
She and her husband pressed us to make a longer tarriance;
but it appeared safest to leave her under her present impressions,
lest conversation should prove the means of dissipating them.

On our way home I was furnished with the following particulars respecting this individual.
She had been a zealous member of another religious society;
and was highly esteemed by those she then was in profession with,
for her piety and strict attention to all their religious rites and ceremonies.
One night, while lying in bed, it was revealed to her,
that there was a teacher in every man and woman,
that could teach them more effectually the way of life and salvation,
than any outward minister could do: this impression continuing with her,
and her mind becoming confirmed in its truth,
she was obliged to cease from attending the place of worship she had frequented,
and withdraw herself from the company of the minister she had so much esteemed,
to the great grief of those in profession with her, by whom she was universally beloved.
She also felt herself enjoined to remain in retirement at home,
her husband attending their place of religious worship alone;
this she continued to do for a considerable length of time.
A Friend being in this neighbourhood,
had a concern to have a meeting with the inhabitants,
on which account a general invitation was requested to be given;
but as the residence of this family was remote from
the place where the meeting was to be held,
some Friends considered, as they were rigid professors in their own way,
not knowing any thing of what was the state of this woman`'s mind,
it would be of no avail to inform them thereof.
But by some means the information reached her,
and she with her husband came to the meeting:
from which time she continued steadily to attend Friends`' meetings, her husband,
on meeting-days, bringing her to the end of the lane,
that led to the house where the meeting was held,
and afterwards coming to meet and take her home again.
After awhile he came with her to meeting,
continuing to do so as long as she kept to meeting.
She had been much given to dress and following the vain fashions of the world;
but her mind being further visited by the Divine power which at first awakened her,
she came to see the inconsistency of all these things with a true Christian walking;
and was enabled to put away all her finery, and in time it became very evident,
the chief adorning she was aspiring after, was the hidden man of the heart.
She applied after awhile to be received into membership with Friends,
which request was complied with.
Being a woman naturally of much sweetness of disposition,
added to her honest simplicity and becoming deportment,
she became an ornament to our religious Society, and continued so for some years; but,
alas! it appears the enemy enviously strove against her,
and against the cause she so faithfully espoused, and by little and little prevailed,
and turned her mind aside from the right way of the Lord.^
footnote:[By a communication from a Friend at Providence, Rhode Island,
dated seventh month, 1829, to her "`esteemed and faithful labourer in the Gospel,
Thomas Shillitoe,`" the following additional information
is obtained respecting the individual visited by the author,
as above described, which, it is believed,
will be interesting to the reader.
{footnote-paragraph-split}
"`The next meeting-day,
after Thomas Shillitoe`'s visit, she attended; after which her kind husband,
who appeared to be a person of some note, yet not a member of the Society of Friends,
called on a neighbour of his, who observed to him,
that his wife attended meeting this morning; to which he replied, with animation,--'`Yes,
an aged gentleman came from Old England, to tell my wife her duty;
and she thinks it is time to attend to it.`' "`From
that time she has enjoyed her family and friends,
and diligently attended meetings;
and is thankful that she is released from that state of
depression she had for a long time been afflicted with;
and is desirous that Thomas Shillitoe may know, previous to his leaving this country,
that his visit was a blessing to her.`"]

The meeting, which had been appointed at my request, proved a quiet, solid opportunity;
afterwards I retired to rest,
thankful I was not permitted to proceed with the Friends to Sandwich.
