== Chapter XXXV.

Seventh-day morning, 1st of ninth month, 1827, we proceeded to Sandwich,
and reached the house of Cyrus Beede, where we took up our abode for the night.

The next day attended their usual meeting, which was very large,
owing to the coming in of those of other societies;
at the close I requested the men and women members to stop, which they accordingly did,
to whom I proposed for consideration, the members of the meeting being numerous,
and not out of the reach of the meetinghouse twice on a first-day,
their holding an evening meeting during the summer-season:
this appeared to be a relief to many minds.
In the afternoon we proceeded to the north meetinghouse,
where a meeting was appointed to be held at my request; the house was greatly crowded,
and the weather so oppressive, I much feared our being able to hold a meeting in quiet,
but we were not only favoured with a quiet, but a solemn time together;
under a sense of which we separated.

Third-day, we rode to Falmouth; and on fourth-day attended the Select Quarterly Meeting,
which was small; the queries were answered in such a summary way,
that the true state of the meeting could not be come at; if my feelings were correct,
this part of the body was in a very low, feeble condition.
I endeavoured, as strength was afforded me,
faithfully to impart to Friends of this meeting, what I believed was given me for them.

Fifth-day, 6th of ninth month, 1827,
the Quarterly Meeting for discipline commenced with a meeting for worship;
which was large, being attended by those not in profession with our religious Society.
I marvelled not at the plungings I endured, on taking my seat in the meetinghouse,
from the close searching testimony I had to declare
to the members of this Quarterly Meeting;
which I was thankful to find found entrance into some minds;
so as to call forth public expression from individual members of the meeting,
in confirmation of the truths that had been given me to deliver.
The meeting for discipline was equally trying;
the answers to the queries exhibited a sorrowful picture
of the state of the Society in this Quarterly Meeting;
and yet there was cause for rejoicing to find, there were a few individuals left,
who manifested a desire for the welfare of the cause of Truth and righteousness;
but I was not able to divest my mind of a fear,
that faintheartedness was a disposition prevalent with such;
for the defects that were noticed in the answers to the queries,
instead of being seasonably attended to,
were allowed to remain and be passed over in silence from quarter to quarter.
By endeavouring to acquit myself faithfully in the meeting for discipline,
I was favoured to retire from it with a peaceful mind,
thankful that I had been made willing to share in the sufferings,
which the well-concerned members of this meeting have, at times, to wade through.

Sixth-day, the breakfast being over, some of our company were on the move;
but my mind feeling charged with something for communication before we separated,
I was obliged to express it, which produced a quiet settling down again,
affording an opportunity for my relief; after which we proceeded towards Brunswick,
in the state of Maine.

First-day, attended Durham meeting, which was large; Friends considered it to be a solid,
favoured meeting.
The next day, we rode to Litchfield.
I had been apprehensive, for several days,
I must have a meeting with Friends at this place before the Quarterly Meeting:
I opened my prospect to suitable Friends of the settlement,
and they appeared readily to unite with it; to accommodate us on our journey afterwards,
the meeting was appointed to be held at an earlier hour than usual next morning.

Third-day morning, from the early hour the meeting was appointed,
I was led to fear it would gather stragglingly, and be thinly attended;
but this was not so in either respect, the house being nearly full.
I felt much tried with poverty and strippedness on taking my seat,
which led me to fear I had not sufficiently digested the subject,
before I took this step;
I was allowed to remain for a considerable time in this tossed state,
to the abasing of all that was of the creature,
whereby a willingness was brought about to become any thing or nothing,
as my Great Master willed I should be: but he condescended, in his own time, to say,
It is enough, and light arose out of obscurity; and I was favoured to leave the meeting,
well satisfied I had yielded to this pointing of duty.
After taking some refreshment, we rode to Vassalborough.

Fourth-day, attended the Select Quarterly Meeting,
which was considerably larger than most I had of late attended;
there appeared to be many Friends who,
from their solid countenances and general demeanour,
were concerned for the promotion of the welfare of the Society:
but when the business of the meeting was gone into,
it was distressing to observe a lack of religious animation in conducting it,
by not giving that due attention to the answers to the queries,
which it was evident the state of some of the meetings called for.

Fifth-day, attended the Quarterly Meeting for discipline;
the house was very much crowded; the meeting for worship held very long,
as did the meeting for discipline.
Friends, I believe,
separated under feelings of thankfulness for that Divine condescension
and goodness which had been near to us at this time.
After meeting, we rode sixteen miles to Hallowell.

Seventh-day, we rode to Portland, a large, thickly-settled town.
First-day, attended their usual meeting: Friends here are few in number;
some of other societies gave us their company.
This, to me, was a trying meeting,
the life of religion appearing to be very low among Friends.
After meeting, we rode about ten miles to Scarborough,
and had a religious opportunity in a large family,
part of them not in membership with Friends; they lived in a very solitary situation,
no meeting being held nearer than Portland: we took up our abode with them for the night.

Third-day, we rode to Hopkins`'s village; having a hard day`'s travel,
we were anxious to reach our journey`'s end, hoping to find a quiet abode,
from the character we had received of the tavern we were to stop at for the night;
but on our entering the village, all appeared to be bustle and confusion,
it being the day when the young men had turned out to be trained for the army;
to proceed further would not be doing justice to our beasts,
we therefore resolved to make the best of our situation.
The widow who kept the tavern appeared willing to do all in her power to care for us,
and make us as comfortable as circumstances would allow of.

The next morning, we rode to Weare, to the north meetinghouse; the meeting was small.

Fifth-day, attended at the south meetinghouse in Weare;
Friends coming in from the north meeting, occasioned a large gathering.

Seventh-day, we rode to Cumberland, and on first-day, attended meeting here:
we had a great coming-in of those of other religious societies.
The people appeared solid, and I felt satisfied my lot had been cast among them;
and here, my service in this Yearly Meeting, for the present closed.

Second-day morning, accompanied by my kind companion, I rode to Providence,
where I was informed it was their Monthly Meeting on fourth-day next.
I was willing to give this subject due consideration; but my face,
I had good ground for believing, was now rightly turned to New York,
to reach there by the first conveyance.
The steam-boat proceeding on the morrow afternoon, I arranged for my departure.

Third-day afternoon, 25th of tenth month,
after taking an affectionate farewell of my kind friend Moses Brown and his family,
with many other Friends, I went on board the steam-boat,
and was favoured to land safely at New York on fourth-day,
and was kindly received by my esteemed friends, Elizabeth Bowne and family.

Fifth-day, attended Hester-street meeting,
at the close of which the Preparative Meeting was held in quiet,
which was a great favour, as the state of the Society is becoming more distressing,
in consequence of the disaffected members becoming increasingly clamorous.
In the afternoon, attended an adjournment of the Preparative Meeting of Rose street,
which was held on account of an application by the
disaffected part of the Society for a certificate,
to be addressed to Green street Monthly Meeting in Philadelphia,
which has been dissolved.
Many Friends promptly rejected this request; the clerk refused to make a minute,
which should order one to be prepared for a meeting
they could not hold correspondence with;
on which the disaffected part of the meeting became very turbulent,
proposing that the clerk should be displaced.
This proposal produced great commotion:
individuals of the disaffected party were called upon to name a clerk;
the name of one of their own party being brought forward, he was ordered to the table,
to make a minute displacing the clerk that had been regularly appointed by the meeting,
and to confirm this fresh appointment,
also ordering the clerk of the Preparative Meeting to quit the table,
and give up the books and papers; but this order not being complied with,
attempts were made to obtain forcible possession; but their attempts failing,
they were obliged to make their minute on loose paper.

During these hostile proceedings, the clerk and sound members of the meeting were,
in a very remarkable manner,
kept from manifesting any thing like impatience or
resentment on account of the abuse thus committed.
The newly-appointed clerk opened their meeting,
the regular clerk of the meeting and Friends sitting quietly,
not taking any part in their transactions.
The newly chosen clerk made a minute, ordering a certificate to be prepared,
addressed to Green street Monthly Meeting,
and appointing individuals of their own party to
prepare it for the next Preparative Meeting,
to go to the Monthly Meeting.

Having accomplished their business, and being about to adjourn,
a Friend requested those Friends who felt themselves
aggrieved at the proceedings that had taken place,
to remain in the meetinghouse.
This request at first occasioned great confusion,
some of the disaffected party saying they would not leave Friends in the meetinghouse;
but, in time, the newly-chosen clerk and most of his party left; the meeting.
A considerable time was spent in silence,
and Friends`' minds were much broken and tendered under
the consideration of this sad state of things among them;
a sweet quiet was felt over the meeting,
and after expressing the views which had passed the minds of many Friends
relative to the proceedings that had taken place in the Preparative Meeting,
it was concluded better to adjourn to seventh-day afternoon.

Seventh-day afternoon.
Friends again met, and endeavoured to come at a judgment how to proceed,
in order that a remedy might be proposed,
that such inconveniences as had been experienced at the
last Preparative Meeting might not occur in future:
it was concluded to select a committee to prepare
a statement of facts for the Monthly Meeting.
This proved a calm, quiet opportunity, and the meeting adjourned to second-day morning.

First-day, attended Hester-street meeting in the morning,
and Rose street meeting in the afternoon,
both of which were to me seasons of much inward labour
and exercise to come at any real settlement of mind.

The next morning, the aggrieved Friends of Rose street Preparative Meeting met,
when the committee appointed for that purpose produced a statement
of the proceedings at the late Preparative Meeting of Rose street,
drawn up in as conciliating language,
and couched in as impressive terms as the nature of the case would allow of,
which was to be laid before the Monthly Meeting by a committee appointed for that purpose.

Third-day, attended the Select Monthly Meeting,
which is composed of the select members of the city and Flushing:
the queries were answered,
and some of the deficiencies apparent in this part of the body spoken to.
Although it was a time of inward suffering to many;
yet I was led to hope it would prove to some of us a profitable season.

Fourth-day, attended Rose street meeting.
After the meeting for worship closed, the men retired into their apartment,
to transact the business of the Monthly Meeting.
My kind friend John Hancock had offered to accompany me towards Baltimore,
until some other Friend offered,
he being considered by the sound members of the Monthly Meeting as a suitable Friend,
and he had concluded to mention the subject to the Monthly Meeting;
but from the proceedings going on in the meeting,
he felt discouraged about opening his prospect.
To relieve his mind from further care, I proposed, when a suitable time offered,
to do it myself, which I accordingly did.
This proposal met with much opposition from some of the disaffected party;
but by keeping in the patience, the proposal made its own way, and he was set at liberty.
The paper representing the situation of Rose street Preparative Meeting was presented,
and great opposition made to the reading of it; and after much time had been spent,
the meeting concluded to have it read, which was done.
The manner of disposing of it considerably agitated the meeting;
and the disaffected part who now very much bore rule, not by soundness of principle,
but by violence, would not allow any further notice to be taken of it,
and the clerk being with them, a minute of adjournment was made.

Before the minute of adjournment was read, a Friend proposed,
that such Friends as prepared the case relative to Rose-street Preparative Meeting,
and any other Friends who inclined,
should stop in the meetinghouse after the adjournment was read;
the number who remained was more considerable than at any other opportunity,
among whom were many young people.
This was a time in which the solid part of the meeting
appeared to be brought very near together;
the weight and exercise of their spirits seemed to
have an influence on the minds of some of the youth;
their countenances, I could not help thinking, bore this testimony;
and after weighty deliberation on the state of this Monthly Meeting,
and many interesting observations had been made,
Friends adjourned to a future day.

Seventh-day morning, accompanied by my kind friends Samuel Wood and John Hancock,
we proceeded towards Rahway; after crossing the New York river by steam-boat,
in passing through Newark, some boys were throwing pieces of paper into the air;
one of these pieces falling before our horses, so frightened one of them,
that he made a jump, whereby his hind leg went over the pole of the carriage;
this set them both to kicking with violence,
and there appeared no other prospect but that the carriage would be broken,
and we should be prevented from proceeding on our journey.
A collection of people about a tavern door came to our assistance;
but the horses continued to kick and plunge until
they were quite loosened from the carriage,
and it was considered doubtful whether we could with safety proceed;
but putting them awhile in the stable,
and washing the wounds which the plunging had occasioned,
it was proposed we should venture.

First-day morning, attended Rahway meeting; I had no pleasant things to deliver.
In the afternoon we rode to Plainfield, a meeting being appointed at my request;
it was largely attended by Friends and others,
and considered to be solid and satisfactory;
much encouragement being held out to the mourners in Zion,
because of the desolating effects which unsoundness in principle was making in our borders.
After this meeting was over,
I was told the greater part of the members of the two meetings I had last attended,
had united in sentiment with the disaffected part of the Yearly Meeting of Philadelphia.
I esteemed it a great favour that this day`'s work was well got through;
and felt the need of great watchfulness over my conduct,
as it appears I am become as obnoxious to the followers of Elias Hicks,
as my country-folks now here on a religious visit.

Second-day morning, we proceeded towards Trenton: our horses performed the journey well,
yet at times manifesting they had not forgotten the fright they had received;
but my confidence in that overruling Providence, who had thus far cared for me,
abiding with me,
I was enabled to pass along without yielding to that
slavish fear to which my nature is so prone;
we were favoured to reach the house of our kind friend, Samuel Paxson, in due time.
Friends were desirous we should have a meeting with them;
and I had also been looking at the subject,
but as I understood some of the Friends lived at a distance,
calling them together on purpose, felt trying to me;
neither was the subject so fully matured in my mind
as to warrant the step being taken this evening;
I therefore proposed leaving the subject until the next morning.

Third-day morning,
earnest were my cries to the Lord to be preserved
from allowing the fear of man so to predominate,
as to be the means of putting me by from having a meeting, if it was required;
and after much weighty deliberation,
the way opened in my mind to yield to Friends being called together.
I passed the afternoon agreeably with a family,
who had a few children under their care for education;
the day thus far closed peacefully, an ample reward for every sacrifice.

Fourth-day morning,
I awoke with the prospect of the meeting called this day at my request,
accompanied with earnest desires, that I might be preserved in my proper place therein.
The religious service which fell to my lot this day,
was to warn such as were in danger of being carried away by the tide of ungodly principles.
In the afternoon we rode to Burlington,
and reached my kind friend Stephen Grellet`'s early in the evening.
Fifth-day, attended meeting here.

Sixth-day morning, we proceeded to Philadelphia,
and reached our kind friend Thomas Stewardson`'s to dinner.
The minds of some Friends in the city appeared to be a little tried,
from a report in circulation, that the disaffected members of this Yearly Meeting,
in conjunction with those who had been disunited
because of their unsoundness of religious principles,
were about establishing a Yearly Meeting in this city, to commence next second-day.

First-day, attended meeting at Arch street; in the afternoon, the North meeting.

Second-day, attended the Select Meeting of Philadelphia Monthly Meeting.
I felt comforted in sitting down with this little company.

Third-day morning, 16th of tenth month, 1827, with my kind companion James Brown,
of Peeks-kiln, who had now taken charge of me,
I rode to Springfield to attend a meeting appointed at my request.
I had understood the body of Friends was not large here,
and that it was expected several would be absent attending the new Yearly Meeting,
in Philadelphia: on reaching the meetinghouse, although we were there in proper time,
the meeting was fully gathered; the attendance was much larger than I had looked for:
on inquiring into the cause, I was informed,
notice had been given of our intentions of being here today,
at the close of their first-day meeting: it had become widely circulated,
and brought many of their members to meeting, who, at other times,
are very seldom seen here;
and that some of those who had been at Philadelphia
to attend what is called the new Yearly Meeting,
had returned to be at this meeting.
We took up our abode for the night at our kind friend Joseph Evans`'s.

Fourth-day morning, we pursued our course to Concord meeting, which we were favoured,
after travelling over a rough and hilly road, to accomplish in due time;
the gathering on the men`'s side of the house was very small.
I found it hard to obtain relief to my exercised mind,
but by endeavouring to keep my eye single, and my dependence simply placed on Him,
who only can help in every needful time,
I was enabled to leave the meeting with a peaceful mind;
Friends expressing the comfort our unexpected visit had afforded them.
We rode to West-town school, where we were kindly received.

Fifth-day morning,
this being the day on which the mid-week meeting is held in this establishment,
a meeting being also held at the same time at Birmingham, a few miles from the school,
and believing that Truth pointed to Birmingham meeting this morning,
and afterwards to have a meeting with the family of this establishment,
with such as usually attended, I left the family to conclude on the time;
and rode to Birmingham.
This meeting was an exercising time to me;
yet I felt thankful in believing it proved a solid, satisfactory opportunity to most.

Sixth-day, attended the meeting appointed at West-town school; the solid,
orderly behaviour of the children during the sitting of the meeting,
and on parting from it,
did great credit to the superintendent and their numerous other care-takers.
This afternoon we left the establishment, and rode to Wilmington,
and reached our kind friend Samuel Canby`'s, before it was dark.
The watch-word being renewedly proclaimed in the ear of my soul on entering Wilmington,
of, "`Go not from house to house,`" I found it must, as much as possible,
be diligently attended to,
as great importunity continued to be used with me to go here and there.

First-day morning, attended Wilmington meeting under feelings of great depression;
when the time came for me to open my mouth among them,
I felt a dread of standing upon my feet, and yet I dreaded keeping silence;
but laying hold of the little strength that was afforded, I stood up with these words,
"`I will divide them in Jacob,
I will scatter them in Israel;`" calling upon those
assembled to be willing to put the query home individually,
is not this language of, "`I will divide them in Jacob,
and scatter them in Israel,`" sorrowfully applicable to the state
of things in this meeting,--and that every one would examine into
the cause why things were thus among them;
and I warned Friends against being carried away by the tide of ungodly principles,
and those notions and speculations on religious subjects,
which many before them have been carried away with to their great injury,
calling the attention of the meeting to a view of the fruits
brought forth by the promoters of this defection in principles.
When the meeting broke up,
I was given to understand my communication had pinched some harder
than they were willing to bear without exposing themselves:
an elder, who soon afterwards made a part of the new Monthly Meeting of Wilmington,
set up by the disaffected party, told me, as I was leaving the house,
that I had given great dissatisfaction; another,
who took a very active part in setting up this new Monthly Meeting,
and depriving Friends of the use of their meetinghouse, beset me, saying,
the meeting had been more like a theatre than a place of worship; adding,
they were quiet among themselves,
and that it was the English Friends coming among them,
that had occasioned all the unpleasantness which had taken place.
I found it would not be safe for me to go into any further explanation than to say,
they were all strangers to me; as such,
I could have no individual in view in what I had to offer in the meeting,
I therefore must leave matters.
I began to feel my situation as I journeyed along more and more awful, and advancing,
as I was, towards Baltimore, hastening into the way of greater danger,
I was sensible that increased watchfulness would
be necessary as to the company I associated with,
and where I took up my abode.

The afternoon meeting was, I understood, larger than usual; I hope I can truly say,
I did not try either to please or displease, this afternoon,
but simply do my duty if any thing was given me for communication.
When this meeting closed, the individual who in the morning said,
the meeting was more like a theatre than a place of worship,
and charged English Friends who had come over on religious visits,
with being the cause of the disturbance now prevailing among Friends,
was waiting at the door of the meetinghouse,
to express his satisfaction with the meeting this afternoon: another person said,
he was well satisfied that my lot had been cast among them that day: under all,
whether approbation or disapprobation,
I found aiming at quietness in myself was the only safe spot for me to abide in.
We had a large company in the evening at our quarters,
among whom were some who had manifested dissatisfaction in the morning: we had a short,
solid, religious opportunity together,
and separated under feelings of more nearness towards each other,
than was manifest by some towards me at the close of the morning meeting,
for which I felt truly thankful.

Second-day morning, left Wilmington,
and rode to New Garden to attend an appointed meeting there; the day being very stormy,
I looked for a small company, but we had a large gathering; it proved,
as at many other places,
a time of close labour and travail to come at the spring of Divine life; feeling,
as I apprehended,
much of the spirit of disaffection prevailing in the minds of many in the meeting,
I found it hard work to be willing to stand upon my feet,
and make the offering that I believed was given me for communication;
the meeting closed in much quiet,
and I was led to hope it would not prove lost time to some.
We went home with our kind aged friend William Jackson,
who made a religious visit to my native land many years ago,
and took up our abode with him for the night.

Third-day, attended an appointed meeting at West Grove, which was large:
I found it hard work to come at that true settlement of mind,
which brings the creature into a willingness to become anything
or nothing in his own eyes and the eyes of the people,
even just what his Divine Master wills he should be among this deluded company,
for such I thought I evidently felt was the case.

The next day we rode to West Nottingham, and attended their mid-week meeting,
which was very small; when the meeting closed.
Friends expressed their satisfaction at our unexpected visit to them.
It being their Select Meeting, I sat with the little company that composed it;
the queries were read, and answers brought ready prepared;
the meeting appeared to enter into a due consideration of them;
after meeting we rode to Deer-creek.

Fifth-day, attended meeting there; the painful sense I was brought under,
that unsoundness of principle had overspread nearly the whole of this meeting,
I am not able fully to set forth; I soon was made sensible,
that what I had to communicate was not well received,
and that I was surrounded by watchers,
such as were watching for the halting of English Friends,
as the spirit of prejudice against them was evidently increasing.

Sixth-day, we were now turning our faces towards Baltimore,
in order to attend that Yearly Meeting; the prospect of which made me sad,--feeling,
as I apprehended, that bonds and afflictions awaited me there.
We stopped to bait our horses at a tavern,
where we met with a large company of members of our Society,
on their way to this Yearly Meeting;
and notwithstanding they pretty generally carried themselves respectfully towards us,
it was sorrowfully to be felt there was an obstruction to that familiar communion,
which has from the commencement of our Society been our characteristic badge.
We were favoured to reach Baltimore,
and the house of our kind friends James and Martha Carey in the evening.

Seventh-day morning, 27th of tenth month, 1827,
attended the first sitting of the Select Yearly Meeting; the business of this meeting,
it was sorrowfully evident, had become a mere formal matter;
instead of reading the answers to the queries, peculiar to this part of the body,
brought up from the Quarterly Meetings, and allowing time for considering their contents,
they were given to the clerk to prepare a summary of them,
to be brought to the adjournment of the meeting.
Although my mind was painfully affected at this mode of doing the business,
yet I did not feel liberty to make remarks thereon,
being fully satisfied it would become the concern of Friends,
who remain firmly attached to our ancient principles and practices,
when separated from those who are trampling upon them,
to reorganize the manner of doing the business of this Yearly Meeting,
and restore order again: the meeting adjourned to the afternoon.
At the adjournment this afternoon, the queries, the answers,
and the summary were hurried through.
Towards the close of the meeting, after a severe struggle,
I gave up to express what I had on my mind; for which, in this perilous time,
I hope I may say, I was made truly thankful.

First-day morning, attended the meeting for the western district of this city,
which was very large; feeling my mind brought under exercise for service in the meeting,
and being aware there were those present who had publicly opposed
the Gospel truths which some of my country folks had to declare,
I felt almost overwhelmed with discouragement;
but endeavouring after entire submission to whatever
should be the will of my Divine Master,
when the time was fully come for me to stand on my feet, and declare my Gospel message,
strength was in adorable condescension and mercy given me, in proportion to the work;
and that opposing spirit, I had so much dreaded, vanished out of sight,
and a free course was felt for what I had to offer to the meeting.
Before the meeting closed,
a few remarks were made that evidently manifested
dissatisfaction with a part of what I had delivered;
but from the evidence in my own mind,
that I had offered nothing but what Truth would bear me out in,
it appeared safest for me to keep quiet.
At Old-town meeting in the afternoon, my difficulties were not lessened;
but as patience was sought after and abode in,
and a willingness experienced to become any thing or nothing in the Master`'s hands,
ability was received to rise above all my discouragements; I trust I may say,
I felt truly thankful that another day of danger and suffering was got through.

Second-day, at ten o`'clock,
the meeting for the general affairs of the Society
assembled after calling over-the representatives,
the answers to the queries from the several Quarterly
Meetings corresponding with this Yearly Meeting,
were delivered in but not read,
being given to the clerk to prepare a summary to be laid before a future sitting:
the meeting adjourned to the afternoon.
At the adjournment,
epistles were read from most of the Yearly Meetings on this continent,
and one from the Yearly Meeting of Friends in Great Britain;
the clerk informed the meeting he had in his possession two epistles from Philadelphia;
one from that Yearly Meeting in correspondence with this Yearly Meeting,
in the fourth month last; and one from a body, styling themselves,
the new Yearly Meeting of Friends, held in Philadelphia, in the tenth month last.
The disaffected party opposed the reading of the epistle from the Yearly Meeting
of Philadelphia which had been in correspondence with this Yearly Meeting,
manifesting a determination that that only should
be read which came from the new Yearly Meeting,
held in the present month.
This brought the sound members into great difficulty,
who bore their testimony faithfully against their proposed disorderly proceedings:
the disaffected party showing a determination to carry their point,
the clerks being of their party,
and it evidently appearing the sound members no longer
had either influence or authority over the meeting,
they were obliged to sit quietly and submit.

An epistle from the Meeting for Sufferings in Philadelphia
to the Meeting for Sufferings belonging to this Yearly Meeting,
setting forth the proceedings of the Separatists in their Yearly Meeting,
was requested to be read in this meeting, but this would not be allowed;
the meeting adjourned in great commotion until next morning.
In the evening, attended the Meeting for Sufferings,
in which the circumstance of withholding from the Yearly Meeting the reading
of the epistle from the Yearly Meeting of Philadelphia in the fourth month last,
was brought forward and fully spoken to,
and the reading of it in the Yearly Meeting urged by Friends as far as Truth bore them;
but being much opposed by those who were of the disaffected party,
there appeared no way for Friends but to submit.

Fourth-day, the meetings for worship were both open;
feeling drawings in my mind to attend Old-town meeting,
my companion James Brown and myself proceeded accordingly;
the quiet of the meeting was greatly interrupted
for some time by members of Society and others,
coming in companies from the other meeting.
The most conspicuous of the Hicksite preachers of this Yearly Meeting,
and some of the same class from Pennsylvania, were here;
my being placed in the gallery with them was trying.
I would gladly, if I dared, have left the meeting, such was the unsettlement;
but by endeavouring to come at that help,
which alone is able to still the commotion of the mind of man,
and stay the swelling of Jordan,
I was favoured to rise above the painful and discouraging feelings I had been tried with.
Those who had left the other meetinghouse, running after the Hicksite preachers,
being more anxious for outward declarations and eloquence of speech,
than willing to bow to the more sure word of prophecy in themselves,
might be gratified by what they heard, but not truly satisfied.

Fifth-day, the meeting assembled according to adjournment; the committee on epistles,
which consisted of the Hicksite part of the meeting, brought in an epistle,
addressed to that body which held a Yearly Meeting in Philadelphia in the last month,
which was read and ordered to be signed by the clerk on behalf of the meeting,
and forwarded to that body.
After Friends had protested against these disorderly proceedings,
they were obliged to submit.
The business of the Yearly Meeting being gone through,
orders were given to inquire if the women had any thing to lay before the men`'s meeting.
I felt myself brought under the necessity before we separated,
to request the shutters might be raised between the men`'s and women`'s meetings;
a short pause being made on this proposal, the women`'s meeting being consulted,
the closing minute of the men`'s meeting was read, and the shutters were raised;
after an opportunity had been afforded me,
in which I endeavoured to be as concise as possible,
so as to be able fully to relieve my own mind, the meeting separated.
From remarks made by different individuals,
it appeared that this opportunity which men and women had of sitting together,
had a cementing effect on many minds; a time in which it might truly be said,
the gathering arm of Omnipotence was afresh extended to this part of his heritage.
I had looked towards attending this Yearly Meeting with a secret dread,
but I could not now feel cause for regret,
notwithstanding I had some rough and rather insulting
usage to endure in some of the meetings.
My companion and myself spent this afternoon with our kind friend Gerrard T. Hopkins.

Having felt drawings in my mind to visit the prisoners in the jail,
I acquainted him with what I had in prospect, requesting him to consult Friends,
and if way opened for such a visit,
to conclude upon its taking place at the time that best suited
the views of those who had the charge of the prisoners.

Sixth-day, 2nd of eleventh month, 1827, this morning we proceeded to the jail.
A court having been lately held to hear causes,
when we arrived we found considerable bustle in the hall where
we were to take our seats and the prisoners to be assembled;
some prisoners discharging and others coming into the jail,
and much conversation going forward which threatened to have a
dissipating effect on the minds of both visited and visitors.
I very much doubted our being able to come at any right settlement,
or that my views in making this visit would be likely to be answered;
but after awhile the bustle subsided, and we became quiet.
When the religious opportunity closed, and we were about to take our leave,
the prisoners generally appeared solid,
and expressed their thankfulness for the opportunity; and one of the prisoners,
rather an elderly man of the Jewish persuasion,
appeared to manifest in a striking manner a sense
of gratitude and susceptibility of feeling,
and as if he lacked words to convey to the full what he had felt,
he closed what he could say with, "`You have been sent from Bethel.`"
I felt fresh cause for setting up the Ebenezer, and saying,
"`Surely hitherto it is the Lord that has helped me.`"
I retired to bed, but my sleep during the night was very short.

My mind had been occupied with an apprehension of
religious duty to make a visit to a great slave merchant,
who resided in this city, where the needy slave holders,
and such as had slaves who were refractory and difficult to manage, were encouraged,
by his weekly advertisements, to come, and find a ready market for them.
A large building is erected on his premises like a prison,
to secure them until he has obtained a suitable complement to send to different places,
where there is a demand for them.
I found he was considered, as a man, independent of his employment,
to be of a ferocious disposition, so that many, we were told, stood in dread of him;
notwithstanding which, this subject had taken such hold of my mind,
that I saw no way for my relief but to be willing to attempt an interview with him.
Seventh-day morning, we called upon a Friend,
to whom I opened my situation relative to making a visit to this slave merchant;
we found if we did make such a visit, it would be best for us to go alone;
and accordingly proceeded towards his residence.
On our way I felt much for my companion,
from what I had heard of the unsubdued will and wicked disposition of the slave merchant,
and the danger we might be exposed to from the large dogs he kept loose about his premises,
to the terror of those who passed by.
But there was no way for me but to cast my care on Him,
who had so many times preserved me as from the paw
of the bear and the jaws of the devourer.

As we advanced towards the house, one of these fierce looking animals came out at us,
followed by another, as if they would have seized us.
Their noise soon brought out one of the house-slaves, and, as we supposed,
the slave merchant himself, whose countenance looked as fierce as his animals,
querying with us in a stern, commanding manner, "`What is your business?`"
I offered him my hand, feeling nothing in my heart but love towards him as a man; saying,
I would be obliged to him to allow me to have a little conversation with him.
He asked us into his house; on my requesting him to have the dogs taken care of, saying,
I was a nervous man, he attended to it; and in ascending the steps of his house,
we observed more of these large dogs chained about the yards.
He showed us into a very elegantly furnished parlour.
On the shelf of the chimney-piece was a pistol,
which appeared to be ready cocked for use,
should he at any time be put to the test of defending himself;
he ordered us to take a seat on a sofa, and placed himself near us.
I gave him my certificates to read, which he appeared to do attentively;
this afforded us an opportunity of having our minds
brought into quiet after our besetment by the dogs,
and their master`'s angry countenance.

When he returned my certificates,
the reading of which appeared to have somewhat softened his mind, he said,
"`I suppose you are going about preaching the Gospel;`" to which I replied,
"`I profess to be so circumstanced.`"
I then endeavoured, in a tender, feeling, but decided manner,
to open the subject that brought me to his house, telling him,
I came on behalf of the poor coloured people;
that I lived in a country where the inhabitants were all free,
but I found I was now in a slave-holding part of the United States of America;
and by an advertisement of his which I had in my possession,
it appeared he was a dealer in these coloured people, who were kept in slavery.
I requested him to pause for a moment, and endeavour, as much as possible,
to place his own parents and nearest relatives in the very situation
of those poor creatures he had at times purchased and sold again,
thereby separating the nearest connections far from each other,--husbands from wives,
and children from parents; and try how far such acts as he was in the practice of,
accorded with such feeling of humanity as he would wish
should be exercised towards his own parents and relatives;
with more to the same effect.

He appeared to hear me patiently, and tried to justify his conduct,
but with coolness and deliberation; saying,
he was educated in a slave-holding state,--that his father was a slaveholder,
that his mother was a pious woman,
in connection with the Methodists;--that she was in
the practice of reading the Bible to her children,
and that her pious care for him he yet remembered,
and some of the good counsel that she gave him;
that through her influence his father manumitted about seventy slaves:
she died when he was young.
On his father marrying again, he found he must leave home,
or render it unpleasant to his parents, which he did not desire to do,
and therefore entered into the army, and was at the battle of New Orleans:
after the war was over, the army was broken up: on quitting it he found himself in debt,
and not knowing what employment to take to, to extricate himself from his difficulties,
a relation encouraged him to become a slave merchant,
offering him funds to commence this trade, which he accepted; and yet said,
we thought feelingly so, it is a bad business, and that he had concluded to give it up,
and had been making arrangements for that purpose.
But some of his employers, in the first rank of slaveholders,
and even some who were making much profession of religion,
would not allow of his giving up his business, but urged him to go on with it.

He laid great stress on the encouragement he received
from this latter description of his barterers,
from which I was led to fear,
that when he felt any qualms of conscience on account
of the manner in which he was getting his wealth,
as he was deemed wealthy, the entreaties of this class would be resorted to,
to salve over the wounds of conscience he at times experienced,
which I could not doubt had been the case at times with him:
he also pleaded having the laws of the state to sanction him in his traffic,
which opened the way for me to go further into the
subject but in time it evidently was manifest,
that the Divine witness was so reached in him,
as to compel him to cast away all his weapons of defence.
He gave it as his opinion, that before twenty years were passed over,
slavery would be brought to a final close, if the work was rightly gone about.

By this time we thought we never witnessed the declaration--that
the lion should lie down with the lamb,
more fully exemplified.
He assured us again of his determination to quit his business,
and acknowledged the gratitude he felt for the visit,
took his leave of us in an affectionate manner,
conducting us himself quite off his premises.
As we quitted him, his countenance, which on our first approach appeared terrific,
was so changed, that he was pleasant to look upon.
Everything about his elegant house and his yards, told, in plain terms,
that he considered himself living in continual danger of losing his life.
I felt truly thankful to the great Preserver of men,
when we reached our place of destination again.

First-day morning, attended meeting:
and in the afternoon our kind friend Gerrard T. Hopkins, and other Friends,
called upon us to proceed to the penitentiary, to make a visit to the prisoners,
for which, arrangements had been previously made:
on arriving at the institution we were kindly received
by the principal keeper and other officers,
who conducted us to the men`'s apartments,
where two hundred and seventy prisoners were assembled.
Their behaviour was generally very becoming,
and the meeting was conducted in a solid manner:
when it was over I found I must request to be permitted
to give each of the prisoners my hand,
as they passed away;
the generality of them appeared very grateful for the religious opportunity,
and manifested tenderness.

We next proceeded to make a visit to the women, only thirty in number,
and twenty-six of these were people of colour, with whom we had a religious opportunity;
at parting I gave them my hand: one woman of colour held me so fast,
I had a difficulty to get loose, and she burst out aloud weeping sorely.
After these opportunities were over,
we walked about the different apartments in the prison; being in the yard,
one of the prisoners, with the consent of the principal keeper, came up to me,
saying he was an Englishman, from Woolwich, sentenced to a few years`' imprisonment,
and importuned me to intercede with the English consul
to have the remainder of his time remitted.
On inquiry of the governor relative to his conduct,
he informed me he had not a better conducted man in the prison.
I could not put from me the request of my countryman,
and on the next day I applied to the British consul on his behalf:
being afterwards at Baltimore, and inquiring after my countryman,
I found he had been liberated and was gone home to his native land.
Accompanied by our kind friend Hugh Balderson, we rode to Elkridge.

Third-day, attended a meeting held here at my request;
the house was pretty generally filled by Friends and others.
I believe it was considered a satisfactory meeting; afterward we rode to Sandy Spring.

The next day, we attended meeting here; the morning being very stormy,
the meeting was small:
but this was not the case in the first commencement of our religious Society,
when Friends could hardly hold their meetings because of the opposition
they at times met with from those in power and the rude rabble:
but now these matters are made easy to us,
and we are protected in holding our meetings in quiet,
greater indifference in the attendance of them prevails.
At the close of the meeting for worship, the Monthly Meeting was held;
there being but little business before the meeting, it was soon quietly got through.
A Friend of the meeting, who came to our lodging, took leave of us to go home,
but after he had reached the door,
came back again to say his mind had been prejudiced against the English Friends,
but that the prejudice had been done away by what had been
communicated to the meeting in the line of the ministry:
my companion as well as myself, had to allude in the meeting,
to the sorrowful divisions that had and were taking place among Friends,
and to point out what appeared to us to be the cause,
and the only remedy that would effect a more close union again;
things were greatly out of order in this meeting in that respect.

Sixth-day morning, attended meeting at Indian Spring,
which we understood was larger than it usually is;
the meeting soon settled down into quiet, and the people appeared solid and attentive.
We then rode to the city of Washington, which we did not reach until it was nearly dark.

Seventh-day morning, 10th of eleventh month, 1827,
my mind being drawn to make a visit to the President of the United States,
I mentioned the subject to my countryman Samuel Brook,
who had for many years held a situation in the treasury department here;
on which he kindly offered to go to the president`'s house and inquire if he was at home;
this prospect afresh bowed my spirit before the Lord in secret cries to him,
if way should open for me to have an interview with the president,
to be preserved faithful to what appeared to be the Divine will.

Samuel Brook soon returned with a message from the president,
saying he was at liberty to receive me at such time as best suited myself.
My companion James Brown and myself soon waited upon him,
by whom we were received in a kind, respectful manner.
I presented him with my certificates, which he appeared to read with attention:
this practice of offering my certificates when making
such visits to those not of our own religious Society,
I have found to be attended with a two-fold benefit,
as being the most agreeable mode of introducing myself,--my certificates
explaining my views in leaving my own home fully,
dispensing with the asking of many questions which
otherwise would in all probability be put,
and affording time, if any perturbation of mind may have taken place,
to endeavour after composure.

On the president returning me my certificates, I informed him,
that during my travels in the United States of America,
various matters had attracted my attention;
some of which had been brought before the view of
my mind since I had arrived at the capital,
which I must lay before him for his serious consideration;
one of which was the very distressed situation of two very aged and infirm women,
one of them having quite lost her sight,
the daughters of the old chief of the Oneida tribe, Scannadore; who, when living,
was highly esteemed by those who were of influence in congress, for his piety,
uprightness of conduct, and great powers of mind.
These two aged and infirm women, have now no other means of supporting themselves,
but by begging their food from day to day, of their tribe, who are poor themselves:
I therefore requested him to take their deplorable case into consideration,
and if there were any funds that could be appropriated
to their support to be so kind as to attend to them.
He assured me it should obtain his attention.
I further informed him, I had been painfully affected in observing,
that spirituous liquors were generally retailed in the grocers`' shops
in this city as well as New York and other places in the United States;
which practice, according to the view I had of it, opened a wide door for intemperance,
because persons who, in the commencement of their intemperance,
would be ashamed to be seen going into a common dram-shop;
and especially respectable looking females could
enter a grocer`'s shop to get their dram,
and not be suspected of indulging themselves in such evil practices;
it also opened a door for servants who were so disposed,
when sent by their employers to these places of temptation to fall into these evil practices,
until they became confirmed drunkards.
I recommended the president to lay the subject before the members of congress,
and if he could do no more than this towards endeavouring to remove this great evil,
I believed he would find peace in so doing;--counselling him not to fear man,
but to fear the Lord,
that so he might be found filling the important situation
he had permitted him to be placed in,
consistently with the Divine will.
I added, it has long been my firm belief, that according to the power invested in us,
if we did not exert that power and influence, as far as in us lies,
in preventing evil practices,
we ourselves become implicated therein in the sight of Almighty God,
with those who are actually in the practice of them;
and that I feared the people of the United States had forgotten that Almighty hand which
had brought about their deliverance from that warfare they had been involved in;
and that it was my belief,
if wickedness continued to increase in the United States as it had done,
a scourge in some way or another would be permitted to come upon the people
of the United States of America;--with more than I can call to remembrance.
At our parting, the president expressed the satisfaction our visit had afforded him;
in which we felt cause to unite,
as he had given us such a full opportunity to relieve our minds.

First-day, attended meeting here;
most of the members had given proof of unsoundness in religious principles;
the meeting was nearly one hour in gathering;
this is one among many other disorders which these unsound principles,
now so widely spread in this land, have introduced into our religious Society.
I believe both my companion and myself were favoured
to quit the meeting with our minds relieved,
yet not without our having public opposition to bear.
We were obliged to exert ourselves to reach the afternoon
meeting at Alexandria in due time.

Second-day morning, we proceeded on our way to attend the Monthly Meeting of Fairfax,
to be held at Waterford; we had a very trying day`'s journey of thirty-six miles,
at the close of which, we were brought into a great strait; night came fast on,
and we were travelling on a road we were strangers to,
where neither inhabitant nor house was to be met with: it became so dark,
that we concluded it would be unsafe for us to proceed much further,
and therefore if we did not soon get sight of some
building to shelter ourselves in for the night,
we must be content to take up our lodging in our wagon.
I felt more for our poor horses than myself, the herbage being entirely burnt up;
but on a sudden we observed, and that was all we could say,
something like the top of a barn, which we ventured to make towards,
and soon discovered a glimmering light,
which led us to the house of the family with whom
we were intending to take up our abode for the night.
I hope I may say, I felt truly thankful to our Almighty Care-taker for this favour:
we met with a kind reception from the family,
and were glad to retire to bed after a day of fatigue to both body and mind.

Fourth-day, we attended the Monthly Meeting: the meeting for worship was large;
and the business of the Monthly Meeting appeared to be conducted in a summary way,
for lack of Friends feeling a more lively interest in the concerns of the Society.
After the Monthly Meeting we rode to Goose creek.
The next morning attended Monthly Meeting there;
the business appeared to be conducted with a good degree of care,
that the right order of the discipline should be maintained;
the subject came before us of petitioning the legislature
on behalf of the people of colour in this state,
whose humane masters had granted them freedom,
but who not having the means to emigrate with their families to a free state,
in the time limited by the law of the state,
were in danger of being by law again sold into bondage; forty of them,
the meeting was informed, had been presented to the grand jury, who, it was said,
were generally men likely to see this law rigidly put in force.
It was concluded by the meeting that the representatives
should report this case to the Quarterly Meeting.

Sixth-day morning, we rode towards Hopewell.
We forded the Shanandoah river, the approach to which appeared awful;
but by endeavouring to keep near to the great Caretaker, I was preserved in the quiet,
until we were favoured to land safely on the other side.

Seventh-day, 17th of eleventh month,
attended the Quarterly Select Meeting for Fairfax held at Hopewell:
this was a very exercising time;
it felt hard work to the creaturely part to deliver
what came before the view of my mind for communication;
but by endeavouring to keep near our great Helper,
strength was mercifully given to deliver what I had in charge,
and I was favoured to leave the meeting peacefully.
I had reason to believe, that comfort was afforded to the honest-hearted members,
who were suffering under the prevalency of unsound principles,
which were sorrowfully spreading among the members of this Quarterly Meeting.

First-day, attended meeting at Hopewell, which was large;
it was nearly an hour after the time it should have gathered,
before we were favoured to settle down into quiet.
We had a large party at my lodgings in the evening, who were very full of conversation;
but I could not give much, if any attention to it,
my mind being introduced into exercise for religious service.
I allowed one short interval of silence after another to pass over unimproved,
until a fear came over me as to the consequences, should the company separate,
and I not be faithful.
I requested Friends to be silent,
fearing such opportunities as I had missed would
not be found again before a separation took place.
My request was yielded to, which afforded me an opportunity for relief;
yet I had no other expectation but that it would have produced opposition;
the chief part of our company were professedly in
connection with those who deny the fundamental doctrines,
which we, as a Society, have ever held, as regards the divinity of our Redeemer;
one of them was a leading man in their cause; but all passed off quietly.

The next morning the Quarterly Meeting for discipline commenced;
the subject of petitioning the legislature on behalf
of the people of colour obtained much consideration;
and the Monthly Meetings in which these cases existed,
were encouraged to proceed therein as Truth might open the way.
The meeting closed upon the whole comfortably.

Third-day, we proceeded towards Newmarket: on our arrival at Harper`'s-ferry,
which we had to cross, we found three wagons, with six horses each,
had reached the ferry before us, and were waiting to go over;
there was only one boat to convey passengers and carriages,
and we had no time to spare to get to our quarters before night:
we offered to purchase the first turn when the boat returned from the other side,
but the wagoners were so imposing we did not feel easy to fall in with their demand,
not aware of the difficulties they were able to expose
us to on the other side by going over before us.
After an exercise of patience, we were favoured to land on the other side.
But here our greatest trials with the wagoners began; the pass, by the river side,
for a great distance, was so narrow, as not to allow of one carriage to pass another,
except in a very few places, where the rock had been cut through for this purpose:
we were much tried with their slow travelling,
which appeared to be more on purpose to annoy us,
because we would not yield to their imposition, than from necessity;
and if we attempted to turn into one of these places, to get before them,
they would either turn their horses across the road, or gallop on to prevent us.
In making a further attempt to turn into one of these nooks, to pass by them,
our wheel touched one of their wagons; upon this,
the driver came out of his wagon in great fury,
and threatened he would stone our wagon to pieces;
we had no other expectation but he would have done us and our wagon an injury.
I felt not a little tried at our being at the mercy
of such a lawless set of unprincipled men;
but one more considerate than the rest assisted us when an opportunity offered,
and with some difficulty we got quite clear of them,
but did not reach our tavern until it was quite dark.

We proceeded to Newmarket, and next day attended meeting at Bush creek,
an old cold meetinghouse; it proved a solid, quiet meeting.
I felt well satisfied I had given up to attend it, from a hope in my own mind,
that those desolating principles, which have so spread in other meetings in this land,
had not made much way among Friends here.
On seventh-day attended Warrington Select Quarterly Meeting, held at Pipe creek,
a time of close exercise, both of faith and patience;
yet feelings of gratitude to my heavenly Master prevailed with me,
in that he had been pleased to favour me with strength,
and the retrospect of this day`'s labour afforded a consoling
evidence that I had acquitted myself faithfully in his cause.

First-day morning, 25th of eleventh month, 1827, attended meeting at Pipe creek,
which was large, many being obliged to remain on the outside of the house.
Second-day morning, the Quarterly Meeting for discipline commenced;
the meeting for worship which preceded it, was, I believe, by most present,
considered a memorable one; it called forth from an experienced, aged Friend,
the acknowledgment that what had gone forth in the line of the ministry, would,
as the wise man expresses it, be like bread cast upon the waters,
that would be found after many days.

There being but little business for the Quarterly Meeting, it soon closed.
I left the meeting under a painful sense of the loss
sustained by Friends of this Quarterly Meeting,
for lack of greater promptness in attending to the concerns
of the Society in their Monthly and Quarterly Meetings,
through giving way to fears that have not their foundation in the Truth;
and yet no way opened for me to relieve my mind more
fully on the subject than I had done.
After meeting, we rode to New Windsor, and took up our abode for the night.

Third-day, we rode to Baltimore,
and were favoured to reach our friend James Carey`'s in the afternoon.
The next day, attended the mid-week meeting, which was very small;
but considered to be a solid, favoured time;
at the close of which was held the Preparative Meeting.

During our travel in Maryland, our road lay through the estate of a great slaveholder:
the feelings I was impressed with at that time frequently came up in my view.
Today, dinner being over, and sitting quietly with my mind turned towards the Lord,
with desires that I might be able to see my way rightly out of Baltimore,
I was brought under an apprehension of duty to make a visit to the owner of the estate,
who I understood was in the city.
It being considered best we should go alone,
my companion and myself proceeded to his residence.
While on our way, I became very thoughtful how I should open my prospects to him.
Labouring under these discouraging impressions,
the saying of the great Master revived in my mind, "`Take no thought before hand,
what you shall speak,`"--accompanied with such power, that all my fears were dissipated;
I therefore endeavoured to keep in the quiet, and near the Divine power.

On reaching his house and inquiring for him, we were shown to his apartment,
and met with a very handsome reception.
After we had taken our seats, and answered a few questions he put to us,
I opened to him the business that had brought me there,
by telling him I understood he was a great slaveholder: to which he replied,
I was correct, he was a slaveholder,
having upwards of three hundred slaves in his possession.
I endeavoured to lay before him the injustice of holding his fellow creatures in bondage,
and to work upon his feelings, by urging him to be willing to place his own parents,
his children, his relatives, in a similar situation with his slaves, and liable,
at pleasure, to be separated,--near relatives far from each other,
during their natural lives; and thus to bring the matter home to his own mind,
how he would feel if he himself were placed under similar circumstances with his slaves.
I pressed upon him the necessity of doing his duty by them,
and to liberate them in his lifetime,
or if he did not choose to liberate them in his lifetime, I found I must query with him,
had he liberated them by his will?
to which he replied, he had willed his slaves to his children and grandchildren,
who would do as well by them as he had done.
I replied, that was more than he could assure himself of, inasmuch as,
though he might bequeath to his children and grandchildren great property,
he being reputed to be very rich,
he could not insure their being able to keep this great property together:
various were the ways Providence had power to make use of,
to strip them of all he might bequeath them,
and without any power on their part to prevent it;--the
slaves he left his children and grandchildren,
then, in all probability, must have new masters; and it was my firm belief,
should this be the case,
whatever sufferings his slaves were brought into in consequence of his
not doing his duty in liberating them while he had it in his power,
by will or otherwise, he would stand accountable to his Maker for.
I urged upon him, as he valued his immortal soul,
the importance of being willing to make this sacrifice.
He replied, "`Our views differ.`"
I again urged him,
to consider well the subject I had believed myself called upon to cast before him;
and to manumit his poor slaves while it was in his power,
and put them in a way to provide for themselves, as he was able to do it.
To which he replied,
that manumitting his slaves would be doing them a
great injury,--that they were lazy and improvident,
and not capable of caring for themselves, and would not be alive, if set free,
three or four years after they were liberated.
Now, he said, they were well fed, well clothed, received religious instruction,
he himself being a Catholic, and the spot they lived upon was so healthy,
they increased so fast,
that they were obliged at times to sell them off to other masters to reduce their stock;
and such as were what he called ugly, not very manageable,
were sent off to the slaveholders in South Carolina.
My companion told him, if their lot should be cast in the indigo works there,
they seldom survived three or four years; this seemed to make an impression on his mind;
he only replied they would be well cared for.

He spoke of his practice of separating parents from children, children from parents,
and near relatives from each other, when his slaves became too numerous for him,
or were difficult to manage,
with quite as much seeming indifference as a farmer
would speak of selling his calves from his cows,
or his pigs from their mother.
He again attempted to justify his conduct in not
being willing to grant his slaves their liberty,
by saying they were lazy, and that keeping them was a losing concern;
but afterwards he committed himself, by adding, he was afraid, in harvest time,
to employ white men, lest they should spoil his negroes,
saying the white men were drunkards and lazy; he preferred negroes in harvest time,
they being industrious and sober, were more to be depended upon than white men.

On his making these remarks, I told him, that from the last confession he had made,
he could not justify himself, on the ground he had attempted, in the sight of his Maker,
in leaving his slaves in bondage, as he intended to do;
and I urged him again to consider the subject I had proposed to him,
and while he had it in his power,
to liberate his slaves;--wishing him to consider what a precious testimony
against this practice of holding our fellow creatures in bondage,
he would leave behind him, when the separation took place between soul and body,
and his death was announced in the public newspapers,
if it could be said he had liberated all those he had held in bondage;
for he was not aware how much his example in this
respect might have an influence on the minds of others,
and promote the like conduct in them.
From the remarks he had unintentionally made, relative to the white men and negroes,
it appeared he was sensible he had committed himself, in a way he did not intend,
which prevented his making further efforts to justify his conduct.
We left him, well satisfied in giving up to this humiliating service,
and I was thankful in believing I had done all that was
required of me in the discharge of apprehended duty,
and had in this respect fulfilled the injunction of the apostle,
"`Be not partakers of other men`'s sins,
but reprove them;`" which cannot be the case in my view, if,
when our minds are brought under exercise on account of the conduct of others,
which our judgment is sensibly affected with a belief
is not in accordance with the will of God,
and we feel ourselves called upon to labour to bring them to a proper sense of it,
if we neglect so to do, from whatsoever cause our omission may arise,
we become implicated in degree with them in the Divine sight.
At parting, he treated us as he received us, with great politeness and civility,
offering himself to conduct us to the door.

Fifth-day morning, we left our kind friend James Carey`'s,
intending to go to Darby meeting on first-day; the rain falling very heavy,
we could not reach Havre-de-Grace that night, as we had proposed.
The next day, the prospect of pursuing our journey was discouraging,
from the great quantity of rain that had fallen during the night,
and its continuing to fall.
When we reached Havre-de-Grace, we had to pass the Susquehanna river,
about one mile over, the fog was so great we could not see many yards before us,
which made our crossing appear dangerous.
In consequence of the great quantity of rain that had fallen since our leaving Baltimore,
the rivers we had to ford had risen so as to make it dangerous to cross some of them.

On our approach to the first, we observed a stage-coach standing on the opposite side,
afraid to venture through; seeing us come up, the driver hailed us,
bidding us to come along, but I told my companion,
as he was the first at the river we must not let him profit by our experience;
and therefore we made a full stand, on which the driver ventured,
and by going through a field, avoided the deepest part of the water;
we kept a sharp look-out at the route he took, and taking the same,
we safely reached the other side.
A passenger in the coach kindly warned us not to attempt to cross
the next river without the assistance of a coloured man,
who had piloted them safely through, and whom we must hail from the other side.

On approaching the next river,
it made a more formidable appearance in width and strength of current;
we hailed the coloured man,
who came over a high foot bridge through the water to our assistance,
and driving our wagon some way round, brought us safe to the other side,
where we left travellers apparently afraid to venture over;
we found the best ford very deep and dangerous,
and were thankful when we reached land again.
This was called the Little Elk; we had yet the Big Elk still to ford,
which was considered the most dangerous.
There was a way round whereby we might escape fording this river;
but if we took this road, we should have to travel in the night to reach Wilmington,
if we reached it at all tonight,
which might endanger our getting to Darby timely for meeting on first-day.
I considered this subject in the best way I was capable,
feeling not a little the responsibility attaching to my
concluding to ford the river instead of going round.
As however I felt quite easy in my own mind to ford the river, we proceeded;
on our way we met a respectable man, and inquired of him,
if we could ford the river with safety; he informed us,
he believed the river was yet safe to ford; we therefore ventured;
the current was running very strong, and before we reached the other side,
for a short distance, the water was so deep our horses and carriage swam;
thankful I was when our horses found foothold again, and more so when we come to shore:
we were favoured to reach Wilmington safely about dark,
where we were kindly received by our friend Samuel Canby.

Seventh-day morning, 1st of twelfth month, 1827, we proceeded towards Darby;
this meeting had now become as disaffected as any in Concord quarter:
the prospect of sitting the meeting for worship tomorrow appeared trying.

Our kind landlord, Nathaniel Newlin,
entertained us in the evening with the following relation.
During the revolutionary war between Great Britain and America,
Friends`' meetinghouse at Darby was occupied by some of the American army,
but on Friends applying to the commanding officer for liberty to meet in it on meeting-days,
it was granted,
and the house was as well cleared at such times as
the situation of the army would allow of:
many of the army sat down with Friends,
the officers and soldiers sitting at the back part
of the house to make room for Friends at the front;
they conducted themselves in a solid manner:
at the first of Friends`' sitting down to hold their meetings,
the swords and other accoutrements of war that hung about the walls of the meetinghouse,
appeared terrific; but in time these feelings were much lessened,
and their meetings were times of Divine favour.

First-day morning, we walked to the meeting, which was large;
I had such close things to deliver,
that I was ready to fear it would have stirred up opposition
from some in the ministry who were of the disaffected party;
but, as my dear companion observed after meeting,
the opposing disposition was chained down.
The behaviour of some young people was so reproachful,
that I was brought under the necessity of noticing it;
disorderly behaviour in meeting among the young men more particularly
prevails where this disaffection has taken place.
We had various invitations to dinner when meeting broke up; one individual,
who afterwards in public print endeavoured to vilify my character, importuned me much;
but it appearing safest to keep out of harm`'s way, we returned to our quarters.
In the afternoon we rode to Philadelphia,
where we were kindly received by Thomas Stewardson and his attentive family.

Second-day, visited the Friends`' Asylum for persons disordered in their minds;
the house is commodious, the grounds for the patients are extensive,
and laid out agreeably, and the situation is healthy;
there appeared no lack of any thing likely to add to the comfort
of the patients in the various circumstances of their malady.
The next morning, attended the north meeting; after the meeting for worship,
an adjournment of the Monthly Meeting was held, many cases were before it of individuals,
who had united themselves to the new Yearly Meeting held in this city;
testimonies of denial were ordered.
Friends appeared to act with great caution, and with unanimity in these sorrowful cases,
manifesting a right concern for their erring brethren.

Fourth-day, attended Pine street meeting, at which there was a marriage;
it proved to me a quiet, favoured meeting:
in the afternoon we crossed the river Delaware into New Jersey,
and were kindly cared for by our friend Benjamin Cooper and his family.

Attended Chester Monthly Meeting, held at Moore`'s-town:
a separation had taken place in this Monthly Meeting,
but Friends and the Hicksites still meet together in a meeting for worship.
When the meeting for worship closed, Friends continued to keep their seats;
the clerk of the Monthly Meeting, having united himself to the Hicksites,
kept possession of the books, and taking his seat at the table,
had the advantage of Friends, and opened their meeting first.
Friends sat quietly,--there appearing no other way under
the trying circumstances in which they were placed.
After the clerk of the Hicksite Monthly Meeting had read the opening minute,
one of the Hicksites called for my certificates;
pausing on the request that had been made, I stood up, saying,
as I did not consider those who were now about to transact Monthly
Meeting business the legitimate Monthly Meeting of Chester,
I could not offer my certificates to them, and here the matter closed;
except that one of their party replied,
my services in the meeting for worship had been acceptable,
but expressing myself as I had done,
by not allowing them to be the legitimate Monthly Meeting,
I must be acting under the influence of the evil power;
silence to these observations appeared to be my duty.
When the Hicksites had done their business they quitted the house,
and Friends proceeded quietly with theirs, and the meeting closed comfortably.

After meeting we proceeded to Evesham,
and took up our abode at my kind friend Job Haines`',
who had offered to release my companion James Brown,
he believing the time to be come when it would be right for him to return to his family;
we, having travelled together in much harmony and Gospel fellowship,
now took an affectionate leave of each other:
this separation at first felt like a stripping time to me.

Sixth-day, attended the Monthly Meeting held at Upper Evesham,
where I met with my country folks, George and Ann Jones;
and the Quarterly Meeting`'s committee gave their attendance.
No separation had taken place in this Monthly Meeting, the clerk being with Friends,
the business went on in its regular course; several cases were on the books,
of those who had united themselves to the Hicksite Yearly,
Quarterly and Monthly Meetings.
The business of the meeting appeared to be conducted under
much concern for the welfare of the cause of Truth,
and we separated with feelings of gratitude,
and a sense that best Help had been near in transacting
the several matters that came before the meeting.

Seventh-day, 8th of twelfth month, attended the Monthly Meeting of Evesham;
no division having taken place in this Monthly Meeting,
in appointing representatives to the Quarterly Meeting,
the names of some were brought forward who had attended the Hicksite Yearly Meeting,
which names were objected to by Friends: all quietly passed on,
and a nomination made of Friends for that purpose:
the meeting closed under feelings of thankfulness
for the Divine help that had been extended.

After meeting we rode towards Cropwell,
and had a very full opportunity with a Friend and his wife,
whom we could not doubt were well-meaning individuals,
but in danger of being drawn aside by the Hicksite party,
by having attended some of their meetings; the woman,
at times with tears flowing from her eyes,
expressed the earnestness of her desire that she might be preserved doing what was right,
either remaining with the Monthly Meeting she now was a member of,
or to join the new Monthly Meeting that was set up, adding,
she was wearied with the contention which of late had prevailed among Friends.
The man appeared more decided at first, and,
as if he had fully made up his mind to become a member of the new Monthly Meeting,
and yet open to hear what we had to offer on the subject: at our retiring to bed,
he manifested a willingness to enter again into the consideration of consequences,
if he pursued his determination of joining the new Monthly Meeting:
my companion meeting with the man next morning,
who told him he had passed a sleepless night; this afforded me some hopes he yet might,
in mercy, escape the snare.

First-day, we attended meeting at Cropwell, it was large;
a considerable portion of which consisted of young people:
the religious labour which fell to my lot in this meeting,
was to guard Friends against the danger of associating with that spirit that is at work,
to cause rents and divisions among us,
and to call their attention to an observance of the
fruits which this spirit has already brought forth,
fruits as opposite to the doctrines and precepts of Christ as light is to darkness:
the meeting was held in great quiet,
the young people keeping their seats until the meeting closed.
After taking our dinner, we rode to Hannah Hopkins`', where we were kindly cared for.

Second-day morning, attended the Monthly Meeting at Haddonfield, which was large,
occasioned by the Quarterly Meeting`'s committee being there,
also some who called themselves members of the new Yearly Meeting in Philadelphia,
and from other meetings in connection with that Yearly Meeting.
I arose on my feet with these words;
"`Fret not yourself because of evil doers;`" having the language
of encouragement given me to hold out to the willing in Israel,
who might be ready to let go their dependence on
that Divine Power which hitherto has sustained them,
not to yield to the enemy`'s insinuations, and conclude their way is hid from the Lord,
and their judgment passed over from their God;
but to be willing to ponder the fruits brought forth by this dividing
spirit which had so sorrowfully entered into our borders:
for by bringing their fruits to that Light which
gives a clear discernment in things Divine,
it will be fully manifest that they are not wrought in God,
and therefore will in due time come to naught.

When the meeting for business opened, great confusion took place;
some members of the Monthly Meeting,
who had been active with others in setting up new meetings,
and locking Friends out of their meetinghouses, offered a paper to be read,
which the meeting stood firm against.
When they could not prevail in this way, one of the advocates for its being read,
informed the meeting, the paper contained a proposal to the Monthly Meeting,
that those who had become members of these newly set-up meetings,
should have liberty to withdraw from the Monthly Meeting without the odium
being attached to their character of being disowned by the Society:
this compromise, could they have prevailed on Friends to yield to it, it was apprehended,
would entitle them to a part of the property of the Monthly Meeting.
Before the meeting closed, one of the disaffected party invited all who were willing,
after the Monthly Meeting was over, to remain to hear the paper read,
and went into the women`'s house, giving the same invitation.

Fourth-day morning, the Select Quarterly Meeting for Haddonfield was held,
which at the commencement was trying, occasioned by some men and women,
part of a committee appointed by the Hicksite Yearly Meeting, to visit the Quarterly,
Monthly, and other meetings of Friends, being in attendance at this Select Meeting,
and refusing to go out of the meetinghouse;
but as it became evident that the general voice of
the meeting was opposed to their remaining,
they withdrew; after which the business of the meeting was quietly proceeded in.

Fifth-day morning, 13th of twelfth month, the Quarterly Meeting for discipline commenced.
Friends having been so interrupted in their proceedings
at the Quarterly Meeting in the ninth month last,
by those who had united themselves to the Hicksite Yearly Meeting,
had concluded it best for the present to suspend the meeting for worship,
heretofore held previously to entering upon the business,
in order to prevent such difficulties in future as had then occurred;
and they appointed a suitable number of doorkeepers to attend
at the doors of the men`'s and women`'s house,
to keep these meetings select:
the doorkeepers made fist the back-doors of the meetinghouse,
expecting to have much opposition to contend with at the front-doors,
as they might be equal to; but some members of this Quarterly Meeting,
who had united themselves to the Hicksite Yearly Meeting,
and been active in setting up new Quarterly and Monthly Meetings,
whose cases had not yet been brought before the Monthly Meeting,
were early in their attendance at the house, and unfastened the back-doors,
and let into the meetinghouse, those whom the doorkeepers had refused,
as having forfeited their membership in the Society.

The meeting being gathered, the clerk opened the business,
after which several Friends requested that those
who had no claim to sit in that Quarterly Meeting,
would leave the meetinghouse;
but with these requests they manifested a determination not to comply,
the Hicksite party ordering the clerk to quit the table,
saying they had nominated a clerk of their own,
whom they directed to take possession of the Quarterly Meeting books.
From the contention and determined spirit which the Hicksite party manifested,
I was led to fear they would have used force to gain their point in obtaining the books.
Friends however manifested calmness and composure through the whole of this trying scene,
and after considerable exercise of patience, as no persuasions were of any avail,
they concluded it would be best to adjourn to sixth-day morning.
This proposal met with violent opposition from the Hicksite party,
and when two men Friends went into the women`'s meeting to inform them of the adjournment,
two of the Hicksite party followed them,
declaring the larger number of the meeting was opposed to this adjournment,
and intended to go on with the business of the Quarterly Meeting;
but not being received as official messengers,
the women`'s meeting adjourned to the same time.
Before the adjournment could be read, one of the Hicksite party stood up,
and requested such as chose to stop,
to remain in the meetinghouse and transact the business of the Quarterly Meeting.
After the adjournment was read.
Friends quietly retired.

Matters now ran high against the English Friends who were
engaged in religious service on this side of the Atlantic.
In one Quarterly Meeting, the enmity against them was such,
that proposals were made by the Hicksite party,
that such minutes as were on the books of that meeting,
acknowledging our certificates being presented should be cancelled,
or a minute made expressive of the meeting`'s dissatisfaction
with our movements among them.
I found it very needful, not only to aim at patiently enduring all things,
but also to be especially careful that no root of bitterness was
allowed to spring up in my mind against the authors of such evil
and unfounded reports as they were circulating respecting me.

Sixth-day morning, Friends again met, free from interruption from the Hicksite party;
the time of silence previous to entering upon the business was a solemn season,
the business that came before the meeting was conducted in much harmony,
and Friends separated under a thankful sense,
that Divine aid had been mercifully extended towards us at this time.

Seventh-day, we proceeded towards Great Egg Harbour,
and on first-day attended meeting there.
This is a very small meeting of Friends,
yet the house was nearly full by the coming in of those not of our Society,
who conducted themselves in a solid manner.

Second-day, 17th of twelfth month, had a meeting at Galloway,
appointed for members and attenders of meetings.
When the meeting was gathered,
it was evident the invitation had been extended beyond my request,
which plunged me into fresh exercise,
that I might be preserved keeping my proper place in this mixed assembly.
I was led to hope,
that the labour of this day would not all prove like the seed that fell by the way-side;--not
doubting that the hearts of some of our company were prepared by the good Husbandman,
to receive with gladness what had been given by Him for communication.
In the afternoon we made a visit to a Friend upwards of ninety years of age,
whose faculties appeared bright,
but who exhibited as striking a picture of suffering humanity, as most I have met with;
a cancer had entirely destroyed one of his eyes,
and was proceeding rapidly towards the other,
and he was reduced in body to little more than skin covering his bones:
but amidst all his sufferings, not a murmur, not a complaint was uttered;
such was the quiet, peaceful state of his mind, that it was instructive to sit with him;
a striking confirmation of the language of the Psalmist:
"`You will make all his bed in sickness.`"

Third-day, we proceeded to the township of Washington, near the Mullicus river,
and took up our abode with David Mapps and his kind wife, both coloured people,
and members of our religious Society:
we attended an indulged meeting in a new meetinghouse,
about three miles from our quarters, at a place called Bridge Port.

Fourth-day morning, we left the comfortable residence of our kind friend David Mapps,
who accompanied me to Little Egg Harbour.

Fifth-day, we attended meeting at Tuckerton;
where there are but few members of our religious Society,
yet the house was much crowded by the coming in of those not in profession with us,
many of whom we understood were at the meeting at Bridge Port yesterday,
and had come nine miles to attend this meeting; they sat in much quietness:
after meeting we rode to Barnagat, where there is a small settlement of Friends.
As the way did not clearly open in my mind to have a meeting here,
I felt it necessary to say so much to our kind companion.

Sixth-day morning, before our departure, I was given to understand,
that our not having a meeting with Friends was a disappointment to them;
but it appeared right for us to proceed on our journey; which we accordingly did,
accompanied by David Mapps, whose services we found to be of great use to us,
our road being through a wilderness country, and so very intricate,
it was with great difficulty we made our port before it was dark.

Seventh-day, we proceeded to Squankum,
where a meeting was appointed to be held at the eleventh hour this morning:
I was led to hope a degree of religious sensibility had
been afresh awakened in some minds that were present;
the meeting separated much in the quiet, and afterwards we rode to Shrewsbury.

First-day morning, were at Shrewsbury,
which I was informed was more largely attended than has been the case of later times;
many who were not in membership,
but had been in the constant practice of attending this meeting,
had withdrawn in consequence of the unsound doctrines
which at times the Hicksite preachers held forth.
During the time of silence, I could not doubt, that many who were present,
experienced the silence of all flesh and the meeting
separated with feelings of holy solemnity,
which is the crown of religious gatherings.
We passed by Monmouth and Crosswicks to Bordentown,
where we met with part of a committee of the Quarterly Meeting.

It being the day their Preparative Meeting was to be held,
several of the disaffected party from other meetings
were present to assist the members of this meeting,
all of whom but one young man had joined the new Yearly Meeting,
in opposing the proceedings of the Quarterly Meeting`'s committee.
Before the meeting for worship had sat nearly its usual time, the members of the meeting,
except this young man, and the Hicksites from other meetings, rose up in a body,
left the meeting, and went up into the chamber where the men transact their business,
stamping with their feet as they proceeded; this young man, the committee, and myself,
following them, but before we could reach our seats,
the clerk was reading his opening minute.
I could not avoid remarking on their disorderly proceedings
in breaking up the meeting for worship,
but a determination was manifested not to regard any thing that could be offered.
One of the Quarterly Meeting`'s committee, on behalf of the whole,
queried with the clerk,
whether he was acting as clerk to the Preparative Meeting of Bordentown,
established by the Monthly Meeting of Crosswicks,
and in subordination to the Quarterly Meeting of Burlington; but these remarks,
although again repeated, were treated with evident contempt,
replying they knew of no Quarterly Meeting`'s committee.
After hurrying through the business of their meeting,
they arose in as disorderly a manner, as was the case in the meeting for worship,
went away, and left the committee, the solitary young man, and myself, on our seats.
We understood the women`'s meeting was not in a much better state.

Fifth-day, attended meeting at Crosswicks; it being Preparative Meeting,
the clerk took his seat at the table: but as the clerk,
with many more of the members of this meeting,
had been assisting in setting up separate meetings,
the committee of the Quarterly Meeting put the same
questions as were put to the clerk at Bordentown.
Some of the Hicksite party replied,
they had nothing to do with any Quarterly or Monthly Meeting`'s committee,
ordering the clerk to go on with his business.
Friends consulted together,
and being satisfied it was the business of a new Preparative Meeting they were transacting,
concluded to adjourn to a Friend`'s house near,
and choose a fresh clerk and transact the business in its regular way,
leaving their old clerk in possession of the books and papers of the meeting;
the women being informed of the proceedings of the men`'s meeting, adjourned also;
the day being stormy, and the cold as severe as had been known this season,
made it very trying to both men and women to have to turn out of their warm meetinghouse,
and seek a place to do the business of the meeting in.
By procuring some planks, with the help of the chairs in the family,
who so kindly accommodated us, we soon became settled down again,
and Friends were favoured to get through their business with satisfaction.
Six of the cases of those who had been most active in the disorderly proceedings,
were ordered to be carried forward to the Monthly Meeting, and the meeting concluded,
if a more suitable place could not be found,
to meet again at the same place to hold the next Preparative Meeting.
After this meeting we rode to Evesham.

The following interesting narrative was given me by a Friend, respecting Edward Andrews,
the father of Peter Andrews, mentioned in John Woolman`'s journal,
who was the first member of our Society that settled in Little Egg Harbour,
and the instrument in settling a meeting there.
Before Edward Andrews became convinced of the principles of Friends, he kept a boat,
and played the violin on board his boat,
to collect people for the purpose of dancing and frolicking.
One day when on shore in his walks, a human bone lay in his path, which he took up,
the viewing of which produced such serious impressions on his mind,
that he never was able to get from under them; he buried the bone.
These serious impressions increased,
and led him to take such a clear view of the danger of pursuing
his mode of conduct and manner of obtaining a livelihood,
that he burnt his violin, forsook his old course of life,
and became convinced of the principles of Friends.
He did not hastily make a change in his outward garb,
and before any material alteration took place in this respect,
his mouth was opened in the ministry.
Apprehending himself called upon to have a meeting appointed
at Crosswicks for those of other religious societies,
he informed Friends thereof, but they could not then allow of his having such a meeting.
On his way home, after his friends had put his concern by,
he stopped at a brook to water his horse, and while his beast was drinking,
the following considerations passed his mind: If this stream,
at which his horse was then drinking, was a living stream,
was it possible that man could wholly stop its progress?
It was presented to his mind that it might be dammed up for a while,
but even if this was the case, in time it would find its way over the dam,
or make its progress through some other channel.
These considerations, under his then trying situation, proved instructive to his mind,
and he was led to conclude that if the concern which he had cast before his friends,
proceeded from the living fountain and spring of Divine Life and Light,
and if he was careful to keep in the faith and patience,
in due time way would open in the minds of his friends
for him to have a meeting at Crosswicks,
which accordingly proved to be the case; and it was supposed to be this meeting,
which Edward Andrews afterwards had at Crosswicks,
that Abraham Farrington alluded to when he said,
that Edward Andrews was the first instrument, in the Divine hand,
of proclaiming in the ear of his soul the awakening call,
by attending to which he was brought into a nearer
acquaintance with the truths professed by Friends.
These circumstances are well worthy the notice of such,
who may be placed in a similarly trying situation.

First-day morning, attended Newtown meeting, which I understood was larger than usual;
it was supposed this was occasioned by two of the Hicksite
preachers being at this meeting on that day,
steps having been previously taken to publish the same.
Although the prospect of sitting a meeting with these
two individuals felt trying to my mind,
yet by endeavouring to do what my hands found to do in the meeting,
I left well satisfied that I had been there: in the evening we rode to Joseph Whitall`'s,
near Woodbury.

Second-day, we attended Monthly Meeting at Woodbury;
after the meeting for worship was over,
and previous to the business of the meeting for discipline being proceeded in,
it being known to Friends there were persons present who had been disowned,
and others of this meeting who were under dealing,
in consequence of their having united themselves to the Hicksite party,
a request was made to such to withdraw;
but this they in a very determined manner refused to do,
treating the committee of the Quarterly Meeting and
some of the members of the Monthly Meeting,
in a very abusive manner.
After much exercise of patience, and they continuing to persist in refusing to withdraw,
Friends were brought to the necessity of adjourning their business to a future day,
and of leaving the disaffected party in the meetinghouse,
going on with the business of their new Monthly Meeting.
After meeting we rode to Scull-town,
and were kindly received by our aged friend Sarah Scull.

Third-day morning, 1st of first month, 1828,
we rode to Pilesgrove to attend the Monthly Meeting there;
the meeting for worship was large.
I found it hard work to obtain relief to my mind amidst
so many evil spies as this meeting was composed of;
there being a close eye kept by the disaffected party upon
English Friends who are travelling in the work of the ministry,
if possible to detect any thing about them in word or deed to make use of to their disadvantage.
In the meeting for worship,
a young man towards the middle of the house stood up while I was on my feet,
and opposed what I advanced in the meeting;
silence to me appeared the safest reply to make to him.
The meeting for worship being over, the clerk of the Monthly Meeting,
who had joined the disaffected party,
taking possession of the table to go on with their business,
the same individuals being present who were at Woodbury, and some of Pilesgrove meeting,
who were under dealing.
Friends requested they would withdraw;
but the same determined spirit was manifested by them, as was yesterday;
and after much exercise of patience on the part of Friends,
and having to endure many insults,
they sat quietly until the disaffected part of the meeting had finished their business.

When they left the house,
Friends nominated a clerk to go on with the business of the Monthly Meeting,
but their numbers, both men and women, were so much reduced,
it became a subject of consideration whether it would not be most
advisable for the present that men and women should meet together:
the men accordingly adjourned to the women`'s meetinghouse.
The young man who had publicly opposed me in the meeting for worship,
came into the women`'s house and sat down among us, with a seeming air of contempt,
as if in his own mind he was disposed to say, "`What can these feeble Jews do?`"
Our sitting together was a truly humbling, heart-tendering season to most, if not all,
of our little company; before the meeting closed,
this young man`'s countenance was evidently changed.

When the meeting closed I followed him out of the house, telling him,
I wanted to give him my hand of love,
at which he immediately advanced towards me and gave me his hand.
I then informed him that in this last meeting we had sat together,
the secret prayer of my soul to the Lord on his account had been,
that He would be pleased to lay His hand upon him,
that he might be constrained to remain with the little company
he had last sat with in a Monthly Meeting capacity:
this he appeared to receive with marks of respect,
assuring me it would afford him great pleasure if
I would give him my company at his own house;
but as I did not feel it would be safe for me to give any such expectation,
I told him I was obliged to him, and we parted.
After meeting, we rode to Salem.

Fourth-day morning, attended meeting here; the meeting for worship being over,
the clerk took his seat at the table and opened the Monthly Meeting,
the company we met with at Pilesgrove and other meetings,
of disowned persons and those under dealing being present,
were requested to leave the meetinghouse; to which a violent resistance was manifested,
some of these declaring their determination to maintain
their right to a seat in that house to the last,
making use of as insulting and provoking language, as words could well furnish,
in which I was not excused from a share.
They manifested as bitter and ranting a spirit as the Keithites^
footnote:[Followers of that sad apostate George Keith.]
in early times,
and a determination to worry Friends out of their property in their meetinghouses,
declaring their intention, if possible, to secure possession of them.
After Friends had borne with them nearly three hours, hearing their scurrilous language,
they adjourned the Monthly Meeting to sixth-day.

After the adjournment we rode to Greenwich; the waters in places were very much raised,
which made it dangerous for us to pursue our journey,
but we reached our friend John Sheppard`'s in safety;
this I esteemed among the many favours a kind Providence
has showered down upon me during my travels in this land.

The next day we attended Greenwich Monthly Meeting;
which consists of two Preparative Meetings, Greenwich and Alloway`'s creek:
when the meeting for worship closed,
Friends entered upon the business of the Monthly Meeting.
It was known to Friends,
that in Alloway`'s creek a large proportion of the members favoured the separatists,
but it was not at this time supposed that they were
in such a state as to be determined on a separation;
it afterwards appeared, however,
that a couple from Alloway`'s creek meeting had passed
the Monthly Meeting in order for marriage,
and some of the members of Alloway`'s creek were
appointed to inquire into the clearness of the parties,
and report to this meeting.
One of the members of that meeting being present, he was called upon to report,
to which he replied a report would be made at another place,
handing a paper to the clerk, saying,
the Preparative Meeting of Alloway`'s creek had ordered him to be the bearer of it.
The purport of the paper was a request to the Monthly Meeting,
that the Preparative Meeting of Alloway`'s creek should become
a Monthly Meeting separate from Greenwich Monthly Meeting.
It afterwards appeared,
that the members of Alloway`'s creek meeting who favoured the separatist party,
had already taken this step, and were sitting as the Monthly Meeting of Alloway`'s creek,
and transacting business as such,
at the very time this paper was presented to the Monthly Meeting,
and which newly set-up meeting received the report relative
to the couple that had passed the previous Monthly Meeting.
After the paper had been read,
as the meeting could not unite with the proposal of Alloway`'s creek meeting,
a committee was appointed to visit that Preparative Meeting,
on which the bearer of this paper left the meeting, uttering aloud a sort of petition,
in which he made use of the Lord`'s name in a disposition
of mind that brought a sort of chill over my whole frame.
Although this was an exercising meeting,
yet I felt well satisfied in having to enter a little into the sufferings,
which this small part of the body had this day, and may have more fully, to pass through.
I had been looking towards the Monthly Meeting of Maurice river,
but on being informed that, except two families,
the whole meeting had joined the separatists,
it appeared best to relinquish my prospect of attending it.
After meeting we rode to Salem,
but did not reach our kind friend William F. Miller`'s until late.

Sixth-day, attended the adjournment of Salem Monthly Meeting.
First-day, attended the meeting at Evesham,
Friends not having yet separated from the Hicksites in their meeting for worship.
It felt trying to sit down in a meeting capacity with those who
are not only unsound in the fundamental doctrines of Christianity,
but in spirit bitter enemies to our religious Society;
yet when I at times compare my situation with that
of my friends on this side of the Atlantic,
myself only a sojourner for a short time, they residents here, to endure, it may be,
a long continuance of these trials,
and the varied scenes of suffering that may grow out of
the schism which has been made in our religious Society,
I thought my present trials would hardly bear to be brought into comparison with theirs.
I see no other way for me but to labour to stand resigned to the Great Master`'s will,
either to keep silence or to be found in the faithful exercise of no gift,
in doing which I do not know I ever was made more fully
sensible of the truth of the language of one of the apostles,
"`When I am weak, then am I strong.`"
In the afternoon we rode to our kind friend John Cox`'s near Burlington.

Second-day, 7th of first month, attended Monthly Meeting at Burlington;
when the meeting for worship closed, as it was not known that there were any present,
who had not a right to a seat in that meeting,
the clerks proceeded with the business of the Monthly Meeting,
which was quietly gone through; but before the meeting separated,
one of the members of the meeting stood up,
and requested that those who were favourable to the newly organized Yearly Meeting,
held in Philadelphia in the tenth month last,
would stop in the meetinghouse when the meeting closed,
in order to organize a Monthly Meeting in connection with that Yearly Meeting.
When the Monthly Meeting closed.
Friends quietly withdrew,
leaving such of their members as favoured this new
Yearly Meeting in possession of the meetinghouse.

Third-day morning,
we rode to Crosswicks to attend the Monthly Meeting to be held there this day;
the meeting for worship being over, the clerks opened the Monthly Meeting,
when a Friend arose and requested, as there were so many strangers present,
if there were any who had not a right to sit in that meeting
in consequence of having been disowned by the Society,
or being under dealing by their Monthly Meeting, they would leave the house.
No individual arose to leave the meeting, and after Friends had waited awhile,
the meeting went on with its business for about half an hour, when a person stood up,
saying,
he was a member of a Monthly and Quarterly Meeting that was not
known to the Yearly Meeting of Friends of Philadelphia;
on which he was requested to withdraw, but this he refused to do.
The meeting continuing to press the matter,
he persisted in his determination to keep his seat,
in doing which he was encouraged by the strangers,
and by some of the members of the Monthly Meeting.
Aware that no entreaty would be of any avail,
it was concluded to adjourn to a Friend`'s house about two miles from the meetinghouse,
where some provision had been made for holding the Monthly Meeting,
should Friends be obliged to leave the house;
this I found was not an unexpected circumstance to some of the members of the meeting.

The weather being very stormy, the rain freezing as it fell to the ground,
made it trying to walk, and dangerous to ride,
the horses being hardly able to keep upon their feet.
The men occupied a large kitchen, and the women an adjoining room,
and soon settled down into quiet again;
it was supposed about three-fourths of this Monthly Meeting remained behind in the meetinghouse.
The cases of some of their members who had been active
in assisting to establish the new Yearly Meeting,
in the tenth month last at Philadelphia,
were brought from the Preparative Meetings to this Monthly Meeting,
and appointments made to visit them;
and after the business of the meeting had been conducted in much harmony and firmness,
that the discipline might be put in force against offenders without partiality,
the meeting concluded to meet again at this place next month.

Fourth-day, attended Monthly Meeting at Upper Springfield;
here we also had the same company of intruders as
obliged Friends yesterday to quit their meetinghouse:
the meeting for worship being over, the clerks took their seats at the table,
and opened the Monthly Meeting;
those who had not a right to sit in the Monthly Meeting
were requested to leave the meetinghouse,
but they manifested a determination to remain,
in which determination they were encouraged by some of the members of the meeting.
Friends finding their entreaties were in vain, concluded to adjourn to the school-house,
on the meetinghouse lot, informing the women`'s meeting thereof;
on which one of the separatists`' party went into the women`'s house,
ordering the women to keep their seats,
saying the business of the men`'s meeting was about to be proceeded in.
As the school-house furnished only one apartment,
the men and women held a consultation there about a place
to meet in to do the business of the Monthly Meeting;
the extremity Friends of this meeting found themselves placed in,
had a humbling effect on many minds, especially on the female side of the house,
some of whom were contrited unto tears,
doubtless in part from the painful circumstances some were placed in,
having left near connections remaining with the sorrowfully deluded multitude.
After Friends had quitted the warm meetinghouse,
and stood as long together as they were well able to do in this comfortless place,
the weather being very severe and no fire,
it was concluded to hold the Monthly Meeting next sixth-day at Mansfield:
we went home with our kind friend William Newbold.

Fifth-day, we proceeded to Mount Holly;
in this Monthly Meeting a separation had already taken place,
and Friends were driven out of their meetinghouse,
and obliged to meet in a school-house, to hold their meetings for worship,
the men`'s Monthly Meeting being held in the academy:
about fifty males and females remain with Friends.
The clerks and registrars of this Monthly Meeting were gone off with the separatists,
who have kept possession of all the books and papers of the Monthly Meeting.
The newly chosen clerks, with the assistance of the Quarterly Meeting`'s committee,
managed to get through the business with more dispatch than might have been expected:
several cases of delinquency, in consequence of the separation that had taken place,
were brought forward by the Preparative Meeting of Mount Holly;
and the state of the Preparative Meetings of Vincent-town and the Mount came under consideration;
in one of these meetings it appeared, that all the members except one,
had joined the separatists, and in the other only three remained with Friends.

After mature deliberation, the meeting concluded,
it would be most to the reputation of the Society
to dissolve these two Preparative Meetings,
and join them to Mount Holly:
the meetings for worship at Vincent-town and the Mount came next under consideration,
and it appearing to the meeting best that these two meetings should be discontinued,
minutes were made accordingly;
and as the Monthly Meeting had not the control of
these meetinghouses of Vincent-town and the Mount,
those Friends in the neighbourhood were advised, as opportunity was afforded,
to make it publicly known,
that the Monthly Meeting had directed these meetinghouses should be shut up,
in order that the Society should not be made accountable for any
doctrines that in future might be advanced in either of them.
The little company left to contend with a host of strong, self-willed members,
had a warm claim on the sympathy of their friends:
I thought it was manifest they were falling into the ranks of the willing in Israel,
and my soul could salute them as such, and bid them God speed.

Sixth-day, attended Evesham Monthly Meeting, a separation having taken place.
Friends were favoured to hold their meeting in quiet;
yet not without an increase of suffering of mind from the numerous cases
of delinquency that were necessarily brought to the Monthly Meeting,
and the prospect of the hostile treatment they had to expect in
performing the duty which the meeting committed to their charge.

The next day I attended Monthly Meeting at Upper Evesham.
The meeting for worship being over, the clerks took their seats at the table,
and opened the Monthly Meeting.
This Monthly Meeting had not separated,
and it appearing to the meeting there were none of those
present who had so disturbed the other Monthly Meetings,
the meeting went quietly on with its business.
When it was finished, one of the members laid a paper on the table,
and requested that it should be read;
on which it was proposed their usual practice should be resorted to,
of nominating some Friends to go out of the house, examine the paper,
and inform the meeting if it was proper to read it in the meeting.
Four Friends were accordingly nominated, who returned with the paper,
giving it as their judgment, that it was not proper to be read in the Monthly Meeting.
After a pause, one of their members replied, as the paper was not allowed to be read,
he requested those who were in favour of the newly organized Yearly Meeting
in Philadelphia would keep their seats at the close of the meeting,
in order to choose a clerk and to establish a Monthly Meeting of their own.
Friends quietly withdrew, leaving, it was afterwards ascertained,
a few men and boys behind in the meetinghouse.
After meeting, we rode to our kind friend Joseph Evans`'s, at Cropwell.

First-day, 13th of first month, attended Haddonfield meeting: the meeting was large,
and settled down in quiet; it proved a time in which the promise of the Great Master,
might, with reverent gratitude be said to be fulfilled.

Second-day morning, attended Monthly Meeting there, which was large;
a considerable number, both men and women of the separatists,
said to be part of a committee of their new Yearly and Quarterly Meeting, attended;
the clerk took his seat at the table, and opened the Monthly Meeting.
After this was done,
the meeting was informed that there were present several individuals, who,
according to the discipline of the Society,
were not entitled to sit in that Monthly Meeting while the business was proceeded in,
some of them having been disowned by other meetings,
and others were under dealing by this Monthly Meeting.
Friends, in as tender and persuasive a manner as possible, requested them to withdraw;
but they refused,
although entreated to do so by several of the members of
the Monthly Meeting and Quarterly Meeting`'s committee,
declaring their determination to keep their seats.
They were headed by an individual who once stood well with Friends as a minister,
but who has united himself to the body of separatists,--a
man of goodly appearance and manners,
and thereby calculated to do more towards the furtherance of this schism,
than those who are attempting to effect their purposes by outrage.
Respecting him it might truly be said, his words were smoother than butter,
yet it was evident war was in his heart, and though softer than oil,
yet were they like drawn swords.
After having spent more than two hours in trying to prevail on them to leave the meeting,
amidst great abuse,
and after that exercise of faith and patience necessary
to be experienced under such trying circumstances,
if preserved from mingling with that spirit in which they were evidently acting,
Friends proposed an adjournment of the meeting.

The women`'s meeting sent a deputation into the men`'s meeting,
for advice how to proceed under the trying circumstances their meeting was placed in,
by a number of women who had intruded themselves into their meeting,
who had no right to a seat there, some of them having been disowned,
and others of them being under dealing by the Monthly Meeting,
and who would not leave the house;
they were informed of the men`'s meeting being in the same situation,
and when the men`'s meeting had concluded on what steps it was
best to take to extricate them from their present difficulties,
the women`'s meeting would be informed thereof.
As no other way appeared for the relief of the meeting,
it was concluded to adjourn to next second-day,
and a Friend was directed to inform the women`'s meeting thereof;
on which the intruders ordered one of their party to go into the
women`'s meeting and request the women to keep their seats,
as the business of the Monthly Meeting was about to be proceeded with.

Before the adjournment was read, a young man,
apparently not much more than twenty years of age, stood up,
calling upon the overseers to take notice of all
who left the meeting when the adjournment was read:
before which, one of the separatists informed Friends,
if they would assure them they should have one of the meetinghouses
belonging to the Monthly Meeting to hold their meetings in,
they would quietly leave the house,
and that they were willing Friends should have the liberty
of choosing which they were desirous of retaining for themselves:
but they were informed no such compromise could be made:
the doorkeepers being sound with Friends,
they knew they had no means of keeping Friends out of their meetinghouses,
as is the case when, by their varied artifices,
they can bring the doorkeepers over to their party.

Third-day morning, we rode to Moore`'s-town, to attend Chester Monthly Meeting:
a separation having already taken place in this Monthly Meeting,
our prospect of a quiet meeting was cheering to the mind:
the meeting for worship was a solemn time,
and the concerns of the Monthly Meeting were conducted
with becoming deliberation and solemnity;
the clerk of the Monthly Meeting,
and those appointed as registrars having joined the separatists,
were in possession of the books and papers,
and persisted in refusing to give them up to Friends.
After meeting, my friend Job Haines returned home,
whose kind services I desire ever to keep in remembrance.
The next day, proceeded to Philadelphia; and fifth-day,
attended Arch street Preparative Meeting,
comforted in being able to sit down with Friends again in quiet, after so much warfare.
