== Chapter XXXVI.

Sixth-day, 18th of first month, 1828, attended the Meeting for Sufferings:
various trying circumstances, in consequence of the outrages,
which the separatists were committing, came before the meeting,
and were deliberated upon and spoken to, I could not doubt, in a Christian spirit.

First-day morning, attended Twelfth street meeting, which was large;
in the afternoon the North meeting--a full attendance for an afternoon, and a quiet,
favoured time.

Second-day, crossed the Delaware,
and was met on the other side by my kind friend Benjamin Cooper,
whom I accompanied to Haddonfield, to attend the adjournment of the Monthly Meeting:
we were favoured with a quiet, comfortable meeting; such a one,
the Friends acknowledged they had not for a very long time witnessed.
After meeting, I returned again to Philadelphia.

The next day, attended the Northern District Monthly Meeting.
Notwithstanding doorkeepers were appointed to keep the meetings for discipline select,
a person under dealing escaped their vigilance,
and managed to take his seat in the Monthly Meeting:
after the clerk had opened the meeting, a request was made,
in as kind a manner as words could well be found to do it,
that if there were any present who had not a right to sit in that meeting,
they would withdraw; on this request being repeated without effect,
the request was made in more plain and pointed terms,
which aroused the individual from his seat,
who positively asserted his right to sit there,
and his determination not to quit the meeting: Friends, not willing to resort to force,
adjourned the meeting until the afternoon.

Fourth-day, attended Pine street Monthly Meeting.
I felt comforted in sitting with Friends of this meeting,
there yet being left among them many well concerned members of our Society,
who appeared rightly engaged for the proper support of our wholesome discipline.

Fifth-day, attended Arch street Monthly Meeting:
various cases of delinquency came before it, on account of separation from the Society,
in principle and practice.
I was comforted in sitting in this meeting, as well as others in this city,
in observing the quietness and deliberation manifested in
transacting the various matters that came before them.

Seventh-day, I rode to Germantown, and on first-day, attended meeting there;
the day being stormy, the women`'s side of the house was thinly attended:
if my feelings were correct,
there appeared great openness to receive what was communicated,
and I felt well satisfied I had given up to attend this meeting.
In the evening, I proceeded to my kind friend and companion, Joel Woolman`'s,
a nephew of John Woolman, whose valuable journal is in print.

Second-day, my companion accompanied me to Abington, to attend a Monthly Meeting there,
composed of the members left in the Monthly Meetings of Abington and Horsham:
these two meetings united in one,
formed an agreeable body of Friends to conduct the business of a Monthly Meeting.
Both Monthly Meetings, it appeared, were deprived of their meeting-houses, their books,
their funds, their registers, their clerks and overseers,
who were gone off with the other disaffected members of these Monthly Meetings.
Friends in their collective capacity,
were remarkably supported under their varied trials,
manifesting nothing but a spirit of love towards those who were the cause of them.
The meeting adjourned to the afternoon,
to receive the report of a committee to propose to
the meeting suitable Friends for overseers,
in order that cases of delinquency might no longer remain unattended to;
in the afternoon,
it was comfortable to observe how much like brethren of one Monthly Meeting, Friends met;
evidently manifesting an united desire harmoniously
to draw together in the support of the discipline:
the meeting closed under a grateful sense of the
favours bestowed by the Divine Master this day.
Fourth-day, attended Gwynedd Select Preparative Meeting.

Fifth-day, 31st of first month, 1828.
This being the day of Gwynedd Monthly Meeting,
we rode to the house of Thomas Chalkley James,
who had kindly offered Friends two rooms to hold the Monthly Meeting in;
report was made that the separatists had in their possession
the funds for the support of the poor and schools:
cases of delinquency were brought forward,
and committees were appointed to visit the defaulters.
Some of those who were advanced in life, and had taken an active part in the discipline,
having joined the separatists,
the concerns of Society rested very much on the shoulders
of the middle-aged and young men,
whose countenances appeared to manifest a sense of
the weight and importance of the concerns,
in which they were now called upon to take an active part,
and gave hopes of a succession of faithful standard-bearers for the Lord`'s cause.
A young couple passed this meeting +++[+++presented their intentions of marriage]
unattended by parents on either side, they having gone off with the separatists,
but had been prevailed upon to send their consent in writing:
their case excited the sympathy of Friends.

Sixth-day, attended the Select Meeting for Abington and Horsham, reduced to three men;
the queries were answered,
and a good degree of care manifested to send forward to the Quarterly
Select Meeting a correct statement of their situation.

The next day, rode to Philadelphia, and attended the Select Quarterly Meeting:
where I met with my countrywoman Elizabeth Robson, which was cheering to my mind;
the time proved comforting and strengthening to me.

First-day morning, 3rd of second month, attended Pine street meeting;
a considerable number of young people of both sexes were present,
some of whose countenances manifested, I thought,
that they were under the preparing hand for usefulness in the church.
In the afternoon, attended Mulberry street meeting; a quiet, favoured time.
The Quarterly Meeting for discipline commenced the next day;
the body of Friends from the different meetings,
placed as door-keepers to prevent intruders entering the meeting-house,
made rather a formidable appearance.
The trying situation into which this Quarterly Meeting is brought,
through those who have gone off from the Society, obtained much solid deliberation,
accompanied, I could not doubt,
with earnest desires on the part of such as were active in the concerns of Society,
that Divine wisdom should regulate their movements.
I felt well satisfied in having to share with Friends in the sufferings
which they have to endure from such painful circumstances.
There seemed ground to believe that Divine regard
is still extended towards this part of his heritage;
of which favour may the members of this Quarterly Meeting be found walking worthy.

Fourth-day, rode to Germantown, and attended the Select Quarterly Meeting for Abington:
this meeting was small;
the business that came before it appeared to be conducted in much harmony.

Fifth-day, the Quarterly Meeting for discipline commenced, and after sitting six hours,
we separated under feelings of gratitude, that Divine help had been in mercy extended,
while transacting its concerns.

First-day, attended meeting at Frankford:
the separatists keeping possession of Friends`' meeting-house,
the meeting is held in a private house.
Friends are greatly incommoded thereby, the rooms being so crowded,
that the air became very oppressive before the meeting closed.

Fourth-day, rode to Cain; and attended the Select Quarterly Meeting.
From the answers to the queries,
it evidently appeared there was a lack of a lively zeal in this part of the family;
yet it appeared to me cause for rejoicing,
that there is still left in this meeting an honest few,
who are desirous they may be found giving proof of
their fidelity to the Lord and his cause.

Fifth-day, the Quarterly Meeting commenced;
the previous meeting for worship was held in quiet.
When the clerk opened the meeting, a pause ensued,
after which an elderly Friend stood up, and requested,
if there were any present who had not a right to sit in that meeting,
they would withdraw; but this request not being complied with, a Friend stood up,
saying there were such in the meeting,
and therefore Friends could not go on with the business until they withdrew:
much entreaty was used to induce them to do so,
on which the disaffected party declared their right to sit,
although the meeting was informed they had been disowned by their Monthly Meeting.
As they persisted in refusing to leave the meeting,
and made use of very abusive and bitter language,
a proposal was made by Friends to adjourn the meeting;
but this the disaffected party in the meeting opposed with great violence.

After we had sat nearly three hours, subject to these interruptions,
the meeting concluded to adjourn to Friends`' meetinghouse in Downing-town,
till the next morning.
When this conclusion was come to, one of the violent separatists from Philadelphia,
who had come to aid his party in this meeting, came forward on their behalf,
and in a very dictatorial manner,
urged the disaffected part of the meeting not to allow an adjournment to take place.
When he found he could not effect his purpose,
he endeavoured to persuade the disaffected party not to
allow the clerk to take the books and papers away with him,
making use of as strong language as he well could, to rouse them to prevent him.
I expected, when the clerk left the meeting, they would have made an attack upon him;
but he took such care to secure the books and papers,
as would have rendered it very difficult for them to have effected their purpose.
Two elderly Friends went into the women`'s meeting to inform
them of the conclusion which the meeting had come to,
on which the disaffected party nominated two young men,
one of whom was the son of one of the other messengers,
to go into the women`'s meeting to contradict this message;
such are the sorrowful effects of this spirit of unsoundness of principle,
that it regards neither age nor sex,
nor is it subject to parental restraint or affection.

The next morning, attended the adjournment: the meeting for worship was short,
but I believe it was a time of favour which many will long remember.
When the meeting for discipline was opened,
Friends`' minds appeared to be much contrited,
under a sense of the trying situation they were in;
a desire after that oneness of spirit, in the conducting of the discipline,
which constitutes religious harmony, I thought was evidently manifested:
a great field of labour must necessarily open for
the faithful members of this Quarterly Meeting,
who are much to be sympathized with.
After the meeting had held nearly seven hours, and been closely engaged,
it concluded under feelings of gratitude to that Almighty Power
who had given strength to conduct the business of the meeting,
to the satisfaction and comfort of all present.

Seventh-day, we rode to Concord, and were kindly received by our friend Nathan Sharpless.
Attended the Quarterly Meeting of Concord, in which a separation has taken place,
in consequence of which a great load of business has fallen upon those who remain faithful;
but few of the elderly active members are left,
so that the meeting now very much consists of middle-aged and young persons.
I did not doubt, that if the Friends of this meeting moved alone;
in faith and faithfulness, and put the discipline in force against the host of offenders,
without fear, favour, or affection, notwithstanding their accumulated difficulties,
they would, in due time, be helped to rise above them.

First-day, attended Kennet-square meeting; which was large,
and chiefly composed of young people; the young men have scarcely a mark left about them,
whereby they would be known to be of our religious Society;
it was considered to be a solid, satisfactory meeting;
after which we rode to our kind friend John Phillips`'s,
and took up our abode for the night.

Second-day morning, the 18th of second month, we rode to New-garden,
to attend the Western Quarterly Meeting, which is to be held there,
in consequence of the separatists having possession of Friends`' meeting-house at London-grove,
where the Quarterly Meeting is usually held: here I met with my countrywoman,
Elizabeth Robson.
This day we attended the Select Quarterly Meeting,
which is greatly stripped of its members by the schism that has taken place;
the few who remain appeared as if they were nearly sinking under discouragement;
and instead of looking to that Power for help, who remains all-sufficient to quicken,
prepare, and qualify for every service in his church, they seem to be querying,
Who among us is sufficient for these things?
We could not see much prospect of their hands becoming
strong for the work they have to do,
while they manifested such a reluctance to leave their meeting-houses,
continuing to meet with the seceders in meetings for worship:
the necessity of finding a place to meet in separately was laid before them,
in order to their being helped properly to take up
the many prominent cases of delinquency among them.
Although we had to suffer in this meeting,
there was cause for thankfulness in believing the solitary
few were under the care of the great and good Shepherd;
who would help them, if they were but willing, with full purpose of heart,
to move along in the discharge of their religious duties, under his Divine counsel,
and cooperate with the help afforded, knowing no man after the flesh in judgment.

Third-day morning,
the Quarterly Meeting for discipline commenced with a meeting for worship;
the weather was cold and wet,
which made it trying to Friends not to have their horses properly cared for,
being deprived of their usual accommodation at the
house fitted up for holding the Quarterly Meeting,
by those who have gone off from the Society.
At our first sitting down, a very precious silence was felt over the meeting;
in reading the answers to the queries, great weakness was manifested,
from an evident lack of willingness in the minds of those who should
stand forward in conducting the concerns of the different meetings,
to accept of that Hand of help that was still stretched forth,
which would be found all-sufficient to enable them to rise
above those discouragements under which they were now mourning:
encouragement was held out by various instruments, to the willing,
to use the little strength afforded, as the way for them to receive more strength.
Before the meeting closed, several testimonies were borne,
encouraging the members of this meeting to consider this as a day of renewed visitation,
and be willing to accept it as such.

We next proceeded to East-land, and to Little Britain,
to attend Nottingham Quarterly Meeting.
While on my feet in this Select Meeting, I was made sensible from my feelings,
that what I was offering was not well received by some.
An aged man, who sat directly under me, while I was speaking, frequently turned round,
I suppose to see if I had taken my seat; when I had so done, he immediately arose,
saying, he never before had heard such an unbecoming sermon preached;
charging me with having come there to try to breed discord among them,
who were a meeting in full unity and harmony one with another, adding,
they did not need any foreigners to dictate to them how they were to conduct themselves;
they were capable of conducting their business without any foreign aid,
and more to that effect.
I found it was safest for me to keep quiet,
and if any thing was required of me during the transaction of the business of the meeting,
to be faithful in communicating it.

The answers to the queries were read;
it appeared safest for me to allow the deficiencies acknowledged therein to pass unnoticed;
but when the meeting was about separating,
I was brought under the necessity of standing up and saying,
that from the answers to the queries which had been read,
it must appear to every impartial and unprejudiced mind present,
that the individual who sat under me had not been correct in the statement he had given,
of the situation of the members of this Select Meeting relative
to love and unity;--that we were in a dangerous condition when
we supposed things were better with us than they really were,
and I added,
that the answers to the queries from three out of four of the Select Preparative Meetings,
declared in plain terms that there was a lack of love and unity in their meetings;
if such were the case in their smaller meetings, how could it be expected,
in this their collective capacity,
that things would be with them as was stated by the individual under me,
that they were a meeting in full unity and harmony one with another?
Some attempts were made by one of their company,
who afterwards manifested himself among the foremost
in the separation that took place in the Yearly Meeting,
to palliate what the individual under me had said,
but here I felt most easy to leave the matter.
When the meeting separated, this individual,
who attempted to smooth over what the elderly man had said, followed me to my wagon,
and in a fawning way said to me, "`Good father,
do not meddle with these divisions among Friends;`"--but I gave him no other reply,
than saying, what I had communicated among them was, I believed,
in the line of apprehended duty,
and that I had not a desire to recall any thing I had offered in the meeting,
and there I left him.

Sixth-day, attended the Quarterly Meeting for discipline:
such was the depressed state of my mind,
that I despaired of being able to stand up and declare
to the meeting the opening I believed given me;
but breathing for help, strength was afforded me,
although the meeting had become unsettled in consequence of a request
by the disaffected party to close the partition shutters;
from the quiet observed, I was led to hope what I had to offer was not wholly rejected.

When the meeting for discipline opened, a minute was read,
said to be from London-grove Monthly Meeting of Friends,
but it was well known to the active members of this Quarterly
Meeting that it came from a newly set-up meeting,
in connection with the Yearly Meeting of the separatists in Philadelphia;
it gave liberty to a female travelling as a minister
to visit families in part of this Quarterly Meeting.
The separatists having the control of this Quarterly Meeting,
dismay had obtained such hold of the minds of the sound members of it,
that they allowed a minute to be made,
expressive of the meeting`'s unity with her services and her proceeding with her visit,
without opposing the measure.
Believing in this case, that opposition would be unavailing,
silence appeared to be my proper place through the meeting;
but when the meeting was about separating, I felt it required of me to say,
a great loss had been sustained by many of our members lightly
esteeming the privilege of having the Scriptures in their possession,
and neglecting to have them read in a collective
as well as individual capacity in their families;
that this, I believed,
had been one of the causes whereby the disorders
now prevailing had crept into our religious Society.
I expected opposition to what I had offered, but all passed quietly over.
After meeting I found some of the sound members of this Quarterly Meeting,
were placed in a very trying situation,
relative to the liberty granted to the individual to visit families,
and they asked for my advice how to proceed.
I told them, although the Quarterly Meeting had sanctioned her proceeding,
I did not see how they could receive a visit under
a minute from a Hicksite Monthly Meeting.

First-day, we rode to Old Chester: this meeting is principally composed of young people,
and some not in membership with us;
we were rather behind the time at which the meeting should be gathered;
this caused me some little uneasiness, and which I found I could not well get from under,
until I had made such an apology for this apparent disorder,
as I believe I was justified in doing, from the bad state in which we found the roads;
it proved a quiet, satisfactory meeting, I believe, to most;
after which we rode to Philadelphia, where I was again well cared for,
after as fatiguing an afternoon`'s travel as most I have passed through.

Second-day, 25th of second month, 1828, went on board the steam-boat for Burlington;
attended the Select Quarterly Meeting there, where I met Elizabeth Robson:
far separated as we were from our own homes, and near and dear connections,
it was no little consolation to meet in this way,
although it was but for a day or two at a time.
Here I received intelligence that a separation had now taken place in all the
Quarterly Meetings within the compass of Philadelphia Yearly Meeting,
at which I could not but rejoice,
as it respected the welfare and comfort of the sound members of these Quarterly Meetings.
Friends in their select capacity, were favoured to sit down quietly together,
the wing of Divine regard, in adorable mercy, being spread, as a canopy, over us,
to the humbling of many of our minds for this renewed favour.

Third-day, the Quarterly Meeting for discipline was held,
and was attended by part of the Yearly Meeting`'s committee;
various matters of importance occasioned by the separation that had taken place,
came before the meeting, and were considered in much harmony:
after the meeting had sat nearly seven hours,
Friends separated under feelings of gratitude to the Author
of all good for the help vouchsafed this day,
in proceeding with and arranging the difficult matters that came before the meeting.
This afternoon we crossed the Delaware, and rode to our kind friend Moses Comfort`'s,
in the neighbourhood of Pennsbury, formerly the residence of William Penn;
but nothing is now remaining of his residence, except the brew-house,
which is converted into a farm-house.

Fourth-day, rode to Falls, and attended the Select Quarterly Meeting of Bucks;
the few members left, appeared to be closely united in the bonds of Gospel-fellowship:
one individual excepted, who,
from remarks he made on matters that came before the meeting,
appeared in imminent danger of swerving with those already gone off:
the business of the meeting was conducted with becoming solemnity;
and Friends were comforted together under a grateful
sense of the mercy extended towards them,
in being delivered from the spirits of those, who long had brought upon them burdens,
at times, almost insupportable.

Fifth-day morning, attended the meeting for discipline,
which proved a time of close exercise and travail,
from the many trying circumstances that had arisen in consequence
of the separation in its Monthly and Preparative Meetings.
Friends had been deprived of their meeting-houses, and, in some instances,
of their books, papers, and registers;
the funds belonging to some of those meetings and the schools,
being nearly all under the control of those who had seceded from the Society.
It was consoling to find Friends were not disposed to sink under these varied trials,
but manifested a disposition to make use of the little
strength that was left among them,
to get through their difficulties.
After the meeting had sat seven hours, closely occupied,
Friends separated under a thankful sense of the favours
received this day from the Great Head of the church;
some acknowledging it felt to them like the return of old times.

On seventh-day we rode to Buckingham, and next morning sat with Friends there;
the meeting was held in a commodious room,
the separatists being in possession of Friends`' meeting-house:
fresh cause was felt by many of us to acknowledge of a truth,
that the mercies of the Lord fail not,
in that he condescended afresh to own us with his life-giving presence.

Second-day morning, 3rd of third month,
I received a visit from an individual whose appearance was very orthodox,
professing to have long had a desire for my company,
and that nothing but love on his part had been his inducement to make me this visit;
he pressed me much to come to his house and take up my abode for the next night.
As I ever wish to put the most favourable construction on
the conduct of others which circumstances will allow,
and not rashly to judge their motives to action,
I made the usual reply I have found it best for me to make,
where persons are strangers to me,--I was obliged to him; this, I think,
I may with safety say, when an invitation is given to the house of another,
until I am fully satisfied their motives for so doing are not pure;
but he continued to press my acceptance of his invitation.
I then informed him,
my lodging places while attending the Monthly Meeting had
been laid out by my friends at the Quarterly Meeting,
a step I wished them to undertake for me, I therefore must decline his invitation,
and he went away: after he had left me,
I was informed he was one of the most bitter and
foremost among the separatists of Buckingham meeting.
Buckingham meetinghouse being in possession of the separatists,
Friends have been obliged to hold their Monthly Meeting at Plumstead,
a distance of eight miles: the door-keeper of that house,
although gone off with the separatists, assured Friends,
so long as he continued in his office,
he would open the meeting-house for them to hold their Monthly Meeting;
but the separatists being dissatisfied with his conduct in this respect, displaced him,
and appointed another doorkeeper, in hopes he would not give Friends this privilege;
but this man, although one of the separatists`' party,
when he obtained possession of the keys of the meeting-house,
followed the example of the man they had displaced, and opened the house for Friends.
The separatists finding this to be the case, and having hired him for a given time,
could not displace him;
they then appointed a committee to try to bring about
a compromise with Friends of Buckingham and Plumstead,
and a part of this committee called upon some of
the active members of this Monthly Meeting,
in order to ascertain how far their committee, who had this in charge,
would be likely to be received by the Monthly Meeting;
but not finding encouragement from the Friends they called upon,
they took such measures with their new door-keeper as to have the
meeting-house doors at Plumstead closed against Friends.

On the morning of the Monthly Meeting, we proceeded to Plumstead;
when about a mile from the meetinghouse,
a Friend informed us the meeting-house was shut against Friends;
and a member of that meeting kindly offered to accommodate them at his house,
where we proceeded, and found the best done that could be,
by placing planks and chairs for the purpose of holding the Monthly Meeting.
The meeting for worship was crowded, after which, when the men and women separated,
each part was comfortably accommodated,
and the business of the Monthly Meeting was entered upon in a quiet solid manner;
the disappointment and trials of this day I was led to hope
would have a tendency to bring Friends nearer together,
and unite them more closely in the bonds of true religious fellowship.

Nineteen testimonies of denial against women,
and upwards of thirty-six against men who had been members of this Monthly Meeting,
were issued this day, and the parties ordered to be properly informed thereof;
various other matters which had grown out of that
lamentable schism which had taken place,
occupied the meeting until nearly five o`'clock in the afternoon.

Third-day, we attended Wright`'s-town Monthly Meeting, held in a private house;
various testimonies were signed and others ordered,
against such as were gone off from the Society.

The next day, we attended Solebury Monthly Meeting, which was held in a wagon-house;
there being a good loft over it.
Friends had fitted it up for the men`'s meeting,
in as convenient a manner as the nature of the building would allow:
the business chiefly consisted in reading, signing,
and concluding upon testimonies against their members who had gone off from the Society,
which did not appear to be lightly entered into by the Friends of this meeting.

Fifth-day morning, 6th of third month, rode to Falls to attend the Monthly Meeting;
the door-keeper continued to open the meetinghouse
for Friends on Quarterly and Monthly Meeting days,
although united with the separatists; Falls and Newtown now compose one Monthly Meeting.
Notwithstanding the difficult task which the active members of this meeting had to perform,
in bringing forward to the Monthly Meeting the names of their near relatives,
and such as at one time were their most intimate and bosom friends,
together with the reports given to the meeting of
the insulting behaviour and abusive language experienced,
without regard to age or sex,
it was to me truly admirable to observe with what Christian
firmness Friends accepted of the appointments of the meeting,
and the proof they gave of having faithfully fulfilled those they had previously accepted:
and I think I am safe in saying,
from observations I have made in the different Monthly Meetings I have attended,
that the cases of delinquency were determined in a truly Christian spirit;
and manifested that Friends were more desirous of restoring
the delinquents than of depriving them of membership.
After the meeting had been closely engaged for nearly six hours,
Friends separated under feelings of gratitude to the great Head of the
militant church for the help mercifully vouchsafed to this meeting.

Sixth-day morning, accompanied by my friends James and Jane Moon,
attended Middletown Monthly Meeting, which was held at a private house;
where we were obliged to pack so closely together, that it made it trying,
yet Friends appeared preserved in patience.
Various testimonies of denial were signed on behalf
of both the men`'s and women`'s meetings,
and fresh cases brought before the meeting: the meeting-houses, except one,
also the books, papers, records and schools, were in the possession of the separatists.
As Friends had not the control of the schools,
they were brought into a great strait to know how
to dispose of their children in order for education.
The few Friends left in this meeting were strengthened to get through
the trying task they had to perform in support of the discipline,
with much unanimity and firmness;
and the meeting separated under a feeling of precious love and harmony
which prevailed in transacting the various matters that came before it.

First-day morning, the separatists having possession of Friends`' meeting-house at Darby,
the meeting is now held about one mile and a half from the town,
a wheelwright`'s shop being hired and fitted up for the purpose.
When the separation took place, Friends were discouraged,
apprehending their number would be very small; but this has not proved to be the case,
for some not in membership, who had been in the constant attendance of Friends`' meeting,
and in consequence of the unsound doctrines they at times heard,
had left the meeting-house at Darby,
again gave Friends their company at this meeting-place.
It was supposed nearly one hundred Friends and others were assembled this morning:
a degree of solemnity was felt, which is not at our command,
being mercifully vouchsafed from the great Author of all our blessings, which I believe,
many felt to be cause of humble gratitude.

Second-day morning, we rode to Wilmington.
The Monthly Meeting not falling in due course before fifth-day,
an opportunity was afforded me of a little rest, both of body and mind,
of which I stood in need; my general health continued good,
yet the bad roads tried me so much,
that I was led to fear I should be under the necessity of lying by,
if not of ceasing to travel altogether.

Fifth-day, 13th of third month, attended Monthly Meeting.
Friends were much united in transacting the business that came before the meeting:
as yet no cases of delinquency had been taken up.
Feeling drawings in my mind to have an opportunity with the men and women together,
it was proposed that the men should go into the women`'s house,
when the business of the women`'s meeting was ended, which they did;
this afforded me an opportunity of casting before
Friends my views of the loss they were sustaining,
by continuing to hold their meeting for worship with
those who had gone from the Society in principle,
as it had a tendency to produce weakness,
and a disqualification to come forward in the proper exercise of the discipline,
which this Monthly Meeting was called upon to do.
I felt thankful strength had been afforded me to relieve my mind on this subject,
it having for some time dwelt with me,
and the more so as I understood other Friends`' minds were relieved thereby.

I had for a considerable time felt a concern to visit a member of this meeting,
who has united with the separatists,
and was in part the reputed editor of a work which
set forth principles destructive to vital religion,
and which held up our religious Society in as contemptible
a point of view as words well could portray.
I could not see that it would be best for me to go alone,
nor look towards any one to accompany me but my kind companion Joel Woolman.
But the subject had not so ripened on my mind as
to allow of my opening my prospect to him,
and his own Monthly Meeting needing his help he had taken
the first place in the coach to leave me tomorrow morning,
whereby I felt myself placed in a very trying situation, hemmed in indeed on either side.
As I did not feel it would do for me to request a
Friend of the meeting to accompany me in the visit,
should it be likely to take place, the prospect of losing my kind companion Joel Woolman,
was an exercise of faith and patience,
although at times a glimmering prospect would pass before my mind,
if my concern was a right one, and I endeavoured to keep quietly under it,
way would open for its accomplishment.
I retired to bed with my mind exercised with this subject,
unable to see how it was to be brought about, and yet comforted under a hope,
if it was a right concern, way would be made for it.

Sixth-day morning, Joel Woolman went to the coach, and finding every seat occupied,
he returned to my quarters again:
the feelings which this unexpected circumstance produced, I cannot better describe,
being at the time weighed down with the subject of the visit in prospect, than by saying,
my heart felt as if it leaped within me for joy; although as it respected myself,
suffering was likely to be the result of his disappointment.
I then saw that I must inform Joel Woolman how it was with me,
and proposed if he felt easy so to do,
our walking together to the house of the individual,
rather than send a messenger to inquire if he were at home; this we accordingly did,
and soon obtained an interview.

After exchanging a few remarks on the state of the weather, a pause ensued;
this afforded me a further opportunity to crave the aid of that wisdom,
which alone is profitable to direct in all things;
of which I thought I never more felt the need to preserve me from
hastily endeavouring to unburden my mind towards him,
on the subject of his separating himself from the Society:
this I endeavoured to do in as few words and as tender language as I knew how.
He heard me with apparent patience,
until I had finished what was on my mind on this subject; he then replied,
I had twice uttered hard things against those who
had separated from the old Yearly Meeting,
and joined themselves to the newly set-up one,
yet he believed my visit to him was from apprehensions of duty,
and that I was sincere in what I had expressed to him, and he accepted it as such,
and always had entertained and still did entertain a regard for me.
I found it would not do for me to quit,
until I had cast before him my views respecting his being a reputed editor,
of the newspaper before alluded to; from which he did not attempt to clear himself,
nor did it appear to be any part of my business to interrogate him on these subjects,
feeling the need of being careful that I did not overact my part,
which might have produced controversy to my own hurt.
I told him, from the little knowledge I had of the work, it was my belief,
it tended to promote deistical principles among mankind,
and strike at the root of vital Christianity,
independent of the attempts to vilify the Society of Friends and render
them odious in the eyes of the world;--that it was my firm belief,
unless those who were active in editing, printing,
and promoting the circulation of this work, did desist therefrom, they would,
if permitted to retain their natural faculties till the winding up of time,
have a bitter portion administered to their minds at that awful period.
As far as the power of expression was given me,
I entreated him to cleanse his hands from it, and endeavour to get into quiet,
and seek for Divine help to retrace the steps he had taken in that path,
which had caused him to separate from our religious Society.

A pause took place, during which a degree of solemnity was to be felt near us;
after awhile he made observations on the former part of what I had to communicate,
relative to his separating from Friends, in a very cool and deliberate manner.
I did not feel that it was required of me to recall any thing I had offered,
nor to make any additions; except as he had been silent on the subject of the newspaper,
I felt it required of me again to cast before the view of his mind,
what I had before declared would be the sorrowful closing result
of promoting the circulation of the newspaper alluded to.
I exhorted him in the most affectionate manner to reflect on what I had offered to him,
and no longer to touch, taste, or handle this unclean thing.
Here we closed the subject, and parted, I believe,
under feelings of kindness towards each other,--he expressing,
and I could not doubt but sincerely, his satisfaction with the visit.
He appeared to be a man of naturally amiable manners;
and I could not but mourn over him for some time after we separated,
and I humbly hope I did not lose sight of the merciful dealings
of the Almighty with me in this time of conflict,
in that he was pleased to open the way for the visit,
and give me strength fully to relieve my mind on this trying occasion.

Seventh-day morning, my kind companion Joel Woolman left me;
in the afternoon rode to Hockesson; and attended meeting there the next morning.
A separation as to meetings for discipline had taken place in this Monthly Meeting,
but not in their meetings for worship: the meeting was large,
a great proportion of young people being at it; it proved a still, quiet meeting,
more so, I was informed, than had of late been the case,
and Friends appeared to separate under some feelings of solemnity.

Fourth-day, attended the meeting at London-grove, which is held in a store-house.
I felt well satisfied we had given up to sit with this solitary, reduced company,
not doubting but our visit had been seasonably made.
As far as my capacity was equal to it,
I was made willing to go down into suffering with
the suffering seed that was left in this meeting;
under the consideration of the bitter plungings and
hidden baptisms they must have to endure,
in the right exercise of the discipline over their delinquent brethren, who are numerous,
and their own number small.

This afternoon we rode to Centre, and attended meeting there, which has not separated.
It is very trying to stand up in these mixed meetings,
when we have reason to believe the bulk of those whom we
are about to address are opposed to sound Christian principles;
yet I dared not do otherwise than declare,--great is the mystery of iniquity,
and great also the mystery of godliness,
and not to be fathomed by man in his natural unregenerate state,
by the strength of his reasoning powers and natural acquirements;--urging
also the necessity of being so reduced,
as to know a becoming babes in Christ,
and receiving from him the sincere milk of the word,
that so we might come to experience a growing thereby from grace to grace,
and one degree of strength to another; until we become strong men for the Lord,
and for the promotion of his glorious cause.
However these observations might be received as idle tales by some that were present,
I felt thankful I had not taken them away with me.

First-day, 23rd of third month, attended meeting at Kennet-squarc;
Friends meet with the separatists.
This to me proved a very suffering time,
the rude behaviour of some of the young people was such,
that I felt called upon publicly to notice it;
some of them at first appeared disposed to stout it out,
but a sense of shame at last became manifest.
After meeting we rode to Kennet,
and took up our abode for the night at our kind friend Edward Temple`'s.

Fourth-day, we attended Marlborough meeting; where we also met with a mixed company;
the meeting was long in gathering, but separated under a precious quiet,
which had in mercy been spread over us.

Fifth-day, attended meeting at Fallowfield; which was held in a school-house.
Friends being shut out of their meeting-house by the separatists:
our meeting consisted of about twenty individuals; it was held in an orderly,
becoming manner, and I humbly hope it might be said,
was a time of edification to some of us, if not generally so.

First-day morning, I had for some time apprehended when I reached West Chester,
I should be called upon to make a visit to an individual in the neighbourhood,
who once was engaged in religious service in my native land.
Fearing any longer to put it off, we made a call upon him on our way to meeting;
and although he had united himself to the new Yearly Meeting of separatists in Philadelphia,
we were kindly received.
After a few observations were made relative to matters in my native land, a quiet ensued;
when I was helped to break silence,
and communicate that which to me appeared to be the counsel of my Divine Master.
I was heard quietly, but from his replies,
it was evident he felt disposed to justify his conduct, and to consider himself whole.
It was lamentably manifest, that that eye,
which once had been anointed clearly to see those
things which appertain to the kingdom of Christ,
was become blinded.
A separation in the meeting for worship at West Chester had not taken place;
it was a quiet, solid meeting,
except that an attempt was made by the individual above alluded to,
to impress on the minds of such as were willing to receive it,
that all order and discipline in Society should be levelled to man`'s inclination;
feeling myself called upon to enter my protest against such doctrine,
I endeavoured to do it faithfully,
which I afterwards understood was to the relief of many Friends.
We rode to West-town school, and attended the afternoon meeting:
here we met part of a committee appointed by the Yearly
Meeting to attend to this Institution`'s concerns;
in the evening we met in the boys`' schoolroom,
the children being collected for reading previous to their retiring to bed;
and I was led to hope that what was offered among them,
would be remembered by most of the elder boys: thus, a trying day in prospect, was,
through adorable help, brought to a peaceful close.

Second-day morning, we rode to Middletown, and attended Chester Monthly Meeting:
numerous testimonies of denial were signed,
and many fresh cases were brought into the meeting,
all the result of unsoundness of religious principles.
Although I felt considerable fatigue of body,
yet I was thankful in being made willing to share
with Friends in their sufferings in these meetings.

1st of fourth month, 1828.
Third-day morning, we attended Darby Monthly Meeting;
the principal business that came before it was issuing testimonies of denial,
ordering others for next meeting, and receiving cases of delinquency,
and also cases of the like kind from the women`'s meeting.
The teacher of the Monthly Meeting school continuing with Friends,
had been ordered by those who had separated,
to take the children to the separatists`' meeting for worship, which she refusing to do,
they had warned her out of the school;
this circumstance occasioned the meeting some exercise how to proceed,
there however appeared no other way but to let the matter take its course.

Fourth-day, my kind companion Joshua Sharpless, accompanied me to Goshen,
to attend Monthly Meeting there;
the business of this meeting principally consisted in issuing testimonies,
ordering testimonies,
and receiving fresh cases of the like kind from the women`'s meeting;
it was consoling to observe,
notwithstanding the very few active members left in this Monthly Meeting,
the lively zeal they manifested for rightly conducting the discipline, while,
as was reported, they were defied by those they visited,
to put the discipline in force against them.

Sixth-day, attended the Monthly Meeting of Concord;
the chief business of this meeting consisted in issuing testimonies of denial,
ordering others, and receiving fresh cases of delinquency.
The affairs of Society appeared to be proceeded with in a good degree of concern,
that they should be conducted under right authority.

First-day, attended meeting at Chichester; the prospect had been trying to me,
for I do not know when I have felt more of the spirit of opposition than in this meeting.
While I was engaged in religious service, a man who sat in the gallery near me,
one of the separatists, stood up and opposed what I was delivering.
I felt it safest not to take notice of him, and he sat down; the meeting kept quiet,
and continued so to the close of it: after which we rode to Wilmington.

The next day we attended Monthly Meeting at Hockesson,
where I met with my dear aged friend William Jackson.
Our little company was favoured to experience the fulfilment
of the promise to the two or three rightly gathered;
these sifting times have been the means of bringing Friends
nearer together in the bond of true religious fellowship.
Friends of this Monthly Meeting had not as yet felt
strong enough to deal with their delinquent members.
I was truly glad that my lot had been cast among this little handful,
hoping that their hands would yet become strong for the work whereunto,
as faithful members of this Monthly Meeting, they are called;
in order that the reproach brought upon the cause of Truth,
by those who are acting in opposition to its principles, may be thus far wiped away.

Third-day, 8th of fourth month,
we proceeded to Kennett to attend the Monthly Meeting there.
Friends not having felt strength to take up the cases of their members,
who have united themselves to the newly set-up Yearly Meeting in Philadelphia,
the business of the meeting was very soon finished.

Fourth-day, my kind friend Benjamin Sharpless took the charge of driving me to Bradford,
to attend that Monthly Meeting, which continues to be large;
the separation in Cain Quarterly Meeting, of which this Monthly Meeting is a branch,
having recently occurred,
no cases of delinquency have been brought to the Monthly Meeting.
We rode to our kind friend William Jackson`'s, and attended New-garden Monthly Meeting.
The meeting for worship was a favoured time,
after which the meeting for discipline commenced:
the clerk of the Monthly Meeting being gone off with the disaffected party,
and the present clerk being new at his work, the business proceeded slowly;
yet it was cheering to find, stripped as this meeting was,
Friends had strength to proceed to put the discipline in force.

Sixth-day, attended Monthly Meeting at Doe Run;
this meeting appears to have been more stripped of
its active members than any I have yet attended;
only four elderly men remained to take an active part in the Monthly Meeting:
no efforts have yet been made to take up the cases of delinquency; some of the overseers,
the clerk of the Monthly Meeting, and the books, are with the separatists.

Seventh-day, 12th of fourth month, we attended London-grove Monthly Meeting:
from accounts given me by two members of this Monthly Meeting,
it appears that the desolation occasioned among them by unsoundness of principle,
is distressing.
Friends here, while they heard of wars and rumours of wars,
appeared to partake of so much peace and harmony within their borders,
that it was hoped they would have escaped that which came upon them like a thunder storm,
the dreadful consequences of which they were unprepared to meet:
so secretly and artfully had the plans been laid which produced the separation,
that nearly the whole of this once large Monthly
Meeting was swept away like a mighty deluge;
the overseers on both sides of the house went off with the separatists,
who also had possession of the books and papers.
It was encouraging to find this little remnant nearly united in love,
and in desires to strengthen each other`'s hands
in a faithful discharge of their religious duty,
by standing firm in the support of our wholesome discipline against offenders.
When looking at this company, and the host of opposers they have to encounter,
my soul craved that the outstretched arm of Omnipotence
might be made bare for their help,
in all their encounters.
After meeting we rode to Birmingham.

First-day morning, attended Whiteland meeting, which was small;
a great number of the usual attenders of this meeting, it was supposed,
were gone to Philadelphia to attend the Yearly Meeting
of those who had seceded from Friends:
in the evening we returned to Birmingham.

Third-day morning, I left Wilmington by steam-boat for Philadelphia:
a number of the seceders were on board the boat, from whom I kept aloof,
aware of the life they have in controversy,
which I never yet found to end in much satisfaction.
