== Chapter XXXVII.

Fourth-day, 16th of fourth month, 1828, attended Twelfth street meeting for worship,
in Philadelphia, after which was held their Monthly Meeting: the next day,
attended Mulberry street meeting, which was a favoured time.

Sixth-day, attended the Meeting for Sufferings;
the several matters that came before it were treated with much deliberation and weight;
and the meeting adjourned to the afternoon: on our sitting down again,
a solemn covering came over the meeting,
under which Friends were favoured to transact the business,
and adjourned to the close of the Yearly Meeting.

First-day morning, attended the North meeting; in the afternoon,
feeling drawings in my mind towards Pine street, I sat with Friends there:
the meeting soon settled down into that holy quiet which is not at our command,
and when it is in mercy vouchsafed to us, calls for gratitude:
I doubt not many minds were comforted in this meeting.
Took tea with I. W. Morris--a large company were present;
after tea we had a religious opportunity together, not sought for,
I humbly hope I may say, in the will of the creature, but yielded to,
under feelings with which we were favoured.
Amidst social conversation the command was proclaimed without the sound of words,
"`Keep silence before me.`"
This opportunity I was led to believe proved a season
of renewal of strength to some of our company.

Second-day, 21st of fourth month, attended the first sitting of this Yearly Meeting,
which was large; and considered by some Friends not much smaller than in ordinary times.
The meeting was opened under a very solemn covering, and great quietness prevailed;
the becoming deportment of the young men,
and the attention they manifested to the various matters that came before the meeting,
evinced the interest they felt in the concerns of the Society,
and produced the cheering prospect of a succession of helpers in the church.

Second-day, 28th of fourth month, this day the Yearly Meeting closed its sittings;
it continued throughout to be large,
and Friends parted under a grateful sense of the help which had in mercy been dispensed,
in transacting the various important matters which came before the meeting.

Fourth-day, crossed the Delaware river to New Jersey, and the next day,
attended meeting at Old Springfield;
the meeting gathered at the same time that of the separatists did;
this to me was cause of regret,
from a fear that it would tend to keep up a familiar
interaction between the youth among us and them.

Seventh-day, 3rd of fifth month,
attended the Select Preparative Meeting for Upper Springfield, held at Mansfield;
which was small.
I thought it was evidently to be felt,
that the Great Head of the church was mercifully near to this little tried company,
waiting to comfort the mourners among them,
and in his own time to give beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.

First-day, attended meeting at East Branch; the number of Friends is small,
but those of other societies came crowding into the meetinghouse,
whereby we had a large gathering, which settled down in quiet,
and continued so to the close.
I felt well satisfied that I had given up to sit with this company:
may the praise be given where only it is due, is the frequent, fervent prayer of my soul.

Second-day, rode to Crosswicks to attend the Select Meeting for Chesterfield,
which met in the school-house.
Friends appeared much cast down at the desolation occasioned among them,
through a departing from the principles of the Society;
the few members left appeared to be banded together
by that love which is stronger than death,
and which, if abode in, will carry them through all their future exercises.
We took up our abode for the night with a Friend,
whom we found in a very trying situation,--his mother and others
of his nearest relations having gone off with the separatists.

Attended Chesterfield Monthly Meeting, held in a private house; the weather being warm,
and Friends packed close together, occasioned it to be oppressive:
the meeting continued until past five o`'clock in the afternoon;
the testimonies of denial issued--the consideration
of other cases where visits had been made,
and fresh cases brought forward in both meetings,
were so numerous as to occasion Friends being detained to this late hour.

Fourth-day morning, we rode to Mansfield, to attend Upper Springfield Monthly Meeting:
numerous cases of delinquency came before us, in consequence of the separation;
it was pleasant to observe a willingness manifested to submit
to appointments to visit their disorderly members:
after meeting we rode to our kind friend Peter Ellis`'s.

Fifth-day, we rode to Mount Holly, to attend the Monthly Meeting.
It was encouraging in sitting with Friends of this meeting to observe,
that under all the abuse which the reports showed they met with,
in visiting those who had gone off from Friends,
there was no relaxation in supporting the discipline;
the help of the Quarterly Meeting`'s committee appeared to be of singular service,
in holding up their hands and counselling them under difficulty.

Seventh-day, 10th of fifth month, rode to Trenton;
it was feared the meeting on first-day would be disturbed by the
separatists leaving the meeting before the usual time;
but they sat until it appeared time to break up the meeting,
and Friends considered it to have been the most quiet
that had been known at Trenton for a long time.

Feeling drawings in my mind to make a visit to the state-prison,
this afternoon was concluded upon by the managers as the most suitable time for it;
the weather being warm, the prisoners, upwards of seventy in number,
were seated in the yard; their behaviour was becoming,
and from the solidity manifested by many of them,
I was led to hope I had not been out of my place in requesting this opportunity;
we were very handsomely treated by the managers at our parting.
Although giving up to this service had cost me very painful feelings,
yet now it was accomplished, I could go on my way rejoicing.

Second-day morning, 12th of fifth month, we rode to Shrewsbury,
and were kindly cared for by the widow of my friend T. Williams.
Although a separation had taken place in the meetings
for discipline in this Quarterly Meeting,
yet the separatists had concluded to hold their Quarterly
Meeting at the same time and place.

The next day, attended an adjournment of the Monthly Meeting;
it was encouraging to observe that the few members left
in this meeting were so alive to the welfare of the Society,
and no disposition was manifested in any to flinch from the calls of the meeting.

Attended the Quarterly Select Meeting:
as the separatists occupied that part of the house heretofore used by this meeting,
it was held by Friends in the women`'s side,
keeping as far as they were well able to do from the partition,
so as not to be annoyed by what passed in the other meeting.
I believe it might be said Friends were comforted together,
and afresh encouraged to be willing to hold on in whatever
way it might be required of them to take up the daily cross.

Fifth-day, Friends met as usual to hold their Quarterly Meeting,
and the separatists met with them; when it was considered a suitable time,
a Friend proposed that the shutters should be closed, to separate the men and women;
on which one of the separatists seized the clerk`'s table,
brought it to the front of the meeting,
took a paper out of his pocket with minutes all ready prepared,
and read over an opening minute of their meeting, and the names
of their representatives.
One of the Friends of the Quarterly Meeting remonstrated
with him on account of these proceedings,
but it was of no avail.
Friends were obliged to leave the meeting and go to the house of a Friend,
and proceed with the business of the Quarterly Meeting.

First-day attended meeting at Stony Brook, which is a small meeting;
it is apprehended nearly one half of its members are unsound,
but are afraid to manifest their principles; the generality of the neighbourhood,
who do not profess with Friends, are reputed to be serious,
religiously disposed Episcopalians, Baptists, Methodists and Presbyterians,
and warmly opposed to those who hold the doctrine of Elias Hicks.
In the afternoon we made a visit to an aged Friend confined to the house, and her sister;
our visit appeared grateful to them both.

Fourth-day, attended Plainfield Monthly Meeting;
the meeting for worship was a time which called for thankfulness,
and the business appeared to be conducted in much harmony;
this meeting had been much stripped of its members, and some of its overseers.
Friends had not as yet found their way open to do
much in dealing with their delinquent members,
who had set up new meetings.
I concluded, from the number of individuals that were present,
there must be those who had joined in the separation;
but their cases not having yet been brought forward,
they still had a claim to sit in the Monthly Meeting of Friends.
Although I feared it would rouse such, if there were of this description present,
and prevent the meeting breaking up in that quiet in which it had been conducted,
I found if I were faithful to apprehended duty, that I must call Friends to consider,
if there were not a danger of their allowing the right time to pass by
for effecting a separation in their meeting for worship,--giving such
reasons for this step as I found accorded with the views of most,
if not all, who took an active part in the concerns of the meeting;
on which a committee was nominated to take the subject into consideration,
and propose the most convenient place for such a purpose.

Fifth-day, proceeded to New York, where after all the perils by land,
and through false brethren, to which I had been exposed,
we were favoured to arrive in safety,
and I hope under a thankful sense of the many merciful
preservations I had been a witness of.

24th of fifth month.
Seventh-day morning, attended the first sitting of the Select Yearly Meeting of New York,
which was large.
After the meeting was opened and the representatives had been called over,
Friends were informed,
there were a number of persons present who had separated
themselves from the religious Society of Friends,
and who had been regularly disowned by the respective
Monthly Meetings to which they had belonged.
These persons were several times requested to withdraw,
that the meeting might proceed with its business, agreeably to our established rules,
which require that the meeting should be select; but this they declined doing,
giving sufficient proof, by their disorderly conduct,
of their determination to disregard the entreaties of the meeting.
During this scene of clamour and confusion,
Friends were preserved in a remarkable manner in
Christian meekness and firmness,--not a word,
that I could observe, escaped from any Friend denoting impatience or hostility;
for which favour many of our minds were bowed as into the very dust before Him, who had,
in this time of danger, thus far preserved us in the hollow of his Divine hand.

After enduring for several hours much abuse from these intruders,
who were countenanced in their conduct by several members of the meeting,
who had identified themselves with the separatists,
the meeting adjourned to the afternoon, directing the representatives to consider of,
and propose to the next meeting, a suitable Friend to serve as clerk.
Agreeably to adjournment, Friends met; when one of the representatives, who had,
in various ways, identified himself with the separatists, informed the meeting,
he was requested by a part of their number to state,
they had agreed to propose for clerk;
the person thus proposed being one of those who had also united himself with the separatists.
A Friend, one of the representatives, also informed the meeting,
that he had been authorized by the representatives while they were all together,
to state as their prevailing sense,
that Joseph Bowne should be nominated for clerk;--many
of the representatives confirmed this last report.
The meeting was again thrown into a state of confusion
by the conduct of some of the separatists,
aided and encouraged by disaffected members of the Yearly Meeting:
but amidst all these trying circumstances.
Friends continued to be mercifully preserved calm.
After they had sat until nearly night amidst these complicated trials,
and there appearing no prospect that the separatists would withdraw from the meeting,
Friends adjourned to fourth-day morning.

First-day morning, attended Hester-street meeting, which was large;
the meeting was early interrupted by a communication
from one of the ministers of the separatists,
but the solemnity was resumed with which at its first sitting down the meeting was favoured.
In the afternoon I attended Rose street meeting,
where I escaped the company of the numerous preachers of the separatists:
the meeting was held in quiet, although much crowded.

Second-day morning, 26th of fifth month, 1828,
the Yearly Meeting for the general concerns of the Society assembled;
the house was crowded to an unusual degree before the time appointed: the clerk,
Samuel Parsons, opened the Yearly Meeting, which done, I found I must stand upon my feet,
and endeavour to lay before the meeting what I believed my mind had become charged with,
although I dreaded making the attempt, being aware,
from the conduct some of the leading separatists manifested towards me,
that I was become increasingly obnoxious to them, but I dared not keep silence.
I therefore rose with nearly these words;
"`I obtained a certificate from my own Monthly and Quarterly Meeting,
also one from the Select Yearly Meeting of Friends held in London,
expressive of their concurrence with my travelling
in the work of the ministry on this continent,
which certificates were read in the last Yearly Meeting of New York,
and entered on the records of that Yearly Meeting; such being the case,
it constitutes me as much a member of this Yearly Meeting as any other member of it;
as such I therefore dare do no other than enter my protest
against the meeting`'s proceeding with its business,
while so many persons are in the meeting who have
no claim or right to sit in this Yearly Meeting.`"^
footnote:[The rules of discipline of New York Yearly Meeting direct,
that "`after the case of an offender is brought to a meeting,
he is not to attend any of our meetings for discipline.`"
There were present in this meeting very many individuals,
whose cases had not only been brought to a meeting, but who had been regularly disowned,
according to the discipline and good order of our Society;
and consequently the Yearly Meeting could not, consistently with its own regulations,
proceed to the transaction of any business.
From "`The Friend.`"
Philadelphia, sixth month, 28th, 1828.]
I was allowed to proceed without interruption,
and was humbled under a thankful sense of support,
that I had not flinched from the step I had taken.

This called forth other Friends in support of the proposal that the meeting
should be select before the business of it was gone into;
but the disaffected part of the meeting manifested a determination
that those who were disqualified to sit should remain,
using many unsound arguments to support them in their determination.
Elias Hicks also declared they had a right to sit in this Yearly Meeting, saying,
he should have no objection to the meeting going on with the business,
if there were a number of Presbyterians in the house at the same time; he further added,
those who had set up the new Yearly Meeting in Philadelphia,
of which these individuals were members, were not the seceders,
but that the few left of the old Yearly Meeting were the seceders;
that with the consent of his own Monthly Meeting he had attended the new Yearly
Meeting in Philadelphia in the second week of the fourth month last;
that it was attended by a large proportion of the members of Pennsylvania, New Jersey,
and the eastern shore of Maryland, and from all the Quarterly Meetings but one,
representatives had come,
which meeting consisted of the cream of these Quarterly Meetings.
Friends maintaining their ground against the business of the meeting being proceeded in,
while those who had no right to sit there were present;
the separatists then ordered the clerk in a very commanding
manner to go on with the business of the meeting,
until at last many of them manifested a disposition
to become riotous in order to compel his proceeding.
A Friend stood up and proposed,
that such Friends as were desirous of preserving the order of this Yearly Meeting,
should adjourn to some suitable place to transact the business,
which proposal was fully united with by other Friends,
but opposed with violence by the separatists.

While matters were thus going on, the clerk,
aware that it must terminate in a separation,
prepared a minute to that effect--to adjourn to the basement story of the meetinghouse,
which he stood up to read; on which an outcry took place,
"`Don`'t let him read it,`"--"`pull him down;`"--others calling out,
"`He is no clerk of the Yearly Meeting,--we have
a clerk of our own;--the representatives have met,
and we have chosen a clerk:`" but this being the opening of the Yearly Meeting,
the representatives had not yet received their orders
from the meeting to meet for that purpose.
Elias Hicks then called upon their newly-chosen clerk to come forward,
which he did over the backs of the forms, and heads and shoulders of Friends,
some of whom were incommoded by it: on his reaching the front of the clerk`'s table,
Elias Hicks put out his hand to assist him in gaining admittance to the table,
but by some means he failed,
on which some of the Hicksite party turned their newly-chosen
clerk heels first into the clerk`'s seat.
Attempts were now made to wrest the minute the clerk had made out of his hands,
which they were not able to effect, nor prevent his reading of it;
but to prevent what he read being heard over the meeting,
they struck their sticks against the wall of the house,
they stamped on the floor with their feet and umbrellas, they hooted and hissed,
and some were heard to swear: the windows being down, the tumult was so great,
people outside of the house compared it to thunder at a distance.
The minute of the adjournment being read,
Friends left the house and went towards the basement-story,
but care had been previously taken by the Hicksite party to keep Friends
out of this part of the house by locking the doors against them;
one of their party threatened Friends with consequences if they attempted an entrance,
on which a Friend present proposed our adjourning to the medical college in Duane street,
which accordingly took place.

From the solemn manner in which Friends moved slowly along the streets,
many strewing their tears on the way,
having left behind them some near relatives and some intimate friends,
together with the painful feelings occasioned by the scene
of uproar and violence they had so recently escaped,
inquiry was made by people, "`Was a burial coming?`"
On reaching the college, and after taking our seats, a time of silence ensued;
praises were vocally offered up,
to the great Shepherd of Israel for this signal deliverance of his people,
when the waters of the Red Sea were made to stand on heaps.
Daniel Haviland, a very aged blind Friend, broke forth in a melodious manner,
and acknowledged his spirit was now set at liberty,
and his lips unsealed to speak of things he had seen for nearly forty years,
and who it should be that would introduce such disorder and confusion in the Society;
adding, thirty-five years ago, when the Yearly Meeting was held at Westbury,
on Long Island, two women Friends from across the great water,
+++[+++believed to be Mary Ridgway and Jane Watson]
sitting in a room by themselves in the Friend`'s house where he lodged,
seeing him pass the door, called him in, and pointing to Elias Hicks,
who was in another room, said, "`That man will, some day or other,
be a troubler in Israel.`"--He said that the scene we had passed through in this
Yearly Meeting was clearly unfolded to his view before he came to the city,
and he expressed his thankfulness to his heavenly Father for this great deliverance.
"`But,`" said he, "`dear friends, there will yet something come to pass,
if my feelings have not deceived me,
that will more fully try our foundation;`" and he exhorted
Friends to get so deep as that they might be able to stand.
This was a heart-tendering time, not only to the aged and middle-aged,
but some of the youth were also observed with their heads resting on their hands,
weeping.^
footnote:[It will doubtless be, to many readers in this country, very affecting,
and to those previously uninformed quite astonishing,
to find what excesses of disorder and of unchristian
conduct the followers of Elias Hicks committed,
in their attempt to overthrow the good order and
Christian principles of the Society in America.
Although it is almost painful to see them again thus exposed in this Journal,
yet these occurrences, now become matters of history,
ought to awaken in our minds reflections of profitable and solemn interest,
as well as feelings of humble and reverent gratitude.
It is believed, that throughout the narrative of these distressing scenes,
"`the marks`" of the patient, peaceable disciple of Jesus,
are to be discovered in the conduct of our suffering brethren in that land;
and for whom our sympathy will not fail to be afresh excited on the perusal of these
accounts.
{footnote-paragraph-split}
While we may be led to reflect upon our state
of comparative quiet and exemption from such distressing trials in this country,
may we ever remember,
that the enemy of all righteousness has various other modes of assailing us,
if we keep not the watch in the light of the Lord,
and cleave with earnest faith unto the Captain of our salvation:--a
building is not more effectually overthrown by direct open force,
than by a secret undermining and removing of it from its true foundation.]

The meeting being opened, the situation of the women became the subject of consideration,
and some men Friends were deputed to attend at Rose street house,
where their Yearly Meeting was then sitting.
The comfortable change of feeling,
between entering the meetinghouse of Hester street this morning and the college,
is not to be conceived to the full: the meeting adjourned to the afternoon.
At the time adjourned to.
Friends met; the committee to attend to women Friends reported,
that the gates of Rose street meetinghouse, were locked,
and that they were denied an entrance;
also that a deputation had been sent to the women
from the body they left in Hester street meetinghouse.
From the prospect of the trying situation the women Friends were likely to be placed in,
some men Friends were requested to lend them such assistance as they were able.
The meeting being informed that the women were circumstanced as the men had been,
and that it was expected they must leave their meetinghouse,
and the African Methodist meetinghouse having been offered for their accommodation,
it was concluded to accept it.

Third-day morning, the women went into the lobby of their house,
and adjourned to the African Methodist meetinghouse, accompanied by some men Friends.
The trying circumstances under which Friends were now placed,
had become noised abroad in the city, and much sympathy appeared to be manifested,
and great quiet was observed by the people, as we passed through the streets.
The Meeting for Sufferings stood adjourned to Hester street house this evening;
the clerk and others of us proceeded there accordingly.
On our arrival, we were informed by one of Elias Hicks`'s party,
there was no longer a Meeting for Sufferings,
it having been dissolved +++[+++by their meeting;]
and that Friends would not be admitted into that house or any part of it,
to hold such meeting.

Fourth-day, the Select Meeting, standing adjourned to the 8th,
have this morning assembled;
most of those who at the former meeting had improperly intruded themselves,
again took their seats in this meeting;
and Elias Hicks and his party manifesting a determination
that the clerk nominated by their party should stand.
Friends could not proceed to business,
and therefore were obliged to move to the other end of the house,
and endeavour after as much quiet as the nature of their situation would allow:
Joseph Bowne was appointed clerk to the Select Meeting;
after which Friends adjourned to the college.^
footnote:[It is stated in "`The Friend,`" that at least
two-thirds of all the ministers and elders of New York,
who were in attendance, continued with Friends.]

This being the day appointed for both the meetinghouses
in the city to be open for religious worship,
and time not allowing for any arrangement for Friends holding their meetings elsewhere,
the separatists having both meetinghouses now in their possession,
after considering the subject.
Friends were left at liberty to attend either of the two meetinghouses or not.
Accompanied by my kind friends, Rowland Green and Daniel Wood,
we proceeded to Rose street house; although we were early in our attendance, yet,
on our entering the house,
we observed the ministers`' gallery was crowded from end to end;
some Friends under the gallery leaving their seats for us, we occupied them.
As it evidently appeared to be a planned thing to
crowd the gallery thus early by the separatist party,
to keep us from our seats,
I found great care would be necessary on my part to watch against any thing like a spirit
of enmity or resentment taking place in my mind towards any on this account.

A very short time after we had taken our seats,
a leader of the separatist party stood up:
on his taking his seat he was quickly followed by another,
both of them held forth doctrines tending to strike at the very root of vital religion,
and in as direct opposition to the acknowledged principles
of our ancient Friends as words could well convey:
these were quickly followed by a female of their party,
who used very strong expressions in what she called setting her seal to
the Gospel truths declared in the two foregoing communications.
My mind was brought under exercise,
and yet I felt a dread at the idea of standing up to discharge my duty,
expecting no other but it would produce opposition;
but when I believed the right time was come, I ventured to rise,
and in as concise a manner as I was capable of,
bore my testimony to the necessity of our experiencing the
aid and assistance of the Spirit and power of Jesus Christ,
who suffered without the gates of Jerusalem,
if the great work of our soul`'s salvation becomes that complete work,
which it most assuredly must, to entitle us to a seat in the kingdom of heaven.
I further exhorted, for the sake of those not in profession with our religious Society,
that their minds might not be turned from the sure foundation,
by any thing that had been before communicated;
and recommended to their perusal a pamphlet published
by the Meeting for Sufferings in Philadelphia,
entitled, "`A Declaration,`" etc.^
footnote:[In the course of the narrative respecting his journey in America,
our dear friend Thomas Shillitoe makes frequent mention of the difficulties which occurred
in consequence of the principles promulgated by Elias Hicks and his adherents,
and their ultimate secession from the religious Society of Friends.
In order to give the reader a correct idea of the wide difference
between those principles and the doctrines of the Society,
the editors of the Friends`' Library think it right to insert some extracts
from "`A Declaration,`" issued by the Yearly Meeting of Philadelphia,
setting forth the causes of the separation, etc.;
a document to which Thomas Shillitoe frequently refers in the following pages.
This document can be found in Appendix B at the end of the journal,
and is well worth the perusal of every serious reader.]
containing extracts from our ancient Friends`' writings
on the doctrines owned by our religious Society,
which I informed them could be easily obtained by applying
to some sound member of our religious community in the city;
and I advised them to compare the principles there laid down,
which continued to be the principles of the sound
members among us to this day as a religious body,
with the unsound doctrines that had been advanced this morning;
and not to charge the Society with holding principles which it does not,
that we may not be blamed for that which we cannot
own or allow to be the truths of the Gospel.
The opposing spirit was so chained down, it was remarked by Friends afterwards,
that none of the usual marks of disapprobation were manifested, such as coughing,
shuffling of the feet, and blowing the nose, which, by the separatists,
are at times very prevalent in our meetings,
when any thing is offered which they do not approve.

After I took my seat, two Friends had very acceptable service in the meeting,
which closed under a good degree of quiet.
On leaving my seat, I was beset by three or four of the supporters of Elias Hicks,
one grasping my hand so tightly that I found it difficult to extricate myself,
evidently wishing to draw me into controversy, which I found it safest to avoid,
and proceeded to leave the house.
I had not advanced much further,
before I was attacked by another of this party coming from between the forms towards me,
exclaiming in a loud tone of voice,
"`By square and by rule works every fool;`" he followed
me down the meetinghouse to the door,
his gestures and countenance being such, that a Friend who was near came between us,
fearing as he said, that he would have proceeded to personal violence.
Some females not professing with Friends, coming towards us,
called out shame at his behaviour, saying, my age, if nothing else,
should have restrained him from attacking me as he had done.
Thus ended a day that had been trying in prospect to me.

Seventh-day morning, before I left my chamber,
I was informed there were two of the separatists waiting for me below stairs,
and I had been previously told that the Select Yearly Meeting
of the separatists had appointed a committee to visit me,
and that some of this committee had been in diligent search of me the preceding day.
Understanding one of these individuals was a person
at whose house I had been twice kindly entertained,
until I had an official proof from himself of his business with me,
I did not feel comfortable at the idea of refusing to see him;
I therefore provided myself with two suitable Friends to bear me company,
who were at hand.
On taking our seats, one of the separatists`' committee informed me,
they were deputed by their Select Yearly Meeting to say that the unsoundness
of my ministry had occasioned great uneasiness to the members of their meeting,
and that they were commissioned to order me not to proceed further on my visit,
but return home.
To which I made nearly the following reply;
"`I deny the authority of your Select Yearly Meeting,
or your having any thing to do with me;
you have already committed yourselves on this subject, for on fourth-day last,
when assembled with you,
before a separation had taken place in the select department of the Society,
Elias Hicks stood up in that meeting and expressed
his surprise at seeing me and my country-folks,
with other Friends, come into the meetinghouse; saying, we had no business there,
we had separated from you and had no more to do with you;
and that he notice should be taken of any remarks we might have to make in that meeting.
If we at that time had nothing to do with you,
on the same ground you can now have nothing to do with us,
and therefore I shall be obliged by your meeting giving me no more trouble.`"

We parted apparently with kindness, for which I felt thankful.
Shortly after which I received the following, addressed to me:--

[.embedded-content-document.letter]
--

At a Yearly Meeting of ministers and elders, held in New York,
and opened the 24th of fifth month, 1828, and met again by adjournments the 28th, 29th,
30th and 31st of the same inclusive.

This meeting has been brought under exercise and concern,
on account of the movements of our friends from England,
now on a religious visit to this country,
and apprehending their services in the line of the ministry ought to cease,
as it is evident we have not united therewith,
believing their labours have had a tendency to produce discord and division in Society;
and it appearing that labour has been frequently extended in the
course of their visits in different parts of the Yearly Meeting,
without producing the desired effect,
a committee was therefore appointed to inform them thereof,
and as a personal interview has been in some instances refused,
they are authorized to communicate the above minute in writing,
and that the clerk be directed to sign it on behalf thereof,
and that a copy be directed to our subordinate meetings of ministers and elders,
and to the Yearly and second-day morning meeting
of ministers and elders to be held in London.

[.signed-section-closing]
+++[+++Extracted from the minutes.]

[.signed-section-signature]
John Barrow, Clerk.

--

First-day, attended at Rose street house in the morning;
we had a very trying meeting from the anti-christian doctrines
we were obliged to hear advanced before a crowded audience,
many of whom were not in profession with Friends; in the afternoon attended a solid,
quiet meeting, held in a large school-house at one of the extremities of the city.

Second-day, 2nd of sixth month, 1828,
after having sat until near eleven o`'clock at night, the Yearly Meeting closed.

Fourth-day, this being the day when the Monthly Meeting for New York is held,
as no separation had taken place in it, Friends proceeded to their meetinghouse,
where the Monthly Meeting is usually held; after the meeting had sat about an hour,
one of the separatists proposed they should go to business,
and Friends with the separatists, retired to the basement-story as heretofore.

Great excitement having taken place in the minds
of the young people who had gone off from the Society,
on the occurrence of this Monthly Meeting, they gave a very general attendance.
The meeting for discipline being opened,
the clerk of the Yearly Meeting of Friends of New York laid
on the table extracts from their Yearly Meeting;
the clerk of the Monthly Meeting, who is in connection with the separatists,
laid on the table also extracts from the Yearly Meeting of the separatists,
and contended for reading the extracts from their Yearly Meeting,
in which he was warmly supported by their body,
but Friends maintained their testimony against the propriety of such a step.
After Friends had passed through a time of sore exercise,
and a determination being manifested on the part of the separatists
to have the extracts from their Yearly Meeting read,
it was proposed to adjourn the Monthly Meeting;
and such Friends as could not favour the disorderly proceedings,
which the meeting had manifested a determination to pursue,
were requested to retire to the back part of the meetinghouse,
and appoint a clerk for the day, and then conclude upon a place to adjourn to;
this measure was warmly opposed by the separatists, but Friends retired,
being partly accommodated with seats,
and getting into as much quiet as the nature of their situation would allow,
they appointed a clerk,
and concluded upon adjourning to Rose street meetinghouse
at ten o`'clock on sixth-day morning.
This step being taken,
it evidently wrought such a change in the countenances of the suffering
members of this Monthly Meeting as cannot well be set forth in words;
thus another day of trial, in anticipation dreaded by not a few, was, in adorable mercy,
passed over.

I had been looking towards Flushing Monthly Meeting tomorrow,
but my bodily strength appeared so much exhausted
by long sittings and continual exercise of mind,
that I had concluded I must give up the thoughts of such an attempt;
but as I found I could not get comfortably from under the weight of it,
I requested my companion to be in readiness, and we proceeded accordingly.
My mind by this time had become a little seasoned to bear these tumults,
which I again looked for at Flushing.
It was expected there would be a part of a committee of the separatists`' Yearly Meeting,
both men and women, in attendance at this Monthly Meeting.
The clerk of the Yearly Meeting of Friends of New York laid
on the clerk`'s table the extracts from that Yearly Meeting,
and extracts from the Yearly Meeting of the separatists
were also laid on the clerk`'s table,
with an epistle from that body.
This produced the like disorder which took place in the Monthly Meeting of New York,
but Friends were preserved in quiet,
amidst all the abusive language and provocation they received from some
of the members of the Monthly Meeting and the committee of the separatists.
Endeavours were used by the separatists to prevent those who were strangers
speaking in support of the order and discipline of the Society;
after the minds of Friends had been thus exercised for about two hours,
in support of their right to have the extracts from the
Yearly Meeting of Friends read in their Monthly Meeting,
and the determined opposition manifest to it by the separatists and their committee,
calling the Yearly Meeting of Friends a spurious Yearly Meeting,
and one they could not own,
it appeared the best way to allow those who denied their allegiance to
the Yearly Meeting of Friends in New York to go on with their business,
and for Friends to sit quietly and not take any active part therein,
the clerk of the Monthly Meeting being with the separatists.

The separatists proceeded to business; a deputation came in from the women`'s meeting,
informing men Friends of the trying situation they were placed in,
by several females being present who had no right to sit that meeting,
and who would not withdraw.
On which the women Friends were informed,
the men Friends had concluded to remain in the meetinghouse
and transact the business of the Monthly Meeting.
Some of the separatists objected to leave Friends in possession of the meetinghouse,
for this purpose, but this not being generally persisted in,
they accordingly left Friends in the house alone,
the clerk taking away with him the books and papers belonging to the Monthly Meeting.
The women Friends then came into the men`'s meeting to say,
the separatists had finished their business,
but were determined not to quit the meetinghouse while the women Friends were there.
The men`'s business being nearly finished, they were informed to that effect,
and that the men would then give up their house to them to transact their business in;
the women therefore took possession of it.
Thus closed this trying day; trying,
not only as it respected the difficulties Friends had to meet with,
but also such well-disposed individuals whose minds had been wrought upon,
either from the affectionate part overpowering their better judgment,
or by being argued out of it, and had united themselves to this body.

Sixth-day morning, we returned to New York,
and at the time of the adjournment of the Monthly Meeting went to Rose street.
Although some Friends had waited on the property committee,
requesting the use of the house to accommodate the adjournment of the Monthly Meeting,
the doors were locked against them;
men and women continued to collect in the street until we formed a considerable company.
Friends were preserved, under their trying circumstances, in the quiet,
and from much conversation;
some aged and infirm females taking their seats on
the steps of the houses opposite to the meetinghouse,
appeared to excite attention:
after waiting a considerable time beyond the hour
when Friends were to have sat down to business,
as no entrance into the house was allowed, the gates continuing to be kept locked,
we quietly moved on in a body to the medical college in Duane street,
to hold the adjournment of the Monthly Meeting.

Seventh-day, 7th of sixth month, 1828, in a very feeble state of body,
I left New York and rode to Rahway.
I could gladly have yielded to more indulgence than has
been common with me since I left my own comfortable home,
but there was no way for me but to proceed on my journey.

First-day morning, I found it hard work to prepare for meeting, and had I given way,
I should have concluded I could not sit meeting this day;
but this I found would not bring peace to my own mind,
nor would it be likely to secure for me a fresh supply of that help I stood in need of,
in order to get comfortably through the journey I had before me;
I therefore resolved to do my best.
While I was on my feet in communication, one plain looking man left the meetinghouse,
and I expected his example would have been followed by others; but this was not the case:
it proved a day of sore conflict to my mind,
yet in that the unruly spirits were made subject,
and were induced to remain in the meetinghouse and hear
what I had to offer to them in the line of the ministry,
I was made thankful;
as well as in believing my friends were not dissatisfied with this day`'s work.
Rode this night to our friend David Clark`'s, at Stonybrook,
a distance of nearly thirty miles.
I felt greatly exhausted when we reached the end of our journey;
but was comforted that I had not done as my inclination prompted me,
and passed by Rahway meeting.

Second-day, we reached my comfortable home at Philadelphia;
here I received the welcome intelligence,
that my kind friend James Emlen had given up to be my companion in the journey before me,
which was not a little cheering to my tried mind,
under the difficulties that at present exist in finding suitable
companions who are able to leave home for any length of time.

Fourth-day, I reached Evesham, and attended the Select Quarterly Meeting of Haddonfield:
I felt well satisfied in sitting down once more with the Friends of this meeting,
who remain attached to the ancient order of our religious Society.

Fifth-day, attended the Quarterly Meeting for the general concerns of the Society:
Friends were obliged to meet men and women apart, with the shutters closed,
to avoid the interruptions they had experienced from
those who had no right to sit in these meetings.
In this Quarterly Meeting a desire appears to prevail that the discipline may be supported,
and Gospel order maintained in all their meetings:
after the meeting closed I returned to Philadelphia,
to prepare for my journey in prospect.
On my way across the Delaware in the steamboat,
a large company of separatists were on board,
who had been to attend their Quarterly Meeting at Haddonfield.
Friends having refused to open the meetinghouse to them,
they had obtained forcible entrance: some of them in a loud tone of voice,
evidently for me to hear, boasted what a comfortable Quarterly Meeting they had,
which led me to query in my own mind, how could that be,
under the circumstances in which they had gained admittance
into the house to hold that Quarterly Meeting;
but silence appearing best for me, I observed it.

Sixth-day, my bodily debility so increased,
it was necessary I should get into the country;
and accordingly I went out to the house of my kind friend Israel W. Morris.

First-day, attended Merion meeting, which was held in a school-house,
the meetinghouse being occupied by the separatists: our company was not very small;
it proved a quiet, and I believe, a comfortable meeting.

Third-day, 17th of sixth month, I rode to Haverford, and attended their week-day meeting;
the separatists having the control of the meetinghouse,
had changed the day of holding the week-day meeting,
and locked the meetinghouse against Friends on the usual day of meeting;
in consequence of which, I was informed by a Friend of the meeting,
they met for about two months at the gates of the meetinghouse yard,
on the day for holding their mid-week meeting, and sitting in their carriages, +++[+++wagons,
etc.]
they held their meetings in that way.
A private house being empty in the neighbourhood,
Friends have since held all their meetings there.
I felt well satisfied in sitting down with the little company I found here.

Fifth-day morning, I left my friend Israel W. Morris`'s, much improved in my strength,
and proceeded to Middletown, to attend the Preparative Meeting.
Friends here have separated as respects meetings for discipline,
but still meet with the Hicksites in meetings for worship:
when the Preparative Meeting was opened, a young man, one of the separatists`' party,
remaining in the meeting, was requested to withdraw,
before Friends proceeded with the business; but this he positively refused to do,
and after a considerable exercise of patience on the part of Friends,
the meeting was adjourned to a private house.
Men and women united in considering the subject of a separation in meetings for worship:
but on going into the subject, a fear prevailed in some minds,
lest Friends should become weary of suffering,
and by this means get from under these trials before the right time; some acknowledging,
that, trying as their situation in their meetings for worship had been,
yet they would rather endure these sufferings longer,
than that the meeting should take any premature steps for relief: it proved, I believe,
a humbling time to most.
A committee was proposed of men and women Friends,
to take the subject under consideration, and report to the Preparative Meeting;
and Friends separated under an evidence that the step they had taken,
was owned by Divine goodness; and they believed the time was not very distant,
when way would clearly open for their release.
Friends were not much longer tried by being obliged
to meet with this unchristian-like company;
for shortly after the subject of a separation had been considered by Friends,
the separatists themselves prepared the way for Friends`' release.
At one of their weekday meetings, before the meeting had sat its usual time,
the disaffected part of the meeting rose up in a body,
and left the house with a view of breaking up the meeting,
but Friends quietly kept their seats; and when they broke up the meeting,
an elder reported,
that a visit had been made him by one of the separatists on behalf of the whole,
telling him they should no longer submit to his breaking up the meeting.

First-day morning, attended meeting at Newtown: the opposing spirit was chained down,
although what I had to offer among them was such,
that I looked for no other than that many would leave the meeting,
yet all kept their seats.

Fifth-day, attended Middletown week-day meeting,
and the day following Chichester meeting, which was small, but still and comfortable.

First-day, attended Stanton meeting, which consisted very much of young people;
it was pleasant to observe the quiet and order that prevailed;
although it was evidently to be felt, that the life of religion was at a very low ebb.
I felt satisfied I had yielded to come and sit down with this company:
I was told it was the most quiet meeting that had been known at Stanton for a long time,
there being some very bitter spirits among them.
We returned to Wilmington in the evening.

Second-day, Friends held their Monthly Meeting here;
and several of the Quarterly Meeting`'s committee gave their attendance.
Friends believing it would be to advantage to meet separately,
in a meeting for worship capacity, from those who had seceded,
a committee was appointed to effect it.
I rejoiced that this step was about to be taken,
not doubting that it would prove one means of their being
better qualified to deal with their delinquent members,
some of whose cases they had now taken up.
After meeting I rode to Concord, and was kindly received by Nathan Sharpless;
and on third-day, 1st of seventh month, attended Monthly Meeting here;
the business of the meeting chiefly consisted in attending to cases of delinquency,
on account of the separation which had taken place in the meeting.

Fourth-day, attended the Monthly Meeting at West Chester.
The meeting was occupied in the consideration of a separation in meetings for worship;
a committee was appointed to consider the subject, and, if way opened for it,
to propose measures for their relief.
The cases of their delinquent members also occupied much time.
Friends appeared to move along in much harmony.
Fifth-day, returned to Philadelphia.
