== Chapter XXXVIII.

Seventh-day, 5th of seventh month, 1828,
my kind friend James Emlen and myself took our departure for our intended visit to Ohio.
First-day, attended Plymouth meeting, held at the house of Hannah Williams.
Here we met from sixty to seventy Friends, many young people,
whose countenances I thought denoted they were under
the preparing Hand for usefulness in the Society.

On our way towards Sadsbury, we understood Elias Hicks was before us,
and had been holding a large meeting in an orchard.
Falling in company with a serious Episcopalian, who had been at the meeting,
I queried with him, was he satisfied with the doctrine he had heard?
To which he replied, "`His doctrine will not do for me; he cries down all laws,
both moral and Divine; if people receive his doctrines,
I should not be safe out of my house in the evening, nor in my bed at night.`"
Having some pamphlets,
and the Declaration printed by the Meeting for Sufferings in Philadelphia,
in which the doctrines of Friends are contrasted with those of Elias Hicks,
by extracts taken from his printed sermons, I gave him some for distribution,
to wipe away any reproach that might attach to the Society,
in consequence of sentiments advanced; which he appeared gladly to accept.

Third-day, attended Monthly Meeting at Lampeter; it being harvest time,
I was told the meeting was thinly attended.
My mind, early in the meeting was brought under exercise for service,
but my faith was at such a very low ebb,
that it was not ucttil the meeting had sat a very long time,
that I had strength to stand up and endeavour to
express what I believed I was commissioned with.
The meeting for discipline was to me a very trying one;
fear and dismay evidently prevailed in the minds of the
few well-concerned Friends who were left in the meeting,
to the hindrance of their coming forward in the right exercise of the discipline.
Most of the overseers being gone with the separatists,
I requested the meeting to turn its attention to the subject of overseers,
and try to settle down into quiet;
and then I believed Truth would point out the necessity of a few Friends being nominated
to bring into the meeting the names of the most suitable Friends among them,
to fill up the vacancy in the number of overseers in both meetings.
Although there was a disposition manifested in some
to put off taking this step a little longer,
yet the meeting went into a nomination which it appeared was a relief to some minds.
It was known to Friends of this meeting, that Elias Hicks was at Columbia,
where those who had separated from Friends in this
meeting were holding their Monthly Meeting,
and that Elias Hicks intended having a meeting in Friends`' meetinghouse here.
This circumstance appeared to bring some of the members of this
meeting under difficulty how they should proceed in the case;
as it appeared all the trustees of this meeting were with Friends,
I thought it was right for me to encourage them to be faithful and do their duty,
by warning the door-keeper against opening the house on his or his party`'s request,
whereby Friends would be clear.
After meeting we rode to Lancaster,
and took up our abode for the night at the house
of one of the judges of the district court,
by whom we were kindly cared for.

We proceeded by Abbot`'s-town to Chambersburgh.
When opportunity was afforded in passing through the different towns and villages,
I endeavoured to obtain an interview with the preachers and serious
members of the different denominations of professing Christians,
with whom I left a number of the Declaration and other pamphlets
printed by the Meeting for Sufferings in Philadelphia.
It appeared as I went along, that the principles of Elias Hicks were known,
and great opposition to them was manifested.
As it was understood he was to take this same route,
I felt it required of me to inform people thereof,
that they might not be taken by surprise should a request be made by his
party for the use of any of their meeting-houses in the name of Friends.

At two places where we stopped, I met with some serious individuals,
with whom I left some of the Declaration and pamphlets;
they appeared to receive them gladly, saying they had heard of Elias Hicks,
and the dangerous doctrines he was endeavouring to propagate.
We had hoped to reach Redstone on first-day, but this was not practicable.
On inquiry, we found there was a settlement of Friends near Bedford,
a distance we could comfortably reach by seventh-day night; but on further information,
it appeared that this meeting was a part of Baltimore Yearly Meeting,
which involved me in some serious considerations,
not knowing but it might be a part of the separatists`' Yearly Meeting of Baltimore;
and yet how to dispose of ourselves on first-day I could not see:
I therefore found it best for the present to leave this subject,
hoping some way would more clearly open for us when we reached Bedford.
Our journey today was over a very mountainous country;
the day was clear and the scenery fine; but, to me,
travelling on a road unprotected on either side of the vast precipices
near the edge of which we had to travel for many miles,
deprived me of that enjoyment which I might have experienced.

Seventh-day, we reached Bedford in the evening.
On our entering the town,
my mind was again turned to the subject of how we should be disposed of tomorrow.
On a sudden I espied a Friend standing at the tavern door,
and to my agreeable surprise it proved to be our kind friend Israel W. Morris,
of Philadelphia, here on business,
who we found had been making some inquiry of the tavern-keeper,
relative to the state of Dunning`'s Creek meeting, near this place;
by which it appeared that the doctrines of Elias
Hicks had not made much if any way among the members,
so as openly to manifest that they were carried away with them.

First-day, a very heavy storm of rain, thunder and lightning came on early this morning;
this presented a discouraging prospect to my mind,
when looking towards attending Dunning`'s-creek meeting, for the distance, we were told,
was ten miles, and a cross-country road.
I had already experienced the difficulty of travelling these
cross-country roads,--the weather also looked very uncertain;
but I found I must not look at these discouragements,
but be willing to do our best to reach the meeting in due time.
We accordingly proceeded, accompanied by our kind friend Israel W. Morris,
allowing ourselves nearly three hours for our journey,
which we found to be little enough for the undertaking,
as the distance exceeded what had been stated to us,
and the roads were so stony and dangerous,
that my companion expected we could not escape being turned over.
When we reached the meeting-house, Friends were pretty generally gathered.
When the meeting closed, it appeared our visit was cordially received by most.
I distributed among them some of the Declaration and other pamphlets,
printed by the Meeting for Sufferings of Philadelphia,
which appeared to be well received.
A kind friend inviting us to take our dinner, we accepted his invitation: he proposed,
as we had concluded to get on our way this afternoon,
to pilot us into the high road again.
His services we found of great advantage, the way being very intricate, and at times bad;
and after a day of both exercise of mind and great bodily fatigue,
we were favoured to reach a comfortable tavern, about twelve miles from Bedford,
on our way to Ohio.

The next day, we proceeded on our journey, and ascended the Alleghany mountains.
Fourth-day, after having waters to ford,
and a road to travel so washed by the rains as to make it at times dangerous,
we were favoured to reach Brownsville,
the first settlement of Friends since we left Dunning`'s-creek.

Fifth-day morning, we crossed the river, and rode to Westland, where we attended meeting.
The demeanour of many of those assembled more comported
with the conduct of spectators met to hear a lecture,
than people professedly met with hearts devoted and turned inward to the Lord:
I dared do no other than endeavour to lay before them the offensive
manner in which they were placing themselves before the Almighty.
After the meeting for worship closed, the Preparative Meeting was held;
the queries and the answers brought in by the overseers were read,
but very little time was allowed for the consideration of them.
The clerk who managed the business of the meeting, conducted it in a very off-hand way,
manifesting a disposition opposed to any interference:
the few solid members of this meeting claimed the sympathy of their friends,
as a great part of the meeting were prepared to unite with
the separatists when an opportunity offered for it.
Our minds were brought under difficulty to know where to shelter ourselves,
and escape those of whom the leprosy of unsound principles had taken hold:
a member of the meeting inviting us to his house, we accepted his invitation,
and were truly thankful to feel ourselves safely cared for.

First-day, we attended meeting at Pike-run: the meeting-house having been burnt down,
and such being the divided state of this meeting in consequence of unsound principles,
a new meeting-house had not been erected; the meeting was held in a cooper`'s shop.
I found it hard work faithfully to acquit myself; but, as far as I was favoured so to do,
I had reason to hope the minds of sound Friends were relieved.
After I had taken my seat, I was constrained to rise again,
and press upon Friends the necessity of being careful to
make a right use of the time on the first-day of the week;
to endeavour as much as possible to close our worldly concerns on the seventh-day,
that nothing but acts of necessity might occupy our attention on the first-day,
and that we might not by any thing be rendered unfit for the duties of religious worship,
and I exhorted Friends to restrain their children
from wandering about on first-day afternoon.

After meeting, I was informed there was a member of Society present,
who had been holding meetings round the neighbourhood,
for the very purpose of disseminating Elias Hicks`'s doctrines on this head,
protesting against the superstitious conduct of religious professors,
in setting apart the first-day of the week for religious purposes.
Such was the low state of things in this meeting, it appeared, on inquiry,
no notice had been taken of the conduct of this individual.
In the afternoon we made a visit to a young couple;
the father of one of whom is a decided Hicksite.
I had no other in view when I entered their house, than a social visit;
but feeling my mind brought under religious exercise,
while others were engaged in conversation,
I waited for a suitable opportunity to claim their attention.
I found I was not alone in believing a door was opened in the minds of the young
people to receive the word of exhortation and encouragement given me for them.
We returned to Westland, and took up our abode at our kind friend, George Smith`'s.

Fifth-day, it was understood that notice had been very widely circulated,
that Elias Hicks was to be at this Monthly Meeting,
the neighbourhood having for many years been noted as a place where deism greatly predominated.
On coming in sight of the meeting-house, although the meeting-time had not quite arrived,
the crowd assembled on the outside of the house awaiting his coming, was very great;
when he entered the meeting-house, the crowd of members of our Society,
and others who followed him in, filled every vacant seat.
He very soon stood up to speak; and in the course of what he delivered,
denied the miraculous conception of Christ, saying,
he did not become the Son of God until the time when he was baptized of John.
Feeling myself called upon to clear our religious Society from holding
such anti-christian principles as had been asserted by Elias Hicks,
I stood up, and as ability was afforded,
endeavoured to remove from the minds of those serious individuals who might be present,
any unfavourable impressions that had been made respecting the Society of Friends,
in consequence of the doctrines which Elias Hicks had been
holding forth on the subject of the miraculous conception,
and the divinity of Christ;
informing the assembly that the doctrines which had been
now advanced were not the doctrines of the Society of Friends,
but altogether at variance with the principles which they hold on these important subjects;
inasmuch as no society of professing Christians were more tenacious
in the support of a firm belief in the miraculous conception,
and the divinity of Christ, than the sound members of our religious Society.
I recommended the audience to apply to the sound members of our religious Society
for the Declaration printed by the Meeting for Sufferings in Philadelphia,
where they would find the doctrines of the Society set forth,
and contrasted with those held by Elias Hicks: and here the meeting closed.

First-day, we proceeded to Redstone: a report had been sent abroad,
that Elias Hicks was to be at this meeting today;
and before we reached the meeting-house, the crowd standing outside of it made me sad,
having no desire to sit another meeting with Elias Hicks, unless an improvement should,
in adorable mercy, take place in his religious principles.
When he entered the meeting-house, this train of people came in after him,
until the house was filled, and many were obliged to remain on the outside.
Believing I was called upon early in the meeting to say a few words,
I stood up with nearly these expressions, "`The law came by Moses,
but the comers to it were not made perfect; yet it proved to such as received it aright,
the bringing in of a better hope,
by leading them to that grace and truth that came by Jesus Christ.`"
After which Elias Hicks arose, and it was evident, I believe,
to Friends as well as myself,
his power of expression did not rise to that height of opposition as to
overturn the truths of the Gospel I believed I was called upon to declare.

Third-day, attended the Select Meeting of elders;
there being no minister belonging to this Preparative Meeting,
it was sorrowful to observe the countenance given to Elias
Hicks in this meeting by nearly all its members.

Fourth-day, the Monthly Meeting was held.
A Friend from Ohio Yearly Meeting stood up in the meeting for worship, and proved,
by a variety of Scripture passages,
the necessity of our experiencing salvation through Jesus Christ our Lord,
who was crucified without the gates of Jerusalem.
After which Elias Hicks stood up, and endeavoured,
by twisting and turning texts of Scripture every way his inventive brain was capable of,
to lay waste what had been thus offered.
I found I dared not do otherwise than declare against
the unsound principles which he had been advancing,
and which he charged the Society with holding from the beginning.
I likewise felt myself called upon to expose his
presuming to impose himself upon the public,
as he was doing, as a minister in unity in our religious Society; adding,
that so far from the sound members of our religious Society
having unity with his doctrines and him as a minister,
they had in the different Yearly Meetings publicly protested against him as a minister,
and the doctrines he professes to hold.
I recommended the audience not to depend wholly on my report,
but to apply to the sound members in the neighbourhood for a pamphlet,
entitled "`A Declaration, etc.`" printed by the Meeting for Sufferings in Philadelphia,
in which they would find the doctrines of the Society
contrasted with those of Elias Hicks,
and then to judge for themselves.
Here this matter ended: the meeting for discipline commenced;
Elias Hicks produced his minutes from the Monthly and Quarterly Meetings,
informing the meeting he was a member of the oldest
Monthly Meeting on the continent of America,
established by George Fox,
and which had continued a Monthly Meeting of Friends to this present time.
Observing a disposition in most of the members of
the meeting to have these minutes read in the meeting,
I proposed to the meeting to consider how far with propriety they could read them,
after their Meeting for Sufferings had given forth
a testimony against the doctrines of Elias Hicks.
I informed the Monthly Meeting,
the minutes he had produced to the meeting were not regular,
not being signed by the clerk of the women`'s Quarterly Meeting,
as the discipline of New York Yearly Meeting requires,
the clerk of the women`'s Quarterly Meeting being sound with Friends,
which was not the case with the clerks of either the men`'s Monthly or Quarterly Meeting.
But a determination to read his minutes being manifested, Friends were obliged to submit:
after meeting we rode to Providence.

Fifth-day, attended Monthly Meeting here; which is small.
We were comforted, in sitting with this little company,
in observing by a minute on their book the care they
manifested to prevent this evil seed,
which had been spreading in the Society, from getting into their borders;
and that they had by minute displaced one of their overseers on
account of his having attached himself to the Hicksite party:
in the afternoon we rode to Redstone, and next day to Westland.

Seventh-day,
the Quarterly Meeting for the more general concerns of the Society commenced:
notice had been circulated, we were informed, many miles round the country,
that Elias Hicks was to be at this Quarterly Meeting.
At an early hour the house was crowded;
Elias Hicks took up most of the time of the meeting,
endeavouring to overturn various Scripture testimonies which
are given in confirmation of the divinity of Christ,
and that sure foundation on which the holy men of
old built their hopes of an eternal rest.
I dared not do otherwise, before the meeting separated,
than expose Elias Hicks as an impostor, in attempting, as he did,
to impose himself upon the public as a minister in unity with the Society of Friends;
the Society having by a printed document declared
against his doctrines and him as an approved minister.
The meeting then proceeded to business; our certificates were produced,
Elias Hicks and his companion produced theirs also; after they had been read,
a proposal was made that these certificates should be entered on minute.

I informed the meeting if I might have a choice,
I would rather the minuting of my certificate was omitted,
if the certificate of Elias Hicks was to be minuted also, as I considered the meeting,
under the circumstances in which he stood, could not, with any propriety,
minute his certificates.
Much time was spent on this subject,
Elias Hicks`'s party striving hard to have his certificate
minuted on the Quarterly Meeting books;
but not effecting their purpose,
this disappointment appeared to rouse Elias Hicks and his attendant,
who laid a complaint against me and my companion before the Quarterly Meeting;
in which his party united,
and called out to the elders and overseers to take charge of us,
urging our being dealt with for having broken the discipline.
I informed the meeting I was willing to meet the elders and overseers generally,
but not a committee of them,
having seen for myself how much this part of the meeting were partisans with Elias Hicks,
as some of the elders had been furnishing him with barns,
fitting them up for holding his meetings in, and giving notice of the same;
I further added, they must produce their book of discipline: it was proposed,
that we should meet at the close of the meeting tomorrow.

First-day, 3rd of eighth month, attended Westland meeting,
which was crowded to an extreme.
Elias Hicks stood up, made a very lengthy communication, saying,
the second coming of Christ, that had been spoken of,
was that same power that delivered the children of Israel formerly,
and not that same Jesus who suffered without the gates of Jerusalem; endeavouring also,
as far as words could go, to lessen the value of the Sacred Writings, and,
in a fawning way, took his leave of the congregation.
I had made up my mind before I came to meeting,
if any thing Elias Hicks should offer called forth from me the necessity of any reply,
rather to be willing to suffer by keeping silence than have to contend;
but I dared not keep my resolution, and allow the attempts he made,
to invalidate the truths of the Gospel, to pass unnoticed: on my standing up,
Elias Hicks`'s party rushed out of the house in a body,
many of those not in profession with Friends, following their example;
on which I requested the meeting to keep quiet,
and those who were on their feet took their seats quietly again until it closed.

After meeting we met the elders and overseers; I told them,
if the cause of our coming together was traced to its foundation,
it would be found that the elders and overseers had broken the discipline,
by countenancing and encouraging Elias Hicks, giving notice of his meetings,
and providing places for him to hold meetings in,
in violation of the judgment of the Meeting for Sufferings of their Yearly Meeting,
which meeting had testified against his doctrines.
I requested their rules of discipline to be read, by which they intended to criminate us;
which being done.
Friends told the Hicksite party these rules did not apply to us,
for we had not opposed Elias Hicks while speaking.
After they had striven hard to criminate us,
and found they could not effect their purpose,
they left us and Friends in the meeting-house, and withdrew disappointed,
as some of their countenances manifested:
thus Truth triumphed to the rejoicing of the few sound members of this Quarterly Meeting.

This evening we reached Washington.
As I felt it laid upon me to caution the inhabitants of this place against Elias
Hicks`'s imposing himself upon them as a minister in unity with Friends,
and as it was expected he was coming here in his way to Mount Pleasant in Ohio,
I went for this purpose to the residence of the head of the college,
who is a preacher among the Society of Methodists,
and who was as I found acquainted with the unsoundness of Elias Hicks`'s doctrine:
I presented him with some of the Declarations of the Meeting for Sufferings in Philadelphia,
and extracts on the divinity of Christ, which appeared to be gladly received.
The retrospect of this day`'s work was cause of humble thankfulness.

Second-day morning, we proceeded on our journey; crossed the Ohio river.
On my landing on the other side, the woman at the ferry told me,
she supposed I was Elias Hicks, who she said it was reported was on his way to Ohio;
I found she had some knowledge of his principles
by her manner of protesting against them;
she kept a tavern, and I left with her one of the Declarations,
requesting her to circulate it among her neighbours.
It appeared that all professing with Friends in this
valley had lately gone off with the separatists,
except the Friend and his wife with whom I lodged;
two zealous preachers of the Hicksites,
who once stood well with Friends as approved ministers,
had been in this neighbourhood industriously sowing the seeds of disaffection.

Third-day, we rode to Middletown, and attended their Select Meeting.
Here we met with a company of simple honest-hearted Friends,
the disaffection not having obtained any footing in this department of the Monthly Meeting;
we were much comforted in sitting with them, although we found they were in trouble,
but not wholly cast down,--perplexed, but not dismayed.
Two zealous advocates for the principles of Elias Hicks,
had proposed to the disaffected members of the Monthly
Meeting holding a meeting of conference with them;
these meetings of conference are for the purpose of laying
their plans to annoy Friends in their meetings for discipline,
by encouraging persons who have lost their membership,
or are under dealing by the Monthly Meeting,
to remain in the meeting-house when the business is entered upon,
in order that they may worry Friends out of their meetinghouses.

Fifth-day, attended the Monthly Meeting: when the meeting for discipline was opened,
it being known to Friends that there were in the meeting several
individuals who had no claim to sit in the Monthly Meeting,
they were repeatedly requested to withdraw; which they refused to do;
one of their party informed the meeting of their
intention to hold a new Monthly Meeting in the woods,
if Friends would not allow them the use of the meetinghouse,
and to call it Middletown Monthly Meeting:
another of their party proposed to Friends an amicable
settlement about the property of the Monthly Meeting,
that they should have an equal interest in the meeting-house with Friends,
and that Friends should hold their Monthly Meeting on one day of the week,
and they would hold theirs on a different day.
Friends having the control of the meetinghouse, the doorkeeper being with them,
the separatists could have no power over it, except,
as has been the case in other places, they broke the meeting-house open,
and took off the locks, and put on new ones of their own.

The disaffected part of the meeting, and such as had no claim to sit in the meeting,
continuing to manifest a determination not to leave the house;
and as the Quarterly Meeting was so near as not to allow of a convenient
adjournment to answer the queries and appoint representatives,
rather than resort to violent measures to clear the house
of such as had no claim to sit the Monthly Meeting,
it was concluded to go on with such of the business as concerned the Quarterly Meeting,
and other business requiring to be early attended to.
I felt it required of me to stand up and say, a snare had been laid for Friends,
and if they did not take care they would be caught in it:
a proposal had been made for a compromise,
but no compromise must be entered into by Friends of that
meeting with those who chose to separate from them,
nor must they allow them to hold a separate Monthly Meeting in their meeting-house;
and as to what had been said about Friends driving
them into the woods to hold their Monthly Meetings,
and thereby exposing their delicate women to danger of suffering in their health,
that was an artifice.
Various cases of delinquency for separation were brought forward,
and testimonies of denial issued.
Friends being determined to go on with their business,
and the separatists finding that if they persisted
remaining in the house till Friends had finished,
there was no prospect of their having daylight to hold their new Monthly Meeting,
rose up in a body and left the house.
Going into a wood that was near, they raised their voices to such a high pitch,
in preaching, praying, and transacting their matters,
that they were distinctly heard by us; but Friends endeavouring to keep in the quiet,
were enabled to go on with their business;
and this day of storm closed with feelings of gratitude to the Almighty,
who had in mercy made a way for Friends, where no way appeared at all likely,
for them to get through the concerns of the Monthly Meeting to satisfaction.

Some Friends at Westland, who made a part of the conference of elders and overseers,
being aware that we had a prospect of being at this Quarterly Meeting,
and that Elias Hicks and his companions also intended to be there,
in order to refute any misrepresentation that might get abroad relative to that conference,
forwarded to a Friend of this Quarterly Meeting the following statement,
of which he furnished us with a copy:

Feeling much sympathy for our dear friend Thomas Shillitoe,
and his companion James Emlen, who, we are informed,
are going on to your Quarterly Meeting, we thought it our duty to say,
that their company and Gospel labours have been acceptable and satisfactory to us.
Elias Hicks has also appointed and attended a number of
meetings within the compass of our Quarterly Meeting,
which has produced great disorder and confusion--Thomas Shillitoe and James Emlen,
feeling it their duty to attend several of our meetings where he was,
and not only to detect his doctrine, but to give such information to the audience,
as had a tendency to mar his prospects to such a degree,
that he and his partisans were much exasperated against them; and yesterday,
in our Quarterly Meeting for discipline,
when the minuting of Elias Hicks`'s certificate was rejected by a number of Friends,
on the ground that it had not the signature of the clerk
of the women`'s meeting of his own Quarterly Meeting,
which their discipline required, and further,
that his ministry had been disapproved by his own Yearly Meeting, Elias Hicks,
in reply to something Thomas Shillitoe had said, rose and informed the meeting,
that what that Friend said was false.
Elias Hicks, his companion, and their followers carried their point so far,
in accusing our said Friends with a breach of discipline,
for opposing a minister in his preaching,
though they did not oppose him while on his feet,
that they entered a complaint in the course of the meeting against them,
to the elders and overseers.
Our said Friends cheerfully consented to meet them,
if the elders and overseers were all present, with a book of discipline.
No doubt but their intention was to prevent them from having
any further opportunity of exposing their leader.
Most of the elders and overseers convened this afternoon,
had a hearing in the presence of Thomas Shillitoe and James Emlen,
Elias Hicks not present, and with all the ingenuity of such as favoured the separatists,
they failed in their attempt.
We therefore hope that no misrepresentation of the
case whatsoever may have place with you,
believing you are aware that many stratagems are made use of,
in the disturbed state of our Society, to carry points.

After consulting together,
we felt best satisfied to give you the foregoing brief information,
craving your sympathy, protection, and brotherly regard for them,
believing them to be vessels for the Master`'s use.

+++[+++Signed by five Friends.]

Information being received by some Friends of this Quarterly Meeting,
that Elias Hicks was in the neighbourhood, intending to be at the Quarterly Meeting,
this being the day when the Select Quarterly Meeting was to be held,
Friends consulted together,
and concluded it would be best to keep the doors of the meeting-house
locked until the time for the meeting`'s gathering was fully come,
and then for Friends to proceed in company with the Friend who had the key.
On our reaching the meeting-house,
Elias Hicks and his companion were waiting for admittance,
two Friends of the meeting informed them they could not be allowed to sit that meeting:
as Friends persisted in this determination, after some time they left the meeting-house,
and one of their party in Salem furnishing them with a schoolhouse,
there they held their Select Quarterly Meeting.

In the afternoon we attended part of a committee of the Meeting for Sufferings,
appointed to assist the Quarterly Meetings, as it was known,
in addition to the separatists of this Quarterly Meeting,
others of the like description were come from a distance,
to aid them in their designs of sitting the Quarterly Meeting-.
This afforded Friends an opportunity of conferring together,
relative to what was best to be done to preserve quiet in the Quarterly Meeting.
It was concluded safest at this time to meet with shutters closed, and not,
as heretofore, have a public meeting,
there being door-keepers appointed by the different
Monthly Meetings to preserve the meeting select.
The subject of the meeting on first-day also claimed attention;
it having been notified that Elias.
Hicks was to be at that meeting, a great crowd of people was expected.
It was concluded it would be advisable that a few Friends should wait upon Elias Hicks,
and inform him it was the determination of Friends,
if he came to the meeting on first-day morning, and attempted to stand up and preach,
to expose him to the audience,
by informing them what was the situation he stood in among Friends.
This visit to him had the desired effect,
so far as it respected Friends being permitted to hold all their meetings in quiet.
His party, finding there was no place for them in Friends`' meeting-house,
made additions to the school-house, where their first-day and Quarterly Meeting,
and one or more public meetings were held.

Seventh-day, the Quarterly Meeting assembled, which was largely attended by Friends,
and acknowledged to have been the most quiet and comfortable
Quarterly Meeting that had been known for many years.

First-day morning, we attended Springfield meeting, about five miles from Salem,
in which I believe the Friends of the meeting considered I had good service.

Second-day morning, we rode to New Garden;
the separatists having possession of the meeting-house,
and books and papers of the Quarterly Meeting, Friends expected to be shut out.
The time for holding the Select Quarterly Meeting being come,
we proceeded to the meeting-house, and finding the doors open.
Friends took their seats.
After the meeting for business was opened,
Friends were informed there were four individuals
present who had been members of the Select Meeting,
some of whom had been disowned, and others were under dealing;
they were therefore requested to leave the meeting;
but this not having the desired effect,
a minute was made to adjourn into the women`'s apartment,
when one of the intruders informed Friends they would
not be admitted into that part of the house.
Two Friends being requested to try the different doors into the women`'s house,
they reported the doors were all made fast:
Friends then adjourned to an old meeting-house near, which had been long out of use,
a mere shell, in case of need,
some Friends had provided a few rough forms for their accommodation.
The business, of the Select Quarterly Meeting was quietly gone through:
when the meeting closed.
Friends`' minds were not a little agitated about the Quarterly Meeting on the morrow,
although it was not known to Friends that Elias Hicks had arrived,
yet notice had been given a month before, that he was to be at this Quarterly Meeting,
and it had also been given out at their meeting at Salem.
From various reports in circulation,
it appears Elias Hicks`'s visit to the different meetings of this Yearly Meeting,
is not favourable to him and his followers,
having a tendency to confirm the minds of the serious part
of professing Christians of different religious denominations,
that the charge of his holding deistical doctrines is correct.

Fourth-day morning, one hour before the time for the meeting`'s gathering,
the company of separatists, and those who did not profess with Friends,
proceeded to the meeting-house in carriages and on horses, in great numbers;
this plan being laid, it was reported, at their last meeting of conference,
in order that they might occupy the gallery and other parts of the house,
and keep Friends from having their proper seats therein,
and that their clerk might take possession of the table.
Although it was known that they had this in view
by coming to the meeting-house thus early,
yet Friends deemed it best to keep as near to the
right time as would be consistent with good order.
About ten minutes before eleven o`'clock, that being the hour for Friends to meet,
we left our quarters, which were very near the meeting-house,
in company with other Friends.

On our arrival at the meeting-house, we found every seat was filled,
many standing in the alleys, and on the outside of the house.
I pressed through the crowd to the ministers`' gallery, my companion following me,
which appeared to be closely packed from end to end by Elias Hicks and his party,
some of whom scarcely made the appearance of persons
professing to be of our religious Society;
two persons who were in the gallery observing us, left their seats for our accommodation,
which we accepted.
It did not appear to me like being in a meeting of Friends,
for some were standing upon the seats,
with countenances manifesting more of a disposition to disturb the meeting,
than promote the quiet of it.
Elias Hicks, soon after we entered, stood up, and asserted,
that mankind did not suffer any loss through the disobedience of our first parents,--that
the idea of a mediator between man and his Creator was gross in its nature,
and a belief herein must be offensive to Almighty God,
recommending the people to the light,
that principle he said which George Fox and our first Friends recommended to the people,
but not to that Jesus Christ who appeared personally among men,
for salvation,--declaring this to be an impossibility.

I found, if I were faithful to the pointings of duty,
I must stand up and inform the audience that this Divine principle in man,
which George Fox and our first Friends recommended the people unto,
Elias Hicks had denied,
it being nothing short of Christ in his second coming
into the soul of man without sin unto salvation,
who was that light they spoke of,
and Elias Hicks could not be warranted in imposing
himself as he was doing upon the people,
as one in profession with Friends,
he having himself departed from the faith which they hold in the divinity of Christ.
I then informed the assembly that seven out of eight
of the Yearly Meetings on this continent,
and the Yearly Meeting of Great Britain had testified
against the doctrines which he preaches,
and do not own him as a Gospel minister; the Yearly Meeting also,
to which he formerly belonged,
having circulated a printed epistle containing a paragraph to the same effect:
therefore the Society of Friends do not hold themselves accountable
for any unsound doctrines he may attempt to propagate,
and his proceeding as he now is doing,
is contrary to the judgment of the sound members
of the body;--with more than I am able to remember.

I expected to be pulled down;
but the evil disposition was chained by Him who has all power.
Soon after I had taken my seat,
some of the separatists ordered the shutters to be closed between the men and women,
which was done.
Two stout men had taken their seats at the clerk`'s table,
and others had placed themselves on the forms near them;
the clerk demanded his usual seat at the table, which was refused him,
the separatists saying, the clerks of the meeting were seated at the clerk`'s table,
and they ordered them to open the meeting.
The overseers, in the name of the meeting, then demanded the clerks`' table,
ordering the individuals seated there to quit, and give the clerks their seats,
that Friends might go on with their business;
but this they continued to refuse to do,--the separatists ordering their
clerks to keep their seats and go on with the business of their meeting.

The request of the overseers being treated with contempt,
it was then proposed that the representatives would
nominate three of their number to demand,
on behalf of the meeting, of those who were seated at the clerks`' table,
to leave their seats, and allow the clerks to go on with their business,
which was as peremptorily refused.
One of the individuals at the table called upon those who
were travelling with certificates to present them,
on which Elias Hicks`'s certificates,
and his companion`'s minutes were quickly handed to the table,
and one of the individuals at the table stood up, beginning to read them.
Friends being satisfied it would not do to go on with their business amidst such confusion,
and such a mixed multitude, the clerk made an opening minute,
calling over the names of the representatives,
from which it appeared very few of them were able to get into the meeting-house;
after which Friends adjourned to a school-house:
the women being placed in a similar situation with the men,
adjourned to the old meeting-house.
Before Friends left the meeting-house,
one of the separatists informed Friends they were disposed
to agree to an amicable division of the property;
to which Friends made no reply.
The school-house was too small for our number,
yet we were favoured soon to settle down in the quiet;
the business that came before the meeting was conducted in much harmony,
and many testimonies were borne to the lovingkindness of the Lord,
who had that day delivered the members of this Quarterly Meeting from the confusion
and distress to which they had of late been exposed in their meetings for discipline.

Sixth-day, 15th of eighth month, proceeded to Mount Pleasant;
and attended the Select Quarterly Meeting, several weighty matters came before it,
and great unanimity prevailed.

Seventh-day, attended the Quarterly Meeting for the general concerns of the Society:
numbers of the separatists from other Quarterly Meetings assembled,
before the doors of the meeting-house were opened.
The meeting for worship was quiet;
after which the meeting for Society concerns was opened,
when such as had been disowned or were under dealing by their Monthly Meetings,
were requested to withdraw;
it being known to Friends there were such individuals present:
the request was repeated again and again.
As persuasion had no effect,
the clerk was requested to take down the names of those who had
no claim to sit in the Quarterly Meeting at first they professed
not to regard these steps the meeting was taking,
yet after some further contention on the part of the separatists,
one of their leading men proposed to withdraw, another followed him,
and the clerk continuing to take down their names, they generally left the meeting.
After a time of quiet, Friends went on comfortably with their business,
and separated under feelings of reverent acknowledgment, that it was the Lord, who,
in the riches of his mercy, had helped them out of their great difficulties.

First-day, attended meeting at Mount Pleasant; it was considered large,
many of the town`'s people giving their company, and proved a quiet meeting.

Second-day, we rode to Smithfield to attend the Monthly Meeting;
the meeting for worship being over, the clerk opened the Monthly Meeting:
many being present who had no claim to sit in this meeting,
they were requested to withdraw, which was repeated again and again,
but without the desired effect.
Some of the separatists, far advanced in age,
stood up and encouraged this disorderly proceeding,
claiming a right to sit in these meetings,--until
a proposal was made to take down the names of such;
the clerk proceeding to do so, they withdrew, except two of my own countrymen,
who stood it out to the last;
after which Friends were favoured to proceed quietly with their business.

Third-day morning, we rode to Short-creek, and attended the Monthly Meeting there;
the meeting for worship was large,
and I believe to many it proved a season of renewal of strength;
the business of the Monthly Meeting was conducted with much unanimity,
a religious concern being manifested in the active members of the
meeting for the welfare of the cause of Truth and righteousness:
many testimonies of denial were issued and many ordered
to be brought to the next Monthly Meeting,
against individuals who had united with Elias Hicks`'s
party in setting up new Monthly Meetings.

Sixth-day, we attended Flushing Monthly Meeting, which was held in quiet,
and the business which came before it was conducted with more despatch
than is often the case in these back settlements of Friends.
After meeting we rode to Barnsville, a journey of sixteen miles,
chiefly through woods and some newly opened roads;
we did not reach our quarters until after sunset.

Seventh-day, attended Stillwater Monthly Meeting:
the meeting for worship was a very exercising time; necessity, I believed,
was laid upon me to warn Friends against the danger
of being implicated with two of the Hicksite preachers,
who had recently been very active in endeavouring
to bring about a separation in this Quarterly Meeting;
I felt myself constrained, if I did my duty,
to describe them to be apostates from the faith they once preached.
Those who had not a claim to sit in the Monthly Meeting, quietly withdrew,
which I afterwards understood was very unexpected to Friends:
from the large portion of business that came before the Monthly Meeting,
we did not separate till late.
It has been pleasant to observe in this and the other Monthly Meetings,
where cases of delinquency have been brought forward,
a disposition of great tenderness manifested towards
those who were the subjects of treatment.

First-day, attended Stillwater meeting, which was large;
it was considered by Friends the most solemn,
comfortable meeting that had been known there for a long time.

Second-day, 25th of eighth month, 1828, we rode to Somerset to attend Monthly Meeting.
The meeting for worship was large; I had to proclaim among the members the language of,
"`Come away from them,
and be separate,`" as a renewed call of the Most High in mercy to some present;
also to hold out the language of encouragement,
if an unreserved willingness were manifested to obey the call,
that help would be vouchsafed, which would be found all-sufficient;
but if there were a continuing to unite with those who had
so sorrowfully departed from the right way of the Lord,
great suffering in a future day would be the result: the meeting was preserved in quiet.
When the meeting for discipline was about to commence,
a large part of our company withdrew;
either having been disowned or were under dealing by the Monthly Meeting,
for uniting in setting up separate Monthly Meetings.
The queries were answered,
and numerous testimonies of denial signed for both men and women,
others ordered for next Monthly Meeting, and fresh cases were brought forward.

The next day, attended the Select Quarterly Meeting, held at Stillwater:
the meeting was informed before it was fully gathered,
that some persons were on their way who had been members of this Select Meeting,
but who had been disowned in consequence of uniting themselves with the separatists:
on their making the attempt to enter the house, and the doorkeepers preventing them,
they assembled on the meeting-house lot, where they held their meeting,
preaching and praying, so much to the annoyance of Friends,
that they were obliged to close the windows of the meetinghouse.

Fourth-day morning, 27th of eighth month, the day of Stillwater Quarterly Meeting;
my companion and myself on proceeding towards the meeting-house,
observed a vast crowd of people assembled; the nearer we approached,
the more awful the commotion appeared;
the countenances and action of many manifested a
determination to make their way into the house,
by resorting to violent means, if no other way would effect their designs:
by pressing through the crowd we gained admittance.
The tumult increased to an alarming degree;
the consequences of keeping the doors fastened any longer were to be dreaded,
as the mob were beginning to break the windows to obtain an entrance that way,
and to inflict blows on some of the door-keepers;
it was therefore concluded to open the doors.
The door of the men`'s house being opened, to attempt to describe the scene to the full,
would be in vain.
The feelings of alarm awakened in my mind were such,
as almost to overpower my confidence in the superintending care of a Divine Protector;
the countenances of many as they entered the house,
seemed to indicate that they were ready to fall upon
the little handful of us in the ministers`' gallery,
there being few others in the house.
Some of their party forced open the shutters between the men`'s and women`'s house,
as if they would have brought the whole of them to the ground;
others ran to the doors which had been made secure, seizing them, tearing them open,
and some off the hinges; the like outrage they committed in the women`'s house;
the cracking; and hammering this occasioned for the short time it lasted was awful to me,
not knowing where, or in what, this scene of riot and wickedness of temper would end.
The house was very soon crowded to an extreme,
the separatists taking possession of one end of the men`'s house and Friends the other;
no sooner was the meeting become a little quiet,
than the preachers of the separatists began uttering their deistical doctrines;
attempting to prove man had not suffered loss through
the disobedience of our first parents,
and to make the sacrifice of Christ of none effect,
and speaking irreverently of the Scriptures.
I dared not do otherwise, trying as it appeared to be, than stand up and say.
If there were any present not in profession with our Society,
I wished them to understand that the doctrines which had been advanced,
were not the doctrines of Friends,
and therefore I hoped we should not be charged with holding such unsound principles,
nor considered accountable for what had been said.
I stated as my belief,
that the sorrowful confusion and distress which had taken place that morning,
had grown out of those unsound doctrines,
which of late had been disseminated and received by many among them.

Trying as our situation was,
it appeared best to proceed with the business amidst
the host of opposers and strangers present;
the representatives were called over, the answers to the queries read,
and a summary prepared:
had I not been present I could not have conceived it possible for
Friends to conduct the business of a Quarterly Meeting so quietly,
circumstanced as they were,--the separatists going on with the business of their
new Quarterly Meeting at one end of the house and Friends at the other.
One of the most active in this riot exhibited charges against me and other ministers,
and against some active members of Stillwater Quarterly Meeting,
charging us with acts of violence towards him, signing the same,
and circulating it in a Hicksite work, called "`The Friend, or Advocate for Truth.`"
The door-keeper, and other Friends who were present at the time,
drew up certificates clearing me and others of the
charges so wickedly brought against us,
signed it, and published it in a weekly publication of the Society,
called "`The Friend,`" and also in Bates`'s Repository, to which no reply ever appeared.
Friends were favoured to get comfortably through their business,
closing under a grateful sense,
that it was the Lord who had in mercy been a stay and staff
to their minds through the difficulties of this day,
and desires were put up to the throne of grace to be enabled
to be found walking worthy of these his favours.

First-day, 31st of eighth month, 1828, we rode to Benjamin Vail`'s,
where a meeting is now held, composed of those who remain with Friends of Plainfield,
Clairsville, and Concord meetings,
the separatists having possession of these three meeting-houses.
The room being small, many were obliged to sit outside the house.
I went to meeting in a tried state of mind: a thorn in the flesh is often my companion,
doubtless permitted in mercy to keep down the creaturely part,
lest any thing like being exalted should appear and take root,
through the acknowledgments made in meetings of approbation
of my ministry and services among my friends:
the meeting was held in the quiet, and proved a comfortable, and, I hope,
an encouraging one to many of our company.

Fourth-day, attended meeting at Mount Pleasant;
on first sitting down the wing of Ancient Goodness was in mercy spread over us;
and as Friends came into the house one after another,
the awe that was brought over their minds was to be observed,
from the manner in which they took their seats: I had cause to say,
it was good for me I was there.

Seventh-day morning, the first sitting of the Select Yearly Meeting commenced:
at the time appointed for the meeting to assemble,
Elias Hicks and two other preachers of his party tried to gain admittance,
but being refused, they replied that they could hold their meeting in the open air,
as George Fox did: furnishing themselves with chairs,
in company with about twelve of the select members of this Yearly Meeting,
who had united themselves to the Hicksite party,
they held their meeting on the outside of the meeting-house fence:
although their voices were at times heard in our meeting,
yet it did not appear the meeting suffered thereby,
except the minds of Friends being affected with sorrow on their account.
In the afternoon, attended the Meeting for Sufferings.
Friends being aware of the difficult situation they were likely to be placed in,
on the day when the Yearly Meeting for the general concerns of the Society was to commence,
a consultation took place on the subject; and it was concluded,
to have the usual doors open,
and that the door-keepers should be requested to endeavour to keep the meeting select,
but not to use force.

First-day morning, attended the meeting at Mount Pleasant:
it may easily be supposed the prospect of going to
meeting this morning must have been formidable:
the house was crowded, and before the meeting was fully gathered,
Elias Hicks stood up and occupied much time in setting
forth doctrines opposed to all Christian principles.
After he had taken his seat,
a Friend rose and informed the audience of the situation
in which Elias Hicks stood with his friends at home;
this he did in order to do away any unfavourable impressions respecting Friends,
which might have been made upon the minds of any
from the doctrines which Elias Hicks had advanced.
From the great concourse of people we passed in the
afternoon on their way to Short-creek meeting,
where Elias Hicks was to be,
I had cherished a hope we should have had a quiet meeting at Mount Pleasant;
but we had not long been settled down before two of the
preachers of the separatists rose one after the other.
On their being requested again and again to sit down,
the Hicksite party shouted from various parts of the meeting,
manifesting such violence of temper, that it appeared safest to allow them to go on.
Although it was as distressing a meeting as most I have sat in, yet when it closed,
I could not say I regretted my lot was cast among Friends,
to share with them in their exercises.

Second-day, 8th of ninth month:
at eight o`'clock this morning the committee of men
and women Friends on Indian affairs met,
to which committee strangers were invited, of which number I considered myself to be one.

When the business of this committee closed, Friends and the clerks remained in the house:
the time for the gathering of the Yearly Meeting on the
general concerns of the Society being nearly come,
these Friends filled up the ministers`' gallery and front seats.
Printed notices had been served on Elias Hicks and others,
and copies nailed on the doors of the men`'s and women`'s house,
signed by the trustees of the property,
warning them not to enter the meeting-house during the sittings of the Yearly Meeting;
numerous door-keepers were also in attendance, but the separatists became so violent,
that it appeared no longer possible for the door-keepers to maintain their posts,
unless they repelled force by force.

Friends conferred together,
when it seemed safest to request the door-keepers to desist from their charge,
and leave the doors; this taking place, the mob,
headed by two of the preachers of the separatists, poured into the house like a torrent,
accompanied by some of the rude rabble of the town;
they violently forced open the doors that had been kept fast,
and some young men entering the women`'s house, committed the same outrage.
After the assembly had become quiet, beyond what could have been expected,
all circumstances considered, the clerk, Jonathan Taylor,
opened the Yearly Meeting amidst this crowd of intruders;
on which one of the separatists`' party stood up,
and declared he was authorized by the members of Ohio Yearly Meeting
to order the clerks that were then at the table to quit,
and give place to such clerks as they should choose for themselves,
at the same time naming an individual for the office;
which nomination was confirmed by many of the separatists
shouting out at the same time "`That`'s my mind,
that`'s my mind;`" "`Why does not our clerk come forward?`"
The separatists then crowding between the front seats, and up to the table,
ordered the Friends who were standing near the clerks`' table to quit;
but their demand not being complied with, they began to use violence,
on which the clerks were ordered to take down the names of such
as appeared to take an active part in such proceedings.
This did not check their proceedings,
and finding they were not likely to succeed in driving
Friends from the front of the table,
they endeavoured to do so by a door behind the clerk: my seat being next to the clerk,
a man of large stature and bulk came over the gallery-rail almost upon me,
and after him two young men.
I was on the point of getting up to leave the house; but before I was upon my feet,
one of the separatists near me, looking up,
exclaimed the gallery that was over our heads was falling:
a great crash at this moment was heard over our heads,
which it was afterwards proved had been produced
by one of the separatists`' breaking a piece of wood.
Immediately on an alarm being given "`the gallery is falling,`"
from the other side of the house there was an outcry,
"`The house is falling;`" The door of the women`'s house was thrown open,
and they were told the house was falling;
a sudden rush in every direction produced a sound not unlike thunder,
and brought down a small part of the ceiling in the gallery;
this raised a considerable dust, and had the appearance of the walls giving way,
and the ceiling coming down.
While I was making my way from my seat,
a Friend informed the meeting it was a false alarm; the separatists,
who had crowded into the ministers`' gallery, and given this alarm,
instead of making their way themselves out of the house, called out,
"`Make way for the old Friend;`" others said,
"`Let the old Friend come by;`" so that I had no difficulty until I reached the door,
where the crowd was very great.
Some were thrown down and were in danger of being trampled to death;
a young Friend told me they forced the sashes out with their feet,
and tumbled out of the windows: one young man, report says, in his fright,
dropped out of an upper window.

The separatists having now obtained access to the door at the back of the clerks`' table,
voices were heard above the general uproar, "`Now is the time, rush on,`" which they did,
but not being able to get possession of the table, it was broken to pieces.
In a short time I returned into the meeting again.
When the tumult and uproar had somewhat subsided,
it was proposed that we should leave this scene of riot; which being united with.
Friends adjourned.

Third-day morning.
Friends met in the meeting-house lot at Mount Pleasant, opened the Select Meeting,
and adjourned it to Shortcreek meeting-house,
admittance having been denied them to Mount Pleasant meeting-house.
The Yearly Meeting standing adjourned to ten o`'clock this morning.
Friends were advised to make a formal demand of the men`'s and women`'s house.
They therefore assembled in the yard of the meeting-house at Mount Pleasant,
and the trustees for the property, with two of the representatives,
went into the meetinghouse, the separatists`' meeting being then sitting in it,
and in an audible manner,
demanded quiet possession of the house to transact
the business of the Yearly Meeting of Ohio select.
After much quibbling on the part of the separatists,
when pressed to give a decisive answer to this question,
whether they were willing quietly to resign the meeting-house?
the answer they gave was,
"`There is no reply;`" the separatists`' then resumed their business.

Notice was now given, that Friends being kept out of their house,
would open their Yearly Meeting in the yard;
men and women collected accordingly at the front of the meeting-house,
the men to the east and the women to the west: here we had a large and solemn meeting.
The pacific nature of our holy profession was again manifested by Friends,
after having asserted their right and made a formal demand of their property,
then submitting to hold their meeting in the open air, rather than resort to force,
their disturbers being less perhaps than one-third of their number.
Several living testimonies were borne to the praise of that Almighty arm,
which had thus far in mercy sustained Friends and preserved them in meekness and patience,
amidst accumulated difficulties.
Friends were informed, that, in consequence of the injury which Jonathan Taylor,
the Yearly Meeting`'s clerk, had received yesterday from the pressure at the table,
he was unable to give his attendance,
the assistant clerk was therefore requested to open the adjournment,
which was accordingly done;
after which the Yearly Meeting was adjourned to Short-creek meeting-house,
in which not a few of our company on this solemn occasion were bathed in tears;
some of the youth among others.

Fourth-day, 10th of ninth month, Friends met according to adjournment,
at Short-creek meeting-house, and were favoured with a solid sitting together;
the meeting being opened, a minute was made,
stating the cause whereby Friends were brought under
the necessity of quitting their own house,
and also excluding from the several sittings of this Yearly Meeting such members of
Society as had united with others in producing the riot at Mount Pleasant meeting-house,
and who had otherwise identified themselves with the separatists.

On taking our seats in Short-creek house,
many minds were afresh contrited before the Lord for his merciful deliverance.
The chief subject that occupied attention at this time was,
what measures Friends were to adopt to secure a peaceable enjoyment
of their privileges in holding their meetings select,
and the names which had been taken down of those
who had been the most active in the riots,
and in breaking the clerks`' table, were read over.

Fifth-day morning.
Friends again met; the meeting continued large, and the weather being fine,
was a favourable circumstance,
as many were obliged to take their seats under the temporary awnings out of the meetinghouse,
the windows having been taken out to accommodate the numerous company.
Friends were favoured with a quiet, comfortable sitting together.

Sixth-day morning, the meeting again assembled,
and matters which came before it were conducted in great harmony;
the trials which Friends had passed through, had brought them very near to each other,
baptizing them together under a sense that the concerns
of the church they were met to transact,
were not their own, but the Lord`'s,
who I believe was much looked unto for counsel and help
throughout this time of close travail and exercise of spirit.

Seventh-day morning, the meeting continued to be largely attended;
Divine goodness still condescended to own us together with his enriching presence,
to the contriting of our spirits,
causing tears of gratitude to flow down the cheeks of many in the meeting.
In the afternoon, I attended an adjournment of the Meeting for Sufferings,
in which we were again refreshed, under a renewed sense,
that the Lord is still in mercy condescending to offer his help to our poor Society.

First-day morning,
feeling drawings in my mind to attend Harrisville
meeting about seven miles distant from Short-creek,
accompanied by my friend Rowland Green, we proceeded there.
We had not long been seated in the gallery before one of the preachers
of the separatists accompanied by many more of his associates,
entered the house, and occupied a great deal of the time of the meeting;
when he took his seat again,
I felt it laid upon me to inform the assembly that the individual
who had spoken had no right to preach in that meeting,
he having been disowned by the Society of Friends.
Although this meeting was a very suffering one,
yet on comparing my feelings with my companion`'s on our way back again,
neither of us felt cause for regret that we had given up to attend it;
believing our sufferings therein, would not all be in vain.

Second-day the Yearly Meeting again met;
when a report from the Indian Committee was received,
from which it appeared the school had been suspended:
Friend`'s minds were exercised with desires that they might
not remit their care over this part of our fellow creatures,
as far as their means and ability were equal to.

Third-day morning, the Yearly Meeting again met,
and attended to the various concerns which still claimed attention,
having grown out of the present trying state of the Society, from the unsound principles,
which had made such inroads in the minds of many of our members.
Under a reverent, thankful sense of the help which had been extended,
while conducting the several weighty matters before the meeting,
and after expressions of concern that we might be found
walking worthy of the continuance of these Divine blessings.
Friends separated in great nearness of spirit;
the cheeks of most were bedewed with tears of sympathy and affection,
at the prospect of the sufferings that awaited them,
through the opposition to be expected from their
revolting brethren in their several meetings at home.
