== Chapter XXXIX.

Fifth-day morning,
my companion and myself left our comfortable abode at our kind friend Jonathan Taylor`'s,
and proceeded towards Indiana: in the evening we were favoured to reach Zanesville.
It being reported Elias Hicks had been at this place,
and procured the use of the courthouse, and held a meeting there,
as I had still some of the Declarations of the Yearly Meeting in Philadelphia,
I devoted some time in visiting the preachers of different religious denominations,
and delivered them to those we met, which appeared to be well received;
I also left others for distribution.
One individual observed, that he had heard much said on both sides,
and had been desirous of seeing something official from Friends themselves;
he was therefore glad to receive the Declaration,
intending to make it known to his hearers.

First-day morning, attended meeting at Zanesville: it was a quiet time,
and I hope a season of instruction to some.
After meeting we pursued our journey through Alexander,
where I distributed some of the Declaration, and then to Circleville,
where we understood Elias Hicks and several men and
women had halted on their way to Indiana,
but had not held a meeting.
We took up our abode for the night at a tavern.
I called upon some of the leaders of the different religious denominations there,
and left some of the Declarations, which appeared to be well received.

Third-day, we proceeded to Dry-run.
It felt pleasant to get into a settlement of Friends again,
from the difficulty we experienced in being obliged to be at taverns,
spending our evenings in such mixed companies as we frequently met.
The prospect of a journey of five hundred miles before me, after quitting Indiana,
when I must have this inconvenience to combat,
of being at taverns to eat and lodge nearly the whole of the time, was trying;
yet I found it was a subject not profitable for me to dwell upon,
satisfied that no unnecessary anxiety of mine could make a change for the better,
in the trials which were to fall to my lot.

Sixth-day, attended the Preparative Meeting held at Walnut-creek;
notice having been given of my desire to sit with Friends of this meeting,
we were informed there was a general attendance,
and we had good ground to believe our visit was acceptable.

Seventh-day, we attended the Monthly Meeting at Fairfield:
the meeting for worship was numerously attended by persons not in profession with Friends;
it proved an exercising season, yet I humbly hope I was found faithful,
in declaring what appeared to be the word of the Lord through me, his feeble instrument.
In the afternoon we proceeded to Wilmington, about sixteen miles,
and were favoured to reach it before dark;
here we were informed Elias Hicks and his party had a meeting in the courthouse,
which at first was numerously attended; but the doctrines he advanced,
caused many of the most respectable of his hearers
to leave the house before the meeting was over.

First-day morning, we reached Centre, and attended meeting there;
a large proportion of this meeting consists of young
people who profess to continue with Friends,
but from their external appearance it would seem they were
ignorant of what they were making a profession of.
I was constrained to endeavour to impress their minds
with a sense of the mercy they enjoyed,
in that there were yet preserved among them so many aged brethren and sisters,
who had not dared to bow the knee to the Baals which
had of late been travelling among them,
nor to kiss the image they had been setting up: great quiet prevailed over the assembly.

Third-day morning, we rode to Wainsville;
on our arrival we were informed Elias Hicks and his party had possession of the meetinghouse,
and were holding what they termed, Indiana Yearly Meeting of Friends.
I was informed there was a settlement of Friends at Springborough,
about eight miles distant, on our way to Indiana;
and believing the pointings of duty directed my mind there that night,
we concluded to proceed.
We rose early to breakfast; and, as we had a long day`'s journey before us,
I proposed our moving on our way to Richmond.
Next day after a long fatiguing day`'s journey,
we were favoured to reach our friend John Smith`'s in the evening, who,
with his wife and family, showed us every kind attention we needed.

Seventh-day, attended the Select Yearly Meeting, which was large;
the Great Master being pleased to own us together:
for the unmerited favour of being able to participate with my friends in these feelings,
unworthy as I am, I hope I felt truly thankful.

First-day, attended meeting at White-water, about one mile out of Richmond;
which was thronged, and a great concourse of people outside,
it was supposed there were nearly four thousand persons in and out of the house:
Friends were constrained to acknowledge, that the Ancient of days in his unmerited mercy,
was pleased to condescend to show himself abundant in lovingkindness to his revolting,
backsliding people.
At the close of the meeting,
one of Elias Hicks`'s party gave notice of a meeting
to be held by Elias Hicks on fourth-day at Richmond.

Second-day morning, attended the African committee:
the care which Friends of this Yearly Meeting manifested
for this much neglected portion of our fellow creatures,
was set forth in a report laid before this committee.
The Yearly Meeting for transacting the general concerns of the Society,
assembled this morning, and was very large.
It being known that there were some individuals in
the meeting who had no claim to sit there,
they were importuned to leave the meetinghouse;
but as they manifested an unwillingness to do so, they were informed,
unless they complied, their names would be exposed and minuted down by the clerk;
on which several left the house, and it appearing the meeting was select,
the clerks proceeded with the business.

Third-day morning, attended the adjournment of the Meeting for Sufferings:
the names of such of the members of this meeting as had united
themselves to the separatist party were brought forward,
in order to their being laid before the Yearly Meeting; the meeting`'s taking this step,
it was evident, closely tried the minds of some Friends present,
but Truth prevailed over the affectionate part, and by keeping in patience,
a general uniting prevailed,
and the names were ordered to be taken forward to the Yearly Meeting.
The meeting again assembled, and though the business occupied much time,
it was conducted in great harmony.

Fourth-day, the public meeting for worship was held; Elias Hicks had appointed a meeting,
to be held at the same hour in a barn adjoining the meetinghouse lot,
which his party had fitted up for him; notwithstanding which,
the meeting of Friends was large, and proved a quiet, favoured one.
In the evening I attended an adjournment of the Indian committee,
which was placed in a difficult situation,
in consequence of the funds which were designed to support the concern,
being in the hands of those persons of Baltimore Yearly Meeting,
who have identified themselves with the separatists.
It appeared,
that application had been made by missionaries of
other societies to take the charge of the Indians,
but that the latter had uniformly rejected their offers, stating,
that they had taken the Quakers by the hand, and would hold them fast;
that they always gave them good advice, and told them things which made them glad.

Fifth-day, 23rd of tenth month, attended an adjournment of the Select Meeting,
where several weighty testimonies were borne,
and pertinent remarks made on the state of this part of the body.

First-day morning, the meeting for worship was very large,
although Elias Hicks had appointed a meeting to be held in the
barn adjoining the meetinghouse lot at the same hour;
we were favoured with a quiet, comfortable sitting together.

Second-day morning, the Yearly Meeting again met,
and after a sitting of nearly six hours, closed under a very precious and awful covering.

On third-day morning, I set out, in company with several Friends, to return eastward;
the next day at noon we reached Cincinnati.
Feeling drawings in our minds to sit with Friends there,
a meeting was appointed to be held that evening,
and we had cause to believe both visitors and visited
were satisfied with the time we passed together.

Fifth-day morning, we again pursued our journey, crossed the Ohio river in a horse boat,
and landed in Kentucky, a slave-holding state;
on which my feelings were awakened to a thankful sense of being no man`'s slave.

On second-day morning, about half a mile out of Mount Vernon,
we had a considerable mountain to ascend, and, to make it more easy of access,
bodies of trees were laid from the foot to the summit; a heavy fall of rain in the night,
and a very large drove of fat hogs which preceded us,
had occasioned the road to be very slippery; on reaching about half way up the mountain,
our carriage ran back, our horses turned round,
and turned the carriage off the road into a hole about three feet deep,
among the rocks; I was favoured to escape unhurt, although in the carriage:
we managed to get it brought on the road again, and pursuing our journey,
reached the top of the mountain in safety.

This morning, we were met by a company of slaves, some of them heavily loaded with irons,
singing as they passed along; this, we were informed,
was an effort to drown the suffering of mind they were brought into,
by leaving behind them wives, children, or other near connections,
and never likely to meet again in this world.
A short time after we met another company; one respectable-looking,
rather well-dressed slave, attracted my attention;
his hand was grasping the hand of a fine looking girl, about fourteen years of age,
his countenance appeared very dejected and melancholy.
I was led to conclude, from the affection with which he appeared to treat the girl,
that she must be his child, whom, in all probability,
he expected soon to be compelled to part with for life.
After this came two wagons, in which they were conveying some who were not able to walk,
also the children, all going to be sold at a market, like cattle.
It being time for us to bait our horses, while they were feeding,
I walked to some distance from our tavern, and observed a handsome carriage standing,
which I supposed belonged to a pedlar,
as it appeared to be loaded with coarse woollen goods:
I addressed myself to the owner of the carriage,
telling him he had a load of more bulk than weight; on which he replied,
his carriage contained the clothing of the company of slaves we had passed on the road,
of which he was the owner, saying,
he was seeking a market where he might dispose of them to the best advantage.
I told him his business was a very bad one,
and that a day of reckoning would come in which he would have to
account to his Maker for his conduct towards these poor creatures.
He replied, he believed so too, but said, I have them, and what am I to do with them?
I told him, I believed, were I in his situation,
my duty would point out to me the necessity of liberating them,
and if it were not in my power to do it in any other way,
to sell all my goods and chattels, and part with the last cent I had,
to assist them in getting to a free country.
To which he replied, it was a bad trade, and he wished it was wholly done away with.
I told him to consider, that same Almighty Power which created him,
created the coloured people; and I asked him,
should his wife and children be torn from him,
as these poor creatures had been torn from their near connections,
how would he feel under the like circumstances?
he replied, he should feel it a hard case.
I told him he had better die poor than amass wealth
by such means as he was aiming to get it by.
I then made inquiry into the situation of the respectable
coloured man I had seen with the other slaves;
he informed me, that this man had left behind him a wife and children,
the property of another slaveholder.
When he took his leave of me he said,
he hoped he should remember the remarks I had made to him.

Sixth-day, our road lay over the Blue Mountains; the ascent being gradual,
our difficulties did not commence until we reached the summit and began to descend;
the descent is computed to be nearly two miles to the foot of the mountain;
my companion remained in the wagon and I footed it, fearing the injury of our wagon,
from the great steep we had to descend, the large stones in the road,
and trunks of trees we had to travel over.
Before we reached the bottom, we had so splintered one of our axletrees,
and broken some of our bolts,
that I began to doubt our being able to reach the house
where we proposed to take up our abode for the night.
On our arrival at the foot of the mountain,
we dared not attempt to proceed until some repairs were accomplished.
We observed a despicable looking tavern, not a pane of glass in any of the windows,
nor did it appear there ever had been; the night threatened to be very cold and frosty;
and how we were to make out here for the night, after such a fatiguing day`'s journey,
I was at a loss to comprehend: on querying with the tavern-keeper,
if he could take us and our horses in, he replied,
he would do his best to make us comfortable, which rather cheered me,
and I told him we would be satisfied with his best.
The rest of our company soon arrived,
and after we had refreshed ourselves with a good hot supper by a comfortable fire,--our
landlord and his family defending the windows with various woollen articles,
we received no injury, but passed a comfortable night;
I had a good bed and plenty of covering.

Next morning we again pursued our journey; and took up our abode at an inn for the night:
two men who were strangers to us, formed a part of our company in the sitting-room;
they inquired of us relative to the droves of fat hogs we had met on the road;
on our giving them such information as we were able, one of them observed,
he had taken a drove of six hundred to one of the markets,
and offered them at ten per cent, discount,
and to take the pay in negroes (!) but could not succeed.
On my companion remarking to him on his trading in his fellow creatures,
he excused himself by saying,
if he had made such an exchange it would have been for his own private use;
but in the course of conversation he gave sufficient
proof that his motives for trying to make this purchase,
were not such as he would have had us to suppose; for on our remarking,
we had met a wagon-load of negro children, and men and women on foot,
he said he would have purchased the whole cargo if he could
have agreed with the owner of them about the price.
Although I felt much at the time he made these remarks,
yet silence appeared to be my proper place; but in the morning, before we parted,
I found it laid upon me to open my mind to him freely
on the iniquitous practice of dealing in,
or keeping in bondage, our fellow creatures,
and to warn him against pursuing such evil courses.

Early this afternoon we reached the comfortable abode of our kind companion, Abel Coffin,
after a journey of about five hundred and sixty-six miles, and eighteen days`' travel,
without rest, except part of a day, and at night.
I was weary in body, but, through adorable mercy, quiet in mind; and I humbly hope,
able to say,
bowed in feelings of reverent thankfulness for the preservation which we experienced.
The weather much favoured us, but little rain having fallen while on our journey;
but during this night,
there was a heavier fall of rain than has been known for a long time,
which in all probability must have impeded our journey, had we not arrived previously.

Seventh-day, 1st of eleventh month,
attended the Select Yearly Meeting for North Carolina, held at New-garden,
which was large.
Caution, counsel, and encouragement were dealt out,
to the tendering of many of our hearts;
causing feelings of humble gratitude to the great
Dispenser of these favours through his poor instruments.

First-day, attended meeting at Deep-river, which I understood was smaller than usual,
occasioned by the great quantity of rain that has fallen since our arrival.
In the afternoon we proceeded to New-garden.

Second-day, the Yearly Meeting opened, which was numerously attended.
The next morning we attended an adjournment of the Meeting for Sufferings,
which was chiefly occupied in the concerns of the negroes under Friends`' notice.
Friends here are much to be sympathised with,
on account of the great load of care and exercise that has devolved upon them,
in consequence of the unjust and oppressive laws of their state,
relative to this long-neglected race of our fellow creatures.

The Yearly Meeting again met;
and the state of Society as exhibited by the summary answers to the queries,
was the first subject of consideration;
and in order that it might be more effectually entered into,
men and women Friends united, and the shutters were raised between their houses.
The clerks of the men`'s and of the women`'s meetings read the summaries
which had been prepared from the answers of their respective meetings;
the deficiencies in the answers of both meetings were fully considered,
and spoken to in a convincing and awakening manner.
It proved a season of favour,
which I believe never will be wholly erased from minds that were
present;--vocal praises were offered for this continued mercy.
The meeting was brought under exercise, on account of the departure,
which had of later times taken place among some of the members of this Yearly Meeting,
from plainness of dress and address, and not altogether confined to the youth;
many pertinent remarks were made thereon, and much salutary advice communicated.

The following circumstance was related in the meeting,
by a Friend who was an eye and ear witness,
and who had acted as one of the jurors in the case:--four
men were called to be witnesses in a trial before the court,
and were required to take the oath; all were dressed alike fashionably.
On being directed to put their hands upon the book, all were sworn but one,
and they departed, leaving the one standing; which the judge observing,
he addressed this individual in nearly the following language.
"`Do you affirm?`"
He answered, "`Yes.`"
"`Are you a Quaker?`"
He said, "`Yes.`"
"`Do you belong to that church or Society?`"
He said, "`Yes.`"
After a little pause, the judge replied, "`The time had been,
when the members of that Society were known by their peculiar dress and appearance;
but it is not so now; you could not be known by your dress,
you are like a ship on the sea or privateer sailing under false colours,
that it may not be known.`"
I felt it best to give this circumstance a place in these memoirs,
should they ever meet the public eye, in hopes it may prove as a watchword to such,
who may be tempted to gratify their natural inclination,
by departing from that simplicity into which the Truth first led its followers.

Fifth-day, after a sitting of about five hours,
the Yearly Meeting finished its business under feelings of gratitude,
that it had been owned by the extension of holy help.

Sixth-day, we rode to Centre, and attended the Western Select Quarterly Meeting,
which was small.
Seventh-day, attended the Quarterly Meeting for discipline,
which gathered very disorderly.

First-day, we rode to Providence, and sat with Friends of that meeting; among whom,
through holy help, I humbly hope, I was favoured faithfully to acquit myself.
In the afternoon we rode to Salem, to attend a meeting there, appointed at my request.
Second-day evening,
I was favoured to rest in body and mind in the well-conducted
family of our companions from Indiana.

Third-day, we rode to Marlborough, to attend an appointed meeting,
which was long in gathering, but in time the house was nearly filled:
many infants were brought in, but my mind was not permitted to be disturbed by them.
Our kind friend Nathan Hunt, who was once engaged in religious service in my native land,
gave us his company.
I had to advocate the Great Master`'s cause with
such as were trampling on his precious testimonies,
and to hold out the language of encouragement to the few,
for they appear to be very thinly strewed in this meeting,
faithful followers of "`the Lamb of God,
which takes away the sins of the world:`" after meeting we rode home with Nathan Hunt.

Fourth-day morning, attended the Monthly Meeting of Springfield.
In the meeting for worship I had to stand up with nearly the following expressions:
"`When a careless, lukewarm, indifferent disposition of mind is given way to,
by the female head of a family, domestic matters are generally brought into confusion;
carelessness being the mother of waste,
and woeful deficiency is frequently the consequence hereof;
and this will apply with respect to spirituals as well as temporals.`"
I felt not a little tried at being obliged to express myself in this way,
but I was afterwards informed,
what I offered was very appropriate in every sense
of the word for some in the meeting to take home.

Fifth-day, went to an appointed meeting at Union,
which we were informed was pretty generally attended by its members,
and some Friends from a neighbouring meeting.
Although I had close things to deliver to the unfaithful,
yet Friends appeared generally to part from us affectionately.

Sixth-day, 14th of eleventh month, we went to Deep-creek;
on our way we had to ford the river Yadden, said to be a quarter of a mile across,
which we found very deep: fording these rivers,
which are rendered dangerous by the rains,
often puts my faith in the superintending care of an Almighty Power closely to the test.

Seventh-day morning, attended the Select Quarterly Meeting for Westfield,
held at this place, in a log meetinghouse;
we were obliged to sit with both the doors open for light; and the frost being intense,
I suffered not a little; there was no convenience for making a fire in the house.
The houses of the attenders of this meeting not being
in a much better state than the meetinghouse,
the Friends would not suffer as I and my companion did from that cause.
The meeting was small,
many Friends having left this Quarterly Meeting and settled in Ohio, partly, it is said,
on account of North Carolina being a slave state.
There being but little business,
this meeting closed a considerable time before the
Quarterly Meeting for discipline commenced;
and no Friends`' houses being near, we, who are strangers to such a mode of proceeding,
found it to be a great exercise of patience to endure the cold.
The Quarterly Meeting for discipline was very small;
and the few well-concerned members of it are much to be felt for.

First-day, the meeting was very largely attended by those not of our religious Society;
and many were obliged to remain outside of the house;
it was considered to be a time of Divine favour,
holy help being near to enable those who had to minister, to divide the word aright:
I believe praises ascended from the hearts of many to the God of all comfort and consolation.
We had a solid sitting in a Friend`'s family in the evening, which closed another day,
in addition to those gone before, to account for to Him, who sees not as man sees,
but who looks at the heart, and weighs not only our actions, but our motives to action,
in a just and equal balance.
May I not, when weighed in this balance, be found lacking,
is the secret breathing of my soul.

In passing through the Moravian settlement, on our way to this Quarterly Meeting,
I left with the preachers of it some of the Declaration of the Yearly Meeting in Philadelphia;
during this halt, apprehensions were awakened in me,
that some religious service would be called for at my hands in this settlement,
before I was clear of North Carolina.

Fourth-day morning, we reached Newberry meeting;
notice having been given to members and such as were
in the practice of coming to Friends`' meetings,
I understood there was a pretty general attendance.
I hope I was favoured to feel truly thankful for the help which was administered,
and that my mind was relieved: may the praise be given, where only it is due!

The next day, attended meeting at Concord; we sat in this meeting nearly half an hour,
before we had any addition to the family where we had lodged; in time,
three men and one young woman were added to our number,
which made the whole of our meeting.
Before the meeting separated,
a Friend stood up and expressed the satisfaction
it had afforded him to be one of our little company:
and he advised Friends to treasure up what had been cast before them; I left the meeting,
thankful I had given up to attend it.

Sixth-day, 21st of eleventh month, proceeded to New Salem,
and attended the Select Quarterly Meeting there, which was small,
in consequence of the great quantity of rain that had fallen:
some of the Friends of this meeting resided on the other side of Deep-river,
which they have to ford to get to meeting, and which had risen, it was supposed,
fourteen feet above its usual height.

Seventh-day morning,
the Quarterly Meeting for the general concerns of the Society commenced,
which was considered to be very small, occasioned, it was supposed,
by the difficulties in travelling:
I thought there was good cause for believing that the meeting separated
under a grateful sense of the continuance of holy help,
which had been extended in transacting the several matters that came before it.

First-day, attended what Friends here call the public meeting,
because there is in general a large attendance of those not of
our religious Society on the first-day after the Quarterly Meeting;
the house was filled with company.
We were favoured with a quiet, comfortable sitting together,
and I left the meetinghouse thankful,
however the expectations of the people might be disappointed,
that I was preserved from attempting to offer what was not intended to be given to others.
We had a comfortable sitting in the family at our quarters, before we retired to rest;
and thus closed another day,
to account for to Him who will judge of our actions according to our motives,
whether pure or not pure, and who will reward us accordingly in that day,
when there will be no possibility of correcting the errors we may have made.

Second-day, in company with our friend Phineas Nixon, we ventured to ford Deep-river;
the current was very strong, and the bottom rocky,
yet we were favoured to get safely through,
and reached our friend Phineas Nixon`'s quiet abode to dinner.
Third-day, I rested, and wrote a letter home to my dear wife and family.

Fourth-day, attended Monthly Meeting at Deep-creek:
I had to labour with those who were at ease in Zion, trusting to a name to religion,
I believe to the relief of the minds of the few faithful
followers of the Lamb in this Monthly Meeting.

Seventh-day, attended New-garden Monthly Meeting;
the meeting for worship was to me a very low time.
After the meeting had sat a considerable while together,
a Friend proposed that the business of the Monthly Meeting should be entered upon;
I had sat for a great part of the meeting under the weight of something to communicate;
but fearful of breaking silence, and fearful also to keep any longer,
the little opening my mind had been exercised with,
I ventured towards the close of the meeting to stand
up and cast before them my little offering,
to my own relief and the quiet settling down of the meeting;
for which favour I hope I may say I felt truly thankful.

First-day, attended Dover meeting:
my service was to labour with those who were settled as on their lees,
easy and unconcerned as it respected a consistency
of conduct with the profession they were making;
also to warn such against the sorrowful consequences
that would eventually result from this careless,
unconcerned disposition of mind, if continued in.
The meeting closed under a precious covering of good.

Fourth-day, attended Hopewell meeting, which gathered very irregularly;
but after it was fully gathered, we were favoured to settle down in that holy quiet,
which, if carefully abode under,
needs not the medium of words to render our coming together truly profitable:
this meeting was, I believe, a time of renewed visitation to many of the members of it;
sympathy was awakened in my mind towards the few still preserved
alive to the promotion of the cause of Truth and righteousness.

Fifth-day, 4th of twelfth month, we attended the Monthly Meeting at Deep-river;
and I had good ground to hope I was in my place.
May the praise and the glory be given unto God for the word of his grace,
without whose renewed aid nothing that is truly good can ever be accomplished.
After meeting, we rode to our friend Jeremiah Hubbard`'s.

First-day, we went to Kennet meetinghouse;
it was as rainy a morning as I remember ever to have turned out in,
yet the meeting was large.
I felt much for the few honest-hearted members of this meeting;
it appeared from feelings my mind had to experience, while silently sitting among them,
that the living were scarcely, if at all, sufficient to bury the dead.
Oh! how those are to be felt for,
whose lot it is thus to sit solitary in meetings and out of meetings;
yet they have this consolation to flee to, in all their seasons of dismay,
that the Lord knows them that are his; and in the day when he makes up his jewels,
if there is but a faithful continuing in the way of well-doing, and in the daily cross,
to the end of the race, he will spare them, as a man spares his only son that serves him.
Fourth-day, attended meeting there,
which I was favoured to leave under a hope I had not been out of my place.

Fifth-day, we rode to Sherbourn, attended their mid-week meeting, which was very small.

Sixth-day morning, we rode to our kind friend Nathan Hunt`'s, at Springfield.
First-day, attended meeting at Piney-woods, which was very small;
it appeared to me Friends here were scarcely equal to keep up a meeting reputably,
although we were led to believe there were two or three,
who in a good degree felt attached to the cause of Truth,
and were desirous to be found walking answerably to its dictates.

Feeling as I apprehended that the time was come for me to attempt
to hold a meeting in the Moravian settlement at Salem,
I proposed the same to the Friend with whom I lodged;
the village being wholly under the control of that religious community,
I understood Friends and others, except in one instance, had been refused that privilege;
yet I saw no way for my relief,
but by being willing to do my part towards its accomplishment.
We proceeded to Salem: on our reaching the settlement,
we waited upon one of the active members of the Society;
I presented him with my certificates, which he appeared slightly to look over,
and returned them to me again, which proved rather discouraging;
but I found I must not be cast down thereat, but do my part.
I informed him of my apprehensions of duty, to try to have a meeting in the settlement;
but this it appeared, did not meet his views with cordiality--he replied,
that no meeting could be had before evening,
and then it was doubtful whether such a liberty could be granted me,
yet he offered to go to one of the ministers and bring us word.

Believing it would be safest for us to accompany him,
always having found it best for me to try to obtain an interview myself with the principals,
who might have any thing to do with my religious concerns; I proposed our going with him,
and we set out together.
But he objecting to this, and one of our company proposing our returning to our tavern,
he then urged it again; and I yielded from persuasion, but not from conviction,
for which I afterwards suffered deeply in my own mind.
In about an hour our messenger returned to us,
saying he had not been able to see the person necessary to be consulted,
nor could he be seen until one o`'clock,
and that it was uncertain if he could then be seen; adding,
he supposed we could not stay so long as that.
I felt as if he wished to get quit of us, but we concluded to wait until that hour,
being fully satisfied I had done wrong in returning to our tavern,
and that if way did not open for me to prosecute my religious prospects,
I should have cause to reflect upon myself,
as not having done all that was in my power towards its accomplishment.

When one o`'clock came, and our messenger did not arrive,
I made inquiry who was the chief person in the settlement, and where he resided;
on receiving the necessary information, I concluded we must go to him;
we therefore proceeded: on our way my mind became very much tried,
lest the step I was now about to adopt should offend our messenger,
and thereby block up my way for effecting what I had in prospect; but after all,
I could see no course but for us to proceed to the house.
On our arrival, we were directly introduced to him; he received us very cordially,
and I opened my prospects of a meeting in their meetinghouse;
but this at first did not appear to be united with.
I was kindly offered the use of their schoolhouse for a meeting,
but this not according with my views, I was obliged to decline the offer.
Feeling it laid upon me, in addition to what I had before proposed to him,
to request to have a meeting with their ministers and elders, in fear and trembling,
I think I may say, I ventured to do so;
this latter request beyond my expectation appeared to be readily fallen in with,
and four o`'clock was concluded upon for their ministers
and elders to assemble for this purpose;
the other meeting was to be further considered.
I felt thankful I had thus pursued my prospects, and that way had been made for me so far.

We were careful to be punctual in keeping to the time appointed;
the company we met with was small.
After a short interval of silence,
I expressed the regard I had long entertained for the Moravian brethren,
but that sadness had covered my mind in passing through
their settlement some weeks before,
on being informed they were in the practice of holding men in slavery.
I then related the interview I had had with a slave-merchant in Baltimore,
who attempted at first to justify his trafficking in his fellow creatures,
by the example of individuals who did so, and yet were, he said,
making a profession of Christianity.
I endeavoured to impress on the minds of our little company,
the necessity there was for them to grant their slaves their liberty as a Christian duty,
and to set a good example to such as might be at times awakened to see
the iniquity of the practice of holding our fellow creatures in slavery.
We were informed their members were advised against the practice.
Although I felt much tenderness towards them,
yet I found I must press the necessity there was, ranking high as they did,
as professors of Christianity, that they should make it a part of their discipline,
and one of the terms of continuing in religious membership with them,
as our Society had done.
I found great openness to receive what I had to offer;
and I believe we were brought very near to each other
in the bonds of true religious love.
On my asking the question,
if it would be allowed me to have a meeting in the town in their house that evening,
a united consent was expressed: one of our estimable company, for so I felt them to be,
expressed a fear,
as our manner of sitting together to worship was so different to others,
the children might not behave as orderly as they would wish them.
They however fixed the time, and undertook all other arrangements for the meeting.
We had a large and satisfactory meeting; the chapel, which is a commodious building,
was well lighted up, and, contrary to the expectation expressed to us, the children,
of whom there was a considerable number, behaved in a solid becoming manner.
The meeting being over, after taking an affectionate leave of our kind friends,
who granted me this privilege, we returned to the tavern,
the individual who at first became our messenger, kindly accompanying us there,
and attending upon us until we took our departure; he parted from us,
as I hope I can truly say I did from him, in feelings of near affection:
we rode about six miles to the house of an attender of Friends`' meetings,
where we took up our abode for the night.

First-day, 14th of twelfth month, attended meeting at Eno,
which we found to be very small, partly, we were told,
occasioned by marriages from among Friends: our visit appeared to be well received.
The close of this day affording a peaceful retrospect,
I humbly hope I was not deficient in my care to return the Lord thanks.

First-day, attended Sutton`'s-creek meeting, which was small,
having been reduced by deaths and removals into free states.
Family concerns calling my kind companion home,
I could not do otherwise than willingly release him,
aware that his own Monthly Meeting had need of his help,
from the sorrowful convulsion that had taken place therein: we parted in near affection,
after having travelled together many months in much harmony.

Fourth-day, attended Newbegun-creek meeting, composed of Friends and others,
a number of whom were coloured people: the meeting was held in quiet.
I was led to hope the minds of some were introduced
into a feeling sense of what was offered;
one woman in particular, not professing with our religious Society,
who came into the meeting as with stretched-out neck and wanton looks,
before the meeting closed manifested much tenderness,
as if she was really brought down into the valley of true pleading,
where the voice of the Shepherd is clearly and distinctly heard.

1st of first month, 1829.
Fifth-day, attended the Narrows meeting, after which we attended a committee of Friends,
who have the charge of a considerable number of free coloured people,
some of whom have been freed by Friends,
and others have been willed to Friends by persons not in profession with our Society,
in order to their becoming free;
the great load of care that has devolved on this committee,
calls for the near sympathy of their absent friends,
from the ignorance and untowardness of those they have to do with,
in addition to the severity of the laws of the state relative to free coloured people.

Seventh-day, attended the Monthly Meeting of Piney Wood;
we had a large meeting of Friends and others,
and I hope our sitting together might be said to be a time
of comfort and encouragement to the feeble-minded.
The concerns of the meeting for discipline appeared to go heavily forward,
for lack of a more lively zeal to assist the clerk by properly
speaking to matters that were before the meeting.

First-day, attended Beech-spring meeting,
at which were many not in profession with Friends,
among whom there appeared much openness to receive what was communicated,
and the meeting separated under a degree of solemnity.

Fourth-day morning, attended Little-river meeting, and the next day,
attended Symond`'s-creek meeting;
we had the company of many not of our religious Society,
in whose minds I was led to fear there was not much openness to receive what was offered;
and yet the necessity being felt to labour as ability was afforded,
I found there would be no way for me to secure that
peace which only can sustain the soul,
but by being faithful, and leaving all to the Divine disposal.

Seventh-day, attended Sutton`'s-creek Monthly Meeting; the weather was severely cold,
and the meetinghouse being cold and comfortless,
occasioned me much suffering during the meetings,
the doors being obliged to be open the whole of the time to give sufficient light.

First-day, attended Wells meeting; the weather continuing very severe,
I had a suffering meeting,--daylight appearing through the roof in at least twenty places,
and the doors obliged to be open for light; this meeting, from a large one,
is now so reduced, partly by Friends moving into the free states of Ohio and Indiana,
and partly by deaths, that it is expected it must be discontinued.

Fourth-day, accompanied by my kind friend Aaron White, we had a meeting at Richsquare;
notice having been given of my desire to see the members and attenders generally,
the meeting was large;
and Friends kept their seats more than is often the case during the time of the meeting.
Here I met with a number of solid Friends, in sitting with whom I felt good satisfaction.

Fifth-day, 15th of first month, 1829, we proceeded towards Virginia;
and on seventh-day attended Monthly Meeting at Gravelly-run,
which is greatly reduced by Friends moving into the Western country,
and it is likely to be more so.
I felt well satisfied in sitting with Friends here, some of whom are to be felt for,
as they have to come forty miles to attend their Monthly Meeting.

First-day, attended meeting here:
some not in profession with Friends gave us their company; it proved to me an exercising,
trying time.
In the evening we had a quiet religious opportunity in a Friend`'s family: after which,
taking a retrospect of the proceedings of this day, before I retired to rest,
feelings of gratitude and praise to the great Author of all that is truly good,
were in mercy the clothing of my mind.

Third-day, attended Stanton`'s meeting: a considerable body of Friends, I was informed,
once composed this meeting, but now it consists of only two families.
These have since that time removed into the Western country,
and the meetinghouse is shut up.

The next day, attended meeting at Blackcreek;
many not of our Society gave us their company.

Fifth-day, attended Johnson`'s meeting: and on seventh-day,
the Monthly Meeting for the Western Branch; it was long in gathering,
which greatly interrupted the quiet settling of the assembly:
at the close of the Monthly Meeting the Select Meeting was held, consisting of six,
in the station of elders;
there are now only two acknowledged ministers in the compass of this Yearly Meeting.

First-day, attended Summerton meeting, which was large,
and I humbly hope profitable to some of us,
a season in which the lukewarm and indifferent were laboured with.

Second-day morning, we set out on our journey to Lynchburgh,
a distance of about two hundred miles, and chiefly away from Friends.

Fourth-day, we took up our abode at a tavern for the night;
this has been to me as trying a day as any I have had to pass through for some time.
From the quantity of snow that had fallen, and bad roads,
our poor horses were greatly fatigued; we were truly thankful when on seventh-day night,
about dark, we reached Lynchburgh.

First-day, 1st of second month, 1829, attended the meeting of Friends,
about three miles from the town, in a cold, comfortless house.
The meeting was long in gathering, which caused it to hold beyond its usual time,
but the people remained quiet to the last.
I felt well satisfied in having given up to travel so far,
at this inclement season of the year, to sit with Friends of this place,
although the prospect of a succession of faithful standard-bearers is discouraging.

Second-day morning, we left
Lynchburgh: it rained and froze, which made the prospect of our journey discouraging;
but we were favoured to reach the neighbourhood of Vicks`' meeting,
on seventh-day evening.

First-day, the meeting was held in a Friend`'s house; after which,
our kind friend Richard Jordan piloted us through the swamp, the water being very deep.

Sixth-day, attended the Select Quarterly Meeting at Blackwater:
it was to me a low trying meeting;
I was led into near sympathy with the little number I met with,
endeavouring to press upon them the necessity there was
to keep near to the spring of Divine life in themselves,
as the only way to experience preservation in their low seasons,
when led to take a view of the stripped state of the church within their borders.

Seventh-day, we attended the Quarterly Meeting at Black-river;
and on first-day the meeting for worship there;
a more disorderly meeting I never attended;
a great crowd of persons assembled not professing with Friends,
many of whom remained during the meeting outside the house in conversation,
where they made up a fire and regaled themselves.
A considerable number of people of colour made a part of our company,
whose good behaviour must, I think,
have shamed many of the white people who were in the meeting:
in the evening we had a quiet religious opportunity at our quarters.

Fourth-day, we attended meeting at Burleigh; and on fifth-day, rode to Richmond,
and were kindly received by our friend Thomas Ladd.

First-day, attended meeting there, which was very long in gathering;
but in time settled down in outward quiet,
and I humbly hope the silence of all flesh was in degree known by not a few of our company.
A visit to the penitentiary had a little exercised my mind,
but the way had not yet opened with clearness to speak to my friends on the subject.
I returned to my quarters.
Fearing the result of giving way to unnecessary discouragement,
and not doing my part towards the discharge of this apprehension of religious duty,
I opened my prospects to my kind friend Thomas Ladd;
and proceeding to the house of the superintendent of the prison,
he kindly granted my request; the prisoners, about one hundred and fifty in number,
were assembled.
Great quietness was manifested,
and I was favoured to leave the prison with feelings
of gratitude to my great Almighty Master,
who had in mercy been a present help to me in the needful time.

Second-day morning, we rode to Cedarcreek, and on fourth-day,
attended the Select Quarterly Meeting: if my feelings were correct,
there are yet left in this meeting those who are preferring
the cause of Truth and righteousness to every other thing.
Fifth-day, attended the Quarterly Meeting for discipline, which is reduced to a very few.
Sixth-day, we returned to Richmond.

Seventh-day morning,
being brought under apprehensions of duty to attempt
to hold a meeting in the place of religious worship,
built on the ground where the theatre had stood,
which was destroyed by fire some years ago; on informing my friend Thomas Ladd thereof,
as the place was the property of the Episcopalians,
it appeared best to apply to the bishop.
Accompanied by my companion and a son of my landlord,
we proceeded to the house of the bishop, by whom we were kindly received.
After he had made a few inquiries relative to the time I left England,
and other indifferent matters,
I prefaced my business with him by presenting him my certificates,
and when he returned them, I said to him nearly as follows;
"`Whenever my mind has been turned towards Richmond,
it has been accompanied with a belief,
that if I reached this city it would be required of me to be willing
to apply for leave to hold a meeting in the place of worship built
on the ground where that theatre stood which was destroyed by fire,
not then knowing to what religious sect it belonged;
but understanding it is the property of the Episcopalians,
I am come to throw myself upon the kindness of the bishop for his aid in this matter.`"
To which he answered, "`I am but an individual;
it is the vestry in whom the power rests to grant such a request;
I will consult the vestry tomorrow:
if they should not be willing to grant the use of the church,
there is a large school-room in the graveyard,
with which perhaps they would be willing to accommodate you;
or there is a large room at the capitol,^
footnote:[The capitol contains the general courthouses or offices of the State.]
which I expect you might have for the purpose, if applied for.`"
I paused for awhile and found no way open in my mind that would
justify me in accepting either of the two last-mentioned places,
but that I must keep firm to my first prospect of religious duty,
if I had any such meeting in Richmond.
I therefore informed the bishop to this effect;
"`I have believed it was right for me thus to cast myself upon you for help,
and having now done as far as in me lies,
in order that this part of my religious duty should be carried into effect,
if the way does not open for my request being granted, I believe, as respects myself,
the will will be accepted for the deed:`"

I then requested him to be so kind as to send me
a note when the mind of the vestry was known.
On which the bishop queried with me, "`had I any prospect,
if liberty should be granted me, of referring to the theatre?`"
I told him, if way opened for my request being granted,
I was not prepared with any thing in prospect to offer there.
He said his reason of putting this question to me was,
that a friend of his engaged to preach for him on a sunday afternoon,
whose mind having been previously occupied with the consideration of theatrical amusements,
introduced the subject in the course of his sermon;
his so doing gave great offence to some who held pews,
many of whom instantly leaving their seats, went out of the church,
and this circumstance appeared to lay the foundation for a new theatre being built;
for some of those who thus withdrew at that time began a subscription for the purpose,
and followed it up until money was raised for completing one:
until this circumstance occurred,
they had no theatre in Richmond after the former one was consumed.

First-day, attended meeting there, which was small;
the prospect of a succession of rightly qualified members to maintain
the wholesome discipline established among us,
is as discouraging as in any meeting I have yet attended on this continent,
both as it respects male and female,--very much owing I believe to the sad effects
of a too free interaction with those out of our own religious Society.
I left the meeting under a hope that what I had to offer among them would not be lost;
I had not daubed as with untempered mortar,
but had given faithfully that which appeared to me to be the counsel of my Divine Master,
whom, I hope I may say, I desire to serve with a perfect heart and a willing mind.
I passed a few silent moments at the monument erected over
the depository of the few mangled remains of the sufferers,
when the theatre was consumed; from the various inscriptions,
it appeared that seventy-three souls, including two children, were,
by this disastrous circumstance, plunged into eternity, comparatively speaking,
as in a moment; the consideration of which produced awful feelings in my mind,
more easily felt than described;
especially when I recalled to mind the manner in
which they were spending their precious time,
and the gaiety of disposition excited in most, if not all,
by the vain pleasures that were set before their eyes,
when the curtain of death was thus awfully drawn over them.

Third-day, attended meeting at Wain Oak;
the meeting suffered greatly owing to the disorderly manner of its gathering;
the prospect of some of the young men here becoming useful members in the Society
were more encouraging than is generally the case in this Yearly Meeting.

Seventh-day, attended the Monthly Meeting at Wain Oak;
this meeting suffered from a lack of that religious energy,
which is in degree the life of our meetings for discipline, and for lack of which,
in those who should help forward the business,
more is imposed upon the clerk than meetings are warranted in doing.

First-day, our meeting was small,
but I hope it proved to some of us a time of renewing covenant:
that we may be as careful to be found keeping our covenants as we are to renew them,
is the frequent fervent breathing of my soul.

Second-day, rode back to Richmond, where I found a note from the bishop, saying,
he had conversed with a few of his friends,
who considered it inexpedient to grant my request,
but if I would use the capitol for a public meeting,
he would with great pleasure attend the service.
I gave the capitol a further consideration, which I found could be easily obtained,
but the way not opening for me to move further in it than I had gone,
the matter rested there.

Third-day, having still in my possession a few printed sheets on theatrical amusements,
headed with the query, "`Why don`'t you go to the play?`"
I procured a young man to conduct me to the residences of some of those most
esteemed for their piety and rightly tempered zeal for the good of others,
among the Baptists, Presbyterians and Methodists,
and furnished each of them with some of those sheets, accompanied with this charge,
"`I have now done my part towards having publicity given, in this city,
to the salutary advice and caution these sheets of paper contain;
be faithful and do your part.`"
I found they were well received, and where they were read over,
accepted as a treasure in a needful time,
when exertions were making to promote stage entertainments:
thus closed my engagements at Richmond,
I humbly hope under a grateful sense of the need I had, afresh to set up my Ebenezer,
to the praise of Him who had helped me, and been present with me in every time of trial.
