== Chapter XLI.

In the year 1830, apprehending I was called upon by my Divine Master,
to bring more generally into view some parts of the Address to our own religious Society,
which I believed it required of me to issue a few years back,
a care was on my mind to see the right time to engage in it;
and believing this time was fully come, I earnestly besought the Lord for help,
to select such parts and make such additions as would be in accordance with his will.
Having, as I apprehended, been enabled to do the needful in this respect,
and put it into the hands of a Friend for revision,
in the year 1831 it was printed for circulation.

New South Wales is of late the subject of my daily thoughts,
and a report being in circulation, that I had given up this prospect of religious duty,
I felt my mind brought under the necessity, in the Select Yearly Meeting,
to inform my friends that this concern still remained with me:
although of late there have been seasons in which I have been disposed to query,
whether "`a ram`" would not be caught.
I earnestly craved, if such should be the will of my Divine Master,
that I might be preserved patiently waiting to know his mind and will,
and that he would prepare the offering,
even the whole burnt sacrifice he is calling for,--offered up in his own time and way.

Having for some months past felt drawings in my mind
to make a visit to the bishop of London,
on the 12th of fifth month, this year, agreeably to a previous appointment,
accompanied by my kind friend Peter Bedford, we waited on him at his residence,
and he received us kindly.
After a short pause, I felt myself constrained to inform the bishop,
that I had been an acknowledged minister in the Society
of Friends upwards of fifty years,
which I found had placed me in an awful and responsible situation;
inasmuch as I was aware my example was looked at by the body.
This led me frequently to consider how far the general tenour
of my conduct and converse corresponded with the doctrines,
precepts, and example of our holy Redeemer,
and how far I was earnestly concerned by example and precept,
to use my utmost influence in checking any wrong practices
that were in danger of creeping or had crept into the Society;
from an assurance that by neglect on my part,
I should be criminating myself in the sight of my Maker, by becoming a party thereto.

I then informed him, there was another subject I must lay before him, which was,
the great increase of intemperance;--fearful as I was,
unless some steps were taken to arrest its progress,
it would arrive at a similar height to that which it attained in
this country about a century back--having heard from my father
a deplorable description of the extent it then reached.
I presented him with a small volume of the tracts published by the Temperance Society,
which he received with pleasure.

I then urged him to promote the objects of the Temperance Society,
assuring him the exertions already used had been a great blessing;
on which it appeared he saw some difficulty in acting in this way,
intimating that some fiscal regulations on the part of government
would be necessary in order to suppress it:
to which I said, in the warmth of my feelings, "`But, my dear friend,
do seek for best help, to enable you to do what you can.`"

Books on our religious principles were then handed to him,
which he appeared to receive acceptably.
During the whole of the interview, he heard us with much courtesy,
and in a friendly and kind manner observed it was
desirable to have the good wishes of all Christians,
and that he was glad in receiving the visit; he shook hands with us,
and escorted us to the door, and soon after became president to the Temperance Society,
and a warm promoter of its interests.

On fifth-day, 27th of ninth month, 1832, I left town, accompanied by three Friends,
for Windsor,--arrangements having been made for me to have an interview with the king,
in order to present him with an address on some subjects
which had deeply occupied my thoughts,
the presentation of which appeared to be a duty.
We reached Windsor by ten o`'clock, and were conducted to the castle;
after some time we were introduced into the apartment of the king,
who was standing to receive us.
We were with him about twenty minutes; he was unattended,
and it may be said received us very graciously.
He entered into familiar conversation,
and held out his hand to receive the books we took with us, which my companion gave him;
after which I handed the address I had prepared, which the king took of me,
and intimated that he would further look at it.
I thought it right to say,
that I believed the king would not be offended at
our appearance before him with our hats on,
and that it was not out of disrespect: to which he promptly replied,
"`You know I am aware of that.`"
Under a degree of solemn feeling, I then expressed that I felt thankful to Almighty God,
that he had been pleased to renew in my mind at this time,
that earnest solicitude which at times I have experienced for the welfare of the king,
accompanied with strong desires that the Almighty would be pleased
to incline his heart so to walk in the ways of his requirings,
that he might become a blessing to the nation over whom he is permitted to reign;
beseeching the Lord, to incline the heart of the king to seek daily for help,
to be enabled to maintain the noble resolution of
one formerly,--"`Let others do as they may,
I will serve the Lord;`" and that when called upon to surrender up his earthly crown,
he might be favoured to receive a crown in the kingdom of heaven.
The king manifested serious attention,
and I acknowledged his kindness in allowing me this interview, and said,
there was still another favour I was anxious to obtain,
but I feared it would be requesting too much.
The king promptly inquired, "`What is it?`"
I then told him I was desirous to present two books to the queen,
and to have the privilege of addressing her in a few words.
The king replied,
"`I have no doubt she will readily comply with your
wishes;`" and he immediately rang the bell,
and sent a message to the queen by one of the servants.

My companion expressed a fear that we were unsuitably
trespassing on the time of the king,
to which he replied, not at all;
he then acknowledged the condescension of the king to us,
and his desire that the Divine blessing might rest
upon him during the remainder of his reign.
The messenger being returned informed us the queen would receive us in her drawing-room,
and we were conducted to the apartment; after waiting a few minutes, the queen,
quite unattended, walked into the room,
presenting a striking example of simplicity in her attire for her exalted station.
We presented her with two books, and a printed copy of the address,
which she received in an obliging manner; after a short pause,
I told her that I was one of the deputation who presented the address of the Society
of Friends to the queen on her accession to the throne,--that at that time,
and frequently since then, she had been brought to my remembrance;
and my mind had been impressed with a belief,
that a kind Providence had favoured her with a mind capable
of entering into feeling for those who were in distress,
which feelings of sympathy, I believed, she was disposed to cherish.
Under these impressions I had often regretted that she had not the opportunity
for becoming more fully acquainted with the distress of thousands,
and tens of thousands of her subjects, who were lacking sufficient food, clothing,
and fuel, principally arising from a lack of employment.

After a pause, I felt it my duty to address the queen nearly to the following effect:
I feel thankful to Almighty God,
that he has been pleased afresh to awaken in my mind earnest desires,
that the queen may be made a blessing to the nation,
by seeking to the Almighty for help to be found so filling her station, that,
when called upon by him to surrender her temporal crown,
she may be prepared to receive an eternal one.
My companion then acknowledged the kindness of the
queen in having favoured us with the interview,
and expressed his sincere desire, that God Almighty might be pleased to bless her.
At our parting, the queen took off her glove and gave us her hand;
and we were thankful the visits to the king and queen had been accomplished, without,
we trust, cause for offence to be taken by any one.
My mind being relieved from the exercise I was labouring under,
at the time of our entering the apartments, feelings of gratitude filled my heart;
and I desire to render unto Him, the Author of all good,
thanksgiving and praise for having made the way easy,
and enabling me to perform that which I believed he required at my hand.
Sewel`'s History was forwarded to the king by my companion,
who received a very handsome acknowledgment of it from Sir Herbert Taylor, stating,
the king received it most graciously.
The Book of Extracts being under revision, it is intended to send one of the new edition.
The address, which was printed, is as follows:

[.embedded-content-document.address]
--

[.letter-heading]
An Affectionate Address to the King and His Government.

[.salutation]
May it please the king,

To receive the respectful and affectionate address of one of his subjects,
whose mind has, of later times,
been deeply impressed with sincere desires for his welfare,
and that of his royal consort, and our native country,
accompanied with fervent prayer to Almighty God, that we may, as a nation,
at this awful awakening crisis, manifest an entire willingness,
through God`'s all-sufficient help, '`to break off our sins by righteousness,
and our iniquities by showing mercy to the poor,
if it may be a means of lengthening our tranquillity.`'
But if this change is happily brought about in our land,
it has long been given me to see that in the onset it must become a government work;
may I therefore be allowed to say, not only to the king,
but to all those who hold the reins of government under him,
that there must be an entire willingness manifested on your part,
through the help of Almighty God,
to remove out of the way of the people those temptations to evil, which by license,
and by your not controlling them, are sanctioned by your authority.

If this reformation goes forward, and becomes more and more an individual work,
you must be willing, O! you rulers, to stand forward,
unshackled by the fear or favour of man, and show yourselves to be on the Lord`'s side.
I am aware this is no easy task which you are loudly called upon to perform,
and that you will have much discouragement to contend with,
both from within and from without;
but then it will be the more necessary for you to endeavour to keep in view,
that the Master whom you will thus serve is '`the Lord on high,
who is mightier than the noise of many waters; yes,
than the mighty waves of the sea;`' and that if he be for you and work with you,
and you with him,
through his divine aid,--who is there that shall oppose you and prevail.

Permit me to remind you, that by merely appointing a fast for a day,
we cannot find acceptance with God, appease his displeasure,
or cause him to withhold his just judgments from us, as we have sufficiently proved;
for since that day has passed over, the threatenings have been yet more awful.
The impending calamity,^
footnote:[The cholera was then prevailing in some parts of England.]
the disease which has baffled the skill of medical aid to fathom its origin,
has from time to time made its terrific appearance in other parts of our nation,
and spread its deadly influence among the inhabitants;
allowing such who have fallen victims to it,
but very little time for that necessary preparation of soul
which we all must experience before we leave this world,
if we are favoured to live with God and Christ Jesus in a happy eternity.
Have we not then reason to fear,
that because of our national and individual transgressions,
the Spirit of the Lord is daily grieved,
and that the language of the psalmist may be applied in this our awful situation:
'`If he turn not, he will whet his sword; he has bent his bow,
and made it ready;`' and yet how have the threatenings of this awful disease,
which has so partially visited our land, been permitted, from time to time,
in degree to subside; as if we were, as a nation,
to be excused from the severe stroke--from the rod thus shaken over us,
which has fallen to the lot of other nations.
But the partial subsiding of this disease,
which has taken place in different parts of the nation,
I have been led to view as permitted in great mercy to us,
by him who remains to be the King of kings and Lord of lords.
If we will hear his voice, and receive his counsel and obey it,
it seems to proclaim in our ears, as a nation, this language--if you will now '`repent,
and do your first works,`' by '`breaking off from your sins by righteousness,
and your iniquities by showing mercy to the poor,`' the deadly portion
which your manifold sins and accumulated transgressions have merited,
shall not be meted out to the full.
But unless we are willing, through God`'s help,
to '`repent and do our first works,`' I dare do no other than say,
that I greatly fear we shall not be spared more than other nations have been.

Should the Almighty see fit, thus to chasten us as with scorpions,
and '`rebuke us in his hot displeasure,`'--should the destroying
angel be commissioned to smite our nation,
you who hold the reins of government will be no more secure in
your costly dwellings from the awful desolation it may occasion,
than the poorest cottager,--the Almighty power not being confined to place or space,
agreeably to the language of the psalmist, '`Where shall I go from your Spirit?
or where shall I flee from your presence?
If I ascend up into heaven, you are there; if I make my bed in hell,
behold you are there; if I take the wings of the morning,
and dwell in the uttermost parts of the sea, even there shall your hand lead me,
and your right hand shall hold me.
If I say, surely the darkness shall cover me, even the night shall be light about me;
yes the darkness hides not from you, but the night shines as the day,
the darkness and the light are both alike to you.`'

Therefore, while time and opportunity are afforded, let us be willing,
through God`'s all-sufficient help, to amend our ways:
for should the Lord`'s judgments be meted out to us as they have been to other nations,
which of us can assure ourselves that we shall be spared to witness
the awful desolation and thinning of the people which it may occasion?
But O! how have I been comforted at times,
when my mind has been under the pressure of these subjects,
in the belief that Divine mercy and all-sufficient
help still await our acceptance as a nation,
and as individuals; and in believing that the language of the Almighty,
through one of the prophets of old, to a highly favoured yet rebellious people,
as we have been and yet are, is still continued to us; '`How shall I give you up,
Ephraim.
How shall I deliver you, Israel?
how shall I make you as Admah?
how shall I set you as Zeboim?
Mine heart is turned within me, my repentings are kindled together.
I will not execute the fierceness of my anger; I will not return to destroy Ephraim;
for I am God, and not man; the Holy One in the midst of you:
and I will not enter into the city.`'

If we thus become the objects of Divine mercy and lovingkindness,
let me again say to you, who hold the reins of government,
in whom the power is vested to do much towards bringing about this reformation,
which the Lord calls for from us as a nation,--you must manifest an unreserved
willingness to come forward and do your part towards it,
by removing the cause of the evils which abound and are increasing
among us,--by no longer giving occasion for it to be said,
'`The leaders of the people cause them to err.`' I am persuaded that a
blessing would attend your recalling all licenses that have been issued,
which allow of theatres, opera-houses, and other places of vain amusement in the nation,
and your prohibiting all such licenses in future,
and enacting such laws as shall prevent horse-races, bull and bear-baiting,
cock-fighting, gambling-houses,
etc. if you would be thus found so far doing your part towards
removing the temptations out of the way of the people,
which are thereby held out to them to frequent such nurseries of vice.

Another enormous evil in which this nation is deeply implicated, is that of slavery.
Nobly resolve, O! you rulers, immediately to abolish this iniquity in all our dominions,
that the cries of the poor, injured, and deeply afflicted Africans,
may no longer be permitted to ascend to the ear of their God and our God,
against our guilty nation: for he will most assuredly, either in time or eternity,
punish their oppressors,
and such as are upholding them in the continuance of this oppression,
unless they timely repent of the sufferings and cruel bondage
which our highly professing nation has long sanctioned,
by allowing them to become a sacrifice to the merciless interest of their owners.

If you do not exert your authority to the utmost, to prevent or remove these evils,
you sanction them; and thus, it has long been my belief,
that in the sight of Almighty God,
you become implicated in all the evil consequences resulting from their continuance.
So consider, I entreat you, as you value the eternal wellbeing of your own souls,
and the souls of the people, the awful situation you are placing yourselves in,
and those who are ensnared by their continuance,
so long as you allow those evils in the nation which are within your province to remove.
Be willing, then, to do your part, through God`'s help, to have these things removed.

And may I earnestly entreat you, O! you rulers,
no longer to allow the temptations to exist which have produced
that unparalleled increase of the sin of drunkenness,
which has of late years taken place in our nation,
from the reducing of the duty on ardent spirits,
and which has so demoralized the minds and manners of the people, in youth, middle-life,
and old age.
Oh! the drunkenness, poverty, starvation and misery,
which this reduction of the duty on ardent spirits has entailed on our nation!
The load of national guilt that has been accumulated by this means is incalculable.

In addition to this sin of drunkenness,
there is another evil attendant upon the increased distillation of ardent spirits,
which is,
the great destruction of that valuable grain which a beneficent
Creator has in his mercy bestowed upon us for our support,
while many of the poor are suffering for lack of sufficient food.
If this alarming waste is allowed to continue,
can we look for any other consequences than that of calamitous national poverty?
Therefore be willing now, even now,
to do your part toward preventing an accumulation of our nation`'s guilt,
that you may no longer become sharers therein;
but by increasing the duty on this baneful article, may prevent the use of it,
except in cases of real necessity, and only to be dispensed by medical practitioners.

Although I have no hesitation in believing,
that the day recently set apart professedly as a day of fasting and humiliation,
was devoutly observed by many pious individuals in the nation,
yet so long as the evils I have enumerated are countenanced by our government,
whether by license, or they are allowed, to go on uncontrolled,
and pride and luxury continue to abound, I very much fear the language of the Most High,
through his prophet, will stand against us as a nation,
should the day of the Lord`'s judgment be yet more awfully revealed,
and then what will a national decree for a fast, one day of humiliation, avail,
oh consider! '`When you come to appear before me, who has required this at your hand,
to tread my courts?
Bring no more vain oblations; incense is an abomination unto me;
the new moons and sabbaths I cannot away with; it is iniquity, even the solemn meeting.
And when you spread forth your hands, I will hide my eyes from you: yes,
when you make many prayers I will not hear.
Wash yourselves, make yourselves clean, put away the evil of your doings from before my eyes;
cease to do evil; learn to do well.`' And again, '`You shall not fast as you do this day,
to make your voice to be heard on high.
Is it such a fast that I have chosen?
a day for a man to afflict his soul?
Is it to bow down his head as a bulrush, and to spread sackloth and ashes under him?
will you call this a fast and an acceptable day to the Lord?
Is not this the fast that I have chosen?
to loose the bands of wickedness, to undo the heavy burdens,
and to let the oppressed go free, and that you break every yoke?
Is it not to deal your bread to the hungry,
and that you bring the poor which are cast out to your house when you see the naked,
that you cover him; and that you hide not yourself from your own flesh?
Then shall your light break forth as the morning,
and your health shall spring forth speedily; and your righteousness shall go before you.
Then shall you call, and the Lord shall answer; you shall cry, and he shall say,
here I am.`'

Every act on our part, as a nation, short of this, I dare do no other than say,
we have abundant cause to fear, will be but offering an insult to the Majesty of Heaven,
and adding to our national guilt.
Allow me, therefore, to quote the language of the psalmist, '`Be wise, therefore,
O! you kings: be instructed you judges of the earth.
Serve the Lord with fear, and rejoice with trembling.
Kiss the Son, lest he be angry, and you perish from the way,
when his wrath is kindled but a little.
Blessed are all they that put their trust in him:`' and allow me to add,
that my soul craves, that by observing the fast recommended by the prophet,
which we are assured the Lord will accept, we may be enabled,
both in a national and individual capacity, to say, '`Blessed be God,
which has not turned away my prayer, nor his mercy from me.`'

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Tottenham, 7th of Ninth month, 1832.

--

[.the-end]
End of the Journal.

[.centered]
=== Conclusion.

Our friend Thomas Shillitoe, after his return from America,
continued to reside at Tottenham, near London, until the close of his life.
It does not appear that he left home again with certificate in the work of the ministry;
but he was remarkably diligent in attending our religious meetings,
both in his own village, and, when able, those held in London,
on behalf of the Society at large.
He was an eminent example of perseverance in attending meetings for Divine worship,
even when under much bodily suffering, as well as of punctuality to the time appointed.
One day, when much worn down by disease, on going to meeting, it was observed to him,
had he not better stay at home, as he appeared so poorly?
He replied, "`No, I believe it is required of me to go, as long as I can;
when I cannot walk, my friends must carry me.`"^
footnote:[He resided within two or three doors of the meetinghouse.]
Less than two weeks previous to his decease, he attended, under great weakness,
the concluding sitting of the Yearly Meeting of ministers and elders in 1836.

While our dear friend was diligently engaged in his Master`'s service,
in what might be considered the work of the evening,
with the sincere desire and endeavour to finish his day`'s work in the day,
his spirit was often clothed with mourning,
on account of the inroads which the enemy of all
righteousness was permitted to make within our borders,
and to overthrow the faith of some.
At this period of trial and of proving, he was often concerned,
as a faithful watchman on the walls, to sound an alarm,
to warn his friends of the near approach of the enemy,
and to encourage them to be unmoved,
and steadfast in "`the faith once delivered unto the saints.`"

On one occasion, about this time, while encouraging to faithfulness,
and signifying his intention to attend at his post of duty so long as strength remained,
he added in a solemn manner these words:
"`My Master`'s orders are--'`Watchmen, be at your posts.`'`"
Thus did he endeavour to stir up his brethren to diligence,
to strengthen the weak hands among them, and to confirm the feeble-minded,
some of whom can now arise and call him blessed;
while he did not fail to raise his warning voice against the spirit of the world,
as well as the delusions of the wicked one,
by which too many have been induced to forsake some of those Christian
testimonies and principles held among us as a Society from the beginning.
His faith was firm and unshaken, that the Lord, in his own time,
would be pleased to cause, not only the recent,
but the desolations of many generations to be repaired; and he said,
"`I believe the latter house will be greater than the former.`"

Having been favoured to experience, through the good hand of his God upon him,
that he could do all things required of him, through Christ, who strengthened him,
he was frequently engaged to press upon others the necessity for, and benefit of,
perfect obedience to the revealed will of the Most High; that thus all might become,
like Caleb and Joshua of old, of whom it is recorded,
that they had "`wholly followed the Lord.`"

The afflicted and the poor continued to share in his sympathy, and labours of love;
his exertions on behalf of the latter class, in his own village, were conspicuous,
even to within a short period of his decease.
Having raised a subscription among his wealthier friends and neighbours,
to provide more comfortable arrangements for the poor inmates in the almshouses at Tottenham,
he attended to the outlay, and sometimes personally inspected the progress of the work;
and shortly before his decease,
he had the satisfaction of visiting the houses on the eve of their completion;
when he said, the retrospect of his interest therein was very consoling to his feelings.

His partner in life, who was several years older than himself,
survived him nearly two years.
She was remarkably fitted as a companion for him,
under his peculiarly exercising services;
affording a striking instance of the overruling care of his great Lord and Master,
in best providing for those who wholly trust in him, in that important union of marriage.
Her exemplary conduct and patient acquiescence in their
frequent and sometimes long separations from each other,
were very instructive.^
footnote:[A few weeks previous to her departure, which took place at Hitchin,
at the advanced age of ninety-two, she said, with much earnestness,
"`O! that I may be prepared, when my time comes.`"
Her last illness was a very short and suffering one;
towards the end of which it was evident, from her tone of voice,
that prayer and praises were the closing engagement of her soul.]

On one occasion, a few months before his departure,
at a time when our faithful ministers were exposed to much gainsaying,
and "`perverse things`" were spoken unjustly against them,
he expressed himself with much tenderness of spirit, to a friend who had called upon him,
in the following terms; at the same time adding, that such had been his sentiments,
during the whole course of his religious life.--"`I
feel that I have nothing to depend upon,
but the mercies of God in Christ Jesus.
I do not rely for salvation upon any merits of my own;
all my own works are as filthy rags:--my faith is in the merits of Christ Jesus,
and in the offering he made for us.
I trust my past sins are all forgiven me,--that they
have been washed away by the blood of Christ,
who died for my sins.
It is mercy I need, and mercy I have; and notwithstanding I thus speak,
I am sensible that I must not presume upon this mercy; but it is only as I endeavour,
through Divine-assistance, to walk circumspectly, that I can hold out to the end.`"

He was taken more alarmingly ill on the 5th of the sixth month, 1836;
and his sufferings from bodily debility became very great.
He supplicated that his faculties might remain clear to the very last,
and that he might praise his Maker with his last breath.
"`I desire,`" he added, "`with truth and sincerity of heart,
to say,--'`Your will be done.`' O! that I could get
within the pearl gates--just within the pearl gates.`"

Early in the morning of the next day he became much worse from debility,
and his breathing being difficult, he said, "`It is labour, but not sorrow.
Oh! deliver me, if consistent with your blessed will.
I am in the hands of a merciful God:--take me; I can give up all in this world.
Oh! come, come, blessed Jesus! if it is consistent with your blessed will.
Into your careful keeping--into your merciful hands--I commit my dear children,
and my dear grandchildren,--all-merciful!`"

After sleeping comfortably the following night, he said,
"`Oh! be pleased to preserve me in patience,--waiting, waiting.
Oh!
Divine mercy, send, O send, if consistent with your holy will, send my release.
Oh! take me in your arms, and carry me--bear me hence.
I feel getting weaker and weaker;--the thread will presently untwist.`"

"`Oh! heavenly Father, be pleased, if consistent with your blessed will,
to say--'`This is enough.`' Send, send, oh! merciful Father, help,
that I may not let go my confidence.
Oh! assist me in your prayers, that I may be released from the shackles of mortality.
Oh, take me, holy Jesus, I pray you, to yourself.
Oh! have mercy! have mercy.`"

He afterwards said, "`My love is to every body--the wicked and all; I love them,
but not their ways.
Oh! for patience, for patience,--no murmuring,--no complaining--but cheerful submission.
Oh!
Lord Jesus! have mercy on me.
Son of David! have mercy on me.
I truly know sorrow, as to the body, but not as to the mind.
My head aches, but not my heart.
What am I better than other men?
But now I shall have to appear, to answer for my precious time;
what have I done that I should not have done, and left undone that I should have done?`"

To his medical attendant he said: "`Does there seem any probability of a speedy release?
I will take any thing in moderation, that will not affect my intellect.
I want to go out of the world with a clear head, and a clean heart.
Oh! bear with me, if I am impatient; the restlessness of the body, but not of the mind,
you can have no conception of.
Perfect obedience to our heavenly Father,
as made known in the secret of the heart,--this is the faith contended for.`"

Third-day, addressing his wife, he said: "`I should like us to lie down together,
and be buried in the same grave.
Oh! let it be known,
that I contend to the last with unremitting confidence and assurance for the
second coming of our Lord and Saviour Jesus Christ to the saving of the soul.
Oh! what should I have been now, if I had not submitted to his baptism,
to the baptism of fire!`"
To Dr. H. he said, "`Am I not weakening fast?`"
Dr. H. replied, "`I fear you are.`"
He replied, "`Oh! do not fear, but rejoice, rejoice, on my account.
Oh, pray for me, with me, that my faith fail not.
Oh! good Lord Jesus! cast a crumb of help, and deliver me.
I earnestly pray you to come; come quickly, if I dare lay claim to be your servant.`"

On inquiring the day of the week, and being told it was fifth-day,
half-past ten o`'clock, he said, "`Friends are at meeting;
I hope they will be benefitted by being there.`"

About ten o`'clock at night, he said, "`I have been helped through many a trying night.`"
And again, about three o`'clock in the morning, after having had some sleep,
"`I have passed a better night than I could have expected,
but it has been through my dear Redeemer sustaining me.
I hope I am kept from murmuring: I desire cheerful submission, for I cannot help myself,
nor can any man help me.
Oh! the balm--the oil poured into my wounds for my shortcomings.--I desire to submit,
and say, '`your blessed will be done.`'`"

On being taken worse, he said, "`Oh! surely this is death; I thank you for it.`"

Seventh-day morning, on inquiring the day of the week,
and being told the morrow would be first-day, he said,
"`The whole day to be devoted to the service of God.
I will try to sing for mercy.
My eyes have seen your salvation, and your glory;
when shall I feel your presence?--My friends must
not think more highly of me than they ought to think;
if I have been any thing, it has been of grace, not of merit.`"
He many times requested that patience might be granted him,
and desired a Friend who visited him, to be valiant in the earth.

On receiving a message of love from a friend, he again said,
his "`love was to every body, all the world over, even the worst sinner, he loved them,
but not their deeds;--that his love was universal, to all the human race;`" and added,
"`if it were not so, how miserable indeed should I feel.
Oh! holy, blessed Jesus,`" he exclaimed, "`be with me in this awful moment.
Come! oh! come, and receive me to yourself; and, of your own free mercy,
in your own time, admit me into your heavenly kingdom!`"

It is believed his supplication, that his faculties might remain clear to the last,
was mercifully granted; though he was not able to articulate for the last two hours.
About two o`'clock on first-day morning, he was moved into a more comfortable position,
after which he became faint, and from that time gradually sank away;
so that those about him could only discover by close watching, when he ceased to breathe.

He died on the 12th day of the sixth month, 1836, aged about eighty-two years;
and his remains were interred in Friends`' burying
ground at Tottenham on the 17th of the same,
after a very solemn meeting.

"`Blessed are the dead, which die in the Lord;--yes, says the Spirit,
that they may rest from their labours; and their works do follow them.`"
