== Chapter XLI.

In the year 1830, apprehending I was called upon by my Divine Master,
to bring more generally into view some parts of the Address to our own religious Society,
which I believed it required of me to issue a few years back,
a care was on my mind to see the right time to engage in it;
and believing this time was fully come, I earnestly besought the Lord for help,
to select such parts and make such additions as would be in accordance with his will.
Having, as I apprehended, been enabled to do the needful in this respect,
and put it into the hands of a Friend for revision,
in the year 1831 it was printed for circulation.

New South Wales is of late the subject of my daily thoughts,
and a report being in circulation, that I had given up this prospect of religious duty,
I felt my mind brought under the necessity, in the Select Yearly Meeting,
to inform my friends that this concern still remained with me:
although of late there have been seasons in which I have been disposed to query,
whether "`a ram`" would not be caught.
I earnestly craved, if such should be the will of my Divine Master,
that I might be preserved patiently waiting to know his mmd and will,
and that he would prepare the offering,
even the whole burnt sacrifice he is calling for,--offered up in his own time and way.

Having for some months past felt drawings in my mind
to make a visit to the bishop of London,
on the 12th of fifth month, this year, agreeably to a previous appointment,
accompanied by my kind friend Peter Bedford, we waited on him at his residence,
and he received us kindly.
After a short pause, I felt myself constrained to inform the bishop,
that I had been an acknowledged minister in the Society
of Friends upwards of fifty years,
which I found had placed me in an awful and responsible situation;
inasmuch as I was aware my example was looked at by the body.
This led me frequently to consider how far the general tenour
of my conduct and converse corresponded with the doctrines,
precepts, and example of our holy Redeemer,
and how far I was earnestly concerned by example and precept,
to use my utmost influence in checking any wrong practices
that were in danger of creeping or had crept into the Society;
from an assurance that by neglect on my part,
I should be criminating myself in the sight of my Maker, by becoming a party thereto.

I then informed him, there was another subject I must lay before him, which was,
the great increase of intemperance;--fearful as I was,
unless some steps were taken to arrest its progress,
it would arrive at a similar height to that which it attained in
this country about a century back--having heard from my father
a deplorable description of the extent it then reached.
I presented him with a small volume of the tracts published by the Temperance Society,
which he received with pleasure.

I then urged him to promote the objects of the Temperance Society,
assuring him the exertions already used had been a great blessing;
on which it appeared he saw some difficulty in acting in this way,
intimating that some fiscal regulations on the part of government
would be necessary in order to suppress it:
to which I said, in the warmth of my feelings, "`But, my dear friend,
do seek for best help, to enable you to do what you can.`"

Books on our religious principles were then handed to him,
which he appeared to receive acceptably.
During the whole of the interview, he heard us with much courtesy,
and in a friendly and kind manner observed it was
desirable to have the good wishes of all Christians,
and that he was glad in receiving the visit; he shook hands with us,
and escorted us to the door, and soon after became president to the Temperance Society,
and a warm promoter of its interests.

On fifth-day, 27th of ninth month, 1832, I left town, accompanied by three Friends,
for Windsor,--arrangements having been made for me to have an interview with the king,
in order to present him with an address on some subjects
which had deeply occupied my thoughts,
the presentation of which appeared to be a duty.
We reached Windsor by ten o`'clock, and were conducted to the castle;
after some time we were introduced into the apartment of the king,
who was standing to receive us.
We were with him about twenty minutes; he was unattended,
and it may be said received us very graciously.
He entered into familiar conversation,
and held out his hand to receive the books we took with us, which my companion gave him;
after which I handed the address I had prepared, which the king took of me,
and intimated that he would further look at it.
I thought it right to say,
that I believed the king would not be offended at
our appearance before him with our hats on,
and that it was not out of disrespect: to which he promptly replied,
"`You know I am aware of that.`"
Under a degree of solemn feeling, I then expressed that I felt thankful to Almighty God,
that he had been pleased to renew in my mind at this time,
that earnest solicitude which at times I have experienced for the welfare of the king,
accompanied with strong desires that the Almighty would be pleased
to incline his heart so to walk in the ways of his requirings,
that he might become a blessing to the nation over whom he is permitted to reign;
beseeching the Lord, to incline the heart of the king to seek daily for help,
to be enabled to maintain the noble resolution of
one formerly,--"`Let others do as they may,
I will serve the Lord;`" and that when called upon to surrender up his earthly crown,
he might be favoured to receive a crown in the kingdom of heaven.
The king manifested serious attention,
and I acknowledged his kindness in allowing me this interview, and said,
there was still another favour I was anxious to obtain,
but I feared it would be requesting too much.
The king promptly inquired, "`What is it?`"
I then told him I was desirous to present two books to the queen,
and to have the privilege of addressing her in a few words.
The king replied,
"`I have no doubt she will readily comply with your
wishes;`" and he immediately rang the bell,
and sent a message to the queen by one of the servants.

My companion expressed a fear that we were unsuitably
trespassing on the time of the king,
to which he replied, not at all;
he then acknowledged the condescension of the king to us,
and his desire that the Divine blessing might rest
upon him during the remainder of his reign.
The messenger being returned informed us the queen would receive us in her drawing-room,
and we were conducted to the apartment; after waiting a few minutes, the queen,
quite unattended, walked into the room,
presenting a striking example of simplicity in her attire for her exalted station.
We presented her with two books, and a printed copy of the address,
which she received in an obliging manner; after a short pause,
I told her that I was one of the deputation who presented the address of the Society
of Friends to the queen on her accession to the throne,--that at that time,
and frequently since then, she had been brought to my remembrance;
and my mind had been impressed with a belief,
that a kind Providence had favoured her with a mind capable
of entering into feeling for those who were in distress,
which feelings of sympathy, I believed, she was disposed to cherish.
Under these impressions I had often regretted that she had not the opportunity
for becoming more fully acquainted with the distress of thousands,
and tens of thousands of her subjects, who were lacking sufficient food, clothing,
and fuel, principally arising from a lack of employment.

After a pause, I felt it my duty to address the queen nearly to the following effect:
I feel thankful to Almighty God,
that he has been pleased afresh to awaken in my mind earnest desires,
that the queen may be made a blessing to the nation,
by seeking to the Almighty for help to be found so filling her station, that,
when called upon by him to surrender her temporal crown,
she may be prepared to receive an eternal one.
My companion then acknowledged the kindness of the
queen in having favoured us with the interview,
and expressed his sincere desire, that God Almighty might be pleased to bless her.
At our parting, the queen took off her glove and gave us her hand;
and we were thankful the visits to the king and queen had been accomplished, without,
we trust, cause for offence to be taken by any one.
My mind being relieved from the exercise I was labouring under,
at the time of our entering the apartments, feelings of gratitude filled my heart;
and I desire to render unto Him, the Author of all good,
thanksgiving and praise for having made the way easy,
and enabling me to perform that which I believed he required at my hand.
Sewel`'s History was forwarded to the king by my companion,
who received a very handsome acknowledgment of it from Sir Herbert Taylor, stating,
the king received it most graciously.
The Book of Extracts being under revision, it is intended to send one of the new edition.
The address, which was printed, is as follows:

An Affectionate Address to the King and His Government.

May it please the king,

To receive the respectful and affectionate address of one of his subjects,
whose mind has, of later times,
been deeply impressed with sincere desires for his welfare,
and that of his royal consort, and our native country,
accompanied with fervent prayer to Almighty God, that we may, as a nation,
at this awful awakening crisis, manifest an entire willingness,
through God`'s all-sufficient help, '`to break off our sins by righteousness,
and our iniquities by showing mercy to the poor,
if it may be a means of lengthening our tranquillity.`'
But if this change is happily brought about in our land,
it has long been given me to see that in the onset it must become a government work;
may I therefore be allowed to say, not only to the king,
but to all those who hold the reins of government under him,
that there must be an entire willingness manifested on your part,
through the help of Almighty God,
to remove out of the way of the people those temptations to evil, which by license,
and by your not controlling them, are sanctioned by your authority.

If this reformation goes forward, and becomes more and more an individual work,
you must be willing, O! you rulers, to stand forward,
unshackled by the fear or favour of man, and show yourselves to be on the Lord`'s side.
I am aware this is no easy task which you are loudly called upon to perform,
and that you will have much discouragement to contend with,
both from within and from without;
but then it will be the more necessary for you to endeavour to keep in view,
that the Master whom you will thus serve is '`the Lord on high,
who is mightier than the noise of many waters; yes,
than the mighty waves of the sea;`' and that if he be for you and work with you,
and you with him,
through his divine aid,--who is there that shall oppose you and prevail.

Permit me to remind you, that by merely appointing a fast for a day,
we cannot find acceptance with God, appease his displeasure,
or cause him to withhold his just judgments from us, as we have sufficiently proved;
for since that day has passed over, the threatenings have been yet more awful.
The impending calamity,^
footnote:[The cholera was then prevailing in some parts of England.]
the disease which has baffled the skill of medical aid to fathom its origin,
has from time to time made its terrific appearance in other parts of our nation,
and spread its deadly influence among the inhabitants;
allowing such who have fallen victims to it,
but very little time for that necessary preparation of soul
which we all must experience before we leave this world,
if we are favoured to live with God and Christ Jesus in a happy eternity.
Have we not then reason to fear,
that because of our national and individual transgressions,
the Spirit of the Lord is daily grieved,
and that the language of the psalmist may be applied in this our awful situation:
'`If he turn not, he will whet his sword; he has bent his bow,
and made it ready;`' and yet how have the threatenings of this awful disease,
which has so partially visited our land, been permitted, from time to time,
in degree to subside; as if we were, as a nation,
to be excused from the severe stroke--from the rod thus shaken over us,
which has fallen to the lot of other nations.
But the partial subsiding of this disease,
which has taken place in different parts of the nation,
I have been led to view as permitted in great mercy to us,
by him who remains to be the King of kings and Lord of lords.
If we will hear his voice, and receive his counsel and obey it,
it seems to proclaim in our ears, as a nation, this language--if you will now '`repent,
and do your first works,`' by '`breaking off from your sins by righteousness,
and your iniquities by showing mercy to the poor,`' the deadly portion
which your manifold sins and accumulated transgressions have merited,
shall not be meted out to the full.
But unless we are willing, through God`'s help,
to '`repent and do our first works,`' I dare do no other than say,
that I greatly fear we shall not be spared more than other nations have been.

Should the Almighty see fit, thus to chasten us as with scorpions,
and '`rebuke us in his hot displeasure,`'--should the destroying
angel be commissioned to smite our nation,
you who hold the reins of government will be no more secure in
your costly dwellings from the awful desolation it may occasion,
than the poorest cottager,--the Almighty power not being confined to place or space,
agreeably to the language of the psalmist, '`Where shall I go from your Spirit?
or where shall I flee from your presence?
If I ascend up into heaven, you are there; if I make my bed in hell,
behold you are there; if I take the wings of the morning,
and dwell in the uttermost parts of the sea, even there shall your hand lead me,
and your right hand shall hold me.
If I say, surely the darkness shall cover me, even the night shall be light about me;
yes the darkness hides not from you, but the night shines as the day,
the darkness and the light are both alike to you.`'

Therefore, while time and opportunity are afforded, let us be willing,
through God`'s all-sufficient help, to amend our ways:
for should the Lord`'s judgments be meted out to us as they have been to other nations,
which of us can assure ourselves that we shall be spared to witness
the awful desolation and thinning of the people which it may occasion?
But O! how have I been comforted at times,
when my mind has been under the pressure of these subjects,
in the belief that Divine mercy and all-sufficient
help still await our acceptance as a nation,
and as individuals; and in believing that the language of the Almighty,
through one of the prophets of old, to a highly favoured yet rebellious people,
as we have been and yet are, is still continued to us; '`How shall I give you up,
Ephraim.
How shall I deliver you, Israel?
how shall I make you as Admah?
how shall I set you as Zeboim?
Mine heart is turned within me, my repentings are kindled together.
I will not execute the fierceness of mine anger; I will not return to destroy Ephraim;
for I am God, and not man; the Holy One in the midst of you:
and I will not enter into the city.`'

If we thus become the objects of Divine mercy and lovingkindness,
let me again say to you, who hold the reins of government,
in whom the power is vested to do much towards bringing about this reformation,
which the Lord calls for from us as a nation,--you must manifest an unreserved
willingness to come forward and do your part towards it,
by removing the cause of the evils which abound and are increasing
among us,--by no longer giving occasion for it to be said,
'`The leaders of the people cause them to err.`' I am persuaded that a
blessing would attend your recalling all licenses that have been issued,
which allow of theatres, opera-houses, and other places of vain amusement in the nation,
and your prohibiting all such licenses in future,
and enacting such laws as shall prevent horse-races, bull and bear-baiting,
cock-fighting, gambling-houses,
etc. if you would be thus found so far doing your part towards
removing the temptations out of the way of the people,
which are thereby held out to them to frequent such nurseries of vice.

Another enormous evil in which this nation is deeply implicated, is that of slavery.
Nobly resolve, O! you rulers, immediately to abolish this iniquity in all our dominions,
that the cries of the poor, injured, and deeply afflicted Africans,
may no longer be permitted to ascend to the ear of their God and our God,
against our guilty nation: for he will most assuredly, either in time or eternity,
punish their oppressors,
and such as are upholding them in the continuance of this oppression,
unless they timely repent of the sufferings and cruel bondage
which our highly professing nation has long sanctioned,
by allowing them to become a sacrifice to the merciless interest of their owners.

If you do not exert your authority to the utmost, to prevent or remove these evils,
you sanction them; and thus, it has long been my belief,
that in the sight of Almighty God,
you become implicated in all the evil consequences resulting from their continuance.
So consider, I entreat you, as you value the eternal wellbeing of your own souls,
and the souls of the people, the awful situation you are placing yourselves in,
and those who are ensnared by their continuance,
so long as you allow those evils in the nation which are within your province to remove.
Be willing, then, to do your part, through God`'s help, to have these things removed.

And may I earnestly entreat you, O! you rulers,
no longer to allow the temptations to exist which have produced
that unparalleled increase of the sin of drunkenness,
which has of late years taken place in our nation,
from the reducing of the duty on ardent spirits,
and which has so demoralized the minds and manners of the people, in youth, middle-life,
and old age.
Oh! the drunkenness, poverty, starvation and misery,
which this reduction of the duty on ardent spirits has entailed on our nation!
The load of national guilt that has been accumulated by this means is incalculable.

In addition to this sin of drunkenness,
there is another evil attendant upon the increased distillation of ardent spirits,
which is,
the great destruction of that valuable grain which a beneficent
Creator has in his mercy bestowed upon us for our support,
while many of the poor are suffering for lack of sufficient food.
If this alarming waste is allowed to continue,
can we look for any other consequences than that of calamitous national poverty?
Therefore be willing now, even now,
to do your part toward preventing an accumulation of our nation`'s guilt,
that you may no longer become sharers therein;
but by increasing the duty on this baneful article, may prevent the use of it,
except in cases of real necessity, and only to be dispensed by medical practitioners.

Although I have no hesitation in believing,
that the day recently set apart professedly as a day of fasting and humiliation,
was devoutly observed by many pious individuals in the nation,
yet so long as the evils I have enumerated are countenanced by our government,
whether by license, or they are allowed, to go on uncontrolled,
and pride and luxury continue to abound, I very much fear the language of the Most High,
through his prophet, will stand against us as a nation,
should the day of the Lord`'s judgment be yet more awfully revealed,
and then what will a national decree for a fast, one day of humiliation, avail,
oh consider! '`When you come to appear before me, who has required this at your hand,
to tread my courts?
Bring no more vain oblations; incense is an abomination unto me;
the new moons and sabbaths I cannot away with; it is iniquity, even the solemn meeting.
And when you spread forth your hands, I will hide mine eyes from you: yes,
when you make many prayers I will not hear.
Wash you, make you clean, put away the evil of your doings from before mine eyes;
cease to do evil; learn to do well.`' And again, '`You shall not fast as you do this day,
to make your voice to be heard on high.
Is it such a fast that I have chosen?
a day for a man to afflict his soul?
Is it to bow down his head as a bulrush, and to spread sackloth and ashes under him?
will you call this a fast and an acceptable day to the Lord?
Is not this the fast that I have chosen?
to loose the bands of wickedness, to undo the heavy burdens,
and to let the oppressed go free, and that you break every yoke?
Is it not to deal your bread to the hungry,
and that you bring the poor which are cast out to your house when you see the naked,
that you cover him; and that you hide not yourself from your own flesh?
Then shall your light break forth as the morning,
and your health shall spring forth speedily; and your righteousness shall go before you.
Then shall you call, and the Lord shall answer; you shall cry, and he shall say,
here I am.`'

Every act on our part, as a nation, short of this, I dare do no other than say,
we have abundant cause to fear, will be but offering an insult to the Majesty of Heaven,
and adding to our national guilt.
Allow me, therefore, to quote the language of the psalmist, '`Be wise, therefore,
O! you kings: be instructed you judges of the earth.
Serve the Lord with fear, and rejoice with trembling.
Kiss the Son, lest he be angry, and you perish from the way,
when his wrath is kindled but a little.
Blessed are all they that put their trust in him:`' and allow me to add,
that my soul craves, that by observing the fast recommended by the prophet,
which we are assured the Lord will accept, we may be enabled,
both in a national and individual capacity, to say, '`Blessed be God,
which has not turned away my prayer, nor his mercy from me.`'

Thomas Shillitoe.

Tottenham, 7th of Ninth month, 1832.

End of the Journal.

=== Conclusion.

Our friend Thomas Shillitoe, after his return from America,
continued to reside at Tottenham, near London, until the close of his life.
It does not appear that he left home again with certificate in the work of the ministry;
but he was remarkably diligent in attending our religious meetings,
both in his own village, and, when able, those held in London,
on behalf of the Society at large.
He was an eminent example of perseverance in attending meetings for Divine worship,
even when under much bodily suffering, as well as of punctuality to the time appointed.
One day, when much worn down by disease, on going to meeting, it was observed to him,
had he not better stay at home, as he appeared so poorly?
He replied, "`No, I believe it is required of me to go, as long as I can;
when I cannot walk, my friends must carry me.`"^
footnote:[He resided within two or three doors of the meeting-house.]
Less than two weeks previous to his decease, he attended, under great weakness,
the concluding sitting of the Yearly Meeting of ministers and elders in 1836.

While our dear friend was diligently engaged in his Master`'s service,
in what might be considered the work of the evening,
with the sincere desire and endeavour to finish his day`'s work in the day,
his spirit was often clothed with mourning,
on account of the inroads which the enemy of all
righteousness was permitted to make within our borders,
and to overthrow the faith of some.
At this period of trial and of proving, he was often concerned,
as a faithful watchman on the walls, to sound an alarm,
to warn his friends of the near approach of the enemy,
and to encourage them to be unmoved,
and steadfast in "`the faith once delivered unto the saints.`"

On one occasion, about this time, while encouraging to faithfulness,
and signifying his intention to attend at his post of duty so long as strength remained,
he added in a solemn manner these words: "`My Master`'s orders are--`'Watchmen,
be at your posts.`"
'`Thus did he endeavour to stir up his brethren to diligence,
to strengthen the weak hands among them, and to confirm the feeble-minded,
some of whom can now arise and call him blessed;
while he did not fail to raise his warning voice against the spirit of the world,
as well as the delusions of the wicked one,
by which too many have been induced to forsake some of those Christian
testimonies and principles held among us as a Society from the beginning.
His faith was firm and unshaken, that the Lord, in his own time,
would be pleased to cause, not only the recent,
but the desolations of many generations to be repaired; and he said,
"`I believe the latter house will be greater than the former.`"

Having been favoured to experience, through the good hand of his God upon him,
that he could do all things required of him, through Christ, who strengthened him,
he was frequently engaged to press upon others the necessity for, and benefit of,
perfect obedience to the revealed will of the Most High; that thus all might become,
like Caleb and Joshua of old, of whom it is recorded,
that they had "`wholly followed the Lord.`"

The afflicted and the poor continued to share in his sympathy, and labours of love;
his exertions on behalf of the latter class, in his own village, were conspicuous,
even to within a short period of his decease.
Having raised a subscription among his wealthier friends and neighbours,
to provide more comfortable arrangements for the poor inmates in the almshouses at Tottenham,
he attended to the outlay, and sometimes personally inspected the progress of the work;
and shortly before his decease,
he had the satisfaction of visiting the houses on the eve of their completion;
when he said, the retrospect of his interest therein was very consoling to his feelings.

His partner in life, who was several years older than himself,
survived him nearly two years.
She was remarkably fitted as a companion for him,
under his peculiarly exercising services;
affording a striking instance of the overruling care of his great Lord and Master,
in best providing for those who wholly trust in him, in that important union of marriage.
Her exemplary conduct and patient acquiescence in their
frequent and sometimes long separations from each other,
were very instructive.^
footnote:[A few weeks previous to her departure, which took place at Hitchin,
at the advanced age of ninety-two, she said, with much earnestness,
"`O! that I may be prepared, when my time comes.`"
Her last illness was a very short and suffering one;
towards the end of which it was evident, from her tone of voice,
that prayer and praises were the closing engagement of her soul.]

On one occasion, a few months before his departure,
at a time when our faithful ministers were exposed to much gainsaying,
and "`perverse things`" were spoken unjustly against them,
he expressed himself with much tenderness of spirit, to a friend who had called upon him,
in the following terms; at the same time adding, that such had been his sentiments,
during the whole course of his religious life.--"`I
feel that I have nothing to depend upon,
but the mercies of God in Christ Jesus.
I do not rely for salvation upon any merits of my own;
all my own works are as filthy rags:--my faith is in the merits of Christ Jesus,
and in the offering he made for us.
I trust my past sins are all forgiven me,--that they
have been washed away by the blood of Christ,
who died for my sins.
It is mercy I need, and mercy I have; and notwithstanding I thus speak,
I am sensible that I must not presume upon this mercy; but it is only as I endeavour,
through Divine-assistance, to walk circumspectly, that I can hold out to the end.`"

He was taken more alarmingly ill on the 5th of the sixth month, 1836;
and his sufferings from bodily debility became very great.
He supplicated that his faculties might remain clear to the very last,
and that he might praise his Maker with his last breath.
"`I desire,`" he added, "`with truth and sincerity of heart,
to say,--'`Your will be done.`' O! that I could get
within the pearl gates--just within the pearl gates.`"

Early in the morning of the next day he became much worse from debility,
and his breathing being difficult, he said, "`It is labour, but not sorrow.
Oh! deliver me, if consistent with your blessed will.
I am in the hands of a merciful God:--take me; I can give up all in this world.
Oh! come, come, blessed Jesus! if it is consistent with your blessed will.
Into your careful keeping--into your merciful hands--I commit my dear children,
and my dear grandchildren,--all-merciful!`"

After sleeping comfortably the following night, he said,
"`Oh! be pleased to preserve me in patience,--waiting, waiting.
Oh!
Divine mercy, send, O send, if consistent with your holy will, send my release.
Oh! take me in your arms, and carry me--bear me hence.
I feel getting weaker and weaker;--the thread will presently untwist.`"

"`Oh! heavenly Father, be pleased, if consistent with your blessed will,
to say--'`This is enough.`' Send, send, oh! merciful Father, help,
that I may not let go my confidence.
Oh! assist me in your prayers, that I may be released from the shackles of mortality.
Oh, take me, holy Jesus, I pray you, to yourself.
Oh! have mercy! have mercy.`"

He afterwards said, "`My love is to every body--the wicked and all; I love them,
but not their ways.
Oh! for patience, for patience,--no murmuring,--no complaining--but cheerful submission.
Oh!
Lord Jesus! have mercy on me.
Son of David! have mercy on me.
I truly know sorrow, as to the body, but not as to the mind.
My head aches, but not my heart.
What am I better than other men?
But now I shall have to appear, to answer for my precious time;
what have I done that I should not have done, and left undone that I should have done?`"

To his medical attendant he said: "`Does there seem any probability of a speedy release?
I will take any thing in moderation, that will not affect my intellect.
I want to go out of the world with a clear head, and a clean heart.
Oh! bear with me, if I am impatient; the restlessness of the body, but not of the mind,
you can have no conception of.
Perfect obedience to our heavenly Father,
as made known in the secret of the heart,--this is the faith contended for.`"

Third-day, addressing his wife, he said: "`I should like us to lie down together,
and be buried in the same grave.
Oh! let it be known,
that I contend to the last with unremitting confidence and assurance for the
second coming of our Lord and Saviour Jesus Christ to the saving of the soul.
Oh! what should I have been now, if I had not submitted to his baptism,
to the baptism of fire!`"
To Dr. H. he said, "`Am I not weakening fast?`"
Dr. H. replied, "`I fear you are.`"
He replied, "`Oh! do not fear, but rejoice, rejoice, on my account.
Oh, pray for me, with me, that my faith fail not.
Oh! good Lord Jesus! cast a crumb of help, and deliver me.
I earnestly pray you to come; come quickly, if I dare lay claim to be your servant.`"

On inquiring the day of the week, and being told it was fifth-day,
half-past ten o`'clock, he said, "`Friends are at meeting;
I hope they will be benefitted by being there.`"

About ten o`'clock at night, he said, "`I have been helped through many a trying night.`"
And again, about three o`'clock in the morning, after having had some sleep,
"`I have passed a better night than I could have expected,
but it has been through my dear Redeemer sustaining me.
I hope I am kept from murmuring: I desire cheerful submission, for I cannot help myself,
nor can any man help me.
Oh! the balm--the oil poured into my wounds for my short-comings.--I desire to submit,
and say, '`your blessed will be done.`'`"

On being taken worse, he said, "`Oh! surely this is death; I thank you for it.`"

Seventh-day morning, on inquiring the day of the week,
and being told the morrow would be first-day, he said,
"`The whole day to be devoted to the service of God.
I will try to sing for mercy.
Mine eyes have seen your salvation, and your glory;
when shall I feel your presence?--My friends must
not think more highly of me than they ought to think;
if I have been any thing, it has been of grace, not of merit.`"
He many times requested that patience might be granted him,
and desired a Friend who visited him, to be valiant in the earth.

On receiving a message of love from a friend, he again said,
his "`love was to every body, all the world over, even the worst sinner, he loved them,
but not their deeds;--that his love was universal, to all the human race;`" and added,
"`if it were not so, how miserable indeed should I feel.
Oh! holy, blessed Jesus,`" he exclaimed, "`be with me in this awful moment.
Come! oh! come, and receive me to yourself; and, of your own free mercy,
in your own time, admit me into your heavenly kingdom!`"

It is believed his supplication, that his faculties might remain clear to the last,
was mercifully granted; though he was not able to articulate for the last two hours.
About two o`'clock on first-day morning, he was moved into a more comfortable position,
after which he became faint, and from that time gradually sank away;
so that those about him could only discover by close watching, when he ceased to breathe.

He died on the 12th day of the sixth month, 1836, aged about eighty-two years;
and his remains were interred in Friends`' burying
ground at Tottenham on the 17th of the same,
after a very solemn meeting.

"`Blessed are the dead, which die in the Lord;--yes, says the Spirit,
that they may rest from their labours; and their works do follow them.`"

=== Appendix A. Thomas Shillitoe`'s Testimony Against the Writings of Joseph John Gurney

As has been sadly portrayed by the events narrated in this journal,
the massive disruption brought about by Elias Hicks and
his followers among the Society of Friends in America,
terminated in the first great schism that Quakers
had experienced since the commencement of their society.
Hicks spoke much of an "`inner light,`" and alleged his
teachings to be in agreement with early Quaker principles,
but they were in fact very much at odds with the long-established
beliefs of the Society (and Christianity in general),
and were rejected and disavowed by the prudent and faithful.
His eloquent sermons exalted a sort of spiritual religion,
speaking much of love for neighbors, abolition of slavery,
and other right-sounding concepts,
but he led his followers into a disregard for the Scriptures,
and a total denial of several fundamentals of Christianity--such as the incarnation,
virgin birth, and divinity of Christ, His role as mediator, the atonement by the cross,
the existence of Satan, etc.
He taught that Jesus Christ was nothing more than a good man who,
having followed the light of God, was endowed with a divine Spirit and power,
often saying things like,
"`The same power that made Christ a Christian must make us Christians;
and the same power that saved him must save us.`"

Perhaps in an attempt to distance themselves from these errors,
and to avoid the false light preached by Hicksites,
Quakers in England soon began to pull away from some of
the original principles and practices of early Friends,
especially those having to do with an entire dependence
upon the immediate influence of God`'s Spirit for true worship,
ministry, and spiritual understanding.
Greatly influenced by the preaching and writings of Joseph John Gurney (in the
1820`'s-1840`'s) many who had not been seduced by Hicksism began to conform more
and more to a traditional and formal Protestant Christianity that did not rightly
understand or emphasize the revelation and formation of Christ within,
or the spiritual nature of New Covenant worship and ministry.
Over the next several decades,
these "`Gurneyites`" progressively departed from many of the precious truths that God
had restored to His church at the bright commencement of the Society of Friends,
and sadly, by the end of the 1800`'s,
the remainder of the Society of Friends was but a small and degenerate body,
the religion of the two largest camps (Hicksites and Gurneyites) bearing little resemblance
to the blessed Truth as professed and upheld by their worthy predecessors.

Not many days before his death, Thomas Shillitoe had been able,
in great debility of body,
to attend only a small portion of the Yearly Meeting in London; perhaps the last sitting,
and one sitting of the Select Meeting.
And three days before his decease, his neighbor John Hodgkin coming into his room,
he requested him to take down in writing the following testimony of his dying sentiments,
in regard to what he considered to be "`the Episcopalian tenets`" of Joseph John Gurney.

Addressing John Hodgkin, he said:

"`You will need a great deal of time and patience to hear what I have got to say,
and it must be faithfully delivered, for I am afraid, at a future day,
it will devolve heavy upon your shoulders.
It is extraordinary that you should have come in at this juncture,
for I have been wanting my son-in-law to come in,
and put down what I am now better satisfied should be received by you from my mouth.

And I therefore declare, unequivocally,
against the generality of the writings of Joseph John Gurney,
as being non-Quaker principles, not sound Quaker principles, but Episcopalian ones;
and they have done great mischief in our Society; and the Society will go gradually down,
if it yields to the further circulation of that part of
his works which they have in their power to suppress.
This is my firm belief.
I have labored under the weight of it for the last twelve months,
beyond what human nature is able to support.
And the committee of the Morning Meeting which passed that
last work +++[+++Gurney`'s '`Peculiarities`' with a new title],
must be willing to come forward, to be sufficiently humble to acknowledge their error.
And the Meeting for Sufferings must also be willing to remove its authority
in allowing it to be given away to those not of our Society.

I declare the author is an Episcopalian, not a Quaker.
I apprehend J. J. Gurney is no Quaker in principle.
Episcopalian views were imbibed from his education, and still remain with him.
I love the man, for the work`'s sake, so far as it goes;
but he has never been emptied from vessel to vessel, and from sieve to sieve,
nor known the baptism of the Holy Spirit and of fire,
to cleanse the floor of his heart from his Episcopalian notions.
He has spread a linsey woolsey garment over our members;
but in a future day it will be stripped off; it will be too short for them,
as they will be without Jesus Christ the Lord.
This is my dying testimony, and I must sign it.
If I had been faithful,
I should have expressed it in the last Yearly Meeting of Ministers and Elders;
but I hope I shall be forgiven.
O Lord! accept me with the best I have!
I have letters from America,
which confirm me in the truth of every part of what I now state.
I believe there is not an individual member of our Society, in England, Scotland,
or Ireland, more willing to do good, than J. J. Gurney.
But willingness is no qualification.
This is my dying testimony to Quaker views, especially as to the ministry.
What was antichrist in George Fox`'s days, is antichrist now.
The clergy of this country, to a man, every one of them,
are antichrist so long as they wear the gowns and receive the pay,
and continue building up the people in the relics of Popery,
which the church of England retained.
It will not do to speak of a man doing a great deal for a little pay,
and call him a minister of Christ.
It is a grievous thing, that any minister in our Society should so speak.
They are antichrist still, since they lead the people from Christ.
And yet I love some of them for the work`'s sake, so far as they go.

=== Appendix B A Declaration of the Yearly Meeting of Friends in Philadelphia Concerning the Unsound Doctrines of Elias Hicks

In the course of the narrative respecting his journey in America,
our dear friend Thomas Shillitoe makes frequent mention of the difficulties which occurred
in consequence of the principles promulgated by Elias Hicks and his adherents,
and their ultimate secession from the religious Society of Friends.
In order to give the reader a correct idea of the wide difference
between those principles and the doctrines of the Society,
the editors of the Friends`' Library think it right to insert some extracts
from "`A Declaration,`" issued by the Yearly Meeting of Philadelphia,
setting forth the causes of the separation, etc.;
a document to which Thomas Shillitoe frequently refers in the following pages.

A Declaration of the Yearly Meeting of Friends, etc.

'`At a Yearly Meeting of Friends held in Philadelphia,
by adjournments from the 21st of the fourth month, to the 28th of the same, inclusive,
1828.

The Meeting for Sufferings having been engaged in preparing a declaration
of the principal causes and progress of the schism which has taken
place on the part of some under our name,
within the limits of this Yearly Meeting,
and which also exhibits the doctrines of the Separatists,
contrasted with the principles and faith of our religious Society,
it was deliberately read;
and the meeting being brought into a serious consideration
of the affecting evidence which it furnishes,
of the desolating consequences produced by the spirit
and principles of unbelief and insubordination,
and believing that it is due to the cause of Christianity,
and the reputation of our religious Society, to bear our testimony to the world,
against the anti-scriptural doctrines,
and disorganizing proceedings and conduct of the Separatists,
fully unites with this declaration and testimony,
and directs it to be signed by the clerk, and published on behalf of this meeting.
It being as follows:

In taking a view of the situation of our religious Society,
and of the various exercises and close trials,
which those who love our Lord Jesus Christ, have had to pass through,
we believe it important to preserve a faithful narrative of the
schism which has taken place among some under our name,
and to trace the subtle workings of that spirit of unbelief and insubordination which
has been the primary cause of it--a spirit which has been privily brought in among us,
under the specious appearance of a refined spirituality,
but which has blinded the understandings of many, and led them, step by step,
into an open denial of the fundamental doctrines of the Christian religion,
as they are laid down by our blessed Redeemer and his apostles, in the Holy Scriptures.

Previous to entering on the proposed narrative,
it may not be improper to notice the rise of our religious Society,
and some of the troubles which befel it during its infancy.
It pleased the Lord Almighty in the dispensations of his infinite wisdom and goodness,
to gather our worthy predecessors out of the various
professions and worships of the world,
to release them from the formalities of a ceremonial religion,
and by the immediate teachings of his Holy Spirit
to bring them to the knowledge of himself,
as he is revealed in and through our Lord and Saviour Jesus Christ.
Instructed in the nature of that worship which is acceptable to the Father,
and yielding obedience to the discipline of the cross,
they were led into purity of life and conversation,
evincing great tenderness of conscience,
and a fear of doing any thing which might bring a shade upon their holy profession.
Thus they became as '`a city set on a hill that could
not be hid,`' and many were convinced of the truth,
and joined in fellowship with them.

In the faithful maintenance of the doctrines and testimonies committed to them,
they endured much persecution and bitter suffering,
but notwithstanding the various obstacles they had to contend with,
the Society rapidly increased, and when William Penn received the grant of Pennsylvania,
many of the members migrated with him,
and found a peaceful retreat from the persecutions which awaited them in their own land.
The privations which they were subjected to in a new country,
being favourable to that simplicity and self-denial which their profession inculcates,
they became a religious body comprising many substantial and divinely gifted members,
in whose hands the cause of Truth prospered, and many meetings were established.
But the old adversary who envies the advancement of the Redeemer`'s kingdom,
and is ever busily striving to lay waste the work of righteousness in the earth,
wrought upon the hearts of some restless and ambitious individuals,
who had once been favoured instruments in the Lord`'s hand,
filling their minds with envy and prejudice against their brethren,
and leading them into open opposition to those things,
which in the days of their fidelity,
they had believed in--and finally into separation from the Society.
This was sorrowfully the case with John Wilkinson
and John Story and their party in England.
The apostacy and misconduct of these Separatists brought great reproach upon the Society,
and subjected those who stood firm in their first love, to deeper exercises,
and more painful trials,
than all the outward afflictions which they endured from their cruel persecutors.
It was a common outcry among them, '`Away with your order;
let everyone be left to his liberty.`' They made '`disturbances
in meetings to the breaking of the church`'s peace,
causing divisions among Friends;
publishing to the world wicked and scandalous books against Friends;
shutting and keeping Friends out of their common meeting houses,
in which they have a just right and property, and not allowing them to meet therein; and,
at length, also set up separate meetings,
in opposition to the meetings of God`'s people,`' See Ellwood`'s Journal, p. 275.

In this country, the peace and harmony of our religious Society,
was early interrupted by George Keith.
His ambitious, aspiring disposition,
led him to attempt introducing innovations in principle and practice,
and when he found that discerning Friends would not be drawn into his measures,
he endeavoured to divide the Society, and to set up a Yearly Meeting,
and other separate meetings, within the limits of this Yearly Meeting.
But the Society steadily adhered to its doctrines and discipline, while ho and his party,
persisting in their disorganizing attempts, were scattered from the fold of Christ,
and many of them were finally disowned.
The revolutionary war was productive of new trials upon the stability of the Society.
Numbers were drawn aside to violate its testimony against war,
but while such experienced much unsettlement,
the sincerely exercised and faithful members,
were more closely united in a deep religious concern,
for their preservation upon the sure foundation,
that they might give practical evidence of the peaceable nature of the Messiah`'s kingdom,
by acting on all occasions consistently therewith.
Thus, though it has been assailed by severe trials, within and without,
the Society continued as a body firmly united in faith and discipline,
and through the mercy and protection of our holy and divine Leader,
was still enabled to hold up a light to the world.

Causes, however, have been operating for several years,
to prepare the way for the introduction of opinions,
repugnant to our religious principles and doctrines,
and tending to lay waste that love and Christian fellowship,
which have so conspicuously distinguished the Society,
and given effect to its exertions in the cause of universal righteousness.
Lukewarmness respecting the important work of religion, an increasing love of the world,
and an eager pursuit of its riches, pleasures and fashions,
disqualifying many for usefulness in the church, introduced weakness,
and eclipsed the brightness of our Christian profession,
which had shone so eminently in the example of our worthy ancestors.
Others who were influenced by a restless aspiring disposition,
have at different periods opposed the administration of a sound discipline,
and endeavoured to throw off those salutary restraints,
indispensable to the existence of every well regulated society.
Among other causes which have contributed to its weakness,
is the too easy reception of papers of acknowledgment
from those who had transgressed the discipline,
and the admission of persons into membership who had not been sufficiently
grounded in the doctrines of the Christian faith.
But one of the most fertile sources of evil, has been the neglect of many of our members,
in not bestowing upon their offspring a guarded religious education;
labouring to imbue their susceptible minds with the saving truths of the Gospel,
and habituating them to frequent reading of the Holy Scriptures.
For lack of this godly concern on the part of parents and teachers,
many of our youth have grown up in great ignorance of those all-important subjects,
as well as of the history and principles of our ancient Friends;
so that many have fallen an easy prey to the cavils and sophistry of designing men,
who were seeking to lead them astray,
by infusing doubts into their minds respecting the truths of the Christian revelation.

In the lapse of a few years, it has pleased the Lord in his unsearchable wisdom,
to remove from works to rewards many eminent servants,
who stood as faithful watchmen upon the walls of Zion,
and being clothed with the spirit of discernment,
were enabled to detect the various stratagems of the enemy,
and to defeat his attempts to lay waste the Society.
Sentiments promulgated at different periods by Elias Hicks,
a minister belonging to Jericho, on Long Island,
occasioned great uneasiness in the minds of some of those Friends, and others,
who privately communicated their apprehensions to him.
A spirit of libertinism and independency,
fostered and strengthened by the neglect of proper discipline in families,
prepared many to listen with delight to such sentiments,
which were before unknown in the communications of our ministers.
The disclosure of his views, however, was gradual,
and for a long time in a very covert manner.
The subordination and respect due from youth, to age and experience,
which true religion ever enforces, were undermined by his frequent suggestions,
that their elder friends were '`sticking in the traditions of their fathers,
and could not go on with the work of reformation,
and it was therefore necessary that the young people
should come forward and take the lead.`"
The observance of the first-day of the week, was held up as being superstitious;
and those who did not join with him in rejecting the products of slave labour,
were compared with the most abandoned and wicked characters,
and pronounced to be unfit to take any part in promoting the cause of Truth.
While he thus boldly denounced those who could not adopt his views,
others were flattered and enlisted with his attentions;
and thus the Society was gradually, and imperceptibly divided by his doctrines,
and the strong contrasts which he drew, between different portions of it.

Under the plausible pretext of exalting the '`light
within,`' as the primary rule of faith and practice,
he endeavoured to lessen the authority of the Holy Scriptures; and,
when he had greatly impaired the sentiments of reverence
justly due to their divine testimony,
he proceeded to speak of our blessed Saviour,
as being merely an example or pattern to us,
and denied that his death was an offering for the sins of mankind,
except for the legal sins of the Jews, calling him the Jewish Messiah.
Faithful, experienced Friends,
who were established in the doctrines of Christ and his apostles,
and who saw the baneful consequences that must result
from the promulgation of such opinions,
were brought under much painful solicitude, for the preservation of the Society,
as many were caught with the speciousness of his arguments,
and the bold and confident manner with which he advanced them.
Having proceeded further in avowing his disbelief
in our Lord Jesus Christ as the Saviour of men,
publicly declaring, that the same power that made him a Christian,
must make us Christians, and that the same power that saved him, must save us;
he was again privately laboured with, in order to convince him of his error;
and upon being told that if he persisted in preaching these doctrines,
so contrary to the Scriptures, and the testimony of our ancient Friends,
it would produce one of the greatest schisms that had ever happened in the Society,
he admitted that it would produce a schism, but that it would soon be over,
for he believed his doctrines must and would prevail.
He was so confirmed in his sentiments, that he said he should persevere therein,
"`let the consequences be what they might.`"

In the twelfth month, 1822, Elias Hicks came to Philadelphia,
with certificates from his Monthly and Quarterly Meetings,
to pay a visit to some parts of our Yearly Meeting,
including the families of two of the Monthly Meetings in this city.
It was well known to many Friends,
that he was charged with holding and propagating opinions,
incompatible with the doctrines always held by our religious Society,
and some of the elders being informed by two Friends
who were present at a meeting in the Southern Quarter,
that he there advocated such opinions,
two of them called upon him on his arrival in Philadelphia,
and stated the information they had received,
and proposed an interview between him and those two Friends,
which he refused to accede to.
Another attempt was made to procure such an interview, which he also rejected.
As the friends of Elias Hicks, as guardians of the ministry,
and of the flock over which they were placed as overseers,
the elders believed it to be their duty still to seek a conference with him,
that '`if any incorrect statement had been made, it might be speedily rectified,
or if true,
that he should be possessed of the concern and judgment of his
friends thereon.`' But after a time and place were fixed,
they failed in their brotherly attempt to obtain the proposed interview,
by his encouraging a number of his partizans to intrude themselves into the company.
The elders then addressed a letter to him,
declaring that they '`could not have religious unity with his conduct,
nor with the doctrines he was charged with promulgating.`' In a subsequent communication,
having the accounts of his unsoundness corroborated
by his public discourses in this city,
they state that they were '`fully and sorrowfully confirmed in the conclusion,
that he holds and is disseminating principles very different from
those which are held and maintained by our religious Society,
and that as he had closed the door against the brotherly
care and endeavours of the elders for his benefit,
and for the clearing our religious profession,
they think the subject ought to claim the weighty attention of his Friends at home.`'

From this period may be dated the regular organization of a party devoted to his interests.
Active exertions were used by those who have since stood
conspicuous among the promoters of the present separation,
to enlist every one they could, in favour of him and his opinions.
Unjust and unfounded representations were industriously spread throughout the Society,
in order to create a prejudice against those who could not conscientiously
approbate his conduct and anti-christian views,
especially against Friends in Philadelphia, who openly avowed their disunity with him.
Much animosity was manifested by his adherents,
and the false reports and opprobrious epithets,
applied to those who bore a faithful testimony against his principles and ministry,
gave ample proof of the origin and disorganizing tendency, of such doctrines.

Under these circumstances our Yearly Meeting convened in 1823.
Among the subjects which had claimed the attention of the Meeting for Sufferings,
they believed it proper as representatives of the Yearly Meeting,
to disclaim certain controversial essays, printed in a periodical paper at Wilmington,
Delaware, appearing to be written in the name of the Society,
but which contained sentiments incompatible with those it had always held and professed.
A short minute for the purpose was adopted and forwarded to the editor;
a few selections from the writings of Friends were
also prepared by a committee to accompany the minute,
showing our faith upon those controverted points of doctrine.
But the meeting deciding that the minute would be sufficient,
it was agreed to print the selections in a pamphlet, to be distributed to our members,
for the purpose of reminding them of those excellent
Christian principles which our forefathers held,
and suffered for.
When the minutes of the Meeting for Sufferings were read in the Yearly Meeting,
its authority to prepare those selections,
was questioned by some of those who have since separated from us;
many severe reflections were passed upon that body and much
disturbance created by the disaffected upon this occasion.
While some professed to admit,
that the sentiments contained in the extracts might be correct,
they unjustly charged the Meeting for Sufferings,
with attempting to impose a creed upon the Society;
others condemned the doctrines themselves, as contrary to Scripture,
reason and revelation,
although selected from works which had been repeatedly approved by the Society.
Great noise and confusion prevailed among them, and the meeting adjourned.
At the next sitting, one of the leaders of the disaffected party,
proposed that those extracts should be expunged from
the minutes of the Meeting for Sufferings;
but as this would have implied a disavowal of the doctrines they contained,
the meeting refused to accede to it.
The clamour and violence of the opposers was such,
that in order to obtain a state of quietude in the meeting,
Friends at length consented to direct the Meeting for Sufferings
to suspend the publication of the pamphlet,
which had been printed, and placed in the book room.
We have thought it right thus to rehearse the facts relating to this subject,
because they have been grossly misrepresented in various places,
and motives and designs attributed to Friends, which were not only untrue,
but absolutely unfounded.

Although the disaffected members denied the right of the Meeting for Sufferings
to prepare and publish extracts from the writings of our early Friends,
yet afterwards they themselves assumed the right of doing so,
and published a pamphlet of extracts,
the object of which was to support the doctrinal views of Elias Hicks.
In making their selections great injustice was done
to the authors from whose works they were taken,
material parts of sentences being omitted, and in some places words were introduced,
so as to change entirely the true meaning of the writer,
and even to make him contradict himself In the progress
of this spirit of misrepresentation and division,
much labour was privately bestowed,
to convince individuals of the unsoundness of the doctrines preached by Elias Hicks,
and by some other ministers who had adopted his opinions,
and to show the desolating effects that would be produced by them upon the Society.
But such was the strength of prejudice against sound Friends,
that arguments or entreaties in most instances were unavailing,
and these endeavours to convince were often met with unkind reflections and criminations.

From the decided opposition which they had made to the dissemination of unsound principles,
it was apparent to the advocates of the '`new views,`' that the elders,
and members of the Meeting for Sufferings,
would present a great obstacle to their general adoption.
Unwearied efforts were therefore used to bring them into discredit,
and to alienate Friends from them; and after great exertion to accomplish this object,
a plan was projected for altering the discipline,
so as to make these appointments subject to frequent change.
Accordingly, in 1825, the project was introduced into one of the Quarterly Meetings,
where the disaffected party predominated, and a minute made,
'`contrary to the solid sense and judgment of many Friends,`' proposing
that all important appointments should be made for a limited time.
On its introduction to the Yearly Meeting, much discussion ensued,
in which the party urged their favourite measure, but the meeting decided,
that such a rule would be unsafe, and it was dismissed.

"`As a further means for spreading the views of the seceding party,
and giving strength to their cause, they widely circulated a volume of discourses,
delivered by Elias Hicks, in one of his visits within this Yearly Meeting,
which contain sentiments correspondent with those he had long been charged with holding,
directly repugnant to the glorious character of our Lord Jesus Christ,
as the Saviour and Redeemer of men, our Mediator and Advocate with the Father,
and also undervaluing the Holy Scriptures.
A periodical paper called the Berean, devoted to the same cause, was also set up,
and circulated among our members, in which was a series of essays,
openly attacking the acknowledged doctrines of Friends,
and tending to subvert their faith in the divinity of Christ,
and his propitiatory sacrifice for the sins of mankind;
by which we believe many have been turned into the paths of scepticism,
and thereby lost that true peace and assurance,
which are only found in the faith of the Gospel.
The lamentable effects of the principles disseminated by such publications,
became more and more obvious.
Accustomed to hear the sacred truths of Christian redemption called in question,
many lost that awe which those solemn subjects had heretofore inspired,
and allowed themselves the liberty of speaking upon
them in a light and very irreverent manner.
The arising and spreading of the power of Truth in our assemblies for divine worship,
was much obstructed by the spirit of unbelief;
and opposition increased among the disaffected to the administration of the discipline,
especially when it was likely to displace any of their own party.
In some meetings, where they had the control,
unjustifiable measures were adopted to promote party purposes,
thereby producing great distress and exercise to Friends.
Notwithstanding all their efforts,
they did not obtain that complete ascendency which their leaders anxiously desired.
Friends being enabled, through the merciful interposition of divine assistance,
to maintain their ground, with a good degree of firmness,
against the inroads of infidelity, and the flood of reproach and false accusations,
which was poured forth against them;
and the disaffected therefore determined to use some
further means to bring about a revolution.

+++[+++After some account of the Yearly Meeting held in Philadelphia, in 1827,
the "`Declaration`" proceeds:]

Having endeavoured to give a faithful narrative of some of the
prominent events which have marked the course of the present schism,
of which it is alleged that the promulgation of doctrines
subversive of the faith of our religious Society,
has been the primary cause,
it remains to exhibit these doctrines from works acknowledged by the Separatists,
and which they have widely circulated for the purpose of disseminating their views;
and also to contrast these doctrines,
with those which have been always held and professed by
the Society of Friends from its rise to the present day.
It should be distinctly recollected that in the first official document which they issued,
and in which they declare the grounds of their dissatisfaction with Friends,
the Separatists assert that '`doctrines held by one part of Society,
and which we believe to be sound and edifying,
are pronounced by the other part to be unsound and spurious.
From this has resulted a state of things,
that has proved destructive of peace and tranquillity,
and in which the fruits of love and condescension have been blasted,
and the comforts and enjoyments,
even of social interaction greatly diminished.`' The address containing this
declaration is signed by direction and on behalf of the meeting held on the 19th,
20th, and 21st of the fourth month, 1827,
by John Comly and nine other persons from different parts of our Yearly Meeting,
and we regard it as a candid acknowledgment that from those doctrines,
which Friends pronounce "`to be unsound and spurious,`" but which
the Separatists "`believe to be sound and edifying,`" have resulted
the difficulties in which the Society has been involved.

In their epistle issued in the sixth month following,
they further allege that '`faithful Friends in the ministry
were unjustly charged with preaching infidel doctrines,
denying the divinity of Christ,
and undervaluing the Scriptures.`' We know of no faithful
Friends against whom these charges have been advanced.
But there are those,
who not keeping in a state of humility and subjection to the cross of Christ,
which would have preserved them in the unity of the faith,
and in a willingness to endure suffering for the Gospel`'s sake,
have listened to the voice of the stranger, and being deceived by his transformations,
as the appearance of an angel of light,
they have by degrees lost their habitation in the blessed Truth,
and made shipwreck of faith and of a good conscience.
Some of these continuing to exercise the office of minister,
which they once acceptably occupied among us, have been led, step by step,
to broach doctrines which are subversive of the Christian faith,
and contrary to the doctrines and principles of our religious Society.
This defection, however, is not confined to those who were ministers,
but there are many others,
who hold and are engaged in propagating the same unsound sentiments.
Their various plans have been arranged and directed,
to procure the adoption of these sentiments, as the faith of the Society;
but disappointed at last by their failure,
and perceiving that Friends were increasingly alive to the importance
of preserving the Society from the dangerous effects of such doctrines,
the only alternative, in their view, was a complete severance from its communion.

We shall not attempt to trace their unsoundness through all its ramifications,
but we shall adduce evidence from their own works,
which we believe must conclusively prove,
that they deny the divinity of our Lord Jesus Christ,
that he is the Redeemer and Saviour of men,
our Propitiation and Mediator with the Father,
and also that they undervalue the Holy Scriptures.
The selections are chiefly taken from the discourses of Elias Hicks.
Most of their ministers inculcate the same opinions,
but we have confined ourselves to a few of those
discourses which are before the public m print.
Extracts are also made from the Berean,
periodical publication which the Separatists have circulated for several years,
as a standard work on the faith of the Society,
but which we believe has had a very pernicious effect
in leading astray many sincere-hearted people,
who were not aware of the poison that is insidiously conveyed through its pages.
This work, speaking of the volume of Elias Hicks`' discourses, already noticed, says,
'`it will make the traditional outside Christian startle, and the dreamers, high priests,
the scribes and pharisees of every denomination to gnash their teeth;
but the great body of the society on this continent,
of which this venerable minister is a member,
together with many other unshackled minds will set
their seals to the doctrines which it contains.
Vol. I. p. 398.

In accordance with this declaration,
several Monthly Meetings in which his adherents had the rule,
and who have since joined the new sect,
prepared and issued minutes expressive of their satisfaction with him and his doctrines.
But the attendance of Elias Hicks at the General Association of the Separatists,
held in this month at Green street, establishes beyond all doubt,
his unity with them in breaking their connection with the Society of Friends;
and by placing a record on their minutes of his presence,
and their satisfaction with his company, the Separatists, as a body,
have formally identified themselves with him and his anti-christian doctrines,
a declaration of which he openly made in very palpable terms,
in one of their largest meetings on the preceding day.

We shall proceed with the extracts,
commencing with their opinions respecting the Holy Scriptures:

Elias Hicks says, "`If the Scriptures were absolutely necessary,
he had power to communicate them to all the nations of the earth,
for he had his way as a path in the clouds:
he knows how to deal out to all his rational children.
But they were not necessary, and perhaps not suited to any other people,
than they to whom they were written.`"
Philadelphia Sermons, p. 119.

"`One would suppose that to a rational mind,
the hearing and reading of the instructive parables of Jesus would have
a tendency to reform and turn men about to truth and lead them on in it.
But they have no such effect.`"
Ibid. p. 129.

"`They have been so bound up in the letter, that they think they must attend to it,
to the exclusion of everything else.
Here is an abominable idol worship, of a thing without any life at all, a dead monument.`"
Ibid p. 139.

"`The great and only thing needful then is, to turn inward,
and turn our back upon the letter, for it is all shadow.`"
Ibid. p. 225.

"`Now the book we read in says, '`Search the Scriptures,`' but this is incorrect,
we must all see it is incorrect;
because we have all reason to believe they read the Scriptures,
and hence they accused Jesus of being an impostor.`"
Ibid. p. 314.

"`He +++[+++Jesus]
does not move us in the least degree to any book, or writing whatever,
but leaves everything outward entirely behind as having passed by,
for he abolished all external evidence,
as not being capable of bringing about salvation to the soul.`"
See Quaker; Elias Hicks`'s sermon, vol.
II. p. 264.

"`No experience will ever be worth any thing to us, which is not our own experience,
begotten through the influence of the blessed spirit of God.`"
N+++.+++ York Sermons, p. 123.

Thomas Wetherald, at an irregular meeting held at Green street, says,
"`And I want us therefore, in our investigation of spiritual things,
to bring spiritual evidence to prove spiritual truths.
Let us attend to spiritual reflections, and not be looking to the Scriptures,
and to the systems of men, and to the words of preachers;
for all these being of an external character, can only form an ignis fatuus,
which '`leads to bewilder and dazzles to blind.`'`"Quaker, vol. II. p. 217.

In accordance with the above sentiments concerning the Holy Scriptures, the Berean says,
"`In vain does any man quote the Scriptures as authority for his opinions;
for if they have not been immediately revealed to his own mind by the Holy Spirit,
they deserve no better name as it respects him, than speculations.`"
Vol. II. p. 211.

"`Those revelations were for other times and other states, and not for us.
They belong to those to whom they were immediately revealed.
And that, and only that, which is immediately revealed to us,
belongs in like manner to us and to us only.`"
Ibid. p. 212.

"`Now the revelations respecting the nature of god, which were made to the Israelites,
are true when viewed as in connection with,
and as having relation to their spiritual condition; but to any other state,
they are not true; therefore such revelations abstractedly taken,
are not true in themselves are not the truth of god.`"
Ibid. Vol. I. p. 403.

We could select many other passages derogatory to the Holy Scriptures,
but these are sufficient to show the contemptuous manner in which
they are spoken of by the Separatists and their ministers.
They assert that they are not necessary, and perhaps not suited to any other people,
than those to whom they were written; they are a thing without any life at all,
a dead monument, all shadow, upon which we should turn our backs;
that the direction of our Lord to search them is not correct;
that his parables have no such effect as a tendency
to reform and turn men about to Truth;
that in vain does any man quote the Scriptures as authority for his opinions;
that without immediate revelation they are no better than speculations;
that they only form an ignis fatuus which leads to bewilder, and dazzles to blind;
that no experience will ever be worth anything to us which is not our own experience,
and that that only belongs to us which is immediately revealed to us;
and that the revelations which were made to the Israelites respecting the nature of God,
are not true in themselves; are not the truth of God.

We are not surprised that persons holding the opinions which they do,
relating to the great truths of Christian redemption,
should undervalue and endeavour to destroy the authority of the Holy Scriptures.
For so long as they are admitted to be a test of doctrine,
all their pretended revelations which contradict the testimony of the Sacred Record,
are properly condemned as '`unsound and spurious.`' But
we could not have supposed that at this enlightened day,
when their divine authority has been so abundantly confirmed,
by the accomplishment of the ancient prophecies,
and in the experience of the true Christian,
that any of the professed believers of the '`light within`' would dare to assert,
that those divine revelations respecting the nature of God, are not true in themselves,
are not the truth of God.
It is an affecting proof of the dreadful consequences
of a spirit of scepticism and unbelief,
that they should become so darkened as to speak in this irreverent
manner of those weighty truths revealed to the Lord`'s servants,
to whom he condescended to speak as face to face.

The Society of Friends have always fully believed in the
authenticity and divine authority of the Holy Scriptures,
and acknowledge them to be the only fit outward test of doctrines,
having been dictated by the Holy Spirit of God, which cannot err.
They are profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works; and are able to make wise unto salvation,
through faith which is in Christ Jesus; and whatever any teach or do contrary thereto,
they reject as a delusion.
Under a profession of exalting the light of Christ as the immediate means of salvation,
which is a doctrine most fully believed by us, some have undervalued the Holy Scriptures,
as being unnecessary to the Christian.
It is contrary to the practice of the Society to speak of them in any such terms.
We esteem them a great blessing to the church,
and desire to cultivate feelings of gratitude to the Great Disposer of events,
for preserving them through various revolutions and vicissitudes,
being fully persuaded that the more we become obedient to
the manifestations of the light of Christ in the heart,
the more precious and valuable are those inestimable writings to us.

In proof that these have been the sentiments of the Society from the beginning,
we shall adduce the testimony of Robert Barclay and William Penn.
In his Apology for the principles and doctrines of the people called Quakers,
which we have always owned as a declaration of our faith, Robert Barclay says,

"`In this respect above mentioned then,
we have shown what service and use the Holy Scriptures, as managed in and by the Spirit,
are of to the church of God; wherefore we do account them a secondary rule.
Moreover because they are commonly acknowledged by all to
have been written by the dictates of the Holy Spirit,
and that the errors which may be supposed by the injury of times to have slipped in,
are not such but that there is a sufficient clear testimony
left to all the essentials of the Christian faith;
we do look upon them as the only fit outward judge of controversies among Christians;
and that whatsoever doctrine is contrary unto their testimony,
may therefore justly be rejected as false.
And for our parts we are very willing that all our
doctrines and practices be tried by them;
which we never refused, nor ever shall, in all controversies with our adversaries,
as the judge and test.
We shall also be very willing to admit it as a positive certain maxim,
that whatsoever any do, pretending to the Spirit, which is contrary to the Scriptures,
be accounted and reckoned a delusion of the devil.`' p. 99.

William Penn,
in his '`Testimony to the Truth,`' after stating
some groundless charges made against Friends,
respecting their belief in the Holy Scriptures, says,

"`Whereas we in truth and sincerity believe them to be of divine authority,
given by the inspiration of God through holy men, they speaking or writing them,
as they were moved by the Holy Spirit;
that they are a declaration of those things most surely believed by the primitive Christians,
and that as they contain the mind and will of God, and are his commands to us,
so they in that respect are his declaratory word; and therefore are obligatory on us,
and are profitable for doctrine, reproof, correction and instruction in righteousness,
that the man of God may be perfect, and thoroughly furnished to every good work.
No, after all, so unjust is the charge +++[+++preferring our own books, etc.]
and so remote from our belief concerning the Holy Scriptures, that we both love, honour,
and prefer them, before all books in the world;
ever choosing to express our belief of the Christian faith and doctrine,
in the terms thereof, and rejecting all principles or doctrines whatsoever,
that are repugnant thereunto.
Nevertheless we are well persuaded,
that notwithstanding there is such an excellency in the Holy Scriptures,
as we have above declared, yet the unstable, and unlearned in Christ`'s school,
too often wrest them to their own destruction.
And upon our reflection on their carnal constructions of them,
we are made undervaluers of Scripture itself But certain it is,
that as the Lord has been pleased to give us,
the experience of the fulfilling of them in measure,
so it is altogether contrary to our faith and practice,
to put any manner of slight or contempt upon them,
much more of being guilty of what maliciously is suggested against us;
since no society of professed Christians in the world,
can have a more reverent and honourable esteem for them than we have.
John 4:24, 16:8. Rom. 1:19. Luke 1:1-2. 2 Tim. 3:16,17. 2 Pet. 3:16.`'
Vol. II. p. 878.`"

The Separatists would appear to be great advocates for divine revelation,
at the same time they declare that the revelations made to the
Lord`'s prophets respecting the divine nature are not true.
In reference to all such pretensions, William Penn says,

"`That we renounce all fantastical, and whimsical intoxications,
or any pretence to the revelation of new matter in opposition to the ancient Gospel,
declared by Christ Jesus and his apostles;
and therefore not the revelation of new things,
but the renewed revelation of the eternal way of truth.
That this revelation is the life, virtue,
condition and very soul of the Gospel and second covenant.`"
Vol. II. p. 48.

In the same essay:

"`If you are led by the spirit of God, then are you sons of God;
let this suffice to vindicate our sense of a true and unerring rule, which we assert,
not in a way of derogation from those Holy Writings, which with reverence we read,
believe and desire always to obey the mind and will of God therein contained;
and let that doctrine be accursed that would overturn them.`"
Ibid. p. 62.

It must be evident to every candid mind,
that the sentiments of the Separatists which we have quoted from their own works,
are at perfect variance with the doctrines of our
early Friends respecting the Holy Scriptures,
however they may endeavour to make the impression upon the public mind,
that they are one in faith with them.

In the next place we will show that they deny the miraculous conception of our Lord.

Elias Hicks says, "`Who was his father?
He was begotten of God.
We cannot suppose that it was the outward body of
flesh and blood that was begotten of God,
but a birth of the spiritual life in the soul.
We must apply it internally and spiritually.
For nothing can be a Son of God but that which is spirit,
and nothing but the soul of man is a recipient for the light and spirit of God.
Therefore nothing can be a Son of God but that which is immortal and invisible.
Nothing visible can be a Son of God.
Every visible thing must come to an end, and we must know the mortality of it.
Flesh and blood cannot enter into heaven.
By the analogy of reason, spirit cannot beget a material body,
because the thing begotten, must be of the same nature with its father.
Spirit cannot beget any thing but spirit; it cannot beget flesh and blood.
No my friends it is impossible.`"
Philadelphia Sermons, p. 10.

"`'`Now in his creed +++[+++the bishop of Rome]
to which he made all the nations of Europe bow by the dint of the sword,
was this of the miraculous birth, therefore all children for several hundred years,
were brought up, and educated in this belief,
without any examination in regard to its correctness.
Finding this to be the case,
I examined the accounts given on this subject by the four evangelists,
and according to my best judgment on the occasion,
I was led to think there was considerable more Scripture
evidence for his being the son of Joseph,
than otherwise,`" etc.
Letter of Elias Hicks to T. Willis.

The Berean says, "`The flesh was made, not begotten,
for the Word which is spiritual to appear in.
A body you have prepared me.
This does not convey to my mind,
the most distant idea of the body of Christ being begotten of God.`"
Vol. II p. 27.

In these passages the miraculous conception of the body of Jesus Christ,
by the overshadowing of the Holy Spirit, is plainly denied;
as such unworthy sentiments are contrary to the declaration of Holy Scripture,
we regard them as the '`spurious`' doctrines of infidelity or unbelief.

The succeeding extracts from the public printed discourses of the Separatists,
clearly prove their denial of the divinity of our Lord Jesus Christ,
his propitiatory sacrifice for the sins of mankind,
and degrade him to a level with his creature man, liable to be lost,
and standing in need of salvation as he does.

Elias Hicks says, "`For he +++[+++Jesus Christ]
had read the law and understood it,
because he was faithful to the manifestation of light; and it was dispensed to him,
in proportion to his necessity to understand the law.
For he had not more given him than would enable him to fulfill it,
the same as the other Israelites; for if he had more,
he could not be an example to them.`"
Wilmington sermon; Quaker, vol. I. p. 193.

"`We must turn our back upon them, and come home to the light of God in us;
for it is the same spirit and life that was in Jesus Christ the Son of God.
We need not say that it is his spirit, but only that it is the same spirit,
a portion of which was in him; because as reasonable beings,
we must always take things rationally.`"
Ibid. p. 197.

"`And what encouragement my friends we receive through this medium,
when we are brought by the light into a feeling of unity with our great pattern,
Jesus Christ, and with God our Creator, O see how we come up into an equality with him.`"
Darby, ibid. p. 13.

"`And we derive a portion of the same +++[+++spirit]
which is able to save the soul if properly obeyed.
Here now he was put upon a level;`" etc.
Ibid. p. 17.

"`Here we find that the Son of God saw no alternative;
for if he gave up his testimony in order to save his natural life,
he could not be saved with God`'s salvation:
hence he surrendered to the divine will rather than to lose
his standing and favour with his Almighty Father;
and what a blessed example it was.`"
Ibid. p. 16.

"`He was tempted in all points as we are.
Now how could he be tempted,
if he had been fixed in a state of perfection in which he could not turn aside.
Can you suppose as rational beings, that such a being could be tempted?
No, not any more than God Almighty could be tempted.
Perfection is perfection, and cannot be tempted.
It is impossible.`"
Philadelphia Sermons, p. 253.

It would follow from this argument that Elias Hicks does
not believe that our blessed Lord was perfect.

"`Every Christian must come up under the influence of the same
light that guided Jesus Christ--that Christ that was his Saviour,
and Preserver; and that power which enabled him to do his work,
will enable us to come on in the same path.`"
Quaker, vol. I. p. 44.

"`I don`'t want to express a great many words,
but I want you to be called home to the substance.
For the Scriptures and all the books in the world can do no more.
Jesus could do no more than to recommend to this comforter, which was this light in him.`"
Ibid. p. 40.

"`He never directed to himself but all he wanted
was to lead their minds to the spirit of Truth,
to the light within, and when he had done this, he had done his office.`"
Ibid. p. 47.

"`If we believe that God is equal and righteous in all his ways,
that he has made of one blood all the families that dwell upon the earth,
it is impossible that he should be partial,
and therefore he has been as willing to reveal his will to every creature,
as he was to our first parents, to Moses and the prophets,
to Jesus Christ and his apostles.
He never can set any op these above us, because if he did he would be partial.`"
Philadelphia Sermons, p. 292.

"`From what Jesus himself said, he was not God.`' N. York Sermons, p. 96.

"`He was only an outward Saviour, that healed their outward diseases,
and gave them strength of body to enjoy that outward good land.
This was a figure of the great Comforter, which he would pray the Father to send them;
an inward one, that would heal all the diseases of their souls,
and cleanse them from all their inward pollutions, that thing of God,
that thing of eternal life.
It was the soul that needed salvation, but this no outward Saviour could do,
no external Saviour could have any hand in it.`"
Philadelphia Sermons, p. 50.

"`The apostle had allusion to that perfect righteousness
which is the immediate saviour in the soul,
Christ within the hope of glory;
but it was not that outward Jesus Christ that was the hope of glory.`"
Quaker, vol. I. p. 164.

"`'`It +++[+++the light]
is truly God in man; for as he fills all things,
he cannot be located in any thing which is capable of being located,
because to suppose that all the fulness of God was in Christ,
is to take him out of every other part of the world.`'
Ibid. p. 166.

"`Oh dearly beloved friends, young and old,
may you gather deeper and deeper to that which is within the veil,
where we may have access to our God without any mediator.`'
Quaker, vol. II. p. 277.

The preceding selections have all been taken from the discourses of Elias Hicks.

Edward Hicks, at the Green street meeting, says, "`I ask then the question,
how did he +++[+++Jesus Christ]
leave the bosom of his Father?
Can we form no other idea than that of a corporeal being, leaving a located place,
somewhere above the clouds, and coming down to this earth?
Is this the coming into the world that is meant?
I want us to go deeper--to come to the spirituality of these things,
and to recognize a spiritual saviour, rather than an outward and corporeal one.
Because it is only a spiritual one that can save us from sin.
That animal body that appeared at Jerusalem, had its use and day,
but the spirit that was clothed upon by the fulness of divine power,
this was the Saviour--this is the Saviour to whom I look for salvation,
and not by any means to any thing outward or corporeal.`"
Quaker, vol.
II. p. 151.

This declaration corresponds with others which we have quoted,
and is a virtual denial that Jesus Christ who appeared at Jerusalem,
is the Saviour of men.
The term "`animal body,`" used to designate our Lord, is irreverent,
and unbecoming a creature dependent upon him for salvation.

The Berean says, "`We read that the Word was in the beginning with God, and was God;
and respecting the Son we read, this day have I begotten you;
before this day then the Son could not have existed.
How therefore is the Son from everlasting?`"
Vol. I. p. 296.

"`In what manner then, or by what means was he made more than man?
I answer by the same means, and in the same manner,
that every other righteous undefiled man is raised above the mere human character;
that is to say by the power and spirit of God the Father.`"
Vol. II. p. 258.

"`Will it be presumed, that God whom the heaven of heavens cannot contain,
whose presence fills the whole universe, abode in his fulness literally in the man Jesus?
Can it be supposed, that he of whom it is declared, that he was limited in knowledge,
power and action, possessed absolutely the spirit of God without measure?
I believe not.`"
Ibid. p. 259.

"`He was but an instrument and servant of God,
but more dignified and glorious than any other that had ever appeared in the world.`"
Ibid.

"`The Christ then which it concerns us to have an interest in,
is not that outward manifestation which was limited
in its operations to a small province--a single nation,
and to this day known only by history to a few,`" etc.
Ibid. vol. II. p. 21.

"`But the manifestation to us is inward, and they +++[+++primitive Friends]
believe that is the Christ within, and not the Christ without,
on which is founded their hope of glory.`"
Vol. II. p. 84.

In his attack upon the '`doctrines of friends`' the berean says,
"`the doctrine therefore contained in the chapter under review,
ascribing a proper divinity to jesus christ,
making him the foundation of every christian doctrine,
asserting that '`the divine nature essentially belonged
to him,`' and constituting him a distinct^
footnote:[Note.--"`The reader is requested to take notice that the word
distinct is not used by me in the case to which it is here,
and in several other places, applied by the Berean.`"
E+++.+++ Bates`'s Reply.]
object of faith and worship, is not only anti-scriptural,
but opposed to the simplest principles of reason;
and is in short among the darkest doctrines that
has ever been introduced into the Christian church.`"
Vol. II. p. 259.

We are not left to conjecture the opinions of those who have separated from us,
respecting our Lord Jesus Christ,
nor to draw our conclusions from a few isolated expressions;
their views upon the subject are delivered in unequivocal terms,
and are diffused through most of their discourses and writings.
By the extracts we have made from the discourses of Elias
Hicks and the doctrinal publications of the Separatists,
it is plain that they directly assert,
That it is impossible for spirit to beget a material body--that
they cannot suppose that the body of Jesus Christ was begotten
of God that before the day in which it was declared,
I have begotten you,
the Son of God could not have existed--that nothing visible can be a Son of God
that he had no more light given him than would enable him to fulfill the law,
the same as the other Israelites--that he was but an instrument and servant of
God--that he was raised above the mere human character by the same means,
and in the same manner,
that every other righteous man is--that he was put upon a level
with us--that God who is equal and righteous in all his ways,
never can set him above us,
because if he did he would be partial--that Christ was the Saviour
of Jesus Christ--that we need not say that it is his spirit,
but only that it is the same spirit,
a portion of which was in him--that we come up into an equality with him--that Jesus
could do no more than to recommend to the Comforter--that when he had done this,
he had done his office--that he never directed to
himself--that he was only an outward Saviour,
a figure of the Comforter--it was the soul that needed salvation,
but this no outward Saviour could do,
no external Saviour could have any hand in it--that Jesus Christ was not the
hope of glory--that it is not that outward manifestation which it concerns us
to have an interest in--that to suppose that all the fulness of God was in Christ,
is to take him out of every other part of the world
that it is declared he was limited in knowledge,
power and action--that they believe not that he possessed
the spirit of God without measure--that he was not God--that
we may have access to God without any mediator--and lastly,
that ascribing a proper divinity to Jesus Christ,
making him the foundation of every Christian doctrine,
and asserting that the divine nature essentially belonged to him,
is among the darkest doctrines that have ever been introduced into the Christian church.

On the offering of our Lord upon the cross as a sacrifice for sin, Elias Hicks remarks:

"`But I do not consider that the crucifixion of the
outward body of flesh and blood of Jesus on the cross,
was an atonement for any sins but the legal sins of the Jews,`" etc.--"`Surely is it
possible that any rational being that has any right sense of justice or mercy,
that would be willing to accept forgiveness of his sins on such
terms!! Would he not rather go forward and offer himself wholly
up to suffer all the penalties due to his crimes,
rather than the innocent should suffer?
No--was he so hardy as to acknowledge a willingness to be saved through such a medium,
would it not prove that he stood in direct opposition
to every principle of justice and honesty,
of mercy and love, and show himself to be a poor selfish creature,
and unworthy of notice!!!`" Elias Hicks`'s letter to N. Shoemaker.

He further says: "`Did Jesus Christ the Saviour ever have any material blood?
Not a drop of it, my friends, not a drop of it.
That blood which cleanses from all sin, was the life of the soul of Jesus.`"
Quaker, vol. I. p. 41.

"`And there is nothing but a surrender of our own will,
that can make atonement for our sins.`"
Ibid. p. 196.

"`Nothing can atone for sin but that which induced us to sin.`"
Vol. II. p. 271.

"`And what are we to do?
We are to give up this life +++[+++our will]
to suffer and die upon the cross; for this is the atonement for all our sins.`"
Ibid, p. 272.

At the Green street meeting Edward Hicks says: "`His work, he +++[+++Jesus Christ]
declared to be finished previous to his being crucified in that outward body.
Therefore what must we suppose will become of the doctrine,
so generally received in the Christian world,
that one of the main purposes of his mission,
was for him to suffer in that outward body without the gates of Jerusalem,
as a propitiatory sacrifice for the sins of the whole world?
Here is a difficulty: for he positively declares that he had glorified his Father,
and finished the work that the Father had given him to do.
Now it must follow as a rational and clear conclusion, to every intelligent mind,
that he must have told the truth or an untruth.
If he told the truth,
then he had finished the work which his heavenly Father had given him to do;
and if he told an untruth, the work must have been yet to do.
But I am not not disposed to believe this.
I do believe in the truth of the emphatic testimony of the Saviour himself,
I have finished the work, and therefore that his sufferings in the outward body,
were never incorporated in the original design of
the blessed Saviour`'s coming into the world.`"
Quaker, vol. II. p. 162.

"`But my friends,
the inward suffering of the immortal soul is infinitely superior to all outward sufferings.
And if sin is atoned for in our souls,
it will require a sacrifice proportionable to that which is to be benefited by it.
So that I apprehend, under this spiritual dispensation and day of light,
there must be a spiritual and inward sacrifice for our sins.`"
Ibid. p. 163.

The Berean says:
"`Whatever redemption therefore was effected by the outward flesh and blood of Christ,
it could not in the nature of things be any thing else than an outward redemption.`"
Vol. II. p. 52.

"`'`And have we not reason to hope that the day is
not far distant when the absurd and pernicious idea,
that the imputed righteousness of another, is the ground of our acceptance with God,
will be found but in the pages of the historian,
when tracing the fruits of that lamented apostacy which early overtook Christendom.`"
Ibid. p. 333.

By these extracts we may perceive that Elias Hicks and his adherents deny the propitiatory
sacrifice of our blessed Saviour upon the cross for the sins of the whole world,
and consider that a willingness to be saved through such a medium
is in direct opposition to every principle of justice and honesty,
of mercy and love, and betrays a poor selfish disposition, unworthy of notice.
They believe that his sufferings in the outward body,
were never incorporated in the original design of his coming into the
world--that whatever redemption was effected by those sufferings,
it was only an outward redemption,
and confined exclusively to the legal sins of the Jews;
and in their opinion the sacrifice of the will is the only atonement
for all the sins now committed--that nothing can atone for sin,
but that which induced us to sin.

This doctrine, as it is contrary to the Holy Scriptures, so it is not,
and never was the faith of the Society of Friends.
We believe that nothing man can do, or suffer, will atone for, or cancel his sins.
They are remitted by the mercy of God, through Christ Jesus our Lord,
for the sake of the sufferings and death of Christ,
and it is the power and efficacy of that propitiatory offering,
upon faith and repentance,
that justifies both Jews and Gentiles from the sins that are past;
and it is the power of Christ`'s spirit in our hearts,
that purifies and makes us acceptable before God.
'`Being justified freely by his grace, through the redemption that is in Jesus Christ;
whom God has set forth to be a propitiation through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God; to declare I say at this time his righteousness;
that he might be just and the justifier of him which believes
in Jesus.`' '`But God commends his love towards us,
in that while we were yet sinners, Christ died for us.
Much more then being now justified by his blood, we shall be saved from wrath through him.
For if when we were enemies, we were reconciled to God by the death of his Son,
much more being reconciled, we shall be saved by his life.
And not only so, but we also joy in God,
through our Lord Jesus Christ by whom we have now received the atonement`'

Not only do the Separatists deny the universal efficacy of the offering of our Lord,
and term the imputation of his righteousness as the ground
of our acceptance a pernicious and absurd idea,
but they appear to rejoice in the hope, that the doctrine will be discarded,
as the fruit of the apostacy from the Christian faith.
Believing`' as we do, that it is only as we come to be divested of our own righteousness,
and of all confidence in it,
and through divine mercy clothed upon with the righteousness of Christ,
that any can have a firm ground whereon to rest their hope of salvation,
we sincerely deplore the delusion of those,
who thus wantonly deprive themselves of that hope, which makes not ashamed,
and enters within the veil.

We think that every candid dispassionate inquirer after Truth,
who sincerely believes the testimony of the Sacred Records,
must be convinced that many of the passages which
we have quoted from the discourses of Elias Hicks,
and the periodical works of the Separatists,
inculcate doctrines of infidelity--that they do deny
the divinity of our Lord and Saviour Jesus Christ,
and the universal efficacy of his most satisfactory
sacrifice for sin without the gates of Jerusalem,
and also undervalue,
and tend to destroy all confidence in the authority of the Holy Scriptures.
Such doctrines, we feel it an incumbent duty,
to pronounce to be unsound and anti-christian,
and contrary to the faith which we have always held and promulgated to the world,
ever since we have been a people.

For we have always professed and sincerely believed,
that our Lord Jesus Christ was miraculously conceived of the Holy Spirit,
and born of the Virgin Mary--that God gave not the spirit by measure unto him,
but that all the fulness of the Godhead dwelt in him bodily,
and of his fulness have all we received,
and grace for grace--that he was given for God`'s salvation to the ends of the earth,
for Gentiles as well as Jews,
and that no man comes unto the Father but by him--that
he was tempted in all points as we are,
yet without sin,
the prince of this world having no part in him--that he wrought many mighty
miracles--that he bore our sins in his own body upon the tree,
that we being dead to sin,
might live unto righteousness--that he laid down his life for the sheep,
that he by the grace of God, should taste death for every man;
and he is therefore the propitiation for our sins, and not for ours only,
but for the sins of the whole world--that he was
buried in the sepulchre of Joseph of Arimathea,
rose again from the dead the third day,
and his body saw no corruption--that he discovered
himself to his disciples for the space of forty days,
ascended up on high, and now sits at the right hand of God, our glorious Mediator,
Intercessor, and Advocate with the Father.
He is that living, eternal Word that was in the beginning with God, and was God;
by him were all things created that are in heaven and that are in earth,
visible and invisible, whether they be thrones or dominions, or principalities or powers,
all things were created by him and for him; and he is before all things,
and by him all tilings consist.
He is now come in spirit,
and by his divine light with which he enlightens every man that comes into the world,
he manifests and reproves for sin, and as he is obeyed, purifies the heart,
and completes the work of sanctification and justification;
and thus prepares the soul to receive that crown of everlasting glory,
which he will give to all them that love and serve him in sincerity and truth.

This has been our religious belief from the rise of the Society to the present day,
in confirmation of which we shall adduce some testimonies from the writings of Friends,
given forth at different periods.

George Fox, in a paper which he wrote, says:

"`Christ took upon him the seed of Abraham,
he does not say the corrupt seed of the Gentiles; so according to the flesh,
he was of the holy seed of Abraham and David;
and his holy body and blood was an offering and a
sacrifice for the sins of the whole world,
as a lamb without blemish, whose flesh saw no corruption.
By the one offering of himself, in the new testament or new covenant,
he has put an end to all the offerings and sacrifices among the Jews in the old testament.
Christ the holy Seed, was crucified, dead and buried, according to the flesh,
and raised again the third day, and his flesh saw no corruption.
Though he was crucified in the flesh, yet quickened again by the Spirit,
and is alive and lives forevermore,
and has all power in heaven and in earth given to him, and reigns over all,
and is the one Mediator between God and man, even the man Christ Jesus.`' Vol. II. p. 384.

In an essay entitled the royal law of God revived, he also says,

"`And further says the apostle in 1 John 1:1-2,`' '`We have an advocate with the Father,
Jesus Christ the righteous; and he is the propitiation for our sins,
and not for ours only, but for the sins of the whole world.`' Now mark,
this is a large word for all people to take notice of,
that Jesus Christ is the propitiation for the sins of the whole world.
Therefore every one of you in your own particulars, know this,
that Christ Jesus who is crowned with glory and honour, did taste death for every man;
mark, for every man; and whosoever denies this doctrine is an antichrist;
and preaches another, is a false preacher and seducer,
and brings people to trouble and loss from that which is right and their due,
in which is their satisfaction.
So these are universal things to all mankind,
whereby all mankind might come out of the earthly old Adam,
in the fall and transgression, to Him that has died for them all, and purchased them all,
and tasted death for all, and enlightens them all, and gave his grace to them all;
and he wills that all might be saved, and come to the knowledge of the truth of Christ,
who does this.
And whoever teaches another doctrine, brings people into sects and confusions,
to destroy one another, where they have not natural affections,
and will do that to another, which they would not have others do unto them,
who break the bonds thereby of civil commerce among mankind; and the religions, ways,
and worships of all such, are no worships, religions, nor ways to god,
but set up by a dark peevish spirit, by which they destroy one another,
which are God`'s creatures, about them: all which came from him who is out of the truth,
whom christ came to destroy.`" p. 19.

In his answer to all such as falsely say, the Quakers are no Christians,
he has this declaration:

"`We believe concerning God the Father, Son and Spirit,
according to the testimony of the Holy Scriptures,
which we receive and embrace as the most authentic
and perfect declaration of Christian faith,
being indited by the Holy Spirit of God, that never errs; 1st,
that there is one God and Father, of whom are all things; 2ndly,
that there is one Lord Jesus Christ, by whom all things were made, John i. and xvii.
Rom. ix.
who was glorified with the Father before the world began, who is God over all,
blessed forever, John xiv.
That there is one Holy Spirit, the promise of the Father and the Son,
and leader and sanctifier and comforter of his people, 1 John v. And we further believe,
as the Holy Scriptures soundly and sufficiently express, that these three are one,
even the Father, the Word and Spirit.`" p. 27.

"`Robert Barclay, in his Apology, says:

"`For the infinite and most wise God, who is the foundation,
root and spring of all operation, has wrought all things by his eternal Word and Son.
This is that Word that was in the beginning with God and was God,
by whom all things were, made, and without whom was not any thing made that was made.
This is that Jesus Christ, by whom God created all things,
by whom and for whom all things were created that are in heaven and in earth,
visible and invisible, whether they be thrones or dominions, or principalities or powers,
Col. 1:16, who therefore is called the First born of every creature,
ver. 15. As then that infinite and incomprehensible Fountain of life and
motion operates in the creatures by his own eternal word and power,
so no creature has access again unto him, but in and by the Son,
according to his own express words, no man knows the Father but the Son,
and he to whom the Son will reveal him. Matt. 11:27.
Luke 10:22. And again he himself says, I am the way,
the truth and the life; no man comes unto the Father but by me, John 14:6.
Hence he is fitly called the Mediator between God and man:
for having been with God from all eternity, being himself god,
and also in time partaking of the nature of man,
through him is the goodness and love of God conveyed to mankind,
and by him again man receives and partakes of these mercies.`"
Apology, p. 41.

William Penn,
in '`A Serious Apology for the Principles and Practices
of the Quakers,`' has this concise confession of Faith:

"`We do believe in one only Holy God Almighty, who is an eternal Spirit,
the Creator of all things.
And in one Lord Jesus Christ, his only Son and express image of his substance;
who took upon him flesh and was in the world, and in life, doctrine, miracles, death,
resurrection, ascension and mediation, perfectly did, and does continue to do,
the will of god; to whose holy life, power, mediation, and blood,
we only ascribe our sanctification, justification, redemption, and perfect salvation.
And we believe in one holy Spirit,
that proceeds and breathes from the Father and the Son,
as the life and virtue of both the Father and the Son;
a measure of which is given to all to profit with; and he that has one has all,
for these three are one, who is the Alpha and Omega, the first and the last,
God over all, blessed forever, amen.`"
Vol. II. p. 66.

In his '`Primitive Christianity revived,`' William Penn declares:

"`We do believe that Jesus Christ was our holy sacrifice, atonement and propitiation;
that he bore our iniquities,
and that by his stripes we were healed of the wounds Adam gave us in his fall;
and that God is just in forgiving true penitents upon the credit
of that holy offering Christ made of himself to God for us;
and that what he did and suffered, satisfied and pleased God,
and was for the sake of fallen man, that had displeased God:
and that through the offering up of himself once for all, through the Eternal Spirit,
he has forever perfected those (in all times) that were sanctified,
who walked not after the flesh but after the Spirit. Rom. 8:1.
Mark that.`"
Vol. II. p. 867.

Richard Claridge on justification says:

"`In a word, if justification be considered in its full and just latitude,
neither Christ`'s work without us, in the prepared body, nor his work within us,
by his Holy Spirit, are to be excluded;
for both have their place and service in our complete and absolute justification.
By the propitiatory sacrifice of Christ without us, we, truly repenting and believing,
are through the mercy of God,
justified from the imputations of sins and transgressions that are past,
as though they had never been committed; and by the mighty work of Christ within us,
the power, nature, and habits of sin are destroyed; that as sin once reigned unto death,
even so now grace reigns, through righteousness, unto eternal life,
by Jesus Christ our Lord.
And all this is effected, not by a bare or naked act of faith, separate from obedience,
but in the obedience of faith;
Christ being the author of eternal salvation to none but those that obey him.`" p. 79.

The Society of Friends published a declaration of its faith in the year 1693,
from which we extract the following:

We sincerely profess faith in God, by his only begotten Son Jesus Christ,
as being our light and life, our only way to the Father, and also our only Mediator,
and Advocate with the Father.
That God created all things, he made the worlds, by his Son Jesus Christ,
he being that powerful and living Word of God, by whom all things were made;
and that the Father, the Word and Holy Spirit are one, in divine being inseparable,
one true, living and eternal God, blessed forever.
Yet that this Word, or Son of God, in the fulness of time, took flesh,
became perfect man, according to the flesh,
descended and came of the seed of Abraham and David,
but was miraculously conceived by the Holy Spirit, and born of the Virgin Mary;
and also further declared powerfully to be the Son of God,
according to the spirit of sanctification by the resurrection from the dead.

That in the Word, or Son of God, was life, and the same life was the light of men;
and that he was that true light which enlightens every man coming into the world;
and therefore that men are to believe in the light,
that they may become the children of the light.
Hereby we believe in Christ the Son of God, as he is the light and life within us;
and wherein we must needs have sincere respect, and honour to, and belief in, Christ,
as in his own unapproachable and incomprehensible glory and fulness,
as he is the fountain of life and light and giver thereof unto us; Christ as in himself,
and as in us being not divided.

That as man, Christ died for our sins,
rose again and was received up into glory in the heavens; he having in his dying for all,
been that one great, universal offering and sacrifice for peace, atonement,
and reconciliation between God and man, and he is the propitiation,
not for our sins only, but for the sins of the whole word.
We were reconciled by his death, but saved by his life.

That Jesus Christ who sits at the right hand of the throne of the Majesty in the heavens,
yet he is our king, high priest and prophet in his church, a minister of the Sanctuary,
and of the true tabernacle which the Lord pitched, and not man.
He is intercessor and advocate with the Father in heaven,
and there appearing in the presence of God for us,
being touched with the feeling of our infirmities, sufferings and sorrows.
And also by his spirit in our hearts, he makes intercession according to the will of God,
crying Abba, Father.

That the Gospel of the grace of God should be preached in the name of the Father,
Son and Holy Spirit, being one in power, wisdom and goodness, and indivisible,
or not to be divided in the great work of man`'s salvation.

We sincerely confess and believe in Jesus Christ, both as he is true God,
and perfect man;
and that he is the author of our living faith in the power and goodness of God,
as manifested in his Son Jesus Christ,
and by his own blessed spirit or divine unction revealed in us,
whereby we inwardly feel and taste of his goodness, life and virtue;
so as our souls live and prosper by and in him;
and the inward sense of this divine power of Christ, and faith in the same,
and this inward experience, is absolutely necessary to make a true, sincere,
and perfect Christian in spirit and life.

That divine honour and worship is due to the Son of God;
and that he is in true faith to be prayed unto, and the name of the Lord Jesus Christ,
called upon, as the primitive Christians did,
because of the glorious union or oneness of the Father and the Son;
and that we cannot acceptably offer up prayers and praises to God,
nor receive a gracious answer, or blessing from God,
but in and through his dear Son Christ.
See Sewel`'s History, p. 499.

Besides the palpable errors we have enumerated,
Elias Hicks and his adherents deny that mankind sustain
any loss through the fall of Adam,^
footnote:[See Quaker 1 vol. p. 183. and Phil. Ser. p. 66.]
asserting that children come into the world precisely in the condition he did.^
footnote:[Phil. Ser. p. 163, 166, 257, 258.]
They also deny the existence of any evil spirit by which man is tempted,
distinct from his own propensities.
"`Heaven,`" they say, "`is a state, and not a place by any means.`"^
footnote:[New York Ser. p. 93.]
"`Belief,`" with them, "`is no virtue, and unbelief no crime:`"^
footnote:[Quaker 1 vol. 146.]
and however at times they may make high pretensions to the divine light,
it is evident that the guide which they follow is their own benighted reason.

Elias hicks says, "`in those things which relate to our moral conduct,
we all have understandings alike, as reasonable beings;
and we know when we do wrong to our fellow creatures;
we know it by our rational understanding--we need
no other inspiration than reason and justice.`"
Again: "`If we transgress against God, or even against our fellow creatures,
the act has its adequate reward,
and it will make us sorry for what we have done--that is we shall be losers by it,
and gain nothing, for no man shall gain by doing evil.`"
"`He +++[+++the Almighty]
has set good and evil before us, and left us to elect for ourselves.`"
Quaker, vol.
II. p. 2.58. 9.

As regards morality, they need no other revelation than reason and justice,
and when we transgress against God, the act will make us sorry for what we have done,
that is we shall be losers, and gain nothing.
While they speak much of the necessity of divine revelation,
reason is held up as the "`balancing and comparing
principle,`" by which we are to test those revelations,
and decide whether they are '`imprudent,`' or '`counterfeit.`"^
footnote:[New York and Phil.
Ser. p. 90, 13, 208.]
A simple and child-like reliance upon that faith which is
of the operation of the Holy Spirit of God is thus disregarded,
and the proud reason of man exalted into the seat of judgment.
We need not therefore be surprised at the unsound opinions which they entertain,
the contemptuous manner in which they treat the inspirations of the Holy Spirit,
contained in the Scriptures of Truth,
and the very irreverent and unworthy sentiments respecting
the blessed Saviour and Redeemer of men,
with which their discourses and writings abound, as if it were a chief object,
to decry the Holy Scriptures, and to degrade the Lord of life and glory.

The contrast between the Christian principles of our religious Society,
and those held by the Separatists,
who have adopted the anti-scriptural sentiments of Elias Hicks,
must be strikingly obvious to every unprejudiced mind.
The sorrowful effects of these principles in deranging the order and subordination
necessary to the well-being of our religious Society,
the disunity and discord produced by them in meetings and in families,
have been very fully developed in the last five years,
not only within the limits of this Yearly Meeting, but also in many other parts.
We believe it right to bear our decided testimony against such principles,
as tending to destroy all faith in the fundamental doctrines of the Christian religion,
and to break asunder the bands of civil and religious society.
And we further declare, that as such who entertain and propagate them,
have departed from the teachings of the Holy Spirit,
which would have preserved them in the doctrines of Christ Jesus and his apostles,
we cannot unite with them in church fellowship, nor own them to be of our communion;
neither can we correspond with any meetings or associations, holding those principles,
and set up in violation of the excellent order,
which has been instituted among us in the unfoldings of Divine wisdom.
While we believe it to be a religious duty,
thus to stand forth in the defence of the Gospel of Christ,
against the spirit and principles of libertinism and infidelity, we have no doubt,
that many who have joined in the present schism, have been led into it,
by the influence of misrepresentation and unfounded prejudice against their brethren,
and without a full knowledge of the principles of their leaders.
For such as these, we feel deep regret and tender solicitude:
and it is our fervent desire for them,
and for all others who have departed from the right way of the Lord,
that he may be pleased to renew the visitations of his love and light to their souls,
and in his own time, gather them to the fold of Christ`'s sheep,
where they may go in and out, and find pasture.

=== A Testimony from Tottenham Monthly Meeting, concerning Thomas Shillitoe.

This our dear friend was born in London in the second month, 1754,
of parents not in profession with Friends.
In his youthful days, through the visitations of Divine grace,
he was given to feel the importance of a religious life; but,
at that very critical period, he was often exposed to great temptations,
and in the way of associating with those who did not fear God, but slighted his holy law,
and went in the way to do evil.
He felt the sad consequences of this; but a hand unseen was near to protect him:
the attractions of heavenly love were graciously afforded, and were not disregarded.

It appears that, as he advanced towards manhood, he became, from preference,
a frequent attendant of our religious meetings,
though he had been brought up in the national mode of worship.
He was then entirely dependent on his own industry for support; and,
as his attachment to the principles of our religious Society increased, he was,
in consequence of his conscientious conduct,
brought into difficulty as to the means of gaining a livelihood.
This circumstance became known to some Friends in London,
through whose kind interest in his behalf he was
placed as a clerk in a banking-house in the city.
He felt the great importance of a life of self-denial,
and of entire conformity to the Divine will;
yet he was often sensible that he had strong temptations
to follow the vanities and follies of the world.
He had a great fondness for gay apparel,
and felt that his peace was concerned in mortifying this disposition;
and he faithfully bore his cross in this as well as in other things.
In the course of his services as banker`'s clerk,
he had to purchase lottery tickets for country correspondents,
and to do some other things which troubled him.
Hence, as he was a man of a tender conscience, he became uneasy in his new situation:
he sought for Divine guidance, and, after many conflicts of mind, gave up his place,
and thought it his duty to learn the trade of a shoemaker,
an employment which he followed as long as he continued in business.

The confinement of London not suiting his health,
he removed to Tottenham in the year 1778,
having sometime previously been admitted as a member of
our religious Society by Gracechurch-street Monthly Meeting.
Here he steadily followed his new line of employment,
and in the ensuing spring formed a respectable connection in marriage.
His course and that of his wife were marked by honest industry,
and contentment with their lot;
and they trained up a young family consistently with their circumstances,
and in accordance with our religious profession, teaching them to fear God,
and keep his commandments.

In the year 1790, our dear friend was acknowledged a minister of this Monthly Meeting,
having for a considerable time previously spoken
in that character in our meetings for worship.
After this period, he left his outward concerns from time to time,
and in Gospel love visited his friends in nearer and more distant counties,
and paid a general visit to Friends in Ireland.
The cares of a rising family pressing heavily upon him,
he felt these sacrifices to be acts of simple faith; but,
believing them to be in the line of his religious duty,
he allowed no inferior considerations to turn him aside.
When from home, he pursued the service with great diligence:
his visits were acceptable to his friends, and we believe to their religious edification.
He was accustomed to travel in a very simple way,
and very careful not to occasion needless expense to himself or to his friends;
and in order to set himself at liberty for these services,
he often made great exertions in his business previous to leaving home.
When, in the latter part of the time that he was in trade,
he found that he could leave his outward concerns with less anxiety,
the journeys were performed principally on foot.

About the year 1806, thinking that, through the Divine blessing on his honest endeavours,
he had gained a competency, he retired from business,
believing it right to be given up to the service of his Lord.
His means were limited, but, as his needs were few,
and his habits very simple and moderate, he found that he had a sufficiency.

Our dear friend was a man of energetic mind.
If in conscientiously and plainly setting before his friends,
in his conversation with them, what he believed to be their mistakes,
whether in practice or in opinion;
and if in an honest zeal to be found not flinching in the discharge of his duty,
he at times tried them,
his love and affection were such as to prove the sincerity of his heart,
and the kindness of his intentions.
He was often brought very low, partly arising from nervous feelings,
and partly from the religious exercises of mind which he passed through:
he was also not unfrequently very cheerful.
This was strikingly the case after the performance of any
act of duty to which he had believed himself called.
In these acts of dedication, he was faithful and persevering,
however humiliating the nature of the engagement.
The greater the cross to his natural inclination,
the greater was his fear lest self-love, or the desire of ease to the flesh,
should cause him to shrink from what he believed to be the will of his God.
An instructive illustration of this feature in his character is
presented in some very trying service which he performed in Ireland.
In the populous cities of Dublin and Cork,
as well as in some other places in that nation, where vice and immorality abound,
he went, in the years 1810 and 1811, accompanied by some of his friends,
from house to house, without distinction, where ardent spirits were offered for sale,
to warn those who kept such shops, and the persons assembled there,
of the evil of their doings.
The message which he conveyed was short and plain and simple; but,
being delivered in Christian love, it was received by many with attention and respect.

He was remarkable, through a long course of years,
for his kindness to the poor and distressed, sympathizing with them in their troubles,
pleading for a just remuneration of their labours,
and liberal to them according to his means;
prompt and unwearied in soliciting the affluent for relief for such,
especially exerting himself on behalf of those who had seen brighter days.
In these labours of love, his disinterested applications seldom failed to be successful.
He bore a faithful testimony against the love of the world,
whether it showed itself in vanity in dress, or in other extravagance,
or in the eager pursuit of wealth,
calling his friends to the necessity of daily bearing the cross in all things,
warning them against speculations in trade, and urging them to take heed lest,
by coveting riches, they should make shipwreck of faith and a good conscience.

With a view of being near his children, he left Tottenham in the year 1812,
and lived some years in Yorkshire, and a longer time in Hertfordshire.
We have received the following communication from Hinchin Monthly Meeting,
within the compass of which meeting he resided, when at home, upwards of eleven years.

"`Although our late friend Thomas Shillitoe was a
member of this Monthly Meeting for some years,
yet, as is well known,
for a considerable portion of that time he was absent
from us on important religious engagements,
for which services he was at different times freely set at liberty by this Monthly Meeting,
under feelings of sympathy,
and with desires that throughout the same he might
mercifully experience Divine guidance and protection.
While here, he possessed the esteem of Friends; and, in some instances,
rather remarkably so, that of several persons of other religious societies,
who seemed to respect him for his faithfulness.
He was frequent in visiting the sick, and sympathizing with the afflicted,
evincing much concern for the everlasting welfare of those among whom he resided.
The moral and religious improvement of the poor was
also a subject that often occupied his attention.
He was frequently engaged among us in a plain, searching testimony,
tending to arouse from a state of indifference and unconcernedness in religion,
and to stir up all to diligence in occupying with
the different talents entrusted to their care.
His watchfulness and circumspect conduct had, it is believed,
a salutary influence among us, and, when he left these parts,
his removal was sincerely regretted.`"

During the period above alluded to,
our dear friend paid two extensive religious visits on the continent, passing through,
or tarrying in, many of the nations of Europe, between the years 1821 and 1825.
In the course of those engagements,
he visited the few professing with Friends in the south of France and in Germany,
also in Norway;
and he sought out and visited pious characters in many places through which he travelled.
Accounts have been received from several of those,
of the comfort and instruction derived from his Christian labours among them.
He travelled mostly alone, and,
being wholly unacquainted with the languages of the people,
it was a close trial of his faith.
But, keeping a single eye to the guidance of his gracious Lord,
he was mercifully cared for from place to place:
his way was in a remarkable manner opened by unexpectedly meeting with kind,
efficient interpreters,
who assisted him in performing the service which he believed to be required of him.
He had long entertained a high sense of the purity
of morals which the Gospel of Christ requires:
in his travels he found much that was opposed to this, and did not fail,
on some such occasions, honestly to testify against it.
One thing which greatly troubled him, was the sad disregard of the first-day of the week;
he plainly set this evil before those who had the power to apply a remedy.
When in the cities of Hamburg and Altona,
he drew up an address to the inhabitants of those places,
remonstrating with them on the neglect of this duty.
This address was translated into the German language,
and extensively distributed by him there with his own hand.

Though our departed friend had received but little education, his courteous and affable,
yet respectful manners, often facilitated his access to persons of high rank in society.
Considering kings in the character of fathers of their people, he many times,
both in this and in foreign countries,
thought it his duty to seek for interviews with them.
As he patiently looked unto the Lord, in simple dependence upon him,
an opportunity was often afforded him to communicate what was upon his mind.
Either verbally, or by written memorials,
he conveyed his exercise for their eternal welfare,
and that they might be good examples to their subjects;
and also his concern for their adopting measures calculated to repress crime,
and to promote Christian virtue, and the true happiness of their people.

In the year, 1826, at the advanced age of seventy-two,
he paid a religious visit to Friends in America,
and travelled among them about three years.
It was a time of much unsettlement and sore trial to faithful Friends,
owing to a grievous disesteem, on the part of many,
of the great truths of the Christian religion.
It appears by the testimonials which have been received,
that the company of our dear friend was acceptable
to his brethren in America at that time,
and that his solid, consistent deportment,
and steady testimony against the spirit of unbelief,
tended to their encouragement and strength.

After returning home he lived the rest of his days at Tottenham with his wife,
who had been, and continued to be, a faithful help-mate to him,
and who still survives him.
He felt the infirmities of declining years.
Of later times, his bodily sufferings were often considerable; but,
living near the meeting-house, he regularly attended all our meetings,
continuing earnestly to exhort us to let our obedience to
the law of God keep pace with the knowledge of its requirements;
labouring with us on the necessity of pressing after holiness of life,
and a thorough surrender of our wills to the Divine will.
He still endeavoured to do good and to communicate.
He was much beloved and respected by his neighbours.

One of the very last acts of his life, when his weakness had greatly increased,
and disease was wasting his constitution,
was to collect and assist in expending some money
for the comfort of a few of his poorer neighbours,
by the repair and improvement of some almshouses.

He was continually concerned that he might be found ready to meet his Lord,
when the solemn messenger of death should arrive,
often adverting to the necessity of watchfulness, lest having long professed the Truth,
he should in the end become a castaway.
In the retrospect of his lengthened but active life,
he was very desirous that his friends should know that he
trusted in nothing but the free mercy of God in Christ Jesus,
repeatedly assuring them that all his own righteousness was but as filthy rags.

On the 5th of the sixth month, 1836, he was taken more alarmingly ill.
Early in the morning of the following day he became much worse from increased debility;
and, his breathing being difficult, he said, "`It is labour, but not sorrow.
O! deliver me, if consistent with your blessed will.
I am in the hands of a merciful God--take me.
I can give up all in this world.
Mercy!
Mercy.
O! come, come, blessed Jesus, if it is consistent with your blessed will.`"
In the course of the evening of that day he was visited by a Friend,
who found him in extreme weakness, but in the possession of his mental powers.

He observed that it was difficult to maintain patience.`"
"`O! for patience!`" he exclaimed;
"`O! for a little help to be preserved in patience;`" adding,
after some further expression,
"`but surely mercy is even now covering the judgment seat as to a hair`'s breadth.`"
A hope was expressed to him that, although the body was brought very low,
the mind was anchored on the unfailing Rock; he promptly replied "`O, yes.
If it were not so, what should I now do, or what would now become of me?
Ah! truly, I am a poor creature every way, wholly dependent on the mercy of my Redeemer;
and if he do but admit the pearl gates to be so far
opened that I may be admitted within them,
it will be enough.
O! I see the goodly land before me, and the glorious journey there;
but I am not yet permitted to enter it.
It is indeed a beautiful prospect,
as clear to the eye of my soul as any outward object to the natural sight.`"
He then exclaimed, "`O! the love of my Redeemer, how sweet it is.
May my latest breath be engaged in singing his praises.`"
He further observed,
that he had no works or merit of his own to carry with him on that beautiful road,
nor any claim to prefer at the pearl gates,
but the love and mercy of that Saviour who shed his precious blood for him.

On the Friends`' taking leave of him,
he expressed that he felt love to all his friends without exception, emphatically adding,
"`to all my friends.`"
At another time, on receiving a message of love from two Friends,
he said his love was to every body, all the world over, even the worst sinner.
He loved them; but not their deeds--that his love was universal to all the human race;
adding, "`If it were not so, how miserable should I feel!`"

He quietly passed away from time to eternity on the 12th of the sixth month, 1836,
and his remains were interred in our burial ground at Tottenham, on the 17th of the same.
He was about eight-two years old, and had been a minister upwards of fifty years;
and we believe that to this aged servant of God may be applied the words of Holy Scripture:
"`Blessed are the dead which die in the Lord from henceforth; yes, says the Spirit,
that they may rest from their labours, and their works do follow them.

London and Middlesex Quarterly Meeting, held the 28th day of third month, 1837.

The foregoing testimony on behalf of our late dear friend Thomas Shillitoe,
has been read in this meeting, and is feelingly united with.

Signed by direction and on behalf of the meeting, by

George Stacey, Clerk.

Signed on behalf of the Women`'s Quarterly Meeting, by

Elizabeth Kidd, Clerk.
