== Appendix A.

[.chapter-subtitle--blurb]
Thomas Shillitoe`'s Testimony Against the Writings of Joseph John Gurney

As has been sadly portrayed by the events narrated in this journal,
the massive disruption brought about by Elias Hicks and
his followers among the Society of Friends in America,
terminated in the first great schism that Quakers
had experienced since the commencement of their society.
Hicks spoke much of an "`inner light,`" and alleged his
teachings to be in agreement with early Quaker principles,
but they were in fact very much at odds with the long-established
beliefs of the Society (and Christianity in general),
and were rejected and disavowed by the prudent and faithful.
His eloquent sermons exalted a sort of spiritual religion,
speaking much of love for neighbors, abolition of slavery,
and other right-sounding concepts,
but he led his followers into a disregard for the Scriptures,
and a total denial of several fundamentals of Christianity--such as the incarnation,
virgin birth, and divinity of Christ, His role as mediator, the atonement by the cross,
the existence of Satan, etc.
He taught that Jesus Christ was nothing more than a good man who,
having followed the light of God, was endowed with a divine Spirit and power,
often saying things like,
"`The same power that made Christ a Christian must make us Christians;
and the same power that saved him must save us.`"

Perhaps in an attempt to distance themselves from these errors,
and to avoid the false light preached by Hicksites,
Quakers in England soon began to pull away from some of
the original principles and practices of early Friends,
especially those having to do with an entire dependence
upon the immediate influence of God`'s Spirit for true worship,
ministry, and spiritual understanding.
Greatly influenced by the preaching and writings of Joseph John Gurney (in the
1820`'s-1840`'s) many who had not been seduced by Hicksism began to conform more
and more to a traditional and formal Protestant Christianity that did not rightly
understand or emphasize the revelation and formation of Christ within,
or the spiritual nature of New Covenant worship and ministry.
Over the next several decades,
these "`Gurneyites`" progressively departed from many of the precious truths that God
had restored to His church at the bright commencement of the Society of Friends,
and sadly, by the end of the 1800`'s,
the remainder of the Society of Friends was but a small and degenerate body,
the religion of the two largest camps (Hicksites and Gurneyites) bearing little resemblance
to the blessed Truth as professed and upheld by their worthy predecessors.

Not many days before his death, Thomas Shillitoe had been able,
in great debility of body,
to attend only a small portion of the Yearly Meeting in London; perhaps the last sitting,
and one sitting of the Select Meeting.
And three days before his decease, his neighbor John Hodgkin coming into his room,
he requested him to take down in writing the following testimony of his dying sentiments,
in regard to what he considered to be "`the Episcopalian tenets`" of Joseph John Gurney.

[.offset]
Addressing John Hodgkin, he said:

[.embedded-content-document.testimony]
--

You will need a great deal of time and patience to hear what I have got to say,
and it must be faithfully delivered, for I am afraid, at a future day,
it will devolve heavy upon your shoulders.
It is extraordinary that you should have come in at this juncture,
for I have been wanting my son-in-law to come in,
and put down what I am now better satisfied should be received by you from my mouth.

And I therefore declare, unequivocally,
against the generality of the writings of Joseph John Gurney,
as being non-Quaker principles, not sound Quaker principles, but Episcopalian ones;
and they have done great mischief in our Society; and the Society will go gradually down,
if it yields to the further circulation of that part of
his works which they have in their power to suppress.
This is my firm belief.
I have labored under the weight of it for the last twelve months,
beyond what human nature is able to support.
And the committee of the Morning Meeting which passed that
last work +++[+++Gurney`'s '`Peculiarities`' with a new title],
must be willing to come forward, to be sufficiently humble to acknowledge their error.
And the Meeting for Sufferings must also be willing to remove its authority
in allowing it to be given away to those not of our Society.

I declare the author is an Episcopalian, not a Quaker.
I apprehend J. J. Gurney is no Quaker in principle.
Episcopalian views were imbibed from his education, and still remain with him.
I love the man, for the work`'s sake, so far as it goes;
but he has never been emptied from vessel to vessel, and from sieve to sieve,
nor known the baptism of the Holy Spirit and of fire,
to cleanse the floor of his heart from his Episcopalian notions.
He has spread a linsey-woolsey garment over our members;
but in a future day it will be stripped off; it will be too short for them,
as they will be without Jesus Christ the Lord.
This is my dying testimony, and I must sign it.
If I had been faithful,
I should have expressed it in the last Yearly Meeting of Ministers and Elders;
but I hope I shall be forgiven.
O Lord! accept me with the best I have!
I have letters from America,
which confirm me in the truth of every part of what I now state.
I believe there is not an individual member of our Society, in England, Scotland,
or Ireland, more willing to do good, than J. J. Gurney.
But willingness is no qualification.
This is my dying testimony to Quaker views, especially as to the ministry.
What was antichrist in George Fox`'s days, is antichrist now.
The clergy of this country, to a man, every one of them,
are antichrist so long as they wear the gowns and receive the pay,
and continue building up the people in the relics of Popery,
which the church of England retained.
It will not do to speak of a man doing a great deal for a little pay,
and call him a minister of Christ.
It is a grievous thing, that any minister in our Society should so speak.
They are antichrist still, since they lead the people from Christ.
And yet I love some of them for the work`'s sake, so far as they go.

--
