[short="A Testimony from Tottenham Monthly Meeting"]
== A Testimony from Tottenham Monthly Meeting, concerning Thomas Shillitoe

This our dear friend was born in London in the second month, 1754,
of parents not in profession with Friends.
In his youthful days, through the visitations of Divine grace,
he was given to feel the importance of a religious life; but,
at that very critical period, he was often exposed to great temptations,
and in the way of associating with those who did not fear God, but slighted his holy law,
and went in the way to do evil.
He felt the sad consequences of this; but a hand unseen was near to protect him:
the attractions of heavenly love were graciously afforded, and were not disregarded.

It appears that, as he advanced towards manhood, he became, from preference,
a frequent attendant of our religious meetings,
though he had been brought up in the national mode of worship.
He was then entirely dependent on his own industry for support; and,
as his attachment to the principles of our religious Society increased, he was,
in consequence of his conscientious conduct,
brought into difficulty as to the means of gaining a livelihood.
This circumstance became known to some Friends in London,
through whose kind interest in his behalf he was
placed as a clerk in a banking-house in the city.
He felt the great importance of a life of self-denial,
and of entire conformity to the Divine will;
yet he was often sensible that he had strong temptations
to follow the vanities and follies of the world.
He had a great fondness for gay apparel,
and felt that his peace was concerned in mortifying this disposition;
and he faithfully bore his cross in this as well as in other things.
In the course of his services as banker`'s clerk,
he had to purchase lottery tickets for country correspondents,
and to do some other things which troubled him.
Hence, as he was a man of a tender conscience, he became uneasy in his new situation:
he sought for Divine guidance, and, after many conflicts of mind, gave up his place,
and thought it his duty to learn the trade of a shoemaker,
an employment which he followed as long as he continued in business.

The confinement of London not suiting his health,
he removed to Tottenham in the year 1778,
having sometime previously been admitted as a member of
our religious Society by Gracechurch-street Monthly Meeting.
Here he steadily followed his new line of employment,
and in the ensuing spring formed a respectable connection in marriage.
His course and that of his wife were marked by honest industry,
and contentment with their lot;
and they trained up a young family consistently with their circumstances,
and in accordance with our religious profession, teaching them to fear God,
and keep his commandments.

In the year 1790, our dear friend was acknowledged a minister of this Monthly Meeting,
having for a considerable time previously spoken
in that character in our meetings for worship.
After this period, he left his outward concerns from time to time,
and in Gospel love visited his friends in nearer and more distant counties,
and paid a general visit to Friends in Ireland.
The cares of a rising family pressing heavily upon him,
he felt these sacrifices to be acts of simple faith; but,
believing them to be in the line of his religious duty,
he allowed no inferior considerations to turn him aside.
When from home, he pursued the service with great diligence:
his visits were acceptable to his friends, and we believe to their religious edification.
He was accustomed to travel in a very simple way,
and very careful not to occasion needless expense to himself or to his friends;
and in order to set himself at liberty for these services,
he often made great exertions in his business previous to leaving home.
When, in the latter part of the time that he was in trade,
he found that he could leave his outward concerns with less anxiety,
the journeys were performed principally on foot.

About the year 1806, thinking that, through the Divine blessing on his honest endeavours,
he had gained a competency, he retired from business,
believing it right to be given up to the service of his Lord.
His means were limited, but, as his needs were few,
and his habits very simple and moderate, he found that he had a sufficiency.

Our dear friend was a man of energetic mind.
If in conscientiously and plainly setting before his friends,
in his conversation with them, what he believed to be their mistakes,
whether in practice or in opinion;
and if in an honest zeal to be found not flinching in the discharge of his duty,
he at times tried them,
his love and affection were such as to prove the sincerity of his heart,
and the kindness of his intentions.
He was often brought very low, partly arising from nervous feelings,
and partly from the religious exercises of mind which he passed through:
he was also not unfrequently very cheerful.
This was strikingly the case after the performance of any
act of duty to which he had believed himself called.
In these acts of dedication, he was faithful and persevering,
however humiliating the nature of the engagement.
The greater the cross to his natural inclination,
the greater was his fear lest self-love, or the desire of ease to the flesh,
should cause him to shrink from what he believed to be the will of his God.
An instructive illustration of this feature in his character is
presented in some very trying service which he performed in Ireland.
In the populous cities of Dublin and Cork,
as well as in some other places in that nation, where vice and immorality abound,
he went, in the years 1810 and 1811, accompanied by some of his friends,
from house to house, without distinction, where ardent spirits were offered for sale,
to warn those who kept such shops, and the persons assembled there,
of the evil of their doings.
The message which he conveyed was short and plain and simple; but,
being delivered in Christian love, it was received by many with attention and respect.

He was remarkable, through a long course of years,
for his kindness to the poor and distressed, sympathizing with them in their troubles,
pleading for a just remuneration of their labours,
and liberal to them according to his means;
prompt and unwearied in soliciting the affluent for relief for such,
especially exerting himself on behalf of those who had seen brighter days.
In these labours of love, his disinterested applications seldom failed to be successful.
He bore a faithful testimony against the love of the world,
whether it showed itself in vanity in dress, or in other extravagance,
or in the eager pursuit of wealth,
calling his friends to the necessity of daily bearing the cross in all things,
warning them against speculations in trade, and urging them to take heed lest,
by coveting riches, they should make shipwreck of faith and a good conscience.

With a view of being near his children, he left Tottenham in the year 1812,
and lived some years in Yorkshire, and a longer time in Hertfordshire.
We have received the following communication from Hinchin Monthly Meeting,
within the compass of which meeting he resided, when at home, upwards of eleven years.

[.embedded-content-document.testimony]
--

Although our late friend Thomas Shillitoe was a
member of this Monthly Meeting for some years,
yet, as is well known,
for a considerable portion of that time he was absent
from us on important religious engagements,
for which services he was at different times freely set at liberty by this Monthly Meeting,
under feelings of sympathy,
and with desires that throughout the same he might
mercifully experience Divine guidance and protection.
While here, he possessed the esteem of Friends; and, in some instances,
rather remarkably so, that of several persons of other religious societies,
who seemed to respect him for his faithfulness.
He was frequent in visiting the sick, and sympathizing with the afflicted,
evincing much concern for the everlasting welfare of those among whom he resided.
The moral and religious improvement of the poor was
also a subject that often occupied his attention.
He was frequently engaged among us in a plain, searching testimony,
tending to arouse from a state of indifference and unconcernedness in religion,
and to stir up all to diligence in occupying with
the different talents entrusted to their care.
His watchfulness and circumspect conduct had, it is believed,
a salutary influence among us, and, when he left these parts,
his removal was sincerely regretted.

--

During the period above alluded to,
our dear friend paid two extensive religious visits on the continent, passing through,
or tarrying in, many of the nations of Europe, between the years 1821 and 1825.
In the course of those engagements,
he visited the few professing with Friends in the south of France and in Germany,
also in Norway;
and he sought out and visited pious characters in many places through which he travelled.
Accounts have been received from several of those,
of the comfort and instruction derived from his Christian labours among them.
He travelled mostly alone, and,
being wholly unacquainted with the languages of the people,
it was a close trial of his faith.
But, keeping a single eye to the guidance of his gracious Lord,
he was mercifully cared for from place to place:
his way was in a remarkable manner opened by unexpectedly meeting with kind,
efficient interpreters,
who assisted him in performing the service which he believed to be required of him.
He had long entertained a high sense of the purity
of morals which the Gospel of Christ requires:
in his travels he found much that was opposed to this, and did not fail,
on some such occasions, honestly to testify against it.
One thing which greatly troubled him, was the sad disregard of the first-day of the week;
he plainly set this evil before those who had the power to apply a remedy.
When in the cities of Hamburg and Altona,
he drew up an address to the inhabitants of those places,
remonstrating with them on the neglect of this duty.
This address was translated into the German language,
and extensively distributed by him there with his own hand.

Though our departed friend had received but little education, his courteous and affable,
yet respectful manners, often facilitated his access to persons of high rank in society.
Considering kings in the character of fathers of their people, he many times,
both in this and in foreign countries,
thought it his duty to seek for interviews with them.
As he patiently looked unto the Lord, in simple dependence upon him,
an opportunity was often afforded him to communicate what was upon his mind.
Either verbally, or by written memorials,
he conveyed his exercise for their eternal welfare,
and that they might be good examples to their subjects;
and also his concern for their adopting measures calculated to repress crime,
and to promote Christian virtue, and the true happiness of their people.

In the year, 1826, at the advanced age of seventy-two,
he paid a religious visit to Friends in America,
and travelled among them about three years.
It was a time of much unsettlement and sore trial to faithful Friends,
owing to a grievous disesteem, on the part of many,
of the great truths of the Christian religion.
It appears by the testimonials which have been received,
that the company of our dear friend was acceptable
to his brethren in America at that time,
and that his solid, consistent deportment,
and steady testimony against the spirit of unbelief,
tended to their encouragement and strength.

After returning home he lived the rest of his days at Tottenham with his wife,
who had been, and continued to be, a faithful help-mate to him,
and who still survives him.
He felt the infirmities of declining years.
Of later times, his bodily sufferings were often considerable; but,
living near the meetinghouse, he regularly attended all our meetings,
continuing earnestly to exhort us to let our obedience to
the law of God keep pace with the knowledge of its requirements;
labouring with us on the necessity of pressing after holiness of life,
and a thorough surrender of our wills to the Divine will.
He still endeavoured to do good and to communicate.
He was much beloved and respected by his neighbours.

One of the very last acts of his life, when his weakness had greatly increased,
and disease was wasting his constitution,
was to collect and assist in expending some money
for the comfort of a few of his poorer neighbours,
by the repair and improvement of some almshouses.

He was continually concerned that he might be found ready to meet his Lord,
when the solemn messenger of death should arrive,
often adverting to the necessity of watchfulness, lest having long professed the Truth,
he should in the end become a castaway.
In the retrospect of his lengthened but active life,
he was very desirous that his friends should know that he
trusted in nothing but the free mercy of God in Christ Jesus,
repeatedly assuring them that all his own righteousness was but as filthy rags.

On the 5th of the sixth month, 1836, he was taken more alarmingly ill.
Early in the morning of the following day he became much worse from increased debility;
and, his breathing being difficult, he said, "`It is labour, but not sorrow.
O! deliver me, if consistent with your blessed will.
I am in the hands of a merciful God--take me.
I can give up all in this world.
Mercy!
Mercy.
O! come, come, blessed Jesus, if it is consistent with your blessed will.`"
In the course of the evening of that day he was visited by a Friend,
who found him in extreme weakness, but in the possession of his mental powers.

He observed that it was difficult to maintain patience.`"
"`O! for patience!`" he exclaimed;
"`O! for a little help to be preserved in patience;`" adding,
after some further expression,
"`but surely mercy is even now covering the judgment seat as to a hair`'s breadth.`"
A hope was expressed to him that, although the body was brought very low,
the mind was anchored on the unfailing Rock; he promptly replied "`O, yes.
If it were not so, what should I now do, or what would now become of me?
Ah! truly, I am a poor creature every way, wholly dependent on the mercy of my Redeemer;
and if he do but admit the pearl gates to be so far
opened that I may be admitted within them,
it will be enough.
O! I see the goodly land before me, and the glorious journey there;
but I am not yet permitted to enter it.
It is indeed a beautiful prospect,
as clear to the eye of my soul as any outward object to the natural sight.`"
He then exclaimed, "`O! the love of my Redeemer, how sweet it is.
May my latest breath be engaged in singing his praises.`"
He further observed,
that he had no works or merit of his own to carry with him on that beautiful road,
nor any claim to prefer at the pearl gates,
but the love and mercy of that Saviour who shed his precious blood for him.

On the Friends`' taking leave of him,
he expressed that he felt love to all his friends without exception, emphatically adding,
"`to all my friends.`"
At another time, on receiving a message of love from two Friends,
he said his love was to every body, all the world over, even the worst sinner.
He loved them; but not their deeds--that his love was universal to all the human race;
adding, "`If it were not so, how miserable should I feel!`"

He quietly passed away from time to eternity on the 12th of the sixth month, 1836,
and his remains were interred in our burial ground at Tottenham, on the 17th of the same.
He was about eight-two years old, and had been a minister upwards of fifty years;
and we believe that to this aged servant of God may be applied the words of Holy Scripture:
"`Blessed are the dead which die in the Lord from henceforth; yes, says the Spirit,
that they may rest from their labours, and their works do follow them.`"

[.signed-section-closing]
London and Middlesex Quarterly Meeting, held the 28th day of third month, 1837.

The foregoing testimony on behalf of our late dear friend Thomas Shillitoe,
has been read in this meeting, and is feelingly united with.

[.signed-section-closing]
Signed by direction and on behalf of the meeting, by

[.signed-section-signature]
George Stacey, Clerk.

[.signed-section-closing]
Signed on behalf of the Women`'s Quarterly Meeting, by

[.signed-section-signature]
Elizabeth Kidd, Clerk.
