== Chapter 3

1805+++.+++ My exercises now put on a different appearance to what they had heretofore done,
from an apprehension which at times presented to my mind,
that the time was fast approaching,
when I must be willing to relinquish a good business
which I had been helped to get together,
and set myself more at liberty to attend to my religious duties from home.
The language which my Divine Master renewedly proclaimed in the ear of my soul,
was "`Gather up thy wares into thine house,
for I have need of the residue of thy days;`" accompanied by an assurance,
that although there was, as some would consider, but little meal in the barrel,
and little oil in the cruse, of temporal property,
not having realised more than a bare hundred pounds a year,
and all my five children to settle in the world,
yet if I was faithful in giving up to this and every future requiring of my great Creator,
the meal and oil should not waste.
I endeavoured to weigh this requisition,
and well knew that the meal and oil he had thus condescended to give,
would be amply sufficient for me and my dear wife, should we be permitted to see old age,
provided we continued to pursue our economical habits,
and that I must leave the provision for my children`'s settling in life
to that same Almighty Power who had so abundantly cared for us;
yet the prospect of relinquishing a good business,
was at times a close trial of my faith.
The requiring, however, pressed upon me with increasing weight, accompanied with a fear,
that if I did not endeavour after a cheerful resignation of myself and my all,
to his disposal, even this would be blasted again,
without power on my part to prevent it.
As I thought prudence pointed out the necessity of not acting with precipitancy,
and that it would be well to take the counsel of some suitable Friends,
I earnestly besought the Lord to direct my attention towards
such as would be likely wisely to counsel me herein;
and believing my secret petitions were in mercy heard,
and that two Friends of our Monthly Meeting were pointed out to me as suitable,
I opened my situation to them; and they gave it as their judgment,
if my mind should continue to be exercised with this apprehension of duty,
it would be best for me to yield to it.

About the fifth month this year, I turned my business over to a Friend;
and shortly after making this sacrifice,
a person added to my store by will one hundred pounds,
which I received as a mark of the merciful interference of my heavenly Benefactor.

In the winter of this year an individual,
who had been a member of the Society within the compass of Berkshire Quarterly Meeting,
served me with a subpoena to attend at Guildhall, London,
in a suit he had commenced against two Friends,
who had the charge of the door of the Quarterly Meeting of London and Middlesex,
in consequence of their preventing his entering that meeting.
It appeared by his suit,
that he was aiming to have our meetings for discipline
left open to all who chose to attend them,
hoping to prove them to be meetings for Divine worship;
and that he built his hopes of gaining his cause on my examination,
from some remarks I made in that Quarterly Meeting.
The morning of the trial was such a one to me as I have not often known.
The court being opened, and the usual ceremonies gone through,
the judge was informed that the first cause to come
before the court was put off until next term;
on which he remarked,
the next case was a cause between the members of one of
the most peaceable and respectable societies in the world,
recommending they should settle these differences among themselves,
and not expose the etiquette of the Society in court.
The individual informing the judge, that could not be the case,
he repeated his advice for Friends to settle the matter amongst themselves by reference.

The individual replied, it could not be settled in that way,
for the whole Society was against him; on which the judge remarked,
it appears you are against the whole Society.
I fear your cause is a bad one.
The counsel for the individual attempted to prove our meetings
for discipline to be meetings for Divine worship,
stating there were both preaching and praying in them.
The judge, who showed himself to be a judicious man, and must,
from the whole tenour of the conduct of the individual in court,
have seen the vindictive spirit which actuated him in his proceedings,
queried with a Friend, who was one of the evidences for the Society,
how far Friends considered preaching and praying essential to worship.

On being informed that we did not consider vocal
preaching and praying essential to worship,
as our meetings for religious worship were at times held wholly in silence, this,
with more in explanation, appeared to enable the judge to close the cause.
It was decided that there might be both preaching and praying in our meetings for discipline,
yet they were no more meetings for worship than the meetings of parliament,
whose practice it was to go to prayer previous to their entering on business;
and therefore none but such as were members of our Society had
any right to intrude themselves into our meetings for discipline,
no more than one not a member of a club society had a right to
intrude himself into their private meetings on their own concerns.

The individual, who before had appeared to carry himself very high,
when called upon to come forward,
and show cause why judgment should not go forth against him by default,
with costs of suit, laid his head on the table before him:
and thus in mercy ended this day, so trying to me in prospect,
though it was so ordered that I was not called upon to appear.

Having obtained certificates from my own Monthly and Quarterly Meeting,
and the Yearly Meeting of ministers and elders in London, to visit Germany and France,
soon after the Yearly Meeting, a war broke out between France and England,
which involved me in difficulty, and brought me under great discouragement.
No way appeared to me but to take the necessary steps
for my departure from my native land,
of which I informed the Meeting for Sufferings,
and a committee was nominated to provide me with a suitable passage,
the necessary sea-stores, and otherwise to assist me in order for my departure.
I could see nothing before me but suffering if I did embark, yet I durst not draw back,
for I had a greater dread of the consequences should I be overpowered by a slavish fear.
The committee, hearing of a vessel bound for a port in Holland, informed me thereof.
Feeling the need there was for me to commit myself to the Almighty Keeper of all mankind,
accompanied by one of the committee, I went on board the vessel,
and took my seat in the cabin, willing to go in her if way opened for me.

We had an interview with the mate of the vessel,
who recommended us previous to our taking any further steps to
apply to the German consul for advice how to proceed about a passport,
which we accordingly did.
He expressed his willingness to give me every necessary document in his power,
but assured us all would be of no avail, as I could not possibly reach Pyrmont,
to which place I intended first to go.
In the afternoon I met the committee: after we had sat awhile solidly together,
with my mind turned in entire resignation to the Lord for his counsel and help,
I believed it was right for me to inform the committee,
that the will was taken for the deed,
and that I was for the present released from taking any
further steps towards accomplishing this religious prospect;
which appeared relieving to my friends, whose sympathy, I was fully satisfied, I had.
I feared hastily to return my certificates,
and therefore held them until the Yearly Meeting two years after;
and then informed the meeting how I had been circumstanced,
desiring advice whether to retain or return them; and it being the mind of the meeting,
that as my certificates had been so long granted, it would be best to return them,
and if the concern should continue with me, to apply for fresh ones,
I returned them accordingly; concluding it best there to leave the whole matter,
and not perplex my mind by endeavouring to fathom that which was not my proper province,
or query, why I had been thus exercised,
and had brought such a load of exercise on my friends, and nothing come of it,
save that my faith had been closely put to the test.
Some Friends, who were not at the meeting when my certificates were granted,
expressed that they believed my movements in applying for certificates had been right;
which was some encouragement to my tried mind.

In the seventh month this year, I requested a certificate to visit Guernsey and Jersey,
and embarked from Weymouth;
and as we sailed with a favourable wind I hoped we might reach Guernsey next morning,
but it soon tacked about.
On first-day afternoon we lay off Alderney, and cast anchor in the Race,
where we lay most of the night,
which proved so tempestuous that some of our passengers manifested great alarm.
I kept quiet in my berth, with my mind mercifully stayed on that Divine Power,
whose word of command, the proud waves and tempestuous winds obey.
Second-day morning we landed safe at Guernsey.

Fourth-day attended their usual meeting, in which I was comforted under a hope,
low as things with Friends here appear to be,
that there had not been a losing ground since we were last favoured to sit together.
Fifth-day morning we had a meeting about four miles out of town,
at a place called the King`'s Mills; the attendance was small.
In the afternoon a meeting was held at the Forest, which was large,
and considered a solid favoured meeting.
My time was filled up until first-day in making calls upon Friends,
and attempting to bring into a train for settling, a difference,
which existed with some who went under our name.
Painful as it was to my natural feeling to engage in it,
yet I feared my being unwilling to make use of the ability received,
in bringing it about, might be afflicting to my mind.
I was favoured to leave the parties under a hope
my labour with them had not been in vain;
but whether or not this should prove to be the case,
when the retrospect of our religious movements is taken,
it is a great consolation to be assured,
that we have done what we could towards helping others out of those difficulties,
into which, through unwatchfulness, the enemy of all righteousness has led them.

First-day morning attended the usual meeting,
after which the Preparative Meeting was held.
Friends on the island had not been in the practice of minuting their proceedings;
and I proposed a book being procured for the purpose, which they concluded to do,
and that the advices should be regularly read: my labour here was well received,
for which I hope I was truly thankful.
Being clear, I felt myself at liberty to go on board the packet,
and on second-day morning we landed on the island of Jersey.
I had a prospect of spending about three weeks in the country part of the island,
and filling up my time, when not engaged in holding meetings with the inhabitants,
by some suitable labour.
I proceeded to the house of John Lemaitre in the parish of St. Ones,
with whom I became acquainted when on the island before,
not doubting but I should meet with some one who could understand my language,
and direct me to his house; but in this I was disappointed,
it was therefore not without much difficulty that I reached his habitation.
The pleasure of meeting again appeared mutual,
although we were not able to express it by words, so as to be understood:
after a while they brought a neighbour who spoke both languages well,
which proved a source of consolation to all parties.
This afforded me an opportunity of explaining my views in coming to their house,
to pass about three weeks, holding meetings occasionally,
and filling up my time in labouring with them on their farm;
showing them a farmer`'s linen frock,
I had provided for the purpose before I left my own home,
that I might be prepared to do any work that fell out for me; and adding,
that if they could accommodate me with board and lodging, and allow me to pay for it,
I would be satisfied.
They objected to take pay for my board and lodging; but on my assuring them,
I could not take up my abode with them on any other terms, they consented,
and our kind middle-man settled the terms for us.

Disappointed in my expectations of an interpreter,
I wrote to Friends of Guernsey to furnish me with one;
but it was three days before he arrived, yet my time did not pass on heavily,
as might have been the case, had I not had suitable employment.
On third-day morning after breakfast I turned out with the whole family,
into the harvest-field to reap oats.
My kind landlord and his family would frequently call out to me, _fatiguea_, meaning,
I was fatigued.
But it appeared to me,
if I pursued the path of duty as my Divine Master required me to do, I must,
as much as possible, avoid showing that such was the case,
although I was truly glad when night came.
The thoughts of turning out next morning was trying to nature,
but believing it was a duty required of me to set
an example of industry to them and their preachers,
I took courage, endeavouring to do my best in my new employ,
and I felt more peaceful when the day closed than would have been
the case had I yielded to the pleading of flesh and blood.

On the arrival of a Friend from Guernsey,
and consulting with him about a place to hold a meeting on sixth-day evening,
he proposed the house of the late Philip Hurle, now occupied by his sister-in-law:
we made application accordingly, but received for answer, that things were altered now,
and the meeting could not be held there.
After receiving this refusal,
we were informed of a place where a meeting was to be held
this evening by some of the society of Methodists,
and feeling drawings in my mind to attend, before what they called the service began,
we proceeded.
I had conversation with some of the principal members of the meeting,
informing them of my view of holding meetings occasionally,
and my difficulty in procuring a place for this purpose; on which,
a proposal was made by them to give up the house to me;
agreeing to sit down with us after the manner of Friends,
which friendly offer I accepted.
The meeting soon settled in solemn silence, and I hope I may say,
I was enabled to labour amongst them in the love of the Gospel,
not only to the relief of my own mind,
but in some good degree to the advancement of the cause of Truth and righteousness.
The report of this meeting was noised abroad, and so opened the way for me,
that in future we found no difficulty in procuring
a place to meet in or a company to meet us.

Seventh-day was passed in making visits to a few serious individuals,
and a man and his sister who profess to be convinced
of the principles of our religious Society.
I felt much for them in their lonely situation,
being the only persons who sit together as Friends in this part of the island.
The man had once suffered banishment because he conscientiously refused to take up arms,
and would have suffered the like again, but for the kind interference of a magistrate.

First-day, we procured a place for a meeting this morning to begin at the eleventh hour,
which was very largely attended.
I was led to say, that I believed there were those present,
who if they were faithful to Divine requirings, must prepare for suffering;
but if they were unfaithful and shunned the cross,
the present manifestation of light and grace with which they were favoured,
and had known what it was to rejoice under a sense of, would be withdrawn,
the light become darkness, and they in danger of losing the crown once in prospect.
We were told, many minds were tenderly reached in this meeting,
some saying that before the interpretation of what I had uttered was given,
there was that in their own minds which said Amen to the truth of what was offered.
At the close of the meeting,
I proposed another at six o`'clock this evening at
this same place for the libertine inhabitants,
which being yielded to, I requested care should be taken to give information to such.
The afternoon was passed over profitably in conversation on various religious subjects.

On our way to the meeting,
I told my companion it seemed to me almost like going to a place of execution,
and I marvelled not at these feelings,
when we reached the place where the meeting was to be held,
the house and yard were crowded and a motley company presented to view,
the lightness observable on many of whose countenances was truly distressing.
Fears were excited in my mind, lest a riot should take place;
and as to our holding a quiet meeting, I saw no prospect of it.
I feared to hold the meeting, and to attempt to disperse the people and not hold it,
I also feared, supposing many had come from a distance to attend it.
As the people who were in the house,
from the oppressive state of the weather appeared unsettled,
I felt most easy to propose our holding the meeting out of doors: on which,
the forms and chairs were brought out of the house.
At our first sitting down,
those who could not be accommodated with seats were disposed to be rather troublesome,
but strength being given me to express a desire that our behaviour might
be suitable to the occasion for which we proposed to come together,
it was well received, a general quiet took place,
which was succeeded by feelings of solemnity, and the meeting was conducted in a quiet,
orderly manner to the close, the people appearing to separate with reluctance;
fresh cause for me, a poor, frail, feeble instrument, to set up my Ebenezer, and say,
"`Hitherto the Lord hath helped me.`"
O, the need there is of a care, after such times of favour,
that self has no part in our services.

Second-day morning made a visit to a religious young man on the south side of the island.
In the afternoon returned to my labour in the harvest-field.
Fifth-day my interpreter informed me, he must return home,
and send a Friend to fill his place: the prospect of this was trying to me,
but I saw no way except to labour after patience.
I continued my labour in the harvest-field until seventh-day,
when we all turned out to cut fern on the mountain for fuel,
which was an agreeable change, and a pleasant way of employing my time.

During the afternoon I had a satisfactory visit from a pious young man,
a preacher belonging to the society of Methodists, who spoke English well;
my companions in labour urged him to persuade me
to desist from my labour the remainder of the day,
which I complied with: we retired together in the thicket of a glen,
where I was once again privileged to converse in my native tongue.
Various interesting subjects occupied our attention in this delightful seat of solitude;
amongst others, that of labour; during which he told me,
he thought the example I was setting in this respect
to their preachers might have its use,
saying, he had often seriously thought on the subject,
and would have been glad to find some suitable employ that he might be allowed to follow,
from a conviction it would be beneficial to both body and mind,
as well as carry a good savour along with it.
During our conversation I found he was acquainted with most of our religious principles,
and I could not doubt but he was also convinced of their truth and efficacy;
he closed our conversation with nearly these expressions,
"`Don`'t spread your net any further over me;`" implying that our
conversation had increased his bonds of unity with our principles.
We separated in great nearness.
On my return home in the evening,
to my agreeable surprise a Friend from Guernsey had arrived,
which was additionally cheering to my mind,
and appeared to have the like effect on the family I was residing with.
No time was now to be lost in making arrangements for tomorrow.
Information had been sent me, that a love-feast was to meet tomorrow in this parish,
and if I was inclined to attend it, the door was open for me to sit with them.
As it respected my accepting the invitation or otherwise,
I believed it was best for me to remain silent.

First-day morning the man and his sister professing
to be convinced of our religious principles,
came to sit with us in our little meeting.
Before we sat down,
I apprehended I must be willing to give up to sit
with those who were to meet at this love-feast,
and yet a fear came over my mind,
lest our example in so doing should prove a stumbling-block to this man and his sister,
who had been brought under the necessity of separating
themselves from these outward signs.
In order to remove any danger of this sort,
I felt most easy to inform them what had been on my mind respecting them,
and my apprehension that it would be better they did not accompany us,
all of which appeared to be kindly received.
Matters being thus concluded, we sat down together at my lodgings,
and held our meeting at the time appointed.
We proceeded to the place where the love-feast was to be held:
I felt most easy we should be fully satisfied that our being introduced
was with the free consent of all the parties we were to meet,
therefore requested this should be first ascertained,
on which we were informed our company would be acceptable.

As we entered, we observed all were uncovered;
as true religion leads to a care to be preserved from willfully offending any,
I felt most easy to remark,
I hoped our continuing with our hats on amongst them
would not hurt the feelings of any tender mind;
informing them it was our uniform practice in our religious meetings,
except in the time of vocal prayer; in reply to which,
we were assured no offence would be taken on this account.
Before the preacher opened the meeting by giving out the hymn,
I requested leave to express what was on my mind, to which he consented,
and kindly gave me his place;
a full opportunity was afforded me to relieve myself of such matters as came before me,
and I thought there was good ground to believe what
was offered found a place in many of their minds,
much affection being manifested at our parting.
Apprehending the pointings of duty were to my having
a meeting this evening at half-past seven o`'clock,
it was held, and the house and yard were so crowded, and the pressure of the people such,
that fears were at first entertained that some accident would occur;
but after awhile all became still, and at the close the people quietly departed.
It was considered to be a favoured season;
but not obtaining that relief which rendered it safe for me to leave this neighbourhood,
I could not see my way clear to make a move,
without appointing another to be held on third-day evening at the same place.

Third-day was spent in labour in the harvest-field,
and in the evening attended the meeting appointed at my request,
which opportunity set me at liberty to quit this part of the island,
and when the meeting separated the people expressed
their regret at the prospect of our leaving them.
Fourth-day morning, after a parting opportunity with John Lemaitre`'s family,
we proceeded towards Hilliers.
On our near approach to the town, I felt such a stop in my mind,
that I was under the necessity of requesting my companion
to sit down at the most convenient place we came to.
We sat some time in silence, during which,
feeling the pointings of duty to a meeting in the town that evening,
I informed my companion thereof.
The probability of our procuring a place for the meeting appeared very uncertain.
On our way, we called at the house of a widow,
where some belonging to the society of Methodists at times meet.
We informed her of what I had in prospect, to which she replied,
she had no doubt of procuring us the use of the meetinghouse and beds for the night;
and on application for the house,
we were given to understand it would be readily granted,
and an invitation was sent us from the proprietor to take tea with him and his family,
and we were assured that general notice would be given of the meeting,
but that it was not likely many would attend,
the house seldom being more than half-filled.

I went to the meeting poor and empty; at first it gathered very straggingly,
but in time the house, two rooms that opened into it, and the passage, were crowded.
I expect the circumstance of our sitting in silence
caused some at first to behave rather rudely,
laughing and whispering; yet after awhile, we had cause to acknowledge,
that the calming influence of the Spirit and power of the
Redeemer subdued and subjected these opposing spirits,
and the meeting closed under a sense that Divine
mercy and condescension had been near to us.
On our way from the place we were joined by a young man who manifested a seeking disposition;
I invited ourselves to breakfast with him next morning,
where we met with an interesting young couple.
This afforded us an opportunity of giving them some account of our principles,
of which we found they were very ignorant; and I regretted the want of suitable books.
My way towards my own home became again shut up;
endeavouring to see into the cause why it should be so,
it appeared I must be willing to have a meeting near the great school.
A suitable place being found, and notice given of the meeting,
we attended at the time appointed and found a full gathering,
the people generally behaved well,
considering a meeting had never been held there before.
Feeling drawings in my mind to have a meeting at St. Brillard`'s,
we proceeded towards the place,
where a meeting is held once a week by the Methodist society,
and found it to be their meeting night.
The preacher hearing our motives for coming,
freely offered to give up the house and his congregation to me, to sit as our manner is,
and take his seat amongst them.
The meeting was largely attended and the way opened for me to obtain relief,
for which I felt truly thankful,
and especially that I had been made willing to sit with this company,
believing there is a precious seed hereaway:
the meeting appeared to separate under the influence of
that love which knows no religious distinction as to name.

We went to lodge at the house of a young man,
who kindly set before us the best his limited circumstances afforded.
Those who travel amongst these islanders must not look for great things,
or to be much waited upon, their means in general being very small,
and a rare thing to find a servant kept.
Yet, as far as I have experienced,
there is no want of necessaries for such as are truly devoted to Christ`'s cause.

Next morning we returned to St. Helliers.
When I was here about three years ago,
my mind was much turned towards those who are deemed the
more respectable part of the inhabitants of this parish;
but the way did not open to have a meeting with them at that time,
although the society of Methodists on my first landing
had kindly offered me the use of their house.
Believing the time was now come for me to have the people called together,
I felt a difficulty about a suitable place,
apprehending if the meeting was held in the house belonging to the Methodists,
it would be likely to be filled with them,
and those towards whom my views were would not be generally accommodated;
but as a more suitable place could not be found,
the subject was mentioned to some of the leading members of that society,
who freely offered the house for our use.
Feeling my mind drawn towards the usual attenders of this meetinghouse,
a meeting was appointed to be held with them on first-day afternoon, which was large.
I was enabled to labour in a close line of doctrine, yet there was reason to believe,
that it was mostly well received.

The meeting for those who are deemed the more respectable inhabitants of this parish,
was fixed for five o`'clock on second-day evening.
It was not so generally attended by those I had felt my mind drawn towards,
as was desirable,
those who had undertaken to give notice not being
equal to the task they had engaged to perform:
it was held much in the quiet, but did not afford me the relief I had hoped for;
but having done all that appeared to be required of me towards securing a better attendance,
I was enabled to leave this matter.

My mind now turned towards the parish called St. Martin`'s;
but from some causes which I had no power of remedying, I became so much discouraged,
that it appeared safest for me to take the first conveyance to Guernsey,
which I accordingly did, and we landed on third-day.

On fifth-day afternoon went on board a trader bound for Southampton,
and after a passage of seventeen hours we were favoured with a safe landing,
having passed through a tremendous night of thunder, lightning and rain.
First-day attended meeting here;
in the afternoon way opened for me to get my mind more fully
relieved than I felt ability for in the morning meeting,
for which favour I hope I felt truly thankful.

Second-day I proceeded to Poole, third-day attended the select Monthly Meeting,
after which was held the Monthly Meeting for discipline,
in both of which I was favoured to experience some renewal of strength.
In the evening I sat with Friends in their select Quarterly Meeting:
here I met with William Forster, jun., a member of my own Monthly Meeting,
whose company after such a long separation from my friends at home, was truly acceptable.
Next day attended the Quarterly Meeting for Dorset and Hants,
the two counties being recently united in one Quarterly Meeting.
It was consoling to observe the concern which was evidently alive in the minds of Friends,
that the unity of the One Spirit which is the bond
of true peace might increase and abound,
and I felt well satisfied that I had given up to sit with Friends at this meeting.
Fifth-day I proceeded to Bristol.

First-day morning attended the Friars`' meeting; after the meeting for worship closed,
Friends were requested to remain,
before whom I spread my concern to pay a visit to the families of Friends in the city;
which being united with, a committee was named to lay out the visits for me.
It was considered best I should proceed alone, as no suitable companion offered.
I was favoured to accomplish this service in about six weeks; after which,
the way opened for me to return to my own home, where I was favoured to find all well.

Only a few days had elapsed after I reached my own home,
when I had a severe attack of disease.
I found it coming on me before I left Bristol; my bodily strength became reduced,
and my mind so depressed, that I thought I should quite sink under it.
I had experienced an attack before, equally severe, out of which I was delivered,
yet such was my trying situation,
that it felt utterly impossible for me to lay hold on hope; until that Divine Power,
who alone is able to apply a sovereign remedy for this greatest of maladies,
in mercy raised me up again, brought me out of the pit of horrors,
and showed me that my day`'s work was not yet accomplished,--that
my Divine Master had further work for me at Manchester,
Sheffield, and some meetings near Kendal; which had a cheering effect on my mind,
having hitherto found, when willing faithfully to serve the Lord,
that he is a good Master, worthy of my very best endeavours to follow him.

1806+++.+++ This year my faith was put to the test,
from an apprehension that it was required of me to make
a further sacrifice of part of my outward substance,
to free my mind more effectually from worldly encumbrances.
It was that part of my income arising from leasehold property in houses,
which engrossed more of my attention than was profitable for me,
in the situation in which I stood, in religious society.
My parting with this property threatened a certain reduction of my income,
which occasioned me some deep plungings,
known only to the Almighty and myself I experienced
that the enemy of all good was busily at work,
magnifying the difficulties in my view;
laying before me the sacrifice I had so recently made of a good business,
and if that step was of Divine requiring this could not be,
because I then had the assurance given me that the meal in the
barrel and the oil of my temporal substance should not waste,
but if I took this step my yearly income would evidently be diminished.
Earnest were my breathings to the Lord, that if this sacrifice was of his requiring,
he would not forsake me, until I was brought to a willingness cheerfully to yield;
for powerful were the pleadings of the creaturely part in me,
as well as the secret workings of the unwearied adversary, to put by my compliance.
Whilst struggling in this tribulated state of mind,
as if human nature and the suggestions of the evil power would predominate
over those clear pointings of duty which continued to follow me,
I had this very significant and instructive dream.

I saw before me a straight but very narrow path gradually rising,
at the foot of which stood a man very simply attired,
who offered to take the charge of safely guiding me up.
I followed him: when we had reached about two-thirds of the way up, my guide halted,
and turning himself round, requested me to do the same, which I accordingly did.
He then bid me take a view both on the right hand
and on the left of the road I had been ascending:
on my right hand, the ground in the bottom appeared rocky and uncultivated,
covered with rubbish, grass, and trees that had been stunted in their growth:
these I was told were fit for nothing but the fire,
and that they were comparable to those whose hearts
continued to be like the stony and thorny ground.
I then turned to take a view on my left hand, and shuddered in myself,
when my guide pointed out to me the dangerous precipice,
close to the edge of which I had travelled.
The foundation of the path appeared as steep as a house side; which led me to conclude,
the road on which my guide had thus far conducted me must be founded on a rock,
otherwise the path being so very narrow,
from the weight of my body I must have been precipitated
into the vast barren space I beheld.
In this I observed a number of persons huddled together,
at times grubbing with their hands in the earth,
and at other times employing themselves in tossing the earth from one hand to the other,
every now and then looking one at the other,
with a sort of consciousness that they were employing their time in vain,
and saying one to another,
"`I am countenanced in spending my time in this manner by thee,`" and another,
"`I am countenanced by thee.`"
On which I queried with my guide, "`What does this all mean?
these men do not look like common labourers,
neither have they such tools as common day-labourers use; besides this,
they are all clad in very nice and costly apparel,
like men of the first rank in the world with respect to property.`"
My guide assured me, that although they were thus apparelled,
and were rich in worldly substance,
wanting nothing this world could bestow to make them as happy as it was capable of, yet,
having made riches their chief hope for happiness,
they had become so estranged in love and affection from
that Divine Power which only can make truly happy,
that they were completely miserable.
My guide, turning round, bid me follow him; and as we began again to ascend,
instructed me to keep very near to him, continually reminding me,
that although I had mercifully escaped the danger,
which those I had observed in the barren space had fallen into,
yet I was not out of the way of danger;
and that my safety depended on my keeping continually near to him,
eyeing him in every step I took from day to day,
without which I should yet be precipitated into the same
barren space with those miserable persons I had beheld,
and become their doleful companion.
When I awoke, the danger which I seemed to have escaped on both hands,
but more especially that on my left, made such an impression on my mind,
that for several days afterwards little besides it came before me.

10th of seventh month,
the Monthly Meeting having granted me its certificate to visit Sheffield,
Manchester and Kendal, and to take meetings on my way, I left my own home.
First-day attended meeting at Hogsty-End:
there are but few in profession with Friends belonging to this meeting,
with them I was favoured to have a comfortable sitting.

After meeting I walked to Olney,
intending to be at their afternoon meeting at five o`'clock.
Feeling drawings in my mind towards the neighbours.
Friends concluded it best to hold the meeting an hour later than usual:
although it proved a time of close exercise to come
at the spring of Divine life in myself,
yet I felt comforted in being there.
Fourth-day attended Leicester mid-week meeting,
in the afternoon walked to Castle Donington,
and lodged at the house of that faithful soldier in the Lamb`'s warfare, Ruth Follows,
who appeared green at a very advanced age.
Fifth-day attended meeting there, after which I reached Derby,
and had a meeting with Friends in the evening,
a considerable convincement having taken place here within a few years.
First-day morning attended meeting at Sheffield,
at the close of which I opened my prospect of a visit
to the families of Friends of this particular meeting.

Third-day walked to Rotherham, sat with two families residing there,
and to Ackworth in the evening, intending to be at the general meeting,
where I met with many Friends from distant parts of the nation.
It had an animating effect on my mind,
to observe the interest manifested in the welfare of the rising generation,
and the harmony that prevailed in conducting the various matters that came under notice.
First-day attended Woodhouse meeting in the morning,
after which I walked to Sheffield meeting in the afternoon,
and this evening proceeded in the visit to the families;
which having been enabled to accomplish,
on fifth-day I attended the Monthly Meeting at Doncaster.
First-day attended the morning meeting at Manchester,
at the close of which I informed Friends of my apprehension
of duty to sit in their families,
which being united with I commenced the visit that evening.

Fifth-day attended the large Monthly Meeting held at Hardshaw.
The great number of testimonies of disownment that
passed this meeting affected me with sorrow,
as I doubt not a preventive would at times be found,
if those who accept the post of watchmen on the walls of our religious
society lived sufficiently loose from the cumbering things of this life;
then would more timely labour be extended towards those who were overtaken with a fault.

First-day, 31st of eighth month, I walked to Oldham meeting, which was large,
many who were in attendance, I understood, professed to be under convincement.
I was led to sympathize with the few rightly exercised members,
also to labour with some who were negligent in the attendance of their mid-week meetings.
I walked back to Manchester, and on seventh-day this deeply humiliating engagement,
of sitting in families, was brought to a comfortable close as it respected my own mind,
having had about one hundred and forty sittings.
After taking an affectionate farewell of Friends of this meeting,
I rode to Bolton in the Moor, a meeting being appointed there at my request.
It was largely attended by other professors, and I found it hard work to relieve my mind,
in consequence of the opposition that was to be felt to the doctrine I had to deliver,
of the necessity of dying daily to sin before we can come
fully to experience what it is to live unto God.
Third-day attended meeting at Bentham, which is very small;
and on fifth-day was at Briggflatts,
and obtained a little relief to my mind from that load of exercise,
under which I have had of late to travel.
In the afternoon I walked to Dent Dale,
a meeting being appointed at my request at seven o`'clock this evening,
which was largely attended by Friends and others.
I thought we had abundant cause to acknowledge that the mercies of the Lord fail not,
in that he still continues mindful of us.
First-day was at a meeting held at Bainbridge,
largely attended by those not in profession with Friends.
In consequence of a funeral, the meeting was long in a very unsettled state,
the burial company not observing the time appointed for the meeting;
yet I was led to hope it would not prove altogether unprofitable to some.

Third-day attended the select meeting at Leyeat in Dent,
and in the afternoon walked to Sedberg.
Next morning I was informed that the town`'s people,
and especially some of the society of Methodists,
were desirous I should have a meeting amongst them,
but not feeling that in my own mind which would justify me in complying with their request,
I walked to Kendal.
Sixth-day attended meeting there,
in which I was favoured to receive a morsel of that bread
which alone can satisfy the immortal part in man.
First-day attended a burial, and returned to the afternoon meeting at Kendal,
which proved an open time.
Fourth-day at Preston Patrick meeting: walking about the graveyard,
the depositing place of many who had been valiants
for the Lord in their day were pointed out to me,
but, alas! how little fruit of their faithfulness is now to be seen; my companion,
myself and four others were the whole company assembled at this week-day meeting.
Fifth-day attended the mid-week meeting at Hawkshead, after which returned to Kendal,
attended Monthly Meeting there, and on seventh-day proceeded to Lancaster.

The morning meeting next day was to me very trying,
but in the afternoon I was enabled to obtain some relief.
Third-day attended Preston Monthly Meeting.
If my feelings were correct as it respects the state of society,
the number of rightly qualified members to support the discipline is very small.
Fourth-day attended Monthly Meeting at Liverpool,
where I met with Deborah Darby and Priscilla Hannah Gurney on a religious visit.
The Monthly Meeting was large,
and it appeared to me holy help was vouchsafed in
transacting the concerns that came before us.

In the evening the select Quarterly Meeting was held,
and the following day the Quarterly Meeting for discipline,
largely attended by young people: I believe it will long be remembered by some.
Not feeling my way clear to leave Liverpool when the Quarterly Meeting closed,
a meeting being appointed by the two travelling Friends, I attended it,
in which silence appeared to be my proper place:
what a favour it is both to know our proper place, and to keep it.
I expected to move towards home after the Quarterly Meeting, but my way continued shut up.
First-day after attending morning and afternoon meeting here,
my way opened with clearness to Chester; and I attended mid-week meeting there,
where Friends are very few in number.
After a meeting with the few Friends at Nantwich, I proceeded home by the way of Stafford.
