== Chapter VI.

Seventh-day, Susannah Hill, myself and some other Friends, proceeded to Wicklow.
The weather was fine, and the country picturesque,
and I became somewhat recruited in mind and body.
Here are a few families scattered that form a part of Dublin Monthly Meeting,
whom we visited by second-day evening,
and the retrospect affords a hope that an open door has been left,
for such who may be called upon to move in the same line of duty,
which was cause of thankfulness.
Fifth-day my companion Susannah Hill returned home.
I walked to Ferns, and next day to Enniscorthy: soon after my arrival,
I proposed that such Friends as were considered suitable should be convened,
before whom I opened my prospect of a visit to the members and attenders of this meeting;
which being united with, on seventh-day I proceeded in the visit,
and on fourth-day it was accomplished:
after attending a satisfactory parting meeting with Friends,
I walked about eleven miles to Grove town and visited a
Friend suffering under great bodily affliction from cancer.
I found her in an humble frame of mind, resigned to her situation;
it proved a season in which encouragement was offered to lay hold on that Divine strength,
which can support the mind in every time of trouble.

Sixth-day attended an appointed meeting at Ross, for members and usual attenders,
but others giving their company shut up my way,
so that I found it hard work to relieve my mind;
my service being to those professing with our religious Society.
For want of care, on the part of those who give notice,
to keep strictly to the views of the visitor,
the designs of the Great Master in sending his servants
into his vineyard are in danger of being frustrated.

Seventh-day accompanied by Samuel Elly rode to Waterford,
where I was very kindly received by Thomas Jacob and wife.
My depression of mind was such on reaching Waterford, that I could not suppress my tears,
and I was for some time unequal to enter into conversation:--a dispensation, which,
however trying to nature,
I was led to believe was preparatory to some hidden and
unexpected service that would be required at my hands,
if I was careful to keep under the weight of it the Lord`'s appointed time.

First-day attended morning and afternoon meeting here.
Third-day attended Monthly Meeting at Enniscorthy, which was small.
My kind friend Samuel Elly and myself had proposed
leaving early on fourth-day morning for Ross,
but after the close of the Monthly Meeting,
my attention was arrested by the revival of a fear that had some
hold of my mind when engaged in visiting families in this meeting,
that a breach of love existed,
yet I did not at that time feel a sufficient warrant to search into it;
but now it appeared unsafe for me to leave this place
without opening my mind on the subject to my companion,
and some of the Friends of Cooladine meeting.
I found I was correct, that the breach had spread very wide,
and the labour bestowed had proved unavailing;
but Friends encouraging me and manifesting a willingness to be helpful to me in it,
after seeking for Divine direction how to move, the pointings of duty, I thought,
were clear to have all the parties concerned collected next morning, which took place.
My companion, a Friend of Cooladine, and myself, joined them,
and from our first sitting down the contriting influence
of the Father`'s love was felt to overshadow us.
The hearts of some were so broken and tendered that tears were abundantly shed,
and everything that was hateful and hating one another, evidently became subdued;
and so far from reflecting on one another, which I much feared before we came together,
all was submission and concession.
We thought we had good ground for believing they were sincere in their
desires that all the animosity that had prevailed amongst them,
might be buried in oblivion,
giving each other the hand with expressions of earnest
desires to be preserved loving as brethren.
Feeling my mind released from any further service hereaway,
after taking some refreshment, my companion and myself returned to Ross.

Fifth-day I rode to Waterford, and at the close of the meeting on first-day morning,
Friends were requested to remain,
whom I informed of my prospect to visit Friends and such as usually attend meetings,
in their families, which being united with,
and Elizabeth Ussher being under a like concern,
she was set at liberty to unite with me in the engagement,
and this evening we entered upon the service.
Our first visit was to a family of Friends on the Quay.
A short time after we had sat down in silence,
there echoed from the street the greatest noise of
tumult and riot I remembered to have heard;
but after awhile it removed further from us,
and through the merciful interposition of Him whose commands the unstable elements obey,
we were favoured with a comfortable sitting in this family.
On inquiry into the cause of the tumult we had heard, it was said to be a bull-baiting.

Fifth-day attended the usual meeting, which proved a memorable time.
First-day attended the two meetings, which were times of close exercise.
May fruits from the labour bestowed,
in due time appear to the praise of that Almighty power who alone
is able rightly to qualify for every good word and work.
Sixth-day closed this field of religious labour, except one family,
nine miles on our way to Clonmel.

Seventh-day we left Waterford for Mayfield, and visited the family there,
from whence I hoped to proceed to Clonmel, but after the opportunity was over,
my apprehensions were awakened that my Divine Master had
some further service for me in Waterford or its neighbourhood,
and that I must be willing to return there.
The circumstance of the tumult on first-day evening, occasioned by bull-baiting,
had never wholly left my mind,
and I believed it imperative on me to make a visit to the Protestant Bishop,
whose influence I was led to hope would be sufficient to prevent such practices in future.
We returned to Waterford,
and at the close of the afternoon meeting I informed Friends
of my prospect to make a visit to the Protestant Bishop,
and they encouraged me to pursue my apprehensions of duty.

Second-day morning accompanied by my kind friends, Thomas Jacob and John Strangman,
proceeded to Dunmore, the bishop`'s country residence,
and obtained an interview with the bishop and his wife, who received us respectfully.
I presented my certificate,
which I thought would give him a correct view of my motive for leaving home,
and manifest to him the care which Friends exercise towards their ministers.
He appeared to read it with attention, and when returning it to me,
expressed his surprise at my coming so far to visit my friends,
and queried if such instances were not very uncommon; to which reply was made,
"`Friends at times come from America on this same errand.`"
I then opened to him the circumstance that occurred on the first-day evening at the Quay,
and the manner in which my mind had been affected by it,
which was the cause of my making him this visit.
The bishop, in a very agreeable manner,
assured us he was willing to do all in his power to prevent such practices in future,
and gave me a full opportunity to clear my mind, making short remarks as I went on,
telling me, I must expect to be jeered at as I passed along, but that I must not mind.
We parted, I believe I may say, under feelings of true love towards each other,
and my companions united with me in considering the opportunity an interesting one.
Being at Waterford some time after, I was informed the practice had been discontinued.

Third-day attended the Monthly Meeting, which was larger than usual;
and a time of favour which I trust many will long remember.
Fifth-day attended Monthly Meeting at Clonmel.
The concerns of the Society here, as in many other places,
appear to rest on the shoulders of a few.
Many of the members of our Society may now be numbered with the people,
as respects externals, to their great loss.
The meeting was greatly hurt by the unseasonable manner of its gathering;
occasioned more from the disorderly practice of staying
out of the house in conversation long after meeting time,
than from not being on the premises in due time.
Third-day attended Monthly Meeting at Youghall.
The prospect of a succession of useful members in the church,
appears more cheering than in some other places:
may no temporal considerations be suffered to mar the good work begun in some minds.

Fifth-day attended Monthly Meeting at Cork.
The meeting, both for worship and discipline was small,
when compared with the number of the members.
We sat a long trying meeting, and then adjourned to the evening,
which was equally exercising.
But a difficult case, that had long been before the meeting,
being brought to a satisfactory close, was a relief to many minds.
Seventh-day attended a burial, at which there was a great gathering of persons,
not in profession with Friends, who behaved solidly on the occasion.
In the evening I had a sitting with the relations of the deceased.
First-day attended the usual meetings.

Third-day attended Monthly Meeting at Limerick, in which I was comforted under a hope,
there are yet left in this meeting,
those who are favoured to feel the welfare of society nearest to their hearts.
On seventh-day evening, attended the select Quarterly Meeting at Waterford,
and on second-day morning the Quarterly Meeting for discipline commenced.

Third-day attended an adjournment of the select meeting: at this meeting my dear friend,
Elizabeth Ridgway, opened a prospect she had been exercised with for ten years,
to pay a religious visit to the drinking-houses in the city and suburbs of Waterford,
which excited the sympathy of her friends.
During the solid deliberation that took place,
encouragement was held out to pursue her prospect.
My mind was made sensible that if I did right I must
be willing to unite with her in the service;
and Friends set me at liberty.
Fourth-day attended a religious opportunity at the Provincial school, at Newtown,
which was a time of favour.

Fifth-day attended the usual meeting,
at the close of which Friends were requested to stop, to afford my dear friend,
Elizabeth Ridgway,
an opportunity of casting her prospect of a visit to the drinking-houses before them.
The concern being of so trying a nature, excited sympathy and much weighty consideration,
and my proposing to join her appeared relieving to Friends`' minds.
After considerable time spent in solemn silent waiting on the Divine Counsellor, who,
when he puts forth, fails not to go before and prepare the way,
as was mercifully the case in most instances from day to day,
a committee was nominated to assist us in the prosecution of this humiliating engagement;
for so we felt and experienced it to be.
After being thus set at liberty, accompanied by our kind friend, Thomas Jacob,
we proceeded till it was accomplished, making about eighty visits; all of the houses,
one excepted, being kept by Roman Catholics.

Our service was not confined to the keepers of the houses,
but frequently extended to the company sitting in them to drink,
who mostly heard quietly what we had to offer, and at our parting behaved respectfully;
one man offered a small matter of money for us as a mark of his gratitude.
Yet we met with a few instances of refusing to receive our visit;
and some of the remarks that were made were very humiliating,
as well as the crowd of people that sometimes followed us from house to house;
but by endeavouring to keep near our holy Helper,
we were enabled to rise above all that otherwise would have been hard to bear.
The visit in the city closed under a humbling hope that, as ability had been afforded,
we had delivered the whole counsel we were entrusted with;
having to contend with dark spirits, settled down in gross superstition,
but yet so far wrought upon by Divine power,
that the words given us to utter appeared generally to find a door of entrance,
we felt abundant cause to acknowledge that the Lord, our Divine Master,
had dealt bountifully with us.
We next proceeded to the suburbs; and having finished there,
it felt to me as though the bitterness of death was not past,
believing I must submit to make a visit to the people in the markets on seventh-day.
Some of the market-women one day cursing us, saying we were crying down the whiskey,
made the prospect of such an engagement trying to human nature;
but as there appeared no way for me to get comfortably out
of Waterford but by being willing to yield in this respect,
after informing my dear companion, I requested the committee to meet,
and laid my concern before them.
The subject being new,
and considering the general disposition of this class of the people,
mostly bigoted Roman Catholics, more Friends than the committee were called together,
and on taking the subject into consideration, my dear companion Elizabeth Ridgway,
expressing her concern to unite with me, we were liberated to pursue our prospects.

Seventh-day, accompanied by our kind friend, Thomas Jacob,
we proceeded to the offal market, on entering which,
the noise and bustle made a discouraging impression on my mind,
labouring as I was under a load of depression and nervous debility.
We ascended some steps of a house much elevated above the people;
and after a short pause, a few words audibly spoken attracted attention,
the tumult ceased, and we were soon surrounded both by sellers and buyers,
whose quiet and solid attention was very remarkable,
remaining with us until our minds were favoured to feel
the evidence of having fully discharged ourselves.
We next proceeded to the cross, and ascended a flight of steps there.
The people surrounded us in great numbers, but soon became quiet,
affording a full opportunity for relief to our minds; many appeared solid;
nothing like an insult was manifested; and some on our leaving them,
gave us their blessing.
Feeling ourselves clear of any further service in this way, we returned home,
with hearts truly contrited, under a fresh sense that all things are possible with God,
who, in mercy,
condescends to confirm this truth in the experience of such
as are willing to be girded and led about by him.
First-day attended the morning meeting here,
a time of favour which I hoped would be profitable to the youth.
Second-day my dear companion and myself visited the
drinking-houses on the way to the Passage,
thirteen in number.
Had an agreeable opportunity with a magistrate there, and returned home rejoicing,
not because the spirits had been made subject, but humbly hoping,
as the path of entire dedication is pursued to the end, we shall be found,
through adorable mercy, amongst the number of those whose names are written in heaven.`"

Third-day, 1st of eleventh month, attended Monthly Meeting;
gave in a short report of our visits, which appeared to bring weight over the meeting.
Before Friends separated,
I called the attention of the meeting to the overseers not seating
themselves in the meeting so as to be able to oversee the gathering
of it and the manner of Friends conducting themselves therein.
Whatever may be the cause whence this proceeds,
whether from a diffidence that has not truth for its cornerstone,
or a fear that by so doing they should see more work
for them to do than is pleasant to the fleshly part,
such are not likely to help forward the cause they profess to espouse.
The meeting entered solidly into the subject,
and Friends were proposed to fill up the vacant seats at the front of the meeting.
My mind being under an apprehension of duty to make
a visit to the mayor and active men in the city,
I informed Friends hereof, on which two were nominated to assist me.
The mayor, with one of the sheriffs, met us at a Friend`'s house,
which afforded an agreeable opportunity fully to relieve my mind,
for which I trust I felt grateful to the Author of
all my blessings in thus making way for me,
and grateful to them for thus receiving my visit,
and for their attention manifested to what was communicated.

Seventh-day, feeling my way now clear to leave Waterford, I proceeded to Clonmel,
where I met with my esteemed friend, Margaret Hoyland,
about to enter on a visit to the families of this meeting:
having felt a similar concern when here before,
but the way not then opening for me to proceed in it,
after some conversation with her on the subject,
and being prepared in my own mind to unite with her,
it was concluded to request Friends to stop at the
close of the meeting for worship tomorrow morning.
First-day attended the usual morning meeting, at the close of which Friends stopped,
and after a suitable time spent in deliberating on our prospects,
we were left at liberty to proceed in the visit.
The afternoon meeting was trying in the commencement,
but through patient waiting and quiet hoping for the arising
of that Almighty power that is able to disperse the clouds,
it closed more comfortably.
After meeting we proceeded in the visit.
Seventh-day we dined at Anner Mills, and enjoyed a peaceful cessation from labour,
which both mind and body seemed to claim.
Went into town in the evening and finished our engagement in this meeting.
First-day rode to Garryroan and attended meeting here,
at the close of which we informed Friends of the
prospect of visiting the families of their meeting,
and on fourth-day it being accomplished, we had a satisfactory parting meeting.

First-day morning attended meeting at Youghall, when I proposed a visit to the families,
which being united with, Abraham Fisher was allowed by the meeting to accompany me,
and the visit was entered upon this evening.
On my return to my lodgings, a letter from my kind friend, Susannah Hill of Dublin,
informed me of her having obtained a certificate
to visit the families of Friends in Cork and elsewhere,
as truth opened the way: this to me was like a brook by the way,
feeling myself bound to the families of that meeting when last in the city,
but it did not then appear as though the time for engaging in it was fully come,
and the thoughts of returning to enter upon such an arduous undertaking alone,
at times appeared trying.
Fifth-day we closed our visit to the families of Friends of Youghall, I trust,
under a grateful sense that Divine help was mercifully near from day to day.
Second-day reached Cork in the evening.

At the close of the meeting on fifth-day, my companion Susannah Hill, with myself,
informed Friends of our prospects of a visit to the members and attenders of their meeting:
our proposal appeared to be willingly united with, and William Wright,
a religious young man, was named to accompany us, with which we cordially united.
Sixth-day morning, 2nd of twelfth month, we entered upon this humiliating engagement.
First-day attended the fore and afternoon meetings, both of which were trying;
we had hard things to deliver, but I humbly hope they were the counsel given us;
and when the day closed, thankfulness was the clothing of our minds,
in believing we had been faithful.
Fifth-day attended Monthly Meeting, which was a suffering time,
from a disposition apparent in some to oppose the orderly
proceedings of the Society in the exercise of the discipline.
First-day attended the morning meeting, which was large, but through late comers-in,
did not quietly settle down until an hour after the time it should have done.
Our labour of love in a visit to the families in this city closed on first-day.

Second-day we rode to Glanmire to breakfast,
and after a solid parting meeting proceeded to Johnstown,
and sat with a member of the Society who resides here.
Third-day we rode about twenty miles to Ballamaline, the weather continuing severe,
the roads slippery and bad to travel upon, we did not reach our quarters until near dark.
Here we met with a large family, members of our Society,
settled down for the sake of what is called a good bargain,
in a farm twelve miles from any meeting of Friends
and no members of our Society nearer them.
Fifth-day rode to Carlow to attend the Quarterly Meeting for Leinster province:
the road in places hilly, and so covered with ice that our horses twice fell down,
and my companion was thrown out in going down hill.
It no longer appearing safe to ride,
we walked nearly the whole of the way we yet had to go; esteeming it a favour,
amidst all the trials and dangers of this day`'s travel,
that we were enabled to reach our journey`'s end safely.
Sixth-day attended the select meeting, which was small,
but we were comforted in sitting with this company.

First-day attended the morning and afternoon meeting here:
in the evening had a solid opportunity in a Friend`'s family with a large company,
mostly young people.
Second-day attended the Quarterly Meeting for discipline: the low state of things,
as appeared by the answers brought up from some of the meetings was distressing.
Third-day the parting meeting was held, which proved a season of Divine favour,
under a humbling sense whereof, the meeting separated.
In the evening we rode to Kilconner, and on fourth-day attended meeting there.
Fifth-day rode to Athy, the most deplorable meeting-house I ever before sat in;
a few months after our sitting with Friends here, the whole of the roof fell in:
after meeting we rode to Ballynakill.
Seventh-day, a meeting was appointed at nine o`'clock this morning at our request,
which proved open and satisfactory, after which we rode to Mundriehead.

First-day rode four miles to Knockballyraaher: the meeting of Friends here is small,
but Friends coming from meetings round, and many of the neighbours,
principally we understood of the Roman Catholic persuasion, attending,
we had a large gathering:
the meeting held very long owing to the straggling manner in which the people assembled.
It proved quiet and satisfactory; we were led to believe generally so.
We then rode to Roscrea, to a meeting appointed at three o`'clock this afternoon,
which was largely attended by persons not professing with Friends:
it proved solid and satisfactory.
Second-day, our guide being much indisposed from a heavy cold contracted at Ballynakill,
from the damp state of that meeting-house, we were obliged to rest this day,
esteeming it a great mercy,
when recurring to the exposure we have had to endure
at this inclement season of the year,
that we ourselves have so far escaped.
Third-day proceeded to Birr, where are only two families in membership;
and the appearance very discouraging as to the probability
of a meeting being kept up here.

Fourth-day we rode thirty-eight Irish miles to Limerick;
fifth-day attended the mid-week meeting,
and at the close of which we informed Friends of our prospects
of a visit to the families of their meeting,
which being united with, we proceeded therein.
From a heavy cold I had taken, and the depressed state of my mind,
I felt under discouragement,
but I found it would not do for me to give way either
to the importunities of nature or my friends.
Oh! let me rather wear out than rust out, is at times the secret craving of my mind.
Second-day rode out to Castle Connell, the day being fine and the scenery picturesque,
my nature felt a little revived.
Third-day attended Monthly Meeting,
in which I was comforted under a feeling of the good presence of the Minister of ministers:
three sittings this afternoon closed our visit to the families of Friends of this meeting.

Fourth-day reached Cork in the evening.
Fifth-day attended their usual meeting, and an adjournment of the Monthly Meeting:
at times this day I have been led to recur to some of my
exercises during our visit to the drinking houses at Waterford,
accompanied with earnest desires,
that if it should be required of me to proceed in
the same line of duty in this rude and bigoted place.
Divine mercy will not leave me until I am brought cheerfully to submit.

Seventh-day attended the select Quarterly Meeting,
and in the evening the Provincial school committee, in which I was comforted to see,
notwithstanding the low state of society in this Quarterly Meeting,
that Friends were so alive to a care for the religious
education of the youth of the Society.
At the close of the select meeting an adjournment of the Monthly Meeting was held,
which continued four hours.
Although it proved a time of close exercise,
the sound members of the meeting were preserved to
move quietly along in a very difficult case,
beyond the expectation of some and the desire of others.
Second-day attended the Quarterly Meeting for discipline,
which was small considering the size of some of the meetings constituting it.
Third-day the parting meeting was held,
in which it appeared to be my place to express a few words and take my seat again;
after which the Gospel flowed freely through rightly qualified instruments.
The meeting closed under a precious covering,
which I doubt not will be remembered by some.

Attended the meeting on fifth-day and the two meetings on first-day,
in all of which silence appeared to be my proper place; my companion had good service.
In the evening a member of the Monthly Meeting came to our quarters,
saying he was not easy we should depart the city without having an opportunity with us:
a Friend being in the adjoining room, we requested he would be present,
when the individual informed me and my companion his business with us was,
to clear himself from things that had been laid to his charge before us,
by different active members of the meeting.

We told him Friends had uniformly acted with great caution,
not to speak to us of persons or things relative to their Monthly Meeting;
but that at the first Monthly Meeting I sat with him,
I heard sufficient from himself to convince me he
was acting under the influence of a wrong spirit,
warning him to take care or he would be dispossessed of
that seat in society which he professed so highly to prize;
and notwithstanding the confidence he manifested
that there was no danger such would be the case,
yet a few years after it took place.
He became much irritated, telling us, he did not expect to be so treated,
and left us in apparent displeasure.
We rather felt satisfied that this opportunity had occurred unsought for,
to clear our minds towards this individual.

Sixth-day attended Mountrath meeting,
and were comforted in believing there are yet preserved here,
as well as in other places in this nation,
those who are preferring Zion`'s prosperity to any worldly acquirement.
Seventh-day we proceeded to Mountmelick.
First-day morning attended meeting there, which was large;
and it proved a time of close exercise to get to the spring of Divine life.
The afternoon meeting was also trying,
yet I trust we were enabled faithfully to acquit ourselves as matter was given for utterance.
Second-day we visited the Provincial school,
my companion intending to proceed to her own home.
Third-day I rode to Edenderry, and sat with Friends of this meeting;
whose number is considerable, mostly young people.

Sixth-day, 3rd of second month, 1809, attended a meeting at Ballitore,
appointed at my request: the number of Friends here has now become very small:
the lamentation uttered formerly may truly be taken
up respecting this once flourishing meeting,
"`How is the city once full of people now become solitary,`" through some of those designed
to fill the vacant seats of the valiants who are gone to their eternal rest,
being led captive by notions and opinions which the Truth does not allow of,
but led their forefathers away from.
When the time came for my departure, it appeared some of the Friends were disappointed,
expecting I should have sat in their families, and had arranged matters accordingly; but,
as I had not a sufficient warrant, we parted under feelings of sincere regard,
considering it a favour the way was open in their minds to receive me.

First-day morning attended meeting at Carlow,
at the close of which I informed Friends of my prospect to visit families in their meeting,
in which service my kind friend William Neale proposed to accompany me;
which being united with, we entered on the visit this afternoon,
and were enabled to accomplish it on third-day.
In the afternoon we proceeded to Ballitore,
the way now clearly opening for me to sit with Friends in their families here,
not doubting but my moving in this backward and forward way,
is in the line of Divine appointment, however singular it may appear to some.
This evening Friends were called together, to whom I proposed a visit to the families,
which being united with, I proceeded therein.

Fifth-day attended the usual meeting, at which there appeared to be a general attendance,
and it proved a favoured parting season; and thus closed this visit,
with fresh cause on my part to set up my Ebenezer, and say,
hitherto it has been of Divine mercy and help that
I have been enabled to get on from day to day,
and that after all, the acknowledgment must be made, I am but an unprofitable servant;
the retrospect convincing me, that if the ground was to go over again,
there is room for amendment.

Sixth-day attended Monthly Meeting at Carlow:
a committee appointed by the Quarterly Meeting gave their attendance
to assist this meeting in its state of great weakness.
The preparative meeting of Ballitore having been long discontinued,
this subject was solidly entered into,
and an appointment made to assist in establishing it again:
a hope accompanied my mind that things were on the revival in this meeting,
there being a few left who appeared well-concerned for the good of the Society, and who,
by uniting the little strength left,
would be found quite equal to conduct such a meeting.
Seventh-day set off for Waterford;
from the heavy falls of rain the floods were so out that the water came into our carriage,
and for some time we were set fast in a quagmire up to our axletree.

We did not reach Waterford until late this evening,
and on first-day morning attended meeting there,
in which we were favoured to witness in a remarkable manner,
the solemnizing influence of Israel`'s Shepherd:
when the meeting for Divine worship closed.
Friends were requested to keep their seats, whereby this solemnity was not broken.
My late kind companion, Elizabeth Ridgway, and myself,
cast before Friends a prospect of religious duty to visit the drinking-houses
at Carrickon-Suir and on our way there and returning,
which obtained much solid deliberation and sympathy, it being a thickly settled, bigoted,
rough place, no Friend residing there and but very few Protestants,
the inhabitants being chiefly Roman Catholics.
We were liberated to pursue our prospect as Truth opened the way, and left Waterford,
accompanied by our kind friends Thomas Jacob and Rebecca Strangman, for Carrick,
taking the houses on our way,
in all eleven sittings with the keepers of the houses and sometimes the company,
most of which, if not all,
afforded us encouragement to pursue the arduous engagement we had before us,
expecting to have great difficulties to encounter.
In Carrick Friends were little known except as tradesmen and when passing through;
on our entering the town, we became the object of much remark,
which with the rude behaviour apparent in many,
made the encouragement I had taken from the manner we were received on our way,
of very short duration, plunged as I was into a feeling of deep distress.
I passed a sleepless night;
and in the morning felt very unequal to the day`'s work before us,
yet I durst not plead excuse.

After breakfast we left our lodging and proceeded in the visit:
for some time we found both houses and hearts open
to receive us and what we had to communicate.
A young man of respectable appearance followed us into a house,
(as it afterwards proved,) for the purpose of opposing us and laying waste our service,
by attempting to prove the lawfulness, as he called it, of the cheerful glass, saying,
Christ countenanced the cheerful glass by turning the water into wine;
and it was needful to encourage the sale of spirits
for the support of the revenue of the country.
After hearing him, I trust with becoming patience, our kind companion, Thomas Jacob,
replying to his remarks in a very suitable manner,
he was brought to acknowledge the sad consequences of drunkenness, and quietly left us.
After a few more visits we returned to our lodgings to take refreshment.

When we proceeded again,
it soon became manifest that the subject of our visit to these houses had gained publicity,
and the people beginning to follow us from house to house in crowds,
we feared would have had a tendency to interrupt our service,
but we were enabled to move on till it was time to take our dinner;
after which we sat awhile quietly together,
if so be we might be favoured to feel some additional strength.
But the people crowded round us, rushing into the houses,
and filling them so as to disquiet the minds of the owners,
that it appeared best for us to return to our lodging,
and wait until the bustle had a little subsided.
We again ventured out, and proceeded without much interruption,
except from two men at one house who opposed what we had to offer,
calling us antichrist,
saying their own priest could instruct them better than any other person,
and to him only they would pay attention.
This day we sat with the keepers of the houses,
and mostly also with those we found drinking in them.

Notwithstanding we became a gazing-stock to many,
and at times were dipped into a feeling of the sad effects of that
bigotry and prejudice which many had imbibed through education,
yet under a humbling sense that we had been moving in the line of Divine appointment,
thus far, cause for thankfulness was experienced,
and although some part of the dispensation permitted us was trying,
yet the retrospect afforded much encouragement to
go forward as Truth might open the way for us.

Third-day morning we left our lodgings,
soon after which a great crowd of persons followed us,
but by endeavouring to retire inward for help, our minds were borne up above them all,
and enabled to press forward from house to house, though not without a fear lest,
by the people crowding in after us, injury should be done to the houses,
or the people`'s property who kept them.
Although the houses would be so filled,
that there did not appear to be room for another to squeeze in,
yet quietness soon prevailed and was in a remarkable manner preserved,
especially whilst we were engaged in delivering our message: truly, we may say,
this was the Lord`'s doing,
and that we were able to come at any quiet in ourselves is marvellous in our eyes.
By our endeavouring to keep in the patience,
and to have our minds clothed with that love which would have all gathered,
taking quietly such insults as were offered,
and any opposition that was made to what we had to communicate,
the veil of prejudice would generally give way, love would beget love,
make way for free and open communication,
and for the opportunities closing satisfactorily,
as some of the people would themselves acknowledge.
We concluded to retire to a tavern in the neighbourhood where our work lay,
to take refreshment: a crowd had been with us most of the morning,
and following us to our tavern,
we proposed retiring to a room up-stairs to be quiet from the gaze of the people,
and proceeded accordingly; but we had not been long in our apartment,
before every vacant chair in the room was filled by persons apparently of some respectability.
At first we felt in difficulty how to act, our view being to take refreshment,
and sit with the keepers of the tavern:
as we could not see our way clear to leave the room, or request them to do so,
we invited the keepers of the house up-stairs, expecting,
when the visit to them was over, we should be quiet by ourselves.
They were accordingly invited up, with whom we had a quiet, free, open opportunity,
after which the company very respectfully departed,
we had reason to believe well satisfied;
two of them we understood were neighbouring magistrates.

Notwithstanding the crowd this afternoon was very great within and outside of the houses,
yet the people generally behaved quietly, and many were attentive.
On our way this evening to our inn,
a magistrate of the Roman Catholic persuasion meeting us, ordered the people to disperse,
saying,
if he had known of our intention he would have ordered
two of the police to attend upon us.
This evening we were favoured to close this engagement:
a fresh proof of what the Great Power is able to effect for us,
for truly we must acknowledge it to have been so.
Sometimes on entering a house, we found persons in a state of intoxication;
their companions, aware of our errand, boasted they would have liquor,
calling out for large quantities, but on our appearing not to notice them,
but to take our seats quietly amongst them, others would take pains to keep them still,
and, in time, all has been hushed into silence,
as much so as I have known in our own meeting.

Fifth-day morning we left Carrick, taking fifteen houses on our way to Pill town.
At one place the woman of the house left us, warning the people to follow her example;
her husband said her conduct was owing to prejudice, and he continued with us.
On our leaving one of the houses, we found a young woman standing in the passage,
as if she had been listening to what had been said;
her countenance attracted our attention, and we queried with her where she resided,
on which she appeared gladly to conduct us to her mother`'s house, who was a widow.
A young man also followed us, who had been with us at one of the sittings.
We had a religious opportunity with them at our parting;
and my companion had a favoured time in supplication, which crowned this day`'s work.
O, may my language ever be, when recurring to these four days`' labour of love,
"`Return unto thy rest,
O my soul,`" for thy merciful Lord has indeed done great and mighty things for thee.

A young man, a Roman Catholic,
whom we observed following us into several of the houses at Carrick,
met us on our road home, wishing for our company, saying,
he durst not come to us at our inn at Pill town,
as he lived in the neighbourhood and they would suspect him.
We informed him of the meeting at Waterford, to which he came on first-day,
and had an opportunity to unburden his mind a little.
It was evident he was fully convinced of the impositions
of their priests in presuming to forgive sins,
saying from a child he had not been a believer herein;
but it was clearly to be felt that he knew not how to shake
off the yoke of bondage he was labouring under,
adding, with seeming heart-rending feelings, "`There is my wife,
my relations--what is to become of my child?`"
We were aware what he alluded to--the persecution he must expect to meet
with if he declared his religious sentiments to be in opposition to theirs:
we gave him such advice as arose in our minds, and some suitable books.

Third-day attended the Monthly Meeting,
at which we gave in our report of the visit to Carrick,
which was satisfactory to our friends,
and I believe thankfulness was felt that we had been preserved from harm.
My companion spread a further prospect before the meeting,
of a visit to the drinking-houses at Ross and on the way there,
and feeling myself also bound to the service, I informed Friends to that effect;
after expressions of sympathy and unity with us in the engagement, we were liberated.
Fourth-day, 1st of third month, we left Waterford,
accompanied by our kind friends Thomas Jacob and Rebecca Strangman;
made seven visits on our way there,
in all of which there was cause for us to be encouraged:
we reached Ross about twelve o`'clock,
and proceeded as far as way opened before we took our dinner.
Fifth-day closed this visit, and with little exception we were kindly received.
One poor woman was very outrageous, frequently bidding us to go out of the house;
but her husband appeared grieved at her conduct.
In the afternoon we had a meeting with Friends to our comfort.
