== Chapter VIII.

Sixth-day, 21st of third month, 1811.
With certificates from my Monthly and Quarterly Meetings, I again left home for Ireland.
My prospect of crossing the water were more than ever discouraging;
my son-in-law`'s health was fast declining,
and my daughter`'s considered in great danger, whereby,
between duty to my Heavenly Father,
and those feelings of parental affection that were powerfully awakened in me,
my situation became almost insupportable; but as the command continued to be,
"`Go forward,`" I dared not hesitate.
Fifth-day, 4th of fourth month,
strength was in adorable mercy dispensed to rend
myself from my dear wife and afflicted children;
it was on all sides a heart-rending season,
there being no prospect of our all meeting again on this side the grave.

Reached Bath on seventh-day.
First-day attended the meeting there, which was large;
many not of our Society giving us their company.
To me it was a season of the renewal of that strength which
alone can support the poor mind in times of trial.
Attended Bristol meeting in the evening,
in which I was favoured to derive a little consolation,
from a belief my movements so far were ordered aright.
Hearing of a vessel to sail the following day, I went on board,
and after mature deliberation,
it appeared right for me to commit myself to the keeping of that Almighty Power,
whose sovereign commands are obeyed by the unstable elements of wind and sea.

Not sailing until third-day noon, I sat with Friends at Temple-street meeting,
to me a time of renewing covenant, and taking a view of the service before me,
accompanied by the language, "`If thou,
O merciful Helper of those who truly trust in thee, wilt but be with me in the way I go,
I am willing to do and to suffer whatsoever thou
mayst be pleased to permit to be my portion.`"
After meeting I went on board the vessel,
and although she did not promise all the accommodation the Milford packets furnish,
and was but indifferently manned, yet from a belief it was the way I was to proceed,
I felt comfortable.
We weighed anchor, but the wind soon turned against us; yet,
having the tide in our favour, we made our way several miles down the channel;
observing that the men were obliged to be frequently at the pump, was discouraging.
The tide turning, drove us back to Pill:
about twelve o`'clock on third-day night I went on shore at Sodbury.

Fifth-day went on board again, the wind continuing fair until seventh-day morning,
when our captain supposed we were within twenty leagues of Cork; but the wind dropped,
and a calm came on, our captain said,
exceeding anything he had known at this season of the year.
The men continued so frequently at the pumps,
that some of our ship`'s company manifested alarm on this account.
My mind was preserved in quiet under all,
from an evidence that I had not only observed the right time in moving,
but that it was not in my own will I had thus proceeded,
with an assurance that I should be landed safe on the shore of Ireland;
but I knew little of the trials that awaited us before that was fulfilled.

On seventh-day evening a tremendous storm arose:
our captain could not quit the deck the whole of the night.
I found it so difficult to keep in my berth, that I was obliged to lie on the cabin-floor.
The cracking of the vessel, as if she would part asunder,
and the pumps being almost continually at work, were truly awful:
towards morning the storm abated.
First-day morning we gained sight of Ireland.
About three o`'clock in the afternoon I went on shore at Passage,
and walked to my friend John Leckey`'s, at Black Rock.
A retrospect of the danger we had escaped,
furnished cause for thankfulness that we were preserved amidst so much danger,
being informed that a vessel was sunk near us during the night.
Second-day attended the select meeting;
and the few members of it were afresh incited to seek after religious courage,
which appears to be much wanting amongst this part of the body.
Friends were kind in renewing their invitations,
but it appeared to me my safety was in keeping quietly to my quarters.
Fifth-day attended the Monthly Meeting, and my certificates being read,
I opened my prospect of making a visit to the drinking-houses in the city and its neighbourhood,
which occupied considerable time.
A committee was nominated to assist me;
but it was concluded best not to enter upon the visit till after the Yearly Meeting.

Fifth-day evening, accompanied by Samuel Harris, we walked to Watergrass-hill.
Sixth-day to Clogheen; the day rainy, wind boisterous, and the road deep in dirt,
which made walking rather oppressive to nature,
yet we were enabled to proceed cheerfully to our journey`'s end.
On viewing the drinkinghouses at Watergrass-hill,
it felt to me as if a debt was contracted which at some future day must be discharged;
and in passing through Fermoy, I felt as if encompassed by its inhabitants,
attended with apprehensions I should have to return there also:
but how different were my feelings in passing through Kilworth
and Ballypooreen--nothing there to arrest my attention.
O the need there is to keep the eye single and the dependence simple, on the sure Guide,
in order to be rightly qualified to know our proper stopping places.
Seventh-day we proceeded to Clonmel: observing a company of men and women before us,
on their way to market, my mind was brought under exercise from an apprehension,
that my Master had some service for me if I stood resigned to do his will;
and yet it appeared to me I might expose myself to personal abuse if I
made the attempt to speak to them in a way they did not approve.

On reaching them we slackened our pace;
but how to introduce myself so as to obtain their attention,
I felt to be more than usually difficult.
I ventured to tell them, in a pleasant manner,
that I approved of my country fashion of walking with the women, giving them the arm,
and carrying the bundles, more than the fashion in Ireland, where the men take the lead,
and leave the women to follow after as well as they can,
and the women carrying the bundles; for the women being considered the weaker sex,
have claims on the men for all the assistance they can render them:
these remarks appeared to please the women better than some of their unfeeling husbands.
It opened my way to plead with them to be careful of their conduct at markets and fairs,
by avoiding to take strong drink,
and as ability was afforded to set before them the evil consequences,
as respected body and soul, that must attend a want of due care in this respect.
They appeared generally attentive, received kindly what was said, and, at our parting,
gave me their blessing.
The peaceful result of this little act of obedience I have not words to describe.
After this a young man who was a Roman Catholic joined us, manifesting an inquiring mind:
I queried if he had ever read the Bible; to which he replied,
he was not allowed to read the Bible; I advised him to procure one,
and endeavour to read it with a sincere desire to
understand for himself the truths therein contained:
he asked me, if I wished him to have one of our translation,
supposing it only to be true.
I told him he might give both theirs and ours an impartial, unprejudiced reading,
and then, I had no doubt,
he would be favoured to determine for himself which of them spoke the whole truth,
and nothing but the truth.
"`But,`" said he,
"`what is a man to do who must not have the Scriptures in his possession.
He must trust to others,`" meaning to his priest.
He appeared to hear with attention what was said, and parted from us in a friendly manner.
I frequently thought of him afterwards, pitying his bondage to the opinions of others,
who make a prey of such innocent minds as his appeared to be.
We were favoured to reach Clonmel in the evening, where I met with Henry Hull,
from New York, on a religious visit.

First-day attended morning meeting, which was large, and he had good service.
To keep silence appeared my place: what a mercy to know our proper place and keep in it.
Attended the afternoon meeting; took tea at the school on Suir Island,
and had a religious opportunity with the children:
thus closed another day to account for, in addition to the many gone before.

Second-day, the Quarterly Meeting for discipline commenced, and closed on third-day,
under a thankful sense that the great and good Shepherd
is still mindful of this part of his flock.
The parting meeting this evening was largely attended; and a favoured quiet time.
We were to proceed next day to Dublin in company with Henry Hull,
and I felt more than a freedom to inform him we were to pass through Kilkenny,
and that a place could be had for holding a meeting,
if he inclined to sit with the people.
After turning the subject in his mind,
it was concluded for us to make an early start next morning,
to allow time to give notice for a meeting in the evening.

Fourth-day we left Clonmel, and reached Kilkenny at noon.
Applying to one of the magistrates, we procured the use of the town-hall,
a spacious room for the purpose.
Passing through the streets, a woman used rude language to us; which,
with the contemptible manner in which some received the information of the meeting,
depressed me very much.
At our first sitting down, very few people assembled,
but in time the company collected freely.
Henry Hull had good service.
I was favoured, amidst my great discouragements,
to obtain relief from the exercise I was brought
under on account of the inhabitants when here before;
the way not then opening for me to have them called together.
Many solid countenances were to be observed in this crowded assembly, some of whom,
in a modest manner, expressed their satisfaction in being at the meeting;
and taking leave of us, quietly departed.
A person of respectable appearance told us, after the meeting,
he was surprised that the people kept their seats,
nearly the whole of them being Roman Catholics.

Fifth-day we rode to Ballitore.
In the evening called upon Friends pretty generally where
my attention was arrested with an apprehension of service,
and I trust I may say there was not a wilful withholding.
The day closed with a song of thanksgiving to Him who had
hitherto in mercy brought me through many difficulties.
Sixth-day several Friends came to our quarters before we departed,
with whom we had a time of solace.
May the praise be given to Him to whom only it is due, is the prayer of my soul!
We were favoured to reach our kind friends Jonas and Ann Stott`'s, who,
with their truly affectionate children, received us with wonted attention.

Seventh-day attended the select Yearly Meeting,
in which much wholesome counsel was imparted, and, in the evening,
a committee for conducting a fund, raised to apprentice out children,
belonging to Ulster province,
and for setting out in life young people who have conducted
themselves consistently with the rules of our Society.
A lively care was manifested to strengthen the weak places in that province, which care,
I doubt not, will be owned,
and the blessing of the poor rest on the faithful labourers in this good work.

First-day morning the opportunity of reading the Holy Scriptures
was owned by the overshadowing of the Divine presence,
a precious beginning of the day; may I be favoured to keep under it,
and not suffer it to be dissipated by unnecessary and trivial conversation.
Attended the meeting in Sycamore-alley,
many not in profession with us gave their attendance; and it proved a quiet,
favoured meeting.
The afternoon meeting was not so large.
I felt much for those who were called into active labour.
I believe I should have left the meeting more peaceful had I appeared in vocal supplication,
but to me it appears such an awful engagement, that I feel deeply before I can yield.

Second-day the Yearly Meeting commenced,
and continued its sittings until fifth-day evening, when it closed,
under a thankful sense that Divine help had been near in
transacting the several matters that came before it.
Sixth-day morning the parting meeting was held, which was largely attended,
and crowned with the good presence of Him,
who only is able to render our assembling together truly beneficial to us.
Seventh-day morning left Dublin, and felt sad, as if, in this place,
time would prove that bonds and afflictions awaited me.

Fourth-day reached Cork.
Fifth-day, 9th of fifth month, attended Monthly Meeting here; at the close of which,
I sat with the committee nominated to assist me in my visit to the drinking-houses.
10th of fifth month, accompanied by my kind friend James Abel,
I began the visit in Barrack-street.
In the first five calls we made, an openness was manifested to receive us, and, by some,
thankfulness expressed for the visit; but this smooth sailing did not continue,
for the next place we came to,
we met with a repulse from the daughter of the keeper of the house,
a girl appearing under twenty years of age, who told us, before a word was spoken,
that we were come to try to convert them and strike at their holy religion,
which was the only true one in the world.
She was soon joined by another young girl,
who set upon us as if they intended to do us mischief, calling us two devils, and saying,
if it was not for our respectable appearance, they would beat our heads flat.
We kept our seats quietly for awhile, and then made a move to depart.
I expected they would have given us some blows, from the countenance they put on,
but they hastened out before us to the next house,
to persuade the people to shut the door against us, which took place.
I felt much for my companion, who was a very meek-spirited man,
and a stranger to such tumultuous behaviour,
and began to fear this opposition would spread, but here it ended for this day.
After making about twenty-four visits to the keepers of houses,
and sometimes to their company, feeling myself much exhausted,
we concluded it best to retire to a Friend`'s house.

In the sittings on seventh-day we mostly met with a cordial reception;
yet I am ready at times to say, it is spending my time and strength for naught;
but feeling the necessity to persevere renewed from day to day,
I am made willing to expose myself to consequences,
from a belief the end will be crowned with peace,
if there is but a following on to know the Lord`'s will,
and a disposition cherished faithfully to perform it.

First-day morning attended meeting here, which was large,
as was the case in the afternoon.
It was pleasant to observe the improvement that had taken place in this meeting,
in keeping to the time appointed.
Second-day proceeded in a visit to the drinking-houses,
and we generally met with a kind and open reception, but the day proving wet,
and feeling exhausted with much walking in the dirt,
and the exercise of mind I had to pass through, I became discouraged,
and after making twenty-one visits, I was obliged to return to my quarters.

The visits on third-day were generally well received; but on fourth-day,
after making six visits,
my discouragements were such as to induce me to give up for this day.
My kind friend William Wright now became my helper, for whom I felt much,
considering his natural diffidence and timidity.
Sixth-day we proceeded;
and the Good Master made way for us in the minds of those we sat with;
nothing occurring that could be called unpleasant,
except our being obliged to quit one part of the city and proceed to another,
to get from the crowd of people that followed us into the houses.

Second-day, very feeble in body and mind, unequal of myself to the task before me;
yet fearing to become a loiterer, and by that means get into perplexity,
I proceeded to join my companion William Wright, and try to do my best.
We were favoured to get along comfortably to ourselves,
yet not without some interruption from a number of rude women, near the great market,
who followed us into a house, dancing and calling for whiskey,
and behaving otherwise insultingly,
so much so that we left the market and proceeded to another part of the city.

Third-day proceeded to Blackpool; and the houses being situated near to each other,
I anticipated making many more visits today than I found myself equal to accomplish,
although there was a willingness,
both on the part of the keepers of the houses and their company,
to receive what was imparted, and, in many instances, thankfulness was manifested;
some saying,
"`Our priest does not give such proof of his care for our
welfare:`" I became so exhausted I was obliged to retreat,
after having made twenty visits.

The sittings on fourth-day were encouraging; two especially,
one with a new-married couple, and one where five young men of respectable appearance,
in addition to the landlord, gave us their company.
Earnest are my desires that faithfulness may obtain
the victory over the slavish fear of man.
Fifth-day attended the usual meeting,
in which I was favoured to experience my faith renewed in the sufficiency of
the Divine power to enable man to do his will on earth as it is done in heaven,
and to crave an increasing acquaintance with its fulfilment.
Sixth-day we had twenty-three sittings;
and generally much willingness was manifested to receive what was communicated.

After one of the opportunities,
the man of the house requested leave to express what was on his mind;
the substance of which was nearly as follows:
"`Where are the faithful Quakers in this day?
where is the Fox and the Penn?
Go speak to the government, for if your mission does not extend beyond this,
it is doing but little.
I wish all the world were Quakers,
for I believe them to be the nearest to the truth of any sect;
but money has done that for them which persecution could not:
by their seeking after money they are become very much like other people again.`"

Seventh-day made several visits satisfactorily to ourselves,
until we came to Devonshire Marsh and Square; here, from the repulse we met with,
and the fear the people manifested to remain with us,
it was evident the priest had prejudiced their minds.
At one place, when I was requesting the woman of the house to give us her company,
a dirty looking man, who was taking his pint of beer at the bar,
after filling his mouth squirted it in my face and bosom,
telling me to take that for Jesus Christ`'s sake, declaring he would go for the poker,
and left us as if he was determined to put his threat in practice;
but it did not discourage me,
feeling the assurance he would not be permitted to hurt a hair of my head.
I was mercifully preserved in the quiet, and we saw no more of him.
After waiting awhile it appeared best to pass this house for the present.
A man followed us to the next house to insult us, asking me to give him whiskey,
and the woman of the house ran away from us, saying,
she had better instructors than we were.
As it was evident the influence of the priest was great in this neighbourhood,
and feeling my bodily strength much enfeebled we proceeded no further this day,
concluding to make an attempt in this neighbourhood at a future time.
In the afternoon rode down to Passage,
where after the storms of this day I found a quiet peaceful retreat.

First-day attended the two meetings, both of which were large,
and I felt truly thankful my lot was cast with my dear friends of Cork.
Second-day, proceeded to the house in Marketlane,
where the rude behaviour of the marketwomen obliged us to quit before.
On our entering the lane, the market-women observing us, came in haste,
soon filling the house: this circumstance,
and the people of the house not manifesting a disposition to receive us,
was rather discouraging.
One woman inclined to be wanton,
but I was supported by holy help to keep my standing quietly amongst them:
pausing awhile, I requested them to be sober, and, as if with one accord,
quietness prevailed,
which continued until I had fully relieved my mind to the
keepers of the house and then to the company assembled,
all appearing attentive and civil at our parting.
We then proceeded to the house where the man squirted the beer over me;
and had an agreeable opportunity with the mistress of it,
who expressed her regret I was so treated when there before.
Twenty-one visits closed this day, with fresh cause to set up my Ebenezer and say,
thus far the Lord has made way for us in the minds of those we have met with.

Third-day our engagements lay in Blarney-lane and the two markets,
which for awhile proved discouraging beyond words to set forth.
A zealous Roman Catholic woman ordered us out of her house, saying,
the devil had sent us there, following us to the next house,
and reprimanding the keepers of it for letting us in, saying,
two such devils came into her house to convert the people, to ruin them,
and she would fetch something to do us a mischief.
All fear as respected myself was removed from my mind,
yet I felt for those who accompanied me: I expected she would proceed to other houses,
but here her resentment ended:
our visits after this repulse were generally satisfactory to ourselves, and,
for aught we could observe, to those we visited in this low and miserable neighbourhood.
The dirt and filthy fumes we had to endure,
on any other occasion would have been almost insupportable,
but when we are favoured to experience the right thing to be uppermost in our minds,
so that it becomes our meat and drink to do our Divine Master`'s will, everything trying,
and which human nature would recoil at, is buried out of sight.

Fourth-day, accompanied by my kind friend Edward Carrol,
finished in Blarney-lane and the inns and taverns, which closed this arduous engagement.
Fifth-day I spread before the committee a prospect of making a visit to the mayor,
sheriffs, and Protestant and Roman Catholic bishops: after deliberating on my proposals,
I was left at liberty,
my friends kindly engaging to do their part towards their being effected.
Seventh-day, proceeded to the mansion-house, where the mayor, sheriffs,
and deputy-mayor were in readiness to receive us.

We next proceeded to the Protestant bishop, who also received us kindly,
expressing his desire the service I had been engaged in might have its use.
The Roman Catholic bishop was in England;
and the way opened in my mind to attempt an opportunity
with the next in authority of the Catholic clergy.
On inquiry, it appeared he was indisposed,
and a great pleader for their religious rites and ceremonies;
but as the engagement felt to me unfinished,
I could not see any way to bring it to a suitable close,
but by the offer of a visit to him.

First-day;
on my way to meeting this morning I rejoiced in observing the early
attention by the mayor and sheriffs to the remarks made to them,
the whiskey-shops being shut up, and the exhibiting of bills,
notifying the theatrical performances, totally done away.

Fourth-day morning, accompanied by my kind friend John Leckey,
we proceeded to the residence of the bishop`'s deputy,
who received us with marks of kindness; after sitting a short time in silence,
I endeavoured, I humbly hope I may say,
faithfully to lay before him what appeared to be the counsel of my Divine Master:
he heard me patiently, and after I had done, remained silent for some time,
then requested leave to say a little;
and expressed in strong terms his approval of the principal part of what I had said,
yet there was one thing in which he thought I was mistaken, viz:
that his endeavouring to effect sobriety among the
people would only be like lopping off the branches,
so long as the people believed confession to the
priest and absolution from him was enough.
I replied, that confession to the priest and a dependence on him for absolution,
must be done away before the root of this evil of drunkenness, so prevalent,
would be thoroughly struck at;
their dependence upon the priest defeating the work of conscience.
So far as my observation has gone in visiting the drinking-houses,
it has not appeared to me that the people are ignorant of that law in the heart,
that tells them what they must do and what they must leave undone,
in order to stand approved in the sight of God;
but when advised to attend to this law within, they reply,
"`We are not to think for ourselves, but the church must think for us,
and our priests are our church, and whatsoever they bid us we must do.`"
After urging the necessity of the people`'s being
brought off from all such erroneous principles,
he replied, "`If I was to preach such doctrine as this to my people,
I should soon lose them; we must keep them in ignorance to keep them at all.`"
He expressed his approval of the service I had recently accomplished, and of this visit,
saying, he hoped it would tend to stir him up to a more faithful discharge of duty.
I was now able to free my friends from any further care about me,
and I trust it might be said,
we united in thankfulness to the alone sure Helper of his dependent children,
for thus mercifully bringing us safely through,
causing Jordan to stand on heaps when the floods appeared at times
ready to overwhelm me:--but my exercises were not at an end.

On my return to my quarters a letter awaited me,
giving an account of the death of my dear son-in-law,
whom I left in a declining state of health, one of his executors urging my return home.
I felt myself brought into a great strait,
the duty which in the first place I owed to my Almighty Creator pressing hard upon me,
and the feelings of affection afresh awakened in my breast, for my widowed daughter,
in declining health, and her infant son.
I laid my trying situation before my friends, and cast myself upon them for disposal;
but they considering themselves unequal to such a task, committed me to Divine direction.
I never felt more the need of Divine counsel, and, perhaps,
never more earnestly sought after it.
When I looked towards returning at this time to England,
a dread of consequences attended my mind,
with an assurance that so far from being helpful
in arranging and settling my son-in-law`'s affairs,
I should be a hinderance; but if I pursued my prospects as way opened,
they would be well cared for; and I durst do no other than write to this effect,
requesting those who were on the spot to pay the best attention they were capable of,
until what I had in prospect on this side of the water was fully accomplished.

On my return home I had cause to be well satisfied,
from an assurance all had been done towards arranging my
son-in-law`'s affairs in my absence that could be done.
I had cause, when the subject of these my trials in Ireland came before me,
to feel thankful to my Divine Caretaker,
that parental affection did not turn me aside from the path of religious duty.

Fifth-day attended the Monthly Meeting: some difficult cases coming before it,
occasioned much exercise of mind to those who were rightly engaged,
that the wholesome discipline established should be maintained.
First-day morning attended meeting here,
after which I met the committee appointed to assist me in visiting the drinking-houses,
to whom I proposed proceeding to Limerick,
taking the drinking-houses in my way at Watergrasshill, Rathcormack, and Furmagh;
after which I withdrew, leaving the subject to the committee to dispose of,
as in the wisdom of Truth they should see best.

Third-day morning, accompanied by Samuel Harris, we proceeded to Watergrass-hill:
the houses were much thronged with company returning from a burial,
yet this did not appear any interruption to my service,
the people being generally quiet and attentive, except in one place,
where a declaration was made,
that it was impossible to be saved out of the pale of the Romish church,
and that all advice but that which came from a Romish priest was unavailing.

We next proceeded to Rathcormack, a small decayed town on our way to Furmagh:
the report of our arrival was soon spread,
and appeared to raise the whole of the inhabitants, whereby we had large companies,
with whom I had to labour,
not only to set before them the evil consequences of taking too much strong drink,
but also to point out to them the sure way of life and salvation,
with the absolute need of ceasing from all dependence upon man,
and depending singly and simply on the Lord alone for preservation and salvation.
Many of our company acknowledged the truth of what was communicated,
and I left Rathcormack truly thankful to my Divine
Master who had invested me with courage to be faithful.
The danger of incurring the resentment of the Roman Catholics
appears far greater when addressing them on the ground of
religion than immorality. We reached Furmagh in the evening,
but too much exhausted to attempt to proceed.

Fourth-day, 12th of sixth month.
Furmagh is principally a new-built town with very extensive barracks,
the inhabitants chiefly depending on the military for their support.
The thoughts of turning out this morning appeared very formidable;
and whilst ruminating on the apparent trials that awaited us,
a dear friend from Cork unexpectedly entered the room:
never was I more rejoiced than at seeing him, which led me secretly to exclaim:
How can I refuse to serve such a Master who so wonderfully cares for me,
helping and sending helpers in my times of extremity.
May none of the few remaining years of my life be marked
by ingratitude to such a long-suffering merciful God!
This unlooked-for addition cheered my mind.
The time being come for us to proceed, Edward Carrol,
Samuel Harris and myself moved towards the barracks.
Our first visit did not afford us encouragement to hope
we should make our way with the keepers of the houses here;
no disposition being manifested on the part of the landlord to receive us, saying,
he knew his duty as well as the best clergyman in the nation: being very full of talk,
we quietly left him, and proceeded to the next house,
where the face of things wore a more agreeable aspect.
We were enabled to accomplish twenty-six visits this day.
One man told us, no alms-deeds, no good works, no sacrifices, no Jew, no Turk,
no religion could enter the kingdom, none but Roman Catholics would be admitted.

Fifth-day, many of the opportunities were amongst as rough,
untutored a set of human beings, as I ever before met with;
yet in many of them seriousness was excited beyond what could have been expected.
One man expressed his desire I would accept of money; and a woman,
who at first appeared rude, became thoughtful, and thanked us for the counsel given.
At another place, a young man`'s countenance appeared very savage towards us,
and he was not willing to hear me; on our being about to depart I offered him my hand,
which he refused, appearing disposed to give me a blow, but as matter presented,
I expressed it to him, and he appeared much changed in his disposition,
and at our parting kindly gave me his hand.
At one place on the outside of the town, the room we entered not being ceiled,
those who were above poured dirty water upon us,
but we were preserved above noticing their rude behaviour in this respect.
The people crowded in after us, amongst whom was a woman in a state of intoxication,
who kept dancing and otherwise making a disturbance:
discouraging as the prospect of our situation appeared, I durst not quit,
but kept my standing amongst them,
my mind being turned to my only sure Helper and support.
The house shortly became so crowded no more could well enter;
one man had a large butcher`'s knife unsheathed in his hand,
which made a terrific appearance, but I was mercifully carried above all discouragements,
which I hope I esteemed an unspeakable favour.
I understood this was not the case with my companion Samuel Harris,
he acknowledging he felt not a little alarmed for our safety,
looking at the lonely situation of the house, the company by which we were enclosed,
and the man with the butcher`'s knife in his hand.
After a while I requested that endeavours might be used
to keep the woman who was in a state of intoxication quiet,
and that they would cease conversing, which they complied with,
and quietness took place beyond what might have been expected,
affording me a full opportunity to relieve my mind, after which the people separated,
apparently satisfied, and in an orderly manner.

On entering one house the woman ran out as if she considered us dangerous persons:
from her husband`'s account, who gave us his company,
the priest had cursed all the houses that should receive us.
Although I felt nearly exhausted,
yet the prospect of coming to a speedy close prompted me to persevere,
and after thirty-four sittings this visit closed.
The three last abundantly compensated for all the
rough and rugged roads we had to travel over.
I passed a sleepless night,
not being able to see my way out of Furmagh without attempting
an opportunity with the head of the Romish clergy here.
Sixth-day morning, I informed my companions, and they kindly offering to accompany me,
we proceeded to his residence: understanding he was a man who thought much of himself,
high in his manners, a great bigot, and one of whom the people stood in terror,
plunged me into deep suffering of mind;
yet I found it would not do to yield to the slavish fear of man,
but there must be an earnest seeking to the Lord to be endued
with courage proportioned to the labour of the day.

He received us with apparent kindness, and,
as if he thought by making him this visit we had done him an honour.
After a pause,
I informed him of my religious engagement in visiting the drinking-houses in Furmagh,
and the state of mind many of those I had visited were in,
laying before him the circumstance related by one of his flock,
that a curse was pronounced upon all the houses that received us,
at which he appeared not a little confused, replying,
he knew not what the clergy under him might have done, adding,
their people were positively charged not to hear things of a religious
tendency from any but their own clergy on pain of incurring excommunication.
I endeavoured to acquit myself faithfully towards him, although he became very irritable,
and endeavoured many times to drown my voice by opening and shutting some drawers,
with as much violence as he appeared capable of.
This not discouraging me from proceeding to give
him that which I had in commission for him,
he rang the bell, ordered his servant to saddle his horse, and bring him out,
although it was as wet a day as most I have seen, and continued raining hard.
Seeing these orders did not move me, he rang his bell again,
and ordered his servant to open the door and show us the way out,
but this was not effected until I had endeavoured to leave with
him the whole of that which I apprehended was given me for him.
At our parting I gave him my hand, which he accepted.
Feeling clear of Furmagh my kind companions returned to Cork.

First-day attended meeting at Limerick:
at the close of the morning meeting I informed Friends of my prospect to visit the drinking-houses;
and arrangements were made for my proceeding on second-day.
Second-day we proceeded to Irish-town, and made twenty visits; generally well received.
I often thought of my companion`'s observation when alike engaged at Clonmel;
the Master appeared to go before us and prepare the way.

Third-day, proceeded towards the Old-town, the cross streets and lanes;
and in most instances were well received.
My companion often saying, he thought good was to be felt amongst those we sat with,
and marks of kindness were offered by some at our parting; yet we had our trials.
At one place, a woman and her daughter violently resented our attempt to give them advice.
The young woman and a man followed us to the next house,
persuading the people not to receive us, saying, we were influenced by the devil,
were false prophets, and false teachers come to ruin the people,
threatening the man of the house they would report
him to his priest if he did not turn us out,
and he would be cursed from the altar if he heard what we had to say.
During this, I felt that silence was my proper place, taking my seat quietly.
After awhile the man and woman left us; and the man of the house said,
he should hear whom he pleased, behaved respectfully,
and expressed his satisfaction with the visit.

On my return to my quarters this evening, I found another letter from my family,
urging the necessity of my lending my help to my widowed daughter`'s temporal concerns,
which occasioned me some conflicts before I had strength
given me to relinquish the prospect of returning home.
The pleadings of natural affection were powerful,
and the struggle to overcome them very great; yet my duty to my Creator,
which demanded my remaining where I was until the language was distinctly
proclaimed in the ear of my soul,--It is enough--obtained the victory,
under an assurance that her affairs, as well as herself and her fatherless child,
were under a better caretaker than I could be.
After writing suitably on the occasion, I proceeded; and yet, at times,
human nature found it hard work to move along under the weight
of considerations that would crowd into the mind on this subject.

Fourth-day, we made twenty-one visits; and it proved a trying day,
from the crowd of people that followed us.
I felt much for my companions, who were new in this work.
Fifth-day attended the usual meeting; and after meeting we proceeded to Irish-town.
Some of the visits were trying,
but cause was felt for thankfulness that others were satisfactory.

Sixth-day my kind friend Samuel Alexander, feeling, as he acknowledged,
bound to accompany me, we proceeded principally to Englishtown, and the back lanes.
Some of our visits today were so exercising,
that I was almost ready to give over proceeding further.
We were persuaded that these difficulties originated in the interference of the priest;
but the way at other times was so remarkably made for us,
that it administered fresh encouragement.

At one place we had a large congregation of different descriptions;
some who appeared persons of respectability, others without shoe or stocking,
and in rags.
We were so closely packed together, that I did not expect much quiet could be come at,
but after a short time,
the calming influence of the heavenly Father`'s love spread over us;
and all was hushed into stillness.
I had to declare amongst them the utter insufficiency of
placing our dependence on man for the means of salvation,
and that those who were so doing would ultimately find they had
been building their hopes of salvation on a sandy foundation;
it appeared to be well received; and at our parting,
many expressed their thankfulness for the opportunity,
and their unity with what had been said,
and sincere desires for my safe return and future welfare.
I humbly hope I may say,
this day closed with rendering all the praise to God and Christ Jesus,
to whom only it belongs.

Seventh-day my bodily strength was so enfeebled by exercise of mind,
the closeness of the rooms occasioned by the large companies that followed us,
and the filth which we had at times to sit down in; that but little was accomplished:
so far another week closed to account for to God--He who knows our most secret thoughts,
and will judge us according to our motive to action.

Second-day, closed the visit to the drinking houses.
Here I found it laid upon me to inform Friends of my prospect
to make a visit to the head of the Romish clergy,
which being united with, James Fisher accompanied me next morning to his house,
agreeably to his own appointment: he received us with marks of kindness.
My mind was brought under exercise that I might be preserved from temporizing,
or giving any just occasion for him to take offence at anything I might say.
In the course of our exchange of sentiments, he expressed his desire,
if he was favoured to reach heaven, we might meet there, in which I united, saying,
I believed if I was favoured to reach heaven at last,
I should there meet with the sincere, upright-hearted of all religious denominations;
to which he replied, there is but one true God, one true faith, one true church;
and that he believed theirs was the only true church, because it had stood the longest,
and that there was no salvation out of it.
So that it appeared,
the desire which he expressed to meet me in heaven was built on the hope
of my being converted to their faith and mode of religious action.
I reminded him of the testimony of the apostle Peter,
"`I perceive of a truth that God is no respecter of persons, but in every nation,
he that feareth him and worketh righteousness is accepted with him.`"
Although we so widely differed in our sentiments in religious matters,
yet we parted in a friendly manner.
The way now clearly opened for me to leave Limerick.
Fourth-day morning left my kind friend Joseph Massey Harvey, and many Friends here,
who came to take a final farewell.
Reached Clogheen this evening.

Fifth-day proceeded in a visit to the drinking-houses there,
in which we were generally well received.
We were followed by two men, of thoughtful countenances, to several of the houses.
A man, about middle age, appeared much tendered in one of the opportunities:
the chief of those we visited here and elsewhere are Roman Catholics,
for whom I often felt much,
on account of their being such bond-slaves to what they call the church.
Their priests rule over them as with a rod of iron.
Sixth-day morning proceeded to visit the drinking-houses at Caher.
After we had made nineteen visits,
I felt so much exhausted that I was obliged to give over for this day:
most of the opportunities were satisfactory.

Seventh-day we understood the priest had been at work to prevent our proceeding,
which occasioned our being refused in several places;
but turning our course towards the bridge, we found a willingness to receive us.
In addition to the man and his daughter,
we had a large company in and outside of the house.
The young woman at first was giddy,
and endeavoured to produce the like disposition in a young man;
but after awhile she appeared brought down, continuing to manifest more thoughtfulness.
The people behaved solidly,
and at our parting expressed their thankfulness for what had been communicated.
After this, we had the closing opportunity with another large company,
who flocked to the house on our approaching it,
to whom I humbly hope I may say I was enabled to preach the way of life and salvation.
On our shaking hands when we parted, many of their countenances appeared solid.
This afternoon I rode to Tincurry,
and on my way was painfully affected in beholding the men and boys lying by the roadside,
and idling at their cabin-doors; not a man to be seen at labour on the land.
Having heard much complaining about the weather being unfavourable
for the farmers getting their crops into the ground;
and the weather now becoming very favourable for this purpose,
it occasioned me to inquire how it was the farming business was at such a total stand.

I was informed it was one of the Roman Catholic idle days, or, as they call them,
holy days, and that it was the second they had kept this week.
Nearly two-thirds of the time of the poor is thus passed over,
going to mass in the morning, and the remainder of the day spent in idleness,
getting drunk, quarrelling and fighting,
whilst the land is suffering for want of their labour:--no
marvel they appear so destitute of outward comforts.
O, how will these heart-hearted task-masters, their leaders--their priests,
who enjoin them to cease from labour on these days,
account for their conduct in the great day of reckoning;
keeping these poor creatures in a state of darkness and cruel bondage to their own self-interest,
being, as they are,
instrumental in depriving them of the means of procuring for themselves
and families the comforts of the present life,
and standing in the way of their endeavouring to secure an eternal inheritance!
I at times lament their pitiful situation; and,
however distant the deliverance of these poor people from this servile bondage may be,
if my feelings do not deceive me, it is in progress,
and when the time is fully come for its accomplishment,
all the opposition it may meet with from these enemies to all right reformation,
the priests, will be of no avail.
During my times of inward quiet,
my attention was awakened to an apprehension of duty to return to Caher,
and to attempt an opportunity with the head of the Romish clergy there.

First-day attended meeting at Garryroan,
and at the close the subject of a visit to the head
of the Romish clergy at Caher pressing on my mind,
I informed my friends, who liberated me to the service.

Second-day, 1st of seventh month.
We proceeded to his house and he received us civilly.
After a suitable pause,
I endeavoured to lay before him the consequences that must result
from the people placing such implicit confidence on the clergy.
He replied,
it was needful the people should be kept dependent on the true church for instruction,
which, he said, was the priest, having descended from the apostle Peter.
I requested him to point out to me where Christ commanded
the keeping of those days they call holy days,
that were spent in idleness,
whilst their families almost wanted bread and sufficient clothing;
their land suffering for want of their labour,
and they frequently passing these days in drunkenness, quarrelling and fighting:
the drinking-houses being mostly crowded on these days.
He said it was the order of the church that these days should be kept,
and the order of the church must be obeyed.
He appeared to part from us in a friendly manner.
If my visits to this description of men only prove like a fresh stirring up,
awakening their attention in ever so small a degree,
to the consideration of their doings,
it may be worth my suffering what I may have at times passed through on their account.

Feeling myself now clear of Caher, I proceeded to Waterford,
and next day attended Monthly Meeting there.
The meeting for worship was small;
at the breaking up of which several Friends were
waiting in the lobby to attend the Monthly Meeting,
which brought me under exercise,
from a persuasion that those who thus willingly neglect
these times of preparation for true usefulness in the church,
the meetings for worship held previous to entering upon the business of the Society,
become as dead weights and burdens in our meetings for discipline,
instead of rightly helping the business forward.
I suffered the meeting to proceed in its business without, as I should have done,
faithfully spreading before it these prospects, fearing lest I should give offence;
but as my unfaithfulness rendered me unfit to give proper
attention to matters that came before the meeting,
I endeavoured to obtain relief to my mind; but I never find this after-time so effectual,
either to myself or the meeting, as when the proper time for speaking is attended to.

Fifth-day attended Monthly Meeting at Clonmel,
feeling thankful in having the opportunity again of sitting with Friends of this meeting,
and observing the continued care manifested for the welfare
of the cause they were engaged in the support of.
Sixth-day proceeded towards Dublin,
which place I was favoured to reach safely on seventh-day.
