== Chapter XI.

In the spring of the year 1812, in the neighbourhood of Huddersfield,
and places adjacent, a large company of men collected;
entered in the night time the houses and workshops of such as employed machinery,
destroying machines, stealing arms, and other property; and, in the fourth month,
one of the master manufacturers was murdered on his return from market.
For a long time they continued to commit great depredations,
becoming a terror to the inhabitants; but through the vigilance of some magistrates,
a discovery was made of many of the offenders,
and they were committed to the castle at York: a special assize was held there,
by commission, in the first-month, 1813,
in order to their being brought to trial for the
several offences they stood charged with.
Some were acquitted, others discharged on bail, one was ordered for transportation,
and seventeen suffered death at York.
Hearing that the sentence of the law on these latter had been enforced,
my mind was brought under such feelings of sympathy with
the widows and fatherless children of the sufferers,
that I believed I should not stand acquitted in the sight of my Divine Master,
unless I was willing to go and sit with them in their families;
and yet the prospect of such a service felt humiliating, beyond words to describe.
Understanding my friend Joseph Wood, of Highflats meeting, was under a similar exercise,
in the second month we spread our concern before Friends,
on which the meeting gave us a minute to proceed therein, as Truth opened our way.

First-day, 28th of second month, I left Barnsley on foot,
and reached Paddock meeting-house in due time for meeting,
where I met with my companion Joseph Wood.
Some close religious labour with our kind friends of this meeting being required of us,
a sense of having endeavoured through holy help, to discharge our duty,
afresh animated us to look with confidence for help from this same Divine source,
in the prosecution of the arduous engagement before us.
At the close of the meeting we spread our religious prospect before Friends,
and presented the minute of our Monthly Meeting.
Friends of Paddock meeting being previously informed of our intention,
made arrangements for our accommodation.

After dining, we proceeded to the house of the widow and five children of Jonah Dean,
of Long-royd Bridge, who suffered for rioting.
Her mind appeared to be under very great distress, with her helpless,
fatherless children; the oldest child being about eight years,
the youngest not more months old.
All that was capable of feeling for her,
plunged as she was into such accumulated distress, we felt to be brought into action.
We next visited the widow and three children of John Walker, who suffered for rioting,
one of the children an infant at the breast.
The feelings of distress awakened in my mind, in sitting down with this family,
were such,
that I was tempted to conclude human nature could
hardly endure to proceed with the visit before us.
We endeavoured in both cases to impart such counsel as came before our minds,
and had reason to hope their being thus noticed, had a tendency, in some small degree,
to add a ray of comfort to their deeply-tried minds.

After tea, feeling my bodily strength a little recruited,
we proceeded to the mournful house of the parents of
G+++______+++ M+++______+++, a single young man,
and one of those concerned in the murder of the master-manufacturer.
We sat with the parents, who are in a respectable line of life.
In this opportunity we had fresh cause to acknowledge that holy help was near,
furnishing matter suitable to the afflicted state of mind in which we found them;
whilst we endeavoured to be upon our guard that nothing escaped our lips,
that should be the means of unnecessarily wounding their feelings.
Our visit was thankfully received by both parents,
and was like a morsel of bread at a time when they appeared almost ready to famish.
The father acknowledged,
that the melancholy circumstance had brought their minds into such a state,
that they had concluded to move to some other part of the country;
but our visit had tended to settle them down in their present place of residence.

Second-day, we bent our course to Lockwood,
and sat with the widow and three children of Thomas Brook, who suffered for rioting.
We also had the company of his parents,
and two brothers who had been in York castle with him, but were discharged.
This proved a heart-rending opportunity to us all: being willing, as I humbly hope,
to sit where the surviving sufferers sat,
we were helped to go down into suffering with them,
and thereby qualified through the renewal of Divine aid,
to administer suitably to their need.
Our minds were clothed with feelings of compassion
for the widow and the deeply-afflicted parents,
accompanied with a hope,
that the opportunity had made an impression on the minds of the two young men,
which would be of lasting benefit to them.
The sufferer, we were informed, had only been out once with the rioters,
at which time he lost his hat, which caused his apprehension.
At our parting,
they endeavoured to make us sensible that our visit had been cordial to their minds,
and expressed the thankfulness which they felt for it.
We proceeded to Huddersfield; visited the widow of James Haigh, who suffered for rioting;
he left no children: we found her under deep affliction.
She appeared to have a clear view of our motives, expressing, in strong terms,
the gratitude she felt for our visit.
Our next visit was to the parents and two sisters of E+++______+++ T+++______+++,
who was a single man, and who suffered for the murder of the master manufacturer:
we felt deeply for the afflicted parents.
Divine regard was mercifully extended in this opportunity, both to visited and visitors:
that a grateful sense thereof may continue in each of our minds,
was the secret prayer of my soul.
It appeared a time of precious visitation to the sisters of the sufferer.

In the afternoon we proceeded to Cow-cliff,
to visit the widow and two children of John Ogden, who suffered for rioting.
We proposed to meet her at her husband`'s parents, in order to have their company,
and that of two of the sufferer`'s sisters; but we were given to understand,
that the parents spurned at the idea of sitting with us.
As it did not appear to me we should be warranted in giving up this prospect,
and apprehending I felt that in my own mind which would bear me out,
in taking the widow and family with us into their cottage, my companion consenting,
we did so, and took our seats amongst them.
After sitting awhile in solemn silence,
we had to hand forth both caution and encouragement, especially to the poor young widow,
and the sufferer`'s sisters; and it proved to all a melting season.
The parents were both confined to the house,
in consequence of the melancholy event that had occurred respecting their son,
and from their appearance, with that of one of their daughters,
they were sinking under the weight of their afflictions.
The parents, in a very feeling manner, expressed thankfulness for our visit,
and feelings of gratitude clothed my mind.
The wedding of a sister of the sufferer`'s being kept at the adjoining cottage,
apprehending it would be safest for us to make them a visit, we accordingly did so,
but the men were all absent.
Feeling something in my mind towards the bride and her female friends, I gave way to it,
and the labour bestowed soon put aside all their light behaviour,
which our presence at first excited.
May glory abound to his praise, who is God over all, blessed forever, and forevermore.

Third-day, accompanied by John King and James Lees, Friends of Brighouse meeting,
we proceeded to Sutcliffe-wood-bottom, to sit with the parents of Thomas Smith,
his sister, and her husband--he also suffered for rioting.
At the time I was engaged in addressing the company, a young man opened the door,
came in, and immediately left again; on which I felt a stop against proceeding,
and was obliged to request the young man might be sought for to give us his company,
which taking place, I proceeded.
This young man`'s mind was wrought upon in the opportunity,
and after having closed what I had given me for the family,
my mouth was again opened with nearly these words:--"`It
is not in man that walketh to direct his own steps aright,
the Lord alone must have the ordering of them, who does at times order our steps,
but we know it not;
which appears to me to have been the case this day with
the young man who came in amongst us;`" after which,
my companion addressed him in a very feeling manner.
After the opportunity was over, he walked with us a short distance:
his mind appeared much broken, and under a remarkable visitation.
He told my companion, he had been apprehended with the rest of the prisoners,
and confined in the castle, but was discharged on bail;
that he was twenty-two years of age, and his name was I+++______+++ S+++______+++;
that he knew nothing of our being in the house, nor could he tell what brought him there,
as he had no business with the family.

In the afternoon we went to Scar-coat-green.
Our first visit was to the widow and five children of Nathaniel Hoyle,
who suffered for robbery: they lived with her aged father and sister, who sat with us,
and who appeared to be under great difficulty to procure the necessaries of life:
their situation appeared to be very pitiable.
We next proceeded to the house of James Hay, who left a widow,
not twenty-one years of age, and two children:
the sufferer`'s parents gave us their company,
and we were favoured with a comfortable time together.
We went into the cottage of the parents;
had a satisfactory opportunity with two brothers of the sufferer,
and then proceeded to Handgreen:
the father of James Hay very acceptably gave us his company.

Fourth-day, we went to Sowerby-bridge.
Our first visit was to the widow of Joseph Crowder, who suffered for robbery:
he had left three children, and his widow near being confined with her fourth.
We encouraged her to persevere in an endeavour after
a steady reliance on that Divine power,
which alone would be sufficient to support her mind in future tossings and temptations;
and we were ready to hope the opportunity would be remembered at a future day,
to her comfort.
We next proceeded to the cottage of the parents of William Hartley,
who suffered for robbery: with them resided his eight children, bereft of both parents,
the mother having been deceased about three weeks.
The neighbours observing us go into their cottage, followed us,
quietly taking their seats: the opportunity proved to many,
especially some of the children, a heart-tendering season--one, I believe,
that will long be remembered by some present.

Our next visit was to North-dean, in Elland township, to the widow of John Hill,
who left one infant--he suffered for robbery.
His widow presented us with an interesting letter,
received from him the day before his execution,
manifesting the peaceful state of mind he had been favoured to attain to,
under the evidence of his having been enabled to forgive all mankind,
and himself experiencing Divine forgiveness for all his sins.
She informed us, the night he was taken, he was forced out of his bed by the Gang;
that she ran after him half-a-mile, until they obliged her to return,
threatening to blow her brains out if she followed them.
We sat with the widow, the sufferer`'s mother, aunt, etc.;
and it proved a solid opportunity.
A brother of the sufferer was also by the same means implicated in these riotous proceedings,
his neighbours say, not from inclination; but overcome by threats,
he being always considered a religiously-disposed young man, and much esteemed;
but he escaped being taken with the rest.
His mother was maintained by the produce of a small farm,
and he was her sole dependence in the management of it.
The loss of her son, by an untimely end,
with the continued fearful apprehensions she laboured under,
of her other son being taken--there being a warrant out against,
and search making for him, appeared almost to drive her to despair.
We endeavoured to console her, and before we left I felt it laid upon me to assure her,
that on account of the general good character we had received of the young man,
and the manner of his being led away,
we would lay his case before the magistrate who granted the warrant,
and use our influence to obtain permission for him to return home.

Our next visit was to the widow of John Hey, and her seven fatherless children:
we found her in a state of mind bordering on despair.
As ability was afforded,
we endeavoured to turn her mind to seek after quietude and submission,
to the dispensation permitted her, in which God is to be known,
and his power experienced, to stay, comfort and console,
and which would carry her through the accumulated afflictions she was struggling with;
but her poor mind was so overcharged with the prospect of her great poverty,
her numerous fatherless children, without any visible means for their support,
that we were ready to fear what we had to offer, obtained but little entrance.
Leaving this cottage of woe and misery, we bent our course to Halifax.

Fifth-day, the week-day meeting being discontinued,
and feeling drawings in our minds to sit with the few Friends of Halifax,
a meeting was concluded to be held this morning, at which, in addition to Friends,
we had the company of several not professing with our religious Society;
amongst whom was I+++______+++ S+++______+++, the young man before-mentioned,
whose mind was again so reached,
that he trembled and could not hide his state from the meeting,
although it was evident he endeavoured for it.
He afterwards settled in the neighbourhood of a meeting of Friends,
and became a steady young man, manifesting attachment to our principles,
and regularly attended our meetings.
In the afternoon we went to Longwood,
with a view of visiting Benjamin W+++______+++. He was a single young man,
living with his parents;
an accomplice with the other two in the murder of the master manufacturer;
and received the reward offered for apprehending the offenders,
having his life saved by turning king`'s evidence.
He being from home, we requested he would give us his company next morning,
at Joseph Mallinson`'s, Long-royd-bridge.

Fifth-day, agreeably to our request, Benjamin W+++______+++ met us.
On his entering the room, he appeared to us raw and ignorant;
with apparent self-condemnation in his countenance, as if he felt himself an outcast,
and thought a mark of infamy was set upon him; newly-clad, as we supposed,
from the money he had recently received,
as the reward of having discovered his accomplices in the murder,
for which they had suffered.
We could not but anticipate the deplorable situation he would find himself in,
when the means of keeping up his spirits were exhausted.
On taking his seat, his mind appeared much agitated, and, during the opportunity,
he was unable to sit with ease to himself.
After a time spent in quiet, a door of utterance opened,
and we were enabled faithfully to relieve our minds towards him:
although he did not manifest any disposition to resent what we offered to him,
but little, if any, appearance of tenderness was visible.
The opportunity was the most distressing we had experienced; feeling,
deeply on his account, lest his mind was getting into a hardened state,
and that his case would become a hopeless one; yet not without some reason for believing,
that in the opportunity we had with him, things had been so closely brought home to him,
that he would not soon be able wholly to cast them away.
We advised him not to go into company, but to return directly home, which,
we afterwards heard, he attended to.
The feelings of suffering we were introduced into on his account, will not, I believe,
soon be forgotten.

When the Friends of Paddock meeting heard of our
intended visit to the families of the sufferers,
it appeared to them advisable to wait upon Joseph Radcliff,
the magistrate who had been so active in putting a stop to these riotous proceedings,
to inform him of what we had in prospect, and the nature of our visit,
lest any unfavourable construction should be put upon it.
We understood he expressed his unity with our intended proceedings,
and his desire for our success in the undertaking.
Being come nearly to a close of our visit,
and having felt drawings in my mind at times to make a visit to Joseph Radcliff,
I opened my prospect to my companion; but he not appearing to feel much, if anything,
of such a concern, it occasioned me close exercise.
As it appeared clear to me my own peace of mind was involved in it,
I laid the subject before a Friend, requesting him,
if he felt nothing in his mind against it, to inform Joseph Radcliff; which, being done,
he gave for answer, our company would be acceptable next morning.

Seventh-day morning, my companion accompanied me,
and the magistrate and his wife received us very courteously, with whom we had a free,
open conversation of nearly an hour and a half.
I gave him, as far as memory furnished me therewith,
some account of our proceedings in the visits,
and the state of mind in which we found the poor widows,
and those we met with who had been liberated on bail.
I then laid before him the suffering situation of the widow Hill,
against whose son his warrant was issued;
detailing the good character the young man uniformly bore,
in the neighbourhood where he had resided before his escape; and that it was the first,
and only night, he had been out with the rioters, and then,
more by constraint than inclination.

Our remarks exciting in his mind feelings of tenderness towards the young man,
we requested him to consider his case, and that of his mother,
and to afford them all the relief in his power; to which he replied,
that the young man must come and surrender himself np;
at the same time giving us authority to inform his mother, that if he thus proceeded,
he should not remain in custody, but have his liberty to return home,
and not be disturbed, so long as he continued to conduct himself in a quiet,
orderly manner.
His mother being informed to this effect, the young man surrendered himself,
and was liberated: since that time he has married, and is comfortably settled in life;
and, from good authority, we understand he continues an exemplary religious character.
I felt truly thankful this point was so far gained; but there was another, which, to me,
appeared of equal importance, and I also laid it before the magistrate, viz:
the deplorable situation of the widows and children;
there appearing no other prospect but that they must, by degrees,
sell their household furniture to procure subsistence.
They informed us, none would employ them; some refusing through prejudice,
and some through fear of being suspected to countenance the proceedings of their husbands;
whereby the parish work-house must soon be their only resource,
if no speedy remedy was applied.
This was to be dreaded; the children, from the company they would associate with,
being likely, on every slight offence, to have reflections cast upon them,
on account of the conduct and disgraceful end of their father: thus held in contempt,
the danger was, the minds of the children would, by degrees, become hardened,
and they unfitted for usefulness in society.
After thus expressing my views,
and my desire that some mode should be adopted to educate, and provide for them,
until they attained to an age fit for servants and apprentices,
and to aid the earnings of the widows whilst they remained single,
and proposing for his consideration a plan for these purposes,
I felt discharged from these subjects, which had pressed heavily upon me.
At our parting, he took us by the hand, and in a very kind manner, bade us farewell.

We proceeded to Berrisfield, where the widow of Joseph Fisher,
and other families of the sufferers, lived: they, having no regular place of settlement,
were collected into one cottage.
The opportunity with them was a favoured one,
leading us to hope the labour would not all prove in vain.
The state of mind of a woman whose husband was transported, called for much sympathy;
she viewed her case to be a more trying one than that of the poor widows, who, she said,
had seen the end of their husbands`' sufferings in this life.
The scene of distress this opportunity presented to our feelings, is not to be described.
We then went to Holland-moor; sat with a widow and six children of John Swallow,
who suffered for robbery: her mother, brother, and a sister of the sufferer sat with us.
Words fall short to describe the distress her mind appeared to be in.
We encouraged her to look for support where alone it was to be found, and where,
we had reason to hope, her poor mind was favoured at times to know a centering:
she received our visit with expressions of gratitude,
and with it our services of this nature closed.

First-day morning, my companion and I separated in near affection.
I walked to Burton in time for meeting; after which,
I was once more permitted quietly to sit down in my own habitation.
I may add, for the encouragement of those who may be brought under peculiar trials,
as respects their religious movements, that although the exercise attending our minds,
whilst engaged in the service, was very humiliating,
and the suffering we had to pass through in sympathy with those we visited,
we found heavy to bear; yet it was eminently manifested in our experience,
that He who puts forth, as He is simply relied on, prepares the way.
It was admirable to us, how readily those we met with sat down with us,
as if they had been previously prepared to receive the visit; though they seldom,
if at all, had any knowledge of our intention until we entered their cottage;
and the manner in which the opportunities were overshadowed with Divine goodness,
was renewed cause of encouragement and deep prostration of soul.
Some visits were more eminently owned than others, it appearing to us,
the minds of some of the visited were more prepared than
others to receive the Gospel message which we had to declare.
May the tribute of thanksgiving and praise to the
Lord for his all-sustaining help and strength,
thus mercifully vouchsafed to us,
become more and more the offering of our minds day by day.

Feeling my mind drawn to the accomplices, who had not been brought to trial,
but were discharged on bail, I informed the Monthly Meeting thereof,
and was set at liberty to pursue my prospect;
but for want of keeping under the exercise my mind
had been introduced into for the service before me,
and minding the pointings of Truth as it respected the proper time to move in it,
and suffering some temporal concerns to take the lead,
my way for moving in this engagement afterwards so closed up,
that I could not with safety proceed in it;--an instance
that the Lord`'s work is not to be entered upon in our time,
and when it best suits our convenience.

1813+++.+++ At the Monthly Meeting in the fourth month, I requested a minute,
which was granted, to take meetings in my way to the Yearly Meeting,
and to attend to some service I had long had in prospect in the neighbourhood of London.
Fifth-day, I left my own home, and reached Sheffield that evening.
Second-day, got to Mansfield, and had a meeting with Friends there in the evening,
which was well attended.
I left the meeting well satisfied I had given up to the service.

Fourth-day, sat with Friends of Loughborough:
although to me it was a very exercising meeting,
yet I was favoured to obtain relief to my own mind.
In the afternoon proceeded to Castle Donington had a meeting with Friends there this
evening Fears were excited in my mind that some of our company were at ease in Zion,
trusting in a bare profession; on which account I left the meeting sorrowful.

Fifth-day, proceeded to Kettering:
attended a meeting in the evening for Friends and others; which was large,
the people behaved solidly, and we were led to hope it was a profitable time to many.
First-day morning, attended meeting at Hertford,
after which we bent our course to Tottenham,
and reached in time for the evening meeting there:
I rejoiced in once more sitting with Friends in this meeting.
Second-day, proceeded to London, to attend the Yearly Meeting;
during the several sittings of which,
my mind was so closely tried with the prospect in my view,
I was scarcely able to take any part in the business,
or any enjoyment in the company of my friends;
believing the time was approaching when it would
be proper for me to cast my concern before my brethren;
but as the way for my so doing did not appear clear,
I laboured to keep in the quiet until the Yearly Meeting came to a close.
Most Friends were now at liberty to return home, but I was left in bonds,
and none but my Maker knew the state of my mind.
I was never more in need of a double portion of faith and patience,
which feelings of gratitude constrain me to acknowledge
was not withheld by my Divine Master,
otherwise I think I could not have borne up as I was enabled to do.
After passing two exercising weeks since the close of the Yearly Meeting,
way opened for me to spread before the Morning-meeting a prospect of duty I had,
to obtain an interview with those in power who had the welfare of Ireland at heart,
and to make a visit to the Prince Regent.
After the meeting had been exercised with the subject,
a few Friends were selected to have a further opportunity with me,
but they not feeling themselves competent to give a judgment,
again called together the select members,
who left me at liberty to pursue my religious prospects as Truth opened my way;
and my kind friend, William Allen,
was proposed to endeavour to obtain for me an interview
with the Chancellor of the Exchequer.

Seventh-day, 26th of sixth month, we proceeded to his residence in Downing-street,
according to appointment: we were received in a courteous manner:
and I laid before him such observations as I had made during my travelling in Ireland,
on the intemperance that so generally pervaded the lower class of society there,
and what to me appeared most likely to effect a remedy.
After affording me a full opportunity,
the Chancellor proposed my throwing the subject before the Secretary for Ireland,
kindly giving us an introductory letter for that purpose, upon whom we also waited.

Having accomplished this part of my engagement,
I quietly waited the time of the Morning-meeting assembling again which was near.
As no Friend had been proposed to assist me in accomplishing
my remaining prospect of religious duty,
I ventured to say in this meeting, that if the Friend who had so far kindly assisted me,
was easy to render me such further assistance as he was able to do,
it would be acceptable; his consenting to do so, appeared agreeable to the meeting,
and afforded great relief to my mind.
A private opportunity was what I had looked toward, and this,
when the attempt for it was first made, there appeared but little doubt,
would be obtained.
I considered it a great favour, whilst these efforts were going forward,
that I had not given up my residence at Tottenham, which afforded me a quiet retreat;
my garden finding me sufficient employment, and furnished an excuse against visiting,
which I felt myself unequal to, independent of a persuasion it would not be to my profit.
But after efforts had been made, it was found a private interview could not be obtained;
which placed me in a trying situation.

As the time of my being liberated now seemed uncertain,
it appeared my only safety was in endeavouring to aim at a resigned state
of mind as to any further openings respecting the Prince Regent.
I had various temporal matters to attend to before my return to the north,
but these I saw it would be unsafe for me to encumber my mind with at the present.
I found I must keep in the quiet, and labour after a willingness,
if not fully discharged from apprehended duty,
to be further instructed and to pursue the path which Truth should point out.
After patiently waiting on my Divine Master,
to become acquainted with the further knowledge of his will,
he was pleased to lay it upon me to take up my pen, and as matter presented to my mind,
commit it to paper; this mode of procedure appeared the only way to obtain an acquittal.
I felt myself placed in a tried and responsible situation,
from a belief that nothing short of imparting the whole counsel
communicated to my mind would find acceptance with God,
whom I thought I could in truth say,
I was desirous of serving with a perfect heart and willing mind.
As I was about to address the first person in power and the head of the nation,
should offence be given by any thing I communicated,
the Society might be implicated in it.
Although these considerations were proper,
yet I saw that without great watchfulness the reasoner would gain ground upon me,
and weaken my hands for the work.
I accordingly sat down, emptied and stripped as to matter,
endeavouring to abide in a humble dependent state,
seeking for that help which alone qualifies for every good word and work.
My Divine Master, in his wonted condescension, sent help in this time of need;
matter flowed faster than my pen was well able to commit it to paper;
and having closed what I believed was given me to communicate to the prince,
the load was removed off my shoulders.
Aware that it would require grammatical corrections,
I submitted the essay to suitable Friends for that purpose;
and believed that nothing would give me clearness, but presenting it in my own person.

On the 7th of the eighth month, I proceeded to Brighton, where the Prince Regent then was.
After opening my views to Friends there,
I gave for their perusal the address to the prince, and claimed their assistance.

The paper was read over:
some apprehensions were expressed that the length of it might prevent its being read;
but on reading it again,
it was concluded that no part could be spared without hurting the whole.
After a time passed in solemn silence,
a general desire was manifested to render me every assistance;
but the difficulty appeared great if I attempted to present it myself;
and as I could see no suitable opportunity but when
the prince was out on his morning ride,
Friends took in charge the needful arrangements.

Fifth-day, attended the usual week-day meeting; I kept pretty close to my quarters,
and passed a tranquil afternoon.
After a sleepless night,
it appeared that it would be proper for me to hold myself
in readiness this day to get relieved from my burden.
During the time of breakfast, our minds were much disposed for silence,
and after it was over a precious pause ensued.
My kind friend Mary Rickman was engaged to supplicate,
in a way that afforded strength to my feeble, emptied, tried mind.
I felt it laid upon me,
to request my friends to obtain information if the prince rode out this morning;
and if so, the time and road he would be likely to take: the road not being ascertained,
and he mostly taking his ride over the Downs, we proceeded towards the palace.

After waiting some time, the gates were thrown open; and the prince,
with a great attendance of nobles, made his appearance; but, to my great disappointment,
they took the opposite road.
I paused, and found it would be unsafe to neglect the present opportunity;
and therefore proceeded up the hill with speed,
being favoured to feel the best of supporters with me.
The hill being very steep, and the exertion great,
my breath was so affected when I came abreast of
the prince that I was unequal to utter a word,
I therefore pushed on some way before him in order to recover my breath, and then halted,
until the prince came up to me,
when I addressed him nearly as follows:--"`Will the prince be pleased to permit
me to express a few words to him;`" on which he checked his horse,
and stooping forward, replied, "`Sir, you must excuse me,
I am in haste:`" to which I answered, "`I have a letter for the prince,
will he be pleased to permit me to present him with it,`" taking it out of my breast-pocket.
He replied,
"`You will please give it to Colonel Bloomfield;`" who accordingly took charge of it.
I found that my work was not complete until I had requested +++[+++of the colonel]
that care should be taken the prince had the letter, and that it was read:
being assured this should be the case,
this exercise of faith and patience peacefully ended.

The countenances of my friends wore a different aspect now
from what they did when we turned out in the morning.
How shall I be able to describe my feelings! the safest spot for me,
is to see and feel myself an unprofitable servant; having done what was required of me,
not of myself, but through the aid of Divine grace.

Here follows a copy of the letter.

To The Prince Regent.

6th of Eighth month, 1813.

Under a feeling of religious love,
which for many years has prevailed in my heart towards thee,
and a full conviction that in the great and awful day of righteous retribution,
I shall be found guilty of a breach of my duty to God,
if I do not attempt faithfully to communicate what
I have apprehended to be his word in mercy to thee,
I have endeavoured to procure a private personal interview; but this having failed,
I am obliged to avail myself of the only means left
of soliciting thy attention to a subject,
in which thy present and eternal interest are deeply concerned.

The conduct of those in exalted stations will naturally attract general observation;
and I am well aware that from different causes,
not only are the virtues of such extolled beyond what they will bear,
but their vices or failings are frequently exaggerated:
their situation is really a pitiable one;
for though the propensities of human nature to sensual gratification are common to all,
yet the temptation is greater to those who have the most
ample means of gratifying them to the fullest extent.
I have endeavoured, as far as possible,
to place myself mentally in thy exposed situation,
and it is with real sympathy that I entreat thee to suffer the word of exhortation.

Our being prone to sin by nature will not be charged against us
in the great day when our future eternal situation shall be decided,
if in good earnest we have been endeavouring, through Divine assistance,
to overcome the evil propensities of our fallen nature: the sin is not in being tempted,
but in yielding to temptation: and suffer me to say,
that if thou hadst occupied and cooperated with the offers of Divine grace,
and the all-sufficient help inwardly manifested,
there would have been no grounds for those remarks upon thy intemperance,
which of late years have been so generally made, but, which I earnestly hope,
have been greatly exaggerated.
Flattery is so often resorted to by those who make their court to princes,
that few are to be found who will dare to represent to them their danger,
however widely they may deviate from the path of duty to their Creator,
however obviously they may be walking in that path which leads to certain destruction.
Many of those who hang about princes, for their own interested purposes,
are strewing with flowers the path which leads to the edge of a precipice,
and are sedulously employed in concealing that horrid precipice from view.
Such are real enemies, as, by flattery and deceit, are endeavouring, if possible,
to gain an undue ascendency over the object of their adulation:
some will promote and partake of the table, and the dissipation of the nightly revel;
while others, less depraved,
and not without some sense of the dangerous situation of their patron, yet,
for fear of incurring his displeasure, and losing their place, pension, promotion,
or seat at the banquet, forbear to remonstrate,
and are even guilty of countenancing and encouraging
what in another place they would not fail to condemn.
This, if my feeling be right, is somewhat descriptive of thy situation:
few have been the faithful, disinterested friends thou hast yet met with--real friends,
who have been conscientiously concerned to cherish every appearance of a virtuous disposition,
and to discourage everything of an opposite tendency.
But, notwithstanding this may have been the case,
I may appeal to thy own feelings--thou hast not been
left friendless nor forgotten by the Lord,
who still sustains the character of the Friend of sinners,
who is still graciously waiting to manifest his mercy
to such as turn to him with full purpose of heart:
these he will never desert in the needful time;
and to him I am concerned that thy whole heart and mind may be directed;
that by a cooperation with his Divine grace inwardly revealed,
and which I assuredly believe even now awaits thee for thy enlargement,
thou mayst experience deliverance from those bonds and fetters which have prevented
thy virtuous exertions,--from those false friends who hitherto have fostered,
and, if permitted, will continue to foster,
every disposition thou mayst manifest to gratify
the sensual tendencies of our fallen nature:
and this same Divine Power will, I firmly believe, raise up for thee companions,
who shall become instrumental to thy emancipation
from a state of spiritual bondage and captivity.
I believe thou hast at times in mercy been awakened to see that
a continuance in this state would bring on spiritual death,
and cause the Most High to withdraw from thee his
protecting grace and good presence in this world,
and finally separate thee from him in the world to come.

Words fail me to set forth the conflict of mind,
which at times I have passed through for many years,
on account of thy precious immortal soul.
O prince!
He who sees the secrets of all hearts,
knows how repeatedly my prayers with my tears have
been spread before him in secret for thee,
that when thou mayst be called upon to resign an earthly crown,
thou mayst not be found among the number of those who have forfeited their heavenly one,
through an unwillingness to take up their daily cross,
through a disinclination to deny themselves of those
things which the light of Christ Jesus,
in the secret of the heart, and the precepts of the Gospel, manifest to be evil,
and which unfit for the kingdom of God.

For although, as an earthly prince, thou art invested with great power,
and art made ruler and head of a mighty nation,
thou rankest no higher in the Divine estimation than the lowest of thy subjects,
further than as thou art found walking with God in obedience to his revealed will,
and righteously filling up the very awful and important station,
which by Divine permission thou art standing in,
according to his Divine purposes respecting thee.
So great has been the anguish and affliction of soul
which I have experienced on thy account,
and so strong the desires which I have felt for thy everlasting welfare,
that I have thought,
if the offering up of my natural life as a sacrifice would have effected it,
I could have felt willing: but I am deeply and consolingly convinced, that,
though no man can save his brother, or give to God a ransom for the soul of his friend,
yet through infinite mercy a ransom has been paid
by the one propitiatory sacrifice for sin.
But to obtain an evidence of our interest in this sacrifice,
we must be willing to receive Christ in his inward and spiritual appearance in the heart,
where he would put an end to sin, finish transgression,
and bring in everlasting righteousness.
For the great and awful work of salvation, if it is ever known to be accomplished,
must become an individual work:
and that this important business may no longer be deferred by thee,
all that is within me capable of feeling, craves at this time;
under an awful sense which has long accompanied my mind,
of the extreme danger thou art in from further procrastination,
and refusing to join in with the day of lengthened-out merciful visitation to thy precious,
immortal soul.

I believe,
never has the report gone abroad and reached my ear
of thy grand entertainments being about to take place,
but my poor mind has felt sorrow on thy account;
and in spirit I have been with thee as a mournful spectator at the banquet.
I have contemplated thee as surrounded by those whom thou callest thy friends: but what,
if they should prove in the end thy greatest enemies! for, prince as thou art,
thou must appear before the tribunal of Divine justice and judgment;
how wilt thou then give an account of these scenes of dissipation?
Remember, the decrees of the Great Judge are unalterable;
and against them there lies no appeal: it will not avail thee then to plead,
that thou wast countenanced in these things by those for whose age and experience,
and even religious knowledge, thou hadst respect:
the awful determination will surely be accomplished,
'`According to thy works so shall thy reward be.`'

If my feelings respecting thee are correct,
thou art at times made sorrowful on these accounts: thou art mercifully met with,
in some of these seasons of revelling; something like the hand-writing upon the wall,
which astonished king Belshazzer formerly, has appeared against thee.
Has not that same Almighty Power which smote that great king amidst his impious guests,
in mercy met with thee?
so that thou hast at times found it difficult to conceal thy conviction;
and thou hast seen that this awful awakening charge has been descriptive
of thy own situation,--'`Thou art weighed in the balances,
and art found wanting.`' Thy ways are not right before God,
for he cannot behold iniquity in princes, any more than in their people,
with approbation or any degree of allowance; and he assured,
if there is not a timely putting away from before
the eyes of the Lord and the eyes of the people,
(that great family over whom thou art placed,) the evil
of thy doings,--if there is not a ceasing to do evil,
and learning to do well,--the eternal crown designed for thee to wear in Christ`'s kingdom,
will be irrecoverably lost.

When I have been thus mentally with thee amongst thy companions, and beheld,
as I apprehended, the charge or complaint of the High and Mighty One against thee,
and that which he has also decreed, if the causes of complaint are not removed;
there has always appeared to me an unoccupied space between the charge or complaint,
and the going forth of the irrevocable decree: and,
on my being desirous to know the meaning of this unoccupied space,
it has been consoling to my deeply tried mind to be assured, it implied,
that the mercy of God was still lengthened out to thee--space still allowed thee,
in mercy, to repent:
this happy space,--this mercy of God,--may it not be suffered
to close unaccepted of! for how have I viewed it,
as contracting,
from year to year--the charge and the decree nearer and nearer approaching each other,
indicating clearly that the day of thy visitation, through the offers of Divine help,
was hastening to an awful close!
And what is the greatest among men, when left to himself,
and bereft of the assistance of his Maker?
When laid upon a deathbed, what can the prayers of others avail thee,
if He who alone can save--He, whose offers of help in time of health have been slighted,
then refuses to hear?
Just and equal are the ways of the Lord:
if we suffer the day of our visitation to pass over unimproved,
the determination will stand, '`When they call, I will not answer.`'

Let me, therefore, entreat thee to lay these things to heart:
the subject is of infinite importance to the interests of thy immortal soul: and though,
through an humble instrument, remember that thou hast been solemnly warned!
With fervent desires for thy real happiness, both here and hereafter, I remain,
dutifully, and very respectfully, thy sincere friend,

Thomas Shillitoe.

I remained at Brighton until the third day, to be forthcoming, and answer for myself,
should any unpleasantness have arisen in consequence of the letter.

Third-day, left Brighton,
and felt like a vessel that wanted vent--gratitude so flowed in my heart.
I do not know I ever before experienced such a flow of heavenly good,
or more of a capacity to magnify the Lord, and to rejoice in the God of my salvation,
in that he had again brought about my enlargement.
Walked thirty miles this day to Reigate, then took a circuitous route to Tottenham:
and after attending to some outward concerns there and in London,
on the 30th of eighth month, I proceeded to Barnsley, where,
after an absence of nearly five months, I was favoured to find my family well.

In the ninth month, I attended the Monthly Meeting held at Ackworth,
and gave in a report of my proceedings, with which my friends appeared satisfied.

In the summer of 1816, my mind was brought under exercise,
in consequence of a theatre being about to be built at Barnsley.
Having witnessed the sad effects of the players occasionally coming to the town,
and performing in a barn, especially on the conduct of the poor people,
I remonstrated with the person who was about to erect the house for them, but in vain.
The nearer it was brought to a finish, the more my exercise increased,
without the prospect of any way opening for me to move which was likely to prove availing;
it only remained for me to abide under my exercise,
being earnestly desirous to stand open to such discoveries of duty,
as the Almighty should see meet to make known to me herein.
A hand-bill that had been given me long before this,
was brought before the view of my mind, on the subject of theatrical performances,
entitled, "`Why don`'t you go to the play?`"
After searching for it, and carefully perusing it,
my mind was impressed with apprehensions of duty
to have a sufficient number printed for distribution,
and posted in the most conspicuous situations in the town.
Aware that such a step would be likely to subject me to opposition,
endeavoured to consider the subject well;
and the day being announced when the theatre was to be opened,
I had them printed two days previous.
Some were posted, and others I delivered myself at the houses of the inhabitants;
and felt a relief abundantly compensating me for my labour.

As I expected opposition, so I met with it; but chiefly from the players themselves,
by circulating hand-bills on the lawfulness and benefit of theatrical performances;
writing me insulting letters on the occasion;
procuring apparel corresponding with my own, and taking me off on the stage;
which I found it safest for me to pass over in silence, and count it all joy,
under an assurance, this labour in the Lord, through his holy help, would not be in vain;
which proved to be the case.
Their prospects were so defeated, they were obliged to leave the town, it was said,
much worse than they came to it;
and they made several attempts after this to obtain supporters, but in vain.
The theatre was afterwards converted into a dissenting meeting-house.
I mention these merciful interferences of Providence, (for without He work with us,
and we with Him,
we labour but in vain,) that others may hereby be encouraged
to do what their hands find to do with a ready mind.

In the spring of the year 1817,
I laid before the Monthly Meeting a concern to visit the ale-houses in Barnsley.
My friend Joseph Wood, of Highflats, proposing to accompany me,
we were liberated for the service.
We were generally well received,
and many of those we visited acknowledged their thankfulness for the visit.

1817+++.+++ At the Monthly Meeting, 17th of eleventh month,
I informed Friends of a concern that had, for a considerable time, attended my mind,
to engage in some service amongst persons not of our religious community, in Sheffield.
After the subject had been deliberated on, a minute was given me;
and on the 4th of twelfth month, I proceeded to Sheffield.
I attended the week-day meeting there;
at the close of which I spread before Friends of that meeting
a prospect of visiting the clergy of the Establishment,
and dissenting congregations; also the proprietors of the theatre in this town,
and the subscribers to the news-room.

Sixth-day, 5th of twelfth month, accompanied by my kind friend David Mallison,
we began with the clergy of the Establishment, calling at their houses.
My mission to them appeared to be to stir them up to consider how far they were
acting agreeably to the declaration they made when entering upon their office,
of believing themselves called to take charge of the souls of people,
where their lot was cast; and whether they were using their influence to discourage,
all in their power, the attendance of the theatre recently opened again in Sheffield,
an evil likely to prove great to the town and its neighbourhood,
as every effort was making by the managers to secure an attendance by advertisements,
drawn up with much plausibility, in order to entrap the unwary.
Our visit appeared to be generally well received and well-timed,
as the subject had obtained place in the minds of most we called upon;
some expressed thankfulness that I was thus raised
up to rouse them to their duty in this matter,
and the desire they felt to do their best in furthering my labour.
Our visit to the clergy of the Establishment closed under a grateful
sense of the cordial manner in which we were received,
and the openness apparent to hear what was offered on the subject.

We next proceeded to visit the preachers of the dissenting congregations;
with whom I had in like manner to labour, and by whom I was as generally well received,
concurrence being manifested with my concern.
We left with each of those we called upon, one of the hand-bills circulated at Barnsley,
with an account of my proceedings there.
After obtaining a list of the proprietors of the theatre,
we proceeded to pay them a visit: here we had rough and rugged work.
Gifts and profits so blinded the eyes of many of these,
that all attempts to convince them of the necessity to abandon the use of such places,
appeared fruitless; yet I felt satisfied that I had done my part with them.
