== Chapter XIII.

1821+++.+++ On the 14th of second month, I bent my course to Wakefield,
and attended the week-day meeting there.
After meeting, walked to Ackworth, which proved a solitary and deeply-exercising journey.
The prospect of religious duty, of which I had long had a view,
to visit the continent of Europe, came weightily before me;
accompanied with a belief the time was fully come,
and that I must stand resigned to lay my concern before the next Monthly Meeting:
I passed the evening comfortably with the family at the school.
I had proposed to return by way of Doncaster, and visit Friends there;
but quietness under my present circumstances appearing safest for me,
I returned direct to Sheffield again,
with a mind overflowing with gratitude to that Almighty Power,
who is watching over me for my eternal good.

The time for holding our Monthly Meeting at Hitchin drawing nigh, fifth-day,
23rd of second month, after attending the week-day meeting here,
I parted from my children and friends of Sheffield in much affection; and on seventh-day,
was favoured to reach Wellingborough.

First-day, attended meeting there,
in which I was strengthened to labour in the love of the Gospel, to my own relief,
and I was led to hope to the edification of my friends.
Second-day morning reached Hitchin in time for Monthly Meeting.

27th of second month, 1821.
At the close of the meeting for worship, men and women were desired to keep their seats,
when I opened a religious prospect my mind had long been exercised with,
to pay a visit to some parts of Holland, Norway, Germany, and the South of France,
to take up my residence for some time in those parts,
and seek such suitable employ as was to be had to fill up my spare time.
The magnitude of my engagement brought considerable exercise over the meeting.
After much deliberation, a certificate was ordered,
the meeting adjourning for the purpose of receiving and signing it.

Having a debt of duty to discharge +++[+++towards an individual]
before I left England for the continent, I left my own home to attend to it;
rode into Northamptonshire, and then took to my feet.
A heavy fall of snow the preceding day, and more than thirty miles to travel,
looked discouraging; but I found it would not secure peace to give way.
At times, during this day`'s travel, I had the assurance given me,
hopeless as the case I had to encounter appeared to be,
that after doing my best according to apprehended duty, I should be clear,
and relieved from my exercise of mind; which spurred me on.
Thus does the hope of reward sweeten labour!
Next day walked to the end of my journey; but on my arrival was disappointed,
the individual having left home a few days since,--and
gone nearly sixty miles further for me to travel,
if I accomplished what I had in prospect.
I was given to see that my not proceeding would involve me in difficulty,
harder to bear than I should have to experience by pursuing my journey.
First-day, after attending meetings here, I proceeded a few miles on my way.
Third-day, reached the end of my journey; arranged for an interview,
which was readily granted;
and what I had to offer on the occasion of my visit
appeared to be received in a very agreeable manner,
the individual acknowledging his obligation,
and that he gave me full credit for the purity of my motives
in undertaking such a journey to become a mediator:
we parted affectionately, and I returned to my quarters, relieved from my burden.

Next day proceeded towards home,
with a heart overflowing with gratitude to that Almighty Power,
who did not suffer me to return, without accomplishing the object for which I left home.
I walked upwards of twenty miles today, over a very hilly and rough road,
much fatigued in body, but in mind comforted,
which greatly alleviates the trials the body may endure to purchase it.

Third-day, the 20th of third month.
Attended the adjournment of the Monthly Meeting, where my certificate was signed,
and given me.

Fourth-day, the 21st of third month.
At the Quarterly Meeting held at Hertford,
I again opened my prospects of duty to visit the continent of Europe;
and an endorsement was made on my certificate,
expressing the unity of the meeting with my proceeding.

First-day, fifth month.
Attended a funeral at Ware; a crowd of people assembling, and some of a rough cast,
made me fearful we should not be able to come at quiet by the grave-side:
what was offered however appeared to find entrance in some minds.
The people came into the meetinghouse, and conducted themselves quietly,
the minds of many appearing to be seriously affected.
I had intended walking to Tottenham evening meeting,
but feeling drawings in my mind to the burial guests, we had a mixed company,
which makes it difficult to come at that outward quiet,
so desirable when brought under exercise.
For a short space conversation ceased,
and the silence of all flesh seemed to predominate;
but for want of improving this opportunity, I made suffering work for myself,
and at last was obliged to request silence should take place.
Some of our company being on the move to go, I was made thankful on my own account,
that I had been preserved from wholly smothering the birth of the Divine word,
which I humbly hope at this time was rightly begotten in me.

Second-day, attended the first sitting of the select Yearly Meeting.
Strength being mercifully dispensed by the Great Head of the church,
I spread before the meeting my prospect of religious
duty to visit the continent of Europe;
which for the present relieved me from this weighty subject, a certificate being ordered.

The Yearly Meeting being over, I took leave of my dear wife,
now in the seventy-fifth year of her age,
which was the most trying parting we ever experienced.
I left her under the care of one of our daughters,
and then proceeded to my cottage at Highbury near Hitchin.

Sixth-day, 15th of sixth month, I proceeded by coach to Sheffield,
and on second-day reached Hull.
On inquiry, no vessel was to sail for Rotterdam before first-day week.
This detention appeared trying, as I had no object to pursue in the meantime;
and I feared lest my mind should in any way be diverted
from the spot where I was led to hope it was safely centered.
Fourth-day, attended meeting here, and wrote to my dear wife.
The Quarterly Meeting to be held at York falling in the following week,
I left Hull on fifth-day, and on the following fourth-day,
the Quarterly Meeting for discipline commenced.
Divine goodness condescended to rest on the members through its several sittings;
whereby a preciously uniting feeling was manifest
in transacting the concerns that came before it,
to the humbling of many of our hearts,
and awakening in us the language of high praises to our God.
