== Chapter XIV.

First-day morning, I went on board the York packet, at Hull, Captain Husband,
for Rotterdam.
We reached the Spurn about noon, when the wind coming a-head, we cast anchor:
our captain with the passengers went on shore to spend the remainder of the day;
but my place appeared to be to keep quiet on board,
which afforded me an opportunity of taking a retrospect of my movements, in doing which,
no condemnation attaching, I endeavoured after resignation to this detention.
Second-day morning, we weighed anchor again, and proceeded on our passage:
my sufferings increased through sickness and total loss of appetite,
until fourth-day morning,
when we came abreast of that part of the Dutch coast called the Brill.
The wind not being favourable for our getting up the river to Rotterdam,
in company with an Englishman, a passenger acquainted with the Dutch language,
I went on shore, travelled about twenty English miles by land and by canal,
and reached Rotterdam in the evening.
At the boat my companion left me;
I was not aware of the difficulty I should have to find the residence
of the merchant I was to apply to for a suitable lodging;
and when this was accomplished, my difficulties were not at an end,
he being unacquainted with the English language.
But as I had aforetime found patience and perseverance
enable me to get through great difficulties,
I endeavoured to maintain my hold on hope; we proceeded to a hotel, where I was left,
understanding the master of the house spoke English.

My supper-time came, and the master of the house was from home:
by signs I procured some fruit and bread, and my wants being supplied, I retired to rest.
Next morning, the partner of the merchant to whom I was addressed, came to my hotel,
and offered his services as my guide and interpreter for the day,
which I gladly accepted.
I had my bill cashed, cleared my luggage, and forwarded it to my hotel.
Feeling pressed in my mind to make my way to Amsterdam,
we proceeded to secure a place in the day-boat, but were too late for it.
On inquiry, the cabin of the night-boat was secured by a man and his son,
who would not allow me a place with them, although I offered to share in the expense:
feeling most easy to proceed by the night-boat,
I concluded to make the best of the accommodation the deck afforded;
with a tarpaulin for a covering, and my luggage for cushions, I made my bed,
and passed the night comfortably; reached Amsterdam in the morning early.
I felt thankful to reach the house of my kind friend, J. S. Mollet.

As my prospect was to remain here for a short time only,
it was needful I should make the best use of my time.
Having a letter for the person who occupies the property belonging to the Society,
accompanied by my kind friend, J. S. Mollet, we proceeded to him.
Whilst J. S. Mollet, this person,
and her family were in conversation in the Dutch language,
my mind became charged with something for communication.
I requested J. S. Mollet would translate for me;
and we believed it obtained their solid attention; after which,
I took a view of the meeting-house and premises.
The meeting-house made a desolate appearance; the forms mostly gone to decay,
and the few that were left were taken into an upper story of the dwelling-house.
The meeting-house appeared well calculated for accommodating about two hundred persons,
and very quietly situated:
in the upper story of the dwelling-house were several large chests,
in which were a quantity of Barclay`'s [.book-title]#Apology#,
and Sewel`'s [.book-title]#History#, in sheets,
with pamphlets in the Dutch language;
a few of the [.book-title]#Apology# and Sewel`'s [.book-title]#History# we had bound,
and distributed where they were likely to be useful.
Offer was made to have the meeting-house seated with chairs to hold a meeting on first-day,
and to give notice.
After endeavouring to give this kind offer all the consideration I was capable of,
it felt to me safest to decline having the meeting-house opened on my account.

Leaving the meeting-house,
I requested J. S. Mollet to take me to the habitations of
such seeking-minded individuals as he had knowledge of.
Our first visit was to a pious bookseller and his sister;
and although we were not able ourselves to exchange a sentiment on religious subjects,
that nearness of affection and union of spirit,
which the true disciples of the great Master experience,
differ as they may in profession or language the world over,
was felt by me with my new acquaintance,
and it was as if our friendship had been maintained from youth.
They requested I might be told, our thus meeting was a great treat to their minds,
saying, "`Although we cannot by words converse,
I find we can converse here,`" the man putting his hand to his breast.
I desired my companion to convey to our little company what arose in my mind for them,
and I was largely opened in the line of the ministry,
which produced such prostration of soul, that at our parting,
they acknowledged they believed the remembrance of
it never would be wholly lost sight of.
We took our tea with a family who spoke my native language,
and passed the afternoon in deliberately conversing on serious subjects.
I endeavoured to satisfy their inquiries respecting the principles which we hold,
giving them our reasons for dissenting from other religious professors
on some points,--the nature of our meetings for discipline,
our care over our members, the manner in which the Society treats delinquent members,
its care over the poor, and over its ministers.
A general assent was manifested to the propriety of these various proceedings,
and their tendency to produce harmony amongst us.
Time passed swiftly over, and it being late, I proposed moving home;
but being importuned to take supper, which we could not well refuse,
on our being seated at the table, a solemn pause was made,
and the like took place before the servant removed the things from the table,
which I concluded was out of respect to us,
the family knowing Friends were in this practice.
After the supper things were cleared away, I was constrained to inform our kind friends,
how much I found I daily stood in need of help from the Divine Power;
and that many would be the opportunities afforded us during each day,
if we were but willing to embrace them, wherein this help would be dispensed;
that a pause at the commencement and close of our meals,
if made in a proper disposition of mind, as unto God, and not to be seen of men,
would prove a season, in which suitable portions of spiritual food would be received:
to the truth of which they feelingly subscribed.
I felt it further laid upon me to advert to the practice
of collecting the family together each day,
for the purpose of reading the Scriptures,
and the advantage of making a pause previous to and after the reading.
This I was informed was their practice,
and that they hoped they could say it had been beneficial to them;
they also stated that the various remarks given me to make, were very salutary,
adding at our parting, it had been a truly interesting evening to them all;
and that they regretted our acquaintance was likely to be of such short duration.

Seventh-day morning,
feeling something further stirring in my mind towards my dear friend, the bookseller,
accompanied by J. S. Mollet, we made him another call.
On our way, a young man, an Englishman, pressed us to turn into his shop,
recommending me to see the palace and gallery of fine paintings,
to which he told me I might have easy access.
Finding he was a high professor,
I gave him to understand what had been my motives for leaving my home to visit the continent;
adding, that spending my time in such a way as he advised, would ill become me,
who professed to be sent on such an embassy.
He manifested great surprise,
that I should object to gratify myself in what he called an innocent way;
and attempted by strength of argument to persuade me there could not possibly
be any impropriety in my indulging my curiosity in such things:
but being strengthened to support the reasons I had advanced,
and to point out the vanity and folly of all such things, he quietly yielded.
A relation of the young man, standing by,
in a few pertinent expressions confirmed the truth of what I had advanced,
and after my making a few more observations, he parted from us affectionately,
giving me a pressing invitation to take a meal with him;
but hoping things were left well,
I felt most easy to decline accepting his kind entreaties.
These remarks, to the wise and prudent of this world, may appear foolishness;
but such as are really concerned to know their eye kept on their holy Head, Christ Jesus,
can read and understand them.

My mind has frequently recurred to some remarks of William Hunt from North America,
when in England on a religious visit to Friends, viz:
the desire he felt to be preserved so entirely devoted to his great Master`'s cause,
as not to spend one moment of his time in pleasing himself:
to be preserved in this devoted state of mind, great watchfulness is necessary.
Our kind friend the bookseller received us with such marks of affection in his countenance,
as bespoke we were welcome guests.
After we had sat down quietly together,
I felt it required of me to lay before him the necessity there was for him to be careful,
whilst so anxiously concerned to witness the kingdom
of Christ set up and established in his own heart,
that he did not become instrumental in the line of his employ,
in building up the kingdom of Satan in the hearts of others,
by publications which he printed or sold;
encouraging him to be willing to sacrifice the profit of such works,
rather than load his conscience with the consequences that must follow such sales,
if seriously reflected upon;
the bad effects produced by reading unsuitable books being deeply rooted in the mind.
These remarks led to an interesting conversation,
and we again parted under feelings of near fellowship,
he with his sister uniting in expressions of gratitude,
that our feet had been turned towards their dwelling.

We next proceeded to the house of +++_______+++: he not being at home,
we spent a short time with his amiable wife.
Although we could not exchange sentiments but through my companion,
I was led to believe she was endeavouring to live
near the Divine Witness in her own soul.
Being told that her husband was to be at home in the afternoon,
my companion and I took tea with them: we were kindly received,
and had a religious opportunity.
Understanding our kind friend, the bookseller,
and his sister were to spend first-day evening with this couple,
I proposed our joining them, and we took leave of each other in much affection.

First-day morning, my companion and I held our meeting; after which,
we had the company of a young man,
who had newly taken orders as a preacher in what is called the Reformed church.
Feeling something in my mind towards him, and a suitable opportunity offering,
I endeavoured to lay before his view the awfully
responsible situation he had placed himself in,
by taking upon himself the charge he had; and how essential it was,
that the vessel through which the mind and will or
the Most High was conveyed to the people,
should be pure,
by the minister endeavouring to be found walking in the footsteps of his Divine Master.
Being helped through this unsought for opportunity, and enabled to pass along as I do,
in a strange land and amongst a people of a strange language,
is fresh cause frequently to adopt the query,
What shall I render to the Lord for all his benefits?
Obedience and praise being the offering he will accept,
may it continue to be my daily care to be found offering them out of a pure heart,
is the fervent prayer of my soul.
In the evening we fulfilled our engagement:
in addition to the company we expected to meet,
we had two religiously disposed young men.
We passed some of our time in conversation on subjects of a serious nature, I believe,
profitably to us all; and feeling something in my mind in the line of the ministry,
I informed my companion, which he communicating, conversation ceased.
I began to be sensible of the need of endeavouring to manage
my mode of expression so as to make it easy to my interpreter,
who, I was well assured, endeavoured to do justice to what I had to offer;
although I found this care to be embarrassing to the mind.
We separated with feelings of near affection;
and the day closed under a grateful sense of the help I had been favoured to experience,
so that I could acknowledge,
it is the Lord who has done such great things for me:--to him be the praise.

Second-day, our first visit was to a preacher of a congregation,
who understood my native language, a man possessed of great natural talents,
very animated,
and abounding with fine expressions calculated to please the itching ear of man.
On entering his residence, the injunction on sacred record rushed into my mind,
"`Be wise as serpents, harmless as doves.`"
Before I left him, I was made sensible, if I preserved peace of mind,
I must leave this caution with him,
not to sew pillows under the arm-holes of his congregation, and cry peace, peace,
where there was no peace.
An interesting young man, a preacher, made us a call,
with whom I had a religious opportunity; he appeared to receive kindly what I had to say.
We took our tea this afternoon with a pious man, a preacher amongst the Menonists.
Here we had the company of a tender-spirited man, a preacher from the Texel,
who appeared gratified by falling into our company, saying,
he had been acquainted with the few members of our Society who had lived in his neighbourhood,
but they were all removed by death:
their memory appeared to live in his mind with feelings of sincere regard,
for their faithfulness to their principles.
We also had the company of a young man, who appeared to be seeking his way to Zion;
and his steady conduct since, has manifested we were not mistaken herein.
A desire being shown to be informed respecting the principles of our Society,
we complied therewith;
and the company appeared to feel a particular interest in the information.
We found an idea prevailed, that we had no regular ministers amongst us,
but all were left at liberty to speak what and when they pleased in our religious meetings.

My companion having my certificates in his possession for translation, produced them;
they were read and explained,
as was also the care the Society exercised towards its ministers,
with which they expressed their full satisfaction:
but they manifested surprise that the ministers amongst Friends travelled
so far from their own homes and for such a length of time,
the preachers amongst themselves being all stationary.
The information given appeared to remove from their
minds many prejudices respecting our Society.
One of our company expressed in a feeling manner his regret
that our religious Society in Holland was become extinct,
and the desire,
that it might be the will of Providence there should be some raised again,
to set forth our principles amongst them.
He added that their community formerly maintained a testimony against oaths,
bearing arms, serving as magistrates, etc.,
but many of their members have now abandoned it,
although these things continue to constitute a part of their creed.
The great increase of riches,
and the revolutions which followed one another in this country,
seem to have been the means which the enemy has made use of,
to bereave them of their former steadfastness and plainness;
and they had to lament a still greater deviation
in other religious matters in a number of their hearers.
Their testimony against oaths was still maintained by some of their members,
and the affirmation taken;
but the testimony they once had been so faithful in bearing against war,
had quite fallen to the ground.
We parted under feelings of that love which is unlimited, and tears of joy were shed,
that the good Hand had brought us together.

Having had a prospect for the last two days,
that I must resign myself to make a visit to the
settlement of the Moravian brethren at Ziest,
I requested my companion to consider the subject; and if he felt nothing opposed to it,
to arrange matters for our proceeding next morning.
Third-day, though I had passed a sleepless night, we left Amsterdam for Ziest,
and reached Utrecht in the afternoon, having now about six miles to walk.
The day being wet, we were obliged to keep in the close cabin,
in a cloud of tobacco-smoke.
I felt indisposed when we left the boat, and having performed one half of our journey,
we were obliged to rest at a house nearly half an hour.
I was so exhausted as to alarm me,
there appeared no prospect of our reaching Ziest by the evening,
and no conveyance was to be had; this,
with the affliction my companion manifested on my account, tried me much;
but with the help of my companion`'s arm occasionally,
we were favoured to reach our inn.

After taking nourishment and resting awhile, we proceeded,
in order to obtain a meeting with the families in the settlement this evening.
On making application, we were informed that their minister,
who had power to grant our request, was from home, and his return uncertain.
My companion being acquainted with some in the settlement,
we concluded to make further trial, but the same reply was given.
We next called on two of the elders, before whom I laid my concern, and my certificates;
on which, we were informed, they had two meetings of their own this evening:
but there was a greater difficulty yet, which they could not tell how to get over, viz:
their preacher`'s absence from home, who had the power to grant such liberty.
After hearing all the difficulties they advanced, I paused awhile,
to be fully satisfied that I had done all that was required
of me towards effecting what had brought me there.
It appeared to me, that before I was fully acquitted,
I must propose for their consideration a meeting
with the family next morning at their own time;
on which, they concluded to have a conference with others in the settlement,
and inform us of the result.
We parted agreeably.

Next morning early, we received information, that my request was complied with,
the time fixed for the meeting, and notice given of it.
On reaching the meeting-house,
we were conducted to the seat set apart for their preachers,
raised about two steps from the level of the floor;
there were seats on the floor as in our meeting-houses,
and the like order was observed in sitting in their meetings,
men on one side of the house and women on the other.
Feeling the spirit of supplication arising in my soul,
it occasioned me an exercise I cannot well describe,
not knowing how my companion would act as my interpreter;
but leaving these considerations, under the constraining influence of Divine love,
I proceeded, my companion following me on his knees.
It was evidently felt by most of our company to be an awful season;
my companion being enabled to acquit himself on the occasion in a remarkable manner.
Feeling myself called upon to labour amongst them in the work of the ministry,
we had good ground for believing that the communication was well received;
their elders and others taking an affectionate leave of us when we parted.
This afternoon we left Ziest, and reached Amsterdam before the gates were shut.

Fifth-day, we made calls upon, and took a last farewell of, my new acquaintance here.
Sixth-day morning, I took my farewell of the children of my kind friend, J. S. Mollet,
and at noon we left Amsterdam in the boat for Haarlem,
which we reached early in the afternoon.
Walked to Dwyn Vliot, where we took our dinner:
when the bell announced its being on the table, I obeyed the call,
and took my seat with the rest.
Something had been stirring in my mind to express,
but though a considerable pause took place,
this did not appear the time for me to make my offering,
although I believed it was expected from me.
The dinner-things being cleared away,
the time appeared come for me to cast off my exercise
in the line of counsel to the children.
We stepped into the Leyden boat, and pursued our journey.
We had the company of a steady man, his wife, her mother,
and two daughters from Middleburgh; I presented them with some tracts,
which the man received and read, giving his approbation of their contents.

As we proceeded, I found some concern in my mind towards him,
but no way opened for my relief in the boat;
and the uncertainty was great of our meeting again.
In this tried state of mind, we landed, and went to our inn.
Whilst at supper, to my great surprise and no little joy,
the man from Middleburgh came into our room.
He, with his family, had taken up their abode for the night at the same inn,
and were going next morning early for Rotterdam, by the way of the Hague.
It appeared too late to request an opportunity with him and his family this night;
and my companion went into their apartment next morning,
and found the man was gone out to make a few purchases, and, on his return,
they were to leave immediately by the boat.
There appeared no alternative, but to risk our timely arrival at Rotterdam,
and proceed in the boat by way of the Hague,
which we reached only in time to step on board before it moved off.

Our fellow traveller knowing our intention of going by Delf,
manifested surprise at having our company;
when my companion gave them our reasons for altering our course,
it seemed to excite alarm, especially in the wife,
as if they apprehended we were aiming to proselyte them; but on my laying before them,
in Gospel love, what I believed was given me for their instruction and encouragement,
they gave their company freely, except the wife.

When we arrived at Leidschenden, a boat by way of Delf to Rotterdam being ready to start,
we took leave of our fellow travellers in much affection, and went on board.
My pointings of duty led me to that part of the boat called the hoope,
appropriated to passengers who are not able to pay for a passage in the cabin.
At first, I took my standing on the roof,
to enjoy the scenery of the country we passed through, the day being fine,
but my enjoyment was of short duration,
being convinced it was not the place my Great Master had chosen for me.
I therefore quitted my pleasant prospects, and took my seat in the hoope, which,
from the closeness of the place, the company I was come amongst,
and the fumes of tobacco-smoke with which I was enveloped,
I thought was the most dismal of all dismal places I had been in.
A young man, sitting by himself at the far end, attracted my attention.
I took my seat by him, requested my companion to do the same,
who by some means had learned he was a Roman Catholic;
and I endeavoured to relieve my mind towards him.
He afterwards manifested a disposition to be sociable with us.
We then placed ourselves amidst the company in our apartment,
feeling it required of me to address them generally; they became quiet,
and seemed disposed to receive what I had to offer;
the opportunity lasted about half-an-hour.

On our reaching Delf, we left this boat; our company in the hoope whom we left behind us,
acknowledging their thankfulness that we were sent amongst them,
some evincing that serious impressions had taken place.
We now entered a boat direct for Rotterdam.
The intimation I received, before I left my native land,
to be willing to be led hither and thither by my gracious Master,
was afresh brought to my remembrance: accompanied with the assurance,
there was no other way,
whereby I could with holy certainty and confidence look for Divine counsel and help,
amidst the varied and unlooked-for exercises and baptisms that awaited me.

Reaching Rotterdam, I expected to find letters from home; but in this I was disappointed,
yet favoured to have my mind preserved from being disturbed thereby.
We proceeded to the meeting-house belonging to Friends, which is a large upper room.
I seated myself in it,
endeavouring after the mind of the Great Master about disposing of ourselves tomorrow.
After sitting quietly a suitable time,
and believing Truth did not point towards my holding a meeting in this house tomorrow,
we returned to our lodgings.

First-day, 15th of seventh month, this morning we held our little meeting in our chamber,
after which, we called upon a person in the government service:
he received us with open arms, saying, he had been acquainted with our visit to Ziest.
He expressed in a humble and diffident manner his belief in the truths I declared to him,
with his desire that my coming into Holland might prove a blessing to those I went amongst.
A fear at times passing in my mind,
that I had not faithfully acquitted myself towards
the preacher of the congregation at Amsterdam,
by suffering the fear of man to obtain the ascendency over my better feelings,
and hearing he came yesterday to Rotterdam by invitation,
to preach today on some public occasion, I could see no way for relief,
but by being willing to do my best to obtain another opportunity with him.
I opened my situation to my friend, and we proceeded in search of him,
with but little prospect of succeeding,
his company we understood was so much sought after; but, by perseverance,
we found a clue which answered our purpose.

We sat down together.
I endeavoured to lay before him the awfully responsible
situation he had placed himself in amongst the people,
by declaring he believed he was called of God to
fill the office of a minister of Jesus Christ;
and the need there was for him to give proof hereof by walking circumspectly before men,
not trying to please the itching ears of his hearers,
but speaking the truth to them as it is in Jesus, from the very bottom of his heart.
He confessed to the truth of what I had cast before him,
professing as he did to be called to the ministry of Jesus Christ; but he added,
it would not be possible for him to follow my counsel and retain
his situation in the congregation he was minister of,
because his hearers would not bear to have such truths laid before them.
I told him, I prized my privilege as a free man in this respect,
and was I in his situation, I durst do no other than do my duty faithfully,
and leave consequences.
Feeling my mind discharged from anything further to communicate, we parted,
I hope in love, for I pitied his situation.
We returned to our inn, exhausted as to my feeble body, but with a grateful heart,
in having been so mercifully carried above the fear of man.
In the evening we waited upon our kind friend Ladabour,
to whom I had a letter of introduction, who offered his assistance to forward my views.

Second-day morning, he accompanied us to the orphan-school, acting as my interpreter.
I hope it may be said, that counsel was imparted suited to the capacity of the children,
and our visit was well received by the overseers of the institution.
We next proceeded to the national school,
where I expected to meet with children of the poorest class;
but in this I was disappointed,
finding the school was made up of children of rather
the higher and middle classes of the citizens.
The school was very large; and the master, my companion told me, before we parted,
revived in a very energetic and impressive manner,
what I had communicated to his scholars, and took leave of us in a respectful manner.
In the afternoon, my kind friend John Cooling,
conducted us to a school of the poorest class:
here we met with about six hundred boys and girls, of various religious denominations,
divided into two companies.
The first company we were introduced to, appeared to be eight years old and under:
at my first view of them, I concluded to pass them without making a halt;
but I soon found this would not produce peace to my own mind.
After having nearly reached the door of the apartment in which they were,
I stopped and paused; when matter was given me for communication,
suited to their infant years;
this is fresh cause for gratitude on my part to that good Power,
who thus watched over me, when my foot had nigh slipped.
We now passed on to the school of those who were more advanced in age:
the masters used their endeavours to produce silence,
in which they succeeded beyond my expectation, when I viewed their number,
the rough countenances and appearance altogether of the company we were with.

Believing it would be best for me to see the captain
of an American vessel bound for Hamburgh,
my kind friend, J. S. Mollet, accompanied me to his hotel.
Not being able to find him, I requested my companion to write to Amsterdam,
to know if there was a vessel in that port about to sail direct to Christiana in Norway;
on which, information was received,
that a vessel would sail in a short time direct for Christiana,
in which I might be accommodated with a passage.
This I was aware would spare me from much perplexity, which I sensibly felt awaited me,
if I went by way of Hamburgh.
But there appeared no other way for me rightly to go to Christiana, but by Hamburgh,
and I was obliged to relinquish the prospect of sailing from Amsterdam.
The captain of the American vessel came to our hotel,
and from the description he gave of his vessel,
I found I was not to expect much accommodation,
yet as I felt easy to go with him so far as I could see at present, I engaged my passage,
if I was at liberty to leave Rotterdam when his vessel was ready to sail.
In the evening, we proceeded to the house of our invitant,
who was at the meeting at Ziest.
In addition to the family, three females were introduced to us,
as being invited to have our company: one of them I found spoke English pretty well,
was ready at translating, manifested a lively interest in our observations,
and communicated them to the rest of our company.
This individual proved, to our great surprise, to be Jacobas Rocquet,
a pious woman we had been in search of:
after passing about an hour in religious conversation,
and answering their many inquiries respecting our religious Society,
we were about to separate, when a person entered the room,
whom I supposed to be a preacher: he looked upon us with some degree of surprise,
and seemed disposed to be shy; but on my carrying myself freely towards him,
he became more sociable with us.
In the course of our conversation,
he requested to know my motives for taking such a journey at my advanced time of life.

The better to satisfy him on this subject, I produced my certificates,
and had them explained to him: he wished to know,
if these prospects of duty had been of long standing; and being satisfied on this head,
he then queried, whether,
as the Society extended so much care as my certificates manifested towards its ministers,
the like watchful care is exercised by the Society over its members in general;
we endeavoured to inform him on this head, with which he appeared well satisfied.
Before we parted, I endeavoured, as it arose in my mind,
faithfully to point out to him the necessity there was,
that his own example should correspond with the example of the great and holy pattern,
Christ Jesus, if he became instrumental in leading others in the right way of the Lord;
to the truth of which he gave his full assent, appearing to receive kindly what I said.

Third-day morning, previous to leaving our hotel,
we received an invitation to go into the adjoining house, which we attended to:
here we found a preacher amongst the Menonists from Hingeloo in Ovcrysset,
an acquaintance of one of our friends at Amsterdam.
He appeared to be a sweet-spirited, tender young man,
desirous of walking before his flock as became a true Gospel minister;
and as if he felt a lively interest in my religious prospects,
he expressed in much simplicity the desire of his mind,
that my labours might be blessed to others where my lot was cast,
as they had been to him during this short interview; adding,
he knew not how to let us go.
Our next call was upon a preacher of, what is called, the Scotch church.
Feeling drawings in my mind to visit one of the prisons,
we waited upon our kind friend Ladabour, requesting his assistance to obtain admittance,
which he effected for us,
recommending our taking with us the preacher we had last been with,
he being a suitable interpreter,
and acquainted with those who had the care of the prison.

We then proceeded to the house of Jacobas Rocquet; who informed me,
she had a request to make, from the preacher we were in company with last evening,
that I would satisfy him,
how I was able to ascertain that my call to leave my own home on a religious errand,
was of Divine requiring; saying, a lad was in waiting with pen, ink and paper,
to furnish him with my reply.
I felt disposed to do my best to answer this extraordinary question;
but the lad making slow progress, I took the pen, and sent him the following:
"`How are we to know, that which we apprehend to be a duty, is of Divine requiring?
Answer.
In the first place, by our endeavouring to turn our attention inward unto Christ Jesus,
putting our whole trust in him, agreeable to his own declaration,
'`As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye,
except ye abide in me.`' For He alone is the wonderful counsellor,
to all who ask wisdom of Him,
to all who truly desire to be found going in and
out before the people with acceptance in his sight.
I have found from my own experience, that as he is thus looked unto and depended upon,
with earnest desires to do his will and not our own,
he condescends to qualify us to distinguish between the voice of Him, the true Shepherd,
and the voice of the stranger;
and strengthens us to follow him in the way he requires us to go,
however opposed it may be to our natural dispositions and inclinations,
or temporal interest; and that, as we are thus found doing his will,
we shall more and more know of his doctrine, and he will not fail to be unto us,
as he was to his favoured people Israel formerly,
a cloud by day and a pillar of fire by night: hereby,
neither divination nor enchantment will be able to prevail against us,
or turn us aside from the straight and narrow way that leads to life and peace.`"

After which, conversation took place, which furnished an opportunity to give,
what to me appeared, suitable replies, but not much in the line of the ministry:
it proved a very precious humbling time.
My kind friend, Jacobas Rocquet,
put into my hands her sentiments on our religious Society, saying,
she could better convey to my understanding her sentiments in writing,
than by her broken manner of expressing herself, which was as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear friend,

I am glad that Providence brought you in this country and in our town,
and I have hope that your way of discoursing, with so much freeness and openness,
will prove that the idea which is common about our Dutch people,
that all Quakers are stiff people, will be taken away;
and that the way in which you speak about religion will prove to them, that,
though you are convinced that in our speaking and
not speaking we are dependent on the Spirit of God,
and we must always be looking to his influence, yet this makes none fanatics,
as they call them, who wish only to be serious,
and not to speak without feeling about religious things.
I wish all friends in your Society may go on in the like way,
and I believe by that way they will, with the blessing of God,
be useful in the kingdom of Christ.
Farewell in God, dear friend! remember me.
Let us walk as in the presence of God; for it is true, we are everywhere in danger;
and old Satan watches, as you so well said, when we are unwatchful.
God bless you,
and give us grace to find one another in eternity by the throne of the Lamb,
where all who love him shall be one in Christ.

[.signed-section-signature]
Jacobas G. Rocauet.

--

In the afternoon, we took tea with the preacher of what is called the Scotch church,
hoping to insure his company to the prison: on our informing him what we had in prospect,
and our desire for his company to interpret,
he yielded so far as to introduce us to those who had the care of the prison;
but having some previous engagements, he could not remain.
He kindly accompanied us to the town-prison, introduced us to a female,
termed the regent, a solid woman, about eighty-two years of age.
We were informed, that at times,
from five hundred to a thousand prisoners were confined here,
and that the principal charge of this great establishment rested on her;
that she kept all the accounts,
each prisoner having a separate account opened for the work done by him,
and the expenses incurred on his account,
one third of the earnings going to the government, the other two thirds to the prisoner.
Her whole deportment bespoke her to be a religious-minded woman,
concerned to fill her important station consistently.
We considered it to be a great favour, that those, who,
for various misdemeanours had forfeited their liberty,
were under such a good care-taker.

Feeling something in my mind towards the prisoners,
the regent and one of the keepers conducted us into a large court-yard,
the men`'s rooms forming three sides of it;
each room was sufficiently large to accommodate eight or ten persons for lodgings,
and to follow their labour.
I did not feel enough to justify me in requesting
to have them collected in their place of worship,
which we were told was the only place that would contain them.
I felt myself placed in a trying situation,
it not appearing likely I could extend my voice so
that all such as understood my language could hear,
nor that my companion`'s voice would be equal to it, which was of the most consequence.
On informing my companion of my difficulties, he communicated it to the regent,
who proposed my committing to writing what I had to offer to the prisoners,
assuring us it should be read to them;
but I was favoured to see that I must go from room to room,
until I felt in my own mind a discharge.

Attended by one of the jailers, we proceeded--the windows of each room,
being sufficiently large to allow all to hear, on their collecting to the windows.
At each window I requested the prisoners should be informed,
mere curiosity had not been the inducement for my coming amongst them,
but an apprehension of religious duty;
if I might be made instrumental in encouraging them
to endeavour to profit under their present afflictions,
into which their own misconduct had plunged them,
for want of their paying due attention to that law written
by the finger of Almighty God on each one of their hearts,
and seeking to him for help in times of temptation;
whereby they were led by their evil passions in various
ways to violate the laws of their country;
in consequence of which, husbands were separated from wives, parents from children,
and children from parents, and they were under suffering many ways.
I laboured with them from room to room,
urging them no longer to despise the long-suffering mercy of the Lord their God;
but to be willing to turn to him with full purpose of heart,
and render obedience to his Divine law,
that true repentance and amendment of life may be experienced:
inasmuch as the Almighty willeth not that we should die in our sins, but return to him,
repent and live;--with more to the same effect.
The jailor, who appeared to feel an interest in what was communicated,
assisted my companion when he appeared in difficulty to interpret what I had offered.
The prisoners conducted themselves in a quiet becoming manner;
many of them appearing awakened to seriousness, and some much tendered;
particularly a young man about eighteen years of age, of respectable appearance,
was melted into tears, his countenance bespeaking the brokenness of his heart:
they mostly offered us their hands at our parting,
expressing their gratitude for the counsel given them.

Feeling my mind released from proceeding further, we retired to the jailor`'s house.
The case of the young man before described, had much hold of my mind;
the man confined in the room with him appeared of a diabolical spirit.
I laid this subject before the head jailor, who informed us,
our views of the latter were correct:
we urged that the young man should be removed from this bad man`'s company;
which we were assured should be attended to.
We then proceeded to the women`'s side of the prison,
where we found them in two companies.
On my beginning to address the first company, some appeared to eye us with astonishment;
but they soon ceased from their employments,
and manifested a degree of tenderness of mind.
One decent-looking young woman continued her spinning after I had broken silence;
but the tears gushed from her eyes, the thread fell from her fingers,
as if she had lost the power to hold it longer: it proved altogether an affecting time;
they parted from us respectfully.
In the other room we visited, they were employed at their needle;
and we found a willingness to receive the word of exhortation,
and much tenderness was manifested.
Some of this company appeared to be of a class that
had received an education above a common one.
Feeling myself under the necessity of adverting to
the cause of their being deprived of their liberty,
and placed under such disgraceful circumstances,
I found that by endeavouring to keep near to that Power,
who will not break the bruised reed nor quench the smoking flax,
I was preserved from expressing myself in a manner
that might have blocked up my way in their minds:
we left them under feelings of much tenderness.

Fourth-day,
we visited the merchant who furnished the order for our admittance to the prison,
and who manifested a lively interest in the welfare of it:
we laid before him the situation of the young man before stated,
and received an assurance his case should obtain proper attention.
This alone felt to me an ample reward for all I had gone through at the prison;
and feelings of gratitude to my Almighty care-taker attended my mind,
for preserving me from requesting to have the prisoners collected in the chapel,
or committing to writing the exercise of my mind;
in either of which cases it is not at all probable this
young man`'s situation would have come to my knowledge;
a fresh proof of the necessity of minding our steps, as well as our times of going forth.
We endeavoured to point out the advantage that would result,
from the prisoners being suitably classed,
and from not having those who were grown old in iniquity,
coupled with such who might be compared to children in evil practices;
and that some way should be devised,
whereby the Scriptures might be read to the prisoners daily.
We were informed, each room was furnished with a Bible; but I felt it right to say,
although this was a pleasant circumstance to hear,
yet it should be remembered many of the prisoners were men of a description,
not likely themselves to make much use of the Scriptures; and Satan,
who is an enemy to everything likely to tend to our good,
will not be deficient in his endeavours to prevent their making a proper use of them.
I acknowledged, difficulties would attend their daily collecting for this purpose;
but I was also well assured in my own mind,
if the practice was properly gone into and followed up,
great advantage might result to the prisoners.
Something arose in my mind to a young man, son of the merchant,
which I feared to take away with me.
What I had to say to him appeared to meet the Divine witness in his soul;
he in a feeling manner expressed his thankfulness for the counsel given him;
the father and son took an affectionate farewell of us.

We next called upon our friend Jacobas Rocquet;
passed an hour with her and one of her friends,
I believe I may say to mutual edification, and returned to our hotel.
Family matters called my companion home, and he left me this afternoon;
we parted at the boat in much affection, he having rendered me and my service great help.
For a time, I felt myself in a very forlorn and stripped situation,
unacquainted as I was with the language and manners of the country.

Fifth-day morning,
my kind friend John Cooling accompanied me as my
interpreter to the house of a preacher in,
what is called, the Reformed church:
my interpreter manifested such a lively interest in what passed,
that I had no doubt he did full justice to what I had to communicate,
from the replies the preacher and his wife made.
See, reader, how I was in mercy again cared for; stripped of my last helper,
and another so soon provided for me;
one who manifested so much willingness to render me every help in his power,
that I had no hesitation in my own mind to make him my mouth-piece to others.
Understanding our friend, the preacher we are now with,
is a young man much followed by the affluent in the city,
I felt concerned to lay before him the necessity of keeping very humble,
and free from every creaturely shackle,
delivering faithfully to his hearers that which he
believed to be the whole counsel of Him,
whose minister he professed to be, without fear, favour or affection;
because as he had obtained so much place in the minds of the people,
the danger was great on his part,
lest their gifts of kindness and respect shown him should blind his eyes,
and he not continue to see the things belonging to Christ`'s
kingdom with the same clearness he now appeared to do.
He seemed to receive willingly what I offered, saying,
so far as he had knowledge of our Society, from what he had read,
he was nearly united to it;
and was desirous of becoming better acquainted with our principles:
I forwarded him an [.book-title]#Apology# and Sewel`'s [.book-title]#History# in his own language.

I found I had to pass through another baptism,
if I quitted Rotterdam with a peaceful mind; but human nature recoiled at it;
which was to request a private opportunity with an individual,
who stood very high in the estimation of men as being a religious character.
He appeared to be so deeply involved in worldly matters,
and undertaking such a multiplicity of concerns of a religious nature,
that if my feelings did not deceive me, what he undertook in this way was marred thereby,
instead of good being promoted through his instrumentality, as it might have been.
I tried writing to him, but the attempt brought trouble over my mind and not relief.
I endeavoured to excuse myself,
from the difficulty of getting a quiet opportunity with him;
but finding I must do all in my power to obtain one, I proceeded to his house.

When I reached it my prospects were not brightened;
for he was so full of his worldly concerns, and one person calling after another,
that I despaired of succeeding.
I watched the first opportunity to claim his attention,
told him I was about to leave Rotterdam,
and could not do so comfortably to myself without
attempting to have a little of his company alone;
to which he pleaded his inability on account of business, and persons calling upon him,
one after another.
He left me again, but I found I must maintain my standing in the outer apartment,
and go into his apartment when no one was with him, and shut to the door.
In this trying position I had to stand a considerable time,
feeling as if I was nailed to the place, amidst hope and fear,
lest I should suffer the suitable opportunity to slip.
After much exercise of faith and patience,
strength was given me to lay hold on the moment when he was left alone,
to go into his room, and take my seat by him.
I told him I had left all, wife and children,
under an apprehension of religious duty to visit Holland,
that I apprehended I had something in commission from my great Master to him,
which I durst not take away with me,
hoping he would allow me a few minutes quietly with him to express what came before me.
The power of Truth appeared to lay hold of him, and he quietly kept his seat,
manifesting a willingness patiently to hear what I had to offer.
I told him it had been given me, I thought clearly,
to see he had received the five talents for usefulness in the militant church;
but if he was burying them in the earth, or wrapping them up in a napkin,
comparable to satisfying himself with a fair outside
show of religion and a life of morality,
instead of his occupying with these talents answerably
to the design of Him who had entrusted him with them,
his being a nominal member of the militant church,
would not entitle him to a seat in the church triumphant in heaven.
I therefore exhorted him to endeavour to have his mind more loosened from worldly concerns;
and to guard against a multiplicity of other engagements,
however desirous he might be to promote the good of his fellow creatures;
believing many have laid waste the usefulness they were designed for,
by undertaking more than they were able promptly and properly to attend to; advising him,
when called upon by others,
from the willingness he manifested to render himself useful to his fellow-citizens,
to feel his own way in accepting appointments,
experiencing something like the woe in his own mind if he did not accept.
He heard me patiently through; no interruption occurring the whole of the time.
I believe we were brought very near to each other;
and he requested me not to keep back anything which I had for him, saying,
he felt what I had communicated to him to be a proof of my love;
and we parted affectionately.
After which I was enabled to go on my way rejoicing, that He,
who called for this sacrifice of my own will,
had in mercy condescended to preserve me as in the hollow of his Divine hand,
when the discourager endeavoured to turn me aside from the path of duty,
which might have embittered the retrospect of my labours on this side of the great deep.

First-day,
I believed it would be right for me to pass the evening with my friend A. V+++______+++,
and yet how to accomplish it without the help of my kind friend and interpreter,
John Cooling, whose place of residence I was unacquainted with,
brought me into difficulty.
I went to the trade-house; but the servants only were at home,
and they could not understand me.
I then returned to my hotel, procured a note in Dutch to give to the servants,
requesting John Cooling`'s address, but it amounted to nothing; my countenance I suppose,
manifesting disappointment, with the importunity of my manner,
roused them to apply to their next neighbour, who, to my agreeable surprise,
accosted me in my native tongue, invited me into his house,
inquiring of me what brought me to their land.
I gave him my certificates, which he read with attention,
making agreeable remarks on the care of the Society over its members:
not being able to procure the information I was in search of,
he kindly proposed to help me to find the house.

Feeling something moving in my mind for him, after a time of quiet,
I ventured to declare it; when he expressed his thankfulness to a kind Providence,
who had in such a remarkable manner brought me to his house,
and for what he had given me to impart to him.
He accompanied me in my search, but it was in vain: we parted,
and I returned toward my hotel.
On my way thither, I observed a large congregation dispersing,
and a number of carriages at the doors of the place of worship.
My mind was forcibly struck with the persuasion, that my friend A. V+++______+++was there:
I made a halt in hopes to see him come out.
Three men were standing together, who appeared to be of the upper rank in society,
and I made up to them, but we could not understand each other;
they manifested disappointment as well as myself, but I could not quit the spot.

After a short time I observed one of these persons coming towards me with another person,
who to my agreeable surprise was an Englishman: he introduced me to my friend A. V+++______+++,
who proposed my passing the evening at his residence.
But there was another difficulty to get over, the want of an interpreter: however,
after a pause, I laid my hand on the shoulder of the Englishman,
telling him I pressed him into our service, which he consented to.
In the evening I attended to my appointment; where,
in addition to my friend A. V+++______+++ and his wife, I had the company of his parents,
his brother and wife, and a friend of his from Ziest, and my kind countryman.
A desire was manifested on the part of the company,
to receive as much information as they could respecting our principles;
also our reasons for differing as we did from other religious professors in many respects,
our internal government, and manner of treating our delinquent members:
to all which I was enabled to reply in a way that appeared to give general satisfaction,
each acknowledging, that, from reports,
they had imbibed sentiments unfavourable to the Society, but which had now been removed.
An allusion was made by some of our company to the
report prevalent on this part of the continent,
that we had no one set apart to the ministry, but whoever inclined, male or female,
were at liberty to stand up in our meetings, and hold forth as they pleased.
I produced my certificates, which my countryman explained to our company,
who generally expressed their satisfaction.

My friend A. V. in strong terms acknowledged that he was highly gratified
in hearing the care the Society manifested towards its members,
especially over its ministers, and the establishment of meetings of ministers and elders,
with the queries peculiar to this part of the body.
Our time passed on rapidly, and finding it was late,
I made an effort to move to my lodgings;
the feelings of regret manifested in each countenance at the prospect of our separating,
cannot be easily set forth:
my kind countryman and another of our company conducted me home,
and at our parting they acknowledged they had spent
a most interesting and profitable evening,
desiring my future movements might continue to be under Divine direction,
and the reward of peace to crown my labours.

Second-day morning, I proceeded to the merchant`'s,
to whom my letters from England were to be addressed,
in order to their being forwarded to Altona; on my way I met with my kind friend,
who interested himself yesterday morning in my behalf,
by introducing my countryman to me:
our meeting again so unexpectedly appeared mutually agreeable,
which he requested a person who stood by that spoke English, to acknowledge,
and the unity of spirit he felt with me;
believing I was come to their country on the same
good errand which brought William Penn amongst them,
to do his countrymen all the good in my power,
and desiring the Divine blessing would attend me for it.
