== Chapter XV.

Our captain having procured his papers, we left Rotterdam for Helvoetsluys,
a journey of about twenty-eight English miles, in a bad uneasy carriage;
the road was very deep from heavy rains, and narrow, with deep ditches on each side,
the night as dark as most I have known;
so that our journey appeared to me a terrific one.
When we reached the end of it, the gates of the fortifications were shut,
and all our efforts to make the sentinel on duty hear us, appeared fruitless,
none of our company spoke the Dutch language but the driver,
who did not seem to interest himself about us.
There appeared now no other prospect but that we
must pass the remainder of the night in our carriage,
which my mind was easily made up to do;
but I felt much for our horses which had brought us the whole of the way,
with only a poor feed on the road.
After urging our driver by signs to take steps for our relief,
he turned back to a turnpike-house, where we had great difficulty in waking the keepers.
The turnpike-man gave us instruction how to proceed to make the sentinel hear,
adding that the silver-key would gain us an easy admittance;
this we found soon effected our purpose, and we reached a comfortable English hotel.

Third-day, 24th of seventh month, I went on board the General Jackson,
from North America: the vessel not being intended to carry passengers,
did not present an appearance of much outward comfort;
but believing I had done right by taking my passage in her,
I endeavoured after a willingness to resign myself
to every deprivation I should have to meet with.
The wind not favouring our clearing out for Hamburgh,
I went on shore again to recruit after the fatigue of our journey;
expecting from the closeness of the cabin, small berth, and poor bed,
that I should have a trying time on board of it,
although the captain had done his best for my comfort.
Our detention afforded me frequent opportunities for considering
how far I had done right in leaving Rotterdam when I did,
but not having a desire left to be anywhere else than I now was,
I considered it a great favour from my heavenly Father,
who had thus far in mercy directed my course.

Fifth-day, the wind was contrary.
Sixth-day, the same; but I was not alone in this detention,
for at the same hotel were five of my countrymen waiting for a passage to England.
Apprehensions were awakened in my mind before we cleared out,
that I must make a visit to the preacher here:
on inquiry I found he did not understand the English language,
which involved me in exercise.
I endeavoured to put by this concern, which I was suffered to do from time to time,
until seventh-day morning,
when our captain made preparations for moving,--the
prospect of our getting out of the river,
and over the fiat, being favourable.
This sudden change in our situation alarmed me,
from a fear that if I left Helvoetsluys without doing my
part to obtain an opportunity with the preacher there,
I should have cause sorely to repent of my neglect.
My five countrymen had left; I therefore had none to open my mind to, but my landlord,
a young man who understood both languages; to him I made my case known,
requesting him to accompany me to the preacher, and to act as my interpreter;
this latter request of interpreting, I observed was trying to him, but he yielded.
We proceeded to his house,
and found the preacher engaged in preparing his sermon for the next day;
yet he appeared to give me his company cheerfully.
I endeavoured faithfully to cast before him matter as it arose in my mind,
which I had reason to believe he received as coming from the right source;
he acknowledged the truth of what I had delivered,
frequently expressing his regret he was not able to converse with me in my native tongue,
and inquired of me if I was a follower of William Penn.
I produced my certificates, which were read and explained to him;
which excited his astonishment, that I should leave my native land on such an errand,
with such a prospect before me,
asking if I was not afraid to take up my residence in France,
where a few years ago they massacred the Protestants.
I laid before him the command of the great Master,
"`Fear not them that can kill the body, and after that have no more they can do;
but fear him who can not only kill the body, but afterwards cast the soul into hell.`"
On which he replied, "`I find where your dependence is, raising up his hand,
"`in heaven;`" adding, "`that dependence will not fail you, but carry you through.`"
He expressed his gratitude for the visit,
and his sincere desires my journey might prove a prosperous one,
and that I might be preserved from harm.

I now had my luggage put on board, and during the night we weighed anchor,
and sailed for Hamburgh.
We were four days on our passage, during which my sufferings from sickness were great,
and not a little increased for want of accommodations: on fourth-day evening,
we landed at Blankanaze, a small fishing-town about seven miles from Hamburgh;
the supercargo, myself and a broker, who came on board,
hired a wagon that night for Hamburgh.
Having a letter addressed to the son of a friend in England, who resided in Hamburgh,
the broker conducted me to his residence, and left me.
Presenting my letter, by signs I was able to understand he was in the country;
it was dark, and how to proceed I knew not,
being unable to find any person I could place confidence in, who understood my language,
to assist me in procuring a place suitable to lodge for the night.
I stopped a lad in the street who spoke a few words of English,
but his replies to my questions were so contrary, I could have no help from him.
I thought I had the name of the hotel, where the supercargo intended taking up his abode;
and by stopping one person after another in the street,
I at last found one who could understand me; he took pity on my situation,
and conducted me to the hotel I had inquired the way to:
but to my great disappointment the supercargo had not taken up his abode there.
Whilst musing over my condition, a person entered the room, who could speak English,
to whom I made known my trying situation;
it turned out that he had lately left the supercargo at another hotel,
to which he conducted me.
Thus a kind Providence again in mercy interfered, and brought me through my difficulties;
may I never forget his many favours, but endeavour to be found walking worthy of them:
I retired to bed weary in body and weary in mind.

Fifth-day, 3rd of eighth month.
Believing it would be right for me to take up my abode at Altona,
and my way to proceed to Christiana at present not appearing
so clear as to justify my making arrangements for it,
I proceeded to Ahona in search of lodgings;
and with the assistance of my very kind friend James Vandersmisson,
I procured such as were tolerably comfortable, as respected house room and bed;
but none of the family understood English,
which was to me at times an exercise of patience,
and the more so from their being so very dull in
comprehending what I meant by the signs I made,
which I endeavoured to do in as significant a manner as possible.
These trials no doubt were intended for my good,
beyond what my poor finite comprehension was at this time capable of fathoming;
it proved the means of my having my apartments to myself,
which under the state of mind in which I had afterwards to move,
was a very precious privilege.
I had references to several religiously disposed persons;
but my safety appeared to be in keeping quietly at home.

First-day morning, intending to sit down quietly in my own apartment,
an apprehension of duty was very unexpectedly laid upon
me to walk through the principal streets of Altona,
and notice the manner in which the day was observed, which I did with an aching heart.
When I had thus far accomplished my mission, I would willingly have bent my course home,
to sit down in the quiet,
and give vent in secret to those feelings of sorrow and mourning.
But I found there was another of these bitter cups for me to drink,
that I must walk through the principal streets of Hamburgh--the adjoining city,
but under a different government, although not one mile apart.
I yielded, but such were the feelings of distress already awakened in my mind,
alone as I was, not a member of our religious Society to look to for counsel,
that I stopped short of what I should have done, and returned home,
under as great a load of exercise as can be conceived.
In adorable mercy, notwithstanding my shortcoming at Hamburgh,
a sense of which caused shame and blushing to be my portion,
I was enabled earnestly to crave,
if it should be required of me in any way to expostulate
with the profane irreligious inhabitants,
I might be preserved faithful, whatever should be the consequences resulting to myself.

Third-day,
the subject of my first-day morning`'s walk has been
much before my mind during the night,
and is now my continual burden.

Sixth-day, my burden becomes heavy and almost insupportable; not a faithful friend near,
or any one I dare open my mind to; as there now appears no way for my relief,
but being willing to sit down in the quiet,
and as matter arises in my mind to commit it to writing, having the assurance,
that if I endeavour to keep sufficiently simple and dependent,
I shall be furnished with matter suited to any occasion
on account of which my mind may be brought under exercise.
I was enabled to take courage, poor and empty as I felt myself, and sit down;
when Divine goodness supplied my pen with counsel to the people of Altona.
Having committed to paper what appeared to be the
whole counsel of my Divine Master thus far,
my next difficulty was to have it put in a train for circulation.
From my impressions on the subject,
it appeared likely no one here would dare to translate or print it; independent of this,
it was to me desirable to consult my friends at home, and yet in doing this I saw danger,
for fear my letter which contained the address should be opened at the post-office;
but as there was no other way for me to proceed,
I forwarded it to my friends in London for their approval or suppression.

Having thus committed the address and my letter to the post, I felt relieved;
but my enlargement was of short duration, I was soon brought into bonds again;
Hamburgh following me the day through, and occasioning me sleepless nights,
convicted as I was of my shortness, and how to come at relief I was not able to see,
but by endeavouring patiently to abide the dispensation of condemnation,
so justly permitted to overtake me.
I received information my kind friend Benjamin Seebohm was at Pyrmont,
and shortly expected at Hamburgh on his way to England.
This information for a moment felt as a cordial to my mind,
but was not sufficient to dissipate the painful feelings I was under respecting Hamburgh.
I wrote to him, giving him some short account of my situation,
and requesting his company and counsel.
But, alas! my hopes of his help soon vanished;
an account being received before my letter arrived, that he had left Pyrmont,
and had pursued another route home.
This unlooked-for disappointment cannot easily be described;
yet I dared not entertain a doubt, but that it was permitted in unerring wisdom,
for the best;
as there would have been a danger of my being tempted to lean on the creature,
and not on that Almighty Power, who, on my going forth, gave me the assurance,
that if I only remained, both in the storm and in the calm,
willing to be led hither and thither, as the Spirit of the Lord might see meet,
I should be safely brought through.

First-day morning,
during a sleepless night the way gradually opened with clearness for my relief,
although my bodily strength appeared unequal to the task.
I proceeded through Hamburgh Burgh, which is a part separate from the city,
where such wicked practices are on the first-day of the week going forward,
from very early in the morning and the whole day through until midnight,
as are not to be met with anywhere besides on the continent,
according to the general report of travellers.
I then proceeded through the principal streets and places of concourse in the city,
and returned home, endeavouring to keep in the quiet;
desirous of being favoured clearly to see if anything further was required of me,
being satisfied the address to Altona would not wholly
reach the state of things at Hamburgh Burgh.
Fifth-day, my exercise respecting Hamburgh pressing heavily upon me, I sat down in quiet;
and being given clearly to see there was no way for my relief,
but by my being willing again to take up my pen, I sat down,
earnestly breathing to the Lord,
that I might have matter given me that would be suitable to the occasion,
and strength to be faithful in penning it.

Sixth-day, this being post-night, and the address to Hamburgh,
the address to the senators, magistrates, and one to the clergy being completed,
I forwarded them by post to my friends in London,
whereby for the present they felt no longer mine but my friends`' at home;
and if they believed it best to suppress them,
and take upon themselves the responsibility of their so doing, the will, I believed,
would be taken for the deed, and I should be clear in the sight of my Maker,
which was all I was to aim at.

Seventh-day,
I received a visit from two of my countrymen belonging to a dissenting congregation here,
their preacher being in England they did not assemble as heretofore;
I believed it right to inform them,
if they were willing to open their meeting-house at the usual hour tomorrow,
assemble and sit down with me in silence, as is usual with our Society,
I was inclined to sit with them; which proposal they appeared cheerfully to unite with.
First-day morning, one of the party called upon me,
to conduct me to their place of worship;
he informed me a young man had arrived last evening to supply
the place of their preacher who had left them,
which placed me in a trying situation,
and I requested liberty to decline complying with the offer I had made,
but this would not satisfy them; we therefore proceeded,
with the conclusion the meeting was to be held agreeable to my request.
We were in all about fifty persons; the meeting gathered in due time,
the people continued to sit in a solid manner, and I believe our thus being together was,
to most, satisfactory.
First-day morning I sat down in my own apartment with an individual from England,
and a young man from Scotland,
both of whom had forfeited their membership in the Society,
together with a physician of Altona.

Fourth-day, 29th of eighth month.
I received a letter this day from my kind friend Joseph Allen,
informing me that the address to Altona was ordered to be translated and printed;
to which I replied, requesting some books in German,
and suitable children`'s books for translation and printing, to be forwarded with them.
First-day, our little company sat down together;
it proved a season in which fresh strength was mercifully vouchsafed.
Second-day evening, I received a visit from a preacher of the French Reform;
he was only able to speak so much English as to make his visit trying to us both,
not being able, when we entered upon a subject, to get through to our satisfaction,
being frequently quite set fast, and with all our hammering,
necessity compelled us to relinquish it.
Third-day morning, I spent some time with a student from the university at Berlin;
who spoke English well, and his visit was interesting:
I felt comforted with the savoury remarks he made;
and great nearness of spirit was I believe mutually felt.

Fourth-day, was much taken up in distributing tracts,
received from my friends in England, in the Pall Mall,
a place of great resort in the parish of Ottingsen.
I was informed the preacher of this parish had forbid one of the
members of the tract association distributing tracts in his parish;
but this to me did not appear a sufficient warrant for ceasing
to do what I believed to be my Master`'s business,
leaving future consequences.
I daily felt that bonds and afflictions awaited me in Altona,
yet I esteemed it a great favour from the Lord to be able to say,
I have not a desire to be anywhere but where my lot is now cast;
from an assurance arising from time to time in my mind,
that if I only endeavour to do my very best towards fulfilling my mission,
it will be accepted,
whereby I shall be clear of the blood of the inhabitants of this city,
whether they will hear or forbear.

Fifth-day, rose from my bed sad, but not sick, remembering the wormwood and the gall,
which I have had to drink since my feet have been
turned into this and the neighbouring city;
sometimes doubting the rectitude of my movement, in taking this route to Christiana,
and at other times I have been tempted to make my
escape from the suffering that awaits me;
but the great deep between me and my home,
and a fear I should become a Jonah in the ship,
and that the judgments of the Lord would accompany me,
have stimulated me earnestly to seek after entire resignation to the Divine will,
whatever my portion of suffering in this place may be.

As the address had not arrived,
I concluded it best to try to get information by obtaining
an interview with the chief magistrate of Hamburgh.
I therefore called upon an individual who was an active member of the government,
with whom I had made a short acquaintance;
and I informed him of my desire to be satisfied by the chief magistrate himself,
relative to the laws of their city,
licensing and encouraging open licentiousness and other matters.
My friend kindly offered to accompany me to the Stadt-house;
but as he had a friend with him,
I refused his kind offer in as handsome a manner as I knew how:
he then furnished me with a note to the chief magistrate,
and in putting it into my hands expressed his desire,
that pressure of business might not prevent my being well received.
I proceeded, as may be supposed, in fear; yet not wholly void of hope,
that my good Master, whom I desired faithfully to serve, would go before me.

When I arrived at the Stadthouse,
the crowd of persons waiting to take their turns was so great,
I feared the pressure of business would preclude my obtaining an interview at all,
or one that would afford me full satisfaction.
On entering an anti-room and showing the note to an officer of the state,
I was conducted into an inner apartment with my hat on, which occasioned so much remark,
that I expected it would stand in my way.
A young man who spoke English, made up to me, to whom I handed my note,
who quickly presented it, and in a short time the magistrate`'s room was cleared.
I was invited in to him, and he kindly handed me a chair; his speaking English,
together with his free, open carriage,
made ample way for me to ask such questions as the nature of my visit required,
which were frankly replied to.
This made way for me to lay before him the iniquitous practices of their government,
and many evils existing in the state,
and the need there was for these things to be remedied.
At our parting, he expressed the satisfaction which the interview had afforded him,
and his desire that we might have a further opportunity together.
My heart overflowed with gratitude to my good Master,
who had made way for me to obtain such information,
as would justify me in speaking boldly as I had done in the address,
even to speak the whole truth, or not to speak at all; such being the command given me.
I called on my friend who was the means of my obtaining
this easy access to the chief magistrate,
and informed him how it had fared with me;
he appeared to share with me in the satisfaction my visit had afforded me, saying,
"`The cause you are engaged in is a good one,
and I have no doubt good will result from the steps you may take.`"

Tenth month, fourth-day, a vessel from England brought the addresses for Altona,
which awakened fresh difficulties in my mind, as regards the distribution of them;
the watchword was, "`Be wise as serpents, harmless as doves.`"
I clearly saw the necessity of the greatest possible care in my proceedings,
or I should be defeated, in my prospect of a general delivery, by the police-master;
and therefore it would be necessary for me,
to keep those addresses I had received for Altona secure in my trunk,
until the Hamburgh addresses arrived,
and if possible have the delivery take place at Altona and Hamburgh on the same day,
to prevent obstructions at either place.

Seventh-day, I received an account that the addresses for Hamburgh were shipped;
which caused me to rejoice, yet with trembling,
through fear of the difficulty I should have to encounter before the delivery was accomplished,
by my not being acquainted with the language of the people; also,
through the awe in which the people stood of the police-master,
and the care necessary on my part not to involve others in difficulty with myself.
I felt it cause for thankfulness during this time of suspense,
that my attention has been steadily preserved to the subject;
and the watch-word from time to time was renewed, "`Fear not with their fear,
lest I confound thee before them:`" and O! the goodness of the Almighty,
in preserving me during the varied assaults of the wicked one,
and in seasons in which I might emphatically say, "`One day or another I shall fall,
through the many stratagems of the enemy,
to cause my mind to wander from the path of duty, and so to bewilder me,
that my future movements may be obstructed!`"

First-day, we held our little meeting,
in which we were favoured with the overshadowing of Divine regard.
Circumstanced as I have been as to society, like the owl in the desert,
or the pelican in the wilderness, and like the sparrow watching alone on the house-top,
the detention I have had to endure, would, but for holy help, have been insupportable;
feeling at times weary of every place.

Sixth-day, no arrival of my parcel of addresses;
this is fresh cause for the exercise of patience.
My friends here say, it will be unsafe for me, at this late season of the year,
to risk a voyage to Norway, or to attempt to winter there;
nor am I able to see that it would be safe for me
to return to England to take up my winter-quarters,
until I feel myself clear of further service in Hamburgh and Altona.
I can therefore only hope that entire resignation will be granted me,
if it should be the Divine will I should bend my course to Norway,
after my services here are closed,
and to encounter all that may be permitted to attend me in my way there.

Tenth month, 14th, first-day, held our little meeting: shortly before we separated,
I had a little matter to communicate,
which I trust will be found as bread cast on the waters, both by preacher and hearers.
Fell in with the Count +++_______+++, a young man who is here to finish his education.
He continued to manifest that sweet tender frame of mind he was in,
when our acquaintance commenced, comparable to wax before the fire,
ready to receive every impression of the Divine will concerning himself;
yet since our last parting, a fear has prevailed in my mind, of the danger there is,
without great watchfulness on his part, of losing this good state of mind,
when he returns home to his parents; his father, it is said, is a professed Atheist,
filling a high post in the government.
I endeavoured to lay before him the danger he might be exposed to,
and the need there would be for him to consult that Divine witness for God,
which he had so feelingly acknowledged was sufficient to guide him in all things;
telling him it was my belief, if he was favoured to keep his proper place,
as a truly religious character should do, when he returned to his parents,
he would become an instrument of good to others.
We passed the evening together, I believe to our mutual advantage;
and on reaching my lodgings,
I found two packets from England containing the address for Hamburgh, and books.

Third-day, went to Hamburgh;
presented the burgomaster or head senator and the police-master with books,
and reports of the penitentiary in London,
which appeared to be received with satisfaction.
On examining my packet,
I found my friends in England had been bountiful in their supply of the address,
both to the inhabitants at large, and to the senators and magistrates,
but a proof-sheet only of the address to the clergy,
of which last I got a friend to procure a sufficient number of printed copies for my use.
I set to work to fold up and wafer the addresses: dispatch was now sounded in my ear,
but the difficulty to encounter before they were ready for delivery,
was to me not a little; it was necessary to prevent my intentions being noised abroad,
lest a stop should be put by the police-master to their delivery.

Fifth-day morning I put one half of the addresses into a bag, and set out with them;
when I reached the city-gate, an officer who spoke English,
demanded to know what I had in my bag.
This unexpected circumstance for the moment placed me in a trying situation, concluding,
after all my care about secrecy, that I should be discovered: after a pause, he said,
he wanted toll for what I had in my bag, and asked, "`what is the value of it?`"
I thought I would say enough; paid my toll gladly, and proceeded;
thankful no obstruction had taken place.
Not knowing how far a public exposure of the conduct of those in authority in Hamburgh,
might cause them to rise up against my distributing them,
occasioned me some anxiety to know how to convey the remainder,
without being liable to the like examination.
I mentioned my situation to a confidential friend,
who managed to take me and my bag in his carriage near to the spot I was going to.
My countryman informed me he had engaged two men
to deliver the addresses at Hamburgh next day;
and a kind friend had engaged a man of the Jewish persuasion,
to deliver at Altona on the same day.

Sixth-day early in the morning, I furnished the man with his day`'s work for Altona,
when he took charge of them my looked-for difficulties seemed to vanish out of sight,
but, soon were my flattering hopes disappointed, by his return,
after he had delivered a very few, saying he durst not proceed to deliver more,
without I would allow him to apply to the police-master
or the governor for liberty to distribute them;
that a person to whom he had delivered one, on reading it gave him this advice.
I sent for my confidential friend; we ordered him to bring the whole back again,
as I did not feel easy to tempt him into danger, by offering him a greater reward;
nor did I feel that I should be warranted in applying
to the police-master for leave to distribute them.
As it appeared to me I must go myself this evening with those for the burgomaster,
syndics, senators and clergy, and leave all future consequences,
I procured a lad to point out to me their places of abode,
and completed this part myself: after which, I went over to Hamburgh,
to solicit my countryman to assist me in the distribution at Altona;
not being able on account of my ignorance of the language and the city,
to undertake the general distribution myself.
On inquiry how the distribution went on at Hamburgh,
my countryman informed me that the men who engaged to deliver,
when they became acquainted with the contents of the several addresses, refused,
through fear, to undertake it;
but my kind countryman proposed to make another effort for my help,
and engaged three persons;
who appeared to be disposed to be courageous in what they undertook,
and who had been used to the employ of delivering papers about the city and burgh:
it was concluded to have them addressed, by a person who could write German well,
"`To the master of this house.`"
A young man engaged to complete them for delivery in Hamburgh on second-day;
and thus matters appeared in an agreeable train.

Second-day, the distribution took place at Hamburgh,
and the men having in charge those for Altona, I felt relieved;
yet I passed an anxious day on the men`'s account, although they appeared fearless:
my mind was released, however, when, in the evening,
the principal man in the delivery came to my lodgings,
and informed me they had completed their work.
May the remembrance of the merciful dealings of the Almighty,
in thus bringing about my enlargement, stimulate me to greater faithfulness,
and awaken in me more of a willingness,
to commit myself and my all to his careful keeping, henceforth and forever,
saith my soul.

I had endeavoured to make the best of my situation to my friends in England,
unwilling to occasion them unnecessary anxiety; aware that, from my remote situation,
it would not be in their power to afford me relief, and from a renewed persuasion,
I was under best care, if I did but endeavour to keep there.
But, from various causes,
I never passed a more trying and distressing two months from exercise of mind;
without an individual to confide in.
Not knowing into what difficulty my faithfulness might introduce me, under a government,
and in a district, where the word of the police-master is very much law,
and he a man void of any tender feeling or religious sensibility,
imperious to a great degree, and very jealous of his conduct being called in question;
had it not been for holy help, human nature hardly could have borne up;
but adorable mercy appeared on my side, and proved again my deliverer.

Sixth-day morning, after a comfortable night`'s rest,
my spirit being liberated and permitted to enjoy somewhat of a sabbath,
and the weather inviting, I rambled into the country a short distance:
all nature appeared alive to enjoyment,
in which my mind was perhaps never more prepared to participate,
or in a more powerful manner to adopt the language of,
"`great and marvellous are thy works, Lord God Almighty; just and true are thy ways,
thou King of saints!`"
The time for my quitting these parts appearing now near; I could see no other way for me,
with safety to that part which will exist when this
poor frail body is mouldering into dust,
but cheerfully to submit to spend the winter in Norway; after all my anxiety,
and trying to contrive in my own will and wisdom to avoid it.
A vessel in the river being to sail for Christiana in about two weeks,
and being recommended as a good one, and the captain speaking English,
it became desirable to myself and my friends, that I should secure my passage in her.
It appearing to me that the time would suit, I felt disposed to see the captain;
but I found from the caution resting on my mind,
I must not come to any agreement with him.
I concluded to take an early dinner, and walk to Hamburgh,
and to call on the chief magistrate and others of my friends,
which I thought would afford me an opportunity of knowing,
if the circulation of the address went quietly down,
as nothing to the contrary appeared yet at Altona.
I left my lodgings with that intent; on my way,
I was accosted in English by a young man of decent appearance,
requesting to have one of the letters,
the address being folded up in the form of a letter; feeling in my pocket,
and finding one, I gave it him, and we walked on together in conversation:
when I came to the turning that was to take me to Hamburgh,
I informed him I must bid him farewell; on which he informed me,
he had orders from the police-master to arrest me,
and that I must go with him to the guard-house, saying,
he was very sorry for my situation, but it was not in his power to help me;
that I was to appear before the police-master, at three o`'clock in the afternoon.

When we reached the guard-house, and I was given in custody to the officer on duty,
the young man who brought me, had much to say respecting me, as I supposed,
from their frequently turning towards me in their conversation.
A pen and ink being on the table,
I took a piece of paper out of my pocket-book to write a note to some of my friends;
but I was prevented, and made to understand, it was the charge of the police-master.
Beginning to feel myself in danger of suffering from cold,
and from the damp of the stone floor, wet and nearly as dirty as the street,
I requested a soldier who was coming off duty, and who spoke English,
to go to my lodgings and fetch me my great-coat; he informed me he dare not,
for fear of the police-master.

Three o`'clock came, and I was informed I was not to be had up before six in the evening.
This treatment of the police-master would preclude my making my defence,
unacquainted as I was with their language,
and he very imperfect in his knowledge of mine;
but no liberty could I have to send for a friend or for my great-coat,
although the officer on duty manifested a disposition to be as kind to me as he durst.
The soldier who came off duty, aware that I was suffering from the cold,
lent me his great-coat; but this enjoyment was of short duration,
for when he was obliged to go on duty again, I could do no other than return his coat;
this left me in a cold, miserable condition; but, in adorable mercy,
the inner man was made strong to bear it without murmuring.

Six o`'clock came, and I was then informed I must remain where I was until next morning,
and at eight o`'clock be had up before the police-master:
by these repeated changes as to the time of my having a hearing,
I began to conclude the police-master had been overhauling my luggage,
and was endeavouring to find something amongst my papers, to commit me to prison upon,
besides the address.
I began by this time to feel the want of food, having had my dinner earlier than usual;
the officer on duty kindly offered me some of his sour bread and coffee,
which I was obliged to refuse, as neither of them suited my stomach:
at eight o`'clock in the evening a fire was made,
which somewhat abated my suffering from cold, but how I was to come at food,
or be provided with an interpreter, when I came before the police-master,
I was unable to see.

When the soldier who spoke English returned from duty again,
he expressed his sorrow that I had got into the hands of the police-master,
saying their prisons were miserable places;
but endeavouring to know my mind stayed on God, I was preserved quiet;
frequently experiencing the assurance from that Almighty Power,
whose promises are yea and amen forever,
that not a hair of my head would they be suffered to hurt.
It now became my song of joy and rejoicing, that,
through cooperating with that Divine help afforded, I had unabatingly exerted my utmost,
and accomplished the work assigned;
for the fear of a wrong step of mine retarding its progress,
would have weighed more with me than the fear of any suffering my body might endure,
for my faithfulness to my Divine Master`'s cause.

The clerk of a kind friend had met me in the street,
with the police-officer walking by my side;
and in the course of conversation in the evening with his employers,
he mentioned the circumstance.
They went to my lodgings, and finding I had not been at home since my dinner,
they proceeded to the policemaster, and on inquiry found I was in custody.
They kindly offered to be bound for my appearance next morning,
if I might be permitted to sleep at my lodging; but this was refused;
the liberty of having my bed at the guard-house was offered,
but there was no other place for me to lie down upon, but the stone floor,
as damp and nearly as dirty as the street.
As nothing could be done with the police-master for my relief,
about ten o`'clock at night my kind friends surprised me by entering my place of confinement;
their countenances confirming the truth of their expressions of sorrow,
to see me in that situation, adding,
"`But how cheerful you appear to be under your difficulties!`"
How could it be otherwise?
my cup overflowed with gratitude,
that I had been preserved from flinching from the work assigned me by my Divine Master;
and nov.`' he, in his wonted goodness and mercy, bore up my head above the billows!
My kind friends soon provided me with a warm mess, and two warm great-coats,
the officer on duty with an arm-chair, and one to lay my legs upon;
thus I prepared for the night, and put on comfortably; feeling, as I was favoured to do,
it was only my poor body they had in bondage; my spirit was free,
and far removed from the molestation of the police-master.

The morning came upon me ere I was aware; when I awoke in the night,
the watchword was in mercy renewed, "`Fear not with their fear,
lest I confound thee before them, accompanied with the assurance,
that if I maintained my integrity, my body would be such a torment to the police-master,
that he would be more anxious to clear his hands of me again,
than he had been to take me into custody.
Early in the morning my kind friends, the Vandersmissons,
sent me a plentiful breakfast of chocolate and cake:
and a countryman of mine making me a visit, who was acquainted with the German language,
I engaged him to accompany me to the police-master.

The officer came for me; and we proceeded with my kind countryman as my interpreter.
I should have been troubled at being conducted through the streets by a police officer,
on any other occasion; but my good Master supported me.
When we arrived at the office, we were left waiting in the passage some time;
whilst the police-master, evidently under great agitation of mind,
was pacing up and down his office.
We were ordered into his office; but instead of noticing us when we were there,
he continued pacing up and down, muttering to himself.
At last, turning to me, he said,
If I had been satisfied with delivering those addresses to the burgomasters, syndics,
etc., all would have been well; but by the general distribution that had taken place,
I had broken the laws of their country,
which forbid the delivery of any books or papers
at the houses of the inhabitants or in the streets,
without leave being first obtained of the police-master;
and that in the address I found fault with the magistrates,
charging them with not doing their duty,
which might cause the people to be dissatisfied with them.
I felt disposed to query, were not the charges brought against the magistrates true;
but as I must do it through my friend,
I was unwilling to put him to the difficulty I apprehended it would place him under,
being aware of the awe the people mostly stand in of the police-master,
looking upon him as a lord inquisitor.
He again turned from us, pacing backwards and forwards and muttering to himself;
then turned about to us again, saying,
out of respect to the acquaintance I had made in Altona, he should discharge me.
My friend said he believed I was become such a trouble to him,
that he was glad to put my discharge on the footing he did, to get rid of me.
He demanded to know, if I had any of the addresses yet left; saying, if I had,
I must promise not to deliver any more in the city: pausing, I told him,
if I promised I hoped I should perform;
but that I durst not enter into any such engagement:
upon which he sent his officer to my apartments, and secured the few he could find.
My friends told me that my arrest would make more for the cause I was engaged in,
than if the police-master had suffered all to pass quietly away;
the curiosity of the people becoming much excited to know what the Quaker had been writing,
for the police-master to be disturbed at; some would have the address copied,
and general dissatisfaction would be manifested at his conduct.
As the police-master hinted to me, it would be more agreeable to him if I left Altona;
not wishing to annoy him by remaining,
as my service here now felt to me brought nearly to a close,
and being in spirit still bound to Hamburgh, I proceeded there in search of lodgings.
On entering the city I found the conduct of the police-master
at Altona had excited disgust in the minds of my friends,
who welcomed me to the city, with the assurance I should find a safe abode amongst them:
having procured lodgings in an English family, my comfort was promoted hereby.
