== Chapter XVIII.

On arriving at the lodgings of my kind friend Enoch Jacobson,
it was a fresh trial of patience to find he was from home,
and I was unable to understand from any of the family when he would return.
I was weary and hungry, longing to reach the lodgings provided for me.
On his return, I told him, the only request I had to make of him was,
to take me to my place of abode, with which he complied; but on my entering the tavern,
my mind felt assured it was not a safe place for me to take up my abode.
My kind friend observing I was not comfortable at
the prospect of taking up my quarters there,
arranged matters for my accommodation in the family of Hans Erricksens;
where I was most comfortably cared for during my stay in Christiana.
In conversation with Enoch Jacobson,
I became afresh confirmed that the route I had taken to Christiana was by Divine direction;
for had I proceeded to Norway, agreeable to my prospect when I left my own home,
Enoch Jacobson would have been absent from Christiana,
and some of the Friends of Stavanger also, on my arrival there;
whereby my difficulties at Christiana might have been very great,
from the want I should have felt of that help I had from him as an interpreter and companion.
O, adorable wisdom in thus leading me about and instructing me!
May I be found walking worthy of these His favours.

Third-day, my mind being no longer occupied about getting forward,
I began more sensibly to feel the soreness of my flesh,
also great weakness for want of a proper supply of nourishment;
which I was fully satisfied nothing but time could relieve.
Today the rain began to fall in great quantities, and continued with little intermission,
for several days,
whereby I understood the roads became so deep in mud as to render them almost impassable.
These rains were succeeded by severe frosts,
in consequence of which the roads became so rough,
my body hardly could have endured the journey;
but let me not say how wonderfully I have made my way,
but rather how wonderfully a kind Providence has made way for me;
for nothing short of his merciful interposition could
have effected what has been brought about.

Fourth-day morning, I enjoyed a privilege which I had not had for six months,
of sitting down in a regular appointed meeting of those professing our religious principles.

First-day, 23rd of twelfth month, 1821, attended the two meetings,
in which a few strangers gave us their company, and which were held in quiet.
My friend Enoch Jacobson not being equal to receive and translate long sentences,
by care, I was enabled to accommodate him,
and to order my mode of expression to suit his ability.
In the evening we had the company of a student,
who occasionally officiates as a preacher amongst the Lutherans.

When he was about to depart, feeling something in my mind to say to him,
I felt tried at the prospect, not knowing how it would be received,
and I hesitated until he was on his feet to go; but strength was dispensed,
and I desired my interpreter to request he would take his seat again,
which he appeared to do as hesitatingly as I had made my request.
After we had quietly taken our seats,
I believed it was required of me to tell him there was a hard lesson,
which every true Gospel minister had to learn, and which he must learn,
if the word preached by him profited his hearers:
he must renounce the spirit of the world; not only its gross pollutions,
but those which might be considered more refined in their nature; such as the customs,
fashions, maxims and manners of the world, all of which,
if we come to view them through the true medium, the light of Christ Jesus in our hearts,
we shall see are not of the Father, but of the wicked one;
for example goes before precept and actions speak louder than words;
and it was my firm belief,
it was for want of a proper care on the part of some of the priesthood in these respects,
that the people on the continent appeared in such
a general way to be going headlong to destruction.

The young man, retorting at my sentiments, attempted to prove,
that though the conduct of a priest might not be consistent
with the doctrines and precepts of the Gospel he preached,
yet, if his preaching was sound and orthodox, it might have a good effect on his hearers.
But being enabled to labour with him, to convince him of the fallacy of such reasoning,
he acknowledged to the truth of what I had advanced,
and spent the remainder of the evening with us very agreeably;
and from remarks he made at our parting,
we were encouraged to hope it had been a profitable time to him.
I retired to bed much exhausted but thankful that I did not suffer
the young man to depart without clearing my mind towards him.

Fourth-day, the usual meeting being held, it was a time of Divine favour.

First-day, attended the two meetings, where some strangers gave us their company.
In the afternoon meeting, I was led to speak pointedly to a state present,
which tried me not a little; fearing I had been led astray by the grand adversary,
and thereby sadly exposed myself.
This buffeting I was permitted to endure, doubtless to humble and keep down the creature;
until a friend informed me that what I had delivered in the afternoon meeting
was as applicable to the conduct and general character of an individual present,
as it could have been, had I been acquainted with his proceedings for a long time past,
and that the individual received it as belonging to himself.

I thought I never more sensibly felt, than during my labours this afternoon,
the necessity of the instrument becoming like a clean tube,
through which liquor passes from one vessel to another,
free from the defilements of creaturely wisdom and activity,
and from all the obstructions of the creaturely will in doing or not doing.
In the evening we had the company of the student before alluded to.

Third-day, the commencement of another year; to me a memorable beginning,
which I believe was the case with the family where my lot is cast.
Some portions of my visit to Copenhagen opened before my mind,
accompanied with the savour of good I was favoured
to experience during my religious engagements there,
which produced a holy quiet in me: and,
on taking my seat with the family at the dinner-table,
this feeling appeared to circulate, as from vessel to vessel,
until most present manifested a participating in it,
so that little conversation took place during our sitting together,
and we separated reluctantly.
"`Gather up the fragments, that nothing may be lost,`" was the watch-word given me;
I therefore endeavoured to avoid as much as possible,
unnecessary conversation during the remainder of the day,
lest what I had thus been permitted to taste of the good word of life,
and the powers of the world to come, should be lavished away.

Fourth-day, 2nd of first month, 1822, attended the usual meeting,
at the close of which was to have been held their two months meeting,
but it was adjourned in consequence of the absence of one of their little company.

Sixth-day.
Feasting and merry-making at this time is followed up by persons of all ranks,
to a greater degree than I ever before heard of.
I found it to be my place to protest against it in the family where I was,
by keeping to my own apartment, when they invited their parties, except on one occasion,
when a few persons, whom they professed to esteem sober, orderly individuals,
were coming to take coffee with them.
But my thus giving up to the entreaties of others placed me in a trying situation.
The coffee-drinking being over, I was soon convinced,
from the repeated roar of laughter which the conversation produced, that their sober,
orderly dispositions were not the effect of true submission
to the regulating influence of the grace of God.

Two young men, professing to be under preparation for the ministry,
appeared foremost in promoting conversation and practices,
which occasioned the uproar and levity.
The company being dispersed, I took an early opportunity with the family,
for spending time in such a reproachful manner;
and the certain sad effects that must be produced thereby in the minds of most,
if not all: these observations were, I understood, carried to all the parties.
The two young men who were candidates for the pulpit, had such hold on my mind,
that I was led to desire I might be found faithful,
should it be required of me to labour with them on
the subject of their conduct at these evening diversions,
humiliating as the task may appear to be.

First-day, the 6th, attended the two meetings in course.
Returned from the afternoon meeting, hoping to pass a quiet evening; but, alas!
I was disappointed; for this feasting and merry-making disposition prevailed,
treating all days alike, and one person after another,
without breach of charity it may be said, void of religious exercise of mind,
coming into the family, I therefore retired to an adjoining room.
But my quiet was broken in upon,
by the sudden bursting into the room of a number of persons,
masked and dressed to personate different characters.
I was told this practice is followed up at this season of the year,
on first-day evenings, in Christiana; individuals going from house to house,
introducing uproar and confusion;
making speeches that tended to excite feelings of levity, likely to produce evil fruits:
no quiet settlement was to be come at in the family afterwards.

First-day, the 13th, attended the usual meetings,
and passed the evening comfortably in the family, the day closing with the language of,
"`Return to thy rest, O my soul, for the Lord hath dealt bountifully with thee.`"

Second-day, feeling my mind drawn to make a visit to the professor in theology,
who has under his care the young men who are designed
for ministers in the Lutheran congregations,
my kind interpreter and I called upon him.
In the course of our visit, I laid before him the evil practice of opening the theatres,
and other places of amusement, and the consequences likely to result from this practice.
The dark, bewildered state of his mind was sorrowfully obvious,
from the replies which he made on this and other important subjects;
evincing a more determined prejudice against our religious Society and its principles,
than I ever before met with; saying, although he could respect me as an individual,
yet not the principles which I professed to hold, calling them ranterism.
Feeling myself called upon to protest against these sentiments,
in as few words as possible, I brought to the view of his mind portions of Scripture,
to prove their error, and he remained silent on the subject afterwards.

He said, if Luther was now living, he would protest against that inward word,
which the members of our religious Society profess so much to rely upon;
that he believed with our Society, it was the same the Scriptures term it,
the grace of God, the Spirit of Christ within;
but that this inward word was only to be received by reading the outward word,
and through the administration of the sacraments;
and was not to be immediately received from God, as professed by our religious Society,
which he considered to be a great error.
I queried with him, from whence did he suppose those feelings proceeded,
that showed him what was right and what was wrong,
and whether he had not felt his mind influenced with that which was good,
when he did that which he saw to be right?
He replied, he durst not rely upon such feelings,
being convinced they might lead him into error; because, said he,
the devil can transform himself into an angel of light,
and the Scriptures were the only rule for our conduct through life,
which can with safety be depended upon;
and that he was called by the Almighty to the situation he was now filling,
to instruct young men in theology, that they might become true Gospel ministers.
On his being asked,
what part of the Scriptures pointed out to him that it was his duty to do thus,
he replied his situation was bestowed upon him by the government,
the government being ordained by God, what the government did was the will of God;
consequently he was called of God,
to the station he now filled as a professor in divinity;
and that individuals who went about the country as I did, under apprehensions of duty,
had better slay at home and take care of their families,
which he believed would be more consistent with the will of God.
He parted from us in a friendly manner, and we could not but entertain a hope,
that when he came coolly to reflect on what had passed, his mind would be softened,
and some of that prejudice he had imbibed against our religious
Society and its principles be done away.
Through a relation of the professor`'s, we were informed,
he mentioned our visit as an acceptable one to himself and his wife;
and when we occasionally met he carried himself kind towards me.

Second-day evening we had the company of one of the young candidates for the pulpit,
before alluded to, who made a part of the company at the merry-making;
but from the tried state of mind I was in,
I feared to lay before him the view I had taken of his example;
but I found I was not to be excused, as he himself opened the way for it.
He had heard that I protested against the clergy attending theatres, dance-rooms,
masquerades, etc., and termed them wicked practices,
and was come for the purpose of confuting by argument what I advanced on the subject.
He attempted to prove the possibility of a wicked priest,
if his sermons were sound and orthodox, profiting his hearers by his preaching,
and thus to justify the conduct of the clergy in
their attendance of these places of dissipation.
I was so strengthened to maintain my standing against his unsound reasoning,
as to put him to silence, and he appeared to go away disappointed in his expectations.
I was thankful for being favoured to acquit myself in such a way
respecting his conduct and his brother candidate for the pulpit,
as to put him to silence;
although it was evident he would gladly have escaped
from the shame he felt on the occasion.

We next made a visit to professor Hersleb, a professor in theology,
a very liberal-minded man:
he allowed me a full opportunity to relieve my mind
on the various subjects that came before me,
manifesting a care in his replies.
Whilst we were sitting together,
it was evident he felt that our minds were favoured with that savour of good,
which unites the children of the same family in one,
however different as to name or religion;
which caused the visit to feel precious to visitors and visited.
He expressed at our parting the satisfaction he felt during our silting together,
and with the little matter I had to offer in the line of ministry,
also the desire that attended his mind,
that the Almighty would condescend to strengthen me throughout my journey,
and give me the reward of peace, which he uttered in a feeling, broken manner.

Fourth-day, attended the usual meeting; a quiet favoured time.
First-day, attended the two meetings;
the strangers who gave their company conducted agreeably,
and the evening was passed over satisfactorily; which I felt to be cause of thankfulness.
Second-day, my kind friend.
Dr. Hoist, renewed his obliging offer of introducing me to some persons in authority.
Although for some time past I had felt drawings in`" my mind to some of these,
yet as the time for moving in it did not appear to be fully come,
I again acknowledged his kindness, and left the matter for the present.
Those whose time appears to be always ready, may not be to able read me;
but I believed my accepting of his offer at this time,
and attempting to move in such service, would be premature;
and I must expect my movements would be in weakness,
unaccompanied with that religious courage and boldness which the truth gives,
when a proper care is maintained to move at its command,
and under its qualifying influence.
Fourth-day, attended the usual meeting.

Fifth-day, I was led to take a retrospect of many of my religious movements,
since my arrival on the continent; but, above all,
to commemorate the mercy and care of my heavenly Father over me,
in not suffering me to become a prey to the tempter;
may this retrospect properly humble me, and produce the frequent, fervent,
heart-felt language of, "`I am willing, O Divine Master, to follow thee,
whithersoever thou mayest be pleased to lead!`"

First-day, the meeting this morning was a season of Divine refreshment,
to those possessed of a sincere desire to be found travelling Zionward.
What a mercy is it to know, that the Lord is yet with Zion,
willing to comfort all her mourners, and to satisfy her poor with bread,
wherever scattered up and down on the face of this earth.
In the afternoon meeting,
for some time I had hard work to come at any true settlement of mind;
but after awhile I was favoured to get under exercise, and life was felt to arise.
We had four strangers in addition to our usual number;
the meeting closed under a sense that He who promised to be with the two or three,
had in mercy been mindful of us.

Fourth-day, attended the usual meeting:
during the course of this day a glimmering prospect was
opened before me of a further path of duty I had to travel,
before the way would open for my departure from this field of labour and exercise,
from which the fleshly part in me was disposed to shrink;
but I was favoured to know my mind brought into a
state of resignation to the Divine mind and will,
and I humbly hope, in sincerity to say.
Not my will but thine be done, O my most merciful Caretaker.

Seventh-day,
I was introduced to one of the counsellors of the state in the ecclesiastical department,
in consequence of some difficulties a Friend of Stavanger was brought into.
He gave me a full opportunity of freely conversing with
him on the subject that had thus brought us together.
The following copy of a letter of the bishop of Christian-sands,
will give a statement of the complaint brought against the Friend.

From the Bishop Sorensen of Christian-sands, to the constituted Dean of Stavanger.

In a letter 26th last month, the church department has informed me,
that it has written to the chief-lieutenant of Stavanger county,
that Elias Eliason Tasted is to be prosecuted by law,
for having caused a man to be buried in the same manner as he some time ago did,
with two deceased children,^
footnote:[These burials were in the field of a Friend,
there not being a burial-place of Friends.]
and for which he already is prosecuted; and also required me,
on account of the specification from Elias Tasted,
containing the names of those Quakers who live in and about Stavanger county,
to ask those persons, who are mentioned in the specification,
if they belong to the before-mentioned sect; and then, if the answer be confirmed,
to demand of them a certificate or testimony,
that they by any true Quaker Society are acknowledged or admitted as Quakers.
Each of those persons who profess themselves as Quakers, must besides be told,
that without such certificate he cannot be allowed to live
in this country or kingdom in quality of a Quaker;
and, that even if he has the said certificates, he must, if he intends to live here,
pursuant to the rescript of the 5th of March, 1754, seek for allowance,
by sending his humble petition for this purpose to his majesty the king; which,
according to what in a like case is determined,
cannot be expected graciously to be granted or permitted,
unless they bind themselves not to make proselytes, and from admitting new members,
as also to pay taxes and duties, as other subjects or bergers of the state.

C+++.+++ SORENSEN.

1822+++.+++

In the course of conversation with the counsellor,
it was evident he had imbibed sentiments to the prejudice of our religious Society,
but which we were enabled to answer to his satisfaction.
The counsellor candidly acknowledged,
they had nothing of an immoral tendency to charge Elias Eliason with;
but that he and others took upon themselves to marry and bury,
without giving notice to those in authority previous thereto, also of births,
when they occurred; refusing also to comply with the ceremonies of the Lutheran church.
He considered that such irregularities undertaken by illiterate persons,
would lead to great inconvenience, being contrary to the laws of the country,
and would be attended with serious consequences to the Friends of Stavanger;
and as he had given instructions to the bishop of Christian-sands
and the dean of Stavanger in the case,
he could not at present do anything to relieve Elias Eliason;
but when the case came before the government,
he would give it as favourable a turn as he thought it would bear.
I felt well satisfied with our visit, believing,
from the kind manner in which the counsellor took his leave of me,
that his mind was much softened towards Friends.

Before I left him, he told me,
to attempt to make proselytes was punishable by their laws,
which I received as intended for a kind caution on his part.
In the evening, one of the magistrates made me a call,
for the purpose of private conversation; by our not understanding each other`'s language,
it could not take place: he then requested me to give him my company at his own house,
and he would provide an interpreter.
This providing his own interpreter,
who might put a very different construction on what I said than I intended,
placed me in a trying situation,
more so than would have been the case had I been
left at liberty to engage my usual interpreter,
but whom, from some cause I was a stranger to,
I learnt it would not do for me to propose.
I was brought into a great strait, being unacquainted with the object of the interview;
to commit the replies expected from me, to the mercy of a total stranger,
required a clear view I was doing right:
and to refuse compliance involved the consideration,
that should offence be taken at my refusal,
considering the situation the individual was in,
it might prove the means of bringing Friends here into difficulty at some future time.
Pausing a little after the request was proposed,
I endeavoured to give such a reply as would not be wholly
binding upon me to accept of such help as he should provide.
This unexpected request caused various conjectures in my mind;
led me to recur to the opportunities I had taken with individuals who had called upon me,
particularly the students and others preparing for priests`' orders,
with whom I had dealt plainly,
by laying before them the awful importance of the engagement,
they professed to believe themselves called upon to enter into,
and the remarks that were made to me by the counsellor,
that it was punishable by their law to attempt to make proselytes.
These, and such like considerations, were permitted for a time to try me,
and prove my faith in the all-sufficiency of God`'s power to preserve from harm;
but being favoured in the Lord`'s time to arrive at a state of
quiet resignation to whatsoever he might see meet to permit,
my mind was fully satisfied I might with safety comply with the request of the magistrate,
leaving him to fix the time for our meeting.

First-day morning, the attendance of strangers at our meeting was more than usual,
who generally conducted themselves well:
I thought I had a sense given me that my interpreter was aided by best help,
to give a correct translation of what I had to communicate,
and that the meeting separated under a covering of Divine good.
Our afternoon meeting was large,
and I doubt not proved a season of Divine instruction to many of our minds.
In the evening, agreeably to appointment,
I proceeded to the house of the magistrate before alluded to;
on his informing me of the cause which had induced him to make this request,
I was fully satisfied he was a friend to free toleration in matters of religion,
and a well-wisher to the few professing with our religious Society here.

In the course of what he had to communicate,
it appeared that some unguarded expressions of one of the attenders of our meeting,
relative to the Lutheran place of religious worship,
had given offence to one of those called the church-wardens,
a man well esteemed in the parish;
and that he had laid a complaint before the magistrates,
by which the individual might be brought into difficulty.
I assured him I would give early attention to the subject,
not doubting but I should be able to prevail on the individual
to do all in his power to bring about a reconciliation;
at which he said he felt satisfied;
and that it was his desire Friends here should be preserved
from an increase of difficulties with the government,
for want of proper care on their parts.

Second-day morning, I went with the individual to the offended party,
and gave such explanations and made such concessions,
that he acknowledged he was fully satisfied,
and could say he felt nothing remaining in his mind but love towards the individual;
he requested that the subject, which had so wounded his feelings,
might never more be thought of.
I waited on the magistrate, and informed him of the result of the visit,
which he appeared to receive with pleasure,
engaging to give notice of it to the other magistrates;
and here this unpleasant matter ended.

I felt my mind engaged to make a visit to Hans Neilson Houghe,
the founder of the sect called the Saints, in Norway, which he,
being previously informed of, requested should be select.
Accompanied by my interpreter, I proceeded to his dwelling,
about four miles from the town.
He is far advanced in life, his constitution appeared very much broken,
it is supposed from his long imprisonment on account of his religious principles.
He gave me an interesting account of his first becoming
awakened to a sense of true religion;
from which it appeared to me, had he proceeded as it was evident he had begun,
he would in time have become an instrument in the Divine hand of
arousing the people of Norway from that lethargic state,
into which they appear to be so generally sunk, professors as well as profane.
He informed me he had read Barclay, and made many remarks on its contents,
more particularly on the ministry; he said, when he first found it his duty to preach,
such power attended his ministry,
that great numbers were convinced at different places
where his mind was drawn to hold meetings;
and several males and females, of those who united with him in holding meetings,
came forth in the ministry also, and meetings were settled in different places.
For thus pursuing the path of apprehended duty,
he was cast into prison by the government;
and his followers were threatened with being imprisoned also,
if they continued to hold meetings and kept on preaching.
In this situation,
he wrote to such as had joined themselves to him in religious fellowship, advising them,
for their own safety, to obey the government,
and cease from holding their meetings and preaching as they had done,
but to hold them in private.
He suffered a long imprisonment, and had been fined in two sums;
one for holding meetings and for preaching in these meetings,
and a further sum for having preached and published against an hireling ministry,
and the reproachful conduct of some of the clergy of the establishment.
In order to obtain his liberty he paid the fines,
and compromised with the government for his enlargement,
by promising not to hold meetings or preach as heretofore;
and that he and his followers should attend the Lutheran places of worship again,
conforming to all their religious rites and ceremonies;
and he was now filling the office of a priest`'s
assistant in the parish in which he resides.

I had to call his attention to that declaration of our holy Redeemer,
respecting those who had put their hand to the plough and looked back,
that such were not fit for the kingdom of heaven; and to give it as my belief,
in the state of mind he was at present in,
this awful sentence was sorrowfully applicable to his situation; and further,
to bring before his view the situation of the son, who, when his father bid him go, said,
"`I go; but went not;`" but with this difference,--he had in part obeyed the command,
which he acknowledged had been given him,
but--sorrowful to relate--had stopped short of faithfully fulfilling the whole of it,
whereby the designs of Heaven,
respecting his being thus called to go forth in the Lord`'s name, had been frustrated.
His countenance manifested in a very striking manner
his conviction of the truth of what I offered.
Before we parted I was constrained to allude to his conduct,
after having suffered fines and imprisonment,
for protesting against an hireling ministry, that he should so fall away again,
as to be receiving pay and to become a priest`'s
assistant and collector of the priest`'s wages.
At our parting he manifested an affectionate disposition; and I returned home,
mourning over the dark and dismal state he appeared to be in,
craving that by others`' harms I might be warned.

First-day morning, only our select company at meeting.
In the afternoon there was a great coming in of students and others:
the meeting settled down in stillness.
We afterwards understood the strangers were satisfied in sitting with us.
Fourth-day, attended meeting, in which we had the company of a stranger,
which is unusual at the mid-week meeting.
What I had to offer to my friends, was considered to be a word in season.

Fifth-day morning, much instructed by reading some remarks of Potto Brown,
in Piety Promoted.
"`This day,`" says he, "`was a day of hard labour to me,
because I was off my guard last night, by entering into a long and needless discourse,
which drew my mind from the Lord; but he was good, and heard me when I cried;
for my spirit was bowed in humility before him,
and joy abounded when I confessed my error to him.`"
This is an evil practice, which those who are religiously inclined,
without great watchfulness, fall into;
and is one of the many snares the enemy makes use of to embarrass the mind,
and draw it away from God, its only sure centre:
the wise man has left us this caution on the subject,
"`In the multitude of words there wanteth not sin.`"
How does it, therefore, behoove us to let our words be few and savoury,
seasoned with grace, more especially in mixed companies;
not introducing subjects that may invite debate, or excite levity and worldly-mindedness:
for however we may be preserved from following up the debate we have excited,
or the conversation that has promoted levity and worldly-mindedness, yet,
our being the first promoters of it, I have sensibly felt,
attaches to us some of the guilt of its continuance.

Sixth-day, unlooked-for trials have come upon me.
My dear friend and interpreter, who has been a true yoke-fellow,
willing to enter into the consideration of my religious prospects,
being subject at times to great depression,
has thereby become disqualified to hear what is given
me to communicate through him in meetings,
and to those who call upon me;
and lost the power of clear utterance which he once possessed.
Under these humiliating circumstances I was unable to see the result of this deprivation,
whether the way was likely to open again for my having his help,
or whether I must return home,
not being able to see upon whom besides him I could
throw myself In the afternoon my friend,
the magistrate, called to accompany me to one of the deans whom I had a concern to visit.
I felt so poor, so comfortless, and tried, that I concluded to decline the visit;
yet a dread of doing this came over my mind, lest I should put by the right time for it:
after contending with the mountains of discouragement that had been permitted to rise up,
I was enabled to go in that grain of faith I was yet favoured to possess,
accompanied by my poor, tried friend and interpreter,
whose situation I had reason to believe was as distressing to himself as it was to me.

The dean received me in a truly brotherly manner.
I presented him with a Danish copy of my certificates,
which he appeared to read with interest;
remarking on the arduous undertaking I had before me,
and expressing his concern that my engagements might
be blessed to those where my lot was cast.
I presented him with the Book of Extracts, printed by Friends in Norway,
which he said he received as an acceptable present,
having been desirous of becoming acquainted with the principles professed by Friends.
Thus, as I was brought into a willingness to become like the simple tube,
my embarrassments respecting my interpreter`'s disqualification vanished;
and whilst endeavouring faithfully to relieve my mind of
what came before me in the line of apprehended duty,
I thought I was favoured with an evidence my interpreter
was helped to do his part of the work faithfully;
it was evident his being called upon to aid me,
tended somewhat to rouse him from that extreme depression he had yielded to.
At our parting, the dean requested I would make him another call,
before I quitted Christiana;
and I felt truly thankful I had not been permitted to put by this visit,
as I had wished to do.
The magistrate spent the evening with us.

First-day morning, only our little company at meeting.
In the afternoon we had the addition of one stranger.
After meeting I returned home, hoping to pass a quiet evening;
but this was broken in upon by one of the priesthood of the Lutheran persuasion;
he kept up a long conversation on religious subjects,
but handled them in a very unsavoury disposition of mind,
from the levity of countenance manifested,
and the roar of laughter that was frequently excited.
I felt truly thankful that, from my ignorance of the Danish language,
I was not able to take any part in the conversation, lest I might have been ensnared.
I watched my opportunity to propose our reading some portion of the Sacred Writings,
hoping this might tend to settle our minds; but, to my great surprise, the priest,
who should have been the first to promote the practice, appeared startled at it,
rose from his seat and left us in this unsettled state.

At intervals, during this exercising evening,
the Lord was pleased to give a little foretaste of fat things in store for me, when,
through old age and infirmity of body, my religious services are brought to a close;
provided I maintained my integrity,
delivering his whole counsel given me from time to time, without fear, favour,
or affection: thus I was afresh animated to renew my covenant in the language of,
"`Only be with me in the way that I am to go, by sea and by land;
cause thy preserving power to be ever near, in all I may yet have to pass through,
before the awful, closing scene; even, shouldst thou see meet,
when my years have become years of labour and sorrow,
to require of me to visit thy seed in New South Wales,
lead me whithersoever thou mayst be pleased:
only cause thy constraining influence to follow me.`"

Fourth-day, attended the usual meeting for worship:
a military officer came in and sat down, in addition to our little number.
Sixth-day, the last two weeks have been as distressing as most I have passed through.
May I be preserved in patience under these provings,
should they be but the beginning of the baptisms which await me; and then, in the end,
there can be no doubt, but that I shall have to acknowledge,
all has been permitted in unerring wisdom, for my present and eternal good.
When, through Divine goodness, the way is made in the minds of strangers,
to receive us and our Gospel message, as has been my case here and elsewhere,
great is the danger of getting up in our minds,
instead of continuing to prostrate ourselves in humble
submission before that Almighty Power,
who thus condescends.

First-day morning, in addition to our usual attenders, we had a student and a few others.
The meeting was held long in silence.
Feeling an engagement to offer something before we separated,
I was encouraged to stand up, from a belief that my dear,
tried friend and interpreter would be strengthened to aid me as heretofore;
the meeting closed under a feeling sense that holy
help had mercifully been near for our good.
On approaching the meetinghouse in the afternoon, a company of persons,
students and others, were waiting for the doors to be opened,
who sat the meeting through in a solid manner;
my interpreter`'s tongue was again set at liberty,
and what was communicated appeared to be well received.

Fourth-day, attended the usual meeting,
in which we had cause to acknowledge we were favoured with the teaching of Him,
who still continues to teach as never man taught.
In the evening, the other young student who made one of the merry-making party,
on whose account my mind had been tried, gave me his company,
and received with openness what I had to remark to him on his conduct that evening;
he acknowledged, so far from being hurt at what I had offered to him,
he admired my honesty, hoping my faithfulness would excite him to greater watchfulness.

Sixth-day, the weather inviting, I walked out of town;
the scenery of the surrounding country I thought equalled most I have beheld;
beautifully planted, stupendous mountains, rising one above the other to the clouds;
a vast expanse of sea in prospect, in different directions,--the billows,
one rolling after another,
upon the varied shore,--the sun warming the earth with his silvery beams,
and scarcely a cloud to be seen in the bold horizon;
the numerous land and water fowl appeared in the full enjoyment
of those blessings their beneficent Creator has bestowed upon them;
in a word, I could not suppress the painful idea that man, poor man, only,
fell short in the enjoyment designed for him by his great Creator;
and I felt constrained to confess that the cause originates with himself.
Although sorrow may be his lot at seasons, when the world is permitted to speak trouble,
yet joy and gladness is the predominating experience of the upright in heart.

Feeling drawings in my mind to visit another of the Lutheran preachers,
I mentioned the subject to my kind friend and interpreter,
who manifested so much surprise at my proposal, and reluctance at my making the visit,
without giving me his reasons for his unwillingness, that it tried me much;
but as I thought I felt that which would warrant my not consenting to be put by,
I urged our making the attempt, and we proceeded to his residence.
He appeared to receive what I had to offer, in an agreeable manner, saying,
at our parting, the visit had been a comfort to him.
On our way home, my companion informed me, his reason for hesitating was,
that he knew the individual entertained unfavourable sentiments respecting Friends;
and he feared we should not meet with an agreeable reception.
He had heard a short time before,
that this individual expressed dissatisfaction at my coming to Christiana, saying,
I was come to make proselytes, but it was not likely, through an interpreter,
I should make my way much with the people.

First-day, I hope our meeting this morning was a profitable season to most of us:
several strangers sat with us in our afternoon meeting.
Fourth-day, attended the usual meeting.

Fifth-day, through my kind friend Dr. Hoist,
I received an invitation from the counsellor of state, before alluded to,
to take a family dinner with him;
and as I knew not but the counsellor had something more
to communicate relative to the Friends of Stavanger,
I accepted his invitation.
Accompanied by my kind friend Dr. Hoist, agreeably to appointment, I proceeded.
On our arrival at the house,
the sight of so many carriages in the yard led me to conclude,
instead of a dinner with the family, it was a party I was to mix with.
I endeavoured, although thus disappointed, to meet the numerous company,
who kindly welcomed me, with all the affability I could muster:
the day was passed over on the whole agreeably to myself.
The counsellor, his family and friends, some of whom spoke my native tongue,
endeavoured all in their power to make me comfortable;
and I was led to hope the good opinion I have felt anxious to establish
in the minds of the people of Christiana respecting our principles,
and the demeanour these principles lead to, was not laid waste in any way by me;
but that such inquiries as were called for on these
subjects were answered with Christian courage.

First-day, attended the usual meeting.
Third-day, my kind friend Dr. Hoist called upon me,
with an invitation to dine with the governor tomorrow at the palace:
I felt disposed to excuse myself from accepting the invitation;
but understanding my refusal might give offence,
and as my way to refuse did not appear clear to my own mind, I yielded:
aware that I was going into the way of danger,
I earnestly besought the Lord for help and preservation through the coming day.

Fourth-day, attended the usual meeting,
in which I was favoured to receive a portion of that bread which comes down from God,
the crumbs of which are more availing to our help and preservation in the way of righteousness,
than anything we can receive through instrumental means; for which,
I humbly hope I may say, I felt truly thankful at this needful time.
After meeting, I proceeded to the palace,
not exulting that such a mark of respect was shown me, but in fear and trembling, lest,
amidst so much pomp and splendour as I expected to witness,
any of those testimonies which the religion of the
Holy Jesus requires to be exalted before the people,
by his professed followers, should, through unwatchfulness or cowardice,
not be properly supported by me.

On my arrival, the governor gave me his hand,
expressing his satisfaction on seeing me at the palace:
he then introduced me to the countess his wife,
who also received me with marked attention.
I was next introduced to the chief officers of the state,
who were generally in attendance, and manifested much affability of manners,
giving me their hand.
Such as spoke English were free in conversation,
others regretted our not being able to exchange sentiments;--one in particular,
taking me by the hand, requested his friend to inform me, that,
although we were deprived of the privilege of conversing together with our tongues,
putting his hand to his heart, said,
"`yet I feel we can understand each other here;`" his countenance
gleamed with the pleasure he felt on the occasion,
and which I could say was mutual.
A military officer who had some knowledge of our religious Society,
manifested an interest for further information relative
to the ground of some of our principles,
in which I endeavoured to satisfy him and others who gathered round us.
While thus engaged, a Count Adolph Eugen Rosen, an interesting young man,
well acquainted with the English language, came forward,
manifesting a desire to do his best for my comfort,
surrounded as I was by those who were total strangers to me.
My mind, by this time, had become perfectly reconciled to the step I had taken,
in yielding to the governor`'s kind invitation; I no longer felt myself as a stranger,
except as it respected our language.

I was given to understand,
the governor had kindly interested himself to have me properly cared for at the dinner-table,
and had engaged the count and my kind friend the doctor, to sit on each side of me.
The Baron Weddel, who is governor of the castle and field-marshal to the king,
manifested a like interest in my welfare, and spoke of the pleasure it afforded him,
to have an opportunity to converse about England, where he had his education,
and spent much of his early life.
Thus one circumstance after another combined to render my situation comfortable,
beyond what I could at all have looked for when first entering the palace, especially so,
when I found myself surrounded by the officers of the state in their uniforms,
decorations, and various badges of distinction.
Being placed between the doctor and the baron, I received every possible attention;
the governor, I observed,
was frequently calling upon my care-lakers to see
that I wanted for nothing his table afforded.

During our meal, great quiet was observed; and the wine drunk at dinner,
was taken in great moderation; no silting to the wine after dinner,
but when the meal was over, we retired into the king`'s audience room,
where the guests formed themselves into parties in conversation for about an hour:
coffee was then handed, and before seven o`'clock in the evening all quietly departed.
On taking my leave,
the governor and his wife manifested their regret that we
were not able to converse without an interpreter,
engaging me to come again to the palace before I quitted Christiana.
I returned home, thankful the visit was well got through;
on taking leave of the Count Rosen,
he expressed his disappointment in being deprived of having the charge of me,
and requested me to allow him to call at my lodgings,
which I cheerfully encouraged his doing.
My being seated by the baron at dinner,
afforded me a favourable opportunity of laying before him a subject, which,
amongst other services,
I believed it would be required of me to engage in before I was clear of Christiana, viz:
a visit to those prisoners in the castle called slaves;
on which he assured me no difficulty should be made,
and kindly invited me to call upon him.

Sixth-day, the Count Rosen called upon me; he said he had noticed friends in London,
and at times had felt a desire for an acquaintance with them:
his mind appeared inclined to religious thoughtfulness.
My mind was afresh plunged into suffering,
my interpreter being again unable to render me service through great depression:
I mourned in secret on his account, as well as my own,
from the evidence given me that his mind had been in a very
peculiar manner preciously visited by the Lord;
who, I was frequently led to believe,
had designed him for the top-stone of that spiritual building,
which he intended to be set up in these northern regions,
had he submitted to be hewn and squared by the great Master-builder.

Apprehending the time for my departure was hastening, I concluded,
unless an alteration took place in his depressed mind,
I must either solicit the aid of my kind friend the doctor,
or leave the work I have in prospect unfinished:
but should the doctor be willing even to give up his time to accompany me to
the houses of certain individuals on whom I have it in prospect to call,
I could not expect his aid beyond that.
The thoughts of sitting in meetings,
(as there were so frequently strangers coming in,) under exercise of mind for service,
and no way for relief, was indeed trying:
I saw no way for me but to spread my cause before the Lord;
and I turned out of town and sought a retired place,
where in vocal accents I might pour out my complaint; for I felt assured that the Lord,
and He alone, was sufficient to sustain me and help me safely through.

Seventh-day, from the state of my mind and want of sleep,
my debility of body and the faintings to which I have been subject of late, increase.
If ever I am to become skilful in mourning and lamentation,
I feel as if I was now a scholar in the school where this is taught.
First-day morning, one stranger gave us his company; in the afternoon,
a student in addition: my interpreter`'s mind beginning to brighten a little,
my prospects were more cheering.

Feeling my mind drawn to make a visit to the police-lieutenant,
I proposed to my interpreter making the attempt,
and was comforted by his quietly yielding to it.
We proceeded; he received us kindly, expressing the desire he had felt,
when in company with me at the palace, that we might pass a little more time together.
I produced my certificates;
he said it was pleasant to him to know the ground on which I was moving,
and if it was in his power '`to render me, or Friends here, any service,
it would afford him pleasure to do it, inquiring,
if Friends had a suitable place to meet in: he parted from us affectionately,
and I returned home thankful,
under a hope that the way was opening for me to move on again.

21st of fourth month, we waited upon the chief magistrate, agreeably to appointment;
he received us kindly, saying, he had been desirous of having some of my company:
I presented him with my certificates,
and he made his observations on parts of them as he passed along,
especially that of the select Yearly Meeting,
showing the care the Society exercised over its ministers.
I also presented him with the Book of Extracts, printed here:
the query relative to war he read with apparent attention, remarking,
"`I see clearly that your principles on the subject of war are not properly understood;
many entertaining an opinion you are opposed to government,
and that you are not willing to bear a share of its
burdens with the citizens in common.`"

Fourth-day, attended the usual meeting; a quiet time,
in which I was favoured to lay hold on a little strength.

First-day sat the usual meeting,
in which I had to labour under great weakness and discouragement,
yet with a hope of having done my best, the day closed pretty peacefully.

Second-day, we had a round of company: I ventured down to dinner, yet in great fear;
my safety appeared to be in avoiding to take part in conversation,
yet so as not to manifest anything like sullen silence, which, when yielded to,
hurts the good cause.

First-day, attended the usual meetings;
in the evening our quiet was much broken in upon by company: a young man, a priest,
came in to take coffee with us: observing him conversing with great glee,
and during his conversation making use of the word comedy, it led me to inquire,
why the priest appeared so very much elated about the comedy.
My interpreter informed me he was enjoying the prospect
of spending this evening at the theatre,
a ticket having been given him for that purpose, which he handed round to the company.
I found I must be willing to remonstrate with him
respecting the great inconsistency of such conduct,
and the dangerous tendency of his example,
if he spent his evening at the theatre as he proposed, querying with him,
if he had not been preaching that afternoon?
He replied, he had; and for any thing he knew, he had given satisfaction to his hearers.
I found it laid upon me to reply,
that in the pulpit that afternoon he had professedly
been advocating the cause of Almighty God,
but if he went to the theatre, it was my firm belief he would,
by his example in being there, be advocating the cause of the devil.
I observed from his countenance he could not bear such sentiments,
but it was my place to be firm in what I had to advance:
he pleaded that he was not going to act any part in the play,
as a justification for his attendance; but I felt it right to tell him,
that as a looker-on he made himself a party to all that was going forward;
and there I left the subject.

Second-day, the same young man called,
and frankly acknowledged the disappointment he had met with last evening,
by not having the enjoyment at the theatre which he had promised himself:
he manifested an affectionate disposition.
Fourth-day, attended the usual meetings: spent the evening agreeably with my kind friend,
the +++_______+++.
