== Chapter XX.

Apprehending my stay here would not be of long duration,
and being informed that vessels from Bergen to Hamburgh passed Tannanger,
about seven miles from Stavanger,
I proposed in my own mind to write to a merchant at Bergen,
whose address I had in my possession,
requesting him to inform me when the first vessel would sail from thence for Hamburgh,
and to secure a passage in her, to be taken in at Tannanger;
but on looking more carefully at this proposal, made in my own will,
such a cloud came over me, that I was obliged to relinquish it.
I was afterwards led to see,
had I been suffered to pursue my own inclination in the matter,
it might have involved me in difficulty and distress,
by influencing my mind to leave Stavanger before the time for it had fully arrived.

Fifth-day, attended the usual meeting for worship of Friends at this place;
most of their members and many strangers gave their attendance:
at the close of the meeting a solid-countenanced man, unknown to Friends,
stood up under much apparent exercise of mind, and expressed himself in a feeling manner,
which produced a solemnity over the meeting;
under which precious covering the meeting separated.
We afterwards learnt that a person who was at the meeting I had at Christian-sands,
had written an account of the meeting to some of his friends at Stavanger,
which had brought this man and others to the meeting that day;
and that the substance of what he expressed,
was the commemoration of the Lord`'s continued goodness to mankind,
in commissioning his servants thus to go up and down in the earth,
proclaiming the truths of the Gospel, which he could say he had heard that day.

At the close of the meeting for worship their two months`' meeting was held.
The laws of this country required all, without distinction of sect,
to render an account to persons appointed by government, of all marriages,
births and deaths that take place in each parish,
which requisition Friends here had not complied with;
whereby they had brought themselves under difficulty.
As I had been informed by some in authority, that this omission was deemed obstinacy,
and opposing the order of the government,
and as I could see no ground for their scrupling to comply with the requisition,
in order to prevent a continuance of this omission, I drew up the following minute,
and had it translated for the approval of the two months`' meeting,
to be always the first minute read,
and replied to by Friends who should be appointed to receive these accounts,
and hand them to the persons appointed by the government. Are
there two or more Friends appointed in this two months`' meeting,
to see that due notice is timely given to those appointed
by the government to receive the same,
when marriages, births, or deaths have taken place?
Has any case occurred since last meeting, and has it, or have they, if more than one,
been attended to?`"
which being approved, was entered on their two months`' meeting-book accordingly.

Feeling constrained to labour for a better observance of true Gospel order amongst them,
I recommended that when they discovered any of their members,
or those who were constant attenders of their meetings, walking disorderly,
or heard reports to their disadvantage, they should labour with them in private,
as being the way to promote the unity of the one Spirit, which is the bond of true peace;
and that they should be especially careful how they
judged those of other religious societies,
or meddled with them relative to their religious rites and ceremonies,
unless they were well assured in their own minds
that necessity was laid upon them so to do.
Also to avoid too familiar intercourse with those of other religious professions,
but to keep in view, that Israel was to dwell alone; because,
if we run into the way of temptation for the sake of gratifying our natural inclination,
let it be in whatsoever way it may,
we cannot expect to receive that Divine support and
protection essential to escaping the danger.
I felt thankful in believing these remarks were seasonable and well received.

The son of a merchant, to whom I was quite a stranger, made me a call, saying,
from apprehensions of duty he came to offer his services as my interpreter,
to the houses of such in the government department, the clergy and others,
as I should feel a concern to visit.
I had felt my mind at times, when looking towards visits of this sort,
brought under a great strait,
as the only Friend here acquainted with the English language,
was very imperfect in his knowledge of it, and he in a very humble situation in life,
so that I feared,
when the time came for me to make visits to those who moved in the higher circles,
independent of his imperfect knowledge of the English language,
and want of capacity to give a correct translation of my words,
he might not be so cordially received as to afford a free,
open opportunity with those I visited.
Although I considered this extraordinary occurrence
as likely to relieve my mind on this subject,
yet it appeared to require mature deliberation before I accepted of his very kind offer,
that I might be fully satisfied in my own mind it had the sanction of my Divine Master;
otherwise,
improper views might be given of my communications to the
hurt of the good cause I am professing to promote.
After mature deliberation, I believed I might with safety accept it;
we therefore proceeded together, and made some agreeable calls.

Seventh-day,
my kind young friend had served me so much to the satisfaction of my own mind,
that I solicited his company at meeting, should I need his aid:
this request I observed appeared to try him much, and I did not feel easy to press him,
as he did not profess with Friends: so the matter was left.

First-day morning, my kind young friend came to my lodgings to accompany me to meeting,
although I found he had not got the better of his
discouragements at the prospect of a public exposure,
should I call upon him to interpret for me in the meeting.
My mind being brought under exercise for service,
when the time for standing up was nearly come, I informed him,
and when I rose he stood up with me.
The meeting being attended by many strangers, I feared he would be embarrassed;
but he was helped through the task, much to the satisfaction of the meeting; and,
I doubt not, to the peace of his own mind; as he informed me, when the meeting closed,
he should be willing to accompany me to the afternoon meeting, and assist me again:
thus the language was afresh excited in my mind,
"`What shall I render to the Lord for all his mercies towards me!`"

On my way to meeting in the afternoon, a Friend met me to say,
the meeting-house was already crowded inside and out, and that amongst those assembled,
were the parish-priest, and some of the principal families in the town.
Soon after I reached the house, my kind young friend made his appearance:
on being informed who they were that made up a part of the company,
his mind exhibited much agitation,
and he pleaded so to be liberated from the engagement he had made,
that I did not feel at liberty to press him to fulfill it,
and went into the meeting-house.
I had been informed that many in the meeting were
so far acquainted with the English language,
as to be able, if anything was communicated, to understand what was said.
After I had taken my seat, it appeared to me,
should I have anything to communicate in the meeting,
I must not call upon the Friend of the meeting or
my kind young friend to interpret for me,
but deliver what came before me, and leave the disposal of it to the Lord;
and yet to address such a large assembly in an unknown tongue,
as it would be to the greater part of those who were assembled,
reasoning after the manner of men, seemed like labouring in vain:
but I found it would be unsafe for me thus to reason upon it.
When my mind was brought under exercise for service,
and the time was come for me to rise on my feet, I told the Friend of the meeting,
I must deliver what I had to offer without claiming his assistance as my interpreter.
During the course of what I had to communicate,
the power of Truth so wrought on the mind of one woman,
who I afterwards was informed could not understand a word, that she wept aloud,
exciting general notice; and others manifested much tenderness,
the tears streaming down their faces: the meeting was held in great quiet,
and continued so to the last.

When the meeting closed, my kind young friend said he was surprised,
considering my language was unknown to a large proportion of the company assembled,
at the proofs that were apparent in the countenances of many,
of the good effects produced by what had been communicated.
I returned to my lodgings, I hope,
truly thankful for that Divine counsel and support I had been favoured with:
may the praise be given, both by preacher and hearers, where only it is due,
is the prayer of my soul.

Second-day, accompanied by my young friend, I made a visit to one of the clergy,
who manifested a concern for the promotion of the Lord`'s cause,
and a desire that Friends here should be careful
in keeping their proper places amongst the people;
he also expressed the high esteem he had for our religious Society,
and his desire that tenderness should be manifested
towards Friends respecting their principles,
if they could produce testimonials from Friends in England,
that they were a part of the same religious body.
I informed him they were so far under the care of the Society of Friends in England,
that they corresponded with a committee of one of our meetings in London,
and had recently received an epistle from that committee;
and having procured a translation of it, I presented him with it,
which he appeared to read with considerable interest;
expressing the satisfaction the contents afforded him,
and the pleasure he felt during the short time we had been together.

In the afternoon we visited the chief magistrate.
I had called at his house before, and he being from home,
I left for him the Book of Extracts peculiar to Norway,
which he now told me he had read to his satisfaction.
I told him,
he would see by it the conduct which our principles led its members to observe,
when fully submitted to;
and where shortness manifested itself in any of the Friends here,
by not coming up to their profession, and it came to his knowledge,
it would be a kindness done the Society tenderly to inform them thereof.
He replied, he knew nothing but that Friends generally conducted themselves well;
but laid great stress on the necessity of their having
testimonials from Friends in England,
that they are a part of the same body.
I made him the same reply which I had before made to the priest,
and gave him the translation of the epistle from the committee in London to read,
informing him the Friends there, were as much under the notice of Friends in England,
as was practicable from their remote situation.
He assured me that the statement I had given him was satisfactory,
and appeared to entertain a kind disposition towards Friends,
which I afterwards was informed he had fully maintained.

This evening I received a visit from a young woman,
who a few years ago had joined Friends here,
and at times had spoken in their meetings to satisfaction; but who,
to obtain the necessaries of life, had thrown herself into an exposed situation,
her affections became entangled with a young man not professing with Friends,
to whom she had become married, and had withdrawn herself from the meetings of Friends.
She appeared in a very tender, yet mournful disposition,
from a sense of the great loss which, through unwatchfulness, she had sustained,
as she said, when recurring to past seasons,
in which she had been favoured to feel the incomes of Divine love and life,
whereby she was strengthened, so long as she abode under its influence,
to withstand the assaults of Satan;
but now all the good she was once favoured to be a witness of, was withdrawn from her,
and she found herself left an easy prey to the enemy.
Feeling, as I apprehended,
a sense given me that Divine mercy still waited her acceptance,
I endeavoured to hold out to her the language of encouragement; to seek for that help,
which, if faithfully cooperated with,
I believed would be found all-sufficient for the great work she had to do,
in order to her recovering that good state she was mourning the loss of.
At our parting, a hope was raised in my mind,
that the opportunity had awakened in her a fresh
resolution to make some efforts to obtain that help,
which alone was sufficient to enable her to experience this good state again.
I felt deeply on her account,
as well as the loss the meeting and the cause had sustained through her fall.

Fifth-day, an hour before the meeting-time many people were waiting about the house,
and when the meeting was fully gathered, it settled down in much quiet.
The Friend, who only had knowledge of the English language, sat next me.
I informed him that I believed it would be best for me simply
to cast before the meeting what might be required of me,
and there to leave it, which took place; and we were favoured with a solid, and,
I doubt not to many, a satisfactory sitting together.

When the meeting closed,
I was rejoiced to find my kind young friend in the passage of the meeting-house,
waiting to see if he could render me any service in a private way,
which was truly relieving to my mind;
and as I had a few matters to cast before Friends before I left them,
I gladly accepted his kind offer,
and requested that the men and women who were members would take their seats again.
After a time of quiet, I endeavoured to impress on the minds of those who had families,
the necessity of being careful to give their children an early and sufficient education,
and to induce them to overcome that drawling and very low tone of voice,
in which they were in the habit of expressing themselves,
directing their faces to the ground, when speaking to persons,
from which I was informed disgust had arisen in the
minds of some of the inhabitants against Friends.
My remarks appeared to be well received, and desires were expressed,
I could not doubt in great sincerity, that they might profit by them.
The care which my kind young friend manifested at this time, unsought for by me,
endeared him much to me.
In the afternoon I walked out of town about four English miles,
and had a religious opportunity in a family.

Seventh-day, accompanied by my young friend, I waited upon the lieutenant of the county,
with whom I had an agreeable interview, relative to some difficulties Friends were under,
whose case was before the ecclesiastical court.
He manifested a kind disposition towards Friends, saying,
if those of Stavanger had been able to produce testimonials of their religious
principles being the same as those of Friends in England,
the prosecution would not have been commenced.
I gave him the same reply I had done to others, with which he appeared satisfied.
I left with him the Book of Extracts;
and after his expressing in an agreeable manner the desire he felt
for my getting comfortably forward the remainder of my journey,
we parted.

I felt drawings in my mind to visit an aged couple, about five miles out of Stavanger,
parents to one of the Friends of Christiana;
but who I was informed were much opposed to Friends,
and would not receive two Friends who had been here from England, on a religious visit.
The prospect of making the attempt felt trying;
but fearing I should not be clear in the sight of my Great Master without it,
we proceeded this afternoon, and met with a very cordial reception.
Every effort in their power, according to their limited circumstances,
appeared to be made to refresh our bodies; and we had reason for believing,
that what was offered in the line of ministry was well received;
at parting they expressing the comfort which our visit had afforded them.

First-day morning, as I approached the meeting-house I was plunged into exercise,
by observing the great number of people already assembled: when the doors were opened,
the meeting soon settled down in quiet, and closed under a covering of good;
a thankful sense attended my mind that holy help had been near,
cementing us together in spirit.
I was again comforted in finding my kind young friend was in the passage of the meeting-house,
to lend me his further assistance.
As I expected to take my departure before another first-day,
I requested Friends again to take their seats to
afford us a quiet parting opportunity together.
Much did not appear to be required of me in the way of ministry:
it proved a time in which heart-felt sorrow was manifest,
and many tears were shed at the prospect of our being likely so soon to separate;
but I believed I felt fully satisfied in my own mind the time was come for it,
and that it would be unsafe for me to yield to the entreaties,
to tarry longer amongst them.
After the opportunity closed, feeling something still on my mind to one of the Friends,
I requested my interpreter to remain with the Friend and myself; we sat down together,
and having been strengthened to relieve my mind fully
on the subject with which I had been exercised,
the way appeared clearly to open for me to request Friends
to arrange for my proceeding towards Bergen.

At the afternoon meeting the crowd of strangers was great:
the manner in which the people entered the meeting-house
encouraged me to hope we should be favoured together.
They manifested agreeable attention to what was communicated,
and remained quiet until the meeting closed;
many of their countenances indicating that their minds were seriously affected.
They came up in a feeling manner, and offered me and my interpreter their hands,
which led me to hope he had been favoured with Divine
help in the discharge of his arduous undertaking.
In the evening I returned home with two Friends of the meeting,
who reside with their parents, on an island, about five miles from shore.
The parents do not profess with Friends, but they received me with great kindness.

Before I retired to rest, feeling something given me to communicate to the parents,
I sought for help to be found faithful to this pointing of duty.
They received what I had to cast before them with expressions of gratitude.
Next morning, after a religious opportunity in the family, we returned to Stavanger.
On inquiry being made about a vessel bound for Hamburgh,
it was found that there was one lying at Tannanger, about seven miles from Stavanger,
waiting for a fair wind, and another was soon to sail from Bergen,
which it was expected would pass Tannanger;
but whenever I looked at taking shipping at Tannanger, such a cloud came over my mind,
that I saw no way for me but to decline so doing,
and yet I could not see any prospect of service likely to open for me at Bergen.
In this trying situation, I thought I might truly say my faith was tried,
as to an hair`'s breadth,
from the dread of encountering a voyage of near a hundred miles to Bergen,
on such a dangerous, rocky coast, in an open boat.
But as my friends here thought I should not be able to endure an overland journey,
there appeared no other way for me,
if I was favoured with the continuation of Divine guidance,
in the safe accomplishing of my further prospects of religious duty, but to submit.

After much exercise and earnest seeking to the Lord not to leave me,
until a willingness was brought about in me to commit my poor body to his keeping,
I was favoured to experience the contending powers to be disarmed;
my fears all vanished out of sight,
and I was enabled cheerfully to yield to proceed in this way,
and not to have a desire in my mind to adopt any other,
from an assurance I should be strengthened to endure whatever difficulties
might be permitted to fall to my lot on the passage.
I therefore requested my friends to arrange for my speedy departure.
After inquiry being made for a boat, and a company of men to take charge of me,
and nothing offering that appeared suitable, my kind friend, Thomas, having a good boat,
and he and my interpreter being well acquainted with the coast,
they engaged to provide themselves with such help as would be necessary,
and to take charge of me to Bergen.
As I had expected that I must commit myself to entire strangers,
whose language I could not understand,
I esteemed this a great mercy from my heavenly Father;
and secretly acknowledged it as a further proof of his superintending care,
and say I have lacked nothing that was essential to my getting forward,
when the time was fully come for my proceeding.
May the recurrence to this instance of Divine regard,
excite in me not only the inquiry of "`Lord, what wilt thou have me to do?`"
but a willingness also to yield unreserved obedience to all his requirings;
that I may not be found an ungrateful receiver of his manifold favours.

Previously to my departure I received a visit from two young persons,
who have of late become diligent attenders of Friends`' meetings;
respecting whom a comfortable hope was raised in my mind,
that if they hold on their way as they have begun,
they will add strength to this meeting.
On inquiry as to the cause that had induced them to come and sit with Friends,
as they lived at some distance from Stavanger,
I received the following interesting narrative.
They were members of the Lutheran church;
the young woman had been a diligent attender of her own place of worship,
but absenting herself for a considerable time from it,
the priest of the parish sent for her, and inquired into the cause,
asking if she had anything against him that was the cause of it.
To which she replied she had.
He appeared greatly confused.
She then told him,
she attended the burial of a man who was well known to have been a very irreligious,
immoral character; and that in a sermon he preached at his grave,
he endeavoured to set him forth to the hearers as a man of good conduct--one
who had walked amongst men as uprightly as the patriarch Jacob;
that she durst no longer sit under his preaching.
For some time after absenting herself from the Lutheran place of worship,
she spent her first-days at home,
until her mind was divinely turned towards the meeting of Friends.
At first she met with great opposition from her brother;
but in time her steady conduct so wrought on his mind,
that he has now become her companion in attending Friends`' meetings:
they appeared to be very near to that principle of light and life, which,
if fully yielded to, would make them waymarks to others,
and instruments in the Divine hand of increasing this meeting.

Fourth-day morning, we set out on our passage.
I was favoured to enter the boat as void of fear as if I
had been entering a carriage to travel on a fine,
level road, and not as having a voyage before me of nearly one hundred miles,
in an open boat, off a dangerous, rocky coast.
We proceeded well on our way until noon, when heavy rain came on,
and we put into Corsunt Harbour for the night.
These harbours, between Stavanger and Bergen are very numerous:
in consequence of the rocks and sudden squalls of wind they are subject to in this passage,
many wrecks occur.
I endeavoured to make the best of the miserable accommodation the house I entered afforded,
and next morning we got on our way;
but we had not proceeded far before a heavy fog came on,
which rendered it difficult for the boatmen to steer
their course with safety amidst numerous sunken rocks.
The appearance of the fog, the anxiety manifested by the boatmen for our safety,
the frequent occurrence of these sunken rocks in every direction,
and my getting rather off my watch,
threatened to shake that confidence in the all-superintending care of a Divine Power,
with which I began my voyage;
but from an assurance that exposing myself to these dangers was not in my own will,
but in obedience to His commands, in whose hand is my life, to do with it as he pleases,
I was favoured with ability to resume my confidence,
and all my fears of danger disappeared,
not leaving a desire to be anywhere than where I then was.
The men kept at their labours late this night,
to reach a station where we were the most likely
to have such beds as we might venture to get into.

On sixth-day we again proceeded, the wind being against us,
and having considerable arms of the sea to cross, and a strong current to contend with,
made it hard work for our boatmen; who being desirous of relief,
and coming up with a fisherman, applied to him, when he directed them to take a course,
which soon led us into still water for four or five miles.

We passed between lofty rocks, on the tops of which, in places,
stones of a great size hung above our heads, as if ready to come down upon us,
the passage not being wider than a canal.
The quietness and terrific appearance of the whole scenery,
during this part of our voyage, were truly awful:
the pieces that had fallen down from the top of the rocks into the stream,
scarcely allowed us room to make our way forward, until, to our great surprise,
we came to a termination of the water-course in which we were.
This led us to conclude we should have to return all the way we had come.
Our boatmen held a consultation.
One of them concluded to climb the highest rock, to ascertain how to proceed.
He soon returned, and proposed our taking the luggage out,
and carrying the boat over the rocks,
whereby we should get into another water-course that
would lead us into the track we must take for Bergen.
This we were obliged to do twice before we reached Bergen,
which we were favoured to do before it was quite dark; for which,
and the calm and quiet my mind had been preserved in during the voyage,
I felt truly thankful.

On my ascending the customhouse steps, to have my luggage examined,
a person of respectable appearance accosted me in the English language;
but it being late, and I under some anxiety about obtaining suitable lodgings,
I did not feel disposed to converse with him.
After I left him, I turned back,
and requested he would assist me in finding comfortable lodgings; on which,
without hesitation, he sent a man with me to the house of a widow woman,
a native of Newcastle-on-Tyne, in England, where, during my stay at Bergen,
I was comfortably cared for.
On inquiry, I found a vessel was to sail, bound to Altona, that it was small,
with very poor accommodations for such a voyage;
but believing I must not let the opportunity slip,
I engaged with the captain accordingly.

First-day, we agreed to sit down together in my apartment, to hold our meeting.
Before the time for our sitting down, three persons made us a call;
and as they appeared disposed to enter into serious conversation,
I felt myself brought into a strait.
The time for our meeting being come, and not feeling easy to desire them to withdraw,
I requested one of the Friends to inform them of our intended meeting,
and leave them at liberty to stay or not.
They were disposed to remain with us, and I humbly hope to a good degree of profit,
the meeting closing under a feeling of solemnity.
In the afternoon meeting we had several others in addition to those we had in the morning.

On looking back at the service which I believed was called for at my hands,
and querying in my own mind, Is any good likely to come of this day`'s work,
considering how imperfect my interpreter was in the knowledge of the English language?
the language of the blessed Master, "`Gather up the fragments,
that nothing may be lost,`" was brought to my mind; accompanied with a belief,
that if the people did not receive all that was given me to hand to them, yet,
if the fragments were but carefully gathered up,
the labour of the day would not all be in vain;
which had a tendency to settle my mind in the quiet.
Feeling drawings to make a visit to the prisoners who are called slaves,
I mentioned the circumstance to my friend, the consul for Lubeck and Bremen,
to whom I had a letter of introduction.
He informed me they were under the care of the governor;
and on my proposing to wait upon him to obtain his permission,
the consul kindly offered to accompany me, which I gladly accepted,
as he was well qualified to act as my interpreter.

The governor received us very respectfully;
but I had some difficulty in getting him to enter into my views,
he supposing that I intended to publish an account
of the manner in which the prison was conducted,
and the state of the prisoners.
When he understood my motive,
he without further hesitation requested me to fix my own time,
and the captain on duty should have the prisoners assembled for the purpose,
and he should attend upon me.
I again saw fresh cause for thankfulness to my good Master,
in thus making way for me in the mind of the governor.
In the afternoon I walked out of town, and took tea with a merchant and his family:
feeling my mind drawn into silence, something was given me for communication,
and endeavouring to be found faithful,
what I had to offer appeared to be gratefully received.
On my way home, I was enabled, as it were, to skip over the mountains,
and afresh to set up my Ebenezer to His praise,
who still in mercy continues to be my present help in every needful time.

Third-day morning, I made a visit to the dean of Bergen; he received me kindly,
spoke some English, but understood it better than he could speak it.
I presented him with some books, which he received freely.
At our parting, expressed the solicitude he felt,
that my views in taking such a journey might be blessed to those I visited,
and that God would preserve me, and grant me a peaceful return to my family:
he then added, although there were so many distinctions amongst men,
with regard to their profession of religion, yet religion being a heartfelt work,
it must become the experience of all, who are favoured to find acceptance with God.
I proceeded with the consul and the Friend who had
occasionally acted as my interpreter to the castle,
where the prisoners are.
On our way I solicited the help of the consul as my interpreter,
but as it appeared a task of such a public nature, finding it would be trying to him,
I did not feel easy to press it; especially, as he assured me,
if my interpreter was at a loss he would assist him if there was need for it.

On our arrival at the castle,
we were received in a very respectful manner by the captain of the guard,
who conducted us to a room where the prisoners were assembled:
during a short space of silence,
I thought I never felt more need of an increase of faith;
and when strength was given me to open my mouth, it was under such feelings of weakness,
that I was led to fear I should not be able to acquit myself so as to obtain full relief:
but by being willing to make use of the strength mercifully afforded,
I was favoured with an increase.
Great quietness and attention were manifested on
the part of the prisoners and their attendants;
the countenances of many appearing to be seriously affected.

At our parting I found, if I followed the pointings of duty,
I must offer each of the prisoners my hand,
to which at the moment a degree of reluctance was felt within; but on offering my hand,
they generally returned theirs with marks of good feeling.
Some who were able to speak English,
expressed their desire that the counsel which had
been imparted might prove profitable to them,
and acknowledged their thankfulness to the Almighty
for inclining my heart to pay them this visit.
The preacher of the German congregation and the consul had informed
me there were two members of our religious Society in Bergen:
this information took such hold of my mind that I requested them to send the Quakers,
as they called them, to my lodgings.
They were described to be very poor, but highly respected by people generally,
for their uniform steady, good conduct.
The man came to my lodgings, and brought his wife with him.

From the account I had received of their poverty, I was much struck with their neat,
clean, and respectable appearance;
but soon satisfied myself they were not of our religious Society,
but part of a company who several years ago suffered great persecution,
on account of their religious principles, in the late king of Wirtemburg`'s dominions.
On inquiry, it appeared that, in many respects, they held the principles of Friends,
with regard to war, oaths, language, and respect of persons.
The woman, who appeared very intelligent,
gave me the following account of some of their sufferings,
in consequence of leaving the established religion of the nation.
Their number was small; and their good conduct so gained the esteem of the king,
that he gave them a parcel of land for a settlement; but in time,
their number increased to several hundreds.
When this great increase came to the king`'s knowledge, he withdrew his kindness,
and began to persecute them; in doing which, it was supposed he was put on by others;
casting into prison men, women, and children as young as ten years of age;
having the men flogged almost daily, until the blood ran into their shoes,
to compel them to renounce those scruples which they believed
they were called upon to maintain against war,
oaths, flattering language, hat-honour, and other matters of faith.

The governor of the castle,
fearing lest their constancy under these sufferings should excite compassion
in the minds of those appointed to execute this rigour of the law,
generally attended in person,
to see that no part of the punishment designed to be inflicted should be omitted.
One day the individual,
who had been an instrument in the Divine hand of gathering this religious body,
being brought out to undergo his punishment,
the governor standing by to see that it was faithfully inflicted, the poor man,
whilst under his sufferings, addressed the governor in nearly the following words,
"`The Lord will reward thee for thy cruelty, in that thou art so unmerciful towards us.`"
At which the governor smote him several times over his breast with his sword, saying,
"`Dost thou, thou me?`"
to which he replied, "`I say, the Lord will reward thee for thy cruelty towards us;
and thou shalt never be able again to witness such acts of cruelty towards us.`"
At which the governor spurred his horse,
and the beast set off with such speed that he fell with him;
whereby his sword was forced out of its sheath, and entering his body at the hip,
wounded him in such a manner, that he never was able to leave his bed while he lived.
This circumstance reaching the ears of the king, he gave orders,
that those who had these poor sufferers in their power,
should be careful not to endanger their lives when punishing them.

Another of the officers was equally cruel; for after having them so severely punished,
that when they were loosened from the post to which they had been fastened,
they scarcely had strength to stand on their feet;
the next day he would have them driven like cattle to hard work.
After long and severe imprisonment, the king gave them their liberty,
on condition that they left his dominions;
the sufferers disposed of what property they had left,
and seven hundred of them engaged their passage in an American vessel,
to be put on shore in some part of the United States of America;
but even then their sufferings did not terminate,
from their falling into the hands of a cruel captain.
The following account of his conduct towards these, his passengers,
was given me by Henry Otiley, his wife, and J. Hurtz, passengers.

She sailed from Holland in 1817, with seven hundred passengers on board, including men,
women and children: each passenger was obliged to pay for his passage in her,
and for provision during the voyage on going on board.
She sailed the next day up the Texel, where she lay at anchor ten days:
she then sailed again for two weeks, and returned to the Texel,
the captain alleging they had not sufficient provision and water:
here they remained for twelve weeks, the captain saying, the wind was contrary.
At the expiration of the first six weeks, the captain told the passengers,
that the provision which was to have served them
until they arrived on the American shore,
was exhausted, and they must purchase from him with the money they had left,
their further supply of provision, which he sent for daily to an island near;
he charging them an exorbitant price.
This continued to be the case for six weeks:
several young men on board were desirous of going on the island to purchase for themselves,
but were forcibly prevented.
Three hundred died of a fever, occasioned by the want of proper food and water:
as fast as they died the captain took possession of their effects,
and their bodies were committed to the great deep,
and sometimes before life was quite extinct.
Several young men on board united and went to the captain`'s cabin
to force from him a better supply of provision and water,
but found the captain and some of his men armed with muskets;
the captain and his men secured those who were the most active in this attempt,
and severely flogged them.
If any complained, the captain frequently caused them to be punished;
and when mothers begged, with all submission, for a little water for their infants,
saying, they were dying for want of it, the captain would refuse, saying,
"`Let them die!`"
He continued these practices,
until he considered himself in danger of having the
provision taken forcibly from the boat,
by those who were no longer able to pay for it.

At length the ship, by order of the captain, was put under full sail,
notwithstanding his sailors remonstrated with him; a storm coming on,
the three masts were broke, and they were in danger of being lost.
A few days after they broke their masts, an English vessel came up to them,
the captain of which offered to take the passengers to England:
after a long dispute with the steward, the steersman and the passengers,
the captain refused the offer.
He then endeavoured to prepare a boat for himself to quit the vessel, but the steward,
whose wife and children were on board, would not suffer him to leave;
but cut the rope of his boat and sent it adrift.
The captain then put into Bergen, where he set the passengers on shore,
under pretence of the vessel undergoing repair; after which he sold her privately,
and disappeared, leaving his passengers to shift for themselves;
many of whom were so feeble for want of food,
that they were not able to land without assistance:
notwithstanding he had water and provision in the vessel when he decamped.

Before their case was fully known in Bergen,
I was informed by different respectable individuals there,
that some of them died for want,
and from being confined for room in the places where they took shelter,
a fever broke out amongst them, whereby nearly one hundred of them died.
Children were left without parents to care for them, which,
children some of the wealthy inhabitants took into their families.
Such as had property still in their possession sold it, and went to North America;
but many whom the captain had stripped of all for a supply of food,
were obliged to remain behind.
Their situation coming to the knowledge of the king of Sweden,
he had them conveyed to America to join their countrymen; but this man,
Henry Otiley and his wife, were left behind.

When the woman had proceeded thus far with her recital of this disastrous account,
for a while she was unable to proceed, being so bathed in tears,
more particularly at that part of it, about their being left behind,
and separated from their relations and those with whom they were in religious fellowship;
being left amongst those whose language they could not generally
understand,--stripped of all their property,
and no religious society with whom they could unite.
She further informed me,
they had by their industry saved one hundred and twenty-five
dollars towards their passage to North America:
that there was an American vessel in the harbour about sailing for the United States,
which sum they had offered the captain for their passage,
it being the utmost they could raise,
the household furniture which they used being only lent them;
but the captain demanded two hundred and fifty dollars,
and they were to find their own provision for the voyage.

The poor woman appeared to despair of release from their trying situation,
if this vessel should leave them behind.
Their case fastened on my mind, and I found,
without doing violence to my religious feelings, I could not cast them off.
I applied to the minister of the German congregation, who informed me,
they were much respected by the inhabitants for their industry,
and steady upright conduct;
and manifested much interest in their being helped to join their brethren in North America;
but appeared discouraged about the money being raised for the purpose.
No way appeared to me so likely to raise it,
as by a petition being presented to the wealthy inhabitants;
I therefore prevailed on the minister of the German congregation,
to draw up such a one as I could be easy to take an active part in presenting,
should no one else be willing to step forward for their help.

Although the different individuals I spoke to on the occasion,
gave it as their opinion the money would not be easily raised,
I found I must not desert the post I had taken; I therefore began the subscription,
on behalf of some of my German friends in London, with twenty dollars,
in hopes it would prove a spur to the generosity of the wealthy inhabitants.
I then consulted my friend, the Lubeck consul,
on the propriety of my going on their Exchange with the petition,
at the time when the merchants were generally assembled,
and presenting the petition to such as were likely to give: he encouraged my doing so,
and agreed to accompany me.

I then called upon the English consul, to whom I found Henry Otiley was well known,
and by whom he was highly spoken of,
who encouraged me to be on the Exchange as I had proposed, saying,
he would prepare the minds of some of his friends to attend to the petition when presented.
Accompanied by the consul, at the time considered the most suitable, I attended;
and in a short time raised nearly the whole of the
amount wanted to complete their passage money,
their provision, and a stock of leather, Henry Otiley being a glover,
to employ him on ship-board,
that he might not be destitute of the means of raising some money when he landed.
The subscription being now so nearly completed,
the two consuls took charge of the petition, assuring me,
they would not quit their post until the whole was completed.
Fearing lest any shortness should occur,
I did not feel myself fully acquitted without giving the consul liberty,
if it should be needful, but which was not the case,
to apply to my friends at Altona for twenty dollars
more on account of my German friends in London.

I next proceeded to the captain, who assured me they should not be left;
and then to Henry Otiley and his wife to set their hearts at rest:
but the account of what had been done had already reached them,
and their countenances sufficiently manifested the gladness
of heart that had taken place of the sadness and depression,
which had been so strikingly portrayed in their countenances: the woman,
in a very pathetic tone of voice, exclaimed, "`The ways of the Lord are, indeed,
ways of wisdom,`" accompanied with strong expressions of gratitude.
Their feelings of gratitude, I thought, could not much exceed my own,
in having been instrumental in their relief from suffering.

After leaving Henry Otiley and his wife,
not feeling that I had done quite all that was required of me,
as the vessel they were going in was bound for Baltimore, I returned,
and wrote a note to two Friends, who I supposed resided at that place,
requesting they would assist them in turning their gloves into money,
and proceeding to the settlement of those who went over before them;
this note was afterwards of singular use to them in England,
where they were again brought under fresh trials.
The consul having engaged to procure their passports,
my mind was at liberty to leave Bergen,
when the vessel I had engaged my passage in to Altona was ready to sail.
I received a visit from the person who accosted me in English on my first landing,
and who so kindly cared for me about procuring a suitable lodging;
although it appeared he was a stranger to our religious Society,
yet from the remarks which he made on several subjects, especially that of oaths,
he was evidently convinced in his judgment of many of our religious principles:
he lamented his not being, as he termed it, a free man,
as he said would have been the case with him,
had he been brought up in the mercantile business;
but now the fear of giving offence to the government, he frankly acknowledged,
was in the way of his publicly avowing his religious principles;
he had a wife and family wholly dependent on him.
I viewed his situation as a mournful one,
but did not feel sufficient to justify much interference on my part.
I gave him the Book of Extracts and a few pamphlets.

Fifth-day, we held our little meeting:
in addition to the Friends who came with me from Stavanger,
we had the company of Captain Erasmus Jepsen, who resides at Marstal Poa Eroe,
in Denmark, who has long separated himself from the established worship,
and sits down in his own house with his family,
in order to perform religious worship as Friends do; and,
from what I was able to understand,
his conduct was much the same as that of a consistent Friend.
I was led to hope, that in this our little parting meeting,
we were enabled each one afresh to renew his covenant:
may we be favoured to keep our covenants, and then,
should our parting prove a final one as to this world,
our souls will again unite in praises and thanksgiving to Him,
who in mercy has condescended to snatch us as brands out of the burning.

This afternoon I received another visit from my friend
who so kindly cared for me on landing;
he informed me he had, with much satisfaction, read over the Book of Extracts,
which fully comported with his own views, on the various subjects it contained;
he again lamented that his situation in life was a bar to his making
that public declaration of his religious principles to the world,
which he otherwise should do.
Notwithstanding it was evident he was acting against conviction,
yet as my way for much interference appeared to be still closed up,
I believed it was both safer for myself and for him,
that I should be sparing in my observations on his trying situation,
and leave him to the good Power who alone was able to effect his enlargement.
The remarks I felt at liberty to make, appeared to be well received;
the tears at times copiously flowed from his eyes; and at our parting he said,
he could not find words to express the joy it gave him,
when he cast his eyes upon me in the boat, before my landing.
It was some time after our parting,
before my mind was in degree relieved from the painful feelings excited on his account,
fearing he would remain a Nicodemus to the end.
I proposed sending him a Barclay`'s [.book-title]#Apology#, which he said he would gladly accept.

Seventh-day, the captain came to inform me, he should sail this afternoon,
or in the evening.
The time now being nearly come for my quitting Norway,
the extension of Divine preservation and help I have been favoured in many ways to experience,
is cause of reverent thankfulness.
I have not passed along without at times anticipating danger,
lest I should get off my watch,
and be drawn out into conversation beyond my proper business,
and my words be used to my disadvantage:
yet on as impartial a retrospect as I have been capable of taking,
I cannot find that I am charged by my Divine Master
with having acted the part of a coward in his cause,
notwithstanding the caution, and in some instances, threatening of some persons,
in stating, that the laws of Norway are severe on an attempt to proselyte;
but I endeavoured, both in public and private,
before I committed myself by giving a sentiment on a religious subject,
to feel something of the woe if I kept silence; and when this woe was felt,
to deliver what came before my mind with becoming boldness,
and in that courage which the truth gives: thus fresh cause is felt by me to declare,
the Lord has been my shield and buckler, and exceeding great reward.

At four o`'clock this afternoon we set sail;
my companion in the cabin was a Lutheran preacher,
whose place of residence was on an island on a rocky part of the coast.
At first we had calm weather,
but after a while a very violent storm of wind and rain came on.
The whistling of the wind,
and the frequent dashing of the tremendous waves against the sides of the vessel,
as if they would have met each other, formed a truly awful scene.
My mind, in adorable mercy was preserved calm through the whole, and I could say,
I was not permitted to feel a desire to be anywhere than where I then was;
although an affecting event at times came before my mind,
which occurred a few months past on this part of the coast,
of upwards of one hundred fishermen and boys leaving
Bergen and its neighbourhood to go a fishing,
on a fine sun-shining morning,
when a storm suddenly arose soon after they left the shore,
and they not being able to return, it was said, nearly the whole of them perished.

First-day, the weather being fine, we made some little way.
Second-day, we reached Carr-sun; here we took in a friend of my companion, the preacher,
who spoke English.
At Carr-sun we cast anchor, and I went on shore for about six hours,
which was a great relief; as our vessel was very small,
and we were sadly pent up for room in the cabin.

Fifth-day, we were favoured to get clear of this rocky part of the coast; and out to sea.
Sixth-day night, it blew a tempest; awful both to hear and feel,
from the violence with which the vessel was tossed to and fro.
The Lutheran preacher appeared much alarmed, frequently rising up in his bed,
calling for the captain, wringing his hands, and weeping in great distress.
I did all in my power, by signs, to encourage him to look up to heaven for support;
but it seemed as though he had no hold there to afford him any consolation.
I was favoured with assurance in my own mind that we should land safely;
at times remembering that my great Master had not yet given me my discharge,
but had given me clearly to see, when this visit was brought to a close,
he had yet further service for me,
and therefore would not suffer me to become a prey to the unstable elements.
The weather being likely to prove stormy,
our captain proposed taking a pilot at Heligoland to take us to Cuxhaven,
in order that we might reach the custom-house at Harburgh in proper time.

After a tremendous night, on seventh-day morning the storm abated,
and we were favoured to land at Altona, about twelve o`'clock on first-day night.
We were informed, that during the storm, on seventh-day night,
several vessels were driven on shore; and received damage various ways:
fresh cause for thankfulness that we were favoured to escape without accident.
Having reached Altona, earnest were my desires,
that if my great Master had any service for me here, I might cheerfully yield to it.

After endeavouring to cherish this disposition of mind from day to day,
and make a proper disposal of books sent me from England,
feeling myself at liberty to prepare for my journey to Pyrmont in Germany,
I called to take leave of my friends at Hamburgh and Altona;
and found I must not pass by the police-master at Altona.
I gave him my hand, telling him, it was the hand of love,
accompanied by a desire that if we should not be permitted to meet again in this world,
we might meet in heaven: this salutation appeared to strike him in a forcible manner,
and he gave me his hand in a way that evinced sincere regard.

After taking leave of dear Henry Vandersmissen and family,
I was accompanied by a servant of theirs to Harburgh;
from Harburgh I proceeded by coach to Hanover:
after much fatigue from the construction of our carriage, the badness of the roads,
and our slow travelling, we reached Hanover early on first-day morning.
No one understanding English at the hotel I was taken to,
was a fresh exercise of patience,
as I should have been well pleased with some refreshment;
but being shown the room I was to occupy, and the bed being prepared for me,
I satisfied myself with trying to get some sleep, which I was not able to accomplish.

Having a letter to a merchant in the town to assist me as I needed,
I procured a messenger to accompany me there: here I met with a brother of the merchant,
who spoke English, and kindly proposed to serve me.
I had concluded, by the advice of my friends, to remain at Hanover two days,
to recruit my strength after the fatigue of the journey:
but on inquiry about a conveyance to Pyrmont,
it appeared I must proceed again this afternoon, or remain at Hanover until fifth-day.
This placed me under difficulty, as it did not feel to me,
although my mind was afresh brought under exercise on entering this place,
that now was the time for me to make a halt.

Towards evening we reached Harmel, here we waited five hours,
and changed our carriage for a wagon, with a covered seat slung in it,
so miserably stuffed,
that from the badness of the roads my back was sorely
bruised during the last ten miles of our journey.
We did not arrive at Pyrmont until five o`'clock on second-day morning,
having been seven hours in travelling ten miles.
I was at a loss to know how to proceed on my arrival; exhausted in body,
and my tongue as it were of no advantage to me,
as none at the coach-office could understand what I said.

Whilst thus ruminating on the course to take,
a person who had come in a wagon on the same route from Harmel, came up,
and addressed me in broken English, which caused my heart to leap for joy.
I informed him how much I needed to lay down upon a bed,
and asked him if he knew where any Friends lived, to take me to their house.
He said he would take me to the house of a family who were Quakers,
and who were in the practice of letting lodgings; this cheered me not a little,
and caused me almost to lose sight of my sufferings,
although from my swelled ankles and feet, and sore bones,
I hardly knew how to get over the ground, having half a mile to walk.
When we arrived at my expected home, from the garb of those who kept the house,
it would seem they were respectable members of our religious Society;
and they offered to take me in, but, why I could not then understand,
I felt fully satisfied I must not take up my abode with them,
and therefore told my kind friend who had brought me there, I must seek other lodgings.
We returned into town, and after much search obtained a lodging: bed was more than food,
although I had not had a regular meal since my breakfast the preceding morning.
I had my bed prepared, and after getting some sleep,
I rose in hopes of procuring a guide to walk with me to John Seebohm`'s,
where I was to take up my quarters; but this I found was two miles from the town,
which I was now quite unequal to undertake:
necessity therefore compelled me to remain where I was.

Third-day morning, I turned into the garden for air;
and hearing some footsteps behind me,
I was agreeably surprised at the sight of two Friends, John Seebohm and John Snowden,
from Bradford, in Yorkshire;
as they were passing the house my landlord informed them of my being there.
I was afterwards conveyed with my luggage to Peace Dale, to John Seebohm`'s,
where I soon found myself comfortably at home:
here I met with Benjamin Seebohm and John Yardley, from England.

On my describing to the Friends the situation of the house I was first taken to,
and the individuals who were the keepers of it,
they informed me they had been in membership with the Society of Friends,
and the man once filled the station of an elder with great propriety;
but through some of the stratagems of the enemy,
they had so far swerved from the sure foundation,
that both of them had forfeited their membership,
and become great persecutors and bitter enemies to the good cause they once espoused,
and wholly absented themselves from the meetings of Friends.
It was fresh cause for reverent thankfulness,
that I attended to the secret caution in my own mind at that time,
otherwise I might have been influenced by prejudice against the Friends of Pyrmont,
which might not easily have been shaken off.
This escape excited in me fresh desires to be preserved steadily attending to my stops.
