== Chapter XXI.

Fourth-day, attended the usual meeting;
many strangers came in and sat the principal part of the time: it proved a solid,
quiet meeting.
Fifth-day put on my round frock and turned out into the garden to labour;
I found it rather trying to the flesh,
yet I was afraid of flinching from this part of my duty.
Sixth-day, my employ occasioned me much pain in my back;
nature was disposed to be excused, yet I found I must be willing to persevere,
not doubting but that, in time, these hard things would become more easy;
and as it was a part of the terms on which my Divine Master engaged me in his service,
that I should fill up my leisure time in some useful employment,
that I might be a good example in this respect to others, I feared,
if I refused to comply, my Master would discharge me from his service,
and I might exchange my back-aching for heart-aching;
one night`'s rest would do much towards curing my back-ache,
but if heart-aching was to be the result of flinching from my post,
where am I to go to seek a sovereign remedy for it?--these
considerations spurred me on to my duty.

First-day, attended the usual meeting;
in the early part of which it was evident the Divine presence was near, which,
if it had been yielded to, would have gathered all under its benign influence;
but it was sorrowfully interrupted by the going out and coming in of strangers,
which is much the case during the season for drinking the waters:
in the evening we had a sitting in the family, I thought to good satisfaction.
Fourth-day, attended the usual meeting; many strangers were waiting for admittance;
it proved a solid meeting,
and the countenances of some of the strangers manifested
that they had been introduced into religious thoughtfulness.

First-day, the meeting was numerously attended by strangers,
most of whom stayed through the principal part of it, and appeared solid,
and attentive to what was communicated;
yet the meeting suffered loss by persons leaving it before it closed.
I have observed, on the continent,
that there is generally great irregularity in going
to and leaving the places of religious worship.
Feeling drawings in my mind to make a visit to the resident preacher at Pyrmont,
I sent him the address to the magistrates and clergy of Hamburgh,
with a message of my intention, and requesting he would fix the time for it.
First-day, the meeting was large, and upon the whole comfortable.

Second-day, I resumed my daily labour, which is no little relief to my mind,
as I become better able to bear it;
and am unable to converse with Friends here if they make me visits.
Fourth-day, attended the usual meeting, my friend Benjamin Seebohm,
who understood the language, being absent,
and my mind brought under exercise for service, I was placed in a trying situation;
the thoughts of being obliged to express myself in an unknown tongue, felt humiliating.
I inquired if there was any one present who understood the English language,
who could interpret for me, but no reply being made,
I could see no other way for my relief,
but by expressing what came before me for communication, and there to leave it.
Great quietness was observed whilst I was on my feet;
the countenances of not a few appeared solid,
and the meeting afterwards settled down quietly,
the strangers keeping their seats beyond what is usual.
Towards the close of the meeting, something was given me for the members of the meeting,
which was a fresh trial,
but as there was no way for me to preserve peace of mind but to offer it, I did so.

After I had sat down,
one of the members of the meeting stood up and spoke in the German language;
although I could not understand the words, yet, at the time,
a sense was given me that they corroborated what I had offered.
On inquiring, after meeting, of my friend John Yardley,
who was sufficiently conversant in the German language
to understand what the Friend had said,
I found my feelings had not deceived me,
and that what the Friend offered was a repetition of part of what I had communicated.
I wished the Friend to be asked if he understood my words, to which he replied,
he was not able to, but putting his hand to his heart,
said he felt there the import of them.
Although the meeting was to me a deeply baptizing one,
yet the retrospect afforded peaceful reflection:
may I never forget these merciful interferences of Divine goodness,
but forever bless his holy name and power,
through which my deliverance has been effected.

First-day, 11th of eighth month.
The people who were waiting about the meeting-house followed us in,
but being weary of silence, soon left it again,
and were succeeded by others who did the like.
This desire after words, calls for an increase of patience, and a godly care,
when the mind is under exercise for service, lest Saul-like,
through the importunity of the people after words,
we should be tempted to make our offerings before the time; and on the other hand,
not to suffer these interruptions to unsettle our minds,
and prove the means of keeping back that which is given us for the people,
when the time for it is fully come.
At the close of this meeting,
I laid before Friends a concern to visit the families of members, attenders,
and others who have absented themselves from the meetings of Friends;
my friend John Yardley proposing to be my companion,
our prospects were united with by the Friends of the meeting,
and our kind friend Benjamin Seebohm being returned,
was to accompany us as our interpreter.
My mind had been for some time exercised with an apprehension
it would be required of me to walk in the Alley,
or Parade, on a first-day evening,
this being the chief place of concourse duinng the season for drinking the waters;
the theatres, gaming tables, and principal shops are situated in the Alley.
This evening, accompanied by my friends, Benjamin Seebohm and John Yardley, I proceeded,
I think I may say, in fear and trembling, unable as I was to see the result:
this step afforded a peaceful close to this day`'s work.

Second-day we proceeded to visit the families, and had six sittings;
in some of which I was introduced into feelings, whereby the creaturely part was abased,
and self laid as in the very dust.
When the day`'s work closed, and the retrospect was taken,
thankfulness was the clothing of my mind, that I had been in mercy made subject.
Third-day, proceeded again with the visit to the families.
Fourth-day morning, we sat with a poor, honest female, who earns her living by spinning,
and is obliged to work very hard;
she is a striking example of diligence in getting out to meetings;
and we had good satisfaction in this opportunity.
After meeting, we sat with one of the families that have left the meetings of Friends;
at our parting they appeared affectionate, and we were satisfied with the visit;
the day closed agreeably to us all.
Seventh-day, we proceeded to the meeting-house to examine the stock of printed books,
the property of Friends in England,
but from the tried state of my mind I was unable to take much share therein.
May every proof of Divine regard be blessed to me,
and may I be preserved from desiring that the thorns in the flesh,
the messengers of Satan, which are in mercy permitted to buffet me, should be removed,
until they have done that for which they are designed.

First-day morning, the meeting suffered loss by the going out of strangers as heretofore.
In the afternoon I proposed to Friends the establishing of a reading-meeting,
to be held on first-day evenings;
some of the time of these meetings to be spent in silence,
and some in reading portions of the Sacred Writings,
and such publications of the Society as were best calculated to
furnish the mind with a correct idea of our religious principles,
and of the virtuous lives of our departed worthies; which being united with,
some Friends were nominated to propose the hour and the place to meet at.
My friend John Yardley also proposed establishing a school,
to be held two evenings in the week, to instruct the children in the English language,
which also met with a cordial reception.
In the afternoon.
Friends held their preparative meeting, men and women uniting in conducting the business.
Although I was not able to understand what passed in the meeting,
yet a sense was given me, that in transacting their business, best help was near.

First-day, 18th of the eighth month.
This evening we had a pretty general attendance of parents and children at the reading-meeting,
Friends having been previously named for readers,
who were to select suitable matter for reading.
After some time passed in silence, a few chapters out of the New Testament,
and parts of Sewel`'s History, were read; a pause took place, and Friends separated,
each manifesting satisfaction at being present at the opportunity.

Second-day, accompanied by my kind friends, John Yardley and Benjamin Seebohm,
I waited upon the resident preacher of Pyrmont, who received us kindly.
I introduced myself by giving him my certificate, which he read with seeming attention,
making observations as he passed along.
I laid before him the absolute need there is for the professed
ministers of Jesus Christ to seek for Divine aid,
that, through its all-sufficiency,
they may be found valiant in opposing the reign of Satan on the earth,
in all his devices and workings, and without fear, favour or affection,
using their influence with those in authority for the suppression of vice.
I felt much for my dear friend and interpreter,
who I believe did his business conscientiously.

First-day morning many strangers were waiting for admittance when we reached the meeting-house,
amongst whom I made a distribution of tracts; the meeting soon settled down quietly,
and we were favoured to continue so to the close;
and solid attention appeared to be given to what was offered.
In the afternoon, the two months`' meeting was held;
from the precious covering to be felt over the meeting,
I hoped a good degree of right concern for the promotion of the cause of Truth and righteousness,
prevailed in the minds of those who took an active part in the business.
In the evening we had a large gathering at the reading-meeting, at Peace Dale,
which we hoped was a favoured time to most;
our hearts being afresh humbled under a sense that Israel`'s Shepherd
was waiting to be gracious to this part of his flock,
if there was but a willingness to accept his offers of help on his own terms.

My mind had for some time been exercised with an
apprehension that it would be required of me,
to attempt an interview with the Prince of Waldeck,
and the weight of this exercise increasing on my mind,
I earnestly besought the Lord to silence everything in me that was of the creature,
that so I might be enabled, with holy certainty,
to come to the knowledge of his will in this matter; which being, as I believed,
in mercy vouchsafed, I informed some Friends of this prospect of duty;
and a Friend undertook to ascertain how an interview could be obtained.
Inquiry being made,
it appeared that he had lately left the castle of Pyrmont for his winter residence.
Although disappointed,
I did not feel condemned for not having made my situation known to Friends earlier:
and on endeavouring to settle down under my disappointment,
in time the way opened for my relief, under an apprehension of duty to take up my pen.
I sat down for the purpose, earnestly beseeching the Almighty to guide me by his counsel,
in penning down what I was commissioned to lay before him.
My faith was closely put to the test; I thought I could truly say, feeling has no fellow,
for I should have been willing to be excused from such a task.
Having committed to writing what rose in my mind, I submitted it to a few Friends;
and it being approved, a fair copy was left for translation.
Fourth-day, the translation being completed, I signed it, and,
with the address to Hamburgh, and that to the magistrates and clergy,
it was addressed to the prince,
"`on private business,`" to prevent its being opened by the prince`'s secretary,
and put under cover addressed to the princess dowager, his mother,
who was remaining at the castle of Pyrmont, intending to follow the prince in a few days.
A Friend took the packet to the castle;
but my way did not appear clear to leave Pyrmont
for several days after it had been delivered,
not knowing, if offence should be taken,
what might be the result as respected the Friends here.

This afternoon my kind friends, Benjamin Seebohm and John Snowden,
left Pyrmont for England; and to me, it felt a stripping time.

Fifth-day, resumed my daily labour.
First-day, felt myself much stripped for want of the help of my friend Benjamin Seebohm.
The reading-meeting was numerously attended and much favoured:
may it continue to be maintained in a proper disposition of mind,
and then I believe a blessing will attend it.

Fourth-day.
This was the last meeting I expected to sit with Friends here.
There was a pretty general attendance.

Sixth-day, I made calls on the different Friends to take my leave of them.

Seventh-day morning, accompanied by my kind friend John Yardley, I left Pyrmont, poor,
blind and naked; but yet with great cause for thankfulness,
that I was leaving it with a peaceful mind;
the retrospect affording me a comfortable hope,
that my coming here was not in my own will.
I now found, if I did my Great Master`'s will,
I must not pursue the direct route to Minden,
but turn aside and spend a few days at Hanover.
The weather being fine, and my mind able to unbend,
afforded me an opportunity to enjoy the works of
the Great Author of all that is worthy of our admiration.
But on our entering the gates of Hanover this evening,
I cannot describe the sudden change of my feelings; suffice it to say,
I felt as a cart loaded with sheaves, weighed down with exercise.
I passed rather a sleepless night;
at intervals my mind was engaged in seeking to the Lord for his counsel and help,
to be able so to demean myself amongst the people as to secure his preservation,
if any service was called for at my hand, during my abode here.
My kind young friend, who had given me so much attention when here before,
again manifested anxiety to render me service, which I gladly accepted.

Third-day morning, being concluded upon by another of the clergy to receive us,
accompanied by our young friend, we proceeded to his house.
We found him very far advanced in life, but green in old age.
On our entering his apartment, his first question was,
"`Which of you was the author of the Address to Hamburgh?`"
On being informed, he gave me both his hands,
expressing in strong terms the comfort which the reading of it had afforded him; adding,
it was cause of sorrow to his mind that a stranger should
have occasion to make such remarks as the address contained,
but which, said he, are too true;
yet he also rejoiced that his Lord had such a faithful pleader of his cause;
and in an impressive manner uttered the solicitude of his
soul that the Divine blessing might attend my labours,
and that the preserving arm of God might accompany me to the end of my journey.

After we had left this dear old man,
we were informed that a few years ago he made considerable efforts
towards remedying some of the prevailing evils in Hanover,
but he met with so much opposition, that he became weary, and gave the matter up.
This I accomplished; but I have reason to believe it would not have been done,
had I attempted it when in Hanover before;
the person who gave me information on the subject,
and was the means of my being furnished with the act, was then absent,
and only returned the evening we arrived there:
another proof of the need of being careful,
that in our religious movements we are not influenced too much by human prudence;
for if it becomes the ruling principle in our actions,
we must expect to be led astray from the path of safety.

Fifth-day morning, we left Hanover, and proceeded to Minden,
a part of the king of Prussia`'s dominions: lodged at Harmel.

Sixth-day, our kind friend, John Seebohm, met us, and we reached Minden in the evening.

Seventh-day was a time of close proving to my mind;
although Lewis Seebohm had kindly offered to attend upon me on first-days as my interpreter;
yet he being obliged to return home on first-day night, a journey of twenty-four miles,
I could not have his help at the week-day meeting, nor at any other time.
During the afternoon an account was received of the death of one of their members,
whose burial was to take place on second-day,
which would be likely to occasion a considerable gathering of people.
This circumstance increased my exercise of mind; but after all my anxiety,
I found it was best for me to leave the future to care for the things of itself.
Late on seventh-day evening, Lewis Seebohm arrived.
I went to his lodgings, and to my agreeable surprise,
without being able to come at the knowledge of the death of the Friend,
he had obtained leave of absence from the managers of the school he superintended,
until third-day, which led me secretly to say, "`Wonderful, indeed,
are the ways of Providence: who shall not fear thee, O Lord, and glorify thy name?`"

Second-day afternoon, accompanied by other Friends,
we proceeded to the house of the deceased, and from thence to the graveyard,
where we were followed by a great company of persons
who had gathered round the house on the occasion.
Considerable time was spent in silence at the grave-side;
the behaviour of the people was becoming, and they left the graveyard again,
as if the awful occasion had made suitable impressions on many of their minds.
This evening, Lewis Seebohm, John Seebohm and John Yardley,
were obliged to leave me to return to their own homes,
by which means I was deprived of the opportunity of conversing with Friends here,
as none of them are acquainted with the English language; but I hope, by this time,
I have learned the necessary lesson of patience under these trials.

Fifth-day, such a succession of discouragements crowded into my mind,
that I concluded there would be no way but to risk the consequences of returning home:
I had not a friend to whom I could open my mind, nor would it have been of much avail,
for I was assured that if favoured to receive help,
it must come from a higher source than poor man.
"`O be pleased to send it, holy Father, in thine own time,
lest I should be tempted to stop short in fulfilling that which thou hast for
me to do!`" was the earnest and fervent breathing of my deeply-tribulated soul.

Seventh-day evening, my kind friend Lewis Seebohm, again arrived,
which afforded me an opportunity of exchange of sentiment.

First-day morning, there was a great coming in of strangers,
who generally sat the meeting through in a solid manner.
I had a laborious time; and notwithstanding the capability of my interpreter,
my trials were such, that I had nearly sat down in the middle of some of my sentences.
Soon after meeting, my kind friend and interpreter left me again,
so that I had to pass my time until seventh-day, very much in silence.
May I be willing to labour after that state of mind,
in which all murmuring is entirely done away,
and then all these deprivations will work together for good.

Third-day, I went to one of the Friends out of the town,
to seek for employment in his garden; but either he could not understand me,
or he was not willing I should be thus employed.
I was obliged to return home disappointed.
I turned out in the afternoon, and tried another of the Friends,
and I made him understand me so far as to give me a hoe,
and portion me a spot of ground to clear from the weeds; for which my mind felt thankful.

Fourth-day morning, rose from my bed in a tried state of mind,
when looking at the meeting-time coming.
The person who took pity on me, when I first arrived at Pyrmont,
resided here as a preacher to the Lutheran congregation,
and had kindly offered me his assistance.
Aware that his time was fully occupied with his school and in divers other ways,
I had not felt easy to intrude myself upon him.
A short time after I took my seat in the meeting, my mind was brought under exercise,
and matter was given me for communication,
but the command to stand up and express it was withheld.
I therefore concluded I must silently bear the burden of the word,
and take it away with me; but near the time the meeting usually closes,
this Lutheran preacher came and took his seat in the meeting.
The way now clearly opening for me to communicate what was before my mind,
I felt at liberty to request the preacher would take his seat by me, and help me out,
as I had something to say to the people, which he did.
He appeared to get forward easily with his task,
and a solemnity was brought over the meeting; thus my difficulties subsided.
On my acknowledging his kindness, when the meeting closed,
he informed me he had no duty to do on the next first-day,
and should I then need his help, he would attend upon me.
This free-will offering, unaccompanied with any semblance of bigotry,
produced a nearness of affection in my mind towards him.
When a suitable opportunity occurred,
I had inquiry made of a Friend who was at the meeting,
and capable of giving a clear opinion,
how far the subject I had spoke upon was correctly given.
The reply of the Friend was, he believed,
as correct a translation was given as well could be:
fresh cause for gratitude on my part, and to take courage,
and trust in the name of the Lord.

Fifth-day, the thorn in the flesh was permitted to goad me sorely.
My soul craves that the designs of Infinite Wisdom,
for which these buffetings of Satan are permitted,
may not be frustrated through my impatience, or any contrivance of my own,
to get from under them.
Seventh-day evening, Lewis Seebohm and John Yardley arrived.

First-day morning, the Lutheran preacher gave us his company at the meeting,
which was numerously attended by strangers, who at the close left it in a solid manner:
after which Friends were requested to remain in the meeting-house,
before whom I spread a concern to sit with Friends of Minden, Edenhauseii and Hilla,
in their families, which being united with,
my friend John Yardley proposed to join me in the visit.
It being the time of the vacation in the school in which Lewis Seebohm was an assistant,
he was at liberty, and kindly offered to accompany us as our interpreter:
way thus again opening for my relief, unsought for and unexpected,
was a fresh call upon me, in my proving seasons,
to endeavour to keep in view the injunction of the apostle, "`Be careful for nothing;
but in everything, by prayer and supplication with thanksgiving,
let your requests be made known unto God; and the peace of God,
which passeth all understanding, keep your hearts and minds through Jesus Christ.`"

Second-day, we bent our course to Buckeburgh, about five English miles from Minden,
and sat with the family of Friends who reside there.
Whilst at Pyrmont, I received an invitation from a female of Buckeburgh,
not professing with Friends, to make her a visit on my way to Minden;
and feeling easy to accept the invitation, I returned an answer accordingly.

On my way to Minden we halted at Buckeburgh,
but my way was so closed up as to making this visit,
that I concluded it would be safest for me to come over specially for the purpose;
but the way now opening for it, we were conducted to her dwelling.
On our arrival, we were welcomed by an elderly man,
who bore the marks of being above the middle rank in life;
he conducted us to the apartment of his sick sister, who had sent me the invitation.
This apartment was nearly in total darkness, as her daughter,
who was her companion in her great bodily suffering,
was labouring under an almost total loss of sight,
and was unable to bear day-light in the room.
We sat down together, but conversation interrupted the quiet that was hovering over us.
I requested that the conversation might cease, which being attended to,
I had much given me for the sick woman, and others in the room.
My interpreter had long been acquainted with the family,
and from the manner I had to address the sick woman,
those present apprehended he had given me information respecting her;
until he assured them, he was ignorant who the individual was we were about to visit,
until we reached the side of the bed, and that,
as I did not understand the German language,
the family I had left could not give me information respecting her.
This explanation appeared fully to satisfy them, and at our parting,
the sick woman and her brother expressed their thankfulness for the visit; the brother,
in a feeling manner, said he desired to profit by what had been communicated to himself.
It appeared that the desire for this visit originated in the circumstance of
one of the addresses to Hamburgh having reached the hands of the brother,
who fills a high office in the chamber of the Prince of Buckeburgh.
I sent him some books, on the receipt of which he returned the following acknowledgment:

Buckeburgh, 14th of October, 1822.

My dear friend Shillitoe,

It is pleasant to me to employ my pen in the familiar style
of the second person singular in writing to thee;
it is the language of nature.
The consoling words with which thou addressedst my sister were affecting to me;
I could not do otherwise than love thee,
believing thee to be an evangelical Christian and a faithful servant of the Lord.
I shall always think of thee with love.
I sincerely thank thee for the books which thou hast sent me,
which contain so much that is true and instructive: I receive them as a valuable present.
If thou wilt apply to me for the cost, it would be no more than what is right.
I should still consider them as a gift of love;
for it does not appear to me to be right for me to receive as a present,
that by which others, who are poorer than I am, might be benefitted.

As I hear thou art likely to travel through France,
a country where there is but little religion and muc infidelity,
but where there must be also many thousands who are desirous of comfort,
and also of a knowledge of the Truth, may the Lord bless and prosper thy labours,
and afford abundant opportunity to establish and enlarge his kingdom,
and preserve thee in this arduous undertaking, both in body and spirit.

My sister greets thee,
and hopes that thou wilt retain her in thy affectionate remembrance.

L+++.+++ H.

On our way home our carriage-wheel came off,
and our axletree broke by the fall of our carriage, which caused considerable difficulty,
the roads being in some places deep in mud;
but we esteemed it a favour that worse did not happen to us,
which might have been the case had the accident occurred where
the ground on either side is several feet below the road.

Third-day, 1st of tenth month, we walked to Edenhausen,
where there is a small settlement of Friends, and a week-day meeting established.
Our first visit was to a family who are farmers.
It appeared they had no place so suitable for sitting with them as the entrance hall,
which runs through the house from front to back.
In the upper part of this hall the family live and cook their provisions:
generally there is no chimney, but the smoke escapes through holes in the wall.
On each side of this entrance are stables, or cribs for the horse, cow, calves, pigs,
goat and poultry, which are open to the hall,
except just so as to keep the animals from coming out and mixing with the family.
From the noise some of their live-stock were making,
the prospect of sitting down with the family, was to me discouraging; so much so,
I felt inclined to give it up; but by endeavouring after patience,
I was preserved from this unadvised step, and we took our seats together.
Soon after, the cow put out her head, and gave a loud bellow,
and the pigs and the geese became very noisy`'. This
interruption continued for some time,
when, to my great surprise, all at once became quiet,
as much so as if there had not been a living creature near besides ourselves;
and continued so until the meeting was over,
and we had a solid opportunity with the family.

In the fourth visit we paid, the wife of the Friend was not in membership;
and upon an offer being made her to sit with us, she refused.
One of my companions regretted her absence;
but the opportunity closing before she had time to retreat,
she was found listening at the door of the apartment, which had been left a little open,
and at our parting she came and kindly gave us her hand.

Fourth-day, we sat with the family, where the meeting is held.
This being the day of their week-day meeting,
there was a numerous attendance of Friends and others: Truth rose into dominion,
and it proved a baptizing time to many.
A man, who on being informed of the meeting,
appeared to receive the information in rather an opposing manner,
came and took his seat near my companion, was much tendered, and when the meeting closed,
took his leave of us affectionately.
A woman also came to our interpreter in a tender disposition of mind,
saying she had been a backslider a great many years;
but hoped she could say a willingness had been brought about in her mind that day,
through the assistance of the Lord`'s power,
to become obedient to his will concerning her.
When the meeting closed, it appeared as if the people hardly knew how to separate.
Having closed our visit, we returned to Minden.

Fifth-day, we proceeded to Hilla, about ten English miles.
We met with two families and one individual in membership with Friends.
After these visits were accomplished we returned to Minden, bringing our sheaves with us.

Sixth-day, we went to Herteford, about ten English miles,
to visit a solitary individual who resides there.
We had good ground for believing this Friend was
very closely bound to the principles of our Society;
but he was unable to provide for his numerous family
anywhere so well as where he is residing;
he appeared to be in what we should call extreme poverty,
but thankful for the portion of this world`'s goods dispensed to him, although so scanty.

First-day, 6th of tenth month, the meeting for worship at Minden was large.
It was a laborious time,
yet fresh cause was mercifully vouchsafed to set up the Ebenezer, and say,
through the Lord`'s help alone, I have been enabled faithfully to acquit myself.

First-day, the meeting this morning was large, in which Truth rose into dominion,
to the humbling of many of our spirits:
the sweet quiet that was to be felt over the meeting,
and the solid deportment of the people when we separated,
afforded cause for thankfulness.

In the afternoon the two months`' meeting was held: Friends of Pyrmont, Minden,
Edenhausen and Hilla, make up this two months`' meeting,
which is held alternately at Minden and Pyrmont.
The business was conducted in much quiet, and if my feelings were correct,
under a good degree of concern, that Gospel order might be promoted.
As I was soon to take my departure, I found I should not be clear of Friends here,
without reviving some expressions of the late John Pemberton,
who laid down his life at Pyrmont, which were these: "`Friends,
Truth is a clean thing;`" I endeavoured as ability was afforded me,
to enforce the belief, that it leads to cleanliness in our persons and our houses,
as well as in our hearts, if we are actuated by its influence;
and it would lead Friends here as well as elsewhere,
to set an example of cleanliness in their persons and houses, to their neighbours,
which is much wanting.
I also recommended to the men, not to require the women to labour so much out of doors,
as now is the case,
whereby they would have more time to attend to their domestic concerns.
What I had to offer was well received;
and I felt thankful that strength was given me to clear my mind respecting these subjects,
which I felt was like touching tender places.

Having felt my mind engaged to make a visit to the general in the army here,
accompanied by John Yardley, Frederick Smidt, and my interpreter,
I proceeded to his residence.
He met us with marks of respect.
I presented him with some books, which he received in a pleasant manner.
It appeared to me right to acknowledge the feelings of gratitude that attended my mind,
since I had come to Minden, towards the King of Prussia for his indulgence,
in granting liberty of conscience to such as were in membership with our religious Society,
as regards military demands;
at the same time I told the general I believed it right for me to cast before his view,
the difficulty which two descriptions of persons, under our name, might be brought into,
for whom no provision was made,
but who might be equally deserving the tenderness of the government;
since the indulgence of the king extended to such
only as are in membership with the Society of Friends.
One description is, those who have forfeited their membership in the Society,
but who manifest signs of sorrow for their outgoings,
and have not lost their conscientious scruples,
but conduct themselves consistently with our principles,
and are diligent in their attendance of our religious meetings;
though the way has not yet opened in the minds of
their friends to restore them into membership.
As the law now is, such must either suffer, or violate their conscience,
which should be viewed as a sacred thing, and ought to be preserved inviolate.
The other case is, those who are convinced of our religious principles,
and are conscientiously concerned to act up to them;
but who had either not applied for admittance into membership,
or the Society had not seen that the time was fully come to admit them:
these also must be placed in a similar situation with the former,
if called upon to comply with military demands.
The general gave me a full opportunity to relieve my mind, assuring me,
should any such cases come under his notice,
he would do all in his power for their relief; saying,
that he regretted we could not converse more freely together,
though the visit had afforded him satisfaction.
At our parting,
I informed him I had no desire to screen such as were not worthy of his lenity;
and any attempt to impose on him might be prevented,
by his requiring a certificate from two respectable members of our Society,
that such who claimed his indulgence,
were in profession with us and of consistent conduct.

Second-day morning, accompanied by Frederick Smidt and my interpreter,
I made a visit to the Stadt-governor, at the Stadt-house.
I had proposed, from the feelings of my own mind,
to visit him at his own house out of the town;
but as it was thought by my friends better to visit him at the Stadt-house, I yielded;
but on entering his apartment I discovered my error in not going to his house,
as we found him so surrounded by persons on public business,
that I despaired of being able to obtain a hearing.
I saw no way but to desire my interpreter to request
the governor would go with us into a private room,
which he complied with.
I laid before him what might be the trying situation
of the above two descriptions of persons,
relative to taking an oath, as I had before done to the general,
which case might come under the governor`'s immediate notice;
requesting he would make such use of my remarks as
would tend most to the peace of his own mind.
I reminded him that conscience was a tender thing,
and that such as acted conscientiously towards their Maker,
must be good subjects to their king.
The governor made judicious remarks on what I said,
assuring us he would not lose sight of my observations,
but do all in his power towards the relief of those whose cases came before him;
he expressed the satisfaction this short interview had afforded,
and the regret he felt that our acquaintance had not commenced sooner.
I presented him with some books, and at our parting,
he said he would take the necessary care about my passport;
but as I proposed leaving Minden early next morning, fearing lest,
through the hurry of business, he should forget, as we had to go by the police-office,
we called ourselves.

On entering the office, the lieutenant of the police ordered us chairs,
saying he was at the Friends`' meeting yesterday, and was well satisfied at being there;
he signed my passport, and would not allow me to pay the usual fees;
and gave me his hand affectionately at our parting.
I now was able to quit Minden with a peaceful mind.
After having made these last-mentioned visits to the general and the governor,
I fell in company with a young man under convincement,
reputed to be of very steady conduct,
but the way had not yet opened in Friends`' minds to receive him:
he was labouring under difficulty for refusing to comply with military demands,
and hearing of this circumstance awakened in my mind
feelings of gratitude to my Divine Master,
who had strengthened me to labour with the general and the governor on this subject.

15th of tenth month, 1822, I leff; Minden, and reached Billifield by night,
where I was kindly cared for by my friend Lewis Seebohm and his wife.
We were informed at Minden,
that by crossing the country to Newn Churchen about twelve o`'clock at noon,
I should meet with a diligence hung on springs.
Fourth-day morning early, we left Billifield for Newn Churchen, about ten English miles;
our road lay through deep sands, and such holes and hollows,
that I expected we should be upset.

Twelve o`'clock came, but we had not reached our journey`'s end;
and on inquiry of the peasantry, our distance from Newn Churchen, we were told,
was four miles.
We did not reach it until one o`'clock,
and found the diligence did not arrive until ten o`'clock at night.
My friends who came with me intended to see me seated in the diligence,
which I could have been glad of,
in order that everything relative to my getting forward might have
been arranged with the superintendent of the carriage;
but as they and the carriage we came in were expected to return by night,
I was obliged to endeavour after resignation, and be left amongst strangers,
uncertain of having a place in the diligence when it arrived.
Not one person in the house where I was left, could understand me, nor I them.
My friend, before he left me, did all in his power to interest the family to care for me.
The carriage did not arrive until twelve o`'clock at night,
and it proved a heavy wagon fixed upon the axletrees
instead of a diligence hung on springs;
but this disappointment was soon got over by my finding there was room for me to proceed.
After halting about two hours, we started; about mid-day we arrived at Paderborn,
where we changed our conveyance for one that afforded relief to my fatigued body.

As I was standing at the door of the hotel,
very pensive and unable to make the people at the diligence-office
understand about paying my fare and packing my luggage,
a young man of genteel appearance came to me, and offered his services.
He kindly undertook to care for me in everything of which I stood in need,
and waited to see me seated in the carriage and started:
by his interceding with the post-master,
the superintendent gave me every attention I required.
When we arrived at Cassel, having a letter to the postmaster, I was taken to a clean,
comfortable hotel, which was a great privilege; yet, none of the family speaking English,
was some take-off; but I procured what satisfied me,
the keepers of the house manifesting a desire to do all in their power for my comfort.

Next morning, whilst at my breakfast, a respectable looking man came into the room,
and the keeper of the hotel made me understand he could speak English;
I therefore addressed myself to him.
At first he carried himself very shy and distant;
but by persevering to secure his attention, he became more disposed to notice me,
querying with me, as I was a stranger to every language but my native tongue,
what had caused me to undertake such a journey.
My certificates being the best explanation to his question, I gave him them,
which he appeared to read with interest, pausing as he went along.
After reading them he became more sociable,
and desirous to afford me every assistance in his power;
he also gave me the address of a person who he said was one of our Society.

In the evening I went to the residence of this person, saying I was an Englishman,
he opened his door and gave me a hearty welcome to his house; his first question was,
what had brought me to the continent.

As usual, I gave him my certificates, on which he made his remarks as he passed along.
On my inquiring relative to his situation,
it appeared he stood in the station of a bishop,
or inspector of the different congregations of the
French reform in this place and its neighbourhood,
who are very numerous.

We spent our time together, I hope to mutual edification.
Next morning he made me a call, and we had much interesting conversation;
and as I intended to leave Cassel that afternoon, and had my luggage to see to,
he settled all these matters for me,
giving the managers of the diligence charge that the superintendent
should give me every attention I needed.
Matters being arranged for my departure,
I accompanied the bishop to the hospital for the aged poor.
In four of the wards I had something to communicate, which he interpreted,
expressing the satisfaction my labours in this way afforded him,
and we took an affectionate leave of each other; but before we parted,
he kindly inquired of me if I needed any pecuniary aid,
as he was willing to furnish me with it;
but I assured him my good Master had abundantly cared for me in this respect.

In consequence of a letter which I brought from Pyrmont to the post-master at Cassel,
I was given to understand he had arranged for my being taken
to a comfortable hotel on our arrival at Frankfort.
I took my seat in the carriage, expecting, as heretofore,
to be obliged to endure in silence such difficulties as I met with by the way.
A female who sat opposite me addressed me in German:
I shook my head as a token of my not understanding her.
A young man, a military officer, who sat in another corner of the carriage,
expressed in good English his surprise that, at my time of life,
and wholly unacquainted with the language of the country where I was travelling,
I should undertake such a journey;
after which he manifested a desire to lay himself out for my accommodation,
in procuring such things as were most suitable for me to take,
and seeing I was not imposed upon at the places of entertainment,
also that I did not take money that would not pass where I was going, without loss.
When we reached Frankfort, he took me with him to his hotel,
accompanied me to the bankers, saw my money was correct,
then went with me to the coach-office; he also pressed me to accompany him to his home,
but as I could not comply with his request, he then engaged my place forward to Basle,
and arranged with the hotelkeeper to give me every attention;
after which he left me for his estate on the Lower Rhine;
but before we parted he gave me an engraving, with a view of his estate,
requesting I would accept of it as a mark of his esteem, accompanied with his address,
and his desire,
if any Friends should come to the Lower Rhine that they might be addressed to him,
and he should feel a pleasure in rendering them any service in his power.

23rd of tenth month, 1822.
Left Frankfort, and after two days and two nights`' travel I was favoured to reach Basle.
I was recommended to a hotel, where I was told the waiter spoke English;
but he was a lad who had obtained a little smattering of it,
and so dull in comprehending my meaning,
that I was frequently disappointed in my expectations of what I wanted.
The frequent occurrence of these circumstances teaches patience,
an ingredient of which I have very little in my natural composition; but grace, I find,
is able to do all that is needful towards our witnessing
patience to have its perfect work in us,
that so all things may work together for our good.
I procured a messenger to conduct me to the house of my kind friend Theophilus Bloomhardt,
who received me with marks of sincere regard, speaking the English language well.
His services were very useful to me with regard to my luggage,
which was to come by a wagon that was to keep company with our carriage;
but I found it would not arrive until noon on first-day.
This circumstance felt trying, and the weather continuing fine,
and the moon still affording good light,
I felt disposed to move forward by the next conveyance to Geneva;
but had I thus hastily proceeded,
I have good cause for believing it would have occasioned my return again to Basle.

First-day evening,
my kind friend Theophilus Bloomhardt invited me to
accompany him to a meeting of a few select friends,
with liberty to use my own freedom with respect to my hat,
or in any manner conforming to such religious ceremonies as they were in the practice of,
which I accepted.
The meeting was held in a large room attached to a meetinghouse;
here I met with upwards of two hundred persons assembled.
Such was the covering of good I was favoured to feel on entering the room,
that my soul saluted them as brethren and children of the same great Almighty Power,
by whom I was professing to be actuated in this wilderness travel.
Endeavouring to retire to the gift of Divine grace in my own heart,
and feeling something given me to express amongst them,
when their meeting closed I gave notice of it to my friend,
who kindly offered to interpret for me.
Although I could not understand what passed in their meeting,
yet I thought a sense was given me,
that towards the close of it a disposition for hastily getting
through what they professed to meet for was yielded to,
whereby the service which these meetings might be of, was in degree laid waste.
My remonstrating with them hereon appeared to find place in their minds,
and it produced an acknowledgment of desire to be willing to act more up to it in future.
I returned to my hotel, not only with a peaceful mind,
but thankful at the disappointment I had met with about my luggage;
earnestly craving to be resigned to such further service as may be required of me here,
and not to proceed to Geneva until the way opens for it with clearness.
My friend, Theophilus Bloomhardt, is head of a college here; and duty prompting me,
I requested liberty to have a meeting with the students, which was consented to.

Second-day evening, I had a meeting with the students and a few others:
we sat a considerable time together in awful solemn silence,
after which strength was given me to rise on my feet,
and I hope I may say faithfully to deliver what was given me to communicate to them,
and from the affectionate manner they pressed towards
me when I was about to leave the room,
I thought I had ground for believing what I offered was well received.
I returned home, feeling fresh cause to set up my Ebenezer, and say,
it is the Lord`'s doing, and truly marvellous in my eyes.

Third-day, the way now opening for my moving towards Geneva,
I secured a place in the next conveyance to Berne.
The burgomaster of the canton having expressed a desire that I would make him a call,
accompanied by my kind friend, I waited upon him this afternoon.
He is far advanced in life, and green in old age,
manifesting an anxious concern to be found filling his situation,
as head-senator of the canton, in a way that would redound to the honour of his Creator,
and the good of his fellow creatures.
I thought I could feelingly subscribe to the truth of this,
as Basle exhibits a striking proof of how much a well-regulated police can do,
towards preserving good order in a large city.
At our parting, the burgo-master expressed the satisfaction the interview had given him,
to which I could fully subscribe as it respected myself I intended to return to my hotel,
but my friend told me, he had another call he wished me to make; after a pause, he said,
he was desirous of introducing me to a general conference
of their preachers in this part of the country.
The proposal at first startled me, but a fear that if I refused to accept the offer,
I should have cause to be sorry, predominated over my discouragements.
I found about thirty of their preachers assembled:
feeling my mind brought under exercise for service, I informed my friend thereof,
who kindly offered to interpret for me: the company gave me a quiet,
full opportunity to relieve my mind; on my quitting the meeting,
some expressed a desire the Divine blessing might attend me, others,
in an affectionate manner, gave me their hands; after which,
and taking an affectionate farewell of my kind friend,
I arranged for my departure to Berne at four o`'clock.

On fourth-day morning, we left Basle for Berne,
from whence a coach would start two hours after my arrival for Geneva.
I had procured a letter to the post-master at Berne,
to secure me a place forward by that conveyance;
but I had not proceeded far on my way to Berne before my mind was
impressed with a sense of the necessity for me to consider well,
before I presented the letter.
Under these impressions, earnest were my desires that the Lord my God would be pleased,
if it was not his will that I should proceed by the next conveyance,
to raise in my soul such a partition-wall between me and Geneva,
that I should not be able to proceed on my journey,
until he was pleased to remove it out of my way.
We lodged one night on the road, which did not add to my comfort.
I was put into a cold, comfortless bed-room.
The waiter was either dull of comprehension,
or did not like to let me have my milk and bread supper,
and I had to wait for it a full hour: having obtained it,
I endeavoured to cast all my care on Him who had in mercy thus far brought me through,
and retired to bed.
Such had been my anxiety to secure my place at Berne, by the next conveyance to Geneva,
that a young man of the college had written to his
brother at Berne to meet me at the coach,
and go with me to the coach-office,
lest the letter I had to the post-master should not be attended to.

When the coach arrived at Berne,
I felt satisfied I must not present my letter to the postmaster.
I looked about for my stranger friend, who, if he had been there,
I concluded from the description given of me, would have taken me in charge;
but as no one came, and I had his address, observing a man who I supposed wanted a job,
I engaged him to take me to where my letter was addressed,
where my stranger friend was at his door ready to go to the coach.
I had concluded to take up my abode at a hotel, but this would not do;
he kindly welcomed me to his house, and to take up my abode with him:
apprehending a refusal would be a grief to him, I yielded,
and found myself quite at home: his speaking English well, added much to my comfort.
He informed me he had exerted himself the preceding day,
and so arranged his outward concerns as to leave him at liberty to attend upon me,
should I incline to make a longer halt at Berne than I had at first proposed;
he manifested the satisfaction, as he said, which it afforded him,
to have a member of our religious Society under his roof.
The information which he had received respecting our religious Society,
originated in a paragraph he met with a few years ago in the British Magazine,
of the year 1774, page twenty-two, which he said,
made such an impression on his mind that he had it
translated and circulated amongst his friends,
which he read me in English.
The account is short, but the author of it appears to have done the Society justice,
in what he has given forth respecting it;
it did not appear that his knowledge of Friends extended
much beyond the information he then received.
His mind seemed to be all alive for further information respecting our principles,
and the reasons for differing from all other professing Christians in many respects.
I did my best to satisfy him, but regretted the want of suitable books to leave with him,
from the thirst he manifested for further acquaintance with our principles and practices.
In the course of the day, we made an interesting visit to a serious family,
and to the family of the police-master, by whom we were kindly received.
Here I met with a pious young woman,
who spoke so much English that we were able clearly to comprehend
each other`'s views on some religious subjects.
At our leaving, her mother, who appeared anxious for her children`'s welfare,
desired her concern might be expressed for my preservation.
The way appearing to open for proceeding to Geneva, my place in the diligence was secured.

Fifth-day, as I was not to set out until twelve o`'clock at noon,
and I had occupied so much of the time of my kind friend,
I requested he would feel himself at liberty until
near the time I was to start by the diligence.
During his absence, I received a visit from one of his brothers;
when he found we could not converse together,
the disappointment he manifested cannot be easily described,
but by putting his hand to his heart, and again applying his hand to my heart,
and by other signs, he tried to make me understand we could converse there.
He then went to his brother`'s library,
and brought me a large volume of copper-plates applicable to the chapters in Matthew,
Mark, Luke and John, these he turned over one after another in a very animated manner;
by signs and striking expressions in his countenance,
he strove to get me to understand the views of his mind
on the different subjects they had an allusion to.
When he came to that part where our holy Redeemer cast out
the devils and caused them to enter the herd of swine,
his raptures surpassed what can be conceived,
as did his labour to make me understand that Christ would still enter our hearts,
and work such miracles for us, if we look up to him,
and were willing to receive him into our hearts.
He next fetched a map of England,
making me understand he wanted to know my place of residence:
the map being on a small scale, Baldock was the nearest place in it to Hitchin;
I pointed to Baldock, but not feeling quite satisfied myself,
I showed him my certificates, and made him understand how near Baldock was to Hitchin.
My German copy of my certificates being in my pocket, I gave them to him to read;
after he had finished reading them, he sat awhile quiet,
and then kneeled down by the sofa on which I was sitting,
and supplicated in a short but very fervent manner.

Although I was not able to understand a word he uttered, except Jesus Christ,
yet great power attended what he offered; and a sense being given me,
that I had been the object of his fervent petition, I was with him bathed in tears.
Shortly after he showed me by signs we must now part,
clasping me in his arms as if he could not submit to a separation;
this unexpected circumstance made such an impression on my mind,
that I felt it for awhile like a brook by the way,
cheering my drooping spirits when exercised with
the prospect of a long journey before me,
and the difficulties I might have to encounter on my entering the territories of France.

When my kind friend returned from visiting his patients, previously to my departure,
he supplied me with fruit and other matters in abundance for my journey,
and proceeded with me to the coach-office,
where our parting was mutually felt to be a severe struggle to the affectionate part;
he saying, there were many persons in Berne I should feel a pleasure in visiting.
These remarks led me afresh to consider how far I was acting
in accordance with the Divine will in now leaving it;
but as I believed the time for my stay here was fully accomplished,
I saw the danger there would be in my suffering the affectionate
part to detain me beyond the right time.

One of our company in the diligence spoke the English language,
which afforded me a more cheering prospect than I had anticipated.
I understood he was going to Lyons, and he manifested a disposition to be accommodating:
but my expectation of having his company to Lyons was soon clouded,
by his informing me he was out on a journey of pleasure, and intended to spend,
at the least, one day at Lausanne, and two days at Geneva.
I would gladly have secured my passage forward by the next conveyance to Lyons,
but fearing I should make the same error at Geneva, which I had nearly done at Berne,
I concluded to proceed to a hotel, and deliberate before I took such a step.
After mature deliberation,
the way not being clear for me to proceed by the next conveyance,
I procured a messenger to conduct me to the places of address of my letters.

My first call was upon a pastor who had separated
himself from the established religion of the country,
and who spoke my native tongue.
Accompanied by a kind young man, a countryman, I walked about two miles out of Geneva,
and called upon a person to whom I had a letter of address,
and found him to be one with whom I could take sweet counsel:
as matter arose in my mind I endeavoured to be faithful,
although what I had to express was much in the line of conversation, yet,
under a humbling hope I was influenced by Divine requirings therein,
it became like water poured upon the thirsty grttund,
having an increasingly solemnizing effect on his pious mind.
He walked with us to the city;
I continued to be vocally exercised as we walked along together,
and at our parting he expressed in an agreeable manner the
obligation he felt himself under to his friend in England,
who had been instrumental in bringing us acquainted.

Second-day, as I was recommended to my hotel by my fellow traveller,
whom I left at Lausanne, I concluded he would come there, and made inquiry,
but he had not arrived; and way not opening in my own mind to proceed,
I rode out of the city, and spent part of the day with a pious young man,
to our mutual comfort and edification.
On the way to my hotel I made a short visit to a pious countrywoman,
long a resident on this part of the continent,
who has had persecution to endure for her faithfulness to the law of her God.
I felt much comfort in being in her company.

Third-day, whilst lying in bed this morning,
the way for my departure so clearly opened in my mind,
that I concluded to go to the coach-office,
and secure my place to Lyons for tomorrow morning,
and cast my care on that good Power who never yet had failed
under all my extremities to bring me safely through;
but before I had finished breakfast,
a waiter came to inform me the person I had been inquiring after,
had arrived at a late hour the preceding night.
On my entering his apartment, the pleasure he manifested at our meeting again,
I thought could not equal my feelings of gratitude to my Divine Master, when he told me,
he would accompany me to Lyons tomorrow morning if I was desirous of it:
on which we proceeded to the coach-office, and secured the only two places not taken.
My mind being thus set at rest about my proceeding,
I spent part of the day with an interesting family,
where I had the company of several religious young men.

The evening I passed with a pious family, and two interesting young men,
who were pastors; one of whom put the following question to me,
"`Is it not possible that a sermon prepared before hand,
if the person who prepared it and was to preach it,
was sincere in his desires of doing good,
praying earnestly to Almighty God to assist him when writing it,
would be profitable to his hearers?`"
I replied, I durst not pronounce the impossibility of it;
but it was a subject I had at times thought much upon,
and it uniformly had closed thus with me,--that what was offered in the way thus described,
at best, could only be compared to hashed meat, or meat that has been warmed over again,
which neither has the same savoury taste,
nor does it appear to possess the same nourishing quality as it would,
had it been set before those who were to partake of it, when first prepared:
after pausing a while he feelingly expressed his full assent to the truth of my reply,
and I left our company under a comfortable belief that this
evening`'s engagement will long be remembered by them.

Before I left Geneva I was constrained to call upon
the pastor to whom I made my first visit,
and lay before him two ways,
whereby Satan assaults the ministers of the Gospel of Christ; one is,
by endeavouring through discouragement to cause them to lag behind their good Guide,
in order that he may defeat the designs of Infinite Wisdom respecting them,
by laying waste the service they were designed to be of to others.
But when he finds, after all his efforts in this way,
such have resolved through holy aid to press towards the mark for the prize,
he will then exert his utmost endeavours, in the other way,
to cause them to run before their good Guide,
hurrying them into things never required at their hands,
or before the time was fully come for them to engage in the services designed for them.
Having thus acquitted myself, we separated affectionately.
