== Chapter XXIII.

In the fifth month, 1823, I left my own home, and proceeded to London,
to attend the Yearly Meeting.
During my attendance of the Yearly Meeting,
I found Friends were desirous to have details of my journey on the continent from myself;
but I was aware that detailing out occurrences, and some rather new in themselves,
accompanied by displays of Divine interposition,
might produce observations tending to set up the creature,
rather than promote that disposition of mind which is the only safe one for me,
viz. a sitting as with my mouth in the dust,
if so be there may be hope that my dedication has
found acceptance in the sight of my heavenly Father.
I therefore believed it safest,
after a summary of my proceedings had been read in the Yearly Meeting,
to request that Friends would excuse me from entering into further details of my journey.
I felt thankful in being permitted once more to sit
down with Friends in a Yearly Meeting capacity,
and in witnessing the continuance of ancient goodness,
whereby the concerns that came before us were conducted in much harmony.

Previous to leaving London,
it appeared to me right to put into the hands of my friend Josiah Forster,
for translation, the German copy of the act of the king`'s council,
without any clear prospect that I should be called upon to make use of it.
The desire to know why or wherefore I was giving my friend this trouble,
appeared to me to be beside my proper business.
In the eighth month, I received the translation,
which introduced me into exercise of mind,
but without any prospect as to the use I was to make of it.

The time drawing nigh when I must lay before my friends
apprehensions of further service on the continent of Europe,
my situation would, at times, have been almost insupportable,
had I not been strengthened, like David, to feel myself brought into that state,
in which, with him, I could say, "`I cried with my whole heart, hear me, O Lord;
I will keep thy statutes;`" yet such were my fears,
lest through any misstep I should be involved in perplexity,
that sadness of heart was frequently my companion.
Yet my help must come from God alone,
if I am favoured to come forth from my present tribulation
acceptably in his most holy sight.

It now seemed to me that the time was come,
when I should have to make use of the translation
of the act of the king and council of Hanover.
I sat down and deliberately perused it,
beseeching the Almighty to direct me in the disposal of it;
and believing it was required of me to address the king
(George IV.) on some of the subjects which the act contained,
I took up my pen, earnestly craving to be furnished with matter suited to the purpose.
After spending a suitable portion of time in inward retirement,
waiting on the Lord for his holy help, I proceeded to write,
and having completed my address, I went on third-day, 20th of fourth month, 1824,
accompanied by my kind friend, Peter Bedford, to Windsor.

On being informed that the king was going from the castle to the lodge,
we proceeded to the long-walk in the great park;
and earnest was my solicitude to be enabled to discharge this act of apprehended duty,
in a way that would, on a retrospect, afford relief to my own mind.
We at length perceived the king coming in his poney-chaise down the long-walk;
when he came nearly abreast of us, we advanced a little towards the middle of the road;
I had the packet in my hand,
containing the German copy of the act of the king and council, the same translated,
and my address on some subjects which it contained.
The king stopped his horses, and we approached the carriage.
On my asking the king, in a respectful manner,
if I might be permitted to present him with a packet, he replied, "`Yes, friend,
you may,`" Several years having elapsed since I had had an interview with him at Brighton,
and the king having lost much of that florid countenance he then had,
also appearing aged, and being wrapped up in a loose drab great-coat,
instead of an uniform, which he wore on the former occasion,
some hesitation arose in my mind lest I should be mistaken,
and it should not be the king.
I, therefore, looking up at him, inquired, "`But is it the king?`"
to which he replied, "`Yes, friend; I am the king:
give it to the Marquis of Conyngham;`" who received it with a smile;
on which the king said, "`Now you have handed it to me.`"
After a short communication which I had to make to the king, he said, "`I thank you.`"
We then acknowledged his condescension, withdrew from the carriage,
and returned to London with grateful hearts.

I was favoured to reach my own home again, and enjoy it for a time.

After obtaining certificates from my own Monthly and Quarterly Meeting to visit Pyrmont,
Minden, Berlin, and parts of Russia, where Truth should open the way; I left my own home,
on the first-day, 16th of fifth month, 1824,
and attended meeting at Hertford in the afternoon,--proceeded to Tottenham,
and attended the evening meeting there; after which I walked to London.

17th. Attended the select Yearly Meeting, which adjourned to the afternoon:
at the adjournment I opened my concern to visit some parts of the continent of Europe,
and my prospect of duty to spend most of the winter in Petersburgh.
Certificates were ordered accordingly.

First-day morning, attended a funeral at Esher in Surry, of a Friend,
whose removal from time into eternity was sudden and unexpected to her friends.
The opportunity at the grave-side continued long;
and there was good ground for believing it proved a profitable season,
not only to the relations of the deceased, but to many others.
I attended the several sittings of the Yearly Meeting,
in which silence appeared to be my proper province;
being favoured thus to see my right place in these meetings, and enabled to keep it,
I esteemed a great mercy from my heavenly Father.
The activity of the creature is so soon stirred up, in some minds more than others,
especially when the meeting becomes agitated with matters that are brought before it,
that dispositions like my own,
require to be exercised in more than a common share of watchfulness,
in order to be preserved from meddling in matters which we are not called upon to do.

27th of fifth month.
The Yearly Meeting closed its sittings: my certificate being signed and delivered to me,
increased my bonds,
accompanied by fresh incitement to be preserved cleaving in spirit to the Lord,
in order to be favoured to experience his all-supporting power,
to bear me up and sustain me through every trial,
that may await the faithful discharge of duty.
Unaccompanied, for aught I had any ground as yet to suppose,
by a sympathizing brother--on my way from meeting to my quarters,
pondering over my solitary situation in this respect,
my kind friend Thomas Christy overtook me, and proceeding with me to my lodgings,
offered to be my companion to Minden.
This offer coming so unexpectedly, we not having conversed on the subject,
was fresh cause of thankfulness to my mind.
I met the committee on continental concerns,
appointed by the Meeting for Sufferings to arrange matters for my departure;
to whom I opened my prospect of the time when the necessary passports should be in readiness.

But there was a subject which had long pressed on my mind,
the weight of which I found I must in some way be relieved from,
before I left my native shore; assured if I did my part towards its accomplishment,
by casting myself upon my friends,
and they were not willing I should proceed in the service,
the will would be accepted for the deed, and the burden removed from my shoulders:
otherwise it appeared to me it would be a heavy load
to carry with me out of my native land,
and at times prove the means of impeding my progress
in my religious engagements on the continent.
I therefore opened to the committee my prospects of duty before I embarked for the continent,
of visiting the principal acting magistrates of the different police-offices in London,
also a member of the privy-council, and the secretary for the home department.

After suitable deliberation, I was left at liberty to proceed.
My kind friend John Eliot, wrote to a member of the privy-council,
who was considered the most suitable to obtain an interview with.
It being several days before a reply was received, in consequence of his indisposition,
the suspense was a fresh exercise of faith and patience:
not feeling myself at liberty to take much active
part in preparing for my departure for the continent,
until the prospect before me was accomplished,
yet I was also desirous to lose no time in prosecuting my journey,
so as to escape the equinoctial gales in the Baltic Sea and Gulf of Finland,
which are said frequently to prove fatal,
and to reach Russia sufficiently early to become
gradually seasoned to the approaching winter.

5th of sixth month.
Accompanied by Peter Bedford, we proceeded to Union Hall, in the borough of Southwark,
where the crowd of persons waiting on the magistrates was so great,
that there appeared no hope of our obtaining a suitable opportunity;
we therefore claimed the advice and assistance of a Friend near,
who wrote a note to the magistrate on the bench, requesting a private interview,
which it appeared could not be granted.
An offer was made, that if I was willing to come to the hall I should be heard.
This, for a while placed me in a trying situation;
fearing if I did not accept the present opportunity for
relieving my mind the way for it would not open again.

Deliberating on the matter in the best way I was capable of,
and finding it was likely that many persons would
be within hearing of what I had to offer,
and catch a part, and very imperfectly catch other parts of what was said,
and thus circulate very erroneous reports of it;
it appeared to require greater clearness than I was able to attain to,
that this was the right way for me to proceed;
I therefore found it safest for me to relinquish it.
On further inquiry, it appeared, that the most active magistrate,
and the one most likely to enter into the consideration of my views,
was not on the bench that day.
Understanding that he resided in the neighbourhood of Peckham,
and the way opening in my mind to attend Peckham meeting next day,
I engaged my young friend, Joseph Sterry, to accompany me.

First-day, 6th of sixth month.
I attended Peckham meeting; after which we made a visit to the magistrate of Union Hall,
who received us kindly.
When he came to understand the motive of our making this visit,
he manifested a willingness to enter into the consideration
of the subjects I laid before him.
I felt my mind constrained to mention to him a circumstance
to which I had been a witness that morning,
and which I was well informed was a common practice on first-day mornings, viz:
for persons to assemble in a footpath field near town, to fight pitched battles;
whereby hundreds of people were collected, and great uproar takes place.
It appeared that the magistrate was a stranger to this circumstance;
he handsomely expressed his obligation for the information,
assuring us that the necessary steps to prevent the practice in future should be taken,
and also the other matters attended to, as far as was in his power.

Second-day, we waited on the principal active magistrate belonging to the police-office,
Queen Square, Westminster, who received us very respectfully;
he gave us a full opportunity to say what came before us,
manifesting a disposition to enter agreeably into the consideration of the various subjects,
and expressed a desire to do his part towards a remedy.

Third-day, accompanied by my friend John Eliot,
we waited upon the chief-magistrate at the police-office, Hatton Garden,
who received us with kindness, manifesting a willingness to do his part,
as far as he was entrusted with power, to remedy the evil practices mentioned to him.
The sad consequences attendant on the tea-gardens,
were generally adverted to by those magistrates whom we visited,
being the cause of producing immorality in many of the youth,
and defeating the exertions of the police in endeavouring to clear the streets of prostitutes,
and thus to remove these temptations to evil out of their way,
the tea-gardens being the place of resort for these abandoned females;
and also the evils produced by the gin-shops being opened,
as was the case in the neighbourhood of the poor,
at four or five o`'clock in the morning,
which laid the foundation for the drunkenness so apparent in these neighbourhoods.
We could not doubt a sincere desire prevailed in the minds of most we visited,
to help these things which are so much out of order: but it was evident,
if good in these respects is effected, it must originate with the higher powers;
the fines now allowed by law to be levied for misdemeanours, being so limited,
that they are by no means adequate to remedy the existing evils.

Fourth-day, we waited upon the lord mayor at the Mansion house,
who received us in a courteous manner.
My endeavouring faithfully to lay before him various subjects as they presented,
afforded me a peaceful reflection.

Sixth-day, we proceeded to Lambeth Palace,
and obtained an interview with the Archbishop of Canterbury;
to whom I opened my concern on various subjects,
as I had done to the different magistrates: informing him,
that a disposition generally prevailed with them, towards remedying these evils,
were their hands made sufficiently strong for the work.
I pointed out the need there was for their hands to be strengthened
by the higher powers to induce this necessary reformation;
laying before him the necessity of his exerting his influence
with the rulers of the nation toward such laws being framed,
that would prove an effectual means of checking the existing evil practices.
We parted, I trust, under feelings of good-will; and I was reverently thankful,
that strength had been given me faithfully to acquit myself.

Seventh-day, we waited on the bishop of London,
who also received us in a respectful manner;
with whom I enlarged much on the subjects I had laid before the magistrates;
to which he appeared to give agreeable attention,
uttering as I proceeded frequent expressions of assent.
I endeavoured in a becoming manner to lay before him, how much it might be in his power,
from the situation in which he stood,
to promote the application of proper remedies for the evils existing in the nation;
exhorting him to do his very utmost towards its being brought about.
The interview afforded me relief; and I left the bishop under feelings of regard,
for the candid opportunity he had afforded us.

First-day morning, attended Winchmore-hill meeting;
where I trust I was favoured to acquit myself faithfully:
attended Tottenham meeting in the afternoon, in which I kept silence;
but I left the meetinghouse under a fear I had not been right in so doing;
yet Divine mercy and tender compassion, when our disobedience is not wilful,
fails not again in due time to manifest itself;
whereby my unfaithfulness was not suffered to remain as a sin unto death against me.

Second-day, attended the morning meeting of ministers and elders,--to me a low,
exercising time; although from testimonies borne by others,
it proved a time in which the wing of Divine regard was stretched over the meeting.
My intended companion continuing anxious to be moving towards the continent,
I felt not a little on his and his family`'s account; with respect to myself,
although a release from further service on this side
the water would have been acceptable to my own mind,
yet, through adorable mercy,
I was favoured to know a centering in quiet resignation to the Divine will; not doubting,
but that in due time, way would be made for such release.

Fourth-day, no answer being received to the note to the privy counsellor,
a second note was forwarded; his indisposition continuing,
placed me in a trying situation, as it respected my companion;
although I believed I clearly saw, if I kept in the patience,
way would be made for an interview.
Fifth-day, a reply to the note to the privy counsellor was received,
appointing seventh-day for the interview with him;
and a note from the secretary of state for the home department,
appointing the afternoon of seventh-day for our interview with him.
What a fresh call was this to unite with the Psalmist, in the pathetic language,
"`Good is the Lord, and worthy to be praised,`" and patiently waited upon.

Seventh-day, we waited on the privy counsellor, who received us respectfully,
allowing a full opportunity for laying before him
the various subjects that arose in our minds;
we acquainted him with the agreeable manner in which we
had been received by the different police-magistrates,
and the willingness they had manifested to unite in endeavouring to further such measures,
as the higher authorities should see it right to adopt,
for remedying the evils I had laid before them:
and that to effect this desirable reformation,
the hands of the magistrates required in some way to be strengthened;
well assured as I was,
if there was a waiting on the part of those who were to strengthen their hands,
for Divine wisdom to direct them in applying a remedy,
and a willingness to move under its influence,
strength would be afforded to rise above the reproach of the libertine part of the people.

My way, after this opportunity, opened towards the continent;
and we proceeded to the foreign-office, to procure passports.
Agreeably to appointment, we waited on the secretary of state for the home department,
who gave us a full opportunity to relieve our minds.
I had prepared a card with the names of the different
police-magistrates we had called upon,
which we presented to the privy counsellor and secretary of state:
we also presented to the bishops, the members of the privy council,
the secretary of state, and each of the magistrates, a work on the principles of Friends,
which appeared to be well received.
I came away desirous of being preserved from anxiety,
as to the result of my many secret baptisms,
both before and during the prosecution of this short but humiliating engagement.

First-day morning, 20th of sixth month, attended Hoddesdon meeting;
and the afternoon meeting at Hertford.
Second-day, proceeded with my dear wife to Hitchin; and then by mail to Sheffield.
Fourth-day, got to Barnsley, where some outward affairs claimed my attention,
which brought me under fresh exercise of mind,
lest I should become improperly involved in them.
Earnest were my cries, whilst on my way there,
for preservation from the wiles of the evil power; to escape which,
I was strengthened to make some temporal sacrifices.

First-day morning, attended meeting at Sheffield;
then taking leave of my dear daughter and grandchildren,
accompanied by my son-in-law John Heppenstall, I proceeded to Doncaster;
and attended their evening meeting.
Second-day, whilst at my breakfast,
I was seized with a violent spasmodic affection in my throat,
which appeared to alarm my friends: this so enfeebled my bodily strength,
that I feared being able to proceed on my journey;
but feeling the necessity now laid upon me to press forward,
I was made willing to commit my enfeebled body to the care of Him,
who is abundantly able to renew strength,
and give ability to accomplish all he requires of us.
We proceeded to Thorn: on our arrival at the steam-boat office,
and inquiring for my luggage, which had been sent forward by the coach,
I was assured it was in the steam-boat.
On landing at Hull, and inquiring for my luggage, it was not to be found in the boat;
nor could any account of it be obtained.
This involved me in considerable embarrassment,
fearing it should prove the means of losing our passage
in the next vessel sailing for Hamburgh.
After considerable exertion on the part of my friends,
it was traced to an out-building at an inn on the road,
where it had been left by the coachman.
