== Chapter XXIV.

Fifth-day evening, my kind companion Thomas Christy and myself, went on board the Laurel,
Captain Morgan;
and after a passage of three days were favoured to land safely at Hamburgh.
On second-day morning, soon after our landing, I proceeded to Altona,
where I called upon an old acquaintance.
On hearing my view of wintering in Petersburgh,
he proposed introducing to me a friend of his, who termed himself a primitive Catholic,
and who had been residing in Petersburgh a considerable time.
The prospect of such an interview at first appeared desirable;
but I soon felt that I had not sufficiently weighed the proposal;
for whilst the messenger was gone to invite their friend to give me his company,
it came out, that this person had been banished from Russia,
in consequence of his religious principles clashing
with the established religion of the country,
and his having brought over to himself numerous followers,
as well as published some works obnoxious to the established clergy.
This account alarmed me not a little,
not knowing how I might be drawn out into conversation by him,
and what might result to myself,
should he keep up a correspondence with those there who were his followers.
I felt so fully convinced of the necessity of my
remaining ignorant altogether of his situation,
both here and there,
that I begged of my friends not to encourage their friend
to give me the least information on either of these heads.
From a fear I should be in danger of being involved in difficulty,
by continuing in his company, if I did not take great care;
in as handsome a manner as I was capable of,
I refused his kind offer of introduction to his friends at Petersburgh,
and soon left him, thankful that I continued as ignorant at our separation,
relative to occurrences in his case, either there or here, as when we first met.

Leaving the residence of my kind friend, it appeared to me,
that if I acted consistently with my duty,
I must call upon the policemaster who arrested me when here before,
and committed me to prison, and to give him my hand of love,
for I felt nothing but love towards him as a man.
This I accordingly did, and he received it with marks of kindness.
I also called upon the governor, who welcomed me again to Altona.

Third-day, accompanied by my kind friend Thomas Christy,
we proceeded to the senate-house to call upon the chief magistrate;
we were received with great respect by the different officers of the state,
and were introduced to him, although he had many persons with him,
and others waiting in an anti-room, also crowds of people at the entrance,
waiting to be admitted to him.
At the sight of us,
his countenance manifested the pleasure which our meeting once more afforded him,
and I could say it was mutual:
he suspended his business to give us some account of the state of things amongst them,
since my first visit to Hamburgh; saying,
with apparent satisfaction marked by his expressions,
that improvement in morality was making progress in the city;
that twelve young women were about leaving the penitentiary,
some to return to their own homes, and others to service;
and in order that such as had no parents might be sheltered
from the danger of falling into the like temptations again,
a house and work were provided for them on leaving the penitentiary,
until suitable situations could be found for them;
which house was solely under the management of some of the respectable female inhabitants;
and he added, that hopes were entertained of further improvements taking place.

Previously to our landing, papers were brought on board our vessel,
by an officer of the police, for the regulation of the behaviour of the sailors on shore,
which produced no little cheering in my mind, hoping, from this circumstance,
something good was at work at Hamburgh; and however slow it may advance, yet,
if it keeps proceeding, hopes may be entertained,
that in time this improvement will become yet more conspicuous.
Feeling tender of the time of the magistrate,
as well as of the time and feelings of the numerous persons waiting to have a hearing,
we concluded to withdraw, and make him another call.
At our parting he furnished us with an order to inspect
their new establishment for the reception of the sick,
presenting each of us with a handsome engraving of Cuxhaven, the light-house,
bathing rooms, etc. which I cheerfully accepted,
from a belief that he designed it as a token of his respect.
Understanding that the old senator on Hamburgh Burgh
had been removed by death since I was last here,
and that the power of remedying the evils still existing
on the burgh now rested with his son,
as senator and bailiff of the burgh, and feeling my mind drawn to make him a visit,
I found I must either cheerfully give up to it,
or endanger my incurring the displeasure of that Almighty power,
who never yet had failed to be strength to me in seasons of the greatest weakness:
I therefore informed my dear companion, Thomas Christy, how it was with me.

Fourth-day, Thomas Christy and myself, accompanied by Morris Birkbeck, of Hamburgh,
proceeded to his residence on the burgh; but he was from home.
The task of paying this visit, was so truly humiliating to the creaturely part in me,
that I would gladly have excused myself from any further attempt to see him;
but a mode of procedure like this, I was satisfied would not secure for me,
that future aid and assistance from Israel`'s Shepherd, of which,
from the nature and extent of my religious prospects, I should stand in great need;
I therefore endeavoured to ascertain when he was most certain to be at home;
which being done, we left a message, proposing to wait upon him.

Sixth-day morning, accompanied by my dear companion, Thomas Christy,
we proceeded to the residence of the old senator,
the colleague of the young man above mentioned--the senator on the burgh;
but I was under considerable embarrassment of mind; for Morris Eirkbeck,
whom I had looked to for our interpreter, was prevented attending upon us:
which ever way my attention was turned for help, all seemed in vain:
when reaching his house we were not able to make
ourselves understood by any of the family.
We therefore came away again; but discouraging as our prospects were,
I durst not give up the matter, as one not to be accomplished,
if I persevered in doing my best towards it; yet my fear was, lest,
while I was in search of an interpreter, he should leave his house,
and so slip away from us.
We had not gone many yards from the house,
before I met with one of the principal officers of the police,
who had always carried himself handsomely towards me when at the Stadt-house;
he was a German, and spoke English well.
I thought I felt that in my own mind, which would warrant me to stop him, and tell him,
I arrested him into my service; which I accordingly did.
Being taken by surprise,
and unacquainted with the subject I meant to impose upon him to translate, he appeared,
at first, rather to hesitate;
but he soon readily consented to render me the help I might require.
We all proceeded to the house of the old senator again,
and were shortly after introduced to him.
I endeavoured, as matter arose in my mind, to lay things close home to him,
which he appeared to bear more patiently, than might have been expected,
from his apparent marks of consequence and his advanced life.

Feeling my mind drawn to make a visit to the prisoners, we obtained liberty for it;
and on seventh-day morning, accompanied by my companion, Thomas Christy,
and a merchant of the city, who gratuitously fills the office of inspector,
we proceeded to the prison; which, being under considerable repair,
did not admit of the prisoners being generally assembled: there was no other way,
therefore, but to visit them in their cells; where we found ten, sometimes twelve,
confined together.
On the men`'s side of the prison, in the first cell, we found ten men,
nine of whom we were informed were desperate characters: the first sight of them,
together with the confined space within which we were locked together, felt to me trying,
as I concluded the keeper, who was with us, could do very little for our safety,
should they be disposed, from anything that might be communicated, to take offence,
and resent it upon us: but being enabled to flee to the great Keeper of us all,
who had never yet failed to care for me in my most trying moments,
He was pleased to give me the unshaken assurance,
that if I was faithful in delivering his whole counsel,
not a hair of my head should be suffered to be harmed:
and strength was given me to put on courage and trust in his name, in breaking silence.
On requesting our kind friend the merchant to interpret for me,
he at first appeared at a loss to understand my views;
but his hesitation did not long remain, and he soon manifested zeal in the cause,
being evidently helped by best help:
his ready flow of expression was striking to us both,
as well as the effect which appeared to be produced on the minds of the prisoners;
so that if they felt evilly disposed towards us, that disposition was chained down.
I had many hard things to say to them,
yet accompanied by encouragement to seek for Divine help,
to be enabled so to conduct themselves towards each other, that, by their example,
they might be instrumental in improving each other`'s minds;
and thereby become benefitted under the trying situation in which they were placed,
by learning obedience to the Divine law, by the things they were now suffering.

From the countenance of one of the prisoners,
I was led to apprehend he hardly could bear some part of what I had to communicate;
but they parted from us respectfully.
Our feelings of sympathy were much excited on hearing
of the situation of one of the prisoners,
a young man about thirty years of age, neat and clean in his person,
of a very interesting countenance, and of agreeable manners,
who was sentenced to this mode of confinement for life,
in consequence of a murder which he had committed when about sixteen years of age:
during and after this opportunity, the tears kept rolling down his cheeks;
his heart seemed so full, he had not power to express his feelings.
We were informed his character for good behaviour stood
high in the estimation of the conductors of the prison,
and that attempts had been made to have some part of his sentence remitted;
but they had failed.
Although I felt much for him respecting his future prospects of confinement,
yet not sufficient to warrant any interference on my part;
for watchfulness was necessary,
lest the affectionate part should be set to work unbidden.

After visiting more of the men`'s cells, and some of the women`'s apartments,
my bodily strength failed,
and notwithstanding the increasingly animating manner
in which my interpreter conducted himself,
I was obliged to retire to the parlour of the prison;
where every kind attention was paid me.
Feeling myself a little recruited, but not equal to endure further excitement,
and not being pressed in my own mind to attempt it, we took our leave,
acknowledging the kind attention that had been shown us:
our obliging interpreter also expressed, in a feeling manner,
his satisfaction in accompanying us.
We were much gratified by the cleanliness and order which we observed in the prison,
and in the persons of the prisoners,
and in finding that every prisoner was in possession
of a Testament and other religious books,
and that at a stated time every day,
the practice of having the Scriptures read in each of the cells was obligatory.
I returned to my hotel, with the heartfelt language of "`Bless the Lord, O my soul,
and all that is within me,
bless his holy name:`" may I never be suffered to forget all his manifold benefits;
may the help he has condescended to vouchsafe to me this day,
both immediately and instrumentally, be imprinted on my mind,
and remembered in my future seasons of conflict,
that dismay may not be permitted to prevail but that
the language of my soul may continue to be,
"`Draw me, O Lord, and I will again run after thee.`"

Feeling clear of Hamburgh, about mid-day we crossed the Elbe to Harburgh,
in the Hanoverian dominions.
First-day intervening, by travelling hard on second-day,
we reached Hanover in the evening.
I apprehended it would not be safe for me to leave Hanover,
without attempting to obtain an interview with the Duke of Cambridge, who is governor.
We inquired how this was to be effected;
but this inquiry did not afford us much encouragement,
understanding that the duke had arrived late the evening before, from a long journey,
and that matters of state would be likely to claim his immediate attention,
as he was to leave Hanover again the following day:
we however took such steps towards it, as we were directed.

We made a call upon my friend, who,
when I was travelling from Cassel to Frankfort on the Main,
rendered me his kind assistance.
This unexpected meeting, appeared to be mutually gratifying.
He informed us he had been at the palace,
and was struck with seeing my name in the book there.
A messenger soon informed us an audience would be granted,
at the time concluded on by the duke.
This introduced me into fresh exercise, and earnest were my cries to the Lord for help,
to be found faithful in delivering his whole counsel,
however in the cross to the creaturely part;
and to deliver it as well as to hear and receive it.
These engagements, if rightly entered upon,
from the situation occupied by the parties visited,
tend very much to reduce and humble the creature;
great care being necessary to give no just occasion of offence in word or deed,
and also to be preserved from daubing as with untempered mortar,
and sewing pillows under the arm-holes, crying peace,
when war is the word to be proclaimed against Babylon,
as it respects either spiritual or carnal things.

Third-day morning, accompanied by my kind companion, we proceeded to the palace,
to be in readiness when called upon,
and it was soon announced that the duke was in readiness to receive us.
My feelings, at this moment,
may more easily be conceived by such as have been placed in a similar situation,
than words can describe them;
for all that I had aforetime experienced of the puttings
forth of the great and good Shepherd of his sheep,
seemed to flee away, as if I never had been acquainted with it:
but Divine mercy did not suffer me to sink below hope of its being again renewed;
and that he who had called to the work, would care for its completion,
and not only be to me mouth and wisdom, tongue and utterance,
but also open the way in the mind of the duke,
to receive what was given me for communication.
The duke received us in a very respectful manner.
I presented the duke with a book on the doctrines of Friends,
and a German copy of the address to Hamburgh; which he obligingly received.
I thought, as I proceeded, I felt the way open in his mind,
for receiving what I had to communicate,
and I could not refrain offering my hand at our parting, which he accepted;
and I can say, it is with feelings of near affection towards him that I make this record.
We were afterwards informed,
through a channel of which we could not doubt the correctness,
that our visit had been an acceptable one.

One woe is passed, but another has risen up.
I found the way would not open for us to quit Hanover,
until I attempted to obtain an interview with the head police-magistrate.
On informing my kind companion, we proceeded to the police-office, where we found him.
We were received in a courteous manner, and after taking our seats,
strength was in mercy given me to impress on his mind,
the necessity of his feeling the responsible situation in which he had placed himself,
by accepting the office he filled under the government;
that he might be able to see how much lay in his power,
towards remedying the evils which I had enumerated as existing in Hanover;
giving it as my firm belief,
that so far as he fell short in faithfully doing his utmost towards their being removed,
the evil consequences resulting from their continuance would rest on his shoulders,
and he would have a sad account to give in that great day,
when all would have to render an account of their time and talents.
It was no easy task to be found faithful, when hard things were given me to communicate,
lest he should rise up in opposition, as we were completely in his power:
I also felt not a little for my dear companion; but I was thankful, as I proceeded,
in believing such fears as these were groundless;
and what was communicated to him was received in love.
He took an affectionate leave of us,
and refused the usual fees on granting us our passports.

Feeling my mind released from further service in Hanover, we proceeded on our journey,
and reached Minden that night, about thirty-five English miles.
Fifth-day morning, we called upon our ancient friend, Frederick Smidt, who,
although fast declining as to the body, appeared in a sweet, tender frame of mind.
After he had recovered from the surprise which the sight of us occasioned,
he appeared cheered at once more seeing Friends from England.
Feeling drawings in my mind to sit with Friends in
their families at Edenhausen and Hilla,
accompanied by Lewis Seebohm of Pyrmont, and John Rash of Minden,
we proceeded to Edenhausen, and entered on the work;
accomplished four visits that evening, and returned, not a little fatigued,
to our quarters; where our kind hostess had done her best in providing beds for us.
I was favoured to pass the night better than I had anticipated;
and although my weary body was not much refreshed,
yet I hope I was not deficient in cherishing a grateful
disposition for this very best accommodation,
which our friends could with their slender means afford us;
for truly nothing appeared to be neglected on their parts to add to our comfort.
Sixth-day, we visited the remainder of the families, and reached Minden that evening.

Seventh-day, we proceeded to Hilla, about ten English miles from Minden,
sat with a single man, also with one large interesting family,
the children being all grown up to man`'s estate, and then with a man and his wife;
these being the whole that compose this meeting.
Recurring to a consideration that frequently arrests my attention,
as the day is closing upon me--"`Here is another day passed over to give an account
of,`" the retrospect afresh excited in my mind feelings of gratitude for the
help mercifully vouchsafed to us by the great head of the church.

We returned to Minden, and had a sitting in one family;
but my companion finding himself much exhausted, which was the case also with myself,
we were obliged to relinquish our intention of proceeding
further in the visit that evening.
Feeling my mind engaged to sit with such of the inhabitants of Edenhausen
as had separated themselves from the national place of religious worship,
which circumstance had taken place since I was in this neighbourhood before,
I proposed the same to Friends of Minden; and if way opened for it,
for them to conclude about the time.
First-day afternoon appearing the most suitable time for holding this meeting,
the two months`' meeting falling in course on that afternoon,
it was concluded for a few Friends to meet as usual, and adjourn it to second-day.

First-day morning,
the meeting for worship at Minden was numerously attended by Friends and others,
and considerable labour fell to my lot.
When the meeting broke up, the people generally appeared loving towards us,
especially some military officers.
Although to the creaturely part it was hard work,
to acquit myself faithfully amongst them,
so that I would gladly have taken my seat again earlier than I did,
if I durst have done so, the retrospect afforded a consoling hope,
that I had been in the way of my duty; which was fresh cause for thankfulness,
that my great and good Master had counted me worthy,
and strengthened me to advocate his glorious cause amongst men.
In the afternoon, accompanied by my kind companion, Thomas Christy,
we proceeded to Edenhausen; the meeting was held with much quiet in a long hall:
about eighty Friends and others assembled.
I was led humbly to hope that it proved a season of profit to many.
We returned to Minden in the evening.

Second-day morning.
Friends met; and after a suitable time spent in quiet,
the business of the two months`' meeting was proceeded with:
it was consoling to our minds to observe such a willingness to allow ample
time for deliberation on the several subjects that came before the meeting;
also the unanimity that prevailed, and the care to make way for us, who were strangers,
fully to relieve our minds.

One of the Friends of Edenhausen, Earns Pytesmyer,
having been under prosecution for military demands,
and we being desirous to come at a clear knowledge of his case,
we invited him to our hotel.
In the course of our investigation of his case,
it appeared that he had prepared a petition to the king of Prussia;
but from his very remote situation from Berlin,
and the want of means to undertake the journey, his case seemed a very hopeless one.
As we had a prospect of being at Berlin,
and feeling much for the Friend under his sufferings,
which appeared to afflict him sorely, we obtained a sight of his petition.
Friends again met in the afternoon, according to adjournment; the queries were answered;
the meeting continued to be conducted in much harmony,
and separated under a thankful sense that Divine goodness
had condescended to be near for our help.

Third-day morning,
we called upon an individual who had forfeited his membership in the Society of Friends,
when I was here before.
I was then introduced into feeling for his situation,
but suffering the right opportunity to pass by,
when I should have relieved my mind towards him,
the way did not clearly open for it afterwards.
His situation now coming again fresh before me,
I thankfully embraced the opportunity of endeavouring to discharge this duty.
Although I had no reason, from my own feelings, to suppose,
that what I had to offer was resisted; yet a fear attended my mind,
that it found but little entrance into his.
What a mercy it should be esteemed by us, when our unfaithfulness,
in not observing the right time of moving in our religious duty,
does not cause our Divine Master quite to turn his back upon us;
but that he is willing to employ us again.
But O! the care which is necessary that we do not presume on his unmerited mercy;
as our faithfulness out of season deprives us of that fulness of reward,
which otherwise would be our experience.

We returned to our hotel, and by the help of our kind friend, Lewis Seebohm,
entered into the consideration of the petition of Earns Pytesmyer,
the Friend of Edenhausen, to the king of Prussia,
against whom it appeared judgment had been given, but not executed.
We endeavoured fully to investigate the nature and
several bearings of the judgment of the tribunal,
that had passed the cruel sentence against him;^
footnote:[That his property should be confiscated;
that he should be incapable of inheriting any property,
and of carrying on any business in that country.]
and after making some alterations in the petition,
it was put in a train to be transcribed, and to receive the signature of Earns Pytesmyer.
In looking towards Berlin, apprehensions kept rising up in my mind,
that it would be required of me to endeavour when there,
to obtain an interview with the king.
From information we had received, it appeared he was at a watering place,
a great distance from Berlin, where he was to take up his abode for some time:
this occasioned me fresh conflict of spirit, from the strait I was brought into,
how to proceed when I was clear of Pyrmont; whether to go to the watering-place,
where report said the king had taken up his abode; or whether we should go to Berlin.
Earnest were my secret cries to the Almighty,
when my mind was free from exercise on other religious accounts,
that I might be directed herein by my Divine Master.
If we proceeded from Pyrmont to the watering-place,
and the king should have left it for Berlin,
our following him there would occasion us some days`' unnecessary travelling.
But after all my anxiety on this subject,
I saw that if I was favoured to prosecute what was at present before me,
so as to afford a peaceful retrospect on my leaving Pyrmont,
the business of the morrow must be left to the morrow; with the assurance,
that as was the day,
so would be the counsel and help for the fulfilling the business of the day;
if there was but a moving forward one day at a time in simplicity:
and here I was enabled to leave this subject for the present.
Fourth-day, our visit to the families of Friends here was brought to a close.

Fifth-day, I went to meeting, very unequal to face a crowd--poor, blind, naked,
and miserable indeed.
Glad would I have been,
could I have found a sufficient excuse from the indisposition
I laboured under from a sleepless night,
to remain at our hotel; but this could not be:
the meeting was numerously attended by Friends and others;
and in it strength was afforded me to labour, and to obtain relief to my poor,
tried mind.
The people separated in a quiet, solid manner;
many manifesting an affectionate regard towards us.

After taking rest and refreshment, we took an affectionate farewell of Friends here,
which caused many tears and expressions of deep heartfelt sorrow,
to which their countenances bore witness.
We proceeded towards Pyrmont: our first halt was at Buckeburgh.
We called on the counsellor of the chamber of the prince and his sister;
her countenance appeared placid, and her mind much more quiet than when I saw her before:
our unexpected visit was very grateful to them.
We proceeded to Hameln, where we took up our abode for the night.
Fifth-day, we reached Pyrmont, and proceeded with a visit to the families of Friends.

First-day, the meeting was numerously attended by strangers;
and the frequent going out and coming in of such, was an exercise of patience.
At the reading meeting in the evening,
the members and attenders of meeting very generally gave us their company:
a sense of holy solemnity was mercifully felt to be near to us,
during the time of silence, of reading, and of verbal communication;
for which favour I believe most of our minds experienced a sense of thankfulness.

Fourth-day, we began to make preparations for our departure from Pyrmont;
attended the usual meeting, and took an affectionate leave of Friends:
finished packing our luggage.
We proceeded to Hameln that evening, where we lodged.
Fifth-day morning, by starting early, we reached Brunswick to lodge, weary in body,
but I believe we could say, peaceful in mind;
which was cause for great thankfulness on my part.
Sixth-day, we left Brunswick,
where we had been informed the king of Prussia was to leave Toplis for Berlin,
but that his stay would be very short there:
this information made it needful for us to use our
utmost endeavours to reach Burgh that night,
a journey of seventy-five English miles,
which we were favoured to accomplish at a late hour,
much exhausted through the shaking of our wagon over the bad roads.
The nearer we approached the capital,
the more the weight of the prospect before me increased.

Seventh-day, we left Burgh, intending to reach Potsdam,
a journey of sixty-five English miles, by night, which we were favoured to accomplish.
First-day, we remained quiet in our hotel,
until we understood the places of worship were closed.
Necessity appearing to compel us to leave Potsdam for Berlin,
a journey of about twenty English miles, we were favoured to arrive there safely,
late in the evening.
We had been addressed to private lodgings; but when we arrived at the house,
the whole of the family were from home: fatigued in body,
and under increasing exercise of mind,
I had been looking forward with a comfortable hope, that when we reached Berlin,
I should be favoured to witness some outward quiet in private lodgings; but,
alas! my disappointment in this respect was very trying to the fleshly part,
as night was fast approaching.
Persons who passed the streets observing we were strangers,
and labouring under difficulty,
proposed to our interpreter different places for our accommodation;
at last we proceeded to the place we understood the most likely for us to find shelter,
which proved to be only a common wagoners`' house,
and so full of guests as scarcely to allow of our finding beds:
here we were glad to lay down our weary bones,
although our bed-room windows looked into the common stable-yard,
and the traffic which was going forward there during
the night allowed of but little quiet:
our bedrooms were very small, and abounded with fleas and flies;
and the weather was extremely hot: these,
together with the smell from the numerous stables,
and a violent storm of thunder and lightning,
occasioned my having a very distressing night.

Second-day, we procured lodgings which promised us more comfort: about mid-day,
accompanied by my kind companion and Lewis Seebohm,
we proceeded to one of the universities in search of a professor,
with whom I had made an acquaintance when at Hamburgh; he not being at home,
we left our address.
In the course of the evening he made us an agreeable visit,
and offered to give me the names of a few serious persons in Berlin,
which I gladly accepted, under feelings that led me to hope they would prove the means,
in some way, of helping me in the prosecution of my religious prospects there,
as I had come without reference,
except being in possession of a letter from a kind friend in England,
addressed to a person who, it appeared,
was one of the chaplains in attendance about the court.

Having heard of William Hoffman, who, by the inhabitants of Berlin,
was reputed to be of our religious Society, we made him a call that evening.
We found him living in a poor, miserable apartment; his room was so small,
we could scarcely sit down to be comfortable.
We learnt that his means of subsistence were derived from
teaching a few young men the French and English languages.
It appeared, during our conversation with him, that he was one amongst many more,
whose minds had been awakened, when Sarah Grubb visited these parts; most of whom,
he told us, were now removed by death,
and others had sorrowfully made shipwreck of their faith.
William Hoffman, it appeared,
did not associate for worship with any of the different professors,
but secluded himself very much from society: from reports we received,
he was much esteemed for his circumspect conduct.
He had several Friends`' books in his possession;
we added to his little stock as far as our means allowed,
and left him under feelings of regard.
Third-day morning, we called upon an individual,
towards whom my heart glowed with feelings of religious love,
although we were quite strangers to each other:
by endeavouring to abide under these precious feelings, willing,
should any little service be called for, to be faithful therein,
matter was given for communication: by yielding obedience I found peace,
accompanied by a belief that my offering was well received.

Whilst on my way from Pyrmont,
my mind was at times tried with the consideration of how I was to proceed,
should my prospect continue of a visit to the King of Prussia,
in order that an interview might be obtained;
having nothing but the letter given me by a kind friend in England.
I endeavoured at times to console myself with a hope
that this letter would do the needful for me;
but the event proved that this was not to be the means through which my help was to come.

We next proceeded to the residence of the person to whom this letter was addressed;
but he was not at home.
This disappointment produced fresh cause in my mind to seek for Divine help,
to be preserved in a becoming manner in the exercise of faith and patience earnestly
craving of the Lord that all my movements might be directed by Him.
We concluded to make another attempt to present this letter, and proceeded accordingly,
under anxious feelings of mind, to meet with him.

The subject of an interview with the king now pressed with increasing weight on my mind,
accompanied by a fear, lest the want of prudent promptness on my part,
or a too hasty movement to attempt its being effected,
should mar all my hopes of a faithful discharge of duty,
and involve me in condemnation of mind, from which I never might be able to rise.
But adorable mercy did not leave me to become a prey to the temptation of despair,
but awakened afresh in my mind the assurance, that,
although some bitter cups would be meted out to me to drink,
before the way would open with clearness for me to take my departure from Berlin,
yet if I maintained a full and perfect reliance on that never-failing arm of Omnipotence,
which thus far had carried me through my many provings,
I should still find it to be all-sufficient,
and know of a truth the Lord`'s strength to become
perfect in the times of my greatest weakness.
When we reached the residence of this person, we were again disappointed;
and from the feelings of my own mind, I believed it would be safest for me, at present,
not to make further attempts to see him.

We returned to our hotel, and endeavoured to sit down in quiet.
After awhile the way seemed to open on my mind with a degree of clearness,
that it would be right to read over deliberately the list
of names of serious persons given us by my friend the professor,
who called upon us from the university.
This we accordingly did, and with a care on my part whilst they were being read over,
if the feelings of my mind were particularly directed to one name more than another,
to keep that name in view; and when the list was gone through,
to see how far it would be right for me to make such individual a call.
Whilst the list was thus read over,
my mind was in a particular manner bound to an individual therein named,
I therefore proposed our proceeding to his residence, which we accordingly did;
but he was absent from home.
Although I felt some disappointment, yet I was not discouraged;
for a secret hope attended my mind, that I was now in a proper channel for help:
we then made inquiry when we should be most likely to meet with him at home,
which having learned, I was favoured to return in quietness to our hotel,
and I retired to rest; enabled under holy help to renew covenant,
to be willing to do my very best,
in accomplishing whatsoever appeared to be the Divine mind and will concerning me,
whilst resident here.

Fourth-day morning, 4th of eighth month, 1824,
we again proceeded to the residence of the individual,
who yesterday was absent from home; finding him within, we sent a request by the servant,
that when it was convenient, he would allow us to have an interview with him;
on which we were soon shown to his apartment.
I presented him with my certificates, which he appeared to read with attention.

Feeling the evidence in my own mind that I had now taken the right course
towards way being made for the discharge of apprehended duty;
I felt as if I was with a well-disposed friend, although, as to the outward,
we were total strangers to each other.
During the time he was reading my certificates,
I was afforded a suitable opportunity for retirement of mind,
with a view to seeing with some degree of clearness how I was to proceed,
in order to receive that help from him,
which it was the design of my Divine Master he should afford.
I then informed him of my apprehensions of duty, to obtain, if possible,
an interview with the king, and that I must throw myself upon him for help,
in pointing out the most certain way to proceed in order to obtain it.
This appeared to affect his mind with momentary embarrassment, but as it regarded myself,
the belief that these movements were thus far ordered by the Lord, gave me confidence,
that all would work together for good at last.
After pausing, he gave us the address of Count +++_______+++, who, we were informed,
filled a station about the court, as likely to afford me help,
and he encouraged us to call on the countess, and make use of his name.
This interview thus far was cheering to my mind, and acted as a spur to my exertions.

The king, we were informed, was expected at Berlin that day for a short time.
The call was proclaimed in the ear of my soul,
to lose no time in the attempt to obtain an interview with the count.
We therefore made the best of our way to his residence;
but on our arrival he was from home.
We made application for an interview with the countess, which was readily granted us:
she spoke good English,
so that our interview promised more satisfaction than otherwise might have been the case;
and the more so, from the proof she gave in conversing with her,
of her genuine piety and true humility of manners.
Whilst we were in conversation with her, a person advanced in life entered the room, who,
from the ribbons and stars which hung about his person,
appeared to be a man of some distinction in the government: he took his seat amongst us,
and we found he spoke some English,
and I feared he would prove an obstruction to having such a full
and select opportunity with the countess as appeared desirable.
I was however assured in my own mind I need not be afraid, before this person,
to present the countess with my certificates to read;
as this appeared to me to be the best way to proceed preparatory
to informing her of my views in calling upon her.
Being desirous of having as early an interview as
could be well allowed us with the count,
we waited awhile, not knowing but our new comer-in would soon depart,
which not taking place, all my fears respecting him vanished,
and I could no longer hesitate to present my certificates to the countess,
and afterwards to our new comer-in: the latter appeared to read them with much interest,
making his observations on parts as he went along,
so that it was evident his mind was favourably impressed towards our religious Society.

My good Master having thus in mercy condescended to open a wide door for me,
to lay before the countess and her visitor my apprehensions of
duty to have an interview with the king and his son the crown-prince,
I accordingly did so; during which, I thought I felt as I went along,
that they were in degree permitted to be dipped into a feeling of my situation,
and that interest was excited in their minds on my account.
I presented the stranger with a copy of the address to Hamburgh, which he read;
and having finished the reading of it, he said, he was to meet the king on his arrival,
to whom he should present the address,
and inform him of my request to have an interview with him.
At his departure he expressed in a feeling manner the desire he
entertained that the Divine blessing might attend my engagements.
We then took leave of the countess, concluding to wait on the count the next morning.

Fifth-day morning, we proceeded to the residence of the Count;
on our getting sight of the house, I observed a carriage drive swiftly from the door,
which led me to fear we should be disappointed in seeing him,
which proved to be the case.
The countess hearing we were in the hall, had us invited into her sitting-room;
and we passed a considerable time in conversation with her and her female companion,
which perhaps at another time would have been very interesting to me;
but being somewhat sorrowful because of our having missed the count,
I was deprived of that pleasure, which my dear companion Thomas Christy partook of:
we returned to our hotel, and in the evening we made a further attempt,
and found the count at home.
On our being introduced to him,
I thought it was evident the countess had prepared
his mind for the business we were come upon,
as he received us with open arms.
We sat down together under feelings of much solemnity;
I gave him my certificates to read,
and then laid before him my prospect of duty to attempt
an interview with the king and his son,
the crown-prince; telling the count I must throw myself upon him for help,
and requesting his utmost exertions for my relief.
I felt such an evidence, after I had thus expressed myself,
of his willingness to do his part faithfully towards accomplishing my views,
that I was fully satisfied with the matter being left under his care.

We returned to our hotel, and shortly after this interview with the count,
information was received that the crown-prince had been applied to on my account,
and that the time for our waiting on him was concluded upon;
at which the creaturely part in me began to feel dismay:
but O! the merciful evidence I was favoured with,
that the all-sufficient arm would be near to sustain me in the needful time;
whereby I was enabled to hold up my head in hope,
that neither the cause in which I was engaged, nor my kind friend the count,
who had been instrumental in making way for me, would be disgraced through me.

Fifth-day, 11th of eighth month.
This day being appointed for our having an interview with the crown-prince,
we left our hotel accordingly,--I may say of myself, feeble in body and feeble in mind;
and arrived at the castle.
The prince`'s apartments being under repair,
he had taken up his abode in a different part of the castle,
and our guide not being expert in inquiring for the prince`'s new apartments,
we lost much time in finding the entrance to them;
this added not a little to the discouragement of mind I was suffering under,
fearing that we should be behind the time appointed by the prince.
At length we made out the entrance, and were shown into an antiroom,
in which were several livery-servants, attendants on the prince,
one of whom took charge of us: our passing through the rooms with our hats on,
appeared to excite surprise.

After waiting awhile in the room, in which we were left by the servant, our kind friend,
the count, gave us his company; and shortly after introduced us to the prince.
On entering the prince`'s apartment, he received us in an affable manner,
offering me his hand: having seen my certificates,
he was by them acquainted with my views in coming to this country.
After he had put some questions to me, and I had made replies, I informed him,
that during my residence at Berlin, my mind had been renewedly impressed with a belief,
that the present day was an important one to Prussia;
a day of renewed visitation from Almighty God,--a day in which
the light of the glorious Gospel of Christ Jesus our Lord,
was afresh dawning in the hearts and minds of many of the inhabitants of that nation:
to which the prince replied, he believed so too.
I then added, "`earnest had been the prayer of my soul,
that nothing on the part of the prince, the clergy, or the people,
might be suffered to prevail,
that would have a tendency to retard the progress of this good work;
but that Prussia might become the beauty of nations,
and praise of the kingdoms and states that surround her.
In order that this good work might go forward in a way that
I believed was consistent with the Divine will,
there were some matters that must claim the proper attention of those who were in authority.`"

The prince appeared to receive kindly what was offered on this and other subjects;
and I concluded with expressing the desire which attended my mind,
that the prince and princess might be true help-meets to each other,
instrumental in the Divine hand in furthering each others`' present and eternal welfare,
and uniting in a concern to be found holding out, by their example,
this language to each other and to the people at large, "`Come,
let us go up to the house of the Lord, to the mountain of the God of Jacob;
who will teach us of his ways, and we will walk in his paths.`"
At our parting, the prince taking hold of my hands,
in a feeling manner said,--"`Do not forget me,--do not forget me.`"
On my saying, I hoped our keeping on our hats had not hurt the prince`'s feelings,
he handsomely replied, "`If I had suffered my feelings to be hurt by it,
you would have had cause to think badly of me.`"
We presented the prince with several Friends`' books, and the address to Hamburgh.
The prince then informed us, he understood from the king,
that arrangements were making for my having an interview with him also.

We made an early call on our kind friend the count,
he being in attendance on the prince when we made our visit to him.
I felt much for him at the time, from his not being able to understand what passed;
and the responsibility that would attach to him,
should anything I might say give offence:
but on my informing him how it was with me in this respect, he replied,
he was glad to be present at the opportunity;
for although he could understand but very little of what I had to say,
yet he was made sensible of the substance, from the feelings he had here,
putting his hand to his heart.
He said the prince, after our departure,
told him he rejoiced at having made acquaintance with those good men;
the count further added, the desire he felt,
that we might remember him in our prayers to Almighty God.
