== Chapter XXV.

No information having been received of the arrangements for our visit to the king,
we waited on the Prince Witgenstein, who is in attendance on the king:
he received us in an affable manner.
On his being made acquainted with the cause of our call,
he informed us that the king had left Berlin for his palace at Charlottenburgh,
but was expected to return on second-day;
and as he should be with the king before that time,
he would use his endeavours that my wishes should be accomplished.

Having felt drawings in my mind to pay a visit to
the prisoners in the state-prison at Spandau,
about ten English miles from Berlin,
to which criminals are removed after sentence is passed against them;
and the subject coming before the view of my mind with increasing
weight whilst we were sitting with the Prince Witgenstein,
and in a manner that led me to believe it would be right
for me to open my prospects to him in this respect,
I mentioned the subject to him,
requesting his advice how to proceed to obtain permission.
I had rather doubted the liberty being granted us,
as I understood that one of my countrymen, who had obtained this permission,
had made such unfavourable reports in print,
relative to the state of the prison and prisoners in various respects,
that it gave great offence to those in power.
The prince however put the question to me,
whether curiosity was my motive for desiring to visit the prison;
but when I told him my real motives for making the request,
he appeared disposed to enter into my views, and gave us a letter.
From the many titles upon the address of the letter,
we supposed the person to whom it was addressed was a person of consequence in the government.
With this letter we proceeded as directed:
but the manner in which we were received did not give me a favourable
opinion as to our reception by the person to whom the letter was addressed.
I concluded our standing in his presence with our hats on,
caused him to treat us with a kind of hauteur we had not before met with: this I found,
without great watchfulness, the creature was ready to recoil at;
but feeling the evidence in my own mind,
that the cause which had brought us to him was not my own, but my Divine Master`'s,
I endeavoured to rise above noticing his treatment.
We were ordered to be with him again the next morning.

Seventh-day morning,
we proceeded to ascertain the result of our visit with the letter presented yesterday.
I was not wholly without apprehension, that our request would not be granted,
from the manner in which we had been received: had this been the case,
I could have sat down satisfied with a refusal,
believing my movements thus far in the business,
had been under the influence of best Wisdom,
and that the will would be taken for the deed.
Although the individual carried himself with as much distance towards us as before,
yet he furnished us with two letters,
one addressed to the governor of the prison at Spandau,
and one to admit us to the town-prison;
that for the town prison we were ordered to present
to the chief magistrate of the city for his signature.
We accordingly proceeded to his residence.
I may remark,
that the town-prison is for the reception of those who are waiting to take their trial;
here great caution is used in admitting persons of any description,
before the prisoners have been tried.
At first he spoke rather sharply to us; but when he inquired of me,
was curiosity my motive for desiring to go to the town-prison,
and I presented him with my certificates, and he had read them,
he appeared cheerfully to add his signature to our order, saying,
had not his engagements with government concerns required his attendance elsewhere,
he would gladly have attended us.

We proceeded to the prison and produced our order;
the person in authority met us at the gate, and asked us if we had called at his house,
and been disappointed at not meeting with him.
To our agreeable surprise, he proved to be the magistrate, whose name,
amongst other serious persons in Berlin, had been furnished us by my kind young friend,
the professor before mentioned.
His countenance bespoke the pleasure which the prospect
of attending upon us afforded him;
and from the feelings of affection awakened in my mind towards him,
his company felt equally grateful to me.

Our first visit was to a man about twenty years of age, in a room by himself;
his legs were chained to the floor, and one arm to the wall; the cause of which,
we were informed, was, that he had repeatedly made his escape from prison.
He was committed for having twice willfully set fire to buildings,
whereby a whole village was destroyed; and about two years ago,
sentence of death was passed upon him: but the merciful laws of Prussia,
and the merciful disposition of the king, had prolonged his life: his present situation,
notwithstanding the greatness of his crime,
awakened in me every feeling of pity I was capable of.
I endeavoured, as ability was afforded,
to lay before him the awful situation he was placed in, through his own evil conduct,
not knowing how soon an order might come for his execution:
he appeared very calmly to hear what I had to say, without, as we could observe,
manifesting signs of sorrow for his conduct,
or a sense of the awful uncertainty of his life, until, at our leaving him,
I gave him my hand, when a change took place in his countenance,
and he grasped it very sharply.
I have since been informed, that the severest part of his sentence is,
by the mercy of the king, remitted.

We next proceeded to the women`'s department, consisting mostly of young persons:
with them we had an interesting opportunity; most of them were brought to tears,
manifesting at our parting, a grateful sense of this token of Divine regard: after which,
we were conducted to a large room, in which, by order of our friend the magistrate,
the keepers brought out the prisoners from their places of confinement,
and collected them together.
In addition to the magistrate, the keepers and prisoners,
we had the company of several genteel looking men,
who remained until the opportunity closed, which was conducted with great quiet.
At our parting, the prisoners generally evinced tenderness,
giving us their hands at leaving them.

After this we called upon the pastor, to whom my friend`'s letter was addressed.
I was struck with his fine person, and the very polite manner with which he received us,
and his profession of the great pleasure it gave him to meet with us.
After he had read the letter of my friend, I presented him with my certificates.

First-day morning, my dear companion Thomas Christy, our kind interpreter,
a young man who had shown us much attention, and myself, left Berlin for Spandau,
where we arrived about ten o`'clock.
Whilst our breakfast was preparing, we made inquiry when, what is called,
the service would be likely to close at the prison;
apprehending if I could sit with them before they separated,
it would make less difficulty in visiting the prisoners
than if they were specially assembled for the purpose.
Hearing the bell begin to chime for the prisoners
to assemble in their place for religious worship,
I placed myself at the door of our hotel,
where I had a full view of the entrance into the prison:
and when I observed a person whom I supposed to be the chaplain of the prison,
making towards it, my interpreter and I met him before he entered the prison,
to whom I proposed my sitting with the prisoners, after he had done with them.
He informed us it rested with the governor to grant such permission; this being the case,
we proceeded to the prison, and were introduced to the governor, who received us kindly.
I informed what my motives were for wishing to see the prisoners,
and my desire to have them all together;
on which we were requested to attend at the prison at twelve o`'clock,
that being the dinner-hour of the prisoners,
and then we were assured an opportunity of seeing them should be afforded me.
I felt it right for me to request,
that the pastor of the prison should be informed of our intention,
and if he inclined to attend, his company would be acceptable.

We proceeded at the time appointed, and found the governor, at sight of us again,
considerably agitated in mind,
and alarmed at the prospect of my intended visit to the prisoners so generally together.
He appeared to bring forward every excuse he could think of,
to discourage me from making the attempt,
telling us that many of the prisoners were such desperately wicked creatures,
that it would be dangerous for us to venture in amongst them.
From the assurance I was favoured with, which never yet had failed me,
I was persuaded that they would not be suffered to harm a hair of our heads;
so that I felt as if I should not hesitate to go in amongst them alone,
could I have made them understand my language.
Notwithstanding all the difficulties which the governor threw in our way,
I found I must persist in my determination to see the prisoners,
if it could possibly be allowed.
When he observed I continued so firm in my determination,
that none of his arguments were sufficient to overcome me,
and cause me to yield to his fears of consequences, he trembled, but at length yielded,
and introduced us to the women prisoners; the pastor also gave us his company.
Here we found about seventy assembled, which we understood were all the female prisoners,
except a few who were ill.

The pastor placed us on a flight of steps,
and the governor gathered them in a circle around us: quiet soon prevailed,
such a quiet as I have not often known to be exceeded.
Before I had expressed much of what I had to offer amongst them,
the tears rolled down their cheeks: this tenderness spread over nearly the whole company;
with some it appeared an effort to avoid crying out,
under the sense they were favoured with, of Divine conviction:
one young woman was obliged to be borne away by some of her companions.
This opportunity proved the most heart-melting of which I ever was a witness;
and on informing them of my desire at parting to give each of them my hand,
they crowded round me in an affectionate manner for that purpose.
The large portion of good wholesome provisions served out to the women, with the clean,
neat appearance of their persons and apparel,
and the order that appeared to be preserved,
did great credit to the managers of this prison.

On quitting the women,
although I found the pastor and governor were well satisfied with our visit to them,
yet I was aware that fear still predominated in the mind of the governor,
and that a consultation was going forward how we were to see the men together,
their yard not being considered a safe place for them all to be collected.
I felt that hesitation was still working in the mind of the governor,
against our seeing the men all assembled; and he again expressed his fears,
that a disturbance would take place amongst them, adding,
that some of them were such terrible characters.
However, I continued to feel that which I thought warranted me in saying,
my confidence had not left me, and that I was not afraid of going amongst them.
The governor, finding his arguments did not prevail with me, proposed,
that instead of admitting us now, as I had expected,
we should come again to the prison at three o`'clock in the afternoon,
when he would have the men collected in the chapel:
the event proved this delay was only to allow time to separate
such prisoners as they feared were the most likely to commit outrage.
I requested our interpreter to tell the pastor,
I should be sorry to give just occasion of offence to him
or any present by our keeping on our hats in their chapel,
to which he replied, we were at liberty to use our own freedom in that respect.

On entering the prison in the afternoon,
we were followed by several persons of genteel appearance,
besides the police-master and the principal officer of the military department.
The governor then informed us, that the prisoners were collected in the chapel.
Seeing a convenient seat near the pulpit, we took our seats there;
quietness soon prevailed;
the prisoners generally appeared solid and attentive to what was communicated:
some of them were tendered to tears.
The opportunity being over,
the governor arranged the prisoners on one side of the chapel, as I had requested,
to give each of them my hand at our parting,
notwithstanding the flesh had pleaded against it,
lest I should by such means take a disease,
or if any of the prisoners should be maliciously disposed,
it would be affording them an opportunity of doing me an injury.
They however passed away in a very orderly manner, and appeared grateful,
pressing their hands in mine, and would have saluted it,
had I not put them by from so doing.
The number of men thus collected appeared few to what I expected to see,
and why it was so, I was at a loss to understand.

It so happened that I did not feel that relief to my own
mind on leaving the men as I had done when leaving the women.
We retired to the governor`'s apartment, and shortly after we had been there,
he surprised me by laying before us, taken down in short-hand,
what had been communicated in the chapel to the prisoners;
this circumstance occasioned me momentary embarrassment,
but the retrospect afforded a peaceful reflection as far as I had gone.
There still felt in my mind a shortness in our visit to the men,
which I could not account for: however, we returned to Berlin,
thankful to almighty God for the help he had in mercy vouchsafed to us this day.
As far as respected my visit to the women, my mind continued to feel fully relieved;
but my visit to the men did not afford me the full relief I hoped for,
but why such should be the case I was still unable to understand.

Second-day,
as the concern still remained with me to make a call
on the Stadt-director and chief police-master,
I again looked at attempting the discharge of this duty;
but the way did not open for it with sufficient clearness to justify my proceeding.
No intelligence being yet received relative to an interview with the king, was indeed,
an exercise of patience; and such were my plungings, that I was led to conclude,
should a messenger arrive fixing the time for it, I was not equal to the task.

We received agreeable visits at our hotel,
from the magistrate who attended upon us at the town-prison,
and from the young man who accompanied us to Spandau,
which proved a little cheering to my mind; believing they were,
as well as others we have met with in Berlin,
rightly concerned to be found seeking the way to Zion, with their faces thitherward.

The cause of my mind not feeling fully relieved by
my visit to the men prisoners at Spandau,
now became developed:
for it came out that the governor had separated the most desperate characters,
and kept them back, so that we were not allowed to see them.
This circumstance would, I feared, from my feelings,
involve me in the necessity of attempting a further visit to them,
which would be trying to my mind, as well as to my dear companion, Thomas Christy,
who was soon expecting to leave Berlin for Hamburgh on his way home.
I had at times entertained a hope, I should be at liberty to accompany him there,
on my way for Cronstadt in Russia;
but every gate of Berlin appeared in my view closed against me:
my prospect of a visit to the Stadt-director, and police-master,
making calls on persons I had not yet seen,
and appointing a meeting for such as inclined to give their attendance,
still remained with me;
but no authority was felt to move towards the accomplishment of them.
My dear companion, as well as my friend Lewis Seebohm, for whom my sympathy was excited,
as their calls home had now become very pressing, were both solicitous,
as well as myself,
to be able to come at something definite with regard to an interview with the king:
a further application to the prince Witgenstein was therefore proposed,
but my way did not appear clear to move in it.

Third-day, on our way to the hotel,
we met our kind friend who had given us the address to the Count ,
who informed us he had understood from very good authority,
that the king had so many engagements before him,
he would not be able to see us before he left Berlin.
This report coming from an attendant at the court,
my companion wished me to consider as decisive information;
but from my own feelings on the occasion,
I could not give up the hope that the way might be
made for me to obtain the desired interview;
and I believed that nothing would be so likely to
bring it about as quietness and entire confidence,
if my concern was rightly begotten,
that the same Almighty Power who had thus begotten it in my mind,
and in whose hands the heart of the king was, would, in his own time,
make way for the accomplishment of it.

We had not long returned to our hotel, before, to my humbling astonishment,
a messenger arrived from the prince Witgenstein,
requesting our interpreter to wait upon him:
after waiting a considerable time to know the result,
Lewis Seebohm returned with a message from the prince, saying,
that the king would receive us at Charlottenburgh the following day;
that all things would be arranged at the palace for our reception,
and that the prince would introduce us to the king.
Although, as far as respected the prospect of my speedy release from Berlin,
this message was relieving to my mind, yet the increased load of exercise it occasioned,
can only be felt to the full, by those who have been placed in a similar situation:
to appear before an absolute monarch, whose word is law,
to plead the cause of Him who is King of kings, and faithfully to deliver his counsel,
be it what it may, involves the mind in many awful considerations.
The reception of this message, was followed by such a stripped state of mind,
that I was tempted to conclude the movement I had made was
under the influence of the adversary of all good;
in order that my weakness might be exposed to those,
in whose minds I had already found a place;
which brought on a severe attack of nervous cough, that tried me much;
yet under all these discouragements,
I was favoured with strength to crave of the Lord my God,
who is all-sufficient to fill my mind in the needful time, to empty and strip me,
as he saw best for me, and for the honour of his cause,
when my faith and faithfulness to his requirings were to be put to the test.
Oh! the earnest cries I was enabled to put up to be preserved,
faithfully delivering what I was favoured clearly
to see to be the counsel of my Divine Master,
without yielding to those slavish fears of man, which, if yielded to,
disqualify for doing the Lord`'s work faithfully.

Fourth-day morning, the forepart of the night I was favoured to sleep well,
and to have my mind preserved quiet, which was another great favour;
but I found that to witness this state of mind,
which was so essential to the well ordering of my
steps in the prospect of duty now before me,
unremitting watchfulness was necessary;
as the adversary of all good was diligently watching
his opportunity to set my mind afloat,
with considerations of what I should say to introduce myself to the king;
but Divine mercy bore me up against the torrent which rushed upon my mind;
for had it been yielded to,
it would have robbed me of the heavenly quiet in mercy dispensed.

We left our hotel this afternoon for Charlottenburgh,
about four English miles from Berlin: on our arrival at the palace,
the sentinel brandished his naked sabre to us to come forward, when a person,
who spoke English, took charge of us, and conducted us into an apartment of the palace.
As soon as the palace-clock struck three,
the person in attendance upon us informed us the king had finished his dinner, saying,
the king`'s practice was to sit down to the dinner-table at two o`'clock,
and rise again from it at three, allowing himself one hour to take his dinner.
In this respect I thought this monarch set a good
example to the great men in my native land.

The person in attendance upon us requested us to follow him into the garden,
where the king would see us,
as I had requested to be excused from an introduction in the usual form:
this mode to me felt a pleasing one.
Waiting at the spot where the king was to meet us,
the person in attendance announced to us,
"`The king is now advancing up one of he avenues towards you,`" and immediately withdrew.
The king then approached us, attended by the prince Witgenstein and his aide-de-camp:
on coming up, he inquired, "`What is your business?`"
We then first presented to him the petition of Earns Pytesmyer,
which he took and handed it to his aide-de-camp:
on the king`'s being informed the petition was on
behalf of a member of our religious Society,
who had been under prosecution on account of his conscientious
scruples against serving as a military man,
he replied, it was not his intention they should have proceeded thus against the Friend.
On the king`'s being reminded that on a former occasion he had said,
conscience with him was a sacred thing, he replied, "`It is so,
and the man shall not suffer.`"
We afterwards heard that he remitted the whole of the sentence.
I then requested the king would accept of some Friends`' books,
which his aide-de-camp took charge of.
Observing the king made use of some English expressions, on my saying,
"`I perceive the king does speak English;`" he replied, "`A very little.`"
The important moment was now arrived,
when I believed I was called upon to address the king in the Lord`'s name:
on my taking off my hat when I began to speak, the king took off his cap.
After I had expressed a few words, the king replied,
"`I see what he wants,--tell him I have read his address to Hamburgh,
and it has pleased me much;`" adding,
"`I wish the Lord may bless you in these your undertakings.`"

We were now, as we supposed, left alone in the garden;
but the person who brought us here soon joined us again,
and gave us to understand he had received orders
from the king to attend upon us to the mausoleum,
a new erection in the garden of the palace, the burial place of the late queen;
and to conduct us about the palace.
This mark of respect we could not but feel grateful for,
although I should have been willing to pass quietly to our hotel,
as our inclinations would not be more gratified by what we should see,
than it had been by the handsome, patient hearing, the king had indulged us with:
but fearing, as the person was very urgent that we should go through the palace,
if the king should question him, and he could not say we passed through it,
the king might think our guide had neglected us, and he might come into blame,
we concluded to follow him.
The great simplicity of the furniture in a suite of rooms occupied by the late queen,
was gratifying, showing the humble state of her mind:
a table stood by her bedside as she left it, on which remained the Bible she used.
Her memory I found was precious to many of her subjects, on account of her good example.
Feelings of reverent gratitude filled my heart, in the belief, that,
through the extension of holy help, this day`'s work, although very trying in prospect,
was well got through:
the retrospect afforded fresh cause for making sweet melody in my heart to the Lord,
and singing, "`Hitherto the Lord hath helped me.`"
May he alone have the praise from the visitors and the visited,
is the prayer of my grateful heart!

In the evening we were visited by an interesting young man,
who had been educated in the Jewish persuasion,
whose mind had been awakened in consequence of a
Testament having been put into his hands:
his countenance and demeanour bespoke the divinely gathered state of his mind,
which appeared the more evident as we became further acquainted with him.
My dear companion, Thomas Christy, continuing to feel anxious to return home,
I no longer durst attempt to detain him;
and I began to believe that the time for my own departure was not very distant:
the thoughts, however, of being left alone, felt trying.
I also found that my kind friend, Lewis Seebohm, would be glad to be released,
on his family`'s account; and I saw no way of safety for me,
but to endeavour after patience, and entire resignation to my present allotment;
and to move forward from day to day, as the clear pointings of duty may require of me.

Fifth-day morning, my companion engaged his place in the diligence to hamburgh;
after which, returning to our hotel,
and feeling in our minds that something was due from us to the prince witgenstein,
for the kind attention and assistance which he had afforded us,
we drew up the following address:

To The Prince Witgenstein.

It is with feelings of gratitude,
we request thou wilt permit us to acknowledge thy kindness in making way for us,
who are strangers, to express to the king, whose confidence thou enjoyest,
the words that were in our minds,
and which we think nothing less than the feelings
of religious duty would have warranted us in doing.

We are thankful for the opportunity, and thankful to the Almighty Creator of all things,
and to the king, that we came away with our minds relieved,
and we trust thou wilt share with us in the peaceful reward.

We are desirous of expressing a little matter respecting the prisoners at Spandau,
believing thou hast their welfare much at heart.
We wish to suggest,
how well it would accord with the king`'s kind disposition towards these poor creatures,
for the governor to be directed to furnish a Testament to each of the prisoners,
male and female, who shall desire to have one,
and who the governor is satisfied are likely to make a proper use of it;
and as a further reward for good conduct,
a hymn-book and other small books which may be approved; and those who have books,
to be allowed a small box with lock and key, which maybe made in the prison.
A prisoner, when his work is done for the day, would then have a book to resort to,
instead of spending his time in hurtful conversation.

We further suggest,
whether an advantage would not arise from one of the best
readers reading to the rest of the prisoners every evening:
the prisoners at Hamburgh, we observed, were each furnished with books,
and we think to great advantage.

We are, with feelings of sincere regard,

Thy affectionate friends,

Thomas Christy, Thomas Shillitoe.

Berlin, 10th of Eighth month, 1824.

After signing the above, my dear companion took the diligence for Hamburgh,
leaving me to fill up my measure of suffering and exercise,
which I thought still awaited me here.
The circumstance of the governor at Spandau having kept me from seeing
those prisoners who were considered to be the most desperate characters,
began now to operate on my mind,
and led me to apprehend it was one of the matters that detained me at Berlin.
I was ready to fear attempting another visit,
when I considered the difficulty that might attend a second application for that purpose,
and the blame that would attach to me, should any of the governor`'s fears be realized;
and yet I felt a dread on my mind of the consequences of my rebelling against that conviction,
which was gaining ground on my best feelings.
I therefore found I must be willing to attempt a
further visit to the men prisoners at Spandau.
Great were the strugglings between flesh and spirit on this occasion;
but seeing no way for me to come at a peaceful, quiet state of mind,
but by cheerfully surrendering my life and all into the Divine keeping,
I was enabled to breathe forth the language of, "`Here am I, Lord,
send me whithersoever thou pleasest.
Resignation being thus wrought in me,
the way appeared to open to make application to the Prince Witgenstein,
for liberty to visit the men prisoners again at Spandau:
our address of acknowledgment of the prince`'s kindness being still in my possession,
I made the following addition to it:

So far as my visit to the prisoners went, when at Spandau, it was to me satisfactory;
but as this visit was only partial--those considered to be the most desperate
characters amongst the men not being present at the opportunity,
from a fear they might prove unruly--and my mind
still feeling anxiously engaged for their welfare,
I do not see I can leave Berlin comfortably to myself,
without making another journey to Spandau, and visiting these also,
if I may be permitted so to do.
If the prince should feel his mind easy to assist me in this matter,
as I am not sure that my former letter will be sufficient
to admit me for that purpose again,
I shall feel truly thankful for it.

Thomas Shillitoe.

Sixth-day, having made this addition,
my kind friend Lewis Seebohm proceeded to the prince`'s residence; he being from home,
the letter was left.
Seventh-day morning, a messenger from the prince came to our hotel,
requesting Lewis Seebohm would wait upon him at his own residence.
On his being introduced, the prince told him,
that on the receipt of my second request to visit the prisoners at Spandau,
he himself waited on the minister of justice, and read my request to him,
in order that no difficulty should be laid in the way of
my making a second visit to the prisoners at Spandau;
he then desired Lewis Seebohm to call on the minister of justice for the order of admission;
and added,
that directions were forwarded to the Bible Society to furnish the prisoners with Bibles.
The order for admittance not being prepared,
the minister of justice engaged to send it to our hotel in the course of the evening.
The way opening in my mind this morning,
to make a visit to the commandant of the city and to the minister of the police,
we proceeded to the minister of the police.

On our first interview, from the distant manner in which he carried himself towards us,
I felt discouraged;
there being something in such a carriage that is humiliating to nature;
but as we are willing to suffer Divine grace to rise into dominion in our minds,
it raises us above the slights and scornful looks of man.
Endeavouring to keep to my own exercise,
the way opened for me to lay before him my motives in making this visit to Berlin;
to which he appeared to give agreeable attention,
allowing me an opportunity to express what came before me in the line of religious duty:
he then kindly conducted us to the door himself,
and parted from us in a very friendly manner.
We next waited on the commandant of the city, who received us courteously.

On my laying before him various occasions of immorality,
which were within his sphere and power to remedy, he united with me in my views,
and expressed his willingness to do his best towards their being remedied; but added,
that such were his difficulties in attempting any thing, that it was discouraging.
I felt as if I could give him full credit for what he said,
and could not but sympathize with him.
He said he hoped, when a suitable opportunity occurred,
to lay before the king the subjects I had mentioned to him.
These two visits being thus comfortably gone through, I enjoyed a peaceful quiet.
Whilst walking along, I was accosted by my friend the chief magistrate of the city,
saying, "`So you are about to make another visit to Spandau.
I would wish you not to go again.
Are you not afraid?--Don`'t you know some of the prisoners murdered the last governor?`"
Although I received his counsel as a mark of his kindness towards me,
I found it safest for me to say as little as possible in reply,
having heard of this circumstance since our last visit,
and that a bowl of scalding liquor had been thrown by one
of the prisoners into the present governor`'s face;
nevertheless this caution of the chief magistrate caused me, for a time,
to feel keenly on the occasion, and to consider there was not only my own life,
but that of my interpreter, the governor, and perhaps other attendants, at stake.
Nature was roused, and all within me capable of it became as an army set in battle array,
pleading to be excused from the attempt of a second visit to Spandau; but He,
who I was led to believe required this service of me, well knew my sincerity,
and the earnest desire that attended my mind,
if this service really was of his requiring, to be enabled to stand firmly to my post.
He mercifully condescended,
after he had suffered the discourager to assail me for a short season,
to raise up my head, in hope that strength would be given me in the needful time,
to proceed in this awful and important engagement before me;
and that neither hurting nor destroying should be
suffered to come upon me or any of my helpers therein.

This evening a messenger arrived with an order from the minister of justice,
+++[+++of which the following seems to be a rough translation:]

There is no hesitation that the institution for correction and improvement,
and all the prisoners, at Spandau, including those that are separated,
may be shown to the gentleman and the deputy^
footnote:[Probably meaning his interpreter.]
of the communion of Quakers in London, and be presented before him,
that he may converse with them; which the director has to mind.

Kirchein, Minister of Justice.

Berlin, 14th August, 1824.

To the Institution for Correction and Improvement.

This order being received,
I found it best to engage a carriage to take us to Spandau in the morning,
in order to return in good time in the evening,
when I proposed to sit with such individuals as were disposed to give me their company;
for which purpose our landlord furnished a large room;
and some serious persons had engaged to give suitable notice.
This step being taken,
I began to feel as if my work at Berlin was now nearly brought to a close.

It was difficult to have my mind divested of the circumstance
of the murder of the former governor at Spandau,
and the recollection of the alarm of the present governor,
on my former request to see them all together.
These considerations, I found, without great watchfulness,
were in danger of producing such agitation of mind as would be very unprofitable for me.
I had concluded, in the course of the night previous to our proceeding to Spandau,
to empty my pockets of my money, watch, pocket-book, and my penknife more particularly;
for, by having my penknife about me,
I might be the cause of furnishing them with the means of my own destruction:
this I accordingly did.
But on mature deliberation on the step I had thus taken, I was mercifully led to see,
that it was the effect of that departure from a full
and entire reliance on God`'s arm of power,
which the enemy was endeavouring to bring about in my mind.
I sensibly felt the performance of this very act had produced weakness,
causing the hands that had been made strong,
through the power of the mighty God of Jacob, rather to fall again.
I therefore returned to my chamber,
and replaced each of these articles as they were before,
taking particular care that my penknife was not left behind.

Early in the morning, Lewis Seebohm, also the young man who was our former companion,
and myself, left our hotel for Spandau: on our arrival there,
we were told our former visit had excited astonishment
in the minds of the people of the town,
that our love should be such as to induce us to leave
our families and cross the ocean to visit their land,
and that we should remember the poor prisoners of Spandau,
who seemed to be forgotten by every body.
After taking our breakfast, we went to the prison;
but the governor was not to be spoken with before ten o`'clock: however,
we met with our old friend the pastor of the prison, who received us kindly,
and conducted us to the chapel,
where we found about fifty young men prisoners receiving instruction,
which we were informed was closely attended to;
some of them appeared to have made considerable improvement in writing,
as we were told was also the case in their reading.
The quiet and order observed was pleasant to behold,
as well as the agreeable countenances many of them exhibited,
as if they rightly appreciated the privilege of being thus cared for.
Feeling something stirring in my mind towards them, my interpreter informed them thereof,
on which the pastor kindly requested such as were reading to cease.
What I had to communicate appeared to obtain attention.
At our parting, the pastor invited us to take our dinner with him,
but this we respectfully declined,
for my dinner now felt the most distant thing from my mind.
At the time proposed for us to see the governor, we returned to the prison.

On being introduced to him, I presented my fresh order from the minister of justice,
to visit the prisoners again: his countenance bespoke the effect it had on his mind,
as he showed himself uncomfortable and much agitated,
probably from two causes--the peremptory manner in which the order was couched,
and the fear prevailing in his mind of those,
whom he called the most desperate of the prisoners, being loose together in the yard.
For a time he appeared like a man recovering from a violent electric shock,
and then again stood like a petrified subject.
During this season of proving to the governor and my companions,
I trust I was not void of a proper feeling for him, and for them;
but I found I must maintain my post with firmness.
After the governor had a little recovered himself, he brought forward, as before,
many reasons to prevent my seeing the prisoners;
but as his excuses did not prove effectual, he next tried what he could do by persuasion,
saying, that from his knowledge of the disposition of some of the prisoners,
it would be dangerous to attempt to have them assembled as I wished.
No such apprehensions, however, prevailed with me, in whatever way I viewed the matter;
yet I humbly hope I may say,
I was not lost to a feeling of sympathy for those who were to accompany me,
and who did not see and feel the subject as I was enabled to do.

The governor seeing there was no other way, yielded to my request,
and ordered all the men prisoners to be assembled in the great yard of the prison.
On entering the yard where they were assembled,
I observed that the number assembled far exceeded
what I had met with in the chapel at my first visit,
there now appearing from three to four hundred prisoners:
many forbidding countenances I could not recollect to have seen before,
whose legs were loaded with irons, but not their hands.
Had they been disposed to injure us, I thought,
as I viewed those who were placed in front,
we should only be like so many grasshoppers amongst them.
Besides ourselves and the governor, we had the company of the head-officer of the town,
several military officers, and some of the inhabitants.
Our kind friend the pastor placed us on a flight of steps,
very suitable for the occasion, and the prisoners formed a circle in front of the steps.

After a pause, the governor addressed the prisoners:
although I could not understand a word which he expressed,
yet I had a clear evidence that his matter was appropriate to the occasion,
and that he was assisted by best help in doing it:
his observations produced a remarkable quiet over the whole assembly;
not the motion of a foot or clink of a fetter was to be heard.
This address of the governor seemed very much to open my way in the minds of the prisoners.

I cannot call to remembrance a time when I have found
a more open door to receive what was communicated,
than in this opportunity;
the countenances of many of the prisoners appeared sorrowfully affected,
and bathed in tears,
and the quiet solid manner in which they behaved during the whole of the meeting,
considering what a rough, uncultivated company they appeared to be,
was a striking proof of the sufficiency of the power of God, now as formerly,
to control and bring into subjection, the evil power in man; that thus he alone,
whose right it is to reign, may have the dominion.
Having been favoured with ability fully to relieve my mind towards them,
I found I must propose to give each of the prisoners my hand of love, before I left them,
and the governor arranged them for that purpose:
in this step I was led to believe the prisoners generally sympathized, for,
although they were not able to express themselves in my own language,
their countenances and their manner of pressing my hand,
I thought fully indicated this disposition of mind.^
footnote:[In a letter written from Berlin, to our dear friend, Thomas Shillitoe,
some years after this period,
his correspondent thus expresses himself:--"`I am sure your visit at Berlin,
and especially the attention you paid to the prisoners, has been of very great benefit.
Since that time,
there has been formed a society for instructing and amending the prisoners.
This very important branch of Christian charity has formerly been too much neglected.
The society has done much good already, and will do much more, if they keep a single eye,
and do all they do,
to glorify Christ.`"
{footnote-paragraph-split}
In
this and other letters written to Thomas Shillitoe,
from the continent, several from persons of rank, are often to be met with,
expressions of much warmth of feeling towards their much esteemed, aged visitor;
indicating how closely they became united in the bonds of Christian love to our Friend.
"`As often as I happened,`" says the above letter, written after his return from America,
"`to speak to Friends coming from England, I used to ask them,
I may say in some degree with the tender feelings of Joseph,
'`Does my father Shillitoe yet live?`'`"]

Having taken a farewell of the prisoners, we retired to the governor`'s apartment,
who seemed at a loss to know how to manifest his kindness sufficiently towards us.
The pastor not following us, I felt anxious to take leave of him;
but before we had finished the repast which the governor had kindly set before us,
the pastor joined us, informing us he had been detained with the prisoners,
who had requested him, in the name of the whole of them,
to express their thankfulness for the visit, and that many of them could say,
the words that had been delivered amongst them reached to their very hearts,
and they hoped, would, in a future day, produce good fruits.
May all the praise be given, where alone it is due, is the prayer of my soul!
We parted from the governor very affectionately,
and the pastor accompanying us to our hotel,
expressed the regret which he and others felt,
that our stay amongst them was of so short a duration.

We were informed, that a man of considerable account in the world,
was in the practice of asserting it to be his belief,
there was no such thing as people being actuated by the
love of God in their conduct towards each other.
Our first visit to Spandau excited much conversation amongst the town`'s-people,
our motive for making it being viewed by some, as proceeding purely from the love of God,
this man took up the subject in support of his own opinions;
in the course of his arguing,
he became so convinced that nothing short of the love of God to the poor
prisoners could have influenced us to leave our homes and families,
and endure the hardships by sea and land which we must have done,
that he acknowledged he must now abandon his former opinions on this subject.
I returned with my companions to Berlin,
thankful that my good Master had not suffered my manifold
discouragements to cause me to rebel against Him.

My great care now was, how I should get through the evening`'s work before me, viz:
holding a meeting with such individuals as were inclined to give us their company.
I fancied I could have been glad to be anywhere else rather than at this occasion,
notwithstanding I had so recently had cause to bow in reverent
acknowledgment to the mercy and goodness of the Lord,
in helping me through the last scene of trial.
Oh! how did my poor mind, in its reduced and stripped condition,
crave a willingness to become anything or nothing,
that so I might be found keeping my proper place amongst the people this evening.
I found, whilst the meeting was gathering,
a young man was preparing to take down in short-hand what might be communicated;
but I prevailed on him to desist.
The meeting gathered early, and soon quietly settled down:
the room was as full as it well could be: the people appeared serious and attentive,
and we understood they were well satisfied with the meeting.

Second-day morning, my prospect of being liberated from Berlin began to brighten;
the gates were now set open for my departure, which rejoiced my heart,
on account of my kind companion Lewis Seebohm.
I proceeded to the post-office,
and secured my place in the diligence to Hamburgh on fourth-day.

Third-day, my friend Lewis Seebohm left me for his own home.
I was now alone, no one in the hotel being able to understand me,
except at times by signs: this made it trying, when visitors came,
with whom I was deprived of the opportunity of an exchange of sentiment.
My mind having been frequently introduced into exercise,
on account of some pious persons who were about the court, I believed,
if the way clearly opened for it,
I must be willing to try to have them brought together in a meeting capacity:
but there appeared such insurmountable difficulties in the way,
that I gave up the prospect, and I had reason to believe properly so:
yet my exercise continued, and by endeavouring to keep patient under it,
the way in due time opened for my relief, by taking up my pen,
and committing to writing what arose in my mind, which was as follows:

To the seriously awakened minds, who are mourning, in the higher circles of life,
in Berlin.

Berlin, 16th of Eighth month, 1824.

The more exalted the situation of life we are by
Divine Providence permitted to be placed in,
the greater need there is for humility of heart;
a virtue that never appears more conspicuous than when it is really
to be found imprinted in the general tenour of the conduct and
converse of such as are travelling in the higher walks of life;
nor is its influence ever so likely to be productive of real good to others; because,
the more elevated our situation in life may be,
the more extensive will be the influence of our example,
whether it be good or whether it be evil.
I have therefore, in my solitary moments, earnestly craved,
that all who may be placed about the person of the king, and every branch of his family,
and others who may be placed in affluent situations in life,
whose lips may have been mercifully touched, as with a live coal from the holy altar,
may keep humble, little and low in their own estimation; for this is the way,
and the only way, for such to experience the Lord to teach them of his ways;
and by keeping in meekness and true fear before him, know him to direct their steps,
guiding them in the paths of true judgment,
causing such who thus love him to inherit substance.
The great must set an example of faithfulness to God,
and an entire dedication of heart to him and his cause,
before those who are moving along in more humble life;
it is these who must lead the way in the paths of holiness of life and conversation,
if the Lord`'s work goes forward and prospers in this land, as he designs it should;
and my soul craves it may.
And now, with the feelings of Gospel love and thankfulness,
for the kind reception of my feeble endeavours, and the assistance I have met with,
I take my last farewell of these amongst you.
I have made acquaintance with many, of whom I can say, they are as bone of my bone.

Thomas Shillitoe.

The above being put into the hands of a faithful, pious individual about the court,
for circulation amongst those to whom it was addressed, my services here closed.
