== Chapter XXVII.

Sixth-day, ninth month, 1824, I proceeded to Elsineur.
I do not know how to describe my state of mind at the present time more correctly,
than by saying,
that I felt like one of the porters employed in London to carry heavy burdens, who,
having finished his day`'s work, lays by his knot.
Being released for the present from the heavy load of exercise
I have had to endure since coming into the city,
I was favoured to reach Elsineur in the afternoon.
The prospect of embarking upon the great deep,
led me further to consider my motive for undertaking a voyage to Russia;
but there appeared no other way for me to come at true and substantial peace,
but quietly to subject my poor nerves to such perils as Divine
wisdom might see meet should attend me on my passage there.
I waited on my kind friend Charles Fenwick, the English consul,
with whom a letter was waiting for me from Daniel Wheeler,
giving me instructions how to proceed on my arrival at Cronstadt,
and conveying an invitation to his house, which was truly acceptable;
for I was sensible of the need there would be for me, when at Petersburgh,
to try to find a safe sheltering place, where I might be out of the way of much company,
and in an English family.
I informed the consul of my desire to take the first vessel for Cronstadt,
whenever he could recommend to me a suitable one;
but the wind was now contrary for a passage to Russia.
I was told the wind had been for some time favourable, but now it had tacked about,
I might be detained here some days.
I found, without great watchfulness,
and endeavouring through holy help to cast my care on that Divine Power,
who had in such a wonderful manner cared for me,
that I should become involved in so much anxiety and perplexity about getting forward,
as to rob me of that consolation, which, I had reason to believe,
the retrospect of my late religious movements was intended to afford me.

Seventh-day,
feeling my mind impressed with a sense of the necessity
of sending my papers and memorandums to England,
I lost no time in making up a packet for that purpose,
which I gave in charge to the consul to forward by post,
lest the wind should suddenly tack about again: my books I had disposed of,
except my Bible, in a way I was led to hope would be useful;
for I had a sense given me before I left Copenhagen,
that it would be unsafe for me to take more books with me to Russia than my Bible,
and that a jealous eye would be upon me when I arrived at Petersburgh.

About four o`'clock on first-day morning, I was called up, and informed that the vessel,
in which the consul wished me to go, was in sight.
I had to take a boat to get on board,
and was truly thankful when I was safe on the deck of the Henry, of Hull, Captain Meggat.
There being no passengers in the cabin, I had it to myself: sickness keeping off,
I passed the day comfortably.

Second-day, the wind was contrary,
which proved an exercise of patience to our ship`'s company.
I retired to bed, and got some sleep until near morning,
when I was awoke by a violent shouting, with great uproar on the deck,
as if all hands were in full motion to escape some danger,
and the vessel I sensibly felt had whirled round;
but I could feel nothing so proper for me as keeping quiet in my bed:
after awhile I found the vessel resumed her station again,
was under sail and all was quiet.
On inquiry next morning into the cause of this awful alarm,
the captain informed me that a foreign vessel under full sail,
instead of keeping her right course, had crossed our course near us;
the probable consequence of which was,
had not our captain used the precautions which he did,
that one or other of the vessels would have gone to the bottom.
This merciful escape produced feelings of gratitude in my mind for the care of Him,
who thus in mercy watches over us by night and by day,
and in times of danger prepares a way for our escape.

Third-day, the wind in our favour,
but the weather so foggy that our captain considered it dangerous
attempting to make much way through the Gulf of Finland,
the passage being narrow and the coast dangerous.
Night coming on, and our captain fearing a storm,
the necessary preparations were made against danger from it;
the forked lightning that appeared in the horizon was truly awful;
yet after all these trying circumstances,
I was favoured to retire to rest in full confidence that I should be watched over,
and cared for by that Divine Power,
to whom I found I could appeal for the sincerity of my motives,
in thus exposing myself upon this unstable element.

Fourth-day, the wind much in our favour;
about midnight we cast anchor abreast of the guard-ship, stationed in the channel.

Fifth-day, the regular officers came on board to take down our names,
and seal up our luggage; we proceeded again,
but were detained some time before we could enter the harbour of Cronstadt,
in consequence of some vessels having arrived from Lubeck,
which sailed about the time I should have taken shipping there; had I sailed,
as I was advised to do, from that port,
I should probably have been a passenger in one of them.
On my landing, I found the passengers, who came in these vessels from Lubeck,
were all of them involved in great distress,
their luggage being seized along with the vessels,
in consequence of their having large quantities of goods concealed on board,
for the purpose of smuggling them into Cronstadt.
On observing the great distress some of the passengers were involved in,
by their not being allowed to take from the vessel
anything more than the clothes they had on them,
I felt a fresh cause for thankfulness on my part,
and a further proof of the watchful care of Israel`'s Shepherd over me;
that this might be engraven on my heart as with the point of a diamond,
never to be effaced, was the earnest prayer of my soul.

After our vessel had made her way into port,
amidst the confusion these Lubeck vessels had occasioned,
we were visited by another set of officers;
the captain accompanied me on shore to the different offices to clear my luggage,
and procure my passport; on which occasion I met with civil treatment,
except from some inexperienced young men in the long-room,
one of whom took my hat from me and detained it for awhile.
Having procured my passport and cleared my luggage, accompanied by my kind captain,
I went on board the steamboat for Petersburgh:
here we also met with some of the passengers who came in the vessel from Lubeck,
whose situation appeared a pitiable one, especially some females,
as they had not been suffered to bring away with
them the least change of apparel of any kind.
My kind friend Samuel Stansfield was waiting on the quay to take charge of me,
a poor wanderer in a strange land as I felt myself; and he hired a droskey,
the carriage used here for hire, which took me to his store;
we then proceeded on foot to the house of my kind friend Daniel Wheeler,
who met me on the road, and, with his wife and family, gave me a kind reception.
I felt grateful to be once more in the company of members of our religious Society;
and nothing appeared to be wanting on their parts,
in endeavouring to make their house a comfortable abode for an Englishman.
This retreat out of the city felt to me very desirable,
concluding in my own mind I should escape many callers,
whom I might otherwise be exposed to the danger of meeting,
which at times I had been led to anticipate with a sort
of dread that proved distressing to my feelings;
for I was aware of my open communicative disposition,
and I knew not how far I might at unawares be drawn into conversation,
and thereby be brought into difficulty.
But, alas! before the day closed,
I was made sensible that this quiet abode was not to be my resting-place,
during my tarriance on this part of the Lord`'s footstool;
but I must be willing to submit to take up my residence in the centre of the city;
under the assurance, that if I kept humble and simple in all my movements,
Divine mercy would so watch over me, that I should not be harmed.
The prospect of being obliged to quit this quiet, and, as I viewed it,
sheltered situation, caused me sadness of heart for a short time; but,
after some sleepless nights,
seeing no way for me to secure Divine protection but by yielding,
I informed my kind friend Daniel Wheeler how I was circumstanced in this respect,
and requested him to inquire after several lodgings
in English families in the centre of the city,
that I might have choice of the one which best accorded
with what to me appeared to be Divine direction.

Sixth-day, I much enjoyed my quiet retreat out of the bustle there was in the city,
and to breathe the clear fresh air of the country.

Seventh-day, I went to Petersburgh in search of lodgings; made calls at several places;
and, as far as respected the accommodation for my poor body,
nothing was wanting but the sanction of my Divine Master,
whom I had most earnestly supplicated to direct me
in the choice of my temporary abode in this city;
this was wanting, which with me was the principal thing to look to.
A family was mentioned to me by my friend Daniel Wheeler, but on inquiry,
it appeared they were not in the practice of taking in boarders.
My mind, on first hearing of these lodgings, felt perfectly at liberty to accept of them,
if I could have them; but this I found was a very doubtful matter.
I requested to be taken to them,
that I might try if way could be made for my accommodation:
the owners of the house received me kindly, and on taking my seat in their apartment,
such were the feelings of my mind that it was pronounced home to me.
On my request being made known to the family,
I was informed I could not be accommodated with two rooms,
which I might have had at the other places I had seen,
and that it would take a day to prepare the one they were willing to spare me;
for this offer of one room I felt truly thankful,
being persuaded in my own mind it was the right place for me to pitch my tent;
I therefore agreed to accept it.

First-day, we held our meetings at Daniel Wheeler`'s, in all about twelve in number;
it rarely occurs that any of the inhabitants give their company,
although it is known in the city that such meetings are held on first-day morning,
first-day afternoon, and fifth-days.

Second-day, I took possession of my new apartment;
from the kind manner I was received by my hostess,
a cheering hope was raised in my mind that I should
find myself much at home under their roof;
and I resolved to put up with every inconvenience as to the body,
rather than by seeking ease this way,
to expose myself to dangers which might subject me
to sufferings both of body and of mind;
for I often felt myself placed as on a pinnacle, which called for my watching well,
not only all my words and actions,
but my looks and appearance as I passed along the streets;
the truth of which soon manifested itself.

Third-day, 21st of ninth month,
having apprehended it to be required of me to make records, from day to day,
of the wonderful manner the Lord my God was leading me about,
instructing and confirming me in the never-failing all-sufficiency of his power,
to effect for man all things essential to his salvation, I was much tried in my mind,
after leaving Copenhagen, to arrange for continuing the practice,
when I reached the Russian territories, in such a way,
that should I come under difficulty, and my papers be seized,
they might not prove a means of involving me in greater difficulty.
I spent the afternoon at Ockter, about seven English miles from the city,
the residence of George Edmunds, one of the English Friends.

People began to manifest an anxiety to know my inducement, at the approach of winter,
for coming to Petersburgh; on my examination at Cronstadt,
before the admiral appointed for that purpose,
relative to my motives for going to Petersburgh,
I could not say I was come to purchase their hemp, tallow, etc.,
and they could not suppose that to see my friends merely could have been my motive;
and I found it was not in my power to advance any other reason, not being able to see,
as yet, any line of religious service laid out for me: I therefore was led to crave,
that through the superintending care of Israel`'s Shepherd,
I might be preserved "`by the word of Truth,--by the power of God,--by
the armour of righteousness on the right hand and on the left;
through honour and dishonour,
through evil report and good report;`" being considered "`as a deceiver, and yet true.`"
With this desire closed a day of deep inward exercise.

Seventh-day, my mind was tried at the prospect of spending a long,
dreary winter in this severely cold climate,
without at present any clear view of good arising from it, either to myself or others;
but believing that quiet submission to this and every requiring of my Divine Master,
was my proper province, I laboured after it.

First-day, I walked out of town to meeting: with gratitude we had cause to acknowledge,
that Divine aid was near, uniting us together in labouring after a portion of that bread,
which alone is able to nourish up the soul unto eternal life.

Third-day, the weather being very gloomy, I concluded to pass my time at home;
but I found my health required I should devote my usual time to walking,
which I did with reluctance.
On my way home I met four companies of prisoners under a military guard,
some for depredations, others for strolling from the estate of their baron,
and others for not being able to produce a passport;
they were on their way to the police-office for examination.
I looked at them with feelings of pity,
considering it was all of Divine mercy that I was not suffered to be one amongst them.

Fourth-day, accompanied by my kind friend, Samuel Stansfield,
I went to the custom-house about my luggage: our keeping on our hats excited notice;
my luggage was examined, but not before the question was put to me, had I any books.
I had been informed, since my coming to Petersburgh,
that no English books on religious subjects were suffered to be brought into the country;
this made me thankful that I yielded to the intimation in my own mind,
either to part with my books in Denmark, or return them to my friends in England.
I was therefore able to say, no; but before my luggage was opened,
it occurred to me that I had a small poetical work in the German language,
the gift of a friend at Altona; therefore I had the officer informed to that effect;
the book was taken in charge, until I had signed a notification,
engaging me to present it to the censor for his inspection.

Samuel Stansfield being about to return to England,
it felt trying to me to be left in the city alone,
a stranger to the language and manners, and not knowing how to market for myself;
as I was not permitted to remain at my kind friend Daniel Wheeler`'s to winter,
and as I was so far removed from my friends in England,
I found it hard work at all times to keep in that entire submission,
in which I could adopt the language, "`Not my will, but thine be done, O Lord.`"

Fifth-day, walked out to Volkova; and attended the usual meeting.
The days being very short, I walked home to tea;
passed the remainder of the day in reading, and reflecting on my solitary situation,
accompanied with desires that I might be preserved, labouring after becoming gratitude,
that a kind Providence had put it in my power to procure
all the outward comforts I stood in need of,--food,
warm clothing, and things suitable to the climate, in which I was to winter.

Sixth-day, 1st of tenth month.
During my walk this morning,
I was favoured with a humbling sense of being in my proper allotment;
which enabled me to make sweet melody in my heart to the Lord,
and to crave the continuation of his Divine counsel and help,
to keep my proper place amongst the people, whose eyes might be upon me,
watching my actions and ways more than I was aware
of. But this rejoicing was not of long duration;
the enemy of all good found other work for me, by suggesting to my mind this query,
what good was likely to result from the labour and toil I had passed through,
and the expense which my coming to Russia had occasioned.
No way, however, being open for me to spend my time otherwise than I was then doing,
after having endured much conflict as the result of these suggestions,
I was favoured again to experience a good degree of quietude of mind;
and I had in the vision of light,
a glimmering prospect of duty to make visits to the emperor,
who was now absent from the city on his travels.

Whilst under the exercise of this humiliating prospect,
I thought if the way should open for the full accomplishment of these visits,
and if my example, in leaving all and coming, in the love of the Gospel, to this country,
had a tendency to convince and confirm the judgment of only a solitary individual,
of the efficacious working of this love of God on the mind of man,
when fully cooperated with, it would be enough.
As the judgment becomes awakened,
and a willingness is brought about to bow to the holy influence of this love,
on the part of the awakened mind,
fruits corresponding with its Divine nature will in due time manifest themselves;
and the example of such, like leaven,
may prove the means of leavening others into the
like spirit and holy disposition of mind.
I received an account from my own home that my family were well;
which I hope I numbered amongst the manifold blessings,
my heavenly Father has showered down upon me, during my painful pilgrimage in this land.

Seventh-day, the weather inviting, I commenced my usual walking:
I rambled until I unexpectedly found myself in the summer
gardens in front of the palace of Peter the Great:
I made a halt to take a survey of this humble edifice,
which produced in my mind this conclusion, respecting the founder of it;
that amongst the vices this great monarch had to contend with, he had not given proof,
that temptation to splendour, was his besetting sin.
I returned home, weary in body, but thankful I was made willing to be gazed at;
for by this time I began to attract considerable attention as a foreigner,
and one called a Quaker;
for I apprehended it to be required of me to choose
the most public places for my daily walks.
My breathing was to Him,
who only could strengthen me patiently to yield to every dispensation,
which he may permit me to be tried with; and thus, I trust,
all things will eventually work together for good, even these humiliating seasons,
in which we become a gazing-stock and wonder,
because we cannot bow to the god of fashion, so much worshipped,
and cringe to the Hamans we at times fall in the way of.

Third-day, took my usual walk.
Oh, the superstition that abounds in this city!
How is obeisance to crosses and pictures,
substituted for that repentance and amendment of life, which God looks for!
A heavy load of condemnation, I fear, will rest on the Greek clergy on this account;
not willing to enter the kingdom themselves, through Christ the door,
they are not promoting it amongst those they call their flock.

Fourth-day, I commenced my morning`'s walk; but by pursuing it too long,
I found myself so weary as to unfit me to sit down to read to much profit;
afresh reminding me of the language of the preacher: "`to everything there is a season,
and a time to every purpose under heaven.`"
May I so aim to come at the knowledge of this right time and season,
and regulate all my movements by it, as to escape that hurry and perturbation of mind,
which is the consequence of our movements, in civil or religious matters,
not being rightly regulated and timed.
My afternoon`'s walk I endeavoured to moderate.
On my way home I was met by one of my countrymen,
who has taken a kind part in endeavouring to better the state of the prisons,
and the condition of the prisoners,
who was on his way to make his usual visit to these abodes of human misery,
and who kindly invited me to accompany him there.
I was not a little tried on the occasion, feeling myself under the necessity,
as heretofore, of refusing his kind offer,
as my time for such visits did not appear to be fully come.
I returned home, well satisfied that my friend`'s importunity to go with him,
did not prevail.
Oh, the need I feel, and in a particular manner since my feet have been set in this city,
to know every inch of ground I am to travel on measured,
before one step is taken in the line of apprehended duty.

Sixth-day, the weather rainy, yet I took my morning`'s walk.
I begin to get bolder in venturing about the city alone,
having by this time obtained the knowledge of several way-marks,
which rise above the tops of the houses, to steer my course home by; otherwise, I find,
I should frequently be brought under difficulty,
for want of a knowledge of the Russian language:
although at times the want of this knowledge places me in a trying situation,
yet I often am led to appreciate my ignorance in this respect,
because I hereby escape the danger of being drawn into conversation,
on things that do not concern me,
nor comport with the sacred errand upon which I profess to be come from home.

Seventh-day, the weather wet and gloomy; my mind partook of gloom also,
on looking at the solitary situation, in which I am very soon to be lefl:,
by the departure of Samuel Stansfield:
but endeavouring after patience and confidence in Him, who was my morning light,
the assurance was again vouchsafed, that if I maintained my integrity,
by being faithful in all things, I should be cared for to the end,
and safely conducted to my family again.

First-day, walked out of town to meeting: in both meetings,
silence was the word of command given me:
what a mercy to be able to understand the Master`'s voice, when to speak,
and when to keep silence.

Third-day, the wind last night was very tempestuous, whilst I lay comfortably on my bed:
I considered it a favour, when I heard it blow a hurricane,
that I was not on the wide ocean.
Thus should our inward exercises be great,
and our outward condition and deprivations such as are not equalled by many,
as we may think, if our minds are but centered on the sure foundation, Jesus Christ,
the same today as yesterday, able to deliver to the very utmost,
we shall often feel the need there is to endeavour to cherish a thankful disposition,
that our situation is not so trying as it might have been;
and thus be enabled to bless the Lord for his past favours, and humbly hope for more.
During my afternoon`'s ramble,
ruminating on the seemingly useless manner in which I am spending my time,
Satan ceased not to bestow great labour and pains
to promote a disposition in me to condemn myself;
but in adorable mercy, he was not permitted to effect his purposes; for,
with respect to my not being engaged in much religious service at present,
whilst the cloud rests on the tabernacle,
it must be unsafe for me to go forth of my tent.

Fourth-day, the ground is covered with snow:
this sample of the approach of winter looks trying to my nature,
considering the inclemency of the season here, when compared with that in my native land.

Fifth-day, accompanied by my kind friend Samuel Stansfield, I walked out to meeting,
which to me proved a time of deep inward conflict of mind.
I do not record this in a spirit of complaining,
being well assured these seasons of inward desertion
are in great mercy permitted by that Almighty Power,
who deals with us, as a wise parent deals with the child,
whose future well-doing he has most at heart;
not always dandling his tender charge on his knee,
but letting him feel his feet on the ground which he is to tread upon.

Sixth-day, during my ramble this morning, I came to a Greek chapel,
at the door of which stood a burial-car, the body being in the chapel;
when the body came out,
I paused and viewed the procession as it moved on to the place of interment;
which awakened in my mind this deeply affecting consideration,
that no more sacrifice for sin can now be made, as it respects the poor individual,
whose mortal remains are about to be committed to its mother earth:
this consideration was accompanied by fervent cries to the Lord for strength,
to witness my day`'s work to keep pace with the day;
that when the same awful period approaches me, the work of salvation may be finished.

Seventh-day, the day being inviting, I enjoyed my walk in the afternoon.
I received a visit from a young man,
whose mind appeared awakened to a sense of good impressions;
but my way felt very much closed up,
so that I did not feel at liberty to enter freely
into conversation with him on religious subjects,
and therefore turned the conversation to the state of agriculture in Russia.
Before he left me,
he informed me he had been a close follower of the
person who was introduced to me in Altona,
who had been banished this country, because of his religious opinions:
it was the same person respecting whom my mind was at that time impressed with a caution,
to avoid all conversation with him relative to his conduct here,
and the conduct of this government towards him.
The young man informed me, there were many in Petersburgh,
who still adhered to this man`'s religious opinions.
I felt thankful, when I came to hear of these things, that I had been on my guard,
and had not entered into much religious conversation with him;
which might have proved one of the snares of the evil fowler.

First-day, walked out to meeting;
at the close of which their three months`' meeting was held,
in which the queries were read and considered.

Second-day, the frost was so severe that I was obliged to cut my walk short,
and remain at home the rest of the day reading,
having a supply of books from Friends here.
How ought we to appreciate our privilege, who have received an education, to be able,
through Divine help, to comprehend the various subjects,
laid before us through the instrumentality of the Scriptures,
which are able to make wise unto salvation through faith, which is in Christ Jesus.

Fourth-day, much of my time is occupied in reading and walking:
this appears to me to be my great Master`'s will at present respecting me,
to which my mind has at times become reconciled, considering that my appearance,
in parading the most public walks in the city,
where many of the people spend much of their time, excites notice.
As I feel it a duty for me so to do,
and am generally known to be one of those called Quakers,
it is impossible for me to say how far some may be excited from curiosity,
to wish to search into our religious principles and practices,
and what may prove the result of such inquiry.
But after all, it appears to be enough for me to know,
I am called upon to make myself thus conspicuous.

Fifth-day, walked out of town to meeting; in addition to our own little company,
we had the company of a Frenchman and a German.
A lively interest was, I believe, excited in some of our minds on their account,
that they might be favoured to know Jerusalem to be a quiet habitation;
which we could not doubt they were desirous of aiming at.

First-day, walked out to meeting,
accompanied for the last time by my kind friend Samuel Stansfield.

Third-day, after being favoured with a comfortable night`'s rest,
and refreshed by a bountiful breakfast, for both of which blessings,
I humbly hope I may say, feelings of gratitude were my theme,
I pursued my morning`'s walk towards the Neva,
where the ice was coming down in large masses from the lake;
on this account great preparations were making to be able, at a short notice,
to remove the bridge of boats that were near the admiralty:
this occasions a great interruption to the foot passengers and carriages,
and much confusion to those who had business to transact
at the custom-house and other public offices on the island.
The evening was a time of general illumination,
but here it is not an act of the people individually, but a government concern,
and performed by placing rows of lamps on the edge of the foot-paths:
all was conducted with quiet.

As I was not giving proof that I came to this country to trade with the inhabitants,
great jealousy was excited in the minds of some in authority respecting me; amongst whom,
as I was credibly informed, reports were in circulation,
that I had been travelling all over the continent,
and giving away a great deal of money wherever I came,
and that my motives for so doing must be, to bring the people over to myself,
in order to excite rebellion.
When this report reached my ears, through a well-wishing Friend,
who received this information from a person very active in the government,
it may well be supposed it awakened in my mind some painful considerations;
more especially having heard of a recent circumstance of one of my countrymen
being ordered out of his bed in the dead of the night into a carriage,
and hurried away to the frontiers, without any previous notice of the cause:
yet I was somewhat prepared to meet reports of jealousy being excited
in the minds of the authorities respecting me,
from the painful feelings of my own mind in this respect;
which caused me to be very careful to give no ground on my part for suspicion,
that my motives for coming to Petersburgh, were any other than they were.
I therefore carefully avoided at all times,
except I could give ample proof that I had business,
setting a foot in any of their establishments;
I confined my walks to places of common resort, and then kept straight forward, avoiding,
as much as I could, any intercourse with strangers;
and when I was accosted in the streets by such, I gave them a short civil answer,
and left them, pursuing my walk again;
for I thought I clearly saw herein only I was safe.

Fourth-day, after a sleepless night, I turned out to take my morning`'s walk,
but the frost had disappeared:
the damp state of the air affected my breathing to that degree,
that I found exercise out of doors oppressive.
During my short morning`'s ramble,
feeling a precious benefit to result from a daily care over the mind,
that I might be enabled, with the Psalmist, to say, "`Bless the Lord, O my soul,
and forget not all his benefits,`" I had to recur to the
exercise of mind I was frequently introduced into,
whilst on my passage from Elsineur, when looking to my becoming a resident here,
accompanied with earnest breathings to the Lord my God, that he would be pleased,
if the way did not open for me to become an inmate
in the family of any of the Friends here,
that he would provide for me a safe, quiet abode;
and I was led to admire his condescension in answering
my prayers in the manner he has done:
the petition was raised in me for the continuation of his watchful care over me,
whose ear is ever open to such an innumerable company of petitioners,
supplying all their manifold wants at one and the same time.
Well indeed exclaimed the Psalmist,
"`his greatness is unsearchable,`" and he is "`greatly to be praised;`" and well
also might the inspired prophet break forth in the descriptive language,
"`Wonderful, Counsellor, the Mighty God, the Everlasting Father, the Prince of Peace!`"

During my walk this afternoon,
I called at the warehouse lately occupied by Samuel Stansfield; on entering it,
a young Englishman, an attendant there, pointing to a person standing at a counter,
remarked, "`That is a Russian nobleman, who speaks English well;
he has been making various inquiries respecting you,
and has expressed a desire to make your acquaintance.`"
I therefore offered him my hand, which he received;
on which he endeavoured to draw me out into conversation,
manifesting an eager disposition to investigate narrowly my motives,
for coming to Russia at this inclement season of the year.
Not being able to make out anything to answer his
evil purpose of ensnaring me in my words,
he next queried with me, could I give him any books.
I was made thankful I had so attended to the intimation in my own mind,
before I left Denmark, to dispose of them all there, that I could therefore say in truth,
that I brought no English books with me to Russia; on which he left me,
never after manifesting any disposition, when we met in the street,
to make my acquaintance any further; but passed me from time to time.
This escape out of the hands of such a designing man,
I considered I was in duty bound to add to the long
list of proofs that Divine mercy has followed me:
a prohibition being made against books being brought into the country,
this request for them was a trap laid for me, as I was afterwards informed,
had I been able to answer his demands: similar attacks I met with in my walks;
but by following the caution given me in my own mind, of making a concise,
civil reply to the questions put to me, and speedily leaving the parties again,
I escaped their snares.

Fifth-day, walked out to meeting; the road was so deep in mud,
as to make it laborious getting along.
I took my tea with a family,
the mistress of which had been educated in our religious Society,
but who married out from amongst Friends;
she retained the marks of a woman of orderly conduct,
which I have found mostly continues to be the case with such;
at least as far as the term orderly conduct comports
with the ideas which the world attaches to it,
however widely they may depart from that distinguishing
badge of simplicity in their outward garb,
which the consistent members of our religious Society
feel themselves constrained to observe.

First-day morning, from a restless night, and the weather proving rainy to an extreme,
a disposition to stay at home I found was gaining upon me, which I felt fully satisfied,
if I gave way to, peace of mind would not result from it:
I therefore resolved to try and do my best, and went to our meeting for worship.
Our little gathering was owned by the good Master`'s presence,
which the rightly-exercised mind will be constrained to acknowledge is enough,
and will not feel anxious about instrumental help.

Second-day, 1st of eleventh month,
my mind has again been brought under exercise on
account of the English residents in this nation,
accompanied with desires that we may in all things
be found setting a good example to the native inhabitants.
I apprehend, before I am clear of the city,
the way will open for me to cast off my exercise on their account.
During my ramble this morning, my solitary situation much occupied my thoughts;
and such discouraging prospects presented themselves to my mind,
on taking a view of my remote distance from my family and friends in England,
that I became almost overwhelmed in the contemplation of them;
but Divine mercy condescended to renew to my mind the assurance,
that if on my part I steadily maintained my integrity,
He would not fail to care for me every day and every way:
this afresh animated me to renew my covenant, and to say, if, like the apostle,
I am but favoured to finish my course with joy, I am willing to follow thee,
my Divine Master, whithersoever thou mayest be pleased to lead me, even into prison,
or unto death, so that thy good presence does but go with me.

Third-day, after breakfast and reading,
I rambled round the outside of the gardens and palace built by the Prince Potemkin,
a favourite of the Empress Catharine, and afterwards to the monastery.
The weather was clear and inviting, and my mind being busily occupied,
I exceeded so much my usual time in my ramble, that when I reached home,
that which might have afforded relief to the body, tended to oppress it.
Passing by one of the canals, at the time when the labourers on board the barges,
which convey the rubbish from the city, were about taking their dinner,
which consisted of black bread and salt, with either a poor drink they call quash,
or water, I was forcibly struck, and somewhat reproved,
by observing the uniform care they manifested,
to fix their attention on a cross placed on the top of one of their places of worship,
and devoutly asking a blessing on what we should consider a very miserable meal,
before they attempted to taste it.
The like care I have observed was manifested after they finished their meal,
returning thanks for it,
before they took a tool in their hand again to resume their labour.
Although there may be reason to fear, with many of them, this, their devotion,
is performed in the oldness of the letter,
and not in the renewings of the Spirit on their minds; yet watching them,
as at times I have done, I have not dared to doubt, that in this act,
sincerity was the governing principle, in the minds of some of this poor,
degraded part of my fellow creatures.

Fourth-day, took my usual walk: retired early to bed; had a very restless night,
through exercise of mind with doubts and fears, which Satan brought before my view.
Towards morning I went to sleep, and dreamed I beheld a mountain on my right hand,
whose top extended into the clouds, out of my sight;
on the side of this mountain I observed a path, as if formed without the labour of man,
very rough and rugged,
and barely affording room for the feet of one traveller to go on it at a time.
Abutting against the foot of the mountain, but considerably below this narrow path,
was a broad, level gravel-path, very smooth and pleasant to look upon;
at the entrance of this broad, level gravel-path, I perceived a vast cavity below,
as if the foundation on which this path stood was not sound, and had given way,
and let those who had been venturing on it into the cavity below.
I was told I must take the narrow path, which I accordingly did.
I then thought I heard a voice,
as clearly and intelligibly as ever I heard a voice with my outward ears, saying to me,
"`This narrow path thou must continue to keep upon,
although it will not allow of thy having a companion,
to share with thee in the sufferings that will await thee,
whilst travelling on this rough and rugged narrow way.`"
I observed there were great stones,
standing up in places in the very track the feet must go.
I was assured, if I observed great circumspection and watchfulness day by day,
no harm would be suffered to befall me;
but without this circumspection and watchfulness,
there would be a danger of my dashing my feet against these stones,
which I saw standing up in the path,
and of being thereby precipitated into the vast cavity below me;
and then it would fare with me as it had done with
travellers on the same narrow path before me,
who, by growing weary, of the difficulties they had to encounter in their journey,
and through a desire to make trial of the broad, smooth, level path,
became indifferent and careless how they moved along,
and in time were precipitated into the vortex below.
I felt constrained, although with fear and trembling, to venture as far as I durst,
to see its immense depth;
and I observed at the bottom a body of water in continual motion, like a whirlpool;
the sight of this, and the manner in which I was warned of my danger,
unless I maintained my daily watch, made such an awful impression on my mind,
that for days afterwards it continued to be the subject uppermost with me;
I could not but view my dream as very significant
of the path I have hitherto had to tread,
and which I am led to believe I shall have to tread whilst I remain in this city,
if I escape the hands of the police, who I understand consider me a dangerous person;
and that it is designed as an intimation in mercy for my future government,
and to confirm me yet more in the necessity of having my mind stayed on God,
and only on him, in all my steppings, without letting in discouragement.
My situation may be said to resemble the owl in the desert,
the pelican in the wilderness, and the sparrow alone on the house-top;
for I passed days and days, and hardly exchanged a word with any one,
except when I went out to meeting,
or asked the family I was residing with for my common necessaries;
for the way did not open in my own mind to hold converse much with them on other subjects.
Why it is so with me, I have no right to query;
my Divine Master knows there is cause for it,
or he would not lay me under this restraint.
I have no companion here whom I can feel at liberty to call upon for help,
should I need it,
assured as I am my motions are all as narrowly watched as they well can be; besides,
should I be brought into difficulty through any stratagems
of those who are watching over me with such an eye of jealousy,
my friends might be brought into difficulty also;
so that I find my solitary situation a matter of absolute necessity on my part,
and I endeavour quietly to yield thereto, trying, as at times it is, to the flesh.

Fifth-day, walked out to my dear friend Daniel Wheeler`'s; attended meeting:
we were favoured with a quiet, comfortable sitting together.
On my way home, my kind friend, John Venning, took me to the Lancasterian school:
a pleasing hope may be entertained,
that through this and other such means going forward in this city,
the work of reformation is making progress.

Seventh-day, rambled up and down the Newskoi Prospekt,
a place of the greatest resort for the gentry in the city: it exceeds a mile in length.
During this walk, my mind felt so sweetly centered in God,
that the great bustle of people, carriages, and business that was going forward,
were not suffered to interrupt that view given me of the character of our potent enemy:
Satan is described by our Lord, John 8:44, as being a murderer from the beginning,
a father of lies; to the truth of which I could set my seal, craving,
as I have done this day, to be preserved,
aiming continually at the character of the perfect and upright man, eschewing evil;
if but, as it were, a grain of faith is at times dispensed to me,
may I be found so faithfully occupying with it,
as to know it to become efficacious to my escaping
all the snares of this great enemy of good.

Another week closed with the language of, "`Return unto thy rest, O my soul,
for the Lord hath dealt bountifully with thee.`"
First-day, I walked out to meeting; in both the morning and afternoon meeting,
fresh cause was experienced to acknowledge,
that the promise to the two or three had been in mercy fulfilled.
I returned home, and spent the evening quite alone; near my time of going to bed,
one of my countrymen came to propose calling upon me on the morrow,
and introducing me to the Prince Alexander Galitzin.

Second-day morning, visited the Prince Alexander Galitzin,
who received me in an affable manner; being obliged to converse through an interpreter,
was a take-off from my enjoyment, yet I felt well satisfied with my visit.

First-day, walked out to meeting, which proved a time of renewal of strength;
for which favour I returned home well rewarded for the exertion my walk had occasioned.
I passed the evening as usual alone, and retired to bed at eight o`'clock,
according to my accustomed practice.

Third-day, was passed in reading and walking: I returned home cold and fatigued,
yet under a humbling sense of the favour, that I had a comfortable room,
good supper and bed to return to; my cup overflowed with gratitude to Him,
who had thus bountifully given me all things richly to enjoy:
may the exercise of my mind continue to be, "`Search me, Lord, try me and know my ways,
prove me and know my thoughts, and if iniquity lodge in me,
make use of such ways and means as thou seest meet, thoroughly to purge me from it,
and keep me in the lowly valley of humility, and in the entire nothingness of self;
that so all I am and all I may be through thy Divine help,
may be to thy honour:`" thus closed another day peacefully.

Fourth-day morning, a variety of concurring circumstances which occupied my mind,
impeded my night`'s rest: may these waking hours in the night season,
which so frequently fall to my lot, be profitably passed, is what I earnestly crave.
On my turning out the next morning to take my usual exercise,
I felt discouraged from having to contend with a severe frosty wind, which,
in this northern clime, is very keenly felt by foreigners;
a sample of what I may expect to have to bear, which led me to sigh and cry for strength,
to be able patiently to endure every difficulty, which,
in the ordering of Divine Providence,
may be my portion during my stay on this side the great deep; then I believe,
if I am favoured to know a daily abiding in patience,
that cause for thankfulness will in the end be the clothing of my mind,
that a willingness was brought about in me to spend the winter in this cold,
dreary climate.
During my ramble, today,
my attention was much occupied in viewing the awful situation of Uzzah; who, unbidden,
put forth his hand to the tottering ark,
and what was the dreadful result of his presumption:
I endeavoured quietly to dwell under the impressions this subject produced on my mind,
in my present trying situation.
Being variously exercised, without a prospect of way opening for my relief,
earnest were my petitions to my Almighty Helper,
that I might be preserved in quiet submission to every dispensation of his wisdom,
until the word of command for my relief was clearly and distinctly heard to go forth.

Fifth-day, I walked out to meeting:
our little company was owned by the Master of all rightly-gathered assemblies;
for which favour, I believe it may be said, thankfulness filled our hearts.

Sixth-day, after breakfast and reading,
I turned out to take my usual ramble under great depression of mind;
but Divine goodness was very merciful to me, and gave me to see, that,
although not much visible actual service had yet fallen to my lot,
Petersburgh was my proper place of abode for the present;
and that I had no cause to be anxious about anything,
save to be preserved keeping my proper place amongst the people;
watching well my words and actions,
keeping in the lamb-like disposition of mind towards all.
O what confidence towards God, this doing our very best before him,
and being found walking circumspectly before all men,
gives us in times of close besetment from within,
and under the various trials we have to pass through from things without!
Amongst the things without,
I find it hard work to be obliged to refuse the kind importunities
of different persons in the city to take my dinner with them;
but I still continue to see with clearness,
that if I am favoured to know all kept quiet within, I must take up the cross in this,
as well as in every other respect, and content myself with my simple fare at home.

First-day, I walked out to meeting, and returned home in the evening, which, as usual,
I passed quietly alone.

Second-day, pursued my usual exercise;
during which a degree of anxiety was excited in my mind,
as to the mode of my returning to England;
but being made sensible it was not a subject for
me as yet to suffer my mind to be taken up with,
I besought the Lord for patience,
until the way for my return opened more clearly on my mind,
than is the case at the present time.

Third-day, after a sleepless night, I turned out to take my usual ramble;
but nature was so feeble, and I was so disposed to totter as I passed along the streets,
from the warm, damp state of the air,
that I was obliged to cut my morning`'s walk very short; I returned home,
and commenced reading in the prophet Hosea; and, if my feelings are correct,
relative to the state of mind of the generality of the people in this great city,
he sets it forth clearly in a very few words.
"`There is no truth, nor mercy, nor knowledge of God in the land; by swearing, and lying,
and killing, and stealing, and committing adultery, they break out,
and blood toucheth blood.`"

Fourth-day, I turned out to take my usual exercise;
but I was soon obliged to retreat from the place I had first aimed at,
on account of the great bustle in the neighbourhood of the palace,
the worthy emperor having arrived the preceding evening after a long absence.

Fifth-day, I walked out to meeting;
the subject of my getting to my own home attacked me again,
but it was soon put to silence, as I became earnestly desirous to be kept in patience,
until the time of my stay here was fully accomplished; to be so helped,
I hope I esteemed a favour, when I consider what a bundle of impatience I am by nature.

By accounts received today, a body of ice had floated from the south coast,
and collected at the mouth of the Mole,
which rendered it needful to cut it away for vessels to go out to sea; this circumstance,
I understand, threatens the approach of more severe weather than I have yet experienced.
