== Chapter XXVIII.

Sixth-day, 19th of eleventh month, 1824, but little sleep last night,
from the most severe tempest of wind and some rain, which I ever remember.
I little expected what an awful scene this city,
in a few hours after I left my bed this morning, would exhibit.
On entering the apartment of my hostess to request my breakfast to be sent into my room,
she asked if there had been much rain in the night,
as there was much water in the street; not supposing,
as afterwards proved to be the case, that this water floated up the common sewers,
from the swell of water in the river.
After taking my breakfast, I proceeded to take my usual walk; but, to my surprise,
I found we were so surrounded by water that I was obliged to return home.
On telling my landlady that we lived in an island, she smiled at me,
not aware of the fearful consequences that very soon followed.
Observing the servant of an English-woman, who lived under the same roof,
unable to reach home in her return from marketing,
I proceeded to go and inform her mistress of her situation,
and crossed the yard to her apartment dry-shod:
although not five minutes had elapsed before I attempted to return home,
everything was floating in the yard.
I stepped on a cellar-window, and from that into the door of a bake-house,
where the water followed me in such a body,
that I concluded no time must be lost in making my way home: I waded through it,
and had I hesitated many minutes longer, the rise of the water was so rapid,
I could not have reached my home.
A hole was afterwards obliged to be cut in the wall of the same bake-house,
to save the life of a woman who had taken shelter there.
After I left it, getting quit of my wet clothes,
I took my standing at the windows of our apartment:
the streets very soon exhibited a scene of great distress;
men wading up to their arm-pits in the water; one woman up to her neck:
I watched her with no little anxiety,
expecting to see her slip off the foot-path on to the road,
where it would have been over her head.
Horses and carriages were swimming in the streets, until they durst not venture forward,
the passing being altogether dangerous.
The water in a short time rose in the streets eight feet; and then to twelve feet.
The ground-floor of the house in which I was a resident, was occupied by a grocer;
the water rose up to the ceiling of the shop and his other apartments,
without allowing him time to move his goods or household stuff,
its progress was so sudden and rapid.
Until the water had reached its height, its advance was truly awful:
it was to be seen hastening up the sides of the houses,
first reaching the bottom of the window, then the top of one pane of glass,
and so on until both doors and windows were quite out of sight.
My landlady seemed to have no other expectation,
but that it would cover the tops of the houses, and we should all perish.

About eleven o`'clock the flood reached its height;
from that time until about four o`'clock in the afternoon,
the most awful stillness I ever witnessed prevailed: as far as my eyes could see,
not a person was to be observed at any window,
nor anything in the streets which had life,
excepting a poor horse that was fastened to a small cart,
and had made his way thus far towards home, but durst not venture further;
he had preserved his life by placing his fore-feet on some steps,
which lay high above the foot-path,
where we could observe he was only barely able to keep his mouth above the water.
About four o`'clock in the afternoon, a policeman came in a boat,
and let this poor prisoner loose, when he swam into a yard that was near:
this policeman was the first person, except our own family, whom we had seen anywhere,
from ten o`'clock in the morning until this time in the afternoon,
when the water began to retire.
Consoling as the prospect of its retreat was,
it was distressing to observe the devastation that had taken place.
As the water retired,
it set the doors of those shopkeepers which opened out into the street wide open;
whereby many of their articles that were floatable passed down the streets to the canals,
and so out to sea.
My landlady feared that the whole city would be so under water,
that none would escape with their lives;
the shock she received from this apprehension was so great,
that she never recovered from it during my stay in Petersburgh.

The impressions of my mind at the time were,
that it was a visitation in mercy from Almighty God
to the inhabitants of this great city.
During the whole time,
when standing at the windows and viewing the progress of this awfully awakening scene,
my mind was in adorable mercy preserved calm and quiet,
free from the least emotion of fear that what my landlady so dreaded would take place.
The darkness of the night, the impracticability of lighting the lamps,
and scarcely a person or carriage passing along the streets,
produced a quiet that was striking to the mind.
This, together with the remembrance of the continued cries, for near two hours,
of a poor man on his carriage, who was driven under the gateway of the house I was in,
and to whom no assistance for a length of time could be given, so pierced my ears,
that it was some time before I was able to rise above it.

Seventh-day, 20th of eleventh month, the waters had left the streets:
after breakfast I went out to view the calamity,
which this extraordinary visitation to this magnificent city had occasioned.
Scarcely a bridge has escaped uninjured by it,
and many are carried quite off their bearings:
part of one of the large bridge of boats across the Neva,
was left standing against the walls of the palace: rafts, small boats,
with two of the large steamboats employed in going to Cronstadt, were left in the city,
on what is called the island.
Here the effects were more severely felt than in the city; houses,
with the people in them, were taken off their foundation, and carried out to sea:
some of these poor inhabitants were observed sitting on the roofs of their houses,
to save life as long as they were able.

On the Catherine Hoff road, in a row of cottages,
two hundred and fifty women and children were found,
to have fallen victims to this awful visitation; the men being from home at their work,
escaped.
The number of horses, horned cattle, and pigs, that perished, was said to be very great.
In walking through the streets of the city,
it was affecting to observe the sorrowful countenances of the shopkeepers,
standing at their doors,
whilst their servants were bringing into the street
the remains of the wreck of their property;
some of them appearing as if they had no power left to lend a helping hand,
but stood as if paralysed: others stood in amazement,
and scarcely a word was to be heard in passing through the streets.
To exhibit to the full the dreadful consequences of this
visitation seems to be out of the power of man.

Notwithstanding this awful visitation, and the distress consequent upon it today,
yet so prevalent is the French principle of keeping up the spirits of the people,
in order to turn their attention from serious reflection,
that the commandant of the city ordered all the theatres to be opened this evening;
but this coming to the knowledge of the worthy emperor, the order was countermanded,
and they were kept shut.
According to various reports, the emperor proved himself to be the father of his people,
not leaving the wants of such of his poor subjects as had suffered from the inundation,
to the inspection of the police, or any other of his officers,
but going himself in person, and attending to their wants;
so that it was believed many were placed in a better condition than they were in before.
First-day, I walked out to meeting: for two miles there was scarcely a fence standing,
on one side of the road;
the land was covered with glass lights from the gardeners`' grounds, also temples,
summer-houses, boats, timber of various descriptions, crosses out of the burial grounds,
parts of coffins, the dead bodies of some who had perished from the flood,
and a variety of cattle, that had perished also.
My kind friend, Daniel Wheeler, and his family, in consequence of his high situation,
had escaped.

This awful visitation, which had taken place in the city, loosened my bonds;
the cloud which had rested on the tabernacle seemed gradually removing.
It appearing to me I must be willing to take up my pen,
and address the inhabitants generally on the solemn occasion;
I looked towards the abode of my kind friend Daniel Wheeler,
as being likely to afford me a quiet retreat for the purpose;
but the way not appearing clear in my own mind for so doing,
believing I must not risk involving my kind friend and his family in any of my engagements,
but have the responsibility rest on myself, I returned to my lodging,
with my mind fully prepared to take up my pen, should the concern remain with me.
I retired to bed at my usual time; but the enemy beset me on every hand,
to discourage and deter me from making an attempt.

Second-day,
apprehending my friends in England would receive the intelligence
of the awful visitation which this city had experienced,
and be anxious on my account, I wrote to them, giving a short detail of it;
and as some light now began to shine on my path,
I thought I saw pretty clearly that it would be right
for me to attend the next Yearly Meeting in London;
and if so, I should be obliged to return overland, as the probability was,
the port of Cronstadt would not be open in time for vessels to get out.
I therefore requested my friends in England to furnish me with letters to Riga, Memel,
and Dantzick.

Fifth-day, walked out to meeting; a great number of dead horses, cows,
and pigs were being carted out of the city, in order to be burnt.
Sixth-day, I was obliged to keep at home, having taken a heavy cold,
from standing a short time in a shop that had been under water.
Seventh-day, not able to use my daily exercise.
First-day, although much indisposed, I walked out to meeting;
but feeling my cold getting worse, I did not stay the afternoon meeting.
The accounts received today from Cronstadt state,
that two vessels were dashed to pieces in the storm, but the crews were saved;
and that great distress was occasioned by the inundation in that town.

Second-day, in my ramble this morning I was met by five English sailors,
part of the crew of a vessel from Liverpool,
which was wrecked on one of the islands in the Gulf of Finland during the late storm:
although total strangers to each other, our meeting appeared mutually agreeable.
Except men are churls indeed, I have found these feelings are generally excited,
when we are permitted to meet our countrymen in a foreign land.
On my way home this afternoon, I was joined by an Englishman,
who was a resident in a part of the palace called the Hermitage,
appropriated to natural curiosities and paintings:
he gave me a kind and pressing invitation to make him a visit,
and view the rarities which the Hermitage contained.
My natural inclination would have prompted me readily to accept his invitation,
but my duty told me,
that to see rarities and paintings was not the errand that
brought me from my native land to visit this city;
I therefore was constrained to decline his kind offer,
at which I thought he felt disappointed,
as I could not doubt that he was desirous of doing me a kindness.

Third-day, the weather threatening to be stormy, drove me home earlier than usual:
in the afternoon I ventured out again, and walked to the Newskoi Prospekt;
the crowd of people and carriages, many of whom came to pass away the time,
was not suffered to dissipate that sweet covering of good desires,
with which my mind was favoured; but amidst all this display of finery and bustle,
I was enabled to strew my tears, and offer up my prayers before the Lord,
that I might be preserved faithful in everything which
he should see meet to require of me in this nation,
more especially in this city; and for a safe return home,
when the time for my departure should be fully come.
Divine mercy condescended to dry up my tears, giving me the assurance,
that if I continued faithful in doing his will,
He would care for me every way to the end of my journey home,
and afresh bringing to my remembrance the repeated intimations which I had received,
that he had service for me to perform amongst my brethren on the American shore,
with such clearness, that all my doubts about my safely getting out of this country,
and reaching my own home, vanished out of sight, as if I never had them to contend with.
But, O! the messengers of Satan, how hard are they to endure; but they are, I doubt not,
permitted, in great wisdom and unutterable lovingkindness,
to prove our faith in the all-sustaining arm of God, and our constancy towards him;
in order that, by patiently enduring them throughout the Lord`'s appointed time,
these tribulations may work patience, and patience experience, and experience hope,
that maketh not ashamed;
because the love of God is shed abroad in our hearts by the Holy Ghost,
which is given unto us.
I returned home, and retired to rest, under a humbling hope,
that another day of my pilgrimage in this city,
which has been a place of sore exercise of mind to
me daily since my lot has been cast in it,
has been as well passed over as many days of my life; for which favour,
under a thankful sense thereof, the exclamation,
"`What shall I render to the Lord for all his benefits!`" was the language of my mind;
accompanied with an earnest desire,
that there may not be a failing in doing what may be called for at my hand,
during my sojourning in this place;
otherwise how will this inquiring language thus uttered, rise up in a future day,
and condemn me.

Fourth-day, in my rambles this morning, I bent my course to Catherine Hoff,
a village about a mile and a half from the city:
had I made my visit to it previously to the late inundation, I suppose,
from the remains left by that awful visitation,
I might have fancied myself entering one of our well-built,
well-planted villages in some of the flats on the banks of the Thames.
I was informed,
that large sums of money were last summer expended by the government on this spot,
in order to form something similar to the Elysian Fields in the neighbourhood of Paris,
to draw the inconsiderate inhabitants out of the city on the first-day,
when the diversions were to be more generally going forward: but, alas! how uncertain,
how short-lived, have all these attempts proved, when the great and terrible One,
who inhabits eternity and dwells on high, whose name is holy,
who inhabits the holy place, sees meet to arise, and assert his power and sovereignty,
fulfilling his determination, because of their wicked ways;--"`I will overturn, overturn,
overturn;`" and it shall be no more.
I stood and viewed with astonishment the remarkable manner,
in which this declaration of the prophet had been fulfilled on this spot,
in a more striking and destructive way,
than in any other part of the city or its suburbs that I had seen or heard of;
how all that the art, skill, and labour,
which the invention of man was capable of producing,
to gratify the evil imaginations and desires of the corrupt heart, had, as it were,
at one stroke been hurled away together;
not a vestige of these inventions was left standing anywhere,
except part of a newly erected building,
where I was informed much of their wicked nightly practices went on:
the stairs and part of the foundation of this building were carried away,
the gravel walks thrown up, the plantations destroyed,
and the labour that had been bestowed as completely laid waste,
as it is possible to conceive.

Whilst viewing these evidences of the Lord`'s judgments, I was led secretly to crave,
that these things might prove a means of awakening in the minds of those,
who had been the frequenters of this place of folly, dissipation and wickedness,
a more serious consideration of their ways and doings; but, alas,
from the manner in which the people continue to conduct themselves,
there is no ground for cherishing this hope on their account.

Fifth-day, I walked out to meeting,
and was well rewarded for my labour in going to sit
down with the little company I met with,
independent of the enjoyment of having the opportunity of a little conversation,
as I mostly pass the day over without exchanging a sentiment with any one, except,
as necessity compels me, with the family I am in;
towards whom the caution in my mind continues to be, to carry myself, on all occasions,
with the greatest possible care as to conversation,
and yet to manifest a kindness of disposition toward them,
and gratitude for the attention I receive.

Sixth-day, my kind friend Daniel Wheeler sent his droskey for me,
and with him and his family I spent the day,
an enjoyment which I seldom have partaken of since coming to the city,
except on meeting-days; for,
understanding that I continue to be considered by
some in authority as a suspicious character,
I feel it necessary to be careful,
not to expose any of my friends here to the danger of becoming implicated with me.

First-day, walked out to meeting; the wind setting strong across the road,
I was greatly annoyed by the burning of the carcasses of the cattle and pigs,
that were brought out of the city, where they had perished during the flood;
it not being considered best to bury them, lest the wolves should be attracted thereby.
The days being very short, I did not stay the afternoon meeting,
having nearly five English miles to walk to my lodgings.

Believing the time to be fully come when I must be willing to take up my pen,
and as matter rose in my mind, commit it to paper,
in an address to the inhabitants of Petersburgh,
I devoted the afternoon and evening to this service.
When I had finished,
my mind felt relieved from some of the load of exercise I had been brought under,
since the awful visitation which this city had witnessed.

Second-day,
my mind continued to be charged with an apprehension
of religious duty to attempt a visit to the emperor.
I waited on a merchant in the city, with whom I had made a slight acquaintance,
who was on terms of friendship with the emperor`'s private secretary,
through whom my request must be conveyed.
On informing him of the cause of my now waiting upon him,
he engaged to call upon the secretary, and to inform him of my request;
having thus far done my part towards bringing about
that which I believed would be required of me,
before the way would open for quitting the city, I did not lose the reward of peace.

Third-day, brought me under fresh difficulty:
my friend who yesterday had offered to assist me
in obtaining an interview with the emperor,
appeared to regret he had taken such a task upon him,
as he requested to be excused from the performance of it.
I therefore concluded it would be best for me to
adopt my usual plan of doing my business myself,
by addressing a note to the secretary, leaving the result to that Almighty Power, who,
I firmly believed, was able to make the way easy for me,
if it was his design I should be admitted to the emperor.
I therefore wrote a note as follows: "`I am one of the Society of Friends; and feeling,
as I have done for some time, my mind exercised with apprehensions of religious duty,
if possible to obtain an interview with the emperor,
I shall feel myself greatly obliged to thee, his secretary, and served,
by thy endeavouring to make such way for me, as may be in thy power.`"
This note was forwarded to him by a messenger whom
my friend provided for me for that purpose.
The circumstance of my friend`'s refusal to fulfill his engagement, was at first trying;
but I believed that Divine goodness was making way
for my release from some of my weights and burdens,
and that if patience were but abode in, these dispensations would be sanctified;
although my faith, patience, and obedience never were more fully put to the test.
Having forwarded my note to the emperor`'s secretary,
the peaceful feeling in my mind enabled me to hold up my head in hope,
that my movements thus far were in the line of Divine appointment;
and I was freed from all anxiety as to the result of it.

Fourth-day, patience is indeed very requisite, when we are lying, as it were,
on our oars, waiting for the word of command to be clearly given to get under way again:
although at times,
I feel as if the time for my release from the field of labour here was hastening apace,
and that an overland journey must be submitted to,
yet I dare not at present take any step whatsoever towards arranging for it;
having the assurance in my own mind,
that everything needful for my safe return to my family again, will, in, due time,
be provided for me.

Fifth-day, I walked out to meeting.

Sixth-day, I rambled to the great market; the snow was falling heavily,
I walked under cover for nearly two hours, and then returned home.
A person called upon me today, inviting me to make him a visit;
although I could not doubt but his invitation was given in great sincerity,
I found I must decline it, which placed me under difficulty;
but as it appeared clear to me my safety was in being
willing to take up the cross by declining,
I endeavoured to do so in as handsome a manner as I was capable of,
so as not to give just occasion for offence to be taken at it.
The evening closed by reading in "`Piety Promoted,`" and by mental
prayer for strength to be enabled to hold on the way of well-doing,
and bear the daily cross to the end.
But, O! the fears that I am at times tried with;
being almost ready to cast away the shield, as if it never had been anointed,
or I had never known anything of its miraculous sufficiency
to ward off every blow of Satan.
Before I retired to rest,
a glimmering prospect was afforded of my safe landing on the shore of Harwich.

Seventh-day, 11th of twelfth month, such have been my secret plungings this day,
and the fears and misgivings which I have had to pass through,
that nature at times seemed nearly exhausted.
Having finished a fair copy of the address to the inhabitants of Petersburgh,
I was not able to know, how it is to be disposed of,
or who will dare to translate and print it; for nothing can go to press in the city,
without first having the sanction of the censor.
When my bed-time arrived,
I saw no other prospect but that of having a distressing night to pass through:
my inclination would have led me to remain up through the night,
but fearing that the family I was in would notice my so doing,
and be anxious to come at the cause of it,
which I should not be able to disclose to them;
such was the state of nervous irritability I was sunk into,
that I found it would be difficult for me to lie quietly in bed;
my feet were more like the feet of a corpse than of one in whom a spark of life existed,
yet there was no way but to go to bed, and endure the suffering that might follow.
Divine mercy however failed me not,
but continued to be my stay and staff during this long and trying night,
for so I thought it; and I anxiously watched for the peep of day,
when I might be able to rise from my bed without notice being taken by the family,
and to parade my room.
That the Lord alone who thus sustains,
may have the praise and full dedication of the remainder of my days,
is the earnest desire of my soul.

First-day, walked out to meeting;
after again reading over the address to the inhabitants, I signed it: on inquiry,
I was fully satisfied a translation could not be procured, nor printed copies,
as no one would dare to attempt to undertake either of these offices of kindness:
my mind continued to feel relieved as far as I had thus proceeded.
There appeared no way for me but to keep in patience,
until the way for disposing of it was seen with greater clearness,
than at present was the case with me.

Fifth-day, I walked out to meeting; the change from a fine clear frost to close, damp,
warm weather, occasioned my walk to be very oppressive; the next day was, however, fine,
clear and frosty.

Seventh-day, a time of close exercise of mind from various causes;
but the day closed quietly.
What an unmerited mercy, when after a storm the calm comes.
First-day, walked out to meeting.

Second-day, no reply to my note to the secretary;
yet I am preserved in patience as to the result, which I hope I esteem a favour.

Third-day, 12th of twelfth month, as I was turning out for my morning`'s walk,
a messenger presented me with a letter, demanding forty copecks,
which I cheerfully paid him; supposing it came from the secretary,
and would prove the means of determining the result of my note to him;
but this was not the case, as it only appointed a time for my waiting upon the secretary.

Fourth-day, agreeably to appointment, I waited upon the secretary.
Prince Alexander Galitzin; who received me cordially,
and informed me the emperor had concluded on seeing me;
the time for the interview however was not fixed, but timely notice would be given me.
Apprehending it would be right for me to put the emperor in possession of my certificates,
I left them with the prince for that purpose.
The subject of disposing of the address I had signed,
came again closely before the view of my mind:
the way for me to obtain an interview with the emperor being now clear,
it appeared to me I must place it in his hands as the father of his people,
to dispose of it as in the wisdom of Truth he might be directed.

Continuing to feel a lively exercise of mind on behalf
of my countrymen residing in this nation,
more particularly those who reside in Petersburgh, Cronstadt and Moscow;
and apprehending I should not acquit myself acceptably in the sight of my great Master,
unless I was willing to commit to paper that which arose in my mind for them,
in the love of the Gospel, I took up my pen, and addressed them also; and,
as no printed copies could be obtained, a few copies were written,
which I placed in the hands of the preachers of the English congregations here,
and put some in train for Cronstadt and Moscow,
requesting care should be taken to give them all the publicity possible;
which I had reason to believe would be the case,
from the agreeable manner in which they were received,
and from the conclusion come to of reading it at the close of their worship.

[.offset]
The address was as follows:

[.embedded-content-document.address]
--

[.letter-heading]
An Address to the English Protestants in Russia,
more particularly to those resident at Petersburgh, Cronstadt, and Moscow.

Since my lot has been cast in this city,
I have felt a lively interest for the best welfare of the native inhabitants;
before landing on this shore, my mind was warmly engaged on your account,
my dear countrymen; accompanied with more than usual feelings of solicitude,
that you may be found walking as becomes the Gospel of our Lord and Saviour Jesus Christ;
thereby proving yourselves instrumental, through Divine help,
towards leavening the minds of the people, like the leaven we read of,
which a woman took and hid in three measures of meal until the whole was leavened.

As far as my observation has gone in different places,
the example of the English people is much looked up to;
on which account I have felt the more solicitous,
believing that the present is a day of great importance both here and elsewhere,
upon the continent of Europe:
a day in which the light of the glorious Gospel of Christ Jesus,
has dawned in the souls of many scattered up and down, and will more and more dawn.
It therefore appears to me of serious consequence to the prosperity of this great work,
that you, who are placed here and there amongst the people,
should keep in constant remembrance these expressions of our dear Lord,
when personally upon earth, to his immediate followers, "`Ye are the light of the world;
a city that is set on a hill, cannot be hid: neither do men light a candle,
and put it under a bushel; but on a candlestick, and it giveth light to the whole house:
let your light so shine before men, that they may see your good works,
and glorify your Father which is in heaven.`"
Far be it from me to charge you with a want of care in this important respect,
from any outward information or knowledge of how matters are with you.
I came a stranger to all, and have felt it right for me to keep so.
It would be uncharitable and unwarrantable in any,
to doubt the propriety of your claim to your being followers of Christ; yet a jealousy,
yea a godly jealousy--arrests my mind, on account of many of you in this respect; I fear,
if my feelings be correct, ye are not an example to the native inhabitants,
in an endeavour to come out of the spirit of the world.

In a degree of that love, which desires the welfare of the human race all the world over;
allow me to press the query individually: Art thou in health, my brother?
art thou in health, my sister?
has it been thy constant daily care to be found preserved in that
watchful state of mind which the royal Psalmist was in,
when he declared, "`I said, I will take heed to my ways, that I sin not with my tongue,
I will keep my mouth with a bridle, while the wicked is before me.`"
For it is only as this disposition of mind is abode in,
that we can reasonably expect Divine regard and approbation.
The enemy of all righteousness has none who serve his purpose better,
no agents which more steadily or firmly support and promote his cause amongst mankind,
than professing Christians,
who are not willing to be found coming up in the practical part of true religion;
for the greater profession such are making, the more they talk about religion,
the more they deceive themselves as well as others;
instead of coming to partake of that living and eternal substance, which will endure,
they are but following an empty shadow.
It matters little by what devices or stratagems Satan prevails,
so long as he can satisfy mankind,
and prevent them from coming to the true knowledge of God,
and keep them from an acquaintance with that Power which can save.
This great adversary of man`'s happiness, will let people go to their place of worship;
he will not hinder their pleading for rites or ceremonies;
he will furnish them with argument from the holy Scriptures to support their cause:
so long as he can keep them worshippers in the outward court,
and hinder the inward work from going forward in the temple of the heart,
his purposes are fully answered.

But to return to these worshippers in the outward court, they serve Satan various ways;
they often become stumbling-blocks to the weak, but honest inquirers,
who are anxious to know the feet of their minds turned into Zion`'s paths;
and when difficulties present to those who have really
felt a desire to be helped over them,
the adversary brings forward to their view the example
of these eager hearers of the word,
but slothful doers of it;
by this means he often checks the sincere desires that are begotten,
and causes a stopping short of that which has been before aimed at.

Now, seeing we are called unto glory and virtue,
and that we have to contend with an unwearied adversary, ever on the alert,
seeking whom he may devour:
how great is the necessity for each of us to watch and be sober,
using all diligence to make our calling and election sure,
before we go hence and are seen of men no more.
There is no work, nor device, nor wisdom, nor knowledge in the grave,
whither we are all hastening; as the tree falls, so it lies; as death leaves us,
so judgment will find us; and from the decision of our all-merciful, all-wise,
and all-just Judge, there is no appeal.

Let none be spending their time, that treasure of eternal consequence, in vain;
but let obedience keep pace with knowledge,
whilst the day of merciful visitation is lengthened out, lest the night come upon us;
and those things which belong unto our peace, should be forever hid from our eyes.

The Lord is no respecter of persons; but in every nation he that feareth him,
and worketh righteousness, is accepted of him: it is also declared,
that a manifestation of the Spirit is given to every man to profit withal;
if we walk in the Spirit, we shall not fulfill the lusts of the flesh:
the primary means of immediate Divine help, the Holy Spirit,
is freely administered unto all; the grace of God, which bringeth salvation,
hath appeared unto all, teaching all.
The holy Scriptures are bountifully distributed;
which are able to make wise unto salvation, through faith which is in Christ Jesus,
and are profitable for doctrine, for reproof, for correction,
for instruction in righteousness.
These Sacred Writings, although a secondary means,
were given forth by inspiration of God; designed, in condescending mercy,
for the help of man;
and they have the blessed tendency to direct our minds to the primary means,
even Christ Jesus, the Alpha and Omega, the beginning and the ending,
the first and the last, the way, the truth, and the life, the only way to God,
as declared by himself, '`No man cometh to the Father,
but by me.`' Are there not sufficient and reasonable grounds to believe and hope,
my dear countrymen,
that if you were found walking as becometh the Gospel of our Lord and Saviour,
your actions would speak louder than words, to the surrounding natives?
When we consider the gracious means afforded, outward and inward,
for the help of mankind, by an all-bountiful Creator;
together with the laudable efforts of the Bible Society,
and the labours of many pious Christians,
can we attribute the small appearance of fruit amongst
the continental nations to any other cause,
than the want of faith,
and a fulness of conformity in the professors of Christianity to the doctrines, precepts,
and example of the self-denying Jesus?
The primary and secondary means are all-sufficient and abundant;
it is the thread of Christian example that is so much wanting,
to make a three-fold cord to the praise and glory of God--the
promotion of the great work of righteousness in the earth,
our own peace while here, and eternal happiness hereafter.
Be entreated then to consider what I say,
and the Lord give you understanding in all things.

Whilst I am addressing others, I feel the need of taking heed to myself;
which I humbly hope will never be lost sight of by your sincere friend and well wisher.

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Petersburgh, Twelfth month, 1824.

--

Fifth-day, I walked out to meeting, and returned home to tea,
at times not a little thoughtful how I should acquit myself before the emperor;
but this I found was not a subject for me to dwell upon: I therefore endeavoured,
as much as in me lay,
to leave this subject and retire to bed in hopes of a night`'s rest.

Sixth-day, I felt weighed down with the prospect of an interview with the emperor.
I turned out for a short walk, fearing a long absence from home,
in case a messenger should come in my absence.
On my return home, I received a letter from the secretary,
appointing an interview with the emperor, for six o`'clock this evening;
it stated that a carriage would be in attendance upon me,
and a person to conduct me to the palace, who was unacquainted with the English language,
whom I was to follow, after I left the carriage.
After reading the letter,
my feelings at the moment may be better conceived
by such who have been placed in a similar situation,
being about to make a visit in the name of the Most High, to an absolute monarch.

I kept quiet at home the remainder of the day;
I endeavoured well to consider the propriety of my putting into
the hands of the emperor the address to the inhabitants of Petersburgh,
and leaving it solely at his disposal;
and I apprehended my proceeding thus was the only
way for me to obtain relief to my own mind.
I enclosed it, with the address to the English Protestants,
in a sheet of paper for that purpose.
I had told a friend of mine,
I was led to apprehend one interview with the emperor would
not afford me a full opportunity to relieve my mind;
to which my friend replied, he did not think a second could be obtained,
giving me such reasons as satisfied me,
that it would not be for want of a willingness on the part of the
emperor to comply with a request for a further opportunity,
so far at least as prudence dictated to him.
I endeavoured to be in readiness early,
as I was requested by the letter to be punctual to the time.
The carriage with my guide arrived at my lodgings
an hour before the time my letter specified,
which placed me in a trying situation, as I knew not how to account for it,
fearing some alteration had taken place in the time since the appointment was first made,
and that a second note had, by some means, not come to my hand.
On inquiring, the guide informed my landlady his orders were to be with me in time,
which was the cause of his coming to me thus early.

On our arrival at a back entrance of the palace, my guide left me in the carriage,
where I was kept waiting a considerable time, I concluded from our being still too early:
at length my guide returned, and took charge of me.
At the entrance, I passed the sentinel on duty; but no notice was taken,
that I could observe, of my hat being kept on:
my guide then conducted me through a long and very dreary passage,
in which the few lamps that were lighted, gave but a very dim light,
which cast somewhat of an awful feeling over my mind, until I came to an open space;
here a young man was in waiting to take charge of me, who conducted me up stairs,
at the top of which, one who, I suppose, is called a lord in waiting on the emperor,
was in readiness to receive me, who conducted me into the emperor`'s private apartment,
and there left me.
As silence was strictly observed on the part of those who had taken charge of me,
not a word passed, or a look from me,
that could express any thing like surprise at this profound silence,
so uniformly observed.

After taking my seat in this room a short time, I observed the handle of the door,
opposite to that by which I had entered, move,
which led me to conclude some person was about to enter.
I rose from my seat; when a rather tall person, with a placid countenance,
came into the room, so plain in his attire, as to ornaments generally worn by sovereigns,
as to induce me to put the question to him, "`Am I now in company with the emperor?
to which he replied, in an affable manner, "`Yes, you are.`"
He held out his hand to me, and taking his seat on a sofa, placed me by him.
After he had inquired after Stephen Grellet and William Allen,
for whom in warm terms he expressed his sincere regard,
I laid before the emperor the manner in which my mind had been exercised.
I informed him the only way that had opened in my mind for relief,
was by taking up my pen and committing to writing matter
as it came before me in the line of religious duty,
addressed to his subjects generally; but as I had been well informed,
the press was now so restricted,
that even the Moravians were denied the liberty they had heretofore enjoyed,
of having their new-year`'s hymn printed,
it was not possible I could have the address translated and printed;^
footnote:[On inquiry, I was well assured,
if I procured a translation of the address in England, and had it printed there,
they must be smuggled in, and then no one would dare to circulate them.]
therefore I believed I should not be able faithfully
to acquit myself in the Divine sight in this matter,
but by giving the address in charge to him,
whom I was to consider the father of his people; desiring, as I most earnestly did,
that Divine wisdom would be pleased to direct him in the right disposal of it:
on which he appeared cordially to receive it from my hands.

After this subject was thus disposed of, various matters were entered into,
during which I brought into view such subjects as to me appeared ripe to bring forward;
other matters which my mind had been exercised with,
I found I must as yet keep in the background; yet I felt not a little tried, lest,
as my friend had told me, there should be no probability of my having a second interview.
However, a secret hope crossed my mind, that if these further matters,
not yet ripe for communication to the emperor,
were subjects Divine wisdom saw meet I should lay before him, the Almighty was able,
without any care of mine, to make way for it.
Thus I was enabled to leave things,
and simply to attend to the business of the present time;
for I think I never witnessed my mind more unshackled,
or felt more freedom from all restraint, and more at liberty to unbosom my whole soul,
than I did on this occasion, to the pious emperor,
on every subject as it rose in my mind to lay before him,
both as it respected himself as sovereign,
and his subjects he was permitted to rule over;
feeling more as if I was sitting by the side of a servant dependent on me,
than by the side of so great a monarch.

Towards the close of this interview,
the emperor very pathetically expressed himself in substance as follows:
"`Before I became acquainted with your religious Society and its principles,
I frequently, from my early life, felt something in myself,
which at times gave me clearly to see,
that I stood in need of a further knowledge of Divine
things than I was then in possession of;
which I could not then account for,
nor did I know where to look for that which would
prove availing to my help in this matter,
until I became acquainted with some of your Society, and with its principles.
This I have since considered to be the greatest of all the
outward blessings the Almighty has bestowed upon me;
because hereby I became fully satisfied in my own mind,
that that which had thus followed me, though I was ignorant of what it meant,
was that same Divine power inwardly revealed,
which your religious Society have from their commencement professed to be actuated by,
in their daily walks through life;
whereby my attention became turned with increasing earnestness,
to seek after more of an acquaintance with it in my own soul.
I bless the Lord, that he thus continues to condescend to send his true Gospel ministers,
to keep me in remembrance of this day of his merciful awakening to my soul.`"
He then added, "`My mind is at times brought under great suffering,
to know how to move along; I see things necessary for me to do,
and things necessary for me to refuse complying with, which are expected from me.
You have counselled me to an unreserved and well-timed obedience
in all things;--I clearly see it to be my duty;
and this is what I want to be more brought into the experience of: but when I try for it,
doubts come into my mind, and discouragements prevail: for,
although they call me an absolute monarch, it is but little power I have,
for doing that which I see it to be right for me to do.`"

I feared my intruding longer on the time of the emperor, having, I believed,
cast off the whole of what my mind was at this time charged with to deliver to him;
and yet it felt trying to me to leave him,
not knowing if I ever should have another opportunity of fully relieving my mind;
however, as it appeared best for me so to do, I made the effort to be moving:
on which the emperor requested we might have a quiet sitting together before we parted,
which accordingly took place.
When I rose from my seat to go, the emperor, taking hold of my hand, and,
turning towards me in the most affectionate manner, said:
"`I shall not consider this as a parting opportunity,
but shall expect another visit from you, before you set off for your own home.`"
This circumstance afresh awakened in my mind a feeling of reverent gratitude,
that I had been preserved from putting forth the hand,
when the command had been to stay it.
On my being about to retire from the emperor,
the case of Hezekiah was brought to my remembrance, although from a different cause,
when he turned his face to the wall and wept:
for I observed the emperor turned himself from me, as I fully believe,
in order to give vent to his tears of gratitude to that Almighty Power,
who in mercy had been pleased to favour us together with
the precious overshadowing influence of his good presence;
of which I never remember to have been more sensible.

I was then conducted to my lodgings in the same quiet manner, and by the same conveyance;
deeply sensible of my inability to set forth my feelings of gratitude to Almighty God,
in making the way so easy as it had been to me.
Whilst in company with the emperor,
he made particular inquiry after the health of my friend Daniel Wheeler,
which appeared to be rather declining; on which I informed the emperor it was my belief,
that nothing would be so likely to restore him to
his usual health as breathing his native air,
and associating with his friends at the ensuing Yearly Meeting.
The emperor replied, "`He shall go.`"

Seventh-day, 25th of twelfth month, after breakfast and reading,
I pursued my usual exercise out of doors.
The temperature was fifteen degrees below freezing.
The people and cattle made a picturesque appearance from the hoar-frost,
more particularly the coachmen and sledge-drivers,
their large long beards resembling a mass of snow, suspended from their chins.
Although this severe change has taken place,
I think I have suffered more from cold in my own country, than I suffered here today:
my clothing was warm, to meet the change out of doors;
and on my returning home I stripped off my warm clothing:
the internal warmth I met with in the house,
from the fires kept in different parts of it,
abundantly compensated for the parting with my warm clothing.
I was not able during the winter, but once, to bear a fire in my own apartment.

First-day morning, the wind boisterous, and the snow fell so very fast,
that my turning out of town to take a bleak walk to meeting was discouraging;
but as I set off with a goodwill to do my best,
although I found it a difficult task to proceed,
the road in places being so blocked up with snow.
I was enabled to reach my kind friend Daniel Wheeler`'s,
at the moment the family were about sitting down to hold their meeting;
and I returned home in the afternoon,
the city feeling to me to be my proper place of residence;
otherwise it would have been more congenial to my natural disposition,
to have passed more of my time with my friend Daniel Wheeler and his family.

I had a conversation with Daniel Wheeler on what
had passed between the emperor and myself,
relative to the state of my said friend`'s health,
and the probability of his receiving benefit by a visit to England:
a cheering prospect was afforded me of having him for my caretaker,
and companion to England.

Second-day, 27th of twelfth month, the weather fine:
I pursued my exercise of walking in the evening.
I had to labour hard to know a task accomplished,
which I have often found a very difficult one,
that of leaving the things of the morrow to care for themselves.

Third-day, mostly spent in walking and reading.
My landlady being frequently indisposed and confined to her bed,
more particularly so since the awful inundation,
when the ringing of the alarm-bell and firing of the cannon,
announces that the Neva is rising above its wonted level,
it is my lot to be left to the mercy of a dirty, idle, voracious Russian servant-girl,
who has no knowledge of the English language,
and who plunders me of my provision every way she can:
I am not able to see any remedy for it, but by bearing all with patience;
believing my getting into these lodgings,
was in answer to my earnest prayers to the Most High,
to provide for me a safe sheltering place,
and I have believed it to be the most so I could have found in the city.
I therefore am made willing to endure all my increased
difficulties as it respects the body,
rather than risk the danger of getting into difficulties that would be harder to bear,
and to be extricated from again.

Fourth-day, the cannon frequently firing, the water in the Neva is rising,
which alarms some of the inhabitants of the city.
When the late awful visitation took place and the water subsided, it was reported,
that some who lived on the island, being absent from home at the time,
finding on their return that their families had perished in their own dwellings,
and in other instances, their house and family were all taken out to sea,
became bereft of their senses; and others put an end to their existence.
This led me to consider, what a mercy it is to be able to find a sure anchoring place,
in seasons of trial like these.

Sixth-day, the weather wet and warm, I rambled on the banks of the Neva,
where great preparations were making on the ice for the accommodation
of carriages and foot-passengers travelling upon it.
With this day the year 1824 closes, and I hope I may say,
I feel thankful to the Great Author of every blessing,
so many of which he has been pleased in unmerited mercy to dispense to me.

Seventh-day, the 1st of the first month, 1825.
The new year commences with a heavy fall of snow.
I walked out, in hopes the air would brace up my nerves, which proved the case.

First-day, walked out to meeting:
my dear friend Daniel Wheeler having received official intelligence
of his being set at liberty to make a journey to England,
we freely conversed together on the subject,
although no time was fixed for our departure.

Second-day, I walked out to the frozen market, which I found well stocked with oxen,
calves, sheep, pigs and poultry of most descriptions; also game in great abundance,
with fresh fish, all in a frozen state for winter store,
which are purchased by the inhabitants,
and deposited in their ice-cellars for family use.
The oxen and sheep were placed on their hind legs in an erect posture,
stripped of the clothing which nature gave them,
which had rather a disgusting appearance.
I understood that the sellers of these articles,
being fearful of a change taking place in the weather from frost to thaw,
were anxious to sell,
as a change to mildness would render their various articles
of much less value for depositing for winter store.

Seventh-day, the weather still continuing very severe, I bent my course to the Neva,
which exhibited a pleasant appearance:
the different paths marked out on the ice for passengers and for carriages,
were decorated on each side with fir-trees,
that passengers might keep their course with safety.
Great numbers of persons were driving on it, seemingly fearless;
but as necessity did not require my venturing on it, I kept on firm ground.

Fifth-day, 6th of first month, walked out to meeting:
accompanied by my friend Daniel Wheeler, we rode to George Edmundson`'s,
one of the English Friends who resides at Octer.
We crossed the Neva on the ice; on our reaching the midway of our journey over,
I was led to query with myself, what had induced me to make this venture,
and I was thankful when we reached the shore again, preferring firm ground.
I now had my departure from Petersburgh announced in the newspaper, according to custom,
as the time for it was concluded on.

Seventh-day, 8th of first month, the time being come,
when I must announce to the emperor my prospect of leaving Petersburgh,
I wrote the following note to his secretary:

[.embedded-content-document.letter]
--

I have been notified in the newspapers as about to leave this country,
and I should wish to be at liberty in two weeks:
it is necessary I should secure my place as early
as well may be in the diligence to Riga,
but this I cannot feel easy to do,
having given the emperor to expect I should not depart without
thus craving an opportunity to take my leave of him.
I wish respectfully to say, I am now holding myself in readiness to wait upon him,
at such time as he may think most suitable to appoint.

[.signed-section-signature]
Thomas Shillitoe.

[.signed-section-context-close]
Petersburgh, 8th of First month, 1825.

--

In reply to which, in the course of the day, I received a note from the prince,
informing me I might make the necessary arrangements for my departure,
as the time for my taking leave of the emperor would be
certainly announced to me in the course of two weeks.

Third-day, by the help of an Englishman, I went to the diligence-office,
to obtain information respecting the time of their departure,
and the weight of luggage which would be allowed each of us,
and the time for rest and refreshment on the road:
I had called myself previously at the office,
and received very insulting behaviour from a young man in the office,
on account of keeping on my hat there;
of which behaviour I informed my friend and interpreter,
who mentioned the circumstance to one of the managers,
and the young man was spoken to respecting his conduct towards me:
but on more maturely considering the subject,
during my moments of quiet when alone this evening,
I felt cause for regret that I had not quietly passed over this insult;
fearing it operated as much to hurt my pride,
as wearing my hat in the office did the young man`'s pride;
and I trust what I have felt on the occasion, will prove as a watchword to me in future,
to be more willing to endure all things for the cause`' sake.

Fifth-day, walked out to meeting,
and found my dear friend Daniel Wheeler busily occupied
in arranging his outward concerns for our departure:
the prospect of my having such a caretaker,
caused my heart to overflow with gratitude to that Divine Power, who rules all things,
and who does all things well.
I have indeed fresh cause to acknowledge his thus making a way,
where at one time no way appeared to open, for my help on the way to my own country.

Sixth-day, after breakfast and reading, I turned out to take my morning`'s ramble:
the thermometer sixteen degrees below freezing, the day fine,
and my mind more at rest than has been the case for some months past,
from the prospect of our soon being on our way to England: what a mercy it will be,
if I am favoured to reach it safely,
not knowing the dangers that may await us during so long a travel over-land,
at this season of the year.

Seventh-day, the weather not so severe, nor so congenial to my nerves.
I have sometimes thought twenty-four or thirty degrees below freezing,
as they sometimes have it here,
would suit my constitution better than the warm close
weather we have at times in my native land;
and I have felt rather desirous to witness one of these pinching days before my departure.

First-day, walked out to meeting; at the close of which was held the preparative meeting,
in which the queries were answered to Balby Monthly Meeting in Yorkshire,--the
Friends who reside here being members of that Monthly Meeting.

Third-day, I walked on the banks of the Neva, which was a very busy scene;
the crowds of people collected on the ice near the palace,
awakened in my mind great apprehensions of their danger.
This being the day for what is called the christening of the waters,
a ceremony performed annually,
I had observed for some time men employed in erecting
at the back of the palace on the ice,
an octagon temple, to which the people were now hastening in every direction:
this building, I was informed, was for the accommodation of the bishop and clergy,
who officiated in performing the ceremony,
with such of the royal family who are able to attend, which they all are expected to do,
if able.
I might have gone with the multitude, and be one in observing the ceremony performed;
but it appeared safest for me to bend my course directly home,
lest by going in the way of danger unbidden, I should get into difficulty,
which I should have escaped had I taken up the cross,
and not suffered my curiosity to prompt me to step aside out of the path of duty:
the Divine witness telling me in plain terms,
I had no warrant given me for countenancing such
superstitious proceedings by being a looker-on.

I was met the day preceding this ceremony by one of my countrymen, who informed me of it,
saying, the talk of the people is,
that the emperor has of late contrived to be on his travels at this time,
and so to be absent from the city; but he is now in Petersburgh,
and it will be as much as his life is worth, if he does not attend:
but neither the emperor nor his empress were present on the occasion;
they left the city for one of their country palaces
at a few miles distance the evening before;
which, perhaps,
was going as far as the emperor saw to be required of him
in bearing his testimony against this superstition;
but his absence did not pass over without remarks being made in consequence.
The ceremony of what is termed the christening the waters, I was informed,
is as follows:--a square hole is left in the floor of the temple,
and a hole cut in the ice to correspond with it; when the company are assembled,
a man by a rope lets down a pail through these holes,
and brings up water out of the river Neva.
The bishop then puts a crucifix into this pail of water, and uses some form of words;
after which the water in which the crucifix was immersed,
is poured through the hole again into the river,
and the credulous multitude are induced to think, that the water,
which the night before was unwholesome,
is now by this ceremony purified and rendered fit for use.

Seventh-day,
hearing that one of my countrymen who was intending
to go to England wanted company I made him a call;
it appeared probable that he would make one of our party,
which would be likely to add to our comfort by its
enabling us to have a carriage much to ourselves.
After my return home, I had some sore conflicts to pass through; the enemy,
who for a little season had been so chained down, as not to be able,
with all his efforts, to weaken my confidence in that Divine Power,
which had thus far directed my course,
and favoured me with strength to keep in the narrow path,
now appeared to be let loose upon me;
so that my situation from his varied suggestions and discouragements, might be,
I thought, fitly compared to fighting with beasts, or the nature of the beast:
but I was favoured to know the Almighty, in whom I had believed,
to be sufficient to keep me from becoming a prey to Satan,
and as I laboured after ability to maintain my confidence firm in him,
after he had seen meet that my faith should be thus closely tried,
he was pleased to speak peace again to my poor tribulated mind.

A messenger brought me a note from the prince Galitzin,
appointing this evening for me to make my visit to the emperor.
Some matters still continuing to press on my mind,
which were not ripe for communication when with the emperor before,
I am led to believe I must not now dare to withhold them from him;
although I am fully sensible they are tender subjects for me to meddle with.
The prospect of this visit has at times humbled me as into the very dust,
looking towards it with dismay,
lest I should fall short in delivering what I may be favoured clearly to see,
is the whole counsel of my Divine Master to this absolute monarch.
But in these seasons of tribulation I am bound in gratitude to acknowledge,
I have not been left destitute of the assurance,
that if I am faithful in all things which in the clear vision of light
are seen to be required of me in the winding up of this religious engagement,
all things will work together for my good.

Late in the evening, a carriage arrived from the palace,
and my former guide took charge of me.
On my arrival I was conducted to the emperor`'s apartment,
who received me with his usual affability, giving me his hand,
and seating me on the sofa beside him.
He then informed me that he had read the address to the inhabitants of Petersburgh,
which I had put into his hands, with the contents of which he was well satisfied.
I stated to him the impracticability of obtaining a translation of my address,
and having it printed in England.
I was fully satisfied if they came into the country they would be destroyed:
therefore as the emperor appeared willing to take the charge of it,
I did not attempt to prescribe any precise mode for him to pursue;
but only expressed the concern of my mind,
that he might be strengthened to seek after Divine wisdom in the right disposal of it.
In this expression of my feeling, he appeared fully to unite;
and in thus leaving the matter with him, my mind was favoured to experience peace.
On my saying, there were some matters of importance to the welfare of his dominions,
which I found I durst do no otherwise than lay before him,
although they might be delicate matters for me to touch upon; the emperor replied,
"`Why hesitate?
I am open to receive all you may have to say on any subject.`"

The way being thus mercifully made plain for me, for so I evidently felt it to be,
to the humbling of my very soul in deep prostration before the Lord, who had,
in the renewings of his mercy dealt with me,
I endeavoured in as concise and impressive a manner as possible,
to obtain full relief to my own mind: I endeavoured to keep under my exercise,
and as subjects were brought before my view,
strength was mercifully given me faithfully to acquit myself.
Amongst the subjects which I had to lay before him, one particularly was,
the very debased state of vassalage in which the greater
part of his subjects were held in bondage to others,
and the awful consequences that eventually must result from it.
This was a subject which I rejoiced to find had laid near his own heart:
he presented me with a small work on Colonization,
containing proposals calculated to bring about a remedy for this evil in his dominions.
I then adverted again to the punishment by the knout,^
footnote:[The knout was a heavy scourge-like multiple whip,
usually made of a bunch of rawhide thongs attached to a long handle,
sometimes with metal wire or hooks incorporated.]
practised in this country: in my former visit,
I had fully expressed my feelings of horror on this subject,
and I was then glad to find that it had occupied the mind of the emperor;
he inquired of me what other mode of punishment could be adopted,
that would be likely to work such a reformation in offenders as was desirable.
On my proposing to substitute the tread-mill,^
footnote:[The prison treadwheel was a long wooden cylinder with metal framing.
It was originally about 6 feet (1.8 m) in diameter.
On the exterior of the cylinder were wooden steps about 7.5 inches (19 cm) apart.
As the prisoner put his weight on the step it depressed the wheel,
and he was forced to step onto the step above,
so it was sometimes called an "`everlasting staircase`". There
would be 18 to 25 positions for prisoners on the wheel,
each separated by a wooden partition so each prisoner had no contact
with the adjacent prisoner and saw only the wall in front.
These drove a shaft that could be used to mill corn or pump water.]
it appeared to meet his ideas,
and I was led to ask if I might be at liberty on my return home,
to forward to him such printed information on the subject,
as my friends in England were able to furnish me with.
He replied, such information would be very acceptable,
it being his desire that reformation should be the object kept in view,
rather than what is deemed, the punishment of offenders.

In conversation afterwards with the merchant through
whom this information was to be conveyed to the emperor,
I learned that the society for the improvement of prisons in England, had,
a considerable time ago,
sent over to this merchant a complete model of the tread-mill in full work,
with figures placed on the wheel, to show its operation;
an order was at the same time received, that it should be presented to the emperor,
which order was produced to me;
but through fear on the part of the person to whom it was consigned,
this model was kept back,
from his having understood such a mode of treating
prisoners here would be warmly opposed by the police.
I informed the emperor of this circumstance,
requesting he would give me the liberty to forward it to him, to which he consented;
desiring it might be put up in a box, and sent to his secretary for him;
which was accordingly done.

Having felt my mind more at liberty, since my first visit to the emperor than heretofore,
to make a few calls before my departure,
I visited the Bible-printing and distributing office in the city:
having made memorandums,
from the information given me by one of the managers of the institution,
of the declining state in which it was,
I left the following copy thereof with the emperor:

[.embedded-content-document.paper]
--

The sales of the Holy Scriptures increased gradually until the year 1823;
since that time they have rapidly decreased; in the last half-year of 1824,
scarcely any orders have been received from the societies in the interior:
at present there are no orders, and no prospect of any; the sales in Petersburgh,
where there is free access to purchase, have been equal to preceding years; the funds,
also, are rapidly on the decrease, and were not the society obliged,
by its declining state, to part with many of their workmen,
they would not half meet the expenditure.
The Bible Society is now looked upon as a proscribed institution, and is quite deserted.
This cannot be wondered at,
as the central committee have not met for the last seven months;
the correspondence with the interior has almost entirely ceased; their Journals,^
footnote:[This Journal is a magazine that came out monthly,
giving a statement of the various proceedings of the Bible Institution,
and furnished with anecdotes of persons who, coming into possession of the Bible,
had found comfort from it, and to show that it was eagerly sought after by many.]
for the last two months have not been published,
owing to the manuscript copies being detained by the metropolitan bishop,
in whose hands they are placed for his signature before they go to the press.
I was shown eleven hundred copies of the first volume of the Old Testament,
which have been printed several months, and bound ready to be distributed;
but not a single copy is permitted to be sold:
out of twelve presses and two printing-machines,
which were in full employ until the beginning of the year 1824,
four of these presses only are now employed,
to finish the work that was in hand at the beginning of the last year;
the workmen have been gradually discharged, and when this work is finished,
the printing-office, unless a change takes place, must be shut up.
In the bookbinding department, the English journeymen are mostly discharged,
and are gone home:
those who remain are employed in repairing the books that were injured by the late flood:
when this work is finished, these will also be discharged,
and the book-binding office will be shut up.
Thus an institution considered, at the time, the finest of its kind in all Europe,
and which promised fair to be one of the means of drawing
down the blessing of heaven upon the Russian empire,
and the admiration of every sincere Christian, established at a very great expense,
is neglected and falling to decay; and while, it is said,
the people are anxiously desiring a supply of the Old Testament in their native tongue,
they are denied this privilege.
Seeing things are thus managed, may I not add the language of the Most High,
through one of his prophets, '`Shall I not visit for these things!`'

--

A full opportunity having now been afforded me to relieve my mind of all that I apprehended
was required of me to express to the emperor in the line of religious duty,
a pause took place; feeling myself constrained to kneel down in supplication,
the emperor went on his knees by my side: after rising from our knees,
and sitting awhile quietly together, the time for my departure being come, I rose to go,
and after holding each other most affectionately by the hand, he saluted me,
and we took a heart-tendering farewell.

Being conveyed back to my lodgings, and taking my seat in my apartment,
it was with great difficulty I could refrain from proclaiming
aloud my feelings of gratitude to Almighty God.
For a while, I felt like one lost in admiration; but afterwards,
the retrospect of what had fallen from my lips caused me to tremble; but in due time.
Divine goodness in mercy condescended to pour into
my heart such a portion of the wine of consolation,
as he best knew I was able to bear; for I soon became sensible a care was now necessary,
that I might be enabled to withstand the wiles of Satan,
as ever it was when my mind was under exercise for the service,
which I had been thus mercifully enabled to accomplish.
My bonds being now loosened, I felt nearly ready to take my departure.

First-day, I walked out to meeting; my mind felt so lightened,
that I seemed scarcely to feel the ground I passed over;
being ready to conclude those I met, who had before noticed my countenance,
must see relief now imprinted on it.
My friends participated with me in my feelings,
when I informed them how mercifully I had been cared for,
and helped through this second visit.

Second-day, I walked to a merchant in the city,
to fix for making a visit on the morrow to the prisons;
on my way home I had a very severe fall on the ice which I had to pass over,
which shook my whole frame to that degree,
that I feared for a time I should he disabled from enduring the journey before me.

Third-day, accompanied by my kind friend, I visited the two prisons for men:
the practice of reading the Scriptures daily to the prisoners is still kept up.
On its being announced that the reading was about to commence,
it was gratifying to observe the readiness with which the prisoners assembled,
and the quiet and order they manifested: they generally appeared clean in their persons,
and their apartments were in as good condition as
the nature of such places will allow of.
We next visited the prison for females.
Here also the prisoners were clean and well clothed,
and their countenances seemed to indicate, that they were well cared for.
Here reading commenced, which was also conducted in a solid, agreeable manner:
the men and women prisoners are generally employed.

From the female prison, we returned to one of the men`'s prisons: on our arrival,
we found fifteen convicts in an outer room, attended by a file of soldiers,
preparing to walk to Siberia, a journey that takes them one year to accomplish,
at the rate of fifteen miles a day, as I was informed:
some of them had irons on their legs, which they were to travel with, and which,
I was told, weighed fourteen pounds;
formerly the fetters worn by such prisoners weighed forty pounds,
but the present humane emperor had not passed over these abodes of misery,
in his endeavours towards relieving suffering humanity,
for he reduced the weight of their fetters to what they now are.
The prisoners were busily engaged in stripping off their own apparel,
and clothing themselves with coarse warm garments
of every description necessary for the journey:
their countenances appeared various,--some very hardened and inattentive to their situation;
others appeared sorrowful, and as if human nature would yield up life,
before they reached the end of their journey.
The distressed state of mind a young man manifested,
who I was told was one of the poor nobles, made such an impression on my mind,
that some days elapsed before I forgot him; he was loaded with irons,
in which he was to travel to the end of his journey if he ever reached it,
his eyes so red and inflamed with weeping, that it was truly distressing to look at him;
at times he appeared like one frantic, repeatedly exclaiming, in the Russian language,
"`Can nothing be done for me?`"
I understood the greatest cause of his distress was,
his having to leave behind him his aged mother, who was waiting to witness his departure.
He had been an officer in the army, and I was informed his offence was,
having struck his superior officer, for which he was sentenced to Siberia,
to work in the mines for the remainder of his life.
My friend had furnished himself with a Testament for each of the prisoners,
who generally received it as if they considered it a treasure,
putting it up carefully in a handkerchief;
the young officer in particular was at a loss sufficiently to manifest
his gratitude for this gift and companion in his miserable allotment;
he went down on his hands and knees to kiss the feet of his donor:
the scene altogether was distressing.
Before we quitted, I found I must venture to express a few sentences to them:
how far my friend`'s timidity suffered him to give the whole or not, I must leave,
and be satisfied that I was strengthened to do my part.
We passed the aged mother of the officer in the passage:
the sight of her occasioned me an aching heart.

Fifth-day, I walked to meeting,
and arranged matters for our departure--a subject
that was pleasant to us both to attend to.
A young man, a Russian, who was to be placed under our care,
and who was going to England for education, made the fourth in our carriage,
so that we had it wholly to ourselves.
I had made memorandums of my visit to the emperor,
but in such a way as if they concerned a private individual; which,
with a few other memorandums I had of late ventured to make,
I had sewed up in the lining of my fur coat, to bring along with me;
but on further considering this matter I thought, should I be searched at Riga,
as I was given to expect would be the case, being still eyed, as I believed,
by the police as a suspicious character,
the very concealment in this way of these memorandums might bring me into difficulty.
I therefore put all my papers and such of my letters as I had not destroyed,
into the hands of George Edmondson, to bring to England with him;
as he was coming by vessel no difficulty would occur.

Second-day, occupied with callers, packing, attending to my passport,
and making purchases for my journey.
This preparing to see my native land, my dear wife and children, felt consoling;
and especially so, having, as I believed,
an evidence that the time for making such preparation was fully come.

Third-day, I paid a visit to the Prince Alexander Galitzin.
During this parting interview,
I endeavoured faithfully to lay before him the state in which I found the Bible institution,
and the cause of its being now at a stand-still:
we parted under feelings of sincere regard as brethren,
however differing in name and external performances as to religion, yet, I trust,
earnestly desirous, that in our daily intercourse amongst men,
we might each be giving proof,
that our chief care was to be found fulfilling the Divine command to Abraham of old,
"`Walk before me, and be thou perfect.`"
This visit closed my services in this city.

I rode out to my kind friend Daniel Wheeler`'s,
in hopes of taking a quiet farewell of his family; but I had not been long there,
before I was followed by two of my countrymen;
I soon left the house to avoid interrogations,
which might have drawn from me that which was best
should not become a subject of general knowledge:
my visits to the emperor had been kept secret as much as possible,
for as they took place after dark, I proceeded unobserved.

Fourth-day, 9th of second month, I was thankful that the time for my release was come;
for I can truly say, after the first week I became a resident in the city,
I never retired to my bed with any degree of certainty,
that I might be permitted to enjoy it quietly until day-light in the morning.
This morning my friend Daniel Wheeler, the young Russian, the Englishman and myself,
left Petersburgh by sledge for Riga: this journey of about four hundred English miles,
we performed in four days and nights`' constant travelling,
except when we halted to change horses and take refreshment.

Our journey was impeded when within five miles of Riga,
by coming to a part where the wind had blown away the snow,
and left the ground quite bare; and as our sledge would not travel on the bare ground,
we were set fast for several hours.
Our vehicle was like two bodies of a single-horse chaise,
placed back to back on the sledge;
the aprons and curtains were in a very tattered condition,
so that the wind forced its way into our carriage, and when near morning,
the air was cold to an extreme; on this occasion our patience was tried,
for the drivers were not able, with all their shouting and beating of the poor horses,
to get them to move along.
Discouraging as our prospect was, and suffering as I did from the cold, fatigue,
and want of nourishment, the assurance was renewed,
if my feet remained sure in the narrow path,
rough and rugged as at times I should find it to be,
it would lead me safe to my native home;
I therefore endeavoured to do my best to keep quiet,
and cast all my care on that merciful Creator, who cares for the very sparrows.
After we had procured an additional horse we proceeded,
and at length reached our hotel at Riga, wanting food,
rest and refreshment for the weary body.

Pleasant as our arrival this morning was, yet my secret exercises were increased,
from my having been informed of the probability of my luggage
and person being searched by order of the governor,
who, it was stated, was a rigid bigot.
I had not to my knowledge any thing about my person or in my luggage,
except a large volume of the New Testament, given me by the emperor,
with his own signature in it, which I could conceive might subject me to difficulty;
yet should such a search take place, the fear of consequences,
and of undue advantages being taken of any default, of which, as a stranger,
I was ignorant, operated upon my susceptible mind.

Second-day morning, after a comfortable breakfast, we left our hotel,
and crossed the river Dwina; on the other side of which we were informed,
a coach would be waiting to convey us forward; but to my great disappointment,
our conveyance was a German wagon, fixed on the axletrees:
the curtains of this wagon were so tattered and worn,
that it was ill calculated to defend us against the intense frosty night-air;
but I found, if we went forward, we must submit to the inconvenience:
at the end of our first stage, we entered Courland,
when the face of the country began to improve.

On our arrival at Mitau, we took a fresh carriage,
but in no respects more commodious than the former.
We had not left Mitau an English mile,
before we found we had committed ourselves to a very drunken driver,
and a superintendent not much better:
whilst we were being driven over a bad piece of road at a very furious rate,
we lost our linchpin, and the hind wheel came off;
we could not prevail on our driver or conductor to
turn back and provide us with another carriage;
we were therefore obliged to submit and proceed,
yet not without serious apprehensions of danger, from the wheel coming off again,
having only a piece of wood out of the hedge to keep it in its place;
but we were favoured to reach our next station, without further accident,
where we changed our driver, and had our carriage-wheels properly repaired.
We felt thankful in being put under the care of a sober driver:
during this stage we reached the banks of a river, over which, with our heavy wagon,
four horses, eight persons, and our luggage, we were to cross on the ice;
the prospect of which was trying; but as it would not do for me to quit the wagon,
I besought the Lord to give me strength to acquit myself properly on this trying occasion,
and he failed not to confirm me in the assurance,
that he still continues to give power to the faint;
and to such as feel they have no might of their own,
and steadily look to him for help in the needful time, he condescends to give strength.
Gratitude filled my heart, when our carriage was safe on land again.

After travelling through a very fatiguing night, my dear companion Daniel Wheeler,
roused me towards day-break,
by informing me we were making our way towards another river,
which soon appeared in view; the state of the ice on which we had to cross,
appeared truly terrific; in many places a separation had taken place,
and from its rotten state the water was flowing over it.
At first I drew back;
to travel upon it appeared more than my feeble frame
and agitated nerves knew how to bear;
and yet, if my companions did so, it would not do for me to remain behind.
Divine mercy, however, in this time of sore trial,
graciously enabled me to cast all my care on Him, and brought before the view of my mind,
the manner in which I had been hitherto watched over;
thus was I enabled to take fresh courage,
and cheerfully concluded to keep with my companions.
The driver and superintendent, after consulting together for some time,
concluded it would be safest to take off the horses and turn them loose,
to make their own way across, and for us to keep the track which the horses took,
and by the help of some men, by tying a rope to the pole of the wagon,
and keeping at a distance from it, draw it over.
Our trials I was led to consider, great as they were,
might have been greater had it occurred in the dead of the night.
Observing a glimmering light on the other side of the river,
which we supposed to be the post-house, we made up to it,
truly thankful when we reached the house.

The first object presented to our view, was a woman far advanced in age,
with as care-worn a countenance as I ever remember to have seen,
spinning at this early hour in the morning,
by the light of a split stick placed in a piece of iron against the wall;
everything about her person and house bespoke the greatest possible indigence,
but much innocence was imprinted on her countenance:
after standing awhile and looking on her, as she also did on us,
I was inclined to put into her hands a piece of money equal to eight-pence;
which having done,
she seemed as if she hardly could believe the truth
of what she saw she was in possession of,
viewing it with surprise, and such a smile of gratitude as I have not often beheld:
my companions doing the like,
I expect she became richer than she had been for a great length of time.
Unable by words to express her gratitude,
she endeavoured to manifest it by attempting to kiss our hands and our clothes.
We felt not a little gratified,
that by so small a donation we had thus added to her present comfort;
the scene altogether, to me, proved a fresh excitement to number my blessings,
which appeared multiplied indeed, when compared with the state of this poor aged woman.

We proceeded on our journey, and after a day and night hard travel, on fifth-day morning,
the 16th of second month, we reached the frontiers of the Russian territories.
