== Chapter XXXI.

Seventh-day, 9th of ninth month, 1826.
I feel quite at home in my quarters, and every possible attention appears to be shown me;
nevertheless, sighing was almost the constant companion of my mind through this day.
It appearing safest for me to remain ignorant of the state
of things amongst Friends on this side the water,
I gave hints to callers on me to this effect, as suitable opportunities opened for it.
This circumstance I afterwards found excited alarm and occasioned
fears in the minds of some of my kind friends respecting me.
The followers of Elias Hicks had circulated a report,
that I was coming over to their help,
and that they should lay claim to me when I arrived.

First-day morning; after a refreshing night`'s rest,
I arose from my bed with my whole soul turned to the Lord in secret supplication,
that his preserving power might encamp round about me through this day,
of the approach of which I had felt a dread.
Feeling drawings in my mind to attend the meeting in Hester street in the morning,
I proceeded thither, under close exercise of mind to be preserved,
if called upon to advocate the Lord`'s cause,
from exceeding my commission on the one hand, and on the other to be found faithful,
by declaring what appeared to me to be the whole counsel of my great Master,
whom I desired fully to serve.
During my silent waiting before the Lord,
a feeling of reverent thankfulness sprang up in my mind,
that I had attended to what I believed was a Divine intimation,
before I left my own home,
and since my landing on this shore,--to remain as clear as possible from
conversing on the state of things amongst Friends on this side the water;
being satisfied my bow would be thereby strengthened,
and that suspicions of my speaking from information would be less likely to attach to me.
I found it hard work to rise upon my feet;
yet believing the offer of the best of all help was made, I ventured,
and was favoured to clear my mind faithfully,
and in a manner that I apprehend would give the followers of Elias Hicks,
a pretty clear idea of the mistake they had been under,
of my being come over to help their unchristian cause.
A Friend closed the meeting in solemn supplication,
and we separated under a humbling sense, that Divine Goodness had, in mercy,
again condescended to own His honest-hearted little ones in this part of the heritage.
Having drawings in my mind towards Rose street meetinghouse,
I proceeded thither in fear and trembling;
being aware of the danger of building our hopes for the future on any former experience,
and of the need there is of a fresh supply of Divine strength,
which alone is sufficient for every good word and work.
Feeling myself called upon to labour with the time-serving professors under our name,
He who, I humbly hope I may say, saw meet to call to the work,
gave ability for the faithful performance of it.
In the evening I received visits from some of my country-folks and other Friends;
and being much exhausted I retired early to bed.

Second-day; my way seems closed up as respects any future movements,
and yet I cannot see that I am to spend much time in the city at present.
May quietness, as a canopy, in mercy be permitted to be the covering of my mind;
that so I may be preserved from taking any premature step,
to escape any suffering that may be designed for me to pass through in this city.

Third-day,
having been informed that the Monthly Meeting of Purchase fell in due course tomorrow,
it obtained considerable place in my mind;
and my friends kindly arranged matters for my proceeding this afternoon,
it being a distance of about thirty miles from the city.
Accompanied by my kind friends, J. R. Willis and wife, we set off,
and reached the house of Hannah Field,
who had been very acceptably engaged in a religious
visit to the meetings of Friends in Great Britain,
by whom and her husband we were kindly received.

Fourth-day morning, we rode about two miles to meeting;
the number of Friends collected was considerable, but I understood,
on account of the season of the year, the meeting was smaller than usual,
the members of this meeting being chiefly in the farming business.
I felt well satisfied in giving up to attend this Monthly Meeting:
at the close I found I could not comfortably leave,
without telling Friends I had experienced great need to be especially upon my watch,
that no opportunity was suffered to pass by unimproved,
wherein ever so small a portion of Divine help was to be obtained;
feeling the need of a daily fresh supply,
and the assurance that opportunities of this sort would frequently be found,
if diligently sought after:
thus the pause previous to and after we have been
partaking of the bounties of Heaven at our tables,
if rightly improved, would often be a season,
in which a renewal of strength would be known,
by heavenly bread being dispensed to our minds;
as also where the practice of daily reading the Scriptures
in our families is properly attended to and conducted.
We returned to William and Hannah Field`'s, and on fifth-day, to New York.

Feeling drawings in my mind to attend Flushing meeting, on Long Island, on first-day,
a suitable caretaker was provided;
it being essential that my companions or caretakers should
be sound in the faith once delivered to the saints.

Seventh-day morning, 16th of ninth month, accompanied by Samuel Wood of New York,
we proceeded by steamboat for Flushing, to the house of Samuel Parsons,
whom we found to be much out of health;
we were affectionately received by his wife and son.
I felt afresh introduced into a very stripped state of mind,
accompanied with many doubts and fears,
how I was to travel in the path that now began a little to open before me.
In the afternoon, we took our tea with the widow Bowne,
who owns and occupies the residence in which George Fox
held the first meeting kept up by Friends on Long Island;
near to which are now standing, in a healthy state of preservation,
two very large oak-trees, under which the meetings used to be held,
when the house they first met in became too small to accommodate them.
Feeling drawings in my mind to have meetings with Friends on this island,
arrangements were made for my taking them one after another: this practice,
of thus purposely calling Friends together, felt trying to my nature;
and yet I could see no way but to submit to it.

At Flushing I found a considerable body of Friends; the meeting, to me,
was a very exercising one,
yet I was strengthened to clear my mind of what appeared to be
the burden of the word to some within the walls of the meetinghouse;
in doing which, I felt relieved.
After meeting, I went home to dine with a newly-married couple;
to whom I had to hold out the language of encouragement to suffer the
kingdom of heaven to become the first and principal thing in their pursuit.
In the afternoon we proceeded to Greatneck, in North Hempstead;
and in consequence of heavy rains, had a very dangerous road to travel,
but through Divine mercy we escaped accidents.

Second-day morning, visited a Friend who had been confined to her bed four years,
and is a striking example of patience under her accumulated sufferings.
These opportunities should be seasons of lasting instruction to us,
who are favoured to pass a long life free from such
humiliating interruptions to social enjoyment;
and ought to produce the inquiry in our minds, of "`How much owest thou unto thy Lord?`"
and how far it has been our chief care to make such returns,
as our Divine Benefactor is looking for from us.
Attended meeting at Cow-neck, which proved a quiet, satisfactory meeting:
I felt thankful I had given up to be at it.
Third-day morning, attended Matinicock meeting,
where I found a large body of Friends standing outside the meetinghouse;
and on entering it, many had taken their seats:
the prospect of such a company being called together at my request, felt awful to me;
I however endeavoured to attain to a state of mind in which I might be willing to become
anything or nothing amongst them,--either to sit in silence through the meeting,
or, if service was called for at my hands,
to endeavour after a faithful discharge of duty.
Two solid Friends, at the close of the meeting,
stood up and expressed the concern they had each been brought under,
that the weighty remarks which had been delivered amongst them at that time,
might be remembered, and that Friends would be willing to profit by them.

In the evening, we reached the habitation of our ancient friend, Gideon Seaman,
an elder in Society, truly worthy of double honour: here I met with my friend,
Henry Hull, who was once in our land on a religious visit,
and is now travelling with a minute from his own Monthly Meeting in Truth`'s service.

Fourth-day, being their Monthly Meeting at Westbury,
on our reaching the meetinghouse we found a large body of Friends assembled.
I took my seat in the gallery, under a feeling of weakness,
and great unfitness for service, more like one that required ministering unto,
than to be called upon to minister to others; my secret sighs were put up to Him,
who alone can preserve us in our right places, as labourers in the work of the Gospel.
In meetings for religious worship, and those for transacting the affairs of the Society,
I am more and more convinced, that unless the Lord build the house, or, in other words,
unless, in our attempting either to build or repair the waste places,
we wait to feel the renewings of the qualifying Spirit and power of Christ,
to assist us therein, our labour will be in vain.
By endeavouring to keep little and low in my own mind, suffering with the suffering seed,
which, if my feelings were right, was under bondage,
strength was mercifully dispensed in proportion to the labour called for;
and I trust that a door of entrance was opened in many minds,
to receive what was communicated.

We proceeded to Jericho, and took up our abode with our kind friend Thomas Willis.
In passing through the village of Jericho, Elias Hicks was at his own door;
he invited me to his house to take up my abode, which I found I could not do,
even had we not previously concluded to take up our abode with Thomas Willis.
I refused his offer in as handsome a manner as I well knew how.
He then pressed me to make him a call;
I was careful to make such a reply as would not make it binding upon me,
believing it was safest for me not to comply with his request.
During the evening, individuals who came to my lodgings,
intimated that a call from me would be acceptable, at the same time pressing it;
I rather hastily concluded on a willingness to comply;
but my mind afterwards feeling uneasy, and desirous of being rightly directed herein,
by quietly retiring to that sure place of waiting,
where the Divine Counsellor is to be met with, and his still,
small voice distinctly heard,
and known to prevail over all the reasoning powers of man`'s wisdom,--this word of caution
was intelligibly proclaimed in the ear of my soul,--"`Keep out of the way of temptation.`"
I therefore relinquished this conclusion, and in doing so I found peace.
I afterwards understood some of these individuals were of Elias Hicks`' party.

Fifth-day morning, as meeting-time drew nigh, my exercise increased,
accompanied with such feelings of fear as I have not often experienced.
Earnest desires attended my mind,
that I might be faithful if called upon to offer any thing in the meeting.
I went to meeting and it settled down into quiet.
It evidently felt to me that there were watchers in the meeting,
who would watch my words, if possible, to turn them to their own account,
in order to help the unrighteous cause they were aiming to promote:
notwithstanding which, I was borne above these discouragements;
and when the time was fully come, was enabled to stand upon my feet,
and declare what appeared to me to be the word of the Lord,
in a close searching testimony.
After I had taken my seat, Elias Hicks stood up, saying,
"`I have been renewedly confirmed in this meeting, that our God is a God hearing prayer;
it was the prayer of my heart in sitting down in this meeting,
that as we had a dear friend with us from a distant land,
we might be edified and instructed by his ministry.
How fully has the prayer been answered,
how clearly has he been led to set forth the efficacy
and sufficiency of the Divine light,
as ye have often heard it held up in this place;
I appeal to this assembly if it is not the same doctrine,
that ye have heard these many years past.
I unite,`" said Elias Hicks, "`with the words of John Locke,
'`Outward testimonies may deceive, but internal evidences cannot err.`'`"^
footnote:[It may be useful, both as caution and information to Friends,
to give an extract from a letter written by a much esteemed Friend of Philadelphia,
to the author of the Beacon, soon after the appearance of his book, in America,
which will show what Elias Hicks meant by the phrases "`Divine
light`" and "`internal evidences.`"
{footnote-paragraph-split}
"`There is a natural tendency in the human mind,
when not under the regulating power of the Spirit of Truth, to run into extremes;
and under such circumstances, it often happens,
that in our zeal against a certain class of errors, we lose the true medium,
and slide into those of an opposite character.
{footnote-paragraph-split}
Such,
I apprehend, has been the case in writing this book, the Beacon.
In thy anxiety to expose the monstrous errors of Hicksism,
and to guard Friends against the dreadful consequences which must result from it,
thou hast suffered thy mind to be carried away by a false,
though specious train of reasoning;
and concluded that the precious Scripture doctrine
of the sensible guidance of the Holy Spirit,
was the cause of the awful delusion,
which unhappily spread over so large a portion of our Society here.
I am as strongly opposed to Hicksism as any one;
and I have had sufficient acquaintance with it and its advocates, to know,
that it was not the belief of the aforesaid Christian doctrine,
but a gross perversion and abuse of it,
which produced and spread the delusion of Elias Hicks and his followers.
It was going from this doctrine, and trusting to the strength of his own reason,
and in this state studying the Scriptures to find arguments to support his unbelief,
that carried him away;
and after thus bringing himself to disbelieve the truths of Christianity,
he then made use of the doctrine of the light within,
as a cloak to conceal the deformity, of his infidel opinions,
the more easily to insinuate them among his hearers.
{footnote-paragraph-split}
"`But with all his pretensions to the guidance of the light of Christ,
he united with thee in rejecting it; for I know well from my own acquaintance with him,
that he believed in nothing more than human reason;
which was what he meant by the term he so often used--"`immediate revelation;`"--declaring,
that without it, we should not know a tree from a horse,
nor a horse from a man.
{footnote-paragraph-split}
It was
therefore the rejection of the doctrine of Holy Scripture respecting
the guidance of the Spirit of Christ in the soul of man,
which led him into his errors; and this undeniable fact ought to be a solemn warning,
to all those who are tempted to fall into the same error,
of rejecting the safe and certain guide, which in the mercy of a gracious Creator,
has been kindly dispensed to us.
It is one of the subtle stratagems of the enemy of souls,
to beguile and deceive the members of our Society by the false notion,
that the doctrine of the light within leads to Hicksism; for,
having failed to sweep away the Society by the floods of infidelity,
and seeing that those who are left are clean escaped from that pit,
and abhor its pollutions,
he is now trying the more plausible and specious plan of misrepresenting
and perverting the true Christian doctrines of Quakerism;
and thus, by his lying insinuations, persuading them to desert that doctrine,
and turn back again to the carnal and formal profession and views,
out of which they were redeemed.`"]]

The above was given me by a Friend of the meeting who was present,
and made memorandums of what passed.
So far from this snare taking with me, for so I have since viewed it,
I was disgusted with the remarks of Elias Hicks,
for which I often think I cannot be sufficiently thankful.
A recurrence to this subject brought fresh to my
remembrance the prospect I had when on ship-board,
in which I saw, after my landing, a man approach me,
full of combustible matter to pour out upon me;
but Divine mercy protected me from the harm that then awaited.
I began now to see clearly the absolute need there was,
to take strict heed to the injunction given me before I left my own home,
of "`Go not from house to house;`" and to be especially careful
to feel that it was safe for me to go where my friends proposed;
for I was aware that Elias Hicks and his party designed, if possible,
to enlist me into their unchristian-like service.

Sixth-day morning, 22nd of ninth month, we attended the meeting at Bethpage,
where we had the company of Anna Willis and her son Thomas,
which was a great comfort to me.
This meetinghouse is placed pretty much in the centre of a small full-grown wood;
the horses are tied to the trees round about the meetinghouse:
everything had a rustic appearance,
a simplicity that would be likely to strike a stranger as I was.
Friends gathered more irregularly than I had yet observed on this side of the water.
I had to tell them,
"`if solitude and a retired situation would secure for them good meetings,
they were in a peculiar manner privileged, to what such were, who,
when they meet together for the purpose of religious worship,
meet in the throng of thickly-settled cities and towns;
but to have good meetings we must come together with
hearts and minds devoted to God out of meetings;
without which there could be no presenting our bodies a living sacrifice, holy,
acceptable to God, which is our reasonable service.`"
The rude and idle manner in which some of the men and lads sat,
had so attracted my attention,
that I found it would be unsafe for me to suffer the meeting to separate,
and not lay this subject before the members, which I endeavoured to do in a tender way;
recommending Friends to bring the young men and lads up to the top of the meeting,
that they might be more under notice than was the case where they now took their seats.
Some of the members of the meeting acknowledged the necessity
of such steps as I had proposed being taken.

In the afternoon we proceeded to Jerusalem: on entering the meetinghouse,
as my view was only to Friends, I was apprehensive they had not attended to my request,
and that we should have a crowd of such, as do not usually attend our religious meetings;
but this I afterwards understood was not the case.
The meeting was held in a private house; it was a newly-settled meeting,
and the last which Solomon Underbill attended,
in which he was acceptably engaged in the exercise of his gift;
although feeble in body from advanced age,
yet he was strong in his attachment to his great Master`'s cause,
which he boldly pleaded through much suffering;
he had been brought forward as a delinquent by Elias Hicks and his party,
who made up by far the greater part of the meeting,
with some other members of Jericho Monthly Meeting,
because they durst not unite with Elias Hicks in his unsound doctrines.
After meeting, Samuel Wood and myself rode to Hempstead.

Seventh-day morning, we left Hempstead for Flushing,
hoping to reach New York this evening;
on arriving at the house of our friend Samuel Parsons, we were informed,
that the corpse of a Friend, whom we had left in a very weak state of health,
when we were there before, had then left the house in order for interment; I had hoped,
after such a succession of exercise,
we should be permitted to proceed quietly to New York.
Our bodies needed some refreshment, but time would not allow of it,
unless we disturbed the meeting by going in after it was settled;
we therefore proceeded to the meetinghouse, where I took my seat,
bowed in spirit under a sense of great poverty and strippedness,
perhaps as much so as I have at any time known: but as matter opened on my mind,
and a willingness was wrought in me, strength was afforded to disclose it to the meeting.
After the meeting closed, apprehensions were awakened in my mind,
that my desire to reach New York this evening might be disappointed;
having some fears that I should be obliged to return to Jericho,
and attend their first-day morning meeting;
but after weighing this matter in the best way I was capable of,
and my mind being brought to be fully resigned to
go back to Jericho if it really were required,
I felt excused from this bitter cup, and we proceeded on our way to New York;
which place we were favoured to reach safely early in the evening.

First-day, attended Rose street meeting.
It is trying to my nature to refuse the importunity of my friends to visit them,
my natural disposition being open and communicative;
but I am satisfied with the caution given me by my Divine Master,
before I left my own home,
and from time to time repeated since,--"`Go not from house to house.`"

Fourth-day, 27th of ninth month, attended Rose street meeting;
at the close of the meeting for worship, the preparative meeting was held;
apprehending I was now favoured with a more clear prospect of future movements,
I informed the preparative meeting that I believed it would be right for me to
attend some of the meetings within the compass of Purchase Quarterly Meeting;
and then to proceed to attend the Quarterly Meetings,
with such of the Monthly and other meetings as fell in course,
belonging to the Yearly Meeting of New York.
This information appeared to obtain the solid and
weighty deliberation of some minds in the meeting,
and a general concurrence with my views was expressed:
some members of the meeting were accordingly nominated to
provide the necessary accommodation for my travelling;
who were requested also to turn their attention toward
a Friend as a suitable companion for me.

Fifth-day, attended Hester street meeting:
I felt truly thankful my lot was cast amongst Friends of this meeting,
it being a memorable time to many of us, in which it might truly be said,
by the living members of the body,
we were favoured to witness a being baptized together into the one, eternal,
invisible Spirit; and in degree permitted to partake of the same spiritual meat,
and to drink of the same spiritual Rock, which rock is Christ,
by his inward and spiritual manifestations to the souls of such,
as in simplicity and godly sincerity continue to look up to him.

Sixth-day, through close exercise of mind, and much bodily indisposition,
I had a trying day.
In the evening many Friends dropped in to see me: after awhile conversation ceased,
and a sweet quiet ensued, during which, we were favoured afresh to witness that He,
who in mercy condescended to visit our forefathers in the beginning,
when we were first gathered to be a people,
is still in mercy continuing to manifest himself to be near to us;
to help us in the faithful support of those Christian testimonies,
and in the promulgation of those Christian principles, which they were made instrumental,
in the Divine hand, of spreading as from sea to sea,
under great and sore travail of mind, subject to great deprivation of bodily comforts,
and even to great sufferings: under a grateful sense of His mercy this evening closed,
and a fresh call was proclaimed in the ear of my mind, "`Bless the Lord, O my soul,
and all that is within me bless his holy name, and forget not all his benefits.`"

First-day morning, 1st of tenth month, 1826, rode to Manhatten-ville,
about five miles out of the city, and attended meeting there;
this being only an allowed meeting,
a committee of Friends of New York were under appointment to attend it,
in addition to the small number of Friends who reside in the neighbourhood.
For a time after I took my seat, I had much suffering of mind to endure,
through a fear I had missed my way in leaving the city.
I endeavoured after as correct a view as possible of my motive,
without being able to see otherwise than that it was pure,
having but one desire in my so doing,
which was that I might be found in the way of my religious duty.
I believe it right for me thus to record and expose my various trials,
for the help and encouragement of those who may come after me;
not doubting but that such seasons of probation are
permitted in great mercy to attend us,
in order that they may prove the means of inducing us to try the fleece,
both wet and dry.
After endeavouring patiently to bear these provings of mind,
deliverance came from that all-bountiful hand, who, when he pleases, says,
"`It is enough.`"
When the meeting closed, I felt thankful I had given up to sit with Friends here;
it proving a solid opportunity.

Feeling drawings on my mind to attend the afternoon meeting in Hester street in the city,
we were favoured to reach the meetinghouse in seasonable time;
the meeting was very largely attended.
There was good ground for believing, that it proved a solid,
satisfactory opportunity to many; some, I had no doubt,
left the meetinghouse under an evidence of the comforting, solacing presence of Him,
who remains to be the resurrection and the life to his humble dependent children.
In adorable mercy,
he condescended to fulfill his gracious promise to those gathered
in his name,--that he would be in the midst of them;
this being mercifully granted, the mind is relieved from anxiety about instrumental help.

From the mixed state of many Friends`' families in this city,
some sound and others unsound in our principles,
it requires great circumspection in visiting them:
the latter generally giving abundant proof of their having a life in argument,
and being very forward in attempting to introduce their unsound doctrines on all occasions,
and not generally strict in keeping to the truth,
when they report any part of a conversation that may have taken place between them and
such as cannot unite with them in their erroneous views of subjects of vital importance.

Third-day, attended the monthly Select Meeting;
but through giving way on the part of a few of its
members to listen to those unsound principles,
which are now industriously propagating by Elias Hicks and his adherents,
this meeting has become like a house divided against itself.
It proved a suffering meeting,
there appearing no way for the relief of the sound members of this meeting,
but patiently to wait the full time when the Lord shall see meet to effect their deliverance.

Fourth-day, attended Hester street meetinghouse, where the Monthly Meeting is held.
When the queries had been answered, Samuel Wood, who had kindly offered to accompany me,
and drive the horses, informed the meeting thereof,
and it appeared to settle down quietly under the consideration of the subject;
much expression of concurrence was made;
but an opposing spirit manifested itself on the part of the disaffected members,
who objected to Samuel Wood`'s accompanying me.
This brought the meeting under considerable embarrassment,
and placed me in a very trying situation.
I informed the meeting Samuel Wood`'s former services had been very acceptable to me;
after which, I found my safety was in sitting, and silently hearing what passed,
without any further interference;
the oppositionists continuing warmly to object to
Samuel Wood`'s having a minute to accompany me.

After much time being spent on the subject, there appeared no other way to proceed,
than by submitting the consideration of providing me with
a companion to a standing committee of the Meeting for Sufferings,
which I afterwards understood consisted of four Friends,
two of whom were with the sound part of the Society,
and the other two in league with Elias Hicks and his party.
I thought I might truly say, I was brought into a very strait place,
and for a time saw no way for my help,
believing unless Samuel Wood was permitted to accompany me,
I should not be able to prosecute my religious engagements
in visiting the meetings of this Yearly Meeting;
but the opposition to his going was conducted with such determination,
I could not see how this difficulty was to be got through.
A glimmering of hope unexpectedly opened before me, that,
if I endeavoured to keep in the quiet,
and avoid giving way to unnecessary anxiety under my present trials,
the way would open for my enlargement,
however great the improbability might appear at present;
and that I should know the Lord`'s power to be all-sufficient to preserve
me from the dangerous deadening influence of this opposing spirit,
which, acting under the control of the prince of the power of the air,
works in the hearts of the children of disobedience,
and which was in a most sorrowful manner, dividing in Jacob, and scattering in Israel.

Sixth-day,
I found that my being disappointed in my prospects
relative to my kind friend Samuel Wood,
had excited great sympathy, both in the city and elsewhere, amongst Friends;
but being preserved in the quiet since the Monthly Meeting,
I thought I felt it required of me to request my
friends not to cherish any anxiety on my account;
believing that when the time was fully come,
way would be made for me to pursue my journey;
and that it would be unsafe for me to enter into conversation
relative to what had passed in the Monthly Meeting;
because, trying as this disappointment had felt to me at the first,
a quiet submission on my part would be more likely to help me,
than any thing of my own contrivance or activity.

Seventh-day, on my return home from collecting a few articles necessary for my journey,
a Friend came to inform me,
that Adam and Anne Mott were intending to be at Cornwall Quarterly Meeting,
and were willing to take charge of me thither and back again to New York.
This offer I felt most easy to accept for the present.

First-day morning, attended Hester street meeting, which was large,
and several weighty testimonies were borne:
my lot was to endeavour to promote in some minds a willingness
to look to the Divine Counsellor in themselves,
that they might be favoured to see that rotten foundation,
on which they were building their views of religious matters,
and thereby risking their eternal happiness.
Although I found it hard work to obtain relief,
yet fresh cause was felt to set up the Ebenezer, to the praise of Him, who,
when he calls to the work, gives strength for the performance of it,
although at times greatly to the abasement of the creature,
that He alone may have the praise.
In the afternoon I sat with Friends at Rose street meeting, which was small:
in the evening several Friends came to my quarters to take their leave of me;
we had a quiet solid sitting together, affording some relief.
My mind had been much tried after the close of the afternoon meeting at Rose street,
and I was unable to understand why;
for I could not see but I had been in the way of my duty, in standing upon my feet,
nor had I kept back any part of what was given me for the people,
or added any thing of my own.
Trying as this baptism was to human nature to endure, yet I felt thankful for it;
and for that Divine support which I experienced whilst labouring under it,
not doubting but that such dispensations are intended in mercy, to humble the creature,
that so all boasting may be excluded,
and that all praise may be given to the Father and his Son Christ Jesus,
to whom only it belongs.

Second-day, 9th of tenth month, 1826. Accompanied by Adam Mott and his wife,
I left my comfortable abode in the city:
we were favoured safely to reach Richard Mott`'s this evening.

Third-day, we attended the Select Preparative Meeting of Mamaroneck;
a quiet and comfortable meeting.
Fourth-day, we attended the Monthly Meeting, which was large.
The service called for at my hands was comparable
to that of entering the cellar of a large old building,
to examine the foundation on which it stood,
and search out the decayed stones and rotten timbers in the foundation,
in order that they might be removed;
that so way might be made for sound materials to be placed in their room.
In the Monthly Meeting it appeared evident,
that unsoundness of principle had made inroads on the minds of some who were busy-bodies,
and took an active part in the concerns of society,
thereby standing in the way of such as were qualified to
come forward and lend a helping hand in the discipline.
The day closed peacefully; in the evening we rode to our kind friend Esther Griffin`'s,
where we took up our abode for the night.

Fifth-day morning, was very stormy, which was discouraging,
as we intended to be at the Monthly Meeting of Shapaqua, about seven miles`' ride;
and proceeded accordingly.
In the meeting for worship,
I had to open the state of things amongst Friends of this meeting,
in such a pointed manner, that when I took my seat I was plunged into discouragement,
fearing what I communicated had proceeded from the transformations of the evil one.
Gladly would I have made my escape from the meetinghouse,
could I have done it with propriety; but endeavoured to settle down into the quiet,
that I might be favoured to come at a true sense
how far my movements had been in the vision of light.
An elderly Friend stood up, and in a solid,
feeling manner expressed his concurrence with the plain truths that had
been delivered amongst them by a stranger from a distant land,
and the desire he felt that the labour which had
been bestowed might be profitable to them.

After meeting, we rode to the house of Moses Sutton, at Croton Valley,
and took up our abode for the night.
On recurring to the baptism I was introduced into in the meeting for worship,
after I had been engaged in religious service,
I thought there was cause for thankfulness on my part,
although it was to the creature most humiliating;
but the assurance attends that it was permitted in great mercy to humble me;
and earnest were my cravings that the same Divine mercy and lovingkindness,
that had thus permitted me to be tried and proved, would not spare me;
but continue to make use of such means, from time to time,
as were necessary to keep me truly humble,
in a state of nothingness and entire dependence upon Him,
who alone remains to be a covert from the heat, a shelter from the storm,
and the shadow of a mighty rock in a weary land, when the blast of the terrible one may,
for the trial of our faith in our holy Redeemer`'s power,
be suffered to come up against our walls: thus closed this day.

Sixth-day morning, we proceeded to Amawalk meeting.
I felt cause for thankfulness in being introduced into that state of mind, which,
if abode under, would prove preparatory to receiving the wine of the kingdom,
should my Divine Master see meet to dispense a portion of it either for my own consolation,
or to mete out for the comfort of others.
We understood the meeting was not so largely attended as generally is the case:
much close exercise of mind and religious labour fell to my lot;
but as faithfulness obtained the ascendency over that fearfulness which is of the creature,
the reward of peace was the result.
Testimonies were borne by some Friends of the meeting, at its close,
in confirmation of the plain truths that had been delivered amongst them.
I was given to understand, that reports were in circulation in this Quarterly Meeting,
of my being closeted with Elias Hicks for an hour,
and that I had declared to a member of Society, who was one of his adherents,
that the state of things amongst Friends in England, when I left it, was worse,
with respect to the prevalency of a separating, dividing spirit, than in this land,
and that the followers of Elias Hicks had brought me over to their party.
Although I well knew all these reports to be utterly false and unfounded, yet,
on my first hearing them, they occasioned me some painful feelings,
not knowing how they might have a tendency to block up my way in the minds of some Friends.
I thought of endeavouring to have them cleared up;
but taking the best view of the subject I was capable of,
it appeared safest for me to move quietly forward, and mind my great Master`'s business;
under an assurance, that these false and unfounded reports,
would in time remedy themselves: and here I was enabled to leave this painful matter.

Seventh-day; after an early dinner we left Amawalk towards Peek`'s-kill,
and lodged at the house of Abraham Carpenter.

First-day morning, we attended Peek`'s-kill meeting.
In the afternoon we walked about two miles to take tea with a Friend`'s family,
where we found a number of young people: conversation occurred, in which I took a share,
until I found I could no longer take any interest therein,
and yet I feared to give way to the feelings my mind was brought under,
lest I should get into a habit of preaching when not called upon;
and through a fear of this sort,
I kept silence until some of the company rose to leave the house,
which obliged me to request them to take their seats again,
and strength was afforded me to obtain relief.
I returned in the evening to James Brown`'s, with a peaceful mind.

Second-day, 16th of tenth month; we proceeded on our way to Cornwall Quarterly Meeting:
reached Canterbury, the residence of the widow of David Sands,
who spent many years in the service of Truth in Old England.

We attended the Select Quarterly Meeting for Cornwall,
which appeared to be composed of some solid weighty Friends,
who manifested a lively zeal for the preservation of soundness in this part of the body.
As I endeavoured to stand resigned to be anything or nothing,
the Lord mercifully condescended to be near for my help,
enabling me to rejoice under a sense of the sufficiency of his
power to give strength for the performance of the work whereunto,
I humbly hope I may say, I felt his renewed call.
The Quarterly Meeting commenced with a meeting for worship, which was largely attended.
The meeting for discipline was greatly disturbed by many young
men coming into the meetinghouse in a noisy and rather rude manner:
after it had become settled again,
feeling an engagement of mind to speak publicly to them relative to their conduct,
I endeavoured to do it in as affectionate a manner
as the nature of such an offence allowed of;
which, I had reason to believe,
was a relief to the rightly exercised members of the meeting.
Cornwall is a newly settled Quarterly Meeting;
the members of it at one time formed a part of Nine Partners`' Quarterly Meeting.
The summary manner in which the queries from the Monthly Meetings were answered,
brought me under the necessity of casting before
the meeting the views I had on this subject.
This appeared to give courage to others, who before had kept silence,
to express their uneasiness with this practice,
which the Monthly Meetings had fallen into.

The meeting was brought under considerable exercise,
that in future the Monthly Meetings should be more explicit in answering the queries,
and a minute was made to go down to the Monthly and Preparative Meetings,
to induce a compliance with the views the meeting had taken on the subject.
Observing that the men`'s meeting was drawing to a close,
and my mind continuing to be exercised with a subject in
which the women were equally concerned with the men,
I requested, if agreeable to the men`'s and women`'s meeting,
that the shutters between the two apartments might be raised,
which took place accordingly.
In obtaining full relief to my own mind,
I was brought under the necessity of going more into
particulars than felt pleasant to my natural inclination;
yet there was fresh cause for me to say,
hitherto the Lord hath been my stay and my support; to him be the praise given.
The concluding meeting for worship was held the next morning, which was largely attended,
and proved a favoured time,
closing with solemn prayer and thanksgiving to Almighty God for his unmerited mercies;
in that he had been pleased once more to manifest his regard
towards the members of this Quarterly Meeting;
under a grateful sense of which Friends separated.

Seventh-day, 21st of tenth month,
we rode to Jonah Odett`'s. The road over the mountains
not admitting of a carriage to travel upon it,
we were obliged to take another route, which made our journey about twenty-seven miles,
and a part of the road was so very bad, that it appeared at times dangerous to proceed.
I endeavoured after patience, under a belief no harm would be suffered to befall us;
and we were thankful when favoured to reach the Upper Clove in safety.

First-day morning: we proceeded to Cokeatt meetinghouse,
about one mile and a half distant,
but the road was worse than any we had travelled the day before.
There are very few members to keep up this meeting, yet,
others coming in who do not profess with our Society, we had a considerable attendance:
in the evening Jonah Odett`'s family was collected,
and after the opportunity of reading closed, a pause took place; when counsel,
I humbly trust,
suitable to the states of some of the younger part of our company was handed out,
which I was ready to hope, would not be lost.
We were much comforted in being in this family,
and the solid manner in which the evening was passed,
rewarded me for giving up to attend this meeting.

The next day, my companions and myself proceeded towards New York,
a journey of about forty miles,
which place we were favoured to reach late in the afternoon; here we parted,
having myself been most kindly and affectionately cared for by them.

Third-day; during my sleepless hours last night,
some of my future prospects of religious duty occupied my mind,
and not being able to look to any one for a companion but my friend Samuel Wood,
I endeavoured to dwell patiently under the weight of this subject,
when Truth appeared to me to point out the propriety of having
the standing committee of the Meeting for Sufferings called together,
to whom was referred the care of providing me with a companion,
of which number I found Samuel Wood was one;
and that it would be proper for me to attend,
and lay before them the trying situation I was placed in,
no reason whatsoever having been brought forward
for objecting to Samuel Wood`'s being my caretaker.
I opened the views I had of this subject to a few suitable Friends,
all of whom concurred with me herein;
but it appeared best to leave the summoning of this
committee until I returned again to New York,
after I had attended the Quarterly Meeting of Flushing on Long Island.

Fourth-day morning: accompanied by Adam and Anne Mott, I proceeded to Flushing,
on Long Island, to attend the Quarterly Meeting,
and was kindly received by Samuel Parsons and wife.
The Select Quarterly Meeting began this morning: the queries were answered,
but in such a summary way,
as to render it difficult to come at the true state of this part of the Society;
these answers were passed over by the members of this meeting in silence.
I found I must lay before Friends the loss which meetings
sustained by answering the queries in such a summary way,
as it opened a door for smothering up wrong things,
which might at times creep into this part of the body.
From the answers brought up, it was clearly manifest,
that a breach of love and unity existed in one of the Select Monthly Meetings,
and that these wounds were so deep, as to proclaim the language, that help was wanting.
Although I felt that there would be great opposition
made by a party in the meeting to taking such a step,
+++[+++the appointment of a committee,]
yet I durst not do otherwise than propose it.
This was warmly objected to,
but by the weighty solid part of the meeting it was united with; divers Friends saying,
that attempts had been made to have a committee formed to visit the Select Monthly Meetings,
but such a measure had been uniformly opposed.
The prospect of Truth`'s prevailing over this spirit for awhile was cheering,
but such a determination to quash the proposal manifested itself again,
that this hope was almost lost sight of; and yet it did not appear right to Friends,
who had the welfare of Society at heart, that it should be too easily abandoned.
Friends were encouraged by some well-concerned strangers present,
to maintain their standing with becoming firmness.

While this subject was agitated,
the mournful desolation that prevailed in the Select
Monthly Meeting of Jericho became more exposed,
by those of that meeting who warmly opposed a committee being appointed,
and a scene of oppression was developed,
which would have pierced the hearts of most present.
These things strengthened the hands of the sound members of the meeting,
in their apprehension of the need of a committee being now appointed,
to visit the Select Monthly Meetings;
and Friends endeavouring in patience to maintain their ground,
Truth prevailed over opposition, and a committee was obtained,
to the relief of the sound members of the meeting but not until we had
sat together from ten o`'clock in the morning till five in the afternoon.

The next morning the Quarterly Meeting for discipline commenced:
the answers to the queries brought up from the Monthly
Meetings were couched in such general terms,
as rendered it difficult to come at a correct statement
of the situation of the Monthly Meetings;
but it appeared in the present state of this Quarterly Meeting,
nothing could be done to remedy this mode of answering.

Seventh-day was spent in packing to prepare for the journey before me;
and the way now clearly opening for it, I requested that the committee,
who were entrusted with the care of providing me with a companion, should meet,
and that I should be allowed to sit with them during their deliberations.
I endeavoured to open to the committee my trying situation,
having left my native land to visit Friends on this continent,
and no prospect opened of any Friend as a companion so suitable as Samuel Wood;
besides I should not feel myself bound to accept of a companion,
though proposed by the committee, with whom I could not fully unite.
These remarks appeared to make some impression on the mind of one of the
individuals who were opposed to Samuel Wood`'s going with me.
The committee commissioned one of their company to
lay the matter again before the next Monthly Meeting,
and to see that some Friend took charge of me to Purchase Quarterly Meeting.

First-day: attended Hester street meeting in the morning and Rose street in the afternoon.
In the latter meeting I sat under much silent suffering, until at the close,
when my mouth was opened in a few words:
in the evening we had a large company at my quarters, mostly young people:
a time of solemn quiet took place.
