== Chapter XXXIII.

Second-day, 18th of twelfth month, 1826, we rode to Rochester, a newly-settled city:
in the evening, whilst sitting in the family with whom we abode,
my mind was brought under religious exercise, accompanied with matter for communication;
but conversation was so continually kept up,
I felt unequal to come at that quiet my soul longed for, in order to obtain relief.
I retired to bed, sad although not sick,
a state of mind the Christian traveller must expect to be frequently baptized into,
if a real desire continues alive in the soul to be
made willing to suffer for and with Christ,
whilst he continues to be under suffering and persecution in the
hearts and minds of so many among us in the present day;
this I believed I was given to see and understand,
was sorrowfully the case in this meeting.
A hope was awakened in my mind, that if I was careful to watch for it,
an opportunity might be found, should my exercise continue with me,
at the close of our taking breakfast next morning;
but by the coming in of persons of other societies, no quiet could be attained:
this free access to the private apartments of Friends in this country,
which those of other societies are allowed,
is a great interruption to the orderly conducting of families,
and I doubt not injurious at times to both parents and children,
by the hearing of conversation inimical to their best welfare.

The next morning, we took our leave of the family who had kindly entertained us,
and proceeded towards Hartland this night, and lodged at an inn.
We continued our journey, and reached my kind countryman, Michael Robson`'s,
in time to attend the Select Monthly Meeting in the afternoon.
Attended the Monthly Meeting the next morning, which was held in a log meetinghouse:
the meeting was not fully gathered until an hour after the time appointed,
which had a very unsettling effect.
I was constrained to endeavour to awaken the attention of
the well-concerned members of the meeting to this subject,
to consider if something more was not required than had been done towards a remedy:
what service I had amongst them was humiliating to the creaturely part,
yet I trust I had no cause to be dissatisfied with that which had fallen to my lot.

I had requested my kind companion, Samuel Wood,
to inform me when we were in the neighbourhood of any of the Indian settlements;
this I found was now the case,
and that the settlement of the Tonawonta Indians could be taken on our way to Canada,
whither we intended soon to bend our course;
I also learnt that there were Friends attending the Monthly
Meeting who resided about nine miles from this settlement,
and who were well acquainted with the Indians of the Tonawonta tribe,
by being at times called upon to be in council with them,
when any matters of importance between them and the white people claimed their attention.
These Friends being spoken to on the subject,
very kindly offered to give us any assistance in their power towards collecting them;
but on turning the subject over in my own mind,
I durst not give expectation at present of my being likely to accept of these kind offers.

Sixth-day morning: after rather a sleepless night,
partly occasioned by the exercise of mind I was brought under,
that I might be rightly directed in the matter respecting the Tonawonta Indians,
and not have to return again, after I had passed the road that led to their settlement,
we proceeded towards Lockport through the woods, on a new road.
Little more, however, appeared to have been done to this road,
than cutting down and clearing away the trees for carriages to pass,
and making a few ill-contrived bridges,
by laying trees across some of the worst of the swampy
places which we must otherwise have passed through;
these trees were placed the reverse of what they should have been,
and some of them were so far apart,
that the wheels of our carriage very narrowly escaped
dropping down between two of these trees.
Some of the mud-holes we had to go through were so deep, it was difficult for our horses,
when appearing to exert their utmost strength, to raise us out of them again:
a large tree had been blown down across our road,
which at first sight threatened to impede our journey,
but as no other way appeared for our help, we were obliged to risk our wheels,
and exert our endeavours to get the wagon over it; which having accomplished,
we pursued our course by a letter H which we found cut on the trees,
denoting where the high road lay to our place of destination,
which we were favoured to reach in safety.

The next morning, we made a visit to a sick Friend, and a few other calls:
I was led to hope our time thus spent had not been unprofitably passed over,
either to ourselves or to those we visited.

First-day morning; we attended meeting at this place; it was a new settlement of Friends;
the meeting was held in a log meetinghouse and was much crowded by Friends and others.
I almost despaired, for a considerable time,
of our being able to arrive at such a quiet settlement in our minds,
as to be favoured with any thing like a qualification to
perform the important duty we professed to be met about;
but I humbly hope it was experienced by some of our company.
I felt thankful when it closed,
that our lot had been thus cast with Friends of this meeting.
We dined with a young couple--had a sitting in the evening in their family;
and thus this day closed, in addition to those gone before,
to account for to a just and a jealous God,--an awful consideration.

A very heavy fall of snow occurred during yesterday and in the night;
the prospect of our proceeding towards Canada looked very discouraging,
not knowing whether it would be better to take our wagon,
or procure a sledge for our accommodation; but on consulting our friends on the subject,
they advised us to continue our wagon.
Being given to understand, that on our way to Lewis town,
we should pass very near a settlement of the Tuscarora Indians,
this brought me into fresh exercise; yet I was preserved in a calm, quiet,
and resigned state of mind, should we be called upon to make a halt at this settlement,
and thus was I enabled to pass the remainder of the evening comfortably,
under a hope I should be favoured, if I kept simple enough in my views,
as we approached near to this settlement, clearly to see what steps, if any,
were to be taken towards having a meeting with them.

Third-day morning, 26th of twelfth month, we began our journey towards Lewis town:
my mind being preserved in quietness, and not disposed for conversation,
afforded an opportunity of endeavouring to come at
a clear sight of what would be right for me to do,
when we arrived at the road that led to the settlement of the Tuscarora Indians.
We halted at a tavern, where I told my friends that I feared to pass on,
and yet the prospect of a meeting with them appeared discouraging,
from the probable difficulty of our being able to procure a suitable interpreter;
but after all, I was willing to leave my friends to do what to them appeared best:
on which my companion and our guide proceeded towards the settlement,
to ascertain if a suitable interpreter could be found,
and if the Indians could be collected tomorrow morning.
After a shorter absence than I at all expected, they returned, informing me,
that they had met with an aged man, who lived in the settlement,
and acted as interpreter,
who engaged to give notice of the meeting to be held in
their school house at ten o`'clock tomorrow morning.

Fourth-day morning, the snow continuing to fall heavy,
and the cold being so very intense that it was said to be thirty degrees below zero,
made the prospect of our having the Indians collected discouraging:
on our arrival at the schoolhouse, no Indians were assembled.
We proceeded to the log-house of the interpreter, who assured us,
notice had been given of our intention; but as the morning was so stormy,
and the cold so severe,
it was doubtful whether many of them would venture out to the meeting.
During our sitting with the interpreter, he gave us some account of his son,
who had been long confined at his home through sickness.
From the impression made on my mind, I proposed to make him a visit,
and we proceeded to his log-house; found him a cripple in his limbs,
but kindly cared for by his mother and family,
and he understood the English language well.

After some time spent with him in conversation,
I found it best for me to endeavour after silence, and when he put questions to me,
to give as short a reply as I well could;
and watching my time to express that which it appeared
to me was given to lay before him for his consideration,
and the future government of his conduct.
He appeared to settle down quietly, and ceasing to put any more questions,
afforded me a full opportunity to relieve my mind; and at our parting,
expressed in a feeling manner his thankfulness for
the counsel that had been communicated to him,
and the desire he felt,
that the Divine protection might go with me and conduct me safely to my own home.
I thought if nothing further resulted from our coming to this settlement than this visit,
I was well rewarded for it.
We returned to the interpreter`'s house,
but none of the Indians had arrived at the schoolhouse;
it being now past eleven o`'clock,
and knowing how slow the Indians are in their movements,
we concluded it would be best for us to wait until
twelve o`'clock before we took our departure.
Whilst we were waiting in the interpreter`'s house, some Indians came in,
whom I requested to take seats, and we dropped into a short quiet:
that which I had to offer amongst them appeared to be well received,
and at our parting they manifested signs of thankfulness for our visit.

We then proceeded on our way to Lewis town,
and after refreshing our horses and ourselves,
having suffered not a little from the intense severity of the weather,
we concluded to cross the Niagara river to Queen`'s-town this evening.
The access to the ferry-boat is down a very steep road, covered with ice,
and having no guard at the side of it nor at the foot,
which is very near the edge of this deep river,
I could not divest my mind of apprehensions of danger.
Our horses with all their care, could hardly keep their footing as they went down,
so that it appeared miraculous the carriage did not overpower them;
but we were favoured to reach the bottom in safety.
The next difficulty to be encountered was,
to get the horses and carriage into the boat and out again,
but to my humbling admiration,
we were favoured to land safely on the shore of Upper Canada:
gratitude clothed my mind to Him, who remains, as He ever was,
sufficient to enable his creature to bear all things and to endure all things,
when in humble confidence he is made willing to cast his care wholly upon Him,
who is God over all, blessed forevermore!
We had another great steep to ascend to the custom-house, which,
after such a day of severe travel, was exercising to us and heavy upon the horses.
After passing the custom-house, we proceeded to our inn,
in hopes of meeting with good provision and comfortable beds,
after the difficulties which we had encountered.
I could not doubt, but the keeper of our inn was disposed,
as far as his means would allow him, to do his best;
our provision was not to be complained of, but our fire was so scanty,
our lodging so miserably cold, and we were so sparingly supplied with covering,
that I passed an uncomfortable night.

Fourth-day morning,
we rode several miles to the tavern at the Niagara Falls to breakfast;
we observed at a distance of at least five miles,
the mist rising like a large white cloud in the air,
from the immense fall of water that passes over this wonderful production of nature;
and we were assured, when the wind is favourable for it,
the roaring noise could be heard eighteen miles.
After refreshing ourselves and our horses, we proceeded towards Black creek;
the snow was now so deep on the ground that our horses had hard work to drag our wagon;
after much patience and perseverance,
we were favoured before dark to reach the house of a Friend, at Black creek,
who undertook to have a sledge provided for us to pursue our journey.

First-day morning, we attended Black creek meeting, where I had hard things to deliver,
yet I felt comfortable under the renewed assurance,
that Divine mercy is still following the gainsayers amongst us,
in order to bring them back from that state of captivity to outward ease, indifference,
and a life of indulgence to the creature,
which many amongst us are giving proof that they
have sunk into,--sitting down fat and full,
and kicking at those Divine reproofs which continue in mercy to be following them.

Fourth-day, 3rd of first month, 1827, I attended the Select Monthly Meeting;
but it was an hour after the time appointed before our little company, of five in number,
assembled: this circumstance occasioned the answers to the queries,
which were brought to the meeting ready prepared, to be hurried through.
The Monthly Meeting for business followed this meeting,
commencing with a meeting for worship, which was largely attended by Friends,
and some few persons not in profession with us:
the answers to the queries occupied considerable time,
a desire being manifested by a few well-concerned Friends,
that the true state of the meeting should be forwarded to the Half-year`'s meeting:
the meeting closed to a good degree of satisfaction.

The next morning, our sledge being in readiness for us,
we proceeded on a road newly-cut through the woods, about twenty-three miles to Pelham;
a kind young man offering to take the charge of driving us,
we gladly accepted his services, which spared us much anxiety,
from the difficulties we should have had to encounter
with our new vehicle in making our way with safety,
the road being barely wide enough in places for our sledge to pass,
and the most crooked and having the sharpest turns we had yet met with.
Stumps of trees were standing close to the road, some three feet high,
and we had great difficulty to avoid being upset from the
jolts occasioned by coming in contact with them:
trees also were lying at times across the road,
over which we were obliged to make our way in the best manner we could;
my back and shoulders suffered severely from the shocks I received.
I felt truly thankful when we arrived safely at Pelham.

Our sledge required some more covering over our heads than we had been provided with,
to secure us from the inclemency of the weather, which we found was increasing;
and after we had this attended to, we proceeded on our journey, accompanied by a Friend,
who took the charge of driving our horses.
Our road today lay pretty much through the woods.

Seventh-day, we rode twelve miles to breakfast:
our track this day was chiefly through the woods,
which at this time of the year make a very dreary appearance.
I did not feel disposed to join much in conversation on any subject,
my mind being turned inward unto the Lord for his counsel in my future movements.
At Ancaster, the place to which we were going,
I understood there was a small settlement of Friends, and an allowed meeting;
and about ten miles further, a settlement of the Mohawk Indians.
My companions appeared to be looking towards our sitting
with Friends at Ancaster in their usual meeting tomorrow,
and, if I should feel it right, to visit the Mohawk settlement, to do it on second-day,
and send forward a messenger to the settlement to inform them to that effect:
although the subject had much occupied my attention,
yet it appeared best for me to keep quiet until we should reach our quarters at Ancaster,
which we did about noon, and were kindly received.
I took my seat in our temporary abode in solemn silence,
in which state of mind I was mercifully preserved,
until I was able to come at some clearness as it respected my future movements.
I soon found the arrangement of my companion was
in accordance with the view of Friends at Ancaster,
but contrary to the prospect which opened in my mind; and I ventured to say,
if I had a meeting with Friends of Ancaster, it must be that afternoon or evening,
and proceed tomorrow morning early to the Mohawk settlement.
This plan I observed appeared to try the Friends of Ancaster,
who were desirous we should pass the first-day amongst them.
I hope I may say, I endeavoured again to give the subject all due consideration;
but no way opened in my mind but that of pursuing my first prospect of duty:
the evening was agreed upon for the meeting at Ancaster, and notice given.
Friends met in a common sitting-room in a private house.
Soon after taking our seats, I felt not a little disappointed,
in observing that my request, in regard to giving notice, had not been attended to,
but that information of the meeting had been spread far and wide in the neighbourhood:
the people coming in,
we were soon so closely packed together as to render the air of the room very oppressive,
and occasioned the infants to be very restless; a great fire had been made up,
which not a little increased the oppressive state of the air.
A hope accompanied my mind when we separated,
that this meeting might prove of lasting benefit to some of our company,
and that my movement had not been in my own will.

First-day morning early, we proceeded to the Mohawk settlement,
about two miles from the Grand River bridge.
Understanding that some Friends who had visited this settlement before,
had received attention from the children of the late Captain Brant, an Indian,
we proceeded to the house of his widow; but to our great disappointment,
found she could not speak or understand English, so as to be any help to us;
the gravity of her countenance and her solid deportment raised regret in my mind,
at not being able to converse with her.
Being advised to proceed to the house of Dr. Henry Aaron Hill, who also is an Indian,
and has acted as an interpreter when Friends have had meetings in these settlements,
as the distance for us to walk was considerable,
and the snow in places very much drifted, my kind companions proposed my staying behind.
But I have always found it tended most to the peace of my own mind,
with the kind assistance of my friends, to follow up my own business,
and share with them in the difficulties as long and as far as my nature will hold out,
and we accordingly proceeded to the house of Dr. Hill.

On our arrival, we found he was absent from home: his man, who could understand English,
on hearing our business, recommended us to go to the house of the chief,
about half a mile further.
On our entering the hut of the chief, he appeared to receive us with marks of pleasure,
and spoke English well.
On hearing the business that had brought us to the settlement,
he manifested his full approval of our views,
informing us that Dr. Henry Aaron Hill and the Episcopalian
preacher lately sent over from England,
would be at the widow`'s of Captain Brant before
they went into the Indian place of worship,
at which the English preacher officiated.

We accordingly made our way there as speedily as we were well able,
in order to ascertain if a meeting could be obtained in their place for religious worship,
as it had been free for Friends aforetime,
and to consult the doctor as to the best time for its being held,
with the manner of giving notice.
After waiting at the widow`'s, the preacher from England and Dr. Henry Aaron Hill,
who acted as the preacher`'s interpreter, came:
my companion proposed to me to give them my certificates to read,
which I accordingly did: after they had read them,
I gave them to understand what had been my views in coming to the settlement;
on hearing which, my countryman, the preacher,
demurred as to our having the use of the Indian place of worship.
A person present queried with him,
if there had not been a precedent to justify such a grant?
To which the doctor replied, not only as it respected Friends,
but also as it respected other religious professors,
the use of the house had been hitherto granted them; notwithstanding which,
the Episcopalian preacher manifested his decided determination
we should not be indulged with this privilege;
we therefore proposed holding a meeting in the schoolhouse next morning.
It appeared evident to us,
the doctor would gladly have given us permission if it had been in his power.
He kindly offered to give notice of the meeting to be held tomorrow,
at the close of their worship today, and to meet at the schoolmaster`'s house.
Previous to the meeting,
my companions expressed a belief this day`'s work would not all be time lost,
with which my mind could fully unite: the countenance of the Episcopalian preacher,
whilst reading my certificate,
I thought evidently manifested that some of the expressions
he met with therein touched him to the quick,
although he opposed our having the use of the house.
Having thus far done all in our power towards our views being accomplished,
we rode to Burford, and were kindly received,
and I was favoured to have a comfortable night`'s rest.

Second-day morning, we proceeded to the settlement:
on approaching the Indian place of worship, observing the window-shutters opened,
and the bell ringing,
I was ready to conclude the preacher had recanted his former opinion;
but this we found was not the case,
but that the doctor had given orders for the bell to be rung,
to give notice of the time of the meeting.
Several male and female Indians assembled;
our interpreter appeared to give what we had to offer,
in a manner that led me to hope he felt some of the weight of it;
and from the solid countenances some of the company manifested at our parting,
I was encouraged to believe our visit would not be altogether in vain.

The next day we left Burford, and proceeded to Norwich.
In consequence of the divided state of this Select Monthly Meeting,
it had been dissolved by the Half-year`'s meeting,
and such of the members as retained their stations
were united to the Select Meeting of Yonge-street.

Fourth-day morning, the meeting for discipline was preceded by a meeting for worship,
which was largely attended, but much interrupted by late comers-in,
and the great number of dogs that were brought to the meeting place,
barking most of the meeting-time: but,
alas! as the business of the Monthly Meeting proceeded,
I found there was much more to try the rightly-exercised mind than these things.
It soon became manifest,
that the enemy to all right order in religious society had
obtained a place in the minds of not a few of the members,
and that the meeting was become like a house divided against itself:
and unless a remedy be soon applied, there appeared no other prospect,
but that it must be dissolved, as had been the case with the Select Monthly Meeting:
the meeting sat six hours,
not because of the multiplicity of business that came before it,
but from a want of unanimity in transacting the concerns of the Society.

On sixth-day, 12th of first month, we left Ancaster, on our way to York,
and made a halt at the residence of a man who once had been in membership with Friends.
When he understood how we were engaged,
he inquired if I intended to make a stop amongst them and give them a sermon;
this matter being mentioned to me by one of our company for my consideration,
I thought I could truly say there was no answer from my Great Master
that would have justified me in taking such a step;
and therefore we moved forward and lodged at an inn.
The Messasagua tribe of Indians had at times come before me,
and occasioned me some exercise of mind;
understanding we were in the neighbourhood of a settlement of part of the tribe,
the subject again came weightily before me.

The next morning, we rode thirteen miles, and breakfasted at an inn,
which afforded us an opportunity of making inquiry respecting the road to the settlement,
and the individuals who had the most influence in this portion of the tribe.
While these inquiries were going on, I felt so stripped and emptied of all good,
that the prospect of proceeding to have a meeting with them felt very humiliating;
and yet I found I must stand resigned to it,
if I preserved a conscience void of offence in the sight of Him,
before whom every knee must bow,
and every tongue confess that Jesus Christ is Lord over all.
Having received the necessary information,
we pursued our journey towards the river Credit,
where this part of the Messasagua tribe reside: the depth of snow, the unbeaten road,
and a large tree lying across it, so impeded our progress,
that I feared we must turn back again; but our driver so skillfully managed this matter,
as to get our horses and sledge over the tree,
but not without some suffering to ourselves from the jolt.
Soon after we entered a road grown over with trees and shrubs,
and one of our company was under the necessity of resorting to our axe,
which we carried with us, and to cut our way through;
but my mind was preserved quiet through these trials of faith and patience;
and on leaving this narrow pass,
we soon found ourselves entering upon a part of the settlement.
Agreeably to the direction we had received, we proceeded to the house of Peter Jones,
an Indian of half-blood; he spoke English well;
we had previously been informed he was a pious man,
and a preacher in connection with the society of Methodists.

On reaching his habitation, we found it clean and well furnished,
which appeared to be generally the case in this settlement,
as far as our observations extended,
everything about it manifesting marks of civilization.
He received us with cordiality: I presented him with my certificates,
and when he had read them,
I opened my prospect of a meeting with the Indians in their settlement;
to which he unhesitatingly replied, there would be no difficulty,
showing us their meeting-place.
He went to the door of his house, blew his horn a few times,
soon after which I observed the Indian men and women,
the latter wrapped in their clean blankets, as is their custom,
making their way towards the meetinghouse.
Not more than half an hour had elapsed, from the time of our first arrival,
before our kind friend Peter Jones informed us he believed the meeting was now gathered;
and taking the lead, we followed him.
The building is commodious for the purposes for which
it was intended,--a meetinghouse and schoolhouse,
equal to accommodate nearly three hundred persons:
the women were seated on one side of the house, by themselves,
and the men on the other side,
the youth and children seated immediately under the notice
of the preacher and the more aged Indians of the settlement,
in order to have the oversight of them during the time of religious worship:
the solid deportment of both the men and the women was very conspicuous.

Feeling myself called upon to stand upon my feet, my kind friend, Peter Jones,
rose with me, delivering in the Indian language, sentence by sentence,
what I had to offer to the people, and in a disposition of mind,
that evidently proved he was brought under the weight of the task he had to perform:
we had reason to believe what we had to deliver amongst
them had found place in their minds,
from the tenderness that was manifested when the meeting closed:
under feelings of gratitude for that help we had
been in mercy favoured with from our heavenly Father,
we separated.
This we were informed was the first visit of the
kind that had been made to the settlement by Friends.
I felt thankful when taking our leave of our worthy friend, Peter Jones,
and this part of the tribe,
in believing we had left an open door for such of
our friends as should hereafter feel a like concern.
From the acknowledgment made of the satisfaction the meeting had afforded them,
and the desire expressed that we might have them in remembrance when absent,
I left the settlement well satisfied we had not passed them by,
and made our way through the woods into the main-road,
taking up our abode for the night at an inn.

First-day morning, we rode to York to breakfast, and concluded it best,
as there was no meeting of Friends in this place, to remain at our inn during the day,
as quietly as our situation would allow of,
except making a visit to an individual who once had
a claim to membership in my native land.
I had been informed, there were several serious persons in the town,
that no difficulty would be found in having a meeting,
and that the town`'s people were expecting it.
I hope I can say in truth, I stood quite resigned to have taken such a step,
could I have seen with clearness it was called for at my hands.
Some of the company at our inn, who became acquainted with my errand to this country,
queried with me, if I did not mean to have a meeting in the town; but I informed them,
that except I felt differently from what I had yet done on that subject,
I must pass quietly away tomorrow on my journey: my answer produced this query.
Why were they to be passed by?
From my own feelings,
I might have replied,--perhaps they had more of a desire to hear than to practise,
for this felt to me to be much the case: in the evening,
we had a very relieving opportunity with the only member of Society here,
and his motherless children.

I was glad the way clearly opened for us to quit York the next morning,
it being the time when the session of parliament was about closing,
and a great deal of party spirit, we understood, was at work in the minds of the people,
whereby the town was kept in continual bustle,
and much appearance of gaiety and dissipation:
we were favoured to reach Yonge-street before dark.

Fourth-day, attended the Select Monthly Meeting, which was very small;
after the close of it, I was favoured to return to my quarters with a peaceful mind;
thankful for the strength that had been mercifully vouchsafed to me,
and comforted in a hope that faithfulness had marked my movements.
We were much importuned to divide our time amongst Friends hereaway,
and dine at one place, take tea at another, sup at another, and so go on from day to day;
but being afresh warned by the good Remembrancer, that if I expected to escape danger,
I must attend to the salutary caution I received before I left my own home,
of,--"`Go not from house to house,`" with feelings of gratitude I yielded to the warning,
leaving my kind companions at liberty to accept or reject such invitations as they pleased;
but I kept close to my quarters: in which, I afterwards had clearly to see the safety,
from the sorrowful manner in which unsoundness of principle had developed itself;
having spread over nearly the whole of this meeting.

Fifth-day morning, 18th of first month,
my inward plungings for a time felt hard to the creature to bear; yet,
as patience was laboured after,
they proved the means in the Divine hand of preserving me from joining in that
wide field of conversation which took place at our quarters before the meeting,
and which I have ever found has had a tendency to unsettle and scatter the mind,
and divert it from its true centre and entire dependence on that Omnipotent arm,
which alone is able to prepare us for the performance of Divine worship,
or for rightly taking an active part in the affairs of the Society.
The meeting for worship was disturbed by the unseasonable manner of its gathering.
The meeting for discipline lasted six hours; the spirit of disaffection and of party,
was evidently to be felt at work in the minds of not a few of the members of the meeting,
which in due time was fully manifested to be the case.

We next rode to Pickering.
The way opening with clearness in my own mind,
I ventured to call upon two families of Friends in the neighbourhood, natives of Ireland,
and a young couple; in all of which there was a call for religious service;
the day closed peacefully.

First-day morning, attended the usual meeting held at this place;
at least one hour had elapsed before the meeting could come at any degree of
settlement from the members of the meeting being so unseasonable in their attendance,
some not coming in until near the time the meeting closed.
I sat and mourned under a sorrowful sense of the prevalency of this evil practice
amongst the members of our religious Society in this wilderness part of the country.

We the next morning left Pickering, intending, if possible, to reach Alderman that night,
a journey of fifty-two miles: stopping on the road to take our dinner at an inn,
we had the company of our kind friend Peter Jones, the Indian of the Messasagua tribe.
Meeting again appeared to be mutually consoling to our minds; on inquiry,
he informed us he was on a religious visit to a settlement of Indians in the neighbourhood:
it appeared he was known to our landlady and her family,
and from their conduct towards him was held in esteem.
They urged him to stay and have a meeting with them, adding, perhaps,
he might do as much good there as going to the Indian settlement; to which he replied,
with very great apparent diffidence,
perhaps he might take a meeting with them on his return;
his countenance and whole deportment bespoke the gathered state of his mind to
the one only qualifying power for religious usefulness amongst mankind:
we parted under feelings of much affection, and proceeded on our journey,
and were favoured before it was quite dark to reach our quarters.

Fourth-day morning, we attended the usual meeting held at Ameliasburg, which was small.
I felt satisfied in sitting with this little company,
and left the meeting under a fresh occasion of gratitude,
for the help that had been given me to acquit myself faithfully.
Before we separated, a Friend stood up under much apparent exercise of mind,
exhorting Friends not to try to put away from them
the truths that had been declared that day;
for if there was not a willingness to receive that which had been offered,
it would redound to their own great loss in a future day.
Thus Divine goodness at times condescends to permit the poor, weary,
disconsolate traveller to receive a word of encouragement,
it feeling like a cordial to my mind.

We rode to Westlake, and intended to go to Grassy-point meeting next morning,
which we had been informed was only eleven miles distant, but now we were informed,
that we were eighteen or twenty miles from it.
The frost being more severe than had been known for several years, the days short,
and the snow in places very deep, all combined to discourage our proceeding;
some Friends also expressed their doubts about its being meeting day in course at Grassy-point,
which involved my mind in yet greater difficulty: but, after all,
I found nothing would do for me, but to labour to surmount it, and proceed.
This being concluded upon, a kind Friend offered to drive our horses,
and we gladly accepted his services.

Fifth-day morning, we proceeded on our way before sun-rise:
I had passed a sleepless night, and found myself in a very feeble state as to the body,
and not much otherwise in my mind:
we rode about six miles to breakfast at the house of a Friend,
where we found some promising young people, and a man advanced in life, a visitor,
who was so talkative that it seemed almost impossible to come at any quiet.
I felt something stirring in my mind towards the young people,
but as our time was circumscribed, and this man continued intrusive in conversation,
I saw no way for me but to say a few words in the midst of his conversation;
on which silence took place,
and my mind was favoured to obtain relief. We proceeded on our way,
and reached Grassy-point in time for meeting, which fell in due course this day.
The meeting was very small,
but I felt well satisfied we had pressed through these difficulties
to sit down with the little number we found gathered there.

26th of first month, 1827.
Understanding there was a large settlement of the Mohawk Indians in this neighbourhood,
and feeling drawings in my mind to have a meeting amongst them,
I opened my prospect to Friends, who informed us,
a Friend had recently had a meeting amongst them.
This led me to hope they were not so much under the control of the Episcopal
clergy as I found was in some instances the case with the Mohawks,
with whom we had obtained a meeting.
Some Friends kindly offered to proceed to the settlement,
and inquire whether a meeting could be obtained;
but feeling as I apprehended that it would be most likely
to afford peace to my own mind if I accompanied them,
I made the proposal; to which one of the Friends replied,
there was the bay of Quinton to cross upon the ice, about a mile and a quarter over:
at the hearing of this, I was at the first not a little dismayed,
but I found I must yield and proceed with them.
On our first coming upon the ice, I involuntarily exclaimed aloud,
"`Into thy careful keeping, O thou Preserver of men,
I commit this poor body of mine!`" the prospect of
this undertaking appearing to me awful;
for we had not travelled far on the bay before our
horses were up to their knees in snow and water,
our sledge plunging first on one side and then on the other, as if we should be upset.
Although I never lost my confidence in the sufficiency of
Divine power to preserve from harm amidst the greatest dangers,
yet my flesh contracted a soreness I cannot describe.

We were favoured to land safely at the settlement;
but then we had to return the same way, and were informed,
we must expect to find the places we had thus travelled through worse on our return.
We proceeded to the schoolhouse, at which we found the school-master, with his scholars:
on our informing him of our business at the settlement, he told us,
with apparent regret on his part,
that the archdeacon of the Episcopalian clergy had recently written to him a letter,
forbidding any dissenters having meetings in that settlement,
and that their place of worship was wholly under his control.
On inquiry, I found they had not been visited by the archdeacon,
who was the only person in attendance upon them, for two months;
and that the Indians stood so much in awe of him,
that if a meeting were appointed any where in the
settlement they would be afraid to attend.
The probable cause is that the archdeacon has the control of what
are called their presents when they are handed out to them,
which is the interest due for land purchased of them by the English nation,
and paid them in articles of clothing, blankets, etc.

My mind was deeply affected on reflecting upon this conduct of the archdeacon,
who had taken upon himself the religious care of this portion of our fellow creatures,
and yet was in an almost total neglect of them;
and would not suffer such as might feel their minds interested in their best welfare,
to attempt to do their part towards their improvement.
We found about twenty Indian children under the care of a school-master,
who appeared to be a well-conducted man: two of his scholars were full-grown lads,
and pretty good English scholars.
I observed the copy that one of them was writing contained the word "`godliness.`"
Feeling it laid upon me to ask the lad,
if he correctly understood the meaning of the word "`godliness,`"
I found him very diffident in giving his reply,
yet, it was evident the question,
put to him produced some serious sensibility in his mind:
whilst I was engaged in explaining to him my views on this all-important word,
others of the scholars, as well as himself, appeared to give attention.
I endeavoured to impress on his mind the great need there was for him, now in early life,
to aim to be found daily living a life of godliness, which he would be enabled to do,
if he was willing to accept of God`'s offered help;
and that this would be the way for him to be fitted for heaven and happiness,
when he came to die.
The tears fell from his eyes,
and a degree of solemnity manifested itself on the countenances of others of the children.
I felt well satisfied with the time we had spent with the master and the scholars,
and that it was well worth encountering the danger I thought we had been carried through,
and yet had to encounter.
I could but hope our labour would not be all lost on the lad,
and some others of the scholars; and that our visit to them, although so short,
would at times come up in their remembrance.
We left the school again, and proceeded towards the bay: on our return,
the snow and water was considerably above our horse`'s knees,
and we so rocked from side to side, that our driver,
who was well acquainted with the pass, told us,
he expected no other but that we should have been upset in the deepest of it;
the water flowing up through the cracks in the ice occasioning this difficulty.
After I had endured no little trepidation of mind, yet,
without loss of confidence in the outstretched arm of Omnipotence, I felt truly thankful,
not only for our safe arrival on land again,
but increasingly so for having been preserved from giving way to discouragement,
or declining to accompany the Friends across the bay to the settlement.

First-day morning, attended meeting at Adolphus town, which was small:
I felt well satisfied in sitting with Friends;
and in the afternoon proceeded towards Westlake again, and reached Holloway.

Third-day morning, we were favoured to reach Westlake,
after having much difficulty to encounter from the snow and severe cold;
attended the Half-year`'s Select Meeting, which was very small,
considering this Half-year`'s Meeting is composed of four Monthly Meetings:
the travelling being so very difficult, had, no doubt, in degree,
contributed to prevent a more general attendance of its members.
The state of this part of the body,
as shown by the answers to the queries brought up from the Select Monthly Meetings,
was very discouraging;
and to look for an improvement in the circumstances under which
the Society is labouring,--the prevalency of unsoundness of principle,
a disposition to undervalue the Sacred Writings and wholesome discipline,
felt to me like hoping against hope;
and that little more at present could be done by
the members who were preserved alive in the Truth,
than to bear their portion in lamentation,
because of the desolations that prevail in the camp;
for truly it may be said of this part of the heritage,--"`Death
is come up into our windows,
and is entered into our palaces, to cut off the children from without,
and the young men from the streets.`"
The prospect of a succession of faithful standard-bearers,
from the present conduct of the youth, is rendered discouraging.
By endeavouring to acquit myself faithfully in the discharge
of the little that I was entrusted with to communicate,
I was favoured to leave the meeting peacefully, which is an ample reward.

Fourth-day, 31st of first month,
the Half-year`'s Meeting for discipline commenced with the meeting for religious worship:
the morning proved very stormy, and the snow fell in such abundance,
that the meeting was very long in gathering;
and from the great number of infants which were I
expect of necessity brought to the meeting,
I very much feared our being able to come at any quiet.
But having aforetime found from experience, that when placed under such circumstances,
much depended on my aiming to attain to quietness in myself,
and having my mind and attention as much as possible
abstracted from every outward object and vocal sound,
I endeavoured after this inward quiet,
and found the declaration still remains to be a truth, "`As is thy day,
so shall thy strength be.`"
An adjournment took place to the close of the meeting for worship tomorrow.

Fifth-day morning, the meeting for worship was largely attended by Friends and others,
with a great train of infants;
some of whom would not be restrained from running about the meetinghouse,
others manifesting a fretful, impatient disposition to get out of their confinement.
Notwithstanding these impediments to that quiet so desirable in religious meetings,
by endeavouring to have my mind as much as possible
brought into resignation to my present allotment,
the meeting closed under a thankful sense that the
arm of Omnipotence had been near for my help,
whereby I had been enabled to bear things which otherwise
would have tried me much in this meeting;
and I have learned afresh the lessons of patience and forbearance with others, who,
in the outward, were differently circumstanced to myself.

Sixth-day morning, my very kind companion Samuel Wood,
feeling his mind drawn towards his own home,
being pretty much exhausted and worn down in his
bodily strength with the fatigue of travelling,
and the inclemency of the weather, left me under the care of Benjamin Birdsall,
until I should reach Pelham again.
The prospect of my kind companion, Samuel Wood,
having to travel so many hundred miles home alone, feeble in body,
and exposed to the extremity of the cold, as he must be, night and day,
was a fresh and continued trial to my mind,
until I heard of his safe arrival at his own home,
but in a yet more enfeebled state of body than when he left me.

First-day, 4th of second month, attended the usual meeting held at Ameliasburg.

Third-day, we attended the meeting of Coalcreek.
Friends meet in a private room, which was much crowded,
and for want of better management in making the fire,
the air of the room became so oppressive,
that some of our company were under the necessity to leave it,
which proved a great interruption to the quiet of the meeting.
After the meeting closed, we went home with John Valentine,
formerly of the city of Dublin, in Ireland, to their hospitable log-house,
which furnished every comfort for the weary traveller, and that sweet, outward quiet,
which in degree conduces to quietude of mind; and this, at times,
proves instrumental in replenishing the bodily powers.
Here tarrying for the night, I received a fresh lesson of instruction,
that man wants but little here below, to come at the real enjoyment of this life.

We rode to Pickering, and next day to Uxbridge, mostly through the woods;
and were favoured to reach our quarters early in the evening.

First-day, 11th of second month, 1827, the wind during the night blew a hurricane,
which awakened my fears, as our journey to Whitechurch lay through the woods,
that we should have difficulty to contend with, before we reached our quarters at night;
but as it rarely happens much advantage is gained by anticipating difficulties,
I endeavoured to cast all future care of this sort behind me,
and not to have my mind unfitted for what might be the duty of the coming day.
Attended the usual meeting here,
in which I was enabled to enter into near sympathy with the few members
who are mourning under a sense of that state of barrenness and poverty,
with which many of their brethren in religious profession are contenting themselves.
After meeting we proceeded to Whitechurch, a journey of twelve miles through the woods;
the snow was very deep, and we had at times drifts to pass over in the valleys;
they had the appearance of smothering us and our horses.
I felt truly thankful when we reached our destined abode for the night,
where we were kindly cared for.

Fifth-day, we attended the Monthly Meeting at Yonge-street;
the meeting for worship was large, and many of other societies gave us their company.
Early in the meeting I rose on my feet,
and delivered what I believed was the word of the Lord to the people.
After I sat down, an acknowledged minister, who stood high with a party in the meeting,
arose,
declaring that our supposing Adam`'s transgression
had in any way affected his posterity was absurd,
and to suppose the coming of Christ in the flesh was to redeem mankind from sin,
was equally absurd.
Never before having heard such a public avowal of these anti-christian principles,
which were so evidently making their way in the minds
of many of our Society in this Half-year`'s Meeting,
I was brought into a trying situation.
I felt that I must not suffer the meeting to close without endeavouring,
as help should be afforded me,
to maintain the ground I had taken in the opening of the meeting;
and yet the consequences were to be feared from the
strong party the individual had in the meeting.
I stood upon my feet, and informed the meeting,
notwithstanding what had been last communicated was in direct
contradiction to what I had offered in the meeting,
and altogether at variance with the well-known doctrines
of the Society of which I was a member,
yet I durst not recall a word I had offered.
In propagating these anti-christian principles,
a party-spirit had so spread in the minds of some of the members,
and such opposition to conducting the discipline in the true spirit of it was manifested,
that the meeting sat from eleven o`'clock in the
morning until near six in the evening before it closed.

Sixth-day, 23rd of second month, 1827, we proceeded towards York,
where I expected to find letters from home,
not having yet received any since I landed on the American shore.
But my patience was to be further tried in this respect,
as I heard that a letter from England had been in the post-office for me,
but was forwarded to the place we had left last.

Seventh-day, having a journey of fifty miles to accomplish,
to be at Pelhain meeting tomorrow, we made an early start,
but found the snow so deep and such drifts to encounter,
that we were in great danger of being overturned;
but before it was quite dark we reached in safety.

First-day morning, we rode about five miles to Pelham meeting, which was large;
and it appeared to separate under a solemn covering,
for which I humbly hope many of our minds were made truly glad.

On fourth-day we rode to Black-creek:--here we attended the usual week-day meeting;
it was to me a time of inward quiet,
for which I hope I felt truly thankful to that Almighty Power,
who only is able to still that roving of the mind,
by which the unwearied enemy seeks to defeat the end proposed by our assembling together.
On sixth-day we took to our wagon again, for the ferry at Black-rock,
in order to cross the Niagara river, which ferry is above the great Falls.
The scow, as it is called, which was to take us, our horses and wagon over,
appeared very small for the purpose;
and in consequence of the current running very strong,
we were obliged to pass a considerable way up the river,
which is considered about three-quarters of a mile wide at this crossing.
We were favoured to land safely on the Buffalo side of the river;
where I received good accounts from home of my dear wife and family.
We then rode to Hamburgh, and were kindly received.

First-day, attended the usual meeting held here,
which was greatly disturbed by the noise of the dogs brought by members of the meeting,
also by Friends moving to and from the stove to warm themselves.
Endeavouring to acquit myself faithfully on these
and other subjects which arose in my mind,
I left the meetinghouse peacefully.
In the afternoon I had a religious opportunity with a number of young Friends,
and the day closed with feelings of gratitude for the help that had been dispensed:
may the praise of all be given to Him who sits on the throne and to the Lamb,
is the prayer of my soul.
We attended the Monthly Meeting held at this place next day.

Fifth-day, we proceeded towards Collins: on our way we were informed,
that the bridge over a stream which crossed the main-road,
over which we were to have travelled, was broken down,
and we were advised to take a road through a swamp;
we proceeded agreeably to the instruction given us,
without much difficulty for a few miles; after which our difficulties began.
My companion, who had been a great traveller in this wilderness country,
acknowledged he never before had met with such a dangerous, bad piece of road,
as we had now come to;
in one place we were all obliged to get out of the wagon
and take to our feet to get it through the swamp;
in consequence of which, stepping as I supposed, on a parcel of leaves,
I sank down into a mud-hole half-way up my legs,
and had not my companion come to my assistance, finding myself sinking deeper and deeper,
it hardly seems likely I could have extricated myself from this perilous situation.
The road we were upon was so narrow,
we could not turn about our carriage to pursue our journey back again;
and to proceed forward,
appeared to be attended with great danger and difficulty to ourselves, our carriage,
and our poor horses,
which last were obliged to put forth their whole
strength to bring the wagon out of the mud-holes.
But we found again to our discouragement, that we had as great a difficulty to encounter,
by coming to the stump of a very large tree, which we could only pass on one side;
on the other side of our road there was a mud-hole,
which appeared deep enough to take in the whole of our carriage,
and the road was so narrow we doubted the possibility of our escaping an upset;
but as no other way appeared for us than to attempt to do our best,
my companion keeping the horses to their work with all his skill,
managed to get the carriage through,
but not without apprehension the harness and carriage had received damage.
This last effort was so great, that our poor horses for some time after,
when they came in sight of a hole, in which was mud or water,
appeared struck with so much terror, that they would make a halt,
and then plunge through with all their might:
at length we reached our friend Samuel Tucker`'s.

The next morning, we proceeded to Collins meetinghouse,
and attended their Monthly Meeting.
A difficult case came before it, which considerably agitated the minds of Friends,
and I could not but fear,
unless there was more of a disposition to labour after brotherly condescension,
it would have a tendency to break that bond of love and unity,
which only will preserve our religious Society as a city that is compact together.

Seventh-day morning, we rode to David Pound`'s,
intending to be at Clear-creek meeting tomorrow.
My mind having been drawn to make a visit to the Seneca tribe of Indians at Cattaraugus,
and being now in the neighbourhood of their settlement,
I opened my prospect to some Friends of Clear-creek,
who arranged matters for a meeting with them on second-day.

First-day morning, 4th of third month, attended Clear-creek meeting:
the house was much crowded by Friends and others; it proved to me an exercising,
trying meeting; and yet I thought I felt cause for thankfulness,
that my lot had been cast here.
The next morning, accompanied by several Friends,
we proceeded to the Cattaraugus settlement,
as emptied and stripped as I think I ever witnessed.
I was even tempted to call in question the propriety of the step which I had taken,
in requesting to have the tribe called together.
I wept and sighed in the inmost of my soul to the Lord for strength,
that I might be preserved faithful to his requirings;
and if silence was the word of command in the meeting,
it might be faithfully maintained by me.

On our arrival at the council-house, where the meeting was to be held,
I could scarcely suppress the feelings of anguish my soul was plunged into.
We found some chiefs and other Indians already assembled:
the building was constructed of wood, about one hundred feet by thirty feet;
the floor was boarded, except three spaces of bare earth left for kindling fires;
over each of which an opening was left in the roof for the smoke to escape;
these holes also were intended to admit light,
there not being windows in any part of the house.
On each side platforms were placed about four feet wide, to answer the purpose of seats,
and to sleep upon when their councils lasted longer than one day.
The head chief received us with marks of respect,
which has been the case wherever I have met with Indians of any tribe,
who have manifested great respect for members of our Society.

They were very slow in gathering: after we had waited an hour, the chief warrior,
Wiandegughta, a man of grave countenance, stepped forward,
and taking off his hat and placing his hands on the back of a chair, expressed himself,
through the interpreter, as follows;
which was afterwards confirmed to me by a Friend present well versed in the Indian language.

[.embedded-content-document.address]
--

Brother, we received a notice two days ago,
that you requested an opportunity with the Indians of Cattaraugus.
This is the day you wished to meet with us, we have now come together at your request.
We are pleased to see you, also the kind friends who are with you,
and are thankful we have all met in good health.
Brother, we understand you have come a long journey from a distant country,
and have crossed the great salt water; and, amongst others, to visit us red people,
living in this place.
Brother, the Good Spirit must have strengthened your mind in so great an undertaking,
and we hope he will still be with you, and protect you on your way.
We are now ready to hear what you may have on your mind to say to us;
we are always disposed to listen to the counsel of those who feel a desire for our welfare,
and we wish you to communicate freely the whole of your message to us.
You must not feel disappointed that we are not all got together;
many of our people are gone to the woods to make sugar;
we will at some convenient time explain to those
that are not present what we shall hear from you.
A Friend, well acquainted with their manners,
assured me this would be faithfully performed.) Brother,
it is our custom in this way to introduce strangers, you are now at liberty to proceed.

--

After the chief warrior, Wiandegughta, had closed his remarks, which he made in a solid,
feeling manner, he retired to his seat again a pause then took place,
and believing I had something given me in commission for them, I stood up on my feet.
The Indian who had been engaged as my interpreter arose,
and great quietness was observed during the time I was in testimony amongst them,
and when I had closed, after a pause, the chief warrior again stepped forward,
and expressed himself in a very broken, feeling manner, as follows:

[.embedded-content-document.address]
--

Brother,
we have listened with attention to what you have said,--your words have
sunk deep in our minds;--we hope we shall remember your good advice:--we
are not in the practice of making long speeches after such opportunities,
but we wish you to know that we thank you for the
concern you have manifested for our welfare.
We feel sensible of the truths you have told us,
and we will try to treasure them up in our minds;--we feel thankful
to the Good Spirit for his continued care over you,
and for the present opportunity afforded us.

--

After giving our hands, both to the Indian men and women, we parted;
and I returned to our friend David Pound`'s for the night.
The Seneca tribe of Indians at Cattaraugus having divided,
one part of the tribe was distinguished by the title of the Missionary party,
the other the Pagan party;
this was occasioned by a missionary coming into the
settlement against the minds of many of the tribe,
and endeavouring to impose religious sentiments upon them, which some could not receive.
At the close of what I communicated,
I recommended to them that collected in each other`'s houses in the evenings,
that such as were able should read the Scriptures
to those who were not able to read them,
in preference to spending their time in such reading, conversation,
and practices as were unprofitable.
