== Chapter XL.

Fourth-day morning, 14th of third month, 1829, we rode to Genito,
and were kindly received by a Friend of that place;
and on fifth-day attended meeting there, consisting of three families;
many not in profession with Friends gave us their company,
and we were favoured with a quiet solid sitting together.

Seventh-day, attended Cedar-creek Monthly Meeting.

First-day, attended Caroline meeting, consisting of two whole families,
and part of two other families;
the house was nearly filled by the coming in of the neighbours.
I believe there was ground to hope that what was offered was received gladly by some.
Had a quiet sitting in the family before I retired to rest,
and in the retrospect of having endeavoured to do my best
towards a faithful discharge of this day`'s work,
fresh cause was felt for singing the Lord`'s praise,
who had in mercy been my stay and my staff through
this day`'s exercise of faith and patience.

Third-day, we proceeded towards Alexandria, and reached Fredericksburgh that night;
the next night we reached Ward`'s tavern with great difficulty,
from the danger we were frequently in of being set fast in mud-holes or turned over,--the
heavy falls of rain having washed the road and made such gulleys in some places,
as barely to leave room for our carriage to pass
between them and the bank on the opposite side:
on conversing with our tavern-keeper on the state of the road we had travelled,
and inquiring into the cause why we had not met one carriage since we left Fredericksburgh,
we were informed, travellers had found it so dangerous,
that the steam-boat conveyance had been considered preferable.

Fifth-day morning, after we had comfortably refreshed ourselves, we pursued our journey,
but soon found we should not have to say that the last part of our journey was the best;
my companion appeared at times apprehensive of not being able to
get to our journey`'s end without some injury to our horses,
carriage, or ourselves; but through the watchful care of that Almighty Power,
without whose notice a sparrow falls not to the ground,
we were favoured to accomplish this journey of eighty miles in three days,
and reached Alexandria in safety this evening,
not having seen a carriage of any kind on the road since we left Fredericksburgh.

As I advanced towards Alexandria the watchword was
in mercy powerfully proclaimed in the ear of my soul,
"`Into whatever city or town ye enter, inquire who is worthy, and there abide;
go not from house to house;`" although I was well aware,
that a steady attention on my part to this Divine injunction,
would expose me to much suffering of mind.
The family in which I was most kindly cared for when here before,
as well as some other families who had been unremitting in their attention to me,
had united themselves to the separatists`' party in this Yearly Meeting.
I thought I never felt greater need of attending to the injunction of, "`Pray always;
pray without ceasing,`"--lest the affectionate part should be so wrought upon,
as that my mind should be turned from the sure foundation.
Aware how generally the members of the Society at Alexandria had gone off with the Hicksites,
I had, before I left Virginia, written to a Friend of Baltimore,
requesting him to inform me where I could be safely housed;
and having received the necessary instructions on this head,
I endeavoured after holy help to be preserved firm in keeping to my quarters,
notwithstanding all the importunities I had,
to visit here and there amongst those who had denied the faith: however,
accompanied by my companion and landlord,
I called upon the amiable family with whom I had taken up my abode when here before.
Our meeting appeared to be mutually trying--trying to them, as they expressed themselves,
that I had changed my quarters,--and as trying to me, if not more so,
on account of the cause of my being obliged so to do.

I felt my mind drawn to make a visit to those individuals,
who were esteemed the most pious amongst the Episcopalians, Presbyterians,
Baptists and Methodists,
for the purpose of leaving with them what I could
spare of the printed sheet on theatrical performances;
they appeared to receive them with feelings of gratitude,
and to view them as help sent in the time of need.
The theatre in this place had been long shut up on account of repairs,
and was to be opened again in a few days; much pains, I was informed, had been taken,
through the public papers, to obtain a full attendance when it should be opened,
by endeavouring to set forth the benefit and advantage of theatrical amusements.

Something to counteract these attempts, I understood,
had been in contemplation by some of the more serious part of the city,
but it was not yet effected;
I was led to rejoice that I had yielded to these simple pointings of duty,
not being aware at the time of the state of things here relative to the theatre.

First-day morning, I rejoiced that the time was come for me to leave Alexandria;
and also that strength had been afforded by my heavenly Father,
to rise above the affectionate part,
and withstand the importunities of those whose spirits I could
not now associate with as it respected religious opinions,--the
command having been renewedly ushered into my mind,
of "`Touch not, taste not, handle not, the leaven of their spirits.`"
Accompanied by a kind friend and his wife, we rode to the city of Washington,
to sit with the four individuals in that city now with Friends;
the few left at Alexandria and Washington, now make one meeting,
which at present is held in a room belonging to one of this little company;
two young women, not in membership with Friends sat with us: the Divine Master,
who told his followers, "`Lo, I am with you always,`" condescended, in his mercy,
to own us, causing feelings of gratitude, I believe, to flow in our hearts.

Second-day morning,
part of a committee appointed by the last Yearly Meeting to visit the Quarterly, Monthly,
and other meetings within the compass of this Yearly Meeting,
having notified Friends of their intention to sit with such of this meeting,
as had not united themselves to those who had seceded from the Society,
application was made for the use of their own meeting-house,
it being in the possession of the Hicksites, but it was refused; on which,
application being made to the Baptists for the use of their house for the purpose,
we understood it was cheerfully granted.
Having yet a few sheets left of the printed paper on theatrical performances,
and apprehending it would be right for me to put them in a channel to be made public,
I waited on the preachers of the different religious denominations in the city,
and found it was gladly received,
with an assurance from them of making it public through the newspapers and other channels.

Fifth-day, part of the Yearly Meeting`'s committee, with the Friends of this place,
also such as had been disowned and others who had
been in the practice of attending Friends`' meeting,
but had not united themselves to the Hicksites, met at the Baptist meeting-house;
several also who had joined the separatists and other
religious persuasions gave their company,
the doors not being shut against any during the meeting for Divine worship:
the people generally appeared solid,
and I doubt not but that it was a season of profit to not a few.
When the meeting for worship closed,
such as had been disowned and others who were in
the practice of attending Friends`' meetings,
but had not united themselves with the separatists,
were encouraged to remain in the house and keep their seats;
a Friend on behalf of the committee informed those who remained
with Friends the cause of their being thus convened,
and such means were proposed for the help of those
yet left with Friends as Truth appeared to dictate;
the meeting separated under a humbling and thankful sense that best help had been mercifully
vouchsafed in conducting the several matters that were brought forward.

First-day; a separation having taken place here,
the meeting was held in a large room offered for the use of Friends;
it was supposed that more than one hundred Friends and others were present.
Second-day morning I proceeded to Baltimore.

Fourth-day, 1st of fourth month, I proceeded to Deer-creek; and on fifth-day,
attended Friends`' meeting there; the Hicksites keeping possession of the meeting-house,
the meeting is now held in a private house;
here are yet left a few solid Friends to keep up this meeting.

Sixth-day, attended meeting at Eastland;
the meeting-house being in possession of the Hicksites,
the few Friends of Little Britain and Eastland are united in one meeting.
Several not in profession with us gave their attendance;
I believe Friends were comforted in sitting together.

Seventh-day, we returned to Baltimore.
First-day; both the meeting-houses in this city being in the possession of the Hicksites,
Friends hold their meeting in a chapel built by a private individual,
of whom it is rented, until they can build for their own accommodation:
here I found a very respectable body of Friends left;
the morning and afternoon meetings were well attended by Friends and others,
and proved solid and satisfactory.

Second-day, I rode to Gunpowder,
accompanying a part of the Yearly Meeting`'s committee of men and women Friends.
The Hicksites having possession of the meetinghouse belonging to Friends,
they had the use of the meeting-house of the Methodists`' Society.

Third-day, the committee and Friends of this meeting met,
and were encouraged to seek a place to meet in for the purpose of religious worship,
which, as yet, it did not appear they had strength to do,
as they sometimes met with the Hicksites, at other times stayed at home,
and some of the young people went to the Methodist meeting;
these are some of the sorrowful effects which this dividing spirit has produced.
Friends of Gunpowder manifesting a desire to embrace the
present opportunity to put in practice what had been proposed,
a time was concluded upon for them to meet and consult together,
as to the most suitable place for them to hold their meetings for worship in,
until some more permanent situation could be provided.
After meeting we rode to Baltimore.

Fifth-day, attended the week-day meeting there;
at the close of which was held the Monthly Meeting.
Friends not having yet taken up the cases of those who are gone off with the separatists,
there was but little business; the meeting closed under a thankful sense,
that Divine support was near, to help this deeply tried company,
during the difficulties that await them.
The separatists in this city, it appeared,
were active in issuing their testimonies of denial against Friends,
without attempting to visit those they testified against,
sending them by lads and coloured people,
and at times throwing them into the houses of Friends.
On sixth-day, I left Baltimore.

First-day, attended meeting at Wilmington, in their new meeting-house,
the Hicksites having possession of that which belongs to Friends;
the morning meeting was well attended.
I rejoiced in sitting down with Friends of this meeting select.
The afternoon meeting was larger; several of the separatists gave their attendance,
and the meeting closed under a grateful sense, that in this collective capacity,
we had not been forgotten by the Great Head of the militant church.
I spent the evening with my kind friend Samuel Hilles, his family and scholars;
the children being collected before retiring to rest,
reading out of the sacred pages commenced, closing with a time of sweet, solemn silence.

Third-day, we rode to Philadelphia, where I was again kindly received.
Fourth-day, attended Twelfth street meeting,
the solemnity of which was much broken in upon, through late comers-in;
before the meeting for worship separated, I found, if I did right,
I must notice this disorderly proceeding.
At the close of the meeting for worship the Monthly Meeting commenced,
the business of which appeared to be conducted with much deliberation and weight.

Fifth-day, I was at Arch street meeting, which, for a mid-week meeting,
appeared well attended, and I trust it proved a season of profit to some.
At the close of the meeting for worship, the Preparative Meeting was held;
Friends appeared to dwell under the weight of the
cases of delinquency brought forward by the overseers,
previous to their being reported to the Monthly Meeting.

Sixth-day, sat with Friends in the Meeting for Sufferings,
which was attended by its members pretty generally,
as appeared when the names were called over; divers remarks were made,
which were applicable to the present tried state of the Society and the trials
that are yet expected to grow out of the schism which has taken place.
I believe it may be said with reverent gratitude to the Author of all our blessings,
that it was a good beginning of the Yearly Meeting,
and an earnest of the Divine help mercifully dispensed to us at that season.

Seventh-day morning, attended the Select Yearly Meeting, at which a large body of,
may I not say in truth, solid, weighty Friends assembled.
Before the meeting separated,
I informed Friends my services in this land appeared to me near coming to a close,
there being no prospect of my sitting with Friends
in another Yearly Meeting in this city.
The meeting adjourned to the afternoon:
these sittings were worthy to be had in remembrance,
to the praise and glory of Israel`'s Shepherd,
who is still in mercy condescending to evince to those who sincerely depend upon him,
that he is ever watching over such for good.

First-day morning, attended Pine street meeting and the North meeting in the afternoon,
whereby I escaped the crowd there was at some of the other meetings,
such is the prevalency of desire to hear what the servants have to say;
but how little fruit do we see in a willingness to obey
the counsel of the Great Master through his servants.

Second-day, 20th of fourth month,
the Yearly Meeting for transacting the general concerns of Society commenced:
this meeting was considered large, and continued its sittings until seventh-day,
in much quiet;
the several matters that came before it being conducted in much harmony and solid deliberation;
the young men manifested an attention to the business,
which revived a hope in the minds of their elder brethren,
that they really felt an interest in what was going forward.

First-day, was at Arch street meeting in the morning, and Pine street in the afternoon,
which was well attended by Friends and others: it proved, I have no doubt,
a comfortable meeting to many, and closed under a precious solemnity.

Third-day morning, we went on board the steam-boat for New York,
where we were favoured to arrive that evening,
and I was again kindly received by my friend Elizabeth Bowne.

Fourth-day morning, proceeded to Long Island,
and attended the adjournment of the Monthly Meeting of Westbury and Jericho,
held at the house of John Titus.
At this adjournment a testimony of denial against Elias Hicks was produced,
and twice read over with great deliberation, accompanied, I believe,
with feelings of regret on the part of most present,
at the necessity of the course the meeting was then about to take:
after much time had been spent,
the meeting generally uniting in the propriety of what had been prepared by the committee,
the clerk was ordered to sign it on behalf of the meeting,
and two Friends appointed to offer Elias Hicks a copy.
I think I may say I never was before at a meeting,
where the issuing of a testimony of denial appeared to excite so much painful sensation,
or when I have witnessed more solemnity accompanying the pause which took place,
after this painful task was thus far closed.

Fifth-day morning, we returned to New York.

First-day, sat with Friends in their newly erected meeting-house,
the day being rainy the meeting was smaller than usual;
we were favoured with a quiet sitting together:
the afternoon meeting was pretty well attended, and I believe to many, or most,
it was a time of divine favour.

Second-day morning, attended an adjournment of the Meeting for Sufferings;
from the minutes of which, it appears the troubles of Friends,
through the medium of the Hicksite party, are increasing in this Yearly Meeting;
but yet it was very consoling to observe Friends so preserved in
meekness and resignation to their allotted portion of suffering.

Fourth-day, 6th of fifth month, 1829, attended the Monthly Meeting of New York;
the meeting for worship was well attended for a week-day meeting,
and it was a time in which I doubt not the minds of many were favoured
to know something of the Lord`'s preparing hand,
qualifying them to enter upon the weighty concerns
of the Society committed to their charge;
the great load of business in consequence of the separation,
and the feelings of sorrow evidenced in the minds of many,
at the necessity there was for the meeting to draw the line
of the discipline over such as were their relatives,
and at one time their bosom friends, called for much sympathy.

Fifth-day, attended the Monthly Meeting at Flushing on Long Island,
which is held in a private-house,
the Hicksites keeping possession of the meeting-house of Friends;
strength was mercifully vouchsafed to this little company,
to give timely attention to the cases of those who had seceded;
no disposition that I could observe was manifested to shrink
from the painful task allotted them by the meeting.

Seventh-day, accompanied by my late kind companion Samuel Wood, we rode to Mamaroneck,
where we were kindly received by our friend Richard Mott and his wife.

First-day, attended meeting in their new meeting-house,
the Hicksites keeping possession of that of Friends:
about one half of the former meeting, I was informed, remain with Friends.

Fourth-day, attended Purchase meeting, held in a new meeting-house;
when the meeting for worship closed, much business came before the Monthly Meeting,
which appeared to be conducted with weight, and in the unity of the Spirit;
although it was painful to observe the task many had to
perform in treating with the delinquent members,
yet the care manifested to deal tenderly by all, was very commendable.

Fifth-day morning, attended Shappaqua Monthly Meeting; which still continues large,
and many solid, weighty Friends belong to it;
the meeting for worship was held in a store; there was a great deal of business; but,
as many hands make light work,
Friends were spared that weight of suffering which
falls to the lot of some of their brethren.

Sixth-day, attended Amawalk Monthly Meeting, held at Croton;
where there is yet left a considerable number of Friends,
and amongst these not a few hopeful young people: the meeting held nearly five hours.
In going through the Monthly Meetings of this Quarterly Meeting since the separation,
I was much comforted in observing the agreeable change that had taken place,
both in meetings for worship and discipline; there was none of that restless,
disorderly conduct,
which is the fruit of the spirit of insubordination which
prevailed in the minds of those who have taken their flight:
the quietness restored to these meetings is not easily to be described.
The meeting for worship and that for discipline were seasons,
in which Divine goodness in mercy condescended to extend his arm of all-sufficient help,
whereby Friends were comforted together, and afresh encouraged to renew their covenants.
Before the closing minute was read,
desires were feelingly expressed by different Friends,
that it might be a day long remembered by them.

First-day, attended the meeting at Peekskill, which was held in a Friend`'s house.
Many of the serious, respectable inhabitants gave us their company;
the meeting was conducted in much quiet, and, I believe,
it proved a time of comfort and encouragement to seeking minds.

Second-day morning, we rode to Poughkeepsie,
and had a meeting with the few Friends left there;
many not in profession with our religious Society attended:
my mind being relieved from the exercise I was under when entering the house, I said,
it is enough, and as much as the poor, unworthy instrument is to look for.

Third-day, we rode to Pleasant-valley,
where there still remain one family and a few individuals with Friends;
those remaining at Poughkeepsie and this place, now unite in making up one meeting.
Having felt drawings in my mind to sit with Friends here;
on our arrival I was informed the Hicksites, hearing of my intentions, came forward,
and informed Friends, the doors of the meetinghouse would be open;
as no other place could be found so suitable,
Friends gave notice of the meeting to be held there this evening.
At first hearing of this circumstance, I felt placed in a trying situation;
but notice having been given, and it being late in the day,
and considering that the house was the property of Friends and not of the Hicksites,
my mind settled down quietly under this unexpected circumstance.
The meeting was largely attended by those of other societies,
also by many of the Hicksites: it was conducted with much quiet, and was, I hope,
profitable to some present.

Fifth-day, attended Monthly Meeting at Creek,
which was held in their commodious new meeting-house.
Although this meeting has experienced a great stripping,
yet it was an encouraging prospect to behold,
how the hands of the few left were strengthened for the labour which falls to their lot.

Sixth-day, attended the Monthly Meeting for Nine Partners, held in one of the schoolrooms.

Friends here are greatly reduced, and, it would seem,
almost ready to cast away the shield of faith, as if it had never been anointed,
and to sink under their discouragements,
and the perplexing and trying circumstances in which
they are involved through the Hicksite party;
who are annoying, in every way they possibly can, the Yearly Meeting`'s institution here,
for the education of the youth.
I have not attended a Monthly Meeting of this Yearly Meeting,
which has a greater claim on the sympathy, and needed more the help of Friends:
encouragement was held out to the few faithful members left,
that they might be willing to make use of the little strength they had,
as the only way to know an increase.

Seventh-day, 23rd of fifth month, 1829,
attended the first sitting of the Select Yearly Meeting of New York, which was large,
considering the mournful schism which had taken place within its borders.
Apprehending my services amongst Friends on this
continent were nearly brought to a close,
I felt it right for me to inform the meeting to this effect.

First-day, Friends occupied the usual meeting-room and basement story;
both of which meetings were well attended and quietly conducted.

Second-day,
the Yearly Meeting for transacting the general concerns of the Society commenced,
which was held in the basement story, the women occupying the meeting-room.
The men`'s meeting was large: divers testimonies were borne to the goodness of the Lord,
in again permitting us to sit down together,
free from that spirit of contention and tumult with
which aforetime these meetings had been tried.
The Yearly Meeting continued by adjournments from day to day until seventh-day,
when it closed under a very precious solemnity, which favour not being at our command,
feelings of gratitude were the clothing of our minds.

First-day,
our morning and afternoon meetings were attended
by many serious persons not in profession with Friends,
and they were owned by the good presence of the Great Head of the church, Christ Jesus.

Second-day, the 1st of sixth month, I left New York,
and went on board the steam-boat for Newport on Rhode Island, in New England.

Fifth-day, attended meeting; the morning being wet, the meeting was small.
First-day, attended the meeting of Friends held on this island; it was large,
and was attended by persons not in profession with our religious Society:
it proved a quiet, solemn meeting.

Second-day morning, we crossed another ferry, about two miles over;
the weather being very foggy, crossing these ferries appeared formidable.

Fourth-day, attended the week-day meeting, held at Western;
a considerable number not in profession with Friends, gave us their company.

First-day, this meeting was attended by many not in profession with our Society,
whose solid and weighty deportment,
manifested a sense of the importance of the great duty of thus coming together;
I felt well satisfied that my lot had been cast amongst Friends of this meeting.

Fifth-day, walked to South Kingston, and attended the mid-week meeting there;
this is a small meeting of Friends, but being attended by many not in membership,
we had a considerable gathering; my faith being at a very low ebb,
I found it hard work to rise upon my feet,
and attempt to obtain relief for my exercised mind; the meeting settled down in quiet,
under which we were favoured to separate.
Sixth-day morning, I returned to Newport, and the next day rode to Portsmouth,
to attend the Select Yearly Meeting held there: here I met with my country folks,
George and Ann Jones.
In the afternoon I attended the Meeting for Sufferings;
divers subjects of importance were weightily considered.

First-day attended meeting at Portsmouth;
the number of carriages and horses at the meeting-house at an early hour was great;
the house soon became crowded with Friends and others,
and very many were obliged to remain out of doors for want of room in the house.
Through the prudent care of the door-keepers, the meeting was held in much quiet,
compared with what was the case the preceding year; and although it lasted long,
yet the people quietly kept their seats until the close.
The afternoon meeting was also very large, and was preserved in quiet;
testimonies were borne by divers Friends,
and the language of supplication and thanksgiving uttered,
and there was good cause for the encouraging hope,
that it was a day of renewed visitation to some of our numerous company.

Second-day, 15th of sixth month, Friends met at Newport,
when the Yearly Meeting for the general concerns of the Society in New England commenced;
and after adjourning from day to day, closed its sittings on fifth-day evening.

Seventh-day, attended Monthly Meeting at Westport, which was large,
a number of hopeful young people making a part of it.
In the afternoon I visited a Friend, a minister,
who had long remained at home under great depression of mind.
I endeavoured, in as tender a way as possible, to arouse him,
believing discouragement was the chief cause which
deprived his friends of his company at their meeting:
viewing the sorrowful situation this dear Friend had slidden into,
strong cries were raised in my heart to the Lord to be preserved from thus giving way,
to whatever sufferings of body my getting out to meetings might expose me.

First-day morning, attended meeting at New Bedford: the afternoon meeting was large;
the calming influence of Divine love was mercifully extended towards us;
I hope it proved a profitable meeting to some.
Third-day, attended the Select Preparative Meeting, which was small;
a good degree of concern was manifested for the welfare of this part of the body,
and the meeting closed under a feeling of thankfulness for
the comfortable quiet which had been spread over us.
Fourth-day, having a prospect of attending the Monthly Meeting of Nantucket,
and the wind continuing contrary for the packets to return,
both of which were on the Nantucket side,
I felt tried lest I should not be able to reach the island in time;
yet under these discouraging prospects, a hope at times would cross my mind,
that the way would yet open for me.
I set out to make a few morning calls, but had not proceeded far from my quarters,
before a Friend came in search of me, with the unexpected information,
that a small sloop would sail for Nantucket in about half an hour:
although I would have chosen a larger vessel,
I feared the consequences of refusing this opportunity.

The wind had been very tempestuous,
in consequence of which the ocean was greatly agitated, and our vessel being small,
her bow frequently pitched deep into the water, whereby we were much tossed to and fro,
but were favoured to land safely in the evening.

Fifth-day, attended the Monthly Meeting, held in the South meeting-house;
there now being only one Monthly Meeting on this island.
It being known to some Friends that there was an aged man present,
formerly a resident on the island, who had joined the Hicksites in the state of New York,
request was made that the meeting should be select;
this request was again and again repeated without effect.
At last he stood up, saying, he supposed he was the person alluded to,
pleading his right to sit;
yet informed Friends if it was the mind of the majority of the meeting he would quit.
Many Friends stood up and requested him so to do,
but it soon became manifest that he had already made a party on the island,
who favoured his principles, these pleaded for his remaining.
Friends continued to urge his leaving, which he now refused to do,
finding he had a party in the meeting to support him in staying.
Friends, not being willing to resort to force, adjourned until the afternoon,
requesting the door-keepers to keep the meeting select.
They were fearful he would give them trouble at the ensuing Quarterly Meeting;
but finding he could make so little way here, he left the island.

First-day morning, attended the South, and in the afternoon the North meeting,
which last was large for an afternoon meeting; both, I hope it may be acknowledged,
were profitable seasons to some of us.

Fourth-day, attended the Quarterly Select Meeting; it was to me a low, trying time,
the harp continuing, through the whole of the meeting, as on the willows.
Fifth-day, the Quarterly Meeting for the general concerns of the Society commenced;
the meeting for worship was attended by a considerable
number of those not in profession with Friends;
the meeting for discipline was quietly conducted.
Friends appearing to move along harmoniously in the business.

Sixth-day morning, 4th of seventh month, went on board one of the packets,
in company with divers other Friends, and after a passage of ten hours,
we landed at New Bedford.

First-day, attended meeting at Allen`'s-neck.
I would gladly have proceeded for New York, but I feared omitting this meeting;
the day being wet, the meeting was smaller than usual.
My service this day was to labour with an individual present,
who had been favoured with a precious Divine visitation,
and had given proof to his Friends of having joined in with it,
by running well for a time,
manifesting by his conduct that there had been a giving in his name to follow Christ;
but he had broken his goodly resolutions, and his conduct bespoke a language,
as if he repented of what had been done.
I endeavoured to lay before him the sorrowful state into which he had fallen,
both as it respected his own soul`'s salvation,
and the influence which his example might have over others,
and earnestly besought him to be willing to renew his covenant with the Lord his God,
if so be his lengthened mercy still awaited his acceptance.
I found it very hard work to obtain full relief to my own mind on this very gloomy subject.
After the meeting closed, a Friend informed me, that an individual,
who sat in the gallery near me, who was once an approved minister, had lost his standing,
swerved into a contentious spirit, and become tinctured with the Hicksite principles.

Third-day, I proceeded to Providence,
where I was kindly received again by my hospitable friend Moses Brown.
Fourth-day, attended meeting at the school,
and the day following the usual meeting held there, which was small;
the meeting separated under a covering of solemnity, which is very precious.
Seventh-day, I went on board the steam-boat for New York,
which place we reached early on first-day morning.
I sat with Friends in this city this morning; the meeting was very large,
as was the case also in the afternoon;
the quietness restored to Friends in these meetings is, I believe,
felt as a fresh cause for gratitude.

Second-day afternoon, attended a burial:
the Hicksites having taken possession of the burial-ground,
Friends were obliged to apply to them for leave to inter the body;
several of them attended at the house and grave-side,
but no interruption took place from their preachers,
although there were one or more present.

Fourth-day, attended the Monthly Meeting of Westbury and Jericho, held at John Titus`'s;
although these two meetings have been so stripped as to
make it necessary to unite them into one Monthly Meeting,
yet there still appears to be a respectable number
of well-concerned Friends to support the meeting:
in the evening we returned to New York.

Sixth-day morning, I left New York, by steam-boat, for Burlington, in New Jersey.

First-day morning;
I had often been led to sympathize with the few Friends left at Bristol,
deprived as they have been by the followers of Elias Hicks, of their meeting-house;
but the way never clearly opened in my mind before this morning to sit with them.
Accompanied by my kind friend Samuel Emlen, we crossed the river Delaware,
and proceeded to a farm-house on the banks of another river,
where the meeting of Friends of Bristol is now held:
the number in attendance at the meeting was considerable,
many not professing with Friends making a part of our company.
I hope I was not out of my place in yielding to this apprehended duty.
We had intended being at the afternoon meeting at Burlington in due time;
but when we reached the ferry, the boat was on the other side of the river,
and having to wait its return,
we were not able to accomplish our object until half an hour after the time of meeting;
but being conscious we had done our best for a timely attendance, we went into meeting.

Second-day, in company with several Friends,
I went on board the steam-boat for Philadelphia.
Third-day, attended the Northern District Preparative Meeting, which,
after a time of close exercise, I was favoured to leave with a peaceful mind.

Fourth-day, attended Twelfth street Monthly Meeting,
and the next day Arch street Preparative Meeting.
My mind had for some time past been exercised with
apprehensions that it would be required of me,
before I left this continent, to attempt a visit to the state prison in the city,
and also the House of Refuge; but the way not clearly opening for it until now,
I consulted a few Friends on the subject,
and they undertook to make arrangements for the visits to take place on the morrow.

First-day morning, accompanied by my kind friends, Thomas Stewardson and Philip Garrett,
we proceeded to the state-prison.
We were shown to the place set apart for religious worship; the prisoners,
about three hundred, were then assembled: the meeting was orderly conducted,
and when it closed the prisoners quietly departed, and placed themselves about the yard.
I gave them each my hand, most of whom appeared to receive it affectionately.
In the afternoon we attended the House of Refuge,
where we met with about eighty-four males and twenty-five females;
the managers appeared to manifest a lively interest in the welfare of the institution:
earnest were my desires that they might not grow
weary in a steady attention to this good work.
The children were assembled in a room set apart as a place of worship: the quiet,
orderly sitting of both sexes did them great credit.
This, I understood, was the first meeting Friends had had in this institution.

Second-day morning, 26th of seventh month, 1829,
representatives from all the Yearly Meetings on this continent,
assembled at Arch street meeting-house,
as a committee to take into consideration the general state of the Society;
from the weighty deliberation with which the subjects were entered upon,
and the harmony which prevailed,
I considered it a favour to have the privilege of being present.

Third-day, attended North meeting, which was large.
Fourth-day morning, attended Pine street meeting; after the meeting for worship,
the Monthly Meeting was held: these meetings were owned by the Great Master, and proved,
I doubt not, times of comfort and consolation to drooping minds.

Fifth-day, sat with the meeting of conference,
in which I was comforted under a sense that we were yet favoured, as a Society,
with an evidence, that the Lord our God has not forgotten to be gracious to us,
but is still offering his aid in rebuilding the waste places,
and repairing the breaches which sin has made in our walls.

Seventh-day morning, 1st of eighth month,
after taking an affectionate leave of my kind friend Thomas Stewardson and family,
with many other Friends who felt very near to me,
I went on board the steam-boat for New York;
where we were favoured to arrive safely that evening.
The new penitentiary of Sing Sing had for a long time so fastened on my mind,
that I found I must now do my part toward making a visit to the prisoners there,
otherwise I believe the way will not clearly open
for my departure from this land on seventh-day next,
as I have been in hopes of doing.
To effect this, I found it was necessary for me to exert myself.
My kind friends Samuel Wood and William Waring did
what they could in the city for that purpose;
but it appeared, if liberty to make the visit was obtained,
it rested very much with the governor of Sing Sing, which was thirty miles from New York:
there was the uncertainty, when we reached there,
of being allowed the privilege of seeing the prisoners; but as I could see no way for me,
but to make every effort for its accomplishment,
and my said friends kindly offering to accompany me, we proceeded, on first-day morning,
for Sing Sing;--this day appearing to me the most suitable time to see the prisoners,
who on other days are occupied in labour.

We had procured a letter of introduction from a person
of some account in the city of New York,
and when the governor had read it, and heard from me my errand,
he told us the time of their worship had been over an hour and a half;
and according to their usual practice,
it being the only day the officers and keepers of the prison could
be at home with their families and attend their own meetings,
they were discharged from their duty, and the prisoners locked up in their cells,
until the return of the keepers in the evening.
This seemed to foreclose all expectation of seeing them,
yet I thought I felt as if the governor expressed himself with feelings of regret.
I was not a little tried, but endeavouring to keep in the quiet,
a ray of hope sprang up in my mind, with a caution, not easily to abandon my prospect.
It appeared to me the next expedient I must try was,
to inquire of the governor if any time next day could
be allowed me to have a meeting with the prisoners,
adding, we should be willing to wait such time as might be thought the most suitable.
On my putting this question to him, he made a pause, and then replied,
it was a serious thing to stop five hundred men from their labour for an hour;
but it may not be time lost: adding, they shall not, therefore,
return to their work after breakfast,
and if you will come to the prison about eight o`'clock in the morning,
I will have the prisoners assembled in the galleries,--a chapel
not yet having been erected for the purpose of Divine worship.
Matters being thus arranged, we hired a small vessel to take us across the Croton bay,
to the house of the widow of Robert Underbill, where we took up our abode for the night.

Second-day morning, the sons of our kind landlady took us over Croton bay,
accompanying us to the prison; a short time after our arrival there,
we were informed the prisoners were ready to receive us:
upwards of five hundred were collected in four galleries,
two on our right hand and two on our left; a large platform stood in the centre,
on which seats were placed for us; these galleries, we understood,
were well constructed for hearing.
The prisoners stood in great order, and after a suitable pause,
in fear and trembling I rose on my feet,
beseeching my Divine Master to preserve me from uttering a word, unless given me by him,
that might have a tendency in the least degree to wound any mind,
which was in the way to be healed soundly without instrumental interference.
I anticipated opposition in the minds of some of the prisoners,
but such feelings were not manifested;
and I felt nothing but openness to receive what I had to communicate;
quietness prevailed until notice was given for the prisoners to retire,
and I felt truly thankful this engagement was, I hope, well got through.
I would gladly have given the prisoners my hand,
but fearing lest I should exceed the bounds of the liberty which had been granted me,
I reluctantly restrained my inclination,
as it would have been attended with considerable difficulty,
from the manner of their retiring.

Third-day, I went on board the Silas Richards, Captain Holdrege, master,
bound for Liverpool, believing I might now with safety secure a passage in her:
I made an agreement with the owners not to be a contributor
towards the spirits and wine drank on board,
which I found, if I acted agreeably to the convictions of my own mind, I must do,
or take my passage in the steerage;
for I had been a painful witness of the unbounded liberty given
to passengers on board these packets of drinking to great excess,
in consequence of a certain sum being charged for the passage, wine and spirits included,
with liberty to call for what they like, and when they like.

Fourth-day, sat with Friends in their Monthly Meeting.

Fifth and sixth days were occupied in taking leave of Friends in this city,
and preparing for my departure.

Seventh-day morning, 8th of eighth month, 1829,
accompanied by my kind and attentive landlady, Elizabeth Bowne,
her daughter Sarah Minturn, and divers other Friends,
after an affectionate and long farewell of each other, I went on board the steam-boat,
which was to take us down to the packet.
There were only five cabin-passengers besides myself,
but a great number of steerage-passengers;
the captain kindly accommodated me with a large state-room.

Before we had made much way, a severe storm of thunder, lightning, and rain arose,
after which the air was more cool and temperate; we sailed with a wind, which,
had it continued, would probably have taken us to Liverpool in about twenty days;
but we were so frequently becalmed, and had head winds to contend with,
that our expectations in this respect were frustrated.
On taking a pilot,
he informed us there had been the most severe storm on the
Irish coast that had been known for several years;
many vessels had been wrecked and lost:
this information afresh excited thankfulness in my mind
that our prospect of a quick passage had been frustrated;
for had we made it agreeably to our first calculation, the probability is,
we should have been in the very mouth of the storm.

Seventh-day afternoon, after a passage of twenty-eight days,
I was released from the society of two as wicked men, cabin-passengers,
as I ever had been in company with, and set my feet on one of the docks in Liverpool,
where I was kindly received by Thomas and Frances Thompson and other Friends.

Fourth-day, I went by coach to Sheffield; and on seventh-day,
proceeded by coach to London.

First-day, attended Gracechurch street meeting, and a burial at Bunhill-fields,
where I met a mournful company round the grave-side of a young woman,
whose removal had been sudden and unexpected to her parents.
After which a kind young Friend drove me down to Tottenham,
where I found my dear wife and children, favoured with health.
We mutually enjoyed each other`'s society again,
after my absence from home of three years and one month.
May I never forget the multiplied mercies of my Divine Care-taker,
amidst the many perils and dangers, to which I have been exposed; but above all,
that he was pleased to hear and answer my daily petitions to him
to preserve me out of the hands of men of unsound principles,
who, I had good ground for believing, were watching for opportunities to ensnare me;
the retrospect affords a consoling evidence, through adorable mercy and preservation,
that they have nothing of an offensive nature justly to lay to my charge.
Oh! may I in future be found walking worthy of these unmerited favours, saith my soul.
